In [22]:
%load_ext autoreload
%autoreload 2

import sklearn
import scipy 
import numpy as np
import pandas as pd
import os
import sys

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
sys.path.append(os.path.abspath("src"))
import jdcoot
import math
from scipy.io import loadmat

from jdcoot.models.discrete_unsupervised_jdcoot import discrete_unsupervised_jdcoot
from jdcoot.models.discrete_semisupervised_jdcoot import discrete_semisupervised_jdcoot
from jdcoot.models.discrete_partial_jdcoot import discrete_partial_jdcoot
from jdcoot.models.discrete_unsupervised_coot import discrete_unsupervised_coot
from jdcoot.models.discrete_semisupervised_coot import discrete_semisupervised_coot
from jdcoot.models.discrete_partial_coot import discrete_partial_coot
from jdcoot.models.discrete_semisupervised_reference import discrete_semisupervised_reference
from jdcoot.models.discrete_partial_reference import discrete_partial_reference


S_data = pd.read_csv("data_omique_S.csv")
T_data = pd.read_csv("data_omique_T.csv")
X_colsS = ['X'+str(i) for i in range(S_data.shape[1]-1)]
X_colsT = ['X'+str(i) for i in range(T_data.shape[1]-1)]
S_data.columns = X_colsS + ['Z']
T_data.columns = X_colsT + ['Z']

source = S_data
target = T_data

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [23]:
source.shape, target.shape

((79, 60661), (79, 370366))

In [2]:
target

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X370356,X370357,X370358,X370359,X370360,X370361,X370362,X370363,X370364,Z
0,0.331337,0.433665,0.907527,0.929226,0.803080,0.913378,0.915925,0.975695,0.943965,0.562206,...,0.014883,0.051429,0.030359,0.090640,0.081120,0.102101,0.066396,0.455526,0.949053,2.0
1,0.380037,0.194028,0.644863,0.483128,0.415208,0.671466,0.497068,0.964929,0.877985,0.621223,...,0.398857,0.258503,0.278820,0.208904,0.288537,0.533426,0.172734,0.254140,0.936177,0.0
2,0.857103,0.819285,0.924852,0.903546,0.822678,0.950027,0.940995,0.971426,0.946664,0.910891,...,0.157011,0.154011,0.175260,0.227087,0.111708,0.171197,0.073877,0.180601,0.960520,1.0
3,0.797363,0.643394,0.932961,0.954545,0.938442,0.949231,0.953950,0.975893,0.953283,0.945784,...,0.012174,0.060258,0.027889,0.090082,0.052156,0.068259,0.036900,0.283432,0.960715,1.0
4,0.848468,0.229679,0.499823,0.784611,0.761054,0.883729,0.923103,0.868607,0.880567,0.926299,...,0.482362,0.191811,0.422333,0.467804,0.149098,0.712462,0.503727,0.416620,0.931660,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
74,0.417972,0.733041,0.830049,0.795599,0.364169,0.856912,0.847503,0.969288,0.878032,0.896617,...,0.013409,0.072668,0.026789,0.090064,0.055967,0.086504,0.034187,0.081877,0.959424,0.0
75,0.892024,0.775338,0.936082,0.917142,0.889666,0.930431,0.782313,0.937133,0.954438,0.952979,...,0.014994,0.073096,0.031776,0.101467,0.059425,0.091796,0.031106,0.197543,0.971323,1.0
76,0.686657,0.176965,0.858470,0.562835,0.244272,0.907377,0.912395,0.969669,0.949788,0.927164,...,0.462350,0.483187,0.494165,0.252890,0.602378,0.702331,0.478408,0.349309,0.877274,0.0
77,0.934454,0.727729,0.879593,0.865560,0.724130,0.902862,0.934276,0.970666,0.965207,0.913717,...,0.013428,0.070319,0.026220,0.092631,0.063690,0.071169,0.039468,0.165058,0.959352,2.0
78,0.568984,0.864085,0.836664,0.919522,0.884077,0.915868,0.941704,0.975674,0.911382,0.932207,...,0.013057,0.048362,0.027773,0.106989,0.062604,0.095138,0.043606,0.250653,0.954124,2.0

In [24]:
source = S_data
target = T_data
source = source.dropna(subset=['Z'])

target = source.dropna(subset=['Z'])

np.unique(source.Z)

source.shape, target.shape

((78, 60661), (78, 60661))

In [73]:
from jdcoot.utils import xcolumns
from sklearn.feature_selection import VarianceThreshold
source = S_data
target = T_data
source = source.dropna(subset=['Z'])
target = target.dropna(subset=['Z'])
x_source = source.loc[:, xcolumns(source)].values
x_target = target.loc[:, xcolumns(target)].values
#selector = VarianceThreshold(threshold=0.5)
selector = VarianceThreshold(threshold=0.3)
x_source_reduced = selector.fit_transform(x_source)
selector = VarianceThreshold(threshold=0.12)
#selector = VarianceThreshold(threshold=0.1)
x_target_reduced = selector.fit_transform(x_target)
x_target_reduced.shape
X_df = pd.DataFrame(x_source_reduced, columns=['X'+str(i) for i in range(x_source_reduced.shape[1])])
X_df['Z'] = source['Z'].values
source = X_df
X_df = pd.DataFrame(x_target_reduced, columns=['X'+str(i) for i in range(x_target_reduced.shape[1])])
X_df['Z'] = target['Z'].values
target = X_df
source.shape, target.shape

((78, 1788), (78, 1078))

In [51]:
target

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X60512,X60513,X60514,X60515,X60516,X60517,X60518,X60519,X60520,Z
0,0.433665,0.803080,0.646837,0.843355,0.877903,0.798815,0.982415,0.434924,0.018803,0.032013,...,0.863415,0.730676,0.016662,0.019008,0.016776,0.047850,0.025646,0.049827,0.204032,2.0
1,0.194028,0.415208,0.116847,0.249093,0.366477,0.096748,0.329840,0.176833,0.013811,0.023012,...,0.562009,0.575389,0.588001,0.532977,0.641690,0.539211,0.174914,0.758622,0.519730,0.0
2,0.819285,0.822678,0.117841,0.241890,0.283895,0.219936,0.971640,0.154427,0.015414,0.024485,...,0.928428,0.947320,0.132949,0.179450,0.168547,0.221971,0.076037,0.075427,0.882865,1.0
3,0.643394,0.938442,0.867871,0.858461,0.930585,0.857678,0.988243,0.576937,0.015632,0.031125,...,0.964975,0.230504,0.015594,0.013431,0.014899,0.062020,0.018839,0.030643,0.231643,1.0
4,0.229679,0.761054,0.207326,0.471554,0.538779,0.068366,0.649715,0.203437,0.015389,0.023411,...,0.310373,0.616332,0.652140,0.589901,0.570310,0.594290,0.578368,0.611783,0.616979,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,0.733041,0.364169,0.266076,0.422501,0.486601,0.081517,0.508009,0.306164,0.016815,0.028808,...,0.957583,0.492130,0.016697,0.017669,0.017898,0.056328,0.022025,0.036220,0.314378,0.0
74,0.775338,0.889666,0.875366,0.849793,0.582354,0.870951,0.977635,0.848177,0.015396,0.028348,...,0.165217,0.941340,0.014586,0.016810,0.017425,0.063671,0.017832,0.028403,0.138123,1.0
75,0.176965,0.244272,0.146807,0.306021,0.367064,0.058455,0.974611,0.146063,0.014086,0.025156,...,0.376853,0.307817,0.539658,0.536321,0.379427,0.573468,0.449295,0.672339,0.512420,0.0
76,0.727729,0.724130,0.705737,0.634697,0.613247,0.722534,0.979706,0.681679,0.703638,0.726884,...,0.955416,0.957125,0.014038,0.015399,0.015365,0.056222,0.021011,0.033257,0.129832,2.0
77,0.864085,0.884077,0.781994,0.832799,0.908474,0.816997,0.969112,0.798505,0.826384,0.850467,...,0.952651,0.950431,0.017942,0.016457,0.015571,0.062196,0.023466,0.034792,0.433815,2.0

In [74]:
a = np.random.choice(np.arange(len(source)), math.ceil(0.9 * len(source)), replace=False)
b = np.random.choice(np.arange(len(target)), math.ceil(0.9 * len(target)), replace=False)

S_test = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
T_test = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)
S = source.iloc[a, :].reset_index(drop=True)
T = target.iloc[b, :].reset_index(drop=True)
import os
os.environ["PYTHONHASHSEED"] = "42"

import numpy as np
import random
import tensorflow as tf

In [ ]:
#Test predicteur

import numpy as np
from sklearn.preprocessing import OneHotEncoder as onehot
from sklearn.model_selection import train_test_split
from jdcoot.utils import xcolumns, discrete_classifiers, discrete_accuracy


source_levels = np.sort(np.unique(S.Z))
target_levels = np.sort(np.unique(T.Z))

nClass = len(np.union1d(source_levels, target_levels))
categories = [np.arange(nClass)]

enc = onehot(handle_unknown="ignore", sparse_output=False, categories=categories)

x_source_train = S.loc[:, xcolumns(S)].values
z_source_train = enc.fit_transform(S.Z.values[:, np.newaxis])

x_target_train = T.loc[:, xcolumns(T)].values
z_target_train = enc.fit_transform(T.Z.values[:, np.newaxis])

x_source_test = S_test.loc[:, xcolumns(S_test)].values
z_source_test = S_test.Z.values

x_target_test = T_test.loc[:, xcolumns(T_test)].values
z_target_test = T_test.Z.values

clf_source, clf_target = discrete_classifiers(S, T, "relu", "softmax")


clf_target.fit(x_target_train, z_target_train, batch_size=len(x_target_train), epochs=10, verbose=0, shuffle=False)

clf_source.fit(x_source_train, z_source_train, batch_size=len(x_source_train), epochs=10, verbose=0, shuffle=False)

z_target_pred = enc.inverse_transform(
        clf_target.predict(x_target_test, verbose=0)
    ).ravel()
z_source_pred = enc.inverse_transform(
        clf_source.predict(x_source_test, verbose=0)
    ).ravel()

perf_test_source = discrete_accuracy(z_source_pred,S_test.Z)
perf_test_target = discrete_accuracy(z_target_pred, T_test.Z)

In [76]:
perf_test_source

np.float64(0.8571428571428571)

In [77]:
perf_test_target

np.float64(0.8571428571428571)

In [78]:
import numpy as np
import math
from sklearn.preprocessing import OneHotEncoder as onehot
from jdcoot.utils import xcolumns, discrete_classifiers, discrete_accuracy

n_runs = 10

perf_source_list = []
perf_target_list = []

for i in range(n_runs):

    a = np.random.choice(np.arange(len(source)), math.ceil(0.9 * len(source)), replace=False)
    b = np.random.choice(np.arange(len(target)), math.ceil(0.9 * len(target)), replace=False)

    S_test = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
    T_test = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)

    S = source.iloc[a, :].reset_index(drop=True)
    T = target.iloc[b, :].reset_index(drop=True)

    source_levels = np.sort(np.unique(S.Z))
    target_levels = np.sort(np.unique(T.Z))

    nClass = len(np.union1d(source_levels, target_levels))
    categories = [np.arange(nClass)]

    enc = onehot(handle_unknown="ignore", sparse_output=False, categories=categories)

    x_source_train = S.loc[:, xcolumns(S)].values
    z_source_train = enc.fit_transform(S.Z.values[:, np.newaxis])

    x_target_train = T.loc[:, xcolumns(T)].values
    z_target_train = enc.fit_transform(T.Z.values[:, np.newaxis])

    x_source_test = S_test.loc[:, xcolumns(S_test)].values
    z_source_test = S_test.Z.values

    x_target_test = T_test.loc[:, xcolumns(T_test)].values
    z_target_test = T_test.Z.values

    clf_source, clf_target = discrete_classifiers(S, T, "relu", "softmax")

    clf_target.fit(x_target_train, z_target_train,
                   batch_size=len(x_target_train), epochs=10, verbose=0, shuffle=False)

    clf_source.fit(x_source_train, z_source_train,
                   batch_size=len(x_source_train), epochs=10, verbose=0, shuffle=False)

    z_target_pred = enc.inverse_transform(
        clf_target.predict(x_target_test, verbose=0)
    ).ravel()

    z_source_pred = enc.inverse_transform(
        clf_source.predict(x_source_test, verbose=0)
    ).ravel()

    perf_test_source = discrete_accuracy(z_source_pred, z_source_test)
    perf_test_target = discrete_accuracy(z_target_pred, z_target_test)

    perf_source_list.append(perf_test_source)
    perf_target_list.append(perf_test_target)


mean_source = np.mean(perf_source_list)
mean_target = np.mean(perf_target_list)

print("Mean source test accuracy:", mean_source)
print("Mean target test accuracy:", mean_target)

Mean source test accuracy: 0.7142857142857142
Mean target test accuracy: 0.8285714285714285

In [16]:
results = []
numRepetitions = 1
#algo = "sinkhorn"
algo = "emd"
reg = 0.1

In [20]:
#Test coot
seed = 42

np.random.seed(seed)
random.seed(seed)
tf.random.set_seed(seed)
algo = "sinkhorn"
reg = 0.1
pure_source, pure_target, test_source, test_target =  discrete_unsupervised_coot(S, T, S_test, T_test,algo=algo,reg=reg,batch_size=len(x_source_train))
test_target

Delta:       0.0355328 	 Loss:       1.0887392
Delta:       0.0369520 	 Loss:       1.0688088
Delta:       0.0298457 	 Loss:       1.0594352
Delta:       0.0224613 	 Loss:       1.0548969
Delta:       0.0179421 	 Loss:       1.0527141
Delta:       0.0134685 	 Loss:       1.0515302
Delta:       0.0117900 	 Loss:       1.0508245
Delta:       0.0120477 	 Loss:       1.0502625
Delta:       0.0129738 	 Loss:       1.0495233
Delta:       0.0136951 	 Loss:       1.0485801
Delta:       0.0134978 	 Loss:       1.0475085
Delta:       0.0105706 	 Loss:       1.0467099
Delta:       0.0074890 	 Loss:       1.0462968
Delta:       0.0057166 	 Loss:       1.0460630
Delta:       0.0045449 	 Loss:       1.0459442
Delta:       0.0033655 	 Loss:       1.0458764
Delta:       0.0034922 	 Loss:       1.0458472
Delta:       0.0025385 	 Loss:       1.0458154
Delta:       0.0016386 	 Loss:       1.0457861
Delta:       0.0021867 	 Loss:       1.0457812
Delta:       0.0023173 	 Loss:       1.0457793
Delta:       0.0021242 	 Loss:       1.0457726
Delta:       0.0019072 	 Loss:       1.0457545
Delta:       0.0012127 	 Loss:       1.0457521
Delta:       0.0011141 	 Loss:       1.0457495
Delta:       0.0005874 	 Loss:       1.0457471
Delta:       0.0005406 	 Loss:       1.0457465
Delta:       0.0017477 	 Loss:       1.0457460
Delta:       0.0011953 	 Loss:       1.0457336
Delta:       0.0007692 	 Loss:       1.0457314
Delta:       0.0002832 	 Loss:       1.0457234
Delta:       0.0003563 	 Loss:       1.0457225
Delta:       0.0003961 	 Loss:       1.0457212
Delta:       0.0006480 	 Loss:       1.0457208
Delta:       0.0006957 	 Loss:       1.0457186
Delta:       0.0016400 	 Loss:       1.0457148
Delta:       0.0001162 	 Loss:       1.0457143
Delta:       0.0002116 	 Loss:       1.0457143
converged at iter  37
WARNING:tensorflow:6 out of the last 6 calls to <function Model.make_predict_function.<locals>.predict_function at 0x76a5389325c0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.

np.float64(0.5714285714285714)

In [22]:
seed = 42

np.random.seed(seed)
random.seed(seed)
tf.random.set_seed(seed)
algo = "emd"
reg = 0.1
pure_source, pure_target, test_source, test_target =  discrete_unsupervised_coot(T, S, T_test, S_test,algo=algo,reg=reg,batch_size=len(x_source_train))
test_target

Delta:       0.1462019 	 Loss:       0.9408186
Delta:       0.0000000 	 Loss:       0.9408186
converged at iter  1

np.float64(0.5714285714285714)

In [ ]:
alpha= 0.5# hyperparamètre devant la loss a été optimé
algo = "emd"
reg = 0.1
pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(S, T, S_test, T_test,algo=algo,reg=reg,batch_size=len(x_source_train), alpha=alpha)
test_target

Delta: 0.09227688251480859 	  Loss: 0.8915382451109897 	 Accuracy: 0.4444444444444444
Delta: 0.07923423515483474 	  Loss: 0.8791124123921206 	 Accuracy: 0.4444444444444444
Delta: 0.07170577576639313 	  Loss: 0.8651861422008841 	 Accuracy: 0.4444444444444444
Delta: 0.0 	  Loss: 0.8651861422008841 	 Accuracy: 0.4444444444444444
converged at iter  3

np.float64(0.7333333333333333)

In [46]:
alpha=1.5
algo = "emd"
reg = 0.1

pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(T, S, T_test, S_test, algo=algo, reg=reg,batch_size=len(x_source_train), alpha=alpha)
test_target

Delta: 0.0 	  Loss: 0.9186105615795105 	 Accuracy: 0.4126984126984127
converged at iter  0

np.float64(0.4)

In [57]:
S = source
T = target


#Test predicteur

tf.config.experimental.enable_op_determinism()
source_levels = np.sort(np.unique(S.Z))
target_levels = np.sort(np.unique(T.Z))

nClass = len(np.union1d(source_levels, target_levels))
categories = [np.arange(nClass)]

enc = onehot(handle_unknown="ignore", sparse_output=False, categories=categories)

x_source_train = S.loc[:, xcolumns(S)].values
z_source_train = enc.fit_transform(S.Z.values[:, np.newaxis])

x_target_train = T.loc[:, xcolumns(T)].values
z_target_train = enc.fit_transform(T.Z.values[:, np.newaxis])

x_source_test = S.loc[:, xcolumns(S)].values
z_source_test = S.Z.values

x_target_test = T.loc[:, xcolumns(T)].values
z_target_test = T.Z.values

clf_source, clf_target = discrete_classifiers(S, T, "relu", "softmax")


clf_target.fit(x_target_train, z_target_train, batch_size=len(x_target_train), epochs=10, verbose=0, shuffle=False)

clf_source.fit(x_source_train, z_source_train, batch_size=len(x_source_train), epochs=10, verbose=0, shuffle=False)

z_target_pred = enc.inverse_transform(
        clf_target.predict(x_target_test, verbose=0)
    ).ravel()
z_source_pred = enc.inverse_transform(
        clf_source.predict(x_source_test, verbose=0)
    ).ravel()

perf_test_source = discrete_accuracy(z_source_pred,S.Z)
perf_test_target = discrete_accuracy(z_target_pred, T.Z)

In [59]:
perf_test_target

np.float64(0.9871794871794872)

In [68]:
algo = "emd"
reg = 0.1
pure_source, pure_target, test_source, test_target =  discrete_unsupervised_coot(S, T, S, T,algo=algo,reg=reg,batch_size=len(x_source_train))
test_target

Delta:       0.1570430 	 Loss:      -0.0000000
Delta:       0.0000000 	 Loss:      -0.0000000
converged at iter  1

np.float64(0.9487179487179487)

In [69]:
pure_source, pure_target, test_source, test_target =  discrete_unsupervised_coot(T, S, T, S,algo=algo,reg=reg,batch_size=len(x_source_train))
test_target

Delta:       0.1570430 	 Loss:      -0.0000000
Delta:       0.0000000 	 Loss:      -0.0000000
converged at iter  1

np.float64(0.9358974358974359)

In [66]:
alpha= 1.5
seed = 42

np.random.seed(seed)
random.seed(seed)
tf.random.set_seed(seed)
pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(S, T, S, T, algo=algo, reg=reg,batch_size=len(x_source_train), alpha=alpha)
test_target

Delta: 0.0 	  Loss: -1.1477454727735212e-17 	 Accuracy: 1.0
converged at iter  0

np.float64(1.0)

In [67]:
alpha= 1.5
seed = 42

np.random.seed(seed)
random.seed(seed)
tf.random.set_seed(seed)
pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(T, S, T, S, algo=algo, reg=reg,batch_size=len(x_source_train), alpha=alpha)
test_target

Delta: 0.0 	  Loss: -1.1477454727735212e-17 	 Accuracy: 1.0
converged at iter  0

np.float64(1.0)

In [70]:
np.linspace(0, 2, 21)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold
import math

alpha_values = np.linspace(0, 2, 21)
num_folds = 5

kf_source = KFold(n_splits=num_folds, shuffle=True, random_state=42)
kf_target = KFold(n_splits=num_folds, shuffle=True, random_state=42)

results = []

algo = "sinkhorn"
reg = 0.1

best_alpha_global = None
best_score_global = -np.inf

for alpha in alpha_values:
    
    fold_scores = []
    
    for (train_idx_s, test_idx_s), (train_idx_t, test_idx_t) in zip(
        kf_source.split(source), 
        kf_target.split(target)
    ):
        
        S = source.iloc[train_idx_s].reset_index(drop=True)
        S_test = source.iloc[test_idx_s].reset_index(drop=True)

        T = target.iloc[train_idx_t].reset_index(drop=True)
        T_test = target.iloc[test_idx_t].reset_index(drop=True)

        pure_source, pure_target, test_source, test_target = \
            discrete_unsupervised_jdcoot(
                S, T,
                S_test, T_test,
                algo=algo,
                reg=reg,
                batch_size=len(S),
                alpha=alpha
            )

        score = test_target   

        fold_scores.append(score)

    mean_score = np.mean(fold_scores)

    if mean_score > best_score_global:
        best_score_global = mean_score
        best_alpha_global = alpha

    results.append({
        "alpha": alpha,
        "mean_score": mean_score
    })

df_results = pd.DataFrame(results)

print("Best alpha:", best_alpha_global)
print("Best score:", best_score_global)

df_results.to_excel("results_cv.xlsx", index=False)

Delta: 0.03859112163244333 	  Loss: 1.0757085724823683 	 Accuracy: 0.6129032258064516
Delta: 0.030214226262528694 	  Loss: 1.0650784225153846 	 Accuracy: 0.5
Delta: 0.022991820540486235 	  Loss: 1.0606929853856388 	 Accuracy: 0.5483870967741935
Delta: 0.020983479227586723 	  Loss: 1.0581411542976906 	 Accuracy: 0.5645161290322581
Delta: 0.019418545181207312 	  Loss: 1.0556429188762637 	 Accuracy: 0.5806451612903226
Delta: 0.01695762847509114 	  Loss: 1.0536094453216345 	 Accuracy: 0.5483870967741935
Delta: 0.011256960611149863 	  Loss: 1.05261203162696 	 Accuracy: 0.5967741935483871
Delta: 0.0071649772076922795 	  Loss: 1.0522742876953193 	 Accuracy: 0.5483870967741935
Delta: 0.005925570069823322 	  Loss: 1.0521076163809995 	 Accuracy: 0.5483870967741935
Delta: 0.005867788978077584 	  Loss: 1.051991302606024 	 Accuracy: 0.5483870967741935
Delta: 0.0049383469305281785 	  Loss: 1.0518938571144967 	 Accuracy: 0.5483870967741935
Delta: 0.003986628174880538 	  Loss: 1.0518017552229963 	 Accuracy: 0.5483870967741935
Delta: 0.003915057744004268 	  Loss: 1.0517466562543298 	 Accuracy: 0.5483870967741935
Delta: 0.004228453836051142 	  Loss: 1.0517130230772582 	 Accuracy: 0.5645161290322581
Delta: 0.004539279213769599 	  Loss: 1.0516578061281932 	 Accuracy: 0.5645161290322581
Delta: 0.0038007946033444436 	  Loss: 1.0515936436660018 	 Accuracy: 0.5645161290322581
Delta: 0.003550359643878536 	  Loss: 1.0515521284621334 	 Accuracy: 0.5645161290322581
Delta: 0.003223218466120591 	  Loss: 1.05154248386705 	 Accuracy: 0.5645161290322581
Delta: 0.0032542288318251835 	  Loss: 1.0515267158942623 	 Accuracy: 0.5483870967741935
Delta: 0.0034979893888553437 	  Loss: 1.0515045786295603 	 Accuracy: 0.5483870967741935
Delta: 0.003135461184106859 	  Loss: 1.0514802528965121 	 Accuracy: 0.5483870967741935
Delta: 0.003615615383928343 	  Loss: 1.0514514016936827 	 Accuracy: 0.5483870967741935
Delta: 0.003551523456441465 	  Loss: 1.0514242943947139 	 Accuracy: 0.5806451612903226
Delta: 0.003493168321054623 	  Loss: 1.051408325234228 	 Accuracy: 0.5806451612903226
Delta: 0.004420315237695201 	  Loss: 1.0514005186175606 	 Accuracy: 0.5806451612903226
Delta: 0.0038808487259705433 	  Loss: 1.0513868776657898 	 Accuracy: 0.5806451612903226
Delta: 0.003699236563261743 	  Loss: 1.0513549695336684 	 Accuracy: 0.5806451612903226
Delta: 0.003902073206618939 	  Loss: 1.0513179080684434 	 Accuracy: 0.5806451612903226
Delta: 0.003262669699440801 	  Loss: 1.0512955061835183 	 Accuracy: 0.5806451612903226
Delta: 0.0037128902044153045 	  Loss: 1.0512556747477542 	 Accuracy: 0.5645161290322581
Delta: 0.0037898656004576293 	  Loss: 1.0512132281463376 	 Accuracy: 0.5645161290322581
Delta: 0.003815736147962439 	  Loss: 1.0511770834438667 	 Accuracy: 0.5806451612903226
Delta: 0.0042428910595193395 	  Loss: 1.051118552305246 	 Accuracy: 0.5806451612903226
Delta: 0.0050343204879049345 	  Loss: 1.0510253741195914 	 Accuracy: 0.5806451612903226
Delta: 0.005576731825258818 	  Loss: 1.0509292635227707 	 Accuracy: 0.5806451612903226
Delta: 0.0054391758495426915 	  Loss: 1.0508189724657284 	 Accuracy: 0.5806451612903226
Delta: 0.00481114421925308 	  Loss: 1.0507215859361516 	 Accuracy: 0.5806451612903226
Delta: 0.005167178642832086 	  Loss: 1.050632657034296 	 Accuracy: 0.5967741935483871
Delta: 0.005705166764730815 	  Loss: 1.050519797891941 	 Accuracy: 0.5967741935483871
Delta: 0.004890471549283933 	  Loss: 1.05036463927541 	 Accuracy: 0.5806451612903226
Delta: 0.003995849804839208 	  Loss: 1.0502825311189934 	 Accuracy: 0.5806451612903226
Delta: 0.003252422300041996 	  Loss: 1.0502176856000818 	 Accuracy: 0.5967741935483871
Delta: 0.0034573529654598626 	  Loss: 1.050165101425479 	 Accuracy: 0.5806451612903226
Delta: 0.002935562459769656 	  Loss: 1.0501167983295494 	 Accuracy: 0.5806451612903226
Delta: 0.0031455707320983913 	  Loss: 1.0500869368939105 	 Accuracy: 0.5967741935483871
Delta: 0.003437256777750592 	  Loss: 1.050049964781262 	 Accuracy: 0.5967741935483871
Delta: 0.0030325834206876424 	  Loss: 1.0500139825455568 	 Accuracy: 0.5967741935483871
Delta: 0.003394620526356327 	  Loss: 1.049970244676285 	 Accuracy: 0.5967741935483871
Delta: 0.003180626294482086 	  Loss: 1.04989466502272 	 Accuracy: 0.5967741935483871
Delta: 0.004006521407550641 	  Loss: 1.0498301264463654 	 Accuracy: 0.5967741935483871
Delta: 0.0028394376961671276 	  Loss: 1.0497498315092901 	 Accuracy: 0.5967741935483871
Delta: 0.003174466616439244 	  Loss: 1.0496976199186603 	 Accuracy: 0.5967741935483871
Delta: 0.0030762003429391734 	  Loss: 1.0496471126950007 	 Accuracy: 0.5967741935483871
Delta: 0.0038549110361754423 	  Loss: 1.0495898988635353 	 Accuracy: 0.6129032258064516
Delta: 0.003369070970655581 	  Loss: 1.049517373806565 	 Accuracy: 0.6129032258064516
Delta: 0.0034121284074662733 	  Loss: 1.0494668011971253 	 Accuracy: 0.5967741935483871
Delta: 0.002997020196355819 	  Loss: 1.0494177131027762 	 Accuracy: 0.5967741935483871
Delta: 0.002354211964956831 	  Loss: 1.049379923067172 	 Accuracy: 0.5967741935483871
Delta: 0.0022768906715929997 	  Loss: 1.0493496198577068 	 Accuracy: 0.5967741935483871
Delta: 0.00241693364886022 	  Loss: 1.0493162230124633 	 Accuracy: 0.5967741935483871
Delta: 0.002177424104434382 	  Loss: 1.0492784240968556 	 Accuracy: 0.5967741935483871
Delta: 0.0020738534192760202 	  Loss: 1.0492472480535109 	 Accuracy: 0.5967741935483871
Delta: 0.001743876113649274 	  Loss: 1.0492248305510279 	 Accuracy: 0.5967741935483871
Delta: 0.0023061280728033876 	  Loss: 1.0492036604989536 	 Accuracy: 0.5806451612903226
Delta: 0.0022246306751884663 	  Loss: 1.0491898547649035 	 Accuracy: 0.5806451612903226
Delta: 0.0025050129714561564 	  Loss: 1.0491911175489084 	 Accuracy: 0.5806451612903226
Delta: 0.002381794244803421 	  Loss: 1.0491750428565463 	 Accuracy: 0.5967741935483871
Delta: 0.0023255678251905307 	  Loss: 1.0491557372926006 	 Accuracy: 0.5967741935483871
Delta: 0.002341828676523744 	  Loss: 1.0491487370028634 	 Accuracy: 0.5967741935483871
Delta: 0.0027419136353721237 	  Loss: 1.0491270456769546 	 Accuracy: 0.6129032258064516
Delta: 0.0028152727862387453 	  Loss: 1.0490966084309545 	 Accuracy: 0.6129032258064516
Delta: 0.002363130552841275 	  Loss: 1.049082633068151 	 Accuracy: 0.6129032258064516
Delta: 0.0015234117023638016 	  Loss: 1.0490576061571726 	 Accuracy: 0.6129032258064516
Delta: 0.0013392432019853479 	  Loss: 1.049045321750001 	 Accuracy: 0.6129032258064516
Delta: 0.001752675837855209 	  Loss: 1.0490276560429879 	 Accuracy: 0.6129032258064516
Delta: 0.002324568361804975 	  Loss: 1.0490083525191176 	 Accuracy: 0.6129032258064516
Delta: 0.0014543049777297748 	  Loss: 1.0489854762339625 	 Accuracy: 0.6129032258064516
Delta: 0.0010264136457342511 	  Loss: 1.048967290472012 	 Accuracy: 0.6129032258064516
Delta: 0.00042896344060614774 	  Loss: 1.0489548097782566 	 Accuracy: 0.6129032258064516
Delta: 0.0009052207081837503 	  Loss: 1.0489520674038557 	 Accuracy: 0.6129032258064516
Delta: 0.0013946285071491935 	  Loss: 1.0489484307802748 	 Accuracy: 0.6129032258064516
Delta: 0.0013281728202029115 	  Loss: 1.0489440808075896 	 Accuracy: 0.6129032258064516
Delta: 0.0006493731198588355 	  Loss: 1.0489330375207877 	 Accuracy: 0.6129032258064516
Delta: 0.0012011036108703662 	  Loss: 1.0489313956635653 	 Accuracy: 0.6129032258064516
Delta: 0.0007472207934729062 	  Loss: 1.0489274890447893 	 Accuracy: 0.6129032258064516
Delta: 0.001371098728521532 	  Loss: 1.0489264496035544 	 Accuracy: 0.6129032258064516
Delta: 0.0013181277616440999 	  Loss: 1.04892783823483 	 Accuracy: 0.6129032258064516
Delta: 0.0005086474511609746 	  Loss: 1.0489197929751175 	 Accuracy: 0.6129032258064516
Delta: 0.0005461479707057253 	  Loss: 1.048920232701816 	 Accuracy: 0.6129032258064516
Delta: 0.0009241639766599001 	  Loss: 1.0489201174445184 	 Accuracy: 0.6129032258064516
Delta: 0.0011318940776897616 	  Loss: 1.048918238737651 	 Accuracy: 0.6129032258064516
Delta: 0.00048616397411908933 	  Loss: 1.0489178689767171 	 Accuracy: 0.6129032258064516
Delta: 0.000591625356100961 	  Loss: 1.048919265604395 	 Accuracy: 0.6129032258064516
Delta: 0.0007360678494523535 	  Loss: 1.048918001738535 	 Accuracy: 0.6129032258064516
Delta: 0.0008058985918219054 	  Loss: 1.0489187108495983 	 Accuracy: 0.6129032258064516
Delta: 0.0007447246560159815 	  Loss: 1.048921894875304 	 Accuracy: 0.6129032258064516
Delta: 0.000628208936111866 	  Loss: 1.0489194746113097 	 Accuracy: 0.6129032258064516
Delta: 0.00036727954954870025 	  Loss: 1.0489188743400575 	 Accuracy: 0.6129032258064516
Delta: 0.0007868079098519829 	  Loss: 1.048916453380686 	 Accuracy: 0.6129032258064516
Delta: 0.000647148512770469 	  Loss: 1.0489160203665768 	 Accuracy: 0.6129032258064516
Delta: 0.03872659074500787 	  Loss: 1.0646267176278332 	 Accuracy: 0.5483870967741935
Delta: 0.02845424158667896 	  Loss: 1.0558757971468693 	 Accuracy: 0.6129032258064516
Delta: 0.02162555076879518 	  Loss: 1.0522753087328642 	 Accuracy: 0.5806451612903226
Delta: 0.015171719301756278 	  Loss: 1.0505727594088046 	 Accuracy: 0.6935483870967742
Delta: 0.01170020352975939 	  Loss: 1.0498409133737239 	 Accuracy: 0.6290322580645161
Delta: 0.010237282091131662 	  Loss: 1.0493712918518971 	 Accuracy: 0.6612903225806451
Delta: 0.009473716082948216 	  Loss: 1.0490161262151383 	 Accuracy: 0.6451612903225806
Delta: 0.008754183801854751 	  Loss: 1.0487741936042645 	 Accuracy: 0.6290322580645161
Delta: 0.008093710716455479 	  Loss: 1.048555179860766 	 Accuracy: 0.6290322580645161
Delta: 0.007671163476257091 	  Loss: 1.048356562805521 	 Accuracy: 0.6129032258064516
Delta: 0.007395531011504185 	  Loss: 1.0481360935875246 	 Accuracy: 0.6129032258064516
Delta: 0.007709247224583194 	  Loss: 1.0478721907439965 	 Accuracy: 0.6129032258064516
Delta: 0.007447469589470982 	  Loss: 1.047656691325728 	 Accuracy: 0.6129032258064516
Delta: 0.006967335596506476 	  Loss: 1.0474883984135315 	 Accuracy: 0.5967741935483871
Delta: 0.005777841607499252 	  Loss: 1.0473576365102564 	 Accuracy: 0.6129032258064516
Delta: 0.005206700439453801 	  Loss: 1.047269193897022 	 Accuracy: 0.6129032258064516
Delta: 0.004128886557004925 	  Loss: 1.0471979199175117 	 Accuracy: 0.6290322580645161
Delta: 0.004636409201715852 	  Loss: 1.0471429477577707 	 Accuracy: 0.6290322580645161
Delta: 0.005336182261897972 	  Loss: 1.0470707234929963 	 Accuracy: 0.6451612903225806
Delta: 0.004410616678296103 	  Loss: 1.0470042479191342 	 Accuracy: 0.6290322580645161
Delta: 0.005091028531922681 	  Loss: 1.0468938241859476 	 Accuracy: 0.6290322580645161
Delta: 0.005227655123779485 	  Loss: 1.0467859406634732 	 Accuracy: 0.6290322580645161
Delta: 0.00497249867690991 	  Loss: 1.0466897533917645 	 Accuracy: 0.6290322580645161
Delta: 0.005080329339976685 	  Loss: 1.0465867093799381 	 Accuracy: 0.6290322580645161
Delta: 0.004516652601186496 	  Loss: 1.0464920042694281 	 Accuracy: 0.6290322580645161
Delta: 0.004614899344537656 	  Loss: 1.0464002289274372 	 Accuracy: 0.6290322580645161
Delta: 0.004640299680888427 	  Loss: 1.0463087039012828 	 Accuracy: 0.6290322580645161
Delta: 0.00600038239643941 	  Loss: 1.0461922053946737 	 Accuracy: 0.6290322580645161
Delta: 0.005201501642949746 	  Loss: 1.0460438118825572 	 Accuracy: 0.6451612903225806
Delta: 0.005559435612305202 	  Loss: 1.0459479957009759 	 Accuracy: 0.6451612903225806
Delta: 0.00446990734779723 	  Loss: 1.0458281300243208 	 Accuracy: 0.6451612903225806
Delta: 0.0040036541340813135 	  Loss: 1.0457646563953094 	 Accuracy: 0.6451612903225806
Delta: 0.0038412384796512335 	  Loss: 1.0457075182928164 	 Accuracy: 0.6451612903225806
Delta: 0.0036787148990987876 	  Loss: 1.0456576139325628 	 Accuracy: 0.6451612903225806
Delta: 0.0034715339065240877 	  Loss: 1.0456124461741279 	 Accuracy: 0.6451612903225806
Delta: 0.0039578121043364264 	  Loss: 1.0455682895843519 	 Accuracy: 0.6451612903225806
Delta: 0.004618535705017945 	  Loss: 1.0455162918524472 	 Accuracy: 0.6451612903225806
Delta: 0.0042345643074148814 	  Loss: 1.04547504295445 	 Accuracy: 0.6451612903225806
Delta: 0.004192856732246034 	  Loss: 1.0454014822706434 	 Accuracy: 0.6451612903225806
Delta: 0.004331691410649767 	  Loss: 1.0453810773295573 	 Accuracy: 0.6451612903225806
Delta: 0.003870443100190123 	  Loss: 1.0453379433491907 	 Accuracy: 0.6451612903225806
Delta: 0.004140209996501826 	  Loss: 1.0453005506806448 	 Accuracy: 0.6451612903225806
Delta: 0.004820569250564998 	  Loss: 1.0452711561614028 	 Accuracy: 0.6451612903225806
Delta: 0.003871474879444604 	  Loss: 1.0452118297593884 	 Accuracy: 0.6612903225806451
Delta: 0.004055884485817662 	  Loss: 1.045178008207387 	 Accuracy: 0.6612903225806451
Delta: 0.00472713079901153 	  Loss: 1.0451648371833402 	 Accuracy: 0.6774193548387096
Delta: 0.00475127541621455 	  Loss: 1.045123318187798 	 Accuracy: 0.6774193548387096
Delta: 0.004929169202605907 	  Loss: 1.0450953792717386 	 Accuracy: 0.6612903225806451
Delta: 0.0038244597080720534 	  Loss: 1.045071009306451 	 Accuracy: 0.6612903225806451
Delta: 0.004677850608987868 	  Loss: 1.045050065557936 	 Accuracy: 0.6612903225806451
Delta: 0.004201806383316906 	  Loss: 1.0450231820463123 	 Accuracy: 0.6612903225806451
Delta: 0.0054521462526253665 	  Loss: 1.044971423333148 	 Accuracy: 0.6612903225806451
Delta: 0.004351276437898125 	  Loss: 1.044925551602608 	 Accuracy: 0.6612903225806451
Delta: 0.004335974928184407 	  Loss: 1.0448907175005373 	 Accuracy: 0.6612903225806451
Delta: 0.004000781676097083 	  Loss: 1.0448523556674671 	 Accuracy: 0.6612903225806451
Delta: 0.0036824103187289444 	  Loss: 1.0448166859174122 	 Accuracy: 0.6612903225806451
Delta: 0.004001626658938607 	  Loss: 1.0448059836021157 	 Accuracy: 0.6612903225806451
Delta: 0.002806455041495643 	  Loss: 1.044786675050462 	 Accuracy: 0.6612903225806451
Delta: 0.003091561844249335 	  Loss: 1.0447703734783889 	 Accuracy: 0.6612903225806451
Delta: 0.0038501806188809126 	  Loss: 1.0447432712153346 	 Accuracy: 0.6612903225806451
Delta: 0.0036674739523958623 	  Loss: 1.0447174794005516 	 Accuracy: 0.6612903225806451
Delta: 0.0032702223239334657 	  Loss: 1.044686870641412 	 Accuracy: 0.6612903225806451
Delta: 0.0024755676330954083 	  Loss: 1.044677041433044 	 Accuracy: 0.6612903225806451
Delta: 0.0025343366610615396 	  Loss: 1.0446599585642264 	 Accuracy: 0.6612903225806451
Delta: 0.0033819718495526957 	  Loss: 1.0446622327898425 	 Accuracy: 0.6612903225806451
Delta: 0.0027378473547817264 	  Loss: 1.0446605717024005 	 Accuracy: 0.6612903225806451
Delta: 0.004104084905401588 	  Loss: 1.044656832214501 	 Accuracy: 0.6612903225806451
Delta: 0.0028703267892557687 	  Loss: 1.0446572075294729 	 Accuracy: 0.6612903225806451
Delta: 0.0033915628287219633 	  Loss: 1.0446479257901302 	 Accuracy: 0.6612903225806451
Delta: 0.002994301017197286 	  Loss: 1.0446094106963555 	 Accuracy: 0.6612903225806451
Delta: 0.0033360899741053055 	  Loss: 1.0445933139569314 	 Accuracy: 0.6451612903225806
Delta: 0.0035797852893490077 	  Loss: 1.044554027389954 	 Accuracy: 0.6451612903225806
Delta: 0.0029258126565689098 	  Loss: 1.0445255501696131 	 Accuracy: 0.6451612903225806
Delta: 0.00239073635946946 	  Loss: 1.044525859568628 	 Accuracy: 0.6451612903225806
Delta: 0.0018562792274206662 	  Loss: 1.0445268077202519 	 Accuracy: 0.6451612903225806
Delta: 0.001912504955721958 	  Loss: 1.0445275786159471 	 Accuracy: 0.6451612903225806
Delta: 0.0016263093395289365 	  Loss: 1.044526511502385 	 Accuracy: 0.6451612903225806
Delta: 0.001986538251046049 	  Loss: 1.0445238046174228 	 Accuracy: 0.6451612903225806
Delta: 0.001960806421929211 	  Loss: 1.0445143776689312 	 Accuracy: 0.6451612903225806
Delta: 0.002432299935991874 	  Loss: 1.0445155819825034 	 Accuracy: 0.6451612903225806
Delta: 0.0014231444739442125 	  Loss: 1.044511030560943 	 Accuracy: 0.6451612903225806
Delta: 0.0013581114344449233 	  Loss: 1.0445045990036763 	 Accuracy: 0.6451612903225806
Delta: 0.0025221921742022337 	  Loss: 1.0444979057121226 	 Accuracy: 0.6451612903225806
Delta: 0.0027663555827030536 	  Loss: 1.0444987632362284 	 Accuracy: 0.6451612903225806
Delta: 0.0023781301385525015 	  Loss: 1.0444947782471734 	 Accuracy: 0.6451612903225806
Delta: 0.0019226028807476793 	  Loss: 1.0444873238233492 	 Accuracy: 0.6451612903225806
Delta: 0.00162010241911337 	  Loss: 1.0444921552926232 	 Accuracy: 0.6451612903225806
Delta: 0.002636593429773581 	  Loss: 1.0445071778797987 	 Accuracy: 0.6451612903225806
Delta: 0.0014605627733804186 	  Loss: 1.0445037201853085 	 Accuracy: 0.6451612903225806
Delta: 0.0016943086383983308 	  Loss: 1.044502016769739 	 Accuracy: 0.6451612903225806
Delta: 0.0019316894719344786 	  Loss: 1.0445024284213282 	 Accuracy: 0.6451612903225806
Delta: 0.0016504591181424825 	  Loss: 1.0444966399852915 	 Accuracy: 0.6451612903225806
Delta: 0.0014490887792722104 	  Loss: 1.0444956033905837 	 Accuracy: 0.6451612903225806
Delta: 0.0011371629118443977 	  Loss: 1.044501513851446 	 Accuracy: 0.6451612903225806
Delta: 0.0008982530558398636 	  Loss: 1.0445035121401853 	 Accuracy: 0.6451612903225806
Delta: 0.0009181811573046396 	  Loss: 1.0445010168670197 	 Accuracy: 0.6451612903225806
Delta: 0.0009539610818867791 	  Loss: 1.0445003942972473 	 Accuracy: 0.6451612903225806
Delta: 0.0018996463235016164 	  Loss: 1.044497030281489 	 Accuracy: 0.6451612903225806
Delta: 0.0010190695017646013 	  Loss: 1.044487084758866 	 Accuracy: 0.6451612903225806
Delta: 0.0010441114411169415 	  Loss: 1.044482017837636 	 Accuracy: 0.6451612903225806
Delta: 0.037687092067394776 	  Loss: 1.0843315922430972 	 Accuracy: 0.45161290322580644
Delta: 0.02996734245503388 	  Loss: 1.0746690210339704 	 Accuracy: 0.5
Delta: 0.02257984836148549 	  Loss: 1.0699308524139002 	 Accuracy: 0.4838709677419355
Delta: 0.018706165771646133 	  Loss: 1.067921456849363 	 Accuracy: 0.4838709677419355
Delta: 0.016454424273332355 	  Loss: 1.0665654695900826 	 Accuracy: 0.46774193548387094
Delta: 0.014439336005969841 	  Loss: 1.0655660278191625 	 Accuracy: 0.46774193548387094
Delta: 0.014196429149217418 	  Loss: 1.0647299391650153 	 Accuracy: 0.46774193548387094
Delta: 0.013988688140330573 	  Loss: 1.0638676162922966 	 Accuracy: 0.4838709677419355
Delta: 0.012090531962578926 	  Loss: 1.0631726902701022 	 Accuracy: 0.5
Delta: 0.009120365317405878 	  Loss: 1.062669861742005 	 Accuracy: 0.5
Delta: 0.007110404998436675 	  Loss: 1.0623737375320734 	 Accuracy: 0.5
Delta: 0.006051554974925835 	  Loss: 1.0622545895926658 	 Accuracy: 0.5
Delta: 0.004632583658196479 	  Loss: 1.0621312145250166 	 Accuracy: 0.5
Delta: 0.0038824453788302705 	  Loss: 1.062051617879765 	 Accuracy: 0.5
Delta: 0.003562383243348495 	  Loss: 1.061980814854584 	 Accuracy: 0.5
Delta: 0.003686969122171532 	  Loss: 1.0619393336000909 	 Accuracy: 0.5
Delta: 0.0030343275240742903 	  Loss: 1.0618903510732947 	 Accuracy: 0.5
Delta: 0.004039941606625293 	  Loss: 1.0618556177785947 	 Accuracy: 0.5
Delta: 0.0038016423617188953 	  Loss: 1.0617993797654215 	 Accuracy: 0.5
Delta: 0.0037250633739981235 	  Loss: 1.0617544432572983 	 Accuracy: 0.5
Delta: 0.0038245032711820078 	  Loss: 1.0616907174429382 	 Accuracy: 0.5
Delta: 0.002834271514299767 	  Loss: 1.061636727394728 	 Accuracy: 0.5
Delta: 0.0031132998532920238 	  Loss: 1.0615990865117615 	 Accuracy: 0.5
Delta: 0.002395179085147067 	  Loss: 1.0615483235348395 	 Accuracy: 0.5161290322580645
Delta: 0.0029832867639550324 	  Loss: 1.0615302119500982 	 Accuracy: 0.5161290322580645
Delta: 0.001962771828531874 	  Loss: 1.06150989467077 	 Accuracy: 0.5161290322580645
Delta: 0.0026074405891793996 	  Loss: 1.0614912478014846 	 Accuracy: 0.5161290322580645
Delta: 0.0032282667935739045 	  Loss: 1.0614765559738548 	 Accuracy: 0.5161290322580645
Delta: 0.002537493812324769 	  Loss: 1.0614491198837392 	 Accuracy: 0.5161290322580645
Delta: 0.002603844425791997 	  Loss: 1.061431082191252 	 Accuracy: 0.5161290322580645
Delta: 0.0029242985466158954 	  Loss: 1.0614139994913983 	 Accuracy: 0.5161290322580645
Delta: 0.0024178485422138556 	  Loss: 1.0613865023710303 	 Accuracy: 0.5161290322580645

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.003856427095219662 	  Loss: 1.0255004149162632 	 Accuracy: 0.4032258064516129
Delta: 0.003191977712695043 	  Loss: 1.02544191966816 	 Accuracy: 0.4032258064516129
Delta: 0.0027925983129557437 	  Loss: 1.0254247182382745 	 Accuracy: 0.4032258064516129
Delta: 0.002478626994706039 	  Loss: 1.0254045005318275 	 Accuracy: 0.4032258064516129
Delta: 0.0018390018905339845 	  Loss: 1.0253673802518857 	 Accuracy: 0.4032258064516129
Delta: 0.0021851059057896405 	  Loss: 1.0253420130654989 	 Accuracy: 0.4032258064516129
Delta: 0.001593525548429793 	  Loss: 1.0253177371650182 	 Accuracy: 0.4032258064516129
Delta: 0.0021047847208479206 	  Loss: 1.0253087279184403 	 Accuracy: 0.4032258064516129
Delta: 0.0014211017568431588 	  Loss: 1.025277792577484 	 Accuracy: 0.4032258064516129
Delta: 0.0015651804954751286 	  Loss: 1.025240460530199 	 Accuracy: 0.4032258064516129
Delta: 0.0018042620079034277 	  Loss: 1.0252184341573476 	 Accuracy: 0.4032258064516129
Delta: 0.0014317042240135263 	  Loss: 1.025176311768642 	 Accuracy: 0.4032258064516129
Delta: 0.0014584099969972195 	  Loss: 1.0251590094197873 	 Accuracy: 0.4032258064516129
Delta: 0.0013610692900780377 	  Loss: 1.0251408305989735 	 Accuracy: 0.4032258064516129
Delta: 0.001507215609003572 	  Loss: 1.0251332515579485 	 Accuracy: 0.4032258064516129
Delta: 0.0021791840411399892 	  Loss: 1.0251162744352302 	 Accuracy: 0.4032258064516129
Delta: 0.00223414894471678 	  Loss: 1.0250837320797006 	 Accuracy: 0.4032258064516129
Delta: 0.0013926736689363378 	  Loss: 1.0250544141246003 	 Accuracy: 0.4032258064516129
Delta: 0.0015552127724806836 	  Loss: 1.0250351023719766 	 Accuracy: 0.4032258064516129
Delta: 0.0013926978695463954 	  Loss: 1.0250096358265146 	 Accuracy: 0.4032258064516129
Delta: 0.0014234455240170986 	  Loss: 1.0249953057567218 	 Accuracy: 0.4032258064516129
Delta: 0.0019859281528062924 	  Loss: 1.0249774632836668 	 Accuracy: 0.4032258064516129
Delta: 0.0016828793184626469 	  Loss: 1.0249596158820533 	 Accuracy: 0.4032258064516129
Delta: 0.0012237387938971679 	  Loss: 1.0249500217570056 	 Accuracy: 0.4032258064516129
Delta: 0.0018178669004232945 	  Loss: 1.024950497627321 	 Accuracy: 0.4032258064516129
Delta: 0.0007320836879975932 	  Loss: 1.0249351594640899 	 Accuracy: 0.4032258064516129
Delta: 0.0006942223424925371 	  Loss: 1.0249281403254722 	 Accuracy: 0.4032258064516129
Delta: 0.0012968311075681283 	  Loss: 1.0249194463105211 	 Accuracy: 0.4032258064516129
Delta: 0.0007667749666883056 	  Loss: 1.024905948955391 	 Accuracy: 0.4032258064516129
Delta: 0.0007117158244599215 	  Loss: 1.0248951018666035 	 Accuracy: 0.4032258064516129
Delta: 0.000297629052428318 	  Loss: 1.0248887532066213 	 Accuracy: 0.4032258064516129
Delta: 0.00035386422968762787 	  Loss: 1.0248843776632537 	 Accuracy: 0.4032258064516129
Delta: 0.00046888745991628027 	  Loss: 1.0248805576763163 	 Accuracy: 0.4032258064516129
Delta: 0.0004937622510828662 	  Loss: 1.0248720377284657 	 Accuracy: 0.4032258064516129
Delta: 0.00040386057868816013 	  Loss: 1.0248619177532459 	 Accuracy: 0.4032258064516129
Delta: 0.000551318410831318 	  Loss: 1.0248581971206987 	 Accuracy: 0.4032258064516129
Delta: 0.0011705427945351904 	  Loss: 1.0248584314932772 	 Accuracy: 0.4032258064516129
Delta: 0.0008311264365427558 	  Loss: 1.0248518228293522 	 Accuracy: 0.4032258064516129
Delta: 0.0013282313814338331 	  Loss: 1.0248505986893606 	 Accuracy: 0.4032258064516129
Delta: 0.0005343419623649435 	  Loss: 1.0248493945587467 	 Accuracy: 0.4032258064516129
Delta: 0.0008618805513206468 	  Loss: 1.0248448463491233 	 Accuracy: 0.4032258064516129
Delta: 0.0008312651602954187 	  Loss: 1.024851415441089 	 Accuracy: 0.4032258064516129
Delta: 0.0010212186321755506 	  Loss: 1.0248559313743995 	 Accuracy: 0.4032258064516129
Delta: 0.0006896326939120016 	  Loss: 1.0248607033326271 	 Accuracy: 0.4032258064516129
Delta: 0.0003371544541379599 	  Loss: 1.024855018547611 	 Accuracy: 0.4032258064516129
Delta: 0.00011293297252857901 	  Loss: 1.024851936560259 	 Accuracy: 0.4032258064516129
Delta: 8.28139610910277e-05 	  Loss: 1.0248481075748879 	 Accuracy: 0.4032258064516129
Delta: 1.538138844426546e-05 	  Loss: 1.024845633575565 	 Accuracy: 0.4032258064516129
Delta: 0.00023229124793205664 	  Loss: 1.024842893562266 	 Accuracy: 0.4032258064516129
Delta: 0.0003726774934431601 	  Loss: 1.0248416772748479 	 Accuracy: 0.4032258064516129
Delta: 0.04278147932375401 	  Loss: 1.0628699543959828 	 Accuracy: 0.5161290322580645
Delta: 0.030954280050357844 	  Loss: 1.055528662428335 	 Accuracy: 0.5483870967741935
Delta: 0.02258177071776446 	  Loss: 1.0506550519849605 	 Accuracy: 0.6451612903225806
Delta: 0.021250173513083996 	  Loss: 1.0478764101424103 	 Accuracy: 0.6451612903225806
Delta: 0.020319036484363985 	  Loss: 1.0452332543875615 	 Accuracy: 0.6774193548387096
Delta: 0.01909485336320034 	  Loss: 1.0425444777218662 	 Accuracy: 0.7096774193548387
Delta: 0.017659371879546155 	  Loss: 1.0399782762197158 	 Accuracy: 0.7096774193548387
Delta: 0.017064113053273645 	  Loss: 1.037602024840267 	 Accuracy: 0.6935483870967742
Delta: 0.0158951900850652 	  Loss: 1.0354386933327455 	 Accuracy: 0.6935483870967742
Delta: 0.01472334704982434 	  Loss: 1.0330970579141283 	 Accuracy: 0.6612903225806451
Delta: 0.015128710912035501 	  Loss: 1.0311092681112228 	 Accuracy: 0.6290322580645161
Delta: 0.013985978380874647 	  Loss: 1.0293447319387852 	 Accuracy: 0.6451612903225806
Delta: 0.013655305842448414 	  Loss: 1.0279459151404877 	 Accuracy: 0.6290322580645161
Delta: 0.013591245271588271 	  Loss: 1.0266963405245355 	 Accuracy: 0.6129032258064516
Delta: 0.011423665215059654 	  Loss: 1.025802863990644 	 Accuracy: 0.6290322580645161
Delta: 0.011242726852350764 	  Loss: 1.0251377674127675 	 Accuracy: 0.6290322580645161
Delta: 0.01088858929665646 	  Loss: 1.0244417524389098 	 Accuracy: 0.6290322580645161
Delta: 0.008810239168611131 	  Loss: 1.0239623650716525 	 Accuracy: 0.6290322580645161
Delta: 0.008174611456924122 	  Loss: 1.023539462538889 	 Accuracy: 0.6290322580645161
Delta: 0.008165689743996824 	  Loss: 1.02308851578711 	 Accuracy: 0.6290322580645161
Delta: 0.007138571495680034 	  Loss: 1.022668747262055 	 Accuracy: 0.6290322580645161
Delta: 0.0075653619096636765 	  Loss: 1.0223138517123491 	 Accuracy: 0.6290322580645161
Delta: 0.007528686540104702 	  Loss: 1.0219492332291087 	 Accuracy: 0.6290322580645161
Delta: 0.007382280507844656 	  Loss: 1.0216218029190292 	 Accuracy: 0.6290322580645161
Delta: 0.005642129882218372 	  Loss: 1.021357100489129 	 Accuracy: 0.6129032258064516
Delta: 0.0059204878540384705 	  Loss: 1.021115347944499 	 Accuracy: 0.6129032258064516
Delta: 0.004994174481860211 	  Loss: 1.0209345697232322 	 Accuracy: 0.6129032258064516
Delta: 0.004135168622114238 	  Loss: 1.0208022193770698 	 Accuracy: 0.6129032258064516
Delta: 0.003912986079228607 	  Loss: 1.0207072502861085 	 Accuracy: 0.6129032258064516
Delta: 0.0038180653941742157 	  Loss: 1.0206153957157034 	 Accuracy: 0.5806451612903226
Delta: 0.004683320610171149 	  Loss: 1.0205417038689655 	 Accuracy: 0.5806451612903226
Delta: 0.004467496248554904 	  Loss: 1.0204538034898478 	 Accuracy: 0.5806451612903226
Delta: 0.0033656387345335414 	  Loss: 1.0203586437182812 	 Accuracy: 0.5806451612903226
Delta: 0.0034956913669758464 	  Loss: 1.0202676969676854 	 Accuracy: 0.5806451612903226
Delta: 0.0030774805442257774 	  Loss: 1.0202199918804529 	 Accuracy: 0.5806451612903226
Delta: 0.0037556996759351012 	  Loss: 1.0201573627246752 	 Accuracy: 0.5806451612903226
Delta: 0.0034366385496533876 	  Loss: 1.0201111027012204 	 Accuracy: 0.5806451612903226
Delta: 0.004347447473198982 	  Loss: 1.0200687313974246 	 Accuracy: 0.5806451612903226
Delta: 0.004046510541969773 	  Loss: 1.0200437749351738 	 Accuracy: 0.5806451612903226
Delta: 0.0031220310766284813 	  Loss: 1.0200326239498065 	 Accuracy: 0.5806451612903226
Delta: 0.0023263092500151565 	  Loss: 1.0200126184400347 	 Accuracy: 0.5806451612903226
Delta: 0.0029968341921771 	  Loss: 1.0199847909606963 	 Accuracy: 0.5806451612903226
Delta: 0.0025233472234004605 	  Loss: 1.0199775938476652 	 Accuracy: 0.5806451612903226
Delta: 0.002450101160720489 	  Loss: 1.0199729015637933 	 Accuracy: 0.5806451612903226
Delta: 0.0020638873440437934 	  Loss: 1.0199633892262912 	 Accuracy: 0.5806451612903226
Delta: 0.0030074308930846064 	  Loss: 1.0199498962611093 	 Accuracy: 0.5806451612903226
Delta: 0.002789216713982831 	  Loss: 1.0198933540810473 	 Accuracy: 0.5806451612903226
Delta: 0.0020552333673669455 	  Loss: 1.0198660498707945 	 Accuracy: 0.5806451612903226
Delta: 0.0015935139327282826 	  Loss: 1.0198471588445597 	 Accuracy: 0.5806451612903226
Delta: 0.0011046748120738883 	  Loss: 1.0198432669895254 	 Accuracy: 0.5806451612903226
Delta: 0.0015433486592195554 	  Loss: 1.0198250475369153 	 Accuracy: 0.5806451612903226

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0015087981733247881 	  Loss: 1.0198074246722078 	 Accuracy: 0.5806451612903226
Delta: 0.001051631663777336 	  Loss: 1.0197827144039855 	 Accuracy: 0.5806451612903226
Delta: 0.0008549233313116429 	  Loss: 1.0197640142658957 	 Accuracy: 0.5806451612903226
Delta: 0.0009677726313131661 	  Loss: 1.0197485359595524 	 Accuracy: 0.5806451612903226
Delta: 0.00106421944152789 	  Loss: 1.0197366188242818 	 Accuracy: 0.5806451612903226
Delta: 0.0010825021175918362 	  Loss: 1.0197414264616629 	 Accuracy: 0.5806451612903226
Delta: 0.001091871738340018 	  Loss: 1.0197396894053465 	 Accuracy: 0.5806451612903226
Delta: 0.001016422869391547 	  Loss: 1.0197181709441443 	 Accuracy: 0.5806451612903226
Delta: 0.0009599827107271506 	  Loss: 1.0197026167001328 	 Accuracy: 0.5806451612903226
Delta: 0.0007950640925560006 	  Loss: 1.0196933139095683 	 Accuracy: 0.5806451612903226
Delta: 0.0002863731975095828 	  Loss: 1.0196798998236716 	 Accuracy: 0.5806451612903226
Delta: 0.0002594045783474038 	  Loss: 1.0196730480623644 	 Accuracy: 0.5806451612903226
Delta: 0.0003370669523161642 	  Loss: 1.0196672443107189 	 Accuracy: 0.5806451612903226
Delta: 0.0004194950327466014 	  Loss: 1.0196599940551205 	 Accuracy: 0.5806451612903226
Delta: 0.0007537119844096418 	  Loss: 1.0196552745001999 	 Accuracy: 0.5806451612903226
Delta: 0.0005047839253699113 	  Loss: 1.0196512699440357 	 Accuracy: 0.5806451612903226
Delta: 0.0004716130716183386 	  Loss: 1.0196494226560948 	 Accuracy: 0.5806451612903226
Delta: 0.00029054492589225637 	  Loss: 1.0196451813439036 	 Accuracy: 0.5806451612903226
Delta: 2.508897573755269e-05 	  Loss: 1.0196413705645 	 Accuracy: 0.5806451612903226
Delta: 1.8899345984496637e-05 	  Loss: 1.019639145732579 	 Accuracy: 0.5806451612903226
Delta: 3.366670957470231e-05 	  Loss: 1.0196371210054314 	 Accuracy: 0.5806451612903226
Delta: 1.662132510880274e-05 	  Loss: 1.019635250298298 	 Accuracy: 0.5806451612903226
Delta: 4.9501819503522726e-05 	  Loss: 1.019633439442388 	 Accuracy: 0.5806451612903226
Delta: 6.0357077397390565e-05 	  Loss: 1.0196317658358067 	 Accuracy: 0.5806451612903226
Delta: 1.3873565217654368e-05 	  Loss: 1.0196302890407176 	 Accuracy: 0.5806451612903226
Delta: 1.2085993295682842e-05 	  Loss: 1.019628784590802 	 Accuracy: 0.5806451612903226
Delta: 1.0964506815648841e-05 	  Loss: 1.0196273997811411 	 Accuracy: 0.5806451612903226
Delta: 9.887830076990232e-06 	  Loss: 1.0196261606619372 	 Accuracy: 0.5806451612903226
Delta: 8.738172183381527e-06 	  Loss: 1.0196250570160075 	 Accuracy: 0.5806451612903226
Delta: 9.238111680526432e-06 	  Loss: 1.0196239243693443 	 Accuracy: 0.5806451612903226
Delta: 8.0117524601918e-06 	  Loss: 1.0196229189375563 	 Accuracy: 0.5806451612903226
Delta: 7.309037338235826e-06 	  Loss: 1.0196219784769451 	 Accuracy: 0.5806451612903226
Delta: 6.802406116982186e-06 	  Loss: 1.0196210680216478 	 Accuracy: 0.5806451612903226
Delta: 7.3777672011222055e-06 	  Loss: 1.0196201662333193 	 Accuracy: 0.5806451612903226
Delta: 6.368908446126526e-06 	  Loss: 1.0196193195952596 	 Accuracy: 0.5806451612903226
Delta: 6.222799092486333e-06 	  Loss: 1.0196185253421783 	 Accuracy: 0.5806451612903226
Delta: 5.881963145652269e-06 	  Loss: 1.0196177643247553 	 Accuracy: 0.5806451612903226
Delta: 5.887648905135044e-06 	  Loss: 1.0196170229313928 	 Accuracy: 0.5806451612903226
Delta: 5.006783987261839e-06 	  Loss: 1.0196163444097164 	 Accuracy: 0.5806451612903226
Delta: 4.796841732989223e-06 	  Loss: 1.019615739016692 	 Accuracy: 0.5806451612903226
Delta: 4.820127337957025e-06 	  Loss: 1.0196150909077428 	 Accuracy: 0.5806451612903226
Delta: 4.839784943001075e-06 	  Loss: 1.0196144729115257 	 Accuracy: 0.5806451612903226
Delta: 4.043172251667502e-06 	  Loss: 1.0196139218147335 	 Accuracy: 0.5806451612903226
Delta: 4.08221372802402e-06 	  Loss: 1.0196133846523057 	 Accuracy: 0.5806451612903226
Delta: 3.7532547752946303e-06 	  Loss: 1.0196128583119823 	 Accuracy: 0.5806451612903226
Delta: 3.7156970188236835e-06 	  Loss: 1.0196123679490445 	 Accuracy: 0.5806451612903226
Delta: 3.602960166927489e-06 	  Loss: 1.01961187393219 	 Accuracy: 0.5806451612903226
Delta: 3.312295192671511e-06 	  Loss: 1.0196114566083465 	 Accuracy: 0.5806451612903226
Delta: 3.2684693300533364e-06 	  Loss: 1.0196109979641297 	 Accuracy: 0.5806451612903226
Delta: 0.03895610619868613 	  Loss: 1.083412904162329 	 Accuracy: 0.5161290322580645
Delta: 0.031072312418617652 	  Loss: 1.0741672061036716 	 Accuracy: 0.5645161290322581
Delta: 0.02511678351360698 	  Loss: 1.0687881819028784 	 Accuracy: 0.5806451612903226
Delta: 0.021217862332630007 	  Loss: 1.0658338298575885 	 Accuracy: 0.5645161290322581
Delta: 0.01956777612614091 	  Loss: 1.06322751677728 	 Accuracy: 0.532258064516129
Delta: 0.01973609650015267 	  Loss: 1.0600879305804805 	 Accuracy: 0.5483870967741935
Delta: 0.022367361490876293 	  Loss: 1.0562606935130594 	 Accuracy: 0.5
Delta: 0.021515145728264722 	  Loss: 1.0520433786944787 	 Accuracy: 0.43548387096774194
Delta: 0.01686702703259954 	  Loss: 1.0491171884761232 	 Accuracy: 0.45161290322580644
Delta: 0.013558048186983706 	  Loss: 1.0472049943055293 	 Accuracy: 0.4838709677419355
Delta: 0.013377574619102278 	  Loss: 1.0455438238971042 	 Accuracy: 0.4838709677419355
Delta: 0.011635728936481567 	  Loss: 1.044120888950691 	 Accuracy: 0.46774193548387094
Delta: 0.01090900849840443 	  Loss: 1.042870270784492 	 Accuracy: 0.46774193548387094
Delta: 0.010542540950588847 	  Loss: 1.0418846030083078 	 Accuracy: 0.4838709677419355
Delta: 0.01036094896711718 	  Loss: 1.041018921816264 	 Accuracy: 0.4838709677419355
Delta: 0.009172884064851242 	  Loss: 1.0402819991159937 	 Accuracy: 0.46774193548387094
Delta: 0.008193065118288096 	  Loss: 1.0395843146586665 	 Accuracy: 0.46774193548387094
Delta: 0.006557767578630504 	  Loss: 1.0391219972000842 	 Accuracy: 0.46774193548387094
Delta: 0.006871941757259997 	  Loss: 1.0387265109148425 	 Accuracy: 0.46774193548387094
Delta: 0.0052101391252141385 	  Loss: 1.0384251093586745 	 Accuracy: 0.46774193548387094
Delta: 0.00432954304986718 	  Loss: 1.0382113737562029 	 Accuracy: 0.46774193548387094
Delta: 0.0031848686702695885 	  Loss: 1.0380674030854162 	 Accuracy: 0.46774193548387094
Delta: 0.004084301845584258 	  Loss: 1.0379528422225106 	 Accuracy: 0.46774193548387094
Delta: 0.005421855234426899 	  Loss: 1.037823095073108 	 Accuracy: 0.46774193548387094
Delta: 0.0039852974841250695 	  Loss: 1.0376780928620517 	 Accuracy: 0.46774193548387094
Delta: 0.0043452230894193795 	  Loss: 1.0375654544588224 	 Accuracy: 0.46774193548387094
Delta: 0.004008757891972643 	  Loss: 1.037474905323926 	 Accuracy: 0.46774193548387094
Delta: 0.003584215708592894 	  Loss: 1.037392214199728 	 Accuracy: 0.46774193548387094
Delta: 0.0034884439038281195 	  Loss: 1.0373056796849776 	 Accuracy: 0.46774193548387094
Delta: 0.0029390468410000706 	  Loss: 1.0372432372552502 	 Accuracy: 0.46774193548387094
Delta: 0.0027975656194219388 	  Loss: 1.0372079556413176 	 Accuracy: 0.46774193548387094
Delta: 0.002576533828641769 	  Loss: 1.0371401485154674 	 Accuracy: 0.46774193548387094
Delta: 0.001981234756712401 	  Loss: 1.0370888019349058 	 Accuracy: 0.46774193548387094
Delta: 0.0025138550657060553 	  Loss: 1.0370518914345257 	 Accuracy: 0.46774193548387094
Delta: 0.0035493941425380287 	  Loss: 1.037008608874682 	 Accuracy: 0.46774193548387094
Delta: 0.0037954814733828527 	  Loss: 1.0369498621619322 	 Accuracy: 0.46774193548387094
Delta: 0.0035718349136266716 	  Loss: 1.0368869562515606 	 Accuracy: 0.46774193548387094
Delta: 0.0022080543963453997 	  Loss: 1.036816270375632 	 Accuracy: 0.46774193548387094
Delta: 0.0021841950558722893 	  Loss: 1.0367827593022232 	 Accuracy: 0.46774193548387094
Delta: 0.0018883552493633127 	  Loss: 1.0367517727532838 	 Accuracy: 0.46774193548387094
Delta: 0.002322517280262307 	  Loss: 1.0367167445154668 	 Accuracy: 0.46774193548387094
Delta: 0.002753956851456285 	  Loss: 1.0366970288308819 	 Accuracy: 0.46774193548387094
Delta: 0.002399343466965345 	  Loss: 1.0366839324700874 	 Accuracy: 0.46774193548387094
Delta: 0.0028588489598397244 	  Loss: 1.036687917460247 	 Accuracy: 0.46774193548387094

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.002963504787137763 	  Loss: 1.0366915757801052 	 Accuracy: 0.46774193548387094
Delta: 0.002716788428349166 	  Loss: 1.036706148742524 	 Accuracy: 0.46774193548387094
Delta: 0.003081000115273201 	  Loss: 1.036698553346416 	 Accuracy: 0.46774193548387094
Delta: 0.00297162400664558 	  Loss: 1.0366678159100386 	 Accuracy: 0.46774193548387094
Delta: 0.003224362519013488 	  Loss: 1.0366468732683591 	 Accuracy: 0.46774193548387094
Delta: 0.0026544101277238786 	  Loss: 1.036627373289084 	 Accuracy: 0.46774193548387094
Delta: 0.0021619769755537818 	  Loss: 1.0366113359951195 	 Accuracy: 0.46774193548387094
Delta: 0.00180654862892283 	  Loss: 1.0365874054979032 	 Accuracy: 0.46774193548387094
Delta: 0.001119540192559442 	  Loss: 1.0365744365116196 	 Accuracy: 0.46774193548387094
Delta: 0.0014813339247893463 	  Loss: 1.0365676595861808 	 Accuracy: 0.46774193548387094
Delta: 0.001684786076914321 	  Loss: 1.0365616335389163 	 Accuracy: 0.46774193548387094
Delta: 0.002179353616416167 	  Loss: 1.0365653351751853 	 Accuracy: 0.46774193548387094
Delta: 0.0017840124228611827 	  Loss: 1.0365491054205056 	 Accuracy: 0.46774193548387094
Delta: 0.0014033345189145637 	  Loss: 1.036533291678618 	 Accuracy: 0.46774193548387094
Delta: 0.0020635081372893105 	  Loss: 1.036527043126188 	 Accuracy: 0.46774193548387094
Delta: 0.001514492776864848 	  Loss: 1.0365208413817757 	 Accuracy: 0.46774193548387094
Delta: 0.001551253423631801 	  Loss: 1.0365209968905664 	 Accuracy: 0.46774193548387094
Delta: 0.0012534221497000468 	  Loss: 1.0365273068653758 	 Accuracy: 0.46774193548387094
Delta: 0.0015299361855299035 	  Loss: 1.0365330616549815 	 Accuracy: 0.46774193548387094
Delta: 0.0009960051964248698 	  Loss: 1.036546171511834 	 Accuracy: 0.46774193548387094
Delta: 0.001037439967579624 	  Loss: 1.0365383356122608 	 Accuracy: 0.46774193548387094
Delta: 0.0018440651799692665 	  Loss: 1.0365354158012976 	 Accuracy: 0.46774193548387094
Delta: 0.0011267505443964228 	  Loss: 1.0365486797975505 	 Accuracy: 0.46774193548387094
Delta: 0.0009544638659001068 	  Loss: 1.0365531073337328 	 Accuracy: 0.46774193548387094
Delta: 0.0009693276353476959 	  Loss: 1.0365547960401909 	 Accuracy: 0.46774193548387094
Delta: 0.0013869843440564521 	  Loss: 1.0365549676312407 	 Accuracy: 0.46774193548387094
Delta: 0.001962394509618052 	  Loss: 1.0365513531782262 	 Accuracy: 0.46774193548387094
Delta: 0.002505386730224784 	  Loss: 1.0365535773627774 	 Accuracy: 0.46774193548387094
Delta: 0.0019682112404704605 	  Loss: 1.0365441855903912 	 Accuracy: 0.46774193548387094
Delta: 0.0017536447136372504 	  Loss: 1.0365485042161118 	 Accuracy: 0.46774193548387094
Delta: 0.0011580250576598986 	  Loss: 1.036548396445836 	 Accuracy: 0.46774193548387094
Delta: 0.0007203521288989578 	  Loss: 1.0365460887479467 	 Accuracy: 0.46774193548387094
Delta: 0.0005221003912280352 	  Loss: 1.0365498182340969 	 Accuracy: 0.46774193548387094
Delta: 0.00030523372015395315 	  Loss: 1.0365518793904467 	 Accuracy: 0.46774193548387094
Delta: 0.0006843260612536421 	  Loss: 1.036551310905642 	 Accuracy: 0.46774193548387094
Delta: 0.00048770201161138776 	  Loss: 1.0365509052994828 	 Accuracy: 0.46774193548387094
Delta: 0.0003077585727888399 	  Loss: 1.0365480658237556 	 Accuracy: 0.46774193548387094
Delta: 0.00047506968114826946 	  Loss: 1.0365485255500415 	 Accuracy: 0.46774193548387094
Delta: 0.0003755168425336843 	  Loss: 1.0365491351919385 	 Accuracy: 0.46774193548387094
Delta: 0.0005040203626844376 	  Loss: 1.0365469572629835 	 Accuracy: 0.46774193548387094
Delta: 0.0008796485794461247 	  Loss: 1.0365471084818494 	 Accuracy: 0.46774193548387094
Delta: 0.0006213211644717259 	  Loss: 1.036546880275292 	 Accuracy: 0.46774193548387094
Delta: 0.0008543666173519699 	  Loss: 1.0365465697408855 	 Accuracy: 0.46774193548387094
Delta: 0.0008538574385715055 	  Loss: 1.036546024127152 	 Accuracy: 0.46774193548387094
Delta: 0.0004618588641601301 	  Loss: 1.0365472755697647 	 Accuracy: 0.46774193548387094
Delta: 0.0003783333606710366 	  Loss: 1.0365469888051428 	 Accuracy: 0.46774193548387094
Delta: 0.00035309476650178487 	  Loss: 1.0365445187252549 	 Accuracy: 0.46774193548387094
Delta: 0.00025347120653353166 	  Loss: 1.0365452578267729 	 Accuracy: 0.46774193548387094
Delta: 3.819482473767421e-05 	  Loss: 1.0365458325378043 	 Accuracy: 0.46774193548387094
Delta: 2.054813659697005e-06 	  Loss: 1.0365450730097212 	 Accuracy: 0.46774193548387094
Delta: 1.3189927265528756e-06 	  Loss: 1.0365442399717981 	 Accuracy: 0.46774193548387094
Delta: 1.2437550996435207e-06 	  Loss: 1.036543410932438 	 Accuracy: 0.46774193548387094
Delta: 1.1924688163245582e-06 	  Loss: 1.0365426503641304 	 Accuracy: 0.46774193548387094
Delta: 1.1116830155823063e-06 	  Loss: 1.0365418475397588 	 Accuracy: 0.46774193548387094
Delta: 1.0452855297068093e-06 	  Loss: 1.0365410582685337 	 Accuracy: 0.46774193548387094
Delta: 1.013021002895524e-06 	  Loss: 1.0365403542892744 	 Accuracy: 0.46774193548387094
Delta: 0.039907603314239676 	  Loss: 1.0797234643013875 	 Accuracy: 0.4603174603174603
Delta: 0.032241353977483594 	  Loss: 1.0667028153899385 	 Accuracy: 0.5714285714285714
Delta: 0.024433280311889724 	  Loss: 1.0614874379896753 	 Accuracy: 0.47619047619047616
Delta: 0.022522389942085497 	  Loss: 1.0575871340198608 	 Accuracy: 0.47619047619047616
Delta: 0.022777864809644357 	  Loss: 1.0537914377988429 	 Accuracy: 0.4444444444444444
Delta: 0.01961958534404716 	  Loss: 1.0504224470654533 	 Accuracy: 0.42857142857142855
Delta: 0.017574161303061143 	  Loss: 1.0477831322938458 	 Accuracy: 0.42857142857142855
Delta: 0.016183065248490044 	  Loss: 1.0454163818611488 	 Accuracy: 0.42857142857142855
Delta: 0.015886548924328628 	  Loss: 1.0433416795600792 	 Accuracy: 0.4444444444444444
Delta: 0.014527418630382684 	  Loss: 1.0415526830416846 	 Accuracy: 0.4126984126984127
Delta: 0.01179808137666257 	  Loss: 1.040032744065772 	 Accuracy: 0.3968253968253968
Delta: 0.008592435761345805 	  Loss: 1.0389690615988978 	 Accuracy: 0.3968253968253968
Delta: 0.007044948804636426 	  Loss: 1.038226814785539 	 Accuracy: 0.3968253968253968
Delta: 0.0062865710489250545 	  Loss: 1.0376289252672237 	 Accuracy: 0.3968253968253968
Delta: 0.005964332046864472 	  Loss: 1.0370440875192926 	 Accuracy: 0.4126984126984127
Delta: 0.0061587032083358535 	  Loss: 1.0365038137729323 	 Accuracy: 0.4126984126984127
Delta: 0.005709767877820813 	  Loss: 1.0360342138634175 	 Accuracy: 0.3968253968253968
Delta: 0.0056115528569697665 	  Loss: 1.0356506432809338 	 Accuracy: 0.3968253968253968
Delta: 0.00529026045922281 	  Loss: 1.0353525159328205 	 Accuracy: 0.3968253968253968
Delta: 0.00461609686704878 	  Loss: 1.0350370793471753 	 Accuracy: 0.3968253968253968
Delta: 0.005095359169296202 	  Loss: 1.034788236397466 	 Accuracy: 0.3968253968253968
Delta: 0.005374735436385876 	  Loss: 1.0345753356282015 	 Accuracy: 0.3968253968253968
Delta: 0.0060960441969722425 	  Loss: 1.0343733140792795 	 Accuracy: 0.3968253968253968
Delta: 0.005123002200729632 	  Loss: 1.0341949195413 	 Accuracy: 0.3968253968253968
Delta: 0.0052800583812438 	  Loss: 1.034060889409078 	 Accuracy: 0.3968253968253968
Delta: 0.004362896333325862 	  Loss: 1.0339260409146531 	 Accuracy: 0.3968253968253968
Delta: 0.004925261800010905 	  Loss: 1.0338310226242533 	 Accuracy: 0.3968253968253968
Delta: 0.005111803168725989 	  Loss: 1.0337195853280177 	 Accuracy: 0.3968253968253968
Delta: 0.005099621770903029 	  Loss: 1.0336067078789757 	 Accuracy: 0.38095238095238093
Delta: 0.004912751797049943 	  Loss: 1.0334972694829272 	 Accuracy: 0.38095238095238093
Delta: 0.004070921542479898 	  Loss: 1.0333604110974637 	 Accuracy: 0.38095238095238093
Delta: 0.003995538393277615 	  Loss: 1.0332639910271717 	 Accuracy: 0.38095238095238093
Delta: 0.00408981372322326 	  Loss: 1.0331830962889854 	 Accuracy: 0.38095238095238093
Delta: 0.003515108703372013 	  Loss: 1.0330942062358797 	 Accuracy: 0.38095238095238093
Delta: 0.0026715274505395292 	  Loss: 1.0330251888308593 	 Accuracy: 0.38095238095238093
Delta: 0.0033448446979577563 	  Loss: 1.0329465916944272 	 Accuracy: 0.38095238095238093
Delta: 0.0038524369290902066 	  Loss: 1.0328797961235137 	 Accuracy: 0.38095238095238093
Delta: 0.003993299377137793 	  Loss: 1.0327773927637722 	 Accuracy: 0.38095238095238093
Delta: 0.00366455651030782 	  Loss: 1.0326579884626819 	 Accuracy: 0.38095238095238093
Delta: 0.003001040505537087 	  Loss: 1.0325654088079714 	 Accuracy: 0.38095238095238093
Delta: 0.0024512042589123094 	  Loss: 1.0325005282916533 	 Accuracy: 0.38095238095238093
Delta: 0.0028164499798416258 	  Loss: 1.0324630550815377 	 Accuracy: 0.38095238095238093
Delta: 0.003350409415700467 	  Loss: 1.0324225203642785 	 Accuracy: 0.38095238095238093

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0027616280942511936 	  Loss: 1.0323809935515098 	 Accuracy: 0.38095238095238093
Delta: 0.0027752371755475035 	  Loss: 1.0323459767118204 	 Accuracy: 0.38095238095238093
Delta: 0.0025664365821896724 	  Loss: 1.0323048906553214 	 Accuracy: 0.38095238095238093
Delta: 0.0027718697043995506 	  Loss: 1.0322935606050856 	 Accuracy: 0.38095238095238093
Delta: 0.0028720852487608374 	  Loss: 1.032288176606373 	 Accuracy: 0.38095238095238093
Delta: 0.00294729904008777 	  Loss: 1.0322696695459388 	 Accuracy: 0.38095238095238093
Delta: 0.002526334350891474 	  Loss: 1.0322691845735341 	 Accuracy: 0.38095238095238093
Delta: 0.0014390733319180084 	  Loss: 1.0322559080264637 	 Accuracy: 0.38095238095238093
Delta: 0.0015808951040680779 	  Loss: 1.0322414592377043 	 Accuracy: 0.38095238095238093
Delta: 0.0017754119968239074 	  Loss: 1.0322320055322662 	 Accuracy: 0.38095238095238093
Delta: 0.0013297598412080989 	  Loss: 1.0322351979816218 	 Accuracy: 0.38095238095238093
Delta: 0.0015780071694497639 	  Loss: 1.0322397935036802 	 Accuracy: 0.38095238095238093
Delta: 0.0015176188695565733 	  Loss: 1.0322547113011085 	 Accuracy: 0.38095238095238093
Delta: 0.0013034161635271724 	  Loss: 1.032257706250258 	 Accuracy: 0.38095238095238093
Delta: 0.001199962274726397 	  Loss: 1.0322526591464483 	 Accuracy: 0.38095238095238093
Delta: 0.0013163724471328385 	  Loss: 1.0322407870491115 	 Accuracy: 0.38095238095238093
Delta: 0.0023337054256487083 	  Loss: 1.0322241138856452 	 Accuracy: 0.38095238095238093
Delta: 0.0018658934549122199 	  Loss: 1.0321934182937715 	 Accuracy: 0.38095238095238093
Delta: 0.0012699575849906078 	  Loss: 1.032182728817399 	 Accuracy: 0.38095238095238093
Delta: 0.0008649055923626405 	  Loss: 1.032177887657363 	 Accuracy: 0.38095238095238093
Delta: 0.0006326018608057106 	  Loss: 1.032179686545848 	 Accuracy: 0.38095238095238093
Delta: 0.0011476036726226961 	  Loss: 1.0321807337787305 	 Accuracy: 0.38095238095238093
Delta: 0.0004325362249926382 	  Loss: 1.0321866939577324 	 Accuracy: 0.38095238095238093
Delta: 0.0008086017443057561 	  Loss: 1.0321836696582263 	 Accuracy: 0.38095238095238093
Delta: 0.0007986706226616215 	  Loss: 1.0321804163442565 	 Accuracy: 0.38095238095238093
Delta: 0.0007400036676244886 	  Loss: 1.032171066282387 	 Accuracy: 0.38095238095238093
Delta: 0.0011241509821564553 	  Loss: 1.0321648333491191 	 Accuracy: 0.36507936507936506
Delta: 0.0011941377139514714 	  Loss: 1.0321574561207396 	 Accuracy: 0.36507936507936506
Delta: 0.0014516343356923895 	  Loss: 1.0321496771701275 	 Accuracy: 0.36507936507936506
Delta: 0.00090832185264996 	  Loss: 1.0321421390416434 	 Accuracy: 0.36507936507936506
Delta: 0.0005756369123513004 	  Loss: 1.0321380460643885 	 Accuracy: 0.36507936507936506
Delta: 0.0009577784922036289 	  Loss: 1.0321339483099004 	 Accuracy: 0.36507936507936506
Delta: 0.0007539858246658751 	  Loss: 1.0321350083118297 	 Accuracy: 0.36507936507936506
Delta: 0.0011434825510992102 	  Loss: 1.0321326347073714 	 Accuracy: 0.36507936507936506
Delta: 0.0009665648331218413 	  Loss: 1.0321310540850752 	 Accuracy: 0.36507936507936506
Delta: 0.0006146525918704242 	  Loss: 1.0321298660684222 	 Accuracy: 0.36507936507936506
Delta: 0.0003906323323346026 	  Loss: 1.0321286210543068 	 Accuracy: 0.36507936507936506
Delta: 0.0006910822601386744 	  Loss: 1.0321285401127345 	 Accuracy: 0.36507936507936506
converged at iter  80
Delta: 0.03860359056600685 	  Loss: 1.069058597221777 	 Accuracy: 0.47619047619047616
Delta: 0.03376527126212224 	  Loss: 1.0563254492321232 	 Accuracy: 0.38095238095238093
Delta: 0.0280062446255802 	  Loss: 1.0480771849877284 	 Accuracy: 0.5079365079365079
Delta: 0.02202846795001671 	  Loss: 1.0435009362578056 	 Accuracy: 0.5079365079365079
Delta: 0.019164980219451847 	  Loss: 1.04052087485885 	 Accuracy: 0.49206349206349204
Delta: 0.01825521450156015 	  Loss: 1.038065020119803 	 Accuracy: 0.4603174603174603
Delta: 0.01691496105245625 	  Loss: 1.0358740628536762 	 Accuracy: 0.4603174603174603
Delta: 0.014741014737504528 	  Loss: 1.034192680371817 	 Accuracy: 0.47619047619047616
Delta: 0.013910101846133099 	  Loss: 1.032838034607971 	 Accuracy: 0.49206349206349204
Delta: 0.011976440347114077 	  Loss: 1.0316843604122046 	 Accuracy: 0.5079365079365079
Delta: 0.011270910766306066 	  Loss: 1.0306664643351862 	 Accuracy: 0.5079365079365079
Delta: 0.012704515014623528 	  Loss: 1.0297354909896157 	 Accuracy: 0.5079365079365079
Delta: 0.012681291628016008 	  Loss: 1.0286853601519863 	 Accuracy: 0.5079365079365079
Delta: 0.012162053509754751 	  Loss: 1.0276690607680647 	 Accuracy: 0.5079365079365079
Delta: 0.010709726337396154 	  Loss: 1.0267737985400403 	 Accuracy: 0.5238095238095238
Delta: 0.00885032871220678 	  Loss: 1.0260124448916044 	 Accuracy: 0.5238095238095238
Delta: 0.008260642465897878 	  Loss: 1.0254198725620463 	 Accuracy: 0.5238095238095238
Delta: 0.009188434019811249 	  Loss: 1.0248531893004889 	 Accuracy: 0.5238095238095238
Delta: 0.008691095813291642 	  Loss: 1.0243079249143956 	 Accuracy: 0.5238095238095238
Delta: 0.00812693002368498 	  Loss: 1.0238463167289498 	 Accuracy: 0.5238095238095238
Delta: 0.006723011973043033 	  Loss: 1.0233888738753731 	 Accuracy: 0.5079365079365079
Delta: 0.007335623089779662 	  Loss: 1.0230526867298548 	 Accuracy: 0.5079365079365079
Delta: 0.007576941321390317 	  Loss: 1.022687922833807 	 Accuracy: 0.5079365079365079
Delta: 0.0063994289059223055 	  Loss: 1.0223667818581683 	 Accuracy: 0.5079365079365079
Delta: 0.006630037746671304 	  Loss: 1.0221471132334328 	 Accuracy: 0.49206349206349204
Delta: 0.006244004646760404 	  Loss: 1.0219011817554953 	 Accuracy: 0.49206349206349204
Delta: 0.006185152429463122 	  Loss: 1.0216476403047476 	 Accuracy: 0.49206349206349204
Delta: 0.005140116289426956 	  Loss: 1.0213623757881658 	 Accuracy: 0.49206349206349204
Delta: 0.004685412179665727 	  Loss: 1.021182317551141 	 Accuracy: 0.49206349206349204
Delta: 0.0035986439030135076 	  Loss: 1.0210214510946574 	 Accuracy: 0.49206349206349204
Delta: 0.005537132927656034 	  Loss: 1.0208676559595986 	 Accuracy: 0.49206349206349204
Delta: 0.005246303077555871 	  Loss: 1.0206904673192323 	 Accuracy: 0.49206349206349204
Delta: 0.003926205150429807 	  Loss: 1.0205365276979295 	 Accuracy: 0.49206349206349204
Delta: 0.0029572108360545416 	  Loss: 1.0204215686862796 	 Accuracy: 0.49206349206349204
Delta: 0.0026520363897135 	  Loss: 1.0203297792393058 	 Accuracy: 0.49206349206349204
Delta: 0.002912135441461765 	  Loss: 1.0202358608269784 	 Accuracy: 0.49206349206349204
Delta: 0.002948084457983677 	  Loss: 1.0201547315081447 	 Accuracy: 0.49206349206349204
Delta: 0.003955099182215941 	  Loss: 1.0200733742369081 	 Accuracy: 0.49206349206349204
Delta: 0.0031197653685652985 	  Loss: 1.0200194491489356 	 Accuracy: 0.49206349206349204
Delta: 0.0029479000345638386 	  Loss: 1.0199443159030332 	 Accuracy: 0.49206349206349204
Delta: 0.003741081698896814 	  Loss: 1.0198800269979473 	 Accuracy: 0.49206349206349204
Delta: 0.0033668544914531324 	  Loss: 1.019796572859104 	 Accuracy: 0.49206349206349204
Delta: 0.004271556714718861 	  Loss: 1.019738578693421 	 Accuracy: 0.49206349206349204
Delta: 0.0035843909889941967 	  Loss: 1.0196623643653802 	 Accuracy: 0.49206349206349204
Delta: 0.002122638157949058 	  Loss: 1.019618312404484 	 Accuracy: 0.49206349206349204
Delta: 0.0014480362045900907 	  Loss: 1.0195891424553574 	 Accuracy: 0.49206349206349204
Delta: 0.002121450246894445 	  Loss: 1.0195602632147898 	 Accuracy: 0.49206349206349204
Delta: 0.0017523743386709438 	  Loss: 1.0195218690930403 	 Accuracy: 0.49206349206349204
Delta: 0.002486084173959297 	  Loss: 1.019483848888497 	 Accuracy: 0.49206349206349204
Delta: 0.0023019019713208444 	  Loss: 1.019452978198224 	 Accuracy: 0.49206349206349204
Delta: 0.0018852496380140128 	  Loss: 1.0194428928209827 	 Accuracy: 0.49206349206349204

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0015621382723454654 	  Loss: 1.0194263502690848 	 Accuracy: 0.49206349206349204
Delta: 0.0011058389314356134 	  Loss: 1.019415200454516 	 Accuracy: 0.49206349206349204
Delta: 0.0012229769477964652 	  Loss: 1.0194052214190974 	 Accuracy: 0.49206349206349204
Delta: 0.0016873831627645618 	  Loss: 1.019398918207709 	 Accuracy: 0.49206349206349204
Delta: 0.0018797628363210156 	  Loss: 1.0193874951886817 	 Accuracy: 0.49206349206349204
Delta: 0.0020714623204336406 	  Loss: 1.0193794014687567 	 Accuracy: 0.49206349206349204
Delta: 0.0015154297720557978 	  Loss: 1.0193614414115522 	 Accuracy: 0.49206349206349204
Delta: 0.0017846472585880974 	  Loss: 1.0193469618264461 	 Accuracy: 0.49206349206349204
Delta: 0.0017135164804139625 	  Loss: 1.019347760974946 	 Accuracy: 0.49206349206349204
Delta: 0.0013872944645253026 	  Loss: 1.0193484863715936 	 Accuracy: 0.49206349206349204
Delta: 0.002164173487153727 	  Loss: 1.0193490408762365 	 Accuracy: 0.49206349206349204
Delta: 0.0016258088869199885 	  Loss: 1.019352571635736 	 Accuracy: 0.49206349206349204
Delta: 0.002720128583443937 	  Loss: 1.0193434150223462 	 Accuracy: 0.49206349206349204
Delta: 0.0018331030176643925 	  Loss: 1.019345318445188 	 Accuracy: 0.49206349206349204
Delta: 0.0013501199784501118 	  Loss: 1.0193602480736206 	 Accuracy: 0.49206349206349204
Delta: 0.0009876116105970508 	  Loss: 1.0193577180300455 	 Accuracy: 0.49206349206349204
Delta: 0.0005845651511449748 	  Loss: 1.0193460423141278 	 Accuracy: 0.49206349206349204
Delta: 0.0003363775591581857 	  Loss: 1.019341449150772 	 Accuracy: 0.49206349206349204
Delta: 0.0006003065859961894 	  Loss: 1.019335691346048 	 Accuracy: 0.49206349206349204
Delta: 0.0007287826337449115 	  Loss: 1.0193273945242267 	 Accuracy: 0.49206349206349204
Delta: 0.0010173055351227294 	  Loss: 1.0193287045816184 	 Accuracy: 0.49206349206349204
Delta: 0.0011043893613866336 	  Loss: 1.019322301266186 	 Accuracy: 0.49206349206349204
Delta: 0.0005831791509701564 	  Loss: 1.0193187015503913 	 Accuracy: 0.49206349206349204
Delta: 0.0007555508250790031 	  Loss: 1.01931759566612 	 Accuracy: 0.49206349206349204
Delta: 0.0008429187806302065 	  Loss: 1.0193233530231507 	 Accuracy: 0.49206349206349204
Delta: 0.0008687404866282863 	  Loss: 1.019330605105556 	 Accuracy: 0.49206349206349204
Delta: 0.0007835511982309287 	  Loss: 1.0193369999433948 	 Accuracy: 0.49206349206349204
Delta: 0.00082703059912992 	  Loss: 1.019335278538943 	 Accuracy: 0.49206349206349204
Delta: 0.0003364030987583298 	  Loss: 1.0193315256609388 	 Accuracy: 0.49206349206349204
Delta: 0.00026922204350215376 	  Loss: 1.0193276536580769 	 Accuracy: 0.49206349206349204
Delta: 0.0002255373738105335 	  Loss: 1.0193242553977344 	 Accuracy: 0.49206349206349204
Delta: 0.00013044395894278943 	  Loss: 1.0193221161309531 	 Accuracy: 0.49206349206349204
Delta: 3.224254206698865e-05 	  Loss: 1.0193208304482915 	 Accuracy: 0.49206349206349204
Delta: 1.8435385978180683e-05 	  Loss: 1.019319920745184 	 Accuracy: 0.49206349206349204
Delta: 1.702350767703676e-05 	  Loss: 1.019319043727375 	 Accuracy: 0.49206349206349204
Delta: 1.5866201186429597e-05 	  Loss: 1.0193182309154705 	 Accuracy: 0.49206349206349204
Delta: 1.4755840906524928e-05 	  Loss: 1.019317462404449 	 Accuracy: 0.49206349206349204
Delta: 1.3751048390065812e-05 	  Loss: 1.0193167367006657 	 Accuracy: 0.49206349206349204
Delta: 1.2758189383332693e-05 	  Loss: 1.01931607462687 	 Accuracy: 0.49206349206349204
Delta: 1.1999475243241599e-05 	  Loss: 1.0193154653404801 	 Accuracy: 0.49206349206349204
Delta: 1.1175903612430665e-05 	  Loss: 1.0193148850747393 	 Accuracy: 0.49206349206349204
Delta: 2.758328618068413e-05 	  Loss: 1.0193143071454478 	 Accuracy: 0.49206349206349204
Delta: 6.130835697931598e-05 	  Loss: 1.019313864020714 	 Accuracy: 0.49206349206349204
Delta: 0.00046847050885707965 	  Loss: 1.019313507834207 	 Accuracy: 0.49206349206349204
Delta: 0.00047998680156379283 	  Loss: 1.0193128986316107 	 Accuracy: 0.49206349206349204
Delta: 0.00021645827062294622 	  Loss: 1.019312357184175 	 Accuracy: 0.49206349206349204
Delta: 0.00021161818304187905 	  Loss: 1.0193127975542362 	 Accuracy: 0.49206349206349204
Delta: 0.00011620747943869368 	  Loss: 1.0193130578905385 	 Accuracy: 0.49206349206349204
Delta: 2.601357392678756e-05 	  Loss: 1.0193129415533724 	 Accuracy: 0.49206349206349204
Delta: 0.044879485969129496 	  Loss: 1.0784808234963088 	 Accuracy: 0.46774193548387094
Delta: 0.03369898591445178 	  Loss: 1.0653101725669414 	 Accuracy: 0.45161290322580644
Delta: 0.028382151375699882 	  Loss: 1.0598046221848878 	 Accuracy: 0.46774193548387094
Delta: 0.02754660953013676 	  Loss: 1.0569556806892142 	 Accuracy: 0.45161290322580644
Delta: 0.02480065214135112 	  Loss: 1.0549605333386847 	 Accuracy: 0.4032258064516129
Delta: 0.021083640624527215 	  Loss: 1.0533575759846814 	 Accuracy: 0.41935483870967744
Delta: 0.019175084516738335 	  Loss: 1.0519460118371415 	 Accuracy: 0.45161290322580644
Delta: 0.01859424551473276 	  Loss: 1.0507003082580306 	 Accuracy: 0.43548387096774194
Delta: 0.015727373162942086 	  Loss: 1.0496952768859238 	 Accuracy: 0.43548387096774194
Delta: 0.013879413120245336 	  Loss: 1.0489811205184831 	 Accuracy: 0.43548387096774194
Delta: 0.010289477063075696 	  Loss: 1.0485627613834496 	 Accuracy: 0.43548387096774194
Delta: 0.007981248090258809 	  Loss: 1.04861145722441 	 Accuracy: 0.43548387096774194
Delta: 0.006540290478892279 	  Loss: 1.0486225120815398 	 Accuracy: 0.41935483870967744
Delta: 0.0063197753833351186 	  Loss: 1.0484977119852605 	 Accuracy: 0.4032258064516129
Delta: 0.0071496796806683185 	  Loss: 1.0481384555237718 	 Accuracy: 0.4032258064516129
Delta: 0.008211698789449603 	  Loss: 1.0476656088214917 	 Accuracy: 0.4032258064516129

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007208690388204802 	  Loss: 1.0472246717777463 	 Accuracy: 0.4032258064516129
Delta: 0.0055744375738009475 	  Loss: 1.0469601407814935 	 Accuracy: 0.4032258064516129
Delta: 0.0043959156142177516 	  Loss: 1.04681971197494 	 Accuracy: 0.4032258064516129
Delta: 0.0036110962100748614 	  Loss: 1.0467837112166818 	 Accuracy: 0.4032258064516129
Delta: 0.003520574465764426 	  Loss: 1.046735210650372 	 Accuracy: 0.4032258064516129
Delta: 0.002559218508888795 	  Loss: 1.0466997229040256 	 Accuracy: 0.4032258064516129
Delta: 0.001616589087513774 	  Loss: 1.0466566218103397 	 Accuracy: 0.4032258064516129
Delta: 0.0014601692522734555 	  Loss: 1.0466360239681185 	 Accuracy: 0.4032258064516129
Delta: 0.002422584698254371 	  Loss: 1.046621186934698 	 Accuracy: 0.4032258064516129
Delta: 0.0019472352225006662 	  Loss: 1.0465967223448915 	 Accuracy: 0.4032258064516129
Delta: 0.0017562602853576617 	  Loss: 1.046575353988481 	 Accuracy: 0.4032258064516129
Delta: 0.0011398056214629512 	  Loss: 1.046565948818666 	 Accuracy: 0.4032258064516129
Delta: 0.000795925130359818 	  Loss: 1.0465639292573599 	 Accuracy: 0.4032258064516129
Delta: 0.0009043670560683761 	  Loss: 1.0465631146186773 	 Accuracy: 0.4032258064516129
Delta: 0.0005063533558987016 	  Loss: 1.046554703016278 	 Accuracy: 0.4032258064516129
Delta: 0.0005422026254009662 	  Loss: 1.0465521610499846 	 Accuracy: 0.4032258064516129
Delta: 0.0006087745656531721 	  Loss: 1.0465479358020913 	 Accuracy: 0.4032258064516129
Delta: 0.00036293218864906284 	  Loss: 1.046545471673099 	 Accuracy: 0.4032258064516129
Delta: 0.0006657779564504346 	  Loss: 1.0465470408398574 	 Accuracy: 0.4032258064516129
Delta: 0.0011202781481322462 	  Loss: 1.0465493039751572 	 Accuracy: 0.4032258064516129
Delta: 0.0009777133845978434 	  Loss: 1.046547207304036 	 Accuracy: 0.4032258064516129
Delta: 0.0015294683547886145 	  Loss: 1.046543832197988 	 Accuracy: 0.4032258064516129
Delta: 0.000478483472175692 	  Loss: 1.0465457577773019 	 Accuracy: 0.4032258064516129
Delta: 0.00041391645786896823 	  Loss: 1.0465475307155758 	 Accuracy: 0.4032258064516129
Delta: 0.000531807908845791 	  Loss: 1.0465477468136128 	 Accuracy: 0.4032258064516129
Delta: 0.0004957535215486645 	  Loss: 1.04654725165826 	 Accuracy: 0.4032258064516129
Delta: 0.00023240677360661166 	  Loss: 1.0465469846906745 	 Accuracy: 0.4032258064516129
Delta: 0.00014387302947040345 	  Loss: 1.0465484394661835 	 Accuracy: 0.4032258064516129
Delta: 0.00015939250251109747 	  Loss: 1.0465480807001182 	 Accuracy: 0.4032258064516129
Delta: 0.0003292744114396792 	  Loss: 1.046547676429677 	 Accuracy: 0.4032258064516129
Delta: 0.0002944706567624907 	  Loss: 1.0465463799724244 	 Accuracy: 0.4032258064516129
Delta: 6.360644772622972e-05 	  Loss: 1.0465455595641326 	 Accuracy: 0.4032258064516129
Delta: 3.7372202095750463e-06 	  Loss: 1.0465452975750344 	 Accuracy: 0.4032258064516129
Delta: 6.228210592969357e-08 	  Loss: 1.0465453269117633 	 Accuracy: 0.4032258064516129
converged at iter  49
Delta: 0.04511711476626689 	  Loss: 1.0699675459695892 	 Accuracy: 0.41935483870967744
Delta: 0.03445442111250618 	  Loss: 1.0575509711555946 	 Accuracy: 0.3870967741935484
Delta: 0.025512315070544064 	  Loss: 1.0509754455303124 	 Accuracy: 0.3548387096774194
Delta: 0.022462898528566862 	  Loss: 1.0463131305715008 	 Accuracy: 0.3709677419354839
Delta: 0.022542910647170525 	  Loss: 1.0428794790630964 	 Accuracy: 0.4032258064516129
Delta: 0.024012267020408144 	  Loss: 1.0406763788173872 	 Accuracy: 0.3870967741935484
Delta: 0.02268725384957753 	  Loss: 1.0399343240963905 	 Accuracy: 0.3870967741935484
Delta: 0.021741434628234038 	  Loss: 1.039886860949772 	 Accuracy: 0.4032258064516129
Delta: 0.019544352893806426 	  Loss: 1.0392039529898294 	 Accuracy: 0.4032258064516129
Delta: 0.016930552212163275 	  Loss: 1.0381625814523274 	 Accuracy: 0.4032258064516129
Delta: 0.014842370995519962 	  Loss: 1.0374970203666767 	 Accuracy: 0.4032258064516129
Delta: 0.010762579159708621 	  Loss: 1.0370206046526547 	 Accuracy: 0.4032258064516129
Delta: 0.009344839734637006 	  Loss: 1.0366446094341855 	 Accuracy: 0.4032258064516129
Delta: 0.007181211080611749 	  Loss: 1.0363696140900347 	 Accuracy: 0.3870967741935484
Delta: 0.006804627300802797 	  Loss: 1.036184744292032 	 Accuracy: 0.3870967741935484
Delta: 0.007574806888552944 	  Loss: 1.0360997111722394 	 Accuracy: 0.3870967741935484
Delta: 0.008721774501370919 	  Loss: 1.035959000211871 	 Accuracy: 0.3870967741935484

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008702126789308042 	  Loss: 1.0357622719198756 	 Accuracy: 0.3870967741935484
Delta: 0.00854832906643375 	  Loss: 1.0355698972187808 	 Accuracy: 0.3709677419354839
Delta: 0.0084392542100127 	  Loss: 1.0352447492334687 	 Accuracy: 0.3709677419354839
Delta: 0.011600108675038837 	  Loss: 1.034703388785573 	 Accuracy: 0.3709677419354839
Delta: 0.013317977195224134 	  Loss: 1.033896065518542 	 Accuracy: 0.3709677419354839
Delta: 0.010324825916909565 	  Loss: 1.033471109058861 	 Accuracy: 0.3709677419354839
Delta: 0.008927819480439034 	  Loss: 1.0332114373752428 	 Accuracy: 0.3709677419354839
Delta: 0.007432401265915798 	  Loss: 1.0329227359791222 	 Accuracy: 0.3709677419354839
Delta: 0.007239978685875047 	  Loss: 1.0327453994545877 	 Accuracy: 0.3709677419354839
Delta: 0.005925600460528059 	  Loss: 1.032528399461254 	 Accuracy: 0.3709677419354839
Delta: 0.004835964675168592 	  Loss: 1.0323929426021112 	 Accuracy: 0.3709677419354839
Delta: 0.004561402394176764 	  Loss: 1.032294103579919 	 Accuracy: 0.3709677419354839
Delta: 0.0033930730679337362 	  Loss: 1.0322602136405115 	 Accuracy: 0.3709677419354839
Delta: 0.0027335133720590016 	  Loss: 1.0322248874214512 	 Accuracy: 0.3709677419354839
Delta: 0.002194525018939193 	  Loss: 1.0322207068919598 	 Accuracy: 0.3709677419354839
Delta: 0.0016972876274241385 	  Loss: 1.0322224977482557 	 Accuracy: 0.3709677419354839
Delta: 0.0021631535574289326 	  Loss: 1.0322205790269081 	 Accuracy: 0.3709677419354839
Delta: 0.001536775352702011 	  Loss: 1.032215810241318 	 Accuracy: 0.3709677419354839
Delta: 0.0022852599999784048 	  Loss: 1.0322163673398737 	 Accuracy: 0.3709677419354839
Delta: 0.0017951735786233842 	  Loss: 1.03221121068171 	 Accuracy: 0.3709677419354839
Delta: 0.0015039849702486094 	  Loss: 1.0322079608609385 	 Accuracy: 0.3709677419354839
Delta: 0.0009451992161030121 	  Loss: 1.0322022877614077 	 Accuracy: 0.3709677419354839
Delta: 0.0011211569252800274 	  Loss: 1.0322015665762585 	 Accuracy: 0.3709677419354839
Delta: 0.0010023361825836825 	  Loss: 1.0322026248710268 	 Accuracy: 0.3709677419354839
Delta: 0.0005727073622008582 	  Loss: 1.0321957150228285 	 Accuracy: 0.3709677419354839
Delta: 0.00047266583013470906 	  Loss: 1.032189760932421 	 Accuracy: 0.3709677419354839
Delta: 0.00024097609828287273 	  Loss: 1.0321845286619367 	 Accuracy: 0.3709677419354839
Delta: 3.0717660347036164e-05 	  Loss: 1.0321841063268957 	 Accuracy: 0.3709677419354839
Delta: 1.114140081307401e-06 	  Loss: 1.0321840193994505 	 Accuracy: 0.3709677419354839
converged at iter  45
Delta: 0.04377053636849122 	  Loss: 1.0859818062238888 	 Accuracy: 0.45161290322580644
Delta: 0.035435510504189166 	  Loss: 1.073409541204051 	 Accuracy: 0.3548387096774194
Delta: 0.02771914474398968 	  Loss: 1.0666906864397934 	 Accuracy: 0.1935483870967742
Delta: 0.024539531461305917 	  Loss: 1.0617960425776607 	 Accuracy: 0.22580645161290322
Delta: 0.023563551709569842 	  Loss: 1.0577230033903522 	 Accuracy: 0.25806451612903225
Delta: 0.02222432177515851 	  Loss: 1.0539718963653757 	 Accuracy: 0.27419354838709675
Delta: 0.020875249428284462 	  Loss: 1.0507306344033638 	 Accuracy: 0.3064516129032258
Delta: 0.019570204854923168 	  Loss: 1.0482376604497072 	 Accuracy: 0.3225806451612903
Delta: 0.015837707737905812 	  Loss: 1.046413247230705 	 Accuracy: 0.3387096774193548
Delta: 0.01208529572923985 	  Loss: 1.0451823904815742 	 Accuracy: 0.3225806451612903
Delta: 0.009725580594578787 	  Loss: 1.0444954847171624 	 Accuracy: 0.3225806451612903
Delta: 0.007684456754246263 	  Loss: 1.0441574530143134 	 Accuracy: 0.3225806451612903

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006348274606784313 	  Loss: 1.0439457716789096 	 Accuracy: 0.3225806451612903
Delta: 0.0056839511831334845 	  Loss: 1.0438857663437118 	 Accuracy: 0.3225806451612903
Delta: 0.004480872006815459 	  Loss: 1.0438419980526175 	 Accuracy: 0.3225806451612903
Delta: 0.0029914210021768674 	  Loss: 1.043789216146115 	 Accuracy: 0.3225806451612903
Delta: 0.002472608843035109 	  Loss: 1.0437777291687707 	 Accuracy: 0.3225806451612903
Delta: 0.00272038084187916 	  Loss: 1.0437938251362877 	 Accuracy: 0.3225806451612903
Delta: 0.002966163469147516 	  Loss: 1.0438381874585367 	 Accuracy: 0.3225806451612903
Delta: 0.0019171043037124777 	  Loss: 1.0438629577054808 	 Accuracy: 0.3225806451612903
Delta: 0.0023154703090391042 	  Loss: 1.043867577565495 	 Accuracy: 0.3225806451612903
Delta: 0.0025009345712514834 	  Loss: 1.0438734129269323 	 Accuracy: 0.3225806451612903
Delta: 0.001702529387407712 	  Loss: 1.0438591957631993 	 Accuracy: 0.3225806451612903
Delta: 0.00283652542887104 	  Loss: 1.0438619637643929 	 Accuracy: 0.3225806451612903
Delta: 0.0023487909533110815 	  Loss: 1.043870856277024 	 Accuracy: 0.3225806451612903
Delta: 0.0024211114038960127 	  Loss: 1.0438753106958716 	 Accuracy: 0.3225806451612903
Delta: 0.0026265545290272167 	  Loss: 1.0438968449331323 	 Accuracy: 0.3225806451612903
Delta: 0.002421028394956315 	  Loss: 1.0439299285174404 	 Accuracy: 0.3225806451612903
Delta: 0.002713121213780512 	  Loss: 1.0439404492974345 	 Accuracy: 0.3225806451612903
Delta: 0.00288749224823302 	  Loss: 1.0439194297174321 	 Accuracy: 0.3225806451612903
Delta: 0.002199921394227562 	  Loss: 1.0438996823342708 	 Accuracy: 0.3225806451612903
Delta: 0.0021813116509667415 	  Loss: 1.0438920129458884 	 Accuracy: 0.3225806451612903
Delta: 0.0027988079560108234 	  Loss: 1.0438859936108482 	 Accuracy: 0.3225806451612903
Delta: 0.0017351893472908279 	  Loss: 1.0438710084574276 	 Accuracy: 0.3225806451612903
Delta: 0.0014233865533319846 	  Loss: 1.0438618834728208 	 Accuracy: 0.3225806451612903
Delta: 0.0020074754611609236 	  Loss: 1.0438625712203042 	 Accuracy: 0.3225806451612903
Delta: 0.0020223470909460184 	  Loss: 1.0438569744612995 	 Accuracy: 0.3225806451612903
Delta: 0.0016490115736031003 	  Loss: 1.0438673778223588 	 Accuracy: 0.3225806451612903
Delta: 0.0015901849776538306 	  Loss: 1.0438626903777386 	 Accuracy: 0.3225806451612903
Delta: 0.002126835323820622 	  Loss: 1.0438560826159144 	 Accuracy: 0.3225806451612903
Delta: 0.0015347879264941918 	  Loss: 1.0438556110280146 	 Accuracy: 0.3225806451612903
Delta: 0.0017136833119485236 	  Loss: 1.0438624115137258 	 Accuracy: 0.3225806451612903
Delta: 0.0016343861674758776 	  Loss: 1.0438762473211818 	 Accuracy: 0.3225806451612903
Delta: 0.0019590314371477143 	  Loss: 1.0438810878065068 	 Accuracy: 0.3225806451612903
Delta: 0.0007656851445403156 	  Loss: 1.0438861025790556 	 Accuracy: 0.3225806451612903
Delta: 0.00031670125990236457 	  Loss: 1.0438881836807021 	 Accuracy: 0.3225806451612903
Delta: 0.00046694772564429276 	  Loss: 1.0438896587128788 	 Accuracy: 0.3225806451612903
Delta: 0.00036339044374310465 	  Loss: 1.0438904760338206 	 Accuracy: 0.3225806451612903
Delta: 0.00018592287300341534 	  Loss: 1.043892286091883 	 Accuracy: 0.3225806451612903
Delta: 5.646371982161266e-05 	  Loss: 1.0438926529943466 	 Accuracy: 0.3225806451612903
Delta: 3.506011226759126e-06 	  Loss: 1.0438928113560952 	 Accuracy: 0.3225806451612903
Delta: 6.2841932145420235e-09 	  Loss: 1.0438928160391538 	 Accuracy: 0.3225806451612903
converged at iter  51
Delta: 0.04499305550882925 	  Loss: 1.0790644041729565 	 Accuracy: 0.3968253968253968
Delta: 0.03234101331959596 	  Loss: 1.0663512589309536 	 Accuracy: 0.4444444444444444
Delta: 0.025597396854553974 	  Loss: 1.0589924582258876 	 Accuracy: 0.4126984126984127
Delta: 0.026119978209320896 	  Loss: 1.055186002804594 	 Accuracy: 0.3492063492063492
Delta: 0.025765308271791385 	  Loss: 1.053695625370724 	 Accuracy: 0.3492063492063492
Delta: 0.02172731535162677 	  Loss: 1.052654885101727 	 Accuracy: 0.3492063492063492
Delta: 0.01965059646923576 	  Loss: 1.0525014679143652 	 Accuracy: 0.36507936507936506
Delta: 0.01762649555483883 	  Loss: 1.052364565207874 	 Accuracy: 0.36507936507936506
Delta: 0.015925435288216837 	  Loss: 1.0516792291117332 	 Accuracy: 0.31746031746031744
Delta: 0.01400904872399212 	  Loss: 1.050858737559633 	 Accuracy: 0.31746031746031744
Delta: 0.012933691394046584 	  Loss: 1.0501770136231567 	 Accuracy: 0.3333333333333333
Delta: 0.012275523434775077 	  Loss: 1.0499410745797189 	 Accuracy: 0.3333333333333333

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01107747006801461 	  Loss: 1.0496688430111814 	 Accuracy: 0.3492063492063492
Delta: 0.010956269631454827 	  Loss: 1.0492716027305642 	 Accuracy: 0.3492063492063492
Delta: 0.00953611311758118 	  Loss: 1.0487671062007777 	 Accuracy: 0.3492063492063492
Delta: 0.0090280331161 	  Loss: 1.0484950646547384 	 Accuracy: 0.3492063492063492
Delta: 0.006941866146632877 	  Loss: 1.0483904963076138 	 Accuracy: 0.3492063492063492
Delta: 0.006954793720019923 	  Loss: 1.0482060565031899 	 Accuracy: 0.3492063492063492
Delta: 0.00614435667749978 	  Loss: 1.0480127662718504 	 Accuracy: 0.3492063492063492
Delta: 0.005647230276112579 	  Loss: 1.047928209579363 	 Accuracy: 0.3492063492063492
Delta: 0.004647548449428721 	  Loss: 1.0478927814485262 	 Accuracy: 0.3492063492063492
Delta: 0.00409924346541563 	  Loss: 1.0477980964600722 	 Accuracy: 0.3492063492063492
Delta: 0.003461370690184615 	  Loss: 1.0477084215594699 	 Accuracy: 0.3492063492063492
Delta: 0.0033011639896666917 	  Loss: 1.0476714205009627 	 Accuracy: 0.3492063492063492
Delta: 0.0028314576981024486 	  Loss: 1.0476076590870453 	 Accuracy: 0.3492063492063492
Delta: 0.002604292392556963 	  Loss: 1.0475702666343798 	 Accuracy: 0.3492063492063492
Delta: 0.002382523817952794 	  Loss: 1.0475619955442643 	 Accuracy: 0.3492063492063492
Delta: 0.0028948833815766054 	  Loss: 1.047535658167396 	 Accuracy: 0.3492063492063492
Delta: 0.0031888688781596067 	  Loss: 1.047480233315583 	 Accuracy: 0.3492063492063492
Delta: 0.0029126451635027766 	  Loss: 1.0474503068088636 	 Accuracy: 0.3492063492063492
Delta: 0.00373476942436422 	  Loss: 1.0474276148948565 	 Accuracy: 0.3492063492063492
Delta: 0.0033279568257434475 	  Loss: 1.0474124345241942 	 Accuracy: 0.3492063492063492
Delta: 0.0038432919024105503 	  Loss: 1.0473890046590353 	 Accuracy: 0.3492063492063492
Delta: 0.003700601944983564 	  Loss: 1.0473310749070484 	 Accuracy: 0.3492063492063492
Delta: 0.004271120103000606 	  Loss: 1.0472981333468052 	 Accuracy: 0.3492063492063492
Delta: 0.0032986241521843532 	  Loss: 1.0472333053243035 	 Accuracy: 0.3492063492063492
Delta: 0.003267975895195017 	  Loss: 1.047165188077806 	 Accuracy: 0.3492063492063492
Delta: 0.0026131810226294842 	  Loss: 1.047143306564399 	 Accuracy: 0.3492063492063492
Delta: 0.002072226975355218 	  Loss: 1.0471362641355273 	 Accuracy: 0.3492063492063492
Delta: 0.0023062971610383204 	  Loss: 1.0471247393892518 	 Accuracy: 0.3492063492063492
Delta: 0.0013392380496435338 	  Loss: 1.0471207487439051 	 Accuracy: 0.3492063492063492
Delta: 0.0011725798376280945 	  Loss: 1.0471315885048802 	 Accuracy: 0.3492063492063492
Delta: 0.0014490643844992047 	  Loss: 1.0471380936268555 	 Accuracy: 0.3492063492063492
Delta: 0.0018070402977334644 	  Loss: 1.0471390861728973 	 Accuracy: 0.3492063492063492
Delta: 0.001628408878824939 	  Loss: 1.0471451614528728 	 Accuracy: 0.3492063492063492
Delta: 0.0023362497707374685 	  Loss: 1.047153499012854 	 Accuracy: 0.3492063492063492
Delta: 0.002698141485411056 	  Loss: 1.0471347602794365 	 Accuracy: 0.3492063492063492
Delta: 0.002154951890568896 	  Loss: 1.047127788902106 	 Accuracy: 0.3492063492063492
Delta: 0.0014651746898056933 	  Loss: 1.0471181298390762 	 Accuracy: 0.3492063492063492
Delta: 0.0013334922906522832 	  Loss: 1.0471075796559117 	 Accuracy: 0.3492063492063492
Delta: 0.001203165903430755 	  Loss: 1.0471007569526858 	 Accuracy: 0.3492063492063492
Delta: 0.0007250149661387649 	  Loss: 1.047094878414773 	 Accuracy: 0.3492063492063492
Delta: 0.0007543810534566209 	  Loss: 1.0470906019633746 	 Accuracy: 0.3492063492063492
Delta: 0.0010496113750140803 	  Loss: 1.0470890747456663 	 Accuracy: 0.3492063492063492
Delta: 0.0006843160463458115 	  Loss: 1.0470914574118764 	 Accuracy: 0.3492063492063492
Delta: 0.0003734349003792148 	  Loss: 1.0470868842916685 	 Accuracy: 0.3492063492063492
Delta: 0.0009276267221412209 	  Loss: 1.0470837159314388 	 Accuracy: 0.3492063492063492
Delta: 0.0008172346322826256 	  Loss: 1.047086206106928 	 Accuracy: 0.3492063492063492
Delta: 0.0006314700339482213 	  Loss: 1.047092391203614 	 Accuracy: 0.3492063492063492
Delta: 0.00012661585224793632 	  Loss: 1.0470974158521058 	 Accuracy: 0.3492063492063492
Delta: 0.00014452768360840416 	  Loss: 1.047098416467777 	 Accuracy: 0.3492063492063492
Delta: 7.627849425515977e-05 	  Loss: 1.0470998120189559 	 Accuracy: 0.3492063492063492
Delta: 9.45184143945685e-05 	  Loss: 1.0471002004475978 	 Accuracy: 0.3492063492063492
Delta: 8.852553678574793e-06 	  Loss: 1.0471007903342868 	 Accuracy: 0.3492063492063492
Delta: 2.1418463790454005e-09 	  Loss: 1.0471007897323208 	 Accuracy: 0.3492063492063492
converged at iter  64
Delta: 0.04366820909532602 	  Loss: 1.0667161386917998 	 Accuracy: 0.2698412698412698
Delta: 0.03655378540823494 	  Loss: 1.0536028100890307 	 Accuracy: 0.31746031746031744
Delta: 0.032905986155641616 	  Loss: 1.046761202041293 	 Accuracy: 0.2698412698412698
Delta: 0.02882216351882662 	  Loss: 1.0448283326419752 	 Accuracy: 0.25396825396825395
Delta: 0.026360944589234183 	  Loss: 1.0439870654874728 	 Accuracy: 0.30158730158730157
Delta: 0.022027538858181456 	  Loss: 1.0412965520418043 	 Accuracy: 0.2857142857142857
Delta: 0.01733717104890918 	  Loss: 1.0390844698489603 	 Accuracy: 0.2857142857142857

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.015926409119796228 	  Loss: 1.037578933419336 	 Accuracy: 0.2857142857142857
Delta: 0.012891391600708523 	  Loss: 1.036592461763185 	 Accuracy: 0.2857142857142857
Delta: 0.008726220848428959 	  Loss: 1.0362390657032847 	 Accuracy: 0.2857142857142857
Delta: 0.007781263383464419 	  Loss: 1.0361049995355671 	 Accuracy: 0.2857142857142857
Delta: 0.007185566645962163 	  Loss: 1.0360213848699669 	 Accuracy: 0.2857142857142857
Delta: 0.005510282634288751 	  Loss: 1.0359450946326714 	 Accuracy: 0.2857142857142857
Delta: 0.0043534046543850565 	  Loss: 1.0359054369474459 	 Accuracy: 0.2857142857142857
Delta: 0.003969274379359706 	  Loss: 1.0358274542162185 	 Accuracy: 0.2857142857142857
Delta: 0.003421857242555625 	  Loss: 1.0357746116674966 	 Accuracy: 0.2857142857142857
Delta: 0.004647552924049196 	  Loss: 1.0357178314950373 	 Accuracy: 0.2857142857142857
Delta: 0.0034353011853818895 	  Loss: 1.0356668905680948 	 Accuracy: 0.2857142857142857
Delta: 0.0025694908670497586 	  Loss: 1.0356089249422875 	 Accuracy: 0.2857142857142857
Delta: 0.002609935750363799 	  Loss: 1.0355773939587092 	 Accuracy: 0.2857142857142857
Delta: 0.0025962629836926406 	  Loss: 1.0355462281943095 	 Accuracy: 0.2857142857142857
Delta: 0.002446602240972291 	  Loss: 1.0355347293353832 	 Accuracy: 0.2857142857142857
Delta: 0.0022253365809877306 	  Loss: 1.0355084951681426 	 Accuracy: 0.2857142857142857
Delta: 0.001095842822776219 	  Loss: 1.0354800264267376 	 Accuracy: 0.2857142857142857
Delta: 0.001754319281253175 	  Loss: 1.0354743743456285 	 Accuracy: 0.2857142857142857
Delta: 0.0017413425226114393 	  Loss: 1.0354508898790329 	 Accuracy: 0.2857142857142857
Delta: 0.002652701733935579 	  Loss: 1.0354407903106013 	 Accuracy: 0.2857142857142857
Delta: 0.0014908515225750486 	  Loss: 1.0354330029281094 	 Accuracy: 0.2857142857142857
Delta: 0.0017809906941763242 	  Loss: 1.0354297281236953 	 Accuracy: 0.2857142857142857
Delta: 0.0019386659108856482 	  Loss: 1.0354342614687007 	 Accuracy: 0.2857142857142857
Delta: 0.0025593974112088544 	  Loss: 1.0354330820818038 	 Accuracy: 0.2857142857142857
Delta: 0.0016948749814471086 	  Loss: 1.0354213814041047 	 Accuracy: 0.2857142857142857
Delta: 0.001296844489802951 	  Loss: 1.03541976045548 	 Accuracy: 0.2857142857142857
Delta: 0.002126667514154896 	  Loss: 1.0354206812193398 	 Accuracy: 0.2857142857142857
Delta: 0.0014648042764488609 	  Loss: 1.0354215692338191 	 Accuracy: 0.2857142857142857
Delta: 0.0022011098614376132 	  Loss: 1.0354108666288813 	 Accuracy: 0.2857142857142857
Delta: 0.0018541848321562038 	  Loss: 1.035392647118111 	 Accuracy: 0.2857142857142857
Delta: 0.001609225134255066 	  Loss: 1.0353712762917104 	 Accuracy: 0.2857142857142857
Delta: 0.001447551028333039 	  Loss: 1.0353738114489985 	 Accuracy: 0.2857142857142857
Delta: 0.0015619807348871341 	  Loss: 1.0353654333751572 	 Accuracy: 0.2857142857142857
Delta: 0.0019219914870099498 	  Loss: 1.035349407651319 	 Accuracy: 0.2857142857142857
Delta: 0.0020919478092657467 	  Loss: 1.0353402127668478 	 Accuracy: 0.2857142857142857
Delta: 0.001861212243762488 	  Loss: 1.0353246022060323 	 Accuracy: 0.2857142857142857
Delta: 0.0015511512733229439 	  Loss: 1.035308101446272 	 Accuracy: 0.2857142857142857
Delta: 0.0013272788495925206 	  Loss: 1.035290284954712 	 Accuracy: 0.2857142857142857
Delta: 0.0012563610198430843 	  Loss: 1.0352809550103215 	 Accuracy: 0.2857142857142857
Delta: 0.001063884103623603 	  Loss: 1.0352789120341443 	 Accuracy: 0.2857142857142857
Delta: 0.0011403675411616931 	  Loss: 1.0352833204581724 	 Accuracy: 0.2857142857142857
Delta: 0.0014494740014453253 	  Loss: 1.0352841857028539 	 Accuracy: 0.2857142857142857
Delta: 0.002136858914801525 	  Loss: 1.035277939139885 	 Accuracy: 0.2857142857142857
Delta: 0.001953805493412994 	  Loss: 1.0352498260246956 	 Accuracy: 0.2857142857142857
Delta: 0.0015653656814955048 	  Loss: 1.0352403125022227 	 Accuracy: 0.2857142857142857
Delta: 0.0018624278720315165 	  Loss: 1.0352210288048151 	 Accuracy: 0.2857142857142857
Delta: 0.0017205542209082136 	  Loss: 1.035207702327556 	 Accuracy: 0.2857142857142857
Delta: 0.0013005090141100344 	  Loss: 1.035190113214108 	 Accuracy: 0.2857142857142857
Delta: 0.001272498131937728 	  Loss: 1.0351719111456186 	 Accuracy: 0.2857142857142857
Delta: 0.0011205989511254308 	  Loss: 1.0351665647480832 	 Accuracy: 0.2857142857142857
Delta: 0.0008289552924426669 	  Loss: 1.0351607328325325 	 Accuracy: 0.2857142857142857
Delta: 0.0007686626090142782 	  Loss: 1.0351595877695638 	 Accuracy: 0.2857142857142857
Delta: 0.0005793840435130637 	  Loss: 1.035157019677411 	 Accuracy: 0.2857142857142857
Delta: 0.0005964664708246543 	  Loss: 1.0351535358995818 	 Accuracy: 0.2857142857142857
Delta: 0.001095890837004918 	  Loss: 1.035154330939314 	 Accuracy: 0.2857142857142857
Delta: 0.0007607692988162951 	  Loss: 1.0351537414254457 	 Accuracy: 0.2857142857142857
Delta: 0.0022404751927213177 	  Loss: 1.0351520802041256 	 Accuracy: 0.2857142857142857
Delta: 0.0018830973733661334 	  Loss: 1.0351362833092765 	 Accuracy: 0.2857142857142857
Delta: 0.0017484277242125973 	  Loss: 1.035128298665455 	 Accuracy: 0.2857142857142857
Delta: 0.00163538780148354 	  Loss: 1.0351091287228014 	 Accuracy: 0.2857142857142857
Delta: 0.0020846743387825943 	  Loss: 1.0350907586757605 	 Accuracy: 0.2857142857142857
Delta: 0.0019490562679779504 	  Loss: 1.0350638095416387 	 Accuracy: 0.2857142857142857
Delta: 0.0016084399126299114 	  Loss: 1.0350499637583295 	 Accuracy: 0.2857142857142857
Delta: 0.00115129000021672 	  Loss: 1.0350451341695128 	 Accuracy: 0.2857142857142857
Delta: 0.0012732450474918968 	  Loss: 1.035044414376201 	 Accuracy: 0.2857142857142857
Delta: 0.0011457416416760522 	  Loss: 1.0350395488153905 	 Accuracy: 0.2857142857142857
Delta: 0.0016810610309784622 	  Loss: 1.0350319500616196 	 Accuracy: 0.2857142857142857
Delta: 0.001862386845318034 	  Loss: 1.0350230136853438 	 Accuracy: 0.2857142857142857
Delta: 0.0009632386647905189 	  Loss: 1.0350135585999722 	 Accuracy: 0.2857142857142857
Delta: 0.0009329931749050269 	  Loss: 1.0350070658540393 	 Accuracy: 0.2857142857142857
Delta: 0.0014781903335255784 	  Loss: 1.0350055114237824 	 Accuracy: 0.2857142857142857
Delta: 0.0011758761231653366 	  Loss: 1.034997822527668 	 Accuracy: 0.2857142857142857
Delta: 0.0012024226982299238 	  Loss: 1.0349901029779582 	 Accuracy: 0.2857142857142857
Delta: 0.00039258260075209135 	  Loss: 1.0349973165183166 	 Accuracy: 0.2857142857142857
Delta: 0.0007206361948828293 	  Loss: 1.0349979106678169 	 Accuracy: 0.2857142857142857
Delta: 0.000982447839408585 	  Loss: 1.034994169299463 	 Accuracy: 0.2857142857142857
Delta: 0.0007813367755067553 	  Loss: 1.0349853162968825 	 Accuracy: 0.2857142857142857
Delta: 0.0006199129641530866 	  Loss: 1.0349766990506426 	 Accuracy: 0.2857142857142857
Delta: 0.000409512583534289 	  Loss: 1.0349690596518304 	 Accuracy: 0.2857142857142857
Delta: 0.0009130251227444891 	  Loss: 1.0349718014800557 	 Accuracy: 0.2857142857142857
Delta: 0.0003814996158363615 	  Loss: 1.034971454493716 	 Accuracy: 0.2857142857142857
Delta: 0.00032825023041310004 	  Loss: 1.0349714960569578 	 Accuracy: 0.2857142857142857
converged at iter  88
Delta: 0.04866686969017475 	  Loss: 1.070020392892051 	 Accuracy: 0.41935483870967744
Delta: 0.039311062829691296 	  Loss: 1.0597912388596238 	 Accuracy: 0.45161290322580644
Delta: 0.03163263790701342 	  Loss: 1.0512072828784231 	 Accuracy: 0.46774193548387094
Delta: 0.03229995808557522 	  Loss: 1.0486961635855936 	 Accuracy: 0.4838709677419355
Delta: 0.027435796502600657 	  Loss: 1.0471554643574743 	 Accuracy: 0.46774193548387094
Delta: 0.021719975826857536 	  Loss: 1.0453509520146829 	 Accuracy: 0.43548387096774194
Delta: 0.021262265271456426 	  Loss: 1.0432568085419724 	 Accuracy: 0.45161290322580644
Delta: 0.020065009814521462 	  Loss: 1.041143857943296 	 Accuracy: 0.43548387096774194
Delta: 0.016512774038919386 	  Loss: 1.0394983655438927 	 Accuracy: 0.43548387096774194

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.013352967388937757 	  Loss: 1.038673855257314 	 Accuracy: 0.43548387096774194
Delta: 0.00926092847951763 	  Loss: 1.0383588018711876 	 Accuracy: 0.43548387096774194
Delta: 0.01064578117108312 	  Loss: 1.0382890077866014 	 Accuracy: 0.43548387096774194
Delta: 0.008377872174394714 	  Loss: 1.0381855720786024 	 Accuracy: 0.43548387096774194
Delta: 0.006989480001155984 	  Loss: 1.038193846352085 	 Accuracy: 0.43548387096774194
Delta: 0.006148173186956871 	  Loss: 1.0381414204775314 	 Accuracy: 0.43548387096774194
Delta: 0.0053906751996871645 	  Loss: 1.0380869956984007 	 Accuracy: 0.43548387096774194
Delta: 0.005550860366919673 	  Loss: 1.0380308930926256 	 Accuracy: 0.43548387096774194
Delta: 0.006736802181790167 	  Loss: 1.0379621481390182 	 Accuracy: 0.43548387096774194
Delta: 0.008654293108691043 	  Loss: 1.0377736925540992 	 Accuracy: 0.43548387096774194
Delta: 0.010848152062593002 	  Loss: 1.0374299488920942 	 Accuracy: 0.43548387096774194
Delta: 0.013798875583693889 	  Loss: 1.0367884915382048 	 Accuracy: 0.43548387096774194
Delta: 0.014081775157950319 	  Loss: 1.0359293193413481 	 Accuracy: 0.43548387096774194
Delta: 0.010407433007670412 	  Loss: 1.0352572459392604 	 Accuracy: 0.43548387096774194
Delta: 0.008797323453202026 	  Loss: 1.0350212248781174 	 Accuracy: 0.43548387096774194
Delta: 0.006559675654241452 	  Loss: 1.034884238620338 	 Accuracy: 0.43548387096774194
Delta: 0.0048263291165156815 	  Loss: 1.0347721441847244 	 Accuracy: 0.43548387096774194
Delta: 0.004794989770178864 	  Loss: 1.0347330520555786 	 Accuracy: 0.43548387096774194
Delta: 0.0042326721750681785 	  Loss: 1.034658020706209 	 Accuracy: 0.43548387096774194
Delta: 0.00447519424199501 	  Loss: 1.034591092241585 	 Accuracy: 0.43548387096774194
Delta: 0.003561606578247436 	  Loss: 1.0344986110856909 	 Accuracy: 0.43548387096774194
Delta: 0.0046081751733746444 	  Loss: 1.0344468055052656 	 Accuracy: 0.43548387096774194
Delta: 0.00506032354967677 	  Loss: 1.0344121976917426 	 Accuracy: 0.43548387096774194
Delta: 0.004434025236189464 	  Loss: 1.0343373557094324 	 Accuracy: 0.43548387096774194
Delta: 0.00521405223517925 	  Loss: 1.0342938012393517 	 Accuracy: 0.43548387096774194
Delta: 0.0037132523202641496 	  Loss: 1.03429949782313 	 Accuracy: 0.43548387096774194
Delta: 0.002574009265093288 	  Loss: 1.0342661360991228 	 Accuracy: 0.43548387096774194
Delta: 0.0024987433242079225 	  Loss: 1.0342572725368595 	 Accuracy: 0.43548387096774194
Delta: 0.0019216769108893446 	  Loss: 1.03427761324973 	 Accuracy: 0.43548387096774194
Delta: 0.0026198960073189363 	  Loss: 1.0342690711724103 	 Accuracy: 0.43548387096774194
Delta: 0.0017435919894399409 	  Loss: 1.034260087221119 	 Accuracy: 0.43548387096774194
Delta: 0.001902289895939817 	  Loss: 1.0342618434891089 	 Accuracy: 0.43548387096774194
Delta: 0.0017481208229205784 	  Loss: 1.0342554856573587 	 Accuracy: 0.43548387096774194
Delta: 0.0024192825894072444 	  Loss: 1.0342342368688278 	 Accuracy: 0.43548387096774194
Delta: 0.002566214050024498 	  Loss: 1.0341875317721319 	 Accuracy: 0.43548387096774194
Delta: 0.0022318689025636372 	  Loss: 1.0341571547755855 	 Accuracy: 0.43548387096774194
Delta: 0.0013928728040377273 	  Loss: 1.0341542233889218 	 Accuracy: 0.43548387096774194
Delta: 0.001163023128489229 	  Loss: 1.0341425547457215 	 Accuracy: 0.43548387096774194
Delta: 0.0011506334785045948 	  Loss: 1.0341421433976319 	 Accuracy: 0.43548387096774194
Delta: 0.001542814870634214 	  Loss: 1.0341471365821988 	 Accuracy: 0.43548387096774194
Delta: 0.0008987622219899891 	  Loss: 1.0341512206203705 	 Accuracy: 0.43548387096774194
Delta: 0.00044822913154851337 	  Loss: 1.0341462783628608 	 Accuracy: 0.43548387096774194
Delta: 0.00044529376218000697 	  Loss: 1.0341423403396726 	 Accuracy: 0.43548387096774194
Delta: 0.0002850510793724728 	  Loss: 1.0341361679529146 	 Accuracy: 0.43548387096774194
Delta: 0.0005867819963162299 	  Loss: 1.0341353431779856 	 Accuracy: 0.43548387096774194
Delta: 0.000262438598628275 	  Loss: 1.034129222780299 	 Accuracy: 0.43548387096774194
Delta: 0.0001888595440408581 	  Loss: 1.0341298639255987 	 Accuracy: 0.43548387096774194
Delta: 0.00011147374845570683 	  Loss: 1.0341280099553005 	 Accuracy: 0.43548387096774194
Delta: 0.00011813192322716621 	  Loss: 1.0341276301084368 	 Accuracy: 0.43548387096774194
Delta: 0.00013629384388035874 	  Loss: 1.0341279535207302 	 Accuracy: 0.43548387096774194
Delta: 3.780271920357498e-05 	  Loss: 1.0341286690829876 	 Accuracy: 0.43548387096774194
Delta: 2.3988086152009453e-06 	  Loss: 1.034128844708393 	 Accuracy: 0.43548387096774194
Delta: 1.8543857431665542e-11 	  Loss: 1.0341288447361587 	 Accuracy: 0.43548387096774194
converged at iter  61
Delta: 0.04554695079910909 	  Loss: 1.064313466391082 	 Accuracy: 0.6290322580645161
Delta: 0.039621258423148065 	  Loss: 1.0602783467004437 	 Accuracy: 0.532258064516129
Delta: 0.038147778834160526 	  Loss: 1.0599247326246282 	 Accuracy: 0.5161290322580645
Delta: 0.02720101990029371 	  Loss: 1.0564169292123795 	 Accuracy: 0.4838709677419355
Delta: 0.02245256042146617 	  Loss: 1.0532708108702062 	 Accuracy: 0.46774193548387094
Delta: 0.020070746202484894 	  Loss: 1.0508938181064056 	 Accuracy: 0.45161290322580644

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01764193972122438 	  Loss: 1.0491516336972166 	 Accuracy: 0.45161290322580644
Delta: 0.017144772153085436 	  Loss: 1.0481543817254244 	 Accuracy: 0.45161290322580644
Delta: 0.012372573793532259 	  Loss: 1.0475575663819399 	 Accuracy: 0.45161290322580644
Delta: 0.01063497849507538 	  Loss: 1.047152647040333 	 Accuracy: 0.45161290322580644
Delta: 0.009157666519790558 	  Loss: 1.046745715699243 	 Accuracy: 0.45161290322580644
Delta: 0.008063499858605182 	  Loss: 1.0465138227073942 	 Accuracy: 0.45161290322580644
Delta: 0.008498184424313266 	  Loss: 1.046375466737628 	 Accuracy: 0.45161290322580644
Delta: 0.007814219942070707 	  Loss: 1.0460961467556031 	 Accuracy: 0.45161290322580644
Delta: 0.00652234930120974 	  Loss: 1.0457972627155323 	 Accuracy: 0.45161290322580644
Delta: 0.005552533548590691 	  Loss: 1.0456432405859064 	 Accuracy: 0.45161290322580644
Delta: 0.004883369541488471 	  Loss: 1.0455302578513743 	 Accuracy: 0.45161290322580644
Delta: 0.005276464733345204 	  Loss: 1.045429063118439 	 Accuracy: 0.45161290322580644
Delta: 0.005221994838384869 	  Loss: 1.0453217332755536 	 Accuracy: 0.45161290322580644
Delta: 0.0051913756235928985 	  Loss: 1.0452704434410527 	 Accuracy: 0.45161290322580644
Delta: 0.005437361341844992 	  Loss: 1.0451607490065156 	 Accuracy: 0.45161290322580644
Delta: 0.004815480017605684 	  Loss: 1.0450334862156967 	 Accuracy: 0.45161290322580644
Delta: 0.0035614277323947332 	  Loss: 1.0449641922987976 	 Accuracy: 0.45161290322580644
Delta: 0.003292876890233859 	  Loss: 1.0449248330635732 	 Accuracy: 0.45161290322580644
Delta: 0.003563192663854478 	  Loss: 1.04489230166102 	 Accuracy: 0.45161290322580644
Delta: 0.004055288564244313 	  Loss: 1.0448632288956645 	 Accuracy: 0.45161290322580644
Delta: 0.004192370031762625 	  Loss: 1.0448196151871143 	 Accuracy: 0.45161290322580644
Delta: 0.0040989728708718896 	  Loss: 1.0447670048068383 	 Accuracy: 0.45161290322580644
Delta: 0.0036552192414604223 	  Loss: 1.0447206926182195 	 Accuracy: 0.45161290322580644
Delta: 0.0030712783379925465 	  Loss: 1.0447052781210273 	 Accuracy: 0.45161290322580644
Delta: 0.0031470910753310954 	  Loss: 1.0446686874218734 	 Accuracy: 0.45161290322580644
Delta: 0.0031700986995389885 	  Loss: 1.0446305126399351 	 Accuracy: 0.45161290322580644
Delta: 0.00316768215629634 	  Loss: 1.0446278038418926 	 Accuracy: 0.45161290322580644
Delta: 0.004772832971101302 	  Loss: 1.0446002707261295 	 Accuracy: 0.45161290322580644
Delta: 0.004613392107631234 	  Loss: 1.0445233268818122 	 Accuracy: 0.45161290322580644
Delta: 0.00487781405011346 	  Loss: 1.0444621325421326 	 Accuracy: 0.45161290322580644
Delta: 0.003476613888858086 	  Loss: 1.0444304602948367 	 Accuracy: 0.45161290322580644
Delta: 0.0029397491654783573 	  Loss: 1.0443812138936162 	 Accuracy: 0.45161290322580644
Delta: 0.0020694518828673902 	  Loss: 1.044361812507974 	 Accuracy: 0.45161290322580644
Delta: 0.0024344085545667925 	  Loss: 1.0443547260220192 	 Accuracy: 0.45161290322580644
Delta: 0.00230426381489624 	  Loss: 1.0443310019344718 	 Accuracy: 0.45161290322580644
Delta: 0.0027371370083299523 	  Loss: 1.044300425658959 	 Accuracy: 0.45161290322580644
Delta: 0.0017700115478931002 	  Loss: 1.044269529357585 	 Accuracy: 0.45161290322580644
Delta: 0.0012832534721640373 	  Loss: 1.0442670574404116 	 Accuracy: 0.45161290322580644
Delta: 0.001780557070850795 	  Loss: 1.0442598901773787 	 Accuracy: 0.45161290322580644
Delta: 0.0018520244781170846 	  Loss: 1.0442539341142711 	 Accuracy: 0.45161290322580644
Delta: 0.003390774197940133 	  Loss: 1.0442502506240086 	 Accuracy: 0.45161290322580644
Delta: 0.0029891797973542423 	  Loss: 1.044218495060938 	 Accuracy: 0.45161290322580644
Delta: 0.0027554799007531426 	  Loss: 1.0441915019711823 	 Accuracy: 0.45161290322580644
Delta: 0.002056097206248678 	  Loss: 1.044154468654946 	 Accuracy: 0.45161290322580644
Delta: 0.001252783721840649 	  Loss: 1.0441495499535174 	 Accuracy: 0.45161290322580644
Delta: 0.0012790495448436081 	  Loss: 1.0441460564541443 	 Accuracy: 0.45161290322580644
Delta: 0.0009544731248883485 	  Loss: 1.0441418318036753 	 Accuracy: 0.45161290322580644
Delta: 0.00047490755216113425 	  Loss: 1.0441437926175465 	 Accuracy: 0.45161290322580644
Delta: 0.0005379336354368859 	  Loss: 1.0441414579707171 	 Accuracy: 0.45161290322580644
Delta: 0.0005595946018194685 	  Loss: 1.0441396520060509 	 Accuracy: 0.45161290322580644
Delta: 0.0001552796278328169 	  Loss: 1.0441351745435095 	 Accuracy: 0.45161290322580644
Delta: 8.12576984705657e-05 	  Loss: 1.0441348832117872 	 Accuracy: 0.45161290322580644
Delta: 2.5930730725451933e-05 	  Loss: 1.0441345855994437 	 Accuracy: 0.45161290322580644
Delta: 0.0001295837714078264 	  Loss: 1.0441345399416333 	 Accuracy: 0.45161290322580644
converged at iter  59
Delta: 0.04587783912393098 	  Loss: 1.0825994283919187 	 Accuracy: 0.5645161290322581
Delta: 0.04226670090847076 	  Loss: 1.0797659984298718 	 Accuracy: 0.5161290322580645
Delta: 0.03351074968634143 	  Loss: 1.0725529398919629 	 Accuracy: 0.3870967741935484

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02946236421167802 	  Loss: 1.06483825787238 	 Accuracy: 0.3548387096774194
Delta: 0.021982000077897433 	  Loss: 1.061282594753969 	 Accuracy: 0.3548387096774194
Delta: 0.01578796306414356 	  Loss: 1.0598173133215967 	 Accuracy: 0.3709677419354839
Delta: 0.014134608347874247 	  Loss: 1.0591564844795958 	 Accuracy: 0.3709677419354839
Delta: 0.012468897858870216 	  Loss: 1.0585128116337748 	 Accuracy: 0.3709677419354839
Delta: 0.010822202432855012 	  Loss: 1.0581909934065168 	 Accuracy: 0.3709677419354839
Delta: 0.008149356539610473 	  Loss: 1.0579199256372007 	 Accuracy: 0.3709677419354839
Delta: 0.00817076135506207 	  Loss: 1.05772161616111 	 Accuracy: 0.3709677419354839
Delta: 0.007119319134914124 	  Loss: 1.05753644916732 	 Accuracy: 0.3709677419354839
Delta: 0.0060802123850674595 	  Loss: 1.0573714856494085 	 Accuracy: 0.3709677419354839
Delta: 0.005191394740667822 	  Loss: 1.0572467709802447 	 Accuracy: 0.3709677419354839
Delta: 0.003991939983647118 	  Loss: 1.0571753108805897 	 Accuracy: 0.3709677419354839
Delta: 0.003931707626547768 	  Loss: 1.057126834267873 	 Accuracy: 0.3709677419354839
Delta: 0.0033613910555930623 	  Loss: 1.057059680642419 	 Accuracy: 0.3709677419354839
Delta: 0.003298045622542551 	  Loss: 1.0570233973853589 	 Accuracy: 0.3709677419354839
Delta: 0.003232689105769574 	  Loss: 1.0570302717939326 	 Accuracy: 0.3709677419354839
Delta: 0.0029709303830096237 	  Loss: 1.0570331078713957 	 Accuracy: 0.3709677419354839
Delta: 0.0033673674081010694 	  Loss: 1.0569902190779326 	 Accuracy: 0.3709677419354839
Delta: 0.004098101556491127 	  Loss: 1.056944087759904 	 Accuracy: 0.3709677419354839
Delta: 0.003248075526070044 	  Loss: 1.0568935402987314 	 Accuracy: 0.3709677419354839
Delta: 0.0034642755384766822 	  Loss: 1.0568654233042085 	 Accuracy: 0.3709677419354839
Delta: 0.003216831989914682 	  Loss: 1.0568090330102913 	 Accuracy: 0.3709677419354839
Delta: 0.0034810761150931195 	  Loss: 1.05678362022135 	 Accuracy: 0.3709677419354839
Delta: 0.0032276686862236365 	  Loss: 1.0567766569679011 	 Accuracy: 0.3709677419354839
Delta: 0.0030662990973789367 	  Loss: 1.0567333836813655 	 Accuracy: 0.3709677419354839
Delta: 0.0027842774914573925 	  Loss: 1.0566925296381358 	 Accuracy: 0.3709677419354839
Delta: 0.0030204189224812585 	  Loss: 1.0566660874348743 	 Accuracy: 0.3709677419354839
Delta: 0.00437433181641833 	  Loss: 1.0566515876452693 	 Accuracy: 0.3709677419354839
Delta: 0.00438369074031745 	  Loss: 1.0565836776463498 	 Accuracy: 0.3709677419354839
Delta: 0.004583471627048927 	  Loss: 1.0564970573974413 	 Accuracy: 0.3709677419354839
Delta: 0.004654658302155026 	  Loss: 1.0563961888175903 	 Accuracy: 0.3709677419354839
Delta: 0.004607930231813688 	  Loss: 1.056305780436793 	 Accuracy: 0.3709677419354839
Delta: 0.0045026743603767015 	  Loss: 1.0562154592019262 	 Accuracy: 0.3709677419354839
Delta: 0.00492276697359329 	  Loss: 1.0561437835694 	 Accuracy: 0.3709677419354839
Delta: 0.005227927284155217 	  Loss: 1.0560470011309186 	 Accuracy: 0.3709677419354839
Delta: 0.004975002788907468 	  Loss: 1.0559497848715378 	 Accuracy: 0.3709677419354839
Delta: 0.004791968484647523 	  Loss: 1.0558627220668984 	 Accuracy: 0.3709677419354839
Delta: 0.004748765581692189 	  Loss: 1.0558049670179859 	 Accuracy: 0.3709677419354839
Delta: 0.004287481911820393 	  Loss: 1.0557666002407262 	 Accuracy: 0.3709677419354839
Delta: 0.004306778194434432 	  Loss: 1.055692352550321 	 Accuracy: 0.3709677419354839
Delta: 0.0051037363738070905 	  Loss: 1.0556452289102798 	 Accuracy: 0.3709677419354839
Delta: 0.003601312007337607 	  Loss: 1.055577953733899 	 Accuracy: 0.3709677419354839
Delta: 0.003915929521908046 	  Loss: 1.0555267684213308 	 Accuracy: 0.3709677419354839
Delta: 0.004371172758377216 	  Loss: 1.055429085444652 	 Accuracy: 0.3709677419354839
Delta: 0.003998723063433798 	  Loss: 1.0553499688237111 	 Accuracy: 0.3709677419354839
Delta: 0.004178540670147889 	  Loss: 1.0552958589193315 	 Accuracy: 0.3709677419354839
Delta: 0.0030972285955501227 	  Loss: 1.0552692277709308 	 Accuracy: 0.3709677419354839
Delta: 0.002664129780770512 	  Loss: 1.0552790545149309 	 Accuracy: 0.3709677419354839
Delta: 0.0025794610625477082 	  Loss: 1.055296942974794 	 Accuracy: 0.3709677419354839
Delta: 0.0030470922840929488 	  Loss: 1.055297220678059 	 Accuracy: 0.3709677419354839
Delta: 0.0020644793505985477 	  Loss: 1.0552765845911598 	 Accuracy: 0.3709677419354839
Delta: 0.002062597899905578 	  Loss: 1.055279666951863 	 Accuracy: 0.3709677419354839
Delta: 0.00211723750732569 	  Loss: 1.0552640436469558 	 Accuracy: 0.3709677419354839
Delta: 0.0021713215602492952 	  Loss: 1.0552511889596832 	 Accuracy: 0.3709677419354839
Delta: 0.002544813040289295 	  Loss: 1.0552422365527434 	 Accuracy: 0.3709677419354839
Delta: 0.0024767220177742107 	  Loss: 1.0552428911907001 	 Accuracy: 0.3709677419354839
Delta: 0.0022545191759061967 	  Loss: 1.0552329389548152 	 Accuracy: 0.3709677419354839
Delta: 0.001671935635269634 	  Loss: 1.0552193248616266 	 Accuracy: 0.3709677419354839
Delta: 0.0013453682820611132 	  Loss: 1.0552187519807372 	 Accuracy: 0.3709677419354839
Delta: 0.0006835348866086004 	  Loss: 1.0552083559978453 	 Accuracy: 0.3709677419354839
Delta: 0.00029758075590904107 	  Loss: 1.055210458774189 	 Accuracy: 0.3709677419354839
Delta: 0.0004541929592765615 	  Loss: 1.055209428709655 	 Accuracy: 0.3709677419354839
Delta: 0.0005104921319862607 	  Loss: 1.0552083794705602 	 Accuracy: 0.3709677419354839
Delta: 0.00044780247310657114 	  Loss: 1.0552039885016504 	 Accuracy: 0.3709677419354839
Delta: 0.0004404041347152544 	  Loss: 1.0552036738253079 	 Accuracy: 0.3709677419354839
Delta: 0.0004990114630469228 	  Loss: 1.0551981045673857 	 Accuracy: 0.3709677419354839
Delta: 0.00046204852095735533 	  Loss: 1.0551987025185026 	 Accuracy: 0.3709677419354839
Delta: 0.00029087130815432763 	  Loss: 1.055197462098763 	 Accuracy: 0.3709677419354839
Delta: 0.00025248232569580003 	  Loss: 1.0551972953688344 	 Accuracy: 0.3709677419354839
Delta: 0.0002823079681974152 	  Loss: 1.0551980802647556 	 Accuracy: 0.3709677419354839
Delta: 5.9742989660272784e-05 	  Loss: 1.0551997358699343 	 Accuracy: 0.3709677419354839
Delta: 3.4753868124808113e-06 	  Loss: 1.0552001198980876 	 Accuracy: 0.3709677419354839
Delta: 2.6791528267356197e-13 	  Loss: 1.055200119897945 	 Accuracy: 0.3709677419354839
converged at iter  75
Delta: 0.04785847879797748 	  Loss: 1.0867841665546085 	 Accuracy: 0.31746031746031744
Delta: 0.03992652948776741 	  Loss: 1.0721280171544485 	 Accuracy: 0.2857142857142857
Delta: 0.03475805048231413 	  Loss: 1.0651981997099882 	 Accuracy: 0.20634920634920634
Delta: 0.029754869705557654 	  Loss: 1.060906920145682 	 Accuracy: 0.20634920634920634
Delta: 0.025218364182264814 	  Loss: 1.0576987195469707 	 Accuracy: 0.2222222222222222
Delta: 0.022001601958362788 	  Loss: 1.0552872310340304 	 Accuracy: 0.23809523809523808
Delta: 0.02003743360181089 	  Loss: 1.0533356261480025 	 Accuracy: 0.23809523809523808
Delta: 0.017969881219672353 	  Loss: 1.0519059457040365 	 Accuracy: 0.2698412698412698
Delta: 0.016943943410530495 	  Loss: 1.0507018525514134 	 Accuracy: 0.2698412698412698
Delta: 0.016777218132483753 	  Loss: 1.0496579715169303 	 Accuracy: 0.2698412698412698
Delta: 0.015873231416833923 	  Loss: 1.0487389331723622 	 Accuracy: 0.2698412698412698

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.012506643537488269 	  Loss: 1.0478174369653213 	 Accuracy: 0.2698412698412698
Delta: 0.010401789440714782 	  Loss: 1.0471979247006358 	 Accuracy: 0.2698412698412698
Delta: 0.008488286298730262 	  Loss: 1.046755173079144 	 Accuracy: 0.2698412698412698
Delta: 0.007652970228544975 	  Loss: 1.0466017948781259 	 Accuracy: 0.2698412698412698
Delta: 0.00797954958868649 	  Loss: 1.0465051224366373 	 Accuracy: 0.2698412698412698
Delta: 0.006430424526485775 	  Loss: 1.046377058894842 	 Accuracy: 0.2698412698412698
Delta: 0.004717721252910264 	  Loss: 1.0462358308395339 	 Accuracy: 0.2698412698412698
Delta: 0.00498156176878208 	  Loss: 1.046178690365375 	 Accuracy: 0.2698412698412698
Delta: 0.004498402134766122 	  Loss: 1.0460897932814515 	 Accuracy: 0.2698412698412698
Delta: 0.0031456098795306087 	  Loss: 1.0460328116379114 	 Accuracy: 0.2698412698412698
Delta: 0.0027279502071986973 	  Loss: 1.0460181290117934 	 Accuracy: 0.2698412698412698
Delta: 0.00281777019999864 	  Loss: 1.0459897237690152 	 Accuracy: 0.2698412698412698
Delta: 0.0027140478357710845 	  Loss: 1.0459782000933473 	 Accuracy: 0.2698412698412698
Delta: 0.00259211570215341 	  Loss: 1.0459410048240867 	 Accuracy: 0.2698412698412698
Delta: 0.002558410062663689 	  Loss: 1.0459321208956656 	 Accuracy: 0.2698412698412698
Delta: 0.0022659263757482968 	  Loss: 1.0459116127906984 	 Accuracy: 0.2698412698412698
Delta: 0.0016173971561359093 	  Loss: 1.0459025486286486 	 Accuracy: 0.2698412698412698
Delta: 0.0017322427225531685 	  Loss: 1.045886425759125 	 Accuracy: 0.2698412698412698
Delta: 0.0012948302857449302 	  Loss: 1.0458822174898539 	 Accuracy: 0.2698412698412698
Delta: 0.001257096188736846 	  Loss: 1.0458797062506537 	 Accuracy: 0.2698412698412698
Delta: 0.0008838198322855675 	  Loss: 1.045865544356949 	 Accuracy: 0.2698412698412698
Delta: 0.001133266701306292 	  Loss: 1.0458568013096698 	 Accuracy: 0.2698412698412698
Delta: 0.0014753620278093451 	  Loss: 1.0458471211087073 	 Accuracy: 0.2698412698412698
Delta: 0.001131410222355911 	  Loss: 1.0458316551353588 	 Accuracy: 0.2698412698412698
Delta: 0.0020076183712818578 	  Loss: 1.0458222340142704 	 Accuracy: 0.2698412698412698
Delta: 0.0013067091853682772 	  Loss: 1.0458130332636195 	 Accuracy: 0.2698412698412698
Delta: 0.001145657542115683 	  Loss: 1.0458099381396897 	 Accuracy: 0.2698412698412698
Delta: 0.0017981111022568525 	  Loss: 1.0458127208548673 	 Accuracy: 0.2698412698412698
Delta: 0.0012169165355467556 	  Loss: 1.045797169298901 	 Accuracy: 0.2698412698412698
Delta: 0.001057898144021924 	  Loss: 1.0457991395899455 	 Accuracy: 0.2698412698412698
Delta: 0.0014224226192237521 	  Loss: 1.045802515746383 	 Accuracy: 0.2698412698412698
Delta: 0.0009921161079569803 	  Loss: 1.0458034393832956 	 Accuracy: 0.2698412698412698
Delta: 0.001046921186898644 	  Loss: 1.045795719999555 	 Accuracy: 0.2698412698412698
Delta: 0.0010609305259264745 	  Loss: 1.0457895281804588 	 Accuracy: 0.2698412698412698
Delta: 0.0012086440721033672 	  Loss: 1.0457874129956646 	 Accuracy: 0.2698412698412698
Delta: 0.0007345601510539651 	  Loss: 1.0457790836667487 	 Accuracy: 0.2698412698412698
Delta: 0.0005994164206880038 	  Loss: 1.0457727649005917 	 Accuracy: 0.2698412698412698
Delta: 0.0005509384080970832 	  Loss: 1.0457773397412748 	 Accuracy: 0.2698412698412698
Delta: 0.0005663546018008497 	  Loss: 1.0457755881298092 	 Accuracy: 0.2698412698412698
Delta: 0.0009481019712247228 	  Loss: 1.0457714962114015 	 Accuracy: 0.2698412698412698
Delta: 0.00028990217633719894 	  Loss: 1.0457700386785376 	 Accuracy: 0.2698412698412698
Delta: 0.0009139154809691297 	  Loss: 1.0457729601930321 	 Accuracy: 0.2698412698412698
Delta: 0.0010999099244248904 	  Loss: 1.0457776820645186 	 Accuracy: 0.2698412698412698
Delta: 0.0012005983759911718 	  Loss: 1.0457815081160076 	 Accuracy: 0.2698412698412698
Delta: 0.0013923317394949118 	  Loss: 1.0457727268977701 	 Accuracy: 0.2698412698412698
Delta: 0.0008403662154125671 	  Loss: 1.0457713307391048 	 Accuracy: 0.2698412698412698
Delta: 0.0006728727176846578 	  Loss: 1.0457704109922403 	 Accuracy: 0.2698412698412698
Delta: 0.000809610139992977 	  Loss: 1.0457683625550858 	 Accuracy: 0.2698412698412698
Delta: 0.0009205604806818007 	  Loss: 1.0457677903618126 	 Accuracy: 0.2698412698412698
Delta: 0.0011054987787507498 	  Loss: 1.0457785704371005 	 Accuracy: 0.2698412698412698
Delta: 0.0011195724670805564 	  Loss: 1.045790219210185 	 Accuracy: 0.2698412698412698
Delta: 0.0012734340539249254 	  Loss: 1.0458038910295258 	 Accuracy: 0.2698412698412698
Delta: 0.0016367737333030893 	  Loss: 1.0458024831009995 	 Accuracy: 0.2698412698412698
Delta: 0.0015550662419145024 	  Loss: 1.0458067036845053 	 Accuracy: 0.2698412698412698
Delta: 0.0011174608969875153 	  Loss: 1.0457883356453141 	 Accuracy: 0.2698412698412698
Delta: 0.0011864400278346916 	  Loss: 1.045774906985375 	 Accuracy: 0.2698412698412698
Delta: 0.000881407892944295 	  Loss: 1.0457603745334647 	 Accuracy: 0.2698412698412698
Delta: 0.0010942335675045729 	  Loss: 1.045756530747195 	 Accuracy: 0.2698412698412698
Delta: 0.0009540127576737498 	  Loss: 1.045752747662191 	 Accuracy: 0.2698412698412698
Delta: 0.00030658969278102115 	  Loss: 1.0457560189924586 	 Accuracy: 0.2698412698412698
Delta: 0.0006238906190990976 	  Loss: 1.0457566875216273 	 Accuracy: 0.2698412698412698
Delta: 0.000297779231503431 	  Loss: 1.0457608851795943 	 Accuracy: 0.2698412698412698
Delta: 0.0004704536878465481 	  Loss: 1.0457618920364489 	 Accuracy: 0.2698412698412698
Delta: 0.00047243213079570435 	  Loss: 1.0457633083244027 	 Accuracy: 0.2698412698412698
Delta: 0.00022478277960639932 	  Loss: 1.0457633890155082 	 Accuracy: 0.2698412698412698
converged at iter  75
Delta: 0.04891343533792365 	  Loss: 1.0657226377750542 	 Accuracy: 0.14285714285714285
Delta: 0.0361724501535337 	  Loss: 1.0537944118801854 	 Accuracy: 0.14285714285714285
Delta: 0.035191426779780446 	  Loss: 1.0472302455041214 	 Accuracy: 0.15873015873015872
Delta: 0.02911157985654339 	  Loss: 1.0446534686379474 	 Accuracy: 0.1746031746031746
Delta: 0.025465757838777966 	  Loss: 1.043457624891402 	 Accuracy: 0.20634920634920634
Delta: 0.0217350367568798 	  Loss: 1.0417907894197018 	 Accuracy: 0.20634920634920634
Delta: 0.017449060122335734 	  Loss: 1.0400947455316554 	 Accuracy: 0.20634920634920634
Delta: 0.017682060949610164 	  Loss: 1.038986015202442 	 Accuracy: 0.2222222222222222

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.015354141407834013 	  Loss: 1.0375911060394172 	 Accuracy: 0.23809523809523808
Delta: 0.013975799802560399 	  Loss: 1.0364032679084607 	 Accuracy: 0.23809523809523808
Delta: 0.010374150113829528 	  Loss: 1.0356710547136316 	 Accuracy: 0.23809523809523808
Delta: 0.007975434201997146 	  Loss: 1.035301685957389 	 Accuracy: 0.23809523809523808
Delta: 0.006200473861672742 	  Loss: 1.0350116655998074 	 Accuracy: 0.23809523809523808
Delta: 0.004537890002973925 	  Loss: 1.0348815115948913 	 Accuracy: 0.23809523809523808
Delta: 0.0035044776596083425 	  Loss: 1.0348075388299187 	 Accuracy: 0.23809523809523808
Delta: 0.003305791312838066 	  Loss: 1.034751495806436 	 Accuracy: 0.23809523809523808
Delta: 0.0027596343001646297 	  Loss: 1.0346890870766658 	 Accuracy: 0.23809523809523808
Delta: 0.00282618974721906 	  Loss: 1.034640986772052 	 Accuracy: 0.23809523809523808
Delta: 0.002873427370299726 	  Loss: 1.0345966546585408 	 Accuracy: 0.23809523809523808
Delta: 0.0027417290602923714 	  Loss: 1.034544178544743 	 Accuracy: 0.23809523809523808
Delta: 0.0026486803231460694 	  Loss: 1.0345021555061975 	 Accuracy: 0.23809523809523808
Delta: 0.00262407620462014 	  Loss: 1.0344736119861202 	 Accuracy: 0.23809523809523808
Delta: 0.0021355780017723552 	  Loss: 1.0344206462359629 	 Accuracy: 0.23809523809523808
Delta: 0.0022298161869057937 	  Loss: 1.0343980988317116 	 Accuracy: 0.23809523809523808
Delta: 0.0024857147764950132 	  Loss: 1.034364804098999 	 Accuracy: 0.23809523809523808
Delta: 0.0015463227331259438 	  Loss: 1.0343434004385528 	 Accuracy: 0.23809523809523808
Delta: 0.001637061495184648 	  Loss: 1.0343235960441537 	 Accuracy: 0.23809523809523808
Delta: 0.0007204320595053106 	  Loss: 1.0342977196522973 	 Accuracy: 0.23809523809523808
Delta: 0.0006097699210849017 	  Loss: 1.0342870136768467 	 Accuracy: 0.23809523809523808
Delta: 0.00016481659863341996 	  Loss: 1.0342825669518123 	 Accuracy: 0.23809523809523808
Delta: 7.944337467463866e-05 	  Loss: 1.0342821891324596 	 Accuracy: 0.23809523809523808
Delta: 2.0187341370899056e-05 	  Loss: 1.0342818440060442 	 Accuracy: 0.23809523809523808
Delta: 1.0895586031182426e-06 	  Loss: 1.0342818037657444 	 Accuracy: 0.23809523809523808
converged at iter  32
Delta: 0.04794680479863749 	  Loss: 1.0750996899748229 	 Accuracy: 0.3387096774193548
Delta: 0.041535432033704175 	  Loss: 1.0671180330103904 	 Accuracy: 0.3064516129032258
Delta: 0.03225997727123306 	  Loss: 1.059701895564972 	 Accuracy: 0.25806451612903225
Delta: 0.030385655038180366 	  Loss: 1.0540110145734902 	 Accuracy: 0.22580645161290322
Delta: 0.02308786330251536 	  Loss: 1.0515186568889598 	 Accuracy: 0.20967741935483872
Delta: 0.019326330413871294 	  Loss: 1.0504230513317327 	 Accuracy: 0.20967741935483872
Delta: 0.014355461736919033 	  Loss: 1.0496375307368644 	 Accuracy: 0.20967741935483872

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.012118587989609502 	  Loss: 1.0491842607741264 	 Accuracy: 0.20967741935483872
Delta: 0.009817199277733987 	  Loss: 1.0488334253700728 	 Accuracy: 0.20967741935483872
Delta: 0.007739739372725919 	  Loss: 1.0487196051377028 	 Accuracy: 0.20967741935483872
Delta: 0.006114439899692183 	  Loss: 1.048602793906956 	 Accuracy: 0.20967741935483872
Delta: 0.006802237118309795 	  Loss: 1.0485514853849014 	 Accuracy: 0.20967741935483872
Delta: 0.007064258806348243 	  Loss: 1.0485156514057223 	 Accuracy: 0.20967741935483872
Delta: 0.005918555610154548 	  Loss: 1.0484503990850103 	 Accuracy: 0.20967741935483872
Delta: 0.00595617653781043 	  Loss: 1.0483607635984185 	 Accuracy: 0.20967741935483872
Delta: 0.005707968617273052 	  Loss: 1.048273925695239 	 Accuracy: 0.20967741935483872
Delta: 0.005546288174347224 	  Loss: 1.0481968165299702 	 Accuracy: 0.20967741935483872
Delta: 0.005129419555368321 	  Loss: 1.048145661614347 	 Accuracy: 0.20967741935483872
Delta: 0.004951368709686375 	  Loss: 1.04810173119276 	 Accuracy: 0.20967741935483872
Delta: 0.004560580386897299 	  Loss: 1.0480421646410123 	 Accuracy: 0.20967741935483872
Delta: 0.004564871796933084 	  Loss: 1.048003881910108 	 Accuracy: 0.20967741935483872
Delta: 0.00501116043159729 	  Loss: 1.047944949054855 	 Accuracy: 0.20967741935483872
Delta: 0.0048236721827741354 	  Loss: 1.0478704600659592 	 Accuracy: 0.20967741935483872
Delta: 0.004715204267243031 	  Loss: 1.0477824325989518 	 Accuracy: 0.20967741935483872
Delta: 0.0036093391455027744 	  Loss: 1.0477060569528025 	 Accuracy: 0.20967741935483872
Delta: 0.0038200718523104435 	  Loss: 1.0476930657428505 	 Accuracy: 0.20967741935483872
Delta: 0.002985082257904748 	  Loss: 1.0476555551465652 	 Accuracy: 0.20967741935483872
Delta: 0.002599675017343923 	  Loss: 1.0476300641592828 	 Accuracy: 0.20967741935483872
Delta: 0.003512640102432535 	  Loss: 1.0476338359176722 	 Accuracy: 0.20967741935483872
Delta: 0.0033928803636351507 	  Loss: 1.0475983686993924 	 Accuracy: 0.20967741935483872
Delta: 0.003142105623321036 	  Loss: 1.0475867724780965 	 Accuracy: 0.20967741935483872
Delta: 0.002757468644356246 	  Loss: 1.047562692479611 	 Accuracy: 0.20967741935483872
Delta: 0.0026092878823487783 	  Loss: 1.0475288377467757 	 Accuracy: 0.20967741935483872
Delta: 0.0025975077098068363 	  Loss: 1.047512438485203 	 Accuracy: 0.20967741935483872
Delta: 0.002238659635795956 	  Loss: 1.0475161059251332 	 Accuracy: 0.20967741935483872
Delta: 0.002094744905295994 	  Loss: 1.047499038931759 	 Accuracy: 0.20967741935483872
Delta: 0.0016603169018346035 	  Loss: 1.0474763945184522 	 Accuracy: 0.20967741935483872
Delta: 0.0017631176069446135 	  Loss: 1.0474737365372278 	 Accuracy: 0.20967741935483872
Delta: 0.0014989698170099902 	  Loss: 1.0474636771881503 	 Accuracy: 0.20967741935483872
Delta: 0.0014648446368634288 	  Loss: 1.0474485145510122 	 Accuracy: 0.20967741935483872
Delta: 0.0012104802609754044 	  Loss: 1.0474388574233449 	 Accuracy: 0.20967741935483872
Delta: 0.001865897791740923 	  Loss: 1.0474358663888905 	 Accuracy: 0.20967741935483872
Delta: 0.0010810980003614274 	  Loss: 1.0474231614765896 	 Accuracy: 0.20967741935483872
Delta: 0.0014080229751535047 	  Loss: 1.0474188959087245 	 Accuracy: 0.20967741935483872
Delta: 0.0011064929005545488 	  Loss: 1.0474174288662952 	 Accuracy: 0.20967741935483872
Delta: 0.0011182936911186265 	  Loss: 1.0474195159788335 	 Accuracy: 0.20967741935483872
Delta: 0.00109957499726116 	  Loss: 1.0474139310953365 	 Accuracy: 0.20967741935483872
Delta: 0.0007209242330867583 	  Loss: 1.0474132949353643 	 Accuracy: 0.20967741935483872
Delta: 0.001307813911838937 	  Loss: 1.047414908252798 	 Accuracy: 0.20967741935483872
Delta: 0.0011848406407107158 	  Loss: 1.0474159229214093 	 Accuracy: 0.20967741935483872
Delta: 0.002020912970064061 	  Loss: 1.0474155839820776 	 Accuracy: 0.20967741935483872
Delta: 0.002814888445354521 	  Loss: 1.0474141587384675 	 Accuracy: 0.20967741935483872
Delta: 0.0019357189456872452 	  Loss: 1.0473860541846247 	 Accuracy: 0.20967741935483872
Delta: 0.0018254644911571765 	  Loss: 1.0473729851963143 	 Accuracy: 0.20967741935483872
Delta: 0.0016095164782937005 	  Loss: 1.0473678441886332 	 Accuracy: 0.20967741935483872
Delta: 0.0009441997027577856 	  Loss: 1.0473536546241518 	 Accuracy: 0.20967741935483872
Delta: 0.0008597588199916328 	  Loss: 1.0473592564415029 	 Accuracy: 0.20967741935483872
Delta: 0.0014385642241900448 	  Loss: 1.0473534433016873 	 Accuracy: 0.20967741935483872
Delta: 0.0007879146969628552 	  Loss: 1.0473545630552332 	 Accuracy: 0.20967741935483872
Delta: 0.001036053934958046 	  Loss: 1.047352746650863 	 Accuracy: 0.20967741935483872
Delta: 0.001816261920081476 	  Loss: 1.0473523786387624 	 Accuracy: 0.20967741935483872
Delta: 0.001200465040890838 	  Loss: 1.047360973954333 	 Accuracy: 0.20967741935483872
Delta: 0.0011886259057419164 	  Loss: 1.0473599097313961 	 Accuracy: 0.20967741935483872
Delta: 0.0007612300732742047 	  Loss: 1.0473554905161375 	 Accuracy: 0.20967741935483872
Delta: 0.0007332060293774419 	  Loss: 1.047357013510074 	 Accuracy: 0.20967741935483872
Delta: 0.0005552211242633071 	  Loss: 1.0473537894519875 	 Accuracy: 0.20967741935483872
Delta: 0.0007431272831946995 	  Loss: 1.0473495971685072 	 Accuracy: 0.20967741935483872
Delta: 0.0007987396614653203 	  Loss: 1.0473517538328612 	 Accuracy: 0.20967741935483872
Delta: 0.0005679336335049838 	  Loss: 1.0473536209289076 	 Accuracy: 0.20967741935483872
Delta: 0.0008714803238923375 	  Loss: 1.0473562097687164 	 Accuracy: 0.20967741935483872
Delta: 0.0006316715779087595 	  Loss: 1.0473619692663994 	 Accuracy: 0.20967741935483872
Delta: 0.0008254750771078884 	  Loss: 1.0473641467612158 	 Accuracy: 0.20967741935483872
Delta: 0.0007088149405093251 	  Loss: 1.047365617250113 	 Accuracy: 0.20967741935483872
Delta: 0.0005187140672613626 	  Loss: 1.0473660926393507 	 Accuracy: 0.20967741935483872
Delta: 0.0003095251352490282 	  Loss: 1.0473639630345721 	 Accuracy: 0.20967741935483872
Delta: 0.00038281520673450695 	  Loss: 1.0473643350088508 	 Accuracy: 0.20967741935483872
Delta: 0.0006942422873036775 	  Loss: 1.0473663268383688 	 Accuracy: 0.20967741935483872
Delta: 0.0003220972198177527 	  Loss: 1.0473671288148951 	 Accuracy: 0.20967741935483872
Delta: 0.0005436638398466158 	  Loss: 1.047369046553594 	 Accuracy: 0.20967741935483872
Delta: 0.0004413087655275211 	  Loss: 1.0473654548743265 	 Accuracy: 0.20967741935483872
Delta: 0.00023515131536106784 	  Loss: 1.047363380602408 	 Accuracy: 0.20967741935483872
Delta: 0.0002694320211335261 	  Loss: 1.0473623217786183 	 Accuracy: 0.20967741935483872
Delta: 0.0003005739652452525 	  Loss: 1.0473624351821178 	 Accuracy: 0.20967741935483872
Delta: 0.0005429126361035803 	  Loss: 1.0473632285510668 	 Accuracy: 0.20967741935483872
Delta: 0.0003692123063670928 	  Loss: 1.0473645155344964 	 Accuracy: 0.20967741935483872
Delta: 0.0006294297513892202 	  Loss: 1.0473658098326653 	 Accuracy: 0.20967741935483872
Delta: 0.0006485518460870058 	  Loss: 1.0473641796948099 	 Accuracy: 0.20967741935483872
Delta: 0.0006019964449402948 	  Loss: 1.0473617666609698 	 Accuracy: 0.20967741935483872
Delta: 0.0010736802750419409 	  Loss: 1.047360144308389 	 Accuracy: 0.20967741935483872
Delta: 0.0006724679044583348 	  Loss: 1.047352992239095 	 Accuracy: 0.20967741935483872
Delta: 0.0003968967737385534 	  Loss: 1.047348688724755 	 Accuracy: 0.20967741935483872
Delta: 0.00032244685411294936 	  Loss: 1.0473452247775195 	 Accuracy: 0.20967741935483872
Delta: 0.0002884030632103689 	  Loss: 1.0473493053581229 	 Accuracy: 0.20967741935483872
Delta: 0.00040768161234409987 	  Loss: 1.0473493691713969 	 Accuracy: 0.20967741935483872
converged at iter  93
Delta: 0.05011673227447199 	  Loss: 1.067730642834026 	 Accuracy: 0.43548387096774194
Delta: 0.03642257819627166 	  Loss: 1.058463706082641 	 Accuracy: 0.5161290322580645
Delta: 0.0375857476407587 	  Loss: 1.0580021111867794 	 Accuracy: 0.3387096774193548
Delta: 0.03312042581101487 	  Loss: 1.0572345450872018 	 Accuracy: 0.3387096774193548
Delta: 0.02556022684458589 	  Loss: 1.0550117521102962 	 Accuracy: 0.3387096774193548

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02019073544454236 	  Loss: 1.0527070603451905 	 Accuracy: 0.3387096774193548
Delta: 0.011339676600309214 	  Loss: 1.0515540795922798 	 Accuracy: 0.3387096774193548
Delta: 0.008168809104711735 	  Loss: 1.0511263370947326 	 Accuracy: 0.3387096774193548
Delta: 0.007446712533264354 	  Loss: 1.0508397614835094 	 Accuracy: 0.3387096774193548
Delta: 0.0061857424732138285 	  Loss: 1.0506484198396064 	 Accuracy: 0.3387096774193548
Delta: 0.00453771356172721 	  Loss: 1.050537033281874 	 Accuracy: 0.3387096774193548
Delta: 0.0038723301397545363 	  Loss: 1.050493836261882 	 Accuracy: 0.3387096774193548
Delta: 0.0049806411244146314 	  Loss: 1.0504330190836022 	 Accuracy: 0.3387096774193548
Delta: 0.005817552317022634 	  Loss: 1.0503816053146335 	 Accuracy: 0.3387096774193548
Delta: 0.005968148040513042 	  Loss: 1.050286770865317 	 Accuracy: 0.3387096774193548
Delta: 0.006095527846982374 	  Loss: 1.0501249174741178 	 Accuracy: 0.3387096774193548
Delta: 0.005352791578856165 	  Loss: 1.0499683247409242 	 Accuracy: 0.3387096774193548
Delta: 0.004806626670941523 	  Loss: 1.0498715816686652 	 Accuracy: 0.3387096774193548
Delta: 0.00426396044475891 	  Loss: 1.0497921522236306 	 Accuracy: 0.3387096774193548
Delta: 0.005250190239077209 	  Loss: 1.049722844511224 	 Accuracy: 0.3387096774193548
Delta: 0.0038958521476651605 	  Loss: 1.0496451999273626 	 Accuracy: 0.3387096774193548
Delta: 0.0037619190884384543 	  Loss: 1.0495898856330714 	 Accuracy: 0.3387096774193548
Delta: 0.004021615702311432 	  Loss: 1.0495657298958878 	 Accuracy: 0.3387096774193548
Delta: 0.004342958421474899 	  Loss: 1.0495497538057819 	 Accuracy: 0.3387096774193548
Delta: 0.004802261529047144 	  Loss: 1.0495215404317126 	 Accuracy: 0.3387096774193548
Delta: 0.0045964502909817675 	  Loss: 1.0494869547427368 	 Accuracy: 0.3387096774193548
Delta: 0.005001275827842501 	  Loss: 1.0494230708394428 	 Accuracy: 0.3387096774193548
Delta: 0.0038831106483691305 	  Loss: 1.0493812486412673 	 Accuracy: 0.3387096774193548
Delta: 0.004055683757734752 	  Loss: 1.0493785320207047 	 Accuracy: 0.3387096774193548
Delta: 0.002646720558030893 	  Loss: 1.0493592087133563 	 Accuracy: 0.3387096774193548
Delta: 0.0028218558897464756 	  Loss: 1.0493508982803874 	 Accuracy: 0.3387096774193548
Delta: 0.0036616091006934177 	  Loss: 1.0493415966155473 	 Accuracy: 0.3387096774193548
Delta: 0.0032481062628192028 	  Loss: 1.0493275310008583 	 Accuracy: 0.3387096774193548
Delta: 0.0025725377810437156 	  Loss: 1.0493086160584018 	 Accuracy: 0.3387096774193548
Delta: 0.00207284854125876 	  Loss: 1.0493063996748235 	 Accuracy: 0.3387096774193548
Delta: 0.0024862539922205435 	  Loss: 1.0493035696639388 	 Accuracy: 0.3387096774193548
Delta: 0.003089423293267863 	  Loss: 1.0492864858987794 	 Accuracy: 0.3387096774193548
Delta: 0.002407821301861275 	  Loss: 1.0492625406835714 	 Accuracy: 0.3387096774193548
Delta: 0.0025062018624633178 	  Loss: 1.0492426457377078 	 Accuracy: 0.3387096774193548
Delta: 0.0025933969801969175 	  Loss: 1.0492359767884014 	 Accuracy: 0.3387096774193548
Delta: 0.0034345790673239607 	  Loss: 1.0492157997576794 	 Accuracy: 0.3387096774193548
Delta: 0.002465571012556288 	  Loss: 1.0491871850682681 	 Accuracy: 0.3387096774193548
Delta: 0.0022769408965858644 	  Loss: 1.0491917001958975 	 Accuracy: 0.3387096774193548
Delta: 0.0018124377679192487 	  Loss: 1.0491818367008778 	 Accuracy: 0.3387096774193548
Delta: 0.0013952712122581217 	  Loss: 1.0491552499647492 	 Accuracy: 0.3387096774193548
Delta: 0.0007654356767786399 	  Loss: 1.0491432251625685 	 Accuracy: 0.3387096774193548
Delta: 0.0013280746280338548 	  Loss: 1.0491411808083866 	 Accuracy: 0.3387096774193548
Delta: 0.0012092961305945138 	  Loss: 1.0491343337754873 	 Accuracy: 0.3387096774193548
Delta: 0.0022215638473605916 	  Loss: 1.0491310417295625 	 Accuracy: 0.3387096774193548
Delta: 0.0026024676305298425 	  Loss: 1.049122164176835 	 Accuracy: 0.3387096774193548
Delta: 0.0028476456593843867 	  Loss: 1.0491309332940932 	 Accuracy: 0.3387096774193548
Delta: 0.0033872275434731693 	  Loss: 1.0491270431751236 	 Accuracy: 0.3387096774193548
Delta: 0.0034634436510556435 	  Loss: 1.0491105131171214 	 Accuracy: 0.3387096774193548
Delta: 0.0032040424983162254 	  Loss: 1.0491115599558178 	 Accuracy: 0.3387096774193548
Delta: 0.002049340123312669 	  Loss: 1.0490917203486445 	 Accuracy: 0.3387096774193548
Delta: 0.0020348261036215835 	  Loss: 1.0490959251514829 	 Accuracy: 0.3387096774193548
Delta: 0.002473553198851527 	  Loss: 1.0490900513495987 	 Accuracy: 0.3387096774193548
Delta: 0.002627943511930698 	  Loss: 1.049076860793889 	 Accuracy: 0.3387096774193548
Delta: 0.0036302360606550333 	  Loss: 1.0490484710236307 	 Accuracy: 0.3387096774193548
Delta: 0.004110153147560897 	  Loss: 1.0490119204982475 	 Accuracy: 0.3387096774193548
Delta: 0.0036010221092009414 	  Loss: 1.0489797809077448 	 Accuracy: 0.3387096774193548
Delta: 0.002915498486381855 	  Loss: 1.048928938993077 	 Accuracy: 0.3387096774193548
Delta: 0.0028924045574681362 	  Loss: 1.0488948174483381 	 Accuracy: 0.3387096774193548
Delta: 0.002820620111935426 	  Loss: 1.0488680762702898 	 Accuracy: 0.3387096774193548
Delta: 0.003163141447666898 	  Loss: 1.0488333390607045 	 Accuracy: 0.3387096774193548
Delta: 0.003386311798880847 	  Loss: 1.048831375235258 	 Accuracy: 0.3387096774193548
Delta: 0.003652576431846149 	  Loss: 1.0488415874369892 	 Accuracy: 0.3387096774193548
Delta: 0.003016685143746574 	  Loss: 1.048797950356748 	 Accuracy: 0.3387096774193548
Delta: 0.002490196504315085 	  Loss: 1.0487694264411893 	 Accuracy: 0.3387096774193548
Delta: 0.00275900414781159 	  Loss: 1.0487474770675833 	 Accuracy: 0.3387096774193548
Delta: 0.002542898551776121 	  Loss: 1.0487369637196269 	 Accuracy: 0.3387096774193548
Delta: 0.0018588015868691527 	  Loss: 1.0487405307718198 	 Accuracy: 0.3387096774193548
Delta: 0.0020436588997713055 	  Loss: 1.0487554222538862 	 Accuracy: 0.3387096774193548
Delta: 0.0024742053923580286 	  Loss: 1.0487673692286648 	 Accuracy: 0.3387096774193548
Delta: 0.0022213571860938384 	  Loss: 1.0487652412713948 	 Accuracy: 0.3387096774193548
Delta: 0.0026044604509701526 	  Loss: 1.0487705286454745 	 Accuracy: 0.3387096774193548
Delta: 0.0022360512917029268 	  Loss: 1.048746922655364 	 Accuracy: 0.3387096774193548
Delta: 0.0017056970001855644 	  Loss: 1.048737422047437 	 Accuracy: 0.3387096774193548
Delta: 0.001428705540111862 	  Loss: 1.0487257209801977 	 Accuracy: 0.3387096774193548
Delta: 0.0017582992889599296 	  Loss: 1.0487213865399614 	 Accuracy: 0.3387096774193548
Delta: 0.0015834727663795035 	  Loss: 1.0487231388776461 	 Accuracy: 0.3387096774193548
Delta: 0.0014531063089117278 	  Loss: 1.048726033087887 	 Accuracy: 0.3387096774193548
Delta: 0.002284370850160001 	  Loss: 1.0487327635568393 	 Accuracy: 0.3387096774193548
Delta: 0.002033371136047436 	  Loss: 1.0487257301368704 	 Accuracy: 0.3387096774193548
Delta: 0.0022533685348961425 	  Loss: 1.0487171665259982 	 Accuracy: 0.3387096774193548
Delta: 0.0032142110990262297 	  Loss: 1.0486991064545628 	 Accuracy: 0.3387096774193548
Delta: 0.002827791421462459 	  Loss: 1.0486981100492847 	 Accuracy: 0.3387096774193548
Delta: 0.0034884411590873836 	  Loss: 1.0486975761397763 	 Accuracy: 0.3387096774193548
Delta: 0.003489705523023528 	  Loss: 1.0486685746189397 	 Accuracy: 0.3387096774193548
Delta: 0.003436546562395443 	  Loss: 1.0486756504347179 	 Accuracy: 0.3387096774193548
Delta: 0.002897297322218557 	  Loss: 1.048648165263632 	 Accuracy: 0.3387096774193548
Delta: 0.002979556768698724 	  Loss: 1.0486383071690695 	 Accuracy: 0.3387096774193548
Delta: 0.0031034017549988763 	  Loss: 1.0486147546090767 	 Accuracy: 0.3387096774193548
Delta: 0.002164820353943975 	  Loss: 1.0485692941849598 	 Accuracy: 0.3387096774193548
Delta: 0.002297195942088055 	  Loss: 1.0485654146481378 	 Accuracy: 0.3387096774193548
Delta: 0.0019425109121998017 	  Loss: 1.0485809031377389 	 Accuracy: 0.3387096774193548
Delta: 0.002032669450344374 	  Loss: 1.0485787155338055 	 Accuracy: 0.3387096774193548
Delta: 0.001714631354983732 	  Loss: 1.0485806308967793 	 Accuracy: 0.3387096774193548
Delta: 0.0010001068976496655 	  Loss: 1.0485822419125608 	 Accuracy: 0.3387096774193548
Delta: 0.0012124423665195614 	  Loss: 1.048592952716587 	 Accuracy: 0.3387096774193548
Delta: 0.04839877724824644 	  Loss: 1.0808017551735032 	 Accuracy: 0.43548387096774194
Delta: 0.04134876493916028 	  Loss: 1.075437702797972 	 Accuracy: 0.3387096774193548
Delta: 0.03693704977701827 	  Loss: 1.0719720514630369 	 Accuracy: 0.27419354838709675
Delta: 0.027226254506035132 	  Loss: 1.0680769810979671 	 Accuracy: 0.25806451612903225
Delta: 0.022342466055294635 	  Loss: 1.0654602366504415 	 Accuracy: 0.2903225806451613

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.018652254035254293 	  Loss: 1.0635070776927638 	 Accuracy: 0.2903225806451613
Delta: 0.014869014629519577 	  Loss: 1.0622595888544206 	 Accuracy: 0.3064516129032258
Delta: 0.012241238291242589 	  Loss: 1.0614382629561727 	 Accuracy: 0.3064516129032258
Delta: 0.010336041783339307 	  Loss: 1.0608678231385984 	 Accuracy: 0.3064516129032258
Delta: 0.009305749456714371 	  Loss: 1.060356055415709 	 Accuracy: 0.3064516129032258
Delta: 0.009217104738276981 	  Loss: 1.059950345076539 	 Accuracy: 0.3064516129032258
Delta: 0.007490418508975435 	  Loss: 1.0596703761645387 	 Accuracy: 0.3064516129032258
Delta: 0.006282730836665395 	  Loss: 1.059502297608879 	 Accuracy: 0.3064516129032258
Delta: 0.006318133062852419 	  Loss: 1.0593944693330941 	 Accuracy: 0.3064516129032258
Delta: 0.005754204544658646 	  Loss: 1.0593139086786603 	 Accuracy: 0.3064516129032258
Delta: 0.004973765114146057 	  Loss: 1.0592453520511222 	 Accuracy: 0.3064516129032258
Delta: 0.004532349434504294 	  Loss: 1.0591725292876708 	 Accuracy: 0.3064516129032258
Delta: 0.004117813562429461 	  Loss: 1.0591214464296925 	 Accuracy: 0.3064516129032258
Delta: 0.0042146043526898195 	  Loss: 1.0590749602059477 	 Accuracy: 0.3064516129032258
Delta: 0.004172845853822268 	  Loss: 1.059017166871869 	 Accuracy: 0.3064516129032258
Delta: 0.003649253988793181 	  Loss: 1.0589654247929436 	 Accuracy: 0.3064516129032258
Delta: 0.0028576813360195125 	  Loss: 1.0589518861522216 	 Accuracy: 0.3064516129032258
Delta: 0.002669457279748924 	  Loss: 1.058942819027484 	 Accuracy: 0.3064516129032258
Delta: 0.0019710374697501326 	  Loss: 1.0589062403588185 	 Accuracy: 0.3064516129032258
Delta: 0.002257329016911415 	  Loss: 1.0588912889512603 	 Accuracy: 0.3064516129032258
Delta: 0.0022611141442532407 	  Loss: 1.058875753945315 	 Accuracy: 0.3064516129032258
Delta: 0.002328968110623053 	  Loss: 1.0588782449571847 	 Accuracy: 0.3064516129032258
Delta: 0.001938000540824338 	  Loss: 1.0588612814569927 	 Accuracy: 0.3064516129032258
Delta: 0.0011378617406410632 	  Loss: 1.0588556687378259 	 Accuracy: 0.3064516129032258
Delta: 0.0007771733415941083 	  Loss: 1.0588459561126669 	 Accuracy: 0.3064516129032258
Delta: 0.0009313160966732678 	  Loss: 1.0588421470050569 	 Accuracy: 0.3064516129032258
Delta: 0.0018236057652724744 	  Loss: 1.058835281883874 	 Accuracy: 0.3064516129032258
Delta: 0.0028290991527439146 	  Loss: 1.0588148003247797 	 Accuracy: 0.3064516129032258
Delta: 0.002409946313099899 	  Loss: 1.0587990300931602 	 Accuracy: 0.3064516129032258
Delta: 0.002229470709358159 	  Loss: 1.0587818013736734 	 Accuracy: 0.3064516129032258
Delta: 0.0016572515061946825 	  Loss: 1.058770340950094 	 Accuracy: 0.3064516129032258
Delta: 0.001323282482708597 	  Loss: 1.0587560614361577 	 Accuracy: 0.3064516129032258
Delta: 0.0015813916302059626 	  Loss: 1.0587494088433238 	 Accuracy: 0.3064516129032258
Delta: 0.0009634331291140878 	  Loss: 1.0587395783009104 	 Accuracy: 0.3064516129032258
Delta: 0.0011348328480325282 	  Loss: 1.0587313987806517 	 Accuracy: 0.3064516129032258
Delta: 0.0009868380884482583 	  Loss: 1.058712521953319 	 Accuracy: 0.3064516129032258
Delta: 0.0010128089348472172 	  Loss: 1.05870926034653 	 Accuracy: 0.3064516129032258
Delta: 0.002228352572389143 	  Loss: 1.0586982164726968 	 Accuracy: 0.3064516129032258
Delta: 0.002184847041381567 	  Loss: 1.0586904193605888 	 Accuracy: 0.3064516129032258
Delta: 0.0014876700772977233 	  Loss: 1.0586920908188122 	 Accuracy: 0.3064516129032258
Delta: 0.001451359406259933 	  Loss: 1.0586766017297382 	 Accuracy: 0.3064516129032258
Delta: 0.002687299570885105 	  Loss: 1.0586593277455358 	 Accuracy: 0.3064516129032258
Delta: 0.0018599725423880643 	  Loss: 1.058644113602801 	 Accuracy: 0.3064516129032258
Delta: 0.001969691643609776 	  Loss: 1.0586306626410646 	 Accuracy: 0.3064516129032258
Delta: 0.001550892174528811 	  Loss: 1.0586193170551197 	 Accuracy: 0.3064516129032258
Delta: 0.0010277577330085005 	  Loss: 1.0586081614182596 	 Accuracy: 0.3064516129032258
Delta: 0.0009490745500967323 	  Loss: 1.0586023778035625 	 Accuracy: 0.3064516129032258
Delta: 0.0006537780891318228 	  Loss: 1.0585945575577218 	 Accuracy: 0.3064516129032258
Delta: 0.00032758101824430686 	  Loss: 1.0585917622631438 	 Accuracy: 0.3064516129032258
Delta: 0.0003645423679129026 	  Loss: 1.0585912356135916 	 Accuracy: 0.3064516129032258
Delta: 3.495110162775694e-05 	  Loss: 1.058592686498097 	 Accuracy: 0.3064516129032258
Delta: 9.702351228428803e-07 	  Loss: 1.0585926429928594 	 Accuracy: 0.3064516129032258
converged at iter  56
Delta: 0.04851630910812869 	  Loss: 1.0761430143367334 	 Accuracy: 0.38095238095238093
Delta: 0.033967961932590836 	  Loss: 1.0667120742447704 	 Accuracy: 0.4126984126984127
Delta: 0.03230323263809137 	  Loss: 1.0616170401078076 	 Accuracy: 0.38095238095238093
Delta: 0.03052139716769535 	  Loss: 1.060697569777103 	 Accuracy: 0.36507936507936506
Delta: 0.02764246261257771 	  Loss: 1.0596148732501764 	 Accuracy: 0.36507936507936506
Delta: 0.025127328050735392 	  Loss: 1.05750412269389 	 Accuracy: 0.36507936507936506
Delta: 0.022254025013341835 	  Loss: 1.0551304840948599 	 Accuracy: 0.36507936507936506

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01873919262698033 	  Loss: 1.053170092842488 	 Accuracy: 0.36507936507936506
Delta: 0.013815684047044377 	  Loss: 1.052036835513179 	 Accuracy: 0.36507936507936506
Delta: 0.011419304596329512 	  Loss: 1.051345413188793 	 Accuracy: 0.36507936507936506
Delta: 0.008703475457202008 	  Loss: 1.0509166529874077 	 Accuracy: 0.36507936507936506
Delta: 0.007827275364648535 	  Loss: 1.0506605908290962 	 Accuracy: 0.36507936507936506
Delta: 0.007039680717660362 	  Loss: 1.0504301907249678 	 Accuracy: 0.36507936507936506
Delta: 0.006711361938278372 	  Loss: 1.0503666549218833 	 Accuracy: 0.36507936507936506
Delta: 0.006024324042517318 	  Loss: 1.0503358385040231 	 Accuracy: 0.36507936507936506
Delta: 0.004911969396902076 	  Loss: 1.0502772618176404 	 Accuracy: 0.36507936507936506
Delta: 0.004735610509910858 	  Loss: 1.0502111257272555 	 Accuracy: 0.36507936507936506
Delta: 0.004861353125924653 	  Loss: 1.050160274319406 	 Accuracy: 0.36507936507936506
Delta: 0.0048101081776281964 	  Loss: 1.0501068525804826 	 Accuracy: 0.36507936507936506
Delta: 0.005135979286826211 	  Loss: 1.0500195489959974 	 Accuracy: 0.36507936507936506
Delta: 0.004045218066627686 	  Loss: 1.0499480405307007 	 Accuracy: 0.36507936507936506
Delta: 0.004624147971640684 	  Loss: 1.0498991742919093 	 Accuracy: 0.36507936507936506
Delta: 0.004303447230408404 	  Loss: 1.0497989403801944 	 Accuracy: 0.36507936507936506
Delta: 0.0032477682810628816 	  Loss: 1.0497228065051043 	 Accuracy: 0.36507936507936506
Delta: 0.003246308003642391 	  Loss: 1.0496755673010532 	 Accuracy: 0.36507936507936506
Delta: 0.002530415123647302 	  Loss: 1.0496420887717852 	 Accuracy: 0.36507936507936506
Delta: 0.0017011422191746622 	  Loss: 1.0496231371305083 	 Accuracy: 0.36507936507936506
Delta: 0.0016324231047584242 	  Loss: 1.0496199844556906 	 Accuracy: 0.36507936507936506
Delta: 0.002054263310951302 	  Loss: 1.049610257141909 	 Accuracy: 0.36507936507936506
Delta: 0.002672655093695097 	  Loss: 1.0495995641123717 	 Accuracy: 0.36507936507936506
Delta: 0.0015241859145804636 	  Loss: 1.049576399639158 	 Accuracy: 0.36507936507936506
Delta: 0.0013229808759830472 	  Loss: 1.0495821664998692 	 Accuracy: 0.36507936507936506
Delta: 0.000991578112729347 	  Loss: 1.0495772368945406 	 Accuracy: 0.36507936507936506
Delta: 0.0009066053556830633 	  Loss: 1.0495745112415198 	 Accuracy: 0.36507936507936506
Delta: 0.002173590630464827 	  Loss: 1.049573807199013 	 Accuracy: 0.36507936507936506
Delta: 0.002185474046276949 	  Loss: 1.049564530703774 	 Accuracy: 0.36507936507936506
Delta: 0.0018221720826927402 	  Loss: 1.0495626741633033 	 Accuracy: 0.36507936507936506
Delta: 0.0016532803199594821 	  Loss: 1.0495370243807183 	 Accuracy: 0.36507936507936506
Delta: 0.001321147132002584 	  Loss: 1.0495169541715024 	 Accuracy: 0.36507936507936506
Delta: 0.001509588698770224 	  Loss: 1.049503065339891 	 Accuracy: 0.36507936507936506
Delta: 0.0008383115759182751 	  Loss: 1.0495006521953087 	 Accuracy: 0.36507936507936506
Delta: 0.0007175003853592043 	  Loss: 1.0495018984318414 	 Accuracy: 0.36507936507936506
Delta: 0.0015277399264667353 	  Loss: 1.0494953297186866 	 Accuracy: 0.36507936507936506
Delta: 0.002118148003151141 	  Loss: 1.0494892872727108 	 Accuracy: 0.36507936507936506
Delta: 0.0015212557824535024 	  Loss: 1.0494761611440753 	 Accuracy: 0.36507936507936506
Delta: 0.0009908310822810537 	  Loss: 1.04946426834824 	 Accuracy: 0.36507936507936506
Delta: 0.0010033920948711885 	  Loss: 1.0494575827826171 	 Accuracy: 0.36507936507936506
Delta: 0.000957137654410696 	  Loss: 1.049446122195529 	 Accuracy: 0.36507936507936506
Delta: 0.001080766661554869 	  Loss: 1.0494253317904754 	 Accuracy: 0.36507936507936506
Delta: 0.0008087660545350129 	  Loss: 1.0494057441864078 	 Accuracy: 0.36507936507936506
Delta: 0.0009031397873758007 	  Loss: 1.0493962960775796 	 Accuracy: 0.36507936507936506
Delta: 0.0007014246522194144 	  Loss: 1.0493908803370076 	 Accuracy: 0.36507936507936506
Delta: 0.001321630628929564 	  Loss: 1.049389779460492 	 Accuracy: 0.36507936507936506
Delta: 0.0008657496401074449 	  Loss: 1.0493986771315522 	 Accuracy: 0.36507936507936506
Delta: 0.0009435262362896943 	  Loss: 1.0494027668738712 	 Accuracy: 0.36507936507936506
Delta: 0.0013284557933952723 	  Loss: 1.0494044510796892 	 Accuracy: 0.36507936507936506
Delta: 0.001288762042032348 	  Loss: 1.0494031193315654 	 Accuracy: 0.36507936507936506
Delta: 0.0012733192160790344 	  Loss: 1.0493945810131882 	 Accuracy: 0.36507936507936506
Delta: 0.001737629620693499 	  Loss: 1.0493874143133162 	 Accuracy: 0.36507936507936506
Delta: 0.0013138942624594285 	  Loss: 1.0493711872742921 	 Accuracy: 0.36507936507936506
Delta: 0.0011193352493481113 	  Loss: 1.0493622639986127 	 Accuracy: 0.36507936507936506
Delta: 0.00043268109278098567 	  Loss: 1.0493574844232643 	 Accuracy: 0.36507936507936506
Delta: 0.0006440929669155272 	  Loss: 1.0493563171699636 	 Accuracy: 0.36507936507936506
Delta: 0.0002993439710698035 	  Loss: 1.0493594614466608 	 Accuracy: 0.36507936507936506
Delta: 8.541624850725531e-05 	  Loss: 1.0493617251810445 	 Accuracy: 0.36507936507936506
Delta: 4.964076213285702e-06 	  Loss: 1.0493615237166585 	 Accuracy: 0.36507936507936506
Delta: 3.128792512980613e-15 	  Loss: 1.0493615237166583 	 Accuracy: 0.36507936507936506
converged at iter  66
Delta: 0.04955120777167004 	  Loss: 1.0684443351040143 	 Accuracy: 0.5555555555555556
Delta: 0.03592615578822427 	  Loss: 1.0623247030661256 	 Accuracy: 0.49206349206349204
Delta: 0.037925412999066065 	  Loss: 1.0579360456960751 	 Accuracy: 0.4444444444444444
Delta: 0.031905817306328035 	  Loss: 1.0518957055822677 	 Accuracy: 0.4126984126984127
Delta: 0.024307741990869304 	  Loss: 1.048706572028633 	 Accuracy: 0.3968253968253968

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.023042490729631174 	  Loss: 1.0466470677226338 	 Accuracy: 0.3968253968253968
Delta: 0.019812461891038607 	  Loss: 1.0448205564422692 	 Accuracy: 0.3968253968253968
Delta: 0.018093347985416283 	  Loss: 1.0433497894836747 	 Accuracy: 0.3968253968253968
Delta: 0.018871621838009396 	  Loss: 1.0415005897109975 	 Accuracy: 0.3968253968253968
Delta: 0.014498089282713627 	  Loss: 1.0402664352140238 	 Accuracy: 0.3968253968253968
Delta: 0.010699587082149024 	  Loss: 1.0396619737323614 	 Accuracy: 0.3968253968253968
Delta: 0.009702164740402723 	  Loss: 1.03923408347972 	 Accuracy: 0.3968253968253968
Delta: 0.009897283501036375 	  Loss: 1.0389519454660174 	 Accuracy: 0.3968253968253968
Delta: 0.008992922265827142 	  Loss: 1.0387222319292742 	 Accuracy: 0.3968253968253968
Delta: 0.008337421257950742 	  Loss: 1.0383895847628175 	 Accuracy: 0.3968253968253968
Delta: 0.007772984141598282 	  Loss: 1.038068096165884 	 Accuracy: 0.3968253968253968
Delta: 0.007820102997826076 	  Loss: 1.037869924735942 	 Accuracy: 0.3968253968253968
Delta: 0.007201060269280692 	  Loss: 1.0377089413623484 	 Accuracy: 0.3968253968253968
Delta: 0.007203174623380884 	  Loss: 1.0375864920039022 	 Accuracy: 0.3968253968253968
Delta: 0.006177710751671933 	  Loss: 1.0374173370054987 	 Accuracy: 0.3968253968253968
Delta: 0.005843009503297213 	  Loss: 1.037293021450361 	 Accuracy: 0.3968253968253968
Delta: 0.006464063928542791 	  Loss: 1.0371202587641553 	 Accuracy: 0.3968253968253968
Delta: 0.0051051034229171255 	  Loss: 1.0369899540548162 	 Accuracy: 0.3968253968253968
Delta: 0.00601281606290537 	  Loss: 1.0368681525163321 	 Accuracy: 0.3968253968253968
Delta: 0.005612562660537034 	  Loss: 1.0367189535412462 	 Accuracy: 0.3968253968253968
Delta: 0.005579937091097625 	  Loss: 1.0365574250040144 	 Accuracy: 0.3968253968253968
Delta: 0.004742394784519025 	  Loss: 1.0364810639102133 	 Accuracy: 0.3968253968253968
Delta: 0.004334855221945988 	  Loss: 1.0364301736343964 	 Accuracy: 0.3968253968253968
Delta: 0.005496125228972759 	  Loss: 1.0363336041502902 	 Accuracy: 0.3968253968253968
Delta: 0.005512602547356249 	  Loss: 1.0362194570638494 	 Accuracy: 0.3968253968253968
Delta: 0.004469323340526695 	  Loss: 1.0361094237482735 	 Accuracy: 0.3968253968253968
Delta: 0.003973398599060486 	  Loss: 1.0360534503408614 	 Accuracy: 0.3968253968253968
Delta: 0.003562465447743365 	  Loss: 1.0359911778786637 	 Accuracy: 0.3968253968253968
Delta: 0.0030895118451533922 	  Loss: 1.0359583149990566 	 Accuracy: 0.3968253968253968
Delta: 0.0033718865280392973 	  Loss: 1.0359188403538913 	 Accuracy: 0.3968253968253968
Delta: 0.0021739651115300703 	  Loss: 1.0358942578775012 	 Accuracy: 0.3968253968253968
Delta: 0.0018999016978515503 	  Loss: 1.035871842084531 	 Accuracy: 0.3968253968253968
Delta: 0.0013185363047365799 	  Loss: 1.0358619079140916 	 Accuracy: 0.3968253968253968
Delta: 0.0006868012027476899 	  Loss: 1.0358458938255293 	 Accuracy: 0.3968253968253968
Delta: 0.0009381874083800747 	  Loss: 1.035838239160209 	 Accuracy: 0.3968253968253968
Delta: 0.0013844643441259835 	  Loss: 1.0358321034547378 	 Accuracy: 0.3968253968253968
Delta: 0.0015526159153091915 	  Loss: 1.0358258818763506 	 Accuracy: 0.3968253968253968
Delta: 0.00167477698450924 	  Loss: 1.0358110164363286 	 Accuracy: 0.3968253968253968
Delta: 0.001990121578958076 	  Loss: 1.03580263616873 	 Accuracy: 0.3968253968253968
Delta: 0.0019706974356718666 	  Loss: 1.0357908250973307 	 Accuracy: 0.3968253968253968
Delta: 0.0012996489800044544 	  Loss: 1.0357877748922517 	 Accuracy: 0.3968253968253968
Delta: 0.0007410684727295685 	  Loss: 1.035778987997149 	 Accuracy: 0.3968253968253968
Delta: 0.0003670395336442309 	  Loss: 1.0357828433691956 	 Accuracy: 0.3968253968253968
Delta: 0.0003123176683120225 	  Loss: 1.0357827054327122 	 Accuracy: 0.3968253968253968
Delta: 0.0016339508756030093 	  Loss: 1.0357858323023716 	 Accuracy: 0.3968253968253968
Delta: 0.00015470022593217072 	  Loss: 1.0357883954225482 	 Accuracy: 0.3968253968253968
Delta: 2.006976601043889e-05 	  Loss: 1.0357893036750954 	 Accuracy: 0.3968253968253968
Delta: 0.00016374916494721936 	  Loss: 1.0357892642418032 	 Accuracy: 0.3968253968253968
converged at iter  52
Delta: 0.05338021667863495 	  Loss: 1.0730546625009656 	 Accuracy: 0.532258064516129
Delta: 0.04650325663601317 	  Loss: 1.067007378361488 	 Accuracy: 0.5483870967741935
Delta: 0.03772130165579937 	  Loss: 1.0620870317285096 	 Accuracy: 0.5161290322580645

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02725975168219775 	  Loss: 1.0588581154486216 	 Accuracy: 0.5161290322580645
Delta: 0.021748079536254735 	  Loss: 1.056014360117056 	 Accuracy: 0.5161290322580645
Delta: 0.018162366604058136 	  Loss: 1.0537646429457141 	 Accuracy: 0.5161290322580645
Delta: 0.01660351455376435 	  Loss: 1.0518813919214949 	 Accuracy: 0.5161290322580645
Delta: 0.013151762727147345 	  Loss: 1.0505796334889461 	 Accuracy: 0.5161290322580645
Delta: 0.0104452241348599 	  Loss: 1.0497730006174633 	 Accuracy: 0.5161290322580645
Delta: 0.008789748036701633 	  Loss: 1.0492719197952385 	 Accuracy: 0.5161290322580645
Delta: 0.008141461181366369 	  Loss: 1.0488127528660771 	 Accuracy: 0.5161290322580645
Delta: 0.00641696039030782 	  Loss: 1.0485002682988251 	 Accuracy: 0.5161290322580645
Delta: 0.005197193977132125 	  Loss: 1.0483084729924537 	 Accuracy: 0.5161290322580645
Delta: 0.00544058844261735 	  Loss: 1.0481476789403885 	 Accuracy: 0.5161290322580645
Delta: 0.005011037495154006 	  Loss: 1.0480133468428505 	 Accuracy: 0.5161290322580645
Delta: 0.0036565158202894435 	  Loss: 1.0479335353876738 	 Accuracy: 0.5161290322580645
Delta: 0.0033797468070072487 	  Loss: 1.0479168140442765 	 Accuracy: 0.5161290322580645
Delta: 0.00358959136596857 	  Loss: 1.0478761445834521 	 Accuracy: 0.5161290322580645
Delta: 0.004101017806224455 	  Loss: 1.0478581618140896 	 Accuracy: 0.5161290322580645
Delta: 0.0037656164699970077 	  Loss: 1.0478242542642096 	 Accuracy: 0.5161290322580645
Delta: 0.002837998336635483 	  Loss: 1.0477616667555285 	 Accuracy: 0.5161290322580645
Delta: 0.0032956271151611217 	  Loss: 1.0477378254491079 	 Accuracy: 0.5161290322580645
Delta: 0.0036044697653694214 	  Loss: 1.047685743974645 	 Accuracy: 0.5161290322580645
Delta: 0.0027622432764373285 	  Loss: 1.0476416062343428 	 Accuracy: 0.5161290322580645
Delta: 0.0019427123194492566 	  Loss: 1.0476063945296232 	 Accuracy: 0.5161290322580645
Delta: 0.0015711563708655208 	  Loss: 1.0476016618979043 	 Accuracy: 0.5161290322580645
Delta: 0.002170509032076282 	  Loss: 1.0475961769846966 	 Accuracy: 0.5161290322580645
Delta: 0.0016644320683615029 	  Loss: 1.0475828100110396 	 Accuracy: 0.5161290322580645
Delta: 0.0013924921020017356 	  Loss: 1.0475636730614246 	 Accuracy: 0.5161290322580645
Delta: 0.0015567670504551372 	  Loss: 1.0475466441213408 	 Accuracy: 0.5161290322580645
Delta: 0.0015880840714445484 	  Loss: 1.047527031823388 	 Accuracy: 0.5161290322580645
Delta: 0.0016208478856267888 	  Loss: 1.0475067795386603 	 Accuracy: 0.5161290322580645
Delta: 0.0012525034346388994 	  Loss: 1.0474881146424804 	 Accuracy: 0.5161290322580645
Delta: 0.0013967202949056899 	  Loss: 1.0474852233987273 	 Accuracy: 0.5161290322580645
Delta: 0.0028659189352426683 	  Loss: 1.0474758340600798 	 Accuracy: 0.5161290322580645
Delta: 0.002217234597525306 	  Loss: 1.0474577195051489 	 Accuracy: 0.5161290322580645
Delta: 0.00227765691701274 	  Loss: 1.0474487639194456 	 Accuracy: 0.5161290322580645
Delta: 0.002522397323878747 	  Loss: 1.0474200244737706 	 Accuracy: 0.5161290322580645
Delta: 0.0018910669035174781 	  Loss: 1.0474057223195583 	 Accuracy: 0.5161290322580645
Delta: 0.0019090695908509112 	  Loss: 1.0473968155342164 	 Accuracy: 0.5161290322580645
Delta: 0.0007146299717791565 	  Loss: 1.047377340365206 	 Accuracy: 0.5161290322580645
Delta: 0.0004343933657480623 	  Loss: 1.0473771800005596 	 Accuracy: 0.5161290322580645
Delta: 0.0009049004715934801 	  Loss: 1.0473759403357406 	 Accuracy: 0.5161290322580645
Delta: 0.00036686383159623517 	  Loss: 1.0473768417384968 	 Accuracy: 0.5161290322580645
Delta: 0.00022636484835911904 	  Loss: 1.047373014215577 	 Accuracy: 0.5161290322580645
Delta: 0.00012973988254813939 	  Loss: 1.0473724552788264 	 Accuracy: 0.5161290322580645
Delta: 2.455105056679398e-05 	  Loss: 1.0473715755914998 	 Accuracy: 0.5161290322580645
Delta: 4.474149321383066e-05 	  Loss: 1.047371541278193 	 Accuracy: 0.5161290322580645
converged at iter  47
Delta: 0.05097166638142057 	  Loss: 1.0619419770726246 	 Accuracy: 0.5967741935483871
Delta: 0.037553906163652805 	  Loss: 1.053512248321582 	 Accuracy: 0.5967741935483871
Delta: 0.04053572396455665 	  Loss: 1.0525248931397715 	 Accuracy: 0.5806451612903226
Delta: 0.034182152722454756 	  Loss: 1.0502972344089807 	 Accuracy: 0.5806451612903226

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028320691875837967 	  Loss: 1.0459199703683124 	 Accuracy: 0.5806451612903226
Delta: 0.021470117573769126 	  Loss: 1.042562095492302 	 Accuracy: 0.5645161290322581
Delta: 0.014957885577556656 	  Loss: 1.0409739509224352 	 Accuracy: 0.5645161290322581
Delta: 0.011452172648198278 	  Loss: 1.040152913490104 	 Accuracy: 0.5645161290322581
Delta: 0.011623423923396416 	  Loss: 1.0396231256089692 	 Accuracy: 0.5645161290322581
Delta: 0.011597072526012607 	  Loss: 1.0392058006144542 	 Accuracy: 0.5645161290322581
Delta: 0.009871848464592707 	  Loss: 1.0386816812525912 	 Accuracy: 0.5645161290322581
Delta: 0.011026862918173863 	  Loss: 1.0383122370647428 	 Accuracy: 0.5645161290322581
Delta: 0.009754276567479637 	  Loss: 1.0379737270629814 	 Accuracy: 0.5645161290322581
Delta: 0.0075905740419568105 	  Loss: 1.0376620560028862 	 Accuracy: 0.5645161290322581
Delta: 0.006978976911040102 	  Loss: 1.0374937105556281 	 Accuracy: 0.5645161290322581
Delta: 0.006028745192450906 	  Loss: 1.0373774358969117 	 Accuracy: 0.5645161290322581
Delta: 0.0052089563063804556 	  Loss: 1.0372348208959412 	 Accuracy: 0.5645161290322581
Delta: 0.004568470244444985 	  Loss: 1.0370651865353502 	 Accuracy: 0.5645161290322581
Delta: 0.004380477460388265 	  Loss: 1.0370072203007503 	 Accuracy: 0.5645161290322581
Delta: 0.0038551420838864622 	  Loss: 1.036944710210124 	 Accuracy: 0.5645161290322581
Delta: 0.0028433414733008825 	  Loss: 1.0369247187104564 	 Accuracy: 0.5645161290322581
Delta: 0.002537661006675024 	  Loss: 1.0369011404586876 	 Accuracy: 0.5645161290322581
Delta: 0.0022491081810648004 	  Loss: 1.036870449798121 	 Accuracy: 0.5645161290322581
Delta: 0.00234443588277372 	  Loss: 1.0368383602438653 	 Accuracy: 0.5645161290322581
Delta: 0.002104509579039008 	  Loss: 1.036786384456277 	 Accuracy: 0.5645161290322581
Delta: 0.0023871261781065454 	  Loss: 1.0367559936217672 	 Accuracy: 0.5645161290322581
Delta: 0.0023247352591998943 	  Loss: 1.036722607541762 	 Accuracy: 0.5645161290322581
Delta: 0.003046443032861191 	  Loss: 1.036697744130728 	 Accuracy: 0.5645161290322581
Delta: 0.0023056491447634867 	  Loss: 1.0366544388294774 	 Accuracy: 0.5645161290322581
Delta: 0.0030054335198870666 	  Loss: 1.0366331725269164 	 Accuracy: 0.5645161290322581
Delta: 0.0015071158970056458 	  Loss: 1.0366028716864393 	 Accuracy: 0.5645161290322581
Delta: 0.0009806154199875894 	  Loss: 1.036590724872977 	 Accuracy: 0.5645161290322581
Delta: 0.0012252676242747007 	  Loss: 1.0365798120131804 	 Accuracy: 0.5645161290322581
Delta: 0.0013222661506208442 	  Loss: 1.0365652584350697 	 Accuracy: 0.5645161290322581
Delta: 0.0005099886978155799 	  Loss: 1.0365621995485714 	 Accuracy: 0.5645161290322581
Delta: 0.0003129259299016357 	  Loss: 1.0365603353391823 	 Accuracy: 0.5645161290322581
Delta: 0.0005556287620135564 	  Loss: 1.036557545293423 	 Accuracy: 0.5645161290322581
Delta: 0.0002719685886989937 	  Loss: 1.0365548655036876 	 Accuracy: 0.5645161290322581
Delta: 0.0004192987355714846 	  Loss: 1.0365532678621916 	 Accuracy: 0.5645161290322581
Delta: 0.000255918091753125 	  Loss: 1.0365500037283228 	 Accuracy: 0.5645161290322581
Delta: 0.0002477396037501682 	  Loss: 1.0365494881737036 	 Accuracy: 0.5645161290322581
Delta: 5.9392713406207125e-05 	  Loss: 1.0365449989224227 	 Accuracy: 0.5645161290322581
Delta: 6.569390085890678e-05 	  Loss: 1.036545108590595 	 Accuracy: 0.5645161290322581
Delta: 0.00037375788573467637 	  Loss: 1.036545091337333 	 Accuracy: 0.5645161290322581
converged at iter  43
Delta: 0.0490897299667768 	  Loss: 1.0785067685569023 	 Accuracy: 0.41935483870967744
Delta: 0.042276768927524605 	  Loss: 1.0703367293944397 	 Accuracy: 0.3548387096774194
Delta: 0.03609545024491578 	  Loss: 1.0637282186134216 	 Accuracy: 0.1774193548387097
Delta: 0.028100117380778764 	  Loss: 1.0586788688754205 	 Accuracy: 0.1935483870967742
Delta: 0.030722592643782812 	  Loss: 1.0563526081600276 	 Accuracy: 0.1774193548387097
Delta: 0.025528350443818976 	  Loss: 1.0531103705088385 	 Accuracy: 0.16129032258064516
Delta: 0.020172410455284104 	  Loss: 1.0511168114917901 	 Accuracy: 0.16129032258064516

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01724411111380065 	  Loss: 1.049356972532454 	 Accuracy: 0.16129032258064516
Delta: 0.01563021770290928 	  Loss: 1.048613783680024 	 Accuracy: 0.1774193548387097
Delta: 0.012808790330509311 	  Loss: 1.0481665688284503 	 Accuracy: 0.1774193548387097
Delta: 0.008798388469055363 	  Loss: 1.0477385246185693 	 Accuracy: 0.1774193548387097
Delta: 0.007963358330238193 	  Loss: 1.047468205759844 	 Accuracy: 0.1774193548387097
Delta: 0.007039270549000202 	  Loss: 1.0472693310558976 	 Accuracy: 0.1774193548387097
Delta: 0.005447001221461573 	  Loss: 1.0470848393716303 	 Accuracy: 0.1774193548387097
Delta: 0.005718358875581658 	  Loss: 1.0470101499891473 	 Accuracy: 0.1774193548387097
Delta: 0.004921421284119933 	  Loss: 1.0469586710532668 	 Accuracy: 0.1774193548387097
Delta: 0.004364097305259687 	  Loss: 1.0468965496622606 	 Accuracy: 0.1774193548387097
Delta: 0.004165528918161385 	  Loss: 1.046835695079262 	 Accuracy: 0.1774193548387097
Delta: 0.0034614093449689934 	  Loss: 1.0467840119128309 	 Accuracy: 0.1774193548387097
Delta: 0.0030819932716235404 	  Loss: 1.0467534717912022 	 Accuracy: 0.1774193548387097
Delta: 0.002727845079276132 	  Loss: 1.0467461491508898 	 Accuracy: 0.1774193548387097
Delta: 0.0025831478232514384 	  Loss: 1.0467260988438178 	 Accuracy: 0.1774193548387097
Delta: 0.0029766376788591836 	  Loss: 1.046703215751635 	 Accuracy: 0.1774193548387097
Delta: 0.0030815688308857385 	  Loss: 1.046692603435698 	 Accuracy: 0.1774193548387097
Delta: 0.0024614229284498704 	  Loss: 1.0466748290393184 	 Accuracy: 0.1774193548387097
Delta: 0.002541876187198131 	  Loss: 1.0466571472007375 	 Accuracy: 0.1774193548387097
Delta: 0.0026920899011865715 	  Loss: 1.046622562579334 	 Accuracy: 0.1774193548387097
Delta: 0.0031394210128471746 	  Loss: 1.0465863095509333 	 Accuracy: 0.1774193548387097
Delta: 0.002161336598881081 	  Loss: 1.046540063477591 	 Accuracy: 0.1774193548387097
Delta: 0.0015450299511290389 	  Loss: 1.046520413136648 	 Accuracy: 0.1774193548387097
Delta: 0.002082773906950834 	  Loss: 1.0465173598831194 	 Accuracy: 0.1774193548387097
Delta: 0.0015903705995592334 	  Loss: 1.0465357934230186 	 Accuracy: 0.1774193548387097
Delta: 0.0013807565694674091 	  Loss: 1.0465366806140517 	 Accuracy: 0.1774193548387097
Delta: 0.0014841196608860305 	  Loss: 1.0465229422275013 	 Accuracy: 0.1774193548387097
Delta: 0.002107900171599407 	  Loss: 1.0465170377717326 	 Accuracy: 0.1774193548387097
Delta: 0.0012655527505808029 	  Loss: 1.04649712474645 	 Accuracy: 0.1774193548387097
Delta: 0.0015473989241334605 	  Loss: 1.0464938416684255 	 Accuracy: 0.1774193548387097
Delta: 0.0004988327968039216 	  Loss: 1.0464850874265128 	 Accuracy: 0.1774193548387097
Delta: 0.00037790031780699163 	  Loss: 1.0464843325930664 	 Accuracy: 0.1774193548387097
Delta: 6.841559138097817e-05 	  Loss: 1.04648148614743 	 Accuracy: 0.1774193548387097
Delta: 5.0186227068807005e-05 	  Loss: 1.046481035162295 	 Accuracy: 0.1774193548387097
Delta: 4.9985429709639646e-05 	  Loss: 1.0464807491451393 	 Accuracy: 0.1774193548387097
Delta: 0.0006431085683061893 	  Loss: 1.046480530519881 	 Accuracy: 0.1774193548387097
Delta: 0.0005667994908825267 	  Loss: 1.04647927068038 	 Accuracy: 0.1774193548387097
Delta: 0.0007260127085142998 	  Loss: 1.0464783496669268 	 Accuracy: 0.1774193548387097
Delta: 0.0004737136000075082 	  Loss: 1.0464770967193842 	 Accuracy: 0.1774193548387097
Delta: 0.0003903993462744781 	  Loss: 1.0464769686934812 	 Accuracy: 0.1774193548387097
Delta: 0.00019851571228716276 	  Loss: 1.046476779037567 	 Accuracy: 0.1774193548387097
Delta: 0.00024213367242800472 	  Loss: 1.0464762697894197 	 Accuracy: 0.1774193548387097
Delta: 0.0003951782866622982 	  Loss: 1.0464768790783774 	 Accuracy: 0.1774193548387097
Delta: 0.00032894713482787977 	  Loss: 1.046476591223548 	 Accuracy: 0.1774193548387097
Delta: 0.0003612620605580036 	  Loss: 1.046477586189336 	 Accuracy: 0.1774193548387097
Delta: 6.776679028889035e-05 	  Loss: 1.0464734299087142 	 Accuracy: 0.1774193548387097
Delta: 1.925671475959235e-06 	  Loss: 1.0464734212967348 	 Accuracy: 0.1774193548387097
converged at iter  53
Delta: 0.05157758415143568 	  Loss: 1.0838543078395502 	 Accuracy: 0.2857142857142857
Delta: 0.034937080542221416 	  Loss: 1.0698872008258289 	 Accuracy: 0.19047619047619047
Delta: 0.03139032263773828 	  Loss: 1.064124966980247 	 Accuracy: 0.1746031746031746
Delta: 0.029528853462831035 	  Loss: 1.0615498102437824 	 Accuracy: 0.1746031746031746
Delta: 0.031125860110866543 	  Loss: 1.0598769969064818 	 Accuracy: 0.19047619047619047
Delta: 0.0244422996782227 	  Loss: 1.05719696669393 	 Accuracy: 0.19047619047619047

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.020687890112273174 	  Loss: 1.0552986595132716 	 Accuracy: 0.19047619047619047
Delta: 0.017701038818996956 	  Loss: 1.0542292433470664 	 Accuracy: 0.19047619047619047
Delta: 0.014806384867698155 	  Loss: 1.0534591294760314 	 Accuracy: 0.19047619047619047
Delta: 0.011600407884668812 	  Loss: 1.0528464379126663 	 Accuracy: 0.19047619047619047
Delta: 0.01125970864191194 	  Loss: 1.052370984066188 	 Accuracy: 0.19047619047619047
Delta: 0.010731354335024399 	  Loss: 1.0518887976045679 	 Accuracy: 0.19047619047619047
Delta: 0.009786295961051125 	  Loss: 1.0513334054425991 	 Accuracy: 0.19047619047619047
Delta: 0.009394764426208315 	  Loss: 1.0510226483282823 	 Accuracy: 0.19047619047619047
Delta: 0.007080236993637953 	  Loss: 1.0508132871356524 	 Accuracy: 0.19047619047619047
Delta: 0.007394720184532266 	  Loss: 1.0506692017519554 	 Accuracy: 0.19047619047619047
Delta: 0.007161213831242968 	  Loss: 1.0504674889141077 	 Accuracy: 0.19047619047619047
Delta: 0.005515058627323335 	  Loss: 1.0503641760048805 	 Accuracy: 0.19047619047619047
Delta: 0.004908080994043238 	  Loss: 1.0503033127484542 	 Accuracy: 0.19047619047619047
Delta: 0.004920393907088394 	  Loss: 1.0502561343459702 	 Accuracy: 0.19047619047619047
Delta: 0.0053605545011663905 	  Loss: 1.0501906245825006 	 Accuracy: 0.19047619047619047
Delta: 0.005982082817942748 	  Loss: 1.0501143242024185 	 Accuracy: 0.19047619047619047
Delta: 0.006617901919724983 	  Loss: 1.0500966913761247 	 Accuracy: 0.19047619047619047
Delta: 0.007306920972924221 	  Loss: 1.0500176513331483 	 Accuracy: 0.19047619047619047
Delta: 0.007739279252181735 	  Loss: 1.049934319550023 	 Accuracy: 0.19047619047619047
Delta: 0.007997147519342144 	  Loss: 1.049831100145207 	 Accuracy: 0.19047619047619047
Delta: 0.009225421304225552 	  Loss: 1.0495760583289548 	 Accuracy: 0.19047619047619047
Delta: 0.010372786043871493 	  Loss: 1.049175737188082 	 Accuracy: 0.19047619047619047
Delta: 0.011007863446587586 	  Loss: 1.0487817838205673 	 Accuracy: 0.19047619047619047
Delta: 0.010676566394891457 	  Loss: 1.0482132202463144 	 Accuracy: 0.19047619047619047
Delta: 0.007089298906214158 	  Loss: 1.0477843340017894 	 Accuracy: 0.19047619047619047
Delta: 0.004647358236034782 	  Loss: 1.0475573739315922 	 Accuracy: 0.19047619047619047
Delta: 0.0033743479927046587 	  Loss: 1.04744411762145 	 Accuracy: 0.19047619047619047
Delta: 0.0029030664549082536 	  Loss: 1.047372872711149 	 Accuracy: 0.19047619047619047
Delta: 0.002175196559495996 	  Loss: 1.047345126899811 	 Accuracy: 0.19047619047619047
Delta: 0.0031451655170008754 	  Loss: 1.047315645303699 	 Accuracy: 0.19047619047619047
Delta: 0.003216747997237147 	  Loss: 1.0472951182749841 	 Accuracy: 0.19047619047619047
Delta: 0.0027732517021837946 	  Loss: 1.047237350096093 	 Accuracy: 0.19047619047619047
Delta: 0.003168426153686157 	  Loss: 1.04718439676296 	 Accuracy: 0.19047619047619047
Delta: 0.0024277941487673045 	  Loss: 1.0471484607138433 	 Accuracy: 0.19047619047619047
Delta: 0.002200729842865354 	  Loss: 1.0471449864805868 	 Accuracy: 0.19047619047619047
Delta: 0.0021623433930958143 	  Loss: 1.0471428609519329 	 Accuracy: 0.19047619047619047
Delta: 0.0027697384522045627 	  Loss: 1.0471282982727588 	 Accuracy: 0.19047619047619047
Delta: 0.002306805039185989 	  Loss: 1.0471305450766972 	 Accuracy: 0.19047619047619047
Delta: 0.0019222115793924776 	  Loss: 1.0471110436410669 	 Accuracy: 0.19047619047619047
Delta: 0.00132366257050899 	  Loss: 1.0471094226464357 	 Accuracy: 0.19047619047619047
Delta: 0.0012055284509965639 	  Loss: 1.0471078341496203 	 Accuracy: 0.19047619047619047
Delta: 0.0010155613967413168 	  Loss: 1.0471130296269762 	 Accuracy: 0.19047619047619047
Delta: 0.0007316735473564361 	  Loss: 1.0471085576737105 	 Accuracy: 0.19047619047619047
Delta: 0.0008477501287696861 	  Loss: 1.047102847313345 	 Accuracy: 0.19047619047619047
Delta: 0.00047164874477881124 	  Loss: 1.0471020705513032 	 Accuracy: 0.19047619047619047
Delta: 0.0008330463533496313 	  Loss: 1.0470986320816942 	 Accuracy: 0.19047619047619047
Delta: 0.0014509669497639408 	  Loss: 1.0470944418709958 	 Accuracy: 0.19047619047619047
Delta: 0.0019563607098316443 	  Loss: 1.0470704601615224 	 Accuracy: 0.19047619047619047
Delta: 0.002233214283781695 	  Loss: 1.0470371656018356 	 Accuracy: 0.19047619047619047
Delta: 0.0021976940625459775 	  Loss: 1.047027142540057 	 Accuracy: 0.19047619047619047
Delta: 0.0014120564763514093 	  Loss: 1.0470107249298852 	 Accuracy: 0.19047619047619047
Delta: 0.0007602813951564548 	  Loss: 1.0470071510818764 	 Accuracy: 0.19047619047619047
Delta: 0.001284769307872389 	  Loss: 1.0470044346408274 	 Accuracy: 0.19047619047619047
Delta: 0.0018028251880472573 	  Loss: 1.046998327805919 	 Accuracy: 0.19047619047619047
Delta: 0.0013495768593734525 	  Loss: 1.047002136815676 	 Accuracy: 0.19047619047619047
Delta: 0.0018742717774129767 	  Loss: 1.0470144521178189 	 Accuracy: 0.19047619047619047
Delta: 0.0021547957531917713 	  Loss: 1.047021442754349 	 Accuracy: 0.19047619047619047
Delta: 0.0013779340526843455 	  Loss: 1.0469965512841668 	 Accuracy: 0.19047619047619047
Delta: 0.001107903207131361 	  Loss: 1.0469733822185023 	 Accuracy: 0.19047619047619047
Delta: 0.001292374995821407 	  Loss: 1.046969617462437 	 Accuracy: 0.19047619047619047
Delta: 0.001590881972815059 	  Loss: 1.04694202652234 	 Accuracy: 0.19047619047619047
Delta: 0.0016010050667914374 	  Loss: 1.04693101277108 	 Accuracy: 0.19047619047619047
Delta: 0.001443601074733168 	  Loss: 1.0469086340491343 	 Accuracy: 0.19047619047619047
Delta: 0.0010993968761211974 	  Loss: 1.0468895864627084 	 Accuracy: 0.19047619047619047
Delta: 0.0016525600767742417 	  Loss: 1.0468807620751561 	 Accuracy: 0.19047619047619047
Delta: 0.0011924120136634392 	  Loss: 1.04686304068953 	 Accuracy: 0.19047619047619047
Delta: 0.0006611793108960372 	  Loss: 1.0468511933147724 	 Accuracy: 0.19047619047619047
Delta: 0.0003138659543775497 	  Loss: 1.046846142830927 	 Accuracy: 0.19047619047619047
Delta: 0.0001684031229441233 	  Loss: 1.0468451244926213 	 Accuracy: 0.19047619047619047
Delta: 0.0005010803148246644 	  Loss: 1.0468452757012408 	 Accuracy: 0.19047619047619047
Delta: 0.0003442126502602552 	  Loss: 1.0468428271567984 	 Accuracy: 0.19047619047619047
Delta: 0.00029466923302901964 	  Loss: 1.0468363525052444 	 Accuracy: 0.19047619047619047
Delta: 0.0005095974270675712 	  Loss: 1.046835810051236 	 Accuracy: 0.19047619047619047
Delta: 0.0001691918832907641 	  Loss: 1.0468370843096362 	 Accuracy: 0.19047619047619047
Delta: 0.0006007245131529307 	  Loss: 1.0468375512180255 	 Accuracy: 0.19047619047619047
Delta: 0.0004956844985809401 	  Loss: 1.0468411095323948 	 Accuracy: 0.19047619047619047
Delta: 0.0003358347336510723 	  Loss: 1.0468411296973417 	 Accuracy: 0.19047619047619047
converged at iter  82
Delta: 0.05409711987799225 	  Loss: 1.0648006633460256 	 Accuracy: 0.25396825396825395
Delta: 0.04063960942358495 	  Loss: 1.0571272453808995 	 Accuracy: 0.1746031746031746
Delta: 0.040064478961909164 	  Loss: 1.0566101913467847 	 Accuracy: 0.1746031746031746
Delta: 0.03341641549848688 	  Loss: 1.052711076058473 	 Accuracy: 0.1746031746031746

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.022965785989159423 	  Loss: 1.0478373918349746 	 Accuracy: 0.1746031746031746
Delta: 0.017032033644111905 	  Loss: 1.0459131044003795 	 Accuracy: 0.19047619047619047
Delta: 0.014791348376565823 	  Loss: 1.0446665680412002 	 Accuracy: 0.19047619047619047
Delta: 0.01155618410319657 	  Loss: 1.0437205782762113 	 Accuracy: 0.19047619047619047
Delta: 0.009434149591743051 	  Loss: 1.043197826109357 	 Accuracy: 0.19047619047619047
Delta: 0.008208336926227399 	  Loss: 1.0428524503626029 	 Accuracy: 0.19047619047619047
Delta: 0.008592735130172826 	  Loss: 1.0425963627962007 	 Accuracy: 0.19047619047619047
Delta: 0.007356062569049772 	  Loss: 1.0423400724914527 	 Accuracy: 0.19047619047619047
Delta: 0.006188850016249975 	  Loss: 1.042221344579042 	 Accuracy: 0.19047619047619047
Delta: 0.00663334171711037 	  Loss: 1.0421475644993907 	 Accuracy: 0.19047619047619047
Delta: 0.0061416079746963535 	  Loss: 1.0420345892995813 	 Accuracy: 0.19047619047619047
Delta: 0.005659667319268183 	  Loss: 1.0419709244944273 	 Accuracy: 0.19047619047619047
Delta: 0.005537160686121337 	  Loss: 1.0418862215565543 	 Accuracy: 0.19047619047619047
Delta: 0.0050099118461184025 	  Loss: 1.0418218814870832 	 Accuracy: 0.19047619047619047
Delta: 0.004637177244115341 	  Loss: 1.0417280902564467 	 Accuracy: 0.19047619047619047
Delta: 0.003903725998265654 	  Loss: 1.0416957024421751 	 Accuracy: 0.19047619047619047
Delta: 0.0027826148723857197 	  Loss: 1.0416634593021838 	 Accuracy: 0.19047619047619047
Delta: 0.003430515501942551 	  Loss: 1.0416323061983253 	 Accuracy: 0.19047619047619047
Delta: 0.00481712768958582 	  Loss: 1.041587675556228 	 Accuracy: 0.19047619047619047
Delta: 0.004031894426810878 	  Loss: 1.041503672269017 	 Accuracy: 0.19047619047619047
Delta: 0.004028097325169024 	  Loss: 1.0414020707572549 	 Accuracy: 0.19047619047619047
Delta: 0.003046934096193971 	  Loss: 1.0413339408294688 	 Accuracy: 0.19047619047619047
Delta: 0.0026177765652541036 	  Loss: 1.0413134506461676 	 Accuracy: 0.19047619047619047
Delta: 0.0022022757617029295 	  Loss: 1.041305282293098 	 Accuracy: 0.19047619047619047
Delta: 0.0017152569781413336 	  Loss: 1.0412764912632833 	 Accuracy: 0.19047619047619047
Delta: 0.00233147911253944 	  Loss: 1.0412467959884595 	 Accuracy: 0.19047619047619047
Delta: 0.001932876475528251 	  Loss: 1.0412324732952598 	 Accuracy: 0.19047619047619047
Delta: 0.002316782202719006 	  Loss: 1.0412139252963493 	 Accuracy: 0.19047619047619047
Delta: 0.002111724241244865 	  Loss: 1.0411829314457341 	 Accuracy: 0.19047619047619047
Delta: 0.0021912675647211936 	  Loss: 1.0411496724586002 	 Accuracy: 0.19047619047619047
Delta: 0.002539972252974681 	  Loss: 1.0411355860807503 	 Accuracy: 0.19047619047619047
Delta: 0.002823384123460507 	  Loss: 1.041117260517828 	 Accuracy: 0.19047619047619047
Delta: 0.0022107493919882645 	  Loss: 1.041101045997865 	 Accuracy: 0.19047619047619047
Delta: 0.001965916288343813 	  Loss: 1.0410731654318635 	 Accuracy: 0.19047619047619047
Delta: 0.0026745628935922667 	  Loss: 1.0410404772678943 	 Accuracy: 0.19047619047619047
Delta: 0.00206860304405055 	  Loss: 1.0409995062835042 	 Accuracy: 0.19047619047619047
Delta: 0.0022805523293335803 	  Loss: 1.0409887070301214 	 Accuracy: 0.19047619047619047
Delta: 0.002851986883288436 	  Loss: 1.0409498089976559 	 Accuracy: 0.19047619047619047
Delta: 0.0027704054117543343 	  Loss: 1.040896392959663 	 Accuracy: 0.19047619047619047
Delta: 0.003249472250170878 	  Loss: 1.040864234751881 	 Accuracy: 0.19047619047619047
Delta: 0.003406122188384338 	  Loss: 1.0408062450552005 	 Accuracy: 0.19047619047619047
Delta: 0.0031231192041340024 	  Loss: 1.0407619706071087 	 Accuracy: 0.19047619047619047
Delta: 0.003041884123532723 	  Loss: 1.0407337747717929 	 Accuracy: 0.19047619047619047
Delta: 0.002699581852967177 	  Loss: 1.0407378137825136 	 Accuracy: 0.19047619047619047
Delta: 0.0028294292641432386 	  Loss: 1.040739258020412 	 Accuracy: 0.19047619047619047
Delta: 0.002959895649177614 	  Loss: 1.0407440804352843 	 Accuracy: 0.19047619047619047
Delta: 0.003538076936755591 	  Loss: 1.0407644344910234 	 Accuracy: 0.19047619047619047
Delta: 0.0029043110661195275 	  Loss: 1.0407372383556037 	 Accuracy: 0.19047619047619047
Delta: 0.0028717140259942697 	  Loss: 1.040715297858417 	 Accuracy: 0.19047619047619047
Delta: 0.002759721510514258 	  Loss: 1.04066726255772 	 Accuracy: 0.19047619047619047
Delta: 0.001872776583197693 	  Loss: 1.0406317228134903 	 Accuracy: 0.19047619047619047
Delta: 0.0017468140453272285 	  Loss: 1.040604545117135 	 Accuracy: 0.19047619047619047
Delta: 0.0016718733693604623 	  Loss: 1.040584691831167 	 Accuracy: 0.19047619047619047
Delta: 0.0014753830714341846 	  Loss: 1.040572314477298 	 Accuracy: 0.19047619047619047
Delta: 0.0013634392811957652 	  Loss: 1.0405522721180462 	 Accuracy: 0.19047619047619047
Delta: 0.0013953807729931392 	  Loss: 1.0405474396666385 	 Accuracy: 0.19047619047619047
Delta: 0.0013288632530659894 	  Loss: 1.040548167877013 	 Accuracy: 0.19047619047619047
Delta: 0.0018097185276811805 	  Loss: 1.0405453356875003 	 Accuracy: 0.19047619047619047
Delta: 0.0017235412260758138 	  Loss: 1.0405347794140796 	 Accuracy: 0.19047619047619047
Delta: 0.0015333780078500483 	  Loss: 1.040527307553127 	 Accuracy: 0.19047619047619047
Delta: 0.0014791273345087395 	  Loss: 1.0405129559122672 	 Accuracy: 0.19047619047619047
Delta: 0.000988977809383147 	  Loss: 1.0405039880827094 	 Accuracy: 0.19047619047619047
Delta: 0.0006150062186254484 	  Loss: 1.0405092428321927 	 Accuracy: 0.19047619047619047
Delta: 0.0011578810308924502 	  Loss: 1.0405075714404173 	 Accuracy: 0.19047619047619047
Delta: 0.0008267465346060795 	  Loss: 1.0405064515311335 	 Accuracy: 0.19047619047619047
Delta: 0.0008193077232825834 	  Loss: 1.0405047460454786 	 Accuracy: 0.19047619047619047
Delta: 0.000804300625690443 	  Loss: 1.0405035808949352 	 Accuracy: 0.19047619047619047
Delta: 0.0005772240358714172 	  Loss: 1.040499210004908 	 Accuracy: 0.19047619047619047
Delta: 0.0010159802562564936 	  Loss: 1.0404961039556087 	 Accuracy: 0.19047619047619047
Delta: 0.0010289931941898029 	  Loss: 1.0404971399444514 	 Accuracy: 0.19047619047619047
Delta: 0.0013312594337370864 	  Loss: 1.0404953373823036 	 Accuracy: 0.19047619047619047
Delta: 0.001235703756832141 	  Loss: 1.0405009565256307 	 Accuracy: 0.19047619047619047
Delta: 0.0019761552048649755 	  Loss: 1.0405063967838495 	 Accuracy: 0.19047619047619047
Delta: 0.0011312604005073146 	  Loss: 1.0405183053428582 	 Accuracy: 0.19047619047619047
Delta: 0.002007055590525824 	  Loss: 1.040526635049237 	 Accuracy: 0.19047619047619047
Delta: 0.0015406338025355474 	  Loss: 1.0405241947722472 	 Accuracy: 0.19047619047619047
Delta: 0.0015707345611487072 	  Loss: 1.0405220175210532 	 Accuracy: 0.19047619047619047
Delta: 0.0015118475106785715 	  Loss: 1.0405112771124267 	 Accuracy: 0.19047619047619047
Delta: 0.0009525070136936018 	  Loss: 1.0405007935284918 	 Accuracy: 0.19047619047619047
Delta: 0.0012896312677636483 	  Loss: 1.0404977781712619 	 Accuracy: 0.19047619047619047
Delta: 0.0008777502277843582 	  Loss: 1.040484092702262 	 Accuracy: 0.19047619047619047
Delta: 0.0007243867110596576 	  Loss: 1.040489575488006 	 Accuracy: 0.19047619047619047
Delta: 0.00127756337035292 	  Loss: 1.0404914746913518 	 Accuracy: 0.19047619047619047
Delta: 0.0005013070766213209 	  Loss: 1.0404969658539178 	 Accuracy: 0.19047619047619047
Delta: 0.00015835154846372947 	  Loss: 1.0404934545255173 	 Accuracy: 0.19047619047619047
Delta: 6.533262252606731e-05 	  Loss: 1.0404919280818437 	 Accuracy: 0.19047619047619047
Delta: 4.167578236430373e-06 	  Loss: 1.0404912957888572 	 Accuracy: 0.19047619047619047
Delta: 2.501402245242373e-17 	  Loss: 1.0404912957888572 	 Accuracy: 0.19047619047619047
converged at iter  91
Delta: 0.05051883145195887 	  Loss: 1.0705627230694792 	 Accuracy: 0.532258064516129
Delta: 0.0445434272627393 	  Loss: 1.0693052790822692 	 Accuracy: 0.5967741935483871
Delta: 0.034878209058174146 	  Loss: 1.0659021950935665 	 Accuracy: 0.5483870967741935
Delta: 0.029436951376403613 	  Loss: 1.0621698190569813 	 Accuracy: 0.5
Delta: 0.02316167883932301 	  Loss: 1.0584682733641726 	 Accuracy: 0.46774193548387094

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01706700465301697 	  Loss: 1.0564437223105703 	 Accuracy: 0.46774193548387094
Delta: 0.014522103996871236 	  Loss: 1.055615636167373 	 Accuracy: 0.45161290322580644
Delta: 0.012543980259133518 	  Loss: 1.054948613753357 	 Accuracy: 0.45161290322580644
Delta: 0.009735438650313323 	  Loss: 1.0544203519133317 	 Accuracy: 0.45161290322580644
Delta: 0.007371456502204444 	  Loss: 1.0540048211783504 	 Accuracy: 0.45161290322580644
Delta: 0.006924191724812309 	  Loss: 1.053751651963747 	 Accuracy: 0.45161290322580644
Delta: 0.007047794698866814 	  Loss: 1.0533985092318026 	 Accuracy: 0.45161290322580644
Delta: 0.005517422769688231 	  Loss: 1.0531339525250485 	 Accuracy: 0.45161290322580644
Delta: 0.005862869222443908 	  Loss: 1.0529493186379317 	 Accuracy: 0.45161290322580644
Delta: 0.004443500409410133 	  Loss: 1.052783209294615 	 Accuracy: 0.45161290322580644
Delta: 0.003899584120985528 	  Loss: 1.0526738960890143 	 Accuracy: 0.45161290322580644
Delta: 0.004685854774291649 	  Loss: 1.052558734641389 	 Accuracy: 0.45161290322580644
Delta: 0.004217155797343743 	  Loss: 1.0524604259272352 	 Accuracy: 0.45161290322580644
Delta: 0.004816015415739532 	  Loss: 1.0523794609580999 	 Accuracy: 0.45161290322580644
Delta: 0.004232256802283396 	  Loss: 1.0523159369198827 	 Accuracy: 0.45161290322580644
Delta: 0.0035472977470385864 	  Loss: 1.0522617022819083 	 Accuracy: 0.45161290322580644
Delta: 0.003174621349243019 	  Loss: 1.0522034237735296 	 Accuracy: 0.45161290322580644
Delta: 0.0026447278643301573 	  Loss: 1.0521432006743536 	 Accuracy: 0.45161290322580644
Delta: 0.0031653390470468778 	  Loss: 1.0521105260291495 	 Accuracy: 0.45161290322580644
Delta: 0.002677783759514804 	  Loss: 1.0520686880575087 	 Accuracy: 0.45161290322580644
Delta: 0.00261820947842011 	  Loss: 1.0520152650555359 	 Accuracy: 0.45161290322580644
Delta: 0.0026423226619965135 	  Loss: 1.051976191046702 	 Accuracy: 0.45161290322580644
Delta: 0.0017884650785300106 	  Loss: 1.0519666798592655 	 Accuracy: 0.45161290322580644
Delta: 0.0020156613783940355 	  Loss: 1.0519456207364914 	 Accuracy: 0.45161290322580644
Delta: 0.002050879149508026 	  Loss: 1.051935654451302 	 Accuracy: 0.45161290322580644
Delta: 0.002266566452308241 	  Loss: 1.0519109799478035 	 Accuracy: 0.45161290322580644
Delta: 0.0029645121111251302 	  Loss: 1.0519019137703896 	 Accuracy: 0.45161290322580644
Delta: 0.0016277903524389138 	  Loss: 1.051875079443028 	 Accuracy: 0.45161290322580644
Delta: 0.0016048329437648246 	  Loss: 1.0518485942002456 	 Accuracy: 0.45161290322580644
Delta: 0.0016528524115819968 	  Loss: 1.051818507233393 	 Accuracy: 0.45161290322580644
Delta: 0.0018260118458080811 	  Loss: 1.0518002219334492 	 Accuracy: 0.45161290322580644
Delta: 0.0022111337200884065 	  Loss: 1.051769633828565 	 Accuracy: 0.45161290322580644
Delta: 0.0024390512374613104 	  Loss: 1.0517317367572838 	 Accuracy: 0.45161290322580644
Delta: 0.0024718890153550476 	  Loss: 1.05170890864949 	 Accuracy: 0.45161290322580644
Delta: 0.0024529575896193134 	  Loss: 1.0516686402712194 	 Accuracy: 0.45161290322580644
Delta: 0.002219347710107954 	  Loss: 1.0516231623767185 	 Accuracy: 0.45161290322580644
Delta: 0.0016495723040140344 	  Loss: 1.051592192799672 	 Accuracy: 0.45161290322580644
Delta: 0.0016630661090991385 	  Loss: 1.0515685885932966 	 Accuracy: 0.45161290322580644
Delta: 0.002043766634277336 	  Loss: 1.0515492311067334 	 Accuracy: 0.45161290322580644
Delta: 0.0019793041645565267 	  Loss: 1.0515245659118302 	 Accuracy: 0.45161290322580644
Delta: 0.0025929930760328823 	  Loss: 1.0515180635681525 	 Accuracy: 0.45161290322580644
Delta: 0.0018280309192091806 	  Loss: 1.0515072462421644 	 Accuracy: 0.45161290322580644
Delta: 0.0012122305268054885 	  Loss: 1.0514905472252722 	 Accuracy: 0.45161290322580644
Delta: 0.0007517228911249019 	  Loss: 1.0514827406347895 	 Accuracy: 0.45161290322580644
Delta: 0.0005271008513114306 	  Loss: 1.0514797085979475 	 Accuracy: 0.45161290322580644
Delta: 0.00023457866319957551 	  Loss: 1.0514708221718694 	 Accuracy: 0.45161290322580644
Delta: 0.00014811159436225533 	  Loss: 1.051470090682871 	 Accuracy: 0.45161290322580644
Delta: 9.974685742214352e-05 	  Loss: 1.0514698050255071 	 Accuracy: 0.45161290322580644
Delta: 7.71773119118868e-06 	  Loss: 1.0514690934585609 	 Accuracy: 0.45161290322580644
Delta: 3.764452743803114e-17 	  Loss: 1.051469093458561 	 Accuracy: 0.45161290322580644
converged at iter  54
Delta: 0.053061569580134846 	  Loss: 1.062543955565121 	 Accuracy: 0.532258064516129
Delta: 0.04662817472558087 	  Loss: 1.0604578814324548 	 Accuracy: 0.4838709677419355
Delta: 0.03808890492728652 	  Loss: 1.054978037413798 	 Accuracy: 0.43548387096774194

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028506076926030684 	  Loss: 1.048862461522694 	 Accuracy: 0.3870967741935484
Delta: 0.020087708983075284 	  Loss: 1.0458493471323997 	 Accuracy: 0.3870967741935484
Delta: 0.016780954207588943 	  Loss: 1.0442436422055628 	 Accuracy: 0.3870967741935484
Delta: 0.012752324207484478 	  Loss: 1.0432848451519343 	 Accuracy: 0.3870967741935484
Delta: 0.011189972572368517 	  Loss: 1.0426906498018043 	 Accuracy: 0.3870967741935484
Delta: 0.010275028254419921 	  Loss: 1.0423383238676118 	 Accuracy: 0.3870967741935484
Delta: 0.006775015832551619 	  Loss: 1.0419923136155131 	 Accuracy: 0.3870967741935484
Delta: 0.006032088602815412 	  Loss: 1.0418134638767735 	 Accuracy: 0.3870967741935484
Delta: 0.006531391377641497 	  Loss: 1.0416799383489335 	 Accuracy: 0.3870967741935484
Delta: 0.007207678713731582 	  Loss: 1.0415114922614408 	 Accuracy: 0.3870967741935484
Delta: 0.007286544232591485 	  Loss: 1.0413361064678068 	 Accuracy: 0.3870967741935484
Delta: 0.00696818639482288 	  Loss: 1.0411286520060532 	 Accuracy: 0.3870967741935484
Delta: 0.0048700161112030715 	  Loss: 1.0409850532970713 	 Accuracy: 0.3870967741935484
Delta: 0.005571872453333198 	  Loss: 1.0408944519013537 	 Accuracy: 0.3870967741935484
Delta: 0.004979430301794187 	  Loss: 1.0407741393790195 	 Accuracy: 0.3870967741935484
Delta: 0.005056665063244422 	  Loss: 1.0406859355129716 	 Accuracy: 0.3870967741935484
Delta: 0.0043653463981698105 	  Loss: 1.0406081740070399 	 Accuracy: 0.3870967741935484
Delta: 0.0033590130434619373 	  Loss: 1.0405445879921627 	 Accuracy: 0.3870967741935484
Delta: 0.003070697678878456 	  Loss: 1.0404765946003836 	 Accuracy: 0.3870967741935484
Delta: 0.003958898322977541 	  Loss: 1.0404166395396388 	 Accuracy: 0.3870967741935484
Delta: 0.0031468523445489062 	  Loss: 1.040361493680802 	 Accuracy: 0.3870967741935484
Delta: 0.0033331777416069305 	  Loss: 1.0403264094079154 	 Accuracy: 0.3870967741935484
Delta: 0.002441453900139233 	  Loss: 1.0402899222177742 	 Accuracy: 0.3870967741935484
Delta: 0.0022942932552701524 	  Loss: 1.0402785178128884 	 Accuracy: 0.3870967741935484
Delta: 0.002218163504051468 	  Loss: 1.0402837503137459 	 Accuracy: 0.3870967741935484
Delta: 0.0025541793521622305 	  Loss: 1.0402713506674912 	 Accuracy: 0.3870967741935484
Delta: 0.0016730263257500246 	  Loss: 1.0402556850296358 	 Accuracy: 0.3870967741935484
Delta: 0.002380028113244895 	  Loss: 1.0402536053318707 	 Accuracy: 0.3870967741935484
Delta: 0.002238635326951182 	  Loss: 1.0402602508859973 	 Accuracy: 0.3870967741935484
Delta: 0.0012334746257722429 	  Loss: 1.0402530583281862 	 Accuracy: 0.3870967741935484
Delta: 0.0011881687204973776 	  Loss: 1.0402521365153343 	 Accuracy: 0.3870967741935484
Delta: 0.0015731616669129192 	  Loss: 1.0402454093256308 	 Accuracy: 0.3870967741935484
Delta: 0.0006205905763741518 	  Loss: 1.040245235774206 	 Accuracy: 0.3870967741935484
Delta: 0.001470174828309662 	  Loss: 1.0402517767322323 	 Accuracy: 0.3870967741935484
Delta: 0.0017130852665728075 	  Loss: 1.0402560820885505 	 Accuracy: 0.3870967741935484
Delta: 0.0013375016810069245 	  Loss: 1.0402513876637123 	 Accuracy: 0.3870967741935484
Delta: 0.0009325499289334969 	  Loss: 1.0402416409285988 	 Accuracy: 0.3870967741935484
Delta: 0.001371311025039734 	  Loss: 1.0402443205410172 	 Accuracy: 0.3870967741935484
Delta: 0.0012610569948687377 	  Loss: 1.0402385699424197 	 Accuracy: 0.3870967741935484
Delta: 0.0019740660898413527 	  Loss: 1.040239975557558 	 Accuracy: 0.3870967741935484
Delta: 0.0012175673151026752 	  Loss: 1.0402363092334017 	 Accuracy: 0.3870967741935484
Delta: 0.001173706146505439 	  Loss: 1.04023504391858 	 Accuracy: 0.3870967741935484
Delta: 0.0007919850070869913 	  Loss: 1.0402398901828465 	 Accuracy: 0.3870967741935484
Delta: 0.0016206067884482153 	  Loss: 1.0402390738419123 	 Accuracy: 0.3870967741935484
Delta: 0.0012504173936347743 	  Loss: 1.0402224160346099 	 Accuracy: 0.3870967741935484
Delta: 0.0012556189420943982 	  Loss: 1.040214373416895 	 Accuracy: 0.3870967741935484
Delta: 0.002456423360537843 	  Loss: 1.0402033946596188 	 Accuracy: 0.3870967741935484
Delta: 0.0014406486307335469 	  Loss: 1.040175620860559 	 Accuracy: 0.3870967741935484
Delta: 0.002026664745095147 	  Loss: 1.0401642003668938 	 Accuracy: 0.3870967741935484
Delta: 0.002271541405009774 	  Loss: 1.0401329091883076 	 Accuracy: 0.3870967741935484
Delta: 0.0019008630073035222 	  Loss: 1.0401086461396434 	 Accuracy: 0.3870967741935484
Delta: 0.0030364533091301986 	  Loss: 1.0401242119750524 	 Accuracy: 0.3870967741935484
Delta: 0.0018388493346343762 	  Loss: 1.0401252423604346 	 Accuracy: 0.3870967741935484
Delta: 0.002478397582469568 	  Loss: 1.0401175624122396 	 Accuracy: 0.3870967741935484
Delta: 0.0015845454649860698 	  Loss: 1.0401040804083026 	 Accuracy: 0.3870967741935484
Delta: 0.0017830892587233065 	  Loss: 1.0400887188933166 	 Accuracy: 0.3870967741935484
Delta: 0.002406477889139108 	  Loss: 1.0400763436774558 	 Accuracy: 0.3870967741935484
Delta: 0.0015048144150036258 	  Loss: 1.0400568897113098 	 Accuracy: 0.3870967741935484
Delta: 0.0010054109308612943 	  Loss: 1.0400443519139437 	 Accuracy: 0.3870967741935484
Delta: 0.0008334551336142452 	  Loss: 1.0400403519372263 	 Accuracy: 0.3870967741935484
Delta: 0.0006564115000512763 	  Loss: 1.0400362916216375 	 Accuracy: 0.3870967741935484
Delta: 0.0008999157619619409 	  Loss: 1.0400285269834386 	 Accuracy: 0.3870967741935484
Delta: 0.0009203430557540707 	  Loss: 1.0400202813234385 	 Accuracy: 0.3870967741935484
Delta: 0.00051065416400426 	  Loss: 1.0400064760647467 	 Accuracy: 0.3870967741935484
Delta: 0.00014708543151951788 	  Loss: 1.0400001604785665 	 Accuracy: 0.3870967741935484
Delta: 0.0002166246705936509 	  Loss: 1.0399999256658998 	 Accuracy: 0.3870967741935484
Delta: 0.0006565478761369254 	  Loss: 1.0400003754087028 	 Accuracy: 0.3870967741935484
Delta: 0.0006256770682310029 	  Loss: 1.040002061938098 	 Accuracy: 0.3870967741935484
Delta: 0.0010049462979420608 	  Loss: 1.0400036990526482 	 Accuracy: 0.3870967741935484
Delta: 0.0003660737719104383 	  Loss: 1.0399985393842133 	 Accuracy: 0.3870967741935484
Delta: 0.0005655714345023891 	  Loss: 1.0399974077616665 	 Accuracy: 0.3870967741935484
Delta: 0.0006814052899655525 	  Loss: 1.0399961200773826 	 Accuracy: 0.3870967741935484
Delta: 0.00019419884992015848 	  Loss: 1.0399981687904498 	 Accuracy: 0.3870967741935484
Delta: 0.0003186446822505804 	  Loss: 1.0399985643290126 	 Accuracy: 0.3870967741935484
Delta: 7.40476105296418e-05 	  Loss: 1.0399987826510455 	 Accuracy: 0.3870967741935484
Delta: 8.405703898014822e-05 	  Loss: 1.0399985706396326 	 Accuracy: 0.3870967741935484
Delta: 6.529930621545729e-06 	  Loss: 1.0399992691515982 	 Accuracy: 0.3870967741935484
Delta: 3.8552927834734675e-17 	  Loss: 1.0399992691515982 	 Accuracy: 0.3870967741935484
converged at iter  80
Delta: 0.05187202953000365 	  Loss: 1.0805511025394023 	 Accuracy: 0.27419354838709675
Delta: 0.04187106912878123 	  Loss: 1.0696704201410854 	 Accuracy: 0.0967741935483871
Delta: 0.037492280502691135 	  Loss: 1.0664586763195663 	 Accuracy: 0.08064516129032258
Delta: 0.029859669930108888 	  Loss: 1.0666338810115894 	 Accuracy: 0.08064516129032258
Delta: 0.022876921265663316 	  Loss: 1.0661070683043126 	 Accuracy: 0.11290322580645161
Delta: 0.018937796002965888 	  Loss: 1.0652701723948732 	 Accuracy: 0.0967741935483871

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.015464903310695551 	  Loss: 1.064115623718108 	 Accuracy: 0.0967741935483871
Delta: 0.01560300330476563 	  Loss: 1.0629918087678134 	 Accuracy: 0.0967741935483871
Delta: 0.011326337193548492 	  Loss: 1.062278602179631 	 Accuracy: 0.0967741935483871
Delta: 0.009707978242966783 	  Loss: 1.0618978416506384 	 Accuracy: 0.0967741935483871
Delta: 0.008856419357215846 	  Loss: 1.0616474743758735 	 Accuracy: 0.0967741935483871
Delta: 0.008268232311681526 	  Loss: 1.0615009161437075 	 Accuracy: 0.0967741935483871
Delta: 0.008980214009568211 	  Loss: 1.061231793774485 	 Accuracy: 0.0967741935483871
Delta: 0.010189348487839804 	  Loss: 1.0609025219241262 	 Accuracy: 0.0967741935483871
Delta: 0.009229802655441334 	  Loss: 1.0604871499647708 	 Accuracy: 0.0967741935483871
Delta: 0.007266312729873422 	  Loss: 1.0600324917018351 	 Accuracy: 0.0967741935483871
Delta: 0.006646109078467074 	  Loss: 1.0598276787639593 	 Accuracy: 0.0967741935483871
Delta: 0.005539457860007506 	  Loss: 1.0596787349972645 	 Accuracy: 0.0967741935483871
Delta: 0.004473739713584019 	  Loss: 1.0595819867526217 	 Accuracy: 0.0967741935483871
Delta: 0.0043734483759042845 	  Loss: 1.059539429120656 	 Accuracy: 0.0967741935483871
Delta: 0.003988683759360184 	  Loss: 1.05951998252752 	 Accuracy: 0.0967741935483871
Delta: 0.0038918441004728763 	  Loss: 1.0594866569605266 	 Accuracy: 0.0967741935483871
Delta: 0.003579992716547036 	  Loss: 1.0594403431885882 	 Accuracy: 0.0967741935483871
Delta: 0.003799338116695219 	  Loss: 1.0594053702670625 	 Accuracy: 0.0967741935483871
Delta: 0.0035571206700585074 	  Loss: 1.0593538563045404 	 Accuracy: 0.0967741935483871
Delta: 0.003210426563474132 	  Loss: 1.059351233961696 	 Accuracy: 0.0967741935483871
Delta: 0.003189476512429058 	  Loss: 1.0593437139685986 	 Accuracy: 0.0967741935483871
Delta: 0.0033276886782165776 	  Loss: 1.0593116688910982 	 Accuracy: 0.0967741935483871
Delta: 0.003702312243241233 	  Loss: 1.0592877758112311 	 Accuracy: 0.0967741935483871
Delta: 0.004091226988776802 	  Loss: 1.059252791090414 	 Accuracy: 0.0967741935483871
Delta: 0.004487434775836976 	  Loss: 1.0591857345782403 	 Accuracy: 0.0967741935483871
Delta: 0.003905386403237154 	  Loss: 1.0591707589753343 	 Accuracy: 0.0967741935483871
Delta: 0.003858756589000834 	  Loss: 1.05916868902899 	 Accuracy: 0.0967741935483871
Delta: 0.0030456655721932263 	  Loss: 1.0591487973723304 	 Accuracy: 0.0967741935483871
Delta: 0.0031827556336871286 	  Loss: 1.0591529350752424 	 Accuracy: 0.0967741935483871
Delta: 0.0015247312079706623 	  Loss: 1.05915288075819 	 Accuracy: 0.0967741935483871
converged at iter  35
Delta: 0.05431376310227046 	  Loss: 1.0746669614064306 	 Accuracy: 0.5238095238095238
Delta: 0.039939730135409926 	  Loss: 1.0666005414046873 	 Accuracy: 0.5079365079365079
Delta: 0.036960869199811584 	  Loss: 1.0627510723938685 	 Accuracy: 0.49206349206349204

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028039602751915037 	  Loss: 1.0597378212843773 	 Accuracy: 0.49206349206349204
Delta: 0.01833510300182382 	  Loss: 1.0570464006754938 	 Accuracy: 0.49206349206349204
Delta: 0.013562051400287118 	  Loss: 1.0560764399333147 	 Accuracy: 0.49206349206349204
Delta: 0.012188539635333192 	  Loss: 1.0554607673517031 	 Accuracy: 0.49206349206349204
Delta: 0.010249848929060962 	  Loss: 1.054831162927148 	 Accuracy: 0.49206349206349204
Delta: 0.008856079535122142 	  Loss: 1.0543952281360018 	 Accuracy: 0.49206349206349204
Delta: 0.008794139605182723 	  Loss: 1.054070458398622 	 Accuracy: 0.49206349206349204
Delta: 0.008990944345800939 	  Loss: 1.0536192065711405 	 Accuracy: 0.49206349206349204
Delta: 0.008536215292082037 	  Loss: 1.0532058414490928 	 Accuracy: 0.49206349206349204
Delta: 0.007593550342195918 	  Loss: 1.052843546753797 	 Accuracy: 0.49206349206349204
Delta: 0.007096536252897062 	  Loss: 1.052544753397591 	 Accuracy: 0.49206349206349204
Delta: 0.006872722441293484 	  Loss: 1.0522648887562107 	 Accuracy: 0.49206349206349204
Delta: 0.006596675085698302 	  Loss: 1.051996239586913 	 Accuracy: 0.49206349206349204
Delta: 0.006093458361248606 	  Loss: 1.0517722499184048 	 Accuracy: 0.49206349206349204
Delta: 0.005756964492070054 	  Loss: 1.0516054944348285 	 Accuracy: 0.49206349206349204
Delta: 0.0063964925046536775 	  Loss: 1.0514853174360879 	 Accuracy: 0.49206349206349204
Delta: 0.0057087025142737915 	  Loss: 1.051283395852968 	 Accuracy: 0.49206349206349204
Delta: 0.0051565337061833146 	  Loss: 1.0511599280225163 	 Accuracy: 0.49206349206349204
Delta: 0.005918573217404183 	  Loss: 1.051028040821703 	 Accuracy: 0.49206349206349204
Delta: 0.006210337749771141 	  Loss: 1.050837823467711 	 Accuracy: 0.49206349206349204
Delta: 0.005696958883658218 	  Loss: 1.050634174786317 	 Accuracy: 0.49206349206349204
Delta: 0.004871281663482852 	  Loss: 1.0504659161527063 	 Accuracy: 0.49206349206349204
Delta: 0.004240155943744064 	  Loss: 1.050363237874072 	 Accuracy: 0.49206349206349204
Delta: 0.0027709142605990677 	  Loss: 1.0502612627094088 	 Accuracy: 0.49206349206349204
Delta: 0.001975599649240112 	  Loss: 1.0501899775417556 	 Accuracy: 0.49206349206349204
Delta: 0.0016758555541060152 	  Loss: 1.0501668901853154 	 Accuracy: 0.49206349206349204
Delta: 0.0009139109252504543 	  Loss: 1.0501515930924503 	 Accuracy: 0.49206349206349204
Delta: 0.0011458931893766496 	  Loss: 1.05014211430779 	 Accuracy: 0.49206349206349204
Delta: 0.0008392703035182066 	  Loss: 1.0501316873673265 	 Accuracy: 0.49206349206349204
Delta: 0.00150397819797071 	  Loss: 1.050127088863451 	 Accuracy: 0.49206349206349204
Delta: 0.0019062899838833652 	  Loss: 1.0501231142542955 	 Accuracy: 0.49206349206349204
Delta: 0.0021406900132090382 	  Loss: 1.0501145957228148 	 Accuracy: 0.49206349206349204
Delta: 0.0013164086799120414 	  Loss: 1.0501071885030493 	 Accuracy: 0.49206349206349204
Delta: 0.0006054961603188577 	  Loss: 1.0501030292955282 	 Accuracy: 0.49206349206349204
Delta: 0.0005732878835298011 	  Loss: 1.0500990421075822 	 Accuracy: 0.49206349206349204
Delta: 0.0007144850428561038 	  Loss: 1.0500977019154834 	 Accuracy: 0.49206349206349204
Delta: 0.0014957932676469548 	  Loss: 1.0500939918033043 	 Accuracy: 0.49206349206349204
Delta: 0.000617787699743499 	  Loss: 1.0500915241677404 	 Accuracy: 0.49206349206349204
Delta: 0.0004897984098966534 	  Loss: 1.050090112945261 	 Accuracy: 0.49206349206349204
Delta: 0.0017921564027619185 	  Loss: 1.0500889918166973 	 Accuracy: 0.49206349206349204
Delta: 0.0011552132867288208 	  Loss: 1.0500722910911175 	 Accuracy: 0.49206349206349204
Delta: 0.000563098411152963 	  Loss: 1.0500689505004068 	 Accuracy: 0.49206349206349204
Delta: 0.0009443563334978886 	  Loss: 1.0500697656233782 	 Accuracy: 0.49206349206349204
Delta: 0.0007955026407435612 	  Loss: 1.0500749207197377 	 Accuracy: 0.49206349206349204
Delta: 0.0007502631545164271 	  Loss: 1.0500719843284416 	 Accuracy: 0.49206349206349204
Delta: 0.0005739238170779425 	  Loss: 1.050066905511089 	 Accuracy: 0.49206349206349204
Delta: 0.00031342358261590844 	  Loss: 1.0500655263231495 	 Accuracy: 0.49206349206349204
Delta: 0.00010013458892293582 	  Loss: 1.05006383256087 	 Accuracy: 0.49206349206349204
Delta: 1.768083192370254e-05 	  Loss: 1.050063801839524 	 Accuracy: 0.49206349206349204
converged at iter  51
Delta: 0.056412922532134716 	  Loss: 1.0627421158851238 	 Accuracy: 0.2698412698412698
Delta: 0.03528424837897033 	  Loss: 1.0539896229796422 	 Accuracy: 0.2222222222222222
Delta: 0.03168382712632035 	  Loss: 1.0474794821026718 	 Accuracy: 0.20634920634920634
Delta: 0.029108958093753145 	  Loss: 1.042630855288428 	 Accuracy: 0.23809523809523808
Delta: 0.023723513386336242 	  Loss: 1.0394679961115747 	 Accuracy: 0.23809523809523808
Delta: 0.02064737950724166 	  Loss: 1.0374468659315947 	 Accuracy: 0.23809523809523808

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.016698585568199024 	  Loss: 1.0358463274123957 	 Accuracy: 0.23809523809523808
Delta: 0.014467917334285554 	  Loss: 1.0347094937401553 	 Accuracy: 0.23809523809523808
Delta: 0.012871735238040983 	  Loss: 1.0337831144522311 	 Accuracy: 0.23809523809523808
Delta: 0.010955813017450064 	  Loss: 1.0329778550841078 	 Accuracy: 0.23809523809523808
Delta: 0.00739742342790835 	  Loss: 1.0324444000827913 	 Accuracy: 0.23809523809523808
Delta: 0.006319912696994086 	  Loss: 1.032258392701535 	 Accuracy: 0.23809523809523808
Delta: 0.005212513617417958 	  Loss: 1.032129835952885 	 Accuracy: 0.23809523809523808
Delta: 0.00532423264101656 	  Loss: 1.032068059777477 	 Accuracy: 0.23809523809523808
Delta: 0.005162395132453828 	  Loss: 1.0320217631810091 	 Accuracy: 0.23809523809523808
Delta: 0.005625251978085051 	  Loss: 1.031928484424698 	 Accuracy: 0.23809523809523808
Delta: 0.004644400793153859 	  Loss: 1.031780657204322 	 Accuracy: 0.23809523809523808
Delta: 0.004156965614063072 	  Loss: 1.0316077718253036 	 Accuracy: 0.23809523809523808
Delta: 0.0036086735251404456 	  Loss: 1.0315384195078772 	 Accuracy: 0.23809523809523808
Delta: 0.0037105143936589573 	  Loss: 1.0314444601135218 	 Accuracy: 0.23809523809523808
Delta: 0.0036995545626222065 	  Loss: 1.0313231464245178 	 Accuracy: 0.23809523809523808
Delta: 0.0037794083322436334 	  Loss: 1.03122182075254 	 Accuracy: 0.23809523809523808
Delta: 0.0033013451194376224 	  Loss: 1.031142029816311 	 Accuracy: 0.23809523809523808
Delta: 0.002741179559987796 	  Loss: 1.031079808567125 	 Accuracy: 0.23809523809523808
Delta: 0.003220601488695402 	  Loss: 1.03103567794887 	 Accuracy: 0.23809523809523808
Delta: 0.0026840228924750018 	  Loss: 1.0309612264734707 	 Accuracy: 0.23809523809523808
Delta: 0.0015373817307912344 	  Loss: 1.0309177713625006 	 Accuracy: 0.23809523809523808
Delta: 0.0016014221582527524 	  Loss: 1.030910332981367 	 Accuracy: 0.23809523809523808
Delta: 0.0013417217214274175 	  Loss: 1.0309086945508268 	 Accuracy: 0.23809523809523808
Delta: 0.001151923877792743 	  Loss: 1.0309082079195908 	 Accuracy: 0.23809523809523808
Delta: 0.0010096249421197038 	  Loss: 1.030907186230856 	 Accuracy: 0.23809523809523808
Delta: 0.0013756838093265445 	  Loss: 1.0309112332847254 	 Accuracy: 0.23809523809523808
Delta: 0.0016349778383480422 	  Loss: 1.0309121239654724 	 Accuracy: 0.23809523809523808
Delta: 0.0010907956818752887 	  Loss: 1.030901515869402 	 Accuracy: 0.23809523809523808
Delta: 0.0009640317932753039 	  Loss: 1.0308901692474257 	 Accuracy: 0.23809523809523808
Delta: 0.0009405661337598045 	  Loss: 1.0308878132983292 	 Accuracy: 0.23809523809523808
Delta: 0.0008565603106026869 	  Loss: 1.030890574567647 	 Accuracy: 0.23809523809523808
Delta: 0.002168835080024277 	  Loss: 1.0308946864521116 	 Accuracy: 0.23809523809523808
Delta: 0.0005652945703115452 	  Loss: 1.0309006368196458 	 Accuracy: 0.23809523809523808
Delta: 0.0002810591954427753 	  Loss: 1.0309009560672682 	 Accuracy: 0.23809523809523808
Delta: 0.00025020769941614654 	  Loss: 1.030900410664541 	 Accuracy: 0.23809523809523808
Delta: 0.0001233512546247546 	  Loss: 1.0309006115655748 	 Accuracy: 0.23809523809523808
Delta: 0.00021760307116917014 	  Loss: 1.0309003717852763 	 Accuracy: 0.23809523809523808
Delta: 0.00016996001689061993 	  Loss: 1.0308990721833693 	 Accuracy: 0.23809523809523808
Delta: 7.07605321858272e-05 	  Loss: 1.0308984957726381 	 Accuracy: 0.23809523809523808
Delta: 0.0003151939956769196 	  Loss: 1.0308982757091 	 Accuracy: 0.23809523809523808
Delta: 0.00015176757186242997 	  Loss: 1.030896736674923 	 Accuracy: 0.23809523809523808
Delta: 0.0001110577146388329 	  Loss: 1.0308963252249237 	 Accuracy: 0.23809523809523808
Delta: 0.00016630038414043518 	  Loss: 1.0308965447669776 	 Accuracy: 0.23809523809523808
Delta: 0.00019475299093438616 	  Loss: 1.0308967249124668 	 Accuracy: 0.23809523809523808
Delta: 9.975594964512526e-05 	  Loss: 1.0308968153521114 	 Accuracy: 0.23809523809523808
converged at iter  50
Delta: 0.05412166840845725 	  Loss: 1.0714338722587589 	 Accuracy: 0.5483870967741935
Delta: 0.04377057918732606 	  Loss: 1.0651387694932914 	 Accuracy: 0.46774193548387094
Delta: 0.03475616109399811 	  Loss: 1.060709784054478 	 Accuracy: 0.43548387096774194

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.024185256140413777 	  Loss: 1.0568500329407238 	 Accuracy: 0.43548387096774194
Delta: 0.020524454810936746 	  Loss: 1.0539962525379067 	 Accuracy: 0.43548387096774194
Delta: 0.016500728713417224 	  Loss: 1.052216718195936 	 Accuracy: 0.43548387096774194
Delta: 0.012280520434608788 	  Loss: 1.0510876454442335 	 Accuracy: 0.41935483870967744
Delta: 0.01187357808056706 	  Loss: 1.0503549995953363 	 Accuracy: 0.41935483870967744
Delta: 0.012188476237001535 	  Loss: 1.0498577782550527 	 Accuracy: 0.41935483870967744
Delta: 0.008484373883776123 	  Loss: 1.049413388758991 	 Accuracy: 0.41935483870967744
Delta: 0.007317813952358477 	  Loss: 1.0490784461684246 	 Accuracy: 0.41935483870967744
Delta: 0.006304806066379862 	  Loss: 1.0488492970467256 	 Accuracy: 0.41935483870967744
Delta: 0.005371815450770032 	  Loss: 1.0486154359884305 	 Accuracy: 0.41935483870967744
Delta: 0.004665419415580163 	  Loss: 1.0484818621517213 	 Accuracy: 0.41935483870967744
Delta: 0.004620582113172186 	  Loss: 1.0483766365294283 	 Accuracy: 0.41935483870967744
Delta: 0.004062483180728778 	  Loss: 1.048292005153339 	 Accuracy: 0.41935483870967744
Delta: 0.005221361032248335 	  Loss: 1.0482018349614277 	 Accuracy: 0.41935483870967744
Delta: 0.006075632476876048 	  Loss: 1.0480635649437744 	 Accuracy: 0.41935483870967744
Delta: 0.005794758770848484 	  Loss: 1.0478594343481409 	 Accuracy: 0.41935483870967744
Delta: 0.00431377402628944 	  Loss: 1.0476638956975048 	 Accuracy: 0.41935483870967744
Delta: 0.003969389802015793 	  Loss: 1.0475485547750347 	 Accuracy: 0.41935483870967744
Delta: 0.0032846341158701766 	  Loss: 1.0474670728998592 	 Accuracy: 0.41935483870967744
Delta: 0.0037094705216947355 	  Loss: 1.0474339146551315 	 Accuracy: 0.41935483870967744
Delta: 0.003862749748777023 	  Loss: 1.0473663053418232 	 Accuracy: 0.41935483870967744
Delta: 0.003917767761967094 	  Loss: 1.0473064089504025 	 Accuracy: 0.41935483870967744
Delta: 0.0033671469532956183 	  Loss: 1.047227608434734 	 Accuracy: 0.41935483870967744
Delta: 0.0022956335529669756 	  Loss: 1.047194176843894 	 Accuracy: 0.41935483870967744
Delta: 0.002821934508162026 	  Loss: 1.0471905626001798 	 Accuracy: 0.41935483870967744
Delta: 0.0020480829064090924 	  Loss: 1.0471741190996706 	 Accuracy: 0.41935483870967744
Delta: 0.0022897955846283217 	  Loss: 1.0471751729354237 	 Accuracy: 0.41935483870967744
Delta: 0.0028921274085822084 	  Loss: 1.0471724727013845 	 Accuracy: 0.41935483870967744
Delta: 0.00283000243787812 	  Loss: 1.0471247502239442 	 Accuracy: 0.41935483870967744
Delta: 0.001807346077962914 	  Loss: 1.0471259007039715 	 Accuracy: 0.41935483870967744
Delta: 0.002057902095190718 	  Loss: 1.0471002774472624 	 Accuracy: 0.41935483870967744
Delta: 0.002544770327788703 	  Loss: 1.0470565663013596 	 Accuracy: 0.41935483870967744
Delta: 0.002222828803867513 	  Loss: 1.0470249027701386 	 Accuracy: 0.41935483870967744
Delta: 0.001544623323496096 	  Loss: 1.0470126985181711 	 Accuracy: 0.41935483870967744
Delta: 0.0020312341322583772 	  Loss: 1.047002456814865 	 Accuracy: 0.41935483870967744
Delta: 0.002386541397280293 	  Loss: 1.0469557409651498 	 Accuracy: 0.41935483870967744
Delta: 0.001879516682111349 	  Loss: 1.0469329254134712 	 Accuracy: 0.41935483870967744
Delta: 0.002820996969474805 	  Loss: 1.0469268028059422 	 Accuracy: 0.41935483870967744
Delta: 0.0031892031610815446 	  Loss: 1.0469467565717891 	 Accuracy: 0.41935483870967744
Delta: 0.0030064047950168946 	  Loss: 1.0469343398526498 	 Accuracy: 0.41935483870967744
Delta: 0.0031074806851866203 	  Loss: 1.0469219798262075 	 Accuracy: 0.41935483870967744
Delta: 0.002933327971984447 	  Loss: 1.0469295633903815 	 Accuracy: 0.41935483870967744
Delta: 0.0020964540432008476 	  Loss: 1.0469132939602164 	 Accuracy: 0.41935483870967744
Delta: 0.0017020531377902408 	  Loss: 1.0469087891865245 	 Accuracy: 0.41935483870967744
Delta: 0.0014801119783699873 	  Loss: 1.0469067958306943 	 Accuracy: 0.41935483870967744
Delta: 0.0020842780258580637 	  Loss: 1.0468939509391146 	 Accuracy: 0.41935483870967744
Delta: 0.001853999807806704 	  Loss: 1.0468934280314015 	 Accuracy: 0.41935483870967744
Delta: 0.0018284857226777327 	  Loss: 1.0468981471808885 	 Accuracy: 0.41935483870967744
Delta: 0.0018638236358013047 	  Loss: 1.0468804937493223 	 Accuracy: 0.41935483870967744
Delta: 0.00260252491845578 	  Loss: 1.0468685762611578 	 Accuracy: 0.41935483870967744
Delta: 0.0017860663904075266 	  Loss: 1.0468647695585303 	 Accuracy: 0.41935483870967744
Delta: 0.0013908128638818167 	  Loss: 1.0468631063672278 	 Accuracy: 0.41935483870967744
Delta: 0.0012739665460256599 	  Loss: 1.0468798564751314 	 Accuracy: 0.41935483870967744
Delta: 0.001001179116591289 	  Loss: 1.0468855518137785 	 Accuracy: 0.41935483870967744
Delta: 0.0007891717652016342 	  Loss: 1.0468955367154833 	 Accuracy: 0.41935483870967744
Delta: 0.0007823603628038863 	  Loss: 1.0468924065671095 	 Accuracy: 0.41935483870967744
Delta: 0.0009034180770253103 	  Loss: 1.0468898529842847 	 Accuracy: 0.41935483870967744
Delta: 0.0007798207084732234 	  Loss: 1.0468887121739934 	 Accuracy: 0.41935483870967744
Delta: 0.0008740389027528663 	  Loss: 1.0468963482318667 	 Accuracy: 0.41935483870967744
Delta: 0.00023971462062641455 	  Loss: 1.0468911399256142 	 Accuracy: 0.41935483870967744
Delta: 0.000170649727587915 	  Loss: 1.0468894370433837 	 Accuracy: 0.41935483870967744
Delta: 3.8697327911904145e-05 	  Loss: 1.0468888601560156 	 Accuracy: 0.41935483870967744
Delta: 2.1653730044937096e-06 	  Loss: 1.0468889128095578 	 Accuracy: 0.41935483870967744
converged at iter  65
Delta: 0.057495353161413916 	  Loss: 1.0635262876612401 	 Accuracy: 0.5
Delta: 0.03840743425236311 	  Loss: 1.0549143503858969 	 Accuracy: 0.27419354838709675
Delta: 0.03137880981366114 	  Loss: 1.0491614453556704 	 Accuracy: 0.25806451612903225
Delta: 0.02675708537638587 	  Loss: 1.0457184054251127 	 Accuracy: 0.25806451612903225

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01825197665091729 	  Loss: 1.0430259698173483 	 Accuracy: 0.25806451612903225
Delta: 0.013948865603674858 	  Loss: 1.04169714899666 	 Accuracy: 0.27419354838709675
Delta: 0.010203422598361373 	  Loss: 1.0409363970318926 	 Accuracy: 0.27419354838709675
Delta: 0.007502360426408375 	  Loss: 1.0405866752494637 	 Accuracy: 0.27419354838709675
Delta: 0.006497384766604 	  Loss: 1.0403816166422173 	 Accuracy: 0.27419354838709675
Delta: 0.005039508031377588 	  Loss: 1.0402538645478723 	 Accuracy: 0.27419354838709675
Delta: 0.004089308312658753 	  Loss: 1.0401221013896202 	 Accuracy: 0.27419354838709675
Delta: 0.0030170400410736648 	  Loss: 1.040063994329919 	 Accuracy: 0.27419354838709675
Delta: 0.0026930892961221525 	  Loss: 1.0400389780712815 	 Accuracy: 0.27419354838709675
Delta: 0.0027992464410808893 	  Loss: 1.0400278025333782 	 Accuracy: 0.27419354838709675
Delta: 0.0025813963818371857 	  Loss: 1.0400133151120396 	 Accuracy: 0.27419354838709675
Delta: 0.002157374393027744 	  Loss: 1.0399930615473727 	 Accuracy: 0.27419354838709675
Delta: 0.001589992918374802 	  Loss: 1.0399822444165854 	 Accuracy: 0.27419354838709675
Delta: 0.0013121625015214513 	  Loss: 1.0399713762693488 	 Accuracy: 0.27419354838709675
Delta: 0.001320427265356818 	  Loss: 1.0399645483805546 	 Accuracy: 0.27419354838709675
Delta: 0.0015538758771348735 	  Loss: 1.0399658896763566 	 Accuracy: 0.27419354838709675
Delta: 0.0023298208100675792 	  Loss: 1.0399578183789115 	 Accuracy: 0.27419354838709675
Delta: 0.0018359213328975276 	  Loss: 1.0399326035565442 	 Accuracy: 0.27419354838709675
Delta: 0.0019055132950766703 	  Loss: 1.0399109088396594 	 Accuracy: 0.27419354838709675
Delta: 0.0018812647821293876 	  Loss: 1.039894195161927 	 Accuracy: 0.27419354838709675
Delta: 0.0012047852469516532 	  Loss: 1.039891971239617 	 Accuracy: 0.27419354838709675
Delta: 0.001132075596132289 	  Loss: 1.0398890681084956 	 Accuracy: 0.27419354838709675
Delta: 0.0006217392882942863 	  Loss: 1.0398865891732565 	 Accuracy: 0.27419354838709675
Delta: 0.0014460415157923944 	  Loss: 1.03988334338672 	 Accuracy: 0.27419354838709675
Delta: 0.0007530643585977446 	  Loss: 1.039881172735265 	 Accuracy: 0.27419354838709675
Delta: 0.0009679517319932026 	  Loss: 1.0398744878256578 	 Accuracy: 0.27419354838709675
Delta: 0.0006490321776479033 	  Loss: 1.0398632241812356 	 Accuracy: 0.27419354838709675
Delta: 0.0006354677736611691 	  Loss: 1.0398563335554765 	 Accuracy: 0.27419354838709675
Delta: 0.000686741094356876 	  Loss: 1.0398519959472716 	 Accuracy: 0.27419354838709675
Delta: 0.001065136976728647 	  Loss: 1.0398460272981827 	 Accuracy: 0.27419354838709675
Delta: 0.0014265101763715124 	  Loss: 1.0398385109197297 	 Accuracy: 0.27419354838709675
Delta: 0.0010555927991109074 	  Loss: 1.0398275662629337 	 Accuracy: 0.27419354838709675
Delta: 0.0008118093562591688 	  Loss: 1.0398228280302058 	 Accuracy: 0.27419354838709675
Delta: 0.0007410730817810385 	  Loss: 1.0398173286667172 	 Accuracy: 0.27419354838709675
Delta: 0.00038013381345867347 	  Loss: 1.03981497742485 	 Accuracy: 0.27419354838709675
Delta: 0.0013493079536000489 	  Loss: 1.039814039310939 	 Accuracy: 0.27419354838709675
Delta: 0.0009527300379190097 	  Loss: 1.0398037346568545 	 Accuracy: 0.27419354838709675
Delta: 0.0008950182274067286 	  Loss: 1.0398003959338458 	 Accuracy: 0.27419354838709675
Delta: 0.001059289415738233 	  Loss: 1.0398014947818728 	 Accuracy: 0.27419354838709675
Delta: 0.0008659806028959519 	  Loss: 1.0398021614959498 	 Accuracy: 0.27419354838709675
Delta: 0.002188906042664842 	  Loss: 1.039802883862416 	 Accuracy: 0.27419354838709675
Delta: 0.0016153634594770869 	  Loss: 1.0398022414329857 	 Accuracy: 0.27419354838709675
Delta: 0.0009055106548170041 	  Loss: 1.0397908335294588 	 Accuracy: 0.27419354838709675
Delta: 0.0007384954394159806 	  Loss: 1.0397854138641254 	 Accuracy: 0.27419354838709675
Delta: 0.000685222296662747 	  Loss: 1.0397788900318727 	 Accuracy: 0.27419354838709675
Delta: 0.001644399475870389 	  Loss: 1.039773337029314 	 Accuracy: 0.27419354838709675
Delta: 0.001417452959828531 	  Loss: 1.0397569362113406 	 Accuracy: 0.27419354838709675
Delta: 0.0017989529395862655 	  Loss: 1.0397497696300757 	 Accuracy: 0.27419354838709675
Delta: 0.0013633328292298945 	  Loss: 1.0397428442798373 	 Accuracy: 0.27419354838709675
Delta: 0.0013835784878985578 	  Loss: 1.039748673326651 	 Accuracy: 0.27419354838709675
Delta: 0.001004272424035069 	  Loss: 1.039752049350744 	 Accuracy: 0.27419354838709675
Delta: 0.0011514532985406087 	  Loss: 1.0397540813251784 	 Accuracy: 0.27419354838709675
Delta: 0.0012899451885893978 	  Loss: 1.0397485532923492 	 Accuracy: 0.27419354838709675
Delta: 0.0012394970066639632 	  Loss: 1.039746760459604 	 Accuracy: 0.27419354838709675
Delta: 0.0009399585928333334 	  Loss: 1.0397536920762482 	 Accuracy: 0.27419354838709675
Delta: 0.0009928343183304733 	  Loss: 1.0397475784375425 	 Accuracy: 0.27419354838709675
Delta: 0.0021285529235408962 	  Loss: 1.0397401889899414 	 Accuracy: 0.27419354838709675
Delta: 0.000995774532523361 	  Loss: 1.0397334133964886 	 Accuracy: 0.27419354838709675
Delta: 0.0014078397080966164 	  Loss: 1.0397314668591648 	 Accuracy: 0.27419354838709675
Delta: 0.0009649576568137402 	  Loss: 1.039718913930081 	 Accuracy: 0.27419354838709675
Delta: 0.0008635692383775016 	  Loss: 1.0397150143684466 	 Accuracy: 0.27419354838709675
Delta: 0.0006685048669155752 	  Loss: 1.0397077789298947 	 Accuracy: 0.27419354838709675
Delta: 0.00037329238577676405 	  Loss: 1.0397066353535593 	 Accuracy: 0.27419354838709675
Delta: 0.00032187906410198827 	  Loss: 1.0397079694029223 	 Accuracy: 0.27419354838709675
Delta: 0.00037777853165141067 	  Loss: 1.0397066452233812 	 Accuracy: 0.27419354838709675
Delta: 0.00023580554886331158 	  Loss: 1.0397039578213736 	 Accuracy: 0.27419354838709675
Delta: 9.573824126897458e-05 	  Loss: 1.0397046080321068 	 Accuracy: 0.27419354838709675
Delta: 5.358479909558395e-05 	  Loss: 1.0397050628688036 	 Accuracy: 0.27419354838709675
Delta: 4.771304542618203e-06 	  Loss: 1.0397050770893963 	 Accuracy: 0.27419354838709675
converged at iter  72
Delta: 0.05399455330565771 	  Loss: 1.0778126721701033 	 Accuracy: 0.41935483870967744
Delta: 0.04805218202800057 	  Loss: 1.0707661593120912 	 Accuracy: 0.3064516129032258
Delta: 0.029043242981324012 	  Loss: 1.0644532351250886 	 Accuracy: 0.27419354838709675
Delta: 0.02394593506337024 	  Loss: 1.0607675832337462 	 Accuracy: 0.2903225806451613

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.018006704046387278 	  Loss: 1.0592006058605266 	 Accuracy: 0.2903225806451613
Delta: 0.016424229165538165 	  Loss: 1.0580148055731007 	 Accuracy: 0.2903225806451613
Delta: 0.011249453685908604 	  Loss: 1.057294743073819 	 Accuracy: 0.2903225806451613
Delta: 0.00936911660316895 	  Loss: 1.0567508637056242 	 Accuracy: 0.2903225806451613
Delta: 0.008672085673471722 	  Loss: 1.0563625428015957 	 Accuracy: 0.2903225806451613
Delta: 0.008101634319707824 	  Loss: 1.0560569771554156 	 Accuracy: 0.2903225806451613
Delta: 0.007308487404470687 	  Loss: 1.055836038139488 	 Accuracy: 0.2903225806451613
Delta: 0.006249007996529035 	  Loss: 1.055589555703718 	 Accuracy: 0.2903225806451613
Delta: 0.005677517459655967 	  Loss: 1.0554154331785548 	 Accuracy: 0.2903225806451613
Delta: 0.00588213521639027 	  Loss: 1.0553325673393754 	 Accuracy: 0.2903225806451613
Delta: 0.0051262637328990165 	  Loss: 1.0551978433056446 	 Accuracy: 0.2903225806451613
Delta: 0.004518341874968553 	  Loss: 1.0551286974733896 	 Accuracy: 0.2903225806451613
Delta: 0.004792913861282313 	  Loss: 1.0550418643945247 	 Accuracy: 0.2903225806451613
Delta: 0.0038439302760914806 	  Loss: 1.0550211913442324 	 Accuracy: 0.2903225806451613
Delta: 0.0030282246441715897 	  Loss: 1.0550155303414162 	 Accuracy: 0.2903225806451613
Delta: 0.003308035325336913 	  Loss: 1.05498097125789 	 Accuracy: 0.2903225806451613
Delta: 0.0031202181334910673 	  Loss: 1.054920575062161 	 Accuracy: 0.2903225806451613
Delta: 0.003427813688608737 	  Loss: 1.0548873364685472 	 Accuracy: 0.2903225806451613
Delta: 0.0025295337517341372 	  Loss: 1.0548530445129316 	 Accuracy: 0.2903225806451613
Delta: 0.00222390037979702 	  Loss: 1.0548273654812603 	 Accuracy: 0.2903225806451613
Delta: 0.001995474414817331 	  Loss: 1.0548152566557683 	 Accuracy: 0.2903225806451613
Delta: 0.0025022115607282753 	  Loss: 1.05480466971678 	 Accuracy: 0.2903225806451613
Delta: 0.0026450931872494324 	  Loss: 1.0547726418286643 	 Accuracy: 0.2903225806451613
Delta: 0.0031652444436849948 	  Loss: 1.0547618141403112 	 Accuracy: 0.2903225806451613
Delta: 0.0032461244418278126 	  Loss: 1.054737746037843 	 Accuracy: 0.2903225806451613
Delta: 0.0037888994223306627 	  Loss: 1.0546750581454654 	 Accuracy: 0.2903225806451613
Delta: 0.003719333479372607 	  Loss: 1.0545977945665648 	 Accuracy: 0.2903225806451613
Delta: 0.0032920448825149596 	  Loss: 1.054527500237835 	 Accuracy: 0.2903225806451613
Delta: 0.003829681864484631 	  Loss: 1.054475538501138 	 Accuracy: 0.2903225806451613
Delta: 0.0036868091808281095 	  Loss: 1.054395318809504 	 Accuracy: 0.2903225806451613
Delta: 0.004175221296612021 	  Loss: 1.0543258638332547 	 Accuracy: 0.2903225806451613
Delta: 0.0036051257284300023 	  Loss: 1.0542811882423184 	 Accuracy: 0.2903225806451613
Delta: 0.004308550871970201 	  Loss: 1.054226169783218 	 Accuracy: 0.2903225806451613
Delta: 0.0034511004545228156 	  Loss: 1.0541602701362365 	 Accuracy: 0.2903225806451613
Delta: 0.0035362073456135347 	  Loss: 1.0540976160771551 	 Accuracy: 0.2903225806451613
Delta: 0.0037268408326160676 	  Loss: 1.0540605130996825 	 Accuracy: 0.2903225806451613
Delta: 0.004043308496885512 	  Loss: 1.054004581765494 	 Accuracy: 0.2903225806451613
Delta: 0.004272230458547102 	  Loss: 1.0539415581922982 	 Accuracy: 0.2903225806451613
Delta: 0.003921931411790818 	  Loss: 1.0538616974781876 	 Accuracy: 0.2903225806451613
Delta: 0.003207407710570163 	  Loss: 1.053799304251687 	 Accuracy: 0.2903225806451613
Delta: 0.0032937789827650024 	  Loss: 1.0537688223587551 	 Accuracy: 0.2903225806451613
Delta: 0.0033672323972088504 	  Loss: 1.053762983156913 	 Accuracy: 0.2903225806451613
Delta: 0.0032553762646793205 	  Loss: 1.0537591428712891 	 Accuracy: 0.2903225806451613
Delta: 0.002233092984471332 	  Loss: 1.0537385240706763 	 Accuracy: 0.2903225806451613
Delta: 0.0020604222201431087 	  Loss: 1.0537417036231425 	 Accuracy: 0.2903225806451613
Delta: 0.0020930124253607436 	  Loss: 1.0537280813334187 	 Accuracy: 0.2903225806451613
Delta: 0.0018830284391954959 	  Loss: 1.0537028926023027 	 Accuracy: 0.2903225806451613
Delta: 0.0013223686804312174 	  Loss: 1.0536652871744536 	 Accuracy: 0.2903225806451613
Delta: 0.0014244167231590977 	  Loss: 1.0536601804071513 	 Accuracy: 0.2903225806451613
Delta: 0.002107599991196817 	  Loss: 1.053661493267491 	 Accuracy: 0.2903225806451613
Delta: 0.0026312528539281133 	  Loss: 1.053637947096421 	 Accuracy: 0.2903225806451613
Delta: 0.002681923738328658 	  Loss: 1.0536193949879742 	 Accuracy: 0.2903225806451613
Delta: 0.0023407409366891408 	  Loss: 1.0535957522632788 	 Accuracy: 0.2903225806451613
Delta: 0.0023452341489993713 	  Loss: 1.0535670749366224 	 Accuracy: 0.2903225806451613
Delta: 0.00216702805884897 	  Loss: 1.0535410708323916 	 Accuracy: 0.2903225806451613
Delta: 0.0023663389659275913 	  Loss: 1.0535287413870775 	 Accuracy: 0.2903225806451613
Delta: 0.002653339252809354 	  Loss: 1.0535292939834815 	 Accuracy: 0.2903225806451613
Delta: 0.0032715294321040023 	  Loss: 1.0535160277012157 	 Accuracy: 0.2903225806451613
Delta: 0.0028730240704355043 	  Loss: 1.0535113972078258 	 Accuracy: 0.2903225806451613
Delta: 0.0032481643684538312 	  Loss: 1.0535035450481542 	 Accuracy: 0.2903225806451613
Delta: 0.002465234421119428 	  Loss: 1.0535118053653896 	 Accuracy: 0.2903225806451613
Delta: 0.002085398048501845 	  Loss: 1.053511148134083 	 Accuracy: 0.2903225806451613
Delta: 0.001971783068285397 	  Loss: 1.053517261329847 	 Accuracy: 0.2903225806451613
Delta: 0.0015569987923854096 	  Loss: 1.0535180913882547 	 Accuracy: 0.2903225806451613
Delta: 0.0021899190832145076 	  Loss: 1.0535338870920752 	 Accuracy: 0.2903225806451613
Delta: 0.001991604705472493 	  Loss: 1.0535501494263966 	 Accuracy: 0.2903225806451613
Delta: 0.002032959300551483 	  Loss: 1.0535637889745546 	 Accuracy: 0.2903225806451613
Delta: 0.00221517524882994 	  Loss: 1.053566584001014 	 Accuracy: 0.2903225806451613
Delta: 0.002290589150690716 	  Loss: 1.0535652279030678 	 Accuracy: 0.2903225806451613
Delta: 0.0028551494008775833 	  Loss: 1.0535508525749835 	 Accuracy: 0.2903225806451613
Delta: 0.002644702948051738 	  Loss: 1.053531762700086 	 Accuracy: 0.2903225806451613
Delta: 0.0024830577335375964 	  Loss: 1.053506479925364 	 Accuracy: 0.2903225806451613
Delta: 0.0022513241929920757 	  Loss: 1.0534715793015272 	 Accuracy: 0.2903225806451613
Delta: 0.0013582146381576673 	  Loss: 1.0534384054348538 	 Accuracy: 0.2903225806451613
Delta: 0.0016775133854725914 	  Loss: 1.053416086946294 	 Accuracy: 0.2903225806451613
Delta: 0.0019753862584818353 	  Loss: 1.0533905539359851 	 Accuracy: 0.2903225806451613
Delta: 0.0011594940326157108 	  Loss: 1.0533732396274869 	 Accuracy: 0.2903225806451613
Delta: 0.000578757448839892 	  Loss: 1.0533673909314851 	 Accuracy: 0.2903225806451613
Delta: 0.00011890876230214278 	  Loss: 1.0533645943408572 	 Accuracy: 0.2903225806451613
Delta: 0.00026875850636135206 	  Loss: 1.0533647159888213 	 Accuracy: 0.2903225806451613
Delta: 0.00022340752589071627 	  Loss: 1.0533648611083404 	 Accuracy: 0.2903225806451613
Delta: 0.0016924343816944645 	  Loss: 1.0533641545327206 	 Accuracy: 0.2903225806451613
Delta: 0.00019781383220341444 	  Loss: 1.0533625351436138 	 Accuracy: 0.2903225806451613
Delta: 0.0003330785008649456 	  Loss: 1.0533611983506657 	 Accuracy: 0.2903225806451613
Delta: 0.0006117977108559692 	  Loss: 1.0533590248263434 	 Accuracy: 0.2903225806451613
Delta: 0.0002816256061712376 	  Loss: 1.0533579592440057 	 Accuracy: 0.2903225806451613
Delta: 0.00020723862072736176 	  Loss: 1.0533576656402328 	 Accuracy: 0.2903225806451613
Delta: 1.418419960909471e-05 	  Loss: 1.0533567929083358 	 Accuracy: 0.2903225806451613
Delta: 3.480132351107075e-17 	  Loss: 1.0533567929083358 	 Accuracy: 0.2903225806451613
converged at iter  92
Delta: 0.054330316356657596 	  Loss: 1.0726161922897066 	 Accuracy: 0.5714285714285714
Delta: 0.038739402436393275 	  Loss: 1.0689609917184713 	 Accuracy: 0.5873015873015873
Delta: 0.03976927173015972 	  Loss: 1.0701945922382121 	 Accuracy: 0.5873015873015873

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02853693417791744 	  Loss: 1.065101409605457 	 Accuracy: 0.5873015873015873
Delta: 0.020986294452803544 	  Loss: 1.061623005772471 	 Accuracy: 0.5873015873015873
Delta: 0.016754885387087432 	  Loss: 1.0597471350373018 	 Accuracy: 0.5873015873015873
Delta: 0.01149467321567371 	  Loss: 1.0588086108405586 	 Accuracy: 0.5873015873015873
Delta: 0.0084838190883486 	  Loss: 1.0583741350586005 	 Accuracy: 0.5873015873015873
Delta: 0.006876716832658192 	  Loss: 1.0581459810108211 	 Accuracy: 0.5873015873015873
Delta: 0.0070694824310196655 	  Loss: 1.0580147649185565 	 Accuracy: 0.5873015873015873
Delta: 0.006063348956945653 	  Loss: 1.057881342299982 	 Accuracy: 0.5873015873015873
Delta: 0.0067751120117852445 	  Loss: 1.057793363471652 	 Accuracy: 0.5873015873015873
Delta: 0.006438528967146142 	  Loss: 1.0576306115791576 	 Accuracy: 0.5873015873015873
Delta: 0.006797064445006709 	  Loss: 1.0574870392372935 	 Accuracy: 0.5873015873015873
Delta: 0.006500133781430901 	  Loss: 1.0573758689299093 	 Accuracy: 0.5873015873015873
Delta: 0.006227224795417038 	  Loss: 1.057248350944211 	 Accuracy: 0.5873015873015873
Delta: 0.0072053655375558774 	  Loss: 1.0571073081092348 	 Accuracy: 0.5873015873015873
Delta: 0.007860857051990057 	  Loss: 1.0569415444500168 	 Accuracy: 0.5873015873015873
Delta: 0.007944625827776438 	  Loss: 1.056752709034013 	 Accuracy: 0.5873015873015873
Delta: 0.006874206914840974 	  Loss: 1.0565539576127128 	 Accuracy: 0.5873015873015873
Delta: 0.007304837790006406 	  Loss: 1.0563841097151059 	 Accuracy: 0.5873015873015873
Delta: 0.006648823447746974 	  Loss: 1.0562604257313435 	 Accuracy: 0.5873015873015873
Delta: 0.00632760558726552 	  Loss: 1.0561536979867137 	 Accuracy: 0.5873015873015873
Delta: 0.006766848898054199 	  Loss: 1.056027673880009 	 Accuracy: 0.5873015873015873
Delta: 0.006884290352598928 	  Loss: 1.055864987719318 	 Accuracy: 0.5873015873015873
Delta: 0.00822374118289349 	  Loss: 1.0557118628560258 	 Accuracy: 0.5873015873015873
Delta: 0.006981404849339022 	  Loss: 1.055427918728598 	 Accuracy: 0.5873015873015873
Delta: 0.006079527368592325 	  Loss: 1.0552591721747646 	 Accuracy: 0.5873015873015873
Delta: 0.006172718003681702 	  Loss: 1.0551258527450726 	 Accuracy: 0.5873015873015873
Delta: 0.004798659534329801 	  Loss: 1.0550159036846076 	 Accuracy: 0.5873015873015873
Delta: 0.004327552414790952 	  Loss: 1.0549331991240032 	 Accuracy: 0.5873015873015873
Delta: 0.003331094571111845 	  Loss: 1.0548795927156642 	 Accuracy: 0.5873015873015873
Delta: 0.0032011483697384976 	  Loss: 1.0548232036844258 	 Accuracy: 0.5873015873015873
Delta: 0.0031763629647553367 	  Loss: 1.0547808777319947 	 Accuracy: 0.5873015873015873
Delta: 0.0022443463372057507 	  Loss: 1.0547512584185632 	 Accuracy: 0.5873015873015873
Delta: 0.002045324027481701 	  Loss: 1.0547270920302996 	 Accuracy: 0.5873015873015873
Delta: 0.001000749601603446 	  Loss: 1.054717289612304 	 Accuracy: 0.5873015873015873
Delta: 0.0017056565061311978 	  Loss: 1.0547136543892048 	 Accuracy: 0.5873015873015873
Delta: 0.0010205369844212312 	  Loss: 1.0547024908176161 	 Accuracy: 0.5873015873015873
Delta: 0.0004932035132765977 	  Loss: 1.0547038368814143 	 Accuracy: 0.5873015873015873
Delta: 0.0009572928820658314 	  Loss: 1.0547033827393315 	 Accuracy: 0.5873015873015873
Delta: 0.001121106240314583 	  Loss: 1.0547110464988492 	 Accuracy: 0.5873015873015873
Delta: 0.0005259098901297891 	  Loss: 1.0547156947960423 	 Accuracy: 0.5873015873015873
Delta: 0.00130065172360616 	  Loss: 1.0547154144432378 	 Accuracy: 0.5873015873015873
Delta: 0.0009526609046963575 	  Loss: 1.054722624557994 	 Accuracy: 0.5873015873015873
Delta: 0.0010344283276860079 	  Loss: 1.054719304548618 	 Accuracy: 0.5873015873015873
Delta: 0.0017351147050125163 	  Loss: 1.0547160576979744 	 Accuracy: 0.5873015873015873
Delta: 0.0018509878409242585 	  Loss: 1.0547027489162133 	 Accuracy: 0.5873015873015873
Delta: 0.0024859718687060663 	  Loss: 1.0546823964693606 	 Accuracy: 0.5873015873015873
Delta: 0.001880637499428114 	  Loss: 1.0546438774142737 	 Accuracy: 0.5873015873015873
Delta: 0.0025999469044602234 	  Loss: 1.0546287279547806 	 Accuracy: 0.5873015873015873
Delta: 0.0024739256719601096 	  Loss: 1.0546162413631741 	 Accuracy: 0.5873015873015873
Delta: 0.002731884085983478 	  Loss: 1.0545962770561728 	 Accuracy: 0.5873015873015873
Delta: 0.002988123744936664 	  Loss: 1.054571250198447 	 Accuracy: 0.5873015873015873
Delta: 0.002389830113504964 	  Loss: 1.0545466048754752 	 Accuracy: 0.5873015873015873
Delta: 0.0016850864472550788 	  Loss: 1.0545426668745905 	 Accuracy: 0.5873015873015873
Delta: 0.0016531168763994151 	  Loss: 1.0545416483139718 	 Accuracy: 0.5873015873015873
Delta: 0.0014826453053847746 	  Loss: 1.0545431133389045 	 Accuracy: 0.5873015873015873
Delta: 0.0019818886177074215 	  Loss: 1.0545418772793091 	 Accuracy: 0.5873015873015873
Delta: 0.0018512897052594722 	  Loss: 1.0545415771003173 	 Accuracy: 0.5873015873015873
Delta: 0.0027989062824202962 	  Loss: 1.0545114954702002 	 Accuracy: 0.5873015873015873
Delta: 0.0020556733282387496 	  Loss: 1.0544830931739073 	 Accuracy: 0.5873015873015873
Delta: 0.0018669283541345187 	  Loss: 1.0544686227112314 	 Accuracy: 0.5873015873015873
Delta: 0.0022092380139922757 	  Loss: 1.054456210922946 	 Accuracy: 0.5873015873015873
Delta: 0.0016342980117440313 	  Loss: 1.0544524121484087 	 Accuracy: 0.5873015873015873
Delta: 0.0014880465101452032 	  Loss: 1.054445869201778 	 Accuracy: 0.5873015873015873
Delta: 0.0012284238927895192 	  Loss: 1.0544406292619959 	 Accuracy: 0.5873015873015873
Delta: 0.001092878216822793 	  Loss: 1.0544491598582317 	 Accuracy: 0.5873015873015873
Delta: 0.0017087116132975335 	  Loss: 1.0544561225702718 	 Accuracy: 0.5873015873015873
Delta: 0.002717864556449814 	  Loss: 1.05444911129808 	 Accuracy: 0.5873015873015873
Delta: 0.0025800634846080907 	  Loss: 1.0544305804863683 	 Accuracy: 0.5873015873015873
Delta: 0.0021535871693289404 	  Loss: 1.054432476746216 	 Accuracy: 0.5873015873015873
Delta: 0.002824829060579617 	  Loss: 1.0544371899063933 	 Accuracy: 0.5873015873015873
Delta: 0.002189393022974104 	  Loss: 1.0544245069544722 	 Accuracy: 0.5873015873015873
Delta: 0.0017452525728185555 	  Loss: 1.0544280280871299 	 Accuracy: 0.5873015873015873
Delta: 0.0017730560897113534 	  Loss: 1.0544158013933693 	 Accuracy: 0.5873015873015873
Delta: 0.002859902082772517 	  Loss: 1.0544071707191527 	 Accuracy: 0.5873015873015873
Delta: 0.001684683054180984 	  Loss: 1.054384261034539 	 Accuracy: 0.5873015873015873
Delta: 0.0013755222342238251 	  Loss: 1.0543847146253236 	 Accuracy: 0.5873015873015873
Delta: 0.0011404073771586276 	  Loss: 1.0543774071137586 	 Accuracy: 0.5873015873015873
Delta: 0.0007498991806270002 	  Loss: 1.054372902768192 	 Accuracy: 0.5873015873015873
Delta: 0.00040720563520559006 	  Loss: 1.0543669656407255 	 Accuracy: 0.5873015873015873
Delta: 0.00011273701032831838 	  Loss: 1.0543652019907543 	 Accuracy: 0.5873015873015873
Delta: 0.00016006598473183945 	  Loss: 1.0543647556545577 	 Accuracy: 0.5873015873015873
Delta: 0.00033053089911379806 	  Loss: 1.054364910431362 	 Accuracy: 0.5873015873015873
Delta: 0.00024327156568300433 	  Loss: 1.0543636774778555 	 Accuracy: 0.5873015873015873
Delta: 0.0002424685878848143 	  Loss: 1.0543656163404789 	 Accuracy: 0.5873015873015873
Delta: 0.0001975524306028355 	  Loss: 1.0543678917999952 	 Accuracy: 0.5873015873015873
Delta: 0.000561689835125987 	  Loss: 1.054368952300369 	 Accuracy: 0.5873015873015873
Delta: 0.0005844340458954176 	  Loss: 1.0543687677714064 	 Accuracy: 0.5873015873015873
Delta: 0.0005385569514321672 	  Loss: 1.054367541400486 	 Accuracy: 0.5873015873015873
Delta: 0.0004439190480178139 	  Loss: 1.0543646300128144 	 Accuracy: 0.5873015873015873
Delta: 0.0001403191737686122 	  Loss: 1.054368351188708 	 Accuracy: 0.5873015873015873
Delta: 2.6652110415300074e-05 	  Loss: 1.0543686697708532 	 Accuracy: 0.5873015873015873
Delta: 1.4411580341490834e-06 	  Loss: 1.0543687558432717 	 Accuracy: 0.5873015873015873
converged at iter  94
Delta: 0.05248139161527261 	  Loss: 1.0687050246396939 	 Accuracy: 0.4603174603174603
Delta: 0.04314154554667611 	  Loss: 1.0592456937845112 	 Accuracy: 0.36507936507936506
Delta: 0.03382531864668234 	  Loss: 1.0522148675916685 	 Accuracy: 0.3492063492063492

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.024533536182348728 	  Loss: 1.0474398163104681 	 Accuracy: 0.3492063492063492
Delta: 0.01737301124091717 	  Loss: 1.0454849898219019 	 Accuracy: 0.3333333333333333
Delta: 0.011321012164194422 	  Loss: 1.0447048802085652 	 Accuracy: 0.3333333333333333
Delta: 0.007596224972164942 	  Loss: 1.0442117682713552 	 Accuracy: 0.3333333333333333
Delta: 0.006036693099647239 	  Loss: 1.0439887661663216 	 Accuracy: 0.3333333333333333
Delta: 0.005391602144750659 	  Loss: 1.0438646365412465 	 Accuracy: 0.3333333333333333
Delta: 0.005270817423481542 	  Loss: 1.0437724462333724 	 Accuracy: 0.3333333333333333
Delta: 0.005847680947507619 	  Loss: 1.0436813991851346 	 Accuracy: 0.3333333333333333
Delta: 0.005431871103282319 	  Loss: 1.0435194446952905 	 Accuracy: 0.3333333333333333
Delta: 0.005092658244234679 	  Loss: 1.043404442249828 	 Accuracy: 0.3333333333333333
Delta: 0.005521829284659396 	  Loss: 1.0432906473002226 	 Accuracy: 0.3333333333333333
Delta: 0.005285675989713843 	  Loss: 1.04315619741385 	 Accuracy: 0.3333333333333333
Delta: 0.0047146174993013745 	  Loss: 1.0430559874469063 	 Accuracy: 0.3333333333333333
Delta: 0.004351960571992951 	  Loss: 1.0429483059285765 	 Accuracy: 0.3333333333333333
Delta: 0.004008967977086083 	  Loss: 1.0428506841908516 	 Accuracy: 0.3333333333333333
Delta: 0.004091424413575068 	  Loss: 1.0428057332704674 	 Accuracy: 0.3333333333333333
Delta: 0.003285728495185217 	  Loss: 1.042785742860626 	 Accuracy: 0.3333333333333333
Delta: 0.0025851015067200754 	  Loss: 1.0427703752733475 	 Accuracy: 0.3333333333333333
Delta: 0.0027490094038267504 	  Loss: 1.0427703667884853 	 Accuracy: 0.3333333333333333
converged at iter  21
Delta: 0.05748498182725821 	  Loss: 1.081933670645519 	 Accuracy: 0.11290322580645161
Delta: 0.04689561921860002 	  Loss: 1.0761887416088047 	 Accuracy: 0.11290322580645161
Delta: 0.03371543484435324 	  Loss: 1.072932544886203 	 Accuracy: 0.08064516129032258

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.032935286403582974 	  Loss: 1.0704211419740055 	 Accuracy: 0.0967741935483871
Delta: 0.02241208629739806 	  Loss: 1.0673325010955625 	 Accuracy: 0.0967741935483871
Delta: 0.019130893348406855 	  Loss: 1.065041573688686 	 Accuracy: 0.0967741935483871
Delta: 0.016618598775892134 	  Loss: 1.0632851006029014 	 Accuracy: 0.0967741935483871
Delta: 0.014452051004706784 	  Loss: 1.062137168776457 	 Accuracy: 0.0967741935483871
Delta: 0.013803597391558505 	  Loss: 1.0611075475797225 	 Accuracy: 0.0967741935483871
Delta: 0.010239356613889375 	  Loss: 1.0603372242703248 	 Accuracy: 0.0967741935483871
Delta: 0.008661342951874084 	  Loss: 1.0599406741660413 	 Accuracy: 0.0967741935483871
Delta: 0.007171607573969337 	  Loss: 1.0597810816012796 	 Accuracy: 0.0967741935483871
Delta: 0.0075530392941718615 	  Loss: 1.059621857963545 	 Accuracy: 0.0967741935483871
Delta: 0.005773452902047371 	  Loss: 1.0595304732400415 	 Accuracy: 0.0967741935483871
Delta: 0.00537457328341809 	  Loss: 1.059441661058376 	 Accuracy: 0.0967741935483871
Delta: 0.005024778740709943 	  Loss: 1.0593819823235444 	 Accuracy: 0.0967741935483871
Delta: 0.004532147508343099 	  Loss: 1.0593405460517498 	 Accuracy: 0.0967741935483871
Delta: 0.004511168046743307 	  Loss: 1.059274536936988 	 Accuracy: 0.0967741935483871
Delta: 0.004984945302925975 	  Loss: 1.059221268868317 	 Accuracy: 0.0967741935483871
Delta: 0.004012505407978104 	  Loss: 1.0592145277115512 	 Accuracy: 0.0967741935483871
Delta: 0.003836774005749495 	  Loss: 1.0591800622676524 	 Accuracy: 0.0967741935483871
Delta: 0.0042383336092721696 	  Loss: 1.0591595933364433 	 Accuracy: 0.0967741935483871
Delta: 0.004025413100129747 	  Loss: 1.0591442574582692 	 Accuracy: 0.0967741935483871
Delta: 0.003939073301624145 	  Loss: 1.0591469600718144 	 Accuracy: 0.0967741935483871
Delta: 0.0029044908869959676 	  Loss: 1.059137895341968 	 Accuracy: 0.0967741935483871
Delta: 0.0028139387670957305 	  Loss: 1.059125509207203 	 Accuracy: 0.0967741935483871
Delta: 0.002931768738224408 	  Loss: 1.0591303531031784 	 Accuracy: 0.0967741935483871
Delta: 0.0034050383824830335 	  Loss: 1.0590883389630166 	 Accuracy: 0.0967741935483871
Delta: 0.00366485731704734 	  Loss: 1.0590336029226193 	 Accuracy: 0.0967741935483871
Delta: 0.004132428393265601 	  Loss: 1.0589904476808725 	 Accuracy: 0.0967741935483871
Delta: 0.0035192964818581175 	  Loss: 1.058940723713334 	 Accuracy: 0.0967741935483871
Delta: 0.0035987436373659102 	  Loss: 1.0589143446150664 	 Accuracy: 0.0967741935483871
Delta: 0.0035238064175318285 	  Loss: 1.0589198980478682 	 Accuracy: 0.0967741935483871
Delta: 0.003692803956649704 	  Loss: 1.0589023229002272 	 Accuracy: 0.0967741935483871
Delta: 0.0035566214617985983 	  Loss: 1.0588956991735041 	 Accuracy: 0.0967741935483871
Delta: 0.004124277073470806 	  Loss: 1.0588750841452192 	 Accuracy: 0.0967741935483871
Delta: 0.004262257614736226 	  Loss: 1.0588689799732343 	 Accuracy: 0.0967741935483871
Delta: 0.003539579192923196 	  Loss: 1.0588202289920008 	 Accuracy: 0.0967741935483871
Delta: 0.003246132650507997 	  Loss: 1.0588222738842918 	 Accuracy: 0.0967741935483871
Delta: 0.00404134184784392 	  Loss: 1.05879401830208 	 Accuracy: 0.0967741935483871
Delta: 0.004738639794710332 	  Loss: 1.0587121449131354 	 Accuracy: 0.0967741935483871
Delta: 0.005458816352013053 	  Loss: 1.0586624652793872 	 Accuracy: 0.0967741935483871
Delta: 0.005393105421137341 	  Loss: 1.0586311736532397 	 Accuracy: 0.0967741935483871
Delta: 0.005347610686305255 	  Loss: 1.0586080025283564 	 Accuracy: 0.0967741935483871
Delta: 0.004705918760529978 	  Loss: 1.058545359415346 	 Accuracy: 0.0967741935483871
Delta: 0.005171392080506314 	  Loss: 1.0585236334816357 	 Accuracy: 0.0967741935483871
Delta: 0.004827900603966366 	  Loss: 1.058520951291849 	 Accuracy: 0.0967741935483871
Delta: 0.005010917380322735 	  Loss: 1.0585063905685321 	 Accuracy: 0.0967741935483871
Delta: 0.004244552647762291 	  Loss: 1.0585020602482886 	 Accuracy: 0.0967741935483871
Delta: 0.004559486096850601 	  Loss: 1.0584694814472497 	 Accuracy: 0.0967741935483871
Delta: 0.0043373232068176825 	  Loss: 1.0584354591386451 	 Accuracy: 0.0967741935483871
Delta: 0.004274366378467866 	  Loss: 1.058396218273388 	 Accuracy: 0.0967741935483871
Delta: 0.0033157456516488067 	  Loss: 1.0583892010636573 	 Accuracy: 0.0967741935483871
Delta: 0.002525996843399245 	  Loss: 1.0583887865549835 	 Accuracy: 0.0967741935483871
Delta: 0.0022710331625764805 	  Loss: 1.0583710843046759 	 Accuracy: 0.0967741935483871
Delta: 0.0023101315557077103 	  Loss: 1.0583788736947783 	 Accuracy: 0.0967741935483871
Delta: 0.0019022147436461255 	  Loss: 1.058396015621192 	 Accuracy: 0.0967741935483871
Delta: 0.0013400603807707963 	  Loss: 1.0584016267650136 	 Accuracy: 0.0967741935483871
Delta: 0.0021970808628414065 	  Loss: 1.0583996473752366 	 Accuracy: 0.0967741935483871
Delta: 0.0015624065061854123 	  Loss: 1.058411814281967 	 Accuracy: 0.0967741935483871
Delta: 0.0019922443560193956 	  Loss: 1.0584172395920388 	 Accuracy: 0.0967741935483871
Delta: 0.0015171871555460146 	  Loss: 1.0584152924136507 	 Accuracy: 0.0967741935483871
Delta: 0.0016261057767461458 	  Loss: 1.0584063433274578 	 Accuracy: 0.0967741935483871
Delta: 0.0015975008520584825 	  Loss: 1.0584011472403734 	 Accuracy: 0.0967741935483871
Delta: 0.0014120737682746644 	  Loss: 1.0583928774987337 	 Accuracy: 0.0967741935483871
Delta: 0.001144375008457429 	  Loss: 1.058378498822832 	 Accuracy: 0.0967741935483871
Delta: 0.0018308540196921481 	  Loss: 1.0583719329366559 	 Accuracy: 0.0967741935483871
Delta: 0.0016265554792083477 	  Loss: 1.0583672750507782 	 Accuracy: 0.0967741935483871
Delta: 0.0012749256258480712 	  Loss: 1.0583587443245237 	 Accuracy: 0.0967741935483871
Delta: 0.0014986364648157072 	  Loss: 1.058356194707751 	 Accuracy: 0.0967741935483871
Delta: 0.0011448799951478258 	  Loss: 1.0583667241586023 	 Accuracy: 0.0967741935483871
Delta: 0.0014941964299615802 	  Loss: 1.0583808245428394 	 Accuracy: 0.0967741935483871
Delta: 0.002214538707205495 	  Loss: 1.0583938201234642 	 Accuracy: 0.0967741935483871
Delta: 0.0024785865096564707 	  Loss: 1.058392470484266 	 Accuracy: 0.0967741935483871
Delta: 0.002961223864445627 	  Loss: 1.05841812011706 	 Accuracy: 0.0967741935483871
Delta: 0.003308551832300385 	  Loss: 1.058433279817239 	 Accuracy: 0.0967741935483871
Delta: 0.0037531002048952593 	  Loss: 1.058406065406861 	 Accuracy: 0.0967741935483871
Delta: 0.003784881672428547 	  Loss: 1.0583940304150836 	 Accuracy: 0.0967741935483871
Delta: 0.004588017049505371 	  Loss: 1.0583551195168024 	 Accuracy: 0.0967741935483871
Delta: 0.005150038408621746 	  Loss: 1.0583344746867827 	 Accuracy: 0.0967741935483871
Delta: 0.005333125811108698 	  Loss: 1.0582584117093217 	 Accuracy: 0.0967741935483871
Delta: 0.005581520029533692 	  Loss: 1.0581927539406455 	 Accuracy: 0.0967741935483871
Delta: 0.005255782307976881 	  Loss: 1.058154701100636 	 Accuracy: 0.0967741935483871
Delta: 0.004364239525103453 	  Loss: 1.0581152137916172 	 Accuracy: 0.0967741935483871
Delta: 0.004350052830857493 	  Loss: 1.0580853543879813 	 Accuracy: 0.0967741935483871
Delta: 0.004823701319190213 	  Loss: 1.0580679018222956 	 Accuracy: 0.0967741935483871
Delta: 0.00483375537962707 	  Loss: 1.0580050428892198 	 Accuracy: 0.0967741935483871
Delta: 0.005013409300527662 	  Loss: 1.057974341554604 	 Accuracy: 0.0967741935483871
Delta: 0.005123771894456937 	  Loss: 1.0579507313703065 	 Accuracy: 0.0967741935483871
Delta: 0.006383515948686491 	  Loss: 1.0578713121575136 	 Accuracy: 0.0967741935483871
Delta: 0.008507491514419256 	  Loss: 1.0577678902599947 	 Accuracy: 0.0967741935483871
Delta: 0.008774310430319392 	  Loss: 1.05766795313406 	 Accuracy: 0.0967741935483871
Delta: 0.008485035974449766 	  Loss: 1.057432923715436 	 Accuracy: 0.0967741935483871
Delta: 0.00734790721953604 	  Loss: 1.0572046570871367 	 Accuracy: 0.0967741935483871
Delta: 0.006725980495396791 	  Loss: 1.0571128928555251 	 Accuracy: 0.0967741935483871
Delta: 0.004586776512487858 	  Loss: 1.0570418427821073 	 Accuracy: 0.0967741935483871
Delta: 0.0029862535327367513 	  Loss: 1.0569929007579537 	 Accuracy: 0.0967741935483871
Delta: 0.002787640422331225 	  Loss: 1.0570003139171882 	 Accuracy: 0.0967741935483871
Delta: 0.00308014744428212 	  Loss: 1.0569904398033474 	 Accuracy: 0.0967741935483871
Delta: 0.0037103292158984368 	  Loss: 1.0569786569402586 	 Accuracy: 0.0967741935483871
Delta: 0.05462444275686994 	  Loss: 1.0693582405139566 	 Accuracy: 0.3387096774193548
Delta: 0.04490628863689647 	  Loss: 1.0618433710736566 	 Accuracy: 0.22580645161290322
Delta: 0.0395977641186772 	  Loss: 1.0572651957611328 	 Accuracy: 0.20967741935483872
Delta: 0.027981626123564904 	  Loss: 1.0553788930705095 	 Accuracy: 0.1935483870967742
Delta: 0.024793243870432215 	  Loss: 1.0539981938454446 	 Accuracy: 0.1935483870967742

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.017844831677607004 	  Loss: 1.0526825780356068 	 Accuracy: 0.1935483870967742
Delta: 0.014196405768542485 	  Loss: 1.0522114307044672 	 Accuracy: 0.1935483870967742
Delta: 0.008850523277089963 	  Loss: 1.0520671639260004 	 Accuracy: 0.1935483870967742
Delta: 0.007249863587364502 	  Loss: 1.0518913792078024 	 Accuracy: 0.1935483870967742
Delta: 0.0057675670606113895 	  Loss: 1.0517353992316552 	 Accuracy: 0.1935483870967742
Delta: 0.005723765259681927 	  Loss: 1.0516291492410776 	 Accuracy: 0.1935483870967742
Delta: 0.006042076177395918 	  Loss: 1.051547717013282 	 Accuracy: 0.1935483870967742
Delta: 0.00683531500183639 	  Loss: 1.0514317111193812 	 Accuracy: 0.1935483870967742
Delta: 0.006315822536539823 	  Loss: 1.051303463398099 	 Accuracy: 0.1935483870967742
Delta: 0.00527555581837965 	  Loss: 1.0511875405654596 	 Accuracy: 0.1935483870967742
Delta: 0.006134369856821951 	  Loss: 1.0510751962922642 	 Accuracy: 0.1935483870967742
Delta: 0.004315482750490079 	  Loss: 1.0509592243910686 	 Accuracy: 0.1935483870967742
Delta: 0.003359638975354089 	  Loss: 1.0508764709087424 	 Accuracy: 0.1935483870967742
Delta: 0.002839381572208151 	  Loss: 1.0508224162102417 	 Accuracy: 0.1935483870967742
Delta: 0.002059338481407279 	  Loss: 1.0507761195447092 	 Accuracy: 0.1935483870967742
Delta: 0.002045118244934289 	  Loss: 1.0507639390510484 	 Accuracy: 0.1935483870967742
Delta: 0.0014843906758333764 	  Loss: 1.0507535903426581 	 Accuracy: 0.1935483870967742
Delta: 0.0017758657952392208 	  Loss: 1.050744867755669 	 Accuracy: 0.1935483870967742
Delta: 0.0016061952725267491 	  Loss: 1.0507240481431523 	 Accuracy: 0.1935483870967742
Delta: 0.0009051723802496181 	  Loss: 1.0507132921872864 	 Accuracy: 0.1935483870967742
Delta: 0.0007811931670479995 	  Loss: 1.0507093613362186 	 Accuracy: 0.1935483870967742
Delta: 0.0008364644892143582 	  Loss: 1.0507135969112982 	 Accuracy: 0.1935483870967742
Delta: 0.0005691820419108664 	  Loss: 1.0507182653339646 	 Accuracy: 0.1935483870967742
Delta: 0.00023609778668925147 	  Loss: 1.0507181235601801 	 Accuracy: 0.1935483870967742
Delta: 0.00011639201125968998 	  Loss: 1.05071858593421 	 Accuracy: 0.1935483870967742
Delta: 8.485682662256859e-05 	  Loss: 1.0507184970250845 	 Accuracy: 0.1935483870967742
converged at iter  30
Delta: 0.05389058884439422 	  Loss: 1.0749696519930985 	 Accuracy: 0.5161290322580645
Delta: 0.04486832775420946 	  Loss: 1.0677066838611333 	 Accuracy: 0.4838709677419355
Delta: 0.04311181067000172 	  Loss: 1.0674451213705787 	 Accuracy: 0.5
Delta: 0.02710621889060948 	  Loss: 1.0629041348713275 	 Accuracy: 0.5

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.022430202862208672 	  Loss: 1.0592138193948393 	 Accuracy: 0.5
Delta: 0.020268872102818025 	  Loss: 1.0565746713423794 	 Accuracy: 0.5
Delta: 0.02031058684717888 	  Loss: 1.0541237337350682 	 Accuracy: 0.5
Delta: 0.01602785948125659 	  Loss: 1.0522499230254745 	 Accuracy: 0.5
Delta: 0.009297705042323978 	  Loss: 1.0514233293311555 	 Accuracy: 0.5
Delta: 0.0062937406499007816 	  Loss: 1.051189544742675 	 Accuracy: 0.5
Delta: 0.0052985874277731325 	  Loss: 1.0510587647949956 	 Accuracy: 0.5
Delta: 0.004166864590048266 	  Loss: 1.05098585611076 	 Accuracy: 0.5
Delta: 0.00355451391353301 	  Loss: 1.050935109194178 	 Accuracy: 0.5
Delta: 0.0029852422604635946 	  Loss: 1.0508790889894857 	 Accuracy: 0.5
Delta: 0.0031128927149881923 	  Loss: 1.0508166337356648 	 Accuracy: 0.5
Delta: 0.003151199515679415 	  Loss: 1.0507662503804323 	 Accuracy: 0.5
Delta: 0.0024059722342596175 	  Loss: 1.050736633926744 	 Accuracy: 0.5
Delta: 0.0020132990569422604 	  Loss: 1.050736607960939 	 Accuracy: 0.5
converged at iter  17
Delta: 0.05174505096030066 	  Loss: 1.069812334926626 	 Accuracy: 0.3968253968253968
Delta: 0.04451981574624195 	  Loss: 1.0617945503329949 	 Accuracy: 0.4444444444444444
Delta: 0.03735765645142068 	  Loss: 1.057130161643288 	 Accuracy: 0.4603174603174603
Delta: 0.03142362884645451 	  Loss: 1.0522805097597776 	 Accuracy: 0.4444444444444444
Delta: 0.02502448475175871 	  Loss: 1.0490526022809248 	 Accuracy: 0.42857142857142855

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01943601466747127 	  Loss: 1.0467074430330747 	 Accuracy: 0.42857142857142855
Delta: 0.012776486433829498 	  Loss: 1.0452901233381358 	 Accuracy: 0.42857142857142855
Delta: 0.011156533411861994 	  Loss: 1.0443363390754947 	 Accuracy: 0.42857142857142855
Delta: 0.00871059834882193 	  Loss: 1.0437251430314345 	 Accuracy: 0.42857142857142855
Delta: 0.005857846827962764 	  Loss: 1.04332348343745 	 Accuracy: 0.42857142857142855
Delta: 0.0054066761692117635 	  Loss: 1.0431387972340014 	 Accuracy: 0.42857142857142855
Delta: 0.00506018662961284 	  Loss: 1.0430244411228604 	 Accuracy: 0.42857142857142855
Delta: 0.003779553001509493 	  Loss: 1.0429389968776874 	 Accuracy: 0.42857142857142855
Delta: 0.0030450107982263994 	  Loss: 1.0428415423410105 	 Accuracy: 0.42857142857142855
Delta: 0.0036982938360557672 	  Loss: 1.0427820720249532 	 Accuracy: 0.42857142857142855
Delta: 0.002735684458851138 	  Loss: 1.0427222996778194 	 Accuracy: 0.42857142857142855
Delta: 0.00221271747957207 	  Loss: 1.0426969353841127 	 Accuracy: 0.42857142857142855
Delta: 0.002314081738090752 	  Loss: 1.042692673068054 	 Accuracy: 0.42857142857142855
Delta: 0.0018581392159482523 	  Loss: 1.0427035992906266 	 Accuracy: 0.42857142857142855
Delta: 0.0021038688092039643 	  Loss: 1.0426981553817747 	 Accuracy: 0.42857142857142855
Delta: 0.0015740969574208944 	  Loss: 1.042714784644688 	 Accuracy: 0.42857142857142855
Delta: 0.0023054007105090114 	  Loss: 1.0427186796316914 	 Accuracy: 0.42857142857142855
Delta: 0.002547819769736849 	  Loss: 1.0427335393740278 	 Accuracy: 0.42857142857142855
Delta: 0.0023686182030994395 	  Loss: 1.0427154088501682 	 Accuracy: 0.42857142857142855
Delta: 0.0018260339625120912 	  Loss: 1.042718533449694 	 Accuracy: 0.42857142857142855
Delta: 0.002230598255088394 	  Loss: 1.0427274224881675 	 Accuracy: 0.42857142857142855
Delta: 0.002252909479843607 	  Loss: 1.042740260090964 	 Accuracy: 0.42857142857142855
Delta: 0.00214697097441999 	  Loss: 1.042740885504903 	 Accuracy: 0.42857142857142855
Delta: 0.001939084525430677 	  Loss: 1.0427282550307992 	 Accuracy: 0.42857142857142855
Delta: 0.002426725036590929 	  Loss: 1.0427112156387746 	 Accuracy: 0.42857142857142855
Delta: 0.0014559881336691166 	  Loss: 1.0426836845691225 	 Accuracy: 0.42857142857142855
Delta: 0.0016352250301063212 	  Loss: 1.0426774750825334 	 Accuracy: 0.42857142857142855
Delta: 0.001318087955249314 	  Loss: 1.0426597052517859 	 Accuracy: 0.42857142857142855
Delta: 0.001129328916065475 	  Loss: 1.0426537014942077 	 Accuracy: 0.42857142857142855
Delta: 0.0012773873443176409 	  Loss: 1.0426568804249583 	 Accuracy: 0.42857142857142855
Delta: 0.0019499937474955487 	  Loss: 1.0426518690987585 	 Accuracy: 0.42857142857142855
Delta: 0.001173112990270776 	  Loss: 1.042640799566445 	 Accuracy: 0.42857142857142855
Delta: 0.001331457910909437 	  Loss: 1.0426443133081462 	 Accuracy: 0.42857142857142855
Delta: 0.001580439297296651 	  Loss: 1.0426380806713658 	 Accuracy: 0.42857142857142855
Delta: 0.0016926241332324893 	  Loss: 1.0426278014157153 	 Accuracy: 0.42857142857142855
Delta: 0.0016673006856154121 	  Loss: 1.042620681006154 	 Accuracy: 0.42857142857142855
Delta: 0.0017555722659992586 	  Loss: 1.042623220683564 	 Accuracy: 0.42857142857142855
Delta: 0.0013329742343708142 	  Loss: 1.0426154619218213 	 Accuracy: 0.42857142857142855
Delta: 0.002211292744074077 	  Loss: 1.0426194462031033 	 Accuracy: 0.42857142857142855
Delta: 0.001608741543666994 	  Loss: 1.0426005606490865 	 Accuracy: 0.42857142857142855
Delta: 0.001462741244027305 	  Loss: 1.0425841585623785 	 Accuracy: 0.42857142857142855
Delta: 0.0011959267762505924 	  Loss: 1.0425839757457598 	 Accuracy: 0.42857142857142855
Delta: 0.0010793392624083471 	  Loss: 1.0425827081575352 	 Accuracy: 0.42857142857142855
Delta: 0.0013419507608413753 	  Loss: 1.0425804905500975 	 Accuracy: 0.42857142857142855
Delta: 0.0017898092945753871 	  Loss: 1.0425689398701443 	 Accuracy: 0.42857142857142855
Delta: 0.0017468898799848224 	  Loss: 1.0425609981198511 	 Accuracy: 0.42857142857142855
Delta: 0.0013708685421162795 	  Loss: 1.0425498503486723 	 Accuracy: 0.42857142857142855
Delta: 0.0012464381201059463 	  Loss: 1.0425476048647004 	 Accuracy: 0.42857142857142855
Delta: 0.0014404236785366788 	  Loss: 1.0425400417431234 	 Accuracy: 0.42857142857142855
Delta: 0.0011551327343903995 	  Loss: 1.0425260888048173 	 Accuracy: 0.42857142857142855
Delta: 0.0011077085001157025 	  Loss: 1.0425225952461485 	 Accuracy: 0.42857142857142855
Delta: 0.0014344250284882602 	  Loss: 1.0425172818099435 	 Accuracy: 0.42857142857142855
Delta: 0.0012913766753610756 	  Loss: 1.0425120416438507 	 Accuracy: 0.42857142857142855
Delta: 0.0006197946414443078 	  Loss: 1.042498702671164 	 Accuracy: 0.42857142857142855
Delta: 0.00020441387436903756 	  Loss: 1.0424949787598234 	 Accuracy: 0.42857142857142855
Delta: 0.0007030132815655034 	  Loss: 1.0424932611609639 	 Accuracy: 0.42857142857142855
Delta: 0.0007145877749212247 	  Loss: 1.0424924335760224 	 Accuracy: 0.42857142857142855
Delta: 0.0002895989756386237 	  Loss: 1.0424894073502418 	 Accuracy: 0.42857142857142855
Delta: 0.0002250111719691842 	  Loss: 1.042489066643703 	 Accuracy: 0.42857142857142855
Delta: 0.00026217240979774665 	  Loss: 1.0424877163454984 	 Accuracy: 0.42857142857142855
Delta: 0.000494760855471067 	  Loss: 1.0424856222480545 	 Accuracy: 0.42857142857142855
Delta: 0.0004615206902255277 	  Loss: 1.0424853793125237 	 Accuracy: 0.42857142857142855
Delta: 0.0004251169911248135 	  Loss: 1.042486295085023 	 Accuracy: 0.42857142857142855
Delta: 0.0015995870170399502 	  Loss: 1.0424885844952436 	 Accuracy: 0.42857142857142855
Delta: 0.0005087560915354157 	  Loss: 1.0424898151555753 	 Accuracy: 0.42857142857142855
Delta: 0.0004351678244721807 	  Loss: 1.0424865880153078 	 Accuracy: 0.42857142857142855
Delta: 0.0004966735557659312 	  Loss: 1.0424864287955549 	 Accuracy: 0.42857142857142855
Delta: 0.0002744896395323244 	  Loss: 1.042483140277564 	 Accuracy: 0.42857142857142855
Delta: 0.0007237496182283998 	  Loss: 1.04248072227777 	 Accuracy: 0.42857142857142855
Delta: 0.0014453168017868208 	  Loss: 1.0424713248485626 	 Accuracy: 0.42857142857142855
Delta: 0.001036951668555176 	  Loss: 1.042450008631866 	 Accuracy: 0.42857142857142855
Delta: 0.0010099219745693094 	  Loss: 1.042436959113163 	 Accuracy: 0.42857142857142855
Delta: 0.0011056313663783707 	  Loss: 1.0424357574232985 	 Accuracy: 0.42857142857142855
Delta: 0.001244578145598729 	  Loss: 1.0424285139603242 	 Accuracy: 0.42857142857142855
Delta: 0.0006062252030561325 	  Loss: 1.0424176161051792 	 Accuracy: 0.42857142857142855
Delta: 0.00030896831239172367 	  Loss: 1.0424119239833778 	 Accuracy: 0.42857142857142855
Delta: 2.057497577797836e-05 	  Loss: 1.0424114815894197 	 Accuracy: 0.42857142857142855
Delta: 3.582904339692945e-17 	  Loss: 1.0424114815894197 	 Accuracy: 0.42857142857142855
converged at iter  82
Delta: 0.053432990247812936 	  Loss: 1.061613210810497 	 Accuracy: 0.19047619047619047
Delta: 0.04601276605234942 	  Loss: 1.0490004167300109 	 Accuracy: 0.12698412698412698
Delta: 0.03609880442158313 	  Loss: 1.0412542371715572 	 Accuracy: 0.14285714285714285
Delta: 0.027672658458001313 	  Loss: 1.0361010578793568 	 Accuracy: 0.15873015873015872

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.021435076954027396 	  Loss: 1.033278877860912 	 Accuracy: 0.15873015873015872
Delta: 0.01541612495955803 	  Loss: 1.0317062421362233 	 Accuracy: 0.15873015873015872
Delta: 0.0144505441426618 	  Loss: 1.0306612488279892 	 Accuracy: 0.15873015873015872
Delta: 0.013161167301681445 	  Loss: 1.029694777138121 	 Accuracy: 0.15873015873015872
Delta: 0.010589587941121434 	  Loss: 1.028879040048301 	 Accuracy: 0.15873015873015872
Delta: 0.008780321624482971 	  Loss: 1.0283618301308688 	 Accuracy: 0.15873015873015872
Delta: 0.007346295477836516 	  Loss: 1.028030835920093 	 Accuracy: 0.15873015873015872
Delta: 0.006477651174192086 	  Loss: 1.027846728207276 	 Accuracy: 0.15873015873015872
Delta: 0.0056841500885580175 	  Loss: 1.0276442835610924 	 Accuracy: 0.15873015873015872
Delta: 0.005408322817330833 	  Loss: 1.0274777111166424 	 Accuracy: 0.15873015873015872
Delta: 0.004850338478513948 	  Loss: 1.027327153146006 	 Accuracy: 0.15873015873015872
Delta: 0.005463105146360454 	  Loss: 1.0272281380851793 	 Accuracy: 0.15873015873015872
Delta: 0.00635444720458788 	  Loss: 1.0271061685520484 	 Accuracy: 0.15873015873015872
Delta: 0.006225194439564052 	  Loss: 1.026913429851811 	 Accuracy: 0.15873015873015872
Delta: 0.006989372703602331 	  Loss: 1.0266992385162728 	 Accuracy: 0.15873015873015872
Delta: 0.007415136794312348 	  Loss: 1.0264580790511275 	 Accuracy: 0.15873015873015872
Delta: 0.008015736945083647 	  Loss: 1.0262383317972632 	 Accuracy: 0.15873015873015872
Delta: 0.007171763611124805 	  Loss: 1.0259304651391679 	 Accuracy: 0.15873015873015872
Delta: 0.005925063617399265 	  Loss: 1.0257907996100624 	 Accuracy: 0.15873015873015872
Delta: 0.004354700864505309 	  Loss: 1.0257633603694103 	 Accuracy: 0.15873015873015872
Delta: 0.0032399569215185065 	  Loss: 1.025730216914075 	 Accuracy: 0.15873015873015872
Delta: 0.0021448318706962844 	  Loss: 1.0257028891902884 	 Accuracy: 0.15873015873015872
Delta: 0.0017186225582469126 	  Loss: 1.0257011119685107 	 Accuracy: 0.15873015873015872
Delta: 0.0017602809780286237 	  Loss: 1.0256963322324735 	 Accuracy: 0.15873015873015872
Delta: 0.0024863884109421136 	  Loss: 1.0256835119181977 	 Accuracy: 0.15873015873015872
Delta: 0.001820736113387361 	  Loss: 1.0256958723808263 	 Accuracy: 0.15873015873015872
Delta: 0.001518569056755049 	  Loss: 1.025684652190432 	 Accuracy: 0.15873015873015872
Delta: 0.00167259062010813 	  Loss: 1.0256734703879538 	 Accuracy: 0.15873015873015872
Delta: 0.0009883542795369959 	  Loss: 1.0256629099191183 	 Accuracy: 0.15873015873015872
Delta: 0.0008528906395268062 	  Loss: 1.0256666522818412 	 Accuracy: 0.15873015873015872
Delta: 0.0007512127835508314 	  Loss: 1.0256698587104993 	 Accuracy: 0.15873015873015872
Delta: 0.0008314584856379103 	  Loss: 1.0256722709275305 	 Accuracy: 0.15873015873015872
Delta: 0.0011774083994316035 	  Loss: 1.0256726790583532 	 Accuracy: 0.15873015873015872
Delta: 0.001240228597697055 	  Loss: 1.0256742168973438 	 Accuracy: 0.15873015873015872
Delta: 0.0005828308215230804 	  Loss: 1.0256701283280054 	 Accuracy: 0.15873015873015872
Delta: 0.0012155299012416693 	  Loss: 1.0256693016641618 	 Accuracy: 0.15873015873015872
Delta: 0.0012800752869257979 	  Loss: 1.0256665668916176 	 Accuracy: 0.15873015873015872
Delta: 0.00222778893535445 	  Loss: 1.0256610977153342 	 Accuracy: 0.15873015873015872
Delta: 0.002408832181991877 	  Loss: 1.0256682126876795 	 Accuracy: 0.15873015873015872
Delta: 0.0013466614017686518 	  Loss: 1.0256756865759042 	 Accuracy: 0.15873015873015872
Delta: 0.0009597676668002445 	  Loss: 1.025671038876662 	 Accuracy: 0.15873015873015872
Delta: 0.0005074571177407963 	  Loss: 1.0256666004073622 	 Accuracy: 0.15873015873015872
Delta: 0.00027712825612910764 	  Loss: 1.0256652567782305 	 Accuracy: 0.15873015873015872
Delta: 0.0004267421812961008 	  Loss: 1.0256649731810423 	 Accuracy: 0.15873015873015872
Delta: 0.0003859779408780827 	  Loss: 1.0256667889680804 	 Accuracy: 0.15873015873015872
Delta: 0.0004304952323630433 	  Loss: 1.0256690427632376 	 Accuracy: 0.15873015873015872
Delta: 0.000613233354980665 	  Loss: 1.0256712238184815 	 Accuracy: 0.15873015873015872
Delta: 0.0007142562403041713 	  Loss: 1.0256720011115252 	 Accuracy: 0.15873015873015872
Delta: 0.00035216273281159807 	  Loss: 1.0256710338941684 	 Accuracy: 0.15873015873015872
Delta: 0.0007360669548589837 	  Loss: 1.025668964405062 	 Accuracy: 0.15873015873015872
Delta: 0.0006992901625081538 	  Loss: 1.0256644201612104 	 Accuracy: 0.15873015873015872
Delta: 0.0006517110896684795 	  Loss: 1.0256664613890052 	 Accuracy: 0.15873015873015872
Delta: 0.00040272385231042955 	  Loss: 1.0256693197584679 	 Accuracy: 0.15873015873015872
Delta: 0.000494235787427984 	  Loss: 1.0256703814734363 	 Accuracy: 0.15873015873015872
Delta: 0.00016073665551407613 	  Loss: 1.02567210703195 	 Accuracy: 0.15873015873015872
Delta: 0.00013293065868376144 	  Loss: 1.0256722300900023 	 Accuracy: 0.15873015873015872
Delta: 0.00016758716058368683 	  Loss: 1.0256725441346393 	 Accuracy: 0.15873015873015872
Delta: 3.201986114507353e-05 	  Loss: 1.0256725462848393 	 Accuracy: 0.15873015873015872
converged at iter  61
Delta: 0.0583754085161989 	  Loss: 1.0726393115845116 	 Accuracy: 0.5
Delta: 0.03841070640120401 	  Loss: 1.0608848747986053 	 Accuracy: 0.45161290322580644
Delta: 0.03330123107196485 	  Loss: 1.056820626153185 	 Accuracy: 0.46774193548387094
Delta: 0.033131787150519745 	  Loss: 1.0582061645965053 	 Accuracy: 0.46774193548387094

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.024947374408166877 	  Loss: 1.0563111320710847 	 Accuracy: 0.46774193548387094
Delta: 0.015902209455909273 	  Loss: 1.0542729701092743 	 Accuracy: 0.46774193548387094
Delta: 0.013821197426982968 	  Loss: 1.0532756732938189 	 Accuracy: 0.46774193548387094
Delta: 0.011174033251743145 	  Loss: 1.0525716843342274 	 Accuracy: 0.46774193548387094
Delta: 0.008707510441456873 	  Loss: 1.0522018607674313 	 Accuracy: 0.46774193548387094
Delta: 0.0068104752220747265 	  Loss: 1.051995834527417 	 Accuracy: 0.46774193548387094
Delta: 0.005515534026398843 	  Loss: 1.0518410594756307 	 Accuracy: 0.46774193548387094
Delta: 0.003962056510660017 	  Loss: 1.0517376994177066 	 Accuracy: 0.46774193548387094
Delta: 0.00364458814547096 	  Loss: 1.0516784752329744 	 Accuracy: 0.46774193548387094
Delta: 0.003908499114649439 	  Loss: 1.0516065392609624 	 Accuracy: 0.46774193548387094
Delta: 0.004711459035489275 	  Loss: 1.051526029579433 	 Accuracy: 0.46774193548387094
Delta: 0.004916486627518083 	  Loss: 1.0514955282961898 	 Accuracy: 0.46774193548387094
Delta: 0.004374859783332684 	  Loss: 1.0514368694834761 	 Accuracy: 0.46774193548387094
Delta: 0.003214782902375783 	  Loss: 1.0513584870799686 	 Accuracy: 0.46774193548387094
Delta: 0.0030258325138132203 	  Loss: 1.051335053970416 	 Accuracy: 0.46774193548387094
Delta: 0.0023814592328897733 	  Loss: 1.0513142455271027 	 Accuracy: 0.46774193548387094
Delta: 0.0016942186975167192 	  Loss: 1.051298797285332 	 Accuracy: 0.46774193548387094
Delta: 0.0020702156157177804 	  Loss: 1.0512870315293321 	 Accuracy: 0.46774193548387094
Delta: 0.0015253661342388512 	  Loss: 1.0512520960179446 	 Accuracy: 0.46774193548387094
Delta: 0.001852094111416229 	  Loss: 1.0512415790863778 	 Accuracy: 0.46774193548387094
Delta: 0.002014330954580525 	  Loss: 1.051233276438949 	 Accuracy: 0.46774193548387094
Delta: 0.0013771632449126724 	  Loss: 1.0511911636865094 	 Accuracy: 0.46774193548387094
Delta: 0.0018445443884103456 	  Loss: 1.0511771054402081 	 Accuracy: 0.46774193548387094
Delta: 0.0029279060688305945 	  Loss: 1.0511629835355647 	 Accuracy: 0.46774193548387094
Delta: 0.0023930231449611514 	  Loss: 1.0511399896903422 	 Accuracy: 0.46774193548387094
Delta: 0.0020996774773622668 	  Loss: 1.0511285081039379 	 Accuracy: 0.46774193548387094
Delta: 0.0017977462390525757 	  Loss: 1.051117670393158 	 Accuracy: 0.46774193548387094
Delta: 0.002085117666315828 	  Loss: 1.0511153286080461 	 Accuracy: 0.46774193548387094
Delta: 0.0021707684789180294 	  Loss: 1.0511086916505492 	 Accuracy: 0.46774193548387094
Delta: 0.001565283463760643 	  Loss: 1.0510979383040708 	 Accuracy: 0.46774193548387094
Delta: 0.001627069250457739 	  Loss: 1.051096379982522 	 Accuracy: 0.46774193548387094
Delta: 0.001369430346740023 	  Loss: 1.0510966821351562 	 Accuracy: 0.46774193548387094
Delta: 0.002369362281573322 	  Loss: 1.0510861920467565 	 Accuracy: 0.46774193548387094
Delta: 0.0012354131107736872 	  Loss: 1.0510725726417234 	 Accuracy: 0.46774193548387094
Delta: 0.0006031742976927403 	  Loss: 1.051074724503282 	 Accuracy: 0.46774193548387094
Delta: 0.000753233253864399 	  Loss: 1.0510784130953825 	 Accuracy: 0.46774193548387094
Delta: 0.0006885671773018689 	  Loss: 1.0510763337144549 	 Accuracy: 0.46774193548387094
Delta: 0.0007130513339918364 	  Loss: 1.0510763552484694 	 Accuracy: 0.46774193548387094
converged at iter  41
Delta: 0.0573584012917711 	  Loss: 1.0595238224638037 	 Accuracy: 0.6129032258064516
Delta: 0.044820287474188175 	  Loss: 1.0538026230176358 	 Accuracy: 0.6290322580645161
Delta: 0.03573245811669302 	  Loss: 1.048501838455345 	 Accuracy: 0.6612903225806451
Delta: 0.025347266218074666 	  Loss: 1.044929219669317 	 Accuracy: 0.6451612903225806

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.021134584919364624 	  Loss: 1.0429963977055845 	 Accuracy: 0.6612903225806451
Delta: 0.01906609263884917 	  Loss: 1.0409641231060014 	 Accuracy: 0.6612903225806451
Delta: 0.015763493602596598 	  Loss: 1.0393368113097146 	 Accuracy: 0.6612903225806451
Delta: 0.01128243262070709 	  Loss: 1.0384625331193909 	 Accuracy: 0.6612903225806451
Delta: 0.009463853146515938 	  Loss: 1.038065906603706 	 Accuracy: 0.6612903225806451
Delta: 0.008296580818620152 	  Loss: 1.0378152130318692 	 Accuracy: 0.6612903225806451
Delta: 0.007442998940195762 	  Loss: 1.0376121824059812 	 Accuracy: 0.6612903225806451
Delta: 0.0054826079348765855 	  Loss: 1.0374754275408615 	 Accuracy: 0.6612903225806451
Delta: 0.005013751046979268 	  Loss: 1.0374056812683956 	 Accuracy: 0.6612903225806451
Delta: 0.004997697242901017 	  Loss: 1.0373359131728945 	 Accuracy: 0.6612903225806451
Delta: 0.004787818401491624 	  Loss: 1.0372606350572637 	 Accuracy: 0.6612903225806451
Delta: 0.004744890098669944 	  Loss: 1.0372206967248507 	 Accuracy: 0.6612903225806451
Delta: 0.004285405999137295 	  Loss: 1.0371788793228645 	 Accuracy: 0.6612903225806451
Delta: 0.003249882115049621 	  Loss: 1.0371167935055463 	 Accuracy: 0.6612903225806451
Delta: 0.004105797167056355 	  Loss: 1.0370874072299396 	 Accuracy: 0.6612903225806451
Delta: 0.0049038247006482315 	  Loss: 1.0370466963764058 	 Accuracy: 0.6612903225806451
Delta: 0.004557733991021617 	  Loss: 1.036981227735704 	 Accuracy: 0.6612903225806451
Delta: 0.004164358453694478 	  Loss: 1.0369186000411366 	 Accuracy: 0.6612903225806451
Delta: 0.004071926479656694 	  Loss: 1.0368588709052087 	 Accuracy: 0.6612903225806451
Delta: 0.004250564374044486 	  Loss: 1.0368051154820472 	 Accuracy: 0.6612903225806451
Delta: 0.0037211430006617446 	  Loss: 1.036743308623684 	 Accuracy: 0.6612903225806451
Delta: 0.0033183930414987686 	  Loss: 1.0367170424095418 	 Accuracy: 0.6612903225806451
Delta: 0.0028375888914057724 	  Loss: 1.0366976352897237 	 Accuracy: 0.6612903225806451
Delta: 0.0025365835164060783 	  Loss: 1.0366835858169257 	 Accuracy: 0.6612903225806451
Delta: 0.001689114885298707 	  Loss: 1.0366542829515442 	 Accuracy: 0.6612903225806451
Delta: 0.002152262281900934 	  Loss: 1.0366418283018457 	 Accuracy: 0.6612903225806451
Delta: 0.0020116584399894727 	  Loss: 1.036631765875625 	 Accuracy: 0.6612903225806451
Delta: 0.0016404000221186476 	  Loss: 1.0366180589775842 	 Accuracy: 0.6612903225806451
Delta: 0.0013344161687497713 	  Loss: 1.0366032930381595 	 Accuracy: 0.6612903225806451
Delta: 0.0010102679187444087 	  Loss: 1.0366039508771654 	 Accuracy: 0.6612903225806451
Delta: 0.0008159015943767183 	  Loss: 1.0366049244562696 	 Accuracy: 0.6612903225806451
Delta: 0.00113570449361284 	  Loss: 1.0366027779803357 	 Accuracy: 0.6612903225806451
Delta: 0.001135173381784847 	  Loss: 1.03659523404044 	 Accuracy: 0.6612903225806451
Delta: 0.0007423061171662353 	  Loss: 1.0365880255365296 	 Accuracy: 0.6612903225806451
Delta: 0.0008108174768506721 	  Loss: 1.0365849987220357 	 Accuracy: 0.6612903225806451
Delta: 0.0008747877875421271 	  Loss: 1.036581443280617 	 Accuracy: 0.6612903225806451
Delta: 0.0009556389345240696 	  Loss: 1.0365778639136893 	 Accuracy: 0.6612903225806451
Delta: 0.0004123546487629939 	  Loss: 1.0365672096655638 	 Accuracy: 0.6612903225806451
Delta: 0.00030478099161099345 	  Loss: 1.0365647554364146 	 Accuracy: 0.6612903225806451
Delta: 0.0002951790776729813 	  Loss: 1.036559931485148 	 Accuracy: 0.6612903225806451
Delta: 9.975455483458306e-05 	  Loss: 1.0365588855107553 	 Accuracy: 0.6612903225806451
Delta: 6.73173951218507e-06 	  Loss: 1.0365583040171797 	 Accuracy: 0.6612903225806451
Delta: 3.351504667475496e-17 	  Loss: 1.0365583040171797 	 Accuracy: 0.6612903225806451
converged at iter  46
Delta: 0.05721525886617713 	  Loss: 1.0937616873903333 	 Accuracy: 0.2903225806451613
Delta: 0.047294591485070384 	  Loss: 1.0862011073446294 	 Accuracy: 0.04838709677419355
Delta: 0.03774899905399228 	  Loss: 1.0803447046952002 	 Accuracy: 0.06451612903225806
Delta: 0.02770556720741187 	  Loss: 1.0750701780644283 	 Accuracy: 0.06451612903225806

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02185490010361003 	  Loss: 1.071768047825383 	 Accuracy: 0.08064516129032258
Delta: 0.016339964027343022 	  Loss: 1.070118697844621 	 Accuracy: 0.08064516129032258
Delta: 0.011265556662555664 	  Loss: 1.069342694577351 	 Accuracy: 0.08064516129032258
Delta: 0.007807048778592546 	  Loss: 1.0689850091353805 	 Accuracy: 0.08064516129032258
Delta: 0.006807236805427032 	  Loss: 1.0688457103384095 	 Accuracy: 0.08064516129032258
Delta: 0.005774467920909787 	  Loss: 1.0688133431618336 	 Accuracy: 0.08064516129032258
Delta: 0.004881933551630249 	  Loss: 1.068709036041021 	 Accuracy: 0.08064516129032258
Delta: 0.005088616312434488 	  Loss: 1.0686741924720509 	 Accuracy: 0.08064516129032258
Delta: 0.004286299476289057 	  Loss: 1.0686567432987717 	 Accuracy: 0.08064516129032258
Delta: 0.004538400744553308 	  Loss: 1.068624224684078 	 Accuracy: 0.08064516129032258
Delta: 0.00414060788460275 	  Loss: 1.0685965819462164 	 Accuracy: 0.08064516129032258
Delta: 0.004321105782962873 	  Loss: 1.0685253568297644 	 Accuracy: 0.08064516129032258
Delta: 0.004298737243549473 	  Loss: 1.0684442654421857 	 Accuracy: 0.08064516129032258
Delta: 0.004279678321669071 	  Loss: 1.0683790674554068 	 Accuracy: 0.08064516129032258
Delta: 0.00423277914579896 	  Loss: 1.068343341581005 	 Accuracy: 0.08064516129032258
Delta: 0.0037638175312271374 	  Loss: 1.0683148649534824 	 Accuracy: 0.08064516129032258
Delta: 0.0036281165331307798 	  Loss: 1.0682604422754032 	 Accuracy: 0.08064516129032258
Delta: 0.003312981578590369 	  Loss: 1.068225006119931 	 Accuracy: 0.08064516129032258
Delta: 0.0029666459055613507 	  Loss: 1.068187619270426 	 Accuracy: 0.08064516129032258
Delta: 0.0024236256452771555 	  Loss: 1.0681551191103575 	 Accuracy: 0.08064516129032258
Delta: 0.0029926406896646175 	  Loss: 1.0681385584838399 	 Accuracy: 0.08064516129032258
Delta: 0.0026190619577808215 	  Loss: 1.0681166331856868 	 Accuracy: 0.08064516129032258
Delta: 0.002237570958507896 	  Loss: 1.0681224227791257 	 Accuracy: 0.08064516129032258
Delta: 0.001375376472933383 	  Loss: 1.0681182730969374 	 Accuracy: 0.08064516129032258
Delta: 0.0015911159540944269 	  Loss: 1.0681185022868536 	 Accuracy: 0.08064516129032258
Delta: 0.0012144739524430441 	  Loss: 1.0681282684983304 	 Accuracy: 0.08064516129032258
Delta: 0.0010202102092791482 	  Loss: 1.0681313007531261 	 Accuracy: 0.08064516129032258
Delta: 0.0019935032398497293 	  Loss: 1.0681297832408299 	 Accuracy: 0.08064516129032258
Delta: 0.0014776317592733422 	  Loss: 1.0681246558821036 	 Accuracy: 0.08064516129032258
Delta: 0.0008622950779838856 	  Loss: 1.0681189513397296 	 Accuracy: 0.08064516129032258
Delta: 0.0006745024744297206 	  Loss: 1.0681164418699562 	 Accuracy: 0.08064516129032258
Delta: 0.00027459010371364424 	  Loss: 1.0681138081407808 	 Accuracy: 0.08064516129032258
Delta: 0.0003039396885898359 	  Loss: 1.0681120729744105 	 Accuracy: 0.08064516129032258
Delta: 0.0004607405843311289 	  Loss: 1.0681128090953393 	 Accuracy: 0.08064516129032258
Delta: 0.0003632510375380678 	  Loss: 1.068108127280516 	 Accuracy: 0.08064516129032258
Delta: 8.982866135540022e-05 	  Loss: 1.0681029776302529 	 Accuracy: 0.08064516129032258
Delta: 9.709257880189518e-05 	  Loss: 1.0681028552324212 	 Accuracy: 0.08064516129032258
Delta: 8.560565864124116e-05 	  Loss: 1.0681033874374677 	 Accuracy: 0.08064516129032258
Delta: 5.146378408428711e-05 	  Loss: 1.0681036239016333 	 Accuracy: 0.08064516129032258
Delta: 0.00016659603778993516 	  Loss: 1.0681037963773976 	 Accuracy: 0.08064516129032258
Delta: 0.00013297049823833408 	  Loss: 1.068104962822693 	 Accuracy: 0.08064516129032258
Delta: 0.00019139684884074006 	  Loss: 1.068105927059833 	 Accuracy: 0.08064516129032258
Delta: 0.0001685239411824559 	  Loss: 1.0681052277897303 	 Accuracy: 0.08064516129032258
Delta: 1.3422514671519813e-05 	  Loss: 1.0681055654093021 	 Accuracy: 0.08064516129032258
Delta: 3.542059481748781e-17 	  Loss: 1.0681055654093021 	 Accuracy: 0.08064516129032258
converged at iter  48
Delta: 0.057115037061802175 	  Loss: 1.0692740083904007 	 Accuracy: 0.6666666666666666
Delta: 0.04620675401975545 	  Loss: 1.0671780084907347 	 Accuracy: 0.7301587301587301
Delta: 0.03612264407658085 	  Loss: 1.0649624495814036 	 Accuracy: 0.7777777777777778

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.027226780309972214 	  Loss: 1.06084264824031 	 Accuracy: 0.746031746031746
Delta: 0.019118502548535872 	  Loss: 1.0579512424399717 	 Accuracy: 0.746031746031746
Delta: 0.014595730145940667 	  Loss: 1.0565157411665957 	 Accuracy: 0.746031746031746
Delta: 0.012433598657004255 	  Loss: 1.0557181025827318 	 Accuracy: 0.746031746031746
Delta: 0.011454073250200368 	  Loss: 1.0549668530953673 	 Accuracy: 0.746031746031746
Delta: 0.008809189877262069 	  Loss: 1.0544498378872378 	 Accuracy: 0.746031746031746
Delta: 0.008693320329058934 	  Loss: 1.0541507267316172 	 Accuracy: 0.746031746031746
Delta: 0.007027531068141905 	  Loss: 1.0539015621136416 	 Accuracy: 0.746031746031746
Delta: 0.006482919151641602 	  Loss: 1.0537554415075179 	 Accuracy: 0.746031746031746
Delta: 0.006620254654486933 	  Loss: 1.053576783105156 	 Accuracy: 0.746031746031746
Delta: 0.0065703516518276495 	  Loss: 1.0534152047587049 	 Accuracy: 0.746031746031746
Delta: 0.006435789510256951 	  Loss: 1.053269156969058 	 Accuracy: 0.746031746031746
Delta: 0.0058736857193622 	  Loss: 1.0530187756049139 	 Accuracy: 0.746031746031746
Delta: 0.004885351394833481 	  Loss: 1.0528483496309196 	 Accuracy: 0.746031746031746
Delta: 0.004487607129195258 	  Loss: 1.0527652899700188 	 Accuracy: 0.746031746031746
Delta: 0.004489910576639779 	  Loss: 1.0526709630625584 	 Accuracy: 0.746031746031746
Delta: 0.003502803499341548 	  Loss: 1.0526042455513205 	 Accuracy: 0.746031746031746
Delta: 0.0032490737011562883 	  Loss: 1.052528807188082 	 Accuracy: 0.746031746031746
Delta: 0.003189433230985037 	  Loss: 1.0524874054478046 	 Accuracy: 0.746031746031746
Delta: 0.0025530551931268663 	  Loss: 1.0524395492742957 	 Accuracy: 0.746031746031746
Delta: 0.0027549120827966836 	  Loss: 1.0524291144442235 	 Accuracy: 0.746031746031746
Delta: 0.0017158322157721127 	  Loss: 1.0524014952909266 	 Accuracy: 0.746031746031746
Delta: 0.00214211275030954 	  Loss: 1.0523911038709792 	 Accuracy: 0.746031746031746
Delta: 0.0025152992319594013 	  Loss: 1.0523797310873597 	 Accuracy: 0.746031746031746
Delta: 0.0026236000948767317 	  Loss: 1.052366691532607 	 Accuracy: 0.746031746031746
Delta: 0.003081676703753557 	  Loss: 1.0523364702899123 	 Accuracy: 0.746031746031746
Delta: 0.0029240255556282403 	  Loss: 1.0523052973588571 	 Accuracy: 0.746031746031746
Delta: 0.0028115769402532703 	  Loss: 1.0523034470453407 	 Accuracy: 0.746031746031746
Delta: 0.002539930538633973 	  Loss: 1.0522931336256807 	 Accuracy: 0.746031746031746
Delta: 0.0025401193901595084 	  Loss: 1.0522718900398471 	 Accuracy: 0.746031746031746
Delta: 0.002295274006684906 	  Loss: 1.0522524769100126 	 Accuracy: 0.746031746031746
Delta: 0.0025154514254193128 	  Loss: 1.0522359162068615 	 Accuracy: 0.746031746031746
Delta: 0.0024534354269901185 	  Loss: 1.0522097614625547 	 Accuracy: 0.746031746031746
Delta: 0.0017870372015786492 	  Loss: 1.052196575592383 	 Accuracy: 0.746031746031746
Delta: 0.001982136149969195 	  Loss: 1.0521959783198285 	 Accuracy: 0.746031746031746
Delta: 0.0023748770031051343 	  Loss: 1.052185422325276 	 Accuracy: 0.746031746031746
Delta: 0.002108215396657731 	  Loss: 1.0521773905983767 	 Accuracy: 0.746031746031746
Delta: 0.002108454614632713 	  Loss: 1.0521631681352481 	 Accuracy: 0.746031746031746
Delta: 0.0021539854976977955 	  Loss: 1.0521619035010779 	 Accuracy: 0.746031746031746
Delta: 0.003213313752445899 	  Loss: 1.0521539389473418 	 Accuracy: 0.746031746031746
Delta: 0.002624858433299211 	  Loss: 1.052131950801242 	 Accuracy: 0.746031746031746
Delta: 0.003929440840679301 	  Loss: 1.0521246175654033 	 Accuracy: 0.746031746031746
Delta: 0.003415883033865422 	  Loss: 1.0520762105861277 	 Accuracy: 0.746031746031746
Delta: 0.0031013694269469453 	  Loss: 1.0520479075512492 	 Accuracy: 0.746031746031746
Delta: 0.0024790721637505822 	  Loss: 1.0520506447491 	 Accuracy: 0.746031746031746
Delta: 0.003455901305664892 	  Loss: 1.0520220558745375 	 Accuracy: 0.746031746031746
Delta: 0.0021317733862600647 	  Loss: 1.0519951943447703 	 Accuracy: 0.746031746031746
Delta: 0.002642871811470607 	  Loss: 1.0519800935637513 	 Accuracy: 0.746031746031746
Delta: 0.002493966630872014 	  Loss: 1.0519661105509588 	 Accuracy: 0.746031746031746
Delta: 0.0030864174485382523 	  Loss: 1.0519466340293926 	 Accuracy: 0.746031746031746
Delta: 0.0023187479494022212 	  Loss: 1.0519463985848718 	 Accuracy: 0.746031746031746
Delta: 0.002268565045337749 	  Loss: 1.0519457690294003 	 Accuracy: 0.746031746031746
Delta: 0.00240263131164884 	  Loss: 1.0519553849483905 	 Accuracy: 0.746031746031746
Delta: 0.0018126720808662338 	  Loss: 1.0519502754217285 	 Accuracy: 0.746031746031746
Delta: 0.0018845307920121864 	  Loss: 1.0519480038344333 	 Accuracy: 0.746031746031746
Delta: 0.0015124189459437937 	  Loss: 1.0519304857694203 	 Accuracy: 0.746031746031746
Delta: 0.0018657381771658836 	  Loss: 1.0519144127251128 	 Accuracy: 0.746031746031746
Delta: 0.002177519918894565 	  Loss: 1.0519293439863207 	 Accuracy: 0.746031746031746
Delta: 0.0023599661533623977 	  Loss: 1.0519219171457337 	 Accuracy: 0.746031746031746
Delta: 0.0021960524869921116 	  Loss: 1.0519273780326945 	 Accuracy: 0.746031746031746
Delta: 0.0015953280404515267 	  Loss: 1.0519184297765771 	 Accuracy: 0.746031746031746
Delta: 0.0014179015598514747 	  Loss: 1.0519253725565807 	 Accuracy: 0.746031746031746
Delta: 0.0020531223760616875 	  Loss: 1.0519291375076834 	 Accuracy: 0.746031746031746
Delta: 0.0013093884574941564 	  Loss: 1.0519153381023996 	 Accuracy: 0.746031746031746
Delta: 0.0007441499788536782 	  Loss: 1.051918389244304 	 Accuracy: 0.746031746031746
Delta: 0.0003363994288513848 	  Loss: 1.0519234716785861 	 Accuracy: 0.746031746031746
Delta: 0.0002670971340130691 	  Loss: 1.0519254600730563 	 Accuracy: 0.746031746031746
Delta: 0.000589725768949479 	  Loss: 1.0519277843866477 	 Accuracy: 0.746031746031746
Delta: 0.0005082200812512835 	  Loss: 1.05192896568128 	 Accuracy: 0.746031746031746
Delta: 0.0012322930876452337 	  Loss: 1.051929586525708 	 Accuracy: 0.746031746031746
Delta: 0.0023299798689770264 	  Loss: 1.0519274478745415 	 Accuracy: 0.746031746031746
Delta: 0.0008694633577119295 	  Loss: 1.0519152188615766 	 Accuracy: 0.746031746031746
Delta: 0.000867492021575414 	  Loss: 1.051916703315489 	 Accuracy: 0.746031746031746
Delta: 0.0018568681920585707 	  Loss: 1.051918634587665 	 Accuracy: 0.746031746031746
Delta: 0.0010705445449204444 	  Loss: 1.0519333101126551 	 Accuracy: 0.746031746031746
Delta: 0.0008386859156543551 	  Loss: 1.0519264993397486 	 Accuracy: 0.746031746031746
Delta: 0.0006148213706098083 	  Loss: 1.051921073819487 	 Accuracy: 0.746031746031746
Delta: 0.0006750216313748364 	  Loss: 1.0519148553378201 	 Accuracy: 0.746031746031746
Delta: 0.00040445105743243913 	  Loss: 1.0519106607768982 	 Accuracy: 0.746031746031746
Delta: 0.0005133651306327673 	  Loss: 1.0519065631746072 	 Accuracy: 0.746031746031746
Delta: 0.0004900638550748598 	  Loss: 1.0519064510009375 	 Accuracy: 0.746031746031746
Delta: 0.0002854349949911218 	  Loss: 1.0519092304730715 	 Accuracy: 0.746031746031746
Delta: 0.00037381763179950846 	  Loss: 1.051909446861293 	 Accuracy: 0.746031746031746
Delta: 0.00043647635862024113 	  Loss: 1.0519110840279224 	 Accuracy: 0.746031746031746
Delta: 0.0007978650141716216 	  Loss: 1.0519119027672041 	 Accuracy: 0.746031746031746
Delta: 0.0003537976189582636 	  Loss: 1.051916025598812 	 Accuracy: 0.746031746031746
Delta: 0.0005512014822974473 	  Loss: 1.051918755032042 	 Accuracy: 0.746031746031746
Delta: 0.0002617252983079748 	  Loss: 1.051922512741531 	 Accuracy: 0.746031746031746
Delta: 6.197056494640414e-05 	  Loss: 1.0519219914486795 	 Accuracy: 0.746031746031746
Delta: 4.2457094624209005e-06 	  Loss: 1.0519222675891307 	 Accuracy: 0.746031746031746
Delta: 2.892219066943819e-17 	  Loss: 1.0519222675891307 	 Accuracy: 0.746031746031746
converged at iter  93
Delta: 0.055659495289901204 	  Loss: 1.0665813619679825 	 Accuracy: 0.38095238095238093
Delta: 0.04773763403190982 	  Loss: 1.0606616143986467 	 Accuracy: 0.2222222222222222
Delta: 0.0315507686757458 	  Loss: 1.0543798692273167 	 Accuracy: 0.23809523809523808

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.022035174738998353 	  Loss: 1.0507284454928651 	 Accuracy: 0.23809523809523808
Delta: 0.017276500329299095 	  Loss: 1.048502567860055 	 Accuracy: 0.23809523809523808
Delta: 0.01420542907453104 	  Loss: 1.0470132426259706 	 Accuracy: 0.23809523809523808
Delta: 0.011352539408555722 	  Loss: 1.0461804164664414 	 Accuracy: 0.23809523809523808
Delta: 0.010014268914098673 	  Loss: 1.0456704343408365 	 Accuracy: 0.23809523809523808
Delta: 0.009535484734614404 	  Loss: 1.0452772389168579 	 Accuracy: 0.23809523809523808
Delta: 0.009812636878415208 	  Loss: 1.0448486243887656 	 Accuracy: 0.23809523809523808
Delta: 0.012492675084381942 	  Loss: 1.0442375582056869 	 Accuracy: 0.23809523809523808
Delta: 0.012217864053124918 	  Loss: 1.0434237109108224 	 Accuracy: 0.23809523809523808
Delta: 0.010302756524276584 	  Loss: 1.0427779042434642 	 Accuracy: 0.23809523809523808
Delta: 0.008822135593414463 	  Loss: 1.042339735457301 	 Accuracy: 0.23809523809523808
Delta: 0.007565781812297426 	  Loss: 1.0420300718181394 	 Accuracy: 0.23809523809523808
Delta: 0.005431544474621184 	  Loss: 1.0418085376906105 	 Accuracy: 0.23809523809523808
Delta: 0.00370932579599553 	  Loss: 1.0416774231704444 	 Accuracy: 0.23809523809523808
Delta: 0.003695619900275018 	  Loss: 1.0416265038078447 	 Accuracy: 0.23809523809523808
Delta: 0.00412243023128273 	  Loss: 1.041579029122444 	 Accuracy: 0.23809523809523808
Delta: 0.003872291527774773 	  Loss: 1.0415054396205132 	 Accuracy: 0.23809523809523808
Delta: 0.004361633046961858 	  Loss: 1.0414358260004801 	 Accuracy: 0.23809523809523808
Delta: 0.004081044750461075 	  Loss: 1.041361254264467 	 Accuracy: 0.23809523809523808
Delta: 0.0023864432299184686 	  Loss: 1.0413259809626774 	 Accuracy: 0.23809523809523808
Delta: 0.0022425326200707996 	  Loss: 1.0412952829009523 	 Accuracy: 0.23809523809523808
Delta: 0.0016549798717937104 	  Loss: 1.0412675096614241 	 Accuracy: 0.23809523809523808
Delta: 0.0016082868569289943 	  Loss: 1.0412503982407926 	 Accuracy: 0.23809523809523808
Delta: 0.0024059126184309792 	  Loss: 1.0412305669539952 	 Accuracy: 0.23809523809523808
Delta: 0.002376496288721699 	  Loss: 1.0412147242856427 	 Accuracy: 0.23809523809523808
Delta: 0.0026877654277950775 	  Loss: 1.0411925833515259 	 Accuracy: 0.23809523809523808
Delta: 0.0031599958025212873 	  Loss: 1.0411666801307122 	 Accuracy: 0.23809523809523808
Delta: 0.0027850752620321123 	  Loss: 1.041123655557933 	 Accuracy: 0.23809523809523808
Delta: 0.0024179961852501567 	  Loss: 1.0411191321803712 	 Accuracy: 0.23809523809523808
Delta: 0.0030134809074591623 	  Loss: 1.04111185970668 	 Accuracy: 0.23809523809523808
Delta: 0.002616247937430742 	  Loss: 1.0411056322750936 	 Accuracy: 0.23809523809523808
Delta: 0.0023405420526944067 	  Loss: 1.0411011700853312 	 Accuracy: 0.23809523809523808
Delta: 0.002014749176181511 	  Loss: 1.0410969562997714 	 Accuracy: 0.23809523809523808
Delta: 0.0018537445448278103 	  Loss: 1.0410798974136792 	 Accuracy: 0.23809523809523808
Delta: 0.0014407675111068777 	  Loss: 1.0410749963267845 	 Accuracy: 0.23809523809523808
Delta: 0.0012366239853798392 	  Loss: 1.0410654353990563 	 Accuracy: 0.23809523809523808
Delta: 0.0009745796681251326 	  Loss: 1.0410672032539399 	 Accuracy: 0.23809523809523808
Delta: 0.0009443406619458613 	  Loss: 1.0410611646215693 	 Accuracy: 0.23809523809523808
Delta: 0.0005050054508729441 	  Loss: 1.0410587773763402 	 Accuracy: 0.23809523809523808
Delta: 0.0006060769870365505 	  Loss: 1.0410579426840085 	 Accuracy: 0.23809523809523808
Delta: 0.000519664666847664 	  Loss: 1.041060397185463 	 Accuracy: 0.23809523809523808
Delta: 0.00042988957918852297 	  Loss: 1.0410614016210769 	 Accuracy: 0.23809523809523808
Delta: 0.00033614278429858576 	  Loss: 1.0410621581361594 	 Accuracy: 0.23809523809523808
Delta: 0.0002651687925334811 	  Loss: 1.0410627588328492 	 Accuracy: 0.23809523809523808
Delta: 0.0004793557711060148 	  Loss: 1.0410637750526424 	 Accuracy: 0.23809523809523808
Delta: 0.0007050497042875538 	  Loss: 1.0410652054844929 	 Accuracy: 0.23809523809523808
Delta: 0.0009900769057492815 	  Loss: 1.0410632439346719 	 Accuracy: 0.23809523809523808
Delta: 0.0004160390512769726 	  Loss: 1.041061340108433 	 Accuracy: 0.23809523809523808
Delta: 9.230744414184728e-05 	  Loss: 1.0410611046419485 	 Accuracy: 0.23809523809523808
Delta: 0.0001722760616863765 	  Loss: 1.0410608672574 	 Accuracy: 0.23809523809523808
Delta: 8.636389043056504e-05 	  Loss: 1.0410602570022278 	 Accuracy: 0.23809523809523808
Delta: 0.00029199854669704654 	  Loss: 1.0410599863096248 	 Accuracy: 0.23809523809523808
Delta: 0.000314581989614939 	  Loss: 1.0410590872164227 	 Accuracy: 0.23809523809523808
Delta: 0.0003693689792318398 	  Loss: 1.0410573682679631 	 Accuracy: 0.23809523809523808
Delta: 0.0002422089809284507 	  Loss: 1.041055543582908 	 Accuracy: 0.23809523809523808
Delta: 0.00017932814369154933 	  Loss: 1.0410526460707485 	 Accuracy: 0.23809523809523808
Delta: 8.661133529742062e-05 	  Loss: 1.0410536479429313 	 Accuracy: 0.23809523809523808
Delta: 0.0001563623495146261 	  Loss: 1.0410535161182657 	 Accuracy: 0.23809523809523808
Delta: 0.00025523567566907335 	  Loss: 1.0410542062992656 	 Accuracy: 0.23809523809523808
Delta: 0.00045015604905275524 	  Loss: 1.0410558697258798 	 Accuracy: 0.23809523809523808
Delta: 0.0001569907116796526 	  Loss: 1.0410540888683104 	 Accuracy: 0.23809523809523808
Delta: 0.00011225164383044767 	  Loss: 1.041054136583449 	 Accuracy: 0.23809523809523808
converged at iter  64
Delta: 0.058895586661675006 	  Loss: 1.0775968020964963 	 Accuracy: 0.27419354838709675
Delta: 0.0470255340083288 	  Loss: 1.0737477443464079 	 Accuracy: 0.20967741935483872
Delta: 0.03870322221338557 	  Loss: 1.0711653813136204 	 Accuracy: 0.22580645161290322
Delta: 0.02589497175125815 	  Loss: 1.0664123411008442 	 Accuracy: 0.22580645161290322

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.019356908984116086 	  Loss: 1.0633413669605816 	 Accuracy: 0.22580645161290322
Delta: 0.01571714337466761 	  Loss: 1.0619923570167078 	 Accuracy: 0.22580645161290322
Delta: 0.013915015224131123 	  Loss: 1.061107480368396 	 Accuracy: 0.22580645161290322
Delta: 0.01197687836064746 	  Loss: 1.0604419408137944 	 Accuracy: 0.22580645161290322
Delta: 0.010444873273226421 	  Loss: 1.0599787901389468 	 Accuracy: 0.22580645161290322
Delta: 0.010933302486109596 	  Loss: 1.0595830099602461 	 Accuracy: 0.22580645161290322
Delta: 0.012236400289998844 	  Loss: 1.0591082464769719 	 Accuracy: 0.22580645161290322
Delta: 0.011929702852819442 	  Loss: 1.05850356215799 	 Accuracy: 0.22580645161290322
Delta: 0.01146863457333154 	  Loss: 1.0579385356399973 	 Accuracy: 0.22580645161290322
Delta: 0.01050830800309431 	  Loss: 1.0575107642456176 	 Accuracy: 0.22580645161290322
Delta: 0.010309725256851813 	  Loss: 1.0571370484385505 	 Accuracy: 0.22580645161290322
Delta: 0.009760508541017766 	  Loss: 1.0567797872422664 	 Accuracy: 0.22580645161290322
Delta: 0.009588317095220865 	  Loss: 1.0563870273539644 	 Accuracy: 0.22580645161290322
Delta: 0.010126227149230607 	  Loss: 1.0559865591580406 	 Accuracy: 0.22580645161290322
Delta: 0.009082204721256992 	  Loss: 1.0557074480560038 	 Accuracy: 0.22580645161290322
Delta: 0.007846854797808197 	  Loss: 1.0555142950873082 	 Accuracy: 0.22580645161290322
Delta: 0.008086335092915065 	  Loss: 1.0553012249549556 	 Accuracy: 0.22580645161290322
Delta: 0.007487518667848622 	  Loss: 1.0551112419783695 	 Accuracy: 0.22580645161290322
Delta: 0.006952955492171527 	  Loss: 1.0549288758462678 	 Accuracy: 0.22580645161290322
Delta: 0.006560158648388744 	  Loss: 1.0547307919310482 	 Accuracy: 0.22580645161290322
Delta: 0.006605222890899973 	  Loss: 1.0545666148570612 	 Accuracy: 0.22580645161290322
Delta: 0.007226659778772747 	  Loss: 1.0544286914539476 	 Accuracy: 0.22580645161290322
Delta: 0.0075117063639144315 	  Loss: 1.0542503993521741 	 Accuracy: 0.22580645161290322
Delta: 0.007012284580400955 	  Loss: 1.0540250543079988 	 Accuracy: 0.22580645161290322
Delta: 0.006970663510182819 	  Loss: 1.0537901089100556 	 Accuracy: 0.22580645161290322
Delta: 0.004962555885036091 	  Loss: 1.0536108350619255 	 Accuracy: 0.22580645161290322
Delta: 0.005535645910301772 	  Loss: 1.0534855986515206 	 Accuracy: 0.22580645161290322
Delta: 0.0047495592017856745 	  Loss: 1.0533446512480302 	 Accuracy: 0.22580645161290322
Delta: 0.003879034235000264 	  Loss: 1.0532652586967601 	 Accuracy: 0.22580645161290322
Delta: 0.0037996629406893434 	  Loss: 1.0532333386686883 	 Accuracy: 0.22580645161290322
Delta: 0.002701689631701476 	  Loss: 1.0531978865009193 	 Accuracy: 0.22580645161290322
Delta: 0.0027635434142842035 	  Loss: 1.0531595347236125 	 Accuracy: 0.22580645161290322
Delta: 0.002709519458904184 	  Loss: 1.0531366200081764 	 Accuracy: 0.22580645161290322
Delta: 0.002349915304281206 	  Loss: 1.053091711155782 	 Accuracy: 0.22580645161290322
Delta: 0.003275165687396685 	  Loss: 1.0530517746647172 	 Accuracy: 0.22580645161290322
Delta: 0.003021514144685647 	  Loss: 1.0529951248865785 	 Accuracy: 0.22580645161290322
Delta: 0.0031699945535878546 	  Loss: 1.0529712779981169 	 Accuracy: 0.22580645161290322
Delta: 0.0025235490482571057 	  Loss: 1.0529459657460403 	 Accuracy: 0.22580645161290322
Delta: 0.0020842529902293594 	  Loss: 1.0529139988970413 	 Accuracy: 0.22580645161290322
Delta: 0.002182821055119102 	  Loss: 1.0528866148985707 	 Accuracy: 0.22580645161290322
Delta: 0.0015282819541021393 	  Loss: 1.0528633338972189 	 Accuracy: 0.22580645161290322
Delta: 0.0018397962355345561 	  Loss: 1.0528585783203999 	 Accuracy: 0.22580645161290322
Delta: 0.0021438509690531763 	  Loss: 1.0528419135377143 	 Accuracy: 0.22580645161290322
Delta: 0.002074377890855425 	  Loss: 1.0528336260503406 	 Accuracy: 0.22580645161290322
Delta: 0.0014107667279320917 	  Loss: 1.0528201424571924 	 Accuracy: 0.22580645161290322
Delta: 0.0012084321120773745 	  Loss: 1.052819802734048 	 Accuracy: 0.22580645161290322
Delta: 0.0007196348085703718 	  Loss: 1.0528047302366637 	 Accuracy: 0.22580645161290322
Delta: 0.0006458693223186683 	  Loss: 1.0528059133293208 	 Accuracy: 0.22580645161290322
Delta: 0.0008666067668723434 	  Loss: 1.0528055871611 	 Accuracy: 0.22580645161290322
Delta: 0.0006504966964540936 	  Loss: 1.052799947395799 	 Accuracy: 0.22580645161290322
Delta: 0.0016678129117256653 	  Loss: 1.0527975467848156 	 Accuracy: 0.22580645161290322
Delta: 0.0013425628609374492 	  Loss: 1.0527951186091584 	 Accuracy: 0.22580645161290322
Delta: 0.00123923121644599 	  Loss: 1.052806808054609 	 Accuracy: 0.22580645161290322
Delta: 0.0007868688835490843 	  Loss: 1.0528037405511306 	 Accuracy: 0.22580645161290322
Delta: 0.0009259123657821463 	  Loss: 1.0528077975356847 	 Accuracy: 0.22580645161290322
Delta: 0.0008737044806989538 	  Loss: 1.0528091424206665 	 Accuracy: 0.22580645161290322
Delta: 0.000691556666241122 	  Loss: 1.052810663794356 	 Accuracy: 0.22580645161290322
Delta: 0.0008217410752002122 	  Loss: 1.0528102268545292 	 Accuracy: 0.22580645161290322
Delta: 0.0013032171149100664 	  Loss: 1.0528121322754405 	 Accuracy: 0.22580645161290322
Delta: 0.0009516797797197469 	  Loss: 1.0528156248627614 	 Accuracy: 0.22580645161290322
Delta: 0.001166273796097766 	  Loss: 1.0528234218860208 	 Accuracy: 0.22580645161290322
Delta: 0.0006259116544050314 	  Loss: 1.0528309388380586 	 Accuracy: 0.22580645161290322
Delta: 0.0005931775280135032 	  Loss: 1.0528333415863393 	 Accuracy: 0.22580645161290322
Delta: 0.000539911955444534 	  Loss: 1.0528420773673988 	 Accuracy: 0.22580645161290322
Delta: 0.0005360486797344756 	  Loss: 1.0528410844859204 	 Accuracy: 0.22580645161290322
Delta: 0.0006070976946278409 	  Loss: 1.0528390036596442 	 Accuracy: 0.22580645161290322
Delta: 0.00031296364083945093 	  Loss: 1.052838970584177 	 Accuracy: 0.22580645161290322
converged at iter  70
Delta: 0.05920998463770233 	  Loss: 1.0795220009165478 	 Accuracy: 0.27419354838709675
Delta: 0.04137249495376441 	  Loss: 1.0701749355877008 	 Accuracy: 0.16129032258064516
Delta: 0.03340936033357204 	  Loss: 1.0632218481316311 	 Accuracy: 0.14516129032258066

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028952992414073085 	  Loss: 1.0579616015553253 	 Accuracy: 0.14516129032258066
Delta: 0.01884805413801969 	  Loss: 1.0555143746582185 	 Accuracy: 0.14516129032258066
Delta: 0.014119767281669728 	  Loss: 1.0544212637252657 	 Accuracy: 0.14516129032258066
Delta: 0.011314296033011588 	  Loss: 1.0537560703279252 	 Accuracy: 0.14516129032258066
Delta: 0.009127000467841512 	  Loss: 1.053385404601387 	 Accuracy: 0.14516129032258066
Delta: 0.009007773619270722 	  Loss: 1.0531294065579928 	 Accuracy: 0.14516129032258066
Delta: 0.0067367717363373105 	  Loss: 1.0529104221316754 	 Accuracy: 0.14516129032258066
Delta: 0.005625034815333217 	  Loss: 1.0527262123696353 	 Accuracy: 0.14516129032258066
Delta: 0.006176001399101567 	  Loss: 1.052595815209103 	 Accuracy: 0.14516129032258066
Delta: 0.005822357971090022 	  Loss: 1.0524516015728524 	 Accuracy: 0.14516129032258066
Delta: 0.0051324809071156075 	  Loss: 1.0523045876768016 	 Accuracy: 0.14516129032258066
Delta: 0.005670617353731538 	  Loss: 1.0521773458112733 	 Accuracy: 0.14516129032258066
Delta: 0.005481363803296115 	  Loss: 1.0520247854663003 	 Accuracy: 0.14516129032258066
Delta: 0.004323408242603498 	  Loss: 1.051849794375317 	 Accuracy: 0.14516129032258066
Delta: 0.004779766451020711 	  Loss: 1.051757144239795 	 Accuracy: 0.14516129032258066
Delta: 0.0046969646017302105 	  Loss: 1.0516555665032543 	 Accuracy: 0.14516129032258066
Delta: 0.00267734503125743 	  Loss: 1.0516117789645034 	 Accuracy: 0.14516129032258066
Delta: 0.002362553707897531 	  Loss: 1.0515848261881673 	 Accuracy: 0.14516129032258066
Delta: 0.001914734303594576 	  Loss: 1.051543280965889 	 Accuracy: 0.14516129032258066
Delta: 0.0017720314258879992 	  Loss: 1.0515319960764744 	 Accuracy: 0.14516129032258066
Delta: 0.002009835088318531 	  Loss: 1.051528735875401 	 Accuracy: 0.14516129032258066
Delta: 0.0008813941249581777 	  Loss: 1.0515282357203242 	 Accuracy: 0.14516129032258066
Delta: 0.0009560428241845289 	  Loss: 1.0515337905611641 	 Accuracy: 0.14516129032258066
Delta: 0.0006521256784541324 	  Loss: 1.051535532905047 	 Accuracy: 0.14516129032258066
Delta: 0.0003921432153932923 	  Loss: 1.051534196962359 	 Accuracy: 0.14516129032258066
Delta: 0.0004957426568386673 	  Loss: 1.051529573370221 	 Accuracy: 0.14516129032258066
Delta: 0.0003723949573390166 	  Loss: 1.051528391946435 	 Accuracy: 0.14516129032258066
Delta: 0.00022218237898369815 	  Loss: 1.0515267288714267 	 Accuracy: 0.14516129032258066
Delta: 7.874243609598174e-05 	  Loss: 1.0515257326424168 	 Accuracy: 0.14516129032258066
Delta: 0.00014404168203635597 	  Loss: 1.0515256246703961 	 Accuracy: 0.14516129032258066
Delta: 8.435163796084171e-05 	  Loss: 1.051525338338909 	 Accuracy: 0.14516129032258066
Delta: 2.0684996778683343e-05 	  Loss: 1.0515249128778104 	 Accuracy: 0.14516129032258066
Delta: 1.2768594847765363e-06 	  Loss: 1.0515247837394663 	 Accuracy: 0.14516129032258066
Delta: 3.227599998607319e-17 	  Loss: 1.0515247837394663 	 Accuracy: 0.14516129032258066
converged at iter  36
Delta: 0.056536990999764336 	  Loss: 1.0800160452620986 	 Accuracy: 0.5483870967741935
Delta: 0.042370460973474335 	  Loss: 1.0734911844944937 	 Accuracy: 0.4032258064516129

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028223273955680108 	  Loss: 1.066760977628959 	 Accuracy: 0.3870967741935484
Delta: 0.02327098539003148 	  Loss: 1.0624150287056207 	 Accuracy: 0.3870967741935484
Delta: 0.017473583092596504 	  Loss: 1.0602490535380638 	 Accuracy: 0.3870967741935484
Delta: 0.014689322736326886 	  Loss: 1.0589372651618907 	 Accuracy: 0.3870967741935484
Delta: 0.013096283421859064 	  Loss: 1.0580083518250978 	 Accuracy: 0.3870967741935484
Delta: 0.009964854165797647 	  Loss: 1.0574368659949078 	 Accuracy: 0.3870967741935484
Delta: 0.008129909428491266 	  Loss: 1.057106901901571 	 Accuracy: 0.3870967741935484
Delta: 0.007003147942593711 	  Loss: 1.0569167249544378 	 Accuracy: 0.3870967741935484
Delta: 0.0071546296360876695 	  Loss: 1.0567849093331954 	 Accuracy: 0.3870967741935484
Delta: 0.006543250912458383 	  Loss: 1.0566701033880372 	 Accuracy: 0.3870967741935484
Delta: 0.005707600246539919 	  Loss: 1.0565615684198524 	 Accuracy: 0.3870967741935484
Delta: 0.005561335855909752 	  Loss: 1.0564990358905262 	 Accuracy: 0.3870967741935484
Delta: 0.006220049060831299 	  Loss: 1.0564132733620333 	 Accuracy: 0.3870967741935484
Delta: 0.006816816367354673 	  Loss: 1.056330628904662 	 Accuracy: 0.3870967741935484
Delta: 0.0075815144847572544 	  Loss: 1.0562233269543901 	 Accuracy: 0.3870967741935484
Delta: 0.008055765953133993 	  Loss: 1.056078897215234 	 Accuracy: 0.3870967741935484
Delta: 0.00815778189060103 	  Loss: 1.055887178081731 	 Accuracy: 0.3870967741935484
Delta: 0.008993835528786284 	  Loss: 1.0556301584916334 	 Accuracy: 0.3870967741935484
Delta: 0.008557339973605029 	  Loss: 1.055287241229558 	 Accuracy: 0.3870967741935484
Delta: 0.009151035081227662 	  Loss: 1.054902536514224 	 Accuracy: 0.3870967741935484
Delta: 0.008298529763916145 	  Loss: 1.0545754354984913 	 Accuracy: 0.3870967741935484
Delta: 0.008972046175658067 	  Loss: 1.054319455208284 	 Accuracy: 0.3870967741935484
Delta: 0.006856421894253937 	  Loss: 1.0540480806609551 	 Accuracy: 0.3870967741935484
Delta: 0.006057445259947637 	  Loss: 1.0538519381526434 	 Accuracy: 0.3870967741935484
Delta: 0.004452470710693349 	  Loss: 1.0537439736808734 	 Accuracy: 0.3870967741935484
Delta: 0.0041523091999817316 	  Loss: 1.0536515036370129 	 Accuracy: 0.3870967741935484
Delta: 0.0037809580136280545 	  Loss: 1.0535972088042855 	 Accuracy: 0.3870967741935484
Delta: 0.0032661845388558793 	  Loss: 1.053565265501923 	 Accuracy: 0.3870967741935484
Delta: 0.003647247548348724 	  Loss: 1.0535369271786306 	 Accuracy: 0.3870967741935484
Delta: 0.0036921510937775012 	  Loss: 1.053517200447566 	 Accuracy: 0.3870967741935484
Delta: 0.0035924139124318306 	  Loss: 1.0535001400247785 	 Accuracy: 0.3870967741935484
Delta: 0.0035695007239332664 	  Loss: 1.053463923882699 	 Accuracy: 0.3870967741935484
Delta: 0.0026529996945182568 	  Loss: 1.0534304404786954 	 Accuracy: 0.3870967741935484
Delta: 0.002992723904586405 	  Loss: 1.0534226802374862 	 Accuracy: 0.3870967741935484
Delta: 0.0032703312044031116 	  Loss: 1.0534003577326319 	 Accuracy: 0.3870967741935484
Delta: 0.002530698232599286 	  Loss: 1.0533581159229688 	 Accuracy: 0.3870967741935484
Delta: 0.002924787465371779 	  Loss: 1.0533441025447774 	 Accuracy: 0.3870967741935484
Delta: 0.003177439405153842 	  Loss: 1.0533133963656427 	 Accuracy: 0.3870967741935484
Delta: 0.0030050183487016612 	  Loss: 1.053290064615981 	 Accuracy: 0.3870967741935484
Delta: 0.0036595275311401133 	  Loss: 1.0532556786513017 	 Accuracy: 0.3870967741935484
Delta: 0.004582463418627596 	  Loss: 1.0532231768737086 	 Accuracy: 0.3870967741935484
Delta: 0.004149934176779852 	  Loss: 1.0531684397362149 	 Accuracy: 0.3870967741935484
Delta: 0.0037823884279359465 	  Loss: 1.0531252846271426 	 Accuracy: 0.3870967741935484
Delta: 0.003564654338066132 	  Loss: 1.0530581589523456 	 Accuracy: 0.3870967741935484
Delta: 0.003515117089858901 	  Loss: 1.0530273461977822 	 Accuracy: 0.3870967741935484
Delta: 0.004102594078850353 	  Loss: 1.052982664274086 	 Accuracy: 0.3870967741935484
Delta: 0.004175104759365542 	  Loss: 1.0529021594470827 	 Accuracy: 0.3870967741935484
Delta: 0.004368484499396696 	  Loss: 1.0528025928964162 	 Accuracy: 0.3870967741935484
Delta: 0.0037030846972150974 	  Loss: 1.0527588850635294 	 Accuracy: 0.3870967741935484
Delta: 0.0034854914295541248 	  Loss: 1.0527004152301624 	 Accuracy: 0.3870967741935484
Delta: 0.003869393370630385 	  Loss: 1.05262262225476 	 Accuracy: 0.3870967741935484
Delta: 0.0026322342141485216 	  Loss: 1.0525742778167058 	 Accuracy: 0.3870967741935484
Delta: 0.0030428348897588967 	  Loss: 1.0525527759918445 	 Accuracy: 0.3870967741935484
Delta: 0.003698523887916761 	  Loss: 1.0525212112536122 	 Accuracy: 0.3870967741935484
Delta: 0.0037058767095476987 	  Loss: 1.0524878784067577 	 Accuracy: 0.3870967741935484
Delta: 0.003155086723953947 	  Loss: 1.0524607708369005 	 Accuracy: 0.3870967741935484
Delta: 0.0035897855795540817 	  Loss: 1.0524275673467423 	 Accuracy: 0.3870967741935484
Delta: 0.003404433960743424 	  Loss: 1.0523854548880112 	 Accuracy: 0.3870967741935484
Delta: 0.0031393223952745747 	  Loss: 1.052332230773189 	 Accuracy: 0.3870967741935484
Delta: 0.0029466204954497876 	  Loss: 1.0522987796353447 	 Accuracy: 0.3870967741935484
Delta: 0.0026027416684487473 	  Loss: 1.0522615406249913 	 Accuracy: 0.3870967741935484
Delta: 0.0017636111559214765 	  Loss: 1.0522365385663153 	 Accuracy: 0.3870967741935484
Delta: 0.0019595675594249007 	  Loss: 1.0522320429608056 	 Accuracy: 0.3870967741935484
Delta: 0.0020950586029764053 	  Loss: 1.052202566799917 	 Accuracy: 0.3870967741935484
Delta: 0.002270349255619179 	  Loss: 1.0521769441888713 	 Accuracy: 0.3870967741935484
Delta: 0.002140079599178522 	  Loss: 1.052153851334372 	 Accuracy: 0.3870967741935484
Delta: 0.00244425973694493 	  Loss: 1.0521402829904956 	 Accuracy: 0.3870967741935484
Delta: 0.0024373564685990045 	  Loss: 1.0521287578296636 	 Accuracy: 0.3870967741935484
Delta: 0.002161278949203227 	  Loss: 1.0521340953762959 	 Accuracy: 0.3870967741935484
Delta: 0.0019523250307648089 	  Loss: 1.052110665984756 	 Accuracy: 0.3870967741935484
Delta: 0.001959980609808156 	  Loss: 1.0520859799134654 	 Accuracy: 0.3870967741935484
Delta: 0.0018731536707526702 	  Loss: 1.0520737789082375 	 Accuracy: 0.3870967741935484
Delta: 0.0011765557028239392 	  Loss: 1.0520460366601223 	 Accuracy: 0.3870967741935484
Delta: 0.0018202156106667965 	  Loss: 1.052032797389351 	 Accuracy: 0.3870967741935484
Delta: 0.002180766510846882 	  Loss: 1.0520276690526253 	 Accuracy: 0.3870967741935484
Delta: 0.0015227261980843578 	  Loss: 1.05200545320105 	 Accuracy: 0.3870967741935484
Delta: 0.0008551295349675594 	  Loss: 1.0520072748912155 	 Accuracy: 0.3870967741935484
Delta: 0.0009103962874784418 	  Loss: 1.0520007983416146 	 Accuracy: 0.3870967741935484
Delta: 0.0014864640089828668 	  Loss: 1.051994225407532 	 Accuracy: 0.3870967741935484
Delta: 0.003117555429116322 	  Loss: 1.0519762735494715 	 Accuracy: 0.3870967741935484
Delta: 0.0028852214182245313 	  Loss: 1.0519333862184095 	 Accuracy: 0.3870967741935484
Delta: 0.00208381356626133 	  Loss: 1.0518784485720296 	 Accuracy: 0.3870967741935484
Delta: 0.0019180102814846814 	  Loss: 1.0518651532898846 	 Accuracy: 0.3870967741935484
Delta: 0.002386706111327922 	  Loss: 1.0518402100325825 	 Accuracy: 0.3870967741935484
Delta: 0.0023944720619391126 	  Loss: 1.0518045632603448 	 Accuracy: 0.3870967741935484
Delta: 0.0030305655035604536 	  Loss: 1.051775321883946 	 Accuracy: 0.3870967741935484
Delta: 0.0028916137839016406 	  Loss: 1.051751426718658 	 Accuracy: 0.3870967741935484
Delta: 0.0026433349923197097 	  Loss: 1.051709229350798 	 Accuracy: 0.3870967741935484
Delta: 0.0020323666124325364 	  Loss: 1.0516706244567213 	 Accuracy: 0.3870967741935484
Delta: 0.002705386114507847 	  Loss: 1.0516295557251911 	 Accuracy: 0.3870967741935484
Delta: 0.002576144661728868 	  Loss: 1.051587654282316 	 Accuracy: 0.3870967741935484
Delta: 0.0023958794530529264 	  Loss: 1.051560590053642 	 Accuracy: 0.3870967741935484
Delta: 0.0017702378971992565 	  Loss: 1.0515368608743136 	 Accuracy: 0.3870967741935484
Delta: 0.0019462050563902771 	  Loss: 1.0515218277534113 	 Accuracy: 0.3870967741935484
Delta: 0.0021994404509785258 	  Loss: 1.0514984302384356 	 Accuracy: 0.3870967741935484
Delta: 0.0014821533706633819 	  Loss: 1.0514864349366593 	 Accuracy: 0.3870967741935484
Delta: 0.0014048577498621403 	  Loss: 1.0514771285386293 	 Accuracy: 0.3870967741935484
Delta: 0.0014570985941181292 	  Loss: 1.051473734159195 	 Accuracy: 0.3870967741935484
Delta: 0.05765553277715957 	  Loss: 1.072770188674805 	 Accuracy: 0.3333333333333333
Delta: 0.046877307227679514 	  Loss: 1.0667719728146237 	 Accuracy: 0.2222222222222222
Delta: 0.03197779748933585 	  Loss: 1.0617257834534461 	 Accuracy: 0.2222222222222222

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02230494448055654 	  Loss: 1.0580677840813157 	 Accuracy: 0.20634920634920634
Delta: 0.015937313518088976 	  Loss: 1.0561744492764578 	 Accuracy: 0.2222222222222222
Delta: 0.012597151685613338 	  Loss: 1.0552022811580684 	 Accuracy: 0.2222222222222222
Delta: 0.010374672854623363 	  Loss: 1.0546406696046118 	 Accuracy: 0.2222222222222222
Delta: 0.008446414959471633 	  Loss: 1.0542733840896485 	 Accuracy: 0.2222222222222222
Delta: 0.008154841765989854 	  Loss: 1.0540005806405404 	 Accuracy: 0.2222222222222222
Delta: 0.007021418411147813 	  Loss: 1.0537512279749883 	 Accuracy: 0.2222222222222222
Delta: 0.00581015965415404 	  Loss: 1.0535490245136898 	 Accuracy: 0.2222222222222222
Delta: 0.006230885845777224 	  Loss: 1.0533901505845167 	 Accuracy: 0.2222222222222222
Delta: 0.005684775130501744 	  Loss: 1.053221788502272 	 Accuracy: 0.2222222222222222
Delta: 0.005210654136843838 	  Loss: 1.0530798723801462 	 Accuracy: 0.2222222222222222
Delta: 0.005134031957920017 	  Loss: 1.0529158541937371 	 Accuracy: 0.2222222222222222
Delta: 0.004624697172961729 	  Loss: 1.0527870883385806 	 Accuracy: 0.2222222222222222
Delta: 0.004445150575447621 	  Loss: 1.0527474917326254 	 Accuracy: 0.2222222222222222
Delta: 0.004618368980784684 	  Loss: 1.0526925462342716 	 Accuracy: 0.2222222222222222
Delta: 0.004270943199627212 	  Loss: 1.0526472007820986 	 Accuracy: 0.2222222222222222
Delta: 0.0035119505270541605 	  Loss: 1.0525857179260214 	 Accuracy: 0.2222222222222222
Delta: 0.0027739075397207867 	  Loss: 1.0525640067758064 	 Accuracy: 0.2222222222222222
Delta: 0.0037833862561852177 	  Loss: 1.0525470292272132 	 Accuracy: 0.2222222222222222
Delta: 0.004380331455331761 	  Loss: 1.0525049606777157 	 Accuracy: 0.2222222222222222
Delta: 0.003021995857919413 	  Loss: 1.0524957426977772 	 Accuracy: 0.2222222222222222
Delta: 0.0019294863832953603 	  Loss: 1.0524812947712485 	 Accuracy: 0.2222222222222222
Delta: 0.0015226454349040808 	  Loss: 1.052481396100651 	 Accuracy: 0.2222222222222222
Delta: 0.0013467157933565934 	  Loss: 1.0524735058321784 	 Accuracy: 0.2222222222222222
Delta: 0.0013085320290305619 	  Loss: 1.0524578648135212 	 Accuracy: 0.2222222222222222
Delta: 0.0016023625943466949 	  Loss: 1.0524468423060773 	 Accuracy: 0.2222222222222222
Delta: 0.0016744358422653245 	  Loss: 1.052428642131721 	 Accuracy: 0.2222222222222222
Delta: 0.002078025277427136 	  Loss: 1.0524260873053721 	 Accuracy: 0.2222222222222222
Delta: 0.001544721825892877 	  Loss: 1.0524100069513782 	 Accuracy: 0.2222222222222222
Delta: 0.001527787812154837 	  Loss: 1.0523957977404574 	 Accuracy: 0.2222222222222222
Delta: 0.001090225042532495 	  Loss: 1.0523982670959557 	 Accuracy: 0.2222222222222222
Delta: 0.0021717582222809703 	  Loss: 1.052396518709875 	 Accuracy: 0.2222222222222222
Delta: 0.0025009222204132094 	  Loss: 1.052403458459215 	 Accuracy: 0.2222222222222222
Delta: 0.002992252722874238 	  Loss: 1.0523988665695316 	 Accuracy: 0.2222222222222222
Delta: 0.003043381306411472 	  Loss: 1.0523691039057579 	 Accuracy: 0.2222222222222222
Delta: 0.0026562392886308635 	  Loss: 1.052316373865212 	 Accuracy: 0.2222222222222222
Delta: 0.003638870095998726 	  Loss: 1.0522846953348237 	 Accuracy: 0.2222222222222222
Delta: 0.0033542815028513814 	  Loss: 1.052208168609898 	 Accuracy: 0.2222222222222222
Delta: 0.0035158445299549638 	  Loss: 1.052155686191044 	 Accuracy: 0.2222222222222222
Delta: 0.003540244252440944 	  Loss: 1.0520495881546799 	 Accuracy: 0.2222222222222222
Delta: 0.0034519198582008133 	  Loss: 1.0520040290015626 	 Accuracy: 0.2222222222222222
Delta: 0.003350623615666972 	  Loss: 1.0519626320648727 	 Accuracy: 0.2222222222222222
Delta: 0.0027082391618484577 	  Loss: 1.0519298859356634 	 Accuracy: 0.2222222222222222
Delta: 0.002762229755806458 	  Loss: 1.0519120579830874 	 Accuracy: 0.2222222222222222
Delta: 0.002332760409170742 	  Loss: 1.0518875630394429 	 Accuracy: 0.2222222222222222
Delta: 0.0019899913376315906 	  Loss: 1.0518812533218884 	 Accuracy: 0.2222222222222222
Delta: 0.0027128030706649623 	  Loss: 1.0518613201327542 	 Accuracy: 0.2222222222222222
Delta: 0.002917782847782929 	  Loss: 1.0518231448416153 	 Accuracy: 0.2222222222222222
Delta: 0.0029375090531152787 	  Loss: 1.0518170237928377 	 Accuracy: 0.2222222222222222
Delta: 0.0023740194595439764 	  Loss: 1.051814789785848 	 Accuracy: 0.2222222222222222
Delta: 0.0027388361371352117 	  Loss: 1.0517700510143801 	 Accuracy: 0.2222222222222222
Delta: 0.003273804892373309 	  Loss: 1.051727071667936 	 Accuracy: 0.2222222222222222
Delta: 0.0017896174438008046 	  Loss: 1.0516723303871724 	 Accuracy: 0.2222222222222222
Delta: 0.0015569874706395197 	  Loss: 1.0516610005946911 	 Accuracy: 0.2222222222222222
Delta: 0.0012180888271106241 	  Loss: 1.0516449838184727 	 Accuracy: 0.2222222222222222
Delta: 0.0008162431265368727 	  Loss: 1.0516317693981119 	 Accuracy: 0.2222222222222222
Delta: 0.0006103872266653809 	  Loss: 1.0516300610723137 	 Accuracy: 0.2222222222222222
Delta: 0.0008124562197621126 	  Loss: 1.0516310651434955 	 Accuracy: 0.2222222222222222
Delta: 0.0008677846300116833 	  Loss: 1.0516371280223704 	 Accuracy: 0.2222222222222222
Delta: 0.001129793377108253 	  Loss: 1.051640794662148 	 Accuracy: 0.2222222222222222
Delta: 0.0013329746111366998 	  Loss: 1.0516479231959943 	 Accuracy: 0.2222222222222222
Delta: 0.0012620249794975346 	  Loss: 1.0516555906367144 	 Accuracy: 0.2222222222222222
Delta: 0.0010324909620463623 	  Loss: 1.051656175812392 	 Accuracy: 0.2222222222222222
Delta: 0.0006129244037046825 	  Loss: 1.0516557400447388 	 Accuracy: 0.2222222222222222
Delta: 0.00020576897209285562 	  Loss: 1.0516565072932131 	 Accuracy: 0.2222222222222222
Delta: 6.229283012275066e-05 	  Loss: 1.0516563459853492 	 Accuracy: 0.2222222222222222
Delta: 2.994415004474691e-05 	  Loss: 1.0516563685775764 	 Accuracy: 0.2222222222222222
converged at iter  69
Delta: 0.056879373988150704 	  Loss: 1.0700338315461853 	 Accuracy: 0.23809523809523808
Delta: 0.04158783825197975 	  Loss: 1.0580683423931632 	 Accuracy: 0.3333333333333333
Delta: 0.02909407595575945 	  Loss: 1.052462807610182 	 Accuracy: 0.30158730158730157

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02120097471566967 	  Loss: 1.0489404230002097 	 Accuracy: 0.30158730158730157
Delta: 0.015796642314591002 	  Loss: 1.047024375323378 	 Accuracy: 0.30158730158730157
Delta: 0.010942057578579932 	  Loss: 1.0461745569341536 	 Accuracy: 0.30158730158730157
Delta: 0.00851991384604671 	  Loss: 1.0456419385751026 	 Accuracy: 0.30158730158730157
Delta: 0.007161335750656834 	  Loss: 1.045361088457664 	 Accuracy: 0.30158730158730157
Delta: 0.006227447671972416 	  Loss: 1.0451387986265328 	 Accuracy: 0.30158730158730157
Delta: 0.007258523253378447 	  Loss: 1.044921177567025 	 Accuracy: 0.30158730158730157
Delta: 0.006947850361558781 	  Loss: 1.0446785932140519 	 Accuracy: 0.30158730158730157
Delta: 0.007437079930691429 	  Loss: 1.0443696343802633 	 Accuracy: 0.30158730158730157
Delta: 0.007617532521035375 	  Loss: 1.044117152119113 	 Accuracy: 0.30158730158730157
Delta: 0.005960334146301714 	  Loss: 1.0439059647766382 	 Accuracy: 0.30158730158730157
Delta: 0.006094985243648501 	  Loss: 1.0437953552457104 	 Accuracy: 0.30158730158730157
Delta: 0.00598244470459265 	  Loss: 1.0436391487596806 	 Accuracy: 0.30158730158730157
Delta: 0.004852666737713845 	  Loss: 1.0435291987177653 	 Accuracy: 0.30158730158730157
Delta: 0.003794069140991937 	  Loss: 1.043459875444129 	 Accuracy: 0.30158730158730157
Delta: 0.0040416339491908095 	  Loss: 1.043450477797594 	 Accuracy: 0.30158730158730157
Delta: 0.003962809663726455 	  Loss: 1.0434422582529925 	 Accuracy: 0.30158730158730157
Delta: 0.004376745383817839 	  Loss: 1.0434240867917792 	 Accuracy: 0.30158730158730157
Delta: 0.004125962983251416 	  Loss: 1.0433852824059975 	 Accuracy: 0.30158730158730157
Delta: 0.002868704870122937 	  Loss: 1.0433572933078583 	 Accuracy: 0.30158730158730157
Delta: 0.0037748285369703653 	  Loss: 1.0433416899661914 	 Accuracy: 0.30158730158730157
Delta: 0.003946656133232596 	  Loss: 1.0433069866579792 	 Accuracy: 0.30158730158730157
Delta: 0.003644125468238476 	  Loss: 1.0432469253346994 	 Accuracy: 0.30158730158730157
Delta: 0.0033719773277899046 	  Loss: 1.04322067591769 	 Accuracy: 0.30158730158730157
Delta: 0.0030143968248527915 	  Loss: 1.0432030185818846 	 Accuracy: 0.30158730158730157
Delta: 0.002844665477760779 	  Loss: 1.0431908568438375 	 Accuracy: 0.30158730158730157
Delta: 0.003908144833918082 	  Loss: 1.0431602551311552 	 Accuracy: 0.30158730158730157
Delta: 0.0034532047981503814 	  Loss: 1.043117219216762 	 Accuracy: 0.30158730158730157
Delta: 0.00364278917258594 	  Loss: 1.0430611897930897 	 Accuracy: 0.30158730158730157
Delta: 0.0032234010793010803 	  Loss: 1.043005563213458 	 Accuracy: 0.30158730158730157
Delta: 0.0034804218405841184 	  Loss: 1.0429324920171081 	 Accuracy: 0.30158730158730157
Delta: 0.0037436430356848674 	  Loss: 1.042871580335544 	 Accuracy: 0.30158730158730157
Delta: 0.0034583309148554725 	  Loss: 1.0427964296768448 	 Accuracy: 0.30158730158730157
Delta: 0.004048225586595019 	  Loss: 1.042745229610774 	 Accuracy: 0.30158730158730157
Delta: 0.004564012824573337 	  Loss: 1.0426745512710283 	 Accuracy: 0.30158730158730157
Delta: 0.00425341480494682 	  Loss: 1.0425631083753277 	 Accuracy: 0.30158730158730157
Delta: 0.00451211557916451 	  Loss: 1.042466306290073 	 Accuracy: 0.30158730158730157
Delta: 0.005251617247756474 	  Loss: 1.0423501525842056 	 Accuracy: 0.30158730158730157
Delta: 0.006257800459149623 	  Loss: 1.0421850922298508 	 Accuracy: 0.30158730158730157
Delta: 0.0054613747459097825 	  Loss: 1.0419999067978203 	 Accuracy: 0.30158730158730157
Delta: 0.0052211040557412795 	  Loss: 1.0418552492627366 	 Accuracy: 0.30158730158730157
Delta: 0.004406209080263009 	  Loss: 1.04175785719651 	 Accuracy: 0.30158730158730157
Delta: 0.0034074204116758145 	  Loss: 1.0416585691889457 	 Accuracy: 0.30158730158730157
Delta: 0.0028123882744142607 	  Loss: 1.0416071329389758 	 Accuracy: 0.30158730158730157
Delta: 0.002953358238318304 	  Loss: 1.0415681232290666 	 Accuracy: 0.30158730158730157
Delta: 0.002578685192421638 	  Loss: 1.0415397351585631 	 Accuracy: 0.30158730158730157
Delta: 0.002349416067686971 	  Loss: 1.0415260324866737 	 Accuracy: 0.30158730158730157
Delta: 0.002076779200093855 	  Loss: 1.0415130419315979 	 Accuracy: 0.30158730158730157
Delta: 0.001895719763766129 	  Loss: 1.0415083838061783 	 Accuracy: 0.30158730158730157
Delta: 0.0019859595978915967 	  Loss: 1.0415011260065552 	 Accuracy: 0.30158730158730157
Delta: 0.0016676572236862734 	  Loss: 1.0414889896112454 	 Accuracy: 0.30158730158730157
Delta: 0.0014971449738731398 	  Loss: 1.0414879755432362 	 Accuracy: 0.30158730158730157
Delta: 0.0020980770896899315 	  Loss: 1.0414920385387392 	 Accuracy: 0.30158730158730157
Delta: 0.0012943600497124159 	  Loss: 1.041483559049639 	 Accuracy: 0.30158730158730157
Delta: 0.0011968746268316275 	  Loss: 1.041483414141222 	 Accuracy: 0.30158730158730157
Delta: 0.0017243450798363046 	  Loss: 1.0414858651885477 	 Accuracy: 0.30158730158730157
Delta: 0.0008443439260631662 	  Loss: 1.041498205333903 	 Accuracy: 0.30158730158730157
Delta: 0.00047671656120320914 	  Loss: 1.0415013706745326 	 Accuracy: 0.30158730158730157
Delta: 0.0004039504956519993 	  Loss: 1.0415000857503438 	 Accuracy: 0.30158730158730157
Delta: 0.0005059956144641212 	  Loss: 1.0414983232021668 	 Accuracy: 0.30158730158730157
Delta: 0.000532320323693398 	  Loss: 1.0414924598288364 	 Accuracy: 0.30158730158730157
Delta: 0.0010212107574871145 	  Loss: 1.041489018076851 	 Accuracy: 0.30158730158730157
Delta: 0.0009949973690932387 	  Loss: 1.0414876422683101 	 Accuracy: 0.30158730158730157
Delta: 0.0008208775003376838 	  Loss: 1.0414836098928668 	 Accuracy: 0.30158730158730157
Delta: 0.001618782508753329 	  Loss: 1.041482341602505 	 Accuracy: 0.30158730158730157
Delta: 0.0018619752590145699 	  Loss: 1.0414962801149033 	 Accuracy: 0.30158730158730157
Delta: 0.0017780353841125056 	  Loss: 1.04150669131502 	 Accuracy: 0.30158730158730157
Delta: 0.001159342245950803 	  Loss: 1.0415048869585695 	 Accuracy: 0.30158730158730157
Delta: 0.000531490826083054 	  Loss: 1.0415092042365046 	 Accuracy: 0.30158730158730157
Delta: 0.0007140309995627438 	  Loss: 1.0415119525404668 	 Accuracy: 0.30158730158730157
Delta: 0.0008792701115698244 	  Loss: 1.0415154913073656 	 Accuracy: 0.30158730158730157
Delta: 0.0007253682471322606 	  Loss: 1.0415134816724492 	 Accuracy: 0.30158730158730157
Delta: 0.001005145465284383 	  Loss: 1.0415114180205505 	 Accuracy: 0.30158730158730157
Delta: 0.0012856605258191507 	  Loss: 1.0415062585535575 	 Accuracy: 0.30158730158730157
Delta: 0.0007877372782739472 	  Loss: 1.0414972376151004 	 Accuracy: 0.30158730158730157
Delta: 0.00041033315221271924 	  Loss: 1.0414997594828843 	 Accuracy: 0.30158730158730157
Delta: 8.261662771193756e-05 	  Loss: 1.0414988526836613 	 Accuracy: 0.30158730158730157
Delta: 0.00032511168191549423 	  Loss: 1.0414983832419988 	 Accuracy: 0.30158730158730157
Delta: 1.790497341730613e-05 	  Loss: 1.0414986635007883 	 Accuracy: 0.30158730158730157
Delta: 2.768805992637297e-17 	  Loss: 1.0414986635007883 	 Accuracy: 0.30158730158730157
converged at iter  82
Delta: 0.059382953183810705 	  Loss: 1.0676789145660135 	 Accuracy: 0.5967741935483871
Delta: 0.047413522016469666 	  Loss: 1.061051969050411 	 Accuracy: 0.5806451612903226
Delta: 0.037327361179372014 	  Loss: 1.0545563347853815 	 Accuracy: 0.5806451612903226

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.027649485867837678 	  Loss: 1.0519289480959242 	 Accuracy: 0.5806451612903226
Delta: 0.01769147506939138 	  Loss: 1.0502607678375393 	 Accuracy: 0.5806451612903226
Delta: 0.012200689340319168 	  Loss: 1.0491579446436972 	 Accuracy: 0.5806451612903226
Delta: 0.008996299732805222 	  Loss: 1.0484690521297475 	 Accuracy: 0.5806451612903226
Delta: 0.006843389068723523 	  Loss: 1.0481024957007583 	 Accuracy: 0.5806451612903226
Delta: 0.00695963017088706 	  Loss: 1.04787201828499 	 Accuracy: 0.5806451612903226
Delta: 0.006456612799259051 	  Loss: 1.0476391548545128 	 Accuracy: 0.5806451612903226
Delta: 0.006404547911369091 	  Loss: 1.0474352396019462 	 Accuracy: 0.5806451612903226
Delta: 0.007414088462155127 	  Loss: 1.04731659838293 	 Accuracy: 0.5806451612903226
Delta: 0.007679444369564869 	  Loss: 1.047111391901248 	 Accuracy: 0.5806451612903226
Delta: 0.007520219352111435 	  Loss: 1.0469124842480022 	 Accuracy: 0.5806451612903226
Delta: 0.008807202840365009 	  Loss: 1.0466692214829618 	 Accuracy: 0.5806451612903226
Delta: 0.00910673464483701 	  Loss: 1.0462654938281504 	 Accuracy: 0.5806451612903226
Delta: 0.008357884585117784 	  Loss: 1.0458990395643675 	 Accuracy: 0.5806451612903226
Delta: 0.009211996464406486 	  Loss: 1.0456603165763074 	 Accuracy: 0.5806451612903226
Delta: 0.007219318063332307 	  Loss: 1.0453741330091617 	 Accuracy: 0.5806451612903226
Delta: 0.005839546051207296 	  Loss: 1.0452721546202954 	 Accuracy: 0.5806451612903226
Delta: 0.00467133292423374 	  Loss: 1.0452201826079754 	 Accuracy: 0.5806451612903226
Delta: 0.003758372665614523 	  Loss: 1.0452157408197924 	 Accuracy: 0.5806451612903226
Delta: 0.003635715465217731 	  Loss: 1.0451947741745518 	 Accuracy: 0.5806451612903226
Delta: 0.0025400144161417055 	  Loss: 1.0452004524873308 	 Accuracy: 0.5806451612903226
Delta: 0.003238812822589013 	  Loss: 1.045198693685168 	 Accuracy: 0.5806451612903226
Delta: 0.002881679781645483 	  Loss: 1.045165679385256 	 Accuracy: 0.5806451612903226
Delta: 0.0029924472896034875 	  Loss: 1.0451190698670738 	 Accuracy: 0.5806451612903226
Delta: 0.002308958763023496 	  Loss: 1.0450679517131 	 Accuracy: 0.5806451612903226
Delta: 0.0023812063141530827 	  Loss: 1.0450282266004627 	 Accuracy: 0.5806451612903226
Delta: 0.0023458395633865754 	  Loss: 1.0450116611695306 	 Accuracy: 0.5806451612903226
Delta: 0.002196144478296247 	  Loss: 1.0449879087024168 	 Accuracy: 0.5806451612903226
Delta: 0.0018893981626215773 	  Loss: 1.0449442253712782 	 Accuracy: 0.5806451612903226
Delta: 0.002279479700688046 	  Loss: 1.0449050692271311 	 Accuracy: 0.5806451612903226
Delta: 0.002445631148362132 	  Loss: 1.0448693852483704 	 Accuracy: 0.5806451612903226
Delta: 0.002768571127004725 	  Loss: 1.044846043363938 	 Accuracy: 0.5806451612903226
Delta: 0.0023410092563634884 	  Loss: 1.0448265808638593 	 Accuracy: 0.5806451612903226
Delta: 0.0019147307075966472 	  Loss: 1.0448139854094456 	 Accuracy: 0.5806451612903226
Delta: 0.0012671804698908607 	  Loss: 1.0448075194118296 	 Accuracy: 0.5806451612903226
Delta: 0.001166431952645325 	  Loss: 1.0448115909476252 	 Accuracy: 0.5806451612903226
Delta: 0.0014746399785792298 	  Loss: 1.0448047699781438 	 Accuracy: 0.5806451612903226
Delta: 0.001342158005992215 	  Loss: 1.0447982936707447 	 Accuracy: 0.5806451612903226
Delta: 0.0010846773144540553 	  Loss: 1.044795608439523 	 Accuracy: 0.5806451612903226
Delta: 0.0012547960227332307 	  Loss: 1.044791591147512 	 Accuracy: 0.5806451612903226
Delta: 0.0010624562878295677 	  Loss: 1.0447968782131674 	 Accuracy: 0.5806451612903226
Delta: 0.0015056233584599956 	  Loss: 1.0447900024095906 	 Accuracy: 0.5806451612903226
Delta: 0.001306379499817269 	  Loss: 1.0447790318517547 	 Accuracy: 0.5806451612903226
Delta: 0.0011792578898523957 	  Loss: 1.0447681750990112 	 Accuracy: 0.5806451612903226
Delta: 0.0006564795157305447 	  Loss: 1.0447653925103624 	 Accuracy: 0.5806451612903226
Delta: 0.0005132262754346756 	  Loss: 1.0447563166201712 	 Accuracy: 0.5806451612903226
Delta: 0.0004944302686532391 	  Loss: 1.0447505331301699 	 Accuracy: 0.5806451612903226
Delta: 0.0004660943839223837 	  Loss: 1.0447541343226523 	 Accuracy: 0.5806451612903226
Delta: 0.00019230558205417296 	  Loss: 1.0447570785493485 	 Accuracy: 0.5806451612903226
Delta: 0.0003535904531298841 	  Loss: 1.0447567949906529 	 Accuracy: 0.5806451612903226
Delta: 0.00044095314791782616 	  Loss: 1.0447547098237489 	 Accuracy: 0.5806451612903226
Delta: 0.0004589647575820623 	  Loss: 1.0447544156153032 	 Accuracy: 0.5806451612903226
Delta: 0.00015112926978795184 	  Loss: 1.0447551297208024 	 Accuracy: 0.5806451612903226
Delta: 0.00010022577933114226 	  Loss: 1.0447551253485599 	 Accuracy: 0.5806451612903226
converged at iter  56
Delta: 0.05637945010091333 	  Loss: 1.0646438750323548 	 Accuracy: 0.5
Delta: 0.04964006653702867 	  Loss: 1.0610282383772338 	 Accuracy: 0.3548387096774194
Delta: 0.03199121451264311 	  Loss: 1.053184896388585 	 Accuracy: 0.3387096774193548

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028156838727005418 	  Loss: 1.0487681706903063 	 Accuracy: 0.3387096774193548
Delta: 0.016647096042758176 	  Loss: 1.0457156175544713 	 Accuracy: 0.3387096774193548
Delta: 0.012598523802533174 	  Loss: 1.0448358568443337 	 Accuracy: 0.3387096774193548
Delta: 0.009778016553050163 	  Loss: 1.0442581930100863 	 Accuracy: 0.3387096774193548
Delta: 0.008950972550467163 	  Loss: 1.0439776122321747 	 Accuracy: 0.3387096774193548
Delta: 0.008017909663677708 	  Loss: 1.0436814810800397 	 Accuracy: 0.3387096774193548
Delta: 0.007468883483132365 	  Loss: 1.0434300321224463 	 Accuracy: 0.3387096774193548
Delta: 0.00712665700223499 	  Loss: 1.0431489088135977 	 Accuracy: 0.3387096774193548
Delta: 0.007277308824205732 	  Loss: 1.0428671035707633 	 Accuracy: 0.3387096774193548
Delta: 0.006396110056322164 	  Loss: 1.0425796207959555 	 Accuracy: 0.3387096774193548
Delta: 0.006349651193645857 	  Loss: 1.04237731772182 	 Accuracy: 0.3387096774193548
Delta: 0.005812931878872755 	  Loss: 1.0421301779904835 	 Accuracy: 0.3387096774193548
Delta: 0.004947159578975604 	  Loss: 1.0419876184874282 	 Accuracy: 0.3387096774193548
Delta: 0.004022905732591852 	  Loss: 1.0418737118791723 	 Accuracy: 0.3387096774193548
Delta: 0.0035054130771762903 	  Loss: 1.041775809504065 	 Accuracy: 0.3387096774193548
Delta: 0.0036830987083331683 	  Loss: 1.0417153581598007 	 Accuracy: 0.3387096774193548
Delta: 0.0028016193479231083 	  Loss: 1.041637897981977 	 Accuracy: 0.3387096774193548
Delta: 0.002914363115356108 	  Loss: 1.0415802448742544 	 Accuracy: 0.3387096774193548
Delta: 0.002546728132385062 	  Loss: 1.0415020036422153 	 Accuracy: 0.3387096774193548
Delta: 0.0021028647984644615 	  Loss: 1.0414849087661788 	 Accuracy: 0.3387096774193548
Delta: 0.001257390287191057 	  Loss: 1.0414758044743015 	 Accuracy: 0.3387096774193548
Delta: 0.0010177191337336691 	  Loss: 1.041471817879719 	 Accuracy: 0.3387096774193548
Delta: 0.0010556769810612608 	  Loss: 1.0414741177846647 	 Accuracy: 0.3387096774193548
Delta: 0.000766394808873903 	  Loss: 1.0414763089563763 	 Accuracy: 0.3387096774193548
Delta: 0.0011665781716494563 	  Loss: 1.0414702077958684 	 Accuracy: 0.3387096774193548
Delta: 0.001569887060558803 	  Loss: 1.041462568772034 	 Accuracy: 0.3387096774193548
Delta: 0.0009961821749308072 	  Loss: 1.0414622659618307 	 Accuracy: 0.3387096774193548
Delta: 0.0013498025166973004 	  Loss: 1.0414497227331876 	 Accuracy: 0.3387096774193548
Delta: 0.0016200610867364588 	  Loss: 1.0414318414463581 	 Accuracy: 0.3387096774193548
Delta: 0.0027687839548448966 	  Loss: 1.041398308081034 	 Accuracy: 0.3387096774193548
Delta: 0.0014298331861311868 	  Loss: 1.041342424286735 	 Accuracy: 0.3387096774193548
Delta: 0.0018542484440296208 	  Loss: 1.0413224369914356 	 Accuracy: 0.3387096774193548
Delta: 0.0012990929387747823 	  Loss: 1.0412940589826614 	 Accuracy: 0.3387096774193548
Delta: 0.0013428113116096786 	  Loss: 1.0412729088687056 	 Accuracy: 0.3387096774193548
Delta: 0.0018732173204034635 	  Loss: 1.0412536583130503 	 Accuracy: 0.3387096774193548
Delta: 0.001918366009058918 	  Loss: 1.041214121145037 	 Accuracy: 0.3387096774193548
Delta: 0.0013345166172918346 	  Loss: 1.0411822840703815 	 Accuracy: 0.3387096774193548
Delta: 0.0012003593197670343 	  Loss: 1.0411718637264356 	 Accuracy: 0.3387096774193548
Delta: 0.0009537993611079023 	  Loss: 1.0411585761135278 	 Accuracy: 0.3387096774193548
Delta: 0.0010766377944435312 	  Loss: 1.0411486253445248 	 Accuracy: 0.3387096774193548
Delta: 0.0008379319932050458 	  Loss: 1.0411392638999462 	 Accuracy: 0.3387096774193548
Delta: 0.001143271645875974 	  Loss: 1.0411444184299214 	 Accuracy: 0.3387096774193548
Delta: 0.0005514961602624696 	  Loss: 1.0411429665331875 	 Accuracy: 0.3387096774193548
Delta: 0.0007754602757290529 	  Loss: 1.0411401339251294 	 Accuracy: 0.3387096774193548
Delta: 0.001172649791044695 	  Loss: 1.0411388313161165 	 Accuracy: 0.3387096774193548
Delta: 0.001448203742016659 	  Loss: 1.041141040349616 	 Accuracy: 0.3387096774193548
Delta: 0.0013325887462420373 	  Loss: 1.0411320670135191 	 Accuracy: 0.3387096774193548
Delta: 0.0008420376243573387 	  Loss: 1.041127621187885 	 Accuracy: 0.3387096774193548
Delta: 0.0006338943619521546 	  Loss: 1.041125244561672 	 Accuracy: 0.3387096774193548
Delta: 0.0001681742199910249 	  Loss: 1.0411241461789091 	 Accuracy: 0.3387096774193548
Delta: 1.040556887023217e-05 	  Loss: 1.0411225764201655 	 Accuracy: 0.3387096774193548
Delta: 3.370639436633164e-17 	  Loss: 1.0411225764201655 	 Accuracy: 0.3387096774193548
converged at iter  54
Delta: 0.05495666988028729 	  Loss: 1.076059578238285 	 Accuracy: 0.3709677419354839
Delta: 0.048405571215832166 	  Loss: 1.065387894473108 	 Accuracy: 0.25806451612903225
Delta: 0.03449875983768047 	  Loss: 1.0583783069167834 	 Accuracy: 0.14516129032258066
Delta: 0.02247904890698435 	  Loss: 1.0551957295786372 	 Accuracy: 0.14516129032258066

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02078629416021226 	  Loss: 1.0536996947853052 	 Accuracy: 0.14516129032258066
Delta: 0.014050795456066292 	  Loss: 1.0526219712646883 	 Accuracy: 0.14516129032258066
Delta: 0.011686732029276174 	  Loss: 1.051994106917859 	 Accuracy: 0.14516129032258066
Delta: 0.00997154533674039 	  Loss: 1.0515408724419855 	 Accuracy: 0.14516129032258066
Delta: 0.008642806816379715 	  Loss: 1.0511030706786633 	 Accuracy: 0.14516129032258066
Delta: 0.007650242369234565 	  Loss: 1.0507825035970801 	 Accuracy: 0.14516129032258066
Delta: 0.006701380992412264 	  Loss: 1.0505798963262927 	 Accuracy: 0.14516129032258066
Delta: 0.006188490082772129 	  Loss: 1.0503596256816183 	 Accuracy: 0.14516129032258066
Delta: 0.006256405560094525 	  Loss: 1.0502129530125073 	 Accuracy: 0.14516129032258066
Delta: 0.0056994568597562795 	  Loss: 1.0500220936025786 	 Accuracy: 0.14516129032258066
Delta: 0.005379187554736386 	  Loss: 1.0498706747926687 	 Accuracy: 0.14516129032258066
Delta: 0.0048705402484127535 	  Loss: 1.0497483958965637 	 Accuracy: 0.14516129032258066
Delta: 0.00491224265026542 	  Loss: 1.0496337025380233 	 Accuracy: 0.14516129032258066
Delta: 0.004887063838315248 	  Loss: 1.049555786248591 	 Accuracy: 0.14516129032258066
Delta: 0.006177178453750953 	  Loss: 1.0494284573644965 	 Accuracy: 0.14516129032258066
Delta: 0.006255374443236945 	  Loss: 1.0493032401737712 	 Accuracy: 0.14516129032258066
Delta: 0.005361081130856192 	  Loss: 1.049055637370655 	 Accuracy: 0.14516129032258066
Delta: 0.0058886897023983815 	  Loss: 1.0489257538379646 	 Accuracy: 0.14516129032258066
Delta: 0.005919272283147462 	  Loss: 1.0488308011777776 	 Accuracy: 0.14516129032258066
Delta: 0.005669317322079189 	  Loss: 1.048662988914649 	 Accuracy: 0.14516129032258066
Delta: 0.005421186380062279 	  Loss: 1.0485091491794032 	 Accuracy: 0.14516129032258066
Delta: 0.004631951942547611 	  Loss: 1.0484122172405062 	 Accuracy: 0.14516129032258066
Delta: 0.004424663603270586 	  Loss: 1.0482906296841352 	 Accuracy: 0.14516129032258066
Delta: 0.003087023036891406 	  Loss: 1.0482438353748984 	 Accuracy: 0.14516129032258066
Delta: 0.0034514917679693874 	  Loss: 1.0482371915443167 	 Accuracy: 0.14516129032258066
Delta: 0.003208249843608606 	  Loss: 1.048223547064411 	 Accuracy: 0.14516129032258066
Delta: 0.002387072420540874 	  Loss: 1.0481995277904748 	 Accuracy: 0.14516129032258066
Delta: 0.0021546047218244315 	  Loss: 1.0481717944887794 	 Accuracy: 0.14516129032258066
Delta: 0.0023680800669429697 	  Loss: 1.0481214613361394 	 Accuracy: 0.14516129032258066
Delta: 0.002080750785402099 	  Loss: 1.0480775297324252 	 Accuracy: 0.14516129032258066
Delta: 0.0020943602798545896 	  Loss: 1.0480521598896755 	 Accuracy: 0.14516129032258066
Delta: 0.0023440255518576386 	  Loss: 1.0480527145434477 	 Accuracy: 0.14516129032258066
Delta: 0.002778930283647599 	  Loss: 1.0480170857692697 	 Accuracy: 0.14516129032258066
Delta: 0.0011934833394025477 	  Loss: 1.048002585879443 	 Accuracy: 0.14516129032258066
Delta: 0.0009895422842187743 	  Loss: 1.0479993628604518 	 Accuracy: 0.14516129032258066
Delta: 0.0013311218193289636 	  Loss: 1.048003443759073 	 Accuracy: 0.14516129032258066
Delta: 0.0010584790781956292 	  Loss: 1.0479976360834669 	 Accuracy: 0.14516129032258066
Delta: 0.0006940441099999825 	  Loss: 1.0479896455105375 	 Accuracy: 0.14516129032258066
Delta: 0.0013359704725840788 	  Loss: 1.0479824694102855 	 Accuracy: 0.14516129032258066
Delta: 0.0012982229351540375 	  Loss: 1.0479667996882864 	 Accuracy: 0.14516129032258066
Delta: 0.0008800375083358202 	  Loss: 1.0479642881710718 	 Accuracy: 0.14516129032258066
Delta: 0.0004691696076393056 	  Loss: 1.047959126396019 	 Accuracy: 0.14516129032258066
Delta: 0.00032292830366809614 	  Loss: 1.047959403436389 	 Accuracy: 0.14516129032258066
Delta: 0.0010141065944050984 	  Loss: 1.0479624349204988 	 Accuracy: 0.14516129032258066
Delta: 0.00043679050449383467 	  Loss: 1.047968234635325 	 Accuracy: 0.14516129032258066
Delta: 0.0002677296025446674 	  Loss: 1.04796936207916 	 Accuracy: 0.14516129032258066
Delta: 0.00039079962768521944 	  Loss: 1.0479684370642537 	 Accuracy: 0.14516129032258066
Delta: 0.0012922511322685786 	  Loss: 1.0479673358503159 	 Accuracy: 0.14516129032258066
Delta: 0.0006515401130311918 	  Loss: 1.047957282559449 	 Accuracy: 0.14516129032258066
Delta: 0.0007095962862161686 	  Loss: 1.0479596203568193 	 Accuracy: 0.14516129032258066
Delta: 0.0007092674269611799 	  Loss: 1.0479671414411194 	 Accuracy: 0.14516129032258066
Delta: 0.0006369898528004172 	  Loss: 1.047972531676293 	 Accuracy: 0.14516129032258066
Delta: 0.0005090986101834882 	  Loss: 1.0479801591068805 	 Accuracy: 0.14516129032258066
Delta: 0.0004996643365175423 	  Loss: 1.0479836940955218 	 Accuracy: 0.14516129032258066
Delta: 0.0017965473670418174 	  Loss: 1.047990846088425 	 Accuracy: 0.14516129032258066
Delta: 0.0016590593530347068 	  Loss: 1.0479872205882559 	 Accuracy: 0.14516129032258066
Delta: 0.0010346449611777552 	  Loss: 1.0479849699680845 	 Accuracy: 0.14516129032258066
Delta: 0.0008773182481430118 	  Loss: 1.0479829181338884 	 Accuracy: 0.14516129032258066
Delta: 0.000380323730967867 	  Loss: 1.0479829755932586 	 Accuracy: 0.14516129032258066
converged at iter  62
Delta: 0.05924568440019096 	  Loss: 1.0726449274721035 	 Accuracy: 0.2222222222222222
Delta: 0.038701556820035225 	  Loss: 1.061612657295424 	 Accuracy: 0.1746031746031746
Delta: 0.026183058679254426 	  Loss: 1.056047157711466 	 Accuracy: 0.19047619047619047
Delta: 0.021402261347656323 	  Loss: 1.0536854845750805 	 Accuracy: 0.20634920634920634

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.018802276540336567 	  Loss: 1.051902090867606 	 Accuracy: 0.20634920634920634
Delta: 0.012625225011171215 	  Loss: 1.0511312374338904 	 Accuracy: 0.20634920634920634
Delta: 0.009642822810772361 	  Loss: 1.0505829718257162 	 Accuracy: 0.20634920634920634
Delta: 0.007671566777490537 	  Loss: 1.0501964562420962 	 Accuracy: 0.20634920634920634
Delta: 0.007120239160679303 	  Loss: 1.0499036157076098 	 Accuracy: 0.20634920634920634
Delta: 0.005959253498295117 	  Loss: 1.0496918239820596 	 Accuracy: 0.20634920634920634
Delta: 0.007536797576419717 	  Loss: 1.0495019451526768 	 Accuracy: 0.20634920634920634
Delta: 0.007473840624381434 	  Loss: 1.0492100846839119 	 Accuracy: 0.20634920634920634
Delta: 0.007138851271476657 	  Loss: 1.0489020013202652 	 Accuracy: 0.20634920634920634
Delta: 0.006327437465935283 	  Loss: 1.048596379765789 	 Accuracy: 0.20634920634920634
Delta: 0.006333317482442622 	  Loss: 1.048370946753356 	 Accuracy: 0.20634920634920634
Delta: 0.005276350004372343 	  Loss: 1.048204584524477 	 Accuracy: 0.20634920634920634
Delta: 0.004388287270536445 	  Loss: 1.0480841211563674 	 Accuracy: 0.20634920634920634
Delta: 0.0035730940747936393 	  Loss: 1.048001941436858 	 Accuracy: 0.20634920634920634
Delta: 0.0035282707731691195 	  Loss: 1.04794252257944 	 Accuracy: 0.20634920634920634
Delta: 0.0034642353272458094 	  Loss: 1.0478997994920851 	 Accuracy: 0.20634920634920634
Delta: 0.002359658358570371 	  Loss: 1.0478817785884451 	 Accuracy: 0.20634920634920634
Delta: 0.002283526502280156 	  Loss: 1.0478506965029357 	 Accuracy: 0.20634920634920634
Delta: 0.002398275645992378 	  Loss: 1.047837248743042 	 Accuracy: 0.20634920634920634
Delta: 0.0030158259615861065 	  Loss: 1.0478283208930068 	 Accuracy: 0.20634920634920634
Delta: 0.0031232173187985884 	  Loss: 1.0477903928502963 	 Accuracy: 0.20634920634920634
Delta: 0.0031365021204082795 	  Loss: 1.0477233627512919 	 Accuracy: 0.20634920634920634
Delta: 0.0034441870793537597 	  Loss: 1.0476846023389315 	 Accuracy: 0.20634920634920634
Delta: 0.0025073848196606025 	  Loss: 1.0476498065847282 	 Accuracy: 0.20634920634920634
Delta: 0.002601821039842933 	  Loss: 1.0476270646276702 	 Accuracy: 0.20634920634920634
Delta: 0.002925161712985727 	  Loss: 1.0476101493078696 	 Accuracy: 0.20634920634920634
Delta: 0.0031460738781440263 	  Loss: 1.0475848242901915 	 Accuracy: 0.20634920634920634
Delta: 0.00377162467748113 	  Loss: 1.0475492915976918 	 Accuracy: 0.20634920634920634
Delta: 0.002349707005119732 	  Loss: 1.0475271175074026 	 Accuracy: 0.20634920634920634
Delta: 0.0019137555737546988 	  Loss: 1.0475159856398406 	 Accuracy: 0.20634920634920634
Delta: 0.001843562795352823 	  Loss: 1.0475169879709485 	 Accuracy: 0.20634920634920634
Delta: 0.0014134953441199709 	  Loss: 1.0475009005712919 	 Accuracy: 0.20634920634920634
Delta: 0.0011299134638265568 	  Loss: 1.0475001524792118 	 Accuracy: 0.20634920634920634
Delta: 0.0004946752229992759 	  Loss: 1.0475000372725731 	 Accuracy: 0.20634920634920634
Delta: 0.0003334242876615203 	  Loss: 1.0474997407259845 	 Accuracy: 0.20634920634920634
Delta: 0.0004381360287346087 	  Loss: 1.0474989962726222 	 Accuracy: 0.20634920634920634
Delta: 0.0005723099767071724 	  Loss: 1.0474963545742577 	 Accuracy: 0.20634920634920634
Delta: 0.001097951414004793 	  Loss: 1.0474920763674753 	 Accuracy: 0.20634920634920634
Delta: 0.0011497745203608667 	  Loss: 1.0474777800946782 	 Accuracy: 0.20634920634920634
Delta: 0.0007407145496424271 	  Loss: 1.0474690864324974 	 Accuracy: 0.20634920634920634
Delta: 0.000564089717317714 	  Loss: 1.047466257250766 	 Accuracy: 0.20634920634920634
Delta: 0.0005440075540714849 	  Loss: 1.047464388943332 	 Accuracy: 0.20634920634920634
Delta: 0.0006540013554919468 	  Loss: 1.0474624192284618 	 Accuracy: 0.20634920634920634
Delta: 0.0003461241563225799 	  Loss: 1.0474530309419594 	 Accuracy: 0.20634920634920634
Delta: 0.00035768857773413093 	  Loss: 1.047447165335628 	 Accuracy: 0.20634920634920634
Delta: 0.0001913379272048543 	  Loss: 1.047446462927 	 Accuracy: 0.20634920634920634
Delta: 0.0013345264360912115 	  Loss: 1.0474453595189623 	 Accuracy: 0.20634920634920634
Delta: 0.000813622162667828 	  Loss: 1.0474296618067096 	 Accuracy: 0.20634920634920634
Delta: 0.0006103402601510539 	  Loss: 1.0474275678083194 	 Accuracy: 0.20634920634920634
Delta: 0.000387115541636894 	  Loss: 1.047431749723033 	 Accuracy: 0.20634920634920634
Delta: 0.00027517739131804094 	  Loss: 1.04743361478771 	 Accuracy: 0.20634920634920634
Delta: 0.000591366068686907 	  Loss: 1.0474346674774102 	 Accuracy: 0.20634920634920634
Delta: 0.0006328000861717766 	  Loss: 1.047438934761721 	 Accuracy: 0.20634920634920634
Delta: 0.0006577137024565303 	  Loss: 1.047437597599785 	 Accuracy: 0.20634920634920634
Delta: 0.0005234301856877918 	  Loss: 1.047435757580684 	 Accuracy: 0.20634920634920634
Delta: 0.000346739269530591 	  Loss: 1.047430707761793 	 Accuracy: 0.20634920634920634
Delta: 0.00011901496960135456 	  Loss: 1.0474305317808228 	 Accuracy: 0.20634920634920634
Delta: 9.214827884980493e-05 	  Loss: 1.0474312209509096 	 Accuracy: 0.20634920634920634
Delta: 0.00026306241755763777 	  Loss: 1.0474308304042546 	 Accuracy: 0.20634920634920634
Delta: 0.00012455143906340063 	  Loss: 1.0474312234894756 	 Accuracy: 0.20634920634920634
Delta: 0.00025692183727848056 	  Loss: 1.0474306629024177 	 Accuracy: 0.20634920634920634
Delta: 0.00020109932425947481 	  Loss: 1.047431601444214 	 Accuracy: 0.20634920634920634
Delta: 0.00011099398012077446 	  Loss: 1.047433892218234 	 Accuracy: 0.20634920634920634
Delta: 9.446899134550451e-05 	  Loss: 1.04743444836837 	 Accuracy: 0.20634920634920634
Delta: 6.11269025124956e-05 	  Loss: 1.0474345659902502 	 Accuracy: 0.20634920634920634
Delta: 5.042469416039002e-05 	  Loss: 1.0474346453982115 	 Accuracy: 0.20634920634920634
converged at iter  69
Delta: 0.0579845626858516 	  Loss: 1.05955173286825 	 Accuracy: 0.23809523809523808
Delta: 0.043742602059318667 	  Loss: 1.0487145401575788 	 Accuracy: 0.2222222222222222
Delta: 0.029962721576387498 	  Loss: 1.043386542307016 	 Accuracy: 0.2222222222222222
Delta: 0.027652852905856812 	  Loss: 1.0409111061360097 	 Accuracy: 0.25396825396825395

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01751591795461503 	  Loss: 1.0389393338886654 	 Accuracy: 0.25396825396825395
Delta: 0.01169470176487341 	  Loss: 1.0381926402711072 	 Accuracy: 0.25396825396825395
Delta: 0.009639182955671267 	  Loss: 1.037715831175325 	 Accuracy: 0.25396825396825395
Delta: 0.008149758649031252 	  Loss: 1.0374276701489182 	 Accuracy: 0.25396825396825395
Delta: 0.006812559186901523 	  Loss: 1.0371528271808512 	 Accuracy: 0.25396825396825395
Delta: 0.0059798768431624065 	  Loss: 1.0370065235205712 	 Accuracy: 0.25396825396825395
Delta: 0.004921266729670195 	  Loss: 1.0369186173994125 	 Accuracy: 0.25396825396825395
Delta: 0.004283685092723734 	  Loss: 1.0368592880534773 	 Accuracy: 0.25396825396825395
Delta: 0.004939315483081517 	  Loss: 1.0367917732049277 	 Accuracy: 0.25396825396825395
Delta: 0.005106676753163263 	  Loss: 1.0366730682150962 	 Accuracy: 0.25396825396825395
Delta: 0.006097545082347766 	  Loss: 1.0365697236884288 	 Accuracy: 0.25396825396825395
Delta: 0.00653619731243767 	  Loss: 1.0364482922325329 	 Accuracy: 0.25396825396825395
Delta: 0.006360532012021273 	  Loss: 1.0363455003611062 	 Accuracy: 0.25396825396825395
Delta: 0.007274487960677381 	  Loss: 1.0361449806424594 	 Accuracy: 0.25396825396825395
Delta: 0.008336713706501311 	  Loss: 1.0358384726247243 	 Accuracy: 0.25396825396825395
Delta: 0.007451861188142253 	  Loss: 1.035416567030922 	 Accuracy: 0.25396825396825395
Delta: 0.006043531933073626 	  Loss: 1.0351725738711748 	 Accuracy: 0.25396825396825395
Delta: 0.00555286058615287 	  Loss: 1.0350457352870905 	 Accuracy: 0.25396825396825395
Delta: 0.005784284526547922 	  Loss: 1.0349644170126853 	 Accuracy: 0.25396825396825395
Delta: 0.004619784991015617 	  Loss: 1.034863395177612 	 Accuracy: 0.25396825396825395
Delta: 0.004267748601729536 	  Loss: 1.0347624380383098 	 Accuracy: 0.25396825396825395
Delta: 0.0045289047481895965 	  Loss: 1.0346659359660053 	 Accuracy: 0.25396825396825395
Delta: 0.004426807138024097 	  Loss: 1.0345817738238192 	 Accuracy: 0.25396825396825395
Delta: 0.005277024168049561 	  Loss: 1.03444841025154 	 Accuracy: 0.25396825396825395
Delta: 0.0052267941738422564 	  Loss: 1.0342971422766514 	 Accuracy: 0.25396825396825395
Delta: 0.006164975775023142 	  Loss: 1.0341061118480595 	 Accuracy: 0.25396825396825395
Delta: 0.005139026295499646 	  Loss: 1.0339513998104108 	 Accuracy: 0.25396825396825395
Delta: 0.004750054441165009 	  Loss: 1.033854736975678 	 Accuracy: 0.25396825396825395
Delta: 0.003962979460424612 	  Loss: 1.033771602960936 	 Accuracy: 0.25396825396825395
Delta: 0.003339610585183894 	  Loss: 1.033714071653169 	 Accuracy: 0.25396825396825395
Delta: 0.0029224120997554544 	  Loss: 1.0336723693658783 	 Accuracy: 0.25396825396825395
Delta: 0.003094565679788224 	  Loss: 1.0336374143707174 	 Accuracy: 0.25396825396825395
Delta: 0.0028548434833951183 	  Loss: 1.0336233159360284 	 Accuracy: 0.25396825396825395
Delta: 0.0028769891239202963 	  Loss: 1.0336077967819095 	 Accuracy: 0.25396825396825395
Delta: 0.003167831345501816 	  Loss: 1.0335901408833323 	 Accuracy: 0.25396825396825395
Delta: 0.0023692201349272274 	  Loss: 1.0335738864898847 	 Accuracy: 0.25396825396825395
Delta: 0.002222282540669923 	  Loss: 1.0335494349642675 	 Accuracy: 0.25396825396825395
Delta: 0.0036740017988711403 	  Loss: 1.0335235048941414 	 Accuracy: 0.25396825396825395
Delta: 0.002706834434124109 	  Loss: 1.0334844531479397 	 Accuracy: 0.25396825396825395
Delta: 0.0028870940555520037 	  Loss: 1.0334546599234176 	 Accuracy: 0.25396825396825395
Delta: 0.0026820408917174535 	  Loss: 1.033433722268624 	 Accuracy: 0.25396825396825395
Delta: 0.0019744149168919706 	  Loss: 1.0334204451458266 	 Accuracy: 0.25396825396825395
Delta: 0.001530547621067547 	  Loss: 1.0334199696200792 	 Accuracy: 0.25396825396825395
Delta: 0.001958766760214339 	  Loss: 1.033402637979898 	 Accuracy: 0.25396825396825395
Delta: 0.0022080109363103867 	  Loss: 1.0333803331503282 	 Accuracy: 0.25396825396825395
Delta: 0.0018860451165115203 	  Loss: 1.0333632229810115 	 Accuracy: 0.25396825396825395
Delta: 0.0010608888262321526 	  Loss: 1.0333375090829913 	 Accuracy: 0.25396825396825395
Delta: 0.0013302856832840323 	  Loss: 1.0333199485527644 	 Accuracy: 0.25396825396825395
Delta: 0.0015268078579730783 	  Loss: 1.033292672482697 	 Accuracy: 0.25396825396825395
Delta: 0.0018101073023276614 	  Loss: 1.0332837539179087 	 Accuracy: 0.25396825396825395
Delta: 0.0015026869756106435 	  Loss: 1.0332674348490505 	 Accuracy: 0.25396825396825395
Delta: 0.0016808317951495153 	  Loss: 1.0332527162138554 	 Accuracy: 0.25396825396825395
Delta: 0.0018337471229501968 	  Loss: 1.0332585952148239 	 Accuracy: 0.25396825396825395
Delta: 0.0022596584629053927 	  Loss: 1.0332222318373352 	 Accuracy: 0.25396825396825395
Delta: 0.0020883925962396086 	  Loss: 1.0331807538851394 	 Accuracy: 0.25396825396825395
Delta: 0.0017791601641081148 	  Loss: 1.0331552619196218 	 Accuracy: 0.25396825396825395
Delta: 0.0019380971177981857 	  Loss: 1.0331501945080324 	 Accuracy: 0.25396825396825395
Delta: 0.0014996410902159733 	  Loss: 1.033133006419229 	 Accuracy: 0.25396825396825395
Delta: 0.0020061403685497805 	  Loss: 1.0331182326088344 	 Accuracy: 0.25396825396825395
Delta: 0.0016616451664185146 	  Loss: 1.0331094430208454 	 Accuracy: 0.25396825396825395
Delta: 0.0019154953872272322 	  Loss: 1.0331127164623832 	 Accuracy: 0.25396825396825395
Delta: 0.0014850671082935437 	  Loss: 1.0331069790668654 	 Accuracy: 0.25396825396825395
Delta: 0.0012001518096937025 	  Loss: 1.0330943693240553 	 Accuracy: 0.25396825396825395
Delta: 0.0009863327670073783 	  Loss: 1.0330868508301592 	 Accuracy: 0.25396825396825395
Delta: 0.0008995646848667803 	  Loss: 1.0330810244830646 	 Accuracy: 0.25396825396825395
Delta: 0.0018896478099668327 	  Loss: 1.0330824799961111 	 Accuracy: 0.25396825396825395
Delta: 0.002091745568058048 	  Loss: 1.0330778747312528 	 Accuracy: 0.25396825396825395
Delta: 0.0018341955908290834 	  Loss: 1.0330695113731039 	 Accuracy: 0.25396825396825395
Delta: 0.0018871957668135052 	  Loss: 1.0330750630955086 	 Accuracy: 0.25396825396825395
Delta: 0.0015083671598391884 	  Loss: 1.0330913891772489 	 Accuracy: 0.25396825396825395
Delta: 0.0016045104546794735 	  Loss: 1.0330921176125454 	 Accuracy: 0.25396825396825395
Delta: 0.0014972864963590643 	  Loss: 1.033103862716412 	 Accuracy: 0.25396825396825395
Delta: 0.001427254472041935 	  Loss: 1.0331047574711196 	 Accuracy: 0.25396825396825395
Delta: 0.0012541725939448967 	  Loss: 1.033084174849329 	 Accuracy: 0.25396825396825395
Delta: 0.0013614147828038933 	  Loss: 1.0330746954227568 	 Accuracy: 0.25396825396825395
Delta: 0.001790227573953556 	  Loss: 1.0330742655980272 	 Accuracy: 0.25396825396825395
Delta: 0.0015886606094530171 	  Loss: 1.0330615966735692 	 Accuracy: 0.25396825396825395
Delta: 0.0017373954917469603 	  Loss: 1.0330555123291976 	 Accuracy: 0.25396825396825395
Delta: 0.001875765239348542 	  Loss: 1.0330312259481893 	 Accuracy: 0.25396825396825395
Delta: 0.0024172837662960146 	  Loss: 1.0330149081934321 	 Accuracy: 0.25396825396825395
Delta: 0.001620436627968415 	  Loss: 1.0329878874075469 	 Accuracy: 0.25396825396825395
Delta: 0.0013397055592591599 	  Loss: 1.0329713030534868 	 Accuracy: 0.25396825396825395
Delta: 0.001208912729151147 	  Loss: 1.0329722171765525 	 Accuracy: 0.25396825396825395
Delta: 0.0015196918547265273 	  Loss: 1.032966584967963 	 Accuracy: 0.25396825396825395
Delta: 0.0017689486905844082 	  Loss: 1.0329731842054948 	 Accuracy: 0.25396825396825395
Delta: 0.0018494393992021685 	  Loss: 1.0329770776971876 	 Accuracy: 0.25396825396825395
Delta: 0.0021406752029854495 	  Loss: 1.032967853357001 	 Accuracy: 0.25396825396825395
Delta: 0.0014734144453123624 	  Loss: 1.0329568416495576 	 Accuracy: 0.25396825396825395
Delta: 0.0020559660399292806 	  Loss: 1.032949979688338 	 Accuracy: 0.25396825396825395
Delta: 0.0035225889042536825 	  Loss: 1.0329498442780607 	 Accuracy: 0.25396825396825395
Delta: 0.0024263022101270928 	  Loss: 1.0329080422176218 	 Accuracy: 0.25396825396825395
Delta: 0.0018962705426601107 	  Loss: 1.032884580826317 	 Accuracy: 0.25396825396825395
Delta: 0.0013700497748361383 	  Loss: 1.0328703204308654 	 Accuracy: 0.25396825396825395
Delta: 0.0013192709829219014 	  Loss: 1.0328705414959503 	 Accuracy: 0.25396825396825395
Delta: 0.002331035684084833 	  Loss: 1.0328644753216245 	 Accuracy: 0.25396825396825395
Delta: 0.0018349073571500485 	  Loss: 1.0328569075158534 	 Accuracy: 0.25396825396825395
Delta: 0.06019923502311586 	  Loss: 1.079318855100163 	 Accuracy: 0.3064516129032258
Delta: 0.040946595137388325 	  Loss: 1.0696287646199678 	 Accuracy: 0.2903225806451613
Delta: 0.03369965652921088 	  Loss: 1.060928690986926 	 Accuracy: 0.25806451612903225
Delta: 0.02502994126572262 	  Loss: 1.0560244932150187 	 Accuracy: 0.25806451612903225
Delta: 0.017665360429324033 	  Loss: 1.0538115339556637 	 Accuracy: 0.25806451612903225
Delta: 0.014933579411487308 	  Loss: 1.0529220638641246 	 Accuracy: 0.24193548387096775

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.014974594130759092 	  Loss: 1.0525744631962761 	 Accuracy: 0.24193548387096775
Delta: 0.010984189288237594 	  Loss: 1.0519888367930645 	 Accuracy: 0.25806451612903225
Delta: 0.007507717680212182 	  Loss: 1.0518378209695893 	 Accuracy: 0.25806451612903225
Delta: 0.004872457709432078 	  Loss: 1.0517465688079983 	 Accuracy: 0.25806451612903225
Delta: 0.0038856237899721935 	  Loss: 1.0516996895750235 	 Accuracy: 0.25806451612903225
Delta: 0.003442177254169603 	  Loss: 1.0516808277485836 	 Accuracy: 0.25806451612903225
Delta: 0.0031592814140693017 	  Loss: 1.0516646544720016 	 Accuracy: 0.25806451612903225
Delta: 0.0036185693235311154 	  Loss: 1.05163826059501 	 Accuracy: 0.25806451612903225
Delta: 0.0033153454871866057 	  Loss: 1.0516247510415513 	 Accuracy: 0.25806451612903225
Delta: 0.0038311985509440812 	  Loss: 1.051579722072007 	 Accuracy: 0.25806451612903225
Delta: 0.002750690456126352 	  Loss: 1.0515452704218538 	 Accuracy: 0.25806451612903225
Delta: 0.0025209423639503646 	  Loss: 1.0515356440966341 	 Accuracy: 0.25806451612903225
Delta: 0.0026617352749326623 	  Loss: 1.0515323027833596 	 Accuracy: 0.25806451612903225
Delta: 0.0026649421942755037 	  Loss: 1.0515325980449912 	 Accuracy: 0.25806451612903225
Delta: 0.001994459710480684 	  Loss: 1.0515195129078192 	 Accuracy: 0.25806451612903225
Delta: 0.0017795840707263508 	  Loss: 1.0515155781555658 	 Accuracy: 0.25806451612903225
Delta: 0.0020917791050203117 	  Loss: 1.051503703756519 	 Accuracy: 0.25806451612903225
Delta: 0.0020917063095975794 	  Loss: 1.0514973700068744 	 Accuracy: 0.25806451612903225
Delta: 0.0018190402673494534 	  Loss: 1.0514813473076852 	 Accuracy: 0.25806451612903225
Delta: 0.0018558272587653132 	  Loss: 1.0514748329978731 	 Accuracy: 0.25806451612903225
Delta: 0.0015081387890158386 	  Loss: 1.051460144785266 	 Accuracy: 0.25806451612903225
Delta: 0.0016167874145321876 	  Loss: 1.051457936498773 	 Accuracy: 0.25806451612903225
Delta: 0.0014926553172778473 	  Loss: 1.051457933690326 	 Accuracy: 0.25806451612903225
converged at iter  28
Delta: 0.06025797446865741 	  Loss: 1.0547561521130562 	 Accuracy: 0.5
Delta: 0.036894719883372076 	  Loss: 1.0437006502879427 	 Accuracy: 0.5483870967741935
Delta: 0.03938597685820096 	  Loss: 1.0436791217374548 	 Accuracy: 0.5806451612903226

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.022137330362203163 	  Loss: 1.03992077551016 	 Accuracy: 0.532258064516129
Delta: 0.014628966537850046 	  Loss: 1.038618009321934 	 Accuracy: 0.532258064516129
Delta: 0.011074146266342065 	  Loss: 1.0378389030213466 	 Accuracy: 0.532258064516129
Delta: 0.008938513335222085 	  Loss: 1.03730976128753 	 Accuracy: 0.532258064516129
Delta: 0.0076423855397982935 	  Loss: 1.0370454699142613 	 Accuracy: 0.532258064516129
Delta: 0.006115879104884984 	  Loss: 1.0368057388987246 	 Accuracy: 0.532258064516129
Delta: 0.007140407429728416 	  Loss: 1.0366296183379364 	 Accuracy: 0.532258064516129
Delta: 0.0062008150568820565 	  Loss: 1.036421866526129 	 Accuracy: 0.532258064516129
Delta: 0.0046836773550686574 	  Loss: 1.0362495333134887 	 Accuracy: 0.532258064516129
Delta: 0.003577133769096333 	  Loss: 1.0361370966007013 	 Accuracy: 0.532258064516129
Delta: 0.0027017101992890895 	  Loss: 1.0360627218403988 	 Accuracy: 0.532258064516129
Delta: 0.0037282933930909406 	  Loss: 1.0360331540607404 	 Accuracy: 0.532258064516129
Delta: 0.004307236431836195 	  Loss: 1.0359666119772868 	 Accuracy: 0.532258064516129
Delta: 0.004987758446610543 	  Loss: 1.0358984806693212 	 Accuracy: 0.532258064516129
Delta: 0.0052295012307435945 	  Loss: 1.035811538838375 	 Accuracy: 0.532258064516129
Delta: 0.005449463156553738 	  Loss: 1.0357122034899127 	 Accuracy: 0.532258064516129
Delta: 0.005522514228933583 	  Loss: 1.035615924214455 	 Accuracy: 0.532258064516129
Delta: 0.006134974757344076 	  Loss: 1.0355133140430337 	 Accuracy: 0.532258064516129
Delta: 0.005083036889404047 	  Loss: 1.035410104374412 	 Accuracy: 0.532258064516129
Delta: 0.005121566479625722 	  Loss: 1.035302313552588 	 Accuracy: 0.532258064516129
Delta: 0.00475592274960487 	  Loss: 1.0351544198309872 	 Accuracy: 0.532258064516129
Delta: 0.0038850039581655674 	  Loss: 1.0350692016577567 	 Accuracy: 0.532258064516129
Delta: 0.004639982033015809 	  Loss: 1.0349727956777561 	 Accuracy: 0.532258064516129
Delta: 0.004438700968217302 	  Loss: 1.034871230864963 	 Accuracy: 0.532258064516129
Delta: 0.003746122947269636 	  Loss: 1.0347994191064112 	 Accuracy: 0.532258064516129
Delta: 0.003578522399945881 	  Loss: 1.0347531399739005 	 Accuracy: 0.532258064516129
Delta: 0.0034863078078042776 	  Loss: 1.0346885927218568 	 Accuracy: 0.532258064516129
Delta: 0.003262343794333741 	  Loss: 1.0346291250993167 	 Accuracy: 0.532258064516129
Delta: 0.003719871518672896 	  Loss: 1.0345787172545464 	 Accuracy: 0.532258064516129
Delta: 0.0033114470390013103 	  Loss: 1.0344890027223919 	 Accuracy: 0.532258064516129
Delta: 0.002491218468770909 	  Loss: 1.0344203870743014 	 Accuracy: 0.532258064516129
Delta: 0.0028517514123091747 	  Loss: 1.0343803727874574 	 Accuracy: 0.532258064516129
Delta: 0.002077192907549302 	  Loss: 1.034359919383414 	 Accuracy: 0.532258064516129
Delta: 0.0025150429026013273 	  Loss: 1.0343251253993642 	 Accuracy: 0.532258064516129
Delta: 0.002044036832225485 	  Loss: 1.0342930770573964 	 Accuracy: 0.532258064516129
Delta: 0.0016659591396215843 	  Loss: 1.0342840961539594 	 Accuracy: 0.532258064516129
Delta: 0.0014043581033153668 	  Loss: 1.0342762833433357 	 Accuracy: 0.532258064516129
Delta: 0.001850168343442077 	  Loss: 1.034259284142176 	 Accuracy: 0.532258064516129
Delta: 0.0019071184119248679 	  Loss: 1.0342602484502241 	 Accuracy: 0.532258064516129
Delta: 0.0010852583552715426 	  Loss: 1.0342461106830565 	 Accuracy: 0.532258064516129
Delta: 0.0008698087202188448 	  Loss: 1.0342403849341175 	 Accuracy: 0.532258064516129
Delta: 0.0010786779947259196 	  Loss: 1.0342342912557831 	 Accuracy: 0.532258064516129
Delta: 0.000829126765116214 	  Loss: 1.0342302231029201 	 Accuracy: 0.532258064516129
Delta: 0.0012974899514287862 	  Loss: 1.034235222654948 	 Accuracy: 0.532258064516129
Delta: 0.001190240138482263 	  Loss: 1.034234990476654 	 Accuracy: 0.532258064516129
Delta: 0.0011727165948268142 	  Loss: 1.034224862234229 	 Accuracy: 0.532258064516129
Delta: 0.0017746920253189063 	  Loss: 1.0342249549330904 	 Accuracy: 0.532258064516129
converged at iter  49
Delta: 0.05800896345316231 	  Loss: 1.0813046057028683 	 Accuracy: 0.24193548387096775
Delta: 0.04550829585403584 	  Loss: 1.0757466484515876 	 Accuracy: 0.16129032258064516
Delta: 0.037488636341369605 	  Loss: 1.0742885163598166 	 Accuracy: 0.1935483870967742
Delta: 0.023588268928289288 	  Loss: 1.0708956653730597 	 Accuracy: 0.1774193548387097

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.018600003668114325 	  Loss: 1.0689301248775132 	 Accuracy: 0.1774193548387097
Delta: 0.018740907667380662 	  Loss: 1.067532594322436 	 Accuracy: 0.1774193548387097
Delta: 0.013624459941842526 	  Loss: 1.0662321858817507 	 Accuracy: 0.1774193548387097
Delta: 0.01124821879245583 	  Loss: 1.065301256307206 	 Accuracy: 0.1774193548387097
Delta: 0.00942054407204652 	  Loss: 1.0647057341211392 	 Accuracy: 0.1774193548387097
Delta: 0.009301817923724025 	  Loss: 1.0642933522915885 	 Accuracy: 0.1774193548387097
Delta: 0.008164053901211417 	  Loss: 1.0639231945600258 	 Accuracy: 0.1774193548387097
Delta: 0.007048092054053218 	  Loss: 1.063662838378167 	 Accuracy: 0.1774193548387097
Delta: 0.006717240392983995 	  Loss: 1.063468693132931 	 Accuracy: 0.1774193548387097
Delta: 0.006074680371494611 	  Loss: 1.0632545305449552 	 Accuracy: 0.1774193548387097
Delta: 0.005620194122779577 	  Loss: 1.0630134310368318 	 Accuracy: 0.1774193548387097
Delta: 0.005768628728551195 	  Loss: 1.0628573502155874 	 Accuracy: 0.1774193548387097
Delta: 0.004146970138357126 	  Loss: 1.0627304292826354 	 Accuracy: 0.1774193548387097
Delta: 0.004726965632273117 	  Loss: 1.0626729429639838 	 Accuracy: 0.1774193548387097
Delta: 0.003931349362796217 	  Loss: 1.0625855185229445 	 Accuracy: 0.1774193548387097
Delta: 0.0043240019231562815 	  Loss: 1.0625641558336327 	 Accuracy: 0.1774193548387097
Delta: 0.003964720328070536 	  Loss: 1.06251795168026 	 Accuracy: 0.1774193548387097
Delta: 0.004557944168022536 	  Loss: 1.0625011111899714 	 Accuracy: 0.1774193548387097
Delta: 0.003941749957381182 	  Loss: 1.0624429834860236 	 Accuracy: 0.1774193548387097
Delta: 0.003916957837490591 	  Loss: 1.0623991142362765 	 Accuracy: 0.1774193548387097
Delta: 0.003929471230418928 	  Loss: 1.062331754975303 	 Accuracy: 0.1774193548387097
Delta: 0.004017782535685392 	  Loss: 1.0622636640763279 	 Accuracy: 0.1774193548387097
Delta: 0.0044596095752953025 	  Loss: 1.0622290420013834 	 Accuracy: 0.1774193548387097
Delta: 0.004156143130604598 	  Loss: 1.0621905228926858 	 Accuracy: 0.1774193548387097
Delta: 0.004343065925323224 	  Loss: 1.0621616723473646 	 Accuracy: 0.1774193548387097
Delta: 0.005304863926189118 	  Loss: 1.0621048305332796 	 Accuracy: 0.1774193548387097
Delta: 0.0056131019927874795 	  Loss: 1.0620149329395838 	 Accuracy: 0.1774193548387097
Delta: 0.005584113318631388 	  Loss: 1.0619238812244856 	 Accuracy: 0.1774193548387097
Delta: 0.005724904957954357 	  Loss: 1.0618700794764475 	 Accuracy: 0.1774193548387097
Delta: 0.008036833697258064 	  Loss: 1.061787997824935 	 Accuracy: 0.1774193548387097
Delta: 0.0095195710470652 	  Loss: 1.0615835780845273 	 Accuracy: 0.1774193548387097
Delta: 0.009572166175943418 	  Loss: 1.061331571384617 	 Accuracy: 0.1774193548387097
Delta: 0.008812909021766225 	  Loss: 1.061163852384614 	 Accuracy: 0.1774193548387097
Delta: 0.006698886381501943 	  Loss: 1.0610186163199702 	 Accuracy: 0.1774193548387097
Delta: 0.004864399721629952 	  Loss: 1.0608951268087232 	 Accuracy: 0.1774193548387097
Delta: 0.004534707087884017 	  Loss: 1.0608215639665706 	 Accuracy: 0.1774193548387097
Delta: 0.004008378520109046 	  Loss: 1.060729943813202 	 Accuracy: 0.1774193548387097
Delta: 0.0036599938730241272 	  Loss: 1.060676222088083 	 Accuracy: 0.1774193548387097
Delta: 0.003583234723205495 	  Loss: 1.0606456435480291 	 Accuracy: 0.1774193548387097
Delta: 0.00338737605318029 	  Loss: 1.0606033962338541 	 Accuracy: 0.1774193548387097
Delta: 0.0034601570276373765 	  Loss: 1.0605725975962539 	 Accuracy: 0.1774193548387097
Delta: 0.0038430584505485324 	  Loss: 1.0605226182821919 	 Accuracy: 0.1774193548387097
Delta: 0.003720655605164354 	  Loss: 1.060489437027031 	 Accuracy: 0.1774193548387097
Delta: 0.002508958242622751 	  Loss: 1.0604882414959884 	 Accuracy: 0.1774193548387097
Delta: 0.0025195528852965357 	  Loss: 1.0604737759440965 	 Accuracy: 0.1774193548387097
Delta: 0.0020372867096127966 	  Loss: 1.0604538458638584 	 Accuracy: 0.1774193548387097
Delta: 0.0011180872498126068 	  Loss: 1.060415486533184 	 Accuracy: 0.1774193548387097
Delta: 0.0012359222681010444 	  Loss: 1.0604109955351142 	 Accuracy: 0.1774193548387097
Delta: 0.0012693398953682032 	  Loss: 1.060412502735147 	 Accuracy: 0.1774193548387097
Delta: 0.0017523026856993596 	  Loss: 1.0604168424590583 	 Accuracy: 0.1774193548387097
Delta: 0.001201738416885915 	  Loss: 1.0604205800643984 	 Accuracy: 0.1774193548387097
Delta: 0.0007633338838151042 	  Loss: 1.0604222191550527 	 Accuracy: 0.1774193548387097
Delta: 0.0006524711935602595 	  Loss: 1.0604232025509734 	 Accuracy: 0.1774193548387097
Delta: 0.0005499525199042818 	  Loss: 1.060420216063248 	 Accuracy: 0.1774193548387097
Delta: 0.0007690681491666185 	  Loss: 1.06041843805678 	 Accuracy: 0.1774193548387097
Delta: 0.0009480153869690688 	  Loss: 1.060406376486593 	 Accuracy: 0.1774193548387097
Delta: 0.0009036786408741262 	  Loss: 1.0604065536493334 	 Accuracy: 0.1774193548387097
Delta: 0.0010248775840024035 	  Loss: 1.0604046116449797 	 Accuracy: 0.1774193548387097
Delta: 0.0010407249496592415 	  Loss: 1.0604073322478471 	 Accuracy: 0.1774193548387097
Delta: 0.001278431844491333 	  Loss: 1.060418348512857 	 Accuracy: 0.1774193548387097
Delta: 0.0015214141604257922 	  Loss: 1.060406019224676 	 Accuracy: 0.1774193548387097
Delta: 0.0011780334841856226 	  Loss: 1.06040058189245 	 Accuracy: 0.1774193548387097
Delta: 0.001522264438238571 	  Loss: 1.0604044554932153 	 Accuracy: 0.1774193548387097
Delta: 0.001467992983333877 	  Loss: 1.0604036370441163 	 Accuracy: 0.1774193548387097
Delta: 0.0013794742417417402 	  Loss: 1.0604212441349217 	 Accuracy: 0.1774193548387097
Delta: 0.0017393762609785746 	  Loss: 1.060412858993765 	 Accuracy: 0.1774193548387097
Delta: 0.0009659934136691658 	  Loss: 1.060403492045951 	 Accuracy: 0.1774193548387097
Delta: 0.00042207406661831474 	  Loss: 1.0603945206977448 	 Accuracy: 0.1774193548387097
Delta: 5.6485510892700336e-05 	  Loss: 1.0603939872553478 	 Accuracy: 0.1774193548387097
Delta: 1.9848687365472535e-06 	  Loss: 1.0603939501478585 	 Accuracy: 0.1774193548387097
converged at iter  73
Delta: 0.05719971758287612 	  Loss: 1.0634822221231715 	 Accuracy: 0.5396825396825397
Delta: 0.04859990571544075 	  Loss: 1.059454105816176 	 Accuracy: 0.5238095238095238
Delta: 0.03664117500490358 	  Loss: 1.055575645562417 	 Accuracy: 0.49206349206349204

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02263128838137544 	  Loss: 1.051423720224001 	 Accuracy: 0.49206349206349204
Delta: 0.014331656523534537 	  Loss: 1.049823675571074 	 Accuracy: 0.49206349206349204
Delta: 0.012342699179231998 	  Loss: 1.0489569472872526 	 Accuracy: 0.49206349206349204
Delta: 0.009926227031824332 	  Loss: 1.0483595824891914 	 Accuracy: 0.49206349206349204
Delta: 0.009411464539169485 	  Loss: 1.04787962625229 	 Accuracy: 0.49206349206349204
Delta: 0.00919158133815959 	  Loss: 1.047483104070678 	 Accuracy: 0.49206349206349204
Delta: 0.008634895216456825 	  Loss: 1.0470365765432652 	 Accuracy: 0.49206349206349204
Delta: 0.008729763741948624 	  Loss: 1.046580433693789 	 Accuracy: 0.49206349206349204
Delta: 0.009908767640434506 	  Loss: 1.0462244659120037 	 Accuracy: 0.49206349206349204
Delta: 0.010020360202256431 	  Loss: 1.045714129525015 	 Accuracy: 0.49206349206349204
Delta: 0.009084996084165766 	  Loss: 1.0452375818693391 	 Accuracy: 0.49206349206349204
Delta: 0.007982397137696752 	  Loss: 1.0449094794343976 	 Accuracy: 0.49206349206349204
Delta: 0.006684226656132658 	  Loss: 1.0446727217430054 	 Accuracy: 0.49206349206349204
Delta: 0.005552780571933003 	  Loss: 1.0445023777067248 	 Accuracy: 0.49206349206349204
Delta: 0.004840230621174342 	  Loss: 1.0444546071989658 	 Accuracy: 0.49206349206349204
Delta: 0.003333430392549853 	  Loss: 1.0444005757416024 	 Accuracy: 0.49206349206349204
Delta: 0.0029347833295467985 	  Loss: 1.0443685661817326 	 Accuracy: 0.49206349206349204
Delta: 0.0020960349044057266 	  Loss: 1.0443309815436759 	 Accuracy: 0.49206349206349204
Delta: 0.001668877495913643 	  Loss: 1.044317112852406 	 Accuracy: 0.49206349206349204
Delta: 0.001406369396462825 	  Loss: 1.0443058567945114 	 Accuracy: 0.49206349206349204
Delta: 0.00128866597509265 	  Loss: 1.0443023347205032 	 Accuracy: 0.49206349206349204
Delta: 0.002449625720086439 	  Loss: 1.044297907665039 	 Accuracy: 0.49206349206349204
Delta: 0.0023117620592346317 	  Loss: 1.044286272510616 	 Accuracy: 0.49206349206349204
Delta: 0.0028431219073166898 	  Loss: 1.0442502923314803 	 Accuracy: 0.49206349206349204
Delta: 0.0029336939992416263 	  Loss: 1.044218818622654 	 Accuracy: 0.49206349206349204
Delta: 0.0024394923573554366 	  Loss: 1.0441657846331085 	 Accuracy: 0.49206349206349204
Delta: 0.0019745279847564515 	  Loss: 1.044151463422839 	 Accuracy: 0.49206349206349204
Delta: 0.0015288309807723367 	  Loss: 1.0441157911486223 	 Accuracy: 0.49206349206349204
Delta: 0.0012784884719749504 	  Loss: 1.0440935636891364 	 Accuracy: 0.49206349206349204
Delta: 0.0008400394497231967 	  Loss: 1.0440747776764985 	 Accuracy: 0.49206349206349204
Delta: 0.001068400394097544 	  Loss: 1.0440621470885172 	 Accuracy: 0.49206349206349204
Delta: 0.0012454284347651419 	  Loss: 1.044044998642451 	 Accuracy: 0.49206349206349204
Delta: 0.0013847071443854639 	  Loss: 1.0440243324168852 	 Accuracy: 0.49206349206349204
Delta: 0.0013460665051934465 	  Loss: 1.0440054647087296 	 Accuracy: 0.49206349206349204
Delta: 0.0011015500099553707 	  Loss: 1.043999968062323 	 Accuracy: 0.49206349206349204
Delta: 0.0009515723611877254 	  Loss: 1.0439943921526242 	 Accuracy: 0.49206349206349204
Delta: 0.0009578134418692577 	  Loss: 1.0440022407350456 	 Accuracy: 0.49206349206349204
Delta: 0.0008467618062955472 	  Loss: 1.044001868353566 	 Accuracy: 0.49206349206349204
Delta: 0.0009867745639726344 	  Loss: 1.0439925904467175 	 Accuracy: 0.49206349206349204
Delta: 0.0008054467585219951 	  Loss: 1.0439838997339548 	 Accuracy: 0.49206349206349204
Delta: 0.000655867151989526 	  Loss: 1.0439771463211773 	 Accuracy: 0.49206349206349204
Delta: 0.001599699187022285 	  Loss: 1.0439676792746986 	 Accuracy: 0.49206349206349204
Delta: 0.0006606269811501631 	  Loss: 1.0439467678377865 	 Accuracy: 0.49206349206349204
Delta: 0.0004570087940211349 	  Loss: 1.0439460754275032 	 Accuracy: 0.49206349206349204
Delta: 0.0002796089763200274 	  Loss: 1.0439474088722185 	 Accuracy: 0.49206349206349204
Delta: 0.0002460631177360593 	  Loss: 1.0439477714397167 	 Accuracy: 0.49206349206349204
Delta: 0.0004261180889724067 	  Loss: 1.0439467333114227 	 Accuracy: 0.49206349206349204
Delta: 0.000519869278453413 	  Loss: 1.0439450021502434 	 Accuracy: 0.49206349206349204
Delta: 0.0006445164763595455 	  Loss: 1.043944500370979 	 Accuracy: 0.49206349206349204
Delta: 0.0003312994226298539 	  Loss: 1.0439456067718411 	 Accuracy: 0.49206349206349204
Delta: 4.00230197688945e-05 	  Loss: 1.043947048042475 	 Accuracy: 0.49206349206349204
Delta: 1.4011213338887057e-06 	  Loss: 1.043947125867282 	 Accuracy: 0.49206349206349204
converged at iter  54
Delta: 0.05638675261598847 	  Loss: 1.058089967759739 	 Accuracy: 0.38095238095238093
Delta: 0.0503757242928382 	  Loss: 1.050680688152295 	 Accuracy: 0.2222222222222222
Delta: 0.03509738859934136 	  Loss: 1.0454857281646395 	 Accuracy: 0.1746031746031746
Delta: 0.02359783426408201 	  Loss: 1.04192354560196 	 Accuracy: 0.19047619047619047

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01999424967500297 	  Loss: 1.0405460829105007 	 Accuracy: 0.19047619047619047
Delta: 0.013132337429893743 	  Loss: 1.0395966408432282 	 Accuracy: 0.19047619047619047
Delta: 0.009805778889230407 	  Loss: 1.0389596715635596 	 Accuracy: 0.19047619047619047
Delta: 0.008342605928389162 	  Loss: 1.0385855280349383 	 Accuracy: 0.19047619047619047
Delta: 0.009243299900099249 	  Loss: 1.0382681113915302 	 Accuracy: 0.19047619047619047
Delta: 0.007808989605143502 	  Loss: 1.0379680549851726 	 Accuracy: 0.19047619047619047
Delta: 0.006489448726734695 	  Loss: 1.0377898700121313 	 Accuracy: 0.19047619047619047
Delta: 0.005494097645901147 	  Loss: 1.0376646343519544 	 Accuracy: 0.19047619047619047
Delta: 0.004270859867027846 	  Loss: 1.037522982784791 	 Accuracy: 0.19047619047619047
Delta: 0.003748188720819479 	  Loss: 1.037427228618542 	 Accuracy: 0.19047619047619047
Delta: 0.0029378628230725336 	  Loss: 1.0373715423725764 	 Accuracy: 0.19047619047619047
Delta: 0.003608294908737488 	  Loss: 1.0373454641875077 	 Accuracy: 0.19047619047619047
Delta: 0.003499942608064264 	  Loss: 1.037325598538044 	 Accuracy: 0.19047619047619047
Delta: 0.003273612020349166 	  Loss: 1.0373277741807518 	 Accuracy: 0.19047619047619047
Delta: 0.004268545697058964 	  Loss: 1.0373374916504476 	 Accuracy: 0.19047619047619047
Delta: 0.0033726023757307314 	  Loss: 1.0373000823463039 	 Accuracy: 0.19047619047619047
Delta: 0.0032358622516425422 	  Loss: 1.0372583129667374 	 Accuracy: 0.19047619047619047
Delta: 0.0036949609011214506 	  Loss: 1.0372453926312875 	 Accuracy: 0.19047619047619047
Delta: 0.004416793732902352 	  Loss: 1.0372283100137416 	 Accuracy: 0.19047619047619047
Delta: 0.004902599570784366 	  Loss: 1.0371606697268265 	 Accuracy: 0.19047619047619047
Delta: 0.004878033154745416 	  Loss: 1.037083101549583 	 Accuracy: 0.19047619047619047
Delta: 0.004471324512877317 	  Loss: 1.0370349212051289 	 Accuracy: 0.19047619047619047
Delta: 0.004181707054839972 	  Loss: 1.0369948846624153 	 Accuracy: 0.19047619047619047
Delta: 0.004314286911226899 	  Loss: 1.0369624509748387 	 Accuracy: 0.19047619047619047
Delta: 0.004154156974491067 	  Loss: 1.0368644691945952 	 Accuracy: 0.19047619047619047
Delta: 0.005059855904851331 	  Loss: 1.036773855992534 	 Accuracy: 0.19047619047619047
Delta: 0.004430609988034431 	  Loss: 1.0366917319033162 	 Accuracy: 0.19047619047619047
Delta: 0.0031840577199637897 	  Loss: 1.036649422848478 	 Accuracy: 0.19047619047619047
Delta: 0.0028865234135287228 	  Loss: 1.0366036451189324 	 Accuracy: 0.19047619047619047
Delta: 0.002403657072342659 	  Loss: 1.0365741611017802 	 Accuracy: 0.19047619047619047
Delta: 0.0024015882887518034 	  Loss: 1.0365489169451527 	 Accuracy: 0.19047619047619047
Delta: 0.0025893787555685147 	  Loss: 1.0365247205430546 	 Accuracy: 0.19047619047619047
Delta: 0.0025866790921006233 	  Loss: 1.0365013190045542 	 Accuracy: 0.19047619047619047
Delta: 0.003118098096058346 	  Loss: 1.0364721390806628 	 Accuracy: 0.19047619047619047
Delta: 0.0023614995232528395 	  Loss: 1.0364371550902636 	 Accuracy: 0.19047619047619047
Delta: 0.002412823034146205 	  Loss: 1.0364070382067445 	 Accuracy: 0.19047619047619047
Delta: 0.0023947987587696774 	  Loss: 1.0363749757824805 	 Accuracy: 0.19047619047619047
Delta: 0.0014532954874537866 	  Loss: 1.0363519486336057 	 Accuracy: 0.19047619047619047
Delta: 0.0010007879876429838 	  Loss: 1.0363521835317773 	 Accuracy: 0.19047619047619047
Delta: 0.0006310846673022041 	  Loss: 1.036346483220484 	 Accuracy: 0.19047619047619047
Delta: 0.0005468314212227086 	  Loss: 1.0363449760564685 	 Accuracy: 0.19047619047619047
Delta: 0.0006194980817371023 	  Loss: 1.0363437229606802 	 Accuracy: 0.19047619047619047
Delta: 0.001338669788229294 	  Loss: 1.036343141437886 	 Accuracy: 0.19047619047619047
Delta: 0.0004870234137583393 	  Loss: 1.0363453953861645 	 Accuracy: 0.19047619047619047
Delta: 0.0006874128268162479 	  Loss: 1.0363437806511255 	 Accuracy: 0.19047619047619047
Delta: 0.0012929305879249248 	  Loss: 1.0363426967381322 	 Accuracy: 0.19047619047619047
Delta: 0.0010040810681298847 	  Loss: 1.0363273211837358 	 Accuracy: 0.19047619047619047
Delta: 0.0011967164981831026 	  Loss: 1.0363250318929258 	 Accuracy: 0.19047619047619047
Delta: 0.00043746128292442384 	  Loss: 1.0363190408545373 	 Accuracy: 0.19047619047619047
Delta: 0.0001987269913088418 	  Loss: 1.0363188928533376 	 Accuracy: 0.19047619047619047
Delta: 0.0004833725905346509 	  Loss: 1.0363184367074985 	 Accuracy: 0.19047619047619047
Delta: 0.00019749043997094 	  Loss: 1.0363186266895381 	 Accuracy: 0.19047619047619047
Delta: 0.00025625056425626993 	  Loss: 1.0363182862933733 	 Accuracy: 0.19047619047619047
Delta: 0.00022458436732907642 	  Loss: 1.0363173160435033 	 Accuracy: 0.19047619047619047
Delta: 0.0003357244339813521 	  Loss: 1.0363166464832927 	 Accuracy: 0.19047619047619047
Delta: 0.0004719037962748451 	  Loss: 1.036315645098461 	 Accuracy: 0.19047619047619047
Delta: 0.0003167719578843612 	  Loss: 1.0363162479966506 	 Accuracy: 0.19047619047619047
Delta: 6.497783947772e-05 	  Loss: 1.0363167088844933 	 Accuracy: 0.19047619047619047
Delta: 1.4720335275835711e-05 	  Loss: 1.036316949335181 	 Accuracy: 0.19047619047619047
Delta: 1.8081863440783544e-05 	  Loss: 1.0363170455663877 	 Accuracy: 0.19047619047619047
converged at iter  63
Delta: 0.0588213734415836 	  Loss: 1.0743714134620355 	 Accuracy: 0.5645161290322581
Delta: 0.0408183742062337 	  Loss: 1.0663974663967444 	 Accuracy: 0.43548387096774194
Delta: 0.03154768331994531 	  Loss: 1.0613319360192115 	 Accuracy: 0.41935483870967744
Delta: 0.027201143283184313 	  Loss: 1.0567821279606322 	 Accuracy: 0.43548387096774194
Delta: 0.0156534533263965 	  Loss: 1.0546235919459275 	 Accuracy: 0.41935483870967744

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0183106745496667 	  Loss: 1.053365368166149 	 Accuracy: 0.41935483870967744
Delta: 0.012445721112828212 	  Loss: 1.0525219062170943 	 Accuracy: 0.41935483870967744
Delta: 0.010359136409807033 	  Loss: 1.051933510479703 	 Accuracy: 0.41935483870967744
Delta: 0.00875427312612398 	  Loss: 1.0514707958167977 	 Accuracy: 0.41935483870967744
Delta: 0.008412401980569858 	  Loss: 1.0511700712675718 	 Accuracy: 0.41935483870967744
Delta: 0.007418497406570569 	  Loss: 1.0509042784003422 	 Accuracy: 0.41935483870967744
Delta: 0.006418847445417534 	  Loss: 1.0506778967228279 	 Accuracy: 0.41935483870967744
Delta: 0.005103224363814764 	  Loss: 1.0505383964486013 	 Accuracy: 0.41935483870967744
Delta: 0.004456778193471226 	  Loss: 1.0504627933984607 	 Accuracy: 0.41935483870967744
Delta: 0.004363684357641834 	  Loss: 1.0503725222831375 	 Accuracy: 0.41935483870967744
Delta: 0.005115869906300417 	  Loss: 1.05030958402972 	 Accuracy: 0.41935483870967744
Delta: 0.0051364517730579 	  Loss: 1.0501870585990936 	 Accuracy: 0.41935483870967744
Delta: 0.004574244463010075 	  Loss: 1.0501042212358183 	 Accuracy: 0.41935483870967744
Delta: 0.004058505521034148 	  Loss: 1.050028034632363 	 Accuracy: 0.41935483870967744
Delta: 0.003555258189541541 	  Loss: 1.0499849216656667 	 Accuracy: 0.41935483870967744
Delta: 0.003977477716887074 	  Loss: 1.049958960167858 	 Accuracy: 0.41935483870967744
Delta: 0.0044425131060985305 	  Loss: 1.0498663301062252 	 Accuracy: 0.41935483870967744
Delta: 0.003409702907763604 	  Loss: 1.0497810869697974 	 Accuracy: 0.41935483870967744
Delta: 0.0028543466585741663 	  Loss: 1.0497444951976922 	 Accuracy: 0.41935483870967744
Delta: 0.003432695125605282 	  Loss: 1.0496899313582024 	 Accuracy: 0.41935483870967744
Delta: 0.003409162748781421 	  Loss: 1.0496094050117029 	 Accuracy: 0.41935483870967744
Delta: 0.003045868823977186 	  Loss: 1.0495619786421222 	 Accuracy: 0.41935483870967744
Delta: 0.0028114265660940966 	  Loss: 1.0495390573467114 	 Accuracy: 0.41935483870967744
Delta: 0.002296181889758056 	  Loss: 1.0494977643003045 	 Accuracy: 0.41935483870967744
Delta: 0.0020351045003995593 	  Loss: 1.0494792815753629 	 Accuracy: 0.41935483870967744
Delta: 0.00280255091669877 	  Loss: 1.049434935140864 	 Accuracy: 0.41935483870967744
Delta: 0.0021754536245310275 	  Loss: 1.0493729883029213 	 Accuracy: 0.41935483870967744
Delta: 0.0030052744081485562 	  Loss: 1.0493529708310048 	 Accuracy: 0.41935483870967744
Delta: 0.0026383116919710065 	  Loss: 1.0492993143123917 	 Accuracy: 0.41935483870967744
Delta: 0.0026250064210716056 	  Loss: 1.0492590890073825 	 Accuracy: 0.41935483870967744
Delta: 0.0035321433186880995 	  Loss: 1.0492220396053926 	 Accuracy: 0.41935483870967744
Delta: 0.001921090611634886 	  Loss: 1.049154764590288 	 Accuracy: 0.41935483870967744
Delta: 0.0021901664991905035 	  Loss: 1.0491510389312082 	 Accuracy: 0.41935483870967744
Delta: 0.002811160164958338 	  Loss: 1.0491067905507176 	 Accuracy: 0.41935483870967744
Delta: 0.0019403698119894264 	  Loss: 1.0491069406580513 	 Accuracy: 0.41935483870967744
Delta: 0.0026095865371621387 	  Loss: 1.0491097649963814 	 Accuracy: 0.41935483870967744
Delta: 0.0027352320205670856 	  Loss: 1.0490858508696705 	 Accuracy: 0.41935483870967744
Delta: 0.003024285977037341 	  Loss: 1.0490729500471692 	 Accuracy: 0.41935483870967744
Delta: 0.0026979492760218766 	  Loss: 1.0490643032518827 	 Accuracy: 0.41935483870967744
Delta: 0.002591511168000208 	  Loss: 1.0490415960396064 	 Accuracy: 0.41935483870967744
Delta: 0.0022222973600457816 	  Loss: 1.049034516688919 	 Accuracy: 0.41935483870967744
Delta: 0.002655959091250104 	  Loss: 1.0490267289849857 	 Accuracy: 0.41935483870967744
Delta: 0.002445011905263898 	  Loss: 1.0490006343097877 	 Accuracy: 0.41935483870967744
Delta: 0.0028709197194919122 	  Loss: 1.0489794457412824 	 Accuracy: 0.41935483870967744
Delta: 0.0026736034077287038 	  Loss: 1.0489419163897444 	 Accuracy: 0.41935483870967744
Delta: 0.002413602933364359 	  Loss: 1.048903703610891 	 Accuracy: 0.41935483870967744
Delta: 0.0018908369962876966 	  Loss: 1.0488609617513514 	 Accuracy: 0.41935483870967744
Delta: 0.0018440514307304086 	  Loss: 1.0488419803979947 	 Accuracy: 0.41935483870967744
Delta: 0.0030157488999174105 	  Loss: 1.0488373582448014 	 Accuracy: 0.41935483870967744
Delta: 0.003141829104195589 	  Loss: 1.0488250920968425 	 Accuracy: 0.41935483870967744
Delta: 0.0032394794721784218 	  Loss: 1.048815587865497 	 Accuracy: 0.41935483870967744
Delta: 0.0019886082313421696 	  Loss: 1.0488022363392147 	 Accuracy: 0.41935483870967744
Delta: 0.001387245890919986 	  Loss: 1.0487937011240702 	 Accuracy: 0.41935483870967744
Delta: 0.0015387822252796788 	  Loss: 1.0487799157778166 	 Accuracy: 0.41935483870967744
Delta: 0.0012728495000615028 	  Loss: 1.0487619472270726 	 Accuracy: 0.41935483870967744
Delta: 0.0015074172094978462 	  Loss: 1.048761992933123 	 Accuracy: 0.41935483870967744
converged at iter  60
Delta: 0.05890791030952637 	  Loss: 1.0648957717021221 	 Accuracy: 0.45161290322580644
Delta: 0.04421252490959256 	  Loss: 1.0580098927662873 	 Accuracy: 0.41935483870967744
Delta: 0.03477503124763799 	  Loss: 1.0534176920579614 	 Accuracy: 0.3548387096774194

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.023620746482532443 	  Loss: 1.0500351687869696 	 Accuracy: 0.3709677419354839
Delta: 0.0183290720057206 	  Loss: 1.048005863249724 	 Accuracy: 0.3709677419354839
Delta: 0.014688856484776107 	  Loss: 1.0467962706927572 	 Accuracy: 0.3709677419354839
Delta: 0.011816041298825231 	  Loss: 1.0459405508009307 	 Accuracy: 0.3709677419354839
Delta: 0.011715833556012314 	  Loss: 1.0453873599275645 	 Accuracy: 0.3709677419354839
Delta: 0.01139132959785208 	  Loss: 1.0448773934674975 	 Accuracy: 0.3709677419354839
Delta: 0.009857969813975569 	  Loss: 1.044433883740557 	 Accuracy: 0.3709677419354839
Delta: 0.00838650402255097 	  Loss: 1.0440523939520783 	 Accuracy: 0.3709677419354839
Delta: 0.007889515085773246 	  Loss: 1.0437984369146875 	 Accuracy: 0.3709677419354839
Delta: 0.007636711263249393 	  Loss: 1.0436105809360003 	 Accuracy: 0.3709677419354839
Delta: 0.005511428436812543 	  Loss: 1.0435129534393766 	 Accuracy: 0.3709677419354839
Delta: 0.005834208648542021 	  Loss: 1.0434128712885156 	 Accuracy: 0.3709677419354839
Delta: 0.0046548733576609845 	  Loss: 1.0432360358152857 	 Accuracy: 0.3709677419354839
Delta: 0.0062528305873359976 	  Loss: 1.0431241465658403 	 Accuracy: 0.3709677419354839
Delta: 0.005450133197054581 	  Loss: 1.0430093856106053 	 Accuracy: 0.3709677419354839
Delta: 0.0050847356538515865 	  Loss: 1.0429223731234685 	 Accuracy: 0.3709677419354839
Delta: 0.00409004147506707 	  Loss: 1.042817022430611 	 Accuracy: 0.3709677419354839
Delta: 0.0047006944379543 	  Loss: 1.0427505232681442 	 Accuracy: 0.3709677419354839
Delta: 0.00443044921112305 	  Loss: 1.0426774644364034 	 Accuracy: 0.3709677419354839
Delta: 0.00429319205370323 	  Loss: 1.0425885922382112 	 Accuracy: 0.3709677419354839
Delta: 0.0042733190387247025 	  Loss: 1.0425082571248527 	 Accuracy: 0.3709677419354839
Delta: 0.0031261284812960214 	  Loss: 1.0424528888277371 	 Accuracy: 0.3709677419354839
Delta: 0.0033254562145993913 	  Loss: 1.042408104940256 	 Accuracy: 0.3709677419354839
Delta: 0.0034310767694434286 	  Loss: 1.0423272486733346 	 Accuracy: 0.3709677419354839
Delta: 0.002921155367509088 	  Loss: 1.042285098617973 	 Accuracy: 0.3709677419354839
Delta: 0.0023850304493260688 	  Loss: 1.0422428586170036 	 Accuracy: 0.3709677419354839
Delta: 0.001959911498251627 	  Loss: 1.0422176056042063 	 Accuracy: 0.3709677419354839
Delta: 0.0013499745535583362 	  Loss: 1.042194012227415 	 Accuracy: 0.3709677419354839
Delta: 0.0014900753376881988 	  Loss: 1.0421858365728105 	 Accuracy: 0.3709677419354839
Delta: 0.0021276601075723403 	  Loss: 1.042172574421202 	 Accuracy: 0.3709677419354839
Delta: 0.0017563671078289964 	  Loss: 1.0421585280349708 	 Accuracy: 0.3709677419354839
Delta: 0.0014884148219657712 	  Loss: 1.0421377837216026 	 Accuracy: 0.3709677419354839
Delta: 0.0016347837554007666 	  Loss: 1.042110903635306 	 Accuracy: 0.3709677419354839
Delta: 0.0014418472298301916 	  Loss: 1.0420965392933463 	 Accuracy: 0.3709677419354839
Delta: 0.0006837038843011475 	  Loss: 1.0420871075344518 	 Accuracy: 0.3709677419354839
Delta: 0.0003517591161602633 	  Loss: 1.0420854271205675 	 Accuracy: 0.3709677419354839
Delta: 0.00020620969566241898 	  Loss: 1.04208275600331 	 Accuracy: 0.3709677419354839
Delta: 0.0005835900190114052 	  Loss: 1.04208182203993 	 Accuracy: 0.3709677419354839
Delta: 0.00025829372714144204 	  Loss: 1.0420826605423936 	 Accuracy: 0.3709677419354839
Delta: 0.0002020703132781682 	  Loss: 1.0420807505470528 	 Accuracy: 0.3709677419354839
Delta: 0.00016960087601682264 	  Loss: 1.0420794389849672 	 Accuracy: 0.3709677419354839
Delta: 0.00019992016550658665 	  Loss: 1.0420786832273898 	 Accuracy: 0.3709677419354839
Delta: 0.0003785942802472498 	  Loss: 1.0420806687724076 	 Accuracy: 0.3709677419354839
Delta: 0.0006790006720955334 	  Loss: 1.0420835608482906 	 Accuracy: 0.3709677419354839
Delta: 0.0007039245028862973 	  Loss: 1.0420755926606358 	 Accuracy: 0.3709677419354839
Delta: 0.0005596704260881027 	  Loss: 1.0420724338415985 	 Accuracy: 0.3709677419354839
Delta: 0.0005816565025645056 	  Loss: 1.0420662228188469 	 Accuracy: 0.3709677419354839
Delta: 0.0007065803218157003 	  Loss: 1.042059690326801 	 Accuracy: 0.3709677419354839
Delta: 0.0016469198408122642 	  Loss: 1.0420527064095282 	 Accuracy: 0.3709677419354839
Delta: 0.0015322806529042428 	  Loss: 1.0420369305181771 	 Accuracy: 0.3709677419354839
Delta: 0.0013764905119954898 	  Loss: 1.0420276037844203 	 Accuracy: 0.3709677419354839
Delta: 0.001437110841074281 	  Loss: 1.0420165510757737 	 Accuracy: 0.3709677419354839
Delta: 0.0014589041885586197 	  Loss: 1.0420166756043479 	 Accuracy: 0.3709677419354839
Delta: 0.0018198574278593192 	  Loss: 1.0420170457589526 	 Accuracy: 0.3709677419354839
Delta: 0.0016221979783141187 	  Loss: 1.042022009732385 	 Accuracy: 0.3709677419354839
Delta: 0.0009224253590375232 	  Loss: 1.04201782917876 	 Accuracy: 0.3709677419354839
Delta: 0.0007641763911660156 	  Loss: 1.0420208833456523 	 Accuracy: 0.3709677419354839
Delta: 0.0014220180630353137 	  Loss: 1.04202211035326 	 Accuracy: 0.3709677419354839
Delta: 0.0016214832030819585 	  Loss: 1.042022455063248 	 Accuracy: 0.3709677419354839
Delta: 0.001579308847103015 	  Loss: 1.0420237476026384 	 Accuracy: 0.3709677419354839
Delta: 0.0013289668113576746 	  Loss: 1.0420165376462482 	 Accuracy: 0.3709677419354839
Delta: 0.0015051180516531435 	  Loss: 1.0420022055697622 	 Accuracy: 0.3709677419354839
Delta: 0.0012685486506615747 	  Loss: 1.0419852105783707 	 Accuracy: 0.3709677419354839
Delta: 0.0013118860932683257 	  Loss: 1.0419763181652637 	 Accuracy: 0.3709677419354839
Delta: 0.0010215733234346807 	  Loss: 1.041965753406188 	 Accuracy: 0.3709677419354839
Delta: 0.000829837161550639 	  Loss: 1.0419663863951631 	 Accuracy: 0.3709677419354839
Delta: 0.00040064371411565697 	  Loss: 1.041965787230121 	 Accuracy: 0.3709677419354839
Delta: 0.000467666510161467 	  Loss: 1.0419624803982797 	 Accuracy: 0.3709677419354839
Delta: 0.00046737252623940673 	  Loss: 1.041958754064002 	 Accuracy: 0.3709677419354839
Delta: 0.00023837654243926811 	  Loss: 1.0419556895622222 	 Accuracy: 0.3709677419354839
Delta: 0.0001137312354772528 	  Loss: 1.0419555906728215 	 Accuracy: 0.3709677419354839
converged at iter  73
Delta: 0.05764221756577882 	  Loss: 1.0739127452351904 	 Accuracy: 0.5967741935483871
Delta: 0.054060785317094115 	  Loss: 1.073097522288276 	 Accuracy: 0.5645161290322581
Delta: 0.041619198969771336 	  Loss: 1.0699702386911092 	 Accuracy: 0.5645161290322581
Delta: 0.031111817371008942 	  Loss: 1.0649609341101332 	 Accuracy: 0.5806451612903226

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.025252204875284217 	  Loss: 1.0609853914758913 	 Accuracy: 0.5806451612903226
Delta: 0.01815580754862576 	  Loss: 1.0584831134931953 	 Accuracy: 0.5645161290322581
Delta: 0.01638647042807304 	  Loss: 1.056866873610605 	 Accuracy: 0.5645161290322581
Delta: 0.013800896794673523 	  Loss: 1.0556525166972026 	 Accuracy: 0.5645161290322581
Delta: 0.01120068178430468 	  Loss: 1.0548235833182156 	 Accuracy: 0.5645161290322581
Delta: 0.007981551982484274 	  Loss: 1.0543190132036737 	 Accuracy: 0.5645161290322581
Delta: 0.006848088827351939 	  Loss: 1.0540157802707668 	 Accuracy: 0.5645161290322581
Delta: 0.006082648488705352 	  Loss: 1.0538094930707929 	 Accuracy: 0.5645161290322581
Delta: 0.006522280327144289 	  Loss: 1.0536475291723644 	 Accuracy: 0.5645161290322581
Delta: 0.00490351988466165 	  Loss: 1.053500214581208 	 Accuracy: 0.5645161290322581
Delta: 0.004172034707326932 	  Loss: 1.0534343576054117 	 Accuracy: 0.5645161290322581
Delta: 0.0031753614547874124 	  Loss: 1.0533862620824288 	 Accuracy: 0.5645161290322581
Delta: 0.0033426600740463653 	  Loss: 1.0533697240844524 	 Accuracy: 0.5645161290322581
Delta: 0.0025184695096180354 	  Loss: 1.053315546753014 	 Accuracy: 0.5645161290322581
Delta: 0.002517557379632713 	  Loss: 1.0533002505229172 	 Accuracy: 0.5645161290322581
Delta: 0.0012879103373036455 	  Loss: 1.0532903688827515 	 Accuracy: 0.5645161290322581
Delta: 0.0017691174914401789 	  Loss: 1.0532889539783477 	 Accuracy: 0.5645161290322581
Delta: 0.0012759172303608965 	  Loss: 1.0532911808250165 	 Accuracy: 0.5645161290322581
Delta: 0.0012906823466325385 	  Loss: 1.0532978591589912 	 Accuracy: 0.5645161290322581
Delta: 0.0011380768795386234 	  Loss: 1.0533030796763827 	 Accuracy: 0.5645161290322581
Delta: 0.002239316224264008 	  Loss: 1.0533039500598531 	 Accuracy: 0.5645161290322581
Delta: 0.0022806790193530043 	  Loss: 1.0533010226700323 	 Accuracy: 0.5645161290322581
Delta: 0.0013170649604917356 	  Loss: 1.0532940837720248 	 Accuracy: 0.5645161290322581
Delta: 0.0016093686821287989 	  Loss: 1.0532963736282541 	 Accuracy: 0.5645161290322581
Delta: 0.001396134493612318 	  Loss: 1.0532974364842846 	 Accuracy: 0.5645161290322581
Delta: 0.0009386336919477167 	  Loss: 1.0532958673114186 	 Accuracy: 0.5645161290322581
Delta: 0.0005968900448165544 	  Loss: 1.0532975123183812 	 Accuracy: 0.5645161290322581
Delta: 0.0009404203978105213 	  Loss: 1.0532923076594625 	 Accuracy: 0.5645161290322581
Delta: 0.0010747303545794902 	  Loss: 1.0532821091953102 	 Accuracy: 0.5645161290322581
Delta: 0.0010562605861896542 	  Loss: 1.053286059188101 	 Accuracy: 0.5645161290322581
Delta: 0.000742957530085205 	  Loss: 1.0532883750822173 	 Accuracy: 0.5645161290322581
Delta: 0.0008941591658215696 	  Loss: 1.0532860895011935 	 Accuracy: 0.5645161290322581
Delta: 0.0012278129930276172 	  Loss: 1.0532773713037518 	 Accuracy: 0.5645161290322581
Delta: 0.0010864039578594772 	  Loss: 1.053270917443539 	 Accuracy: 0.5645161290322581
Delta: 0.0013860576512538549 	  Loss: 1.0532590526900134 	 Accuracy: 0.5645161290322581
Delta: 0.0012170877635358257 	  Loss: 1.0532557323988527 	 Accuracy: 0.5645161290322581
Delta: 0.0008219310869321871 	  Loss: 1.0532512172004351 	 Accuracy: 0.5645161290322581
Delta: 0.0014680140323412461 	  Loss: 1.0532496440263959 	 Accuracy: 0.5645161290322581
Delta: 0.0018020960294938418 	  Loss: 1.053246586514249 	 Accuracy: 0.5645161290322581
Delta: 0.002546510521039037 	  Loss: 1.0532398047405538 	 Accuracy: 0.5645161290322581
Delta: 0.0015236683440309666 	  Loss: 1.0532438339726837 	 Accuracy: 0.5645161290322581
Delta: 0.0012267864954548654 	  Loss: 1.0532389963585076 	 Accuracy: 0.5645161290322581
Delta: 0.0018086249365021896 	  Loss: 1.0532288304179707 	 Accuracy: 0.5645161290322581
Delta: 0.0014611733031547666 	  Loss: 1.0532126543109932 	 Accuracy: 0.5645161290322581
Delta: 0.001303700108334571 	  Loss: 1.053205735951519 	 Accuracy: 0.5645161290322581
Delta: 0.0014075055910836196 	  Loss: 1.053198584748763 	 Accuracy: 0.5645161290322581
Delta: 0.0011301077782570666 	  Loss: 1.0531897309276985 	 Accuracy: 0.5645161290322581
Delta: 0.0007105704037123108 	  Loss: 1.0531826618874305 	 Accuracy: 0.5645161290322581
Delta: 0.00051370441851062 	  Loss: 1.0531775661452358 	 Accuracy: 0.5645161290322581
Delta: 0.00068704543442719 	  Loss: 1.0531772183330905 	 Accuracy: 0.5645161290322581
Delta: 0.0005691077453311968 	  Loss: 1.0531788278255207 	 Accuracy: 0.5645161290322581
Delta: 0.00041644051745163044 	  Loss: 1.0531754036342944 	 Accuracy: 0.5645161290322581
Delta: 0.0007711596856502147 	  Loss: 1.0531713079089686 	 Accuracy: 0.5645161290322581
Delta: 0.00045230772142923546 	  Loss: 1.0531723116155813 	 Accuracy: 0.5645161290322581
Delta: 0.001168832547118844 	  Loss: 1.0531709897829047 	 Accuracy: 0.5645161290322581
Delta: 0.0008661335111288271 	  Loss: 1.053165245977838 	 Accuracy: 0.5645161290322581
Delta: 0.000653738317421904 	  Loss: 1.0531674842853853 	 Accuracy: 0.5645161290322581
Delta: 0.0010388211458541956 	  Loss: 1.0531637900630455 	 Accuracy: 0.5645161290322581
Delta: 0.0012758046803785141 	  Loss: 1.0531628287796615 	 Accuracy: 0.5645161290322581
Delta: 0.0004958370252779808 	  Loss: 1.0531637561866871 	 Accuracy: 0.5645161290322581
Delta: 0.0005361842145554119 	  Loss: 1.0531612850077234 	 Accuracy: 0.5645161290322581
Delta: 0.00033545186321155894 	  Loss: 1.0531590738485213 	 Accuracy: 0.5645161290322581
Delta: 0.0002779123979120746 	  Loss: 1.0531585691363363 	 Accuracy: 0.5645161290322581
Delta: 0.00035398079708272377 	  Loss: 1.0531568514648608 	 Accuracy: 0.5645161290322581
Delta: 0.0005077066920326262 	  Loss: 1.0531532366036316 	 Accuracy: 0.5645161290322581
Delta: 0.0003329340027448573 	  Loss: 1.0531530904651816 	 Accuracy: 0.5645161290322581
Delta: 0.0002565720474020267 	  Loss: 1.0531491942306963 	 Accuracy: 0.5645161290322581
Delta: 0.0007508861138850279 	  Loss: 1.0531462707367887 	 Accuracy: 0.5645161290322581
Delta: 0.0009715805454554977 	  Loss: 1.0531491039577476 	 Accuracy: 0.5645161290322581
Delta: 0.0005986377528254763 	  Loss: 1.0531543018438543 	 Accuracy: 0.5645161290322581
Delta: 7.486841415509813e-05 	  Loss: 1.053157577212592 	 Accuracy: 0.5645161290322581
Delta: 2.4930894607445888e-06 	  Loss: 1.05315743959502 	 Accuracy: 0.5645161290322581
Delta: 2.0672532501668008e-17 	  Loss: 1.05315743959502 	 Accuracy: 0.5645161290322581
converged at iter  76
Delta: 0.060714234587689736 	  Loss: 1.0768237268958911 	 Accuracy: 0.2857142857142857
Delta: 0.04319783297524771 	  Loss: 1.070968188034474 	 Accuracy: 0.19047619047619047
Delta: 0.03530346839205317 	  Loss: 1.0648634789439178 	 Accuracy: 0.2222222222222222

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.03277734649555847 	  Loss: 1.0592097492539438 	 Accuracy: 0.2222222222222222
Delta: 0.02247484475514736 	  Loss: 1.0549104469432748 	 Accuracy: 0.2222222222222222
Delta: 0.017588918207146087 	  Loss: 1.05282605632852 	 Accuracy: 0.2222222222222222
Delta: 0.012821563091411648 	  Loss: 1.0516250752016354 	 Accuracy: 0.23809523809523808
Delta: 0.008860368220225106 	  Loss: 1.0511475590747976 	 Accuracy: 0.23809523809523808
Delta: 0.006275681706864829 	  Loss: 1.0509820366491873 	 Accuracy: 0.23809523809523808
Delta: 0.005170458180986267 	  Loss: 1.0508878042369283 	 Accuracy: 0.23809523809523808
Delta: 0.00560142555609936 	  Loss: 1.0507891393793405 	 Accuracy: 0.23809523809523808
Delta: 0.004633221299055195 	  Loss: 1.0506858485030857 	 Accuracy: 0.23809523809523808
Delta: 0.003458702066429371 	  Loss: 1.0506454988645335 	 Accuracy: 0.23809523809523808
Delta: 0.0027086864815585644 	  Loss: 1.0506357612444717 	 Accuracy: 0.23809523809523808
Delta: 0.0017539640446380784 	  Loss: 1.0506417323290247 	 Accuracy: 0.23809523809523808
Delta: 0.002220995940758072 	  Loss: 1.0506459664983714 	 Accuracy: 0.23809523809523808
Delta: 0.0020838971538247263 	  Loss: 1.0506418113080704 	 Accuracy: 0.23809523809523808
Delta: 0.0013183453789817198 	  Loss: 1.0506387941527282 	 Accuracy: 0.23809523809523808
Delta: 0.0010554053320828635 	  Loss: 1.0506328996323835 	 Accuracy: 0.23809523809523808
Delta: 0.0014757062089859065 	  Loss: 1.0506247246466267 	 Accuracy: 0.23809523809523808
Delta: 0.0017029790578939822 	  Loss: 1.0506269690211127 	 Accuracy: 0.23809523809523808
Delta: 0.001337692761457555 	  Loss: 1.0506214670420766 	 Accuracy: 0.23809523809523808
Delta: 0.0020343712635080132 	  Loss: 1.0506122259281407 	 Accuracy: 0.23809523809523808
Delta: 0.0020209748127675707 	  Loss: 1.0505732405179828 	 Accuracy: 0.23809523809523808
Delta: 0.0025305301671562077 	  Loss: 1.0505477151519738 	 Accuracy: 0.23809523809523808
Delta: 0.0018747436247901128 	  Loss: 1.0505082529596241 	 Accuracy: 0.23809523809523808
Delta: 0.0018377999040299232 	  Loss: 1.050479702410613 	 Accuracy: 0.23809523809523808
Delta: 0.0016148620833956405 	  Loss: 1.0504701646000596 	 Accuracy: 0.23809523809523808
Delta: 0.0015004104466053644 	  Loss: 1.0504604656449463 	 Accuracy: 0.23809523809523808
Delta: 0.0024258087789215525 	  Loss: 1.0504427519481656 	 Accuracy: 0.23809523809523808
Delta: 0.0023836389279334813 	  Loss: 1.0504187043134365 	 Accuracy: 0.23809523809523808
Delta: 0.0029956472777064418 	  Loss: 1.0503853657515643 	 Accuracy: 0.23809523809523808
Delta: 0.002304987388519283 	  Loss: 1.0503531860097337 	 Accuracy: 0.23809523809523808
Delta: 0.0035692931951267384 	  Loss: 1.0503390394220966 	 Accuracy: 0.23809523809523808
Delta: 0.0030855297098119116 	  Loss: 1.0503112491194835 	 Accuracy: 0.23809523809523808
Delta: 0.0033182372332031516 	  Loss: 1.0502912545434184 	 Accuracy: 0.23809523809523808
Delta: 0.002801219614054668 	  Loss: 1.0502523857635688 	 Accuracy: 0.23809523809523808
Delta: 0.003417265998810211 	  Loss: 1.050234459809332 	 Accuracy: 0.23809523809523808
Delta: 0.003991112017225609 	  Loss: 1.0502040050998909 	 Accuracy: 0.23809523809523808
Delta: 0.00398937560118272 	  Loss: 1.050169382387443 	 Accuracy: 0.23809523809523808
Delta: 0.002626692393664781 	  Loss: 1.0501434908402936 	 Accuracy: 0.23809523809523808
Delta: 0.003694830910683059 	  Loss: 1.0501115321385837 	 Accuracy: 0.23809523809523808
Delta: 0.003888147792600985 	  Loss: 1.0500854879398975 	 Accuracy: 0.23809523809523808
Delta: 0.003436574850702023 	  Loss: 1.0500472528574614 	 Accuracy: 0.23809523809523808
Delta: 0.0033093249937022635 	  Loss: 1.0499714825778939 	 Accuracy: 0.23809523809523808
Delta: 0.0031881581621307125 	  Loss: 1.049915484837287 	 Accuracy: 0.23809523809523808
Delta: 0.0029516334216028645 	  Loss: 1.0498755160593476 	 Accuracy: 0.23809523809523808
Delta: 0.0024368163864839326 	  Loss: 1.0498575002426271 	 Accuracy: 0.23809523809523808
Delta: 0.002190759785266225 	  Loss: 1.0498403580856346 	 Accuracy: 0.23809523809523808
Delta: 0.0018687972520522187 	  Loss: 1.0498183573921533 	 Accuracy: 0.23809523809523808
Delta: 0.0019050863788667289 	  Loss: 1.0498141899370999 	 Accuracy: 0.23809523809523808
Delta: 0.0012483661525209892 	  Loss: 1.0498157974456253 	 Accuracy: 0.23809523809523808
Delta: 0.0018956005676102573 	  Loss: 1.0498239231034168 	 Accuracy: 0.23809523809523808
Delta: 0.0026793024397972678 	  Loss: 1.0498227022819884 	 Accuracy: 0.23809523809523808
Delta: 0.0014806129111703593 	  Loss: 1.0498318135277915 	 Accuracy: 0.23809523809523808
Delta: 0.0006503102735545803 	  Loss: 1.049836440995933 	 Accuracy: 0.23809523809523808
Delta: 0.0007199388136181811 	  Loss: 1.0498324645948163 	 Accuracy: 0.23809523809523808
Delta: 0.0004433648752090773 	  Loss: 1.0498295190601787 	 Accuracy: 0.23809523809523808
Delta: 0.0005298073342478713 	  Loss: 1.0498274602411577 	 Accuracy: 0.23809523809523808
Delta: 0.0009104430175606625 	  Loss: 1.0498260702663735 	 Accuracy: 0.23809523809523808
Delta: 0.0003791054868216228 	  Loss: 1.0498257961268815 	 Accuracy: 0.23809523809523808
Delta: 0.0006738849908981653 	  Loss: 1.0498257151008836 	 Accuracy: 0.23809523809523808
converged at iter  61
Delta: 0.06073092597499016 	  Loss: 1.0631269351507693 	 Accuracy: 0.19047619047619047
Delta: 0.04637409499746829 	  Loss: 1.0558818374900816 	 Accuracy: 0.25396825396825395
Delta: 0.036327427320683725 	  Loss: 1.0487265648424304 	 Accuracy: 0.2698412698412698

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.026646146173905504 	  Loss: 1.0431837159322654 	 Accuracy: 0.2857142857142857
Delta: 0.017660347479516572 	  Loss: 1.0404061848203514 	 Accuracy: 0.2857142857142857
Delta: 0.013159348396450667 	  Loss: 1.039313438042734 	 Accuracy: 0.2857142857142857
Delta: 0.013651214311353126 	  Loss: 1.0384476665580942 	 Accuracy: 0.2857142857142857
Delta: 0.01323952733858066 	  Loss: 1.0374948807493094 	 Accuracy: 0.2857142857142857
Delta: 0.011547933166636683 	  Loss: 1.0367035781534333 	 Accuracy: 0.2857142857142857
Delta: 0.009835870179412759 	  Loss: 1.0362158788014173 	 Accuracy: 0.2857142857142857
Delta: 0.008534822847857483 	  Loss: 1.0359201908683535 	 Accuracy: 0.2857142857142857
Delta: 0.006153843824201774 	  Loss: 1.035754929586981 	 Accuracy: 0.2857142857142857
Delta: 0.0059526696033000434 	  Loss: 1.0357121673756087 	 Accuracy: 0.2857142857142857
Delta: 0.005020084282451272 	  Loss: 1.0357362951482416 	 Accuracy: 0.2857142857142857
Delta: 0.005667995026278229 	  Loss: 1.0357345366643713 	 Accuracy: 0.2857142857142857
Delta: 0.0056566088386317106 	  Loss: 1.0357425941079443 	 Accuracy: 0.2857142857142857
Delta: 0.0061771883467530595 	  Loss: 1.035740881560865 	 Accuracy: 0.2857142857142857
Delta: 0.004664910745066584 	  Loss: 1.0357180520079774 	 Accuracy: 0.2857142857142857
Delta: 0.004239909811896529 	  Loss: 1.0357033194990182 	 Accuracy: 0.2857142857142857
Delta: 0.003916473142964496 	  Loss: 1.035694687077791 	 Accuracy: 0.2857142857142857
Delta: 0.00340335368609787 	  Loss: 1.0356883956986267 	 Accuracy: 0.2857142857142857
Delta: 0.004082073815046905 	  Loss: 1.035669039146125 	 Accuracy: 0.2857142857142857
Delta: 0.0034616882235370666 	  Loss: 1.035632003994047 	 Accuracy: 0.2857142857142857
Delta: 0.0023956988322892674 	  Loss: 1.035604932752567 	 Accuracy: 0.2857142857142857
Delta: 0.0021646664934394516 	  Loss: 1.0355877014692747 	 Accuracy: 0.2857142857142857
Delta: 0.001704672359836733 	  Loss: 1.0355561577810526 	 Accuracy: 0.2857142857142857
Delta: 0.0024958704559604602 	  Loss: 1.0355368709185462 	 Accuracy: 0.2857142857142857
Delta: 0.0018063741693598772 	  Loss: 1.0355480999278064 	 Accuracy: 0.2857142857142857
Delta: 0.0019467371015476432 	  Loss: 1.0355439913292865 	 Accuracy: 0.2857142857142857
Delta: 0.002214292544772667 	  Loss: 1.0355508560866984 	 Accuracy: 0.2857142857142857
Delta: 0.0023252378420954758 	  Loss: 1.0355596751457004 	 Accuracy: 0.2857142857142857
Delta: 0.0030350825131802766 	  Loss: 1.0355631643909537 	 Accuracy: 0.2857142857142857
Delta: 0.0031878233871291705 	  Loss: 1.035554660577299 	 Accuracy: 0.2857142857142857
Delta: 0.0029632007691330065 	  Loss: 1.035522064226476 	 Accuracy: 0.2857142857142857
Delta: 0.003040055720329651 	  Loss: 1.035473802703188 	 Accuracy: 0.2857142857142857
Delta: 0.0023107021216650517 	  Loss: 1.0354478588972205 	 Accuracy: 0.2857142857142857
Delta: 0.002732499351673385 	  Loss: 1.0354413567618657 	 Accuracy: 0.2857142857142857
Delta: 0.0027908728021922183 	  Loss: 1.0354390045951036 	 Accuracy: 0.2857142857142857
Delta: 0.0022820148250263126 	  Loss: 1.0354286968187276 	 Accuracy: 0.2857142857142857
Delta: 0.0022607214038153447 	  Loss: 1.0354340383590497 	 Accuracy: 0.2857142857142857
Delta: 0.0025114633575409784 	  Loss: 1.0354173296463103 	 Accuracy: 0.2857142857142857
Delta: 0.0017838062661917086 	  Loss: 1.0353963565837694 	 Accuracy: 0.2857142857142857
Delta: 0.0014906649596265467 	  Loss: 1.0353857755381068 	 Accuracy: 0.2857142857142857
Delta: 0.0016797210181670288 	  Loss: 1.0353681578741099 	 Accuracy: 0.2857142857142857
Delta: 0.0012656684657377845 	  Loss: 1.0353520300281323 	 Accuracy: 0.2857142857142857
Delta: 0.0012757401576551112 	  Loss: 1.0353435687547823 	 Accuracy: 0.2857142857142857
Delta: 0.0013189951110600614 	  Loss: 1.0353296303881678 	 Accuracy: 0.2857142857142857
Delta: 0.0018525096033765124 	  Loss: 1.0353223470734951 	 Accuracy: 0.2857142857142857
Delta: 0.0023835218335706353 	  Loss: 1.0353050126899241 	 Accuracy: 0.2857142857142857
Delta: 0.0018303804684534303 	  Loss: 1.035306165698347 	 Accuracy: 0.2857142857142857
Delta: 0.0008559344484826185 	  Loss: 1.0353148246313157 	 Accuracy: 0.2857142857142857
Delta: 0.0005684979697667122 	  Loss: 1.035311865291256 	 Accuracy: 0.2857142857142857
Delta: 0.0008787299485783026 	  Loss: 1.035308662539533 	 Accuracy: 0.2857142857142857
Delta: 0.0009059044699373743 	  Loss: 1.0353076330036712 	 Accuracy: 0.2857142857142857
Delta: 0.0009637225696327653 	  Loss: 1.0353057834843964 	 Accuracy: 0.2857142857142857
Delta: 0.0004949150041699021 	  Loss: 1.035299156811837 	 Accuracy: 0.2857142857142857
Delta: 9.590869663370422e-05 	  Loss: 1.0352982106081756 	 Accuracy: 0.2857142857142857
Delta: 6.3144961887383675e-06 	  Loss: 1.0352981768418577 	 Accuracy: 0.2857142857142857
converged at iter  57
Delta: 0.059236014071071194 	  Loss: 1.0625026625257918 	 Accuracy: 0.532258064516129
Delta: 0.04079031114540814 	  Loss: 1.0513720229730321 	 Accuracy: 0.5483870967741935
Delta: 0.042171422600805746 	  Loss: 1.0502629723538857 	 Accuracy: 0.5806451612903226
Delta: 0.03648712461642304 	  Loss: 1.046064255524755 	 Accuracy: 0.5806451612903226

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02231610603683061 	  Loss: 1.0408610392011979 	 Accuracy: 0.5645161290322581
Delta: 0.014884048535100659 	  Loss: 1.0387149928565145 	 Accuracy: 0.5645161290322581
Delta: 0.011073793162103121 	  Loss: 1.0379313264426824 	 Accuracy: 0.5645161290322581
Delta: 0.010330771307481284 	  Loss: 1.0374352862512495 	 Accuracy: 0.5645161290322581
Delta: 0.009889902350779023 	  Loss: 1.0369788701162377 	 Accuracy: 0.5645161290322581
Delta: 0.007553244042414732 	  Loss: 1.036625039749857 	 Accuracy: 0.5645161290322581
Delta: 0.007236797515575012 	  Loss: 1.036398195957687 	 Accuracy: 0.5645161290322581
Delta: 0.004943639903166548 	  Loss: 1.0361554760136604 	 Accuracy: 0.5645161290322581
Delta: 0.003966463597359041 	  Loss: 1.036057473800759 	 Accuracy: 0.5645161290322581
Delta: 0.002913431509630252 	  Loss: 1.0359966531710039 	 Accuracy: 0.5645161290322581
Delta: 0.0026246227495088613 	  Loss: 1.0359474033167662 	 Accuracy: 0.5645161290322581
Delta: 0.0021314511655420505 	  Loss: 1.0359185548602587 	 Accuracy: 0.5645161290322581
Delta: 0.002299632786537074 	  Loss: 1.0359185183540967 	 Accuracy: 0.5645161290322581
converged at iter  16
Delta: 0.05854368324452395 	  Loss: 1.0675822696257669 	 Accuracy: 0.5967741935483871
Delta: 0.04338581457851726 	  Loss: 1.0629406718245615 	 Accuracy: 0.41935483870967744
Delta: 0.03325963081728771 	  Loss: 1.0560967055040398 	 Accuracy: 0.3870967741935484

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.023839990885079515 	  Loss: 1.0509662064737015 	 Accuracy: 0.3870967741935484
Delta: 0.016575960843608312 	  Loss: 1.04907301925877 	 Accuracy: 0.3870967741935484
Delta: 0.013822858171506339 	  Loss: 1.0480405971261022 	 Accuracy: 0.3870967741935484
Delta: 0.01316554108015014 	  Loss: 1.0472726563288883 	 Accuracy: 0.3870967741935484
Delta: 0.012240821066335207 	  Loss: 1.0466006446205798 	 Accuracy: 0.3870967741935484
Delta: 0.009567060408301397 	  Loss: 1.0460702182884987 	 Accuracy: 0.3870967741935484
Delta: 0.008295273341891604 	  Loss: 1.0457855947318917 	 Accuracy: 0.3870967741935484
Delta: 0.007716065341525422 	  Loss: 1.0455524605519226 	 Accuracy: 0.3870967741935484
Delta: 0.006598961958863277 	  Loss: 1.045392559674298 	 Accuracy: 0.3870967741935484
Delta: 0.0065790440415292905 	  Loss: 1.0452723599265803 	 Accuracy: 0.3870967741935484
Delta: 0.00575028673493343 	  Loss: 1.0451501083335222 	 Accuracy: 0.3870967741935484
Delta: 0.005477104898629878 	  Loss: 1.0450877144502067 	 Accuracy: 0.3870967741935484
Delta: 0.005084101203301475 	  Loss: 1.045029751510058 	 Accuracy: 0.3870967741935484
Delta: 0.0038534430863638247 	  Loss: 1.0450010487503731 	 Accuracy: 0.3870967741935484
Delta: 0.00370135915626741 	  Loss: 1.0449872449321571 	 Accuracy: 0.3870967741935484
Delta: 0.003834363740552753 	  Loss: 1.0449352902482443 	 Accuracy: 0.3870967741935484
Delta: 0.003364819483124095 	  Loss: 1.0448586101418398 	 Accuracy: 0.3870967741935484
Delta: 0.003284967005582435 	  Loss: 1.0447974952240202 	 Accuracy: 0.3870967741935484
Delta: 0.0028602961875397494 	  Loss: 1.0447425573429976 	 Accuracy: 0.3870967741935484
Delta: 0.003592442864745405 	  Loss: 1.0447007092406375 	 Accuracy: 0.3870967741935484
Delta: 0.004215925000120541 	  Loss: 1.0446651604346724 	 Accuracy: 0.3870967741935484
Delta: 0.0029711647682879663 	  Loss: 1.044648193629249 	 Accuracy: 0.3870967741935484
Delta: 0.0028679294805093116 	  Loss: 1.044613125866739 	 Accuracy: 0.3870967741935484
Delta: 0.0024091205992033365 	  Loss: 1.0445835157158325 	 Accuracy: 0.3870967741935484
Delta: 0.002402437985622184 	  Loss: 1.044582083327862 	 Accuracy: 0.3870967741935484
Delta: 0.0012596800717764019 	  Loss: 1.044574585872975 	 Accuracy: 0.3870967741935484
Delta: 0.0010530413184326327 	  Loss: 1.044569814885779 	 Accuracy: 0.3870967741935484
Delta: 0.0017367995726788113 	  Loss: 1.0445656209346406 	 Accuracy: 0.3870967741935484
Delta: 0.0020670335755475443 	  Loss: 1.0445692928115298 	 Accuracy: 0.3870967741935484
Delta: 0.001782544120319866 	  Loss: 1.044588843413711 	 Accuracy: 0.3870967741935484
Delta: 0.001952331569763337 	  Loss: 1.0446054620459613 	 Accuracy: 0.3870967741935484
Delta: 0.002259497800604435 	  Loss: 1.0446091879390522 	 Accuracy: 0.3870967741935484
Delta: 0.0017185202031129137 	  Loss: 1.0446229083439975 	 Accuracy: 0.3870967741935484
Delta: 0.0021631290534864377 	  Loss: 1.0446355566191974 	 Accuracy: 0.3870967741935484
Delta: 0.001987291177326457 	  Loss: 1.0446515813180377 	 Accuracy: 0.3870967741935484
Delta: 0.0012633928823332899 	  Loss: 1.0446582866469818 	 Accuracy: 0.3870967741935484
Delta: 0.0010561934328381822 	  Loss: 1.0446559871021335 	 Accuracy: 0.3870967741935484
Delta: 0.0017494603310320655 	  Loss: 1.0446540737147374 	 Accuracy: 0.3870967741935484
Delta: 0.0009380858874070667 	  Loss: 1.044648669438294 	 Accuracy: 0.3870967741935484
Delta: 0.0010661987840724382 	  Loss: 1.044644871031359 	 Accuracy: 0.3870967741935484
Delta: 0.0008860175879228848 	  Loss: 1.0446402615125456 	 Accuracy: 0.3870967741935484
Delta: 0.0014296086569563207 	  Loss: 1.0446443734339377 	 Accuracy: 0.3870967741935484
Delta: 0.002018172713929856 	  Loss: 1.0446422274712026 	 Accuracy: 0.3870967741935484
Delta: 0.001961314513896163 	  Loss: 1.0446524557325039 	 Accuracy: 0.3870967741935484
Delta: 0.0014598476635613886 	  Loss: 1.0446507520125108 	 Accuracy: 0.3870967741935484
Delta: 0.0021687366547419157 	  Loss: 1.0446464429028022 	 Accuracy: 0.3870967741935484
Delta: 0.0016756766461285787 	  Loss: 1.0446522830828529 	 Accuracy: 0.3870967741935484
Delta: 0.0014649575420380488 	  Loss: 1.04464515650018 	 Accuracy: 0.3870967741935484
Delta: 0.002191665858298538 	  Loss: 1.0446339268667024 	 Accuracy: 0.3870967741935484
Delta: 0.0018172202098028075 	  Loss: 1.0446261562793768 	 Accuracy: 0.3870967741935484
Delta: 0.002219386234284989 	  Loss: 1.0446097638496652 	 Accuracy: 0.3870967741935484
Delta: 0.0027638931484125664 	  Loss: 1.0445846201760234 	 Accuracy: 0.3870967741935484
Delta: 0.003220259039147559 	  Loss: 1.0445698361904827 	 Accuracy: 0.3870967741935484
Delta: 0.0031539773806692735 	  Loss: 1.0445508621957384 	 Accuracy: 0.3870967741935484
Delta: 0.0037413993655400156 	  Loss: 1.0444878539734965 	 Accuracy: 0.3870967741935484
Delta: 0.004246503273582093 	  Loss: 1.0444664230789833 	 Accuracy: 0.3870967741935484
Delta: 0.004074613068221577 	  Loss: 1.0444178304982 	 Accuracy: 0.3870967741935484
Delta: 0.004225316781962726 	  Loss: 1.0443932878808986 	 Accuracy: 0.3870967741935484
Delta: 0.0038018653857572063 	  Loss: 1.0443770577905025 	 Accuracy: 0.3870967741935484
Delta: 0.00359652197534997 	  Loss: 1.0443287623256117 	 Accuracy: 0.3870967741935484
Delta: 0.0037685529316473804 	  Loss: 1.044279817086951 	 Accuracy: 0.3870967741935484
Delta: 0.005103147056799934 	  Loss: 1.0442507911959331 	 Accuracy: 0.3870967741935484
Delta: 0.004422114198739747 	  Loss: 1.0441795781393282 	 Accuracy: 0.3870967741935484
Delta: 0.0043857717998305856 	  Loss: 1.044154415541529 	 Accuracy: 0.3870967741935484
Delta: 0.0031681940817437715 	  Loss: 1.0441355372188135 	 Accuracy: 0.3870967741935484
Delta: 0.003456464623420091 	  Loss: 1.0441376926485377 	 Accuracy: 0.3870967741935484
Delta: 0.003645434560586976 	  Loss: 1.0441073588455505 	 Accuracy: 0.3870967741935484
Delta: 0.0029665628218184257 	  Loss: 1.0440445369432851 	 Accuracy: 0.3870967741935484
Delta: 0.00339061032797597 	  Loss: 1.0440017486463158 	 Accuracy: 0.3870967741935484
Delta: 0.002098383684978365 	  Loss: 1.043984512098993 	 Accuracy: 0.3870967741935484
Delta: 0.0015347964065396495 	  Loss: 1.0439825826973943 	 Accuracy: 0.3870967741935484
Delta: 0.0024310387789168424 	  Loss: 1.043981644407142 	 Accuracy: 0.3870967741935484
Delta: 0.002670741046635418 	  Loss: 1.043959211299117 	 Accuracy: 0.3870967741935484
Delta: 0.0036550514850256736 	  Loss: 1.0439159050766493 	 Accuracy: 0.3870967741935484
Delta: 0.0035030715503446106 	  Loss: 1.0438509416591828 	 Accuracy: 0.3870967741935484
Delta: 0.0041236318464092595 	  Loss: 1.0437856343271636 	 Accuracy: 0.3870967741935484
Delta: 0.0043149975614037005 	  Loss: 1.0437139067497503 	 Accuracy: 0.3870967741935484
Delta: 0.004316246996145266 	  Loss: 1.0436738754853234 	 Accuracy: 0.3870967741935484
Delta: 0.005424834872942534 	  Loss: 1.043624927576987 	 Accuracy: 0.3870967741935484
Delta: 0.006441519138580813 	  Loss: 1.0435616950587474 	 Accuracy: 0.3870967741935484
Delta: 0.007219804308033399 	  Loss: 1.0434226920125944 	 Accuracy: 0.3870967741935484
Delta: 0.007748303858150751 	  Loss: 1.0432180897953311 	 Accuracy: 0.3870967741935484
Delta: 0.006754530300215541 	  Loss: 1.043002721424029 	 Accuracy: 0.3870967741935484
Delta: 0.006358188896116396 	  Loss: 1.0428467355744473 	 Accuracy: 0.3870967741935484
Delta: 0.00605605306084202 	  Loss: 1.0427385754316414 	 Accuracy: 0.3870967741935484
Delta: 0.005452683329118667 	  Loss: 1.0426230802062553 	 Accuracy: 0.3870967741935484
Delta: 0.005080722213459225 	  Loss: 1.042519265359163 	 Accuracy: 0.3870967741935484
Delta: 0.005392495071691466 	  Loss: 1.0424170811263087 	 Accuracy: 0.3870967741935484
Delta: 0.0034299820944110257 	  Loss: 1.0423346305865646 	 Accuracy: 0.3870967741935484
Delta: 0.0032963625070107348 	  Loss: 1.0423003829255282 	 Accuracy: 0.3870967741935484
Delta: 0.0027091279109158384 	  Loss: 1.0422601806871037 	 Accuracy: 0.3870967741935484
Delta: 0.002372810932077023 	  Loss: 1.042260236715565 	 Accuracy: 0.3870967741935484
converged at iter  94
Delta: 0.060516014631476586 	  Loss: 1.0781189806764178 	 Accuracy: 0.22580645161290322
Delta: 0.04615189054224332 	  Loss: 1.0757692993194223 	 Accuracy: 0.16129032258064516
Delta: 0.035420194902052435 	  Loss: 1.0727541396126867 	 Accuracy: 0.16129032258064516
Delta: 0.026168373085703432 	  Loss: 1.069297008431064 	 Accuracy: 0.14516129032258066

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02226280940034967 	  Loss: 1.0680819288665755 	 Accuracy: 0.14516129032258066
Delta: 0.0153618382710105 	  Loss: 1.0668672175254184 	 Accuracy: 0.14516129032258066
Delta: 0.013140037857341979 	  Loss: 1.0660610075255057 	 Accuracy: 0.14516129032258066
Delta: 0.010615049648649665 	  Loss: 1.0654327487515731 	 Accuracy: 0.14516129032258066
Delta: 0.010205484955559981 	  Loss: 1.0649082640215646 	 Accuracy: 0.14516129032258066
Delta: 0.008954951215328872 	  Loss: 1.0643548822618083 	 Accuracy: 0.14516129032258066
Delta: 0.009890193741703702 	  Loss: 1.0639591585261825 	 Accuracy: 0.14516129032258066
Delta: 0.00802869277200628 	  Loss: 1.0635242532542564 	 Accuracy: 0.14516129032258066
Delta: 0.0059815250000518645 	  Loss: 1.0633085342451 	 Accuracy: 0.14516129032258066
Delta: 0.005800747732305711 	  Loss: 1.063186762217413 	 Accuracy: 0.14516129032258066
Delta: 0.005715297585244084 	  Loss: 1.0631065853934365 	 Accuracy: 0.14516129032258066
Delta: 0.004663771558248475 	  Loss: 1.0630132324888755 	 Accuracy: 0.14516129032258066
Delta: 0.004743959260228942 	  Loss: 1.0629887806214708 	 Accuracy: 0.14516129032258066
Delta: 0.005141488052029518 	  Loss: 1.0629427281306716 	 Accuracy: 0.14516129032258066
Delta: 0.005327018427408947 	  Loss: 1.0628953186040433 	 Accuracy: 0.14516129032258066
Delta: 0.0058734607713244544 	  Loss: 1.0628282762385552 	 Accuracy: 0.14516129032258066
Delta: 0.008947043816629231 	  Loss: 1.0627203718916742 	 Accuracy: 0.14516129032258066
Delta: 0.009397623851013252 	  Loss: 1.0624542532203765 	 Accuracy: 0.14516129032258066
Delta: 0.010698124529062575 	  Loss: 1.0619915931572184 	 Accuracy: 0.14516129032258066
Delta: 0.009854331962718031 	  Loss: 1.0615387007178945 	 Accuracy: 0.14516129032258066
Delta: 0.009882245479463958 	  Loss: 1.0610501068934854 	 Accuracy: 0.14516129032258066
Delta: 0.009346701259703273 	  Loss: 1.0606075563451522 	 Accuracy: 0.14516129032258066
Delta: 0.008778262101562372 	  Loss: 1.0602476504300045 	 Accuracy: 0.14516129032258066
Delta: 0.006370780783743197 	  Loss: 1.059946980748717 	 Accuracy: 0.14516129032258066
Delta: 0.005049290063748332 	  Loss: 1.059799665818085 	 Accuracy: 0.14516129032258066
Delta: 0.004000690300075357 	  Loss: 1.0596974057104407 	 Accuracy: 0.14516129032258066
Delta: 0.002718784721077446 	  Loss: 1.0596451718769138 	 Accuracy: 0.14516129032258066
Delta: 0.0017858449516858768 	  Loss: 1.0596167075083733 	 Accuracy: 0.14516129032258066
Delta: 0.0021723261780116072 	  Loss: 1.0596079822647226 	 Accuracy: 0.14516129032258066
Delta: 0.001243577145894678 	  Loss: 1.0595907495071342 	 Accuracy: 0.14516129032258066
Delta: 0.0008616490614187899 	  Loss: 1.059574522238659 	 Accuracy: 0.14516129032258066
Delta: 0.0012088698547585933 	  Loss: 1.0595695163175134 	 Accuracy: 0.14516129032258066
Delta: 0.0008252073919818332 	  Loss: 1.0595614910515485 	 Accuracy: 0.14516129032258066
Delta: 0.0014968379348061927 	  Loss: 1.059561406635312 	 Accuracy: 0.14516129032258066
converged at iter  37
Delta: 0.05798248429930586 	  Loss: 1.073811908912949 	 Accuracy: 0.4603174603174603
Delta: 0.04680276341936403 	  Loss: 1.0743451559722947 	 Accuracy: 0.4444444444444444

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.03238034128744912 	  Loss: 1.0673838894224328 	 Accuracy: 0.4126984126984127
Delta: 0.0216548764337305 	  Loss: 1.063207221198238 	 Accuracy: 0.4126984126984127
Delta: 0.01759114226576063 	  Loss: 1.0613694033351306 	 Accuracy: 0.4126984126984127
Delta: 0.014079979313498728 	  Loss: 1.0600396449596579 	 Accuracy: 0.4126984126984127
Delta: 0.01238129836257375 	  Loss: 1.0590712200189487 	 Accuracy: 0.4126984126984127
Delta: 0.012218413166363497 	  Loss: 1.0582346182351565 	 Accuracy: 0.4126984126984127
Delta: 0.011415419174272533 	  Loss: 1.0575862351637517 	 Accuracy: 0.4126984126984127
Delta: 0.00990240519856918 	  Loss: 1.0569968448152112 	 Accuracy: 0.4126984126984127
Delta: 0.008407452203805251 	  Loss: 1.056597970259113 	 Accuracy: 0.4126984126984127
Delta: 0.006179126990430558 	  Loss: 1.0563228981174853 	 Accuracy: 0.4126984126984127
Delta: 0.0059436256165281524 	  Loss: 1.0561759852096233 	 Accuracy: 0.4126984126984127
Delta: 0.004699413762700838 	  Loss: 1.0560330603206656 	 Accuracy: 0.4126984126984127
Delta: 0.0038839115406015885 	  Loss: 1.0559469360839537 	 Accuracy: 0.4126984126984127
Delta: 0.0036502030106372423 	  Loss: 1.0558540640776461 	 Accuracy: 0.4126984126984127
Delta: 0.003585883837710152 	  Loss: 1.055798545344465 	 Accuracy: 0.4126984126984127
Delta: 0.003306176503648108 	  Loss: 1.0557307938977756 	 Accuracy: 0.4126984126984127
Delta: 0.0034398671262855876 	  Loss: 1.055678028757293 	 Accuracy: 0.4126984126984127
Delta: 0.0032415307163616404 	  Loss: 1.0556461576242149 	 Accuracy: 0.4126984126984127
Delta: 0.003699625650630577 	  Loss: 1.0556195954250711 	 Accuracy: 0.4126984126984127
Delta: 0.0030615140958049803 	  Loss: 1.0555618279262813 	 Accuracy: 0.4126984126984127
Delta: 0.00358355785155311 	  Loss: 1.0555099013147298 	 Accuracy: 0.4126984126984127
Delta: 0.0034160772165238293 	  Loss: 1.05544141305891 	 Accuracy: 0.4126984126984127
Delta: 0.0029090575176041068 	  Loss: 1.0553533841286653 	 Accuracy: 0.4126984126984127
Delta: 0.0031413084093771934 	  Loss: 1.0553058768319525 	 Accuracy: 0.4126984126984127
Delta: 0.003385365004818051 	  Loss: 1.055261650567819 	 Accuracy: 0.4126984126984127
Delta: 0.0023208211252866906 	  Loss: 1.0552166649014239 	 Accuracy: 0.4126984126984127
Delta: 0.0020553597377188666 	  Loss: 1.055189897910187 	 Accuracy: 0.4126984126984127
Delta: 0.0017738707664460272 	  Loss: 1.055159852815347 	 Accuracy: 0.4126984126984127
Delta: 0.0014574130035302601 	  Loss: 1.0551683574748751 	 Accuracy: 0.4126984126984127
Delta: 0.0014341681969068155 	  Loss: 1.0551651812739389 	 Accuracy: 0.4126984126984127
Delta: 0.0013481133580903184 	  Loss: 1.0551563282429202 	 Accuracy: 0.4126984126984127
Delta: 0.0008149753111624647 	  Loss: 1.0551447796690403 	 Accuracy: 0.4126984126984127
Delta: 0.0009563276036425713 	  Loss: 1.0551353532395442 	 Accuracy: 0.4126984126984127
Delta: 0.001161435504289201 	  Loss: 1.0551239997498814 	 Accuracy: 0.4126984126984127
Delta: 0.00139418341891059 	  Loss: 1.0551192590717733 	 Accuracy: 0.4126984126984127
Delta: 0.0007043809891260108 	  Loss: 1.0551158199567907 	 Accuracy: 0.4126984126984127
Delta: 0.0006811752678162866 	  Loss: 1.0551216035732183 	 Accuracy: 0.4126984126984127
Delta: 0.0007758424022817807 	  Loss: 1.055124744468893 	 Accuracy: 0.4126984126984127
Delta: 0.0005630637917311901 	  Loss: 1.0551267058330873 	 Accuracy: 0.4126984126984127
Delta: 0.00029329630824342137 	  Loss: 1.055128004156868 	 Accuracy: 0.4126984126984127
Delta: 0.0006267956257773362 	  Loss: 1.0551281005549809 	 Accuracy: 0.4126984126984127
converged at iter  42
Delta: 0.05782399612802296 	  Loss: 1.0590890701737545 	 Accuracy: 0.4603174603174603
Delta: 0.04731022749985147 	  Loss: 1.0573614529693187 	 Accuracy: 0.3968253968253968

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.04079311191755607 	  Loss: 1.0541806289424471 	 Accuracy: 0.30158730158730157
Delta: 0.024873016566664005 	  Loss: 1.049100270173802 	 Accuracy: 0.30158730158730157
Delta: 0.01864451228089903 	  Loss: 1.0460640379273038 	 Accuracy: 0.30158730158730157
Delta: 0.014126060577577128 	  Loss: 1.0445133612379514 	 Accuracy: 0.30158730158730157
Delta: 0.011271705073449228 	  Loss: 1.0437087595079888 	 Accuracy: 0.30158730158730157
Delta: 0.008456592653544837 	  Loss: 1.04312336200068 	 Accuracy: 0.30158730158730157
Delta: 0.0073668372195874 	  Loss: 1.042838029731678 	 Accuracy: 0.30158730158730157
Delta: 0.00709602308735616 	  Loss: 1.042682600001378 	 Accuracy: 0.30158730158730157
Delta: 0.007173702616760268 	  Loss: 1.042502745282053 	 Accuracy: 0.30158730158730157
Delta: 0.006745357231686726 	  Loss: 1.0423282663037303 	 Accuracy: 0.30158730158730157
Delta: 0.006403651424622914 	  Loss: 1.0421224472680186 	 Accuracy: 0.30158730158730157
Delta: 0.005722047663763935 	  Loss: 1.0419557828326702 	 Accuracy: 0.30158730158730157
Delta: 0.007253366376127466 	  Loss: 1.0417421602661647 	 Accuracy: 0.30158730158730157
Delta: 0.007143825351511546 	  Loss: 1.0414843748260891 	 Accuracy: 0.30158730158730157
Delta: 0.00979825776917051 	  Loss: 1.041211679213025 	 Accuracy: 0.30158730158730157
Delta: 0.011112669661507828 	  Loss: 1.0407555623797067 	 Accuracy: 0.30158730158730157
Delta: 0.012623466298900207 	  Loss: 1.0401485424248675 	 Accuracy: 0.30158730158730157
Delta: 0.01113035617818304 	  Loss: 1.0395241412875853 	 Accuracy: 0.30158730158730157
Delta: 0.008960814965495532 	  Loss: 1.0390707391640877 	 Accuracy: 0.30158730158730157
Delta: 0.007994554567910962 	  Loss: 1.0388096818243013 	 Accuracy: 0.30158730158730157
Delta: 0.007360890734411649 	  Loss: 1.0386651468191865 	 Accuracy: 0.30158730158730157
Delta: 0.005856659701861 	  Loss: 1.03856132984936 	 Accuracy: 0.30158730158730157
Delta: 0.005980169602337325 	  Loss: 1.0384231491944977 	 Accuracy: 0.30158730158730157
Delta: 0.0057611082330921715 	  Loss: 1.038259270337779 	 Accuracy: 0.30158730158730157
Delta: 0.00507618075644073 	  Loss: 1.0381264158477534 	 Accuracy: 0.30158730158730157
Delta: 0.004540780209504427 	  Loss: 1.0380103696553613 	 Accuracy: 0.30158730158730157
Delta: 0.0040047795229820864 	  Loss: 1.0379623890490488 	 Accuracy: 0.30158730158730157
Delta: 0.004240172234200666 	  Loss: 1.0378717867494152 	 Accuracy: 0.30158730158730157
Delta: 0.0040134400827020935 	  Loss: 1.037810622046858 	 Accuracy: 0.30158730158730157
Delta: 0.00350252705070905 	  Loss: 1.037782538303263 	 Accuracy: 0.30158730158730157
Delta: 0.0019821992040616413 	  Loss: 1.0377549891183793 	 Accuracy: 0.30158730158730157
Delta: 0.0015195699496502154 	  Loss: 1.0377465175038885 	 Accuracy: 0.30158730158730157
Delta: 0.001218735422304812 	  Loss: 1.0377384088106112 	 Accuracy: 0.30158730158730157
Delta: 0.0019401713085400946 	  Loss: 1.03773694993661 	 Accuracy: 0.30158730158730157
Delta: 0.0016375315008255455 	  Loss: 1.0377367675812663 	 Accuracy: 0.30158730158730157
Delta: 0.0012006692133462833 	  Loss: 1.0377291187867765 	 Accuracy: 0.30158730158730157
Delta: 0.0008452326531978924 	  Loss: 1.0377388541333263 	 Accuracy: 0.30158730158730157
Delta: 0.0010100047578755903 	  Loss: 1.0377414936925524 	 Accuracy: 0.30158730158730157
Delta: 0.0011417558014790354 	  Loss: 1.0377496984742849 	 Accuracy: 0.30158730158730157
Delta: 0.0014300757111954685 	  Loss: 1.037756837845776 	 Accuracy: 0.30158730158730157
Delta: 0.0026268875775125986 	  Loss: 1.0377617708400897 	 Accuracy: 0.30158730158730157
Delta: 0.0024280777982517506 	  Loss: 1.0377506662295386 	 Accuracy: 0.30158730158730157
Delta: 0.001909386663150622 	  Loss: 1.0377363660360337 	 Accuracy: 0.30158730158730157
Delta: 0.0014497461284043059 	  Loss: 1.0377308153082998 	 Accuracy: 0.30158730158730157
Delta: 0.0013814310565953211 	  Loss: 1.0377333923599703 	 Accuracy: 0.30158730158730157
Delta: 0.001353518304901323 	  Loss: 1.0377419781907795 	 Accuracy: 0.30158730158730157
Delta: 0.0018042496778431488 	  Loss: 1.0377470386361631 	 Accuracy: 0.30158730158730157
Delta: 0.0015243503188843992 	  Loss: 1.0377543075926243 	 Accuracy: 0.30158730158730157
Delta: 0.0014516091177830973 	  Loss: 1.0377589772258433 	 Accuracy: 0.30158730158730157
Delta: 0.0013339337086947893 	  Loss: 1.0377695052755962 	 Accuracy: 0.30158730158730157
Delta: 0.0020650936837082043 	  Loss: 1.0377739933356218 	 Accuracy: 0.30158730158730157
Delta: 0.0023483025176107113 	  Loss: 1.037764431261713 	 Accuracy: 0.30158730158730157
Delta: 0.001560939998900355 	  Loss: 1.037771640371742 	 Accuracy: 0.30158730158730157
Delta: 0.001366740451443478 	  Loss: 1.0377738187552636 	 Accuracy: 0.30158730158730157
Delta: 0.0011922135307506974 	  Loss: 1.0377666079036107 	 Accuracy: 0.30158730158730157
Delta: 0.0010227471975290778 	  Loss: 1.0377697715018117 	 Accuracy: 0.30158730158730157
Delta: 0.0006590552139246381 	  Loss: 1.0377756205110993 	 Accuracy: 0.30158730158730157
Delta: 0.0006485828295031348 	  Loss: 1.037777902133624 	 Accuracy: 0.30158730158730157
Delta: 0.00029631711765155217 	  Loss: 1.037782781735288 	 Accuracy: 0.30158730158730157
Delta: 0.0004030913359779079 	  Loss: 1.0377851588515024 	 Accuracy: 0.30158730158730157
Delta: 0.000527797455200908 	  Loss: 1.0377841181948992 	 Accuracy: 0.30158730158730157
Delta: 0.0004994664590226235 	  Loss: 1.0377823178696213 	 Accuracy: 0.30158730158730157
Delta: 0.00044831647969652147 	  Loss: 1.0377841262545493 	 Accuracy: 0.30158730158730157
Delta: 0.0004237193555623592 	  Loss: 1.0377848236978062 	 Accuracy: 0.30158730158730157
Delta: 0.00018142454306393818 	  Loss: 1.0377859379910692 	 Accuracy: 0.30158730158730157
Delta: 2.6943774743825167e-05 	  Loss: 1.037785169962402 	 Accuracy: 0.30158730158730157
Delta: 1.2379141081060851e-06 	  Loss: 1.037785128776501 	 Accuracy: 0.30158730158730157
converged at iter  68
Delta: 0.060758199375191904 	  Loss: 1.0766839704315836 	 Accuracy: 0.20967741935483872
Delta: 0.04136582341596731 	  Loss: 1.0699812077164346 	 Accuracy: 0.12903225806451613
Delta: 0.04570702516138781 	  Loss: 1.071394387040324 	 Accuracy: 0.12903225806451613

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.029159127262649503 	  Loss: 1.0650891199120172 	 Accuracy: 0.12903225806451613
Delta: 0.02354869229744922 	  Loss: 1.0607315368648988 	 Accuracy: 0.12903225806451613
Delta: 0.017750595747622316 	  Loss: 1.0585182788104852 	 Accuracy: 0.12903225806451613
Delta: 0.01621737586244948 	  Loss: 1.057313488887878 	 Accuracy: 0.12903225806451613
Delta: 0.015511126934968951 	  Loss: 1.0560650454921428 	 Accuracy: 0.12903225806451613
Delta: 0.013879704340925707 	  Loss: 1.054971193815057 	 Accuracy: 0.12903225806451613
Delta: 0.011157658282760623 	  Loss: 1.0542463108063966 	 Accuracy: 0.12903225806451613
Delta: 0.009566191064608728 	  Loss: 1.0538646491867025 	 Accuracy: 0.12903225806451613
Delta: 0.008427474257373994 	  Loss: 1.0535139715024775 	 Accuracy: 0.12903225806451613
Delta: 0.006735503564470898 	  Loss: 1.0532807083746354 	 Accuracy: 0.12903225806451613
Delta: 0.004995940091927355 	  Loss: 1.0531530207270647 	 Accuracy: 0.12903225806451613
Delta: 0.00417900666301037 	  Loss: 1.0530901124703784 	 Accuracy: 0.12903225806451613
Delta: 0.0038062273554030344 	  Loss: 1.0530752438363025 	 Accuracy: 0.12903225806451613
Delta: 0.0042634162016944015 	  Loss: 1.0530914909925828 	 Accuracy: 0.12903225806451613
Delta: 0.0039771231229620415 	  Loss: 1.0531143568033012 	 Accuracy: 0.12903225806451613
Delta: 0.004565792630539208 	  Loss: 1.0531029484688013 	 Accuracy: 0.12903225806451613
Delta: 0.0034745639334683985 	  Loss: 1.053082225561252 	 Accuracy: 0.12903225806451613
Delta: 0.002505908352867313 	  Loss: 1.0530877027289702 	 Accuracy: 0.12903225806451613
Delta: 0.0022706868780471286 	  Loss: 1.0530961467492213 	 Accuracy: 0.12903225806451613
Delta: 0.001700904086457109 	  Loss: 1.0531040241107443 	 Accuracy: 0.12903225806451613
Delta: 0.0012602783095970556 	  Loss: 1.0531072631362144 	 Accuracy: 0.12903225806451613
Delta: 0.0012008926781405325 	  Loss: 1.0530997303729777 	 Accuracy: 0.12903225806451613
Delta: 0.0016885876146150618 	  Loss: 1.0531007336768101 	 Accuracy: 0.12903225806451613
Delta: 0.0018050893862360284 	  Loss: 1.053102165741709 	 Accuracy: 0.12903225806451613
Delta: 0.0016386618616226417 	  Loss: 1.0531008722866066 	 Accuracy: 0.12903225806451613
Delta: 0.0011119336788288302 	  Loss: 1.0530987425823497 	 Accuracy: 0.12903225806451613
Delta: 0.0015770186965568217 	  Loss: 1.05309612471848 	 Accuracy: 0.12903225806451613
Delta: 0.0009028886960931803 	  Loss: 1.0530835078620187 	 Accuracy: 0.12903225806451613
Delta: 0.00036628308784843785 	  Loss: 1.0530810338069518 	 Accuracy: 0.12903225806451613
Delta: 0.00027804107539508886 	  Loss: 1.0530808577275619 	 Accuracy: 0.12903225806451613
Delta: 0.0002028461570774122 	  Loss: 1.0530787892196765 	 Accuracy: 0.12903225806451613
Delta: 0.0005572768435810331 	  Loss: 1.0530779044765786 	 Accuracy: 0.12903225806451613
Delta: 0.0005224611311315224 	  Loss: 1.0530767051189887 	 Accuracy: 0.12903225806451613
Delta: 0.00033042266006201706 	  Loss: 1.0530775406916217 	 Accuracy: 0.12903225806451613
Delta: 7.940717073384417e-05 	  Loss: 1.0530792440618972 	 Accuracy: 0.12903225806451613
Delta: 4.849725793919455e-06 	  Loss: 1.0530796619188996 	 Accuracy: 0.12903225806451613
Delta: 3.353022433567706e-17 	  Loss: 1.0530796619188996 	 Accuracy: 0.12903225806451613
converged at iter  39
Delta: 0.0628934821624069 	  Loss: 1.0733635430916417 	 Accuracy: 0.14516129032258066
Delta: 0.045839710681506954 	  Loss: 1.0659467420484905 	 Accuracy: 0.12903225806451613
Delta: 0.032166844626784076 	  Loss: 1.0608319557805814 	 Accuracy: 0.12903225806451613

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.024563689650997676 	  Loss: 1.056615074113797 	 Accuracy: 0.12903225806451613
Delta: 0.018379821676638385 	  Loss: 1.0542613423943263 	 Accuracy: 0.12903225806451613
Delta: 0.013126396987155623 	  Loss: 1.0529465492434924 	 Accuracy: 0.12903225806451613
Delta: 0.010102999994546905 	  Loss: 1.052316052438059 	 Accuracy: 0.12903225806451613
Delta: 0.009020503979041555 	  Loss: 1.0518664959413604 	 Accuracy: 0.12903225806451613
Delta: 0.00879316654729421 	  Loss: 1.0515734078621906 	 Accuracy: 0.12903225806451613
Delta: 0.007682583562985709 	  Loss: 1.0512780467568303 	 Accuracy: 0.12903225806451613
Delta: 0.007094002100095219 	  Loss: 1.0510333063820867 	 Accuracy: 0.12903225806451613
Delta: 0.006762543979956834 	  Loss: 1.0508932694890152 	 Accuracy: 0.12903225806451613
Delta: 0.005867738280188843 	  Loss: 1.0507978597789265 	 Accuracy: 0.12903225806451613
Delta: 0.004650070350688741 	  Loss: 1.050678781931376 	 Accuracy: 0.12903225806451613
Delta: 0.003916925329739781 	  Loss: 1.0506022936422115 	 Accuracy: 0.12903225806451613
Delta: 0.0036980059309595203 	  Loss: 1.0505670114759298 	 Accuracy: 0.12903225806451613
Delta: 0.0028493934757410407 	  Loss: 1.050547158256892 	 Accuracy: 0.12903225806451613
Delta: 0.002654921418959226 	  Loss: 1.0505427164216212 	 Accuracy: 0.12903225806451613
Delta: 0.0031352093633942282 	  Loss: 1.0505314900909721 	 Accuracy: 0.12903225806451613
Delta: 0.0035914293302060168 	  Loss: 1.0505208436498832 	 Accuracy: 0.12903225806451613
Delta: 0.0024573825393412185 	  Loss: 1.0504807659046556 	 Accuracy: 0.12903225806451613
Delta: 0.0017446274822481185 	  Loss: 1.0504449256687238 	 Accuracy: 0.12903225806451613
Delta: 0.001106787998324758 	  Loss: 1.0504162859085262 	 Accuracy: 0.12903225806451613
Delta: 0.001261539390833789 	  Loss: 1.0504065904169626 	 Accuracy: 0.12903225806451613
Delta: 0.001797208060552052 	  Loss: 1.0504020589838188 	 Accuracy: 0.12903225806451613
Delta: 0.0003891983493066048 	  Loss: 1.0503916946201377 	 Accuracy: 0.12903225806451613
Delta: 0.00037716674042700016 	  Loss: 1.0503884150985492 	 Accuracy: 0.12903225806451613
Delta: 0.0006781935147834416 	  Loss: 1.0503886132455724 	 Accuracy: 0.12903225806451613
Delta: 0.00024171492191831979 	  Loss: 1.0503861246472161 	 Accuracy: 0.12903225806451613
Delta: 0.00030222948431085156 	  Loss: 1.050385422455728 	 Accuracy: 0.12903225806451613
Delta: 0.0008022791408588115 	  Loss: 1.0503854646182842 	 Accuracy: 0.12903225806451613
converged at iter  30
Delta: 0.058641083537465125 	  Loss: 1.0721136055622293 	 Accuracy: 0.3870967741935484
Delta: 0.04324973448093275 	  Loss: 1.063935777962008 	 Accuracy: 0.3064516129032258
Delta: 0.03588599375697653 	  Loss: 1.057675387014472 	 Accuracy: 0.2903225806451613

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.025829114526256063 	  Loss: 1.053453845845294 	 Accuracy: 0.2903225806451613
Delta: 0.016625272920032207 	  Loss: 1.0515313091525786 	 Accuracy: 0.2903225806451613
Delta: 0.013313604879914669 	  Loss: 1.0505980629669684 	 Accuracy: 0.2903225806451613
Delta: 0.013118070412213316 	  Loss: 1.0497295021344994 	 Accuracy: 0.2903225806451613
Delta: 0.008920703765231328 	  Loss: 1.0492876667949942 	 Accuracy: 0.2903225806451613
Delta: 0.0059941707885434094 	  Loss: 1.0490716936319053 	 Accuracy: 0.2903225806451613
Delta: 0.005200795940177752 	  Loss: 1.0489422830693829 	 Accuracy: 0.2903225806451613
Delta: 0.004857664199255787 	  Loss: 1.048827705359829 	 Accuracy: 0.2903225806451613
Delta: 0.004343940467660136 	  Loss: 1.0487245740626374 	 Accuracy: 0.2903225806451613
Delta: 0.003734467591792516 	  Loss: 1.0486839937773724 	 Accuracy: 0.2903225806451613
Delta: 0.004148280770175161 	  Loss: 1.0486263641951097 	 Accuracy: 0.2903225806451613
Delta: 0.00351669048688656 	  Loss: 1.0485589540393139 	 Accuracy: 0.2903225806451613
Delta: 0.0036106922417278127 	  Loss: 1.048506828126328 	 Accuracy: 0.2903225806451613
Delta: 0.0029992843985094816 	  Loss: 1.0484605864172423 	 Accuracy: 0.2903225806451613
Delta: 0.002975389053796192 	  Loss: 1.048420006311067 	 Accuracy: 0.2903225806451613
Delta: 0.0034880391905642485 	  Loss: 1.048371394470476 	 Accuracy: 0.2903225806451613
Delta: 0.004191576442177466 	  Loss: 1.0483285109281415 	 Accuracy: 0.2903225806451613
Delta: 0.004280964288316245 	  Loss: 1.0482374066768987 	 Accuracy: 0.2903225806451613
Delta: 0.004782725123481374 	  Loss: 1.0481552782588424 	 Accuracy: 0.2903225806451613
Delta: 0.006822000474430678 	  Loss: 1.0480176474785774 	 Accuracy: 0.2903225806451613
Delta: 0.00710562478048187 	  Loss: 1.0477450884047919 	 Accuracy: 0.2903225806451613
Delta: 0.00751827367825847 	  Loss: 1.047423089204647 	 Accuracy: 0.2903225806451613
Delta: 0.006716714585104294 	  Loss: 1.0471251192826805 	 Accuracy: 0.2903225806451613
Delta: 0.006183225335708873 	  Loss: 1.0469197798942003 	 Accuracy: 0.2903225806451613
Delta: 0.006083290979181859 	  Loss: 1.0467611761262416 	 Accuracy: 0.2903225806451613
Delta: 0.0054047058182927175 	  Loss: 1.0466345629297935 	 Accuracy: 0.2903225806451613
Delta: 0.005258301701177411 	  Loss: 1.046505903134968 	 Accuracy: 0.2903225806451613
Delta: 0.004243605671188179 	  Loss: 1.046415878871807 	 Accuracy: 0.2903225806451613
Delta: 0.0034353054474455724 	  Loss: 1.0463865296156543 	 Accuracy: 0.2903225806451613
Delta: 0.00339652905533057 	  Loss: 1.0463542302263333 	 Accuracy: 0.2903225806451613
Delta: 0.0033933346801787926 	  Loss: 1.0462939371530897 	 Accuracy: 0.2903225806451613
Delta: 0.0034530617077049935 	  Loss: 1.0462366814115085 	 Accuracy: 0.2903225806451613
Delta: 0.0032145809635511086 	  Loss: 1.046191709681712 	 Accuracy: 0.2903225806451613
Delta: 0.0026986391880851985 	  Loss: 1.0461879410522825 	 Accuracy: 0.2903225806451613
Delta: 0.0030443149881580274 	  Loss: 1.0461544046921212 	 Accuracy: 0.2903225806451613
Delta: 0.0024225149034004865 	  Loss: 1.0461051858507169 	 Accuracy: 0.2903225806451613
Delta: 0.0027005113503600145 	  Loss: 1.046061907458713 	 Accuracy: 0.2903225806451613
Delta: 0.002587843459808464 	  Loss: 1.0460097626532079 	 Accuracy: 0.2903225806451613
Delta: 0.0019885424964653773 	  Loss: 1.0459639960252942 	 Accuracy: 0.2903225806451613
Delta: 0.0015216768837314578 	  Loss: 1.0459504047483439 	 Accuracy: 0.2903225806451613
Delta: 0.0009909216444917786 	  Loss: 1.04593631308984 	 Accuracy: 0.2903225806451613
Delta: 0.0006222020275253723 	  Loss: 1.0459321439188645 	 Accuracy: 0.2903225806451613
Delta: 0.0006118380765697115 	  Loss: 1.0459349938417657 	 Accuracy: 0.2903225806451613
Delta: 0.0005530835787621068 	  Loss: 1.045936320164918 	 Accuracy: 0.2903225806451613
Delta: 0.0004173911266815432 	  Loss: 1.0459370460885313 	 Accuracy: 0.2903225806451613
Delta: 0.0016379513279902139 	  Loss: 1.0459379651737482 	 Accuracy: 0.2903225806451613
Delta: 0.0007962786697433948 	  Loss: 1.0459342824056383 	 Accuracy: 0.2903225806451613
Delta: 0.0007470927197981083 	  Loss: 1.0459320166987782 	 Accuracy: 0.2903225806451613
Delta: 0.0006766307236170763 	  Loss: 1.0459266221161188 	 Accuracy: 0.2903225806451613
Delta: 0.0008010559779730822 	  Loss: 1.0459256262087684 	 Accuracy: 0.2903225806451613
Delta: 0.0011231816865837523 	  Loss: 1.0459242490887597 	 Accuracy: 0.2903225806451613
Delta: 0.001108021998915875 	  Loss: 1.0459151997086178 	 Accuracy: 0.2903225806451613
Delta: 0.0008219509314289298 	  Loss: 1.0459075354526495 	 Accuracy: 0.2903225806451613
Delta: 0.0004927851967247686 	  Loss: 1.0459060096645385 	 Accuracy: 0.2903225806451613
Delta: 0.0002882982504970255 	  Loss: 1.0459025093695802 	 Accuracy: 0.2903225806451613
Delta: 0.000677645847288005 	  Loss: 1.045903409008948 	 Accuracy: 0.2903225806451613
Delta: 0.00043237081051425137 	  Loss: 1.0459072143498584 	 Accuracy: 0.2903225806451613
Delta: 0.0006409638904964884 	  Loss: 1.0459073637995304 	 Accuracy: 0.2903225806451613
Delta: 0.0005784642915685169 	  Loss: 1.045904723291087 	 Accuracy: 0.2903225806451613
Delta: 0.0002951232066148066 	  Loss: 1.0459016883809062 	 Accuracy: 0.2903225806451613
Delta: 0.000548657550966266 	  Loss: 1.0459010104119901 	 Accuracy: 0.2903225806451613
Delta: 0.0006737961005006849 	  Loss: 1.0459015569941823 	 Accuracy: 0.2903225806451613
Delta: 0.0011732629933933405 	  Loss: 1.0458994457227475 	 Accuracy: 0.2903225806451613
Delta: 0.0011296548055808704 	  Loss: 1.045900644274909 	 Accuracy: 0.2903225806451613
Delta: 0.0007573347440729994 	  Loss: 1.0458887442589027 	 Accuracy: 0.2903225806451613
Delta: 0.00029040433727970516 	  Loss: 1.0458849870815616 	 Accuracy: 0.2903225806451613
Delta: 0.00024182621368030977 	  Loss: 1.0458857923201397 	 Accuracy: 0.2903225806451613
Delta: 0.0004282603908969798 	  Loss: 1.0458846698484612 	 Accuracy: 0.2903225806451613
Delta: 0.00037386665912448626 	  Loss: 1.0458772391427118 	 Accuracy: 0.2903225806451613
Delta: 0.00018562258628720675 	  Loss: 1.045874749494697 	 Accuracy: 0.2903225806451613
Delta: 1.5307411543522684e-05 	  Loss: 1.0458769495015716 	 Accuracy: 0.2903225806451613
Delta: 2.7477465402946707e-17 	  Loss: 1.0458769495015716 	 Accuracy: 0.2903225806451613
converged at iter  74
Delta: 0.05827086118021891 	  Loss: 1.0730508204622669 	 Accuracy: 0.5873015873015873
Delta: 0.0392400784516242 	  Loss: 1.0653354651404063 	 Accuracy: 0.4126984126984127
Delta: 0.033425096991731185 	  Loss: 1.0629394436263677 	 Accuracy: 0.3333333333333333

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.023623965817064285 	  Loss: 1.0598984933477436 	 Accuracy: 0.2857142857142857
Delta: 0.021956218650562045 	  Loss: 1.0586829494659504 	 Accuracy: 0.2857142857142857
Delta: 0.014031665628455058 	  Loss: 1.057241999981362 	 Accuracy: 0.2857142857142857
Delta: 0.011544220914054205 	  Loss: 1.0563234744445904 	 Accuracy: 0.2857142857142857
Delta: 0.009609755136607572 	  Loss: 1.0557825776783987 	 Accuracy: 0.2857142857142857
Delta: 0.008452597598708672 	  Loss: 1.0553530909638131 	 Accuracy: 0.2857142857142857
Delta: 0.007833418890098639 	  Loss: 1.0550030334828868 	 Accuracy: 0.2857142857142857
Delta: 0.005955501200338676 	  Loss: 1.0547357720647006 	 Accuracy: 0.2857142857142857
Delta: 0.005428997861654017 	  Loss: 1.0545320619190341 	 Accuracy: 0.2857142857142857
Delta: 0.0053613041261045755 	  Loss: 1.0543697798353446 	 Accuracy: 0.2857142857142857
Delta: 0.004711554624763198 	  Loss: 1.054241554283095 	 Accuracy: 0.2857142857142857
Delta: 0.0046855094757625735 	  Loss: 1.0541163607497488 	 Accuracy: 0.2857142857142857
Delta: 0.004232063175479579 	  Loss: 1.0540397802772188 	 Accuracy: 0.2857142857142857
Delta: 0.004295323535005895 	  Loss: 1.053976348595815 	 Accuracy: 0.2857142857142857
Delta: 0.004339990605590634 	  Loss: 1.0538736833815803 	 Accuracy: 0.2857142857142857
Delta: 0.004143558821199612 	  Loss: 1.0538030842829982 	 Accuracy: 0.2857142857142857
Delta: 0.00394438285529674 	  Loss: 1.0537274701088937 	 Accuracy: 0.2857142857142857
Delta: 0.004660408482387085 	  Loss: 1.0536309859876325 	 Accuracy: 0.2857142857142857
Delta: 0.0039511986309436605 	  Loss: 1.0535598331928877 	 Accuracy: 0.2857142857142857
Delta: 0.004375531857000669 	  Loss: 1.0535114792491287 	 Accuracy: 0.2857142857142857
Delta: 0.0036148356280082195 	  Loss: 1.0534458614668218 	 Accuracy: 0.2857142857142857
Delta: 0.003794006504491887 	  Loss: 1.053390581358118 	 Accuracy: 0.2857142857142857
Delta: 0.0030074087708386633 	  Loss: 1.0533816165291894 	 Accuracy: 0.2857142857142857
Delta: 0.002864228417693092 	  Loss: 1.0533343794624928 	 Accuracy: 0.2857142857142857
Delta: 0.0020954195156697945 	  Loss: 1.0532946418937832 	 Accuracy: 0.2857142857142857
Delta: 0.0017804190554163374 	  Loss: 1.0532658583908967 	 Accuracy: 0.2857142857142857
Delta: 0.0024183595095626743 	  Loss: 1.053241477187732 	 Accuracy: 0.2857142857142857
Delta: 0.0027610604018698456 	  Loss: 1.0531845669706144 	 Accuracy: 0.2857142857142857
Delta: 0.0019839019738632493 	  Loss: 1.053140329145898 	 Accuracy: 0.2857142857142857
Delta: 0.0021734979127314502 	  Loss: 1.053111629387094 	 Accuracy: 0.2857142857142857
Delta: 0.0017513456204136613 	  Loss: 1.053098211430648 	 Accuracy: 0.2857142857142857
Delta: 0.0020795320689505755 	  Loss: 1.0530994625295929 	 Accuracy: 0.2857142857142857
Delta: 0.0021154934696579796 	  Loss: 1.053107643726749 	 Accuracy: 0.2857142857142857
Delta: 0.0012184647223889497 	  Loss: 1.0531012416561845 	 Accuracy: 0.2857142857142857
Delta: 0.0015100187833124337 	  Loss: 1.053089124878856 	 Accuracy: 0.2857142857142857
Delta: 0.0013653278642617173 	  Loss: 1.0530740431234804 	 Accuracy: 0.2857142857142857
Delta: 0.0012136301048348008 	  Loss: 1.0530710130944962 	 Accuracy: 0.2857142857142857
Delta: 0.0008714615139360595 	  Loss: 1.0530658844767764 	 Accuracy: 0.2857142857142857
Delta: 0.0007414400362377954 	  Loss: 1.0530659328494254 	 Accuracy: 0.2857142857142857
converged at iter  41
Delta: 0.06071990910062078 	  Loss: 1.0551054941358506 	 Accuracy: 0.5238095238095238
Delta: 0.04538072190650082 	  Loss: 1.0507593072483727 	 Accuracy: 0.5714285714285714
Delta: 0.047105573085301534 	  Loss: 1.0544481959020773 	 Accuracy: 0.47619047619047616

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.031958746971346194 	  Loss: 1.048546788349766 	 Accuracy: 0.42857142857142855
Delta: 0.022233733124877992 	  Loss: 1.044868873867049 	 Accuracy: 0.42857142857142855
Delta: 0.015845940168127157 	  Loss: 1.0428604839610442 	 Accuracy: 0.42857142857142855
Delta: 0.011346354788164464 	  Loss: 1.0418728830853055 	 Accuracy: 0.42857142857142855
Delta: 0.010113396233238554 	  Loss: 1.041298946749674 	 Accuracy: 0.42857142857142855
Delta: 0.008128182687241997 	  Loss: 1.0408265764376254 	 Accuracy: 0.42857142857142855
Delta: 0.007596734034511934 	  Loss: 1.0405649917282178 	 Accuracy: 0.42857142857142855
Delta: 0.007681297499436467 	  Loss: 1.0403241857524068 	 Accuracy: 0.42857142857142855
Delta: 0.007461956895679569 	  Loss: 1.0401001176021105 	 Accuracy: 0.42857142857142855
Delta: 0.005460387236863817 	  Loss: 1.0399178524751926 	 Accuracy: 0.42857142857142855
Delta: 0.0055087612507856735 	  Loss: 1.0398033784304292 	 Accuracy: 0.42857142857142855
Delta: 0.005260531320484075 	  Loss: 1.0396437889561732 	 Accuracy: 0.42857142857142855
Delta: 0.005184984958909847 	  Loss: 1.039505607400534 	 Accuracy: 0.42857142857142855
Delta: 0.005716275113677712 	  Loss: 1.0394206746853338 	 Accuracy: 0.42857142857142855
Delta: 0.004990234033966385 	  Loss: 1.0392846071159592 	 Accuracy: 0.42857142857142855
Delta: 0.005454319701682788 	  Loss: 1.0391476602705654 	 Accuracy: 0.42857142857142855
Delta: 0.004676867915526279 	  Loss: 1.0389821373181247 	 Accuracy: 0.42857142857142855
Delta: 0.004608741943543552 	  Loss: 1.0388665038384395 	 Accuracy: 0.42857142857142855
Delta: 0.0043244320508623165 	  Loss: 1.0387564589364056 	 Accuracy: 0.42857142857142855
Delta: 0.003700237199714232 	  Loss: 1.0386648701519108 	 Accuracy: 0.42857142857142855
Delta: 0.0038131234921906275 	  Loss: 1.0386249268118937 	 Accuracy: 0.42857142857142855
Delta: 0.004365934274973477 	  Loss: 1.0385530543209425 	 Accuracy: 0.42857142857142855
Delta: 0.00420066773191728 	  Loss: 1.0384978768053155 	 Accuracy: 0.42857142857142855
Delta: 0.004550374805283233 	  Loss: 1.038451127763187 	 Accuracy: 0.42857142857142855
Delta: 0.005617882026601708 	  Loss: 1.0383852422013242 	 Accuracy: 0.42857142857142855
Delta: 0.006034600563295248 	  Loss: 1.0382946731096 	 Accuracy: 0.42857142857142855
Delta: 0.00573384831416312 	  Loss: 1.038104166767133 	 Accuracy: 0.42857142857142855
Delta: 0.005268663671806244 	  Loss: 1.0380023316559412 	 Accuracy: 0.42857142857142855
Delta: 0.004102997684865722 	  Loss: 1.0378842245877824 	 Accuracy: 0.42857142857142855
Delta: 0.00341382522588107 	  Loss: 1.0377873468987238 	 Accuracy: 0.42857142857142855
Delta: 0.0030070435010562235 	  Loss: 1.0377274544469204 	 Accuracy: 0.42857142857142855
Delta: 0.0024545350446221843 	  Loss: 1.0377024701450028 	 Accuracy: 0.42857142857142855
Delta: 0.00235694647538194 	  Loss: 1.0376691088324188 	 Accuracy: 0.42857142857142855
Delta: 0.0022344483407895173 	  Loss: 1.037625112074973 	 Accuracy: 0.42857142857142855
Delta: 0.0019940898954483866 	  Loss: 1.0375964070504238 	 Accuracy: 0.42857142857142855
Delta: 0.0019515062815119136 	  Loss: 1.0375899418142325 	 Accuracy: 0.42857142857142855
Delta: 0.002101735933854419 	  Loss: 1.037567414818589 	 Accuracy: 0.42857142857142855
Delta: 0.0013114749922858173 	  Loss: 1.037552044753061 	 Accuracy: 0.42857142857142855
Delta: 0.0011436122565039288 	  Loss: 1.0375607224676242 	 Accuracy: 0.42857142857142855
Delta: 0.0011088039404730065 	  Loss: 1.037554839905329 	 Accuracy: 0.42857142857142855
Delta: 0.0022528951401652414 	  Loss: 1.0375354115362787 	 Accuracy: 0.42857142857142855
Delta: 0.0018663181745887884 	  Loss: 1.0374773830191222 	 Accuracy: 0.42857142857142855
Delta: 0.001737318405334214 	  Loss: 1.0374493049333098 	 Accuracy: 0.42857142857142855
Delta: 0.0017263263247079823 	  Loss: 1.0374271867689069 	 Accuracy: 0.42857142857142855
Delta: 0.001656372321179901 	  Loss: 1.0374212112660537 	 Accuracy: 0.42857142857142855
Delta: 0.001306823097394109 	  Loss: 1.0374214813527272 	 Accuracy: 0.42857142857142855
Delta: 0.001167305980873701 	  Loss: 1.0374130851309624 	 Accuracy: 0.42857142857142855
Delta: 0.0013891909534862598 	  Loss: 1.037408707185368 	 Accuracy: 0.42857142857142855
Delta: 0.001502566233230876 	  Loss: 1.0374026739439142 	 Accuracy: 0.42857142857142855
Delta: 0.0011250101384821648 	  Loss: 1.037379838848513 	 Accuracy: 0.42857142857142855
Delta: 0.0013999220602966922 	  Loss: 1.0373733059543095 	 Accuracy: 0.42857142857142855
Delta: 0.0012307496661139194 	  Loss: 1.0373670352638715 	 Accuracy: 0.42857142857142855
Delta: 0.001224137200425274 	  Loss: 1.037363763025421 	 Accuracy: 0.42857142857142855
Delta: 0.0008308361525401313 	  Loss: 1.037354315395485 	 Accuracy: 0.42857142857142855
Delta: 0.0008002730361614485 	  Loss: 1.0373597875432607 	 Accuracy: 0.42857142857142855
Delta: 0.00034878427252571054 	  Loss: 1.0373584974600072 	 Accuracy: 0.42857142857142855
Delta: 0.0005599373045391969 	  Loss: 1.0373584151013209 	 Accuracy: 0.42857142857142855
converged at iter  59
Delta: 0.06028046558276154 	  Loss: 1.0724425706764902 	 Accuracy: 0.5806451612903226
Delta: 0.050104055856485946 	  Loss: 1.069738724647556 	 Accuracy: 0.5483870967741935

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.036120880735394045 	  Loss: 1.0646099663685673 	 Accuracy: 0.532258064516129
Delta: 0.025103777596199448 	  Loss: 1.0606045743188464 	 Accuracy: 0.532258064516129
Delta: 0.01874592554353226 	  Loss: 1.0578937180558006 	 Accuracy: 0.532258064516129
Delta: 0.01643029894208039 	  Loss: 1.0561742910614311 	 Accuracy: 0.532258064516129
Delta: 0.013175902328862212 	  Loss: 1.0550091528678658 	 Accuracy: 0.532258064516129
Delta: 0.011318501311784933 	  Loss: 1.0541644483360617 	 Accuracy: 0.532258064516129
Delta: 0.008826190758380299 	  Loss: 1.0536109185659115 	 Accuracy: 0.532258064516129
Delta: 0.007353136481448389 	  Loss: 1.0533200333157409 	 Accuracy: 0.532258064516129
Delta: 0.006397483720995941 	  Loss: 1.0530541192095448 	 Accuracy: 0.532258064516129
Delta: 0.0058910966687289994 	  Loss: 1.0528721540427852 	 Accuracy: 0.532258064516129
Delta: 0.004403367691360991 	  Loss: 1.0527287867002506 	 Accuracy: 0.532258064516129
Delta: 0.004143035339078295 	  Loss: 1.0526950143325857 	 Accuracy: 0.532258064516129
Delta: 0.0025445814073440944 	  Loss: 1.0526457434128755 	 Accuracy: 0.532258064516129
Delta: 0.003077301963552891 	  Loss: 1.0526342611640989 	 Accuracy: 0.532258064516129
Delta: 0.0033325463648136333 	  Loss: 1.0526083984072978 	 Accuracy: 0.532258064516129
Delta: 0.004227660584742673 	  Loss: 1.0525517162971585 	 Accuracy: 0.532258064516129
Delta: 0.002390917399434413 	  Loss: 1.0524697483701653 	 Accuracy: 0.532258064516129
Delta: 0.0028613191546072616 	  Loss: 1.0524569175526461 	 Accuracy: 0.532258064516129
Delta: 0.0017464977883569273 	  Loss: 1.0524033420760994 	 Accuracy: 0.532258064516129
Delta: 0.00142386853331899 	  Loss: 1.052383367469501 	 Accuracy: 0.532258064516129
Delta: 0.0015389571602721299 	  Loss: 1.0523739038533613 	 Accuracy: 0.532258064516129
Delta: 0.0006994153285847919 	  Loss: 1.0523620934230493 	 Accuracy: 0.532258064516129
Delta: 0.0009900207198481076 	  Loss: 1.0523506153684727 	 Accuracy: 0.532258064516129
Delta: 0.0014767291070635243 	  Loss: 1.052330312150313 	 Accuracy: 0.532258064516129
Delta: 0.0018605919848462345 	  Loss: 1.0523206171087935 	 Accuracy: 0.532258064516129
Delta: 0.0013719710050506984 	  Loss: 1.052295209976474 	 Accuracy: 0.532258064516129
Delta: 0.0009566934819895609 	  Loss: 1.052282049286077 	 Accuracy: 0.532258064516129
Delta: 0.0008088209511126119 	  Loss: 1.0522785555654872 	 Accuracy: 0.532258064516129
Delta: 0.0006192125107355439 	  Loss: 1.0522637864152493 	 Accuracy: 0.532258064516129
Delta: 0.0005502421581000002 	  Loss: 1.0522603026082729 	 Accuracy: 0.532258064516129
Delta: 0.0011704882524486175 	  Loss: 1.0522591861972237 	 Accuracy: 0.532258064516129
Delta: 0.0007645011277151119 	  Loss: 1.0522494007437082 	 Accuracy: 0.532258064516129
Delta: 0.0005049687873399223 	  Loss: 1.052252645298286 	 Accuracy: 0.532258064516129
Delta: 0.00027609385743344915 	  Loss: 1.0522538437671116 	 Accuracy: 0.532258064516129
Delta: 0.00029480935933606865 	  Loss: 1.052255395542523 	 Accuracy: 0.532258064516129
Delta: 0.0003218581010869172 	  Loss: 1.0522545509709995 	 Accuracy: 0.532258064516129
Delta: 0.0003544032893415177 	  Loss: 1.0522549458937331 	 Accuracy: 0.532258064516129
Delta: 0.00010540846736385278 	  Loss: 1.0522531617099269 	 Accuracy: 0.532258064516129
Delta: 9.629093614108264e-05 	  Loss: 1.0522527716680803 	 Accuracy: 0.532258064516129
Delta: 0.0003826558066210999 	  Loss: 1.052251118931938 	 Accuracy: 0.532258064516129
Delta: 0.00020641961812816208 	  Loss: 1.0522477683126454 	 Accuracy: 0.532258064516129
Delta: 0.0004882558102996289 	  Loss: 1.052245850650064 	 Accuracy: 0.532258064516129
Delta: 0.00025322926250648573 	  Loss: 1.0522438314631 	 Accuracy: 0.532258064516129
Delta: 0.00013988200215458004 	  Loss: 1.0522435649874042 	 Accuracy: 0.532258064516129
Delta: 4.7594329080794026e-05 	  Loss: 1.0522431060420758 	 Accuracy: 0.532258064516129
Delta: 7.063948422183896e-05 	  Loss: 1.0522427639227674 	 Accuracy: 0.532258064516129
Delta: 8.457647721386375e-05 	  Loss: 1.0522425601833145 	 Accuracy: 0.532258064516129
Delta: 0.00011554879458586165 	  Loss: 1.05224210035134 	 Accuracy: 0.532258064516129
Delta: 0.00045749014375817844 	  Loss: 1.0522416461279025 	 Accuracy: 0.532258064516129
Delta: 0.0001666134663286256 	  Loss: 1.0522443394970722 	 Accuracy: 0.532258064516129
Delta: 4.25492760870502e-05 	  Loss: 1.0522453953938582 	 Accuracy: 0.532258064516129
Delta: 3.070491478764739e-06 	  Loss: 1.0522457047173581 	 Accuracy: 0.532258064516129
Delta: 2.4966532383201773e-17 	  Loss: 1.0522457047173581 	 Accuracy: 0.532258064516129
converged at iter  54
Delta: 0.06046731027317599 	  Loss: 1.0657564006552889 	 Accuracy: 0.5645161290322581
Delta: 0.03919917438693839 	  Loss: 1.0581801479494728 	 Accuracy: 0.5161290322580645

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.025550269685387875 	  Loss: 1.0525000403691085 	 Accuracy: 0.46774193548387094
Delta: 0.019601303866454794 	  Loss: 1.0496497271109906 	 Accuracy: 0.45161290322580644
Delta: 0.01590077395353022 	  Loss: 1.0477266704457215 	 Accuracy: 0.45161290322580644
Delta: 0.014186558934807194 	  Loss: 1.0463507732828434 	 Accuracy: 0.45161290322580644
Delta: 0.013809232765397382 	  Loss: 1.0454032846313042 	 Accuracy: 0.45161290322580644
Delta: 0.012604157268706125 	  Loss: 1.044588946136163 	 Accuracy: 0.45161290322580644
Delta: 0.011918100480051293 	  Loss: 1.0437920229913917 	 Accuracy: 0.45161290322580644
Delta: 0.012625293772194773 	  Loss: 1.0430740712894364 	 Accuracy: 0.45161290322580644
Delta: 0.011487177412780571 	  Loss: 1.0423047582140805 	 Accuracy: 0.45161290322580644
Delta: 0.008546747954656882 	  Loss: 1.0418604832528504 	 Accuracy: 0.45161290322580644
Delta: 0.006537335095218474 	  Loss: 1.041718570788744 	 Accuracy: 0.45161290322580644
Delta: 0.0066284778991907165 	  Loss: 1.0416564874398615 	 Accuracy: 0.45161290322580644
Delta: 0.005534075869660195 	  Loss: 1.0415709131743633 	 Accuracy: 0.45161290322580644
Delta: 0.004746846559545236 	  Loss: 1.04154749386242 	 Accuracy: 0.45161290322580644
Delta: 0.005337338108417112 	  Loss: 1.0414855012451385 	 Accuracy: 0.45161290322580644
Delta: 0.004493448129711762 	  Loss: 1.0414351777618198 	 Accuracy: 0.45161290322580644
Delta: 0.003914280977214139 	  Loss: 1.0413846455300275 	 Accuracy: 0.45161290322580644
Delta: 0.003945516733734979 	  Loss: 1.0413042029934179 	 Accuracy: 0.45161290322580644
Delta: 0.003917111576264996 	  Loss: 1.0412135903138409 	 Accuracy: 0.45161290322580644
Delta: 0.003388797552221985 	  Loss: 1.041158770221064 	 Accuracy: 0.45161290322580644
Delta: 0.002286223289748244 	  Loss: 1.0411498862584445 	 Accuracy: 0.45161290322580644
Delta: 0.0029079953642687545 	  Loss: 1.041114877620564 	 Accuracy: 0.45161290322580644
Delta: 0.002837621303676958 	  Loss: 1.0410722551084035 	 Accuracy: 0.45161290322580644
Delta: 0.003247861479172296 	  Loss: 1.041070434697445 	 Accuracy: 0.45161290322580644
Delta: 0.0023333437055768525 	  Loss: 1.0410518532166666 	 Accuracy: 0.45161290322580644
Delta: 0.002670306367029489 	  Loss: 1.0410176438353425 	 Accuracy: 0.45161290322580644
Delta: 0.002568165147024827 	  Loss: 1.0410045659071052 	 Accuracy: 0.45161290322580644
Delta: 0.0032173133292181483 	  Loss: 1.040959670478672 	 Accuracy: 0.45161290322580644
Delta: 0.003063027864100241 	  Loss: 1.0409075095143683 	 Accuracy: 0.45161290322580644
Delta: 0.002960372831399892 	  Loss: 1.0408813546433284 	 Accuracy: 0.45161290322580644
Delta: 0.0023361333740646232 	  Loss: 1.0408466601160535 	 Accuracy: 0.45161290322580644
Delta: 0.003690116147287854 	  Loss: 1.040811655339037 	 Accuracy: 0.45161290322580644
Delta: 0.004573449592690354 	  Loss: 1.0407537369325879 	 Accuracy: 0.45161290322580644
Delta: 0.004414908285339067 	  Loss: 1.0406767318883507 	 Accuracy: 0.45161290322580644
Delta: 0.002881802325412889 	  Loss: 1.040622738890604 	 Accuracy: 0.45161290322580644
Delta: 0.0024328136666510983 	  Loss: 1.0405905825538024 	 Accuracy: 0.45161290322580644
Delta: 0.002453974618746806 	  Loss: 1.0405665069061305 	 Accuracy: 0.45161290322580644
Delta: 0.002898482483566972 	  Loss: 1.040533183195317 	 Accuracy: 0.45161290322580644
Delta: 0.0024770596658664455 	  Loss: 1.0404745980880818 	 Accuracy: 0.45161290322580644
Delta: 0.0025164939309860607 	  Loss: 1.0404627214886546 	 Accuracy: 0.45161290322580644
Delta: 0.0018916587512695614 	  Loss: 1.0404419283682502 	 Accuracy: 0.45161290322580644
Delta: 0.0012498241669288191 	  Loss: 1.0404419092550448 	 Accuracy: 0.45161290322580644
converged at iter  43
Delta: 0.058679966438882084 	  Loss: 1.0735935312121823 	 Accuracy: 0.3548387096774194
Delta: 0.04416120539099252 	  Loss: 1.0642314543457274 	 Accuracy: 0.27419354838709675

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02896881270898269 	  Loss: 1.0584986867598811 	 Accuracy: 0.25806451612903225
Delta: 0.021161333524115318 	  Loss: 1.0555553973658716 	 Accuracy: 0.27419354838709675
Delta: 0.0167972572617853 	  Loss: 1.0537742345459937 	 Accuracy: 0.27419354838709675
Delta: 0.014318698709020998 	  Loss: 1.052412719920404 	 Accuracy: 0.27419354838709675
Delta: 0.01221649166505139 	  Loss: 1.0514500853959747 	 Accuracy: 0.27419354838709675
Delta: 0.009866496039000819 	  Loss: 1.0507444375502901 	 Accuracy: 0.27419354838709675
Delta: 0.008719046846674355 	  Loss: 1.0503164418065454 	 Accuracy: 0.27419354838709675
Delta: 0.007627728560350769 	  Loss: 1.0498732749377175 	 Accuracy: 0.27419354838709675
Delta: 0.006389565337525369 	  Loss: 1.0496343970234165 	 Accuracy: 0.27419354838709675
Delta: 0.005351761236137143 	  Loss: 1.0494990850650918 	 Accuracy: 0.27419354838709675
Delta: 0.004212165331609069 	  Loss: 1.0493500899130215 	 Accuracy: 0.27419354838709675
Delta: 0.0036729071116466737 	  Loss: 1.04929037887178 	 Accuracy: 0.27419354838709675
Delta: 0.002526950797961959 	  Loss: 1.0492264467480976 	 Accuracy: 0.27419354838709675
Delta: 0.0023925322673330855 	  Loss: 1.049182648901854 	 Accuracy: 0.27419354838709675
Delta: 0.002221502227131491 	  Loss: 1.0491535763594229 	 Accuracy: 0.27419354838709675
Delta: 0.002490104993877039 	  Loss: 1.049122119498234 	 Accuracy: 0.27419354838709675
Delta: 0.002129600832320022 	  Loss: 1.0490835379934291 	 Accuracy: 0.27419354838709675
Delta: 0.002015328402121609 	  Loss: 1.0490574123713756 	 Accuracy: 0.27419354838709675
Delta: 0.002320294278743669 	  Loss: 1.0490422704322058 	 Accuracy: 0.27419354838709675
Delta: 0.0020289910553793165 	  Loss: 1.0490194633433836 	 Accuracy: 0.27419354838709675
Delta: 0.0024269176611184723 	  Loss: 1.0489947377498818 	 Accuracy: 0.27419354838709675
Delta: 0.002237381695292494 	  Loss: 1.0489659365820638 	 Accuracy: 0.27419354838709675
Delta: 0.0028317550353379123 	  Loss: 1.048940109397197 	 Accuracy: 0.27419354838709675
Delta: 0.002947039856738795 	  Loss: 1.0489045354346551 	 Accuracy: 0.27419354838709675
Delta: 0.0028769479861264794 	  Loss: 1.0488618702194494 	 Accuracy: 0.27419354838709675
Delta: 0.0029050733405089806 	  Loss: 1.0488121372368617 	 Accuracy: 0.27419354838709675
Delta: 0.0019424121659920154 	  Loss: 1.048771529336705 	 Accuracy: 0.27419354838709675
Delta: 0.0018327803471601385 	  Loss: 1.0487603793771088 	 Accuracy: 0.27419354838709675
Delta: 0.0026338840827106373 	  Loss: 1.048754991923732 	 Accuracy: 0.27419354838709675
Delta: 0.003168812897064146 	  Loss: 1.048742417350838 	 Accuracy: 0.27419354838709675
Delta: 0.0025871848192521715 	  Loss: 1.048719541344778 	 Accuracy: 0.27419354838709675
Delta: 0.0017197437430958888 	  Loss: 1.0486962471884567 	 Accuracy: 0.27419354838709675
Delta: 0.0013939611713697114 	  Loss: 1.0486771131653563 	 Accuracy: 0.27419354838709675
Delta: 0.0016224712579476423 	  Loss: 1.0486675763753768 	 Accuracy: 0.27419354838709675
Delta: 0.0013032028348572632 	  Loss: 1.0486687445461307 	 Accuracy: 0.27419354838709675
Delta: 0.0015517535599526545 	  Loss: 1.0486480163684475 	 Accuracy: 0.27419354838709675
Delta: 0.0016415367661150823 	  Loss: 1.0486206461298395 	 Accuracy: 0.27419354838709675
Delta: 0.0014758108565276 	  Loss: 1.0485945720955856 	 Accuracy: 0.27419354838709675
Delta: 0.0014005545182928388 	  Loss: 1.0485753486344882 	 Accuracy: 0.27419354838709675
Delta: 0.001606051365532404 	  Loss: 1.0485561516086706 	 Accuracy: 0.27419354838709675
Delta: 0.001060276207985204 	  Loss: 1.0485400152542943 	 Accuracy: 0.27419354838709675
Delta: 0.0006867517069918412 	  Loss: 1.0485464048620816 	 Accuracy: 0.27419354838709675
Delta: 0.0010076931458422589 	  Loss: 1.048545897627276 	 Accuracy: 0.27419354838709675
Delta: 0.0006355767915887784 	  Loss: 1.0485417189311834 	 Accuracy: 0.27419354838709675
Delta: 0.0008113061852796294 	  Loss: 1.0485366175707962 	 Accuracy: 0.27419354838709675
Delta: 0.0019663413988678592 	  Loss: 1.048528511460151 	 Accuracy: 0.27419354838709675
Delta: 0.0008958085582256853 	  Loss: 1.0485140580429484 	 Accuracy: 0.27419354838709675
Delta: 0.001236276765006914 	  Loss: 1.0485067378285746 	 Accuracy: 0.27419354838709675
Delta: 0.0013361861503251742 	  Loss: 1.0484960461066355 	 Accuracy: 0.27419354838709675
Delta: 0.0009648002980170165 	  Loss: 1.0484757648280443 	 Accuracy: 0.27419354838709675
Delta: 0.00034638006907362575 	  Loss: 1.0484788367628113 	 Accuracy: 0.27419354838709675
Delta: 0.00036725251235258694 	  Loss: 1.0484766061430473 	 Accuracy: 0.27419354838709675
Delta: 0.00014887418243938438 	  Loss: 1.0484755083451653 	 Accuracy: 0.27419354838709675
Delta: 2.5397821424414058e-05 	  Loss: 1.0484757171552341 	 Accuracy: 0.27419354838709675
Delta: 5.749474068295636e-05 	  Loss: 1.0484757003004277 	 Accuracy: 0.27419354838709675
converged at iter  56
Delta: 0.06028934988721088 	  Loss: 1.085936063816857 	 Accuracy: 0.19047619047619047
Delta: 0.04852764938911314 	  Loss: 1.0833254116815811 	 Accuracy: 0.09523809523809523
Delta: 0.03489865646559133 	  Loss: 1.0772509605852916 	 Accuracy: 0.09523809523809523
Delta: 0.02782826852672561 	  Loss: 1.0755248519453262 	 Accuracy: 0.1111111111111111
Delta: 0.027075918748384487 	  Loss: 1.0764491865361205 	 Accuracy: 0.1111111111111111

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.021590059163489744 	  Loss: 1.0761482272972192 	 Accuracy: 0.1111111111111111
Delta: 0.015306172263235818 	  Loss: 1.0752302954818354 	 Accuracy: 0.1111111111111111
Delta: 0.015820540040063755 	  Loss: 1.0743391765308736 	 Accuracy: 0.1111111111111111
Delta: 0.014235676553350176 	  Loss: 1.0733980793948408 	 Accuracy: 0.1111111111111111
Delta: 0.012704240416749701 	  Loss: 1.072504907396461 	 Accuracy: 0.1111111111111111
Delta: 0.011357843400040582 	  Loss: 1.0717944908252552 	 Accuracy: 0.1111111111111111
Delta: 0.009348703630858818 	  Loss: 1.0714904301854944 	 Accuracy: 0.1111111111111111
Delta: 0.007547758895035503 	  Loss: 1.0712445367301042 	 Accuracy: 0.1111111111111111
Delta: 0.006191543240007124 	  Loss: 1.0710592655777122 	 Accuracy: 0.1111111111111111
Delta: 0.0062848047153264185 	  Loss: 1.070950532267156 	 Accuracy: 0.1111111111111111
Delta: 0.005805598211823122 	  Loss: 1.070797581442294 	 Accuracy: 0.1111111111111111
Delta: 0.004844483764678992 	  Loss: 1.070678380884029 	 Accuracy: 0.1111111111111111
Delta: 0.005475875336791695 	  Loss: 1.0705709858619468 	 Accuracy: 0.1111111111111111
Delta: 0.005359169600009419 	  Loss: 1.0704530580493172 	 Accuracy: 0.1111111111111111
Delta: 0.00562443013754594 	  Loss: 1.0702969661134485 	 Accuracy: 0.1111111111111111
Delta: 0.004551731743350545 	  Loss: 1.0701412750602377 	 Accuracy: 0.1111111111111111
Delta: 0.004660406372074922 	  Loss: 1.0700921380708266 	 Accuracy: 0.1111111111111111
Delta: 0.0037924803231463955 	  Loss: 1.0700067150329455 	 Accuracy: 0.1111111111111111
Delta: 0.0037968602329477978 	  Loss: 1.069926618566634 	 Accuracy: 0.1111111111111111
Delta: 0.004082854650583249 	  Loss: 1.0699056348908718 	 Accuracy: 0.1111111111111111
Delta: 0.004147596530054249 	  Loss: 1.069881031421575 	 Accuracy: 0.1111111111111111
Delta: 0.0036907621768949676 	  Loss: 1.069799655093823 	 Accuracy: 0.1111111111111111
Delta: 0.003517687280176254 	  Loss: 1.0697022152613027 	 Accuracy: 0.1111111111111111
Delta: 0.002828722839463168 	  Loss: 1.0696173581844377 	 Accuracy: 0.1111111111111111
Delta: 0.0031546404314495894 	  Loss: 1.0695702869332393 	 Accuracy: 0.1111111111111111
Delta: 0.002993572849903164 	  Loss: 1.0695209058049029 	 Accuracy: 0.1111111111111111
Delta: 0.003015479063773947 	  Loss: 1.0694852971919362 	 Accuracy: 0.1111111111111111
Delta: 0.0030869913002289223 	  Loss: 1.0694583213386242 	 Accuracy: 0.1111111111111111
Delta: 0.0025079043173131268 	  Loss: 1.069432320737043 	 Accuracy: 0.1111111111111111
Delta: 0.002621497759549435 	  Loss: 1.0694316170492009 	 Accuracy: 0.1111111111111111
Delta: 0.002749924523630523 	  Loss: 1.0694309941085898 	 Accuracy: 0.1111111111111111
Delta: 0.002710574808569755 	  Loss: 1.0694126942947313 	 Accuracy: 0.1111111111111111
Delta: 0.002656172262188484 	  Loss: 1.069397159573787 	 Accuracy: 0.1111111111111111
Delta: 0.002652905184277495 	  Loss: 1.0693823742593507 	 Accuracy: 0.1111111111111111
Delta: 0.0021466659655986855 	  Loss: 1.06936855921901 	 Accuracy: 0.1111111111111111
Delta: 0.0025158042163305923 	  Loss: 1.0693589340881295 	 Accuracy: 0.1111111111111111
Delta: 0.001977413402367913 	  Loss: 1.0693222974572274 	 Accuracy: 0.1111111111111111
Delta: 0.002706840481266488 	  Loss: 1.0693211559394264 	 Accuracy: 0.1111111111111111
Delta: 0.0024553609123107133 	  Loss: 1.0692945789140655 	 Accuracy: 0.1111111111111111
Delta: 0.001451286793515427 	  Loss: 1.0692598060660852 	 Accuracy: 0.1111111111111111
Delta: 0.0010198425217758048 	  Loss: 1.0692297722521138 	 Accuracy: 0.1111111111111111
Delta: 0.0015908916871298067 	  Loss: 1.0692259635681927 	 Accuracy: 0.1111111111111111
Delta: 0.0017741013872007098 	  Loss: 1.0692187561947897 	 Accuracy: 0.1111111111111111
Delta: 0.001737038701373479 	  Loss: 1.0692303367739775 	 Accuracy: 0.1111111111111111
Delta: 0.0011430377339571411 	  Loss: 1.0692057805839763 	 Accuracy: 0.1111111111111111
Delta: 0.001642251746618592 	  Loss: 1.069199074712595 	 Accuracy: 0.1111111111111111
Delta: 0.0017162432496108525 	  Loss: 1.0691962089012028 	 Accuracy: 0.1111111111111111
Delta: 0.0015777331085479194 	  Loss: 1.0691832367514893 	 Accuracy: 0.1111111111111111
Delta: 0.0012425225229272987 	  Loss: 1.0691680095365586 	 Accuracy: 0.1111111111111111
Delta: 0.0023191457578192014 	  Loss: 1.0691572445816764 	 Accuracy: 0.1111111111111111
Delta: 0.0021311373185738114 	  Loss: 1.0691359247661518 	 Accuracy: 0.1111111111111111
Delta: 0.00216355591895205 	  Loss: 1.0691255174167655 	 Accuracy: 0.1111111111111111
Delta: 0.002310351970619285 	  Loss: 1.069091142915403 	 Accuracy: 0.1111111111111111
Delta: 0.002375624511728043 	  Loss: 1.0690739202989699 	 Accuracy: 0.1111111111111111
Delta: 0.002406949271077484 	  Loss: 1.0690599169666224 	 Accuracy: 0.1111111111111111
Delta: 0.0019198436166868503 	  Loss: 1.0690222209466773 	 Accuracy: 0.1111111111111111
Delta: 0.0020423494215335743 	  Loss: 1.0689977069001273 	 Accuracy: 0.1111111111111111
Delta: 0.0021489954683944503 	  Loss: 1.0689666664828095 	 Accuracy: 0.1111111111111111
Delta: 0.002461298633975816 	  Loss: 1.0689511215191776 	 Accuracy: 0.1111111111111111
Delta: 0.0014318334798532062 	  Loss: 1.0689261486069597 	 Accuracy: 0.1111111111111111
Delta: 0.001300260411317758 	  Loss: 1.0689128991798533 	 Accuracy: 0.1111111111111111
Delta: 0.001353262457432943 	  Loss: 1.068915265900984 	 Accuracy: 0.1111111111111111
Delta: 0.0008008987836086527 	  Loss: 1.0689096691481672 	 Accuracy: 0.1111111111111111
Delta: 0.0005008431057099856 	  Loss: 1.0689035999783125 	 Accuracy: 0.1111111111111111
Delta: 0.0008916028688364448 	  Loss: 1.0689023754226823 	 Accuracy: 0.1111111111111111
Delta: 0.0006003978288039043 	  Loss: 1.0688853346355756 	 Accuracy: 0.1111111111111111
Delta: 0.0002700762304379068 	  Loss: 1.0688789620067585 	 Accuracy: 0.1111111111111111
Delta: 0.0005059401022460253 	  Loss: 1.068878406106056 	 Accuracy: 0.1111111111111111
Delta: 0.0007891504932298084 	  Loss: 1.0688759684709939 	 Accuracy: 0.1111111111111111
Delta: 0.0006289481619525787 	  Loss: 1.0688692979963275 	 Accuracy: 0.1111111111111111
Delta: 0.0007374560312434384 	  Loss: 1.0688687984394791 	 Accuracy: 0.1111111111111111
Delta: 0.0004442876879762323 	  Loss: 1.0688735145755155 	 Accuracy: 0.1111111111111111
Delta: 0.0005714288984842845 	  Loss: 1.0688730534318749 	 Accuracy: 0.1111111111111111
Delta: 0.0006119698638325424 	  Loss: 1.0688696747052955 	 Accuracy: 0.1111111111111111
Delta: 0.0005036483217155634 	  Loss: 1.0688656508045333 	 Accuracy: 0.1111111111111111
Delta: 0.0008104584756629842 	  Loss: 1.0688681336499655 	 Accuracy: 0.1111111111111111
Delta: 0.0013308737631896313 	  Loss: 1.0688648870560964 	 Accuracy: 0.1111111111111111
Delta: 0.0005408429541538866 	  Loss: 1.068858288519218 	 Accuracy: 0.1111111111111111
Delta: 0.00010966948729425402 	  Loss: 1.068854794107909 	 Accuracy: 0.1111111111111111
Delta: 0.0005634865563784383 	  Loss: 1.0688541724164526 	 Accuracy: 0.1111111111111111
Delta: 0.00041345061961569056 	  Loss: 1.0688581493181837 	 Accuracy: 0.1111111111111111
Delta: 0.0006054756140628907 	  Loss: 1.0688579333403503 	 Accuracy: 0.1111111111111111
Delta: 0.0004288881737029625 	  Loss: 1.0688536582517958 	 Accuracy: 0.1111111111111111
Delta: 0.00044938700034919077 	  Loss: 1.0688465075756102 	 Accuracy: 0.1111111111111111
Delta: 0.0003995261974589331 	  Loss: 1.068840324532011 	 Accuracy: 0.1111111111111111
Delta: 0.000347632585964029 	  Loss: 1.0688353341411942 	 Accuracy: 0.1111111111111111
Delta: 0.0016642002295036212 	  Loss: 1.068832996798529 	 Accuracy: 0.1111111111111111
Delta: 0.0009342007267580222 	  Loss: 1.068824759839857 	 Accuracy: 0.1111111111111111
Delta: 0.0002029800890072342 	  Loss: 1.0688221205765276 	 Accuracy: 0.1111111111111111
Delta: 0.00014924102477919943 	  Loss: 1.0688208473013514 	 Accuracy: 0.1111111111111111
Delta: 0.0002913590985885037 	  Loss: 1.068819949302351 	 Accuracy: 0.1111111111111111
Delta: 0.00026186821119777445 	  Loss: 1.0688173867334618 	 Accuracy: 0.1111111111111111
Delta: 0.00010152916539265278 	  Loss: 1.0688168788571704 	 Accuracy: 0.1111111111111111
Delta: 0.0001113422213133693 	  Loss: 1.0688172769746218 	 Accuracy: 0.1111111111111111
Delta: 8.768505417529596e-05 	  Loss: 1.0688177875714158 	 Accuracy: 0.1111111111111111
Delta: 0.05973298622060033 	  Loss: 1.0612360210817848 	 Accuracy: 0.47619047619047616
Delta: 0.045744679949818304 	  Loss: 1.05540857749496 	 Accuracy: 0.47619047619047616
Delta: 0.03808680487220794 	  Loss: 1.0518031132965704 	 Accuracy: 0.47619047619047616

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.03206431936566545 	  Loss: 1.0480236356866963 	 Accuracy: 0.47619047619047616
Delta: 0.018992037811300006 	  Loss: 1.045248039933335 	 Accuracy: 0.4603174603174603
Delta: 0.015352226850537751 	  Loss: 1.04384536248589 	 Accuracy: 0.4603174603174603
Delta: 0.014336234099912904 	  Loss: 1.0427294891475147 	 Accuracy: 0.4603174603174603
Delta: 0.01424016544934626 	  Loss: 1.0418892591158477 	 Accuracy: 0.4603174603174603
Delta: 0.014927048648741404 	  Loss: 1.0407519922535076 	 Accuracy: 0.4603174603174603
Delta: 0.01646570643977243 	  Loss: 1.039677937682915 	 Accuracy: 0.4603174603174603
Delta: 0.014443688274532199 	  Loss: 1.038630795823675 	 Accuracy: 0.4603174603174603
Delta: 0.011033777857515505 	  Loss: 1.0379251211551555 	 Accuracy: 0.4603174603174603
Delta: 0.009005582699000871 	  Loss: 1.0375224517933146 	 Accuracy: 0.4603174603174603
Delta: 0.008315588455183598 	  Loss: 1.0373274742198606 	 Accuracy: 0.4603174603174603
Delta: 0.00695691638303423 	  Loss: 1.037190107327126 	 Accuracy: 0.4603174603174603
Delta: 0.006864254505896047 	  Loss: 1.0369689447908539 	 Accuracy: 0.4603174603174603
Delta: 0.006573585324173386 	  Loss: 1.036739920329854 	 Accuracy: 0.4603174603174603
Delta: 0.006059079340793047 	  Loss: 1.0365391805668756 	 Accuracy: 0.4603174603174603
Delta: 0.006435916287093932 	  Loss: 1.036357309467012 	 Accuracy: 0.4603174603174603
Delta: 0.005984003030391519 	  Loss: 1.036188773784048 	 Accuracy: 0.4603174603174603
Delta: 0.005047038492519306 	  Loss: 1.0360800085578388 	 Accuracy: 0.4603174603174603
Delta: 0.004603138043687234 	  Loss: 1.0360072178347677 	 Accuracy: 0.4603174603174603
Delta: 0.002622337631586692 	  Loss: 1.0359390197058236 	 Accuracy: 0.4603174603174603
Delta: 0.0021494797830040294 	  Loss: 1.035901035818262 	 Accuracy: 0.4603174603174603
Delta: 0.003013697814270679 	  Loss: 1.0358560539104635 	 Accuracy: 0.4603174603174603
Delta: 0.0026542119635803345 	  Loss: 1.035802109895311 	 Accuracy: 0.4603174603174603
Delta: 0.0020736290185456845 	  Loss: 1.0357899454165236 	 Accuracy: 0.4603174603174603
Delta: 0.0024573417301609266 	  Loss: 1.0357798922268109 	 Accuracy: 0.4603174603174603
Delta: 0.0017758311373380744 	  Loss: 1.0357629223138156 	 Accuracy: 0.4603174603174603
Delta: 0.002135681966961039 	  Loss: 1.0357546658189936 	 Accuracy: 0.4603174603174603
Delta: 0.0020369094570821342 	  Loss: 1.035741908349734 	 Accuracy: 0.4603174603174603
Delta: 0.002473983504451717 	  Loss: 1.035748205442972 	 Accuracy: 0.4603174603174603
Delta: 0.0018683459501177783 	  Loss: 1.035766218793973 	 Accuracy: 0.4603174603174603
Delta: 0.002080017363247909 	  Loss: 1.0357734540357073 	 Accuracy: 0.4603174603174603
Delta: 0.0020490547969583706 	  Loss: 1.0357621164346076 	 Accuracy: 0.4603174603174603
Delta: 0.0016799271271886317 	  Loss: 1.0357479962951823 	 Accuracy: 0.4603174603174603
Delta: 0.0012609058983489253 	  Loss: 1.0357433298785748 	 Accuracy: 0.4603174603174603
Delta: 0.0011292495090236701 	  Loss: 1.0357431053540123 	 Accuracy: 0.4603174603174603
Delta: 0.0007318229983638967 	  Loss: 1.0357433429803218 	 Accuracy: 0.4603174603174603
Delta: 0.0009741359021885084 	  Loss: 1.0357419197084727 	 Accuracy: 0.4603174603174603
Delta: 0.0013463429728711195 	  Loss: 1.0357358949020452 	 Accuracy: 0.4603174603174603
Delta: 0.00048825550910265624 	  Loss: 1.0357371046669464 	 Accuracy: 0.4603174603174603
Delta: 0.0001746789662764283 	  Loss: 1.0357385087263786 	 Accuracy: 0.4603174603174603
Delta: 0.00014782749216081618 	  Loss: 1.035737916614629 	 Accuracy: 0.4603174603174603
Delta: 0.0004506752652468979 	  Loss: 1.0357378691492198 	 Accuracy: 0.4603174603174603
converged at iter  44
Delta: 0.060525421330272465 	  Loss: 1.065054477596802 	 Accuracy: 0.6935483870967742
Delta: 0.04517364243159419 	  Loss: 1.0588896040599594 	 Accuracy: 0.7419354838709677
Delta: 0.0352375846875861 	  Loss: 1.055455184577862 	 Accuracy: 0.7580645161290323
Delta: 0.029010690868864163 	  Loss: 1.0529161633068875 	 Accuracy: 0.7741935483870968

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.020767502403868092 	  Loss: 1.0504071897885092 	 Accuracy: 0.7741935483870968
Delta: 0.016371581297021973 	  Loss: 1.0488174168529105 	 Accuracy: 0.7741935483870968
Delta: 0.014448839478199693 	  Loss: 1.0477829522453892 	 Accuracy: 0.7741935483870968
Delta: 0.011537445827766555 	  Loss: 1.0470822053482194 	 Accuracy: 0.7741935483870968
Delta: 0.008027821259355526 	  Loss: 1.0467582841014451 	 Accuracy: 0.7741935483870968
Delta: 0.0053905979784144185 	  Loss: 1.0465606954338398 	 Accuracy: 0.7741935483870968
Delta: 0.0038183099490289754 	  Loss: 1.0464972120748952 	 Accuracy: 0.7741935483870968
Delta: 0.0033509346147851727 	  Loss: 1.0464793127723262 	 Accuracy: 0.7741935483870968
Delta: 0.003165269628130107 	  Loss: 1.0464478979965568 	 Accuracy: 0.7741935483870968
Delta: 0.0027603315967383683 	  Loss: 1.0464033452059773 	 Accuracy: 0.7741935483870968
Delta: 0.002795249582921825 	  Loss: 1.0463487900962072 	 Accuracy: 0.7741935483870968
Delta: 0.0025248098091999478 	  Loss: 1.0463025449294212 	 Accuracy: 0.7741935483870968
Delta: 0.0025134095435670523 	  Loss: 1.0462789403973958 	 Accuracy: 0.7741935483870968
Delta: 0.0016233040377220326 	  Loss: 1.0462699242857763 	 Accuracy: 0.7741935483870968
Delta: 0.0026023425337682476 	  Loss: 1.0462700634145847 	 Accuracy: 0.7741935483870968
Delta: 0.0015246587904197224 	  Loss: 1.046261429459233 	 Accuracy: 0.7741935483870968
Delta: 0.0012199732535069835 	  Loss: 1.0462449365276578 	 Accuracy: 0.7741935483870968
Delta: 0.0013063780921151367 	  Loss: 1.0462441560219784 	 Accuracy: 0.7741935483870968
Delta: 0.0012263663132139175 	  Loss: 1.0462462604782463 	 Accuracy: 0.7741935483870968
Delta: 0.0018140559302204358 	  Loss: 1.0462378691076977 	 Accuracy: 0.7741935483870968
Delta: 0.0012454680972329745 	  Loss: 1.0462072530721258 	 Accuracy: 0.7741935483870968
Delta: 0.0019960565449445382 	  Loss: 1.0461948508717431 	 Accuracy: 0.7741935483870968
Delta: 0.002031837584933701 	  Loss: 1.046179648718212 	 Accuracy: 0.7741935483870968
Delta: 0.0022038994635925043 	  Loss: 1.0461884129116306 	 Accuracy: 0.7741935483870968
Delta: 0.0014985278208658203 	  Loss: 1.0461896990445756 	 Accuracy: 0.7741935483870968
Delta: 0.0014775460480053605 	  Loss: 1.0461974012619644 	 Accuracy: 0.7741935483870968
Delta: 0.0024672876392373097 	  Loss: 1.0462051317093892 	 Accuracy: 0.7741935483870968
Delta: 0.0018525415201520812 	  Loss: 1.0461797066849208 	 Accuracy: 0.7741935483870968
Delta: 0.0026132600118133464 	  Loss: 1.0461712044134244 	 Accuracy: 0.7741935483870968
Delta: 0.0020524515253832814 	  Loss: 1.0461492477813374 	 Accuracy: 0.7741935483870968
Delta: 0.0026008502092606596 	  Loss: 1.0461319429285854 	 Accuracy: 0.7741935483870968
Delta: 0.0025786328237468186 	  Loss: 1.0461078703010787 	 Accuracy: 0.7741935483870968
Delta: 0.0024707531755589454 	  Loss: 1.0461069375615373 	 Accuracy: 0.7741935483870968
Delta: 0.002588027444805714 	  Loss: 1.0461190793934576 	 Accuracy: 0.7741935483870968
Delta: 0.0029464462334497844 	  Loss: 1.0461215707424523 	 Accuracy: 0.7741935483870968
Delta: 0.003017712767420272 	  Loss: 1.046103926665888 	 Accuracy: 0.7741935483870968
Delta: 0.003323336456368381 	  Loss: 1.046070204699956 	 Accuracy: 0.7741935483870968
Delta: 0.00492773864612012 	  Loss: 1.0460136569189267 	 Accuracy: 0.7741935483870968
Delta: 0.00408993884629167 	  Loss: 1.045938766906895 	 Accuracy: 0.7741935483870968
Delta: 0.003951480152394998 	  Loss: 1.0459056524575816 	 Accuracy: 0.7741935483870968
Delta: 0.004059408154914615 	  Loss: 1.0458898579910334 	 Accuracy: 0.7741935483870968
Delta: 0.0044940842163712445 	  Loss: 1.045825466113116 	 Accuracy: 0.7741935483870968
Delta: 0.0041065766517139855 	  Loss: 1.045763138779398 	 Accuracy: 0.7741935483870968
Delta: 0.0041303586152141416 	  Loss: 1.0456991215688518 	 Accuracy: 0.7741935483870968
Delta: 0.005243580021457384 	  Loss: 1.0456519978438048 	 Accuracy: 0.7741935483870968
Delta: 0.004532282989871471 	  Loss: 1.0455854498192423 	 Accuracy: 0.7741935483870968
Delta: 0.004454019629333806 	  Loss: 1.0455552472505976 	 Accuracy: 0.7741935483870968
Delta: 0.004247438267854356 	  Loss: 1.0455069868660392 	 Accuracy: 0.7741935483870968
Delta: 0.003395991902281079 	  Loss: 1.0454470966866753 	 Accuracy: 0.7741935483870968
Delta: 0.0033932888743794833 	  Loss: 1.0454222058336293 	 Accuracy: 0.7741935483870968
Delta: 0.0026584151671191717 	  Loss: 1.04538823205576 	 Accuracy: 0.7741935483870968
Delta: 0.0021899974218704574 	  Loss: 1.0453662601829752 	 Accuracy: 0.7741935483870968
Delta: 0.0018969647468849613 	  Loss: 1.0453541228351384 	 Accuracy: 0.7741935483870968
Delta: 0.0016823119247821815 	  Loss: 1.045352598540991 	 Accuracy: 0.7741935483870968
Delta: 0.0013409104577557897 	  Loss: 1.0453624275850575 	 Accuracy: 0.7741935483870968
Delta: 0.0011014247636222192 	  Loss: 1.045354601746291 	 Accuracy: 0.7741935483870968
Delta: 0.0014949911305856256 	  Loss: 1.045356404044255 	 Accuracy: 0.7741935483870968
Delta: 0.00132473130555377 	  Loss: 1.0453625083370113 	 Accuracy: 0.7741935483870968
Delta: 0.001417562599420966 	  Loss: 1.0453634347204832 	 Accuracy: 0.7741935483870968
Delta: 0.001556240372251503 	  Loss: 1.0453695722640113 	 Accuracy: 0.7741935483870968
Delta: 0.001194942137378633 	  Loss: 1.0453615326175747 	 Accuracy: 0.7741935483870968
Delta: 0.0012245550174328484 	  Loss: 1.0453559018301346 	 Accuracy: 0.7741935483870968
Delta: 0.0007022077855205664 	  Loss: 1.0453585779032537 	 Accuracy: 0.7741935483870968
Delta: 0.000824605393083699 	  Loss: 1.0453624613526855 	 Accuracy: 0.7741935483870968
Delta: 0.0006948469749535287 	  Loss: 1.0453590536647135 	 Accuracy: 0.7741935483870968
Delta: 0.0006698515797446227 	  Loss: 1.0453481895695207 	 Accuracy: 0.7741935483870968
Delta: 0.0009050390385479657 	  Loss: 1.0453405425927573 	 Accuracy: 0.7741935483870968
Delta: 0.001007191972656884 	  Loss: 1.045332325062202 	 Accuracy: 0.7741935483870968
Delta: 0.0018772591784020133 	  Loss: 1.0453278423919803 	 Accuracy: 0.7741935483870968
Delta: 0.0016540701326442759 	  Loss: 1.045305574522268 	 Accuracy: 0.7741935483870968
Delta: 0.0008740695128505209 	  Loss: 1.0452956891556529 	 Accuracy: 0.7741935483870968
Delta: 0.0013673122933880834 	  Loss: 1.0452902678647793 	 Accuracy: 0.7741935483870968
Delta: 0.0010626027993211583 	  Loss: 1.0452847840427155 	 Accuracy: 0.7741935483870968
Delta: 0.0016259653009618802 	  Loss: 1.0452747573632784 	 Accuracy: 0.7741935483870968
Delta: 0.0014462819994105532 	  Loss: 1.0452384555862646 	 Accuracy: 0.7741935483870968
Delta: 0.0017600438878116235 	  Loss: 1.045230520810528 	 Accuracy: 0.7741935483870968
Delta: 0.0010901256845450462 	  Loss: 1.0452268762371708 	 Accuracy: 0.7741935483870968
Delta: 0.0017765732274982525 	  Loss: 1.0452144278652669 	 Accuracy: 0.7741935483870968
Delta: 0.0023930434194931152 	  Loss: 1.0452044454071099 	 Accuracy: 0.7741935483870968
Delta: 0.003374160340713064 	  Loss: 1.0451805006959867 	 Accuracy: 0.7741935483870968
Delta: 0.003044365209673732 	  Loss: 1.0451579822128234 	 Accuracy: 0.7741935483870968
Delta: 0.0025634099590310547 	  Loss: 1.045144139118507 	 Accuracy: 0.7741935483870968
Delta: 0.0027306339602385585 	  Loss: 1.045110741317273 	 Accuracy: 0.7741935483870968
Delta: 0.002365712675892002 	  Loss: 1.04508915611218 	 Accuracy: 0.7741935483870968
Delta: 0.0035324976904606256 	  Loss: 1.0450484939876818 	 Accuracy: 0.7741935483870968
Delta: 0.003309159503038352 	  Loss: 1.0449733627339313 	 Accuracy: 0.7741935483870968
Delta: 0.004512314425112616 	  Loss: 1.0449398077400316 	 Accuracy: 0.7741935483870968
Delta: 0.004137763886436655 	  Loss: 1.044896879714028 	 Accuracy: 0.7741935483870968
Delta: 0.0031345964560441295 	  Loss: 1.044851417150526 	 Accuracy: 0.7741935483870968
Delta: 0.0032198815290655682 	  Loss: 1.0447878911118105 	 Accuracy: 0.7741935483870968
Delta: 0.0037412750236195617 	  Loss: 1.044730945778375 	 Accuracy: 0.7741935483870968
Delta: 0.003534383310654767 	  Loss: 1.0446475293347701 	 Accuracy: 0.7741935483870968
Delta: 0.003167420084166109 	  Loss: 1.044534720429731 	 Accuracy: 0.7741935483870968
Delta: 0.0029996289419655683 	  Loss: 1.0444709702645585 	 Accuracy: 0.7741935483870968
Delta: 0.0035704678256526586 	  Loss: 1.0444330363144703 	 Accuracy: 0.7741935483870968
Delta: 0.003222136119405058 	  Loss: 1.0443571076893272 	 Accuracy: 0.7741935483870968
Delta: 0.06059800532208044 	  Loss: 1.0620001383522424 	 Accuracy: 0.4838709677419355
Delta: 0.04214839211320598 	  Loss: 1.0566163539885478 	 Accuracy: 0.2903225806451613
Delta: 0.03708309094832181 	  Loss: 1.0523289786192136 	 Accuracy: 0.2903225806451613

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.026045701050211992 	  Loss: 1.0494021317992563 	 Accuracy: 0.2903225806451613
Delta: 0.016539512096570185 	  Loss: 1.048065344650153 	 Accuracy: 0.2903225806451613
Delta: 0.013309585038450419 	  Loss: 1.0471712915799487 	 Accuracy: 0.2903225806451613
Delta: 0.010421974333736608 	  Loss: 1.046534812694233 	 Accuracy: 0.2903225806451613
Delta: 0.009621654115434664 	  Loss: 1.045998146910347 	 Accuracy: 0.2903225806451613
Delta: 0.009398025266466688 	  Loss: 1.0456049855118708 	 Accuracy: 0.2903225806451613
Delta: 0.009951424548037208 	  Loss: 1.0453296937344931 	 Accuracy: 0.2903225806451613
Delta: 0.009699119949563463 	  Loss: 1.0450303448076992 	 Accuracy: 0.2903225806451613
Delta: 0.008284826824388797 	  Loss: 1.0447238162026444 	 Accuracy: 0.2903225806451613
Delta: 0.007207296250235427 	  Loss: 1.0444792597278103 	 Accuracy: 0.2903225806451613
Delta: 0.0063390748412376005 	  Loss: 1.0442990123766323 	 Accuracy: 0.2903225806451613
Delta: 0.004994020591626075 	  Loss: 1.044246215726599 	 Accuracy: 0.2903225806451613
Delta: 0.00576899817029717 	  Loss: 1.0441305026533607 	 Accuracy: 0.2903225806451613
Delta: 0.0042183166924251595 	  Loss: 1.044046164807235 	 Accuracy: 0.2903225806451613
Delta: 0.003578908930961659 	  Loss: 1.0439897771065318 	 Accuracy: 0.2903225806451613
Delta: 0.0036135491243543994 	  Loss: 1.0439387166208407 	 Accuracy: 0.2903225806451613
Delta: 0.0038747287902477397 	  Loss: 1.0438912570346122 	 Accuracy: 0.2903225806451613
Delta: 0.0031950233408351873 	  Loss: 1.0438843890606448 	 Accuracy: 0.2903225806451613
Delta: 0.0021038188085874534 	  Loss: 1.0438613246388857 	 Accuracy: 0.2903225806451613
Delta: 0.0022342704392567018 	  Loss: 1.0438482065747459 	 Accuracy: 0.2903225806451613
Delta: 0.002046616029613432 	  Loss: 1.0438308150703206 	 Accuracy: 0.2903225806451613
Delta: 0.0019668073778208533 	  Loss: 1.0438171880669866 	 Accuracy: 0.2903225806451613
Delta: 0.0015544065012556636 	  Loss: 1.0438194079487317 	 Accuracy: 0.2903225806451613
Delta: 0.001573068933193884 	  Loss: 1.0438181030395102 	 Accuracy: 0.2903225806451613
Delta: 0.0010140664484586525 	  Loss: 1.0438111343798084 	 Accuracy: 0.2903225806451613
Delta: 0.0014038713932883753 	  Loss: 1.043811690263679 	 Accuracy: 0.2903225806451613
Delta: 0.0016989909757415195 	  Loss: 1.0438119268604533 	 Accuracy: 0.2903225806451613
Delta: 0.0011912125630264888 	  Loss: 1.0438035507086059 	 Accuracy: 0.2903225806451613
Delta: 0.0009371286766976003 	  Loss: 1.0437918129362274 	 Accuracy: 0.2903225806451613
Delta: 0.0016738478217361847 	  Loss: 1.043782508369381 	 Accuracy: 0.2903225806451613
Delta: 0.0012785195355479514 	  Loss: 1.043773752547534 	 Accuracy: 0.2903225806451613
Delta: 0.001943873254296307 	  Loss: 1.0437599192409532 	 Accuracy: 0.2903225806451613
Delta: 0.0006011788416278862 	  Loss: 1.0437440696688778 	 Accuracy: 0.2903225806451613
Delta: 0.00041561692350270806 	  Loss: 1.043740299606462 	 Accuracy: 0.2903225806451613
Delta: 0.0003272336151109082 	  Loss: 1.0437403107315621 	 Accuracy: 0.2903225806451613
converged at iter  37
Delta: 0.057834745076203835 	  Loss: 1.0737529177649892 	 Accuracy: 0.5483870967741935
Delta: 0.04524297140641527 	  Loss: 1.0623502965697327 	 Accuracy: 0.25806451612903225
Delta: 0.028343494941702338 	  Loss: 1.0561877668237518 	 Accuracy: 0.3064516129032258

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.020987512460586215 	  Loss: 1.0534677905862702 	 Accuracy: 0.3225806451612903
Delta: 0.012184321145752554 	  Loss: 1.0521215215780346 	 Accuracy: 0.3225806451612903
Delta: 0.008597737361352038 	  Loss: 1.0516075814850234 	 Accuracy: 0.3225806451612903
Delta: 0.007129423320247494 	  Loss: 1.0513038868360982 	 Accuracy: 0.3225806451612903
Delta: 0.005877918312537049 	  Loss: 1.0511288080619834 	 Accuracy: 0.3225806451612903
Delta: 0.005609029065496499 	  Loss: 1.050946092942601 	 Accuracy: 0.3225806451612903
Delta: 0.005767074919870523 	  Loss: 1.050827732049115 	 Accuracy: 0.3225806451612903
Delta: 0.0058777974706302576 	  Loss: 1.0506937373285916 	 Accuracy: 0.3225806451612903
Delta: 0.0051507455342653325 	  Loss: 1.0505608585182178 	 Accuracy: 0.3225806451612903
Delta: 0.005625805752844837 	  Loss: 1.05043479188594 	 Accuracy: 0.3225806451612903
Delta: 0.0045128982098254005 	  Loss: 1.0503413250137834 	 Accuracy: 0.3225806451612903
Delta: 0.005329994740404069 	  Loss: 1.0502660174116953 	 Accuracy: 0.3225806451612903
Delta: 0.0050502964434111335 	  Loss: 1.0501763028341666 	 Accuracy: 0.3225806451612903
Delta: 0.005418644095785148 	  Loss: 1.0501132953663213 	 Accuracy: 0.3225806451612903
Delta: 0.0047951143386238205 	  Loss: 1.0500048899449788 	 Accuracy: 0.3225806451612903
Delta: 0.004259024696604371 	  Loss: 1.0498977408667762 	 Accuracy: 0.3225806451612903
Delta: 0.00401346943671414 	  Loss: 1.0498108232731231 	 Accuracy: 0.3225806451612903
Delta: 0.0045692244501182025 	  Loss: 1.0497294458885043 	 Accuracy: 0.3225806451612903
Delta: 0.004429645201146118 	  Loss: 1.0496383000897462 	 Accuracy: 0.3225806451612903
Delta: 0.0035443711369677606 	  Loss: 1.0495453184691348 	 Accuracy: 0.3225806451612903
Delta: 0.0042549070867495264 	  Loss: 1.049471484068841 	 Accuracy: 0.3225806451612903
Delta: 0.0030653631929295597 	  Loss: 1.04941344651702 	 Accuracy: 0.3225806451612903
Delta: 0.0030108472516668 	  Loss: 1.0493802745224543 	 Accuracy: 0.3225806451612903
Delta: 0.0033108471593379374 	  Loss: 1.0493238929117439 	 Accuracy: 0.3225806451612903
Delta: 0.002950947550101954 	  Loss: 1.0492654200161144 	 Accuracy: 0.3225806451612903
Delta: 0.0030964560891455464 	  Loss: 1.0492235227120443 	 Accuracy: 0.3225806451612903
Delta: 0.0022869018587926156 	  Loss: 1.0492023598065092 	 Accuracy: 0.3225806451612903
Delta: 0.0027104755335034068 	  Loss: 1.0491661152044882 	 Accuracy: 0.3225806451612903
Delta: 0.0029769309338420775 	  Loss: 1.0491420660314597 	 Accuracy: 0.3225806451612903
Delta: 0.0025935028089661247 	  Loss: 1.0491021662981541 	 Accuracy: 0.3225806451612903
Delta: 0.003688312533793742 	  Loss: 1.0490824574790856 	 Accuracy: 0.3225806451612903
Delta: 0.0031749449867034592 	  Loss: 1.049041678614015 	 Accuracy: 0.3225806451612903
Delta: 0.003425281757378432 	  Loss: 1.0490104767212582 	 Accuracy: 0.3225806451612903
Delta: 0.0030987185119315656 	  Loss: 1.0489801994659342 	 Accuracy: 0.3225806451612903
Delta: 0.003543233246502487 	  Loss: 1.0489445206550505 	 Accuracy: 0.3225806451612903
Delta: 0.0033140807045269147 	  Loss: 1.048930874064696 	 Accuracy: 0.3225806451612903
Delta: 0.0031670539465960376 	  Loss: 1.048909115363553 	 Accuracy: 0.3225806451612903
Delta: 0.0022423251117608773 	  Loss: 1.0488796213470897 	 Accuracy: 0.3225806451612903
Delta: 0.0025604394556025907 	  Loss: 1.048874353412296 	 Accuracy: 0.3225806451612903
Delta: 0.002466415336700729 	  Loss: 1.0488629476739613 	 Accuracy: 0.3225806451612903
Delta: 0.0029938299142068508 	  Loss: 1.0488648436376362 	 Accuracy: 0.3225806451612903
Delta: 0.002561601144887337 	  Loss: 1.0488518791623322 	 Accuracy: 0.3225806451612903
Delta: 0.0026194319725591996 	  Loss: 1.0488359492014716 	 Accuracy: 0.3225806451612903
Delta: 0.002657118449879478 	  Loss: 1.0488383307476181 	 Accuracy: 0.3225806451612903
Delta: 0.0025836318344101576 	  Loss: 1.048835356493377 	 Accuracy: 0.3225806451612903
Delta: 0.00255733585252328 	  Loss: 1.0488309375161868 	 Accuracy: 0.3225806451612903
Delta: 0.003011724050799165 	  Loss: 1.0488337967912396 	 Accuracy: 0.3225806451612903
Delta: 0.003842225600582217 	  Loss: 1.0488301781326537 	 Accuracy: 0.3225806451612903
Delta: 0.0033079323929599736 	  Loss: 1.048767407682672 	 Accuracy: 0.3225806451612903
Delta: 0.0031392215804616373 	  Loss: 1.048753814555277 	 Accuracy: 0.3225806451612903
Delta: 0.003175727823197738 	  Loss: 1.0487378217029801 	 Accuracy: 0.3225806451612903
Delta: 0.0037011297386427174 	  Loss: 1.0487242693413705 	 Accuracy: 0.3225806451612903
Delta: 0.0038753113774530677 	  Loss: 1.0486938296555923 	 Accuracy: 0.3225806451612903
Delta: 0.003467384171445814 	  Loss: 1.048627129362648 	 Accuracy: 0.3225806451612903
Delta: 0.003908573001088716 	  Loss: 1.0485578641102031 	 Accuracy: 0.3225806451612903
Delta: 0.0035596180110918393 	  Loss: 1.0484825364907178 	 Accuracy: 0.3225806451612903
Delta: 0.002560603510104135 	  Loss: 1.0484216281663423 	 Accuracy: 0.3225806451612903
Delta: 0.0025162231689792856 	  Loss: 1.0483964725450967 	 Accuracy: 0.3225806451612903
Delta: 0.0025613315851202136 	  Loss: 1.0483817186028517 	 Accuracy: 0.3225806451612903
Delta: 0.0014093869452818123 	  Loss: 1.0483707023699125 	 Accuracy: 0.3225806451612903
Delta: 0.0013153885405140014 	  Loss: 1.048364999124434 	 Accuracy: 0.3225806451612903
Delta: 0.0018086835819843894 	  Loss: 1.0483562812332852 	 Accuracy: 0.3225806451612903
Delta: 0.0017880143736781358 	  Loss: 1.048357955650081 	 Accuracy: 0.3225806451612903
Delta: 0.0011427328109249973 	  Loss: 1.0483557030644393 	 Accuracy: 0.3225806451612903
Delta: 0.001082301438360728 	  Loss: 1.0483454865075759 	 Accuracy: 0.3225806451612903
Delta: 0.001260930368918239 	  Loss: 1.0483498177748252 	 Accuracy: 0.3225806451612903
Delta: 0.0010516707557502345 	  Loss: 1.0483493629782554 	 Accuracy: 0.3225806451612903
Delta: 0.0011509346358361797 	  Loss: 1.0483498843896513 	 Accuracy: 0.3225806451612903
Delta: 0.0014603616797533676 	  Loss: 1.0483534459636283 	 Accuracy: 0.3225806451612903
Delta: 0.0022787196808159564 	  Loss: 1.0483440964297581 	 Accuracy: 0.3225806451612903
Delta: 0.0018101001590115663 	  Loss: 1.048313846277677 	 Accuracy: 0.3225806451612903
Delta: 0.001710534880995911 	  Loss: 1.0482820417798782 	 Accuracy: 0.3225806451612903
Delta: 0.0022467452354766365 	  Loss: 1.0482567901145745 	 Accuracy: 0.3225806451612903
Delta: 0.002090863200996358 	  Loss: 1.0482383171281113 	 Accuracy: 0.3225806451612903
Delta: 0.0012348489044561274 	  Loss: 1.048215426552634 	 Accuracy: 0.3225806451612903
Delta: 0.0011178929936864785 	  Loss: 1.0482055714710135 	 Accuracy: 0.3225806451612903
Delta: 0.0016086797689222523 	  Loss: 1.0481874344559285 	 Accuracy: 0.3225806451612903
Delta: 0.0010767260640263897 	  Loss: 1.0481617110200605 	 Accuracy: 0.3225806451612903
Delta: 0.001312049201038572 	  Loss: 1.0481607570287819 	 Accuracy: 0.3225806451612903
Delta: 0.0012579933739070245 	  Loss: 1.0481487259472568 	 Accuracy: 0.3225806451612903
Delta: 0.001086429998253131 	  Loss: 1.0481401481870833 	 Accuracy: 0.3225806451612903
Delta: 0.0013299829299654026 	  Loss: 1.048137612886051 	 Accuracy: 0.3225806451612903
Delta: 0.0008368554396538654 	  Loss: 1.0481339001542738 	 Accuracy: 0.3225806451612903
Delta: 0.0005630365356501107 	  Loss: 1.0481268471554124 	 Accuracy: 0.3225806451612903
Delta: 0.000438058748189013 	  Loss: 1.048123274277368 	 Accuracy: 0.3225806451612903
Delta: 0.0004814518316183812 	  Loss: 1.0481196769301189 	 Accuracy: 0.3225806451612903
Delta: 0.00023342661820333483 	  Loss: 1.0481193336073922 	 Accuracy: 0.3225806451612903
Delta: 0.0003363679677155455 	  Loss: 1.0481188801638701 	 Accuracy: 0.3225806451612903
Delta: 0.00036450617030159044 	  Loss: 1.0481177478360673 	 Accuracy: 0.3225806451612903
Delta: 0.0005467654195013913 	  Loss: 1.0481132137607618 	 Accuracy: 0.3225806451612903
Delta: 0.0008820194181464034 	  Loss: 1.0481082120160874 	 Accuracy: 0.3225806451612903
Delta: 0.0006408710799330916 	  Loss: 1.0481029479375796 	 Accuracy: 0.3225806451612903
Delta: 0.0004052809618850638 	  Loss: 1.0481020370446343 	 Accuracy: 0.3225806451612903
Delta: 0.0004448163682780419 	  Loss: 1.0480986644750274 	 Accuracy: 0.3225806451612903
Delta: 0.00031465385759328065 	  Loss: 1.0480951777606198 	 Accuracy: 0.3225806451612903
Delta: 0.00013995837267145953 	  Loss: 1.0480963717466096 	 Accuracy: 0.3225806451612903
Delta: 0.00013899029366819723 	  Loss: 1.0480969749504134 	 Accuracy: 0.3225806451612903
Delta: 0.05884413092164299 	  Loss: 1.0776311329931043 	 Accuracy: 0.31746031746031744
Delta: 0.040995408976250626 	  Loss: 1.0728131481288385 	 Accuracy: 0.2698412698412698

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028737493253436053 	  Loss: 1.0681519385364275 	 Accuracy: 0.25396825396825395
Delta: 0.020213924850887497 	  Loss: 1.0653249628233066 	 Accuracy: 0.25396825396825395
Delta: 0.017405188179079132 	  Loss: 1.063069133369951 	 Accuracy: 0.25396825396825395
Delta: 0.01590604650881944 	  Loss: 1.061231142622739 	 Accuracy: 0.25396825396825395
Delta: 0.0127468971494764 	  Loss: 1.0603001605184743 	 Accuracy: 0.25396825396825395
Delta: 0.010987190006279646 	  Loss: 1.059565485808216 	 Accuracy: 0.25396825396825395
Delta: 0.01008605047630262 	  Loss: 1.0590753707748441 	 Accuracy: 0.25396825396825395
Delta: 0.008317893020600396 	  Loss: 1.0586749463981153 	 Accuracy: 0.25396825396825395
Delta: 0.006553272913994929 	  Loss: 1.0584696110206049 	 Accuracy: 0.25396825396825395
Delta: 0.005356022118556831 	  Loss: 1.058315324163024 	 Accuracy: 0.25396825396825395
Delta: 0.005412199971361378 	  Loss: 1.0582201020648485 	 Accuracy: 0.25396825396825395
Delta: 0.005053840798835192 	  Loss: 1.0581423163289854 	 Accuracy: 0.25396825396825395
Delta: 0.004284361770655502 	  Loss: 1.0580818855224479 	 Accuracy: 0.25396825396825395
Delta: 0.00456696012585509 	  Loss: 1.0580022888226472 	 Accuracy: 0.25396825396825395
Delta: 0.0036706291157285907 	  Loss: 1.057954682619818 	 Accuracy: 0.25396825396825395
Delta: 0.003476485305664965 	  Loss: 1.0579134942584236 	 Accuracy: 0.25396825396825395
Delta: 0.002955572332385808 	  Loss: 1.0578345211372546 	 Accuracy: 0.25396825396825395
Delta: 0.003226641443424352 	  Loss: 1.0577684529397755 	 Accuracy: 0.25396825396825395
Delta: 0.0034919858880134926 	  Loss: 1.0577130849598038 	 Accuracy: 0.25396825396825395
Delta: 0.003921718753309806 	  Loss: 1.0576835910781957 	 Accuracy: 0.25396825396825395
Delta: 0.003955371473198203 	  Loss: 1.0576136846490096 	 Accuracy: 0.25396825396825395
Delta: 0.004035874533235207 	  Loss: 1.0575686678081895 	 Accuracy: 0.25396825396825395
Delta: 0.003054355591768338 	  Loss: 1.0575255262797991 	 Accuracy: 0.25396825396825395
Delta: 0.0029685671938110567 	  Loss: 1.0575040783991008 	 Accuracy: 0.25396825396825395
Delta: 0.004156518667415439 	  Loss: 1.0574715153579584 	 Accuracy: 0.25396825396825395
Delta: 0.004519407569632635 	  Loss: 1.0574381931439778 	 Accuracy: 0.25396825396825395
Delta: 0.004139105470134043 	  Loss: 1.0574019902216616 	 Accuracy: 0.25396825396825395
Delta: 0.003389869052155576 	  Loss: 1.0573669069764828 	 Accuracy: 0.25396825396825395
Delta: 0.002744583710916305 	  Loss: 1.0573340804262479 	 Accuracy: 0.25396825396825395
Delta: 0.0029556694755411756 	  Loss: 1.05730862590416 	 Accuracy: 0.25396825396825395
Delta: 0.003619330095524192 	  Loss: 1.0572653448372225 	 Accuracy: 0.25396825396825395
Delta: 0.003022389468053202 	  Loss: 1.0572202406087907 	 Accuracy: 0.25396825396825395
Delta: 0.0025513879952284925 	  Loss: 1.0571779527419447 	 Accuracy: 0.25396825396825395
Delta: 0.003084089399393624 	  Loss: 1.0571547452874746 	 Accuracy: 0.25396825396825395
Delta: 0.003507813298639091 	  Loss: 1.057100608645754 	 Accuracy: 0.25396825396825395
Delta: 0.0031545976700715034 	  Loss: 1.0570295653971034 	 Accuracy: 0.25396825396825395
Delta: 0.002572338607345574 	  Loss: 1.0570116510478642 	 Accuracy: 0.25396825396825395
Delta: 0.002677664871246474 	  Loss: 1.056973767530149 	 Accuracy: 0.25396825396825395
Delta: 0.0027818213252750364 	  Loss: 1.056936455568557 	 Accuracy: 0.25396825396825395
Delta: 0.003934748030150415 	  Loss: 1.056915481381671 	 Accuracy: 0.25396825396825395
Delta: 0.002684345958397305 	  Loss: 1.0569076615475972 	 Accuracy: 0.25396825396825395
Delta: 0.0021859500476162723 	  Loss: 1.0569079814462294 	 Accuracy: 0.25396825396825395
Delta: 0.0024843892700565553 	  Loss: 1.056894951729923 	 Accuracy: 0.25396825396825395
Delta: 0.0029009924500823926 	  Loss: 1.0568818726069296 	 Accuracy: 0.25396825396825395
Delta: 0.0019617721258509023 	  Loss: 1.0568782885228676 	 Accuracy: 0.25396825396825395
Delta: 0.0015207740638730973 	  Loss: 1.0568776568415759 	 Accuracy: 0.25396825396825395
Delta: 0.001484995400456067 	  Loss: 1.0568688085015416 	 Accuracy: 0.25396825396825395
Delta: 0.0024834942766814075 	  Loss: 1.0568614443787432 	 Accuracy: 0.25396825396825395
Delta: 0.002275224407260053 	  Loss: 1.0568349170518951 	 Accuracy: 0.25396825396825395
Delta: 0.0011987314154500613 	  Loss: 1.0568203734852135 	 Accuracy: 0.25396825396825395
Delta: 0.0016676914949364907 	  Loss: 1.056821474797652 	 Accuracy: 0.25396825396825395
Delta: 0.0012422147939396319 	  Loss: 1.056828651135791 	 Accuracy: 0.25396825396825395
Delta: 0.001458954254664363 	  Loss: 1.0568292386161429 	 Accuracy: 0.25396825396825395
Delta: 0.0007238505058034618 	  Loss: 1.0568404816538275 	 Accuracy: 0.25396825396825395
Delta: 0.00040461286597984046 	  Loss: 1.0568383089506692 	 Accuracy: 0.25396825396825395
Delta: 0.0007071809111875568 	  Loss: 1.0568359922470298 	 Accuracy: 0.25396825396825395
Delta: 0.0005147434832227552 	  Loss: 1.056832217135439 	 Accuracy: 0.25396825396825395
Delta: 0.0005220228237158573 	  Loss: 1.0568315473278571 	 Accuracy: 0.25396825396825395
Delta: 0.0005739786199919365 	  Loss: 1.0568296966970667 	 Accuracy: 0.25396825396825395
Delta: 0.00023681951473700347 	  Loss: 1.0568305597818761 	 Accuracy: 0.25396825396825395
Delta: 0.00017098575604749405 	  Loss: 1.0568323560569084 	 Accuracy: 0.25396825396825395
Delta: 0.00021330330936365367 	  Loss: 1.0568329738134123 	 Accuracy: 0.25396825396825395
Delta: 0.00042745497955558787 	  Loss: 1.0568347976041217 	 Accuracy: 0.25396825396825395
Delta: 0.0002895404891965376 	  Loss: 1.0568361261200785 	 Accuracy: 0.25396825396825395
Delta: 7.5016388666584e-05 	  Loss: 1.0568329897236937 	 Accuracy: 0.25396825396825395
Delta: 4.3752763897997195e-06 	  Loss: 1.0568325526161497 	 Accuracy: 0.25396825396825395
Delta: 2.448883159673212e-17 	  Loss: 1.0568325526161497 	 Accuracy: 0.25396825396825395
converged at iter  68
Delta: 0.061610091276842194 	  Loss: 1.0603475628489827 	 Accuracy: 0.2698412698412698
Delta: 0.0409074560954238 	  Loss: 1.0531129390577258 	 Accuracy: 0.2222222222222222
Delta: 0.03416918208622962 	  Loss: 1.0480115237448735 	 Accuracy: 0.2222222222222222

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.024726070142083875 	  Loss: 1.0432878480586876 	 Accuracy: 0.2222222222222222
Delta: 0.01778731528690302 	  Loss: 1.040656222449436 	 Accuracy: 0.2222222222222222
Delta: 0.013935169434583216 	  Loss: 1.0392440197786867 	 Accuracy: 0.2222222222222222
Delta: 0.01230998883408907 	  Loss: 1.0384794694213986 	 Accuracy: 0.2222222222222222
Delta: 0.01103339006110506 	  Loss: 1.0378493826219188 	 Accuracy: 0.2222222222222222
Delta: 0.00841333442401178 	  Loss: 1.0373513682609123 	 Accuracy: 0.2222222222222222
Delta: 0.006059006860357547 	  Loss: 1.0370944935791377 	 Accuracy: 0.2222222222222222
Delta: 0.005082528639933853 	  Loss: 1.0369084322247137 	 Accuracy: 0.2222222222222222
Delta: 0.003939244896845493 	  Loss: 1.0367815404943719 	 Accuracy: 0.2222222222222222
Delta: 0.003547230756354369 	  Loss: 1.0367575016902966 	 Accuracy: 0.2222222222222222
Delta: 0.0023808735440867157 	  Loss: 1.036735386487179 	 Accuracy: 0.2222222222222222
Delta: 0.0024915287748359578 	  Loss: 1.036736280968403 	 Accuracy: 0.2222222222222222
Delta: 0.0018733257753132944 	  Loss: 1.0367192956514075 	 Accuracy: 0.2222222222222222
Delta: 0.0011624744655327523 	  Loss: 1.036712419652332 	 Accuracy: 0.2222222222222222
Delta: 0.0022879072449029448 	  Loss: 1.036713973288651 	 Accuracy: 0.2222222222222222
Delta: 0.001792566006751141 	  Loss: 1.036710599276209 	 Accuracy: 0.2222222222222222
Delta: 0.0016933765737099549 	  Loss: 1.0367242737636517 	 Accuracy: 0.2222222222222222
Delta: 0.002494212321851803 	  Loss: 1.0367385344254976 	 Accuracy: 0.2222222222222222
Delta: 0.002137039286409465 	  Loss: 1.0367369994444513 	 Accuracy: 0.2222222222222222
Delta: 0.0019939949493304344 	  Loss: 1.0367120856979082 	 Accuracy: 0.2222222222222222
Delta: 0.0021564093377418976 	  Loss: 1.0366944379147234 	 Accuracy: 0.2222222222222222
Delta: 0.002282687214629848 	  Loss: 1.0366701331153931 	 Accuracy: 0.2222222222222222
Delta: 0.0028732337760707227 	  Loss: 1.0366461099612614 	 Accuracy: 0.2222222222222222
Delta: 0.0021713927430896834 	  Loss: 1.036615108299019 	 Accuracy: 0.2222222222222222
Delta: 0.00242326222528438 	  Loss: 1.0366125199857057 	 Accuracy: 0.2222222222222222
Delta: 0.002827391457879092 	  Loss: 1.0366111771304656 	 Accuracy: 0.2222222222222222
Delta: 0.0020666004446248066 	  Loss: 1.0365944543523904 	 Accuracy: 0.2222222222222222
Delta: 0.0013395213147884691 	  Loss: 1.0366090527463316 	 Accuracy: 0.2222222222222222
Delta: 0.0013810573533431722 	  Loss: 1.0366101134808758 	 Accuracy: 0.2222222222222222
Delta: 0.0020824129602905906 	  Loss: 1.036595737535611 	 Accuracy: 0.2222222222222222
Delta: 0.0015227468396260644 	  Loss: 1.0365759692591063 	 Accuracy: 0.2222222222222222
Delta: 0.0012362343762287447 	  Loss: 1.0365618339854084 	 Accuracy: 0.2222222222222222
Delta: 0.0010023471079690094 	  Loss: 1.0365546879290322 	 Accuracy: 0.2222222222222222
Delta: 0.0008475836982058518 	  Loss: 1.0365479387156895 	 Accuracy: 0.2222222222222222
Delta: 0.000622884713158499 	  Loss: 1.036548796606067 	 Accuracy: 0.2222222222222222
Delta: 0.0002589087251139016 	  Loss: 1.0365452232599408 	 Accuracy: 0.2222222222222222
Delta: 0.00030228258977360085 	  Loss: 1.0365437548108467 	 Accuracy: 0.2222222222222222
Delta: 0.0004253548706781292 	  Loss: 1.0365421743954644 	 Accuracy: 0.2222222222222222
Delta: 0.0008963707968559663 	  Loss: 1.0365390658348015 	 Accuracy: 0.2222222222222222
Delta: 0.001515793855635102 	  Loss: 1.0365340960415754 	 Accuracy: 0.2222222222222222
Delta: 0.0011286455305669042 	  Loss: 1.0365236760126277 	 Accuracy: 0.2222222222222222
Delta: 0.0011293329714846816 	  Loss: 1.036519712364282 	 Accuracy: 0.2222222222222222
Delta: 0.0007126017676049429 	  Loss: 1.036512230292559 	 Accuracy: 0.2222222222222222
Delta: 0.0015120399075749089 	  Loss: 1.0365116290386283 	 Accuracy: 0.2222222222222222
Delta: 0.0012787965894917946 	  Loss: 1.036503117864645 	 Accuracy: 0.2222222222222222
Delta: 0.001054829729550491 	  Loss: 1.0365007259996846 	 Accuracy: 0.2222222222222222
Delta: 0.00128206326855016 	  Loss: 1.0364892788966822 	 Accuracy: 0.2222222222222222
Delta: 0.0019475269521424669 	  Loss: 1.0364731368955833 	 Accuracy: 0.2222222222222222
Delta: 0.001366778253747097 	  Loss: 1.0364760757285851 	 Accuracy: 0.2222222222222222
Delta: 0.0010072185555544436 	  Loss: 1.0364711781643803 	 Accuracy: 0.2222222222222222
Delta: 0.0006856258404450677 	  Loss: 1.0364746150038295 	 Accuracy: 0.2222222222222222
Delta: 0.0009125464820675643 	  Loss: 1.0364750902060815 	 Accuracy: 0.2222222222222222
Delta: 0.0011040664316464227 	  Loss: 1.036468884550425 	 Accuracy: 0.2222222222222222
Delta: 0.0021013931546296463 	  Loss: 1.0364661347140898 	 Accuracy: 0.2222222222222222
Delta: 0.0022848262363022167 	  Loss: 1.0364601222810434 	 Accuracy: 0.2222222222222222
Delta: 0.0011745735580549544 	  Loss: 1.0364255187966172 	 Accuracy: 0.2222222222222222
Delta: 0.0014115222059913049 	  Loss: 1.036411211670279 	 Accuracy: 0.2222222222222222
Delta: 0.0008698879278013351 	  Loss: 1.0363975239788286 	 Accuracy: 0.2222222222222222
Delta: 0.0009429228192992562 	  Loss: 1.0363898013655346 	 Accuracy: 0.2222222222222222
Delta: 0.0008883709639411314 	  Loss: 1.0363947190674987 	 Accuracy: 0.2222222222222222
Delta: 0.00021413832025517497 	  Loss: 1.0363978319860134 	 Accuracy: 0.2222222222222222
Delta: 0.0003961035140511072 	  Loss: 1.0363971332374209 	 Accuracy: 0.2222222222222222
Delta: 0.00043973583821203355 	  Loss: 1.0363942020064973 	 Accuracy: 0.2222222222222222
Delta: 0.0004559009288609816 	  Loss: 1.0363924823669097 	 Accuracy: 0.2222222222222222
Delta: 0.0001891727313477487 	  Loss: 1.036390355314988 	 Accuracy: 0.2222222222222222
Delta: 0.0008338827618967346 	  Loss: 1.036390279029595 	 Accuracy: 0.2222222222222222
converged at iter  68
Delta: 0.06173541813007756 	  Loss: 1.0708352035091058 	 Accuracy: 0.6451612903225806
Delta: 0.03875950715603072 	  Loss: 1.060649328220653 	 Accuracy: 0.5161290322580645
Delta: 0.03804204953383809 	  Loss: 1.0573295416951707 	 Accuracy: 0.46774193548387094

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.030905752079876808 	  Loss: 1.0557537318102213 	 Accuracy: 0.4838709677419355
Delta: 0.019847184913108454 	  Loss: 1.0531984106945322 	 Accuracy: 0.46774193548387094
Delta: 0.01853631647542142 	  Loss: 1.0518485750465398 	 Accuracy: 0.46774193548387094
Delta: 0.01370534908360049 	  Loss: 1.0507352851403213 	 Accuracy: 0.46774193548387094
Delta: 0.011406220210857174 	  Loss: 1.0502054794689042 	 Accuracy: 0.46774193548387094
Delta: 0.009428487477078463 	  Loss: 1.0497790353012943 	 Accuracy: 0.46774193548387094
Delta: 0.008645196292289914 	  Loss: 1.0494550311510031 	 Accuracy: 0.46774193548387094
Delta: 0.009004473460759018 	  Loss: 1.0491541764193675 	 Accuracy: 0.46774193548387094
Delta: 0.008368434863760477 	  Loss: 1.0488885390677933 	 Accuracy: 0.46774193548387094
Delta: 0.007027097720530549 	  Loss: 1.0485997564303893 	 Accuracy: 0.46774193548387094
Delta: 0.006863326093029367 	  Loss: 1.0484045451138666 	 Accuracy: 0.46774193548387094
Delta: 0.007510747042599548 	  Loss: 1.0481765408543806 	 Accuracy: 0.46774193548387094
Delta: 0.0071557597190673415 	  Loss: 1.0479084238701377 	 Accuracy: 0.46774193548387094
Delta: 0.0066741822506749034 	  Loss: 1.0476464163486687 	 Accuracy: 0.46774193548387094
Delta: 0.005653831210350424 	  Loss: 1.047480498976416 	 Accuracy: 0.46774193548387094
Delta: 0.004908422796575918 	  Loss: 1.0473428299294443 	 Accuracy: 0.46774193548387094
Delta: 0.004556821528921109 	  Loss: 1.0472499099541461 	 Accuracy: 0.46774193548387094
Delta: 0.004547981639072828 	  Loss: 1.0471199915511478 	 Accuracy: 0.46774193548387094
Delta: 0.005346507136086213 	  Loss: 1.0470259851548254 	 Accuracy: 0.46774193548387094
Delta: 0.005267062938332513 	  Loss: 1.0469305724424602 	 Accuracy: 0.46774193548387094
Delta: 0.00542466154483517 	  Loss: 1.046789871326705 	 Accuracy: 0.46774193548387094
Delta: 0.005425754971241048 	  Loss: 1.0466195330224115 	 Accuracy: 0.46774193548387094
Delta: 0.00532561951015373 	  Loss: 1.0465162289564691 	 Accuracy: 0.46774193548387094
Delta: 0.0038690056229042074 	  Loss: 1.0463804391288931 	 Accuracy: 0.46774193548387094
Delta: 0.003479273749180675 	  Loss: 1.0462935125380979 	 Accuracy: 0.46774193548387094
Delta: 0.0027995131692218956 	  Loss: 1.0462367014897747 	 Accuracy: 0.46774193548387094
Delta: 0.003277187410556673 	  Loss: 1.0462164939776604 	 Accuracy: 0.46774193548387094
Delta: 0.003439073099144043 	  Loss: 1.0461946480173774 	 Accuracy: 0.46774193548387094
Delta: 0.0028550572789604023 	  Loss: 1.0461503453851564 	 Accuracy: 0.46774193548387094
Delta: 0.0024647931130317813 	  Loss: 1.0460997364093565 	 Accuracy: 0.46774193548387094
Delta: 0.002476561865631267 	  Loss: 1.0460537519176545 	 Accuracy: 0.46774193548387094
Delta: 0.0022120282864049995 	  Loss: 1.0460119190128139 	 Accuracy: 0.46774193548387094
Delta: 0.0023661486856291036 	  Loss: 1.0459989081382564 	 Accuracy: 0.46774193548387094
Delta: 0.0014820136168806747 	  Loss: 1.045988142627228 	 Accuracy: 0.46774193548387094
Delta: 0.0013847494176298205 	  Loss: 1.0459883662457568 	 Accuracy: 0.46774193548387094
Delta: 0.0012805858066020394 	  Loss: 1.0459940800059497 	 Accuracy: 0.46774193548387094
Delta: 0.0016577783573798724 	  Loss: 1.0459886289179363 	 Accuracy: 0.46774193548387094
Delta: 0.0009809218462157004 	  Loss: 1.045996560960018 	 Accuracy: 0.46774193548387094
Delta: 0.0009078638879398391 	  Loss: 1.0459989216678727 	 Accuracy: 0.46774193548387094
Delta: 0.0019645074835375875 	  Loss: 1.046002074339179 	 Accuracy: 0.46774193548387094
Delta: 0.0008681225721917272 	  Loss: 1.0460085519653846 	 Accuracy: 0.46774193548387094
Delta: 0.0007400119247041319 	  Loss: 1.0460118069975248 	 Accuracy: 0.46774193548387094
Delta: 0.0005078031965719132 	  Loss: 1.0460101465868128 	 Accuracy: 0.46774193548387094
Delta: 0.0008789035129445592 	  Loss: 1.0460125828932283 	 Accuracy: 0.46774193548387094
Delta: 0.0012226959989199214 	  Loss: 1.0460125790433015 	 Accuracy: 0.46774193548387094
converged at iter  47
Delta: 0.0605031432509572 	  Loss: 1.0659117804800537 	 Accuracy: 0.45161290322580644
Delta: 0.04091425094987733 	  Loss: 1.0565624696797729 	 Accuracy: 0.43548387096774194
Delta: 0.032671671033027386 	  Loss: 1.0501390696379393 	 Accuracy: 0.3870967741935484

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.020233102832679883 	  Loss: 1.046754142965144 	 Accuracy: 0.3548387096774194
Delta: 0.01586678920443879 	  Loss: 1.0450177923182147 	 Accuracy: 0.3548387096774194
Delta: 0.013452681835565744 	  Loss: 1.0439839939284385 	 Accuracy: 0.3548387096774194
Delta: 0.009921530775481264 	  Loss: 1.0432671867047782 	 Accuracy: 0.3548387096774194
Delta: 0.007711449556330313 	  Loss: 1.0429203200437247 	 Accuracy: 0.3548387096774194
Delta: 0.005872474887891799 	  Loss: 1.0427023796237085 	 Accuracy: 0.3548387096774194
Delta: 0.004581718356618863 	  Loss: 1.042578496478229 	 Accuracy: 0.3548387096774194
Delta: 0.0035292393808515 	  Loss: 1.0425213995215832 	 Accuracy: 0.3548387096774194
Delta: 0.0026826097170455786 	  Loss: 1.0424744117060005 	 Accuracy: 0.3548387096774194
Delta: 0.002544500481266284 	  Loss: 1.0424394496480636 	 Accuracy: 0.3548387096774194
Delta: 0.002357113083853889 	  Loss: 1.042413689026737 	 Accuracy: 0.3548387096774194
Delta: 0.002569966264655097 	  Loss: 1.0423703079699655 	 Accuracy: 0.3548387096774194
Delta: 0.00264443253077472 	  Loss: 1.042340160166451 	 Accuracy: 0.3548387096774194
Delta: 0.0020637774477522235 	  Loss: 1.0423263439968506 	 Accuracy: 0.3548387096774194
Delta: 0.0017845469238663971 	  Loss: 1.0423043358729687 	 Accuracy: 0.3548387096774194
Delta: 0.0021147796044174755 	  Loss: 1.0422909782053789 	 Accuracy: 0.3548387096774194
Delta: 0.0016273056583930652 	  Loss: 1.0422840504576212 	 Accuracy: 0.3548387096774194
Delta: 0.001583225439260454 	  Loss: 1.0422642220434737 	 Accuracy: 0.3548387096774194
Delta: 0.0015095283668487662 	  Loss: 1.0422642572492464 	 Accuracy: 0.3548387096774194
converged at iter  21
Delta: 0.05903310693047694 	  Loss: 1.076289288701473 	 Accuracy: 0.4032258064516129
Delta: 0.043366124036541824 	  Loss: 1.0694238442362654 	 Accuracy: 0.27419354838709675
Delta: 0.03649116399540044 	  Loss: 1.0657283109384523 	 Accuracy: 0.25806451612903225

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.02712094759021537 	  Loss: 1.0618259530846186 	 Accuracy: 0.25806451612903225
Delta: 0.01819463887921626 	  Loss: 1.0587864776244922 	 Accuracy: 0.25806451612903225
Delta: 0.012216351308080017 	  Loss: 1.0574517213243961 	 Accuracy: 0.25806451612903225
Delta: 0.008599995458692356 	  Loss: 1.056831710243499 	 Accuracy: 0.25806451612903225
Delta: 0.006993607438987137 	  Loss: 1.0565618873170335 	 Accuracy: 0.25806451612903225
Delta: 0.005550104568671077 	  Loss: 1.0564235075697754 	 Accuracy: 0.25806451612903225
Delta: 0.004597777340117787 	  Loss: 1.0563139726691673 	 Accuracy: 0.25806451612903225
Delta: 0.004669268116534922 	  Loss: 1.0561994945146782 	 Accuracy: 0.25806451612903225
Delta: 0.004043382572254705 	  Loss: 1.0561337091395362 	 Accuracy: 0.25806451612903225
Delta: 0.003670061853562042 	  Loss: 1.0560653515892047 	 Accuracy: 0.25806451612903225
Delta: 0.0045672274860836404 	  Loss: 1.0560221415035245 	 Accuracy: 0.25806451612903225
Delta: 0.0038526457377407973 	  Loss: 1.0559520132346676 	 Accuracy: 0.25806451612903225
Delta: 0.004786644354051436 	  Loss: 1.0559052900352992 	 Accuracy: 0.25806451612903225
Delta: 0.004743082862014531 	  Loss: 1.0558313602702059 	 Accuracy: 0.25806451612903225
Delta: 0.0038078954491992225 	  Loss: 1.0557284437213479 	 Accuracy: 0.25806451612903225
Delta: 0.003643811921154957 	  Loss: 1.0556743728961766 	 Accuracy: 0.25806451612903225
Delta: 0.0034950828488111464 	  Loss: 1.055622665829913 	 Accuracy: 0.25806451612903225
Delta: 0.004024837726877904 	  Loss: 1.0555848035781148 	 Accuracy: 0.25806451612903225
Delta: 0.004692217035376519 	  Loss: 1.0555115402532755 	 Accuracy: 0.25806451612903225
Delta: 0.004309778342404719 	  Loss: 1.0554319417358993 	 Accuracy: 0.25806451612903225
Delta: 0.002781917988902034 	  Loss: 1.0553806576935925 	 Accuracy: 0.25806451612903225
Delta: 0.0027923905123457314 	  Loss: 1.0553724668848252 	 Accuracy: 0.25806451612903225
Delta: 0.0036318792053291146 	  Loss: 1.0553298787258663 	 Accuracy: 0.25806451612903225
Delta: 0.0030069843014886607 	  Loss: 1.0553018364566333 	 Accuracy: 0.25806451612903225
Delta: 0.002598834739028333 	  Loss: 1.0552773535766353 	 Accuracy: 0.25806451612903225
Delta: 0.001937566461561065 	  Loss: 1.0552523399670615 	 Accuracy: 0.25806451612903225
Delta: 0.0018202133081129544 	  Loss: 1.0552505435405184 	 Accuracy: 0.25806451612903225
Delta: 0.0023325455454744296 	  Loss: 1.055229443031316 	 Accuracy: 0.25806451612903225
Delta: 0.001958966951764306 	  Loss: 1.0552095647479587 	 Accuracy: 0.25806451612903225
Delta: 0.0018184843013343333 	  Loss: 1.0551854136354386 	 Accuracy: 0.25806451612903225
Delta: 0.002151592000834261 	  Loss: 1.0551658654334148 	 Accuracy: 0.25806451612903225
Delta: 0.0014944591733884699 	  Loss: 1.0551401829942115 	 Accuracy: 0.25806451612903225
Delta: 0.0015093632619621825 	  Loss: 1.0551282039271253 	 Accuracy: 0.25806451612903225
Delta: 0.0017053129234628796 	  Loss: 1.0551218552836577 	 Accuracy: 0.25806451612903225
Delta: 0.0012967593277838291 	  Loss: 1.0551145281365808 	 Accuracy: 0.25806451612903225
Delta: 0.0018474433591624396 	  Loss: 1.055105651050312 	 Accuracy: 0.25806451612903225
Delta: 0.0017841431819296657 	  Loss: 1.0551012859923923 	 Accuracy: 0.25806451612903225
Delta: 0.002297932641575227 	  Loss: 1.0550857743410123 	 Accuracy: 0.25806451612903225
Delta: 0.001120368117567249 	  Loss: 1.0550764445467764 	 Accuracy: 0.25806451612903225
Delta: 0.0013282370627490144 	  Loss: 1.0550762300796452 	 Accuracy: 0.25806451612903225
Delta: 0.0018160284024475056 	  Loss: 1.0550618235907527 	 Accuracy: 0.25806451612903225
Delta: 0.001064512632927921 	  Loss: 1.0550546821456905 	 Accuracy: 0.25806451612903225
Delta: 0.000952135321097196 	  Loss: 1.0550499007613283 	 Accuracy: 0.25806451612903225
Delta: 0.001097115257059941 	  Loss: 1.0550432143803303 	 Accuracy: 0.25806451612903225
Delta: 0.0012893807814928283 	  Loss: 1.0550426548936156 	 Accuracy: 0.25806451612903225
Delta: 0.0017032012326515249 	  Loss: 1.0550352082888774 	 Accuracy: 0.25806451612903225
Delta: 0.001916509526272919 	  Loss: 1.0550342884813417 	 Accuracy: 0.25806451612903225
Delta: 0.001182844379507202 	  Loss: 1.0550263709226924 	 Accuracy: 0.25806451612903225
Delta: 0.0007005880304558968 	  Loss: 1.0550252811790393 	 Accuracy: 0.25806451612903225
Delta: 0.0007038928949449819 	  Loss: 1.0550259542860907 	 Accuracy: 0.25806451612903225
Delta: 0.000546329157341805 	  Loss: 1.0550216363736205 	 Accuracy: 0.25806451612903225
Delta: 0.0005777193269331374 	  Loss: 1.055019990825166 	 Accuracy: 0.25806451612903225
Delta: 0.0005108174211992976 	  Loss: 1.05502099088425 	 Accuracy: 0.25806451612903225
Delta: 0.00018385294439699594 	  Loss: 1.055020309227217 	 Accuracy: 0.25806451612903225
Delta: 1.3188109810801375e-05 	  Loss: 1.0550197093598896 	 Accuracy: 0.25806451612903225
Delta: 3.8128817891225126e-17 	  Loss: 1.0550197093598896 	 Accuracy: 0.25806451612903225
converged at iter  58
Delta: 0.058462420020045425 	  Loss: 1.0732413019282885 	 Accuracy: 0.3333333333333333
Delta: 0.05104979053042051 	  Loss: 1.0693218379158034 	 Accuracy: 0.30158730158730157
Delta: 0.033178066166417206 	  Loss: 1.0661170443122743 	 Accuracy: 0.23809523809523808

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.026062502773570403 	  Loss: 1.061904765820887 	 Accuracy: 0.2698412698412698
Delta: 0.0225825089301087 	  Loss: 1.058774501389942 	 Accuracy: 0.2698412698412698
Delta: 0.01417274299203974 	  Loss: 1.0574555986116927 	 Accuracy: 0.2698412698412698
Delta: 0.009831657486501439 	  Loss: 1.0570039323408684 	 Accuracy: 0.2698412698412698
Delta: 0.008600307244287593 	  Loss: 1.0567369074271085 	 Accuracy: 0.2698412698412698
Delta: 0.008403898454495897 	  Loss: 1.056432648884336 	 Accuracy: 0.2698412698412698
Delta: 0.007693385821486486 	  Loss: 1.0561350953392425 	 Accuracy: 0.2698412698412698
Delta: 0.008163441744359854 	  Loss: 1.0558343014970462 	 Accuracy: 0.2698412698412698
Delta: 0.007588001798220746 	  Loss: 1.0556150748520314 	 Accuracy: 0.2698412698412698
Delta: 0.007348142737915866 	  Loss: 1.0554434894806635 	 Accuracy: 0.2698412698412698
Delta: 0.006091795216787394 	  Loss: 1.055243558002032 	 Accuracy: 0.2698412698412698
Delta: 0.006345279311226764 	  Loss: 1.0550975333205401 	 Accuracy: 0.2698412698412698
Delta: 0.00588647820211412 	  Loss: 1.0549362781049731 	 Accuracy: 0.2698412698412698
Delta: 0.0073188667544231084 	  Loss: 1.0547471011748524 	 Accuracy: 0.2698412698412698
Delta: 0.007788983803707756 	  Loss: 1.0545005315955547 	 Accuracy: 0.2698412698412698
Delta: 0.008409690046213936 	  Loss: 1.054148190685778 	 Accuracy: 0.2698412698412698
Delta: 0.007890056824982802 	  Loss: 1.0538017223412186 	 Accuracy: 0.2698412698412698
Delta: 0.0069678103527983665 	  Loss: 1.0534930782847536 	 Accuracy: 0.2698412698412698
Delta: 0.006507640284866715 	  Loss: 1.0532744396138458 	 Accuracy: 0.2698412698412698
Delta: 0.006017843523317337 	  Loss: 1.0531697859452112 	 Accuracy: 0.2698412698412698
Delta: 0.005419784942022055 	  Loss: 1.0530799379738722 	 Accuracy: 0.2698412698412698
Delta: 0.005184645294330422 	  Loss: 1.0529891074895126 	 Accuracy: 0.2698412698412698
Delta: 0.0043998764820910455 	  Loss: 1.052883479425358 	 Accuracy: 0.2698412698412698
Delta: 0.004712216385826134 	  Loss: 1.0528228208887744 	 Accuracy: 0.2698412698412698
Delta: 0.004768801938205463 	  Loss: 1.0528137000983975 	 Accuracy: 0.2698412698412698
Delta: 0.00406496559748401 	  Loss: 1.0527896160574208 	 Accuracy: 0.2698412698412698
Delta: 0.0034584238990611896 	  Loss: 1.0527701079284586 	 Accuracy: 0.2698412698412698
Delta: 0.0028992780944758056 	  Loss: 1.0527484367203002 	 Accuracy: 0.2698412698412698
Delta: 0.002657696990330988 	  Loss: 1.0527454860209333 	 Accuracy: 0.2698412698412698
Delta: 0.002387262720172631 	  Loss: 1.0527341765224691 	 Accuracy: 0.2698412698412698
Delta: 0.0026441374680944577 	  Loss: 1.0527281019049677 	 Accuracy: 0.2698412698412698
Delta: 0.0033132345402222866 	  Loss: 1.0527180320727156 	 Accuracy: 0.2698412698412698
Delta: 0.002672786508334944 	  Loss: 1.0526859108825541 	 Accuracy: 0.2698412698412698
Delta: 0.002516238944792943 	  Loss: 1.0526507879972833 	 Accuracy: 0.2698412698412698
Delta: 0.0026806338751748666 	  Loss: 1.0526183239479954 	 Accuracy: 0.2698412698412698
Delta: 0.0028566975736389073 	  Loss: 1.052580477213397 	 Accuracy: 0.2698412698412698
Delta: 0.003213787774142014 	  Loss: 1.052535243463892 	 Accuracy: 0.2698412698412698
Delta: 0.0034449434721969163 	  Loss: 1.0524962590456686 	 Accuracy: 0.2698412698412698
Delta: 0.0027331905741199746 	  Loss: 1.0524619622417377 	 Accuracy: 0.2698412698412698
Delta: 0.0026883817650015566 	  Loss: 1.0524471324556217 	 Accuracy: 0.2698412698412698
Delta: 0.00294028116859123 	  Loss: 1.0524229356855488 	 Accuracy: 0.2698412698412698
Delta: 0.002618800036407563 	  Loss: 1.0523970666575397 	 Accuracy: 0.2698412698412698
Delta: 0.002047949830540332 	  Loss: 1.05236956698081 	 Accuracy: 0.2698412698412698
Delta: 0.0020452006701252865 	  Loss: 1.0523690294990633 	 Accuracy: 0.2698412698412698
Delta: 0.0032579953040948475 	  Loss: 1.0523720824142682 	 Accuracy: 0.2698412698412698
Delta: 0.0036340551699799105 	  Loss: 1.0523736520301163 	 Accuracy: 0.2698412698412698
Delta: 0.0035756801673636307 	  Loss: 1.052319786494622 	 Accuracy: 0.2698412698412698
Delta: 0.0022772686419692944 	  Loss: 1.0522811573199244 	 Accuracy: 0.2698412698412698
Delta: 0.002730175343697002 	  Loss: 1.0522741609344801 	 Accuracy: 0.2698412698412698
Delta: 0.0020194553728586926 	  Loss: 1.0522514518677615 	 Accuracy: 0.2698412698412698
Delta: 0.002428357716702805 	  Loss: 1.0522462256406615 	 Accuracy: 0.2698412698412698
Delta: 0.0018762322253858665 	  Loss: 1.052224435969868 	 Accuracy: 0.2698412698412698
Delta: 0.001547992147133106 	  Loss: 1.0522127797426246 	 Accuracy: 0.2698412698412698
Delta: 0.0014683579272185463 	  Loss: 1.0521981747350968 	 Accuracy: 0.2698412698412698
Delta: 0.002220093507285264 	  Loss: 1.0521909386177906 	 Accuracy: 0.2698412698412698
Delta: 0.0018833989342475867 	  Loss: 1.052189601055942 	 Accuracy: 0.2698412698412698
Delta: 0.002374325390567202 	  Loss: 1.0521751448909176 	 Accuracy: 0.2698412698412698
Delta: 0.0017791399862357449 	  Loss: 1.052171635386345 	 Accuracy: 0.2698412698412698
Delta: 0.0019163297330045937 	  Loss: 1.05217291773749 	 Accuracy: 0.2698412698412698
Delta: 0.0012918914273816297 	  Loss: 1.0521617512380184 	 Accuracy: 0.2698412698412698
Delta: 0.0010986859588570967 	  Loss: 1.0521652276380966 	 Accuracy: 0.2698412698412698
Delta: 0.0011089774076835045 	  Loss: 1.052174227204322 	 Accuracy: 0.2698412698412698
Delta: 0.001109514951639545 	  Loss: 1.0521774358754894 	 Accuracy: 0.2698412698412698
Delta: 0.0020770326924572256 	  Loss: 1.052182932982022 	 Accuracy: 0.2698412698412698
Delta: 0.0019153233345427802 	  Loss: 1.0521776788450905 	 Accuracy: 0.2698412698412698
Delta: 0.002216832235732452 	  Loss: 1.0521689267450247 	 Accuracy: 0.2698412698412698
Delta: 0.0018512360806750773 	  Loss: 1.0521509572371284 	 Accuracy: 0.2698412698412698
Delta: 0.0024650392379576137 	  Loss: 1.0521363052289092 	 Accuracy: 0.2698412698412698
Delta: 0.0024154224216036404 	  Loss: 1.0521329453484785 	 Accuracy: 0.2698412698412698
Delta: 0.0020307596334637468 	  Loss: 1.0521460403870173 	 Accuracy: 0.2698412698412698
Delta: 0.002155986531664994 	  Loss: 1.0521559831875487 	 Accuracy: 0.2698412698412698
Delta: 0.002414566911782601 	  Loss: 1.0521719307370945 	 Accuracy: 0.2698412698412698
Delta: 0.0026398815708604108 	  Loss: 1.0521625154503143 	 Accuracy: 0.2698412698412698
Delta: 0.002302336540630988 	  Loss: 1.052172203142701 	 Accuracy: 0.2698412698412698
Delta: 0.0029757887555752678 	  Loss: 1.052164376098472 	 Accuracy: 0.2698412698412698
Delta: 0.002342928969246502 	  Loss: 1.0521544748696114 	 Accuracy: 0.2698412698412698
Delta: 0.0024650858681646627 	  Loss: 1.052166863575068 	 Accuracy: 0.2698412698412698
Delta: 0.0031601256904764084 	  Loss: 1.052163066775039 	 Accuracy: 0.2698412698412698
Delta: 0.003474397901313191 	  Loss: 1.0521633703029973 	 Accuracy: 0.2698412698412698
Delta: 0.002456973250272131 	  Loss: 1.0521687932087427 	 Accuracy: 0.2698412698412698
Delta: 0.002224403423797919 	  Loss: 1.0521585307732741 	 Accuracy: 0.2698412698412698
Delta: 0.0026432959198473757 	  Loss: 1.0521674403813357 	 Accuracy: 0.2698412698412698
Delta: 0.0021095082618550554 	  Loss: 1.0521632948593824 	 Accuracy: 0.2698412698412698
Delta: 0.0014793685124372279 	  Loss: 1.0521561640066488 	 Accuracy: 0.2698412698412698
Delta: 0.0016317482618173392 	  Loss: 1.0521516211595354 	 Accuracy: 0.2698412698412698
Delta: 0.0011491494787861608 	  Loss: 1.0521423618415136 	 Accuracy: 0.2698412698412698
Delta: 0.000853487014373593 	  Loss: 1.0521362852581921 	 Accuracy: 0.2698412698412698
Delta: 0.000757376674770178 	  Loss: 1.0521304875661395 	 Accuracy: 0.2698412698412698
Delta: 0.0015491889925458157 	  Loss: 1.0521329311740177 	 Accuracy: 0.2698412698412698
Delta: 0.0008120275721272269 	  Loss: 1.0521389380304171 	 Accuracy: 0.2698412698412698
Delta: 0.0008829293956834837 	  Loss: 1.0521368105395914 	 Accuracy: 0.2698412698412698
Delta: 0.0011094878942326833 	  Loss: 1.0521375231483328 	 Accuracy: 0.2698412698412698
Delta: 0.0007076335207089066 	  Loss: 1.0521374604161886 	 Accuracy: 0.2698412698412698
converged at iter  95
Delta: 0.05917842150795946 	  Loss: 1.059520273154726 	 Accuracy: 0.2698412698412698
Delta: 0.045927976282926365 	  Loss: 1.0565073917208228 	 Accuracy: 0.31746031746031744
Delta: 0.03085675565775663 	  Loss: 1.050324786305357 	 Accuracy: 0.30158730158730157

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.021199872426309736 	  Loss: 1.0466401829954324 	 Accuracy: 0.2857142857142857
Delta: 0.014725952318069934 	  Loss: 1.0447429745033738 	 Accuracy: 0.2857142857142857
Delta: 0.010833137602887177 	  Loss: 1.043912127676025 	 Accuracy: 0.2857142857142857
Delta: 0.010509294840460643 	  Loss: 1.043280811862307 	 Accuracy: 0.2857142857142857
Delta: 0.009771363205965704 	  Loss: 1.0426547868748064 	 Accuracy: 0.2857142857142857
Delta: 0.009162986915619495 	  Loss: 1.0420583129172618 	 Accuracy: 0.2857142857142857
Delta: 0.008519067615004315 	  Loss: 1.041590907136221 	 Accuracy: 0.2857142857142857
Delta: 0.007380583269763616 	  Loss: 1.0412101519335766 	 Accuracy: 0.2857142857142857
Delta: 0.006940937269168876 	  Loss: 1.0409411940753786 	 Accuracy: 0.2857142857142857
Delta: 0.006606061516962339 	  Loss: 1.0406845551946067 	 Accuracy: 0.2857142857142857
Delta: 0.00585154100816168 	  Loss: 1.0404367374086545 	 Accuracy: 0.2857142857142857
Delta: 0.005626711907607029 	  Loss: 1.0403138647305956 	 Accuracy: 0.2857142857142857
Delta: 0.004726566283224355 	  Loss: 1.0402070645614439 	 Accuracy: 0.2857142857142857
Delta: 0.004321856095094668 	  Loss: 1.040103715432641 	 Accuracy: 0.2857142857142857
Delta: 0.0038838505261692734 	  Loss: 1.0400307024582776 	 Accuracy: 0.2857142857142857
Delta: 0.004106249437580478 	  Loss: 1.0399792780724604 	 Accuracy: 0.2857142857142857
Delta: 0.004191964845246765 	  Loss: 1.0399052286525445 	 Accuracy: 0.2857142857142857
Delta: 0.003052032984453185 	  Loss: 1.0398112916375113 	 Accuracy: 0.2857142857142857
Delta: 0.003307464775930497 	  Loss: 1.0397339901189397 	 Accuracy: 0.2857142857142857
Delta: 0.0037467270899052226 	  Loss: 1.039706233019953 	 Accuracy: 0.2857142857142857
Delta: 0.004779999625746158 	  Loss: 1.0396262599624226 	 Accuracy: 0.2857142857142857
Delta: 0.004841143747989652 	  Loss: 1.0394869998588931 	 Accuracy: 0.2857142857142857
Delta: 0.004283591736814499 	  Loss: 1.039389850812554 	 Accuracy: 0.2857142857142857
Delta: 0.003920513399501874 	  Loss: 1.039297821838999 	 Accuracy: 0.2857142857142857
Delta: 0.004019162045379962 	  Loss: 1.0392330559663103 	 Accuracy: 0.2857142857142857
Delta: 0.0035568553410839066 	  Loss: 1.0391279352920897 	 Accuracy: 0.2857142857142857
Delta: 0.003602273152446195 	  Loss: 1.039044859715137 	 Accuracy: 0.2857142857142857
Delta: 0.00425632886671238 	  Loss: 1.0389583667283406 	 Accuracy: 0.2857142857142857
Delta: 0.004580483716011256 	  Loss: 1.0388905285534185 	 Accuracy: 0.2857142857142857
Delta: 0.0039664447208970395 	  Loss: 1.0387932201286008 	 Accuracy: 0.2857142857142857
Delta: 0.004769174865574119 	  Loss: 1.0387324225167676 	 Accuracy: 0.2857142857142857
Delta: 0.004580886431060772 	  Loss: 1.038644290000927 	 Accuracy: 0.2857142857142857
Delta: 0.003625819065433339 	  Loss: 1.0385447309647144 	 Accuracy: 0.2857142857142857
Delta: 0.0029347709785295384 	  Loss: 1.0384887009666288 	 Accuracy: 0.2857142857142857
Delta: 0.002682364399590869 	  Loss: 1.038471477938326 	 Accuracy: 0.2857142857142857
Delta: 0.002632787395095269 	  Loss: 1.0384657246087432 	 Accuracy: 0.2857142857142857
Delta: 0.0017202210393991988 	  Loss: 1.0384668809107351 	 Accuracy: 0.2857142857142857
Delta: 0.0019998183182733976 	  Loss: 1.0384636829060683 	 Accuracy: 0.2857142857142857
Delta: 0.001951666040258177 	  Loss: 1.0384618630179179 	 Accuracy: 0.2857142857142857
Delta: 0.0021421625711555746 	  Loss: 1.0384622990947818 	 Accuracy: 0.2857142857142857
Delta: 0.0013837969908940977 	  Loss: 1.0384492983777391 	 Accuracy: 0.2857142857142857
Delta: 0.0017279193090521503 	  Loss: 1.038442168165679 	 Accuracy: 0.2857142857142857
Delta: 0.0013704187666756145 	  Loss: 1.0384382040930142 	 Accuracy: 0.2857142857142857
Delta: 0.0016707086786445762 	  Loss: 1.0384317337037436 	 Accuracy: 0.2857142857142857
Delta: 0.002254460971726358 	  Loss: 1.038439442383071 	 Accuracy: 0.2857142857142857
Delta: 0.0018011399688361036 	  Loss: 1.0384436262811945 	 Accuracy: 0.2857142857142857
Delta: 0.0008841395376480054 	  Loss: 1.0384410209767365 	 Accuracy: 0.2857142857142857
Delta: 0.0013584745719019892 	  Loss: 1.0384387806648774 	 Accuracy: 0.2857142857142857
Delta: 0.0016785026662576772 	  Loss: 1.0384458092561393 	 Accuracy: 0.2857142857142857
Delta: 0.0012736063658804083 	  Loss: 1.0384462884092096 	 Accuracy: 0.2857142857142857
Delta: 0.0021380644597474904 	  Loss: 1.038439566057761 	 Accuracy: 0.2857142857142857
Delta: 0.0011746073397632209 	  Loss: 1.0384252401674694 	 Accuracy: 0.2857142857142857
Delta: 0.0008831780717144308 	  Loss: 1.0384219028050257 	 Accuracy: 0.2857142857142857
Delta: 0.0014512893648074433 	  Loss: 1.038414810026089 	 Accuracy: 0.2857142857142857
Delta: 0.0007973177949444015 	  Loss: 1.0384084148431159 	 Accuracy: 0.2857142857142857
Delta: 0.002183925906922889 	  Loss: 1.0384062884526883 	 Accuracy: 0.2857142857142857
Delta: 0.0012781580479011212 	  Loss: 1.0383942597423381 	 Accuracy: 0.2857142857142857
Delta: 0.0007804241973157289 	  Loss: 1.0383912555324961 	 Accuracy: 0.2857142857142857
Delta: 0.0012529738492233476 	  Loss: 1.0383886009122092 	 Accuracy: 0.2857142857142857
Delta: 0.0009337968693808491 	  Loss: 1.0383833396752546 	 Accuracy: 0.2857142857142857
Delta: 0.0011362472963814979 	  Loss: 1.038387462850713 	 Accuracy: 0.2857142857142857
Delta: 0.0006946557819218003 	  Loss: 1.0383918050362007 	 Accuracy: 0.2857142857142857
Delta: 0.00018227411189267726 	  Loss: 1.0383920367051602 	 Accuracy: 0.2857142857142857
Delta: 0.0003390818808203537 	  Loss: 1.038392007149886 	 Accuracy: 0.2857142857142857
converged at iter  66
Delta: 0.06088524853189828 	  Loss: 1.0728146393813505 	 Accuracy: 0.5161290322580645
Delta: 0.04921628518432079 	  Loss: 1.0739785500657328 	 Accuracy: 0.5

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.032291209567883686 	  Loss: 1.068315428182944 	 Accuracy: 0.3709677419354839
Delta: 0.02441466095665889 	  Loss: 1.0641073093420177 	 Accuracy: 0.3709677419354839
Delta: 0.020702142359131186 	  Loss: 1.0610776740779964 	 Accuracy: 0.3709677419354839
Delta: 0.016888047146464344 	  Loss: 1.0589469398185165 	 Accuracy: 0.3709677419354839
Delta: 0.013385577961643145 	  Loss: 1.05761659433694 	 Accuracy: 0.3709677419354839
Delta: 0.010519744992050998 	  Loss: 1.056845591729574 	 Accuracy: 0.3709677419354839
Delta: 0.008701271189771462 	  Loss: 1.0564215132416477 	 Accuracy: 0.3709677419354839
Delta: 0.008414244070216568 	  Loss: 1.05606895179137 	 Accuracy: 0.3709677419354839
Delta: 0.007750528101181223 	  Loss: 1.0557484203494258 	 Accuracy: 0.3709677419354839
Delta: 0.007568504598536353 	  Loss: 1.0554798402591412 	 Accuracy: 0.3709677419354839
Delta: 0.006696640355341052 	  Loss: 1.0552720538949898 	 Accuracy: 0.3709677419354839
Delta: 0.006999877074711235 	  Loss: 1.0550950130279293 	 Accuracy: 0.3709677419354839
Delta: 0.006736254261659871 	  Loss: 1.0548916848516046 	 Accuracy: 0.3709677419354839
Delta: 0.005204588074877014 	  Loss: 1.054756394312128 	 Accuracy: 0.3709677419354839
Delta: 0.004769711279134498 	  Loss: 1.0546591763265127 	 Accuracy: 0.3709677419354839
Delta: 0.004343689480626734 	  Loss: 1.054624920632862 	 Accuracy: 0.3709677419354839
Delta: 0.004080634072762725 	  Loss: 1.0545870462299876 	 Accuracy: 0.3709677419354839
Delta: 0.003010430080940786 	  Loss: 1.054542836530115 	 Accuracy: 0.3709677419354839
Delta: 0.0021277435609305833 	  Loss: 1.0545069535331142 	 Accuracy: 0.3709677419354839
Delta: 0.0026733975973549018 	  Loss: 1.054500046946564 	 Accuracy: 0.3709677419354839
Delta: 0.002670131140577957 	  Loss: 1.0544627077288866 	 Accuracy: 0.3709677419354839
Delta: 0.0018256563944645248 	  Loss: 1.0544278648722591 	 Accuracy: 0.3709677419354839
Delta: 0.0010102400352952575 	  Loss: 1.054406553105646 	 Accuracy: 0.3709677419354839
Delta: 0.0008363284204077242 	  Loss: 1.0544076475570265 	 Accuracy: 0.3709677419354839
Delta: 0.0011910818804856474 	  Loss: 1.0544035682242763 	 Accuracy: 0.3709677419354839
Delta: 0.0011043800215788755 	  Loss: 1.0544053355297507 	 Accuracy: 0.3709677419354839
Delta: 0.0006190510518638891 	  Loss: 1.054399662513013 	 Accuracy: 0.3709677419354839
Delta: 0.00048567720925792306 	  Loss: 1.0543982317794276 	 Accuracy: 0.3709677419354839
Delta: 0.0007719400310447545 	  Loss: 1.0543986125178266 	 Accuracy: 0.3709677419354839
Delta: 0.0009326748588463059 	  Loss: 1.0543952692290053 	 Accuracy: 0.3709677419354839
Delta: 0.0003590543266815375 	  Loss: 1.0543957655810345 	 Accuracy: 0.3709677419354839
Delta: 0.00015945894329915481 	  Loss: 1.054393015849211 	 Accuracy: 0.3709677419354839
Delta: 0.00029775521861125553 	  Loss: 1.0543927198094831 	 Accuracy: 0.3709677419354839
Delta: 0.00022432196842543583 	  Loss: 1.0543906113172414 	 Accuracy: 0.3709677419354839
Delta: 0.0001989499367211789 	  Loss: 1.0543890572602268 	 Accuracy: 0.3709677419354839
Delta: 0.0002099912095344995 	  Loss: 1.0543870903773307 	 Accuracy: 0.3709677419354839
Delta: 0.0002055032025557054 	  Loss: 1.0543852298555403 	 Accuracy: 0.3709677419354839
Delta: 0.00035403577509184964 	  Loss: 1.0543828373448432 	 Accuracy: 0.3709677419354839
Delta: 7.989313930761331e-05 	  Loss: 1.0543823551798237 	 Accuracy: 0.3709677419354839
Delta: 4.975295476191399e-06 	  Loss: 1.0543819513294856 	 Accuracy: 0.3709677419354839
Delta: 2.685863361127591e-17 	  Loss: 1.0543819513294856 	 Accuracy: 0.3709677419354839
converged at iter  42
Delta: 0.06260916453905054 	  Loss: 1.0800885209548503 	 Accuracy: 0.11290322580645161
Delta: 0.04177449110812402 	  Loss: 1.0735600920457793 	 Accuracy: 0.06451612903225806
Delta: 0.02673834195031944 	  Loss: 1.0687781190217875 	 Accuracy: 0.06451612903225806

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.028266341127272446 	  Loss: 1.0646005634545481 	 Accuracy: 0.06451612903225806
Delta: 0.021691111507961935 	  Loss: 1.0615607360240829 	 Accuracy: 0.06451612903225806
Delta: 0.01811490989844219 	  Loss: 1.0596557252068066 	 Accuracy: 0.06451612903225806
Delta: 0.01551847766147842 	  Loss: 1.0584422496900237 	 Accuracy: 0.06451612903225806
Delta: 0.015150033105038298 	  Loss: 1.0575215032227867 	 Accuracy: 0.06451612903225806
Delta: 0.01406432182987655 	  Loss: 1.056603766779959 	 Accuracy: 0.06451612903225806
Delta: 0.012494642274081846 	  Loss: 1.0558633907723776 	 Accuracy: 0.06451612903225806
Delta: 0.01137818859663781 	  Loss: 1.055364018278855 	 Accuracy: 0.06451612903225806
Delta: 0.010054555105884624 	  Loss: 1.0549354411711422 	 Accuracy: 0.06451612903225806
Delta: 0.0094043752931877 	  Loss: 1.054616322590187 	 Accuracy: 0.06451612903225806
Delta: 0.008600649140687968 	  Loss: 1.0544342674831966 	 Accuracy: 0.06451612903225806
Delta: 0.0073385188653712135 	  Loss: 1.0541310172212393 	 Accuracy: 0.06451612903225806
Delta: 0.007017629580218556 	  Loss: 1.0539523279084055 	 Accuracy: 0.06451612903225806
Delta: 0.006045302777748856 	  Loss: 1.0538035620386592 	 Accuracy: 0.06451612903225806
Delta: 0.005625563669334243 	  Loss: 1.0537241901552783 	 Accuracy: 0.06451612903225806
Delta: 0.004626533175151721 	  Loss: 1.0536722713968336 	 Accuracy: 0.06451612903225806
Delta: 0.004402158806333084 	  Loss: 1.053582484684129 	 Accuracy: 0.06451612903225806
Delta: 0.00490277316638731 	  Loss: 1.0535310514420662 	 Accuracy: 0.06451612903225806
Delta: 0.004281956797882142 	  Loss: 1.0534833250857782 	 Accuracy: 0.06451612903225806
Delta: 0.00419954608233087 	  Loss: 1.0534236952777207 	 Accuracy: 0.06451612903225806
Delta: 0.004459496443653563 	  Loss: 1.0533856715981367 	 Accuracy: 0.06451612903225806
Delta: 0.003931798957319944 	  Loss: 1.0533391299446073 	 Accuracy: 0.06451612903225806
Delta: 0.004499623261822522 	  Loss: 1.0533039922896084 	 Accuracy: 0.06451612903225806
Delta: 0.004228068090660281 	  Loss: 1.0532736177028013 	 Accuracy: 0.06451612903225806
Delta: 0.0038925209656617333 	  Loss: 1.053276070325312 	 Accuracy: 0.06451612903225806
Delta: 0.00456407952005018 	  Loss: 1.0532695606624656 	 Accuracy: 0.06451612903225806
Delta: 0.003511031246994501 	  Loss: 1.0531939016936906 	 Accuracy: 0.06451612903225806
Delta: 0.003355579728881982 	  Loss: 1.0531522752423892 	 Accuracy: 0.06451612903225806
Delta: 0.0031877103360087233 	  Loss: 1.0531335443682124 	 Accuracy: 0.06451612903225806
Delta: 0.0034683069814839865 	  Loss: 1.0530968768914521 	 Accuracy: 0.06451612903225806
Delta: 0.0030552405871043502 	  Loss: 1.0530472106905573 	 Accuracy: 0.06451612903225806
Delta: 0.004213083370752122 	  Loss: 1.0529969607582932 	 Accuracy: 0.06451612903225806
Delta: 0.004684695805862286 	  Loss: 1.0529551074274888 	 Accuracy: 0.06451612903225806
Delta: 0.0048995654654440885 	  Loss: 1.0528633525839943 	 Accuracy: 0.06451612903225806
Delta: 0.005890487686042616 	  Loss: 1.052708303502433 	 Accuracy: 0.06451612903225806
Delta: 0.007888308957570197 	  Loss: 1.05250814681913 	 Accuracy: 0.06451612903225806
Delta: 0.008956666767183876 	  Loss: 1.0521994087064837 	 Accuracy: 0.06451612903225806
Delta: 0.009801376849226495 	  Loss: 1.0518504262460482 	 Accuracy: 0.06451612903225806
Delta: 0.009348780793291756 	  Loss: 1.0514216372702214 	 Accuracy: 0.06451612903225806
Delta: 0.008445371272473474 	  Loss: 1.051123520340908 	 Accuracy: 0.06451612903225806
Delta: 0.007235367756965639 	  Loss: 1.0510278240478645 	 Accuracy: 0.06451612903225806
Delta: 0.006432557885160447 	  Loss: 1.0509429613833317 	 Accuracy: 0.06451612903225806
Delta: 0.005339649538688017 	  Loss: 1.0509332626223657 	 Accuracy: 0.06451612903225806
Delta: 0.004838200857658188 	  Loss: 1.0509291320507101 	 Accuracy: 0.06451612903225806
Delta: 0.004037085856553367 	  Loss: 1.0509170624366404 	 Accuracy: 0.06451612903225806
Delta: 0.0036427486870507252 	  Loss: 1.050881860688663 	 Accuracy: 0.06451612903225806
Delta: 0.003032306509886197 	  Loss: 1.050844779466197 	 Accuracy: 0.06451612903225806
Delta: 0.003720776045967065 	  Loss: 1.050840107930553 	 Accuracy: 0.06451612903225806
Delta: 0.0037097945492343878 	  Loss: 1.0508416401749483 	 Accuracy: 0.06451612903225806
Delta: 0.002659201407428686 	  Loss: 1.0508578252513374 	 Accuracy: 0.06451612903225806
Delta: 0.002148254945689859 	  Loss: 1.0508592540497281 	 Accuracy: 0.06451612903225806
Delta: 0.002488527467721575 	  Loss: 1.0508388064354175 	 Accuracy: 0.06451612903225806
Delta: 0.003062877948837846 	  Loss: 1.0508142933297666 	 Accuracy: 0.06451612903225806
Delta: 0.0024571402858234864 	  Loss: 1.050796588649867 	 Accuracy: 0.06451612903225806
Delta: 0.002986914731347131 	  Loss: 1.0507795597899685 	 Accuracy: 0.06451612903225806
Delta: 0.003098589573312155 	  Loss: 1.0508010271679318 	 Accuracy: 0.06451612903225806
Delta: 0.002851701186511224 	  Loss: 1.0508024515981795 	 Accuracy: 0.06451612903225806
Delta: 0.003392253082163772 	  Loss: 1.0508042319806936 	 Accuracy: 0.06451612903225806
Delta: 0.0037203922872774994 	  Loss: 1.0508204024857166 	 Accuracy: 0.06451612903225806
Delta: 0.003985353223838395 	  Loss: 1.050836705898122 	 Accuracy: 0.06451612903225806
Delta: 0.0036786054393360395 	  Loss: 1.0507968862602777 	 Accuracy: 0.06451612903225806
Delta: 0.003971673954938938 	  Loss: 1.0507650461022755 	 Accuracy: 0.06451612903225806
Delta: 0.0036235908652088155 	  Loss: 1.0507432959234473 	 Accuracy: 0.06451612903225806
Delta: 0.004195860120222139 	  Loss: 1.0507129113880052 	 Accuracy: 0.06451612903225806
Delta: 0.0050951945528773124 	  Loss: 1.0506913764727654 	 Accuracy: 0.06451612903225806
Delta: 0.005350327606647332 	  Loss: 1.0507045968175783 	 Accuracy: 0.06451612903225806
Delta: 0.0053303109192420475 	  Loss: 1.050704754463742 	 Accuracy: 0.06451612903225806
Delta: 0.005705835846019893 	  Loss: 1.0506826598383068 	 Accuracy: 0.06451612903225806
Delta: 0.006549957084089043 	  Loss: 1.0506119672758394 	 Accuracy: 0.06451612903225806
Delta: 0.008202450830681067 	  Loss: 1.050421945305545 	 Accuracy: 0.06451612903225806
Delta: 0.007018036916054334 	  Loss: 1.0501311851679185 	 Accuracy: 0.06451612903225806
Delta: 0.007528815425003996 	  Loss: 1.049986344863055 	 Accuracy: 0.06451612903225806
Delta: 0.007425866902876606 	  Loss: 1.0497988669564562 	 Accuracy: 0.06451612903225806
Delta: 0.005684554256546827 	  Loss: 1.0496564857945698 	 Accuracy: 0.06451612903225806
Delta: 0.0040555865276420055 	  Loss: 1.04961061841635 	 Accuracy: 0.06451612903225806
Delta: 0.0029945114393073063 	  Loss: 1.0495727920933602 	 Accuracy: 0.06451612903225806
Delta: 0.0025738985169675216 	  Loss: 1.0495724201821806 	 Accuracy: 0.06451612903225806
Delta: 0.0015911600067741393 	  Loss: 1.0495604061269996 	 Accuracy: 0.06451612903225806

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import KFold

numRepetitions = 10
num_folds = 5

algo = "emd"
reg = 0.1
alpha = 0.6   # fixe ici si tu ne fais pas tuning

results = []

for repe in range(numRepetitions):
    print("num repe :", repe + 1)

    kf_source = KFold(n_splits=num_folds, shuffle=True, random_state=repe)
    kf_target = KFold(n_splits=num_folds, shuffle=True, random_state=repe)

    for fold, ((train_s, test_s), (train_t, test_t)) in enumerate(
        zip(kf_source.split(source), kf_target.split(target))
    ):

        S = source.iloc[train_s].reset_index(drop=True)
        S_test = source.iloc[test_s].reset_index(drop=True)

        T = target.iloc[train_t].reset_index(drop=True)
        T_test = target.iloc[test_t].reset_index(drop=True)

        # ==========================
        # COOT
        # ==========================
        pure_source, pure_target, test_source, test_target = \
            discrete_unsupervised_coot(
                S, T, S_test, T_test,
                algo=algo,
                reg=reg,
                batch_size=len(S)
            )

        score_coot = test_target  # ⚠️ mets ta vraie métrique

        results.append({
            "repetition": repe,
            "fold": fold,
            "recoding": "coot",
            "learning": "unsupervised",
            "score": score_coot,
        })

        # ==========================
        # JDCOOT
        # ==========================
        pure_source, pure_target, test_source, test_target = \
            discrete_unsupervised_jdcoot(
                S, T, S_test, T_test,
                algo=algo,
                reg=reg,
                batch_size=len(S),
                alpha=alpha
            )

        score_jdcoot = test_target  # ⚠️ mets ta vraie métrique

        results.append({
            "repetition": repe,
            "fold": fold,
            "recoding": "jdcoot",
            "learning": "unsupervised",
            "score": score_jdcoot,
        })

# ==============================
# Résumé
# ==============================

df_results = pd.DataFrame(results)

df_summary = (
    df_results
    .groupby(["recoding"])
    .agg(mean_score=("score", "mean"),
         std_score=("score", "std"))
    .reset_index()
)

print(df_summary)

df_summary.to_excel("results_cv_mean.xlsx", index=False)

num repe : 1