In [ ]:
%load_ext autoreload
%autoreload 2

import sklearn
import scipy 
import numpy as np
import pandas as pd
import os
import sys
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "0"
sys.path.append(os.path.abspath("src"))
import jdcoot
import math
from scipy.io import loadmat

from jdcoot.models.discrete_unsupervised_jdcoot import discrete_unsupervised_jdcoot
from jdcoot.models.discrete_semisupervised_jdcoot import discrete_semisupervised_jdcoot
from jdcoot.models.discrete_partial_jdcoot import discrete_partial_jdcoot
from jdcoot.models.discrete_unsupervised_coot import discrete_unsupervised_coot
from jdcoot.models.discrete_semisupervised_coot import discrete_semisupervised_coot
from jdcoot.models.discrete_partial_coot import discrete_partial_coot
from jdcoot.models.discrete_semisupervised_reference import discrete_semisupervised_reference
from jdcoot.models.discrete_partial_reference import discrete_partial_reference
from jdcoot.utils import xcolumns, continuous_classifiers, continuous_accuracy
from sklearn.model_selection import train_test_split

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [15]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"

# les donnees caffeNet GoogleNet

In [ ]:
featuresToUse = ["CaffeNet4096", "GoogleNet1024"] 
#featuresToUse = ["CaffeNet4096", "CaffeNet4096"] 
sourceDomainName = ['caltech10'] #['caltech10','amazon','webcam']
targetDomainName = ['caltech10'] #['caltech10','amazon','webcam']

min_max_scaler = sklearn.preprocessing.MinMaxScaler()
# Collab
possible_data = loadmat(os.path.join("data/", "features", featuresToUse[0],
                                                 "caltech10" + '.mat'))
feat = possible_data['fts'].astype(float)
labels = possible_data['labels'].ravel()
S_data = [feat, labels]
S_nClass = len(np.unique(labels)) # nb de class in source data
possible_data = loadmat(os.path.join("data/", "features", featuresToUse[1],
                                                 "amazon" + '.mat'))
feat = possible_data['fts'].astype(float)
labels = possible_data['labels'].ravel()
T_data = [feat, labels]
T_nClass = len(np.unique(labels)) # nb de class in target data

source=pd.DataFrame(np.concatenate((S_data[0],S_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(S_data[0].shape[1])]+['Z'])
target=pd.DataFrame(np.concatenate((T_data[0],T_data[1].reshape(-1,1)),axis=1),columns=['X'+str(i) for i in range(T_data[0].shape[1])]+['Z'])

source.loc[:,'Z'] = source.loc[:, 'Z'] - 1
target.loc[:,'Z'] = target.loc[:, 'Z'] - 1

In [17]:
results = []
numRepetitions = 10
alpha =1.5# hyperparamètre devant la loss a été optimé
prop_target = 0.005
algo = "sinkhorn"
reg = 1

In [18]:
a = np.random.choice(np.arange(len(source)), math.ceil(0.8 * len(source)), replace=False)
b = np.random.choice(np.arange(len(target)), math.ceil(0.8 * len(target)), replace=False)

S_test = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
T_test = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)
S = source.iloc[a, :].reset_index(drop=True)
T = target.iloc[b, :].reset_index(drop=True)

In [ ]:
pure_source, pure_target, test_source, test_target = discrete_unsupervised_jdcoot(
                S, T, S_test, T_test,algo="sinkhorn",reg=1,batch_size=20,alpha =1.5
            )

Delta: 0.05453553408535183 	  Loss: 1.8393473970662568 	 Accuracy: 0.17079530638852672
Delta: 0.042278361239779336 	  Loss: 1.7944731530648248 	 Accuracy: 0.1590612777053455
Delta: 0.03410262716994622 	  Loss: 1.7759854758522358 	 Accuracy: 0.16297262059973924
Delta: 0.028383809153818832 	  Loss: 1.7663491869016381 	 Accuracy: 0.16036505867014342
Delta: 0.02637239268143947 	  Loss: 1.7606049723063306 	 Accuracy: 0.14993481095176012
Delta: 0.025770515640946665 	  Loss: 1.7548057552958922 	 Accuracy: 0.16166883963494133
Delta: 0.022112764323919117 	  Loss: 1.7526454389898316 	 Accuracy: 0.16427640156453716
Delta: 0.019017739576254442 	  Loss: 1.7515220105255533 	 Accuracy: 0.16297262059973924
Delta: 0.020641931078377557 	  Loss: 1.7477388663732518 	 Accuracy: 0.16166883963494133
Delta: 0.018791303606261463 	  Loss: 1.7463321219554109 	 Accuracy: 0.1590612777053455
Delta: 0.017983748064326156 	  Loss: 1.7452173011063752 	 Accuracy: 0.15645371577574968
Delta: 0.018937731946484057 	  Loss: 1.7433701757288889 	 Accuracy: 0.1590612777053455
Delta: 0.017020190511352278 	  Loss: 1.7423673374383761 	 Accuracy: 0.1590612777053455
Delta: 0.01652265678686743 	  Loss: 1.741982648951315 	 Accuracy: 0.1590612777053455
Delta: 0.015638238091658447 	  Loss: 1.7413494915261718 	 Accuracy: 0.1590612777053455
Delta: 0.013744358961278007 	  Loss: 1.7410545135089088 	 Accuracy: 0.1590612777053455
Delta: 0.012840357257550278 	  Loss: 1.7407041208928358 	 Accuracy: 0.1590612777053455
Delta: 0.013823825211022121 	  Loss: 1.7402603717397171 	 Accuracy: 0.1590612777053455
Delta: 0.01258079651676987 	  Loss: 1.740090685139495 	 Accuracy: 0.1590612777053455
Delta: 0.014490557744132888 	  Loss: 1.7399969002660594 	 Accuracy: 0.1590612777053455
Delta: 0.012881509894741546 	  Loss: 1.7398041014599173 	 Accuracy: 0.1590612777053455
Delta: 0.014096555517666726 	  Loss: 1.739643918683652 	 Accuracy: 0.16036505867014342
Delta: 0.013378155442536356 	  Loss: 1.7394362226381181 	 Accuracy: 0.1590612777053455
Delta: 0.012738905024441308 	  Loss: 1.739395578227211 	 Accuracy: 0.1590612777053455
Delta: 0.01262802810730113 	  Loss: 1.739247577167149 	 Accuracy: 0.1590612777053455
Delta: 0.012646822918168571 	  Loss: 1.7393713156360162 	 Accuracy: 0.1590612777053455
Delta: 0.013098546948214648 	  Loss: 1.7392076965823668 	 Accuracy: 0.1590612777053455
Delta: 0.012200194790127454 	  Loss: 1.7389636802050141 	 Accuracy: 0.1590612777053455
Delta: 0.013105995286644724 	  Loss: 1.7388580008334058 	 Accuracy: 0.1590612777053455
Delta: 0.012669183666332013 	  Loss: 1.7387064161667611 	 Accuracy: 0.1590612777053455
Delta: 0.01282303642049052 	  Loss: 1.7385305576241548 	 Accuracy: 0.1590612777053455
Delta: 0.012509486929352488 	  Loss: 1.7383563560418498 	 Accuracy: 0.1590612777053455
Delta: 0.0122160052722062 	  Loss: 1.738199297221747 	 Accuracy: 0.1590612777053455
Delta: 0.013593046186385772 	  Loss: 1.7379775823986854 	 Accuracy: 0.1590612777053455
Delta: 0.014187568186565663 	  Loss: 1.737820034476628 	 Accuracy: 0.1590612777053455
Delta: 0.011788242678776702 	  Loss: 1.7377427592865917 	 Accuracy: 0.16036505867014342
Delta: 0.011493979853642412 	  Loss: 1.737639546737746 	 Accuracy: 0.1590612777053455
Delta: 0.011150449937590203 	  Loss: 1.737582704045455 	 Accuracy: 0.1590612777053455
Delta: 0.01040889959013469 	  Loss: 1.737550987969794 	 Accuracy: 0.1590612777053455
Delta: 0.008960036704706444 	  Loss: 1.73753916801501 	 Accuracy: 0.1590612777053455
Delta: 0.009978071116680146 	  Loss: 1.737529211219392 	 Accuracy: 0.1590612777053455
Delta: 0.011029001860832461 	  Loss: 1.737492946967052 	 Accuracy: 0.1590612777053455
Delta: 0.012002578904729368 	  Loss: 1.7374044793137289 	 Accuracy: 0.1590612777053455
Delta: 0.010571884287487274 	  Loss: 1.737292966930073 	 Accuracy: 0.1590612777053455
Delta: 0.011589440660659762 	  Loss: 1.7372050551791516 	 Accuracy: 0.1590612777053455
Delta: 0.01103806213290303 	  Loss: 1.7371474616601532 	 Accuracy: 0.15645371577574968
Delta: 0.011421670210955283 	  Loss: 1.737316126894969 	 Accuracy: 0.1590612777053455
Delta: 0.012842537006953047 	  Loss: 1.7370911918177658 	 Accuracy: 0.1590612777053455
Delta: 0.01159294285890072 	  Loss: 1.7370111468945904 	 Accuracy: 0.1590612777053455
Delta: 0.011419239640645631 	  Loss: 1.7369270403308388 	 Accuracy: 0.1590612777053455
Delta: 0.011532691001040646 	  Loss: 1.7369049645477221 	 Accuracy: 0.1590612777053455
Delta: 0.012057938401579238 	  Loss: 1.736862048664908 	 Accuracy: 0.1590612777053455
Delta: 0.012470886632459845 	  Loss: 1.7366837517920037 	 Accuracy: 0.16036505867014342
Delta: 0.01569481597764446 	  Loss: 1.7370823449463915 	 Accuracy: 0.1577574967405476
Delta: 0.014631229651907513 	  Loss: 1.7365315633173335 	 Accuracy: 0.1577574967405476
Delta: 0.01344828093908689 	  Loss: 1.7363186817067668 	 Accuracy: 0.1577574967405476
Delta: 0.012516728868062767 	  Loss: 1.736101115971307 	 Accuracy: 0.1577574967405476
Delta: 0.01304201885855289 	  Loss: 1.735956405912674 	 Accuracy: 0.1577574967405476
Delta: 0.012404061193377513 	  Loss: 1.735871060926498 	 Accuracy: 0.1577574967405476
Delta: 0.012869148621654194 	  Loss: 1.7356990664244796 	 Accuracy: 0.1577574967405476
Delta: 0.012610074907172794 	  Loss: 1.7355675541455444 	 Accuracy: 0.1577574967405476
Delta: 0.012423512393367267 	  Loss: 1.7354699135742746 	 Accuracy: 0.1577574967405476
Delta: 0.011974309282100505 	  Loss: 1.735422801560686 	 Accuracy: 0.1577574967405476
Delta: 0.010885028136714636 	  Loss: 1.735360224709628 	 Accuracy: 0.1577574967405476
Delta: 0.012753488833276323 	  Loss: 1.735240486626699 	 Accuracy: 0.1577574967405476
Delta: 0.01197733165175101 	  Loss: 1.735107929895321 	 Accuracy: 0.1577574967405476
Delta: 0.010897471841768891 	  Loss: 1.7350365693412975 	 Accuracy: 0.1577574967405476
Delta: 0.012141995887731 	  Loss: 1.7349696516537594 	 Accuracy: 0.1577574967405476
Delta: 0.009536047862362753 	  Loss: 1.734950153256909 	 Accuracy: 0.1577574967405476
Delta: 0.010091483470810418 	  Loss: 1.7349270755514046 	 Accuracy: 0.1577574967405476
Delta: 0.010076676245976761 	  Loss: 1.7348921825890922 	 Accuracy: 0.1577574967405476
Delta: 0.010404753997777717 	  Loss: 1.7348596947025898 	 Accuracy: 0.1577574967405476
Delta: 0.01040949311855046 	  Loss: 1.7348274799632752 	 Accuracy: 0.1577574967405476
Delta: 0.009968607571184762 	  Loss: 1.7348085131936068 	 Accuracy: 0.1577574967405476
Delta: 0.010646059703441894 	  Loss: 1.7347897552405644 	 Accuracy: 0.1577574967405476
Delta: 0.009404047429817665 	  Loss: 1.7347726095752938 	 Accuracy: 0.15645371577574968
Delta: 0.016481719447274615 	  Loss: 1.7278373402791696 	 Accuracy: 0.16036505867014342
Delta: 0.01268738230590355 	  Loss: 1.7276709994009356 	 Accuracy: 0.16166883963494133
Delta: 0.013485005405478211 	  Loss: 1.7274634897682102 	 Accuracy: 0.16036505867014342
Delta: 0.012893922485426902 	  Loss: 1.7269807910112376 	 Accuracy: 0.16036505867014342
Delta: 0.012304151731239377 	  Loss: 1.726722507665971 	 Accuracy: 0.16036505867014342
Delta: 0.010406252864017857 	  Loss: 1.726685943887189 	 Accuracy: 0.16166883963494133
Delta: 0.009595421555143667 	  Loss: 1.7266206685509415 	 Accuracy: 0.16166883963494133
Delta: 0.009449071935857365 	  Loss: 1.7263976331631028 	 Accuracy: 0.16166883963494133
Delta: 0.007031159951923862 	  Loss: 1.7263851838984703 	 Accuracy: 0.16688396349413298
Delta: 0.011195524073633556 	  Loss: 1.7260285020904065 	 Accuracy: 0.16166883963494133
Delta: 0.010660243565913257 	  Loss: 1.7260930372346484 	 Accuracy: 0.16166883963494133
Delta: 0.010228156453989697 	  Loss: 1.7260623271393238 	 Accuracy: 0.16166883963494133
Delta: 0.009289186483488613 	  Loss: 1.7260457522261592 	 Accuracy: 0.16166883963494133
Delta: 0.01037034043708391 	  Loss: 1.7260390038781503 	 Accuracy: 0.16166883963494133
Delta: 0.010676887665876912 	  Loss: 1.7260449286250386 	 Accuracy: 0.16166883963494133
Delta: 0.009982117594768709 	  Loss: 1.7259646653906842 	 Accuracy: 0.16166883963494133
Delta: 0.009835644655694118 	  Loss: 1.7259942441380116 	 Accuracy: 0.1590612777053455
Delta: 0.020674575603774902 	  Loss: 1.7263092064652992 	 Accuracy: 0.16166883963494133
Delta: 0.016656328500576623 	  Loss: 1.7255184647381132 	 Accuracy: 0.16166883963494133
Delta: 0.01435978547861683 	  Loss: 1.7250047676602476 	 Accuracy: 0.16166883963494133

In [8]:
pure_source, pure_target, test_source, test_target = discrete_semisupervised_jdcoot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                alpha=alpha,
                prop_target=0.005               
            )

Delta: 0.04383717945890281 	 Loss: 1.8018819688882228 	 Accuracy: 0.23167539267015708
Delta: 0.055515640269475676 	 Loss: 1.6279092252263683 	 Accuracy: 0.23036649214659685
Delta: 0.03795958246723688 	 Loss: 1.6054616205476746 	 Accuracy: 0.23167539267015708
Delta: 0.029932273605127516 	 Loss: 1.5969041002017894 	 Accuracy: 0.22905759162303665
Delta: 0.024186490282418024 	 Loss: 1.593085284688188 	 Accuracy: 0.23298429319371727
Delta: 0.0223830758648303 	 Loss: 1.59042553165712 	 Accuracy: 0.23167539267015708
Delta: 0.018750191394769647 	 Loss: 1.5890356900987574 	 Accuracy: 0.23167539267015708
Delta: 0.01655582575288755 	 Loss: 1.5884225017925249 	 Accuracy: 0.23167539267015708
Delta: 0.015816654235646217 	 Loss: 1.587807088354376 	 Accuracy: 0.23167539267015708
Delta: 0.014126256143828144 	 Loss: 1.5874113300444308 	 Accuracy: 0.23167539267015708
Delta: 0.014536596202974464 	 Loss: 1.5870813279147353 	 Accuracy: 0.23167539267015708
Delta: 0.012339737063951323 	 Loss: 1.5867937131471164 	 Accuracy: 0.23167539267015708
Delta: 0.012611414391817913 	 Loss: 1.5863401149351948 	 Accuracy: 0.23167539267015708
Delta: 0.012989376658036692 	 Loss: 1.5861576282751013 	 Accuracy: 0.23298429319371727
Delta: 0.01577121838876317 	 Loss: 1.5869935634360708 	 Accuracy: 0.23036649214659685
Delta: 0.015633331026162454 	 Loss: 1.5862335630979993 	 Accuracy: 0.23167539267015708
Delta: 0.013988603151910755 	 Loss: 1.586085174734129 	 Accuracy: 0.23167539267015708
Delta: 0.012368919654975233 	 Loss: 1.5859053640148009 	 Accuracy: 0.23167539267015708
Delta: 0.012318176649840702 	 Loss: 1.5857833654632736 	 Accuracy: 0.23167539267015708
Delta: 0.01158078704359614 	 Loss: 1.5856044140384735 	 Accuracy: 0.23167539267015708
Delta: 0.012002947205153599 	 Loss: 1.5853988041276945 	 Accuracy: 0.23167539267015708
Delta: 0.011906885866497293 	 Loss: 1.5852411057277007 	 Accuracy: 0.23167539267015708
Delta: 0.01290649812822009 	 Loss: 1.585038113281478 	 Accuracy: 0.23167539267015708
Delta: 0.011039816199289334 	 Loss: 1.5848903726878838 	 Accuracy: 0.23167539267015708
Delta: 0.012223513305732094 	 Loss: 1.584705636532337 	 Accuracy: 0.23167539267015708
Delta: 0.011825693515602882 	 Loss: 1.584540759886528 	 Accuracy: 0.23167539267015708
Delta: 0.012153067983107547 	 Loss: 1.5844021966013253 	 Accuracy: 0.23167539267015708
Delta: 0.010180431417359363 	 Loss: 1.5843275024314898 	 Accuracy: 0.24083769633507854
Delta: 0.014492744358965895 	 Loss: 1.5849186645685815 	 Accuracy: 0.23167539267015708
Delta: 0.015575081765776617 	 Loss: 1.584797151205876 	 Accuracy: 0.23167539267015708
Delta: 0.012481883590165159 	 Loss: 1.5844678572465956 	 Accuracy: 0.23167539267015708
Delta: 0.011428579053949357 	 Loss: 1.5844199216759896 	 Accuracy: 0.23167539267015708
Delta: 0.01238784698739041 	 Loss: 1.5843093009081723 	 Accuracy: 0.23167539267015708
Delta: 0.01212451586187559 	 Loss: 1.584094227063835 	 Accuracy: 0.23167539267015708
Delta: 0.010409215256119196 	 Loss: 1.5840138288173269 	 Accuracy: 0.23167539267015708
Delta: 0.010710961034066595 	 Loss: 1.583952393391539 	 Accuracy: 0.23298429319371727
Delta: 0.010626624558121578 	 Loss: 1.5839130934923562 	 Accuracy: 0.23298429319371727
Delta: 0.010752363835926967 	 Loss: 1.5838739601252128 	 Accuracy: 0.23167539267015708
Delta: 0.010617177042694279 	 Loss: 1.583789695411165 	 Accuracy: 0.23298429319371727
Delta: 0.010366071850468856 	 Loss: 1.5837307273718166 	 Accuracy: 0.23167539267015708
Delta: 0.011596556721739485 	 Loss: 1.583677608769102 	 Accuracy: 0.21858638743455497
Delta: 0.013076346302523703 	 Loss: 1.5842650056796876 	 Accuracy: 0.23036649214659685
Delta: 0.011173401042375523 	 Loss: 1.5841144725266516 	 Accuracy: 0.23036649214659685
Delta: 0.009930050395560917 	 Loss: 1.584056976560349 	 Accuracy: 0.23036649214659685
Delta: 0.009614075659504883 	 Loss: 1.5839918084452143 	 Accuracy: 0.23036649214659685
Delta: 0.00934030704389603 	 Loss: 1.5840145543964006 	 Accuracy: 0.23036649214659685
Delta: 0.008150288058471074 	 Loss: 1.583994253328685 	 Accuracy: 0.23036649214659685
Delta: 0.009517155638001873 	 Loss: 1.5839606024629749 	 Accuracy: 0.23167539267015708
Delta: 0.010668780296477939 	 Loss: 1.5838924258408649 	 Accuracy: 0.23036649214659685
Delta: 0.008368433231015437 	 Loss: 1.5836729629849187 	 Accuracy: 0.23036649214659685
Delta: 0.015845675964096348 	 Loss: 1.5817394759349415 	 Accuracy: 0.22774869109947643
Delta: 0.013212299330055136 	 Loss: 1.581508235678947 	 Accuracy: 0.22774869109947643
Delta: 0.010531295268945 	 Loss: 1.581387652562056 	 Accuracy: 0.22774869109947643
Delta: 0.011548923629354935 	 Loss: 1.5813114206486232 	 Accuracy: 0.22774869109947643
Delta: 0.011239187416709439 	 Loss: 1.5812015229386593 	 Accuracy: 0.22774869109947643
Delta: 0.01271812350255802 	 Loss: 1.5811943118876748 	 Accuracy: 0.22774869109947643
Delta: 0.011352263425854634 	 Loss: 1.5811978053217626 	 Accuracy: 0.22774869109947643
Delta: 0.011763289828324777 	 Loss: 1.5810345371487444 	 Accuracy: 0.22905759162303665
Delta: 0.012172226120348422 	 Loss: 1.5808342856460034 	 Accuracy: 0.22774869109947643
Delta: 0.011567376734553037 	 Loss: 1.5807571678276846 	 Accuracy: 0.22774869109947643
Delta: 0.010126624823730517 	 Loss: 1.5806859581280268 	 Accuracy: 0.22774869109947643
Delta: 0.012580036155389277 	 Loss: 1.5805285948048344 	 Accuracy: 0.22774869109947643
Delta: 0.010663810260273524 	 Loss: 1.5804299312387124 	 Accuracy: 0.22774869109947643
Delta: 0.010137282971125702 	 Loss: 1.5804114968891678 	 Accuracy: 0.22774869109947643
Delta: 0.009878236727754303 	 Loss: 1.5803860099300584 	 Accuracy: 0.22774869109947643
Delta: 0.008853252196419348 	 Loss: 1.5803705701433992 	 Accuracy: 0.22774869109947643
Delta: 0.007206666283059097 	 Loss: 1.5803663399928363 	 Accuracy: 0.22774869109947643
Delta: 0.005051399927764732 	 Loss: 1.580365698019371 	 Accuracy: 0.22774869109947643
converged at iter  68

In [10]:
pure_target

np.float64(0.22774869109947643)

In [ ]:
pure_source, pure_target, test_source, test_target = discrete_semisupervised_coot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                alpha=alpha,
                prop_target=0.005               
            )

In [ ]:
pure_source, pure_target, test_source, test_target = discrete_semisupervised_reference(
                S, T, S_test, T_test,algo=algo,reg=reg,
                alpha=alpha,
                prop_target=0.005               
            )

In [5]:
pure_source, pure_target, test_source, test_target = discrete_partial_jdcoot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                alpha=alpha,
                prop_source=0.5,
                prop_target=0.005               
            )

I0000 00:00:1773692877.806990 1409726 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 31129 MB memory:  -> device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0
I0000 00:00:1773692879.052294 1410121 service.cc:148] XLA service 0x787698e49a10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1773692879.052354 1410121 service.cc:156]   StreamExecutor device (0): Tesla V100S-PCIE-32GB, Compute Capability 7.0
I0000 00:00:1773692879.073582 1410121 cuda_dnn.cc:529] Loaded cuDNN version 91002
I0000 00:00:1773692879.160113 1410121 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

Delta: 0.0442272665521862 	  Loss: 1.884906279633607 	 Accuracy: 0.25654450261780104
Delta: 0.056260074706917795 	  Loss: 1.682564342212201 	 Accuracy: 0.25392670157068065
Delta: 0.037398100099511423 	  Loss: 1.6558062441368375 	 Accuracy: 0.2591623036649215
Delta: 0.02975214049509029 	  Loss: 1.6449148212101163 	 Accuracy: 0.25654450261780104
Delta: 0.02793553990815873 	  Loss: 1.635689796917399 	 Accuracy: 0.2630890052356021
Delta: 0.02624149811351395 	  Loss: 1.6282567825806875 	 Accuracy: 0.2670157068062827
Delta: 0.02531940500216994 	  Loss: 1.6196192269741698 	 Accuracy: 0.2709424083769634
Delta: 0.024581591077897525 	  Loss: 1.6132164735506462 	 Accuracy: 0.2696335078534031
Delta: 0.022048772085402357 	  Loss: 1.608803809741957 	 Accuracy: 0.2696335078534031
Delta: 0.022396995675887127 	  Loss: 1.6030625664139515 	 Accuracy: 0.2696335078534031
Delta: 0.02170521434141691 	  Loss: 1.5996627622990558 	 Accuracy: 0.27356020942408377
Delta: 0.021896968367035474 	  Loss: 1.596502938591325 	 Accuracy: 0.27486910994764396
Delta: 0.017835355566326462 	  Loss: 1.594220280970168 	 Accuracy: 0.27356020942408377
Delta: 0.016781518604325238 	  Loss: 1.592718778004953 	 Accuracy: 0.2709424083769634
Delta: 0.020335345250971554 	  Loss: 1.5904564912495576 	 Accuracy: 0.2709424083769634
Delta: 0.017445144377579307 	  Loss: 1.5891474315150762 	 Accuracy: 0.2670157068062827
Delta: 0.017903236928595273 	  Loss: 1.587570379846587 	 Accuracy: 0.2630890052356021
Delta: 0.019286954670229745 	  Loss: 1.5871582850780155 	 Accuracy: 0.2670157068062827
Delta: 0.01701803471981652 	  Loss: 1.5859784479642614 	 Accuracy: 0.2643979057591623
Delta: 0.014851167803626934 	  Loss: 1.585100721088767 	 Accuracy: 0.26570680628272253
Delta: 0.016175045158692544 	  Loss: 1.5843231669416207 	 Accuracy: 0.2683246073298429
Delta: 0.015750017427877405 	  Loss: 1.583709830089415 	 Accuracy: 0.26570680628272253
Delta: 0.016759063095103787 	  Loss: 1.5830786970905137 	 Accuracy: 0.26570680628272253
Delta: 0.01574891886445218 	  Loss: 1.5820418238316365 	 Accuracy: 0.26570680628272253
Delta: 0.014109089289408547 	  Loss: 1.581317916804995 	 Accuracy: 0.2630890052356021
Delta: 0.015386864831736721 	  Loss: 1.5805084934732239 	 Accuracy: 0.2683246073298429
Delta: 0.014482615431463173 	  Loss: 1.5797092024499189 	 Accuracy: 0.2696335078534031
Delta: 0.017426745899456718 	  Loss: 1.5792609451978417 	 Accuracy: 0.2709424083769634
Delta: 0.015374096610627965 	  Loss: 1.5784800114714166 	 Accuracy: 0.26570680628272253
Delta: 0.01464854097777638 	  Loss: 1.578046488675593 	 Accuracy: 0.2696335078534031
Delta: 0.01561772267369687 	  Loss: 1.5776409930103807 	 Accuracy: 0.2643979057591623
Delta: 0.013876239923014398 	  Loss: 1.5771800979013606 	 Accuracy: 0.2617801047120419
Delta: 0.01219489905869061 	  Loss: 1.5770090885148291 	 Accuracy: 0.2604712041884817
Delta: 0.01523903415706572 	  Loss: 1.5766001892977863 	 Accuracy: 0.2643979057591623
Delta: 0.01647352508544421 	  Loss: 1.575997666902078 	 Accuracy: 0.26570680628272253
Delta: 0.014570023046371809 	  Loss: 1.5755024930533328 	 Accuracy: 0.26570680628272253
Delta: 0.011470899449661415 	  Loss: 1.5752732219423318 	 Accuracy: 0.2643979057591623
Delta: 0.012357001123702015 	  Loss: 1.575062626862573 	 Accuracy: 0.2643979057591623
Delta: 0.0124678800868962 	  Loss: 1.5747533760054337 	 Accuracy: 0.2670157068062827
Delta: 0.012905693714832555 	  Loss: 1.574195257129085 	 Accuracy: 0.2696335078534031
Delta: 0.011777333235676368 	  Loss: 1.5739169304877252 	 Accuracy: 0.2709424083769634
Delta: 0.013139881612023268 	  Loss: 1.5740759307408458 	 Accuracy: 0.2670157068062827
Delta: 0.0137711704366748 	  Loss: 1.57376792476716 	 Accuracy: 0.26570680628272253
Delta: 0.011898450874024314 	  Loss: 1.573366142611764 	 Accuracy: 0.2696335078534031
Delta: 0.01169944641758265 	  Loss: 1.5732137001276025 	 Accuracy: 0.2670157068062827
Delta: 0.011880482883847241 	  Loss: 1.573064880857896 	 Accuracy: 0.2683246073298429
Delta: 0.011848846720562287 	  Loss: 1.5727738362746888 	 Accuracy: 0.2670157068062827
Delta: 0.013922428494177094 	  Loss: 1.5724096179738267 	 Accuracy: 0.2670157068062827
Delta: 0.011558105517806882 	  Loss: 1.5721978631436748 	 Accuracy: 0.26570680628272253
Delta: 0.011783932988297462 	  Loss: 1.572069966032305 	 Accuracy: 0.2683246073298429
Delta: 0.010745197198569794 	  Loss: 1.5720513650045023 	 Accuracy: 0.26570680628272253
Delta: 0.012801515946078292 	  Loss: 1.5719582383222603 	 Accuracy: 0.26570680628272253
Delta: 0.010774671636274376 	  Loss: 1.5718546341214696 	 Accuracy: 0.26570680628272253
Delta: 0.010085219631327889 	  Loss: 1.5718699141476464 	 Accuracy: 0.26570680628272253
Delta: 0.010050336058467243 	  Loss: 1.5718127508737767 	 Accuracy: 0.2670157068062827
Delta: 0.00925718239226366 	  Loss: 1.5717547544287302 	 Accuracy: 0.2630890052356021
Delta: 0.010708914099230011 	  Loss: 1.5717210540625732 	 Accuracy: 0.26570680628272253
Delta: 0.011629291622883505 	  Loss: 1.571595011494927 	 Accuracy: 0.26570680628272253
Delta: 0.008994655338076326 	  Loss: 1.5715638928134503 	 Accuracy: 0.26570680628272253
Delta: 0.010622296284413748 	  Loss: 1.5715177788893087 	 Accuracy: 0.25392670157068065
Delta: 0.014533271678588387 	  Loss: 1.5715291201698318 	 Accuracy: 0.25523560209424084
Delta: 0.01375823694691631 	  Loss: 1.5710414370008845 	 Accuracy: 0.25523560209424084
Delta: 0.012232960342711593 	  Loss: 1.5707082134078973 	 Accuracy: 0.25523560209424084
Delta: 0.011087650833132129 	  Loss: 1.5706270154618294 	 Accuracy: 0.25654450261780104
Delta: 0.009613762757038739 	  Loss: 1.5706344323325458 	 Accuracy: 0.25523560209424084
Delta: 0.011142471155399151 	  Loss: 1.5705473432407024 	 Accuracy: 0.25654450261780104
Delta: 0.011155256351854007 	  Loss: 1.5703066592393102 	 Accuracy: 0.25785340314136124
Delta: 0.009947577753086106 	  Loss: 1.5700729515300296 	 Accuracy: 0.25654450261780104
Delta: 0.011388743326161481 	  Loss: 1.569972363042576 	 Accuracy: 0.25785340314136124
Delta: 0.01193058799856994 	  Loss: 1.5697276424835747 	 Accuracy: 0.25785340314136124
Delta: 0.012640209068129562 	  Loss: 1.5694461066235663 	 Accuracy: 0.2591623036649215
Delta: 0.010633018383399449 	  Loss: 1.569281663668355 	 Accuracy: 0.2591623036649215
Delta: 0.01142708601939295 	  Loss: 1.5692173197197656 	 Accuracy: 0.2604712041884817
Delta: 0.010043717673158762 	  Loss: 1.5691051459311767 	 Accuracy: 0.25785340314136124
Delta: 0.010104399263258085 	  Loss: 1.5691204953640525 	 Accuracy: 0.2604712041884817
Delta: 0.009089543075731482 	  Loss: 1.5690447728918187 	 Accuracy: 0.2604712041884817
Delta: 0.009504873378622805 	  Loss: 1.5688548887175284 	 Accuracy: 0.25654450261780104
Delta: 0.009514470674039545 	  Loss: 1.5687832006260412 	 Accuracy: 0.2591623036649215
Delta: 0.010139970777574682 	  Loss: 1.5688443825074485 	 Accuracy: 0.25654450261780104
Delta: 0.01002491340662265 	  Loss: 1.5688216348032777 	 Accuracy: 0.25654450261780104
Delta: 0.009821511406307746 	  Loss: 1.5687842446141171 	 Accuracy: 0.25654450261780104
Delta: 0.010668738500268624 	  Loss: 1.5686911377344581 	 Accuracy: 0.2591623036649215
Delta: 0.010407913781151978 	  Loss: 1.5686865611292435 	 Accuracy: 0.25785340314136124
Delta: 0.01012924576246824 	  Loss: 1.568608276104123 	 Accuracy: 0.25785340314136124
Delta: 0.008778607044278798 	  Loss: 1.5685940612221625 	 Accuracy: 0.25785340314136124
Delta: 0.009945023012617685 	  Loss: 1.5685398022971575 	 Accuracy: 0.25785340314136124
Delta: 0.009474037184604314 	  Loss: 1.5685118820714836 	 Accuracy: 0.25785340314136124
Delta: 0.008813029180428016 	  Loss: 1.5686057298447769 	 Accuracy: 0.25654450261780104
Delta: 0.009533884440359077 	  Loss: 1.5685698500181862 	 Accuracy: 0.25392670157068065
Delta: 0.00913962252871121 	  Loss: 1.5685657183880521 	 Accuracy: 0.25523560209424084
Delta: 0.009235269944852787 	  Loss: 1.5685396463280759 	 Accuracy: 0.25523560209424084
Delta: 0.00860158154696643 	  Loss: 1.5684626757844988 	 Accuracy: 0.25523560209424084
Delta: 0.009281555507645495 	  Loss: 1.5684976572623102 	 Accuracy: 0.2604712041884817
Delta: 0.010601572896554338 	  Loss: 1.5684746506693537 	 Accuracy: 0.25654450261780104
Delta: 0.008252557774544745 	  Loss: 1.5684604939214337 	 Accuracy: 0.25654450261780104
Delta: 0.009079765792524785 	  Loss: 1.5684196811938849 	 Accuracy: 0.25523560209424084
Delta: 0.009470837987054307 	  Loss: 1.5684274139288528 	 Accuracy: 0.25523560209424084
Delta: 0.009962058727721108 	  Loss: 1.5684108097392628 	 Accuracy: 0.25523560209424084
Delta: 0.009224108152978305 	  Loss: 1.5683597364825683 	 Accuracy: 0.25523560209424084
Delta: 0.008565441817351208 	  Loss: 1.5683376500433042 	 Accuracy: 0.25523560209424084

In [34]:
pure_source, pure_target, test_source, test_target = discrete_partial_coot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                alpha=alpha,
                prop_source=0.5,
                prop_target=0.005               
            )

Delta:       0.0479516 	 Loss:       1.9762464
Delta:       0.0609581 	 Loss:       1.6340702
Delta:       0.0516342 	 Loss:       1.5282199
Delta:       0.0448399 	 Loss:       1.4688440
Delta:       0.0412043 	 Loss:       1.4216875
Delta:       0.0350215 	 Loss:       1.4046976
Delta:       0.0262738 	 Loss:       1.3989525
Delta:       0.0251216 	 Loss:       1.3950071
Delta:       0.0208525 	 Loss:       1.3926575
Delta:       0.0186918 	 Loss:       1.3909998
Delta:       0.0168946 	 Loss:       1.3897824
Delta:       0.0172880 	 Loss:       1.3886747
Delta:       0.0172434 	 Loss:       1.3876016
Delta:       0.0198028 	 Loss:       1.3854229
Delta:       0.0220048 	 Loss:       1.3819343
Delta:       0.0230253 	 Loss:       1.3774892
Delta:       0.0240716 	 Loss:       1.3726989
Delta:       0.0235114 	 Loss:       1.3671677
Delta:       0.0227175 	 Loss:       1.3640346
Delta:       0.0200562 	 Loss:       1.3624380
Delta:       0.0171076 	 Loss:       1.3615987
Delta:       0.0136917 	 Loss:       1.3611921
Delta:       0.0140088 	 Loss:       1.3608376
Delta:       0.0136186 	 Loss:       1.3604747
Delta:       0.0147792 	 Loss:       1.3600167
Delta:       0.0147607 	 Loss:       1.3596575
Delta:       0.0133750 	 Loss:       1.3593295
Delta:       0.0132029 	 Loss:       1.3590648
Delta:       0.0127710 	 Loss:       1.3588526
Delta:       0.0123801 	 Loss:       1.3586584
Delta:       0.0104961 	 Loss:       1.3585480
Delta:       0.0118550 	 Loss:       1.3583995
Delta:       0.0112272 	 Loss:       1.3581970
Delta:       0.0102381 	 Loss:       1.3580658
Delta:       0.0095418 	 Loss:       1.3579995
Delta:       0.0088381 	 Loss:       1.3579546
Delta:       0.0087410 	 Loss:       1.3579029
Delta:       0.0085509 	 Loss:       1.3578843
Delta:       0.0090682 	 Loss:       1.3578223
Delta:       0.0072379 	 Loss:       1.3578070
Delta:       0.0076478 	 Loss:       1.3577860
Delta:       0.0085127 	 Loss:       1.3577618
Delta:       0.0091310 	 Loss:       1.3577027
Delta:       0.0080944 	 Loss:       1.3576829
Delta:       0.0105919 	 Loss:       1.3575990
Delta:       0.0081608 	 Loss:       1.3575501
Delta:       0.0069092 	 Loss:       1.3575386
Delta:       0.0076741 	 Loss:       1.3575327
Delta:       0.0060098 	 Loss:       1.3575151
Delta:       0.0061486 	 Loss:       1.3575024
Delta:       0.0084039 	 Loss:       1.3574714
Delta:       0.0083831 	 Loss:       1.3574464
Delta:       0.0081481 	 Loss:       1.3574334
Delta:       0.0106801 	 Loss:       1.3572998
Delta:       0.0090046 	 Loss:       1.3572289
Delta:       0.0080232 	 Loss:       1.3571954
Delta:       0.0096763 	 Loss:       1.3570523
Delta:       0.0082435 	 Loss:       1.3569541
Delta:       0.0082624 	 Loss:       1.3569238
Delta:       0.0073039 	 Loss:       1.3569013
Delta:       0.0100108 	 Loss:       1.3568375
Delta:       0.0074676 	 Loss:       1.3568200
Delta:       0.0086906 	 Loss:       1.3567842
Delta:       0.0073649 	 Loss:       1.3567709
Delta:       0.0079289 	 Loss:       1.3567595
Delta:       0.0072131 	 Loss:       1.3567393
Delta:       0.0074460 	 Loss:       1.3567286
Delta:       0.0061663 	 Loss:       1.3567236
Delta:       0.0037150 	 Loss:       1.3567234
Delta:       0.0000000 	 Loss:       1.3567234
converged at iter  69

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:630: RuntimeWarning: divide by zero encountered in divide
  v = b / KtransposeU
/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/backend.py:1197: RuntimeWarning: invalid value encountered in dot
  return np.dot(a, b)
/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:642: UserWarning: Warning: numerical errors at iteration 0
  warnings.warn("Warning: numerical errors at iteration %d" % ii)

Delta:       0.0341262 	 Loss:       3.1785024
Delta:       0.0231159 	 Loss:       3.1102141
Delta:       0.0200409 	 Loss:       3.1029424
Delta:       0.0178044 	 Loss:       3.1010317
Delta:       0.0164633 	 Loss:       3.1001679
Delta:       0.0144265 	 Loss:       3.0997151
Delta:       0.0129711 	 Loss:       3.0995345
Delta:       0.0114814 	 Loss:       3.0994602
Delta:       0.0106878 	 Loss:       3.0994272
Delta:       0.0093161 	 Loss:       3.0994186
Delta:       0.0092652 	 Loss:       3.0994281
Delta:       0.0084965 	 Loss:       3.0994142
Delta:       0.0073695 	 Loss:       3.0994134
Delta:       0.0080357 	 Loss:       3.0994070
Delta:       0.0075126 	 Loss:       3.0994092
Delta:       0.0072860 	 Loss:       3.0994098
Delta:       0.0068025 	 Loss:       3.0994098
converged at iter  16

In [35]:
test_target

np.float64(0.09424083769633508)

In [9]:
import numpy as np
from sklearn.model_selection import train_test_split

import ot
from jdcoot.coot import init_matrix_np
from jdcoot.losses import loss_crossentropy2
from jdcoot.utils import xcolumns, discrete_classifiers, discrete_accuracy
from tf_keras.utils import to_categorical


def one_hot(z, nClass):
    return to_categorical(z, num_classes=nClass)


def one_cold(z_hot):
    return np.argmax(z_hot, axis=1)

In [30]:
prop_source = 0.5
prop_target = 0.005
algo = "sinkhorn"
reg = 1
batch_size = 20
alpha = 1.5

source_levels = np.sort(np.unique(source.Z))
target_levels = np.sort(np.unique(target.Z))
nClass = len(np.union1d(source_levels, target_levels))

z_source = source.Z.values
z_target = target.Z.values

n_source = len(z_source)
n_target = len(z_target)

l_source_train, l_source_test = train_test_split(
        np.arange(n_source),
        train_size=prop_source,
    )

l_target_train, l_target_test = train_test_split(
        np.arange(n_target),
        train_size=prop_target,
    )

x_source = source.loc[:, xcolumns(source)].values
x_target = target.loc[:, xcolumns(target)].values

x_source_train = x_source[l_source_train, :]
x_target_train = x_target[l_target_train, :]

z_source_train = one_hot(z_source[l_source_train], nClass).astype(np.float64)
z_target_train = one_hot(z_target[l_target_train], nClass).astype(np.float64)

x_source_test = x_source[l_source_test, :]
z_source_test = z_source[l_source_test]

x_target_test = x_target[l_target_test, :]
z_target_test = z_target[l_target_test]
clf_source, clf_target = discrete_classifiers(source, target, "relu", "softmax")

    #algo = "sinkhorn"
     #reg = 1
algo = algo
reg = reg
algo2 = "emd"
reg2 = 0
numIterBCD = 100
nb_epoch = 10
batch_size = 20

source =S
target =T
test_source = S_test
test_target = T_test

nA, dA = x_source.shape
nB, dB = x_target.shape

vA = np.ones(dA) / dA
vB = np.ones(dB) / dB
wA = np.ones(nA) / nA
wB = np.ones(nB) / nB

    # original losses
C_s, h1_s, h2_s = init_matrix_np(x_source, x_target, vA, vB)
C_v, h1_v, h2_v = init_matrix_np(x_source.T, x_target.T, wA, wB)

cost = np.inf
Gs = np.ones((nA, nB)) / (nA * nB)
Gv = np.ones((dA, dB)) / (dA * dB)

    # we train the classifier with labelled examples only
clf_source.fit(
        x_source_train,
        z_source_train,
        batch_size=batch_size,
        epochs=nb_epoch,
        verbose=0,
    )

z_source_pred = clf_source.predict(x_source, verbose=0)

z_source_pred[l_source_train, :] = (
        z_source_train  # injection of known labels in the classifier predictions
    )

   # we train the classifier with labelled examples only
clf_target.fit(
        x_target_train, z_target_train, batch_size=batch_size, epochs=nb_epoch, verbose=0
    )

z_target_pred = clf_target.predict(x_target, verbose=0)

    # injection of known labels in the classifier predictions
z_target_pred[l_target_train] = z_target_train

log_out = {}
log_out["cost"] = []

fcost = loss_crossentropy2(z_source_pred, z_target_pred)

In [ ]:
Gsold = Gs
Gvold = Gv
costold = cost
        # step 1 : samples coupling optimization
Ms = (C_s - np.dot(h1_s, Gv).dot(h2_s.T)) + alpha * fcost  # is (nA,nB)
if algo == "emd":
            Gs = ot.emd(wA, wB, Ms, numItermax=1e7)
elif algo == "sinkhorn":
            Gs = ot.sinkhorn(wA, wB, Ms, reg)

        # step 2 : features coupling optimization
Mv = C_v - np.dot(h1_v, Gs).dot(h2_v.T)  # is (dA,dB)
if algo2 == "emd":
            Gv = ot.emd(vA, vB, Mv, numItermax=1e7)
elif algo2 == "sinkhorn":
            Gv = ot.sinkhorn(vA, vB, Mv, reg2)

delta = np.linalg.norm(Gs - Gsold) + np.linalg.norm(Gv - Gvold)
cost = np.sum(Mv * Gv)

if delta < 1e-16 or np.abs(costold - cost) < 1e-7:
            print("converged at iter ", k)


        # estimated labels of XA using transport map on samples
z_source_hat = nA * Gs.dot(z_target_pred)
z_source_hat[l_source_train] = z_source_train

In [21]:
z_source_hat = nA * Gs.dot(z_target_pred)
z_source_hat .shape

(1123, 10)

In [22]:
clf_source.fit(
            x_source, z_source_hat, batch_size=batch_size, epochs=nb_epoch, verbose=0
        )
z_source_pred = clf_source.predict(x_source, verbose=0)

z_source_pred[l_source_train] = z_source_train

z_target_hat = nB * Gs.T.dot(z_source_pred)
z_target_hat[l_target_train] = z_target_train

clf_target.fit(
            x_target, z_target_hat, batch_size=batch_size, epochs=nb_epoch, verbose=0
        )
z_target_pred = clf_target.predict(x_target, verbose=0)

z_target_pred[l_target_train] = z_target_train

accuracy = np.mean(
            (one_cold(z_target_pred[l_target_test]) + min(target_levels))
            == z_target[l_target_test]
        )

In [31]:
zpred_target = one_cold(clf_target.predict(x_target_test, verbose=0)) + min(
        target_levels
    )
zpred_source = one_cold(clf_source.predict(x_source_test, verbose=0)) + min(
        source_levels
    )

perf_pure_source = discrete_accuracy(zpred_source, z_source_test)
perf_pure_target = discrete_accuracy(zpred_target, z_target_test)
zt_test = one_cold(
        clf_target.predict(test_target.loc[:, xcolumns(test_target)], verbose=0)
    ) + min(target_levels)
zs_test = one_cold(
        clf_source.predict(test_source.loc[:, xcolumns(test_source)], verbose=0)
    ) + min(source_levels)

perf_test_source = discrete_accuracy(zs_test, test_source.Z)
perf_test_target = discrete_accuracy(zt_test, test_target.Z)

In [33]:
perf_pure_target

np.float64(0.2589098532494759)

In [69]:
from sklearn.preprocessing import OneHotEncoder as onehot
from tf_keras.utils import to_categorical
batch_size = 20
prop_target = 0.005
source =S
target =T
test_source = S_test
test_target = T_test
alpha =1.5# hyperparamètre devant la loss a été optimé
prop_target = 0.005
prop_source = 0.5
algo = "sinkhorn"
reg = 1
def one_hot(z, nClass):
    return to_categorical(z, num_classes=nClass)


def one_cold(z_hot):
    return np.argmax(z_hot, axis=1)
source_levels = np.sort(np.unique(source.Z))
target_levels = np.sort(np.unique(target.Z))

nClass = len(np.union1d(source_levels, target_levels))

z_source = source.Z.values
z_target = target.Z.values

n_source = len(z_source)
n_target = len(z_target)

l_source_train, l_source_test = train_test_split(
        np.arange(n_source),
        train_size=prop_source,
    )

l_target_train, l_target_test = train_test_split(
        np.arange(n_target),
        train_size=prop_target,
    )

x_source = source.loc[:, xcolumns(source)].values
x_target = target.loc[:, xcolumns(target)].values

x_source_train = x_source[l_source_train, :]
x_target_train = x_target[l_target_train, :]

z_source_train = one_hot(z_source[l_source_train], nClass).astype(np.float64)
z_target_train = one_hot(z_target[l_target_train], nClass).astype(np.float64)

x_source_test = x_source[l_source_test, :]
z_source_test = z_source[l_source_test]

x_target_test = x_target[l_target_test, :]
z_target_test = z_target[l_target_test]

clf_source, clf_target = discrete_classifiers(source, target, "relu", "softmax")

In [72]:
#algo = "sinkhorn"
     #reg = 1
from jdcoot.coot import init_matrix_np
from jdcoot.losses import loss_crossentropy2
algo = algo
reg = reg
algo2 = "emd"
reg2 = 0
numIterBCD = 100
nb_epoch = 10
batch_size = 20

nA, dA = x_source.shape
nB, dB = x_target.shape

vA = np.ones(dA) / dA
vB = np.ones(dB) / dB
wA = np.ones(nA) / nA
wB = np.ones(nB) / nB

    # original losses
C_s, h1_s, h2_s = init_matrix_np(x_source, x_target, vA, vB)
C_v, h1_v, h2_v = init_matrix_np(x_source.T, x_target.T, wA, wB)

cost = np.inf

Gs = np.ones((nA, nB)) / (nA * nB)
Gv = np.ones((dA, dB)) / (dA * dB)

    # we train the classifier with labelled examples only
clf_source.fit(
        x_source_train,
        z_source_train,
        batch_size=batch_size,
        epochs=nb_epoch,
        verbose=0,
    )

z_source_pred = clf_source.predict(x_source, verbose=0)

z_source_pred[l_source_train, :] = (
        z_source_train  # injection of known labels in the classifier predictions
    )

    # we train the classifier with labelled examples only
clf_target.fit(
        x_target_train, z_target_train, batch_size=batch_size, epochs=nb_epoch, verbose=0
    )

z_target_pred = clf_target.predict(x_target, verbose=0)

    # injection of known labels in the classifier predictions
z_target_pred[l_target_train] = z_target_train

log_out = {}
log_out["cost"] = []

fcost = loss_crossentropy2(z_source_pred, z_target_pred)

In [64]:
test_target

np.float64(0.20915032679738563)

In [77]:
pure_source, pure_target, test_source, test_target = discrete_partial_coot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                prop_source=0.5,prop_target=prop_target
            )

Delta:       0.0479674 	 Loss:       1.9549072
Delta:       0.0615606 	 Loss:       1.5565324
Delta:       0.0539611 	 Loss:       1.4316012
Delta:       0.0392991 	 Loss:       1.4072564
Delta:       0.0348158 	 Loss:       1.3896015
Delta:       0.0335191 	 Loss:       1.3696127
Delta:       0.0347046 	 Loss:       1.3530347
Delta:       0.0292510 	 Loss:       1.3442301
Delta:       0.0251045 	 Loss:       1.3395374
Delta:       0.0206878 	 Loss:       1.3378131
Delta:       0.0181679 	 Loss:       1.3366811
Delta:       0.0139952 	 Loss:       1.3360885
Delta:       0.0135830 	 Loss:       1.3357773
Delta:       0.0138507 	 Loss:       1.3353904
Delta:       0.0142552 	 Loss:       1.3349999
Delta:       0.0144668 	 Loss:       1.3344814
Delta:       0.0156734 	 Loss:       1.3338927
Delta:       0.0155882 	 Loss:       1.3333637
Delta:       0.0143538 	 Loss:       1.3329163
Delta:       0.0156316 	 Loss:       1.3323201
Delta:       0.0133918 	 Loss:       1.3319861
Delta:       0.0100438 	 Loss:       1.3318614
Delta:       0.0113955 	 Loss:       1.3317844
Delta:       0.0125106 	 Loss:       1.3316024
Delta:       0.0105451 	 Loss:       1.3314870
Delta:       0.0097286 	 Loss:       1.3314177
Delta:       0.0097977 	 Loss:       1.3313728
Delta:       0.0104093 	 Loss:       1.3312933
Delta:       0.0106766 	 Loss:       1.3312093
Delta:       0.0099061 	 Loss:       1.3311591
Delta:       0.0102875 	 Loss:       1.3311150
Delta:       0.0090569 	 Loss:       1.3310892
Delta:       0.0088295 	 Loss:       1.3310539
Delta:       0.0090530 	 Loss:       1.3310329
Delta:       0.0084451 	 Loss:       1.3310156
Delta:       0.0079315 	 Loss:       1.3310074
Delta:       0.0085168 	 Loss:       1.3309989
Delta:       0.0084449 	 Loss:       1.3309561
Delta:       0.0101232 	 Loss:       1.3309350
Delta:       0.0081845 	 Loss:       1.3309217
Delta:       0.0102482 	 Loss:       1.3308685
Delta:       0.0081111 	 Loss:       1.3308452
Delta:       0.0085144 	 Loss:       1.3308146
Delta:       0.0069659 	 Loss:       1.3308002
Delta:       0.0069653 	 Loss:       1.3307911
Delta:       0.0068679 	 Loss:       1.3307897
Delta:       0.0066897 	 Loss:       1.3307876
Delta:       0.0080367 	 Loss:       1.3307853
Delta:       0.0071252 	 Loss:       1.3307852
Delta:       0.0080900 	 Loss:       1.3307812
Delta:       0.0080097 	 Loss:       1.3307618
Delta:       0.0085798 	 Loss:       1.3307535
Delta:       0.0075129 	 Loss:       1.3307486
Delta:       0.0084160 	 Loss:       1.3307264
Delta:       0.0078909 	 Loss:       1.3307200
Delta:       0.0089522 	 Loss:       1.3307037
Delta:       0.0091001 	 Loss:       1.3306726
Delta:       0.0070626 	 Loss:       1.3306677
Delta:       0.0081242 	 Loss:       1.3306651
Delta:       0.0061312 	 Loss:       1.3306608
Delta:       0.0071460 	 Loss:       1.3306601
Delta:       0.0059246 	 Loss:       1.3306597
Delta:       0.0059237 	 Loss:       1.3306592
Delta:       0.0056466 	 Loss:       1.3306580
Delta:       0.0073747 	 Loss:       1.3306570
Delta:       0.0067664 	 Loss:       1.3306566
Delta:       0.0049089 	 Loss:       1.3306566
converged at iter  66

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:630: RuntimeWarning: divide by zero encountered in divide
  v = b / KtransposeU
/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/backend.py:1197: RuntimeWarning: invalid value encountered in dot
  return np.dot(a, b)
/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:642: UserWarning: Warning: numerical errors at iteration 0
  warnings.warn("Warning: numerical errors at iteration %d" % ii)

Delta:       0.0339445 	 Loss:       2.9216015
Delta:       0.0227292 	 Loss:       2.8502939
Delta:       0.0144800 	 Loss:       2.8456455
Delta:       0.0098485 	 Loss:       2.8452380
Delta:       0.0073204 	 Loss:       2.8451369
Delta:       0.0044932 	 Loss:       2.8451322
Delta:       0.0039989 	 Loss:       2.8451317
Delta:       0.0036054 	 Loss:       2.8451314
Delta:       0.0000000 	 Loss:       2.8451314
converged at iter  8

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.

In [11]:
pure_source, pure_target, test_source, test_target = discrete_partial_reference(
                S, T, S_test, T_test,algo=algo,reg=reg,
                prop_source=0.5,
                prop_target=prop_target
            )

In [ ]:
test_target

np.float64(0.5602094240837696)

In [57]:
from sklearn.preprocessing import OneHotEncoder as onehot
batch_size = 20
prop_target = 0.005
source =S
target =T
test_source = S_test
test_target = T_test
source_levels = np.sort(np.unique(source.Z))
target_levels = np.sort(np.unique(target.Z))

nClass = len(np.union1d(source_levels, target_levels))
categories = [np.arange(nClass)]

enc = onehot(handle_unknown="ignore", sparse_output=False, categories=categories)

source_train, source_test = train_test_split(source, train_size=0.5)
target_train, target_test = train_test_split(target, train_size=prop_target)
target_train

,X0,X1,X2,X3,X4,X5,X6,X7,X8,X9,...,X1015,X1016,X1017,X1018,X1019,X1020,X1021,X1022,X1023,Z
347,3.226796,0.000000,3.619705,0.091887,0.0,0.000000,0.001672,0.0,0.000000,0.007939,...,3.527637,0.000000,0.251337,0.000000,0.285064,0.0,0.000000,0.0,0.000000,5.0
756,2.329142,0.050401,1.775118,3.216696,0.0,4.927517,0.388101,0.0,0.064215,0.016476,...,0.026453,0.046857,0.711302,0.420250,0.205345,0.0,0.956591,0.0,0.005848,8.0
701,1.875320,0.116668,0.967097,0.021234,0.0,0.000000,0.000000,0.0,0.011634,0.000000,...,1.403997,0.000000,0.005195,0.015218,0.000000,0.0,0.000000,0.0,0.000000,6.0

In [58]:
x_source_train = source_train.loc[:, xcolumns(source)].values
z_source_train = enc.fit_transform(source_train.Z.values[:, np.newaxis])

x_target_train = target_train.loc[:, xcolumns(target)].values
z_target_train = enc.fit_transform(target_train.Z.values[:, np.newaxis])

x_source_test = source_test.loc[:, xcolumns(source)].values
z_source_test = source_test.Z.values

x_target_test = target_test.loc[:, xcolumns(target)].values
z_target_test = target_test.Z.values

x_target_train.shape

(3, 1024)

In [59]:
from jdcoot.utils import xcolumns, discrete_accuracy, discrete_classifiers

clf_source, clf_target = discrete_classifiers(source, target, "relu", "softmax")
clf_target.fit(x_target_train, z_target_train, batch_size=batch_size, epochs=10, verbose=0)
clf_source.fit(x_source_train, z_source_train, batch_size=batch_size, epochs=10, verbose=0)

z_target_pred = enc.inverse_transform(
        clf_target.predict(x_target_test, verbose=0)
    ).ravel()
z_source_pred = enc.inverse_transform(
        clf_source.predict(x_source_test, verbose=0)
    ).ravel()

perf_pure_source = discrete_accuracy(z_source_pred, z_source_test)
perf_pure_target = discrete_accuracy(z_target_pred, z_target_test)

x_test_source = test_source.loc[:, xcolumns(source)]
x_test_target = test_target.loc[:, xcolumns(target)]

z_test_source = enc.inverse_transform(
        clf_source.predict(x_test_source, verbose=0)
    ).ravel()
z_test_target = enc.inverse_transform(
        clf_target.predict(x_test_target, verbose=0)
    ).ravel()

perf_test_source = discrete_accuracy(z_test_source, test_source.Z)
perf_test_target = discrete_accuracy(z_test_target, test_target.Z)

In [60]:
perf_test_target

np.float64(0.2094240837696335)

In [5]:
for repe in range(numRepetitions):
    print("num repe :", repe + 1)

    a = np.random.choice(np.arange(len(source)), math.ceil(0.8 * len(source)), replace=False)
    b = np.random.choice(np.arange(len(target)), math.ceil(0.8 * len(target)), replace=False)

    S_test = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
    T_test = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)
    S = source.iloc[a, :].reset_index(drop=True)
    T = target.iloc[b, :].reset_index(drop=True)

    # =========================================================
    # UNSUPERVISED
    # =========================================================
     # COOT
    pure_source, pure_target, test_source, test_target =  discrete_unsupervised_coot(S, T, S_test, T_test,algo=algo,reg=reg)

    results.append({
        "repetition": repe,
        "recoding": "coot",
        "learning": "unsupervised",
        "prop_source": 1,
        "prop_target": 0,
        "pure_source": pure_source,
        "test_source": test_source,
        "pure_target": pure_target,
        "test_target": test_target,
    })
    
    # JDCOOT
    pure_source, pure_target, test_source, test_target = \
         discrete_unsupervised_jdcoot(S, T, S_test, T_test, algo=algo, reg=reg, alpha=alpha)

    results.append({
         "repetition": repe,
         "recoding": "jdcoot",
         "learning": "unsupervised",
         "prop_source": 1,
         "prop_target": 0,
         "pure_source": pure_source,
         "test_source": test_source,
         "pure_target": pure_target,
         "test_target": test_target,
     })

    for prop_target in prop_target_values_s:

        # JDCOOT
        pure_source, pure_target, test_source, test_target = discrete_semisupervised_jdcoot(
                S, T, S_test, T_test,
                alpha=alpha,
                prop_target=prop_target,
                algo=algo,
                reg=reg
            )

        results.append({
            "repetition": repe,
            "recoding": "jdcoot",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # COOT
        pure_source, pure_target, test_source, test_target = discrete_semisupervised_coot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "coot",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # Reference
        pure_source, pure_target, test_source, test_target = discrete_semisupervised_reference(
                S, T, S_test, T_test,
                prop_target=prop_target,algo=algo,reg=reg
            )

        results.append({
            "repetition": repe,
            "recoding": "reference",
            "learning": "semisupervised",
            "prop_source": 1,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

    # =========================================================
    # PARTIAL
    # =========================================================
    for prop_target in prop_target_values_p:

        # JDCOOT
        pure_source, pure_target, test_source, test_target = discrete_partial_jdcoot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                alpha=alpha,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "jdcoot",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # COOT
        pure_source, pure_target, test_source, test_target = discrete_partial_coot(
                S, T, S_test, T_test,algo=algo,reg=reg,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "coot",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })

        # Reference
        pure_source, pure_target, test_source, test_target = discrete_partial_reference(
                S, T, S_test, T_test,algo=algo,reg=reg,
                prop_source=0.5,
                prop_target=prop_target
            )

        results.append({
            "repetition": repe,
            "recoding": "reference",
            "learning": "partial",
            "prop_source": 0.5,
            "prop_target": prop_target,
            "pure_source": pure_source,
            "test_source": test_source,
            "pure_target": pure_target,
            "test_target": test_target,
        })    

   

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "prop_source", "prop_target"],
        as_index=False
    )
    .agg(
        pure_source_mean=("pure_source", "mean"),
        pure_source_var=("pure_source", "var"),
        test_source_mean=("test_source", "mean"),
        test_source_var=("test_source", "var"),
        pure_target_mean=("pure_target", "mean"),
        pure_target_var=("pure_target", "var"),
        test_target_mean=("test_target", "mean"),
        test_target_var=("test_target", "var"),
    )
)

df_summary

df_summary.to_excel("results_mean.xlsx", index=False)

num repe : 1
Delta:       0.0156342 	 Loss:       2.1898716
Delta:       0.0208300 	 Loss:       2.1531316
Delta:       0.0182993 	 Loss:       2.1062000
Delta:       0.0143183 	 Loss:       2.0746391
Delta:       0.0101736 	 Loss:       2.0662397
Delta:       0.0076357 	 Loss:       2.0647772
Delta:       0.0073698 	 Loss:       2.0641208
Delta:       0.0095221 	 Loss:       2.0626732
Delta:       0.0107479 	 Loss:       2.0579851
Delta:       0.0093393 	 Loss:       2.0542179
Delta:       0.0067933 	 Loss:       2.0525879
Delta:       0.0041581 	 Loss:       2.0523363
Delta:       0.0038087 	 Loss:       2.0522088
Delta:       0.0013010 	 Loss:       2.0521508
Delta:       0.0014675 	 Loss:       2.0521515
Delta:       0.0000027 	 Loss:       2.0521512
Delta:       0.0000000 	 Loss:       2.0521512
converged at iter  16

I0000 00:00:1772268289.435497 3132503 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 31129 MB memory:  -> device: 0, name: Tesla V100S-PCIE-32GB, pci bus id: 0000:3b:00.0, compute capability: 7.0
I0000 00:00:1772268290.478646 3133600 service.cc:148] XLA service 0x7866d9305440 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1772268290.478695 3133600 service.cc:156]   StreamExecutor device (0): Tesla V100S-PCIE-32GB, Compute Capability 7.0
I0000 00:00:1772268290.497161 3133600 cuda_dnn.cc:529] Loaded cuDNN version 91002
I0000 00:00:1772268290.582352 3133600 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

Delta: 0.020996047184738794 	  Loss: 2.152773504142843 	 Accuracy: 0.18252933507170796
Delta: 0.018792853172571893 	  Loss: 2.063891267139697 	 Accuracy: 0.28552803129074317
Delta: 0.01669052786618614 	  Loss: 1.90707727534775 	 Accuracy: 0.30247718383311606
Delta: 0.014947723229737763 	  Loss: 1.7554657169813415 	 Accuracy: 0.2777053455019557
Delta: 0.012631281643225713 	  Loss: 1.6650440180687684 	 Accuracy: 0.2790091264667536
Delta: 0.011185817967914692 	  Loss: 1.6188625409133395 	 Accuracy: 0.28292046936114734
Delta: 0.009670421949668108 	  Loss: 1.596035899596986 	 Accuracy: 0.2894393741851369
Delta: 0.008305851206778358 	  Loss: 1.5848711222985725 	 Accuracy: 0.28552803129074317
Delta: 0.007586077124993016 	  Loss: 1.5783922549088483 	 Accuracy: 0.29986962190352023

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006502155065100796 	  Loss: 1.5755764160556034 	 Accuracy: 0.31029986962190353
Delta: 0.006501988065390927 	  Loss: 1.5737413773666553 	 Accuracy: 0.3050847457627119
Delta: 0.003665228093089218 	  Loss: 1.573252891452163 	 Accuracy: 0.3050847457627119
Delta: 0.004760675708414077 	  Loss: 1.5730101632941702 	 Accuracy: 0.3050847457627119
Delta: 0.0025152145749396315 	  Loss: 1.5726388948500918 	 Accuracy: 0.3050847457627119
Delta: 0.0030677466573256476 	  Loss: 1.5726208908093464 	 Accuracy: 0.3050847457627119
Delta: 0.0028888098383902452 	  Loss: 1.5723986347564982 	 Accuracy: 0.3050847457627119
Delta: 0.0005120200383004244 	  Loss: 1.572406464929189 	 Accuracy: 0.3050847457627119
Delta: 0.0025240901477323005 	  Loss: 1.5723857840932247 	 Accuracy: 0.3050847457627119
Delta: 0.0012899934164273348 	  Loss: 1.5724185913400657 	 Accuracy: 0.3050847457627119
Delta: 0.0008160867488172346 	  Loss: 1.5723351724664298 	 Accuracy: 0.3076923076923077
Delta: 0.001369778596900384 	  Loss: 1.5722094894576686 	 Accuracy: 0.3050847457627119
Delta: 0.0011802864654864393 	  Loss: 1.5724014275050822 	 Accuracy: 0.3050847457627119
Delta: 0.003365591880343241 	  Loss: 1.5722610419417578 	 Accuracy: 0.3050847457627119
Delta: 0.0016571037667125097 	  Loss: 1.57246658145653 	 Accuracy: 0.30378096479791394
Delta: 0.00235045196980949 	  Loss: 1.5725073350019272 	 Accuracy: 0.3050847457627119
Delta: 0.0037791282605470515 	  Loss: 1.5728335653914844 	 Accuracy: 0.3050847457627119
Delta: 0.0017708653159688196 	  Loss: 1.5727303639817327 	 Accuracy: 0.3050847457627119
Delta: 0.0016275091032619516 	  Loss: 1.5727739461431067 	 Accuracy: 0.3050847457627119
Delta: 0.0012698062123026343 	  Loss: 1.5727007638814952 	 Accuracy: 0.30638852672750977
Delta: 0.0021786228596361854 	  Loss: 1.5727039648136596 	 Accuracy: 0.3050847457627119
Delta: 0.0018031344769749243 	  Loss: 1.5726804327468835 	 Accuracy: 0.3050847457627119
Delta: 0.001585372915915744 	  Loss: 1.5727449752533709 	 Accuracy: 0.3050847457627119
Delta: 0.0007366528965549535 	  Loss: 1.5726009014554276 	 Accuracy: 0.3050847457627119
Delta: 0.0006607593666180663 	  Loss: 1.5726347044758506 	 Accuracy: 0.3050847457627119
Delta: 0.0005198704091294225 	  Loss: 1.5725776088708963 	 Accuracy: 0.3089960886571056
Delta: 2.3887588973017113e-05 	  Loss: 1.572609587134331 	 Accuracy: 0.3050847457627119
Delta: 0.0014803915793872146 	  Loss: 1.5727236717364244 	 Accuracy: 0.30247718383311606
Delta: 0.0008487174829134017 	  Loss: 1.5727854363125897 	 Accuracy: 0.3050847457627119
Delta: 0.0005689358777257392 	  Loss: 1.572588192163369 	 Accuracy: 0.3050847457627119
Delta: 0.00108909979687865 	  Loss: 1.5728789000474808 	 Accuracy: 0.3050847457627119
Delta: 0.0007570441923961726 	  Loss: 1.5726664225544407 	 Accuracy: 0.3050847457627119
Delta: 0.0005407002186937879 	  Loss: 1.572614004118277 	 Accuracy: 0.3050847457627119
Delta: 0.0008676626124301211 	  Loss: 1.5726421492830216 	 Accuracy: 0.3050847457627119
Delta: 3.193411241468157e-05 	  Loss: 1.5726163316107957 	 Accuracy: 0.3050847457627119
Delta: 0.0012077719900458214 	  Loss: 1.5726721918784055 	 Accuracy: 0.3050847457627119
Delta: 3.1046828412599444e-05 	  Loss: 1.5726257487922086 	 Accuracy: 0.3050847457627119
Delta: 1.8628071497262038e-05 	  Loss: 1.5726739386991513 	 Accuracy: 0.30378096479791394
Delta: 4.481391825636173e-05 	  Loss: 1.5725656487240993 	 Accuracy: 0.3050847457627119
Delta: 2.9876441146512617e-05 	  Loss: 1.5726094414632705 	 Accuracy: 0.30378096479791394
Delta: 0.0005690973553653519 	  Loss: 1.5729786516571642 	 Accuracy: 0.3050847457627119
Delta: 0.0014848692549285592 	  Loss: 1.5727271206700095 	 Accuracy: 0.3050847457627119
Delta: 6.351347649698842e-05 	  Loss: 1.5728300750914457 	 Accuracy: 0.3050847457627119
Delta: 0.001657864137170687 	  Loss: 1.5725805282420078 	 Accuracy: 0.30247718383311606
Delta: 0.0021405894003907297 	  Loss: 1.573080210760554 	 Accuracy: 0.30378096479791394
Delta: 0.002874066895063967 	  Loss: 1.5736310933617275 	 Accuracy: 0.30378096479791394
Delta: 0.002302844811205279 	  Loss: 1.5737370024839312 	 Accuracy: 0.30378096479791394
Delta: 9.980331196217401e-05 	  Loss: 1.5738109615013132 	 Accuracy: 0.30378096479791394
Delta: 0.0001432054066003903 	  Loss: 1.573091621713096 	 Accuracy: 0.30378096479791394
Delta: 0.0010673974743019283 	  Loss: 1.5730913541070577 	 Accuracy: 0.30378096479791394
Delta: 0.0026824718221596655 	  Loss: 1.57306913358717 	 Accuracy: 0.29986962190352023
Delta: 0.001067904591441693 	  Loss: 1.5731102316352021 	 Accuracy: 0.30378096479791394
Delta: 0.0013559448671843337 	  Loss: 1.5730515215031817 	 Accuracy: 0.30378096479791394
Delta: 0.0014064466862994869 	  Loss: 1.5734908671247632 	 Accuracy: 0.3050847457627119
Delta: 0.0007117050395858068 	  Loss: 1.5733179933999426 	 Accuracy: 0.30378096479791394
Delta: 0.0006050054365759577 	  Loss: 1.57408193313301 	 Accuracy: 0.30378096479791394
Delta: 5.372905528735694e-05 	  Loss: 1.5738744789308063 	 Accuracy: 0.3011734028683181
Delta: 0.0035452733435777303 	  Loss: 1.5745876686507754 	 Accuracy: 0.30247718383311606
Delta: 0.0027319692320736983 	  Loss: 1.5748272346525407 	 Accuracy: 0.2985658409387223
Delta: 0.0014452282899696824 	  Loss: 1.5747553480469252 	 Accuracy: 0.30378096479791394
Delta: 0.004138175538969422 	  Loss: 1.5740959926409341 	 Accuracy: 0.30247718383311606
Delta: 0.001183121292423355 	  Loss: 1.5742982004073318 	 Accuracy: 0.30378096479791394
Delta: 0.0005996932143674769 	  Loss: 1.5741371752853652 	 Accuracy: 0.3011734028683181
Delta: 0.0005801973418262912 	  Loss: 1.574349875180713 	 Accuracy: 0.30247718383311606
Delta: 0.0018608020832346548 	  Loss: 1.5742552857709633 	 Accuracy: 0.30378096479791394
Delta: 0.0005582485343856255 	  Loss: 1.5740955439180886 	 Accuracy: 0.30247718383311606
Delta: 9.622687480128382e-05 	  Loss: 1.5743325562781527 	 Accuracy: 0.30247718383311606
Delta: 0.002775588366766681 	  Loss: 1.5746631205772954 	 Accuracy: 0.30247718383311606
Delta: 0.0006326014869813691 	  Loss: 1.5746682349164403 	 Accuracy: 0.30378096479791394
Delta: 0.001855464556547658 	  Loss: 1.5743500024200163 	 Accuracy: 0.30247718383311606
Delta: 0.0015631711297312096 	  Loss: 1.5744161478126908 	 Accuracy: 0.30378096479791394
Delta: 0.002496997998770966 	  Loss: 1.5740867499729903 	 Accuracy: 0.30247718383311606
Delta: 0.0016890830311985518 	  Loss: 1.5741829847702362 	 Accuracy: 0.30378096479791394
Delta: 0.0020539126332755784 	  Loss: 1.5740897501956148 	 Accuracy: 0.30378096479791394
Delta: 0.0021134748732705272 	  Loss: 1.5740710081255926 	 Accuracy: 0.30378096479791394
Delta: 0.0026612722585600095 	  Loss: 1.5745162491647076 	 Accuracy: 0.3050847457627119
Delta: 0.00482364732266789 	  Loss: 1.5756335837250306 	 Accuracy: 0.30378096479791394
Delta: 0.0043213982989266835 	  Loss: 1.5746353944403668 	 Accuracy: 0.3050847457627119
Delta: 0.0032495843846323536 	  Loss: 1.5744506607752315 	 Accuracy: 0.3050847457627119
Delta: 0.004103663345518606 	  Loss: 1.573910237878819 	 Accuracy: 0.30378096479791394
Delta: 0.0013261448525233497 	  Loss: 1.5739659291609365 	 Accuracy: 0.30247718383311606
Delta: 0.0005475505743349483 	  Loss: 1.5743130316394724 	 Accuracy: 0.30378096479791394
Delta: 2.868844859504219e-05 	  Loss: 1.574158124540244 	 Accuracy: 0.30247718383311606
Delta: 0.0031376313156998015 	  Loss: 1.575279995501949 	 Accuracy: 0.30378096479791394
Delta: 0.005120658300078377 	  Loss: 1.5757362259922174 	 Accuracy: 0.29986962190352023
Delta: 0.002705185265624546 	  Loss: 1.5767013981860156 	 Accuracy: 0.30247718383311606
Delta: 0.0033490757399926045 	  Loss: 1.5754351185546156 	 Accuracy: 0.30247718383311606
Delta: 0.0027666993079938714 	  Loss: 1.5753015261788876 	 Accuracy: 0.30378096479791394
Delta: 0.0034635875937364695 	  Loss: 1.5765313582667622 	 Accuracy: 0.29986962190352023
Delta: 0.002992036906408732 	  Loss: 1.576281943243874 	 Accuracy: 0.29465449804432853
Delta: 0.0020942567517290745 	  Loss: 1.5765131776207655 	 Accuracy: 0.29986962190352023
Delta: 0.018416171371422506 	 Loss: 1.727944617042346 	 Accuracy: 0.5855263157894737
Delta: 0.013305685496240963 	 Loss: 1.6758174338229848 	 Accuracy: 0.5894736842105263
Delta: 0.010691587580910893 	 Loss: 1.6593494794447472 	 Accuracy: 0.6
Delta: 0.008963995477427225 	 Loss: 1.652204774221845 	 Accuracy: 0.5815789473684211
Delta: 0.007821842714257 	 Loss: 1.6517000828264918 	 Accuracy: 0.6065789473684211

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005895870632100793 	 Loss: 1.6503420836659823 	 Accuracy: 0.5986842105263158
Delta: 0.005339339954426899 	 Loss: 1.6492988806608357 	 Accuracy: 0.6013157894736842
Delta: 0.004075568732895967 	 Loss: 1.6487990206342313 	 Accuracy: 0.6039473684210527
Delta: 0.0022276016481052943 	 Loss: 1.648420162502943 	 Accuracy: 0.5894736842105263
Delta: 0.00984692671343523 	 Loss: 1.6490672437914533 	 Accuracy: 0.5986842105263158
Delta: 0.0053552400894778885 	 Loss: 1.6483831397434 	 Accuracy: 0.6013157894736842
Delta: 0.0031925358863359203 	 Loss: 1.6482116891225687 	 Accuracy: 0.6
Delta: 0.0015205634769811299 	 Loss: 1.6481888839039691 	 Accuracy: 0.6
Delta: 0.002478386101180866 	 Loss: 1.6477543906863172 	 Accuracy: 0.6
Delta: 0.0018935877032223364 	 Loss: 1.6476737478085917 	 Accuracy: 0.6
Delta: 0.0019484517532242275 	 Loss: 1.6474694761720694 	 Accuracy: 0.6
Delta: 0.0014171033030550824 	 Loss: 1.6475657270885746 	 Accuracy: 0.5973684210526315
Delta: 0.002418729542885884 	 Loss: 1.6479837334400118 	 Accuracy: 0.5986842105263158
Delta: 0.0023111867640651877 	 Loss: 1.6481163999107555 	 Accuracy: 0.6013157894736842
Delta: 0.0020109866475298906 	 Loss: 1.6474871741865174 	 Accuracy: 0.6013157894736842
Delta: 0.0021849757074600307 	 Loss: 1.647555368715801 	 Accuracy: 0.6013157894736842
Delta: 6.313122005167374e-05 	 Loss: 1.6475201788378246 	 Accuracy: 0.6052631578947368
Delta: 4.8217731258208584e-05 	 Loss: 1.6474678753003527 	 Accuracy: 0.6013157894736842
Delta: 0.004361459842322571 	 Loss: 1.648505831192126 	 Accuracy: 0.6013157894736842
Delta: 0.001869187368130472 	 Loss: 1.6484700240849892 	 Accuracy: 0.6
Delta: 3.955145287464603e-05 	 Loss: 1.6482516367304745 	 Accuracy: 0.6
Delta: 0.003625391632972376 	 Loss: 1.6479194632122027 	 Accuracy: 0.6013157894736842
Delta: 0.0036619714433920045 	 Loss: 1.647971465270701 	 Accuracy: 0.5973684210526315
Delta: 0.004581545301072258 	 Loss: 1.6495981761889487 	 Accuracy: 0.6
Delta: 0.0016453076265778544 	 Loss: 1.6496412375656084 	 Accuracy: 0.6
Delta: 6.167610694475395e-05 	 Loss: 1.6496440192538273 	 Accuracy: 0.6
Delta: 0.0010598885146302374 	 Loss: 1.6497864306564671 	 Accuracy: 0.6
converged at iter  32
Delta:       0.0160001 	 Loss:       2.1825870
Delta:       0.0203881 	 Loss:       2.0871997
Delta:       0.0141929 	 Loss:       2.0496728
Delta:       0.0100136 	 Loss:       2.0396127
Delta:       0.0061946 	 Loss:       2.0373326
Delta:       0.0024331 	 Loss:       2.0370639
Delta:       0.0024726 	 Loss:       2.0370200
Delta:       0.0014262 	 Loss:       2.0370185
Delta:       0.0000008 	 Loss:       2.0370177
Delta:       0.0000000 	 Loss:       2.0370177
converged at iter  9
Delta: 0.0189812867969703 	 Loss: 1.570575704201711 	 Accuracy: 0.8532235939643347
Delta: 0.010183535642921439 	 Loss: 1.5379595938113346 	 Accuracy: 0.8587105624142661
Delta: 0.006948910960173338 	 Loss: 1.5360795908498504 	 Accuracy: 0.8477366255144033

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004854014746171697 	 Loss: 1.5356051933581867 	 Accuracy: 0.8477366255144033
Delta: 0.004757824338656748 	 Loss: 1.5357031469413756 	 Accuracy: 0.8491083676268861
Delta: 0.003709637315386927 	 Loss: 1.5356368391650204 	 Accuracy: 0.850480109739369
Delta: 0.0020409776017180146 	 Loss: 1.5358441662601314 	 Accuracy: 0.850480109739369
Delta: 0.0037538323029430386 	 Loss: 1.5358093314629868 	 Accuracy: 0.8477366255144033
Delta: 0.0014817617293149212 	 Loss: 1.5358550295310298 	 Accuracy: 0.8491083676268861
Delta: 0.002304659664941159 	 Loss: 1.535786838976604 	 Accuracy: 0.8491083676268861
Delta: 0.0017876326748458697 	 Loss: 1.5356971973192057 	 Accuracy: 0.8573388203017832
Delta: 0.0037760905563686575 	 Loss: 1.5353856371652022 	 Accuracy: 0.850480109739369
Delta: 0.0014451226635680393 	 Loss: 1.535440653566987 	 Accuracy: 0.8491083676268861
Delta: 0.001104397592097245 	 Loss: 1.5356086045303403 	 Accuracy: 0.8518518518518519
Delta: 5.017585983622265e-05 	 Loss: 1.5352786850453881 	 Accuracy: 0.8518518518518519
Delta: 3.393457148001246e-05 	 Loss: 1.5353515994110838 	 Accuracy: 0.850480109739369
Delta: 3.7074256876100216e-05 	 Loss: 1.5353388592120298 	 Accuracy: 0.850480109739369
Delta: 0.0052372972229484385 	 Loss: 1.5343485900197942 	 Accuracy: 0.8573388203017832
Delta: 0.000601572269130286 	 Loss: 1.5354549107951005 	 Accuracy: 0.850480109739369
Delta: 8.804331742356223e-05 	 Loss: 1.5343481686481553 	 Accuracy: 0.850480109739369
Delta: 6.202399684163244e-05 	 Loss: 1.5343772510985998 	 Accuracy: 0.8477366255144033
Delta: 4.006978226007565e-05 	 Loss: 1.5344400748684732 	 Accuracy: 0.8532235939643347
Delta: 0.0018591962565832163 	 Loss: 1.5341597363427557 	 Accuracy: 0.8477366255144033
Delta: 0.0007045914048116849 	 Loss: 1.5342116637587808 	 Accuracy: 0.8628257887517147
Delta: 8.765949353667757e-05 	 Loss: 1.5342628220783991 	 Accuracy: 0.8395061728395061
Delta: 5.600415388628997e-05 	 Loss: 1.534364999303232 	 Accuracy: 0.8518518518518519
Delta: 0.0035117268857918597 	 Loss: 1.535953713044513 	 Accuracy: 0.8491083676268861
Delta: 0.001206621791691609 	 Loss: 1.536152679508299 	 Accuracy: 0.8463648834019204
Delta: 0.0013297194341143242 	 Loss: 1.5365355213837124 	 Accuracy: 0.8395061728395061
Delta: 7.5258996050083e-05 	 Loss: 1.5365674778671317 	 Accuracy: 0.8449931412894376
Delta: 0.002185776982561052 	 Loss: 1.537134680203619 	 Accuracy: 0.8449931412894376
Delta: 0.0030703663443517135 	 Loss: 1.5375879943237363 	 Accuracy: 0.8463648834019204
Delta: 1.8860912702578675e-05 	 Loss: 1.5375354354557524 	 Accuracy: 0.8463648834019204
Delta: 0.0011522473573433454 	 Loss: 1.5375182182703786 	 Accuracy: 0.8449931412894376
Delta: 0.005922264625598003 	 Loss: 1.5407482943918913 	 Accuracy: 0.8477366255144033
Delta: 0.006425411546323993 	 Loss: 1.536407618488086 	 Accuracy: 0.8477366255144033
Delta: 0.00195143653400342 	 Loss: 1.5369388249103721 	 Accuracy: 0.8477366255144033
Delta: 0.0007060040722114687 	 Loss: 1.5365582976894971 	 Accuracy: 0.850480109739369
Delta: 0.000884325085990766 	 Loss: 1.5365317703142556 	 Accuracy: 0.850480109739369
Delta: 0.0023816310303627374 	 Loss: 1.5361436489800693 	 Accuracy: 0.8491083676268861
Delta: 0.006331097316616534 	 Loss: 1.539873108504429 	 Accuracy: 0.8491083676268861
Delta: 0.005082759101264313 	 Loss: 1.5377218506204686 	 Accuracy: 0.850480109739369
Delta: 1.366049358153792e-05 	 Loss: 1.537711893006229 	 Accuracy: 0.8518518518518519
Delta: 0.002345352233966296 	 Loss: 1.5375623025177783 	 Accuracy: 0.850480109739369
Delta: 0.0005798047571180848 	 Loss: 1.5375740399878666 	 Accuracy: 0.850480109739369
Delta: 7.895993044763195e-05 	 Loss: 1.5376215056465434 	 Accuracy: 0.8491083676268861
Delta: 0.0035988678279701633 	 Loss: 1.5385442959029523 	 Accuracy: 0.8491083676268861
Delta: 0.0026385540117664498 	 Loss: 1.53925444737965 	 Accuracy: 0.8477366255144033
Delta: 0.0006334956923205221 	 Loss: 1.5391809892533226 	 Accuracy: 0.8436213991769548
Delta: 0.0007858400275681431 	 Loss: 1.5390751298816854 	 Accuracy: 0.8477366255144033
Delta: 1.6903525887544944e-05 	 Loss: 1.5389555638724715 	 Accuracy: 0.8477366255144033
Delta: 0.0046159465848643385 	 Loss: 1.5399396083035817 	 Accuracy: 0.8477366255144033
Delta: 0.004802338945081011 	 Loss: 1.5377957301715843 	 Accuracy: 0.8491083676268861
Delta: 0.0008617244976406897 	 Loss: 1.5377364219586434 	 Accuracy: 0.8353909465020576
Delta: 0.007828406647962595 	 Loss: 1.5459585141474184 	 Accuracy: 0.8381344307270233
Delta: 0.005874910026127481 	 Loss: 1.5440651242017618 	 Accuracy: 0.8463648834019204
Delta: 0.007139000555580476 	 Loss: 1.5409077830476088 	 Accuracy: 0.8477366255144033
Delta: 0.002349226255189051 	 Loss: 1.540741526754797 	 Accuracy: 0.8477366255144033
Delta: 0.004494910011923108 	 Loss: 1.5403046355676775 	 Accuracy: 0.8477366255144033
Delta: 0.004627584017909128 	 Loss: 1.5387739441945834 	 Accuracy: 0.8463648834019204
Delta: 0.004418268399074685 	 Loss: 1.5396081297492916 	 Accuracy: 0.8463648834019204
Delta: 0.0031244263290331545 	 Loss: 1.5405783971505405 	 Accuracy: 0.8449931412894376
Delta: 4.376023600295156e-05 	 Loss: 1.540533437075485 	 Accuracy: 0.8449931412894376
Delta: 0.0020809998829562034 	 Loss: 1.540516731106399 	 Accuracy: 0.8449931412894376
Delta: 0.0008808581834100068 	 Loss: 1.5406225158741444 	 Accuracy: 0.840877914951989
Delta: 0.004793081977088181 	 Loss: 1.5409188092486286 	 Accuracy: 0.8340192043895748
Delta: 0.0031805276503959834 	 Loss: 1.5410792571455154 	 Accuracy: 0.8381344307270233
Delta: 0.0027057835355988307 	 Loss: 1.5409251432453832 	 Accuracy: 0.8395061728395061
Delta: 0.0012545913466357585 	 Loss: 1.540448590470581 	 Accuracy: 0.8422496570644719
Delta: 0.0026461100563561516 	 Loss: 1.5405715894861183 	 Accuracy: 0.8422496570644719
Delta: 0.002909954352297367 	 Loss: 1.5403488991835106 	 Accuracy: 0.8395061728395061
Delta: 0.002306435317390291 	 Loss: 1.5408758274226764 	 Accuracy: 0.8381344307270233
Delta: 0.0029505499506294343 	 Loss: 1.5410172469929477 	 Accuracy: 0.8395061728395061
Delta: 0.0012711355488429221 	 Loss: 1.54093778457844 	 Accuracy: 0.8395061728395061
Delta: 3.501956588137271e-05 	 Loss: 1.5410094603773408 	 Accuracy: 0.8381344307270233
Delta: 0.0009112514207431905 	 Loss: 1.541049947177529 	 Accuracy: 0.8381344307270233
Delta: 6.516462032089236e-05 	 Loss: 1.5410157813698993 	 Accuracy: 0.8436213991769548
Delta: 0.005536435416159144 	 Loss: 1.5405499105440632 	 Accuracy: 0.8436213991769548
Delta: 0.002693635735767469 	 Loss: 1.5409379000097414 	 Accuracy: 0.8422496570644719
Delta: 0.0031584958589298312 	 Loss: 1.5404001840197332 	 Accuracy: 0.840877914951989
Delta: 0.004247073576027032 	 Loss: 1.5425788301942684 	 Accuracy: 0.840877914951989
Delta: 0.0009553204795247645 	 Loss: 1.5428227265819388 	 Accuracy: 0.840877914951989
Delta: 0.0044649818784250755 	 Loss: 1.5426501966097215 	 Accuracy: 0.840877914951989
Delta: 0.0030526768029812785 	 Loss: 1.542983582551842 	 Accuracy: 0.8367626886145405
Delta: 0.005452795237404162 	 Loss: 1.5449684852965149 	 Accuracy: 0.8381344307270233
Delta: 0.00249562475143487 	 Loss: 1.5444444981286276 	 Accuracy: 0.8395061728395061
Delta: 0.0036058901996915303 	 Loss: 1.5432232057596322 	 Accuracy: 0.8395061728395061
Delta: 0.006623161994504304 	 Loss: 1.544219221865287 	 Accuracy: 0.8381344307270233
Delta: 0.002680866710689353 	 Loss: 1.5434314163415261 	 Accuracy: 0.8395061728395061
Delta: 0.005325217581937988 	 Loss: 1.5415010702096612 	 Accuracy: 0.840877914951989
Delta: 0.0025809260102199394 	 Loss: 1.5423551527592663 	 Accuracy: 0.8381344307270233
Delta: 0.004027849007874478 	 Loss: 1.5426303762124487 	 Accuracy: 0.8367626886145405
Delta: 0.0014105984960793019 	 Loss: 1.5428796116320174 	 Accuracy: 0.8353909465020576
Delta: 0.002814365867617137 	 Loss: 1.5427337553514175 	 Accuracy: 0.8257887517146777
Delta: 0.0049519825979610745 	 Loss: 1.5462648755699904 	 Accuracy: 0.831275720164609
Delta: 0.00394831003123765 	 Loss: 1.5428467161343384 	 Accuracy: 0.8353909465020576
Delta: 0.003152824759913548 	 Loss: 1.543857146919745 	 Accuracy: 0.8353909465020576
Delta: 0.003634283003928745 	 Loss: 1.5449258102956742 	 Accuracy: 0.831275720164609
Delta: 0.003603147327696624 	 Loss: 1.542857854435129 	 Accuracy: 0.8367626886145405
Delta: 0.0005670529097305086 	 Loss: 1.5424042598850247 	 Accuracy: 0.8422496570644719
Delta:       0.0164536 	 Loss:       2.1607437
Delta:       0.0184859 	 Loss:       2.0389298
Delta:       0.0091623 	 Loss:       2.0144750
Delta:       0.0042287 	 Loss:       2.0128849
Delta:       0.0015953 	 Loss:       2.0126999
Delta:       0.0000007 	 Loss:       2.0126994
Delta:       0.0000000 	 Loss:       2.0126994
converged at iter  6
Delta: 0.01907935978973318 	 Loss: 1.5524472309688169 	 Accuracy: 0.8871201157742402
Delta: 0.009443101170245122 	 Loss: 1.5286408955577402 	 Accuracy: 0.8784370477568741

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004649879075309851 	 Loss: 1.5274076762505968 	 Accuracy: 0.874095513748191
Delta: 0.004913831413216494 	 Loss: 1.5271973920705009 	 Accuracy: 0.8712011577424024
Delta: 0.004583021685523163 	 Loss: 1.5269997143464886 	 Accuracy: 0.869753979739508
Delta: 0.0018247908273537998 	 Loss: 1.5269980588572871 	 Accuracy: 0.8683068017366136
Delta: 0.0007692477557217745 	 Loss: 1.5268906248170588 	 Accuracy: 0.8683068017366136
Delta: 0.0019479872428666246 	 Loss: 1.5271231494131907 	 Accuracy: 0.8668596237337193
Delta: 0.003172211196973857 	 Loss: 1.527236680063962 	 Accuracy: 0.8668596237337193
Delta: 0.0036128828623614214 	 Loss: 1.52742506366116 	 Accuracy: 0.8668596237337193
Delta: 0.0005570042541673546 	 Loss: 1.527081310417558 	 Accuracy: 0.8683068017366136
Delta: 1.5265923034363353e-05 	 Loss: 1.52705398240037 	 Accuracy: 0.8668596237337193
Delta: 0.0010781371449413077 	 Loss: 1.52722489023756 	 Accuracy: 0.8668596237337193
Delta: 4.6533502305763976e-05 	 Loss: 1.5272452033139414 	 Accuracy: 0.8668596237337193
Delta: 6.107747338054657e-05 	 Loss: 1.5273528875669782 	 Accuracy: 0.8683068017366136
Delta: 0.001240865794799055 	 Loss: 1.5273961471907809 	 Accuracy: 0.8668596237337193
Delta: 0.0010813214531706344 	 Loss: 1.5273664541739762 	 Accuracy: 0.8668596237337193
Delta: 6.575739497240338e-05 	 Loss: 1.5272771548917798 	 Accuracy: 0.8625180897250362
Delta: 9.41290746094742e-05 	 Loss: 1.5268294430966733 	 Accuracy: 0.8639652677279306
Delta: 0.0038532328155047296 	 Loss: 1.5267083726069182 	 Accuracy: 0.8654124457308249
Delta: 0.000580707168127714 	 Loss: 1.5269680119671478 	 Accuracy: 0.8654124457308249
Delta: 0.0006607104645600335 	 Loss: 1.5270093870015553 	 Accuracy: 0.8668596237337193
Delta: 0.0018295858173544806 	 Loss: 1.526968946380638 	 Accuracy: 0.8668596237337193

KeyboardInterrupt:

10

In [12]:
perf_test_target

np.float64(0.9322916666666666)

In [10]:
a = np.random.choice(np.arange(len(source)), math.ceil(0.8 * len(source)), replace=False)
b = np.random.choice(np.arange(len(target)), math.ceil(0.8 * len(target)), replace=False)

S_test = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
T_test = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)
S = source.iloc[a, :].reset_index(drop=True)
T = target.iloc[b, :].reset_index(drop=True)

import numpy as np
from sklearn.preprocessing import OneHotEncoder as onehot
from sklearn.model_selection import train_test_split
from jdcoot.utils import xcolumns, discrete_classifiers, discrete_accuracy
prop_source = 0.8
prop_target = 0.8
source_levels = np.sort(np.unique(S.Z))
target_levels = np.sort(np.unique(T.Z))

nClass = len(np.union1d(source_levels, target_levels))
categories = [np.arange(nClass)]

enc = onehot(handle_unknown="ignore", sparse_output=False, categories=categories)



x_source_train = S.loc[:, xcolumns(S)].values
z_source_train = enc.fit_transform(S.Z.values[:, np.newaxis])

x_target_train = T.loc[:, xcolumns(T)].values
z_target_train = enc.fit_transform(T.Z.values[:, np.newaxis])

x_source_test = S_test.loc[:, xcolumns(S_test)].values
z_source_test = S_test.Z.values

x_target_test = T_test.loc[:, xcolumns(T_test)].values
z_target_test = T_test.Z.values

clf_source, clf_target = discrete_classifiers(source, target, "relu", "softmax")

clf_target.fit(x_target_train, z_target_train, batch_size=20, epochs=20, verbose=0)
clf_source.fit(x_source_train, z_source_train, batch_size=20, epochs=20, verbose=0)

z_target_pred = enc.inverse_transform(
        clf_target.predict(x_target_test, verbose=0)
    ).ravel()
z_source_pred = enc.inverse_transform(
        clf_source.predict(x_source_test, verbose=0)
    ).ravel()

perf_test_source = discrete_accuracy(z_source_pred,S_test.Z)
perf_test_target = discrete_accuracy(z_target_pred, T_test.Z)

In [6]:
perf_test_target

np.float64(0.9581151832460733)

In [ ]:
import numpy as np
# Exemple de valeurs à tester pour alpha
alpha_values = np.linspace(1, 3, 21)  # 0, 0.1, 0.2, ..., 1.0
best_alpha = None
best_score = -np.inf  # ou 0 selon ta métrique
results = []
numRepetitions = 10
for repe in range(numRepetitions):
   
        a = np.random.choice(np.arange(len(source)), math.ceil(0.8 * len(source)), replace=False)
        b = np.random.choice(np.arange(len(target)), math.ceil(0.8 * len(target)), replace=False)

        S_test = source.iloc[np.setdiff1d(np.arange(len(source)), a), :].reset_index(drop=True)
        T_test = target.iloc[np.setdiff1d(np.arange(len(target)), b), :].reset_index(drop=True)
        S = source.iloc[a, :].reset_index(drop=True)
        T = target.iloc[b, :].reset_index(drop=True)
        for a in alpha_values:
            pure_source, pure_target, test_source, test_target = \
            discrete_unsupervised_jdcoot(S, T, S_test, T_test,alpha=a)

            score = test_target  
    
            if score > best_score:
                best_score = score
                best_alpha = a

        results.append({
         "repetition": repe,
         "recoding": "jdcoot",
         "learning": "unsupervised",
         "alpha": best_alpha,
     })

   

df_results = pd.DataFrame(results)


df_results

df_summary = (
    df_results
    .groupby(
        ["recoding", "learning", "alpha"],
        as_index=False
    )
    .agg(
        alpha_mean=("alpha", "mean"),
    )
)

df_summary

df_summary.to_excel("results_mean.xlsx", index=False)

Delta: 0.02092633484461369 	  Loss: 2.14224528364411 	 Accuracy: 0.18252933507170796
Delta: 0.018176953250223424 	  Loss: 2.076236270607468 	 Accuracy: 0.28292046936114734
Delta: 0.016913402047423795 	  Loss: 1.9716716026534993 	 Accuracy: 0.40547588005215124
Delta: 0.014520431794906617 	  Loss: 1.8454590126498591 	 Accuracy: 0.5097783572359843
Delta: 0.011881452125277088 	  Loss: 1.7546242454622245 	 Accuracy: 0.5228161668839635
Delta: 0.009674465390928417 	  Loss: 1.698684494847213 	 Accuracy: 0.5202086049543677
Delta: 0.008769443620514402 	  Loss: 1.662466722491427 	 Accuracy: 0.5215123859191656
Delta: 0.0073013686771785545 	  Loss: 1.638404211386383 	 Accuracy: 0.5228161668839635
Delta: 0.007038005114058835 	  Loss: 1.6199267417866 	 Accuracy: 0.5228161668839635
Delta: 0.007591871689274479 	  Loss: 1.6066873126727785 	 Accuracy: 0.5176010430247718
Delta: 0.006789434164771827 	  Loss: 1.5963459873051473 	 Accuracy: 0.5241199478487614
Delta: 0.006842256866761354 	  Loss: 1.588015822722844 	 Accuracy: 0.5436766623207301
Delta: 0.007410099933670952 	  Loss: 1.5810263633152921 	 Accuracy: 0.5501955671447197
Delta: 0.0073707787688166975 	  Loss: 1.5747415928930901 	 Accuracy: 0.546284224250326
Delta: 0.006180698838244777 	  Loss: 1.5696017006381526 	 Accuracy: 0.5501955671447197
Delta: 0.006829524705007727 	  Loss: 1.5644036761631859 	 Accuracy: 0.5632333767926988
Delta: 0.006297554819954984 	  Loss: 1.5598913525453102 	 Accuracy: 0.5710560625814863
Delta: 0.006297289063550445 	  Loss: 1.5556126954252685 	 Accuracy: 0.5645371577574967
Delta: 0.005244726991613287 	  Loss: 1.5521152131308944 	 Accuracy: 0.5840938722294654
Delta: 0.006799936892432434 	  Loss: 1.548245462086185 	 Accuracy: 0.5827900912646675
Delta: 0.005540556425430151 	  Loss: 1.5451156795764731 	 Accuracy: 0.5919165580182529
Delta: 0.0059851212196017824 	  Loss: 1.542187108638963 	 Accuracy: 0.5919165580182529
Delta: 0.004216535699428493 	  Loss: 1.5399575911745638 	 Accuracy: 0.5945241199478487
Delta: 0.00519614082651496 	  Loss: 1.5381614346328845 	 Accuracy: 0.5958279009126467
Delta: 0.004022352263166521 	  Loss: 1.536427869031299 	 Accuracy: 0.590612777053455
Delta: 0.004069151949377786 	  Loss: 1.5354978762136966 	 Accuracy: 0.5932203389830508
Delta: 0.0030675830391989926 	  Loss: 1.534577337796963 	 Accuracy: 0.5997392438070405
Delta: 0.004043822897662037 	  Loss: 1.5337898204196052 	 Accuracy: 0.5997392438070405
Delta: 0.0038808639608986562 	  Loss: 1.5331061361106286 	 Accuracy: 0.5997392438070405
Delta: 0.0037593919358264584 	  Loss: 1.532343975216902 	 Accuracy: 0.5971316818774446
Delta: 0.0027830208870954667 	  Loss: 1.5317205038911939 	 Accuracy: 0.6023468057366362
Delta: 0.003273394124368923 	  Loss: 1.5312697729742508 	 Accuracy: 0.5984354628422425
Delta: 0.004014455084267004 	  Loss: 1.53072047908441 	 Accuracy: 0.6010430247718384

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004268351425853599 	  Loss: 1.5302416076309593 	 Accuracy: 0.5971316818774446
Delta: 0.002468600151216607 	  Loss: 1.5298568680534534 	 Accuracy: 0.6010430247718384
Delta: 0.003409394980149225 	  Loss: 1.5294051191112767 	 Accuracy: 0.6036505867014341
Delta: 0.0026056418154393524 	  Loss: 1.5290989163623905 	 Accuracy: 0.6036505867014341
Delta: 0.004450593221749945 	  Loss: 1.5287926472316449 	 Accuracy: 0.6010430247718384
Delta: 0.0019982357466058792 	  Loss: 1.5285084229842665 	 Accuracy: 0.6010430247718384
Delta: 0.003024546015134233 	  Loss: 1.5281522435370294 	 Accuracy: 0.6036505867014341
Delta: 0.0031814445326312723 	  Loss: 1.5279872360789952 	 Accuracy: 0.6023468057366362
Delta: 0.002331933267503773 	  Loss: 1.5276707170414545 	 Accuracy: 0.5997392438070405
Delta: 0.003337752432730538 	  Loss: 1.5275016550320366 	 Accuracy: 0.6036505867014341
Delta: 0.00247531803093028 	  Loss: 1.52738016471346 	 Accuracy: 0.6023468057366362
Delta: 0.003883076425155863 	  Loss: 1.527155695546577 	 Accuracy: 0.6049543676662321
Delta: 0.002832280248932885 	  Loss: 1.5269180796647186 	 Accuracy: 0.6010430247718384
Delta: 0.0024908385541816905 	  Loss: 1.5269323117037263 	 Accuracy: 0.6023468057366362
Delta: 0.0022027693316763386 	  Loss: 1.5267353106978878 	 Accuracy: 0.6049543676662321
Delta: 0.002667776817475358 	  Loss: 1.5265596867908644 	 Accuracy: 0.6049543676662321
Delta: 0.002019842743098206 	  Loss: 1.5263530600211799 	 Accuracy: 0.60625814863103
Delta: 0.003027525014756175 	  Loss: 1.526167469040138 	 Accuracy: 0.6010430247718384
Delta: 0.0025643544442239307 	  Loss: 1.5260732604525653 	 Accuracy: 0.6010430247718384
Delta: 0.002363047993407593 	  Loss: 1.5258821924259802 	 Accuracy: 0.5997392438070405
Delta: 0.0036705377924177228 	  Loss: 1.5256698754556077 	 Accuracy: 0.5984354628422425
Delta: 0.002857387898698673 	  Loss: 1.5255398138940777 	 Accuracy: 0.6049543676662321
Delta: 0.0028042684186828457 	  Loss: 1.5254061937751655 	 Accuracy: 0.5997392438070405
Delta: 0.0015964861404586261 	  Loss: 1.5255201318984892 	 Accuracy: 0.6023468057366362
Delta: 0.0010425072639215819 	  Loss: 1.525359305470291 	 Accuracy: 0.6023468057366362
Delta: 0.0041745398075246735 	  Loss: 1.5251690877757729 	 Accuracy: 0.6049543676662321
Delta: 0.002687995863422256 	  Loss: 1.525016808093031 	 Accuracy: 0.6010430247718384
Delta: 0.002470845233613222 	  Loss: 1.5249092517355824 	 Accuracy: 0.6010430247718384
Delta: 0.0028145724691463828 	  Loss: 1.5247568555470639 	 Accuracy: 0.6075619295958279
Delta: 0.0022677316200652897 	  Loss: 1.5246245643469092 	 Accuracy: 0.6023468057366362
Delta: 0.0010996869754922119 	  Loss: 1.524558397695366 	 Accuracy: 0.6049543676662321
Delta: 0.002420663529890616 	  Loss: 1.5245031186776896 	 Accuracy: 0.6010430247718384
Delta: 0.0016611774050257387 	  Loss: 1.5244456205210875 	 Accuracy: 0.6049543676662321
Delta: 0.0016448727751863395 	  Loss: 1.5244114796592878 	 Accuracy: 0.6049543676662321
Delta: 0.0010646412502847476 	  Loss: 1.5243480041312325 	 Accuracy: 0.6023468057366362
Delta: 0.0028351200286360527 	  Loss: 1.5243708581975015 	 Accuracy: 0.6010430247718384
Delta: 0.001314354876700535 	  Loss: 1.5243786078859116 	 Accuracy: 0.6010430247718384
Delta: 0.0022642356015680183 	  Loss: 1.5243218200732456 	 Accuracy: 0.6023468057366362
Delta: 0.0027054463604969116 	  Loss: 1.5242718925130068 	 Accuracy: 0.6010430247718384
Delta: 0.0023995681376199796 	  Loss: 1.524190020942679 	 Accuracy: 0.5945241199478487
Delta: 0.002941104544608734 	  Loss: 1.5241198383661578 	 Accuracy: 0.5971316818774446
Delta: 0.0016380593665412037 	  Loss: 1.5241018142840967 	 Accuracy: 0.5958279009126467
Delta: 2.5066593313115205e-05 	  Loss: 1.5240642992380729 	 Accuracy: 0.5958279009126467
Delta: 1.5845548699870904e-05 	  Loss: 1.5240352063047302 	 Accuracy: 0.6010430247718384
Delta: 0.0023294234285839337 	  Loss: 1.5240673760198393 	 Accuracy: 0.5971316818774446
Delta: 0.0005148784074284461 	  Loss: 1.5240166883252773 	 Accuracy: 0.5958279009126467
Delta: 0.0021190881977333174 	  Loss: 1.5240167777982525 	 Accuracy: 0.5958279009126467
converged at iter  79
Delta: 0.02089465530088819 	  Loss: 2.142645908736151 	 Accuracy: 0.19035202086049544
Delta: 0.018324889951317716 	  Loss: 2.0741145710959907 	 Accuracy: 0.2985658409387223
Delta: 0.016871023031744457 	  Loss: 1.9621084067780292 	 Accuracy: 0.4041720990873533
Delta: 0.014579474102209344 	  Loss: 1.8289914482115421 	 Accuracy: 0.47327249022164275
Delta: 0.012199488044954994 	  Loss: 1.735972808708751 	 Accuracy: 0.5449804432855281
Delta: 0.010418746452733533 	  Loss: 1.680155115086355 	 Accuracy: 0.5449804432855281
Delta: 0.009586496985565615 	  Loss: 1.6430089475873322 	 Accuracy: 0.5501955671447197
Delta: 0.008629736951895249 	  Loss: 1.6171749962636137 	 Accuracy: 0.5632333767926988
Delta: 0.007888170379186425 	  Loss: 1.5997506403556323 	 Accuracy: 0.5684485006518905
Delta: 0.00766933717858912 	  Loss: 1.586927670585487 	 Accuracy: 0.5788787483702738
Delta: 0.007739431500127138 	  Loss: 1.576853804436626 	 Accuracy: 0.5827900912646675
Delta: 0.007619431138133497 	  Loss: 1.5690182077867973 	 Accuracy: 0.5827900912646675
Delta: 0.007088614299766722 	  Loss: 1.5629771051113046 	 Accuracy: 0.5801825293350718
Delta: 0.007168254911786516 	  Loss: 1.5576035697134591 	 Accuracy: 0.5801825293350718
Delta: 0.006422740475952674 	  Loss: 1.5530814083536364 	 Accuracy: 0.5919165580182529
Delta: 0.005725370794065315 	  Loss: 1.5494431115418772 	 Accuracy: 0.5958279009126467
Delta: 0.005988072130202418 	  Loss: 1.5469258820741203 	 Accuracy: 0.5932203389830508
Delta: 0.005928426576960824 	  Loss: 1.5443906797783868 	 Accuracy: 0.5945241199478487
Delta: 0.0053077968510692915 	  Loss: 1.5419178446025577 	 Accuracy: 0.590612777053455
Delta: 0.00453451267550132 	  Loss: 1.540915246617204 	 Accuracy: 0.5997392438070405
Delta: 0.00473661794482668 	  Loss: 1.5396029552882649 	 Accuracy: 0.5984354628422425
Delta: 0.004663149734295903 	  Loss: 1.5383899397941638 	 Accuracy: 0.6010430247718384

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004250858110592078 	  Loss: 1.5375583315617698 	 Accuracy: 0.5971316818774446
Delta: 0.004925172950520025 	  Loss: 1.5366972513651223 	 Accuracy: 0.5971316818774446
Delta: 0.0025573262853966373 	  Loss: 1.536596680295323 	 Accuracy: 0.6023468057366362
Delta: 0.0030462749842994933 	  Loss: 1.5363899627465376 	 Accuracy: 0.6010430247718384
Delta: 0.004018761166484025 	  Loss: 1.53628394740011 	 Accuracy: 0.6010430247718384
Delta: 0.0035866075779905095 	  Loss: 1.5358793178845394 	 Accuracy: 0.6010430247718384
Delta: 0.0028464444850449413 	  Loss: 1.5356471662770999 	 Accuracy: 0.5958279009126467
Delta: 0.0030939960551417058 	  Loss: 1.5355380805102017 	 Accuracy: 0.5945241199478487
Delta: 0.0014537634695905965 	  Loss: 1.535479073065265 	 Accuracy: 0.5997392438070405
Delta: 0.0026527589885764046 	  Loss: 1.535308454312641 	 Accuracy: 0.5984354628422425
Delta: 0.00432571082097549 	  Loss: 1.5351977496988485 	 Accuracy: 0.6010430247718384
Delta: 0.003790032444591693 	  Loss: 1.534973179762389 	 Accuracy: 0.6010430247718384
Delta: 0.0023536871435048414 	  Loss: 1.535004897033713 	 Accuracy: 0.5997392438070405
Delta: 0.0020863708622989125 	  Loss: 1.5349697918254317 	 Accuracy: 0.6023468057366362
Delta: 0.002603863164596835 	  Loss: 1.5349859007996187 	 Accuracy: 0.6010430247718384
Delta: 0.001156262178803922 	  Loss: 1.5347720329368846 	 Accuracy: 0.6023468057366362
Delta: 0.001770304747047543 	  Loss: 1.5346810880497188 	 Accuracy: 0.6023468057366362
Delta: 0.0025130979582564366 	  Loss: 1.534608785315193 	 Accuracy: 0.6036505867014341
Delta: 0.0009665261824342977 	  Loss: 1.53455211041919 	 Accuracy: 0.6010430247718384
Delta: 0.0019261776681014366 	  Loss: 1.534518311309967 	 Accuracy: 0.6023468057366362
Delta: 0.0005629947114913376 	  Loss: 1.5345815417224964 	 Accuracy: 0.6010430247718384
Delta: 0.00141168351535709 	  Loss: 1.5346448626098106 	 Accuracy: 0.6023468057366362
Delta: 0.0028118646716343058 	  Loss: 1.5346166697818322 	 Accuracy: 0.6036505867014341
Delta: 0.001589416376699578 	  Loss: 1.534594091289953 	 Accuracy: 0.6036505867014341
Delta: 4.012297684780255e-05 	  Loss: 1.5345646234404886 	 Accuracy: 0.6036505867014341
Delta: 2.8475112989745433e-05 	  Loss: 1.534540326081415 	 Accuracy: 0.6036505867014341
Delta: 0.0008121631491307098 	  Loss: 1.5346436759266937 	 Accuracy: 0.6036505867014341
Delta: 0.00278681251604282 	  Loss: 1.5345122775396884 	 Accuracy: 0.6036505867014341
Delta: 0.001231269619030291 	  Loss: 1.5345069822213142 	 Accuracy: 0.6036505867014341
Delta: 1.3993431140346582e-05 	  Loss: 1.5344655595886578 	 Accuracy: 0.6036505867014341
Delta: 0.003300217262546625 	  Loss: 1.5344971275793837 	 Accuracy: 0.6023468057366362
Delta: 0.002240394297138076 	  Loss: 1.5344775085412272 	 Accuracy: 0.6023468057366362
Delta: 0.0014082089592103294 	  Loss: 1.534452325128612 	 Accuracy: 0.6023468057366362
Delta: 0.0017177533986376383 	  Loss: 1.5345046495480772 	 Accuracy: 0.6023468057366362
Delta: 3.2692308420123674e-05 	  Loss: 1.5344412509694212 	 Accuracy: 0.6010430247718384
Delta: 0.0011655137344186702 	  Loss: 1.5344537090990342 	 Accuracy: 0.6036505867014341
Delta: 2.2067248208062916e-05 	  Loss: 1.5344198787967764 	 Accuracy: 0.6023468057366362
Delta: 1.566458020670897e-05 	  Loss: 1.5344110315436903 	 Accuracy: 0.6036505867014341
Delta: 0.0012978090077590512 	  Loss: 1.5343478195028517 	 Accuracy: 0.6023468057366362
Delta: 0.0010626453527346083 	  Loss: 1.534481595447557 	 Accuracy: 0.6036505867014341
Delta: 0.0008806914509707418 	  Loss: 1.5344184463736745 	 Accuracy: 0.6036505867014341
Delta: 0.0008771520692376736 	  Loss: 1.534426301462985 	 Accuracy: 0.6036505867014341
Delta: 0.0015733415989247464 	  Loss: 1.5345100227194535 	 Accuracy: 0.6010430247718384
Delta: 0.001349884143046869 	  Loss: 1.5345284855546275 	 Accuracy: 0.6010430247718384
Delta: 0.0008761344111201102 	  Loss: 1.5345145083003342 	 Accuracy: 0.6023468057366362
Delta: 0.0008964017812027648 	  Loss: 1.534513805508492 	 Accuracy: 0.6036505867014341
Delta: 3.088645767197219e-05 	  Loss: 1.5344299028043866 	 Accuracy: 0.6036505867014341
Delta: 2.0844769228612725e-05 	  Loss: 1.5344672570398794 	 Accuracy: 0.6010430247718384
Delta: 0.0016253158977586261 	  Loss: 1.5344924132235889 	 Accuracy: 0.6049543676662321
Delta: 0.00224516541020619 	  Loss: 1.5344760633196965 	 Accuracy: 0.6023468057366362
Delta: 4.0297059053395004e-05 	  Loss: 1.534467644770666 	 Accuracy: 0.6023468057366362
Delta: 0.0007084685009850011 	  Loss: 1.5345165471003273 	 Accuracy: 0.6036505867014341
Delta: 2.288566403666005e-05 	  Loss: 1.534453072266487 	 Accuracy: 0.6049543676662321
Delta: 0.0007902554456953124 	  Loss: 1.534476238664372 	 Accuracy: 0.6023468057366362
Delta: 0.0005245129705748078 	  Loss: 1.5345113270100623 	 Accuracy: 0.6036505867014341
Delta: 1.2793047389631848e-05 	  Loss: 1.5344890066490329 	 Accuracy: 0.6010430247718384
Delta: 0.0005189448122373102 	  Loss: 1.534474297693619 	 Accuracy: 0.5997392438070405
Delta: 3.801950664072393e-05 	  Loss: 1.5345391232230434 	 Accuracy: 0.6010430247718384
Delta: 0.0007563407026807111 	  Loss: 1.5344862539432627 	 Accuracy: 0.6023468057366362
Delta: 6.283036986002276e-05 	  Loss: 1.5345527208266179 	 Accuracy: 0.6023468057366362
Delta: 1.3071929318357105e-05 	  Loss: 1.5345088478741613 	 Accuracy: 0.6023468057366362
Delta: 2.606480594931879e-05 	  Loss: 1.5345288573118554 	 Accuracy: 0.6010430247718384
Delta: 0.0025681856944166203 	  Loss: 1.5344230514205996 	 Accuracy: 0.6036505867014341
Delta: 0.0036617881839906366 	  Loss: 1.5346582758795635 	 Accuracy: 0.6023468057366362
Delta: 0.0007360270581151875 	  Loss: 1.53463536443422 	 Accuracy: 0.6023468057366362
Delta: 0.002124597659132724 	  Loss: 1.5346489970202484 	 Accuracy: 0.6023468057366362
Delta: 0.001520069418878819 	  Loss: 1.5345404616210145 	 Accuracy: 0.6049543676662321
Delta: 0.0008950681118548399 	  Loss: 1.5345498770063701 	 Accuracy: 0.60625814863103
Delta: 0.002284083749438824 	  Loss: 1.5345884931807854 	 Accuracy: 0.6049543676662321
Delta: 0.0005326415950036793 	  Loss: 1.5345724259861688 	 Accuracy: 0.6049543676662321
Delta: 0.0007723482298333561 	  Loss: 1.534576986118819 	 Accuracy: 0.6049543676662321
Delta: 0.0024080727329596654 	  Loss: 1.5345002445972749 	 Accuracy: 0.6036505867014341
Delta: 0.0010992922084716726 	  Loss: 1.534596731477106 	 Accuracy: 0.6036505867014341
Delta: 0.0010107331156734246 	  Loss: 1.5346003415206388 	 Accuracy: 0.6049543676662321
Delta: 0.0015673309498609672 	  Loss: 1.5346169170282278 	 Accuracy: 0.60625814863103
Delta: 0.003734677837563596 	  Loss: 1.5347106822394565 	 Accuracy: 0.6010430247718384
Delta: 0.0029944793808717556 	  Loss: 1.5348091040445158 	 Accuracy: 0.6023468057366362
Delta: 0.0014696466902056444 	  Loss: 1.5345715033746194 	 Accuracy: 0.6010430247718384
Delta: 0.020988675736555235 	  Loss: 2.1410983060806186 	 Accuracy: 0.18122555410691005
Delta: 0.018653422271367858 	  Loss: 2.06380617130279 	 Accuracy: 0.3494132985658409
Delta: 0.017275419837972088 	  Loss: 1.9236171988939144 	 Accuracy: 0.5332464146023468
Delta: 0.014298848402524154 	  Loss: 1.782734742450668 	 Accuracy: 0.546284224250326
Delta: 0.011534726749818269 	  Loss: 1.7049011224449337 	 Accuracy: 0.5319426336375489
Delta: 0.011274804797888425 	  Loss: 1.6628627207600646 	 Accuracy: 0.5176010430247718
Delta: 0.009980694139637552 	  Loss: 1.6345193137820866 	 Accuracy: 0.5097783572359843
Delta: 0.008961266887085734 	  Loss: 1.613484838183167 	 Accuracy: 0.48891786179921776
Delta: 0.009023739576079316 	  Loss: 1.5976792562006255 	 Accuracy: 0.47327249022164275
Delta: 0.007718069515378897 	  Loss: 1.585386511026249 	 Accuracy: 0.45371577574967403
Delta: 0.007661377600736404 	  Loss: 1.577254470388307 	 Accuracy: 0.4498044328552803
Delta: 0.007316561068103835 	  Loss: 1.5713249247450267 	 Accuracy: 0.43546284224250326
Delta: 0.006179871123630522 	  Loss: 1.5664870587155202 	 Accuracy: 0.4380704041720991
Delta: 0.006367751041424821 	  Loss: 1.5636680880858886 	 Accuracy: 0.43546284224250326
Delta: 0.005235215089130434 	  Loss: 1.5616029236996518 	 Accuracy: 0.43415906127770537
Delta: 0.0057059839701502565 	  Loss: 1.5602071728865847 	 Accuracy: 0.4315514993481095

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005308711435902428 	  Loss: 1.5590345505015257 	 Accuracy: 0.4302477183833116
Delta: 0.004215536349418338 	  Loss: 1.5585618837901412 	 Accuracy: 0.4302477183833116
Delta: 0.004356948494195246 	  Loss: 1.5579628052586922 	 Accuracy: 0.4302477183833116
Delta: 0.004197808304187191 	  Loss: 1.5578109813816758 	 Accuracy: 0.4302477183833116
Delta: 0.002741675808431672 	  Loss: 1.557714977991094 	 Accuracy: 0.4302477183833116
Delta: 0.0029396964192087687 	  Loss: 1.5577167455807255 	 Accuracy: 0.4302477183833116
Delta: 0.0031538559261567243 	  Loss: 1.5577304760993265 	 Accuracy: 0.4276401564537158
Delta: 0.0013134990116651936 	  Loss: 1.5576383748199183 	 Accuracy: 0.42894393741851367
Delta: 0.0025317161708260645 	  Loss: 1.5574987442746813 	 Accuracy: 0.42894393741851367
Delta: 0.002610432627096932 	  Loss: 1.5573922457112919 	 Accuracy: 0.4276401564537158
Delta: 0.001126315453182746 	  Loss: 1.5573453036874185 	 Accuracy: 0.42894393741851367
Delta: 0.001640441256632789 	  Loss: 1.5573419049881954 	 Accuracy: 0.42894393741851367
Delta: 1.4408213508443562e-05 	  Loss: 1.5573406612705782 	 Accuracy: 0.4276401564537158
Delta: 0.0016954340410279907 	  Loss: 1.5572661172663045 	 Accuracy: 0.4276401564537158
Delta: 5.572490289259527e-05 	  Loss: 1.5573499037569327 	 Accuracy: 0.4302477183833116
Delta: 0.0027706095238767357 	  Loss: 1.5572334660776166 	 Accuracy: 0.42894393741851367
Delta: 0.0006196439954650269 	  Loss: 1.5572146425213735 	 Accuracy: 0.42894393741851367
Delta: 2.0183621201695013e-05 	  Loss: 1.557228175520024 	 Accuracy: 0.42894393741851367
Delta: 0.00096151753433534 	  Loss: 1.5571928798869603 	 Accuracy: 0.4302477183833116
Delta: 2.468270010705469e-05 	  Loss: 1.5571859463138353 	 Accuracy: 0.42503259452411996
Delta: 0.0031599408855555035 	  Loss: 1.557312673372937 	 Accuracy: 0.42894393741851367
Delta: 0.0021222241618552335 	  Loss: 1.5570878792290705 	 Accuracy: 0.4302477183833116
Delta: 5.9578309503355336e-05 	  Loss: 1.5570464984495924 	 Accuracy: 0.4276401564537158
Delta: 3.347005343405194e-05 	  Loss: 1.5570558731275055 	 Accuracy: 0.4276401564537158
Delta: 4.5400626569615615e-05 	  Loss: 1.5571108696971248 	 Accuracy: 0.4276401564537158
Delta: 4.1307896421675993e-05 	  Loss: 1.5571214819924193 	 Accuracy: 0.4276401564537158
Delta: 4.3091473392141565e-05 	  Loss: 1.5570936398933497 	 Accuracy: 0.4302477183833116
Delta: 5.492495334697452e-05 	  Loss: 1.5572211818937693 	 Accuracy: 0.42894393741851367
Delta: 5.698690709644066e-05 	  Loss: 1.557083210767531 	 Accuracy: 0.4302477183833116
Delta: 2.0033824397949875e-05 	  Loss: 1.5571427228646826 	 Accuracy: 0.4302477183833116
Delta: 0.005488402688229118 	  Loss: 1.5582389389310554 	 Accuracy: 0.42894393741851367
Delta: 0.0014102457652049555 	  Loss: 1.5582218559627545 	 Accuracy: 0.4315514993481095
Delta: 0.0008391030894361464 	  Loss: 1.5582667525087561 	 Accuracy: 0.4302477183833116
Delta: 0.0028410836440779384 	  Loss: 1.55815513834613 	 Accuracy: 0.4302477183833116
Delta: 0.003511075371135879 	  Loss: 1.5580057569082357 	 Accuracy: 0.4276401564537158
Delta: 0.0016851871723200726 	  Loss: 1.5581494946817793 	 Accuracy: 0.42894393741851367
Delta: 0.0016475298793610887 	  Loss: 1.5582495641518574 	 Accuracy: 0.42894393741851367
Delta: 0.0008064472676491083 	  Loss: 1.5582588004706293 	 Accuracy: 0.42894393741851367
Delta: 4.398053521457714e-05 	  Loss: 1.5581998946160747 	 Accuracy: 0.4302477183833116
Delta: 0.0009010525566693818 	  Loss: 1.5581058474557954 	 Accuracy: 0.4302477183833116
Delta: 0.0010671882218687427 	  Loss: 1.5578953631062205 	 Accuracy: 0.4302477183833116
Delta: 0.0014820663847461143 	  Loss: 1.5577939285284212 	 Accuracy: 0.4302477183833116
Delta: 1.84598831549841e-05 	  Loss: 1.557873311191937 	 Accuracy: 0.4302477183833116
Delta: 1.6686780968865328e-05 	  Loss: 1.5578199543300237 	 Accuracy: 0.4302477183833116
Delta: 1.8488819171277062e-05 	  Loss: 1.5578991460163285 	 Accuracy: 0.4302477183833116
Delta: 1.9334953283393912e-05 	  Loss: 1.5578126658785554 	 Accuracy: 0.4315514993481095
Delta: 8.908100612490914e-06 	  Loss: 1.5578062089993443 	 Accuracy: 0.4302477183833116
Delta: 3.0665460846924504e-05 	  Loss: 1.5579791226395405 	 Accuracy: 0.42894393741851367
Delta: 4.015553225446985e-05 	  Loss: 1.55776820179028 	 Accuracy: 0.4302477183833116
Delta: 1.1861451602872325e-05 	  Loss: 1.5577997949389195 	 Accuracy: 0.4315514993481095
Delta: 8.47760452527969e-06 	  Loss: 1.557777069103285 	 Accuracy: 0.4315514993481095
Delta: 0.0024720022775288324 	  Loss: 1.5573460613146242 	 Accuracy: 0.4302477183833116
Delta: 5.085813280442655e-05 	  Loss: 1.5574249469667376 	 Accuracy: 0.42894393741851367
Delta: 0.0023031552211147037 	  Loss: 1.5575456363801516 	 Accuracy: 0.43285528031290743
Delta: 0.002802578006103726 	  Loss: 1.557807943459844 	 Accuracy: 0.4302477183833116
Delta: 0.001776791210973519 	  Loss: 1.5573665709442466 	 Accuracy: 0.4315514993481095
Delta: 5.6548493370612886e-05 	  Loss: 1.5575243028644508 	 Accuracy: 0.42894393741851367
Delta: 0.0009003734713557155 	  Loss: 1.5575204458134195 	 Accuracy: 0.42894393741851367
Delta: 0.0026825669954372447 	  Loss: 1.5577021009076875 	 Accuracy: 0.4315514993481095
Delta: 0.0015828235054856751 	  Loss: 1.5578734897866422 	 Accuracy: 0.4302477183833116
Delta: 0.002077969286633942 	  Loss: 1.5581702455766462 	 Accuracy: 0.4315514993481095
Delta: 0.0008363885829204258 	  Loss: 1.5580723351717514 	 Accuracy: 0.4302477183833116
Delta: 0.0023070026902840333 	  Loss: 1.5576607938994478 	 Accuracy: 0.42894393741851367
Delta: 0.0025197449493196025 	  Loss: 1.55804115740501 	 Accuracy: 0.4302477183833116
Delta: 0.0008228315238976641 	  Loss: 1.5581421323010036 	 Accuracy: 0.4315514993481095
Delta: 0.0027151393208947553 	  Loss: 1.558002415313323 	 Accuracy: 0.4315514993481095
Delta: 3.7293425838442284e-05 	  Loss: 1.5580624418298195 	 Accuracy: 0.4315514993481095
Delta: 0.0008199430816188361 	  Loss: 1.5584246091151273 	 Accuracy: 0.4302477183833116
Delta: 0.0010181047884493656 	  Loss: 1.5577820493201955 	 Accuracy: 0.43285528031290743
Delta: 0.0008248919551325553 	  Loss: 1.5578351418625238 	 Accuracy: 0.4315514993481095
Delta: 0.0012172474366588402 	  Loss: 1.5583907951429892 	 Accuracy: 0.4315514993481095
Delta: 0.0005794763789283619 	  Loss: 1.5582695883012683 	 Accuracy: 0.43285528031290743
Delta: 0.0014343849065157916 	  Loss: 1.5581510596457462 	 Accuracy: 0.43285528031290743
Delta: 0.00011148167093456925 	  Loss: 1.558027871357254 	 Accuracy: 0.4315514993481095
Delta: 0.0008201901835507754 	  Loss: 1.5581427301352075 	 Accuracy: 0.4302477183833116
Delta: 0.001010144196488726 	  Loss: 1.5581633149515488 	 Accuracy: 0.42894393741851367
Delta: 0.003095316930660523 	  Loss: 1.5574161335111243 	 Accuracy: 0.4315514993481095
Delta: 0.002802835383999505 	  Loss: 1.5582922646631625 	 Accuracy: 0.4315514993481095
Delta: 0.0028715690018859476 	  Loss: 1.5590442759482939 	 Accuracy: 0.4302477183833116
Delta: 3.8195956939845076e-05 	  Loss: 1.5589802716711874 	 Accuracy: 0.4302477183833116
Delta: 0.0015351467404442205 	  Loss: 1.5590905758876277 	 Accuracy: 0.42894393741851367
Delta: 0.0025659978925564224 	  Loss: 1.559094734325683 	 Accuracy: 0.42894393741851367
Delta: 0.000800471341580211 	  Loss: 1.559026496240246 	 Accuracy: 0.4302477183833116
Delta: 2.57492417243547e-05 	  Loss: 1.5591697712908412 	 Accuracy: 0.4302477183833116
Delta: 0.02094095524198223 	  Loss: 2.142552308200301 	 Accuracy: 0.20599739243807041
Delta: 0.01864845783528328 	  Loss: 2.065319702489786 	 Accuracy: 0.33116036505867014
Delta: 0.0172118140219881 	  Loss: 1.9241799316723887 	 Accuracy: 0.4211212516297262
Delta: 0.014598551847484664 	  Loss: 1.7701405794673644 	 Accuracy: 0.48239895697522817
Delta: 0.012135561834769416 	  Loss: 1.6797190621692486 	 Accuracy: 0.5215123859191656
Delta: 0.010638976594514177 	  Loss: 1.6315465495915584 	 Accuracy: 0.559322033898305
Delta: 0.00960402863029227 	  Loss: 1.6027505608796035 	 Accuracy: 0.5710560625814863
Delta: 0.008537870201630956 	  Loss: 1.5851961628123268 	 Accuracy: 0.560625814863103
Delta: 0.008084662305707972 	  Loss: 1.5741468639182745 	 Accuracy: 0.5632333767926988
Delta: 0.00721851894104081 	  Loss: 1.5674532873275124 	 Accuracy: 0.5580182529335072
Delta: 0.006595686012576456 	  Loss: 1.5630734046912023 	 Accuracy: 0.5580182529335072
Delta: 0.006244657269076 	  Loss: 1.5604098521864667 	 Accuracy: 0.5554106910039114

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006061278441792621 	  Loss: 1.5588594535005704 	 Accuracy: 0.5567144719687093
Delta: 0.005528202626099053 	  Loss: 1.5578338258539206 	 Accuracy: 0.560625814863103
Delta: 0.004018272734591745 	  Loss: 1.55740199630633 	 Accuracy: 0.559322033898305
Delta: 0.004027659170811508 	  Loss: 1.5572771739573559 	 Accuracy: 0.5554106910039114
Delta: 0.0048116267009819585 	  Loss: 1.5570294209010926 	 Accuracy: 0.5528031290743155
Delta: 0.003256211146855751 	  Loss: 1.556950799884552 	 Accuracy: 0.5554106910039114
Delta: 0.0034856554650497746 	  Loss: 1.5569692900120884 	 Accuracy: 0.5541069100391134
Delta: 0.0028737632313105537 	  Loss: 1.5570222201637238 	 Accuracy: 0.5554106910039114
Delta: 0.0032459343254152583 	  Loss: 1.5570361244785258 	 Accuracy: 0.5567144719687093
Delta: 0.003206880176207335 	  Loss: 1.5570303647524217 	 Accuracy: 0.5554106910039114
Delta: 0.002136480647217606 	  Loss: 1.5570468617888862 	 Accuracy: 0.5567144719687093
Delta: 0.0026240922900112673 	  Loss: 1.5570268352435623 	 Accuracy: 0.5567144719687093
Delta: 0.0013877127877403694 	  Loss: 1.5570096437042809 	 Accuracy: 0.5554106910039114
Delta: 0.0005062338767562873 	  Loss: 1.5570191709776213 	 Accuracy: 0.5580182529335072
Delta: 0.0006394702149687039 	  Loss: 1.5570463116862763 	 Accuracy: 0.5554106910039114
Delta: 0.001854261015774634 	  Loss: 1.557052417926573 	 Accuracy: 0.5567144719687093
Delta: 0.0007290948712063428 	  Loss: 1.5570964270430316 	 Accuracy: 0.5541069100391134
Delta: 0.00102167602686303 	  Loss: 1.5570110644980577 	 Accuracy: 0.5554106910039114
Delta: 0.0007008948574886394 	  Loss: 1.5569971277065815 	 Accuracy: 0.5554106910039114
Delta: 0.0010542689363443928 	  Loss: 1.5570377933796564 	 Accuracy: 0.5541069100391134
Delta: 0.0020708987678212717 	  Loss: 1.5570063442510995 	 Accuracy: 0.5554106910039114
Delta: 3.344096263305641e-05 	  Loss: 1.5570368757913484 	 Accuracy: 0.5528031290743155
Delta: 0.001598504913657402 	  Loss: 1.5571929874096377 	 Accuracy: 0.5567144719687093
Delta: 0.0029312311033211354 	  Loss: 1.557241076530262 	 Accuracy: 0.5567144719687093
Delta: 0.0038766159555656916 	  Loss: 1.5569222230967896 	 Accuracy: 0.5567144719687093
Delta: 0.0009037051933807197 	  Loss: 1.557065476978105 	 Accuracy: 0.5567144719687093
Delta: 0.002240036435891368 	  Loss: 1.5572513203919591 	 Accuracy: 0.5541069100391134
Delta: 0.0008146816214118696 	  Loss: 1.5572785028125897 	 Accuracy: 0.5567144719687093
Delta: 0.0017950591460922766 	  Loss: 1.5570982019844724 	 Accuracy: 0.5567144719687093
Delta: 0.0018936646419123447 	  Loss: 1.556971172551421 	 Accuracy: 0.5554106910039114
Delta: 0.001359932298395704 	  Loss: 1.5570956363706852 	 Accuracy: 0.5567144719687093
Delta: 0.0028706642038891375 	  Loss: 1.5571477529756248 	 Accuracy: 0.5567144719687093
Delta: 0.0021604139968766927 	  Loss: 1.5571841192217502 	 Accuracy: 0.5580182529335072
Delta: 0.0016160263721816236 	  Loss: 1.5574430930540009 	 Accuracy: 0.5580182529335072
Delta: 0.0023153181649145545 	  Loss: 1.5577315037784847 	 Accuracy: 0.5554106910039114
Delta: 5.9109222916449046e-05 	  Loss: 1.5573280839955461 	 Accuracy: 0.5567144719687093
Delta: 0.0033818169541310113 	  Loss: 1.5572814882157187 	 Accuracy: 0.5541069100391134
Delta: 0.0024094063210172473 	  Loss: 1.5576250716939104 	 Accuracy: 0.5554106910039114
Delta: 0.0032185972759641358 	  Loss: 1.5569221764875896 	 Accuracy: 0.5567144719687093
Delta: 0.0029427140805182448 	  Loss: 1.5568079457425863 	 Accuracy: 0.5554106910039114
Delta: 0.00150358029718731 	  Loss: 1.556168822924239 	 Accuracy: 0.5554106910039114
Delta: 0.0016444013092355649 	  Loss: 1.5564470953871232 	 Accuracy: 0.5528031290743155
Delta: 0.003183391061951193 	  Loss: 1.5571923903755396 	 Accuracy: 0.5554106910039114
Delta: 0.00344727286990899 	  Loss: 1.556145228423953 	 Accuracy: 0.5567144719687093
Delta: 0.003038244257916299 	  Loss: 1.5566927233657744 	 Accuracy: 0.5554106910039114
Delta: 0.002421105901147618 	  Loss: 1.5561713838654667 	 Accuracy: 0.5554106910039114
Delta: 0.000930763761138808 	  Loss: 1.5561611655507857 	 Accuracy: 0.5554106910039114
Delta: 0.005672017710645824 	  Loss: 1.5580460220391328 	 Accuracy: 0.5554106910039114
Delta: 0.003231906876987991 	  Loss: 1.5577755304156384 	 Accuracy: 0.5554106910039114
Delta: 0.0015000119545002127 	  Loss: 1.5576417352655678 	 Accuracy: 0.5449804432855281
Delta: 0.0024344967226266724 	  Loss: 1.5577857292217419 	 Accuracy: 0.5541069100391134
Delta: 0.0031370706586865047 	  Loss: 1.5579874721468467 	 Accuracy: 0.5541069100391134
Delta: 0.0033916150608689854 	  Loss: 1.557857283287435 	 Accuracy: 0.5541069100391134
Delta: 0.0037474596435245746 	  Loss: 1.5571528291308416 	 Accuracy: 0.5554106910039114
Delta: 0.0038683870744647113 	  Loss: 1.5564178935147601 	 Accuracy: 0.5514993481095176
Delta: 0.0013722922062368405 	  Loss: 1.5563873912971464 	 Accuracy: 0.5554106910039114
Delta: 3.686839414178595e-05 	  Loss: 1.5563218578715683 	 Accuracy: 0.5554106910039114
Delta: 0.002809850592985198 	  Loss: 1.5570442149301533 	 Accuracy: 0.5567144719687093
Delta: 0.0027479959171078827 	  Loss: 1.5565652001451604 	 Accuracy: 0.5554106910039114
Delta: 0.002342728508030373 	  Loss: 1.5572733764317863 	 Accuracy: 0.5567144719687093
Delta: 0.0037276927466449194 	  Loss: 1.5581061132629745 	 Accuracy: 0.5514993481095176
Delta: 0.0012018811162275113 	  Loss: 1.5574957992003642 	 Accuracy: 0.5514993481095176
Delta: 0.0016375836425539757 	  Loss: 1.5575354727337833 	 Accuracy: 0.5528031290743155
Delta: 0.0014936866048368507 	  Loss: 1.5580178394535595 	 Accuracy: 0.5554106910039114
Delta: 0.0012985701410956917 	  Loss: 1.5575500122019283 	 Accuracy: 0.5554106910039114
Delta: 0.0006873647492895715 	  Loss: 1.557001347154312 	 Accuracy: 0.5541069100391134
Delta: 0.0009149922419771579 	  Loss: 1.557319365326599 	 Accuracy: 0.5501955671447197
Delta: 0.0011617802423993964 	  Loss: 1.5576504464102117 	 Accuracy: 0.5541069100391134
Delta: 0.0019159160170111984 	  Loss: 1.5577067330724068 	 Accuracy: 0.5541069100391134
Delta: 0.002758833300654018 	  Loss: 1.557916630355355 	 Accuracy: 0.5528031290743155
Delta: 0.005076145492546794 	  Loss: 1.5581614301554996 	 Accuracy: 0.5501955671447197
Delta: 0.0037391705986089254 	  Loss: 1.5582393035872426 	 Accuracy: 0.5554106910039114
Delta: 0.00526999650804451 	  Loss: 1.5590180315673465 	 Accuracy: 0.5514993481095176
Delta: 0.002852677100538563 	  Loss: 1.5587392185249196 	 Accuracy: 0.5488917861799217
Delta: 0.00444664785868004 	  Loss: 1.5581876902581335 	 Accuracy: 0.5567144719687093
Delta: 0.0014001458427759662 	  Loss: 1.5581644286609184 	 Accuracy: 0.5475880052151239
Delta: 0.006163440142021662 	  Loss: 1.5608461470197785 	 Accuracy: 0.5488917861799217
Delta: 0.005547242132028786 	  Loss: 1.5582048532677564 	 Accuracy: 0.5488917861799217
Delta: 0.0017780035289581071 	  Loss: 1.55824200297914 	 Accuracy: 0.5501955671447197
Delta: 0.003273728501615886 	  Loss: 1.558351561045329 	 Accuracy: 0.5514993481095176
Delta: 0.005745827946312058 	  Loss: 1.5609280887805561 	 Accuracy: 0.560625814863103
Delta: 0.005745595408481594 	  Loss: 1.5609145496322736 	 Accuracy: 0.5501955671447197
Delta: 0.004846794107323205 	  Loss: 1.562188723213422 	 Accuracy: 0.5514993481095176
Delta: 0.003507068366258764 	  Loss: 1.5626340001529897 	 Accuracy: 0.5501955671447197
Delta: 0.004801853446508335 	  Loss: 1.5610500374160805 	 Accuracy: 0.5488917861799217
Delta: 0.003104447880281371 	  Loss: 1.5611059952476727 	 Accuracy: 0.5475880052151239
Delta: 0.002100848725219465 	  Loss: 1.5612361766927867 	 Accuracy: 0.5475880052151239
Delta: 0.002522684755083938 	  Loss: 1.5610788100272583 	 Accuracy: 0.5501955671447197
Delta: 0.020932728885579985 	  Loss: 2.1417206486709057 	 Accuracy: 0.18122555410691005
Delta: 0.018462318002820468 	  Loss: 2.0643800785397852 	 Accuracy: 0.25684485006518903
Delta: 0.0165131799841238 	  Loss: 1.938996031822939 	 Accuracy: 0.44328552803129073
Delta: 0.014749345683496586 	  Loss: 1.807226489361096 	 Accuracy: 0.47196870925684486
Delta: 0.012960499346531347 	  Loss: 1.7239980081708255 	 Accuracy: 0.4380704041720991
Delta: 0.012112585945239843 	  Loss: 1.6761923079184573 	 Accuracy: 0.42633637548891784
Delta: 0.011008134827895432 	  Loss: 1.6470045002285267 	 Accuracy: 0.41851368970013036
Delta: 0.009476432752624973 	  Loss: 1.6305243819366901 	 Accuracy: 0.42633637548891784
Delta: 0.008786136148034978 	  Loss: 1.6221150735310328 	 Accuracy: 0.4211212516297262
Delta: 0.008248747585595894 	  Loss: 1.615401074770439 	 Accuracy: 0.4198174706649283
Delta: 0.006979784008259564 	  Loss: 1.6118626950068413 	 Accuracy: 0.41851368970013036
Delta: 0.007399375649067541 	  Loss: 1.6087105983126109 	 Accuracy: 0.423728813559322

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006708580281948405 	  Loss: 1.6069433493564882 	 Accuracy: 0.4198174706649283
Delta: 0.0049917059481634635 	  Loss: 1.606075247685212 	 Accuracy: 0.423728813559322
Delta: 0.0050829911581926675 	  Loss: 1.605884178828068 	 Accuracy: 0.423728813559322
Delta: 0.002902808013059687 	  Loss: 1.6055970613523138 	 Accuracy: 0.42503259452411996
Delta: 0.0038549353853266364 	  Loss: 1.6054930603169901 	 Accuracy: 0.42503259452411996
Delta: 0.0031426301914211563 	  Loss: 1.6055934524586506 	 Accuracy: 0.42503259452411996
Delta: 0.0011069653604677233 	  Loss: 1.6057965088708648 	 Accuracy: 0.423728813559322
Delta: 0.003076275652943537 	  Loss: 1.6058092799621368 	 Accuracy: 0.42242503259452413
Delta: 0.002460823364956758 	  Loss: 1.6057179336368956 	 Accuracy: 0.42242503259452413
Delta: 0.0027276862295678036 	  Loss: 1.605627949997221 	 Accuracy: 0.42242503259452413
Delta: 0.0009009249410974721 	  Loss: 1.6057774792582071 	 Accuracy: 0.423728813559322
Delta: 4.052340268783621e-05 	  Loss: 1.6057322603853503 	 Accuracy: 0.4211212516297262
Delta: 0.0014840706462792863 	  Loss: 1.6058061419268057 	 Accuracy: 0.423728813559322
Delta: 0.0011822248079417835 	  Loss: 1.6056925571871625 	 Accuracy: 0.4211212516297262
Delta: 0.0006313356346888578 	  Loss: 1.6056608151385376 	 Accuracy: 0.423728813559322
Delta: 0.0020245319699774985 	  Loss: 1.6056184396286812 	 Accuracy: 0.423728813559322
Delta: 2.615867591532872e-05 	  Loss: 1.6055567640342798 	 Accuracy: 0.4211212516297262
Delta: 0.0026216714252198154 	  Loss: 1.60547170670601 	 Accuracy: 0.42242503259452413
Delta: 1.9140623095813837e-05 	  Loss: 1.6054443919859782 	 Accuracy: 0.4211212516297262
Delta: 3.5891832864916755e-05 	  Loss: 1.60541788213185 	 Accuracy: 0.42503259452411996
Delta: 0.004063040429694935 	  Loss: 1.6049769210238454 	 Accuracy: 0.4211212516297262
Delta: 0.00245784624772184 	  Loss: 1.605138312596428 	 Accuracy: 0.4211212516297262
Delta: 0.0024468459490880543 	  Loss: 1.6056126735149974 	 Accuracy: 0.4211212516297262
Delta: 3.6991796282149754e-05 	  Loss: 1.6055796702458607 	 Accuracy: 0.423728813559322
Delta: 3.900898133136726e-05 	  Loss: 1.605589573934746 	 Accuracy: 0.4198174706649283
Delta: 0.001456645183694554 	  Loss: 1.6054606857445146 	 Accuracy: 0.423728813559322
Delta: 0.0005540529006968688 	  Loss: 1.6052920830517192 	 Accuracy: 0.42503259452411996
Delta: 5.135989295460588e-05 	  Loss: 1.6056516802579075 	 Accuracy: 0.42242503259452413
Delta: 4.1551194430346154e-05 	  Loss: 1.6056546911619738 	 Accuracy: 0.4211212516297262
Delta: 0.0017357105407223873 	  Loss: 1.6058934302595735 	 Accuracy: 0.423728813559322
Delta: 0.0006803334129981733 	  Loss: 1.6054530281200616 	 Accuracy: 0.41851368970013036
Delta: 0.004654807832757106 	  Loss: 1.6055617375246551 	 Accuracy: 0.41851368970013036
Delta: 0.0022986839343038363 	  Loss: 1.6056472409203182 	 Accuracy: 0.4198174706649283
Delta: 0.004288963365960022 	  Loss: 1.6066258593677056 	 Accuracy: 0.4198174706649283
Delta: 0.002777654555258477 	  Loss: 1.6070266896677647 	 Accuracy: 0.4211212516297262
Delta: 0.0013172806340997203 	  Loss: 1.6067407846942572 	 Accuracy: 0.41851368970013036
Delta: 0.0016471031576228733 	  Loss: 1.607040906546072 	 Accuracy: 0.4211212516297262
Delta: 7.35456657323862e-05 	  Loss: 1.6073574462398406 	 Accuracy: 0.42242503259452413
Delta: 0.0005309294239294357 	  Loss: 1.6072619762801656 	 Accuracy: 0.42242503259452413
Delta: 0.0010103816431888534 	  Loss: 1.6074512265148848 	 Accuracy: 0.4211212516297262
Delta: 0.0005338687628682423 	  Loss: 1.607305993913682 	 Accuracy: 0.4198174706649283
Delta: 5.409930831585933e-05 	  Loss: 1.607455349396451 	 Accuracy: 0.4211212516297262
Delta: 0.0013480037831392353 	  Loss: 1.6069834803059193 	 Accuracy: 0.41851368970013036
Delta: 0.0008960626523223375 	  Loss: 1.606925117368882 	 Accuracy: 0.4198174706649283
Delta: 7.21258299631406e-05 	  Loss: 1.6073067753043202 	 Accuracy: 0.4198174706649283
Delta: 0.0010659724774885197 	  Loss: 1.607052434057152 	 Accuracy: 0.4198174706649283
Delta: 0.004172582441708713 	  Loss: 1.6063779844742885 	 Accuracy: 0.423728813559322
Delta: 0.004149009793606267 	  Loss: 1.6059732563933606 	 Accuracy: 0.4198174706649283
Delta: 0.0014889126309665327 	  Loss: 1.606339005821391 	 Accuracy: 0.4172099087353325
Delta: 0.00418036096882888 	  Loss: 1.6071698897308375 	 Accuracy: 0.4198174706649283
Delta: 0.00292891032366508 	  Loss: 1.606090843175482 	 Accuracy: 0.4198174706649283
Delta: 0.0024508599858258768 	  Loss: 1.6067780920788086 	 Accuracy: 0.4198174706649283
Delta: 0.002445199740821177 	  Loss: 1.6061455439534214 	 Accuracy: 0.41851368970013036
Delta: 5.912491149420305e-05 	  Loss: 1.6063656989604969 	 Accuracy: 0.4172099087353325
Delta: 0.0025094392623390273 	  Loss: 1.605706194731415 	 Accuracy: 0.42503259452411996
Delta: 0.0024274291784380274 	  Loss: 1.6059952593204279 	 Accuracy: 0.4198174706649283
Delta: 0.000523337631713949 	  Loss: 1.6060962882927061 	 Accuracy: 0.41851368970013036
Delta: 0.0009907179372877532 	  Loss: 1.6064641054008009 	 Accuracy: 0.4172099087353325
Delta: 0.0030557150224012008 	  Loss: 1.6075944513859324 	 Accuracy: 0.41851368970013036
Delta: 0.003408072803790892 	  Loss: 1.6077542353822638 	 Accuracy: 0.41851368970013036
Delta: 0.0014538408384607451 	  Loss: 1.607613579486642 	 Accuracy: 0.4172099087353325
Delta: 0.0007302691216711697 	  Loss: 1.607523689429828 	 Accuracy: 0.41590612777053454
Delta: 0.0019013492894884012 	  Loss: 1.6079917060480098 	 Accuracy: 0.41851368970013036
Delta: 7.047865990313119e-05 	  Loss: 1.6074934606925348 	 Accuracy: 0.4172099087353325
Delta: 4.664183617950554e-06 	  Loss: 1.6074793375697967 	 Accuracy: 0.41851368970013036
Delta: 0.0010814507854379704 	  Loss: 1.6076845021357162 	 Accuracy: 0.4172099087353325
Delta: 1.4423776592217923e-05 	  Loss: 1.6077531487426366 	 Accuracy: 0.4172099087353325
Delta: 0.0008261027909071558 	  Loss: 1.6076014005132957 	 Accuracy: 0.4172099087353325
Delta: 4.104331349483212e-05 	  Loss: 1.607429130588977 	 Accuracy: 0.4172099087353325
Delta: 0.0026999073166268286 	  Loss: 1.6072320003593947 	 Accuracy: 0.41460234680573665
Delta: 0.0022155203205581615 	  Loss: 1.6079874159444543 	 Accuracy: 0.41590612777053454
Delta: 4.7183600586078806e-05 	  Loss: 1.6077635707715572 	 Accuracy: 0.4172099087353325
Delta: 0.002003149932467561 	  Loss: 1.6072276967096841 	 Accuracy: 0.4132985658409387
Delta: 0.002693593312050449 	  Loss: 1.6079822555116619 	 Accuracy: 0.4172099087353325
Delta: 0.0009443402192329944 	  Loss: 1.6075618863705752 	 Accuracy: 0.41590612777053454
Delta: 0.0025688145424826664 	  Loss: 1.6077561943275542 	 Accuracy: 0.4172099087353325
Delta: 0.001541306675791178 	  Loss: 1.6072034631550414 	 Accuracy: 0.4172099087353325
Delta: 8.064655383954408e-06 	  Loss: 1.6072207647360575 	 Accuracy: 0.4172099087353325
Delta: 2.1463977491624855e-05 	  Loss: 1.6072386636331677 	 Accuracy: 0.4172099087353325
Delta: 0.0037138799048025447 	  Loss: 1.6077695638950544 	 Accuracy: 0.4172099087353325
Delta: 0.002829002040352492 	  Loss: 1.6072711857564683 	 Accuracy: 0.42633637548891784
Delta: 0.005227730277280699 	  Loss: 1.6077729036239785 	 Accuracy: 0.41460234680573665
Delta: 0.002895616008847993 	  Loss: 1.6080986988779444 	 Accuracy: 0.41590612777053454
Delta: 0.001506785916029877 	  Loss: 1.6075873663702924 	 Accuracy: 0.41590612777053454
Delta: 2.1559033138973688e-06 	  Loss: 1.6075826110474334 	 Accuracy: 0.4198174706649283
Delta: 0.0006038515540892172 	  Loss: 1.6075782500395963 	 Accuracy: 0.41590612777053454
Delta: 0.001827277151708513 	  Loss: 1.607933877720367 	 Accuracy: 0.4172099087353325
Delta: 0.00499987189005722 	  Loss: 1.607894121375665 	 Accuracy: 0.4132985658409387
Delta: 0.020979577208044577 	  Loss: 2.141997742352384 	 Accuracy: 0.19295958279009126
Delta: 0.01878654077788163 	  Loss: 2.0594242761686554 	 Accuracy: 0.3089960886571056
Delta: 0.01731486686048937 	  Loss: 1.9040473883938471 	 Accuracy: 0.43285528031290743
Delta: 0.015034179628684464 	  Loss: 1.7392793049442896 	 Accuracy: 0.4915254237288136
Delta: 0.012387094540032331 	  Loss: 1.6610804455703274 	 Accuracy: 0.5189048239895697
Delta: 0.011401367428431758 	  Loss: 1.624794925985122 	 Accuracy: 0.4863102998696219
Delta: 0.010480435857033812 	  Loss: 1.6024800380500173 	 Accuracy: 0.48239895697522817
Delta: 0.009334302974274657 	  Loss: 1.5889265053065185 	 Accuracy: 0.4863102998696219
Delta: 0.007927071744092984 	  Loss: 1.5806937150495721 	 Accuracy: 0.47196870925684486
Delta: 0.0071255601358504225 	  Loss: 1.5761799700511285 	 Accuracy: 0.4784876140808344

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006608331061886635 	  Loss: 1.5737247729208488 	 Accuracy: 0.4706649282920469
Delta: 0.005834352735875644 	  Loss: 1.5720016495857192 	 Accuracy: 0.4745762711864407
Delta: 0.004910706797995963 	  Loss: 1.5711392860341409 	 Accuracy: 0.48239895697522817
Delta: 0.004586663839484311 	  Loss: 1.5705075218397275 	 Accuracy: 0.4784876140808344
Delta: 0.004337066773011674 	  Loss: 1.569679591552261 	 Accuracy: 0.4758800521512386
Delta: 0.003351236263940911 	  Loss: 1.569417810491282 	 Accuracy: 0.4771838331160365
Delta: 0.003467708392416277 	  Loss: 1.5693137450383565 	 Accuracy: 0.4745762711864407
Delta: 0.001341667859198741 	  Loss: 1.5692967059756682 	 Accuracy: 0.4745762711864407
Delta: 0.001965122303726456 	  Loss: 1.5692441146797096 	 Accuracy: 0.4745762711864407
Delta: 0.0024150536079994996 	  Loss: 1.5693134948375433 	 Accuracy: 0.4745762711864407
Delta: 2.8523328063757452e-05 	  Loss: 1.5693214966451816 	 Accuracy: 0.4745762711864407
Delta: 0.0016660117226982166 	  Loss: 1.569300862816239 	 Accuracy: 0.47327249022164275
Delta: 0.0027226848672296366 	  Loss: 1.5692744079549268 	 Accuracy: 0.47196870925684486
Delta: 3.8485933838598214e-05 	  Loss: 1.569263671984219 	 Accuracy: 0.47327249022164275
Delta: 0.0006254902179911516 	  Loss: 1.5693076048929842 	 Accuracy: 0.4745762711864407
Delta: 0.0006188978225436478 	  Loss: 1.569289013263064 	 Accuracy: 0.4706649282920469
Delta: 0.001650247577731006 	  Loss: 1.5691898887753415 	 Accuracy: 0.47327249022164275
Delta: 5.23965020905089e-05 	  Loss: 1.5692362822795989 	 Accuracy: 0.47327249022164275
Delta: 0.0013404035173642602 	  Loss: 1.5692482064542093 	 Accuracy: 0.4745762711864407
Delta: 0.002382856098281448 	  Loss: 1.5692735236073165 	 Accuracy: 0.4745762711864407
Delta: 0.000631322647463117 	  Loss: 1.5692998456361034 	 Accuracy: 0.47196870925684486
Delta: 7.484633410254712e-05 	  Loss: 1.5692962124050154 	 Accuracy: 0.47327249022164275
Delta: 0.002153143349614303 	  Loss: 1.569398277951343 	 Accuracy: 0.47327249022164275
Delta: 5.962448780819207e-05 	  Loss: 1.5694742045454197 	 Accuracy: 0.4745762711864407
Delta: 5.4214817118165136e-05 	  Loss: 1.5693445116486333 	 Accuracy: 0.47327249022164275
Delta: 0.002523747029378391 	  Loss: 1.5697947024111416 	 Accuracy: 0.4745762711864407
Delta: 0.0009313791815109347 	  Loss: 1.569809559521027 	 Accuracy: 0.4758800521512386
Delta: 0.002063267733447688 	  Loss: 1.5699304772540752 	 Accuracy: 0.47196870925684486
Delta: 0.0005689563640706473 	  Loss: 1.5701556621140398 	 Accuracy: 0.4745762711864407
Delta: 0.00261060524151632 	  Loss: 1.5701984875257216 	 Accuracy: 0.47327249022164275
Delta: 8.292700212906553e-05 	  Loss: 1.5697556997139102 	 Accuracy: 0.47196870925684486
Delta: 0.00129881404589514 	  Loss: 1.5698968709238155 	 Accuracy: 0.4771838331160365
Delta: 5.636480371863611e-05 	  Loss: 1.569837494280049 	 Accuracy: 0.47327249022164275
Delta: 0.001023634797293062 	  Loss: 1.5702225692592418 	 Accuracy: 0.47327249022164275
Delta: 0.002608525470243887 	  Loss: 1.570049513227723 	 Accuracy: 0.47327249022164275
Delta: 0.001478130300031345 	  Loss: 1.569931652947905 	 Accuracy: 0.47327249022164275
Delta: 0.0005908463656907173 	  Loss: 1.569781485882347 	 Accuracy: 0.4810951760104302
Delta: 0.0007556758107277626 	  Loss: 1.5698342033859256 	 Accuracy: 0.4680573663624511
Delta: 0.0019125471202698866 	  Loss: 1.569661319263737 	 Accuracy: 0.4706649282920469
Delta: 0.003558926610273912 	  Loss: 1.5700451258609631 	 Accuracy: 0.4667535853976532
Delta: 0.0016605525944320524 	  Loss: 1.5697474816766293 	 Accuracy: 0.47196870925684486
Delta: 0.0016058132370443642 	  Loss: 1.5697558332942996 	 Accuracy: 0.46936114732724904
Delta: 0.0037672723563466157 	  Loss: 1.5699389255707579 	 Accuracy: 0.4667535853976532
Delta: 0.0015215440375238361 	  Loss: 1.569695291072963 	 Accuracy: 0.4706649282920469
Delta: 0.001241957037312487 	  Loss: 1.5701669879694649 	 Accuracy: 0.4654498044328553
Delta: 0.001285700737914248 	  Loss: 1.5705153664914084 	 Accuracy: 0.47327249022164275
Delta: 0.0016311357722717983 	  Loss: 1.5698317276555522 	 Accuracy: 0.47196870925684486
Delta: 0.0020218960762013027 	  Loss: 1.569923269166241 	 Accuracy: 0.47327249022164275
Delta: 3.406868807487541e-05 	  Loss: 1.5699798901888538 	 Accuracy: 0.47196870925684486
Delta: 0.001365475437482431 	  Loss: 1.56938014528132 	 Accuracy: 0.47196870925684486
Delta: 0.001054459462583605 	  Loss: 1.569793836262067 	 Accuracy: 0.47196870925684486
Delta: 0.0018669555372180767 	  Loss: 1.5695057364583498 	 Accuracy: 0.47196870925684486
Delta: 0.001457832447854914 	  Loss: 1.569966308819417 	 Accuracy: 0.4680573663624511
Delta: 3.339795963301004e-05 	  Loss: 1.5699499573657045 	 Accuracy: 0.47196870925684486
Delta: 0.0007801820438050045 	  Loss: 1.5699421687380086 	 Accuracy: 0.47196870925684486
Delta: 0.0032952557710796294 	  Loss: 1.5698237911374817 	 Accuracy: 0.4667535853976532
Delta: 0.0022244545038227546 	  Loss: 1.5694805047029616 	 Accuracy: 0.4706649282920469
Delta: 0.0011677078747679942 	  Loss: 1.5698223111888843 	 Accuracy: 0.4667535853976532
Delta: 8.982985394730834e-05 	  Loss: 1.5698581842539001 	 Accuracy: 0.46936114732724904
Delta: 0.0035341179971479036 	  Loss: 1.569560956749631 	 Accuracy: 0.4680573663624511
Delta: 0.002206723991330621 	  Loss: 1.569692654566702 	 Accuracy: 0.4810951760104302
Delta: 0.0011755715702428148 	  Loss: 1.5694171357143065 	 Accuracy: 0.46936114732724904
Delta: 0.001636100485457169 	  Loss: 1.5693682840718073 	 Accuracy: 0.4706649282920469
Delta: 5.040821905583666e-05 	  Loss: 1.5694162952663997 	 Accuracy: 0.4654498044328553
Delta: 3.484079492559043e-05 	  Loss: 1.569540358771821 	 Accuracy: 0.4706649282920469
Delta: 0.0021341271810060166 	  Loss: 1.5693607451277438 	 Accuracy: 0.4745762711864407
Delta: 0.0017526411786402292 	  Loss: 1.5695572463314038 	 Accuracy: 0.4641460234680574
Delta: 0.0017150999069603689 	  Loss: 1.5696728958431052 	 Accuracy: 0.4654498044328553
Delta: 0.0006569924866123629 	  Loss: 1.5695371288263769 	 Accuracy: 0.4654498044328553
Delta: 7.925233102316559e-05 	  Loss: 1.5693560833377362 	 Accuracy: 0.46936114732724904
Delta: 0.0016768831129538178 	  Loss: 1.5693270824605858 	 Accuracy: 0.4654498044328553
Delta: 0.0006337032643156069 	  Loss: 1.5694592720575233 	 Accuracy: 0.4706649282920469
Delta: 0.0016819065508054277 	  Loss: 1.5692972049534823 	 Accuracy: 0.4654498044328553
Delta: 0.003040633528321165 	  Loss: 1.5689417318791563 	 Accuracy: 0.4667535853976532
Delta: 0.002208972085323784 	  Loss: 1.5687276240369195 	 Accuracy: 0.4654498044328553
Delta: 0.004602439635546256 	  Loss: 1.5694169620799485 	 Accuracy: 0.46153846153846156
Delta: 0.006481515676149923 	  Loss: 1.5732343778262998 	 Accuracy: 0.4602346805736636
Delta: 0.004917754302594258 	  Loss: 1.5728846049469007 	 Accuracy: 0.4641460234680574
Delta: 0.00585113202804746 	  Loss: 1.5722716019870968 	 Accuracy: 0.4641460234680574
Delta: 0.004419015677519253 	  Loss: 1.5701797413663061 	 Accuracy: 0.4641460234680574
Delta: 0.0034696757190188637 	  Loss: 1.5695610512761833 	 Accuracy: 0.4667535853976532
Delta: 0.003542913521241735 	  Loss: 1.568960264816213 	 Accuracy: 0.4654498044328553
Delta: 0.0007140514701398017 	  Loss: 1.5690246373673566 	 Accuracy: 0.46284224250325945
Delta: 0.0034536793540473902 	  Loss: 1.5699984420291622 	 Accuracy: 0.4641460234680574
Delta: 0.0008527631169819354 	  Loss: 1.5702568401445407 	 Accuracy: 0.46284224250325945
Delta: 0.0016626563181101933 	  Loss: 1.570005924892766 	 Accuracy: 0.4641460234680574
Delta: 2.7669852310546998e-05 	  Loss: 1.5699041073319464 	 Accuracy: 0.4654498044328553
Delta: 3.4058591270484835e-05 	  Loss: 1.5699267250764537 	 Accuracy: 0.4706649282920469
Delta: 6.97745942688632e-05 	  Loss: 1.5702714041088424 	 Accuracy: 0.46936114732724904
Delta: 0.002180061388456509 	  Loss: 1.5705185440748366 	 Accuracy: 0.4654498044328553
Delta: 0.020988198869764742 	  Loss: 2.1419201282335054 	 Accuracy: 0.1760104302477184
Delta: 0.01810045276047213 	  Loss: 2.0620443407192948 	 Accuracy: 0.25554106910039115
Delta: 0.017158133387403192 	  Loss: 1.930811467306031 	 Accuracy: 0.41590612777053454
Delta: 0.01626772966842577 	  Loss: 1.7603817495188632 	 Accuracy: 0.39765319426336376
Delta: 0.013237982330703767 	  Loss: 1.6556029032775297 	 Accuracy: 0.38461538461538464
Delta: 0.011199574143900095 	  Loss: 1.6164637351187632 	 Accuracy: 0.3767926988265971
Delta: 0.010569062330865289 	  Loss: 1.5958081514361906 	 Accuracy: 0.36114732724902215
Delta: 0.009451031738707406 	  Loss: 1.5825757793404087 	 Accuracy: 0.35071707953063885
Delta: 0.008431656815158763 	  Loss: 1.5743845191459311 	 Accuracy: 0.3455019556714472

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006121605122904884 	  Loss: 1.5701382692108101 	 Accuracy: 0.3428943937418514
Delta: 0.0067366513666243695 	  Loss: 1.567772763507401 	 Accuracy: 0.34419817470664926
Delta: 0.004159592805484698 	  Loss: 1.56728507580564 	 Accuracy: 0.34159061277705344
Delta: 0.0034530738802509026 	  Loss: 1.5670225227438048 	 Accuracy: 0.34028683181225555
Delta: 0.004863594441080297 	  Loss: 1.566754893694059 	 Accuracy: 0.34028683181225555
Delta: 0.002770737185289003 	  Loss: 1.5666199554191858 	 Accuracy: 0.3376792698826597
Delta: 0.003149465442635645 	  Loss: 1.5665176792688897 	 Accuracy: 0.3389830508474576
Delta: 0.0005610035711948391 	  Loss: 1.5665133659134116 	 Accuracy: 0.34028683181225555
Delta: 0.0024339471304507245 	  Loss: 1.566464800623556 	 Accuracy: 0.34028683181225555
Delta: 2.044388316110148e-05 	  Loss: 1.566459265700701 	 Accuracy: 0.34159061277705344
Delta: 0.002579967411659134 	  Loss: 1.5666325482801575 	 Accuracy: 0.34028683181225555
Delta: 0.0015296554433926503 	  Loss: 1.566566719441817 	 Accuracy: 0.34028683181225555
Delta: 2.9721424180142053e-05 	  Loss: 1.566582807415362 	 Accuracy: 0.34028683181225555
Delta: 3.956274024463469e-05 	  Loss: 1.5665756372468653 	 Accuracy: 0.34159061277705344
Delta: 0.000815950099464076 	  Loss: 1.566744846470381 	 Accuracy: 0.34028683181225555
Delta: 0.002880994612350571 	  Loss: 1.5665403078256794 	 Accuracy: 0.34028683181225555
Delta: 0.0018495449632961515 	  Loss: 1.5667887358142918 	 Accuracy: 0.3389830508474576
Delta: 0.0009712302630065744 	  Loss: 1.5671147403504426 	 Accuracy: 0.3389830508474576
Delta: 0.0014806640115154338 	  Loss: 1.5669798151789012 	 Accuracy: 0.34028683181225555
Delta: 0.0006748062862894719 	  Loss: 1.5669148260733727 	 Accuracy: 0.34028683181225555
Delta: 0.001452787780243012 	  Loss: 1.5667856508044835 	 Accuracy: 0.3389830508474576
Delta: 0.0009886882643141525 	  Loss: 1.5666817650674032 	 Accuracy: 0.34028683181225555
Delta: 0.0021066892241150066 	  Loss: 1.5673122012372969 	 Accuracy: 0.34028683181225555
Delta: 0.0007705094007310632 	  Loss: 1.5667984816456708 	 Accuracy: 0.34028683181225555
Delta: 0.001757052616481427 	  Loss: 1.5666445774731652 	 Accuracy: 0.34028683181225555
Delta: 0.0016385178059032226 	  Loss: 1.5668001003571965 	 Accuracy: 0.34028683181225555
Delta: 0.0026696308871532477 	  Loss: 1.566642681263935 	 Accuracy: 0.34028683181225555
Delta: 0.002256966286350577 	  Loss: 1.5667220077758663 	 Accuracy: 0.3389830508474576
Delta: 0.0015049676361081742 	  Loss: 1.5667358218543717 	 Accuracy: 0.34028683181225555
Delta: 0.001460225289503582 	  Loss: 1.56685013311739 	 Accuracy: 0.34159061277705344
Delta: 0.0006985439987273935 	  Loss: 1.5666420096526388 	 Accuracy: 0.34028683181225555
Delta: 0.0021225487895987854 	  Loss: 1.5665272376354347 	 Accuracy: 0.34028683181225555
Delta: 0.00012415205599294993 	  Loss: 1.5667495208156301 	 Accuracy: 0.34159061277705344
Delta: 0.00010901180772855803 	  Loss: 1.5668129627741854 	 Accuracy: 0.3363754889178618
Delta: 0.00010167591864618045 	  Loss: 1.566956711069945 	 Accuracy: 0.3376792698826597
Delta: 0.0005280617524824981 	  Loss: 1.566712886629095 	 Accuracy: 0.34028683181225555
Delta: 0.0007609653325446341 	  Loss: 1.5668282484544447 	 Accuracy: 0.3363754889178618
Delta: 0.004265441738790436 	  Loss: 1.5675537219180373 	 Accuracy: 0.34028683181225555
Delta: 0.002925948109239433 	  Loss: 1.5665706273619808 	 Accuracy: 0.34028683181225555
Delta: 0.0010261483407979957 	  Loss: 1.566652474154861 	 Accuracy: 0.34028683181225555
Delta: 0.0015381947751383189 	  Loss: 1.5667779586237773 	 Accuracy: 0.34028683181225555
Delta: 0.0032215147218800757 	  Loss: 1.5666943707204457 	 Accuracy: 0.34028683181225555
Delta: 0.0011104394020096174 	  Loss: 1.5667005815594963 	 Accuracy: 0.34028683181225555
Delta: 6.98845453754336e-05 	  Loss: 1.5666200203796576 	 Accuracy: 0.3389830508474576
Delta: 0.0012393725693633654 	  Loss: 1.5668497627368518 	 Accuracy: 0.34028683181225555
Delta: 0.001488608726067386 	  Loss: 1.5667266663145467 	 Accuracy: 0.34028683181225555
Delta: 7.41387383963962e-05 	  Loss: 1.566700312077143 	 Accuracy: 0.3389830508474576
Delta: 0.003739829704018576 	  Loss: 1.5666929361119082 	 Accuracy: 0.3363754889178618
Delta: 0.0027134881581557103 	  Loss: 1.5670311800055583 	 Accuracy: 0.3389830508474576
Delta: 0.0020612227582575745 	  Loss: 1.5669316109950413 	 Accuracy: 0.3389830508474576
Delta: 0.0046770852341520485 	  Loss: 1.5669571803868358 	 Accuracy: 0.3389830508474576
Delta: 0.0038208450644238254 	  Loss: 1.5662078241136177 	 Accuracy: 0.3389830508474576
Delta: 0.0007992758437450711 	  Loss: 1.566564986469877 	 Accuracy: 0.3389830508474576
Delta: 8.666519746810742e-05 	  Loss: 1.5663200381593831 	 Accuracy: 0.3376792698826597
Delta: 0.0014846888901554926 	  Loss: 1.5665201622159235 	 Accuracy: 0.3389830508474576
Delta: 0.0013494888246318752 	  Loss: 1.566078031533249 	 Accuracy: 0.3389830508474576
Delta: 0.000840726998405312 	  Loss: 1.56633469820347 	 Accuracy: 0.3389830508474576
Delta: 0.0007755734886771751 	  Loss: 1.566601399200529 	 Accuracy: 0.34028683181225555
Delta: 9.997038286888412e-05 	  Loss: 1.5663724898529905 	 Accuracy: 0.3376792698826597
Delta: 0.0005438100923091069 	  Loss: 1.5663730157180211 	 Accuracy: 0.3389830508474576
Delta: 3.934736974333667e-05 	  Loss: 1.5663710320677064 	 Accuracy: 0.34419817470664926
Delta: 0.0022377386166194642 	  Loss: 1.5664117109882905 	 Accuracy: 0.3389830508474576
Delta: 0.00010126416687747024 	  Loss: 1.5663469755726158 	 Accuracy: 0.3389830508474576
Delta: 0.0006859745557825358 	  Loss: 1.566206942013598 	 Accuracy: 0.3389830508474576
Delta: 7.755232791557128e-05 	  Loss: 1.56613714192174 	 Accuracy: 0.3350717079530639
Delta: 8.445020640627779e-05 	  Loss: 1.5664693891018975 	 Accuracy: 0.3389830508474576
Delta: 6.85853119117777e-05 	  Loss: 1.5663590873320565 	 Accuracy: 0.3389830508474576
Delta: 6.164748411708525e-05 	  Loss: 1.566367336363038 	 Accuracy: 0.3389830508474576
Delta: 0.004030977687215641 	  Loss: 1.567261520947785 	 Accuracy: 0.34028683181225555
Delta: 0.003432356820776646 	  Loss: 1.5666665850298944 	 Accuracy: 0.3376792698826597
Delta: 0.0032700172740446694 	  Loss: 1.5666870974081675 	 Accuracy: 0.3363754889178618
Delta: 0.0024155365384410836 	  Loss: 1.5656078981910213 	 Accuracy: 0.3389830508474576
Delta: 2.3156661894723767e-05 	  Loss: 1.5655076770461083 	 Accuracy: 0.3389830508474576
Delta: 0.003487802167162064 	  Loss: 1.5649637452654095 	 Accuracy: 0.3389830508474576
Delta: 5.2793375266586144e-05 	  Loss: 1.5650600293384207 	 Accuracy: 0.3389830508474576
Delta: 6.874735371377902e-05 	  Loss: 1.5651080709672756 	 Accuracy: 0.3389830508474576
Delta: 0.004530054489534007 	  Loss: 1.5662506808755312 	 Accuracy: 0.3389830508474576
Delta: 0.002810200754030864 	  Loss: 1.5651804612045601 	 Accuracy: 0.3350717079530639
Delta: 0.0024737889095160647 	  Loss: 1.5658611244963319 	 Accuracy: 0.3389830508474576
Delta: 0.0014781362904770362 	  Loss: 1.565058835711466 	 Accuracy: 0.3389830508474576
Delta: 3.0859924072229106e-05 	  Loss: 1.5649635818331662 	 Accuracy: 0.3376792698826597
Delta: 0.0026013086301355905 	  Loss: 1.5654831049247537 	 Accuracy: 0.3389830508474576
Delta: 0.004499419689211239 	  Loss: 1.566068809443348 	 Accuracy: 0.3389830508474576
Delta: 0.0012567082230709836 	  Loss: 1.5660695662664375 	 Accuracy: 0.34028683181225555
Delta: 0.004326625487250657 	  Loss: 1.565024191642471 	 Accuracy: 0.3363754889178618
Delta: 0.002010092842991191 	  Loss: 1.5651065448354768 	 Accuracy: 0.34028683181225555
Delta: 2.685095964715826e-05 	  Loss: 1.5650604571975375 	 Accuracy: 0.3363754889178618
Delta: 0.0048744816141416455 	  Loss: 1.5662046007629158 	 Accuracy: 0.3389830508474576
Delta: 0.005234710806853445 	  Loss: 1.5650367633441467 	 Accuracy: 0.3389830508474576
Delta: 0.0025174762846053287 	  Loss: 1.5654882770516036 	 Accuracy: 0.3389830508474576
Delta: 0.0032078293777608917 	  Loss: 1.565064511975042 	 Accuracy: 0.3363754889178618
Delta: 0.021037443766929943 	  Loss: 2.1421396095902305 	 Accuracy: 0.17992177314211213
Delta: 0.018308658182311116 	  Loss: 2.0553358992866357 	 Accuracy: 0.2242503259452412
Delta: 0.016912815939062395 	  Loss: 1.9066432563350564 	 Accuracy: 0.2790091264667536
Delta: 0.015482444294174131 	  Loss: 1.7741837023680276 	 Accuracy: 0.26988265971316816
Delta: 0.013805825949784396 	  Loss: 1.7071188872900367 	 Accuracy: 0.2620599739243807
Delta: 0.012731695774750036 	  Loss: 1.669009481688182 	 Accuracy: 0.2620599739243807
Delta: 0.011286628806691078 	  Loss: 1.6425083294551608 	 Accuracy: 0.26597131681877445
Delta: 0.009654182605003243 	  Loss: 1.6272275756070402 	 Accuracy: 0.27640156453715775

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008992454777354142 	  Loss: 1.6196102931332588 	 Accuracy: 0.2711864406779661
Delta: 0.0069961961820202 	  Loss: 1.6155673932718555 	 Accuracy: 0.26988265971316816
Delta: 0.005178985509515032 	  Loss: 1.6149190635354418 	 Accuracy: 0.26988265971316816
Delta: 0.0048177187985753295 	  Loss: 1.6135037280726623 	 Accuracy: 0.2711864406779661
Delta: 0.0015340241999041038 	  Loss: 1.6134989252810252 	 Accuracy: 0.26988265971316816
Delta: 0.0035639322809917287 	  Loss: 1.6132884600867567 	 Accuracy: 0.26988265971316816
Delta: 0.002543504463249533 	  Loss: 1.6131181520560953 	 Accuracy: 0.2711864406779661
Delta: 0.003195012100324232 	  Loss: 1.6126250517343679 	 Accuracy: 0.2711864406779661
Delta: 0.001608379948482862 	  Loss: 1.6127774084814015 	 Accuracy: 0.2711864406779661
Delta: 0.0024129921808255946 	  Loss: 1.612999814320955 	 Accuracy: 0.2711864406779661
Delta: 0.0027943449676901665 	  Loss: 1.6131047571044734 	 Accuracy: 0.2711864406779661
Delta: 0.001158751542896922 	  Loss: 1.6131773320749652 	 Accuracy: 0.2711864406779661
Delta: 0.0023474922486858545 	  Loss: 1.613120840731307 	 Accuracy: 0.26988265971316816
Delta: 0.000630145082563891 	  Loss: 1.612962374382767 	 Accuracy: 0.27249022164276404
Delta: 8.033912565151059e-05 	  Loss: 1.612858610211724 	 Accuracy: 0.2711864406779661
Delta: 0.0008041936127517362 	  Loss: 1.6130472918868404 	 Accuracy: 0.26988265971316816
Delta: 0.001913020151794905 	  Loss: 1.6125164461374513 	 Accuracy: 0.2711864406779661
Delta: 0.0033861220904344703 	  Loss: 1.6131825151114134 	 Accuracy: 0.2711864406779661
Delta: 0.0027515311455073507 	  Loss: 1.61242810661498 	 Accuracy: 0.2711864406779661
Delta: 0.0014033397398406028 	  Loss: 1.612313840569296 	 Accuracy: 0.2711864406779661
Delta: 0.0022183358950114236 	  Loss: 1.6120696080298753 	 Accuracy: 0.2711864406779661
Delta: 0.0014047301462125372 	  Loss: 1.612129234963816 	 Accuracy: 0.2711864406779661
Delta: 0.002838641810287999 	  Loss: 1.6120136864399943 	 Accuracy: 0.26727509778357234
Delta: 0.0006678642610122214 	  Loss: 1.6121456996140187 	 Accuracy: 0.2711864406779661
Delta: 0.003110925105985355 	  Loss: 1.612116952781582 	 Accuracy: 0.26988265971316816
Delta: 0.0008538046725533378 	  Loss: 1.6121189278081167 	 Accuracy: 0.26727509778357234
Delta: 0.0020543564121815175 	  Loss: 1.6120237954399683 	 Accuracy: 0.2711864406779661
Delta: 0.0014207095033041618 	  Loss: 1.6121335567803432 	 Accuracy: 0.26988265971316816
Delta: 0.000601841953336803 	  Loss: 1.6119370396825659 	 Accuracy: 0.26988265971316816
Delta: 0.0005973017232976896 	  Loss: 1.6121214394643442 	 Accuracy: 0.26988265971316816
Delta: 0.0013422034228894437 	  Loss: 1.6120305510273711 	 Accuracy: 0.2711864406779661
Delta: 0.0033653253404763088 	  Loss: 1.6123214846859044 	 Accuracy: 0.2711864406779661
Delta: 0.003227004025627856 	  Loss: 1.6122926876531278 	 Accuracy: 0.26988265971316816
Delta: 0.002647676619676224 	  Loss: 1.6120120267265767 	 Accuracy: 0.27509778357235987
Delta: 0.0007894236072614672 	  Loss: 1.612431098858946 	 Accuracy: 0.2711864406779661
Delta: 0.0029955636199189783 	  Loss: 1.6123147948528156 	 Accuracy: 0.2711864406779661
Delta: 6.675559100980762e-05 	  Loss: 1.6123837704346473 	 Accuracy: 0.26988265971316816
Delta: 0.0006887809164318115 	  Loss: 1.6123940449409297 	 Accuracy: 0.26988265971316816
Delta: 0.0022643467599499597 	  Loss: 1.6128994423972247 	 Accuracy: 0.26988265971316816
Delta: 0.0019542448177060365 	  Loss: 1.6128805506919255 	 Accuracy: 0.26988265971316816
Delta: 0.002404378165412748 	  Loss: 1.6129938896786418 	 Accuracy: 0.2685788787483703
Delta: 9.156452748523144e-05 	  Loss: 1.6127550425082244 	 Accuracy: 0.2711864406779661
Delta: 0.0001049407277225598 	  Loss: 1.6129337484481705 	 Accuracy: 0.26988265971316816
Delta: 0.003317063375339852 	  Loss: 1.6129085195595372 	 Accuracy: 0.2711864406779661
Delta: 5.145196803230338e-05 	  Loss: 1.6129543258423116 	 Accuracy: 0.26988265971316816
Delta: 0.0031561894518508126 	  Loss: 1.6131651861102674 	 Accuracy: 0.26988265971316816
Delta: 0.0018580641483856492 	  Loss: 1.612808908006158 	 Accuracy: 0.26988265971316816
Delta: 0.002584642122210111 	  Loss: 1.6131770151127396 	 Accuracy: 0.26988265971316816
Delta: 2.6863624189976738e-05 	  Loss: 1.6131954403628477 	 Accuracy: 0.26988265971316816
Delta: 0.0010653162913557036 	  Loss: 1.613189515400744 	 Accuracy: 0.2711864406779661
Delta: 0.001353506993525735 	  Loss: 1.613311021293405 	 Accuracy: 0.26988265971316816
Delta: 0.0015567292005642709 	  Loss: 1.6126054452838605 	 Accuracy: 0.26988265971316816
Delta: 0.0011566444948939527 	  Loss: 1.6126986612420753 	 Accuracy: 0.2685788787483703
Delta: 7.561170591087896e-05 	  Loss: 1.6127432544070612 	 Accuracy: 0.26988265971316816
Delta: 0.0014187730078542194 	  Loss: 1.6129542421741774 	 Accuracy: 0.26988265971316816
Delta: 0.0027468047807301006 	  Loss: 1.6129285637967878 	 Accuracy: 0.26988265971316816
Delta: 6.21925486853445e-05 	  Loss: 1.612923730977921 	 Accuracy: 0.2633637548891786
Delta: 0.003921249154825572 	  Loss: 1.6125046504527158 	 Accuracy: 0.26988265971316816
Delta: 0.0028487062172321805 	  Loss: 1.612658124646286 	 Accuracy: 0.26988265971316816
Delta: 0.001007942311642414 	  Loss: 1.6126937081048425 	 Accuracy: 0.2711864406779661
Delta: 0.0016194754669943102 	  Loss: 1.6124803923995752 	 Accuracy: 0.2711864406779661
Delta: 0.0021646818412156634 	  Loss: 1.6127403110257061 	 Accuracy: 0.26727509778357234
Delta: 0.0029997405534135622 	  Loss: 1.6131046299368677 	 Accuracy: 0.2685788787483703
Delta: 0.0015438673267718975 	  Loss: 1.6127252531300225 	 Accuracy: 0.26988265971316816
Delta: 0.004663589259972129 	  Loss: 1.6124501918192773 	 Accuracy: 0.26988265971316816
Delta: 0.0008180892179306089 	  Loss: 1.6124468039840392 	 Accuracy: 0.26727509778357234
Delta: 0.003616521999132127 	  Loss: 1.6116375499189206 	 Accuracy: 0.26727509778357234
Delta: 0.0007948958900896507 	  Loss: 1.611766502652133 	 Accuracy: 0.2685788787483703
Delta: 0.0007584819466628695 	  Loss: 1.6117360351795063 	 Accuracy: 0.26727509778357234
Delta: 0.0018779621589317024 	  Loss: 1.61173501007784 	 Accuracy: 0.26988265971316816
Delta: 3.859521748511465e-05 	  Loss: 1.611726201537096 	 Accuracy: 0.26988265971316816
Delta: 9.223632332599223e-05 	  Loss: 1.611705603552812 	 Accuracy: 0.26988265971316816
Delta: 0.002234301596805489 	  Loss: 1.6122295186268794 	 Accuracy: 0.27249022164276404
Delta: 0.0020438903177656185 	  Loss: 1.6125267310541136 	 Accuracy: 0.26988265971316816
Delta: 0.0011695058613744893 	  Loss: 1.6119683133999376 	 Accuracy: 0.26988265971316816
Delta: 0.00011137538858159554 	  Loss: 1.6117921158872521 	 Accuracy: 0.26988265971316816
Delta: 2.4028847293081065e-05 	  Loss: 1.611746536433292 	 Accuracy: 0.2711864406779661
Delta: 0.0044909037459911075 	  Loss: 1.611405162334385 	 Accuracy: 0.27249022164276404
Delta: 0.003889352526797504 	  Loss: 1.6116660466318653 	 Accuracy: 0.27249022164276404
Delta: 0.001603302186431722 	  Loss: 1.611478186465316 	 Accuracy: 0.2711864406779661
Delta: 0.002108318962863106 	  Loss: 1.6114917358464809 	 Accuracy: 0.27249022164276404
Delta: 0.0037891964964727348 	  Loss: 1.611477426119453 	 Accuracy: 0.26988265971316816
Delta: 0.0021761700850620913 	  Loss: 1.611408369962752 	 Accuracy: 0.26988265971316816
Delta: 0.0009314637574955732 	  Loss: 1.611204431876515 	 Accuracy: 0.2711864406779661
Delta: 0.0007194820703908913 	  Loss: 1.6112414642566286 	 Accuracy: 0.26597131681877445
Delta: 0.0012468281563112337 	  Loss: 1.6112859764768992 	 Accuracy: 0.27509778357235987
Delta: 0.004839410424802788 	  Loss: 1.6123648276841867 	 Accuracy: 0.27509778357235987
Delta: 0.0038719770069093494 	  Loss: 1.611610901558616 	 Accuracy: 0.2685788787483703
Delta: 0.0035985693237163886 	  Loss: 1.6114639345139485 	 Accuracy: 0.2685788787483703
Delta: 0.0027325703237729743 	  Loss: 1.6109567252805022 	 Accuracy: 0.2711864406779661
Delta: 0.0028433296289987024 	  Loss: 1.6103654261531686 	 Accuracy: 0.2711864406779661
Delta: 0.0016783043251335282 	  Loss: 1.6101179896197155 	 Accuracy: 0.2711864406779661
Delta: 0.021004826279651757 	  Loss: 2.1432086038851343 	 Accuracy: 0.18122555410691005
Delta: 0.018669564441962466 	  Loss: 2.0543133819577557 	 Accuracy: 0.3050847457627119
Delta: 0.018007586801858183 	  Loss: 1.8757846053307303 	 Accuracy: 0.4498044328552803
Delta: 0.015732067117892032 	  Loss: 1.6897617414810828 	 Accuracy: 0.49674054758800523
Delta: 0.012763076143375551 	  Loss: 1.6116439220205836 	 Accuracy: 0.5410691003911343
Delta: 0.010887595361774362 	  Loss: 1.5794508281869044 	 Accuracy: 0.5710560625814863
Delta: 0.00941827819316973 	  Loss: 1.5608537206545714 	 Accuracy: 0.5814863102998696

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008417834672563183 	  Loss: 1.5495822671098314 	 Accuracy: 0.5853976531942634
Delta: 0.007103014972455647 	  Loss: 1.543289701450709 	 Accuracy: 0.5919165580182529
Delta: 0.0058436452693827355 	  Loss: 1.5407870220133715 	 Accuracy: 0.5880052151238592
Delta: 0.004430155243431844 	  Loss: 1.5399437744628663 	 Accuracy: 0.5880052151238592
Delta: 0.004591259045270253 	  Loss: 1.5398019784279156 	 Accuracy: 0.5840938722294654
Delta: 0.004035171763739368 	  Loss: 1.5396722372099552 	 Accuracy: 0.5853976531942634
Delta: 0.001440180143398736 	  Loss: 1.539395211365751 	 Accuracy: 0.5867014341590613
Delta: 0.0027828905172266366 	  Loss: 1.5395558206676 	 Accuracy: 0.5840938722294654
Delta: 0.001244362576869524 	  Loss: 1.5394834315887165 	 Accuracy: 0.5853976531942634
Delta: 0.003752364618652078 	  Loss: 1.5393724606406072 	 Accuracy: 0.5867014341590613
Delta: 0.003021623262531646 	  Loss: 1.539467735810576 	 Accuracy: 0.590612777053455
Delta: 0.00237571737822304 	  Loss: 1.5396694355723182 	 Accuracy: 0.5867014341590613
Delta: 0.0010529948931548734 	  Loss: 1.5397554488622964 	 Accuracy: 0.5867014341590613
Delta: 0.0014892560924135018 	  Loss: 1.5394397640611706 	 Accuracy: 0.5919165580182529
Delta: 0.0023115562116535816 	  Loss: 1.5397938793789114 	 Accuracy: 0.5736636245110821
Delta: 0.004318158987801883 	  Loss: 1.540250164523776 	 Accuracy: 0.5840938722294654
Delta: 0.0015269507710650842 	  Loss: 1.5403437559703614 	 Accuracy: 0.5853976531942634
Delta: 0.001139689379902083 	  Loss: 1.5404483696427875 	 Accuracy: 0.5801825293350718
Delta: 0.00308134384666614 	  Loss: 1.5408558677668358 	 Accuracy: 0.5840938722294654
Delta: 0.001204550744323967 	  Loss: 1.5405770958897862 	 Accuracy: 0.5827900912646675
Delta: 0.0021331101471284593 	  Loss: 1.5404620726582752 	 Accuracy: 0.5827900912646675
Delta: 0.001490781372680044 	  Loss: 1.5408820108797308 	 Accuracy: 0.5814863102998696
Delta: 0.0011075266876724697 	  Loss: 1.5410605746876653 	 Accuracy: 0.5827900912646675
Delta: 0.0021244081274637435 	  Loss: 1.5411824412228388 	 Accuracy: 0.5840938722294654
Delta: 0.0020247842236008 	  Loss: 1.5404717978383151 	 Accuracy: 0.5814863102998696
Delta: 0.0010332227889801927 	  Loss: 1.5409166327672414 	 Accuracy: 0.5814863102998696
Delta: 0.0007826164323156701 	  Loss: 1.5407020029788887 	 Accuracy: 0.5840938722294654
Delta: 0.0016058001480455354 	  Loss: 1.5401830419654319 	 Accuracy: 0.5788787483702738
Delta: 0.0032453237805676136 	  Loss: 1.5405613004804515 	 Accuracy: 0.5827900912646675
Delta: 0.001872794907378407 	  Loss: 1.5407399447697865 	 Accuracy: 0.5840938722294654
Delta: 0.001047127809494879 	  Loss: 1.5405187214299345 	 Accuracy: 0.5827900912646675
Delta: 0.002245235269654187 	  Loss: 1.5406737193299567 	 Accuracy: 0.5840938722294654
Delta: 0.0040967365938545264 	  Loss: 1.540398668966561 	 Accuracy: 0.5840938722294654
Delta: 0.0016272298938604197 	  Loss: 1.5405300767307488 	 Accuracy: 0.5840938722294654
Delta: 0.000939510110942591 	  Loss: 1.5406695966462962 	 Accuracy: 0.5893089960886571
Delta: 0.0037962253965788803 	  Loss: 1.539828593681285 	 Accuracy: 0.5867014341590613
Delta: 0.0030302473453726426 	  Loss: 1.5401846468974552 	 Accuracy: 0.5827900912646675
Delta: 0.0022993097032528104 	  Loss: 1.5401035742683442 	 Accuracy: 0.5814863102998696
Delta: 0.0037646757636524233 	  Loss: 1.5413113266563905 	 Accuracy: 0.5775749674054759
Delta: 0.004600348526641399 	  Loss: 1.5414882935764942 	 Accuracy: 0.5840938722294654
Delta: 0.005855688749189363 	  Loss: 1.5409812746693405 	 Accuracy: 0.5814863102998696
Delta: 0.00290920307016088 	  Loss: 1.5409338105081358 	 Accuracy: 0.5749674054758801
Delta: 0.005171974014949368 	  Loss: 1.5418554011266472 	 Accuracy: 0.5814863102998696
Delta: 0.0001288731649841913 	  Loss: 1.5407745024503483 	 Accuracy: 0.5827900912646675
Delta: 3.147130069215856e-05 	  Loss: 1.5409308616711745 	 Accuracy: 0.5827900912646675
Delta: 0.003294183995202492 	  Loss: 1.5401977405133362 	 Accuracy: 0.5840938722294654
Delta: 0.0009096868756771955 	  Loss: 1.5396336627183964 	 Accuracy: 0.5827900912646675
Delta: 0.0018421099595165092 	  Loss: 1.540223243449143 	 Accuracy: 0.5853976531942634
Delta: 0.0027768877524021376 	  Loss: 1.5391844630989375 	 Accuracy: 0.5853976531942634
Delta: 0.003414264037377477 	  Loss: 1.539941274096741 	 Accuracy: 0.5853976531942634
Delta: 0.0015618374045684139 	  Loss: 1.5391710211806187 	 Accuracy: 0.5827900912646675
Delta: 0.0016357438964716953 	  Loss: 1.5393390463048369 	 Accuracy: 0.5880052151238592
Delta: 0.0040128752128339605 	  Loss: 1.5395514572617202 	 Accuracy: 0.5932203389830508
Delta: 0.003782797937529855 	  Loss: 1.539053889816876 	 Accuracy: 0.5893089960886571
Delta: 0.0013889864316013378 	  Loss: 1.5391678112626006 	 Accuracy: 0.5880052151238592
Delta: 0.0019210639436209444 	  Loss: 1.539768126340099 	 Accuracy: 0.5893089960886571
Delta: 0.0015094097675374019 	  Loss: 1.5390525280400902 	 Accuracy: 0.5814863102998696
Delta: 0.004587708519449053 	  Loss: 1.5407230696423069 	 Accuracy: 0.5853976531942634
Delta: 0.003502941823765996 	  Loss: 1.5405014187675357 	 Accuracy: 0.5880052151238592
Delta: 0.0010310015565077899 	  Loss: 1.5407154149607174 	 Accuracy: 0.5801825293350718
Delta: 0.0035293096948282076 	  Loss: 1.54039080975026 	 Accuracy: 0.5880052151238592
Delta: 0.002821509882418338 	  Loss: 1.5409448274295694 	 Accuracy: 0.5867014341590613
Delta: 0.0011628724499642533 	  Loss: 1.5408811897893377 	 Accuracy: 0.5853976531942634
Delta: 0.002882680701834953 	  Loss: 1.5410831842848203 	 Accuracy: 0.5893089960886571
Delta: 0.0018919961270297651 	  Loss: 1.5405447611590386 	 Accuracy: 0.5867014341590613
Delta: 0.0007314887974891723 	  Loss: 1.540625417395811 	 Accuracy: 0.5867014341590613
Delta: 0.0017809368101560042 	  Loss: 1.540419045854703 	 Accuracy: 0.5880052151238592
Delta: 3.4503778496645585e-05 	  Loss: 1.5403849191875871 	 Accuracy: 0.590612777053455
Delta: 4.4088284122696665e-05 	  Loss: 1.540554821888894 	 Accuracy: 0.5893089960886571
Delta: 0.0033764327619326437 	  Loss: 1.5406044306148683 	 Accuracy: 0.5893089960886571
Delta: 0.0007239848578949531 	  Loss: 1.5406302428046026 	 Accuracy: 0.5867014341590613
Delta: 0.002426962686460616 	  Loss: 1.540526089328022 	 Accuracy: 0.5867014341590613
Delta: 0.0027466458466672574 	  Loss: 1.5401613912256193 	 Accuracy: 0.5867014341590613
Delta: 0.0031996856064119474 	  Loss: 1.5407406308282305 	 Accuracy: 0.5853976531942634
Delta: 0.0015762998990884994 	  Loss: 1.5407232707424026 	 Accuracy: 0.5945241199478487
Delta: 0.004467142095751798 	  Loss: 1.541051830786075 	 Accuracy: 0.5893089960886571
Delta: 0.0038225190183086527 	  Loss: 1.5406448715738617 	 Accuracy: 0.5827900912646675
Delta: 0.00314068315603045 	  Loss: 1.5408344068121829 	 Accuracy: 0.5840938722294654
Delta: 0.0011730822516733406 	  Loss: 1.5405636583314022 	 Accuracy: 0.5827900912646675
Delta: 0.0016423767643081377 	  Loss: 1.5413842482457425 	 Accuracy: 0.5853976531942634
Delta: 0.003828298207660158 	  Loss: 1.541754436193449 	 Accuracy: 0.5853976531942634
Delta: 0.0024071814989175457 	  Loss: 1.5406947470189591 	 Accuracy: 0.5880052151238592
Delta: 0.002876345871129988 	  Loss: 1.5398491556529568 	 Accuracy: 0.5880052151238592
Delta: 0.0038778625232713635 	  Loss: 1.5408168827098099 	 Accuracy: 0.5867014341590613
Delta: 0.002435712966415668 	  Loss: 1.5412434961429058 	 Accuracy: 0.5867014341590613
Delta: 0.0005258754026843632 	  Loss: 1.5412112356798868 	 Accuracy: 0.5880052151238592
Delta: 0.0024471535617240888 	  Loss: 1.5405591028229293 	 Accuracy: 0.5840938722294654
Delta: 0.00232757976345684 	  Loss: 1.5411805517149038 	 Accuracy: 0.590612777053455
Delta: 9.223998421254917e-05 	  Loss: 1.5409012290037856 	 Accuracy: 0.5880052151238592
Delta: 0.0008426101270955535 	  Loss: 1.5408855967172461 	 Accuracy: 0.5880052151238592
Delta: 0.00135299133523815 	  Loss: 1.5408261338045492 	 Accuracy: 0.5893089960886571
Delta: 0.001281425586494132 	  Loss: 1.5410455599958888 	 Accuracy: 0.5853976531942634
Delta: 0.005175493694162746 	  Loss: 1.5412073933822645 	 Accuracy: 0.5840938722294654
Delta: 0.020937803074173884 	  Loss: 2.1424754857254458 	 Accuracy: 0.19035202086049544
Delta: 0.018662800971974033 	  Loss: 2.0543917201990967 	 Accuracy: 0.31681877444589307
Delta: 0.01804294906116737 	  Loss: 1.8768656494096425 	 Accuracy: 0.4745762711864407
Delta: 0.01565929239790336 	  Loss: 1.709823037657375 	 Accuracy: 0.590612777053455
Delta: 0.012801480655143586 	  Loss: 1.6478577201624731 	 Accuracy: 0.6153846153846154
Delta: 0.010922671706183378 	  Loss: 1.6170416335070301 	 Accuracy: 0.6258148631029987
Delta: 0.0108171946808343 	  Loss: 1.5992151761286593 	 Accuracy: 0.6284224250325945

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009227785925161443 	  Loss: 1.5891498293814728 	 Accuracy: 0.6388526727509778
Delta: 0.007805192042319311 	  Loss: 1.5847004709945924 	 Accuracy: 0.6505867014341591
Delta: 0.005941677978168156 	  Loss: 1.5823799703212515 	 Accuracy: 0.6440677966101694
Delta: 0.004292603555825735 	  Loss: 1.581822264263013 	 Accuracy: 0.6453715775749674
Delta: 0.004083188089076975 	  Loss: 1.58165176358101 	 Accuracy: 0.6427640156453716
Delta: 0.003721152971307116 	  Loss: 1.581450019112435 	 Accuracy: 0.6427640156453716
Delta: 0.0026789456275369238 	  Loss: 1.5812644004762457 	 Accuracy: 0.6440677966101694
Delta: 0.0021311608848442235 	  Loss: 1.5813877415344746 	 Accuracy: 0.6427640156453716
Delta: 1.4091844880494187e-05 	  Loss: 1.5813460551712546 	 Accuracy: 0.6427640156453716
Delta: 0.000805474975322265 	  Loss: 1.5813669228768206 	 Accuracy: 0.6414602346805737
Delta: 2.769600594710608e-05 	  Loss: 1.581392994691516 	 Accuracy: 0.6414602346805737
Delta: 3.369426301642913e-05 	  Loss: 1.5813799331583869 	 Accuracy: 0.6427640156453716
Delta: 0.0019802122733449555 	  Loss: 1.5814512911753962 	 Accuracy: 0.6414602346805737
Delta: 0.0027059997463614403 	  Loss: 1.5821012550368243 	 Accuracy: 0.6401564537157758
Delta: 0.0014739147133440904 	  Loss: 1.5820962182762681 	 Accuracy: 0.6414602346805737
Delta: 0.0021930107419718355 	  Loss: 1.5820066590214399 	 Accuracy: 0.6427640156453716
Delta: 0.002733810367379665 	  Loss: 1.5815047911586069 	 Accuracy: 0.6414602346805737
Delta: 0.001215703480818343 	  Loss: 1.581999022485073 	 Accuracy: 0.6427640156453716
Delta: 5.4425627888836066e-05 	  Loss: 1.5818616849994354 	 Accuracy: 0.6414602346805737
Delta: 9.571035354082761e-05 	  Loss: 1.5822117344637705 	 Accuracy: 0.6414602346805737
Delta: 6.763032113853542e-05 	  Loss: 1.5818937718192303 	 Accuracy: 0.6401564537157758
Delta: 6.895522346783945e-05 	  Loss: 1.5822684576866937 	 Accuracy: 0.6401564537157758
Delta: 0.000868432286351149 	  Loss: 1.582272192180115 	 Accuracy: 0.6414602346805737
Delta: 0.0005299419483274462 	  Loss: 1.5819677933276708 	 Accuracy: 0.6414602346805737
Delta: 0.0001344640239893036 	  Loss: 1.5817494590615593 	 Accuracy: 0.6427640156453716
Delta: 0.0009616453006024896 	  Loss: 1.5815505764363882 	 Accuracy: 0.6440677966101694
Delta: 0.0007494767920831854 	  Loss: 1.5818062758912144 	 Accuracy: 0.6440677966101694
Delta: 4.6938154019042024e-05 	  Loss: 1.5815291959560123 	 Accuracy: 0.6388526727509778
Delta: 0.0016910624367238248 	  Loss: 1.5813267034920493 	 Accuracy: 0.6427640156453716
Delta: 0.0028435375509287637 	  Loss: 1.5808164402027258 	 Accuracy: 0.6440677966101694
Delta: 0.0017112785954766048 	  Loss: 1.581240583850516 	 Accuracy: 0.6466753585397653
Delta: 0.004637301421819174 	  Loss: 1.5823966646804262 	 Accuracy: 0.6414602346805737
Delta: 0.002356345548061024 	  Loss: 1.5819951552017184 	 Accuracy: 0.6401564537157758
Delta: 0.002466385819639923 	  Loss: 1.5818147042194068 	 Accuracy: 0.6414602346805737
Delta: 2.732836722503412e-05 	  Loss: 1.5817665025309844 	 Accuracy: 0.6232073011734028
Delta: 0.001055022232767511 	  Loss: 1.5817547218821901 	 Accuracy: 0.6414602346805737
Delta: 0.0024174159372902537 	  Loss: 1.5815916612362806 	 Accuracy: 0.6388526727509778
Delta: 0.0007376850978286852 	  Loss: 1.581612082664824 	 Accuracy: 0.6349413298565841
Delta: 0.0022443218901740383 	  Loss: 1.5813217958143264 	 Accuracy: 0.6401564537157758
Delta: 0.001871276043914278 	  Loss: 1.5819672896357893 	 Accuracy: 0.6414602346805737
Delta: 0.001089033202599338 	  Loss: 1.5817332035327805 	 Accuracy: 0.6414602346805737
Delta: 0.0005757869272561276 	  Loss: 1.581504643826253 	 Accuracy: 0.6401564537157758
Delta: 0.0024662061323049 	  Loss: 1.5817508180038253 	 Accuracy: 0.6427640156453716
Delta: 0.0018798458515690993 	  Loss: 1.5819711494873603 	 Accuracy: 0.6401564537157758
Delta: 0.0005537544886286939 	  Loss: 1.5821508272473621 	 Accuracy: 0.6427640156453716
Delta: 0.003716350490868803 	  Loss: 1.5809791696056616 	 Accuracy: 0.6375488917861799
Delta: 0.004220080618937223 	  Loss: 1.5819721356324545 	 Accuracy: 0.6414602346805737
Delta: 0.0012986455028764987 	  Loss: 1.5819710796173243 	 Accuracy: 0.6427640156453716
Delta: 0.0019378826493636348 	  Loss: 1.5818298579577978 	 Accuracy: 0.6297262059973925
Delta: 0.002689706411088775 	  Loss: 1.581476246981889 	 Accuracy: 0.6427640156453716
Delta: 0.0030728846493361965 	  Loss: 1.5814285348590706 	 Accuracy: 0.6401564537157758
Delta: 0.004422141327020831 	  Loss: 1.581703871656805 	 Accuracy: 0.6414602346805737
Delta: 0.0036817613461660984 	  Loss: 1.5824327949472705 	 Accuracy: 0.6440677966101694
Delta: 0.0021874423396816512 	  Loss: 1.5821193440752808 	 Accuracy: 0.6440677966101694
Delta: 0.0038492405126016233 	  Loss: 1.58139146793854 	 Accuracy: 0.6453715775749674
Delta: 0.00330781203484021 	  Loss: 1.582447143516073 	 Accuracy: 0.6427640156453716
Delta: 0.0030505549494270075 	  Loss: 1.5819486995022582 	 Accuracy: 0.6427640156453716
Delta: 0.0021548102185811584 	  Loss: 1.5817642382484383 	 Accuracy: 0.6440677966101694
Delta: 0.0025965316200474288 	  Loss: 1.5816982261051789 	 Accuracy: 0.6414602346805737
Delta: 1.4054616124787204e-05 	  Loss: 1.5817246772321636 	 Accuracy: 0.6414602346805737
Delta: 1.6276806890496355e-05 	  Loss: 1.5817450220824458 	 Accuracy: 0.6401564537157758
Delta: 0.002033619804883285 	  Loss: 1.582343639875266 	 Accuracy: 0.6427640156453716
Delta: 0.0033057709433599565 	  Loss: 1.582169426164365 	 Accuracy: 0.6440677966101694
Delta: 0.003049226936433024 	  Loss: 1.580915679375836 	 Accuracy: 0.6427640156453716
Delta: 0.0034151635278553798 	  Loss: 1.5815383300838293 	 Accuracy: 0.6427640156453716
Delta: 0.003012424080964774 	  Loss: 1.5808498841638086 	 Accuracy: 0.6401564537157758
Delta: 0.003798590430008309 	  Loss: 1.5823603965348494 	 Accuracy: 0.6388526727509778
Delta: 0.003709612708087548 	  Loss: 1.5823689502961993 	 Accuracy: 0.6414602346805737
Delta: 0.0021427754643270564 	  Loss: 1.5823298795295013 	 Accuracy: 0.6414602346805737
Delta: 0.0028905242540505564 	  Loss: 1.5823453367527978 	 Accuracy: 0.6427640156453716
Delta: 0.001896011227408517 	  Loss: 1.5826056714129546 	 Accuracy: 0.6388526727509778
Delta: 0.002185880413230933 	  Loss: 1.5826522943193448 	 Accuracy: 0.6414602346805737
Delta: 0.0034376826862911962 	  Loss: 1.5829068294481923 	 Accuracy: 0.6414602346805737
Delta: 0.002664693220867511 	  Loss: 1.5830047835806758 	 Accuracy: 0.6401564537157758
Delta: 0.003580521134597177 	  Loss: 1.5824438576683988 	 Accuracy: 0.6401564537157758
Delta: 0.0009765888086363896 	  Loss: 1.5822782958817987 	 Accuracy: 0.6388526727509778
Delta: 0.0027611590240854476 	  Loss: 1.5821798577618253 	 Accuracy: 0.6375488917861799
Delta: 0.001540826130634492 	  Loss: 1.5825496610048035 	 Accuracy: 0.6375488917861799
Delta: 6.725765067153362e-05 	  Loss: 1.5824899117153157 	 Accuracy: 0.6336375488917861
Delta: 0.003534845416971731 	  Loss: 1.5825449069123716 	 Accuracy: 0.6401564537157758
Delta: 0.0027773452435327834 	  Loss: 1.5828617752652003 	 Accuracy: 0.6401564537157758
Delta: 0.0038303841552268657 	  Loss: 1.5828936703365133 	 Accuracy: 0.6349413298565841
Delta: 0.002357052379603957 	  Loss: 1.582893523649299 	 Accuracy: 0.6375488917861799
Delta: 0.0010848565607280212 	  Loss: 1.582686859082533 	 Accuracy: 0.636245110821382
Delta: 0.0027107456917466843 	  Loss: 1.582705136941359 	 Accuracy: 0.6375488917861799
Delta: 1.7305288410385134e-05 	  Loss: 1.5827228202658348 	 Accuracy: 0.6388526727509778
Delta: 3.209118094816907e-05 	  Loss: 1.5826655380847425 	 Accuracy: 0.6388526727509778
Delta: 0.003928071182020802 	  Loss: 1.5825950445830101 	 Accuracy: 0.6388526727509778
Delta: 0.0007067017869119162 	  Loss: 1.5824639115836456 	 Accuracy: 0.6401564537157758
Delta: 0.0021693165841501125 	  Loss: 1.5824149064782547 	 Accuracy: 0.6401564537157758
Delta: 4.040823846870474e-05 	  Loss: 1.582236833144821 	 Accuracy: 0.6401564537157758
Delta: 5.207467551350766e-05 	  Loss: 1.5823791135589373 	 Accuracy: 0.6453715775749674
Delta: 0.004068224621170215 	  Loss: 1.582640331291357 	 Accuracy: 0.6414602346805737
Delta: 0.02101984516083075 	  Loss: 2.1422800597561755 	 Accuracy: 0.1864406779661017
Delta: 0.018985550553231312 	  Loss: 2.0463779200605217 	 Accuracy: 0.2737940026075619
Delta: 0.017627518414074613 	  Loss: 1.8783633954797128 	 Accuracy: 0.28552803129074317
Delta: 0.01628437975284319 	  Loss: 1.7217974140936207 	 Accuracy: 0.31029986962190353
Delta: 0.012912863469056835 	  Loss: 1.6326116427735085 	 Accuracy: 0.3194263363754889
Delta: 0.010267526829566588 	  Loss: 1.603500181109443 	 Accuracy: 0.318122555410691
Delta: 0.008425316537825439 	  Loss: 1.595079583651647 	 Accuracy: 0.31421121251629724

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0073717854297451505 	  Loss: 1.5920981024139051 	 Accuracy: 0.31421121251629724
Delta: 0.006082242095957464 	  Loss: 1.5913531812764319 	 Accuracy: 0.3089960886571056
Delta: 0.004203091942635483 	  Loss: 1.5909910941431293 	 Accuracy: 0.31029986962190353
Delta: 0.003775481955338869 	  Loss: 1.5911095173846062 	 Accuracy: 0.31029986962190353
Delta: 0.002594287211468302 	  Loss: 1.591041945752258 	 Accuracy: 0.31421121251629724
Delta: 0.002779408933758347 	  Loss: 1.5911727273095648 	 Accuracy: 0.31029986962190353
Delta: 0.001540423912142074 	  Loss: 1.591289428446311 	 Accuracy: 0.31029986962190353
Delta: 0.003047663082191579 	  Loss: 1.5912585599215248 	 Accuracy: 0.31421121251629724
Delta: 0.0010800035109282081 	  Loss: 1.5911866132125672 	 Accuracy: 0.31029986962190353
Delta: 0.0011356928142094494 	  Loss: 1.5911805895540727 	 Accuracy: 0.31029986962190353
Delta: 0.001379884060544952 	  Loss: 1.5911202621237688 	 Accuracy: 0.31290743155149936
Delta: 0.0031132220220778427 	  Loss: 1.59126243489241 	 Accuracy: 0.3116036505867014
Delta: 0.0017757121127139383 	  Loss: 1.5914189544942774 	 Accuracy: 0.31029986962190353
Delta: 0.0011817685741552426 	  Loss: 1.5914299925312863 	 Accuracy: 0.3089960886571056
Delta: 0.00223060780946907 	  Loss: 1.5912473639498828 	 Accuracy: 0.31029986962190353
Delta: 0.00116648996420666 	  Loss: 1.591581815309585 	 Accuracy: 0.31421121251629724
Delta: 0.0016954145885449744 	  Loss: 1.5919555723751777 	 Accuracy: 0.3076923076923077
Delta: 9.410806477982213e-05 	  Loss: 1.5919834611243326 	 Accuracy: 0.31421121251629724
Delta: 0.002203846511305184 	  Loss: 1.5911654126982273 	 Accuracy: 0.31029986962190353
Delta: 0.0029088212197911894 	  Loss: 1.591320712633295 	 Accuracy: 0.31421121251629724
Delta: 0.0026012476924894166 	  Loss: 1.591425032634687 	 Accuracy: 0.31029986962190353
Delta: 0.005537663689414603 	  Loss: 1.5916693318533377 	 Accuracy: 0.3116036505867014
Delta: 0.003442919638071151 	  Loss: 1.5918902441916036 	 Accuracy: 0.31029986962190353
Delta: 0.0026078444848121303 	  Loss: 1.5916277547278417 	 Accuracy: 0.3089960886571056
Delta: 0.0025982604928805894 	  Loss: 1.591304685525989 	 Accuracy: 0.3089960886571056
Delta: 0.0038715323486248916 	  Loss: 1.5908600110088646 	 Accuracy: 0.31029986962190353
Delta: 0.0031513438680328917 	  Loss: 1.5902631797554951 	 Accuracy: 0.32073011734028684
Delta: 0.0026291015869012967 	  Loss: 1.5904193577065784 	 Accuracy: 0.31029986962190353
Delta: 0.0005755957893183322 	  Loss: 1.5906622541828654 	 Accuracy: 0.31290743155149936
Delta: 0.0032378884056521785 	  Loss: 1.590541469908529 	 Accuracy: 0.3116036505867014
Delta: 0.0034791581864635633 	  Loss: 1.5907249128765972 	 Accuracy: 0.31290743155149936
Delta: 0.002963295482912596 	  Loss: 1.5906875838730499 	 Accuracy: 0.3116036505867014
Delta: 0.003580134057095636 	  Loss: 1.5903881090325616 	 Accuracy: 0.31290743155149936
Delta: 0.0012393386590857582 	  Loss: 1.590641857834615 	 Accuracy: 0.31290743155149936
Delta: 0.002898240837064053 	  Loss: 1.5903537435055028 	 Accuracy: 0.31290743155149936
Delta: 0.0011310125755798984 	  Loss: 1.590344536505766 	 Accuracy: 0.31290743155149936
Delta: 0.0014702980900741548 	  Loss: 1.5900865909681206 	 Accuracy: 0.31290743155149936
Delta: 0.0030200851385402436 	  Loss: 1.5896587934716566 	 Accuracy: 0.31290743155149936
Delta: 0.0005554881000600052 	  Loss: 1.5898593161820158 	 Accuracy: 0.31029986962190353
Delta: 0.001907444620637071 	  Loss: 1.5899664587670694 	 Accuracy: 0.31290743155149936
Delta: 0.0007894457155392671 	  Loss: 1.5893682554591408 	 Accuracy: 0.31290743155149936
Delta: 7.709091334727361e-05 	  Loss: 1.589306230563437 	 Accuracy: 0.31290743155149936
Delta: 0.0009716438006917526 	  Loss: 1.589292255934835 	 Accuracy: 0.31290743155149936
Delta: 9.629031396707042e-05 	  Loss: 1.5893100619241094 	 Accuracy: 0.31290743155149936
Delta: 3.982988803526839e-05 	  Loss: 1.589242483268231 	 Accuracy: 0.31421121251629724
Delta: 0.004386853993079289 	  Loss: 1.5901682277433014 	 Accuracy: 0.31421121251629724
Delta: 0.002646582160803321 	  Loss: 1.5897879778609774 	 Accuracy: 0.31290743155149936
Delta: 0.0027554358744002207 	  Loss: 1.5891646194954974 	 Accuracy: 0.31681877444589307
Delta: 0.002797550048217256 	  Loss: 1.5899691058154133 	 Accuracy: 0.31290743155149936
Delta: 0.0012629536751688091 	  Loss: 1.5894580795911208 	 Accuracy: 0.31421121251629724
Delta: 0.0017648408671232056 	  Loss: 1.5892356880996257 	 Accuracy: 0.31421121251629724
Delta: 0.004097376735354899 	  Loss: 1.5902230436331481 	 Accuracy: 0.31421121251629724
Delta: 0.0007517627309049114 	  Loss: 1.5900774138229736 	 Accuracy: 0.31290743155149936
Delta: 0.0013401809062426229 	  Loss: 1.5902116120953427 	 Accuracy: 0.3155149934810952
Delta: 0.0043731867107492245 	  Loss: 1.589091588071504 	 Accuracy: 0.31681877444589307
Delta: 0.0025938649825100655 	  Loss: 1.5888780863522523 	 Accuracy: 0.3155149934810952
Delta: 0.002869347817385229 	  Loss: 1.5886951778484368 	 Accuracy: 0.3155149934810952
Delta: 0.0016178386521300187 	  Loss: 1.5887528446154486 	 Accuracy: 0.3155149934810952
Delta: 0.0037482502404218576 	  Loss: 1.5887856061570003 	 Accuracy: 0.31421121251629724
Delta: 0.0010254023932090653 	  Loss: 1.5888614879799783 	 Accuracy: 0.3155149934810952
Delta: 0.0031560241022339894 	  Loss: 1.588452087823617 	 Accuracy: 0.3155149934810952
Delta: 0.0010503697804423585 	  Loss: 1.5886893086943075 	 Accuracy: 0.31681877444589307
Delta: 0.0010862773095134065 	  Loss: 1.5886819070311105 	 Accuracy: 0.318122555410691
Delta: 0.0037890877089732434 	  Loss: 1.5883045787331427 	 Accuracy: 0.31681877444589307
Delta: 0.002734687103225622 	  Loss: 1.5875627780068875 	 Accuracy: 0.31681877444589307
Delta: 0.005372066131936867 	  Loss: 1.5886354223927845 	 Accuracy: 0.31681877444589307
Delta: 0.0032545323640553003 	  Loss: 1.5896996535983166 	 Accuracy: 0.31681877444589307
Delta: 0.004665379292645293 	  Loss: 1.5894675296249232 	 Accuracy: 0.318122555410691
Delta: 0.0019511027934034024 	  Loss: 1.5891578751982398 	 Accuracy: 0.31290743155149936
Delta: 0.004633162930732864 	  Loss: 1.5902692418343882 	 Accuracy: 0.318122555410691
Delta: 0.0019541253108498937 	  Loss: 1.5898081858963822 	 Accuracy: 0.318122555410691
Delta: 0.002624082745331346 	  Loss: 1.589379828850451 	 Accuracy: 0.31681877444589307
Delta: 0.0026370158717575667 	  Loss: 1.589114621322542 	 Accuracy: 0.31681877444589307
Delta: 0.003674094073068837 	  Loss: 1.5895037571177975 	 Accuracy: 0.3155149934810952
Delta: 0.003753147404224995 	  Loss: 1.5886871598412058 	 Accuracy: 0.3155149934810952
Delta: 0.0024385161644118825 	  Loss: 1.589048082476969 	 Accuracy: 0.31290743155149936
Delta: 0.0052165851644517735 	  Loss: 1.5891476598946603 	 Accuracy: 0.31681877444589307
Delta: 0.0019115833390074878 	  Loss: 1.5900110451907845 	 Accuracy: 0.31421121251629724
Delta: 0.0037051634097672315 	  Loss: 1.588543030430223 	 Accuracy: 0.31681877444589307
Delta: 0.005566184511796848 	  Loss: 1.590725553274002 	 Accuracy: 0.31290743155149936
Delta: 5.024645887639211e-05 	  Loss: 1.590372560066132 	 Accuracy: 0.31290743155149936
Delta: 5.656237929596864e-05 	  Loss: 1.5903382390538152 	 Accuracy: 0.31421121251629724
Delta: 0.0020724926339532653 	  Loss: 1.5897387194722672 	 Accuracy: 0.31421121251629724
Delta: 0.0015356819742020239 	  Loss: 1.5901173055585938 	 Accuracy: 0.31421121251629724
Delta: 5.449506989462515e-05 	  Loss: 1.5901688697133778 	 Accuracy: 0.31290743155149936
Delta: 0.0032419094645110696 	  Loss: 1.5900754606226992 	 Accuracy: 0.31290743155149936
Delta: 0.00263183212032808 	  Loss: 1.590158495425746 	 Accuracy: 0.31421121251629724
Delta: 0.0035467246597681735 	  Loss: 1.5900326664155544 	 Accuracy: 0.31421121251629724
Delta: 0.0022540420833732687 	  Loss: 1.590383517730584 	 Accuracy: 0.31290743155149936
Delta: 0.002144640080980201 	  Loss: 1.5907988323860507 	 Accuracy: 0.31290743155149936
Delta: 0.0022380541722400536 	  Loss: 1.5903332768364686 	 Accuracy: 0.31290743155149936
Delta: 4.841179555502676e-05 	  Loss: 1.590487867150404 	 Accuracy: 0.3116036505867014
Delta: 0.002521195092202085 	  Loss: 1.5905785160764176 	 Accuracy: 0.30378096479791394
Delta: 0.021049099455237866 	  Loss: 2.14114505896566 	 Accuracy: 0.18252933507170796
Delta: 0.018959449133152347 	  Loss: 2.036367958282651 	 Accuracy: 0.35723598435462844
Delta: 0.017947235961432106 	  Loss: 1.8189892205134641 	 Accuracy: 0.4810951760104302
Delta: 0.015436294110530109 	  Loss: 1.667912836413254 	 Accuracy: 0.6010430247718384
Delta: 0.013198254589525484 	  Loss: 1.6068365723234241 	 Accuracy: 0.6075619295958279
Delta: 0.010557974331873884 	  Loss: 1.578815790292356 	 Accuracy: 0.5971316818774446

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00832281177585041 	  Loss: 1.5709765857636389 	 Accuracy: 0.6010430247718384
Delta: 0.006552866659374918 	  Loss: 1.5690355940801397 	 Accuracy: 0.5958279009126467
Delta: 0.004899723265177714 	  Loss: 1.5689741296201918 	 Accuracy: 0.5932203389830508
Delta: 0.003657845362319106 	  Loss: 1.569014601975011 	 Accuracy: 0.5984354628422425
Delta: 0.003456592228191167 	  Loss: 1.56890337498107 	 Accuracy: 0.5932203389830508
Delta: 0.002106140325450955 	  Loss: 1.568689371113897 	 Accuracy: 0.5984354628422425
Delta: 0.002961964250983626 	  Loss: 1.5682836090464078 	 Accuracy: 0.5971316818774446
Delta: 0.001370501263475828 	  Loss: 1.5684509624827059 	 Accuracy: 0.5971316818774446
Delta: 0.0013853543350764782 	  Loss: 1.5686032354061565 	 Accuracy: 0.5932203389830508
Delta: 0.002780733323519393 	  Loss: 1.569026258634584 	 Accuracy: 0.5971316818774446
Delta: 0.0015061405777772236 	  Loss: 1.569309486901933 	 Accuracy: 0.5971316818774446
Delta: 0.0016992643263407453 	  Loss: 1.56943083506404 	 Accuracy: 0.5919165580182529
Delta: 7.180167273291817e-05 	  Loss: 1.5692542122545783 	 Accuracy: 0.6075619295958279
Delta: 0.003855104602662869 	  Loss: 1.5699136024823934 	 Accuracy: 0.5932203389830508
Delta: 0.0017096333217635712 	  Loss: 1.5700436471089465 	 Accuracy: 0.5971316818774446
Delta: 0.0016512520345157245 	  Loss: 1.5694972216680156 	 Accuracy: 0.5997392438070405
Delta: 0.0054429631257453875 	  Loss: 1.568396569014617 	 Accuracy: 0.5932203389830508
Delta: 0.001548283291749602 	  Loss: 1.5686785896035167 	 Accuracy: 0.5984354628422425
Delta: 0.0026423539536797607 	  Loss: 1.5690742504301651 	 Accuracy: 0.5958279009126467
Delta: 0.000803083728289662 	  Loss: 1.5688249613672651 	 Accuracy: 0.5880052151238592
Delta: 0.005160090448166798 	  Loss: 1.569622862756436 	 Accuracy: 0.5997392438070405
Delta: 0.003273079364973922 	  Loss: 1.5695842410766043 	 Accuracy: 0.5997392438070405
Delta: 0.0015452942175060394 	  Loss: 1.5694609349290753 	 Accuracy: 0.5958279009126467
Delta: 0.0031946726210208857 	  Loss: 1.569953877927652 	 Accuracy: 0.5984354628422425
Delta: 0.001626651864243233 	  Loss: 1.569735778547061 	 Accuracy: 0.5984354628422425
Delta: 0.004070454846668424 	  Loss: 1.5701425949688221 	 Accuracy: 0.5984354628422425
Delta: 0.0010025558496658932 	  Loss: 1.5704254739166021 	 Accuracy: 0.5880052151238592
Delta: 0.003309058759274802 	  Loss: 1.5721168007277253 	 Accuracy: 0.5932203389830508
Delta: 0.0025385334524099597 	  Loss: 1.5719444023523406 	 Accuracy: 0.5958279009126467
Delta: 0.0010348668154348919 	  Loss: 1.5721845204178364 	 Accuracy: 0.5971316818774446
Delta: 0.0005118980701937004 	  Loss: 1.572188472520708 	 Accuracy: 0.5971316818774446
Delta: 2.330520430307983e-05 	  Loss: 1.5721983360404497 	 Accuracy: 0.5971316818774446
Delta: 1.4356399131676268e-05 	  Loss: 1.5721453581795792 	 Accuracy: 0.5932203389830508
Delta: 1.5497965281027657e-05 	  Loss: 1.5722203267463624 	 Accuracy: 0.5932203389830508
Delta: 0.0011545636736127313 	  Loss: 1.5723078307052638 	 Accuracy: 0.5984354628422425
Delta: 0.00288112470253396 	  Loss: 1.57099566741195 	 Accuracy: 0.5945241199478487
Delta: 0.0014534793295284097 	  Loss: 1.5701888675465183 	 Accuracy: 0.5971316818774446
Delta: 0.0020826407584322807 	  Loss: 1.5702691248488185 	 Accuracy: 0.5984354628422425
Delta: 0.0016459616635806375 	  Loss: 1.5700942276864873 	 Accuracy: 0.5997392438070405
Delta: 5.622471613516318e-05 	  Loss: 1.5703531998269844 	 Accuracy: 0.5932203389830508
Delta: 0.0016960894579025937 	  Loss: 1.5701811637457368 	 Accuracy: 0.5984354628422425
Delta: 0.004305535838774218 	  Loss: 1.5698631823519418 	 Accuracy: 0.5971316818774446
Delta: 0.003783741004130975 	  Loss: 1.5694256367851513 	 Accuracy: 0.5971316818774446
Delta: 0.0036145824829630093 	  Loss: 1.5698035778204025 	 Accuracy: 0.590612777053455
Delta: 0.001845159064926265 	  Loss: 1.570143095354633 	 Accuracy: 0.5971316818774446
Delta: 0.0031270684548177154 	  Loss: 1.5715590786176472 	 Accuracy: 0.5984354628422425
Delta: 0.00278914565366614 	  Loss: 1.5715871218280815 	 Accuracy: 0.5971316818774446
Delta: 0.0014517361664891076 	  Loss: 1.572131712249909 	 Accuracy: 0.5984354628422425
Delta: 0.0023550862491048953 	  Loss: 1.5723186680135801 	 Accuracy: 0.5984354628422425
Delta: 0.004477453398448036 	  Loss: 1.5730288995357828 	 Accuracy: 0.5984354628422425
Delta: 0.0018948441392986819 	  Loss: 1.5727579744784652 	 Accuracy: 0.5971316818774446
Delta: 6.826948916455029e-05 	  Loss: 1.5730032077360823 	 Accuracy: 0.5932203389830508
Delta: 0.0035492561012325017 	  Loss: 1.5737214346929642 	 Accuracy: 0.5997392438070405
Delta: 0.00402002671608601 	  Loss: 1.572672468294916 	 Accuracy: 0.5971316818774446
Delta: 0.00260813125361138 	  Loss: 1.5727796702743624 	 Accuracy: 0.5945241199478487
Delta: 0.0025743836678058948 	  Loss: 1.5741606062469962 	 Accuracy: 0.5958279009126467
Delta: 6.349406246664585e-05 	  Loss: 1.5737101691961821 	 Accuracy: 0.5971316818774446
Delta: 0.004319623426305032 	  Loss: 1.5737770669301976 	 Accuracy: 0.5945241199478487
Delta: 0.001215420063929415 	  Loss: 1.5737686804383522 	 Accuracy: 0.5919165580182529
Delta: 0.004636830976358277 	  Loss: 1.5746820833794648 	 Accuracy: 0.5984354628422425
Delta: 0.00440557343028994 	  Loss: 1.5744152167624401 	 Accuracy: 0.5932203389830508
Delta: 0.0017593828998279108 	  Loss: 1.5744191941863679 	 Accuracy: 0.5971316818774446
Delta: 0.0009709968605238638 	  Loss: 1.5743209983835977 	 Accuracy: 0.5945241199478487
Delta: 0.0023062466344849165 	  Loss: 1.5736887913385291 	 Accuracy: 0.5984354628422425
Delta: 0.0012294264779237566 	  Loss: 1.5743225825107834 	 Accuracy: 0.5958279009126467
Delta: 0.0027468158879793113 	  Loss: 1.5734692174532616 	 Accuracy: 0.5945241199478487
Delta: 0.0006660255433497575 	  Loss: 1.5737197476009523 	 Accuracy: 0.5958279009126467
Delta: 0.0012201326131996973 	  Loss: 1.5734086048807567 	 Accuracy: 0.5932203389830508
Delta: 0.003135015683418341 	  Loss: 1.5747785333982858 	 Accuracy: 0.5893089960886571
Delta: 0.002374567224847319 	  Loss: 1.5741227177007262 	 Accuracy: 0.5971316818774446
Delta: 0.004073402124689109 	  Loss: 1.574355282449127 	 Accuracy: 0.5932203389830508
Delta: 0.003697709435050054 	  Loss: 1.5744153840161714 	 Accuracy: 0.5932203389830508
Delta: 0.002530659897049426 	  Loss: 1.574565842215082 	 Accuracy: 0.5932203389830508
Delta: 0.0038402385933016593 	  Loss: 1.5743592498526748 	 Accuracy: 0.5945241199478487
Delta: 0.004894167957755399 	  Loss: 1.5742031694894645 	 Accuracy: 0.60625814863103
Delta: 0.0035630406220761943 	  Loss: 1.572947985440833 	 Accuracy: 0.5958279009126467
Delta: 0.0038213666508441196 	  Loss: 1.5703952706812208 	 Accuracy: 0.5984354628422425
Delta: 0.00537644081503655 	  Loss: 1.5690499580503352 	 Accuracy: 0.5958279009126467
Delta: 0.001055241017959411 	  Loss: 1.569458568866844 	 Accuracy: 0.5958279009126467
Delta: 0.0035314062604207253 	  Loss: 1.5702434021170908 	 Accuracy: 0.5893089960886571
Delta: 0.0045675596488170996 	  Loss: 1.5703761517601524 	 Accuracy: 0.5997392438070405
Delta: 0.00204205953206611 	  Loss: 1.5701649826467927 	 Accuracy: 0.5984354628422425
Delta: 1.9246703369110902e-05 	  Loss: 1.5702180280530451 	 Accuracy: 0.5984354628422425
Delta: 0.003800799884208262 	  Loss: 1.5703849754942987 	 Accuracy: 0.5945241199478487
Delta: 0.005066687487928486 	  Loss: 1.5717183727792834 	 Accuracy: 0.5958279009126467
Delta: 0.0036866509938050865 	  Loss: 1.572261587727264 	 Accuracy: 0.5958279009126467
Delta: 0.0031252606325522085 	  Loss: 1.5707768284015788 	 Accuracy: 0.5932203389830508
Delta: 0.005852540212965615 	  Loss: 1.5731275103179208 	 Accuracy: 0.5971316818774446
Delta: 0.0037909017316164547 	  Loss: 1.5716152400259467 	 Accuracy: 0.5958279009126467
Delta: 0.005098939407906487 	  Loss: 1.571678980982767 	 Accuracy: 0.590612777053455
Delta: 0.004890017824101546 	  Loss: 1.5724151217100957 	 Accuracy: 0.5919165580182529
Delta: 0.004777702256617959 	  Loss: 1.5738896798037192 	 Accuracy: 0.5919165580182529
Delta: 0.003662060948694817 	  Loss: 1.5734828103997873 	 Accuracy: 0.5840938722294654
Delta: 0.00414726407984833 	  Loss: 1.573916309761784 	 Accuracy: 0.5893089960886571
Delta: 0.020963807867884817 	  Loss: 2.142562345875621 	 Accuracy: 0.1864406779661017
Delta: 0.018714772735630932 	  Loss: 2.0480427919300856 	 Accuracy: 0.30247718383311606
Delta: 0.018300323878353907 	  Loss: 1.8620621582094867 	 Accuracy: 0.41199478487614083
Delta: 0.016363970084774564 	  Loss: 1.6897724079142697 	 Accuracy: 0.4067796610169492
Delta: 0.013238994429201758 	  Loss: 1.6256597752183752 	 Accuracy: 0.4276401564537158
Delta: 0.011626115577370975 	  Loss: 1.5954561865478167 	 Accuracy: 0.42503259452411996

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009411193843039232 	  Loss: 1.5804069263646747 	 Accuracy: 0.42894393741851367
Delta: 0.006524981405388742 	  Loss: 1.5762263223253745 	 Accuracy: 0.423728813559322
Delta: 0.005801160698775367 	  Loss: 1.574720010122234 	 Accuracy: 0.41851368970013036
Delta: 0.003888021124411502 	  Loss: 1.574257831113353 	 Accuracy: 0.41851368970013036
Delta: 0.0036315976082015597 	  Loss: 1.5744148927808315 	 Accuracy: 0.41851368970013036
Delta: 0.002224407558857843 	  Loss: 1.5742269222199257 	 Accuracy: 0.4172099087353325
Delta: 0.0010681684481207458 	  Loss: 1.5741229437569952 	 Accuracy: 0.41590612777053454
Delta: 0.004222377940639088 	  Loss: 1.573793179080266 	 Accuracy: 0.41590612777053454
Delta: 0.0030563329913343954 	  Loss: 1.5740698042776122 	 Accuracy: 0.4172099087353325
Delta: 0.0007405081312152047 	  Loss: 1.5739358794161569 	 Accuracy: 0.4172099087353325
Delta: 5.48820922664782e-05 	  Loss: 1.573951856108586 	 Accuracy: 0.41460234680573665
Delta: 0.001233588720694439 	  Loss: 1.5743104523527534 	 Accuracy: 0.4172099087353325
Delta: 0.0012432464445720206 	  Loss: 1.5738354216552801 	 Accuracy: 0.4172099087353325
Delta: 0.003069081616917419 	  Loss: 1.5735995539589265 	 Accuracy: 0.4172099087353325
Delta: 0.0020156204860453625 	  Loss: 1.5733779810036563 	 Accuracy: 0.41199478487614083
Delta: 0.0015499598970521407 	  Loss: 1.5734509015236298 	 Accuracy: 0.41460234680573665
Delta: 0.0027561477920641196 	  Loss: 1.5743156617256582 	 Accuracy: 0.41590612777053454
Delta: 0.005164326594536788 	  Loss: 1.5748691883842962 	 Accuracy: 0.41590612777053454
Delta: 0.0038050335225784764 	  Loss: 1.5749718992563955 	 Accuracy: 0.41590612777053454
Delta: 0.0032023099423361375 	  Loss: 1.575875185808011 	 Accuracy: 0.41590612777053454
Delta: 0.0036209330784047855 	  Loss: 1.5762418212658895 	 Accuracy: 0.41590612777053454
Delta: 0.002317419929392115 	  Loss: 1.5758269852075697 	 Accuracy: 0.41590612777053454
Delta: 0.00240455908410175 	  Loss: 1.576072683277008 	 Accuracy: 0.41590612777053454
Delta: 0.0012319849435552686 	  Loss: 1.5761203566319328 	 Accuracy: 0.41590612777053454
Delta: 0.0018407285403747716 	  Loss: 1.5753703887348944 	 Accuracy: 0.41851368970013036
Delta: 0.00319855615527216 	  Loss: 1.5755471208499885 	 Accuracy: 0.41460234680573665
Delta: 0.001168398513616066 	  Loss: 1.575327615104198 	 Accuracy: 0.41460234680573665
Delta: 0.0039104094704207415 	  Loss: 1.5747179571592884 	 Accuracy: 0.41460234680573665
Delta: 0.002260343251299324 	  Loss: 1.5747847370066097 	 Accuracy: 0.41460234680573665
Delta: 0.0029891354551983607 	  Loss: 1.5746792228991233 	 Accuracy: 0.41590612777053454
Delta: 0.002717978211325372 	  Loss: 1.5748585797528234 	 Accuracy: 0.41460234680573665
Delta: 0.002560337368043053 	  Loss: 1.5746583014765907 	 Accuracy: 0.41460234680573665
Delta: 0.003044600058403148 	  Loss: 1.574645081469858 	 Accuracy: 0.41460234680573665
Delta: 0.002432843449176796 	  Loss: 1.5742003640157183 	 Accuracy: 0.41590612777053454
Delta: 0.002553310906348439 	  Loss: 1.5746334976367047 	 Accuracy: 0.41460234680573665
Delta: 0.0006764098577114385 	  Loss: 1.5747085500636575 	 Accuracy: 0.41590612777053454
Delta: 0.0015649772023080485 	  Loss: 1.5744713344134413 	 Accuracy: 0.41460234680573665
Delta: 0.0032086910907998347 	  Loss: 1.5745125801888729 	 Accuracy: 0.41590612777053454
Delta: 7.127109439770125e-05 	  Loss: 1.5744179324997463 	 Accuracy: 0.41590612777053454
Delta: 0.0012161583782896988 	  Loss: 1.5744870645454834 	 Accuracy: 0.41590612777053454
Delta: 0.0023619238820172827 	  Loss: 1.5746531075761698 	 Accuracy: 0.409387222946545
Delta: 0.0012847126288548863 	  Loss: 1.574640515883683 	 Accuracy: 0.41460234680573665
Delta: 9.395759819352704e-05 	  Loss: 1.57484946709163 	 Accuracy: 0.4172099087353325
Delta: 0.003355934167287145 	  Loss: 1.5751330896085185 	 Accuracy: 0.41590612777053454
Delta: 0.00010935936833881326 	  Loss: 1.5748652578010907 	 Accuracy: 0.41460234680573665
Delta: 9.465315824207e-05 	  Loss: 1.5751649502172707 	 Accuracy: 0.41590612777053454
Delta: 0.0001020863300286327 	  Loss: 1.5750213550713164 	 Accuracy: 0.41460234680573665
Delta: 0.0010479956382880788 	  Loss: 1.5750083670907729 	 Accuracy: 0.4172099087353325
Delta: 0.0015815093777919987 	  Loss: 1.5747399637068646 	 Accuracy: 0.41590612777053454
Delta: 0.001580805073533068 	  Loss: 1.5753777211496676 	 Accuracy: 0.41199478487614083
Delta: 0.0005949512061876785 	  Loss: 1.575073715971237 	 Accuracy: 0.41590612777053454
Delta: 0.0006808775248870668 	  Loss: 1.5750459453075418 	 Accuracy: 0.41460234680573665
Delta: 7.456290851765052e-05 	  Loss: 1.5750444509976171 	 Accuracy: 0.40808344198174706
Delta: 7.51735421853181e-05 	  Loss: 1.5754468869773 	 Accuracy: 0.41199478487614083
Delta: 0.0011860758771097709 	  Loss: 1.575115680127444 	 Accuracy: 0.41590612777053454
Delta: 4.225792907811537e-05 	  Loss: 1.5750718055187183 	 Accuracy: 0.41460234680573665
Delta: 0.0005904089523125473 	  Loss: 1.574871237537023 	 Accuracy: 0.41590612777053454
Delta: 0.0005500552234255288 	  Loss: 1.5749692261259338 	 Accuracy: 0.4106910039113429
Delta: 8.329711276220337e-05 	  Loss: 1.5751412193273695 	 Accuracy: 0.4172099087353325
Delta: 0.0031343947844591925 	  Loss: 1.5748719041689316 	 Accuracy: 0.41590612777053454
Delta: 8.626521661996451e-05 	  Loss: 1.5750314818480344 	 Accuracy: 0.41590612777053454
Delta: 0.003926147805799723 	  Loss: 1.5734062564335876 	 Accuracy: 0.41590612777053454
Delta: 0.0010163276353409912 	  Loss: 1.5738624012031268 	 Accuracy: 0.4132985658409387
Delta: 0.0016031637960056363 	  Loss: 1.5731092043769999 	 Accuracy: 0.41460234680573665
Delta: 0.0018182399227426762 	  Loss: 1.5736331625850632 	 Accuracy: 0.41590612777053454
Delta: 0.002338312622375884 	  Loss: 1.5751625755359746 	 Accuracy: 0.41590612777053454
Delta: 0.0027160037227822605 	  Loss: 1.5745796190083123 	 Accuracy: 0.41590612777053454
Delta: 0.0012049132932472578 	  Loss: 1.5752166477284733 	 Accuracy: 0.41460234680573665
Delta: 0.0027379667477064936 	  Loss: 1.5748544510780533 	 Accuracy: 0.41590612777053454
Delta: 0.0033724848028184465 	  Loss: 1.5749976332690245 	 Accuracy: 0.4198174706649283
Delta: 0.0037075835301780802 	  Loss: 1.5734295063069565 	 Accuracy: 0.4172099087353325
Delta: 9.619912145915302e-05 	  Loss: 1.5734658316386072 	 Accuracy: 0.4172099087353325
Delta: 0.00016353497077769243 	  Loss: 1.57395798298023 	 Accuracy: 0.4172099087353325
Delta: 0.0034237577523298698 	  Loss: 1.5739679632025032 	 Accuracy: 0.41851368970013036
Delta: 0.00263459124356323 	  Loss: 1.5757697754172808 	 Accuracy: 0.41590612777053454
Delta: 0.0017772701076999744 	  Loss: 1.5751813520467852 	 Accuracy: 0.41590612777053454
Delta: 0.0011446842682069375 	  Loss: 1.5749199524952928 	 Accuracy: 0.4172099087353325
Delta: 0.00011641327162148644 	  Loss: 1.5758134429436372 	 Accuracy: 0.4198174706649283
Delta: 0.004225491101940898 	  Loss: 1.5758438188249435 	 Accuracy: 0.41851368970013036
Delta: 0.004139554695690396 	  Loss: 1.5756874278948474 	 Accuracy: 0.41590612777053454
Delta: 0.004448979184505023 	  Loss: 1.5760193085373437 	 Accuracy: 0.41590612777053454
Delta: 0.004838417063550368 	  Loss: 1.5759779679483379 	 Accuracy: 0.41460234680573665
Delta: 0.0034297057646499665 	  Loss: 1.576375579699445 	 Accuracy: 0.4198174706649283
Delta: 0.0030043221461835733 	  Loss: 1.5757151547622565 	 Accuracy: 0.42242503259452413
Delta: 0.0026722279942732684 	  Loss: 1.5756706243809155 	 Accuracy: 0.41851368970013036
Delta: 0.003325955555094624 	  Loss: 1.576214971592171 	 Accuracy: 0.41590612777053454
Delta: 0.0036644600202243955 	  Loss: 1.5764041445965151 	 Accuracy: 0.40808344198174706
Delta: 0.005412356165808268 	  Loss: 1.579429787849627 	 Accuracy: 0.4172099087353325
Delta: 0.005006534686140753 	  Loss: 1.5755736489046215 	 Accuracy: 0.41851368970013036
Delta: 0.0036875874661662237 	  Loss: 1.574596924089862 	 Accuracy: 0.41851368970013036
Delta: 0.002430498213005939 	  Loss: 1.574583209649215 	 Accuracy: 0.41851368970013036
Delta: 0.0007390894376026942 	  Loss: 1.5744550534870703 	 Accuracy: 0.41590612777053454
Delta: 0.0038705007218311086 	  Loss: 1.5751555226034184 	 Accuracy: 0.41851368970013036
Delta: 0.0026395228378706744 	  Loss: 1.5746732840408348 	 Accuracy: 0.41851368970013036
Delta: 0.02107324102417502 	  Loss: 2.141714061320406 	 Accuracy: 0.19035202086049544
Delta: 0.018419376116331987 	  Loss: 2.040763730961399 	 Accuracy: 0.26597131681877445
Delta: 0.017916797378047345 	  Loss: 1.8648223852864254 	 Accuracy: 0.36114732724902215
Delta: 0.01634649805804091 	  Loss: 1.7115668217741837 	 Accuracy: 0.35853976531942633
Delta: 0.013586304785672451 	  Loss: 1.6397611628494444 	 Accuracy: 0.3520208604954368
Delta: 0.01066168260792743 	  Loss: 1.6139542796142203 	 Accuracy: 0.3376792698826597

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007530677743100248 	  Loss: 1.6060020492211922 	 Accuracy: 0.3428943937418514
Delta: 0.006565570180270338 	  Loss: 1.6040314356216525 	 Accuracy: 0.34028683181225555
Delta: 0.004372478005051393 	  Loss: 1.6035785172117714 	 Accuracy: 0.3428943937418514
Delta: 0.0032783655875031144 	  Loss: 1.6036151805833023 	 Accuracy: 0.34419817470664926
Delta: 0.0032479839994503895 	  Loss: 1.6037205344735477 	 Accuracy: 0.3455019556714472
Delta: 0.0005947804089547896 	  Loss: 1.6034920425293844 	 Accuracy: 0.3428943937418514
Delta: 0.003165767791741984 	  Loss: 1.6037052501117248 	 Accuracy: 0.33376792698826596
Delta: 0.00389067019408041 	  Loss: 1.6040574847206743 	 Accuracy: 0.3376792698826597
Delta: 0.003449067417815185 	  Loss: 1.6039946074748888 	 Accuracy: 0.34159061277705344
Delta: 0.0005581721976752736 	  Loss: 1.6038251895010758 	 Accuracy: 0.34159061277705344
Delta: 0.001311456358833477 	  Loss: 1.6033850292431355 	 Accuracy: 0.34028683181225555
Delta: 0.001112598211764815 	  Loss: 1.6037361028837473 	 Accuracy: 0.34159061277705344
Delta: 0.0023320912154358065 	  Loss: 1.6035138567286307 	 Accuracy: 0.34159061277705344
Delta: 0.0021380291561112694 	  Loss: 1.6032889979686695 	 Accuracy: 0.34159061277705344
Delta: 0.0006516915275394767 	  Loss: 1.6036084557261936 	 Accuracy: 0.34159061277705344
Delta: 0.001504735123921473 	  Loss: 1.6034819921547205 	 Accuracy: 0.34028683181225555
Delta: 0.0005586780319306171 	  Loss: 1.6037903860878648 	 Accuracy: 0.34159061277705344
Delta: 0.002340056873564506 	  Loss: 1.6028712487008772 	 Accuracy: 0.34159061277705344
Delta: 0.0015787330814294174 	  Loss: 1.603125187122781 	 Accuracy: 0.34159061277705344
Delta: 0.004565630682026001 	  Loss: 1.6026363459933768 	 Accuracy: 0.34159061277705344
Delta: 0.004470428961316416 	  Loss: 1.6022875705953192 	 Accuracy: 0.34159061277705344
Delta: 0.0005365658536144133 	  Loss: 1.6022901091229778 	 Accuracy: 0.3350717079530639
Delta: 0.006991526965799588 	  Loss: 1.6047298450366994 	 Accuracy: 0.3376792698826597
Delta: 0.006492326270627852 	  Loss: 1.6032754292625206 	 Accuracy: 0.3350717079530639
Delta: 0.0031226952031897254 	  Loss: 1.603044161534092 	 Accuracy: 0.3350717079530639
Delta: 0.002445074323519807 	  Loss: 1.6032988073795575 	 Accuracy: 0.3363754889178618
Delta: 0.0026531460565380667 	  Loss: 1.6036502772537846 	 Accuracy: 0.3350717079530639
Delta: 5.5810699532207235e-05 	  Loss: 1.6034797869749955 	 Accuracy: 0.3350717079530639
Delta: 0.0015504403675461118 	  Loss: 1.603326441685354 	 Accuracy: 0.3350717079530639
Delta: 0.001671398447070748 	  Loss: 1.6031878599189935 	 Accuracy: 0.34028683181225555
Delta: 0.0013929947115581716 	  Loss: 1.6033466752547418 	 Accuracy: 0.33376792698826596
Delta: 0.003645215390290019 	  Loss: 1.6036270703818254 	 Accuracy: 0.3350717079530639
Delta: 0.0023593938852863277 	  Loss: 1.6035720770779744 	 Accuracy: 0.33376792698826596
Delta: 0.0017580519279454267 	  Loss: 1.6039741157257874 	 Accuracy: 0.3350717079530639
Delta: 0.001466934647575138 	  Loss: 1.6036909549017366 	 Accuracy: 0.3350717079530639
Delta: 0.0020027276768755983 	  Loss: 1.6033646781529933 	 Accuracy: 0.3324641460234681
Delta: 0.0033752905400409212 	  Loss: 1.6043894884708272 	 Accuracy: 0.33376792698826596
Delta: 0.002594087339047913 	  Loss: 1.6039782602919817 	 Accuracy: 0.33376792698826596
Delta: 0.0014755591435986052 	  Loss: 1.6043173644504736 	 Accuracy: 0.33376792698826596
Delta: 0.0022378642419741968 	  Loss: 1.604005475481886 	 Accuracy: 0.3324641460234681
Delta: 0.001680266297812663 	  Loss: 1.6037298670478586 	 Accuracy: 0.3324641460234681
Delta: 0.0030014638974817207 	  Loss: 1.6034940303052716 	 Accuracy: 0.3324641460234681
Delta: 0.0006233097338994154 	  Loss: 1.6035618614377096 	 Accuracy: 0.3324641460234681
Delta: 0.002202279801100394 	  Loss: 1.6037939215133863 	 Accuracy: 0.3324641460234681
Delta: 0.003818593991947375 	  Loss: 1.6039812135445533 	 Accuracy: 0.3324641460234681
Delta: 0.0027144185593561583 	  Loss: 1.603963887152577 	 Accuracy: 0.3324641460234681
Delta: 3.1487013961884415e-05 	  Loss: 1.6038451523457966 	 Accuracy: 0.33376792698826596
Delta: 0.003563632232003354 	  Loss: 1.6033570773183259 	 Accuracy: 0.3324641460234681
Delta: 0.0022004946394542117 	  Loss: 1.6031998583831564 	 Accuracy: 0.33116036505867014
Delta: 0.004889996433975238 	  Loss: 1.6050615520170717 	 Accuracy: 0.33116036505867014
Delta: 0.0028658281661779576 	  Loss: 1.6051428111344128 	 Accuracy: 0.33116036505867014
Delta: 0.0022038828421922217 	  Loss: 1.6048068929444745 	 Accuracy: 0.32985658409387225
Delta: 0.00431986063952873 	  Loss: 1.605422564936529 	 Accuracy: 0.32985658409387225
Delta: 0.0035157617159771353 	  Loss: 1.604410873472868 	 Accuracy: 0.32985658409387225
Delta: 0.0025086025899946768 	  Loss: 1.6035928923122333 	 Accuracy: 0.32985658409387225
Delta: 0.0009781437134854562 	  Loss: 1.604159809843791 	 Accuracy: 0.33116036505867014
Delta: 0.005521202204126178 	  Loss: 1.6043964154957955 	 Accuracy: 0.33116036505867014
Delta: 0.002986575825378074 	  Loss: 1.6040215101759185 	 Accuracy: 0.33116036505867014
Delta: 0.0035448713846006103 	  Loss: 1.603080274096205 	 Accuracy: 0.33116036505867014
Delta: 0.001132850567062645 	  Loss: 1.6031364532273313 	 Accuracy: 0.33116036505867014
Delta: 0.0013358865962418871 	  Loss: 1.6028442671522403 	 Accuracy: 0.33116036505867014
Delta: 0.0014902137645320323 	  Loss: 1.602679924746711 	 Accuracy: 0.3259452411994785
Delta: 0.0019058748115485399 	  Loss: 1.6026355030186021 	 Accuracy: 0.33116036505867014
Delta: 0.0016116834806886656 	  Loss: 1.602876935497505 	 Accuracy: 0.3285528031290743
Delta: 8.398482540689859e-05 	  Loss: 1.6026625997033435 	 Accuracy: 0.33116036505867014
Delta: 8.457243294664967e-05 	  Loss: 1.6028611258295915 	 Accuracy: 0.33116036505867014
Delta: 0.00010673843669604436 	  Loss: 1.6026488662591962 	 Accuracy: 0.33116036505867014
Delta: 2.924882200569954e-05 	  Loss: 1.6027674860902739 	 Accuracy: 0.33116036505867014
Delta: 0.003826207352641671 	  Loss: 1.6023901040387412 	 Accuracy: 0.32985658409387225
Delta: 0.004358162095896912 	  Loss: 1.6028393339771194 	 Accuracy: 0.32985658409387225
Delta: 0.0008851389587608992 	  Loss: 1.602968177139426 	 Accuracy: 0.32985658409387225
Delta: 0.002434041874912948 	  Loss: 1.6029863677345635 	 Accuracy: 0.32985658409387225
Delta: 0.0028141134829074545 	  Loss: 1.6030850753091772 	 Accuracy: 0.3259452411994785
Delta: 0.002081333432827253 	  Loss: 1.6029447578877067 	 Accuracy: 0.32985658409387225
Delta: 0.0006526009778097044 	  Loss: 1.6029581174435 	 Accuracy: 0.32985658409387225
Delta: 0.0024055172227898233 	  Loss: 1.6031316428957318 	 Accuracy: 0.32985658409387225
Delta: 0.0021935096405038533 	  Loss: 1.60292720195859 	 Accuracy: 0.3285528031290743
Delta: 0.004096634039936237 	  Loss: 1.6025758166677067 	 Accuracy: 0.33116036505867014
Delta: 0.0023572345585793925 	  Loss: 1.6027185818795062 	 Accuracy: 0.32985658409387225
Delta: 0.004237799455888084 	  Loss: 1.6021778219906686 	 Accuracy: 0.33116036505867014
Delta: 0.0025422540486440357 	  Loss: 1.6024353036691659 	 Accuracy: 0.3324641460234681
Delta: 0.0015835397542190183 	  Loss: 1.6023534918784101 	 Accuracy: 0.33116036505867014
Delta: 0.0016539738718358277 	  Loss: 1.6026842215587482 	 Accuracy: 0.33116036505867014
Delta: 0.0025584803586101313 	  Loss: 1.6020523324800757 	 Accuracy: 0.3324641460234681
Delta: 0.003005218130184807 	  Loss: 1.6027567859508332 	 Accuracy: 0.33116036505867014
Delta: 0.0008889223391007841 	  Loss: 1.6031694429227756 	 Accuracy: 0.32985658409387225
Delta: 3.950884180227574e-05 	  Loss: 1.603313697463809 	 Accuracy: 0.33116036505867014
Delta: 0.003398231608252053 	  Loss: 1.602781156876382 	 Accuracy: 0.32333767926988266
Delta: 0.003943263325280795 	  Loss: 1.6033845018924542 	 Accuracy: 0.32985658409387225
Delta: 0.0013796433273848695 	  Loss: 1.6032640008703518 	 Accuracy: 0.32985658409387225
Delta: 0.0036246578484977303 	  Loss: 1.6023918714366643 	 Accuracy: 0.32985658409387225
Delta: 0.0005241485759939838 	  Loss: 1.6023788243493786 	 Accuracy: 0.3285528031290743
Delta: 0.003605625420904042 	  Loss: 1.6032898334585584 	 Accuracy: 0.32985658409387225
Delta: 0.0022564871280171114 	  Loss: 1.6031748969432214 	 Accuracy: 0.32985658409387225
Delta: 0.02095188827764215 	  Loss: 2.1424290739605096 	 Accuracy: 0.19426336375488917
Delta: 0.018965476315132537 	  Loss: 2.041138148210692 	 Accuracy: 0.32333767926988266
Delta: 0.017875211798541225 	  Loss: 1.863063943549749 	 Accuracy: 0.4132985658409387
Delta: 0.017104403095762687 	  Loss: 1.7014936761498816 	 Accuracy: 0.42894393741851367
Delta: 0.014126184110791662 	  Loss: 1.6286660858814517 	 Accuracy: 0.4315514993481095
Delta: 0.010897637659300996 	  Loss: 1.6062081575169715 	 Accuracy: 0.42894393741851367

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007517151548972522 	  Loss: 1.601769554782543 	 Accuracy: 0.42633637548891784
Delta: 0.006496575468369612 	  Loss: 1.6007286406337782 	 Accuracy: 0.42633637548891784
Delta: 0.005562162982777249 	  Loss: 1.6000422142827357 	 Accuracy: 0.423728813559322
Delta: 0.004424472703913978 	  Loss: 1.5992612807082671 	 Accuracy: 0.42503259452411996
Delta: 0.002985391544699328 	  Loss: 1.5986763347039203 	 Accuracy: 0.42503259452411996
Delta: 0.0022455210381684882 	  Loss: 1.5989743088701625 	 Accuracy: 0.423728813559322
Delta: 0.0038168188098907686 	  Loss: 1.59873333027124 	 Accuracy: 0.42633637548891784
Delta: 0.0015332328117272798 	  Loss: 1.5988150314743304 	 Accuracy: 0.42503259452411996
Delta: 0.0018625176179296423 	  Loss: 1.5993343669425955 	 Accuracy: 0.42503259452411996
Delta: 0.0037216477310083275 	  Loss: 1.6003038573276602 	 Accuracy: 0.42503259452411996
Delta: 0.002104227373755526 	  Loss: 1.5998230742913297 	 Accuracy: 0.42503259452411996
Delta: 0.0006682125435534922 	  Loss: 1.5999886809233101 	 Accuracy: 0.42503259452411996
Delta: 0.0009131662035832081 	  Loss: 1.600171825095754 	 Accuracy: 0.42503259452411996
Delta: 0.0021528124773130676 	  Loss: 1.5987387832046491 	 Accuracy: 0.42503259452411996
Delta: 4.292361353342364e-05 	  Loss: 1.5990871566009748 	 Accuracy: 0.42633637548891784
Delta: 0.0009998977216642958 	  Loss: 1.5994549463435537 	 Accuracy: 0.42503259452411996
Delta: 3.7836245611079e-05 	  Loss: 1.599259196020101 	 Accuracy: 0.42503259452411996
Delta: 0.0024139161199713093 	  Loss: 1.5996703006178246 	 Accuracy: 0.423728813559322
Delta: 0.0037809552881022225 	  Loss: 1.5992539718627543 	 Accuracy: 0.42503259452411996
Delta: 0.0012063106605278982 	  Loss: 1.598810426109004 	 Accuracy: 0.42503259452411996
Delta: 0.0008523793532229201 	  Loss: 1.5982196975053036 	 Accuracy: 0.4211212516297262
Delta: 0.0031415986903748643 	  Loss: 1.5984123038313593 	 Accuracy: 0.42503259452411996
Delta: 0.0005258165579038352 	  Loss: 1.5984702595910107 	 Accuracy: 0.42503259452411996
Delta: 0.0025781203610056 	  Loss: 1.5994709182712166 	 Accuracy: 0.42503259452411996
Delta: 4.295348801810416e-05 	  Loss: 1.599584038131253 	 Accuracy: 0.42503259452411996
Delta: 0.0019336065715855576 	  Loss: 1.6002556081981756 	 Accuracy: 0.42503259452411996
Delta: 0.0013415890612933955 	  Loss: 1.5994840808879707 	 Accuracy: 0.42503259452411996
Delta: 0.001708164338588397 	  Loss: 1.6001593069474853 	 Accuracy: 0.42633637548891784
Delta: 0.001190201823043936 	  Loss: 1.5993688211025219 	 Accuracy: 0.42633637548891784
Delta: 0.0024433914529317386 	  Loss: 1.5990499924124004 	 Accuracy: 0.42633637548891784
Delta: 0.004011009583480158 	  Loss: 1.598042052086782 	 Accuracy: 0.4498044328552803
Delta: 0.0021834046608265505 	  Loss: 1.597837125127901 	 Accuracy: 0.4276401564537158
Delta: 0.0036268813843839073 	  Loss: 1.5978793384761039 	 Accuracy: 0.4276401564537158
Delta: 0.0018922190560513653 	  Loss: 1.597301007370894 	 Accuracy: 0.42633637548891784
Delta: 0.0021596939998465136 	  Loss: 1.597351037613353 	 Accuracy: 0.42503259452411996
Delta: 0.0013121573896747872 	  Loss: 1.597674560494736 	 Accuracy: 0.4302477183833116
Delta: 0.004287119140796067 	  Loss: 1.598797207524885 	 Accuracy: 0.42503259452411996
Delta: 0.0019403400829027413 	  Loss: 1.598505305296595 	 Accuracy: 0.42503259452411996
Delta: 1.9247050820074593e-05 	  Loss: 1.5985259127016582 	 Accuracy: 0.4276401564537158
Delta: 0.0034629637358962713 	  Loss: 1.5987808457217383 	 Accuracy: 0.42633637548891784
Delta: 0.0013810510163977708 	  Loss: 1.5988484288017237 	 Accuracy: 0.42503259452411996
Delta: 0.0023018272304549687 	  Loss: 1.5984507322695491 	 Accuracy: 0.423728813559322
Delta: 0.000917633496368505 	  Loss: 1.5983386349720807 	 Accuracy: 0.42242503259452413
Delta: 0.0015089941983015866 	  Loss: 1.5984687070081218 	 Accuracy: 0.42242503259452413
Delta: 0.0010923912884093015 	  Loss: 1.5983500592643902 	 Accuracy: 0.42503259452411996
Delta: 0.0010938206886608945 	  Loss: 1.5980965410280694 	 Accuracy: 0.423728813559322
Delta: 0.0009320688778819375 	  Loss: 1.598149482345856 	 Accuracy: 0.4198174706649283
Delta: 0.0040827532534896405 	  Loss: 1.59800274925399 	 Accuracy: 0.423728813559322
Delta: 0.0038189443907216338 	  Loss: 1.5981059134319717 	 Accuracy: 0.42242503259452413
Delta: 0.002893560098011306 	  Loss: 1.5984080787661439 	 Accuracy: 0.42242503259452413
Delta: 8.135546101508544e-05 	  Loss: 1.5980844890632846 	 Accuracy: 0.423728813559322
Delta: 4.34133099657891e-06 	  Loss: 1.5980849473274776 	 Accuracy: 0.423728813559322
Delta: 0.0005737382579163583 	  Loss: 1.5978907496411305 	 Accuracy: 0.423728813559322
Delta: 0.0016971409166596518 	  Loss: 1.597836515529783 	 Accuracy: 0.423728813559322
Delta: 0.001765571933239235 	  Loss: 1.5978245547168997 	 Accuracy: 0.423728813559322
Delta: 0.001289993872773852 	  Loss: 1.597738078656334 	 Accuracy: 0.42242503259452413
Delta: 0.0027500913337782326 	  Loss: 1.5973687876746963 	 Accuracy: 0.4198174706649283
Delta: 0.003560354630781773 	  Loss: 1.5974023038365779 	 Accuracy: 0.42242503259452413
Delta: 0.002146194143204637 	  Loss: 1.597097826129538 	 Accuracy: 0.42242503259452413
Delta: 0.0029368529459432736 	  Loss: 1.5970485958138858 	 Accuracy: 0.4211212516297262
Delta: 0.0014187148240539656 	  Loss: 1.5970173370334195 	 Accuracy: 0.423728813559322
Delta: 0.002006554778675971 	  Loss: 1.597086207557835 	 Accuracy: 0.42242503259452413
Delta: 0.0038107380493544772 	  Loss: 1.5983432439428518 	 Accuracy: 0.423728813559322
Delta: 0.0038131161937555724 	  Loss: 1.5965635864683674 	 Accuracy: 0.423728813559322
Delta: 0.0036301409237274648 	  Loss: 1.5978942918855434 	 Accuracy: 0.42503259452411996
Delta: 1.1399310782742667e-05 	  Loss: 1.597873071793225 	 Accuracy: 0.423728813559322
Delta: 0.0005712793686670345 	  Loss: 1.597829185861794 	 Accuracy: 0.423728813559322
Delta: 0.0020619273987799855 	  Loss: 1.5971908237763284 	 Accuracy: 0.423728813559322
Delta: 0.0019189723298264519 	  Loss: 1.597430050325158 	 Accuracy: 0.423728813559322
Delta: 0.002078229201270325 	  Loss: 1.5976911661115474 	 Accuracy: 0.42242503259452413
Delta: 0.0018465026123105181 	  Loss: 1.5978314628274561 	 Accuracy: 0.423728813559322
Delta: 0.000773002175098399 	  Loss: 1.597758824810745 	 Accuracy: 0.423728813559322
Delta: 0.0017888976806125423 	  Loss: 1.5977213136095751 	 Accuracy: 0.42503259452411996
Delta: 0.0007608497919852635 	  Loss: 1.5978759221154872 	 Accuracy: 0.423728813559322
Delta: 0.00010255415324243115 	  Loss: 1.5977643121780174 	 Accuracy: 0.42633637548891784
Delta: 0.0019442832298347 	  Loss: 1.5977031215967124 	 Accuracy: 0.42242503259452413
Delta: 0.002618561716161188 	  Loss: 1.5969966265225095 	 Accuracy: 0.42242503259452413
Delta: 0.0010612430628245367 	  Loss: 1.5970470618264505 	 Accuracy: 0.4067796610169492
Delta: 3.525261307381201e-05 	  Loss: 1.597299136702254 	 Accuracy: 0.42242503259452413
Delta: 0.001726129066352376 	  Loss: 1.5970553098856874 	 Accuracy: 0.41460234680573665
Delta: 0.004583372673499447 	  Loss: 1.5988870034527962 	 Accuracy: 0.4172099087353325
Delta: 0.0035995756931543467 	  Loss: 1.5990110282150372 	 Accuracy: 0.41851368970013036
Delta: 0.002476342638126624 	  Loss: 1.5992346966862219 	 Accuracy: 0.4198174706649283
Delta: 0.003203176128348996 	  Loss: 1.5979303590362117 	 Accuracy: 0.423728813559322
Delta: 0.004202059837405079 	  Loss: 1.5973323492603577 	 Accuracy: 0.41199478487614083
Delta: 0.0038628461610913274 	  Loss: 1.59827562213454 	 Accuracy: 0.4198174706649283
Delta: 0.0017467181057768356 	  Loss: 1.5981865521898877 	 Accuracy: 0.4198174706649283
Delta: 0.0012433775653344396 	  Loss: 1.5979511333103562 	 Accuracy: 0.4198174706649283
Delta: 6.0480944992219517e-05 	  Loss: 1.5980749459541557 	 Accuracy: 0.4198174706649283
Delta: 0.0018881423121805962 	  Loss: 1.597871348915716 	 Accuracy: 0.4198174706649283
Delta: 0.0037199877600491713 	  Loss: 1.59889797020141 	 Accuracy: 0.42242503259452413
Delta: 0.0040631007358892055 	  Loss: 1.5971893364305538 	 Accuracy: 0.4211212516297262
Delta: 0.0030195133735377226 	  Loss: 1.597264046076553 	 Accuracy: 0.4211212516297262
Delta: 0.0010046905288661275 	  Loss: 1.5971565416768465 	 Accuracy: 0.4211212516297262
Delta: 0.02101637234762962 	  Loss: 2.1414872531676727 	 Accuracy: 0.20078226857887874
Delta: 0.018993095926851302 	  Loss: 2.031652397871368 	 Accuracy: 0.34419817470664926
Delta: 0.017712342476149126 	  Loss: 1.8563140030875809 	 Accuracy: 0.39504563233376794
Delta: 0.016018788688887578 	  Loss: 1.7233097706356575 	 Accuracy: 0.3924380704041721
Delta: 0.01288680963675654 	  Loss: 1.6679212868883706 	 Accuracy: 0.38070404172099087
Delta: 0.010499835416020368 	  Loss: 1.649534497656448 	 Accuracy: 0.3650586701434159

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009489806066522373 	  Loss: 1.6425300096195867 	 Accuracy: 0.35723598435462844
Delta: 0.007638377449224047 	  Loss: 1.6400575799428496 	 Accuracy: 0.35071707953063885
Delta: 0.005672985826323992 	  Loss: 1.638907879787388 	 Accuracy: 0.3455019556714472
Delta: 0.005159802412835604 	  Loss: 1.638194519145586 	 Accuracy: 0.3455019556714472
Delta: 0.004318442534314841 	  Loss: 1.6380654349663175 	 Accuracy: 0.3468057366362451
Delta: 0.004322710279258869 	  Loss: 1.6376823453301008 	 Accuracy: 0.3468057366362451
Delta: 0.002959460487778329 	  Loss: 1.6377086084462147 	 Accuracy: 0.34810951760104303
Delta: 0.002324022983543798 	  Loss: 1.6377824715727929 	 Accuracy: 0.3494132985658409
Delta: 0.0028120745928621486 	  Loss: 1.63777782766411 	 Accuracy: 0.3494132985658409
Delta: 0.0015930735231358118 	  Loss: 1.6378403186770303 	 Accuracy: 0.35723598435462844
Delta: 0.00507935279881517 	  Loss: 1.637543350782666 	 Accuracy: 0.34810951760104303
Delta: 0.0034400691742670643 	  Loss: 1.63689923627093 	 Accuracy: 0.34810951760104303
Delta: 0.0030784994790232045 	  Loss: 1.6372036942768888 	 Accuracy: 0.34810951760104303
Delta: 0.0035969650257833916 	  Loss: 1.6378322256612519 	 Accuracy: 0.34810951760104303
Delta: 0.001534315287726942 	  Loss: 1.6375840022417862 	 Accuracy: 0.34810951760104303
Delta: 0.003624407992910259 	  Loss: 1.6376789385593318 	 Accuracy: 0.3468057366362451
Delta: 0.002929657353090883 	  Loss: 1.6375048121080045 	 Accuracy: 0.3468057366362451
Delta: 0.0028133575643556888 	  Loss: 1.6375299584491743 	 Accuracy: 0.34810951760104303
Delta: 0.0024048447352479985 	  Loss: 1.6376309309412953 	 Accuracy: 0.34810951760104303
Delta: 0.0026162822622630604 	  Loss: 1.6377101756332104 	 Accuracy: 0.34810951760104303
Delta: 0.002098960975116831 	  Loss: 1.6374397693261789 	 Accuracy: 0.3468057366362451
Delta: 0.002048265109814203 	  Loss: 1.6373928565770361 	 Accuracy: 0.3468057366362451
Delta: 0.0011188115805818152 	  Loss: 1.6376754786104843 	 Accuracy: 0.34419817470664926
Delta: 6.591882352920056e-05 	  Loss: 1.6377910736246193 	 Accuracy: 0.3468057366362451
Delta: 9.564218601355432e-05 	  Loss: 1.637574247860857 	 Accuracy: 0.3455019556714472
Delta: 0.001643971333606727 	  Loss: 1.637498761377445 	 Accuracy: 0.34419817470664926
Delta: 0.0025445488383361793 	  Loss: 1.637866824210143 	 Accuracy: 0.3468057366362451
Delta: 8.702593824147888e-05 	  Loss: 1.6376496111618022 	 Accuracy: 0.3468057366362451
Delta: 9.760350877957731e-05 	  Loss: 1.637490327603436 	 Accuracy: 0.3468057366362451
Delta: 0.0037296140305375343 	  Loss: 1.6374499727085916 	 Accuracy: 0.3455019556714472
Delta: 0.002974166660967543 	  Loss: 1.6372555642882267 	 Accuracy: 0.3455019556714472
Delta: 0.001896698091452315 	  Loss: 1.6374674209995237 	 Accuracy: 0.3468057366362451
Delta: 0.0040807798678420696 	  Loss: 1.6373604289374368 	 Accuracy: 0.34810951760104303
Delta: 0.002758908446197421 	  Loss: 1.6375637285421063 	 Accuracy: 0.3468057366362451
Delta: 0.002967562318011596 	  Loss: 1.6378858447305222 	 Accuracy: 0.3468057366362451
Delta: 0.002720559114251544 	  Loss: 1.6379539150826383 	 Accuracy: 0.34159061277705344
Delta: 0.00353716897718036 	  Loss: 1.6391988303267429 	 Accuracy: 0.3468057366362451
Delta: 0.0040715784332441525 	  Loss: 1.639068552643776 	 Accuracy: 0.3468057366362451
Delta: 0.0020737199325973673 	  Loss: 1.639652783672128 	 Accuracy: 0.35723598435462844
Delta: 0.0014405718605517127 	  Loss: 1.6395353937444683 	 Accuracy: 0.34810951760104303
Delta: 0.004605202239009736 	  Loss: 1.6394702195939226 	 Accuracy: 0.3468057366362451
Delta: 0.00010896567370501098 	  Loss: 1.639126721602639 	 Accuracy: 0.3468057366362451
Delta: 0.0013576207860524605 	  Loss: 1.6390635146716193 	 Accuracy: 0.3428943937418514
Delta: 0.0034689035485357318 	  Loss: 1.638986056250019 	 Accuracy: 0.3468057366362451
Delta: 0.00423076864892309 	  Loss: 1.639287943333862 	 Accuracy: 0.34028683181225555
Delta: 0.0012146682290536527 	  Loss: 1.6392842729650245 	 Accuracy: 0.3468057366362451
Delta: 0.004071113465247727 	  Loss: 1.6386799697166765 	 Accuracy: 0.3455019556714472
Delta: 0.0007646723829554667 	  Loss: 1.6384677354844785 	 Accuracy: 0.3468057366362451
Delta: 0.002402122835651008 	  Loss: 1.6381242423748417 	 Accuracy: 0.3389830508474576
Delta: 0.0028071753765215035 	  Loss: 1.6378725099553149 	 Accuracy: 0.3455019556714472
Delta: 0.004412637573164764 	  Loss: 1.6384216055185334 	 Accuracy: 0.34159061277705344
Delta: 0.005424558161031181 	  Loss: 1.6384050112395245 	 Accuracy: 0.3455019556714472
Delta: 0.0019976313328075607 	  Loss: 1.6384941190256215 	 Accuracy: 0.3455019556714472
Delta: 0.0034184371827312085 	  Loss: 1.639257186958257 	 Accuracy: 0.3455019556714472
Delta: 7.436198616472309e-05 	  Loss: 1.6390734442067054 	 Accuracy: 0.3455019556714472
Delta: 0.0006680816986370024 	  Loss: 1.6392871887200473 	 Accuracy: 0.3455019556714472
Delta: 3.710671975558631e-05 	  Loss: 1.6391257433748474 	 Accuracy: 0.34028683181225555
Delta: 0.0032068464861726652 	  Loss: 1.6394039850331432 	 Accuracy: 0.3455019556714472
Delta: 0.0008275582520641814 	  Loss: 1.6391549167019064 	 Accuracy: 0.3455019556714472
Delta: 0.0010754196103316574 	  Loss: 1.6393543001353457 	 Accuracy: 0.3428943937418514
Delta: 5.580748609297435e-05 	  Loss: 1.6393866727437212 	 Accuracy: 0.3455019556714472
Delta: 0.003605625552897079 	  Loss: 1.6400737067388762 	 Accuracy: 0.3455019556714472
Delta: 0.0014236815188950415 	  Loss: 1.6397408527326036 	 Accuracy: 0.34028683181225555
Delta: 0.00456056044556847 	  Loss: 1.6395864793593429 	 Accuracy: 0.34159061277705344
Delta: 0.005022910992658679 	  Loss: 1.6401602958506403 	 Accuracy: 0.34028683181225555
Delta: 0.0038307348183764826 	  Loss: 1.6404236469172635 	 Accuracy: 0.3428943937418514
Delta: 1.369149063663405e-05 	  Loss: 1.6403986925284513 	 Accuracy: 0.3428943937418514
Delta: 0.002388706183209022 	  Loss: 1.6407219128569344 	 Accuracy: 0.3428943937418514
Delta: 0.0032143516101885324 	  Loss: 1.6403705493476937 	 Accuracy: 0.34419817470664926
Delta: 0.0005447781103661023 	  Loss: 1.640466778701676 	 Accuracy: 0.34419817470664926
Delta: 0.00217764215776652 	  Loss: 1.640480485672261 	 Accuracy: 0.34419817470664926
Delta: 0.004135894721045288 	  Loss: 1.6408177595108793 	 Accuracy: 0.34159061277705344
Delta: 0.0034363302265560205 	  Loss: 1.6411298159524006 	 Accuracy: 0.34419817470664926
Delta: 0.0036728710191857913 	  Loss: 1.6404948039580427 	 Accuracy: 0.34419817470664926
Delta: 0.003820426920532408 	  Loss: 1.6406429791914312 	 Accuracy: 0.33376792698826596
Delta: 0.005066633692494708 	  Loss: 1.6411565819594198 	 Accuracy: 0.3428943937418514
Delta: 0.0028529732240679833 	  Loss: 1.640954362872902 	 Accuracy: 0.3428943937418514
Delta: 5.02169594564254e-06 	  Loss: 1.6409570100521598 	 Accuracy: 0.34419817470664926
Delta: 0.0035477152787862848 	  Loss: 1.641370613635896 	 Accuracy: 0.3468057366362451
Delta: 0.005752487696742973 	  Loss: 1.6416608389244676 	 Accuracy: 0.34028683181225555
Delta: 0.004571088058421896 	  Loss: 1.6428895009771418 	 Accuracy: 0.33376792698826596
Delta: 0.003247859121443783 	  Loss: 1.642872731935182 	 Accuracy: 0.34028683181225555
Delta: 0.0011584577377832242 	  Loss: 1.642863361676254 	 Accuracy: 0.3389830508474576
Delta: 0.0017426296887380205 	  Loss: 1.6429444621408082 	 Accuracy: 0.3428943937418514
Delta: 0.00467223163518518 	  Loss: 1.6429439131894927 	 Accuracy: 0.34028683181225555
Delta: 0.0028817006260584907 	  Loss: 1.6428082196024132 	 Accuracy: 0.34028683181225555
Delta: 0.004513793212640987 	  Loss: 1.6443393415928806 	 Accuracy: 0.34028683181225555
Delta: 0.0037265452490860248 	  Loss: 1.6441350980153153 	 Accuracy: 0.34028683181225555
Delta: 0.004459668632993011 	  Loss: 1.6442737382433292 	 Accuracy: 0.34028683181225555
Delta: 0.0017243887449812018 	  Loss: 1.6446996845452095 	 Accuracy: 0.34028683181225555
Delta: 0.0035746202788951285 	  Loss: 1.6442170643504914 	 Accuracy: 0.34028683181225555
Delta: 0.004103225175765014 	  Loss: 1.6440862610363751 	 Accuracy: 0.34159061277705344
Delta: 0.003896807170504482 	  Loss: 1.6441918813432586 	 Accuracy: 0.30247718383311606
Delta: 0.008445634557322815 	  Loss: 1.6571323302410597 	 Accuracy: 0.33376792698826596
Delta: 0.02127438799386734 	  Loss: 2.139355258131217 	 Accuracy: 0.2033898305084746
Delta: 0.019485960394775827 	  Loss: 1.9985562037965987 	 Accuracy: 0.32333767926988266
Delta: 0.01789395516926223 	  Loss: 1.7505562777133326 	 Accuracy: 0.37809647979139505
Delta: 0.014506077217570301 	  Loss: 1.649176572245504 	 Accuracy: 0.37157757496740546
Delta: 0.010971493876815166 	  Loss: 1.6244068756908108 	 Accuracy: 0.3624511082138201
Delta: 0.008643831409821738 	  Loss: 1.6218461453649236 	 Accuracy: 0.3520208604954368

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00700659804079674 	  Loss: 1.6207006837684734 	 Accuracy: 0.3546284224250326
Delta: 0.005277927888160495 	  Loss: 1.6203171458288752 	 Accuracy: 0.3546284224250326
Delta: 0.004124825609577402 	  Loss: 1.620008778767841 	 Accuracy: 0.35071707953063885
Delta: 0.0032876101807561954 	  Loss: 1.6199086197210657 	 Accuracy: 0.35071707953063885
Delta: 0.004446067064724251 	  Loss: 1.619372161651881 	 Accuracy: 0.35071707953063885
Delta: 0.002700912466881813 	  Loss: 1.619113662528355 	 Accuracy: 0.35071707953063885
Delta: 0.0013758086289300975 	  Loss: 1.6190160089546988 	 Accuracy: 0.35071707953063885
Delta: 3.9793867818810055e-05 	  Loss: 1.6189356676073958 	 Accuracy: 0.3520208604954368
Delta: 2.675637224596267e-05 	  Loss: 1.6189799559718354 	 Accuracy: 0.35071707953063885
Delta: 0.0014233861229279087 	  Loss: 1.6191022878508199 	 Accuracy: 0.35071707953063885
Delta: 3.2106481974188e-05 	  Loss: 1.6190696224575443 	 Accuracy: 0.35071707953063885
Delta: 0.002756489179259275 	  Loss: 1.6188516306720893 	 Accuracy: 0.35071707953063885
Delta: 0.003869276838446538 	  Loss: 1.6195162986557838 	 Accuracy: 0.35071707953063885
Delta: 0.0007458150968234267 	  Loss: 1.6198377665974428 	 Accuracy: 0.3520208604954368
Delta: 0.0028218978651017974 	  Loss: 1.6190885916547115 	 Accuracy: 0.3520208604954368
Delta: 0.0005350607166838115 	  Loss: 1.6189861231831957 	 Accuracy: 0.3520208604954368
Delta: 0.0006492334010147512 	  Loss: 1.6189747662700595 	 Accuracy: 0.35071707953063885
Delta: 0.00538588621914037 	  Loss: 1.620192176710217 	 Accuracy: 0.35071707953063885
Delta: 0.0038133640365866127 	  Loss: 1.6189232891594694 	 Accuracy: 0.34810951760104303
Delta: 0.004477674774518767 	  Loss: 1.6193911652497008 	 Accuracy: 0.34810951760104303
Delta: 0.00408720657263215 	  Loss: 1.619821772001162 	 Accuracy: 0.34810951760104303
Delta: 0.0031041883742723235 	  Loss: 1.6195369205253658 	 Accuracy: 0.34810951760104303
Delta: 0.004598779524456488 	  Loss: 1.6189855288419812 	 Accuracy: 0.34810951760104303
Delta: 0.0017942414244729854 	  Loss: 1.6186850033841913 	 Accuracy: 0.3468057366362451
Delta: 0.0006699646715570349 	  Loss: 1.6190084751050127 	 Accuracy: 0.34810951760104303
Delta: 3.0740359281882254e-05 	  Loss: 1.6189633993530623 	 Accuracy: 0.3494132985658409
Delta: 0.004492051237688158 	  Loss: 1.619850071854804 	 Accuracy: 0.34810951760104303
Delta: 0.003837882996135154 	  Loss: 1.618661230295325 	 Accuracy: 0.35984354628422427
Delta: 0.0017737602177045704 	  Loss: 1.618669801056357 	 Accuracy: 0.34810951760104303
Delta: 9.269054599447601e-05 	  Loss: 1.618641975276912 	 Accuracy: 0.34810951760104303
Delta: 0.0061639092290939656 	  Loss: 1.620191366017088 	 Accuracy: 0.34810951760104303
Delta: 0.003942552077297244 	  Loss: 1.620434598766755 	 Accuracy: 0.3494132985658409
Delta: 0.0031371652022579646 	  Loss: 1.6204902791402995 	 Accuracy: 0.3494132985658409
Delta: 0.0028974863219485437 	  Loss: 1.6203652939296067 	 Accuracy: 0.3494132985658409
Delta: 0.002126970257007597 	  Loss: 1.620243411802896 	 Accuracy: 0.35071707953063885
Delta: 0.006192621607056846 	  Loss: 1.6185324550997833 	 Accuracy: 0.3494132985658409
Delta: 0.007959681331134652 	  Loss: 1.6236297132218742 	 Accuracy: 0.3494132985658409
Delta: 0.005155921953835973 	  Loss: 1.6211257506807693 	 Accuracy: 0.3455019556714472
Delta: 0.0017783175073698104 	  Loss: 1.621000590188505 	 Accuracy: 0.3559322033898305
Delta: 0.006700483372460033 	  Loss: 1.6194484172206662 	 Accuracy: 0.3494132985658409
Delta: 0.001567326414610931 	  Loss: 1.619430353661233 	 Accuracy: 0.3494132985658409
Delta: 0.004552324407457482 	  Loss: 1.620238483267203 	 Accuracy: 0.3520208604954368
Delta: 0.0050092307494419225 	  Loss: 1.6210776394079178 	 Accuracy: 0.3520208604954368
Delta: 0.0011733590712277359 	  Loss: 1.6204768833920427 	 Accuracy: 0.3520208604954368
Delta: 0.00463345225740206 	  Loss: 1.6209260097796443 	 Accuracy: 0.3559322033898305
Delta: 0.0016328675061193089 	  Loss: 1.6211546918838702 	 Accuracy: 0.35071707953063885
Delta: 0.001774138129636388 	  Loss: 1.6206094602592611 	 Accuracy: 0.35071707953063885
Delta: 0.0027817221940636995 	  Loss: 1.621161305316709 	 Accuracy: 0.35071707953063885
Delta: 0.0015233530663549552 	  Loss: 1.6208635654649248 	 Accuracy: 0.35071707953063885
Delta: 0.001623202337882101 	  Loss: 1.6208495861273513 	 Accuracy: 0.3520208604954368
Delta: 0.0007051147218775539 	  Loss: 1.6204615947496914 	 Accuracy: 0.3520208604954368
Delta: 1.4139762177913276e-05 	  Loss: 1.6204954054583225 	 Accuracy: 0.3520208604954368
Delta: 0.0009844978986705956 	  Loss: 1.6203027415924778 	 Accuracy: 0.35071707953063885
Delta: 0.0032908915627690126 	  Loss: 1.6219815751939066 	 Accuracy: 0.35071707953063885
Delta: 0.0034932145535831764 	  Loss: 1.6226049897659431 	 Accuracy: 0.35071707953063885
Delta: 0.0026954216948794074 	  Loss: 1.622591934352644 	 Accuracy: 0.34810951760104303
Delta: 0.0017737455957546073 	  Loss: 1.6226596488040168 	 Accuracy: 0.3546284224250326
Delta: 0.004127803325873524 	  Loss: 1.6228020937789347 	 Accuracy: 0.3520208604954368
Delta: 0.0014847382127439967 	  Loss: 1.6226622294654078 	 Accuracy: 0.3533246414602347
Delta: 0.0032741574874470924 	  Loss: 1.6229833679345496 	 Accuracy: 0.35071707953063885
Delta: 9.766014296384204e-05 	  Loss: 1.6226420610061858 	 Accuracy: 0.3520208604954368
Delta: 0.0026288459873868527 	  Loss: 1.6224980656184562 	 Accuracy: 0.3533246414602347
Delta: 0.0038332300539607113 	  Loss: 1.6217397103805409 	 Accuracy: 0.35071707953063885
Delta: 0.0039481016822411 	  Loss: 1.6217531493428963 	 Accuracy: 0.3520208604954368
Delta: 0.002353807211142484 	  Loss: 1.6221371224459857 	 Accuracy: 0.3520208604954368
Delta: 0.0008676047466807451 	  Loss: 1.62220201447325 	 Accuracy: 0.34810951760104303
Delta: 0.002606691525364981 	  Loss: 1.6220558980621886 	 Accuracy: 0.35071707953063885
Delta: 0.0026199803982631994 	  Loss: 1.6215437647358422 	 Accuracy: 0.3520208604954368
Delta: 0.0029693905803343523 	  Loss: 1.6213389087194687 	 Accuracy: 0.3494132985658409
Delta: 0.003820654507023804 	  Loss: 1.6226350789859356 	 Accuracy: 0.3520208604954368
Delta: 0.0033581700392060557 	  Loss: 1.622822941690783 	 Accuracy: 0.3520208604954368
Delta: 0.004452867150704716 	  Loss: 1.6221037281471757 	 Accuracy: 0.35071707953063885
Delta: 0.0020105182788169793 	  Loss: 1.6221373268164534 	 Accuracy: 0.3533246414602347
Delta: 0.0035634698636237585 	  Loss: 1.6225438291193106 	 Accuracy: 0.35071707953063885
Delta: 0.003246266211671952 	  Loss: 1.622155940331087 	 Accuracy: 0.35071707953063885
Delta: 0.002329139880895203 	  Loss: 1.6224104333591627 	 Accuracy: 0.3533246414602347
Delta: 0.001933946651758991 	  Loss: 1.6218998797703401 	 Accuracy: 0.3559322033898305
Delta: 3.970536140591397e-05 	  Loss: 1.6218727230105277 	 Accuracy: 0.3494132985658409
Delta: 0.0068768677833835135 	  Loss: 1.625212627762263 	 Accuracy: 0.3455019556714472
Delta: 0.0038707486894559904 	  Loss: 1.6237916034592272 	 Accuracy: 0.34810951760104303
Delta: 0.007027592203199596 	  Loss: 1.6222040932382882 	 Accuracy: 0.3546284224250326
Delta: 0.004843719037473816 	  Loss: 1.622892679408341 	 Accuracy: 0.35071707953063885
Delta: 0.0033001649148824558 	  Loss: 1.622278283256093 	 Accuracy: 0.3494132985658409
Delta: 0.003147435893317342 	  Loss: 1.6224298227733944 	 Accuracy: 0.35071707953063885
Delta: 0.005049834904908423 	  Loss: 1.6212804821571858 	 Accuracy: 0.3533246414602347
Delta: 0.004272615339897111 	  Loss: 1.6214743040970343 	 Accuracy: 0.3520208604954368
Delta: 0.004050462372653264 	  Loss: 1.6222070343382575 	 Accuracy: 0.3520208604954368
Delta: 0.004080609852093718 	  Loss: 1.6217276933339722 	 Accuracy: 0.3533246414602347
Delta: 0.0026208525153566505 	  Loss: 1.6217407397760506 	 Accuracy: 0.35984354628422427
Delta: 0.0035859538161022225 	  Loss: 1.6212205564399014 	 Accuracy: 0.3520208604954368
Delta: 0.005003188522433475 	  Loss: 1.6206747938045771 	 Accuracy: 0.3533246414602347
Delta: 0.004962141011371221 	  Loss: 1.6200896735381023 	 Accuracy: 0.3559322033898305
Delta: 0.005373869896610921 	  Loss: 1.6203340387451608 	 Accuracy: 0.3546284224250326
Delta: 0.0064835776880530814 	  Loss: 1.6187109474335992 	 Accuracy: 0.3533246414602347
Delta: 0.020984391392704395 	  Loss: 2.142015241620011 	 Accuracy: 0.19426336375488917
Delta: 0.019177102516100282 	  Loss: 2.0321994368091896 	 Accuracy: 0.2920469361147327
Delta: 0.018130305134431528 	  Loss: 1.8431499670595133 	 Accuracy: 0.38852672750977835
Delta: 0.01665230110103145 	  Loss: 1.7059301932907325 	 Accuracy: 0.4028683181225554
Delta: 0.013150832388852559 	  Loss: 1.6572997499225237 	 Accuracy: 0.41199478487614083

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010401687639244947 	  Loss: 1.6395527506306689 	 Accuracy: 0.4106910039113429
Delta: 0.008252802357088255 	  Loss: 1.6347324421542582 	 Accuracy: 0.4106910039113429
Delta: 0.006803958851758506 	  Loss: 1.63392222476795 	 Accuracy: 0.41460234680573665
Delta: 0.0055496135927090105 	  Loss: 1.6348929313339244 	 Accuracy: 0.41590612777053454
Delta: 0.002470702183319061 	  Loss: 1.6348351884715042 	 Accuracy: 0.4172099087353325
Delta: 0.0034564851280846918 	  Loss: 1.633942007577596 	 Accuracy: 0.4172099087353325
Delta: 0.0027013488237341435 	  Loss: 1.6338596119048825 	 Accuracy: 0.41590612777053454
Delta: 0.0015249035754616917 	  Loss: 1.634373415585727 	 Accuracy: 0.41590612777053454
Delta: 6.108762356528974e-05 	  Loss: 1.6343673392067475 	 Accuracy: 0.4106910039113429
Delta: 0.0007379362034867977 	  Loss: 1.6341689732125184 	 Accuracy: 0.41460234680573665
Delta: 8.706802839875076e-05 	  Loss: 1.6346405369605495 	 Accuracy: 0.41460234680573665
Delta: 2.4449426753052664e-05 	  Loss: 1.6345262022584068 	 Accuracy: 0.42503259452411996
Delta: 0.0017500556089414619 	  Loss: 1.634369899937913 	 Accuracy: 0.41590612777053454
Delta: 0.0005677445419251827 	  Loss: 1.634399847126572 	 Accuracy: 0.41590612777053454
Delta: 0.0005883707203201851 	  Loss: 1.634498343408244 	 Accuracy: 0.41590612777053454
Delta: 0.0018878042108076173 	  Loss: 1.63391676898339 	 Accuracy: 0.4172099087353325
Delta: 0.0011722979194114269 	  Loss: 1.6339876877049544 	 Accuracy: 0.4172099087353325
Delta: 0.0014478585510273546 	  Loss: 1.63375992362807 	 Accuracy: 0.41590612777053454
Delta: 0.0020087568058546937 	  Loss: 1.6339411391445582 	 Accuracy: 0.4172099087353325
Delta: 0.001921924703468215 	  Loss: 1.6337277317928147 	 Accuracy: 0.4172099087353325
Delta: 0.0031647153280402996 	  Loss: 1.6341878318187124 	 Accuracy: 0.4172099087353325
Delta: 0.0018001925281156538 	  Loss: 1.63389887591428 	 Accuracy: 0.41590612777053454
Delta: 0.0012059347314742164 	  Loss: 1.6343598924483949 	 Accuracy: 0.4172099087353325
Delta: 0.0005602689063183779 	  Loss: 1.634125363970159 	 Accuracy: 0.3963494132985658
Delta: 0.004686983534650934 	  Loss: 1.6327401545349127 	 Accuracy: 0.41851368970013036
Delta: 0.0018542833394204201 	  Loss: 1.6329716374435406 	 Accuracy: 0.4172099087353325
Delta: 0.0017192222952953286 	  Loss: 1.6327016604283813 	 Accuracy: 0.41851368970013036
Delta: 0.0015378055391179074 	  Loss: 1.6326423575993716 	 Accuracy: 0.4172099087353325
Delta: 0.0034533596121169574 	  Loss: 1.6324600375391056 	 Accuracy: 0.4172099087353325
Delta: 0.002326073042897178 	  Loss: 1.632840388187406 	 Accuracy: 0.41851368970013036
Delta: 0.001705325818057542 	  Loss: 1.6330391495117706 	 Accuracy: 0.4172099087353325
Delta: 0.0010400507127449178 	  Loss: 1.6330008502047373 	 Accuracy: 0.4172099087353325
Delta: 0.0030911737415283643 	  Loss: 1.6338606422435507 	 Accuracy: 0.4172099087353325
Delta: 0.003054792384227188 	  Loss: 1.6332782606074225 	 Accuracy: 0.4172099087353325
Delta: 0.002523668975134578 	  Loss: 1.6329235869072285 	 Accuracy: 0.4172099087353325
Delta: 0.002683202566167911 	  Loss: 1.6331967830432053 	 Accuracy: 0.4172099087353325
Delta: 0.0019165512822881148 	  Loss: 1.633046281876076 	 Accuracy: 0.4172099087353325
Delta: 0.0013677447751576086 	  Loss: 1.6335563387686691 	 Accuracy: 0.41460234680573665
Delta: 0.00180023405532733 	  Loss: 1.6334386320844105 	 Accuracy: 0.41851368970013036
Delta: 9.356560327052027e-05 	  Loss: 1.633070125771636 	 Accuracy: 0.41590612777053454
Delta: 9.57486959574869e-05 	  Loss: 1.6333115624280519 	 Accuracy: 0.4172099087353325
Delta: 2.9948144797805136e-05 	  Loss: 1.6334225519736194 	 Accuracy: 0.41851368970013036
Delta: 0.0013270128069735464 	  Loss: 1.6337274300989806 	 Accuracy: 0.4132985658409387
Delta: 0.004200122529289949 	  Loss: 1.6338804348799933 	 Accuracy: 0.4172099087353325
Delta: 0.0006702810085000032 	  Loss: 1.6343757583007252 	 Accuracy: 0.3963494132985658
Delta: 0.0030816200951357506 	  Loss: 1.6359314201330082 	 Accuracy: 0.4198174706649283
Delta: 0.004882709522458249 	  Loss: 1.6341594505282582 	 Accuracy: 0.4172099087353325
Delta: 0.0052528039952387156 	  Loss: 1.6338840410113413 	 Accuracy: 0.4172099087353325
Delta: 0.0036586039951822615 	  Loss: 1.6350145213891412 	 Accuracy: 0.4172099087353325
Delta: 0.003460338916050945 	  Loss: 1.634977352896383 	 Accuracy: 0.4132985658409387
Delta: 0.002464654241481768 	  Loss: 1.6351488301049693 	 Accuracy: 0.41851368970013036
Delta: 0.0009518894698699302 	  Loss: 1.635118571154998 	 Accuracy: 0.4172099087353325
Delta: 0.0020884967628021227 	  Loss: 1.6346981011417043 	 Accuracy: 0.41851368970013036
Delta: 0.0010668805504230306 	  Loss: 1.6349516074208938 	 Accuracy: 0.4172099087353325
Delta: 0.003537574465506194 	  Loss: 1.635121307024554 	 Accuracy: 0.4106910039113429
Delta: 0.002418216586518708 	  Loss: 1.635177064244916 	 Accuracy: 0.41851368970013036
Delta: 0.0006331736795415899 	  Loss: 1.635009888109742 	 Accuracy: 0.41851368970013036
Delta: 0.0016589696816132254 	  Loss: 1.6352985917971754 	 Accuracy: 0.41851368970013036
Delta: 0.0012129404229243423 	  Loss: 1.6352950280322522 	 Accuracy: 0.4198174706649283
Delta: 0.003900030273509239 	  Loss: 1.6354633560236096 	 Accuracy: 0.41460234680573665
Delta: 0.0046610338267018304 	  Loss: 1.6360133052112429 	 Accuracy: 0.4198174706649283
Delta: 0.0010460724937164016 	  Loss: 1.635967929773715 	 Accuracy: 0.41851368970013036
Delta: 0.005193072617987743 	  Loss: 1.6360397325509952 	 Accuracy: 0.41851368970013036
Delta: 0.004836870359421462 	  Loss: 1.635130259907017 	 Accuracy: 0.41851368970013036
Delta: 0.0017663334644051872 	  Loss: 1.634611181974868 	 Accuracy: 0.4172099087353325
Delta: 0.0028162775509384167 	  Loss: 1.6346052276553402 	 Accuracy: 0.41590612777053454
Delta: 0.003717294911025079 	  Loss: 1.6353271691171751 	 Accuracy: 0.41851368970013036
Delta: 0.0043628398573325846 	  Loss: 1.6354498830327715 	 Accuracy: 0.4172099087353325
Delta: 0.003360680400879105 	  Loss: 1.6347678492668405 	 Accuracy: 0.4198174706649283
Delta: 0.0025512538671329664 	  Loss: 1.6345700084831591 	 Accuracy: 0.4198174706649283
Delta: 0.0034104758097347142 	  Loss: 1.6345784418402056 	 Accuracy: 0.4172099087353325
Delta: 0.004647004926347257 	  Loss: 1.6357618170338855 	 Accuracy: 0.41590612777053454
Delta: 0.0035626191348966316 	  Loss: 1.6349919138503157 	 Accuracy: 0.423728813559322
Delta: 0.0028268687694368534 	  Loss: 1.6342506353351471 	 Accuracy: 0.4211212516297262
Delta: 0.0006228991488128767 	  Loss: 1.6340924757723565 	 Accuracy: 0.41590612777053454
Delta: 0.0035235645142326025 	  Loss: 1.6341078325595366 	 Accuracy: 0.4172099087353325
Delta: 0.0026038835638926877 	  Loss: 1.6346426500549978 	 Accuracy: 0.4172099087353325
Delta: 0.002120848114291727 	  Loss: 1.6341856376700021 	 Accuracy: 0.423728813559322
Delta: 0.0009009258611072181 	  Loss: 1.6341977359702482 	 Accuracy: 0.4198174706649283
Delta: 4.7009770207727075e-05 	  Loss: 1.6341887717952726 	 Accuracy: 0.41460234680573665
Delta: 0.0017003140960770273 	  Loss: 1.634416842434274 	 Accuracy: 0.41199478487614083
Delta: 0.006982544833973553 	  Loss: 1.635670637455827 	 Accuracy: 0.42503259452411996
Delta: 0.004972098097923614 	  Loss: 1.6340200019638078 	 Accuracy: 0.4198174706649283
Delta: 0.0037684218054586096 	  Loss: 1.6351294054202747 	 Accuracy: 0.42633637548891784
Delta: 0.004666844173122867 	  Loss: 1.6350414631573127 	 Accuracy: 0.4276401564537158
Delta: 7.666592369739185e-05 	  Loss: 1.634917203462555 	 Accuracy: 0.42633637548891784
Delta: 0.0005981249146391818 	  Loss: 1.6352795065269987 	 Accuracy: 0.39895697522816165
Delta: 0.00452653002770896 	  Loss: 1.6346829712019173 	 Accuracy: 0.4211212516297262
Delta: 0.00212953158023516 	  Loss: 1.6353194449032733 	 Accuracy: 0.42503259452411996
Delta: 0.001541102145912461 	  Loss: 1.6344303006800907 	 Accuracy: 0.4211212516297262
Delta: 6.590775205290757e-05 	  Loss: 1.6342459132677796 	 Accuracy: 0.4198174706649283
Delta: 0.004137845819293113 	  Loss: 1.6345471352425187 	 Accuracy: 0.4172099087353325
Delta: 0.0030540722052965277 	  Loss: 1.6346723922266735 	 Accuracy: 0.423728813559322
Delta: 0.003176742346245126 	  Loss: 1.63370718471467 	 Accuracy: 0.42633637548891784
Delta: 0.004447546076954616 	  Loss: 1.6337550071622091 	 Accuracy: 0.41851368970013036
Delta: 0.021160010799092518 	  Loss: 2.139483416136607 	 Accuracy: 0.18513689700130379
Delta: 0.019219895876018512 	  Loss: 2.005887665179265 	 Accuracy: 0.3363754889178618
Delta: 0.01800277889534356 	  Loss: 1.761646157103799 	 Accuracy: 0.4680573663624511
Delta: 0.014600822631195587 	  Loss: 1.6715516451178865 	 Accuracy: 0.4941329856584094
Delta: 0.011593247046242454 	  Loss: 1.6493312729685734 	 Accuracy: 0.5058670143415906

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009352195654372746 	  Loss: 1.6442002046857254 	 Accuracy: 0.5045632333767927
Delta: 0.007607706570485469 	  Loss: 1.6432819749163572 	 Accuracy: 0.49674054758800523
Delta: 0.0061493539022157255 	  Loss: 1.6426030570618393 	 Accuracy: 0.4954367666232073
Delta: 0.004071661675330012 	  Loss: 1.6424269440433137 	 Accuracy: 0.49674054758800523
Delta: 0.0038502998804017395 	  Loss: 1.6425399439676402 	 Accuracy: 0.49674054758800523
Delta: 0.002617036211394786 	  Loss: 1.642623367906342 	 Accuracy: 0.4980443285528031
Delta: 0.0024789288800382793 	  Loss: 1.642632120580853 	 Accuracy: 0.4980443285528031
Delta: 2.1081700233868983e-05 	  Loss: 1.6426633912051907 	 Accuracy: 0.4980443285528031
Delta: 0.003196920696368176 	  Loss: 1.6427429843998427 	 Accuracy: 0.4980443285528031
Delta: 0.002666234861617557 	  Loss: 1.6425315173244566 	 Accuracy: 0.4980443285528031
Delta: 0.001291240481081005 	  Loss: 1.6424774757671776 	 Accuracy: 0.4980443285528031
Delta: 0.0006494300750001988 	  Loss: 1.6424810783194235 	 Accuracy: 0.4980443285528031
Delta: 0.0017030084413565427 	  Loss: 1.6425653871039225 	 Accuracy: 0.4980443285528031
Delta: 0.0006363438367478305 	  Loss: 1.642581787639216 	 Accuracy: 0.4980443285528031
Delta: 0.000669000176184494 	  Loss: 1.6425444966779108 	 Accuracy: 0.4980443285528031
Delta: 0.0017050487809233822 	  Loss: 1.6425807039057 	 Accuracy: 0.49934810951760106
Delta: 0.0010755093440063934 	  Loss: 1.6425950361968948 	 Accuracy: 0.4980443285528031
Delta: 0.0016364028125029227 	  Loss: 1.6425731870617493 	 Accuracy: 0.4980443285528031
Delta: 0.002575025256395871 	  Loss: 1.642727554298157 	 Accuracy: 0.4980443285528031
Delta: 0.0015916644378862138 	  Loss: 1.6430461436512314 	 Accuracy: 0.4980443285528031
Delta: 0.0018821421738085917 	  Loss: 1.6427637053818236 	 Accuracy: 0.49674054758800523
Delta: 0.0033984332094987844 	  Loss: 1.6433181825604253 	 Accuracy: 0.500651890482399
Delta: 0.008292635122439208 	  Loss: 1.6414103057565803 	 Accuracy: 0.49282920469361147
Delta: 0.00359871203268174 	  Loss: 1.6410675671278914 	 Accuracy: 0.4941329856584094
Delta: 0.0027777554163332845 	  Loss: 1.6412647278642396 	 Accuracy: 0.4941329856584094
Delta: 0.003395684532328226 	  Loss: 1.64191833094523 	 Accuracy: 0.49282920469361147
Delta: 0.0010452699370840156 	  Loss: 1.6415418165918307 	 Accuracy: 0.49282920469361147
Delta: 0.0034410876564032883 	  Loss: 1.642053744441123 	 Accuracy: 0.4941329856584094
Delta: 0.003452813602102216 	  Loss: 1.641205204307623 	 Accuracy: 0.4954367666232073
Delta: 0.0033100963385197133 	  Loss: 1.6412487150645982 	 Accuracy: 0.4941329856584094
Delta: 0.0020840282168970376 	  Loss: 1.6413823205180642 	 Accuracy: 0.49282920469361147
Delta: 0.001856732296929304 	  Loss: 1.641418601210196 	 Accuracy: 0.49282920469361147
Delta: 0.0009352204521629856 	  Loss: 1.641470263728431 	 Accuracy: 0.4954367666232073
Delta: 0.004666884055769455 	  Loss: 1.6393034491851965 	 Accuracy: 0.49674054758800523
Delta: 0.004504658453106799 	  Loss: 1.6405060424211981 	 Accuracy: 0.4941329856584094
Delta: 0.002754491210053847 	  Loss: 1.64061033006293 	 Accuracy: 0.49282920469361147
Delta: 0.0015410092106521195 	  Loss: 1.6406519637565498 	 Accuracy: 0.4954367666232073
Delta: 0.0029518729280306436 	  Loss: 1.6405347037908047 	 Accuracy: 0.4954367666232073
Delta: 0.003768112772836916 	  Loss: 1.6407978572436483 	 Accuracy: 0.4941329856584094
Delta: 0.001582503059610029 	  Loss: 1.6405032073596726 	 Accuracy: 0.4954367666232073
Delta: 0.0005234323103751782 	  Loss: 1.6405011145581945 	 Accuracy: 0.4954367666232073
Delta: 0.003909373601245845 	  Loss: 1.6400587066352958 	 Accuracy: 0.4954367666232073
Delta: 0.0012669062059093479 	  Loss: 1.6402026390226299 	 Accuracy: 0.49674054758800523
Delta: 0.0032128103089284488 	  Loss: 1.6407622682979532 	 Accuracy: 0.4954367666232073
Delta: 0.0023516515202868563 	  Loss: 1.6403861300108367 	 Accuracy: 0.500651890482399
Delta: 0.002616714518050448 	  Loss: 1.6407419436103698 	 Accuracy: 0.4941329856584094
Delta: 0.0028922892499389187 	  Loss: 1.6408750223539623 	 Accuracy: 0.4941329856584094
Delta: 0.0004999589566741167 	  Loss: 1.6408614144999132 	 Accuracy: 0.4941329856584094
Delta: 0.0004951087218331533 	  Loss: 1.6408541734398896 	 Accuracy: 0.4941329856584094
Delta: 5.0127889652925564e-05 	  Loss: 1.6407956321615607 	 Accuracy: 0.4954367666232073
Delta: 0.0008799333839235133 	  Loss: 1.6406988513549903 	 Accuracy: 0.4954367666232073
Delta: 0.003322391148127978 	  Loss: 1.640585254545691 	 Accuracy: 0.4941329856584094
Delta: 0.003317681057401589 	  Loss: 1.641143074358046 	 Accuracy: 0.4954367666232073
Delta: 0.0017488330810723107 	  Loss: 1.640754569497501 	 Accuracy: 0.4980443285528031
Delta: 0.00290788013114167 	  Loss: 1.6403565084770881 	 Accuracy: 0.4941329856584094
Delta: 0.0009419573417850794 	  Loss: 1.6404548235609773 	 Accuracy: 0.4954367666232073
Delta: 5.8377091882296436e-05 	  Loss: 1.6403769974944038 	 Accuracy: 0.4954367666232073
Delta: 0.0023904823349623146 	  Loss: 1.6405896381135157 	 Accuracy: 0.49674054758800523
Delta: 0.000710964977023413 	  Loss: 1.6405216059144259 	 Accuracy: 0.49282920469361147
Delta: 0.002643253607096471 	  Loss: 1.6409583298208184 	 Accuracy: 0.4941329856584094
Delta: 3.260299160258301e-05 	  Loss: 1.6409011185371587 	 Accuracy: 0.4941329856584094
Delta: 2.6936181628389938e-05 	  Loss: 1.6409382634380822 	 Accuracy: 0.4941329856584094
Delta: 0.0013979437600747536 	  Loss: 1.6408802309789028 	 Accuracy: 0.49674054758800523
Delta: 4.633339239355362e-05 	  Loss: 1.6409149340047602 	 Accuracy: 0.4941329856584094
Delta: 0.0035813279038442473 	  Loss: 1.6415124732608641 	 Accuracy: 0.4954367666232073
Delta: 0.0026943105745772617 	  Loss: 1.6406785353639532 	 Accuracy: 0.4941329856584094
Delta: 0.001958439368212166 	  Loss: 1.6406857665470906 	 Accuracy: 0.4954367666232073
Delta: 0.002242019262091762 	  Loss: 1.6406097593458608 	 Accuracy: 0.4941329856584094
Delta: 0.004132629353118149 	  Loss: 1.6409317121148481 	 Accuracy: 0.49674054758800523
Delta: 0.002396487532800387 	  Loss: 1.6408984512544829 	 Accuracy: 0.49674054758800523
Delta: 0.0037322718413946823 	  Loss: 1.6407683737389134 	 Accuracy: 0.49674054758800523
Delta: 0.0008745914179210372 	  Loss: 1.6405058821183571 	 Accuracy: 0.4980443285528031
Delta: 0.0005150582578754693 	  Loss: 1.6404976090681167 	 Accuracy: 0.4941329856584094
Delta: 0.0023327258350071176 	  Loss: 1.6396525690932737 	 Accuracy: 0.49674054758800523
Delta: 0.0029544693166568643 	  Loss: 1.639394908553356 	 Accuracy: 0.49674054758800523
Delta: 1.837092309537187e-05 	  Loss: 1.6394026298865563 	 Accuracy: 0.4980443285528031
Delta: 0.0007622274236746254 	  Loss: 1.6393477892284807 	 Accuracy: 0.49674054758800523
Delta: 0.003639764273897227 	  Loss: 1.6393058526836366 	 Accuracy: 0.4980443285528031
Delta: 0.0034838658393171774 	  Loss: 1.6384158901619426 	 Accuracy: 0.49674054758800523
Delta: 0.0036306752393258416 	  Loss: 1.638800750278223 	 Accuracy: 0.49674054758800523
Delta: 0.002281372203961352 	  Loss: 1.6388963015213935 	 Accuracy: 0.49674054758800523
Delta: 0.001380735498866078 	  Loss: 1.638920057581404 	 Accuracy: 0.4954367666232073
Delta: 0.0012521368433261962 	  Loss: 1.6393212295665691 	 Accuracy: 0.49934810951760106
Delta: 0.00299208297992451 	  Loss: 1.6389066187508103 	 Accuracy: 0.500651890482399
Delta: 0.0032923962804870736 	  Loss: 1.639118214194712 	 Accuracy: 0.4980443285528031
Delta: 0.0010394339812881232 	  Loss: 1.6389473940323702 	 Accuracy: 0.49934810951760106
Delta: 0.0036916092037851287 	  Loss: 1.6385249915830764 	 Accuracy: 0.49674054758800523
Delta: 0.004544718689785454 	  Loss: 1.6382456043667717 	 Accuracy: 0.49674054758800523
Delta: 0.003630093878273642 	  Loss: 1.6384515644501234 	 Accuracy: 0.4876140808344198
Delta: 0.0021754784370222415 	  Loss: 1.6386177501676484 	 Accuracy: 0.4980443285528031
Delta: 0.003926344265694025 	  Loss: 1.6379940306083713 	 Accuracy: 0.4980443285528031
Delta: 0.0022858318941612952 	  Loss: 1.6379743064322767 	 Accuracy: 0.4954367666232073
Delta: 0.0027239520472935514 	  Loss: 1.6362101338497619 	 Accuracy: 0.49674054758800523
Delta: 0.004349307172982255 	  Loss: 1.6377156445731706 	 Accuracy: 0.5019556714471969
Delta: 0.0024900647925218213 	  Loss: 1.6377478792416438 	 Accuracy: 0.4954367666232073
Delta: 0.02124043372958049 	  Loss: 2.139853141876255 	 Accuracy: 0.19295958279009126
Delta: 0.019002446521490347 	  Loss: 2.028882835243685 	 Accuracy: 0.3494132985658409
Delta: 0.018504568222439084 	  Loss: 1.8297363923224073 	 Accuracy: 0.4471968709256845
Delta: 0.01577422742308251 	  Loss: 1.6973984442467995 	 Accuracy: 0.439374185136897
Delta: 0.011503573611942486 	  Loss: 1.668718870054322 	 Accuracy: 0.4445893089960887

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009296021485422306 	  Loss: 1.663529679510181 	 Accuracy: 0.44589308996088656
Delta: 0.006447500089028265 	  Loss: 1.6617818693292026 	 Accuracy: 0.4471968709256845
Delta: 0.004113238573615238 	  Loss: 1.6615628412870809 	 Accuracy: 0.4485006518904824
Delta: 0.0021998475007692308 	  Loss: 1.6613460412822432 	 Accuracy: 0.4498044328552803
Delta: 0.002746264168097807 	  Loss: 1.662161798372845 	 Accuracy: 0.4498044328552803
Delta: 0.003736319815721537 	  Loss: 1.661091879114375 	 Accuracy: 0.45632333767926986
Delta: 0.0030499454835827876 	  Loss: 1.660616871458569 	 Accuracy: 0.45241199478487615
Delta: 0.0005368333436560903 	  Loss: 1.660469187049387 	 Accuracy: 0.4511082138200782
Delta: 2.3686308651247166e-05 	  Loss: 1.6604255301911812 	 Accuracy: 0.4511082138200782
Delta: 0.0005545332919863293 	  Loss: 1.6609684939025748 	 Accuracy: 0.4511082138200782
Delta: 0.0014602829456992887 	  Loss: 1.6612435724133232 	 Accuracy: 0.4511082138200782
Delta: 0.002118430167711987 	  Loss: 1.6614352026603705 	 Accuracy: 0.4511082138200782
Delta: 8.658233475146317e-05 	  Loss: 1.661157756799043 	 Accuracy: 0.4511082138200782
Delta: 0.0031313605454974082 	  Loss: 1.6613151854582884 	 Accuracy: 0.4511082138200782
Delta: 0.0009831807034107328 	  Loss: 1.6610594462126902 	 Accuracy: 0.4511082138200782
Delta: 0.002682010817529488 	  Loss: 1.6607116160006896 	 Accuracy: 0.4511082138200782
Delta: 0.0011515297237804788 	  Loss: 1.6612894182150633 	 Accuracy: 0.4471968709256845
Delta: 0.00290202059275199 	  Loss: 1.6599995122132858 	 Accuracy: 0.4511082138200782
Delta: 0.0005547337053453554 	  Loss: 1.6606109263431112 	 Accuracy: 0.455019556714472
Delta: 0.0022808594773542972 	  Loss: 1.6611551997946918 	 Accuracy: 0.45371577574967403
Delta: 0.002106598339741076 	  Loss: 1.6613411793973087 	 Accuracy: 0.44589308996088656
Delta: 0.0023377246966831545 	  Loss: 1.6612957640749244 	 Accuracy: 0.4511082138200782
Delta: 0.0015913981144830775 	  Loss: 1.6612277250036216 	 Accuracy: 0.45241199478487615
Delta: 0.0020477836203036943 	  Loss: 1.6611820806015394 	 Accuracy: 0.4485006518904824
Delta: 8.375103305740639e-05 	  Loss: 1.6613693745315894 	 Accuracy: 0.4511082138200782
Delta: 0.0007906140448210865 	  Loss: 1.6613489782581343 	 Accuracy: 0.45241199478487615
Delta: 0.0023764439798446705 	  Loss: 1.6610002469056577 	 Accuracy: 0.4511082138200782
Delta: 0.0021933890725234937 	  Loss: 1.6611904453995279 	 Accuracy: 0.4498044328552803
Delta: 0.0026379612279620822 	  Loss: 1.6611291667396615 	 Accuracy: 0.45241199478487615
Delta: 0.0027143435793943386 	  Loss: 1.6607955914769175 	 Accuracy: 0.4511082138200782
Delta: 0.003303821725690101 	  Loss: 1.660604877072274 	 Accuracy: 0.45371577574967403
Delta: 0.0026215659776937434 	  Loss: 1.6600977523224336 	 Accuracy: 0.4511082138200782
Delta: 0.0031461876573106802 	  Loss: 1.6605833110062078 	 Accuracy: 0.455019556714472
Delta: 0.004490396147967608 	  Loss: 1.6605168158297934 	 Accuracy: 0.45371577574967403
Delta: 0.0027690677141321077 	  Loss: 1.659626764226351 	 Accuracy: 0.45241199478487615
Delta: 0.0005536234782370807 	  Loss: 1.6598645946754338 	 Accuracy: 0.45632333767926986
Delta: 0.004934769697973054 	  Loss: 1.659306598596959 	 Accuracy: 0.45371577574967403
Delta: 0.001968801010148864 	  Loss: 1.6589688108032368 	 Accuracy: 0.44328552803129073
Delta: 0.007655157743273459 	  Loss: 1.6556366428420004 	 Accuracy: 0.45632333767926986
Delta: 0.007706572958970455 	  Loss: 1.6518360156500536 	 Accuracy: 0.46153846153846156
Delta: 0.004073366924747831 	  Loss: 1.651950416571891 	 Accuracy: 0.44589308996088656
Delta: 0.0058843817308937086 	  Loss: 1.650669675019477 	 Accuracy: 0.46284224250325945
Delta: 0.004911184726303997 	  Loss: 1.649904706781086 	 Accuracy: 0.4576271186440678
Delta: 0.005436196009135118 	  Loss: 1.6478777734601882 	 Accuracy: 0.46284224250325945
Delta: 0.002496741856843155 	  Loss: 1.6477048639268286 	 Accuracy: 0.46284224250325945
Delta: 0.0011497664479548787 	  Loss: 1.6476633202938133 	 Accuracy: 0.46284224250325945
Delta: 0.004765985063730295 	  Loss: 1.648014605939456 	 Accuracy: 0.4602346805736636
Delta: 0.0030567937374603236 	  Loss: 1.6483103834547794 	 Accuracy: 0.46284224250325945
Delta: 0.001541434630202319 	  Loss: 1.6479050445765018 	 Accuracy: 0.4602346805736636
Delta: 0.00286420153778063 	  Loss: 1.6479030589065298 	 Accuracy: 0.4654498044328553
Delta: 0.004795105101988605 	  Loss: 1.6490726407346523 	 Accuracy: 0.4641460234680574
Delta: 0.004365446259508699 	  Loss: 1.64813964744877 	 Accuracy: 0.4589308996088657
Delta: 0.00394340767248869 	  Loss: 1.6497773628953765 	 Accuracy: 0.46153846153846156
Delta: 0.0026714172008428924 	  Loss: 1.649548542379201 	 Accuracy: 0.46153846153846156
Delta: 0.0020441784074156756 	  Loss: 1.6496514615310682 	 Accuracy: 0.45632333767926986
Delta: 0.0037986594801918665 	  Loss: 1.649895915197258 	 Accuracy: 0.4654498044328553
Delta: 0.004285399840679624 	  Loss: 1.649820858192375 	 Accuracy: 0.4667535853976532
Delta: 0.0038703446324549967 	  Loss: 1.6498187852850128 	 Accuracy: 0.46153846153846156
Delta: 0.0036436502684933196 	  Loss: 1.650325161089694 	 Accuracy: 0.4654498044328553
Delta: 0.0052379679108680716 	  Loss: 1.6480713431027405 	 Accuracy: 0.4602346805736636
Delta: 0.004948330391670402 	  Loss: 1.6487777519379416 	 Accuracy: 0.46284224250325945
Delta: 0.003676569826763464 	  Loss: 1.648916345827553 	 Accuracy: 0.46284224250325945
Delta: 0.0040796189896241475 	  Loss: 1.6489536735218677 	 Accuracy: 0.4589308996088657
Delta: 0.003510693954840597 	  Loss: 1.6501072212738128 	 Accuracy: 0.45632333767926986
Delta: 0.0012573327613602625 	  Loss: 1.6492288788921805 	 Accuracy: 0.4602346805736636
Delta: 0.0031252039283343647 	  Loss: 1.648648311934375 	 Accuracy: 0.46284224250325945
Delta: 0.0030786009351321413 	  Loss: 1.6481118869024778 	 Accuracy: 0.4641460234680574
Delta: 0.005545081095447382 	  Loss: 1.6487815215654376 	 Accuracy: 0.4654498044328553
Delta: 0.0020647565751827543 	  Loss: 1.648431222514485 	 Accuracy: 0.46284224250325945
Delta: 0.0027322380544759018 	  Loss: 1.6481283901474644 	 Accuracy: 0.4602346805736636
Delta: 0.0033449012624399066 	  Loss: 1.6466942789523358 	 Accuracy: 0.46284224250325945
Delta: 0.004487154387920045 	  Loss: 1.6473084193893035 	 Accuracy: 0.46284224250325945
Delta: 0.004256821708381129 	  Loss: 1.6477646306717615 	 Accuracy: 0.46153846153846156
Delta: 0.004463819777098197 	  Loss: 1.6484768952076747 	 Accuracy: 0.4602346805736636
Delta: 0.004569297545837157 	  Loss: 1.6480183455062067 	 Accuracy: 0.46153846153846156
Delta: 0.0010674646382732795 	  Loss: 1.6479245307513035 	 Accuracy: 0.46153846153846156
Delta: 0.0031640306992929963 	  Loss: 1.648011239298802 	 Accuracy: 0.46284224250325945
Delta: 0.0034063573059292316 	  Loss: 1.647673399312464 	 Accuracy: 0.46153846153846156
Delta: 0.0028202472789441995 	  Loss: 1.6480047597093348 	 Accuracy: 0.4576271186440678
Delta: 0.004038380819743573 	  Loss: 1.6479047853477926 	 Accuracy: 0.4589308996088657
Delta: 0.0035233170861237425 	  Loss: 1.6485505000000378 	 Accuracy: 0.4589308996088657
Delta: 0.004458360003391301 	  Loss: 1.6473883857721419 	 Accuracy: 0.4602346805736636
Delta: 0.004666821591786984 	  Loss: 1.6487156233953333 	 Accuracy: 0.4602346805736636
Delta: 0.00374609924647766 	  Loss: 1.6480910274808411 	 Accuracy: 0.46153846153846156
Delta: 0.003775390233147442 	  Loss: 1.648219836586331 	 Accuracy: 0.46153846153846156
Delta: 0.0033980191675349702 	  Loss: 1.6479424956154918 	 Accuracy: 0.4589308996088657
Delta: 0.004992327353582304 	  Loss: 1.6492547406970894 	 Accuracy: 0.4576271186440678
Delta: 0.004850926759339605 	  Loss: 1.6505784088513975 	 Accuracy: 0.4576271186440678
Delta: 1.9951196213631164e-05 	  Loss: 1.6505532429257992 	 Accuracy: 0.45632333767926986
Delta: 0.0065899937238453575 	  Loss: 1.6526246332242054 	 Accuracy: 0.45632333767926986
Delta: 0.0036195478451257535 	  Loss: 1.6522070604982229 	 Accuracy: 0.45632333767926986
Delta: 1.3060256008193987e-05 	  Loss: 1.652196127323876 	 Accuracy: 0.45371577574967403
Delta: 0.0031966354212900924 	  Loss: 1.6523843008339039 	 Accuracy: 0.45632333767926986
Delta: 0.003557159650695757 	  Loss: 1.6524185390369421 	 Accuracy: 0.45632333767926986
Delta: 0.005755514855547488 	  Loss: 1.6525802512055283 	 Accuracy: 0.4602346805736636
Delta: 0.021041019974857255 	  Loss: 2.142204043080752 	 Accuracy: 0.1694915254237288
Delta: 0.019315626047423005 	  Loss: 2.0293535310835535 	 Accuracy: 0.29726205997392435
Delta: 0.018809971315698067 	  Loss: 1.8339490571060995 	 Accuracy: 0.3820078226857888
Delta: 0.01638578111262395 	  Loss: 1.6921092485555893 	 Accuracy: 0.4315514993481095
Delta: 0.012304891583584544 	  Loss: 1.6584174669065281 	 Accuracy: 0.43285528031290743

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009668880596774669 	  Loss: 1.6510816172262532 	 Accuracy: 0.43415906127770537
Delta: 0.007185770929177645 	  Loss: 1.6493639272769542 	 Accuracy: 0.439374185136897
Delta: 0.005888876384339979 	  Loss: 1.6489858990640947 	 Accuracy: 0.4380704041720991
Delta: 0.004396568133558625 	  Loss: 1.6477404552651045 	 Accuracy: 0.4367666232073012
Delta: 0.0037560907056159464 	  Loss: 1.6473656358103805 	 Accuracy: 0.4380704041720991
Delta: 0.0007454236082274683 	  Loss: 1.647839469564031 	 Accuracy: 0.439374185136897
Delta: 0.0019035426261031895 	  Loss: 1.6483280023041778 	 Accuracy: 0.4367666232073012
Delta: 0.002169051589519662 	  Loss: 1.6478958135875397 	 Accuracy: 0.43415906127770537
Delta: 0.0005717959056737716 	  Loss: 1.6486035372223953 	 Accuracy: 0.42894393741851367
Delta: 0.007211400966618162 	  Loss: 1.6467185378726392 	 Accuracy: 0.43546284224250326
Delta: 0.004612587356181116 	  Loss: 1.6469291706663332 	 Accuracy: 0.43285528031290743
Delta: 0.0037077979243995926 	  Loss: 1.6461258491551423 	 Accuracy: 0.43546284224250326
Delta: 0.0031624219328587064 	  Loss: 1.646166189733316 	 Accuracy: 0.4367666232073012
Delta: 0.0013081747840025997 	  Loss: 1.6460709835246807 	 Accuracy: 0.4380704041720991
Delta: 0.00269774262218465 	  Loss: 1.6462529078453507 	 Accuracy: 0.439374185136897
Delta: 0.001542593105115441 	  Loss: 1.6456963869030137 	 Accuracy: 0.4367666232073012
Delta: 0.0016493068074476033 	  Loss: 1.6460121823012215 	 Accuracy: 0.4380704041720991
Delta: 8.646746176506124e-05 	  Loss: 1.646020689521246 	 Accuracy: 0.4380704041720991
Delta: 4.663433101191122e-05 	  Loss: 1.6461268299587855 	 Accuracy: 0.4485006518904824
Delta: 0.0035908211744132322 	  Loss: 1.645610512144911 	 Accuracy: 0.439374185136897
Delta: 0.0022339582018783897 	  Loss: 1.6451421708583873 	 Accuracy: 0.4367666232073012
Delta: 0.0035913563478039037 	  Loss: 1.6447763668837627 	 Accuracy: 0.439374185136897
Delta: 0.0033817378271914157 	  Loss: 1.6455308013148149 	 Accuracy: 0.439374185136897
Delta: 0.005690386908851157 	  Loss: 1.6463444473215343 	 Accuracy: 0.439374185136897
Delta: 0.002095817951809689 	  Loss: 1.6452134720336065 	 Accuracy: 0.4367666232073012
Delta: 0.0034951442609435232 	  Loss: 1.6465367991907494 	 Accuracy: 0.4380704041720991
Delta: 0.0032977030513531664 	  Loss: 1.64614249963471 	 Accuracy: 0.4367666232073012
Delta: 0.004723417423379185 	  Loss: 1.6468133169818424 	 Accuracy: 0.4380704041720991
Delta: 0.002331367788061467 	  Loss: 1.6465036798976997 	 Accuracy: 0.4380704041720991
Delta: 0.002898121447625531 	  Loss: 1.6463695597246262 	 Accuracy: 0.43285528031290743
Delta: 0.002455159500534866 	  Loss: 1.6465768504004998 	 Accuracy: 0.44198174706649285
Delta: 0.005105336784913526 	  Loss: 1.6444608685487725 	 Accuracy: 0.4406779661016949
Delta: 0.004898766980315533 	  Loss: 1.6464160726117663 	 Accuracy: 0.4380704041720991
Delta: 0.0046964976828720575 	  Loss: 1.6455190834642512 	 Accuracy: 0.4406779661016949
Delta: 0.003001734061358873 	  Loss: 1.6455160536263262 	 Accuracy: 0.4367666232073012
Delta: 6.832754737905965e-05 	  Loss: 1.6455117786599005 	 Accuracy: 0.4367666232073012
Delta: 0.0021822076993957716 	  Loss: 1.6451124750214074 	 Accuracy: 0.4367666232073012
Delta: 0.0035467282435476446 	  Loss: 1.645409324818008 	 Accuracy: 0.4367666232073012
Delta: 0.0008680561953398661 	  Loss: 1.6453942282984304 	 Accuracy: 0.4367666232073012
Delta: 3.1105739275971613e-07 	  Loss: 1.6453943250109329 	 Accuracy: 0.4380704041720991
converged at iter  44
Delta: 0.02089087918939917 	  Loss: 2.1516033204799623 	 Accuracy: 0.1981747066492829
Delta: 0.019112764562141973 	  Loss: 2.063362207092394 	 Accuracy: 0.31421121251629724
Delta: 0.016202391932593735 	  Loss: 1.9470399130996934 	 Accuracy: 0.49282920469361147
Delta: 0.013411761039952355 	  Loss: 1.846061229115652 	 Accuracy: 0.5358539765319427
Delta: 0.01144194071288983 	  Loss: 1.7653081713003955 	 Accuracy: 0.5423728813559322
Delta: 0.009861151277154584 	  Loss: 1.7044211382725418 	 Accuracy: 0.5528031290743155
Delta: 0.0092681774642335 	  Loss: 1.6604201878464386 	 Accuracy: 0.5567144719687093
Delta: 0.008041474560024518 	  Loss: 1.6303791785996533 	 Accuracy: 0.560625814863103
Delta: 0.006971530422070174 	  Loss: 1.6098965925869875 	 Accuracy: 0.5671447196870926
Delta: 0.007089203733683679 	  Loss: 1.5965467496919323 	 Accuracy: 0.5658409387222947
Delta: 0.0058710775142687514 	  Loss: 1.5866795457459817 	 Accuracy: 0.5749674054758801
Delta: 0.0055369688153706674 	  Loss: 1.5789990993517984 	 Accuracy: 0.5853976531942634
Delta: 0.006262449057853401 	  Loss: 1.5728660081780035 	 Accuracy: 0.5945241199478487
Delta: 0.005614707738431409 	  Loss: 1.5687133643497706 	 Accuracy: 0.5958279009126467
Delta: 0.005162357217050608 	  Loss: 1.5651325931543136 	 Accuracy: 0.6036505867014341
Delta: 0.0048577168762464545 	  Loss: 1.5620271368951892 	 Accuracy: 0.6088657105606258
Delta: 0.0050597495198220445 	  Loss: 1.5595561270556118 	 Accuracy: 0.6114732724902217
Delta: 0.005256297686368151 	  Loss: 1.5571232822049073 	 Accuracy: 0.6088657105606258
Delta: 0.0044082065625349305 	  Loss: 1.5550609985011237 	 Accuracy: 0.6166883963494133
Delta: 0.00424875951283888 	  Loss: 1.5532594143561331 	 Accuracy: 0.6179921773142112
Delta: 0.0047695691647831094 	  Loss: 1.551444351970157 	 Accuracy: 0.6179921773142112
Delta: 0.004097401676310965 	  Loss: 1.549914257746683 	 Accuracy: 0.6258148631029987
Delta: 0.0035613648427038733 	  Loss: 1.5486481396168745 	 Accuracy: 0.6232073011734028
Delta: 0.0030955069266104143 	  Loss: 1.5475908237770764 	 Accuracy: 0.6245110821382008
Delta: 0.004184456974561145 	  Loss: 1.5465267163577001 	 Accuracy: 0.6258148631029987
Delta: 0.001953780527289778 	  Loss: 1.5457391490149759 	 Accuracy: 0.6271186440677966

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0031915562899336477 	  Loss: 1.5451554000876166 	 Accuracy: 0.6232073011734028
Delta: 0.0034623845576942655 	  Loss: 1.544434240305141 	 Accuracy: 0.6205997392438071
Delta: 0.0021891690339928328 	  Loss: 1.5439996385821688 	 Accuracy: 0.621903520208605
Delta: 0.0029019600752076893 	  Loss: 1.5436855248466697 	 Accuracy: 0.6205997392438071
Delta: 0.0008990825346777445 	  Loss: 1.543323214393789 	 Accuracy: 0.6192959582790091
Delta: 0.003069065420826317 	  Loss: 1.5429813220670052 	 Accuracy: 0.621903520208605
Delta: 0.002177055119188439 	  Loss: 1.5425863427011142 	 Accuracy: 0.6192959582790091
Delta: 0.003076655184872058 	  Loss: 1.5423640987858325 	 Accuracy: 0.6205997392438071
Delta: 0.0007339772478238033 	  Loss: 1.5421806978150112 	 Accuracy: 0.6232073011734028
Delta: 0.002396562338592027 	  Loss: 1.5419522534946803 	 Accuracy: 0.621903520208605
Delta: 0.0019932680798740196 	  Loss: 1.541788539784617 	 Accuracy: 0.6258148631029987
Delta: 0.0005352963448938163 	  Loss: 1.5416464628814328 	 Accuracy: 0.6205997392438071
Delta: 0.0025190642763377722 	  Loss: 1.5415374702895202 	 Accuracy: 0.621903520208605
Delta: 0.0024241413747548074 	  Loss: 1.5414348605664498 	 Accuracy: 0.6205997392438071
Delta: 0.0011360969561510213 	  Loss: 1.5413365666383023 	 Accuracy: 0.6245110821382008
Delta: 0.0029582782882988296 	  Loss: 1.5411643636715402 	 Accuracy: 0.621903520208605
Delta: 0.0007831967682151505 	  Loss: 1.541051027229253 	 Accuracy: 0.6232073011734028
Delta: 0.0026363284058624394 	  Loss: 1.5409320140248561 	 Accuracy: 0.6232073011734028
Delta: 0.0028258202233841967 	  Loss: 1.5408494445802954 	 Accuracy: 0.6232073011734028
Delta: 0.0007777270597183414 	  Loss: 1.5407696056037108 	 Accuracy: 0.6245110821382008
Delta: 0.001477076406766314 	  Loss: 1.540740559725228 	 Accuracy: 0.6258148631029987
Delta: 0.0016704282382290331 	  Loss: 1.5406878747605823 	 Accuracy: 0.6245110821382008
Delta: 5.649401251258686e-05 	  Loss: 1.5406209027826918 	 Accuracy: 0.6258148631029987
Delta: 0.00254912589736977 	  Loss: 1.5405700107299363 	 Accuracy: 0.6245110821382008
Delta: 0.0022679403973413096 	  Loss: 1.5405216296638775 	 Accuracy: 0.6271186440677966
Delta: 0.0005128110460824735 	  Loss: 1.5404755744021694 	 Accuracy: 0.621903520208605
Delta: 0.0026164427941830592 	  Loss: 1.5405098460011832 	 Accuracy: 0.6245110821382008
Delta: 0.0013274700736478431 	  Loss: 1.5404763322922996 	 Accuracy: 0.621903520208605
Delta: 0.002449128697845088 	  Loss: 1.5404726721024435 	 Accuracy: 0.6258148631029987
Delta: 0.0019298986345684993 	  Loss: 1.5404518878800142 	 Accuracy: 0.6232073011734028
Delta: 0.0014124990290732594 	  Loss: 1.5404126471481074 	 Accuracy: 0.6245110821382008
Delta: 0.001326810997686055 	  Loss: 1.5403503992318306 	 Accuracy: 0.6258148631029987
Delta: 0.0022224607977598156 	  Loss: 1.540310821680461 	 Accuracy: 0.6245110821382008
Delta: 0.0019310003810944054 	  Loss: 1.540287156810918 	 Accuracy: 0.6245110821382008
Delta: 0.00098304638113568 	  Loss: 1.540266471792835 	 Accuracy: 0.6232073011734028
Delta: 0.0013703760830495978 	  Loss: 1.5402199805170143 	 Accuracy: 0.6232073011734028
Delta: 0.0010718899122796049 	  Loss: 1.540190669006452 	 Accuracy: 0.6232073011734028
Delta: 0.0023936670221363365 	  Loss: 1.540194606108705 	 Accuracy: 0.621903520208605
Delta: 0.0007241882490884175 	  Loss: 1.5401394366006942 	 Accuracy: 0.621903520208605
Delta: 0.0005294076728552754 	  Loss: 1.5401222146485554 	 Accuracy: 0.6205997392438071
Delta: 0.000517929924602963 	  Loss: 1.5401017881142005 	 Accuracy: 0.621903520208605
Delta: 0.0019229753594961528 	  Loss: 1.5400709407790667 	 Accuracy: 0.621903520208605
Delta: 0.001470578761262234 	  Loss: 1.5400501790910472 	 Accuracy: 0.621903520208605
Delta: 0.0008089248173492707 	  Loss: 1.5400416572736844 	 Accuracy: 0.621903520208605
Delta: 5.185054258837844e-05 	  Loss: 1.540031361429071 	 Accuracy: 0.621903520208605
Delta: 0.002017211811418548 	  Loss: 1.5399966386121657 	 Accuracy: 0.6232073011734028
Delta: 0.0009650373939198879 	  Loss: 1.5400310698972262 	 Accuracy: 0.6232073011734028
Delta: 1.9294030972061408e-05 	  Loss: 1.5399974453326566 	 Accuracy: 0.6245110821382008
Delta: 0.0012806586946365872 	  Loss: 1.5399882297630798 	 Accuracy: 0.6232073011734028
Delta: 0.0007288250063421911 	  Loss: 1.539997004022713 	 Accuracy: 0.621903520208605
Delta: 0.0013378266736258672 	  Loss: 1.5399826130525485 	 Accuracy: 0.6205997392438071
Delta: 0.0005352330190890873 	  Loss: 1.5399293707960529 	 Accuracy: 0.6205997392438071
Delta: 0.0006157586453938341 	  Loss: 1.5399232688007323 	 Accuracy: 0.6245110821382008
Delta: 0.0021763200604027586 	  Loss: 1.5399348688515588 	 Accuracy: 0.621903520208605
Delta: 5.4361526832464633e-05 	  Loss: 1.539894342322572 	 Accuracy: 0.621903520208605
Delta: 2.4408079334097713e-05 	  Loss: 1.5398692557909013 	 Accuracy: 0.6245110821382008
Delta: 0.001839980077354296 	  Loss: 1.539855394951544 	 Accuracy: 0.6205997392438071
Delta: 0.0012692397852083583 	  Loss: 1.5398239303578554 	 Accuracy: 0.6205997392438071
Delta: 0.0025955687321437926 	  Loss: 1.539805178283848 	 Accuracy: 0.6205997392438071
Delta: 0.0018429192159453666 	  Loss: 1.5398195574852258 	 Accuracy: 0.6205997392438071
Delta: 0.0014939556167230456 	  Loss: 1.5398291196840581 	 Accuracy: 0.6205997392438071
Delta: 0.0008715209586521286 	  Loss: 1.5398298841014824 	 Accuracy: 0.6205997392438071
Delta: 0.0015999499525769425 	  Loss: 1.539816213337299 	 Accuracy: 0.6205997392438071
Delta: 0.0008752155383617501 	  Loss: 1.5397865821193688 	 Accuracy: 0.6232073011734028
Delta: 0.0022418775793438587 	  Loss: 1.5398045917436827 	 Accuracy: 0.621903520208605
Delta: 0.0005079509228285622 	  Loss: 1.5397910042397203 	 Accuracy: 0.6205997392438071
Delta: 0.000727005869343024 	  Loss: 1.5397822658249694 	 Accuracy: 0.6205997392438071
Delta: 0.0013939084025990814 	  Loss: 1.539786865165368 	 Accuracy: 0.6205997392438071
Delta: 0.0005160450760500327 	  Loss: 1.5397820934817459 	 Accuracy: 0.6245110821382008
Delta: 3.7281967593374765e-05 	  Loss: 1.5397572412960523 	 Accuracy: 0.6205997392438071
Delta: 0.0006206271020574058 	  Loss: 1.5397539968247471 	 Accuracy: 0.6205997392438071
Delta: 0.002448250305034321 	  Loss: 1.539739066398106 	 Accuracy: 0.6205997392438071
Delta: 0.0013886925947453818 	  Loss: 1.5397369101726746 	 Accuracy: 0.6205997392438071
Delta: 0.001516475100739056 	  Loss: 1.5397430296355619 	 Accuracy: 0.6205997392438071
Delta: 0.020994301086280514 	  Loss: 2.151312446652889 	 Accuracy: 0.21121251629726207
Delta: 0.01889616217575948 	  Loss: 2.055982742334953 	 Accuracy: 0.3194263363754889
Delta: 0.016024084290857717 	  Loss: 1.9261750141957643 	 Accuracy: 0.4784876140808344
Delta: 0.013354302627208952 	  Loss: 1.8160428970806715 	 Accuracy: 0.5019556714471969
Delta: 0.01185082667181037 	  Loss: 1.7301563373772466 	 Accuracy: 0.5189048239895697
Delta: 0.010714304483174439 	  Loss: 1.668585855380529 	 Accuracy: 0.5110821382007823
Delta: 0.009507153249891034 	  Loss: 1.6278935511842056 	 Accuracy: 0.5228161668839635
Delta: 0.008352823015790429 	  Loss: 1.6024724861060453 	 Accuracy: 0.5110821382007823
Delta: 0.007636989585846488 	  Loss: 1.5862345610389026 	 Accuracy: 0.5084745762711864
Delta: 0.006874928072592574 	  Loss: 1.5753758049560584 	 Accuracy: 0.4954367666232073
Delta: 0.00663720173049924 	  Loss: 1.5679575597945912 	 Accuracy: 0.49022164276401564
Delta: 0.005794388095792497 	  Loss: 1.5625744446741487 	 Accuracy: 0.48370273794002605
Delta: 0.005727896983143388 	  Loss: 1.5583968163663668 	 Accuracy: 0.48239895697522817
Delta: 0.006190969755353863 	  Loss: 1.5548837511054128 	 Accuracy: 0.47196870925684486
Delta: 0.0059990417837190915 	  Loss: 1.5523045828351103 	 Accuracy: 0.4745762711864407
Delta: 0.004291886745564994 	  Loss: 1.5504084141307324 	 Accuracy: 0.47327249022164275

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004380917267229539 	  Loss: 1.5486816490983921 	 Accuracy: 0.47327249022164275
Delta: 0.005408633508165029 	  Loss: 1.5471036157960794 	 Accuracy: 0.4654498044328553
Delta: 0.0035443584623422184 	  Loss: 1.5461303573407776 	 Accuracy: 0.46284224250325945
Delta: 0.0035803691518092834 	  Loss: 1.5452009360612045 	 Accuracy: 0.4602346805736636
Delta: 0.0036882649637806813 	  Loss: 1.5443657383549536 	 Accuracy: 0.46153846153846156
Delta: 0.0036323816315828334 	  Loss: 1.5440310701752227 	 Accuracy: 0.4589308996088657
Delta: 0.0033028625043299066 	  Loss: 1.543617890069971 	 Accuracy: 0.4589308996088657
Delta: 0.00304411293966341 	  Loss: 1.5432342647103399 	 Accuracy: 0.46153846153846156
Delta: 0.003573629073321532 	  Loss: 1.542935976187774 	 Accuracy: 0.4602346805736636
Delta: 0.0032365523003886325 	  Loss: 1.5427881718539715 	 Accuracy: 0.4654498044328553
Delta: 0.0029051726489999785 	  Loss: 1.5425262590421323 	 Accuracy: 0.4641460234680574
Delta: 0.0030297146344091174 	  Loss: 1.5423855120561456 	 Accuracy: 0.4602346805736636
Delta: 0.0014841487567367855 	  Loss: 1.5423984678870624 	 Accuracy: 0.4602346805736636
Delta: 0.0020898475153739004 	  Loss: 1.5422078583094638 	 Accuracy: 0.46284224250325945
Delta: 0.003922652359678597 	  Loss: 1.5421305575942093 	 Accuracy: 0.46153846153846156
Delta: 0.0017152407529918321 	  Loss: 1.5419996547144033 	 Accuracy: 0.46284224250325945
Delta: 0.001622811346287451 	  Loss: 1.5420095597124195 	 Accuracy: 0.46284224250325945
Delta: 0.0024507406187408206 	  Loss: 1.5419154292496269 	 Accuracy: 0.46284224250325945
Delta: 0.002642556282939886 	  Loss: 1.5418750096394993 	 Accuracy: 0.46284224250325945
Delta: 0.0005236616012172894 	  Loss: 1.54182631052451 	 Accuracy: 0.4641460234680574
Delta: 0.002715536977851199 	  Loss: 1.541782170665883 	 Accuracy: 0.4680573663624511
Delta: 0.0011105457280881838 	  Loss: 1.54180674142718 	 Accuracy: 0.4641460234680574
Delta: 4.000221311621577e-05 	  Loss: 1.541743299138281 	 Accuracy: 0.46936114732724904
Delta: 0.0009268732498886289 	  Loss: 1.5417809825307138 	 Accuracy: 0.4641460234680574
Delta: 0.0007593860986397554 	  Loss: 1.5417950779944276 	 Accuracy: 0.4654498044328553
Delta: 0.000743813483807956 	  Loss: 1.5417663485536004 	 Accuracy: 0.4706649282920469
Delta: 0.0024785032767507312 	  Loss: 1.5418310086798939 	 Accuracy: 0.4654498044328553
Delta: 0.0008118903891602287 	  Loss: 1.5417849560956214 	 Accuracy: 0.4667535853976532
Delta: 0.001542545254257423 	  Loss: 1.5417249231500243 	 Accuracy: 0.4706649282920469
Delta: 0.0021538814536121277 	  Loss: 1.5418123569515407 	 Accuracy: 0.46936114732724904
Delta: 0.0021779363254202295 	  Loss: 1.541823373958818 	 Accuracy: 0.46936114732724904
Delta: 0.001998895733282167 	  Loss: 1.5417251083552257 	 Accuracy: 0.4680573663624511
Delta: 0.002641221955619915 	  Loss: 1.541812002500209 	 Accuracy: 0.4680573663624511
Delta: 0.0010485409498700495 	  Loss: 1.5417711691692837 	 Accuracy: 0.46936114732724904
Delta: 0.0006586355467403456 	  Loss: 1.5417954022354852 	 Accuracy: 0.4667535853976532
Delta: 0.0024095315672437705 	  Loss: 1.5418758208628798 	 Accuracy: 0.4706649282920469
Delta: 0.0010312583770776883 	  Loss: 1.5418916253440567 	 Accuracy: 0.46936114732724904
Delta: 0.0005644070764147252 	  Loss: 1.5418776052382301 	 Accuracy: 0.4667535853976532
Delta: 0.0019406822021444813 	  Loss: 1.5419737378683147 	 Accuracy: 0.4680573663624511
Delta: 2.739325278347525e-05 	  Loss: 1.5418372295531038 	 Accuracy: 0.4758800521512386
Delta: 0.001126532777637359 	  Loss: 1.5417272325133586 	 Accuracy: 0.4654498044328553
Delta: 0.001177324505375691 	  Loss: 1.5418328708897424 	 Accuracy: 0.4667535853976532
Delta: 3.876396576118913e-05 	  Loss: 1.5418415216806687 	 Accuracy: 0.4680573663624511
Delta: 0.0011657509151182187 	  Loss: 1.5417274146964686 	 Accuracy: 0.4680573663624511
Delta: 0.0014460033966375815 	  Loss: 1.5419015326648422 	 Accuracy: 0.4680573663624511
Delta: 0.00119581525553986 	  Loss: 1.5418236203809728 	 Accuracy: 0.4680573663624511
Delta: 0.00010014651512948255 	  Loss: 1.5416480532939139 	 Accuracy: 0.4680573663624511
Delta: 5.2165755114528895e-05 	  Loss: 1.5418030102105869 	 Accuracy: 0.4680573663624511
Delta: 4.3832769687801934e-05 	  Loss: 1.541754763489025 	 Accuracy: 0.4680573663624511
Delta: 4.353653029143572e-05 	  Loss: 1.5416808641635846 	 Accuracy: 0.4680573663624511
Delta: 0.0018533798846280824 	  Loss: 1.541769113861161 	 Accuracy: 0.4680573663624511
Delta: 5.892183154995364e-05 	  Loss: 1.5416712723168455 	 Accuracy: 0.4680573663624511
Delta: 1.8782486050481402e-05 	  Loss: 1.5416763122292045 	 Accuracy: 0.4680573663624511
Delta: 2.6732598399139418e-05 	  Loss: 1.5416824026967593 	 Accuracy: 0.4680573663624511
Delta: 2.5342347055794346e-05 	  Loss: 1.5416779688973468 	 Accuracy: 0.4680573663624511
Delta: 2.091637723475136e-05 	  Loss: 1.5416488804050172 	 Accuracy: 0.4680573663624511
Delta: 4.476022912528843e-05 	  Loss: 1.5418031438499322 	 Accuracy: 0.4654498044328553
Delta: 0.0012132517709548699 	  Loss: 1.541642716071065 	 Accuracy: 0.4680573663624511
Delta: 0.0006688943912474845 	  Loss: 1.5419201211783777 	 Accuracy: 0.4680573663624511
Delta: 0.000654351738521383 	  Loss: 1.5416892227488543 	 Accuracy: 0.4680573663624511
Delta: 2.8324805806476055e-05 	  Loss: 1.5416636510936608 	 Accuracy: 0.4667535853976532
Delta: 3.827317353966019e-05 	  Loss: 1.5417690658669927 	 Accuracy: 0.4680573663624511
Delta: 0.0008720566814678584 	  Loss: 1.5417430194450534 	 Accuracy: 0.4680573663624511
Delta: 3.812386227056173e-05 	  Loss: 1.5416755700518716 	 Accuracy: 0.4680573663624511
Delta: 2.226776446937393e-05 	  Loss: 1.5416398155796665 	 Accuracy: 0.4667535853976532
Delta: 0.0014728658692483199 	  Loss: 1.5420039922342543 	 Accuracy: 0.4680573663624511
Delta: 0.0006749666365187096 	  Loss: 1.5417130990264314 	 Accuracy: 0.4667535853976532
Delta: 0.0006983216673275903 	  Loss: 1.5417862509712106 	 Accuracy: 0.4667535853976532
Delta: 0.0020653946860793738 	  Loss: 1.5418513410854802 	 Accuracy: 0.47196870925684486
Delta: 0.00394264001445775 	  Loss: 1.5429029881310279 	 Accuracy: 0.4641460234680574
Delta: 0.0023583111045522407 	  Loss: 1.5418833799627985 	 Accuracy: 0.4667535853976532
Delta: 4.844846880312207e-05 	  Loss: 1.541821182941511 	 Accuracy: 0.4680573663624511
Delta: 8.893409140850013e-05 	  Loss: 1.5417295010338012 	 Accuracy: 0.4680573663624511
Delta: 5.790122056320913e-05 	  Loss: 1.5417471067305293 	 Accuracy: 0.4667535853976532
Delta: 2.0077465703600552e-05 	  Loss: 1.5417300323137755 	 Accuracy: 0.4680573663624511
Delta: 5.1746295092299645e-05 	  Loss: 1.5417709230360015 	 Accuracy: 0.4680573663624511
Delta: 3.892749205435031e-05 	  Loss: 1.5416829388039976 	 Accuracy: 0.46936114732724904
Delta: 0.004108630882738194 	  Loss: 1.5415258699516006 	 Accuracy: 0.46936114732724904
Delta: 0.0023857421357057207 	  Loss: 1.541700088207926 	 Accuracy: 0.4680573663624511
Delta: 0.0025314499157369106 	  Loss: 1.5416538570072418 	 Accuracy: 0.4680573663624511
Delta: 6.750856750998426e-06 	  Loss: 1.5416622585535962 	 Accuracy: 0.4680573663624511
Delta: 0.0013598497223490321 	  Loss: 1.5417547798812326 	 Accuracy: 0.4680573663624511
Delta: 0.0019549801957202723 	  Loss: 1.5419711324047864 	 Accuracy: 0.4680573663624511
Delta: 0.001978697827322342 	  Loss: 1.541665152494928 	 Accuracy: 0.4680573663624511
Delta: 0.020912457589021594 	  Loss: 2.151692471582936 	 Accuracy: 0.20860495436766624
Delta: 0.01901207928277437 	  Loss: 2.0550151782304376 	 Accuracy: 0.3468057366362451
Delta: 0.016495464010285992 	  Loss: 1.9190888537756194 	 Accuracy: 0.4745762711864407
Delta: 0.014066373719093195 	  Loss: 1.797218747831274 	 Accuracy: 0.5267275097783573
Delta: 0.012285678884450873 	  Loss: 1.7014492737412175 	 Accuracy: 0.5384615384615384
Delta: 0.010756697261130337 	  Loss: 1.6389863317161306 	 Accuracy: 0.5541069100391134
Delta: 0.009101266647305544 	  Loss: 1.6034865854338696 	 Accuracy: 0.5202086049543677
Delta: 0.007933878674896106 	  Loss: 1.5832110372139234 	 Accuracy: 0.5097783572359843
Delta: 0.006967667935509014 	  Loss: 1.5715408502182906 	 Accuracy: 0.5058670143415906
Delta: 0.006711301834444571 	  Loss: 1.5641545077582073 	 Accuracy: 0.49934810951760106
Delta: 0.005988667976603667 	  Loss: 1.559682355031288 	 Accuracy: 0.49022164276401564
Delta: 0.006264799876607766 	  Loss: 1.5563942156244241 	 Accuracy: 0.4876140808344198

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006338960461380251 	  Loss: 1.5534386859433256 	 Accuracy: 0.4876140808344198
Delta: 0.006078542193703702 	  Loss: 1.5511059377473893 	 Accuracy: 0.4810951760104302
Delta: 0.005629978287550612 	  Loss: 1.5489871023520942 	 Accuracy: 0.4784876140808344
Delta: 0.004519788076804071 	  Loss: 1.5472907532028486 	 Accuracy: 0.4758800521512386
Delta: 0.004082720678308798 	  Loss: 1.5462336846310238 	 Accuracy: 0.4745762711864407
Delta: 0.004421605929788433 	  Loss: 1.5453126989270654 	 Accuracy: 0.47327249022164275
Delta: 0.004100500774703711 	  Loss: 1.5445033461991016 	 Accuracy: 0.46936114732724904
Delta: 0.003360230119936221 	  Loss: 1.544031181671347 	 Accuracy: 0.4745762711864407
Delta: 0.0036967267388406406 	  Loss: 1.5438037034287393 	 Accuracy: 0.4706649282920469
Delta: 0.0033835923576009484 	  Loss: 1.54378024625173 	 Accuracy: 0.47327249022164275
Delta: 0.002689470011224801 	  Loss: 1.5436404493174305 	 Accuracy: 0.4758800521512386
Delta: 0.0031017470422070948 	  Loss: 1.5435416329671918 	 Accuracy: 0.4745762711864407
Delta: 0.0015321243062070727 	  Loss: 1.5435315824480602 	 Accuracy: 0.4758800521512386
Delta: 0.0006483344262576888 	  Loss: 1.5434947540485084 	 Accuracy: 0.4758800521512386
Delta: 0.003041248213361288 	  Loss: 1.5434300709874613 	 Accuracy: 0.4745762711864407
Delta: 0.0009478342639364801 	  Loss: 1.5434493754270324 	 Accuracy: 0.4745762711864407
Delta: 0.002218878754982123 	  Loss: 1.5434367790338286 	 Accuracy: 0.47327249022164275
Delta: 0.0023760003155671797 	  Loss: 1.5436822764106035 	 Accuracy: 0.4745762711864407
Delta: 0.0006951421266784134 	  Loss: 1.5434354735762028 	 Accuracy: 0.4758800521512386
Delta: 0.000664343386595234 	  Loss: 1.5434874594787176 	 Accuracy: 0.4745762711864407
Delta: 0.0014885842900891112 	  Loss: 1.5434568659094476 	 Accuracy: 0.47327249022164275
Delta: 0.00053762317321558 	  Loss: 1.543505320941588 	 Accuracy: 0.47327249022164275
Delta: 0.0028287954873870594 	  Loss: 1.5434464868260025 	 Accuracy: 0.47327249022164275
Delta: 0.0006634947392899785 	  Loss: 1.5434366279546254 	 Accuracy: 0.47327249022164275
Delta: 5.568100634546725e-05 	  Loss: 1.5434806957249552 	 Accuracy: 0.4745762711864407
Delta: 5.484740725500516e-05 	  Loss: 1.5434536861351043 	 Accuracy: 0.4745762711864407
Delta: 0.0012049628639543492 	  Loss: 1.5434124756807284 	 Accuracy: 0.4745762711864407
Delta: 0.0015884725728889599 	  Loss: 1.5434289093132465 	 Accuracy: 0.4745762711864407
Delta: 0.0005319212984449283 	  Loss: 1.5434100354545066 	 Accuracy: 0.4745762711864407
Delta: 4.004726121353277e-05 	  Loss: 1.5434849835541176 	 Accuracy: 0.4745762711864407
Delta: 2.8555203857466285e-05 	  Loss: 1.5434456679926936 	 Accuracy: 0.47327249022164275
Delta: 3.5783846449681633e-05 	  Loss: 1.5434903684805552 	 Accuracy: 0.47327249022164275
Delta: 4.414040287107609e-05 	  Loss: 1.5434198271228228 	 Accuracy: 0.47196870925684486
Delta: 4.9377233706534965e-05 	  Loss: 1.543495065656672 	 Accuracy: 0.4745762711864407
Delta: 0.00073463879211646 	  Loss: 1.5435742338078071 	 Accuracy: 0.4745762711864407
Delta: 0.001170898373370078 	  Loss: 1.5435856927295273 	 Accuracy: 0.4745762711864407
Delta: 0.0016258048710834831 	  Loss: 1.5434632242407664 	 Accuracy: 0.47327249022164275
Delta: 0.0014311301615516443 	  Loss: 1.5433710470002762 	 Accuracy: 0.4745762711864407
Delta: 5.1570605776405095e-05 	  Loss: 1.5434274084152992 	 Accuracy: 0.4745762711864407
Delta: 5.710423368419904e-05 	  Loss: 1.543397181571966 	 Accuracy: 0.4745762711864407
Delta: 6.393406953453526e-05 	  Loss: 1.54328243663366 	 Accuracy: 0.4745762711864407
Delta: 5.590753241756088e-05 	  Loss: 1.543572429018019 	 Accuracy: 0.4745762711864407
Delta: 6.758790802906902e-05 	  Loss: 1.5435294879173622 	 Accuracy: 0.47327249022164275
Delta: 0.0017631544287038496 	  Loss: 1.5436038317882357 	 Accuracy: 0.47196870925684486
Delta: 0.0005166463339647589 	  Loss: 1.5436891708892986 	 Accuracy: 0.4745762711864407
Delta: 0.0005683427171587436 	  Loss: 1.5434258267604668 	 Accuracy: 0.47327249022164275
Delta: 5.481657178189963e-05 	  Loss: 1.5435368022114755 	 Accuracy: 0.4745762711864407
Delta: 0.0008306649508804388 	  Loss: 1.5434966215464576 	 Accuracy: 0.4667535853976532
Delta: 0.0006711279589235561 	  Loss: 1.5434042824917624 	 Accuracy: 0.4745762711864407
Delta: 4.2994814028495525e-05 	  Loss: 1.543365663667846 	 Accuracy: 0.4745762711864407
Delta: 8.337693893305848e-05 	  Loss: 1.543483277018248 	 Accuracy: 0.4745762711864407
Delta: 7.505081989426633e-05 	  Loss: 1.5433181693838156 	 Accuracy: 0.4745762711864407
Delta: 3.8093614323151224e-05 	  Loss: 1.5432983749203222 	 Accuracy: 0.47979139504563234
Delta: 5.848041143688301e-05 	  Loss: 1.543361065288476 	 Accuracy: 0.4745762711864407
Delta: 3.6745770516479316e-05 	  Loss: 1.5434234215721596 	 Accuracy: 0.4745762711864407
Delta: 1.685168370824845e-05 	  Loss: 1.5433706647472754 	 Accuracy: 0.4745762711864407
Delta: 3.523183573018086e-05 	  Loss: 1.5435232856047247 	 Accuracy: 0.4745762711864407
Delta: 3.3923394811459466e-05 	  Loss: 1.543377373522838 	 Accuracy: 0.4745762711864407
Delta: 0.001748942092763682 	  Loss: 1.5432954564895642 	 Accuracy: 0.4758800521512386
Delta: 0.004853836665254704 	  Loss: 1.5431573507927407 	 Accuracy: 0.4758800521512386
Delta: 2.3121456226015802e-05 	  Loss: 1.543159400420795 	 Accuracy: 0.4758800521512386
Delta: 2.2981808820481577e-05 	  Loss: 1.5431330002448655 	 Accuracy: 0.4758800521512386
Delta: 0.0028924886520789034 	  Loss: 1.5430704841369653 	 Accuracy: 0.4771838331160365
Delta: 0.0029819780087613408 	  Loss: 1.5429163574387874 	 Accuracy: 0.47979139504563234
Delta: 0.0020542791815058386 	  Loss: 1.5431973069383367 	 Accuracy: 0.4771838331160365
Delta: 0.0011336201759167067 	  Loss: 1.542761916777096 	 Accuracy: 0.47979139504563234
Delta: 0.0015356845965475887 	  Loss: 1.5424903937627825 	 Accuracy: 0.4771838331160365
Delta: 6.40227884923068e-05 	  Loss: 1.5425951355843017 	 Accuracy: 0.4758800521512386
Delta: 0.002335955154153604 	  Loss: 1.5428469572771624 	 Accuracy: 0.4706649282920469
Delta: 0.0018972315520392222 	  Loss: 1.5432590844186143 	 Accuracy: 0.4758800521512386
Delta: 0.0029927183588251906 	  Loss: 1.543024228289526 	 Accuracy: 0.4758800521512386
Delta: 0.0033875399970723363 	  Loss: 1.543046846959133 	 Accuracy: 0.4758800521512386
Delta: 0.002878179523795326 	  Loss: 1.5439378458758153 	 Accuracy: 0.4758800521512386
Delta: 0.0015725620115578313 	  Loss: 1.5437552205428582 	 Accuracy: 0.4745762711864407
Delta: 0.002803560160875391 	  Loss: 1.544180733596925 	 Accuracy: 0.4758800521512386
Delta: 0.0005442763233862097 	  Loss: 1.544147078792026 	 Accuracy: 0.4771838331160365
Delta: 0.0013366279276791505 	  Loss: 1.5441685714764448 	 Accuracy: 0.4680573663624511
Delta: 4.2152676314216665e-05 	  Loss: 1.5440463877911927 	 Accuracy: 0.4758800521512386
Delta: 3.463950163491765e-05 	  Loss: 1.5440105225528704 	 Accuracy: 0.4758800521512386
Delta: 0.00109798287460302 	  Loss: 1.543979366073534 	 Accuracy: 0.4758800521512386
Delta: 0.001256015732056655 	  Loss: 1.5440152770130886 	 Accuracy: 0.4641460234680574
Delta: 3.6633629472212066e-05 	  Loss: 1.5442274291228617 	 Accuracy: 0.4758800521512386
Delta: 4.9041679352403495e-05 	  Loss: 1.5441489087451519 	 Accuracy: 0.4758800521512386
Delta: 4.660166966522106e-05 	  Loss: 1.5439964440414284 	 Accuracy: 0.4758800521512386
Delta: 3.3438063645494935e-05 	  Loss: 1.5440185627378655 	 Accuracy: 0.4758800521512386
Delta: 2.321300345305356e-05 	  Loss: 1.5439569866992364 	 Accuracy: 0.4706649282920469
Delta: 0.0024993300838909737 	  Loss: 1.5449974486704339 	 Accuracy: 0.48239895697522817
Delta: 0.0021115816199968962 	  Loss: 1.5440148403233944 	 Accuracy: 0.4758800521512386
Delta: 0.020883803993678677 	  Loss: 2.1519213733965454 	 Accuracy: 0.20599739243807041
Delta: 0.018928944821734125 	  Loss: 2.0543210626138046 	 Accuracy: 0.3389830508474576
Delta: 0.016624904269236764 	  Loss: 1.9107414320354184 	 Accuracy: 0.44589308996088656
Delta: 0.014662318296824902 	  Loss: 1.7893119777232946 	 Accuracy: 0.47327249022164275
Delta: 0.01367060574752943 	  Loss: 1.6973989467904602 	 Accuracy: 0.43546284224250326
Delta: 0.012039341483528462 	  Loss: 1.6324144630096025 	 Accuracy: 0.4367666232073012
Delta: 0.01030144809764422 	  Loss: 1.5917543058246166 	 Accuracy: 0.43285528031290743
Delta: 0.008520766187701393 	  Loss: 1.5696093126647983 	 Accuracy: 0.43546284224250326
Delta: 0.007474830503771698 	  Loss: 1.557741158839488 	 Accuracy: 0.4172099087353325

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007591564082475899 	  Loss: 1.5507336203099213 	 Accuracy: 0.423728813559322
Delta: 0.006712244985302836 	  Loss: 1.5460957978068515 	 Accuracy: 0.40808344198174706
Delta: 0.006380482698922607 	  Loss: 1.5429468451726076 	 Accuracy: 0.4067796610169492
Delta: 0.006127195977061127 	  Loss: 1.540245201178615 	 Accuracy: 0.4067796610169492
Delta: 0.00615437229617489 	  Loss: 1.538379616665817 	 Accuracy: 0.4041720990873533
Delta: 0.005100207799672425 	  Loss: 1.5370033747311818 	 Accuracy: 0.4041720990873533
Delta: 0.004248927119481243 	  Loss: 1.536045678668247 	 Accuracy: 0.4028683181225554
Delta: 0.003996738771480708 	  Loss: 1.5354946402222698 	 Accuracy: 0.40547588005215124
Delta: 0.00354311045318632 	  Loss: 1.5351172748378734 	 Accuracy: 0.4041720990873533
Delta: 0.003343487755720416 	  Loss: 1.534891603168525 	 Accuracy: 0.39765319426336376
Delta: 0.0031484695895118817 	  Loss: 1.5347843272011414 	 Accuracy: 0.4015645371577575
Delta: 0.002948976452297501 	  Loss: 1.534625384773147 	 Accuracy: 0.4015645371577575
Delta: 0.000939595054504858 	  Loss: 1.5346181695294692 	 Accuracy: 0.4015645371577575
Delta: 0.0034966320098262257 	  Loss: 1.5346022666766874 	 Accuracy: 0.4002607561929596
Delta: 0.0021335278878652116 	  Loss: 1.534695110919304 	 Accuracy: 0.4015645371577575
Delta: 0.0014382677856732253 	  Loss: 1.534675120386717 	 Accuracy: 0.4015645371577575
Delta: 0.0013195686135389927 	  Loss: 1.5347404912269436 	 Accuracy: 0.4015645371577575
Delta: 0.002561831474166519 	  Loss: 1.534823747904445 	 Accuracy: 0.4028683181225554
Delta: 4.35850169118839e-05 	  Loss: 1.5347560575717352 	 Accuracy: 0.4015645371577575
Delta: 0.0005297181559661003 	  Loss: 1.5347034887770823 	 Accuracy: 0.4015645371577575
Delta: 3.427241470038894e-05 	  Loss: 1.534651157764332 	 Accuracy: 0.4015645371577575
Delta: 2.347904837151036e-05 	  Loss: 1.5348326192834785 	 Accuracy: 0.4028683181225554
Delta: 0.0010988814016214161 	  Loss: 1.5348034921483231 	 Accuracy: 0.4028683181225554
Delta: 3.330982837228569e-05 	  Loss: 1.5347720331852441 	 Accuracy: 0.4028683181225554
Delta: 2.650348971212678e-05 	  Loss: 1.5347523423276557 	 Accuracy: 0.4015645371577575
Delta: 0.0029252882685031345 	  Loss: 1.53483528346672 	 Accuracy: 0.4028683181225554
Delta: 6.190690305195295e-05 	  Loss: 1.534708113578934 	 Accuracy: 0.4028683181225554
Delta: 0.0010899301774771953 	  Loss: 1.534695439940911 	 Accuracy: 0.4041720990873533
Delta: 0.0007634446089032433 	  Loss: 1.5346788248590908 	 Accuracy: 0.4028683181225554
Delta: 4.0122322155207174e-05 	  Loss: 1.534680200233582 	 Accuracy: 0.4041720990873533
Delta: 3.2903488402292784e-05 	  Loss: 1.534808339874881 	 Accuracy: 0.4028683181225554
Delta: 4.618420624869905e-05 	  Loss: 1.5345538511432824 	 Accuracy: 0.4028683181225554
Delta: 5.250512523953376e-05 	  Loss: 1.5348145709879555 	 Accuracy: 0.4028683181225554
Delta: 4.5042319780435354e-05 	  Loss: 1.5348790223836544 	 Accuracy: 0.4028683181225554
Delta: 6.90285158299631e-05 	  Loss: 1.5349697021688125 	 Accuracy: 0.4028683181225554
Delta: 3.1409277691714604e-05 	  Loss: 1.534892719998708 	 Accuracy: 0.4028683181225554
Delta: 0.0006854643321581804 	  Loss: 1.5345921618789535 	 Accuracy: 0.4028683181225554
Delta: 0.00010329481199669612 	  Loss: 1.534895753882793 	 Accuracy: 0.4028683181225554
Delta: 5.928376772636173e-05 	  Loss: 1.5347461359924726 	 Accuracy: 0.4028683181225554
Delta: 6.092147598888849e-05 	  Loss: 1.5350399615675103 	 Accuracy: 0.40547588005215124
Delta: 0.00011029302253431873 	  Loss: 1.534685881668266 	 Accuracy: 0.4028683181225554
Delta: 0.0016550631947969342 	  Loss: 1.534660591607544 	 Accuracy: 0.4028683181225554
Delta: 0.0012962928999752995 	  Loss: 1.5348267114856209 	 Accuracy: 0.4028683181225554
Delta: 0.0013381934885563073 	  Loss: 1.5345586086156544 	 Accuracy: 0.4028683181225554
Delta: 6.734844202736223e-05 	  Loss: 1.5348132459202612 	 Accuracy: 0.4028683181225554
Delta: 2.8204343723959417e-05 	  Loss: 1.534740964377629 	 Accuracy: 0.4028683181225554
Delta: 3.1149731007114944e-05 	  Loss: 1.534815929383037 	 Accuracy: 0.4028683181225554
Delta: 3.5741736053554114e-05 	  Loss: 1.5347270254060814 	 Accuracy: 0.4028683181225554
Delta: 3.249236222044167e-05 	  Loss: 1.5346978589291607 	 Accuracy: 0.4028683181225554
Delta: 3.840890926173365e-05 	  Loss: 1.534646731702408 	 Accuracy: 0.4028683181225554
Delta: 3.991321669679139e-05 	  Loss: 1.5347237291542908 	 Accuracy: 0.4028683181225554
Delta: 0.000760528196600441 	  Loss: 1.5346862190262267 	 Accuracy: 0.4028683181225554
Delta: 0.0007715706659687208 	  Loss: 1.534684327905084 	 Accuracy: 0.4028683181225554
Delta: 4.525149909086117e-05 	  Loss: 1.5346878279022866 	 Accuracy: 0.4028683181225554
Delta: 4.2967664843092604e-05 	  Loss: 1.5347269423017003 	 Accuracy: 0.4028683181225554
Delta: 3.2681556656423275e-05 	  Loss: 1.5346988174047909 	 Accuracy: 0.4028683181225554
Delta: 2.5931018383474728e-05 	  Loss: 1.5347459271862476 	 Accuracy: 0.4028683181225554
Delta: 3.5725579683477887e-06 	  Loss: 1.534746443612259 	 Accuracy: 0.4028683181225554
Delta: 9.032719269898834e-06 	  Loss: 1.534731553749388 	 Accuracy: 0.4015645371577575
Delta: 0.0024090221166613583 	  Loss: 1.5380769038980984 	 Accuracy: 0.4015645371577575
Delta: 0.0016405790077041503 	  Loss: 1.5365388633763466 	 Accuracy: 0.4028683181225554
Delta: 0.0014491163027612673 	  Loss: 1.5348716574720112 	 Accuracy: 0.4028683181225554
Delta: 4.617489008237498e-05 	  Loss: 1.534829640850277 	 Accuracy: 0.4067796610169492
Delta: 5.428470130951167e-05 	  Loss: 1.5348607035135786 	 Accuracy: 0.4028683181225554
Delta: 0.0005280873441786363 	  Loss: 1.5347549511308674 	 Accuracy: 0.4028683181225554
Delta: 0.0007655779584369192 	  Loss: 1.5345557892004216 	 Accuracy: 0.4041720990873533
Delta: 7.566474158574069e-05 	  Loss: 1.534755282070291 	 Accuracy: 0.4041720990873533
Delta: 5.34912459304023e-05 	  Loss: 1.534803023104491 	 Accuracy: 0.4028683181225554
Delta: 3.3281365151730774e-05 	  Loss: 1.534772276094023 	 Accuracy: 0.4041720990873533
Delta: 0.0035820330119857298 	  Loss: 1.534563483081849 	 Accuracy: 0.4028683181225554
Delta: 0.0012233005615986273 	  Loss: 1.5350845867197382 	 Accuracy: 0.4028683181225554
Delta: 0.003855120348525564 	  Loss: 1.535397725259184 	 Accuracy: 0.4067796610169492
Delta: 0.004084606552031885 	  Loss: 1.5344308756464624 	 Accuracy: 0.4041720990873533
Delta: 0.0006525995910426174 	  Loss: 1.5348630991714634 	 Accuracy: 0.4041720990873533
Delta: 0.002868817150879791 	  Loss: 1.5354356784051513 	 Accuracy: 0.4041720990873533
Delta: 0.0021942254249424785 	  Loss: 1.5347635557006427 	 Accuracy: 0.4041720990873533
Delta: 0.00291707261125161 	  Loss: 1.534792344498569 	 Accuracy: 0.4041720990873533
Delta: 0.0006696371264121397 	  Loss: 1.5349975791824269 	 Accuracy: 0.4041720990873533
Delta: 4.281177749029933e-05 	  Loss: 1.5349620230985406 	 Accuracy: 0.4041720990873533
Delta: 0.0015088023690288134 	  Loss: 1.534837837448324 	 Accuracy: 0.4041720990873533
Delta: 4.9074739639067425e-05 	  Loss: 1.5350354530137313 	 Accuracy: 0.4028683181225554
Delta: 0.0006577643957781502 	  Loss: 1.5350041450087766 	 Accuracy: 0.4041720990873533
Delta: 0.00110836594632273 	  Loss: 1.5347834388267572 	 Accuracy: 0.4041720990873533
Delta: 2.1448621522276457e-05 	  Loss: 1.534709021564793 	 Accuracy: 0.4041720990873533
Delta: 7.618941960136208e-05 	  Loss: 1.5350006083274805 	 Accuracy: 0.4041720990873533
Delta: 0.0009129814286422791 	  Loss: 1.5349800347893323 	 Accuracy: 0.4041720990873533
Delta: 0.0006560307620991999 	  Loss: 1.5350950388555313 	 Accuracy: 0.4041720990873533
Delta: 4.661641318285817e-07 	  Loss: 1.5350939116213729 	 Accuracy: 0.4015645371577575
Delta: 6.384071328854596e-05 	  Loss: 1.534835673595652 	 Accuracy: 0.4041720990873533
Delta: 5.164518615928504e-05 	  Loss: 1.5349838746638964 	 Accuracy: 0.40547588005215124
Delta: 3.32344311397408e-05 	  Loss: 1.5349313921177745 	 Accuracy: 0.4041720990873533
Delta: 0.021031668831045607 	  Loss: 2.1510868091308675 	 Accuracy: 0.21642764015645372
Delta: 0.018851892130954662 	  Loss: 2.0520075876408534 	 Accuracy: 0.37809647979139505
Delta: 0.017137686212089318 	  Loss: 1.9064005065880671 	 Accuracy: 0.4602346805736636
Delta: 0.014884694123282399 	  Loss: 1.7796300782291539 	 Accuracy: 0.40547588005215124
Delta: 0.013358447356034123 	  Loss: 1.6898993209945283 	 Accuracy: 0.3650586701434159
Delta: 0.011566478295985802 	  Loss: 1.6338846320553695 	 Accuracy: 0.38070404172099087
Delta: 0.010027745868358586 	  Loss: 1.6015108173377834 	 Accuracy: 0.37809647979139505
Delta: 0.008247100424647134 	  Loss: 1.5846106871161272 	 Accuracy: 0.3754889178617992
Delta: 0.007515830637859428 	  Loss: 1.574549438605448 	 Accuracy: 0.39374185136897

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006554357608027111 	  Loss: 1.5697185360743577 	 Accuracy: 0.3898305084745763
Delta: 0.006469658235544207 	  Loss: 1.5667738974399046 	 Accuracy: 0.39374185136897
Delta: 0.005094802764563379 	  Loss: 1.5650470739139974 	 Accuracy: 0.39374185136897
Delta: 0.004552983618920915 	  Loss: 1.5640584854242867 	 Accuracy: 0.3859191655801825
Delta: 0.0037197088281550094 	  Loss: 1.5636146361940022 	 Accuracy: 0.3963494132985658
Delta: 0.0034395108562375342 	  Loss: 1.5633816624451837 	 Accuracy: 0.3963494132985658
Delta: 0.003780304454645443 	  Loss: 1.5632808605080433 	 Accuracy: 0.39374185136897
Delta: 0.0010536087652005333 	  Loss: 1.5632150518690546 	 Accuracy: 0.38852672750977835
Delta: 0.0016854287788286093 	  Loss: 1.563285042884435 	 Accuracy: 0.3924380704041721
Delta: 0.0020808388842259245 	  Loss: 1.5632823051089377 	 Accuracy: 0.39113428943937417
Delta: 0.002868722802267275 	  Loss: 1.5633248716304344 	 Accuracy: 0.39113428943937417
Delta: 0.0023642202058349457 	  Loss: 1.5634616833416426 	 Accuracy: 0.39113428943937417
Delta: 0.0009904332408595471 	  Loss: 1.5634661946863655 	 Accuracy: 0.3898305084745763
Delta: 2.4975068353794122e-05 	  Loss: 1.5634559048680656 	 Accuracy: 0.39113428943937417
Delta: 0.0007176281828517604 	  Loss: 1.5634993522664082 	 Accuracy: 0.3898305084745763
Delta: 1.8481848727160432e-05 	  Loss: 1.563529673727877 	 Accuracy: 0.39113428943937417
Delta: 1.4197968675275886e-05 	  Loss: 1.5635051346751132 	 Accuracy: 0.39113428943937417
Delta: 2.3014734126607924e-05 	  Loss: 1.5634617947373002 	 Accuracy: 0.39113428943937417
Delta: 0.0009530229469846246 	  Loss: 1.5634249210802496 	 Accuracy: 0.39113428943937417
Delta: 0.0013342959903155176 	  Loss: 1.5634163010355326 	 Accuracy: 0.39113428943937417
Delta: 1.2609044707920165e-05 	  Loss: 1.5633974215292519 	 Accuracy: 0.39113428943937417
Delta: 5.9882439817409374e-05 	  Loss: 1.5635695484696255 	 Accuracy: 0.39113428943937417
Delta: 0.0015741772625649797 	  Loss: 1.563525133526519 	 Accuracy: 0.39113428943937417
Delta: 1.874108346132416e-05 	  Loss: 1.563494720232365 	 Accuracy: 0.39113428943937417
Delta: 1.9815261562662333e-05 	  Loss: 1.5634895634384693 	 Accuracy: 0.39113428943937417
Delta: 0.0005194960339559316 	  Loss: 1.563509164011031 	 Accuracy: 0.39113428943937417
Delta: 3.1013950607266294e-05 	  Loss: 1.5635277757098707 	 Accuracy: 0.3924380704041721
Delta: 0.0007381260933338146 	  Loss: 1.5635088432163833 	 Accuracy: 0.39113428943937417
Delta: 0.0005633607415183649 	  Loss: 1.5634553248744887 	 Accuracy: 0.3898305084745763
Delta: 6.377391562979391e-05 	  Loss: 1.5637277284662807 	 Accuracy: 0.38852672750977835
Delta: 0.001273467757902255 	  Loss: 1.563556578020556 	 Accuracy: 0.39113428943937417
Delta: 0.0008234936699865989 	  Loss: 1.5635547532603655 	 Accuracy: 0.39113428943937417
Delta: 5.429028711365508e-05 	  Loss: 1.5634687038717976 	 Accuracy: 0.39113428943937417
Delta: 2.0322406005190943e-05 	  Loss: 1.5635073750794128 	 Accuracy: 0.39113428943937417
Delta: 0.0006379026343027888 	  Loss: 1.5634813878405205 	 Accuracy: 0.39113428943937417
Delta: 3.7187373708746845e-05 	  Loss: 1.5635247656804827 	 Accuracy: 0.39113428943937417
Delta: 4.446420896747477e-05 	  Loss: 1.5634847971524133 	 Accuracy: 0.3898305084745763
Delta: 0.0009023831843785715 	  Loss: 1.563563199571269 	 Accuracy: 0.39113428943937417
Delta: 0.0005804814442899666 	  Loss: 1.5634609150577807 	 Accuracy: 0.39113428943937417
Delta: 6.078247460200889e-05 	  Loss: 1.5634471792191178 	 Accuracy: 0.3924380704041721
Delta: 0.0008361214568315604 	  Loss: 1.5636608827408738 	 Accuracy: 0.39113428943937417
Delta: 7.463837928748954e-05 	  Loss: 1.563521008860889 	 Accuracy: 0.39113428943937417
Delta: 2.961510657534766e-05 	  Loss: 1.5634817110572934 	 Accuracy: 0.3924380704041721
Delta: 0.0005721203284861264 	  Loss: 1.5634573474951958 	 Accuracy: 0.39113428943937417
Delta: 2.3976467121495492e-05 	  Loss: 1.5634514873858298 	 Accuracy: 0.39113428943937417
Delta: 4.343142656379884e-05 	  Loss: 1.5635884574215233 	 Accuracy: 0.3924380704041721
Delta: 0.000533240614919954 	  Loss: 1.5634531877556563 	 Accuracy: 0.39113428943937417
Delta: 0.0005136122722857578 	  Loss: 1.5635093458586207 	 Accuracy: 0.39113428943937417
Delta: 3.8642982149413515e-05 	  Loss: 1.5634505570408535 	 Accuracy: 0.39113428943937417
Delta: 3.864402862920717e-05 	  Loss: 1.563509745606275 	 Accuracy: 0.39113428943937417
Delta: 1.0233456776345477e-05 	  Loss: 1.563488843775416 	 Accuracy: 0.39113428943937417
Delta: 1.0602738903627357e-05 	  Loss: 1.563506341234607 	 Accuracy: 0.39113428943937417
Delta: 2.1960648784304478e-05 	  Loss: 1.5634797580542443 	 Accuracy: 0.39113428943937417
Delta: 2.2463362073574097e-05 	  Loss: 1.5635089160716422 	 Accuracy: 0.39113428943937417
Delta: 2.5663111925625267e-05 	  Loss: 1.5634667666416682 	 Accuracy: 0.39113428943937417
Delta: 0.0005364555125882284 	  Loss: 1.5634653883316842 	 Accuracy: 0.39113428943937417
Delta: 4.8278522269419824e-05 	  Loss: 1.563471047979437 	 Accuracy: 0.39113428943937417
Delta: 0.0014197702727736415 	  Loss: 1.5634386886752338 	 Accuracy: 0.38852672750977835
Delta: 0.0007067162442950166 	  Loss: 1.563475560836954 	 Accuracy: 0.39113428943937417
Delta: 0.0015201660201537557 	  Loss: 1.563463946410402 	 Accuracy: 0.39113428943937417
Delta: 4.012952010662477e-05 	  Loss: 1.5634837392950438 	 Accuracy: 0.39374185136897
Delta: 2.004302441893748e-05 	  Loss: 1.5635023153603798 	 Accuracy: 0.39113428943937417
Delta: 0.0016003956037526571 	  Loss: 1.5633844876104832 	 Accuracy: 0.39113428943937417
Delta: 0.0015683691167332242 	  Loss: 1.563450849345645 	 Accuracy: 0.3898305084745763
Delta: 1.910001451146254e-05 	  Loss: 1.563476931696812 	 Accuracy: 0.39113428943937417
Delta: 4.207040745692846e-05 	  Loss: 1.5635089457147946 	 Accuracy: 0.36766623207301175
Delta: 0.006519094893650215 	  Loss: 1.5699200417441257 	 Accuracy: 0.3728813559322034
Delta: 0.005994701442262124 	  Loss: 1.5671944736961412 	 Accuracy: 0.38461538461538464
Delta: 0.0029641279569450436 	  Loss: 1.5672639554906316 	 Accuracy: 0.3859191655801825
Delta: 0.002484144870559749 	  Loss: 1.566733325111512 	 Accuracy: 0.38461538461538464
Delta: 0.00274771492630287 	  Loss: 1.5669951707469645 	 Accuracy: 0.38461538461538464
Delta: 0.002026859019531658 	  Loss: 1.5671683286124476 	 Accuracy: 0.3859191655801825
Delta: 0.001430121923588965 	  Loss: 1.5674892376899672 	 Accuracy: 0.38461538461538464
Delta: 0.0029174696641885035 	  Loss: 1.5678635145830047 	 Accuracy: 0.39374185136897
Delta: 0.004598251214146105 	  Loss: 1.5676860804083992 	 Accuracy: 0.363754889178618
Delta: 0.004289920056246227 	  Loss: 1.5665245727975399 	 Accuracy: 0.38722294654498046
Delta: 0.0027060253483483223 	  Loss: 1.5662696801605593 	 Accuracy: 0.38722294654498046
Delta: 0.003485315323447876 	  Loss: 1.5658968380489986 	 Accuracy: 0.38722294654498046
Delta: 0.0007266642688240302 	  Loss: 1.565832158539055 	 Accuracy: 0.38722294654498046
Delta: 3.525324746044051e-05 	  Loss: 1.565899432165673 	 Accuracy: 0.3898305084745763
Delta: 0.0015685854640828504 	  Loss: 1.5659015392140785 	 Accuracy: 0.3859191655801825
Delta: 0.0017029389429031724 	  Loss: 1.5660082349426765 	 Accuracy: 0.38461538461538464
Delta: 0.0005070399836724209 	  Loss: 1.5659559040817006 	 Accuracy: 0.38722294654498046
Delta: 0.0020881635974352337 	  Loss: 1.566284804981561 	 Accuracy: 0.3859191655801825
Delta: 4.9611924410758854e-05 	  Loss: 1.5662548337362816 	 Accuracy: 0.38722294654498046
Delta: 0.0019083396600861082 	  Loss: 1.5664733903981478 	 Accuracy: 0.38722294654498046
Delta: 0.0010145792428494903 	  Loss: 1.5664593431788556 	 Accuracy: 0.38722294654498046
Delta: 0.0010861254838837287 	  Loss: 1.5665108840599942 	 Accuracy: 0.38722294654498046
Delta: 4.373792232534724e-05 	  Loss: 1.5665624633302704 	 Accuracy: 0.38722294654498046
Delta: 0.0032498061715985948 	  Loss: 1.5668110440810725 	 Accuracy: 0.3859191655801825
Delta: 0.0021556741559580496 	  Loss: 1.5666695367569936 	 Accuracy: 0.38070404172099087
Delta: 0.020927042037219516 	  Loss: 2.151935439799265 	 Accuracy: 0.20599739243807041
Delta: 0.019251773816887193 	  Loss: 2.0515419159560397 	 Accuracy: 0.30638852672750977
Delta: 0.016882569201443747 	  Loss: 1.8921389457112414 	 Accuracy: 0.3859191655801825
Delta: 0.014902349994286261 	  Loss: 1.7628255376209505 	 Accuracy: 0.34028683181225555
Delta: 0.013954140457515347 	  Loss: 1.6775433255105128 	 Accuracy: 0.3155149934810952
Delta: 0.012775770718631006 	  Loss: 1.616895252941889 	 Accuracy: 0.31029986962190353
Delta: 0.010659697942465522 	  Loss: 1.579513337100789 	 Accuracy: 0.30638852672750977
Delta: 0.00806310140262129 	  Loss: 1.5615554873284425 	 Accuracy: 0.30638852672750977

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006908500249091051 	  Loss: 1.55415659083435 	 Accuracy: 0.3050847457627119
Delta: 0.0056582943498825 	  Loss: 1.5504250729738922 	 Accuracy: 0.30638852672750977
Delta: 0.0043466466195319995 	  Loss: 1.549000715097043 	 Accuracy: 0.3050847457627119
Delta: 0.005563489988826652 	  Loss: 1.549200194394621 	 Accuracy: 0.30638852672750977
Delta: 0.0026710712634696546 	  Loss: 1.5489670883177644 	 Accuracy: 0.3050847457627119
Delta: 0.002012671253900396 	  Loss: 1.54892663791442 	 Accuracy: 0.30638852672750977
Delta: 0.002914657278985691 	  Loss: 1.5488230192036927 	 Accuracy: 0.30638852672750977
Delta: 0.0033146378761269722 	  Loss: 1.5490458625133892 	 Accuracy: 0.30638852672750977
Delta: 0.002681223520964355 	  Loss: 1.5490122876266847 	 Accuracy: 0.30638852672750977
Delta: 0.002217960833477235 	  Loss: 1.5487494947935367 	 Accuracy: 0.3076923076923077
Delta: 0.0007689755489909684 	  Loss: 1.5486646949136222 	 Accuracy: 0.3050847457627119
Delta: 0.0014839287538677979 	  Loss: 1.548648340391623 	 Accuracy: 0.30638852672750977
Delta: 0.0032434972499657193 	  Loss: 1.5485993274087635 	 Accuracy: 0.30638852672750977
Delta: 0.0008208003139846616 	  Loss: 1.54847980990063 	 Accuracy: 0.30638852672750977
Delta: 3.0749228040171456e-05 	  Loss: 1.5485710628244311 	 Accuracy: 0.3076923076923077
Delta: 2.8578872738227345e-05 	  Loss: 1.5485398707288485 	 Accuracy: 0.30638852672750977
Delta: 2.679292783854194e-05 	  Loss: 1.5485841301987777 	 Accuracy: 0.30378096479791394
Delta: 0.002133769496822918 	  Loss: 1.548751001559077 	 Accuracy: 0.30638852672750977
Delta: 0.001270150631960757 	  Loss: 1.5488576785765586 	 Accuracy: 0.31290743155149936
Delta: 5.4958076606582316e-05 	  Loss: 1.548582536793512 	 Accuracy: 0.3076923076923077
Delta: 0.0012653016187250323 	  Loss: 1.5485417532476848 	 Accuracy: 0.30638852672750977
Delta: 0.000819333148093959 	  Loss: 1.548549765734253 	 Accuracy: 0.30638852672750977
Delta: 3.010169753076885e-05 	  Loss: 1.5485529052232438 	 Accuracy: 0.3076923076923077
Delta: 6.241675530751007e-06 	  Loss: 1.5485579176078832 	 Accuracy: 0.30638852672750977
Delta: 0.0014309997873319918 	  Loss: 1.548619205742988 	 Accuracy: 0.30378096479791394
Delta: 0.000557293425346049 	  Loss: 1.5485651778372973 	 Accuracy: 0.3050847457627119
Delta: 0.0021175936518237643 	  Loss: 1.5486600020378496 	 Accuracy: 0.3076923076923077
Delta: 0.0010911621759635433 	  Loss: 1.5485285920041658 	 Accuracy: 0.30638852672750977
Delta: 0.0014808176066382628 	  Loss: 1.5485622006752826 	 Accuracy: 0.30638852672750977
Delta: 3.665868980097726e-05 	  Loss: 1.5487988993363815 	 Accuracy: 0.30638852672750977
Delta: 4.660771748734051e-05 	  Loss: 1.5489813674639135 	 Accuracy: 0.30638852672750977
Delta: 4.074933707567182e-05 	  Loss: 1.5489679691271454 	 Accuracy: 0.30638852672750977
Delta: 2.45595416110621e-05 	  Loss: 1.5489391466086553 	 Accuracy: 0.30638852672750977
Delta: 8.051950749690964e-05 	  Loss: 1.5484023483445906 	 Accuracy: 0.30638852672750977
Delta: 5.8232206702305785e-05 	  Loss: 1.5483548679514414 	 Accuracy: 0.30638852672750977
Delta: 0.0018820808476548829 	  Loss: 1.5481507273351744 	 Accuracy: 0.30638852672750977
Delta: 0.00011791954628797926 	  Loss: 1.5489068130772412 	 Accuracy: 0.30638852672750977
Delta: 1.1885834013083297e-05 	  Loss: 1.5488893444069216 	 Accuracy: 0.30638852672750977
Delta: 2.61934287232457e-05 	  Loss: 1.5489927730601225 	 Accuracy: 0.30638852672750977
Delta: 0.0005848537759896966 	  Loss: 1.5483953928771659 	 Accuracy: 0.30638852672750977
Delta: 5.566123861934265e-05 	  Loss: 1.5485484845710031 	 Accuracy: 0.30638852672750977
Delta: 3.223770092295233e-08 	  Loss: 1.5485484550550086 	 Accuracy: 0.30638852672750977
converged at iter  49
Delta: 0.020882269014811373 	  Loss: 2.152025933174902 	 Accuracy: 0.2046936114732725
Delta: 0.01920880861730028 	  Loss: 2.045143678853152 	 Accuracy: 0.31421121251629724
Delta: 0.016907500233604836 	  Loss: 1.8815774431729877 	 Accuracy: 0.47196870925684486
Delta: 0.014928438899060453 	  Loss: 1.7411654365997782 	 Accuracy: 0.4876140808344198
Delta: 0.013244643052894469 	  Loss: 1.645260987495616 	 Accuracy: 0.4602346805736636
Delta: 0.010876196434073188 	  Loss: 1.597542626438296 	 Accuracy: 0.4445893089960887
Delta: 0.009339021332798026 	  Loss: 1.5760144127272455 	 Accuracy: 0.423728813559322
Delta: 0.008753561482513912 	  Loss: 1.5653911378607335 	 Accuracy: 0.4002607561929596

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007322678314683693 	  Loss: 1.5588982096586745 	 Accuracy: 0.4041720990873533
Delta: 0.005694846637469415 	  Loss: 1.555886734194765 	 Accuracy: 0.40547588005215124
Delta: 0.004776977410860127 	  Loss: 1.5545059495629048 	 Accuracy: 0.409387222946545
Delta: 0.003392636144803586 	  Loss: 1.5537564739445457 	 Accuracy: 0.4067796610169492
Delta: 0.002973135208007837 	  Loss: 1.553527928983454 	 Accuracy: 0.4067796610169492
Delta: 0.0024249212649385217 	  Loss: 1.5534527063410308 	 Accuracy: 0.409387222946545
Delta: 0.0029889108907965515 	  Loss: 1.5533778323315213 	 Accuracy: 0.409387222946545
Delta: 0.001360956641065854 	  Loss: 1.5533344572954184 	 Accuracy: 0.40808344198174706
Delta: 0.003019072516465236 	  Loss: 1.5533728909670697 	 Accuracy: 0.409387222946545
Delta: 0.0021690172250996504 	  Loss: 1.5535488679544516 	 Accuracy: 0.4106910039113429
Delta: 0.0016195643858270359 	  Loss: 1.5536653614872624 	 Accuracy: 0.4106910039113429
Delta: 1.9658648719755062e-05 	  Loss: 1.55368068919178 	 Accuracy: 0.4106910039113429
Delta: 0.0023870374471436037 	  Loss: 1.553736554373211 	 Accuracy: 0.4106910039113429
Delta: 0.0026818553184219484 	  Loss: 1.5537849645657413 	 Accuracy: 0.409387222946545
Delta: 6.021694615678786e-05 	  Loss: 1.553780559186486 	 Accuracy: 0.409387222946545
Delta: 0.00205847360071834 	  Loss: 1.5539991841763459 	 Accuracy: 0.4106910039113429
Delta: 0.002043003361804266 	  Loss: 1.5539148025957807 	 Accuracy: 0.409387222946545
Delta: 0.001459542599852833 	  Loss: 1.553702039345826 	 Accuracy: 0.409387222946545
Delta: 0.0016098583391399544 	  Loss: 1.5537578763680342 	 Accuracy: 0.409387222946545
Delta: 1.7858607737648625e-05 	  Loss: 1.5538326485119707 	 Accuracy: 0.40808344198174706
Delta: 1.5380342095333085e-05 	  Loss: 1.553812661201074 	 Accuracy: 0.4041720990873533
Delta: 0.00052344104545129 	  Loss: 1.5539062184707018 	 Accuracy: 0.41199478487614083
Delta: 0.0020355460085311216 	  Loss: 1.5538459419809734 	 Accuracy: 0.4106910039113429
Delta: 0.002475159688923344 	  Loss: 1.5536434125909815 	 Accuracy: 0.4106910039113429
Delta: 0.0032950000463276485 	  Loss: 1.5537692380185242 	 Accuracy: 0.41199478487614083
Delta: 0.0014704983256376097 	  Loss: 1.5536951248614121 	 Accuracy: 0.4106910039113429
Delta: 0.00169060412610223 	  Loss: 1.5539077072250116 	 Accuracy: 0.4106910039113429
Delta: 0.001390165715364895 	  Loss: 1.5541062150881657 	 Accuracy: 0.409387222946545
Delta: 0.003524855729040638 	  Loss: 1.5544204325326212 	 Accuracy: 0.409387222946545
Delta: 0.0005396812610144543 	  Loss: 1.5544387757375058 	 Accuracy: 0.409387222946545
Delta: 1.6908888914337203e-05 	  Loss: 1.5544523696418642 	 Accuracy: 0.4106910039113429
Delta: 0.0010597790166596553 	  Loss: 1.5543184297665653 	 Accuracy: 0.4106910039113429
Delta: 0.001980694335499861 	  Loss: 1.5542219191241684 	 Accuracy: 0.409387222946545
Delta: 0.0014743508772596951 	  Loss: 1.5543739676971318 	 Accuracy: 0.41199478487614083
Delta: 4.319094716581376e-05 	  Loss: 1.5542657461797678 	 Accuracy: 0.41199478487614083
Delta: 0.000533253094059214 	  Loss: 1.5541460516077574 	 Accuracy: 0.4106910039113429
Delta: 0.0008357291328903986 	  Loss: 1.554435241705166 	 Accuracy: 0.4106910039113429
Delta: 0.004574193607627341 	  Loss: 1.553682439616523 	 Accuracy: 0.40808344198174706
Delta: 0.0023380657044844624 	  Loss: 1.5543525649903105 	 Accuracy: 0.4106910039113429
Delta: 0.0015585820247033702 	  Loss: 1.5540693721565337 	 Accuracy: 0.41460234680573665
Delta: 0.003966919050413113 	  Loss: 1.5544922422409737 	 Accuracy: 0.4106910039113429
Delta: 0.0018492649588270345 	  Loss: 1.5542529064710255 	 Accuracy: 0.4106910039113429
Delta: 0.0007574560465201349 	  Loss: 1.5544438328889756 	 Accuracy: 0.4106910039113429
Delta: 0.0007353793518451551 	  Loss: 1.5542934366688999 	 Accuracy: 0.4106910039113429
Delta: 0.001435731908649141 	  Loss: 1.5543185312471546 	 Accuracy: 0.4106910039113429
Delta: 0.0008254651300842359 	  Loss: 1.5545430260275506 	 Accuracy: 0.4106910039113429
Delta: 3.4269611465020165e-05 	  Loss: 1.55450212391865 	 Accuracy: 0.4106910039113429
Delta: 0.0005253970149970878 	  Loss: 1.554563630689269 	 Accuracy: 0.409387222946545
Delta: 0.003840936377869298 	  Loss: 1.555004783753768 	 Accuracy: 0.4067796610169492
Delta: 0.002512661821782451 	  Loss: 1.5556276741544584 	 Accuracy: 0.409387222946545
Delta: 0.0025539748572812244 	  Loss: 1.55468919328069 	 Accuracy: 0.40808344198174706
Delta: 0.0012705791467698103 	  Loss: 1.5544347971988994 	 Accuracy: 0.409387222946545
Delta: 0.0023633312471173233 	  Loss: 1.5550275984364095 	 Accuracy: 0.409387222946545
Delta: 0.0017973126826590388 	  Loss: 1.5544219936719461 	 Accuracy: 0.409387222946545
Delta: 0.001581182090463058 	  Loss: 1.5546573671868722 	 Accuracy: 0.4106910039113429
Delta: 0.002999027863044854 	  Loss: 1.5550485774302922 	 Accuracy: 0.409387222946545
Delta: 0.003304924019996593 	  Loss: 1.5553327089167577 	 Accuracy: 0.40808344198174706
Delta: 0.0031828297992390108 	  Loss: 1.5556090961956959 	 Accuracy: 0.409387222946545
Delta: 0.0017600233150023219 	  Loss: 1.5556721614722773 	 Accuracy: 0.409387222946545
Delta: 0.0029465618134438634 	  Loss: 1.5557784144503162 	 Accuracy: 0.4041720990873533
Delta: 0.0005222328188892111 	  Loss: 1.5559274234200018 	 Accuracy: 0.409387222946545
Delta: 3.17044138627462e-05 	  Loss: 1.5557542817376055 	 Accuracy: 0.409387222946545
Delta: 1.4761040087722646e-05 	  Loss: 1.5557735301029954 	 Accuracy: 0.40808344198174706
Delta: 4.80027036640521e-05 	  Loss: 1.555817279338593 	 Accuracy: 0.409387222946545
Delta: 0.0005434873342186797 	  Loss: 1.5556975097764374 	 Accuracy: 0.40808344198174706
Delta: 0.0015453744281481044 	  Loss: 1.5560066881391152 	 Accuracy: 0.409387222946545
Delta: 0.000539288881536228 	  Loss: 1.555696597651009 	 Accuracy: 0.409387222946545
Delta: 6.514066697324068e-05 	  Loss: 1.5557675840516336 	 Accuracy: 0.4067796610169492
Delta: 0.0032185741823964964 	  Loss: 1.5563032989095444 	 Accuracy: 0.40808344198174706
Delta: 0.002518221746213348 	  Loss: 1.5563431104338146 	 Accuracy: 0.40808344198174706
Delta: 0.001337533578979878 	  Loss: 1.556526094845346 	 Accuracy: 0.4067796610169492
Delta: 0.0014951373148280153 	  Loss: 1.5564589684338663 	 Accuracy: 0.40808344198174706
Delta: 0.0029679535424652456 	  Loss: 1.556265181195966 	 Accuracy: 0.4028683181225554
Delta: 0.0008268340294109532 	  Loss: 1.5564755542459556 	 Accuracy: 0.40808344198174706
Delta: 0.000524931514811771 	  Loss: 1.556240671472359 	 Accuracy: 0.40808344198174706
Delta: 1.5816895946857658e-05 	  Loss: 1.5562493803727735 	 Accuracy: 0.40808344198174706
Delta: 4.761860951871068e-05 	  Loss: 1.556372125213261 	 Accuracy: 0.40808344198174706
Delta: 0.0012763589690649817 	  Loss: 1.5564163077654456 	 Accuracy: 0.40808344198174706
Delta: 5.433325862647859e-05 	  Loss: 1.5565289344550504 	 Accuracy: 0.40808344198174706
Delta: 0.0005461593951148043 	  Loss: 1.5563125945498235 	 Accuracy: 0.40808344198174706
Delta: 0.0005540394507560997 	  Loss: 1.5564221554086273 	 Accuracy: 0.4067796610169492
Delta: 5.0193255446692586e-05 	  Loss: 1.5562556904635885 	 Accuracy: 0.40808344198174706
Delta: 3.2573842996687844e-05 	  Loss: 1.5562409332963822 	 Accuracy: 0.40808344198174706
Delta: 1.7314760630928194e-05 	  Loss: 1.5562504990533792 	 Accuracy: 0.40808344198174706
Delta: 3.187788246628058e-05 	  Loss: 1.5563259052271037 	 Accuracy: 0.40808344198174706
Delta: 0.0028422088007394384 	  Loss: 1.5562570338976387 	 Accuracy: 0.40808344198174706
Delta: 7.278658515131532e-05 	  Loss: 1.5563799398506066 	 Accuracy: 0.40808344198174706
Delta: 6.244720174680436e-05 	  Loss: 1.5564477625661801 	 Accuracy: 0.40547588005215124
Delta: 5.056970168405554e-05 	  Loss: 1.5564483892576755 	 Accuracy: 0.40808344198174706
Delta: 5.688387713199465e-05 	  Loss: 1.556452228654928 	 Accuracy: 0.4015645371577575
Delta: 0.0036225242267126463 	  Loss: 1.556451743487488 	 Accuracy: 0.40808344198174706
Delta: 0.0016620974087269938 	  Loss: 1.5566939049511366 	 Accuracy: 0.40808344198174706
Delta: 0.021053342332267844 	  Loss: 2.150146756602304 	 Accuracy: 0.20208604954367665
Delta: 0.019195725108946602 	  Loss: 2.036563281044863 	 Accuracy: 0.34810951760104303
Delta: 0.01718418758279444 	  Loss: 1.85656308916063 	 Accuracy: 0.34159061277705344
Delta: 0.01478722485844707 	  Loss: 1.7157276613651606 	 Accuracy: 0.33116036505867014
Delta: 0.012576766321862096 	  Loss: 1.6398003012957592 	 Accuracy: 0.3259452411994785
Delta: 0.01100342925199338 	  Loss: 1.605661996419268 	 Accuracy: 0.33116036505867014
Delta: 0.008834435951747646 	  Loss: 1.5913679684496929 	 Accuracy: 0.34028683181225555

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007543443632585227 	  Loss: 1.5865257163542257 	 Accuracy: 0.3468057366362451
Delta: 0.00620806123363078 	  Loss: 1.583839246704058 	 Accuracy: 0.3285528031290743
Delta: 0.005875766145788492 	  Loss: 1.5828361398845567 	 Accuracy: 0.3455019556714472
Delta: 0.005619189795040238 	  Loss: 1.582087071665493 	 Accuracy: 0.34419817470664926
Delta: 0.004765867593166319 	  Loss: 1.5821580181092774 	 Accuracy: 0.34419817470664926
Delta: 0.002518053357238979 	  Loss: 1.5819988227990733 	 Accuracy: 0.34419817470664926
Delta: 0.0031406273779123464 	  Loss: 1.5824978932853824 	 Accuracy: 0.3428943937418514
Delta: 0.0020082931833593 	  Loss: 1.582504117672578 	 Accuracy: 0.3389830508474576
Delta: 0.001995324265688068 	  Loss: 1.5822383453474718 	 Accuracy: 0.34159061277705344
Delta: 0.002933330993740252 	  Loss: 1.5823850608429784 	 Accuracy: 0.34419817470664926
Delta: 0.0027693679734787664 	  Loss: 1.582186405393204 	 Accuracy: 0.3428943937418514
Delta: 0.0027903921352951406 	  Loss: 1.5822638271414922 	 Accuracy: 0.34419817470664926
Delta: 0.0037459167712392337 	  Loss: 1.582356638284832 	 Accuracy: 0.3468057366362451
Delta: 0.0040331386002673214 	  Loss: 1.5823579236351188 	 Accuracy: 0.34419817470664926
Delta: 0.001162713840231095 	  Loss: 1.5822730258895628 	 Accuracy: 0.3455019556714472
Delta: 0.0028842294504531057 	  Loss: 1.582235908202756 	 Accuracy: 0.3455019556714472
Delta: 0.0013693290584098695 	  Loss: 1.58225808308132 	 Accuracy: 0.34419817470664926
Delta: 1.850413603565093e-05 	  Loss: 1.5822041466423746 	 Accuracy: 0.34419817470664926
Delta: 1.7109996695568162e-05 	  Loss: 1.5821785760395306 	 Accuracy: 0.3455019556714472
Delta: 2.497468842197103e-05 	  Loss: 1.5822787129664984 	 Accuracy: 0.3468057366362451
Delta: 0.0006479788856101655 	  Loss: 1.5821702304404925 	 Accuracy: 0.3455019556714472
Delta: 3.375530956917231e-05 	  Loss: 1.5822314197659817 	 Accuracy: 0.3455019556714472
Delta: 2.635659709485458e-05 	  Loss: 1.5822555241690082 	 Accuracy: 0.3455019556714472
Delta: 0.0005410863937059374 	  Loss: 1.5822091584929514 	 Accuracy: 0.34419817470664926
Delta: 3.675850013673611e-05 	  Loss: 1.5821557839704132 	 Accuracy: 0.3428943937418514
Delta: 0.0008834546751776617 	  Loss: 1.5822099577088506 	 Accuracy: 0.3455019556714472
Delta: 3.60711844564526e-05 	  Loss: 1.5821889196427408 	 Accuracy: 0.34419817470664926
Delta: 4.8077489282103386e-05 	  Loss: 1.5822125131407367 	 Accuracy: 0.3455019556714472
Delta: 1.612651300885914e-05 	  Loss: 1.5821801394128912 	 Accuracy: 0.3455019556714472
Delta: 3.1833162532140434e-05 	  Loss: 1.582283215620151 	 Accuracy: 0.34419817470664926
Delta: 0.001132823147576083 	  Loss: 1.5821613027390695 	 Accuracy: 0.3468057366362451
Delta: 0.0012233318699418688 	  Loss: 1.5821359772255636 	 Accuracy: 0.3455019556714472
Delta: 0.0025338098185349123 	  Loss: 1.5822506113996706 	 Accuracy: 0.34419817470664926
Delta: 0.0011468366648690815 	  Loss: 1.5821748541726266 	 Accuracy: 0.3455019556714472
Delta: 3.128768532267127e-05 	  Loss: 1.5822127259554835 	 Accuracy: 0.34419817470664926
Delta: 2.212275515886938e-05 	  Loss: 1.5821913641066216 	 Accuracy: 0.3455019556714472
Delta: 3.9722997565260225e-05 	  Loss: 1.5821773778866821 	 Accuracy: 0.3468057366362451
Delta: 1.556762731931302e-05 	  Loss: 1.5821359094021599 	 Accuracy: 0.34810951760104303
Delta: 0.0009677163958061876 	  Loss: 1.5822211033000437 	 Accuracy: 0.3455019556714472
Delta: 2.36636640443742e-05 	  Loss: 1.5822552818155737 	 Accuracy: 0.3455019556714472
Delta: 0.0005325766155092937 	  Loss: 1.582300402059285 	 Accuracy: 0.34419817470664926
Delta: 3.824939247814843e-05 	  Loss: 1.5822610903048064 	 Accuracy: 0.3455019556714472
Delta: 2.6891816627450663e-05 	  Loss: 1.5821988430818477 	 Accuracy: 0.34419817470664926
Delta: 3.4289996324914555e-05 	  Loss: 1.582249968129306 	 Accuracy: 0.34419817470664926
Delta: 3.56178123888012e-05 	  Loss: 1.5822086182870523 	 Accuracy: 0.34419817470664926
Delta: 1.1777778856756781e-05 	  Loss: 1.582215479042337 	 Accuracy: 0.3455019556714472
Delta: 0.0012294878451538788 	  Loss: 1.582108441922955 	 Accuracy: 0.3455019556714472
Delta: 4.4776905501430015e-05 	  Loss: 1.5822221564915315 	 Accuracy: 0.3455019556714472
Delta: 1.6991267865385953e-05 	  Loss: 1.5822358235170042 	 Accuracy: 0.3455019556714472
Delta: 2.064498460166822e-05 	  Loss: 1.5822259148212923 	 Accuracy: 0.3533246414602347
Delta: 3.048900302022214e-05 	  Loss: 1.582212203333563 	 Accuracy: 0.3468057366362451
Delta: 3.5380685978998264e-06 	  Loss: 1.5822195929465939 	 Accuracy: 0.34419817470664926
Delta: 0.0009503572741984225 	  Loss: 1.5822078159014688 	 Accuracy: 0.3455019556714472
Delta: 0.0012045809358204862 	  Loss: 1.5822439486395479 	 Accuracy: 0.34159061277705344
Delta: 3.514060185140862e-05 	  Loss: 1.5822602762666798 	 Accuracy: 0.3468057366362451
Delta: 0.0005554698939385958 	  Loss: 1.5821294060486495 	 Accuracy: 0.3455019556714472
Delta: 2.117278917985954e-05 	  Loss: 1.5821938457542164 	 Accuracy: 0.3428943937418514
Delta: 0.0009334295832754634 	  Loss: 1.5822548036297226 	 Accuracy: 0.34419817470664926
Delta: 2.5957140559869946e-05 	  Loss: 1.5821915679706826 	 Accuracy: 0.3428943937418514
Delta: 0.003825795594587709 	  Loss: 1.5822380800132705 	 Accuracy: 0.35723598435462844
Delta: 0.0017831864798813725 	  Loss: 1.5820334836743872 	 Accuracy: 0.34419817470664926
Delta: 0.0016193514792416847 	  Loss: 1.582128262024853 	 Accuracy: 0.34419817470664926
Delta: 0.0005306842592773033 	  Loss: 1.5821813722488596 	 Accuracy: 0.34419817470664926
Delta: 0.003538915704989753 	  Loss: 1.581971468726849 	 Accuracy: 0.3455019556714472
Delta: 0.0006305295724877823 	  Loss: 1.5819365169010862 	 Accuracy: 0.3455019556714472
Delta: 2.6099320996618096e-06 	  Loss: 1.5819349722167155 	 Accuracy: 0.3455019556714472
Delta: 0.0009609094391276897 	  Loss: 1.5819814981882083 	 Accuracy: 0.34159061277705344
Delta: 0.0006811250771996479 	  Loss: 1.5821180738209124 	 Accuracy: 0.3468057366362451
Delta: 6.949410024202143e-05 	  Loss: 1.5819451911330809 	 Accuracy: 0.3455019556714472
Delta: 1.6453715052350443e-05 	  Loss: 1.5819294720191535 	 Accuracy: 0.3455019556714472
Delta: 1.953718202677267e-09 	  Loss: 1.581929473421523 	 Accuracy: 0.3455019556714472
converged at iter  77
Delta: 0.020883095882012235 	  Loss: 2.1519033851486045 	 Accuracy: 0.2033898305084746
Delta: 0.019261263687098094 	  Loss: 2.0423235835023954 	 Accuracy: 0.3546284224250326
Delta: 0.01729003006275548 	  Loss: 1.8622621023307642 	 Accuracy: 0.44328552803129073
Delta: 0.014976930500226946 	  Loss: 1.7147755868309242 	 Accuracy: 0.4471968709256845
Delta: 0.013085419167316996 	  Loss: 1.6354405233555849 	 Accuracy: 0.4445893089960887
Delta: 0.010507247127947476 	  Loss: 1.6026562028124447 	 Accuracy: 0.41590612777053454
Delta: 0.008806083317243682 	  Loss: 1.589183645660058 	 Accuracy: 0.4002607561929596

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007530593065582907 	  Loss: 1.5847508448404237 	 Accuracy: 0.39504563233376794
Delta: 0.005133850056473849 	  Loss: 1.5826531498830643 	 Accuracy: 0.39895697522816165
Delta: 0.004737713317611177 	  Loss: 1.581902758335011 	 Accuracy: 0.3963494132985658
Delta: 0.003841098087889013 	  Loss: 1.5816108676326874 	 Accuracy: 0.4002607561929596
Delta: 0.0019515073513135669 	  Loss: 1.581422805488411 	 Accuracy: 0.4028683181225554
Delta: 0.00324694526675198 	  Loss: 1.5812555429111654 	 Accuracy: 0.4015645371577575
Delta: 0.0008366755845904731 	  Loss: 1.5813837932021049 	 Accuracy: 0.4015645371577575
Delta: 0.0008089956243385963 	  Loss: 1.5814799108743938 	 Accuracy: 0.4015645371577575
Delta: 0.0010625499254581859 	  Loss: 1.5815379650751575 	 Accuracy: 0.4015645371577575
Delta: 2.371485185218601e-05 	  Loss: 1.5814979785504715 	 Accuracy: 0.4002607561929596
Delta: 2.0085900426907672e-05 	  Loss: 1.5815000686983927 	 Accuracy: 0.4015645371577575
Delta: 1.050261116589892e-05 	  Loss: 1.5815378415954089 	 Accuracy: 0.4015645371577575
Delta: 0.0017827812800106492 	  Loss: 1.5814742722732877 	 Accuracy: 0.4002607561929596
Delta: 0.0007104471402948016 	  Loss: 1.5815203384300185 	 Accuracy: 0.4002607561929596
Delta: 3.474004764721279e-05 	  Loss: 1.5815151990155234 	 Accuracy: 0.4015645371577575
Delta: 0.0005246880048551081 	  Loss: 1.5815327162328576 	 Accuracy: 0.4015645371577575
Delta: 0.000713238410570183 	  Loss: 1.5816078495309442 	 Accuracy: 0.4015645371577575
Delta: 3.083008152114521e-05 	  Loss: 1.5814771875661506 	 Accuracy: 0.4002607561929596
Delta: 2.8809402451687073e-05 	  Loss: 1.5815483886109978 	 Accuracy: 0.4002607561929596
Delta: 9.81530820304624e-06 	  Loss: 1.5815154959900684 	 Accuracy: 0.4015645371577575
Delta: 0.001390147524474436 	  Loss: 1.581451482777553 	 Accuracy: 0.4015645371577575
Delta: 4.8625524574792787e-05 	  Loss: 1.5815224846577267 	 Accuracy: 0.4015645371577575
Delta: 0.0005624247470319841 	  Loss: 1.5813716903010406 	 Accuracy: 0.4028683181225554
Delta: 1.2574707699720901e-05 	  Loss: 1.5814238016113717 	 Accuracy: 0.4002607561929596
Delta: 0.0007658940365719574 	  Loss: 1.581593564177801 	 Accuracy: 0.4015645371577575
Delta: 7.110660998808395e-05 	  Loss: 1.5813255848741494 	 Accuracy: 0.4015645371577575
Delta: 3.5845681691860905e-05 	  Loss: 1.5814098081533454 	 Accuracy: 0.4015645371577575
Delta: 0.0005321543889424263 	  Loss: 1.5814876732378182 	 Accuracy: 0.4015645371577575
Delta: 3.491160267559801e-05 	  Loss: 1.581404721990119 	 Accuracy: 0.4002607561929596
Delta: 8.37440727415066e-05 	  Loss: 1.581392851190068 	 Accuracy: 0.4015645371577575
Delta: 8.204184713871936e-05 	  Loss: 1.581192210039524 	 Accuracy: 0.4015645371577575
Delta: 3.688129042165415e-05 	  Loss: 1.5814080858570279 	 Accuracy: 0.39895697522816165
Delta: 5.0998339317465424e-05 	  Loss: 1.5815181409496153 	 Accuracy: 0.4015645371577575
Delta: 4.728018629908468e-05 	  Loss: 1.5814258335704166 	 Accuracy: 0.4015645371577575
Delta: 1.9816865318604163e-05 	  Loss: 1.581387490840267 	 Accuracy: 0.4002607561929596
Delta: 0.0023168733415470824 	  Loss: 1.581408298308143 	 Accuracy: 0.4015645371577575
Delta: 0.0018240486392119347 	  Loss: 1.5813554468365996 	 Accuracy: 0.39895697522816165
Delta: 0.0005533639102589744 	  Loss: 1.581444739571837 	 Accuracy: 0.4002607561929596
Delta: 0.0005634228118777449 	  Loss: 1.581609509294084 	 Accuracy: 0.4015645371577575
Delta: 2.501178693724439e-05 	  Loss: 1.5816925291106123 	 Accuracy: 0.4015645371577575
Delta: 0.0026982188986954996 	  Loss: 1.5809792967164165 	 Accuracy: 0.4002607561929596
Delta: 0.002870667589859159 	  Loss: 1.5811377123189918 	 Accuracy: 0.39895697522816165
Delta: 0.0023832843261673083 	  Loss: 1.5807605300516583 	 Accuracy: 0.4015645371577575
Delta: 0.0033972740115160685 	  Loss: 1.58133851194069 	 Accuracy: 0.4015645371577575
Delta: 0.002197299401553144 	  Loss: 1.5813429638007823 	 Accuracy: 0.4015645371577575
Delta: 0.0029404292444167642 	  Loss: 1.581293626636 	 Accuracy: 0.4015645371577575
Delta: 0.0028371267596826485 	  Loss: 1.581112414078552 	 Accuracy: 0.4015645371577575
Delta: 0.0026427256372494245 	  Loss: 1.5816302092444894 	 Accuracy: 0.39895697522816165
Delta: 0.0035362260186903188 	  Loss: 1.5820379927981554 	 Accuracy: 0.39895697522816165
Delta: 0.004705258942125885 	  Loss: 1.5822251266542728 	 Accuracy: 0.39895697522816165
Delta: 0.0012643703811743175 	  Loss: 1.582237718052256 	 Accuracy: 0.39895697522816165
Delta: 0.0018963056427432473 	  Loss: 1.58213673160274 	 Accuracy: 0.39895697522816165
Delta: 0.001801381948917399 	  Loss: 1.5822082249118394 	 Accuracy: 0.39895697522816165
Delta: 0.0016454138544548522 	  Loss: 1.5822140700925287 	 Accuracy: 0.4015645371577575
Delta: 0.0021892544367255263 	  Loss: 1.5824012193825554 	 Accuracy: 0.39895697522816165
Delta: 0.003257515046762579 	  Loss: 1.5823728513375652 	 Accuracy: 0.39895697522816165
Delta: 0.0036193410487037 	  Loss: 1.5823613180685023 	 Accuracy: 0.3963494132985658
Delta: 0.0027830450447559963 	  Loss: 1.5822519800130057 	 Accuracy: 0.39765319426336376
Delta: 0.0031217512332612015 	  Loss: 1.582157864283702 	 Accuracy: 0.39765319426336376
Delta: 0.002399376364692968 	  Loss: 1.5820930050531512 	 Accuracy: 0.39895697522816165
Delta: 0.0025070839499578015 	  Loss: 1.582015963811742 	 Accuracy: 0.39895697522816165
Delta: 0.0007369474285356183 	  Loss: 1.5819623407937549 	 Accuracy: 0.3963494132985658
Delta: 0.0022127075462104787 	  Loss: 1.582122463070533 	 Accuracy: 0.3963494132985658
Delta: 0.0030538908488942683 	  Loss: 1.5825520956724497 	 Accuracy: 0.4015645371577575
Delta: 0.0038347772664753315 	  Loss: 1.582599512341148 	 Accuracy: 0.3963494132985658
Delta: 0.004590153445252768 	  Loss: 1.5832218291483728 	 Accuracy: 0.3963494132985658
Delta: 0.002512415229278099 	  Loss: 1.583358505378945 	 Accuracy: 0.39765319426336376
Delta: 0.002263281807063205 	  Loss: 1.582305315948345 	 Accuracy: 0.4015645371577575
Delta: 0.001916701668972967 	  Loss: 1.5831437469137963 	 Accuracy: 0.39765319426336376
Delta: 0.003113674769080429 	  Loss: 1.5836651187143587 	 Accuracy: 0.39765319426336376
Delta: 0.0017568016828300637 	  Loss: 1.5839936508839365 	 Accuracy: 0.3963494132985658
Delta: 0.0023832291388733557 	  Loss: 1.5836269288480995 	 Accuracy: 0.39765319426336376
Delta: 0.0012154244969734317 	  Loss: 1.5838182451310632 	 Accuracy: 0.39765319426336376
Delta: 6.013688805922972e-06 	  Loss: 1.5838162496379364 	 Accuracy: 0.39765319426336376
Delta: 4.479833789848975e-07 	  Loss: 1.5838180111311995 	 Accuracy: 0.39765319426336376
Delta: 0.002172874953580296 	  Loss: 1.583809585105152 	 Accuracy: 0.39374185136897
Delta: 0.001082569755609947 	  Loss: 1.5840113198422154 	 Accuracy: 0.39765319426336376
Delta: 5.2066347754334795e-05 	  Loss: 1.5837871094103302 	 Accuracy: 0.39374185136897
Delta: 0.0005317436857690201 	  Loss: 1.583706823300048 	 Accuracy: 0.39765319426336376
Delta: 4.814499492017644e-05 	  Loss: 1.5838026445805875 	 Accuracy: 0.39765319426336376
Delta: 1.3234604480643726e-05 	  Loss: 1.5837976137099627 	 Accuracy: 0.3963494132985658
Delta: 0.0008340580529065222 	  Loss: 1.5836590216460604 	 Accuracy: 0.39765319426336376
Delta: 0.0022937811927368056 	  Loss: 1.583388660205538 	 Accuracy: 0.3898305084745763
Delta: 0.002819293099873088 	  Loss: 1.5842533257228664 	 Accuracy: 0.39765319426336376
Delta: 0.0019243732935757467 	  Loss: 1.583682593769026 	 Accuracy: 0.39765319426336376
Delta: 0.0016639518023251329 	  Loss: 1.583323940441748 	 Accuracy: 0.39765319426336376
Delta: 1.181621787458204e-05 	  Loss: 1.5833127064160395 	 Accuracy: 0.39765319426336376
Delta: 3.3238810573495324e-05 	  Loss: 1.5833901408675484 	 Accuracy: 0.40547588005215124
Delta: 0.0036132152168693466 	  Loss: 1.5843545046811025 	 Accuracy: 0.39895697522816165
Delta: 0.003965864552932836 	  Loss: 1.584590412919671 	 Accuracy: 0.4002607561929596
Delta: 0.004480753215825355 	  Loss: 1.584672132102248 	 Accuracy: 0.39765319426336376
Delta: 0.0025957621210111106 	  Loss: 1.5846174354796743 	 Accuracy: 0.39895697522816165
Delta: 0.00013194473898363798 	  Loss: 1.5846232293205178 	 Accuracy: 0.39765319426336376
Delta: 0.020946460857992576 	  Loss: 2.151814911909983 	 Accuracy: 0.20078226857887874
Delta: 0.01929568483488306 	  Loss: 2.0387589228613834 	 Accuracy: 0.26597131681877445
Delta: 0.017490093809412112 	  Loss: 1.8560449082240884 	 Accuracy: 0.41460234680573665
Delta: 0.015690569049803035 	  Loss: 1.7032700256867974 	 Accuracy: 0.3924380704041721
Delta: 0.01311503725922278 	  Loss: 1.6223812751325748 	 Accuracy: 0.3663624511082138
Delta: 0.011213031527604398 	  Loss: 1.5910802627610496 	 Accuracy: 0.3455019556714472

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009557827385309376 	  Loss: 1.5775245009220207 	 Accuracy: 0.34159061277705344
Delta: 0.007268641003754092 	  Loss: 1.5730426414786334 	 Accuracy: 0.3350717079530639
Delta: 0.006197324782317979 	  Loss: 1.5711713676072776 	 Accuracy: 0.33116036505867014
Delta: 0.005373676782574748 	  Loss: 1.5703327356539754 	 Accuracy: 0.3363754889178618
Delta: 0.004582731709825315 	  Loss: 1.5702975524944986 	 Accuracy: 0.33376792698826596
Delta: 0.0022194298023774546 	  Loss: 1.5702102765177581 	 Accuracy: 0.3363754889178618
Delta: 0.004096516444791973 	  Loss: 1.5698209786246764 	 Accuracy: 0.3376792698826597
Delta: 0.003449183643151661 	  Loss: 1.5700611503392645 	 Accuracy: 0.3376792698826597
Delta: 0.0011575724868317925 	  Loss: 1.57018686880075 	 Accuracy: 0.33116036505867014
Delta: 0.0028107859069303968 	  Loss: 1.5706577256062961 	 Accuracy: 0.3350717079530639
Delta: 0.002918599148798268 	  Loss: 1.5709174204899004 	 Accuracy: 0.33376792698826596
Delta: 0.0016818522582571938 	  Loss: 1.570977116604666 	 Accuracy: 0.3350717079530639
Delta: 9.516903271752867e-06 	  Loss: 1.5709646015595484 	 Accuracy: 0.3324641460234681
Delta: 0.0019986369656407412 	  Loss: 1.570948529537639 	 Accuracy: 0.3324641460234681
Delta: 0.000715834882365032 	  Loss: 1.5709474347072423 	 Accuracy: 0.33376792698826596
Delta: 0.0005056285574989104 	  Loss: 1.5709281468374974 	 Accuracy: 0.3350717079530639
Delta: 0.0006513035664651173 	  Loss: 1.570819211864328 	 Accuracy: 0.3350717079530639
Delta: 0.0006397079406923536 	  Loss: 1.5709203513387155 	 Accuracy: 0.3350717079530639
Delta: 3.295799531848985e-05 	  Loss: 1.5709821203694458 	 Accuracy: 0.3350717079530639
Delta: 3.642225232094932e-05 	  Loss: 1.5710023537487792 	 Accuracy: 0.33376792698826596
Delta: 0.0019001621263701313 	  Loss: 1.571021724815794 	 Accuracy: 0.3350717079530639
Delta: 5.14206099290404e-05 	  Loss: 1.5710673758983282 	 Accuracy: 0.33376792698826596
Delta: 0.0026438930846358006 	  Loss: 1.570939224073747 	 Accuracy: 0.32985658409387225
Delta: 0.00259858391046217 	  Loss: 1.571027430707168 	 Accuracy: 0.3350717079530639
Delta: 0.0006586758740955809 	  Loss: 1.5711231265942567 	 Accuracy: 0.3363754889178618
Delta: 0.0015207036816728614 	  Loss: 1.5709485796561113 	 Accuracy: 0.33376792698826596
Delta: 4.889556233928758e-05 	  Loss: 1.5710590359398897 	 Accuracy: 0.3350717079530639
Delta: 2.1812498944767857e-05 	  Loss: 1.571060510177789 	 Accuracy: 0.3350717079530639
Delta: 4.225234154894012e-05 	  Loss: 1.5710828043468892 	 Accuracy: 0.3350717079530639
Delta: 3.6182088835526256e-05 	  Loss: 1.571065662896881 	 Accuracy: 0.3350717079530639
Delta: 5.51888760688422e-05 	  Loss: 1.571203222593724 	 Accuracy: 0.3350717079530639
Delta: 4.970280379587537e-05 	  Loss: 1.5710581578321006 	 Accuracy: 0.3350717079530639
Delta: 1.9992182352036812e-05 	  Loss: 1.5710594180861213 	 Accuracy: 0.3350717079530639
Delta: 1.2878913874530271e-05 	  Loss: 1.5710281034971836 	 Accuracy: 0.3350717079530639
Delta: 1.4358959390620977e-05 	  Loss: 1.5710601922546248 	 Accuracy: 0.3376792698826597
Delta: 5.109623642044997e-05 	  Loss: 1.571003013164335 	 Accuracy: 0.3350717079530639
Delta: 0.0010042200406706896 	  Loss: 1.5710481559686857 	 Accuracy: 0.3363754889178618
Delta: 0.0013292859610024585 	  Loss: 1.571089599978904 	 Accuracy: 0.33376792698826596
Delta: 0.0006352435887970973 	  Loss: 1.5711408952161858 	 Accuracy: 0.3350717079530639
Delta: 2.5667017584129943e-05 	  Loss: 1.5711272506748895 	 Accuracy: 0.3259452411994785
Delta: 5.2108585088709696e-05 	  Loss: 1.5710832042713205 	 Accuracy: 0.3350717079530639
Delta: 0.000969585398136818 	  Loss: 1.5711118801788415 	 Accuracy: 0.3285528031290743
Delta: 0.0017038899342049036 	  Loss: 1.5709458122519417 	 Accuracy: 0.3350717079530639
Delta: 6.299957447528394e-05 	  Loss: 1.571135439751158 	 Accuracy: 0.3350717079530639
Delta: 3.28445713817791e-06 	  Loss: 1.5711320701702332 	 Accuracy: 0.3324641460234681
Delta: 0.0008992657316706491 	  Loss: 1.571094026967546 	 Accuracy: 0.3350717079530639
Delta: 0.0009221367844989873 	  Loss: 1.5710905306324816 	 Accuracy: 0.33376792698826596
Delta: 7.970341453384347e-05 	  Loss: 1.5711284285030556 	 Accuracy: 0.3246414602346806
Delta: 0.0016101500766541033 	  Loss: 1.571250371941538 	 Accuracy: 0.3350717079530639
Delta: 0.0023617682168518284 	  Loss: 1.5714068244118335 	 Accuracy: 0.3350717079530639
Delta: 0.0011003902725057733 	  Loss: 1.571128560044483 	 Accuracy: 0.33376792698826596
Delta: 0.0019675876422502615 	  Loss: 1.5711349880171925 	 Accuracy: 0.3350717079530639
Delta: 2.8528858224531123e-05 	  Loss: 1.5711287795470787 	 Accuracy: 0.3350717079530639
Delta: 0.000829737428652096 	  Loss: 1.5710469463229602 	 Accuracy: 0.3350717079530639
Delta: 0.0008357046821059515 	  Loss: 1.5710385876635997 	 Accuracy: 0.3350717079530639
Delta: 2.2411848163344218e-05 	  Loss: 1.571114854649016 	 Accuracy: 0.3350717079530639
Delta: 1.6539725255646407e-05 	  Loss: 1.5710794298993755 	 Accuracy: 0.3350717079530639
Delta: 1.8231758599563922e-05 	  Loss: 1.5710254408499602 	 Accuracy: 0.3350717079530639
Delta: 4.858149686173336e-05 	  Loss: 1.57111263984983 	 Accuracy: 0.33376792698826596
Delta: 0.002086919473019196 	  Loss: 1.570902644029661 	 Accuracy: 0.33376792698826596
Delta: 0.002348255202408538 	  Loss: 1.571114002269122 	 Accuracy: 0.33376792698826596
Delta: 2.8934585355781893e-05 	  Loss: 1.5711068013934404 	 Accuracy: 0.33376792698826596
Delta: 0.0019603391541998046 	  Loss: 1.5708834584327112 	 Accuracy: 0.3350717079530639
Delta: 0.001277455048890758 	  Loss: 1.5712083934235643 	 Accuracy: 0.3285528031290743
Delta: 0.0013797258796042022 	  Loss: 1.571367839298451 	 Accuracy: 0.33376792698826596
Delta: 0.003163500768459493 	  Loss: 1.5719572629591685 	 Accuracy: 0.3324641460234681
Delta: 0.004988467466174052 	  Loss: 1.572199676331749 	 Accuracy: 0.3324641460234681
Delta: 0.0030719397457460744 	  Loss: 1.5719127098147214 	 Accuracy: 0.33116036505867014
Delta: 0.0014673836425096497 	  Loss: 1.572241888728927 	 Accuracy: 0.3350717079530639
Delta: 0.0007277079072399578 	  Loss: 1.5720132940873845 	 Accuracy: 0.33376792698826596
Delta: 0.001952247380862393 	  Loss: 1.571868159521024 	 Accuracy: 0.3324641460234681
Delta: 0.0007525412576317771 	  Loss: 1.5718640585907036 	 Accuracy: 0.33376792698826596
Delta: 0.0011009692151401046 	  Loss: 1.5720289879983378 	 Accuracy: 0.34028683181225555
Delta: 0.004606384030013436 	  Loss: 1.5728058117141783 	 Accuracy: 0.33376792698826596
Delta: 0.004871356538090698 	  Loss: 1.5720752576618684 	 Accuracy: 0.3363754889178618
Delta: 2.5189829957482835e-05 	  Loss: 1.571974938775462 	 Accuracy: 0.3376792698826597
Delta: 0.0012776710442512266 	  Loss: 1.5721911839351281 	 Accuracy: 0.3350717079530639
Delta: 0.004218123153726522 	  Loss: 1.5722761452310778 	 Accuracy: 0.3350717079530639
Delta: 0.003875021288423233 	  Loss: 1.5719894630240865 	 Accuracy: 0.3363754889178618
Delta: 0.0027861171470804327 	  Loss: 1.5719541246848614 	 Accuracy: 0.3363754889178618
Delta: 0.000623267215942776 	  Loss: 1.5719287597330158 	 Accuracy: 0.3363754889178618
Delta: 0.0013651873129439558 	  Loss: 1.5719541667480923 	 Accuracy: 0.3363754889178618
Delta: 0.002358596248885989 	  Loss: 1.5718452085605847 	 Accuracy: 0.34028683181225555
Delta: 0.005376156423980014 	  Loss: 1.571431429320406 	 Accuracy: 0.3259452411994785
Delta: 0.0030335854659915016 	  Loss: 1.572456068413334 	 Accuracy: 0.33376792698826596
Delta: 0.0028414732453968224 	  Loss: 1.5719307193287306 	 Accuracy: 0.3363754889178618
Delta: 0.0015529262301005563 	  Loss: 1.5716921717058323 	 Accuracy: 0.3376792698826597
Delta: 0.0023822158182704276 	  Loss: 1.5721456184798308 	 Accuracy: 0.3389830508474576
Delta: 0.003209582992973806 	  Loss: 1.5728343390189319 	 Accuracy: 0.3376792698826597
Delta: 0.004578945363528353 	  Loss: 1.573193871234797 	 Accuracy: 0.3376792698826597
Delta: 0.0011876799418119094 	  Loss: 1.5731594754900908 	 Accuracy: 0.34159061277705344
Delta: 0.0038107525451004727 	  Loss: 1.5738814018844645 	 Accuracy: 0.3376792698826597
Delta: 0.0022330715712227086 	  Loss: 1.5739417897271344 	 Accuracy: 0.3116036505867014
Delta: 0.0009029042731360748 	  Loss: 1.574154930048735 	 Accuracy: 0.3376792698826597
Delta: 0.02091975557942054 	  Loss: 2.1520365057203206 	 Accuracy: 0.20599739243807041
Delta: 0.019326319185447076 	  Loss: 2.0359511710542826 	 Accuracy: 0.3116036505867014
Delta: 0.017567921689658636 	  Loss: 1.8474495823380335 	 Accuracy: 0.4367666232073012
Delta: 0.016051885049547823 	  Loss: 1.6981294301976841 	 Accuracy: 0.4028683181225554
Delta: 0.013282742176857421 	  Loss: 1.6194118179647154 	 Accuracy: 0.3754889178617992
Delta: 0.011183725554045499 	  Loss: 1.5825818923052815 	 Accuracy: 0.3650586701434159

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008792720423339563 	  Loss: 1.5669631848677235 	 Accuracy: 0.36766623207301175
Delta: 0.006733801440823497 	  Loss: 1.5618375132236335 	 Accuracy: 0.3663624511082138
Delta: 0.005833327066397684 	  Loss: 1.5602793540325335 	 Accuracy: 0.35984354628422427
Delta: 0.004226659196021751 	  Loss: 1.5597892410760816 	 Accuracy: 0.3650586701434159
Delta: 0.0020182558819216542 	  Loss: 1.5599102848919002 	 Accuracy: 0.3650586701434159
Delta: 0.0027305892816003323 	  Loss: 1.5596582384119768 	 Accuracy: 0.3650586701434159
Delta: 0.002330790260714442 	  Loss: 1.559630243229567 	 Accuracy: 0.363754889178618
Delta: 0.0025399644587894323 	  Loss: 1.5595908760055615 	 Accuracy: 0.3650586701434159
Delta: 0.0014752050101182893 	  Loss: 1.559558740440743 	 Accuracy: 0.3650586701434159
Delta: 1.5721357377481585e-05 	  Loss: 1.559565000640991 	 Accuracy: 0.3650586701434159
Delta: 0.0007171132317176402 	  Loss: 1.5595898973783882 	 Accuracy: 0.3650586701434159
Delta: 0.0023399505184693954 	  Loss: 1.559493456133277 	 Accuracy: 0.3650586701434159
Delta: 0.0007303433397811095 	  Loss: 1.5596434751804074 	 Accuracy: 0.3650586701434159
Delta: 1.609171804201192e-05 	  Loss: 1.5596136792563589 	 Accuracy: 0.3650586701434159
Delta: 5.869856415718175e-05 	  Loss: 1.5595604472868942 	 Accuracy: 0.3650586701434159
Delta: 4.95667780424332e-05 	  Loss: 1.5594712577115548 	 Accuracy: 0.3650586701434159
Delta: 0.0008971540341417147 	  Loss: 1.5593623794827962 	 Accuracy: 0.3663624511082138
Delta: 0.002506003159023771 	  Loss: 1.5590612011387681 	 Accuracy: 0.36114732724902215
Delta: 0.0014126305837786628 	  Loss: 1.5597662821378466 	 Accuracy: 0.363754889178618
Delta: 0.0015954263121961214 	  Loss: 1.5596040007349403 	 Accuracy: 0.3650586701434159
Delta: 7.706562114162134e-05 	  Loss: 1.559389087772044 	 Accuracy: 0.363754889178618
Delta: 0.0008310418203694615 	  Loss: 1.5596489690285162 	 Accuracy: 0.3650586701434159
Delta: 0.0016287278430461604 	  Loss: 1.5595013089136525 	 Accuracy: 0.3650586701434159
Delta: 0.0012820261019421963 	  Loss: 1.5596172653173328 	 Accuracy: 0.3663624511082138
Delta: 0.0011725787818448537 	  Loss: 1.559518963438384 	 Accuracy: 0.363754889178618
Delta: 0.0012238888160481553 	  Loss: 1.559584204736397 	 Accuracy: 0.3624511082138201
Delta: 0.0014311629563370494 	  Loss: 1.5595277270946277 	 Accuracy: 0.3650586701434159
Delta: 0.0013156565067163365 	  Loss: 1.5594507102143997 	 Accuracy: 0.3650586701434159
Delta: 5.903781326464435e-05 	  Loss: 1.5595708631119924 	 Accuracy: 0.363754889178618
Delta: 5.4272075482230646e-05 	  Loss: 1.5596279454466024 	 Accuracy: 0.3650586701434159
Delta: 0.0007681423481759708 	  Loss: 1.559537499222507 	 Accuracy: 0.363754889178618
Delta: 0.0007433127269063149 	  Loss: 1.559537084532217 	 Accuracy: 0.3650586701434159
Delta: 8.449989850208903e-05 	  Loss: 1.5594621211534825 	 Accuracy: 0.3650586701434159
Delta: 5.742892224830141e-05 	  Loss: 1.5596549208990556 	 Accuracy: 0.3650586701434159
Delta: 6.0517577886002394e-05 	  Loss: 1.5595828870685633 	 Accuracy: 0.3650586701434159
Delta: 6.155673474449229e-05 	  Loss: 1.5594919212379115 	 Accuracy: 0.3650586701434159
Delta: 2.665144566880531e-05 	  Loss: 1.5595105613688238 	 Accuracy: 0.3650586701434159
Delta: 3.0124022833833252e-05 	  Loss: 1.5594278688775054 	 Accuracy: 0.3663624511082138
Delta: 0.000138861231014576 	  Loss: 1.5598239256633226 	 Accuracy: 0.35071707953063885
Delta: 0.0016609151623090171 	  Loss: 1.5598198042863385 	 Accuracy: 0.3650586701434159
Delta: 0.0037188367183250922 	  Loss: 1.5596901753114834 	 Accuracy: 0.3650586701434159
Delta: 0.0041628233008369 	  Loss: 1.5594550063951012 	 Accuracy: 0.3663624511082138
Delta: 0.0038318156052528627 	  Loss: 1.558552047511169 	 Accuracy: 0.3663624511082138
Delta: 0.0023387724295345132 	  Loss: 1.5584407326255434 	 Accuracy: 0.36114732724902215
Delta: 0.004372804834783388 	  Loss: 1.5584682027600163 	 Accuracy: 0.36766623207301175
Delta: 0.004448391592752349 	  Loss: 1.5594561981737471 	 Accuracy: 0.3650586701434159
Delta: 0.0017980938656903724 	  Loss: 1.5592819328970369 	 Accuracy: 0.3663624511082138
Delta: 0.004665466100482315 	  Loss: 1.5593227054213088 	 Accuracy: 0.3663624511082138
Delta: 0.0016440177643528692 	  Loss: 1.5593770590223455 	 Accuracy: 0.36897001303780963
Delta: 0.0009879647543606606 	  Loss: 1.5590504859148586 	 Accuracy: 0.36766623207301175
Delta: 2.9846779561891648e-05 	  Loss: 1.5590925793697117 	 Accuracy: 0.36766623207301175
Delta: 2.3855230296067763e-05 	  Loss: 1.559117481829674 	 Accuracy: 0.36766623207301175
Delta: 2.7853125260346504e-05 	  Loss: 1.5591296668614503 	 Accuracy: 0.3650586701434159
Delta: 0.003139675863538562 	  Loss: 1.5609917418916397 	 Accuracy: 0.36766623207301175
Delta: 0.0028250171370851327 	  Loss: 1.5589992655915421 	 Accuracy: 0.36766623207301175
Delta: 0.0009673904521412511 	  Loss: 1.5591077138080485 	 Accuracy: 0.36766623207301175
Delta: 1.8818128136702283e-06 	  Loss: 1.5591080291096413 	 Accuracy: 0.36766623207301175
Delta: 0.0005331413136050518 	  Loss: 1.5590359242215044 	 Accuracy: 0.36766623207301175
Delta: 0.0005331448486617397 	  Loss: 1.5591083473330918 	 Accuracy: 0.3663624511082138
Delta: 7.843640032463122e-05 	  Loss: 1.5590417006710195 	 Accuracy: 0.36766623207301175
Delta: 7.843292679069262e-05 	  Loss: 1.559108097204835 	 Accuracy: 0.36766623207301175
Delta: 2.452158228979019e-06 	  Loss: 1.5591008320210675 	 Accuracy: 0.36766623207301175
Delta: 2.788340781750842e-06 	  Loss: 1.5591052849963547 	 Accuracy: 0.36766623207301175
Delta: 3.8965596579933416e-06 	  Loss: 1.559094162329997 	 Accuracy: 0.36766623207301175
Delta: 0.0020263538532382503 	  Loss: 1.559067482972654 	 Accuracy: 0.3663624511082138
Delta: 0.0006722323130963087 	  Loss: 1.559107273005715 	 Accuracy: 0.363754889178618
Delta: 0.001768279910525249 	  Loss: 1.5592226194152212 	 Accuracy: 0.36766623207301175
Delta: 0.0017682917224234854 	  Loss: 1.5591102158145715 	 Accuracy: 0.36766623207301175
Delta: 0.000644734470883748 	  Loss: 1.5591924954726828 	 Accuracy: 0.36766623207301175
Delta: 0.0006446734492922631 	  Loss: 1.5591104575113857 	 Accuracy: 0.36766623207301175
Delta: 4.56488103185863e-05 	  Loss: 1.5590945734753634 	 Accuracy: 0.36766623207301175
Delta: 4.566382734093075e-05 	  Loss: 1.5591096251050143 	 Accuracy: 0.36766623207301175
Delta: 0.0029551548809363623 	  Loss: 1.5591070608309705 	 Accuracy: 0.36766623207301175
Delta: 0.002755494509688392 	  Loss: 1.559088045316432 	 Accuracy: 0.36766623207301175
Delta: 2.619813602894759e-05 	  Loss: 1.5591082406789267 	 Accuracy: 0.36766623207301175
Delta: 0.0021205188906626786 	  Loss: 1.559420208645898 	 Accuracy: 0.36766623207301175
Delta: 0.000648020086799989 	  Loss: 1.5591880644977767 	 Accuracy: 0.3728813559322034
Delta: 0.003942792001985231 	  Loss: 1.5583098328093428 	 Accuracy: 0.36897001303780963
Delta: 0.0013134956316340684 	  Loss: 1.5583358096423012 	 Accuracy: 0.36897001303780963
Delta: 0.002286060482342656 	  Loss: 1.558466197085799 	 Accuracy: 0.36897001303780963
Delta: 0.004376487063568502 	  Loss: 1.5578901416749424 	 Accuracy: 0.37027379400260757
Delta: 0.00456928936727668 	  Loss: 1.5583179377985776 	 Accuracy: 0.37027379400260757
Delta: 0.004079266133073969 	  Loss: 1.557150938128145 	 Accuracy: 0.36766623207301175
Delta: 0.004144952121228219 	  Loss: 1.5579103492501896 	 Accuracy: 0.36766623207301175
Delta: 0.0013068202644460605 	  Loss: 1.5579039030104198 	 Accuracy: 0.36897001303780963
Delta: 0.003802786469780827 	  Loss: 1.5572775339679767 	 Accuracy: 0.37027379400260757
Delta: 0.004072159204871773 	  Loss: 1.558246224759234 	 Accuracy: 0.37027379400260757
Delta: 0.005243807685404462 	  Loss: 1.5589229238528342 	 Accuracy: 0.37157757496740546
Delta: 0.0032094934101113853 	  Loss: 1.5584805793147114 	 Accuracy: 0.37157757496740546
Delta: 0.00455708456984778 	  Loss: 1.5581878795294515 	 Accuracy: 0.37157757496740546
Delta: 0.001059518260267224 	  Loss: 1.5581721833676379 	 Accuracy: 0.3728813559322034
Delta: 0.0028339815194351344 	  Loss: 1.5577279756986786 	 Accuracy: 0.37157757496740546
Delta: 0.004918273243308736 	  Loss: 1.5588700956900143 	 Accuracy: 0.37157757496740546
Delta: 0.004918539053046015 	  Loss: 1.5575027293324246 	 Accuracy: 0.3741851368970013
Delta: 0.021002877689668367 	  Loss: 2.151652401316113 	 Accuracy: 0.20599739243807041
Delta: 0.019076421522190513 	  Loss: 2.036815130703162 	 Accuracy: 0.28552803129074317
Delta: 0.017305156881186088 	  Loss: 1.858322289356158 	 Accuracy: 0.33116036505867014
Delta: 0.015773372754679913 	  Loss: 1.7384729257802205 	 Accuracy: 0.29726205997392435
Delta: 0.014399329800948407 	  Loss: 1.6760789755272785 	 Accuracy: 0.29726205997392435
Delta: 0.012796155266441317 	  Loss: 1.6389953291784385 	 Accuracy: 0.3050847457627119

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009489822841673289 	  Loss: 1.6245411037791158 	 Accuracy: 0.30638852672750977
Delta: 0.007614437439643657 	  Loss: 1.6204870980618864 	 Accuracy: 0.3011734028683181
Delta: 0.00566028427527012 	  Loss: 1.620149014849249 	 Accuracy: 0.3050847457627119
Delta: 0.00557596210483194 	  Loss: 1.619559053001862 	 Accuracy: 0.3076923076923077
Delta: 0.0037541811653609303 	  Loss: 1.619903512798308 	 Accuracy: 0.30638852672750977
Delta: 0.0025739848829273914 	  Loss: 1.6200951275025999 	 Accuracy: 0.3050847457627119
Delta: 0.003001240894859397 	  Loss: 1.620362399554843 	 Accuracy: 0.3050847457627119
Delta: 0.0034961449222831844 	  Loss: 1.6203703924880837 	 Accuracy: 0.30638852672750977
Delta: 0.002688887577485531 	  Loss: 1.6206963030930321 	 Accuracy: 0.30638852672750977
Delta: 1.3903343602165813e-05 	  Loss: 1.6206867074831135 	 Accuracy: 0.30638852672750977
Delta: 5.790400939689895e-06 	  Loss: 1.6206846686487921 	 Accuracy: 0.30638852672750977
Delta: 0.001534670079234728 	  Loss: 1.6207481286159693 	 Accuracy: 0.30638852672750977
Delta: 1.701763167890586e-06 	  Loss: 1.6207458099946646 	 Accuracy: 0.30638852672750977
Delta: 1.545378337643009e-05 	  Loss: 1.6207099053960592 	 Accuracy: 0.3050847457627119
Delta: 1.7274915295757722e-05 	  Loss: 1.620733992501469 	 Accuracy: 0.30638852672750977
Delta: 0.0005135588099878416 	  Loss: 1.6207661079032527 	 Accuracy: 0.30638852672750977
Delta: 3.559255100178476e-05 	  Loss: 1.6207593988397075 	 Accuracy: 0.30638852672750977
Delta: 0.0014810472519614433 	  Loss: 1.621029330005454 	 Accuracy: 0.30638852672750977
Delta: 3.691694594661519e-05 	  Loss: 1.6208118933170634 	 Accuracy: 0.3116036505867014
Delta: 0.0021881279824198653 	  Loss: 1.6210042466561783 	 Accuracy: 0.30638852672750977
Delta: 0.0009808807841590005 	  Loss: 1.6211195239931278 	 Accuracy: 0.30638852672750977
Delta: 5.083794555767282e-05 	  Loss: 1.6210359596417454 	 Accuracy: 0.3076923076923077
Delta: 4.264242873372206e-05 	  Loss: 1.6208515217649675 	 Accuracy: 0.3050847457627119
Delta: 0.002133207665233007 	  Loss: 1.6207146817298896 	 Accuracy: 0.30378096479791394
Delta: 0.0010611448456806635 	  Loss: 1.6207132058138278 	 Accuracy: 0.30378096479791394
Delta: 0.0010705814439269812 	  Loss: 1.6207941251367046 	 Accuracy: 0.30638852672750977
Delta: 0.0010181771526653453 	  Loss: 1.6206759969782956 	 Accuracy: 0.3050847457627119
Delta: 0.0007235071648530399 	  Loss: 1.6207027904938907 	 Accuracy: 0.30638852672750977
Delta: 2.625013186418371e-05 	  Loss: 1.6207065407141386 	 Accuracy: 0.30638852672750977
Delta: 2.8944652387735247e-05 	  Loss: 1.6207749616727398 	 Accuracy: 0.3050847457627119
Delta: 5.01349488787663e-05 	  Loss: 1.6207664694619013 	 Accuracy: 0.3076923076923077
Delta: 0.0019170862891112234 	  Loss: 1.620898965126444 	 Accuracy: 0.30638852672750977
Delta: 0.0010794676844921205 	  Loss: 1.6209354093295105 	 Accuracy: 0.30638852672750977
Delta: 3.794267366800739e-05 	  Loss: 1.620740187947064 	 Accuracy: 0.30638852672750977
Delta: 0.0005690896111686672 	  Loss: 1.6207192945740334 	 Accuracy: 0.30638852672750977
Delta: 0.001203919661011939 	  Loss: 1.6209460901135335 	 Accuracy: 0.3050847457627119
Delta: 0.0005423505942358034 	  Loss: 1.6206956988945858 	 Accuracy: 0.30638852672750977
Delta: 1.3556162245409612e-05 	  Loss: 1.6207541832122034 	 Accuracy: 0.29465449804432853
Delta: 0.0006011066299574782 	  Loss: 1.6206110238786013 	 Accuracy: 0.30638852672750977
Delta: 0.0012275216722411643 	  Loss: 1.621039556392343 	 Accuracy: 0.30638852672750977
Delta: 0.0012479460827219473 	  Loss: 1.620763573315281 	 Accuracy: 0.3050847457627119
Delta: 0.0009682270805737519 	  Loss: 1.6207168346364833 	 Accuracy: 0.30638852672750977
Delta: 0.002468578210672722 	  Loss: 1.621465264034438 	 Accuracy: 0.30378096479791394
Delta: 0.0018477452472197599 	  Loss: 1.6220861630900139 	 Accuracy: 0.30638852672750977
Delta: 0.0027147777402353416 	  Loss: 1.622766243153254 	 Accuracy: 0.3089960886571056
Delta: 0.0026727284959653726 	  Loss: 1.622007380234296 	 Accuracy: 0.30638852672750977
Delta: 4.964926726779231e-05 	  Loss: 1.6221909936520191 	 Accuracy: 0.30638852672750977
Delta: 0.0029747299113148896 	  Loss: 1.6225993794439142 	 Accuracy: 0.30638852672750977
Delta: 0.004838225678513831 	  Loss: 1.623134006171843 	 Accuracy: 0.30638852672750977
Delta: 0.0016280700220563707 	  Loss: 1.6228729878701513 	 Accuracy: 0.30638852672750977
Delta: 0.0053740675370580445 	  Loss: 1.6225623311276793 	 Accuracy: 0.3089960886571056
Delta: 0.0024027435846146507 	  Loss: 1.6226421926937236 	 Accuracy: 0.3050847457627119
Delta: 0.004360797656284211 	  Loss: 1.6231501686973455 	 Accuracy: 0.30638852672750977
Delta: 0.004657584856723119 	  Loss: 1.623160022494413 	 Accuracy: 0.30638852672750977
Delta: 0.0005275815567932022 	  Loss: 1.623061216299722 	 Accuracy: 0.30378096479791394
Delta: 0.0024903226500177598 	  Loss: 1.6230760602297418 	 Accuracy: 0.30247718383311606
Delta: 0.002364452307222352 	  Loss: 1.6232335014452102 	 Accuracy: 0.30378096479791394
Delta: 0.0008822023320601746 	  Loss: 1.6233752869144331 	 Accuracy: 0.30378096479791394
Delta: 0.0010558382273115556 	  Loss: 1.6239712024758073 	 Accuracy: 0.30378096479791394
Delta: 0.0034520935092628856 	  Loss: 1.6231993925698989 	 Accuracy: 0.30247718383311606
Delta: 0.003155695619102217 	  Loss: 1.6229399877777455 	 Accuracy: 0.30378096479791394
Delta: 0.0038945693670833247 	  Loss: 1.624984568357279 	 Accuracy: 0.30247718383311606
Delta: 0.00316149988318362 	  Loss: 1.6247004764102992 	 Accuracy: 0.30247718383311606
Delta: 0.003264279658697809 	  Loss: 1.6253791564684605 	 Accuracy: 0.3011734028683181
Delta: 0.003610807406784615 	  Loss: 1.625595770431239 	 Accuracy: 0.3011734028683181
Delta: 0.001863998911511533 	  Loss: 1.625298043784091 	 Accuracy: 0.29986962190352023
Delta: 9.245305983652089e-05 	  Loss: 1.6258650599876825 	 Accuracy: 0.3011734028683181
Delta: 0.002018831597947595 	  Loss: 1.6251408301687222 	 Accuracy: 0.3011734028683181
Delta: 0.004134832104349933 	  Loss: 1.624695603061554 	 Accuracy: 0.3011734028683181
Delta: 0.004106601209188142 	  Loss: 1.6247515033783602 	 Accuracy: 0.29986962190352023
Delta: 0.0016909714321131117 	  Loss: 1.6248144408705794 	 Accuracy: 0.29986962190352023
Delta: 0.003007727032563534 	  Loss: 1.6252487416989343 	 Accuracy: 0.29986962190352023
Delta: 0.0020763210616188722 	  Loss: 1.625498847923092 	 Accuracy: 0.29986962190352023
Delta: 0.003083775697058616 	  Loss: 1.6246794386608516 	 Accuracy: 0.3011734028683181
Delta: 0.0029100935074079905 	  Loss: 1.6253097628900184 	 Accuracy: 0.3011734028683181
Delta: 0.0026018578612853308 	  Loss: 1.6256313613837319 	 Accuracy: 0.30247718383311606
Delta: 0.0008100190975685487 	  Loss: 1.6252762513662249 	 Accuracy: 0.29986962190352023
Delta: 0.003224502805926439 	  Loss: 1.6254089554168187 	 Accuracy: 0.2985658409387223
Delta: 0.00307791595157123 	  Loss: 1.6262454805821442 	 Accuracy: 0.29465449804432853
Delta: 0.004902257536362951 	  Loss: 1.6259820983941053 	 Accuracy: 0.2985658409387223
Delta: 0.0021971435691570955 	  Loss: 1.6261039212010002 	 Accuracy: 0.2985658409387223
Delta: 0.0034216428494641808 	  Loss: 1.6263272658638324 	 Accuracy: 0.2985658409387223
Delta: 0.003192369761093642 	  Loss: 1.625481709959023 	 Accuracy: 0.29726205997392435
Delta: 0.003996725068223804 	  Loss: 1.626447388229784 	 Accuracy: 0.2985658409387223
Delta: 0.00425079809313759 	  Loss: 1.6262090145458001 	 Accuracy: 0.29986962190352023
Delta: 0.0020760308841849466 	  Loss: 1.6266156018186246 	 Accuracy: 0.29465449804432853
Delta: 0.0020141346358993318 	  Loss: 1.626036230161997 	 Accuracy: 0.29986962190352023
Delta: 0.0011430782373058944 	  Loss: 1.625959541023842 	 Accuracy: 0.30247718383311606
Delta: 0.005115032200851529 	  Loss: 1.6248530770383955 	 Accuracy: 0.2985658409387223
Delta: 0.0037983735890665107 	  Loss: 1.626595681931586 	 Accuracy: 0.3011734028683181
Delta: 0.0007839687475172445 	  Loss: 1.6261105299909167 	 Accuracy: 0.2907431551499348
Delta: 0.0041559214357021045 	  Loss: 1.6275220125286116 	 Accuracy: 0.2920469361147327
Delta: 0.0040632126236615695 	  Loss: 1.6283262496978486 	 Accuracy: 0.2985658409387223
Delta: 0.004019235477057981 	  Loss: 1.6273447557766527 	 Accuracy: 0.2985658409387223
Delta: 0.02089769583296456 	  Loss: 2.1518785635502726 	 Accuracy: 0.20208604954367665
Delta: 0.019412565035573898 	  Loss: 2.029936526928702 	 Accuracy: 0.3963494132985658
Delta: 0.01766877026007456 	  Loss: 1.8241677415591901 	 Accuracy: 0.4445893089960887
Delta: 0.015950934676979826 	  Loss: 1.666101854034487 	 Accuracy: 0.43285528031290743
Delta: 0.012715041517432534 	  Loss: 1.59049132391898 	 Accuracy: 0.4106910039113429

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009559061335057923 	  Loss: 1.5726141259068593 	 Accuracy: 0.4028683181225554
Delta: 0.0073883922496710205 	  Loss: 1.5683371049085664 	 Accuracy: 0.4041720990873533
Delta: 0.005349732677194093 	  Loss: 1.5670772829896884 	 Accuracy: 0.40547588005215124
Delta: 0.004309941298431982 	  Loss: 1.5674381795166399 	 Accuracy: 0.409387222946545
Delta: 0.003364522875597447 	  Loss: 1.5675743815718346 	 Accuracy: 0.40808344198174706
Delta: 0.0038836273487351993 	  Loss: 1.5675537852576074 	 Accuracy: 0.40808344198174706
Delta: 0.0022238956066768603 	  Loss: 1.567499562747174 	 Accuracy: 0.40808344198174706
Delta: 0.000608106980430156 	  Loss: 1.5674500385839305 	 Accuracy: 0.40808344198174706
Delta: 0.0006960854284534115 	  Loss: 1.567452788604026 	 Accuracy: 0.409387222946545
Delta: 0.0020300887098053185 	  Loss: 1.5675250541954362 	 Accuracy: 0.409387222946545
Delta: 5.1819858127085815e-05 	  Loss: 1.5673464927680085 	 Accuracy: 0.409387222946545
Delta: 0.0017694032107106411 	  Loss: 1.5673395936904013 	 Accuracy: 0.409387222946545
Delta: 5.6725963482672466e-05 	  Loss: 1.5673648885341152 	 Accuracy: 0.4106910039113429
Delta: 3.115692669083325e-05 	  Loss: 1.5675112792976043 	 Accuracy: 0.40808344198174706
Delta: 3.090801596160149e-05 	  Loss: 1.5673946075312795 	 Accuracy: 0.409387222946545
Delta: 2.15238282300574e-05 	  Loss: 1.5674584074960738 	 Accuracy: 0.409387222946545
Delta: 6.726237518806271e-05 	  Loss: 1.5672989423725698 	 Accuracy: 0.41199478487614083
Delta: 0.001298477742726665 	  Loss: 1.566967066922417 	 Accuracy: 0.40808344198174706
Delta: 0.0013509583508670145 	  Loss: 1.567160413176684 	 Accuracy: 0.409387222946545
Delta: 0.0006664480336713079 	  Loss: 1.5673609821360195 	 Accuracy: 0.409387222946545
Delta: 5.4467262068990544e-05 	  Loss: 1.5675290862933258 	 Accuracy: 0.409387222946545
Delta: 3.871051632719509e-05 	  Loss: 1.5674977547941127 	 Accuracy: 0.409387222946545
Delta: 5.262373149479602e-05 	  Loss: 1.567386871950973 	 Accuracy: 0.409387222946545
Delta: 0.0021927261337930746 	  Loss: 1.5673690907713929 	 Accuracy: 0.409387222946545
Delta: 1.261103285913998e-05 	  Loss: 1.5673822120886332 	 Accuracy: 0.409387222946545
Delta: 8.029867979263154e-06 	  Loss: 1.5673980672440475 	 Accuracy: 0.409387222946545
Delta: 2.853353740906087e-05 	  Loss: 1.5673935071436285 	 Accuracy: 0.40547588005215124
Delta: 6.177266776855729e-05 	  Loss: 1.5675718027021228 	 Accuracy: 0.4132985658409387
Delta: 6.92872023136011e-05 	  Loss: 1.567541051915692 	 Accuracy: 0.409387222946545
Delta: 5.3690498942641505e-05 	  Loss: 1.5673899932427822 	 Accuracy: 0.409387222946545
Delta: 3.37928656264132e-05 	  Loss: 1.5673146487279483 	 Accuracy: 0.40808344198174706
Delta: 0.001754345029935087 	  Loss: 1.5672592799065108 	 Accuracy: 0.409387222946545
Delta: 0.0015808319487763418 	  Loss: 1.5672654597041271 	 Accuracy: 0.409387222946545
Delta: 0.0011989740153478458 	  Loss: 1.5674032184181481 	 Accuracy: 0.409387222946545
Delta: 5.344423823950489e-06 	  Loss: 1.567391478487676 	 Accuracy: 0.41199478487614083
Delta: 0.000980659165630545 	  Loss: 1.5675850294317124 	 Accuracy: 0.4106910039113429
Delta: 6.452413586313671e-05 	  Loss: 1.5673892119122383 	 Accuracy: 0.4028683181225554
Delta: 0.0007251802743507839 	  Loss: 1.5675410256168005 	 Accuracy: 0.4041720990873533
Delta: 4.8972402656466165e-05 	  Loss: 1.567410017495476 	 Accuracy: 0.40808344198174706
Delta: 0.00186821311100917 	  Loss: 1.5673988615368097 	 Accuracy: 0.409387222946545
Delta: 0.0011007199686417844 	  Loss: 1.5673919531587712 	 Accuracy: 0.409387222946545
Delta: 3.558884739486723e-05 	  Loss: 1.5673147911615313 	 Accuracy: 0.409387222946545
Delta: 3.730702307888782e-05 	  Loss: 1.5674071599395019 	 Accuracy: 0.409387222946545
Delta: 1.9565284164414638e-05 	  Loss: 1.567466255595379 	 Accuracy: 0.409387222946545
Delta: 7.994024966315434e-05 	  Loss: 1.5676061395240177 	 Accuracy: 0.409387222946545
Delta: 7.829192366695529e-05 	  Loss: 1.567392126063809 	 Accuracy: 0.409387222946545
Delta: 0.0006515983079050593 	  Loss: 1.5673379466360313 	 Accuracy: 0.409387222946545
Delta: 6.917150783016991e-06 	  Loss: 1.567344511992338 	 Accuracy: 0.409387222946545
Delta: 4.7905986087428715e-05 	  Loss: 1.5674086600825274 	 Accuracy: 0.409387222946545
Delta: 3.125672837250062e-05 	  Loss: 1.5673179367040846 	 Accuracy: 0.4106910039113429
Delta: 0.0006311308578546197 	  Loss: 1.5674548835107305 	 Accuracy: 0.40547588005215124
Delta: 0.002096221196396816 	  Loss: 1.56725528526326 	 Accuracy: 0.409387222946545
Delta: 0.001908343452113547 	  Loss: 1.5673926028200145 	 Accuracy: 0.40547588005215124
Delta: 0.001315607597593852 	  Loss: 1.5676838315547297 	 Accuracy: 0.40547588005215124
Delta: 0.003188065359718216 	  Loss: 1.567921841623908 	 Accuracy: 0.409387222946545
Delta: 7.211816167625937e-05 	  Loss: 1.568108418646733 	 Accuracy: 0.409387222946545
Delta: 0.002323221803148256 	  Loss: 1.5682629097014833 	 Accuracy: 0.409387222946545
Delta: 0.0027314414861590794 	  Loss: 1.5688598126098956 	 Accuracy: 0.409387222946545
Delta: 0.0015979842181651203 	  Loss: 1.568757475243813 	 Accuracy: 0.4106910039113429
Delta: 0.00339287684442916 	  Loss: 1.5680996106839684 	 Accuracy: 0.4106910039113429
Delta: 0.003639403503774381 	  Loss: 1.5687235025200146 	 Accuracy: 0.40808344198174706
Delta: 0.003514769521640418 	  Loss: 1.568966567573819 	 Accuracy: 0.40547588005215124
Delta: 0.00293314147278987 	  Loss: 1.5690102931649381 	 Accuracy: 0.4067796610169492
Delta: 0.002570297999015184 	  Loss: 1.5690003394170882 	 Accuracy: 0.40808344198174706
Delta: 0.004195166940621002 	  Loss: 1.5694611150863267 	 Accuracy: 0.40808344198174706
Delta: 0.0019169959654700536 	  Loss: 1.5693186069098715 	 Accuracy: 0.40808344198174706
Delta: 0.0033807038115648428 	  Loss: 1.5693318436020385 	 Accuracy: 0.4015645371577575
Delta: 0.005605270009456807 	  Loss: 1.571598714611079 	 Accuracy: 0.4041720990873533
Delta: 0.0034677883902375704 	  Loss: 1.5715257206488813 	 Accuracy: 0.4041720990873533
Delta: 0.0013461058047662456 	  Loss: 1.5714627737685163 	 Accuracy: 0.4041720990873533
Delta: 0.004814520355354308 	  Loss: 1.5706288142915168 	 Accuracy: 0.4015645371577575
Delta: 0.004400821755850225 	  Loss: 1.570755817229966 	 Accuracy: 0.4067796610169492
Delta: 0.004657471287503208 	  Loss: 1.569759294589944 	 Accuracy: 0.40547588005215124
Delta: 0.003365160534899594 	  Loss: 1.569815123856965 	 Accuracy: 0.40547588005215124
Delta: 0.0035985698716531895 	  Loss: 1.569666991456264 	 Accuracy: 0.40547588005215124
Delta: 0.0021488427224019358 	  Loss: 1.5694692570955984 	 Accuracy: 0.40808344198174706
Delta: 0.004457207027707471 	  Loss: 1.5689726108213895 	 Accuracy: 0.40808344198174706
Delta: 0.003102831542744092 	  Loss: 1.569681940360605 	 Accuracy: 0.409387222946545
Delta: 0.001843765023806882 	  Loss: 1.5697805294375904 	 Accuracy: 0.409387222946545
Delta: 0.003392777424035417 	  Loss: 1.5705884541679813 	 Accuracy: 0.3963494132985658
Delta: 0.0037446547986472387 	  Loss: 1.5712442568537708 	 Accuracy: 0.4067796610169492
Delta: 0.004962418569414043 	  Loss: 1.5707529362196617 	 Accuracy: 0.4041720990873533
Delta: 0.003697111105477345 	  Loss: 1.571163978406355 	 Accuracy: 0.40547588005215124
Delta: 0.0030078369100957313 	  Loss: 1.57133951937314 	 Accuracy: 0.40547588005215124
Delta: 0.0005000140183855054 	  Loss: 1.5713628954842602 	 Accuracy: 0.4067796610169492
Delta: 0.0035059930939083397 	  Loss: 1.571098931240801 	 Accuracy: 0.4067796610169492
Delta: 1.0459837515082626e-05 	  Loss: 1.5711061699038908 	 Accuracy: 0.4067796610169492
Delta: 0.0036356768948144617 	  Loss: 1.570692096306582 	 Accuracy: 0.409387222946545
Delta: 0.003111687067456196 	  Loss: 1.5699727240565005 	 Accuracy: 0.409387222946545
Delta: 0.003022914488756452 	  Loss: 1.5691479287570056 	 Accuracy: 0.4041720990873533
Delta: 0.004979223119017647 	  Loss: 1.570452157795515 	 Accuracy: 0.409387222946545
Delta: 0.0035107021558157276 	  Loss: 1.56907809189439 	 Accuracy: 0.40808344198174706
Delta: 0.0038474120585971173 	  Loss: 1.5699547794812414 	 Accuracy: 0.40808344198174706
Delta: 0.002576182862247093 	  Loss: 1.569646490297533 	 Accuracy: 0.40808344198174706
Delta: 0.0030354857802028356 	  Loss: 1.5693709379577963 	 Accuracy: 0.4106910039113429
Delta: 0.02110015829096325 	  Loss: 2.151554833195765 	 Accuracy: 0.19035202086049544
Delta: 0.019546194896985666 	  Loss: 2.02850722655327 	 Accuracy: 0.26727509778357234
Delta: 0.01777499210446429 	  Loss: 1.8278285497689182 	 Accuracy: 0.35071707953063885
Delta: 0.015628687684026994 	  Loss: 1.7077511869843276 	 Accuracy: 0.3350717079530639
Delta: 0.013213943968040974 	  Loss: 1.6556025165311492 	 Accuracy: 0.32985658409387225
Delta: 0.009116440061930381 	  Loss: 1.6398224716834142 	 Accuracy: 0.32333767926988266

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007444323587634489 	  Loss: 1.635778495388751 	 Accuracy: 0.3259452411994785
Delta: 0.006290570420408017 	  Loss: 1.6345710736283239 	 Accuracy: 0.33116036505867014
Delta: 0.003797937439939936 	  Loss: 1.6337388231693954 	 Accuracy: 0.3285528031290743
Delta: 0.0040232436585759136 	  Loss: 1.6333654810757232 	 Accuracy: 0.3285528031290743
Delta: 0.0030575277775496497 	  Loss: 1.6336369415578722 	 Accuracy: 0.3285528031290743
Delta: 0.002193484985724823 	  Loss: 1.6336752609674954 	 Accuracy: 0.3285528031290743
Delta: 4.9370894201589554e-05 	  Loss: 1.63367813041372 	 Accuracy: 0.3089960886571056
Delta: 0.002006863103378839 	  Loss: 1.6339609549738459 	 Accuracy: 0.3285528031290743
Delta: 0.0017148200411316009 	  Loss: 1.6338307752499914 	 Accuracy: 0.3285528031290743
Delta: 0.0012618588835857393 	  Loss: 1.6338079814071813 	 Accuracy: 0.3272490221642764
Delta: 0.0035781795561515895 	  Loss: 1.6341389347018909 	 Accuracy: 0.3285528031290743
Delta: 0.0027204894987582374 	  Loss: 1.634619918722254 	 Accuracy: 0.32985658409387225
Delta: 0.0018708960236206254 	  Loss: 1.634480875061698 	 Accuracy: 0.32985658409387225
Delta: 0.001256995577903475 	  Loss: 1.6344598139118522 	 Accuracy: 0.32985658409387225
Delta: 2.817800216505199e-05 	  Loss: 1.6344569363011543 	 Accuracy: 0.32985658409387225
Delta: 5.909886656162e-06 	  Loss: 1.6344547891452175 	 Accuracy: 0.32985658409387225
Delta: 1.4563030446882994e-05 	  Loss: 1.634467695462937 	 Accuracy: 0.32985658409387225
Delta: 1.4414683995605199e-05 	  Loss: 1.6344557251281095 	 Accuracy: 0.3246414602346806
Delta: 0.002375495114135121 	  Loss: 1.63451409673101 	 Accuracy: 0.32985658409387225
Delta: 4.4670198421787956e-05 	  Loss: 1.6344463854140565 	 Accuracy: 0.32985658409387225
Delta: 0.0007017999025455542 	  Loss: 1.634421459221938 	 Accuracy: 0.3272490221642764
Delta: 0.001393542823481284 	  Loss: 1.6345316900563702 	 Accuracy: 0.32985658409387225
Delta: 0.0005619119031507772 	  Loss: 1.634701416606964 	 Accuracy: 0.32985658409387225
Delta: 5.654969358087761e-05 	  Loss: 1.6347922225661669 	 Accuracy: 0.3285528031290743
Delta: 0.0005638297870324544 	  Loss: 1.634599452799545 	 Accuracy: 0.32985658409387225
Delta: 0.0007522121604520683 	  Loss: 1.6345501941665739 	 Accuracy: 0.3285528031290743
Delta: 7.021642641694617e-05 	  Loss: 1.6344266331190813 	 Accuracy: 0.32985658409387225
Delta: 0.00276980718866165 	  Loss: 1.6342363058912057 	 Accuracy: 0.3246414602346806
Delta: 0.0027619846784172407 	  Loss: 1.6342679464759478 	 Accuracy: 0.3285528031290743
Delta: 0.0035867110338834193 	  Loss: 1.6342615335351072 	 Accuracy: 0.3272490221642764
Delta: 0.003894305552846782 	  Loss: 1.6337394093837327 	 Accuracy: 0.3285528031290743
Delta: 0.0038848939191602635 	  Loss: 1.6345816094711716 	 Accuracy: 0.3285528031290743
Delta: 0.0015908164026541306 	  Loss: 1.6340063217369933 	 Accuracy: 0.3285528031290743
Delta: 0.003097480709667099 	  Loss: 1.6340440695342375 	 Accuracy: 0.3285528031290743
Delta: 0.0007429534829169114 	  Loss: 1.6341769648898583 	 Accuracy: 0.3285528031290743
Delta: 0.0010290405249603455 	  Loss: 1.6341266218781383 	 Accuracy: 0.32985658409387225
Delta: 0.0018313405436089557 	  Loss: 1.6342092269698996 	 Accuracy: 0.32985658409387225
Delta: 0.0005594365698446622 	  Loss: 1.6341569091907642 	 Accuracy: 0.32985658409387225
Delta: 0.003620799317460801 	  Loss: 1.6341674135765825 	 Accuracy: 0.33116036505867014
Delta: 0.003484615081140716 	  Loss: 1.6341458890088234 	 Accuracy: 0.33116036505867014
Delta: 6.49618997697246e-05 	  Loss: 1.633978079931219 	 Accuracy: 0.32985658409387225
Delta: 0.000893410441657509 	  Loss: 1.6339887380996412 	 Accuracy: 0.33116036505867014
Delta: 0.0037721512414076548 	  Loss: 1.6341250633738995 	 Accuracy: 0.33116036505867014
Delta: 1.790489191746579e-05 	  Loss: 1.6341305066996044 	 Accuracy: 0.33116036505867014
Delta: 0.0027494569306362637 	  Loss: 1.6344962068489488 	 Accuracy: 0.32985658409387225
Delta: 0.003089270710682265 	  Loss: 1.6345095791710686 	 Accuracy: 0.32985658409387225
Delta: 0.0008286589814748634 	  Loss: 1.634729764576729 	 Accuracy: 0.33116036505867014
Delta: 0.002599690114474397 	  Loss: 1.6344583073490453 	 Accuracy: 0.33116036505867014
Delta: 0.00012489968337319696 	  Loss: 1.6342991247321925 	 Accuracy: 0.33116036505867014
Delta: 0.0019231481582245474 	  Loss: 1.6341921326434985 	 Accuracy: 0.33116036505867014
Delta: 0.0007234445148442442 	  Loss: 1.6341763863778667 	 Accuracy: 0.33116036505867014
Delta: 0.005451592456445527 	  Loss: 1.636216679685405 	 Accuracy: 0.33116036505867014
Delta: 0.005034804384207858 	  Loss: 1.6365568600259386 	 Accuracy: 0.33116036505867014
Delta: 0.0036518447436437633 	  Loss: 1.6367769183173193 	 Accuracy: 0.33376792698826596
Delta: 0.002923266901949545 	  Loss: 1.6365721896644239 	 Accuracy: 0.33116036505867014
Delta: 0.004352120427580818 	  Loss: 1.6359325758840706 	 Accuracy: 0.33116036505867014
Delta: 0.0023625743440449072 	  Loss: 1.6366659144621778 	 Accuracy: 0.33116036505867014
Delta: 0.004733349809514372 	  Loss: 1.6360626590224316 	 Accuracy: 0.3350717079530639
Delta: 0.0005612114377201828 	  Loss: 1.636321830614433 	 Accuracy: 0.32985658409387225
Delta: 0.00010900927514747037 	  Loss: 1.6363784084777198 	 Accuracy: 0.33116036505867014
Delta: 0.0005853746461076886 	  Loss: 1.636380044560766 	 Accuracy: 0.33116036505867014
Delta: 6.219925880835675e-05 	  Loss: 1.6362759588062934 	 Accuracy: 0.3324641460234681
Delta: 0.0033133581043136447 	  Loss: 1.6373144635309749 	 Accuracy: 0.33116036505867014
Delta: 0.0005537569495212648 	  Loss: 1.637005375769355 	 Accuracy: 0.32985658409387225
Delta: 0.0011206318633642694 	  Loss: 1.6371773995754966 	 Accuracy: 0.33116036505867014
Delta: 0.0009605294390711594 	  Loss: 1.6369348599550737 	 Accuracy: 0.3285528031290743
Delta: 0.003466067100831822 	  Loss: 1.6371890846536883 	 Accuracy: 0.33116036505867014
Delta: 0.002241475211636798 	  Loss: 1.6374703269171405 	 Accuracy: 0.33116036505867014
Delta: 0.001244978119722211 	  Loss: 1.6371884340266019 	 Accuracy: 0.3285528031290743
Delta: 0.0005438150091037019 	  Loss: 1.6369705792824552 	 Accuracy: 0.33116036505867014
Delta: 7.692205416853837e-05 	  Loss: 1.6373390657380276 	 Accuracy: 0.33116036505867014
Delta: 1.7153518587375072e-05 	  Loss: 1.6372796070017626 	 Accuracy: 0.33116036505867014
Delta: 6.163657887410656e-05 	  Loss: 1.6370448754158344 	 Accuracy: 0.33116036505867014
Delta: 2.034409534314414e-05 	  Loss: 1.6370542467906892 	 Accuracy: 0.33116036505867014
Delta: 1.8922769585761223e-05 	  Loss: 1.6369903007540874 	 Accuracy: 0.3324641460234681
Delta: 1.2846225765461868e-05 	  Loss: 1.6370294676212427 	 Accuracy: 0.33116036505867014
Delta: 1.6148933360650014e-05 	  Loss: 1.6369689953519024 	 Accuracy: 0.33116036505867014
Delta: 5.909103799940117e-06 	  Loss: 1.6369868046091811 	 Accuracy: 0.33116036505867014
Delta: 8.014679000585769e-05 	  Loss: 1.6373483283074481 	 Accuracy: 0.33116036505867014
Delta: 1.1061153301773895e-06 	  Loss: 1.6373473611667628 	 Accuracy: 0.33116036505867014
Delta: 0.0014628054882778075 	  Loss: 1.6369639643887106 	 Accuracy: 0.33116036505867014
Delta: 0.0010244618097034624 	  Loss: 1.6370435309183369 	 Accuracy: 0.3363754889178618
Delta: 0.00484005647184935 	  Loss: 1.6360222473518524 	 Accuracy: 0.33376792698826596
Delta: 0.004230310341862371 	  Loss: 1.635667796595317 	 Accuracy: 0.33116036505867014
Delta: 0.002082204590162698 	  Loss: 1.6357403315961472 	 Accuracy: 0.32985658409387225
Delta: 0.002146007728774661 	  Loss: 1.635769800072199 	 Accuracy: 0.33116036505867014
Delta: 0.0026720902371737843 	  Loss: 1.6361774631253536 	 Accuracy: 0.32985658409387225
Delta: 0.004748513063287797 	  Loss: 1.638017515980494 	 Accuracy: 0.32985658409387225
Delta: 3.2105041795411904e-05 	  Loss: 1.63803449984495 	 Accuracy: 0.33116036505867014
Delta: 0.004025845301831903 	  Loss: 1.6378814645697422 	 Accuracy: 0.33116036505867014
Delta: 0.0036155827703015127 	  Loss: 1.6389346981235726 	 Accuracy: 0.3285528031290743
Delta: 0.004316310786385265 	  Loss: 1.6388796031307276 	 Accuracy: 0.32985658409387225
Delta: 0.002558262246442403 	  Loss: 1.639372243508097 	 Accuracy: 0.3272490221642764
Delta: 0.004239046372527505 	  Loss: 1.6401627468380573 	 Accuracy: 0.32985658409387225
Delta: 0.020907279529308594 	  Loss: 2.1520296708243167 	 Accuracy: 0.2046936114732725
Delta: 0.01943087005221639 	  Loss: 2.028408359553772 	 Accuracy: 0.34810951760104303
Delta: 0.018151036839151008 	  Loss: 1.8195067132037517 	 Accuracy: 0.40808344198174706
Delta: 0.015982647644543848 	  Loss: 1.679233218635182 	 Accuracy: 0.39895697522816165
Delta: 0.013180572158734413 	  Loss: 1.6171547047465382 	 Accuracy: 0.35984354628422427

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010222773248849248 	  Loss: 1.5946800463823596 	 Accuracy: 0.3520208604954368
Delta: 0.007197730033211437 	  Loss: 1.5892992738088756 	 Accuracy: 0.34419817470664926
Delta: 0.005961695214368901 	  Loss: 1.589066171947493 	 Accuracy: 0.34810951760104303
Delta: 0.004808284954626069 	  Loss: 1.5880844750205125 	 Accuracy: 0.3494132985658409
Delta: 0.003544629669526919 	  Loss: 1.5881909222184893 	 Accuracy: 0.3455019556714472
Delta: 0.003473939714357875 	  Loss: 1.5881499707617983 	 Accuracy: 0.3468057366362451
Delta: 0.002596709380302498 	  Loss: 1.5880909239944203 	 Accuracy: 0.3468057366362451
Delta: 0.002493982703164875 	  Loss: 1.5879039598170521 	 Accuracy: 0.3468057366362451
Delta: 8.873788614420779e-05 	  Loss: 1.5879462009115106 	 Accuracy: 0.3468057366362451
Delta: 0.001562556980074404 	  Loss: 1.5877806564334938 	 Accuracy: 0.3468057366362451
Delta: 4.956711179224063e-05 	  Loss: 1.5878719652438136 	 Accuracy: 0.3455019556714472
Delta: 3.897107070013245e-05 	  Loss: 1.5879743225070078 	 Accuracy: 0.3455019556714472
Delta: 3.936053163685914e-05 	  Loss: 1.5879346797549982 	 Accuracy: 0.3468057366362451
Delta: 6.9970772071116e-05 	  Loss: 1.5878352001107536 	 Accuracy: 0.3428943937418514
Delta: 7.324214018885872e-05 	  Loss: 1.5880699792425206 	 Accuracy: 0.3455019556714472
Delta: 1.628589090627091e-05 	  Loss: 1.5879428872059402 	 Accuracy: 0.3455019556714472
Delta: 4.965187929783761e-06 	  Loss: 1.5879248931508627 	 Accuracy: 0.3468057366362451
Delta: 0.0013209938820583917 	  Loss: 1.587956810779679 	 Accuracy: 0.3468057366362451
Delta: 4.15967140689987e-05 	  Loss: 1.587904451762507 	 Accuracy: 0.34419817470664926
Delta: 5.007211666560306e-05 	  Loss: 1.5878045175845126 	 Accuracy: 0.3468057366362451
Delta: 5.221828145203501e-05 	  Loss: 1.5878940135085493 	 Accuracy: 0.3468057366362451
Delta: 0.0010936214213291082 	  Loss: 1.5875638341326335 	 Accuracy: 0.3468057366362451
Delta: 0.00012147806579533792 	  Loss: 1.5880361395977425 	 Accuracy: 0.3455019556714472
Delta: 0.0017340854073111807 	  Loss: 1.5880106957803994 	 Accuracy: 0.3455019556714472
Delta: 7.590900971487884e-05 	  Loss: 1.5880702490804646 	 Accuracy: 0.3455019556714472
Delta: 0.00237363035166654 	  Loss: 1.5886802411516328 	 Accuracy: 0.3494132985658409
Delta: 4.8407383007949343e-05 	  Loss: 1.5886849100095737 	 Accuracy: 0.3468057366362451
Delta: 0.0018427762189275792 	  Loss: 1.588969110796894 	 Accuracy: 0.34810951760104303
Delta: 0.0019041169032715433 	  Loss: 1.5881629758456879 	 Accuracy: 0.3455019556714472
Delta: 0.002344188812904769 	  Loss: 1.5888039123874762 	 Accuracy: 0.34028683181225555
Delta: 0.004256814869297616 	  Loss: 1.5881480892951296 	 Accuracy: 0.34159061277705344
Delta: 0.0019764654761194357 	  Loss: 1.5881645885918543 	 Accuracy: 0.3455019556714472
Delta: 0.0025316527540238548 	  Loss: 1.5877163018318425 	 Accuracy: 0.3455019556714472
Delta: 0.0020076746748818406 	  Loss: 1.5875677669841939 	 Accuracy: 0.3455019556714472
Delta: 0.0005353257813510485 	  Loss: 1.5876213047945225 	 Accuracy: 0.3455019556714472
Delta: 3.6280160168036416e-07 	  Loss: 1.587621738473026 	 Accuracy: 0.3455019556714472
Delta: 4.1340177804780895e-07 	  Loss: 1.5876216927006492 	 Accuracy: 0.3428943937418514
converged at iter  41
Delta: 0.02102772024678392 	  Loss: 2.1510241157440784 	 Accuracy: 0.21642764015645372
Delta: 0.019494495559630443 	  Loss: 2.0179302987963292 	 Accuracy: 0.33376792698826596
Delta: 0.01800196318893071 	  Loss: 1.7790283286043507 	 Accuracy: 0.46936114732724904
Delta: 0.01585835428808371 	  Loss: 1.6359224888418953 	 Accuracy: 0.43546284224250326

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.012258726472327501 	  Loss: 1.5907143801917416 	 Accuracy: 0.43285528031290743
Delta: 0.009180717149866235 	  Loss: 1.5777805911325653 	 Accuracy: 0.42894393741851367
Delta: 0.007106280115853685 	  Loss: 1.5747022041405319 	 Accuracy: 0.4315514993481095
Delta: 0.006589360263096618 	  Loss: 1.5732973259975436 	 Accuracy: 0.43285528031290743
Delta: 0.004848351636134176 	  Loss: 1.5724167275623417 	 Accuracy: 0.43415906127770537
Delta: 0.0039062394704054105 	  Loss: 1.572113760450509 	 Accuracy: 0.43415906127770537
Delta: 0.0023662615655189903 	  Loss: 1.572226270230117 	 Accuracy: 0.43285528031290743
Delta: 0.0027068350968413985 	  Loss: 1.5724233222549358 	 Accuracy: 0.43285528031290743
Delta: 0.0020215996227727407 	  Loss: 1.5724268165142297 	 Accuracy: 0.43285528031290743
Delta: 0.0005204809687120451 	  Loss: 1.5724242804756603 	 Accuracy: 0.42503259452411996
Delta: 0.0016840301333214812 	  Loss: 1.57252248088962 	 Accuracy: 0.43285528031290743
Delta: 0.0005125343441975805 	  Loss: 1.5726112914861985 	 Accuracy: 0.4315514993481095
Delta: 0.002089491333876207 	  Loss: 1.573029890518867 	 Accuracy: 0.43285528031290743
Delta: 4.932644445403831e-05 	  Loss: 1.5731257660545936 	 Accuracy: 0.43285528031290743
Delta: 7.613552333671128e-05 	  Loss: 1.5728222178438003 	 Accuracy: 0.43285528031290743
Delta: 4.155009727160112e-05 	  Loss: 1.5728830865217134 	 Accuracy: 0.43285528031290743
Delta: 0.0026871433421731907 	  Loss: 1.5727965553181218 	 Accuracy: 0.43285528031290743
Delta: 0.0009416339869237304 	  Loss: 1.5725659901678457 	 Accuracy: 0.43285528031290743
Delta: 0.0009043024676901693 	  Loss: 1.572364520498402 	 Accuracy: 0.43285528031290743
Delta: 0.001541712428851844 	  Loss: 1.5727733852498091 	 Accuracy: 0.43285528031290743
Delta: 5.498862257301239e-05 	  Loss: 1.5729149740297053 	 Accuracy: 0.43285528031290743
Delta: 0.0021605898192166694 	  Loss: 1.5729144097861174 	 Accuracy: 0.43285528031290743
Delta: 7.812288553070666e-05 	  Loss: 1.5727633559435623 	 Accuracy: 0.43285528031290743
Delta: 0.0017342988539963996 	  Loss: 1.5731717230400515 	 Accuracy: 0.4315514993481095
Delta: 0.002044513190652739 	  Loss: 1.5728408169407717 	 Accuracy: 0.43415906127770537
Delta: 0.0051596349074303416 	  Loss: 1.572965015794839 	 Accuracy: 0.43285528031290743
Delta: 0.0014678567172047544 	  Loss: 1.572935771592809 	 Accuracy: 0.43285528031290743
Delta: 0.0017923480092640338 	  Loss: 1.5729114818065235 	 Accuracy: 0.43285528031290743
Delta: 0.001950953431484078 	  Loss: 1.572946757993908 	 Accuracy: 0.42894393741851367
Delta: 0.0015922667463596654 	  Loss: 1.572951997615267 	 Accuracy: 0.43285528031290743
Delta: 5.278994577735913e-05 	  Loss: 1.5730136900116705 	 Accuracy: 0.43285528031290743
Delta: 3.694642414489285e-05 	  Loss: 1.5728958592381228 	 Accuracy: 0.4315514993481095
Delta: 3.083870843101849e-05 	  Loss: 1.572960495937031 	 Accuracy: 0.43415906127770537
Delta: 0.0008408696562746532 	  Loss: 1.5725253873511433 	 Accuracy: 0.43285528031290743
Delta: 0.003706942579617072 	  Loss: 1.5724150725337749 	 Accuracy: 0.43285528031290743
Delta: 0.002375727365354106 	  Loss: 1.5721573452839555 	 Accuracy: 0.43285528031290743
Delta: 0.002721671441367048 	  Loss: 1.5723572782483592 	 Accuracy: 0.4315514993481095
Delta: 0.00284617129090377 	  Loss: 1.5724073245512427 	 Accuracy: 0.4302477183833116
Delta: 0.0019476498722786296 	  Loss: 1.5723648701294586 	 Accuracy: 0.4315514993481095
Delta: 0.003102402997216095 	  Loss: 1.5723367834751474 	 Accuracy: 0.43285528031290743
Delta: 0.00465379797012141 	  Loss: 1.5718742733864977 	 Accuracy: 0.439374185136897
Delta: 0.0023651835100841354 	  Loss: 1.5717096540339486 	 Accuracy: 0.43285528031290743
Delta: 0.0018955819233801177 	  Loss: 1.5719161945650546 	 Accuracy: 0.4198174706649283
Delta: 0.003783858968106359 	  Loss: 1.5715196497733448 	 Accuracy: 0.43285528031290743
Delta: 0.002198851440849284 	  Loss: 1.572164727659215 	 Accuracy: 0.43285528031290743
Delta: 0.0030968855424074286 	  Loss: 1.572136323191006 	 Accuracy: 0.43546284224250326
Delta: 0.0027351807212030823 	  Loss: 1.5723498148089112 	 Accuracy: 0.4315514993481095
Delta: 0.0043493721081446 	  Loss: 1.5717983781866305 	 Accuracy: 0.43285528031290743
Delta: 0.001872650847082756 	  Loss: 1.5718960424237731 	 Accuracy: 0.43546284224250326
Delta: 5.211395944972832e-05 	  Loss: 1.5720929621235937 	 Accuracy: 0.43415906127770537
Delta: 5.414746996947623e-05 	  Loss: 1.5718897792820896 	 Accuracy: 0.43546284224250326
Delta: 0.002460670251451581 	  Loss: 1.5718883517951903 	 Accuracy: 0.4315514993481095
Delta: 0.00011851676731349513 	  Loss: 1.5719702310238133 	 Accuracy: 0.43415906127770537
Delta: 0.004469603618976421 	  Loss: 1.5708766561053737 	 Accuracy: 0.43285528031290743
Delta: 0.000543596673451084 	  Loss: 1.5712602533617952 	 Accuracy: 0.43285528031290743
Delta: 1.2942314097331004e-06 	  Loss: 1.5712601521075893 	 Accuracy: 0.4276401564537158
Delta: 6.425897290860098e-05 	  Loss: 1.5714121390360152 	 Accuracy: 0.43285528031290743
Delta: 6.630267040873507e-05 	  Loss: 1.5712214027035394 	 Accuracy: 0.43285528031290743
Delta: 4.559488851873829e-05 	  Loss: 1.5715137045225331 	 Accuracy: 0.43285528031290743
Delta: 4.3092298895989793e-05 	  Loss: 1.571263071493949 	 Accuracy: 0.43285528031290743
Delta: 1.6323277771953594e-05 	  Loss: 1.5712000346699722 	 Accuracy: 0.43546284224250326
Delta: 0.0032268315796180774 	  Loss: 1.5706740990423238 	 Accuracy: 0.43546284224250326
Delta: 0.004652789643982585 	  Loss: 1.5691150237598261 	 Accuracy: 0.43546284224250326
Delta: 0.0016892393897151594 	  Loss: 1.569715508718951 	 Accuracy: 0.43415906127770537
Delta: 3.26128561084643e-05 	  Loss: 1.5697088940882225 	 Accuracy: 0.43415906127770537
Delta: 0.0018876736536795255 	  Loss: 1.5699774461267237 	 Accuracy: 0.43285528031290743
Delta: 0.0024425134898016353 	  Loss: 1.5698333944407525 	 Accuracy: 0.43285528031290743
Delta: 0.0025891631038454004 	  Loss: 1.5699930406194937 	 Accuracy: 0.4315514993481095
Delta: 0.005467254123436423 	  Loss: 1.5682550910419826 	 Accuracy: 0.4302477183833116
Delta: 0.005834134466088316 	  Loss: 1.5690352923428383 	 Accuracy: 0.43285528031290743
Delta: 0.0027370205420699893 	  Loss: 1.5693956481352942 	 Accuracy: 0.4302477183833116
Delta: 0.0040773298744767724 	  Loss: 1.5709089257942859 	 Accuracy: 0.4315514993481095
Delta: 0.0027986662710987836 	  Loss: 1.5709878582449672 	 Accuracy: 0.4315514993481095
Delta: 0.003270114612838971 	  Loss: 1.5712334803970265 	 Accuracy: 0.4315514993481095
Delta: 0.003416729234302786 	  Loss: 1.572279846421106 	 Accuracy: 0.43415906127770537
Delta: 0.004568959247267409 	  Loss: 1.570870252954873 	 Accuracy: 0.4315514993481095
Delta: 0.005172357884484634 	  Loss: 1.5772205630895217 	 Accuracy: 0.4315514993481095
Delta: 0.0013003858614857378 	  Loss: 1.5772389072005035 	 Accuracy: 0.4315514993481095
Delta: 2.0333762011975495e-06 	  Loss: 1.5772376446016252 	 Accuracy: 0.4315514993481095
Delta: 1.574641071256944e-07 	  Loss: 1.5772376667532313 	 Accuracy: 0.4315514993481095
converged at iter  83
Delta: 0.02119502468914424 	  Loss: 2.148649750897566 	 Accuracy: 0.20860495436766624
Delta: 0.019365160036791344 	  Loss: 2.0131557104999205 	 Accuracy: 0.4067796610169492
Delta: 0.01778941348989115 	  Loss: 1.7853700976079487 	 Accuracy: 0.4315514993481095
Delta: 0.015783417876820537 	  Loss: 1.649395988065511 	 Accuracy: 0.4015645371577575
Delta: 0.011489771421527342 	  Loss: 1.6161937910606705 	 Accuracy: 0.38070404172099087

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008036746337276425 	  Loss: 1.609012599554072 	 Accuracy: 0.3741851368970013
Delta: 0.0058300402459811815 	  Loss: 1.6077447074817048 	 Accuracy: 0.3741851368970013
Delta: 0.005574686655985372 	  Loss: 1.6080245421975035 	 Accuracy: 0.3728813559322034
Delta: 0.0036395241112046443 	  Loss: 1.6082557137158204 	 Accuracy: 0.37157757496740546
Delta: 0.0028444350493073436 	  Loss: 1.6083848666700566 	 Accuracy: 0.37027379400260757
Delta: 0.0010160367016349646 	  Loss: 1.6084192298577769 	 Accuracy: 0.37027379400260757
Delta: 0.0022628815098422223 	  Loss: 1.6085937705723132 	 Accuracy: 0.37027379400260757
Delta: 0.0005244788243494338 	  Loss: 1.6085982534525003 	 Accuracy: 0.36766623207301175
Delta: 0.003432650749483903 	  Loss: 1.6083380046340607 	 Accuracy: 0.37027379400260757
Delta: 0.002290258491210897 	  Loss: 1.607965061963728 	 Accuracy: 0.37027379400260757
Delta: 0.0008647139999167103 	  Loss: 1.6079219040626545 	 Accuracy: 0.36897001303780963
Delta: 0.0016719175134696234 	  Loss: 1.6077318077452074 	 Accuracy: 0.37027379400260757
Delta: 4.46130966811087e-05 	  Loss: 1.607956396058766 	 Accuracy: 0.37027379400260757
Delta: 0.001326005781845003 	  Loss: 1.6078010635327462 	 Accuracy: 0.37157757496740546
Delta: 0.0010022216992799642 	  Loss: 1.6079842520919196 	 Accuracy: 0.37027379400260757
Delta: 7.656990371942143e-05 	  Loss: 1.6079595424331172 	 Accuracy: 0.37027379400260757
Delta: 6.538323239152678e-05 	  Loss: 1.608008879176809 	 Accuracy: 0.36897001303780963
Delta: 0.001982354588070679 	  Loss: 1.608101281729987 	 Accuracy: 0.37027379400260757
Delta: 0.000774696602394871 	  Loss: 1.6079507781766909 	 Accuracy: 0.37027379400260757
Delta: 4.0911818121497484e-05 	  Loss: 1.6079286826758636 	 Accuracy: 0.37027379400260757
Delta: 4.13400320831089e-05 	  Loss: 1.608031731514053 	 Accuracy: 0.3728813559322034
Delta: 2.8604242935285145e-05 	  Loss: 1.6078787175941471 	 Accuracy: 0.37027379400260757
Delta: 0.0035883330488083853 	  Loss: 1.6081115731288467 	 Accuracy: 0.36766623207301175
Delta: 0.0023258202354088644 	  Loss: 1.6079404488722073 	 Accuracy: 0.36766623207301175
Delta: 0.0024463278260135044 	  Loss: 1.6077893643917551 	 Accuracy: 0.37027379400260757
Delta: 0.0014470365453066406 	  Loss: 1.6075761169098628 	 Accuracy: 0.3663624511082138
Delta: 0.0012068963582130578 	  Loss: 1.6076734010240066 	 Accuracy: 0.36897001303780963
Delta: 0.0005300882955456683 	  Loss: 1.6075136502080967 	 Accuracy: 0.36897001303780963
Delta: 0.0009780726425725323 	  Loss: 1.6075115853073765 	 Accuracy: 0.3663624511082138
Delta: 8.644371892301839e-05 	  Loss: 1.607268617095939 	 Accuracy: 0.3663624511082138
Delta: 0.0025337178443290477 	  Loss: 1.607272791270717 	 Accuracy: 0.3650586701434159
Delta: 0.0014233946163149894 	  Loss: 1.607284178284894 	 Accuracy: 0.3663624511082138
Delta: 6.710667727153957e-05 	  Loss: 1.607230046873573 	 Accuracy: 0.3663624511082138
Delta: 4.044496257404161e-06 	  Loss: 1.6072307883291583 	 Accuracy: 0.3663624511082138
Delta: 4.319713806990976e-05 	  Loss: 1.6070186492509744 	 Accuracy: 0.363754889178618
Delta: 4.739263534524926e-05 	  Loss: 1.6071793782449242 	 Accuracy: 0.3663624511082138
Delta: 0.0005100033683031047 	  Loss: 1.6071865135999719 	 Accuracy: 0.3663624511082138
Delta: 4.065843436844339e-05 	  Loss: 1.60729959420653 	 Accuracy: 0.3663624511082138
Delta: 3.790000488675108e-05 	  Loss: 1.6072281246485245 	 Accuracy: 0.3663624511082138
Delta: 1.218519204452688e-06 	  Loss: 1.6072297752723306 	 Accuracy: 0.36766623207301175
Delta: 0.0006464389474249175 	  Loss: 1.6073847459399573 	 Accuracy: 0.35853976531942633
Delta: 0.005269285544055041 	  Loss: 1.609287654151554 	 Accuracy: 0.3624511082138201
Delta: 0.005049262003543516 	  Loss: 1.6082612599638626 	 Accuracy: 0.363754889178618
Delta: 0.0005090515309732412 	  Loss: 1.608231628119096 	 Accuracy: 0.363754889178618
Delta: 0.0023005946441334853 	  Loss: 1.6078748413569408 	 Accuracy: 0.3624511082138201
Delta: 0.004768835841986115 	  Loss: 1.6069815490120962 	 Accuracy: 0.3624511082138201
Delta: 0.0015185579622633283 	  Loss: 1.6067679079562047 	 Accuracy: 0.35984354628422427
Delta: 0.0005496543956547765 	  Loss: 1.6065725491847211 	 Accuracy: 0.363754889178618
Delta: 0.001172905257306464 	  Loss: 1.6068039506129308 	 Accuracy: 0.363754889178618
Delta: 6.526583327492675e-05 	  Loss: 1.6066592042715144 	 Accuracy: 0.363754889178618
Delta: 2.208180371694698e-05 	  Loss: 1.606597094594053 	 Accuracy: 0.3663624511082138
Delta: 0.005964889011759269 	  Loss: 1.6051758679695793 	 Accuracy: 0.363754889178618
Delta: 0.0044685986829290395 	  Loss: 1.6063644178627008 	 Accuracy: 0.363754889178618
Delta: 1.2647433645433746e-05 	  Loss: 1.6063576883407018 	 Accuracy: 0.363754889178618
Delta: 0.002862159605971064 	  Loss: 1.6064023266377856 	 Accuracy: 0.3663624511082138
Delta: 0.00291638228191851 	  Loss: 1.605363311353936 	 Accuracy: 0.3663624511082138
Delta: 0.004621309590042355 	  Loss: 1.6054639869109462 	 Accuracy: 0.3624511082138201
Delta: 0.001218307877877529 	  Loss: 1.6055039246026288 	 Accuracy: 0.36897001303780963
Delta: 0.0013300631880653322 	  Loss: 1.605335545597661 	 Accuracy: 0.3650586701434159
Delta: 0.0011846273462682668 	  Loss: 1.6055605060551006 	 Accuracy: 0.363754889178618
Delta: 0.005208346364612693 	  Loss: 1.6079254472691382 	 Accuracy: 0.3533246414602347
Delta: 0.005642857044715914 	  Loss: 1.6085036203739569 	 Accuracy: 0.3663624511082138
Delta: 0.004014439065687957 	  Loss: 1.6069874165607347 	 Accuracy: 0.3650586701434159
Delta: 0.0005129107633405697 	  Loss: 1.6068849445970896 	 Accuracy: 0.37027379400260757
Delta: 0.002010242476768455 	  Loss: 1.606687280487149 	 Accuracy: 0.363754889178618
Delta: 0.001379804328340846 	  Loss: 1.6068824356559437 	 Accuracy: 0.363754889178618
Delta: 0.00139391730799462 	  Loss: 1.6067775486848164 	 Accuracy: 0.363754889178618
Delta: 0.0006673088393307212 	  Loss: 1.606871274434625 	 Accuracy: 0.3650586701434159
Delta: 0.0021030992752690586 	  Loss: 1.6066586249289119 	 Accuracy: 0.3650586701434159
Delta: 5.539778816548605e-05 	  Loss: 1.6068828336108285 	 Accuracy: 0.363754889178618
Delta: 0.0018226646660981832 	  Loss: 1.6066227840787912 	 Accuracy: 0.3663624511082138
Delta: 0.004142426446692968 	  Loss: 1.6061325631449326 	 Accuracy: 0.35984354628422427
Delta: 0.00329675224713295 	  Loss: 1.6071233174999744 	 Accuracy: 0.363754889178618
Delta: 0.0018232659133592664 	  Loss: 1.6065817599786443 	 Accuracy: 0.3650586701434159
Delta: 0.0005936714905959616 	  Loss: 1.6070100161278922 	 Accuracy: 0.37027379400260757
Delta: 0.004581886604491235 	  Loss: 1.6075292261728256 	 Accuracy: 0.3741851368970013
Delta: 0.006473315204912966 	  Loss: 1.6074035489288714 	 Accuracy: 0.3663624511082138
Delta: 0.003960019197062442 	  Loss: 1.6081328687452445 	 Accuracy: 0.36897001303780963
Delta: 0.001796833640805217 	  Loss: 1.6080273293330656 	 Accuracy: 0.36766623207301175
Delta: 0.004303710877827284 	  Loss: 1.6076806900161027 	 Accuracy: 0.3650586701434159
Delta: 0.001084210734266666 	  Loss: 1.6078408178373973 	 Accuracy: 0.36897001303780963
Delta: 0.0036529576377453115 	  Loss: 1.6082536824212903 	 Accuracy: 0.3820078226857888
Delta: 0.00645644295744552 	  Loss: 1.6067017701856978 	 Accuracy: 0.34159061277705344
Delta: 0.007846810063158188 	  Loss: 1.6118210308595953 	 Accuracy: 0.33376792698826596
Delta: 0.005489505687523579 	  Loss: 1.6148922947889384 	 Accuracy: 0.3559322033898305
Delta: 0.006754564129816992 	  Loss: 1.6083136715062376 	 Accuracy: 0.3663624511082138
Delta: 0.0014223534924471938 	  Loss: 1.6082498522907727 	 Accuracy: 0.3663624511082138
Delta: 0.00488965392962322 	  Loss: 1.6081207552377719 	 Accuracy: 0.35853976531942633
Delta: 0.0016145903022045233 	  Loss: 1.6079996226134776 	 Accuracy: 0.3624511082138201
Delta: 0.0047515419765275305 	  Loss: 1.6059184779102909 	 Accuracy: 0.36766623207301175
Delta: 0.00294938683665006 	  Loss: 1.6068427433957764 	 Accuracy: 0.3663624511082138
Delta: 0.005559227367658258 	  Loss: 1.6067674540159071 	 Accuracy: 0.36766623207301175
Delta: 0.004891830062726738 	  Loss: 1.6057879719900847 	 Accuracy: 0.3663624511082138
Delta: 0.004465438253536603 	  Loss: 1.6053855592796382 	 Accuracy: 0.363754889178618
Delta: 0.00334776367685899 	  Loss: 1.6053012758650143 	 Accuracy: 0.3663624511082138
Delta: 0.020867484686215673 	  Loss: 2.1521959214359683 	 Accuracy: 0.20599739243807041
Delta: 0.019594857601998507 	  Loss: 2.0211754206920944 	 Accuracy: 0.35984354628422427
Delta: 0.01844429840319593 	  Loss: 1.7925804819111966 	 Accuracy: 0.42242503259452413
Delta: 0.01604557167915266 	  Loss: 1.6529211423102441 	 Accuracy: 0.4015645371577575
Delta: 0.012251070336070502 	  Loss: 1.6064356829068016 	 Accuracy: 0.3833116036505867

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009074314158240927 	  Loss: 1.5925098113689622 	 Accuracy: 0.37809647979139505
Delta: 0.006509675315506448 	  Loss: 1.5896815003655838 	 Accuracy: 0.38461538461538464
Delta: 0.003750646270709872 	  Loss: 1.589666528320645 	 Accuracy: 0.38722294654498046
Delta: 0.0027343614627432255 	  Loss: 1.5897934942756442 	 Accuracy: 0.3859191655801825
Delta: 0.0037601414554428855 	  Loss: 1.5899184962767263 	 Accuracy: 0.38852672750977835
Delta: 0.002312050092585992 	  Loss: 1.5897984490321115 	 Accuracy: 0.39113428943937417
Delta: 0.0005466239511834172 	  Loss: 1.589985877437457 	 Accuracy: 0.38722294654498046
Delta: 1.0817433417734518e-05 	  Loss: 1.5899457543001407 	 Accuracy: 0.38852672750977835
Delta: 0.000988337638233617 	  Loss: 1.5898899437189469 	 Accuracy: 0.39895697522816165
Delta: 0.0075613352510252516 	  Loss: 1.5859263319762595 	 Accuracy: 0.39113428943937417
Delta: 0.0037284423951433544 	  Loss: 1.5861730128806175 	 Accuracy: 0.39113428943937417
Delta: 0.0015639877938568593 	  Loss: 1.5858536818130384 	 Accuracy: 0.39113428943937417
Delta: 0.0025059238057647724 	  Loss: 1.5865366695122693 	 Accuracy: 0.38852672750977835
Delta: 0.003511008331675332 	  Loss: 1.5858271483385162 	 Accuracy: 0.39113428943937417
Delta: 0.0005398874053972602 	  Loss: 1.58595318328253 	 Accuracy: 0.39113428943937417
Delta: 0.0016125717695034986 	  Loss: 1.5856023235477297 	 Accuracy: 0.39504563233376794
Delta: 7.679447825733989e-06 	  Loss: 1.5856033969416503 	 Accuracy: 0.39113428943937417
Delta: 0.0032160604685565145 	  Loss: 1.5859186748874614 	 Accuracy: 0.3898305084745763
Delta: 0.000715430962707722 	  Loss: 1.5859122586992864 	 Accuracy: 0.3898305084745763
Delta: 1.2031669409282494e-05 	  Loss: 1.5859221049748478 	 Accuracy: 0.39504563233376794
Delta: 5.304986875565441e-05 	  Loss: 1.5859767396170779 	 Accuracy: 0.39113428943937417
Delta: 0.0009882956014581363 	  Loss: 1.585846666884024 	 Accuracy: 0.39113428943937417
Delta: 0.0034161578967912775 	  Loss: 1.5857088494608997 	 Accuracy: 0.39113428943937417
Delta: 0.002043287661658537 	  Loss: 1.5855306852298474 	 Accuracy: 0.39113428943937417
Delta: 0.001261768372342475 	  Loss: 1.5854022835483073 	 Accuracy: 0.39113428943937417
Delta: 0.0009803247311506778 	  Loss: 1.5855920766391636 	 Accuracy: 0.3898305084745763
Delta: 0.001351833766465859 	  Loss: 1.585635507997795 	 Accuracy: 0.3898305084745763
Delta: 0.003060111126023555 	  Loss: 1.5860887103944126 	 Accuracy: 0.38852672750977835
Delta: 1.9626375424443806e-05 	  Loss: 1.5859622444471815 	 Accuracy: 0.3898305084745763
Delta: 0.0016850890820597816 	  Loss: 1.5862867746445803 	 Accuracy: 0.3898305084745763
Delta: 0.0018568999526312083 	  Loss: 1.5869249732330357 	 Accuracy: 0.3898305084745763
Delta: 0.0007327261897620535 	  Loss: 1.585801610759622 	 Accuracy: 0.3898305084745763
Delta: 0.001805140342779908 	  Loss: 1.5858545342688046 	 Accuracy: 0.3898305084745763
Delta: 0.0001141673015344083 	  Loss: 1.5861859761378991 	 Accuracy: 0.3898305084745763
Delta: 0.0009003931600600342 	  Loss: 1.5862752907624342 	 Accuracy: 0.3898305084745763
Delta: 0.002657996845786532 	  Loss: 1.5860605467273952 	 Accuracy: 0.38722294654498046
Delta: 0.0011612970638626976 	  Loss: 1.586243879925029 	 Accuracy: 0.3898305084745763
Delta: 5.530143491270764e-05 	  Loss: 1.5864073551143205 	 Accuracy: 0.38852672750977835
Delta: 0.0008393114757915658 	  Loss: 1.586122772080067 	 Accuracy: 0.38722294654498046
Delta: 0.0017650518366322692 	  Loss: 1.5866754043014657 	 Accuracy: 0.3898305084745763
Delta: 0.0005912988762646163 	  Loss: 1.586290134993917 	 Accuracy: 0.3898305084745763
Delta: 6.390874114606359e-05 	  Loss: 1.5859051143591936 	 Accuracy: 0.3898305084745763
Delta: 0.0007097108137504382 	  Loss: 1.5860462568453941 	 Accuracy: 0.3898305084745763
Delta: 0.001900008443528867 	  Loss: 1.585463133624864 	 Accuracy: 0.39113428943937417
Delta: 0.0031599072187538605 	  Loss: 1.5866084998454544 	 Accuracy: 0.38852672750977835
Delta: 0.0035431148624434517 	  Loss: 1.5872224401183044 	 Accuracy: 0.38852672750977835
Delta: 4.133558455766981e-05 	  Loss: 1.5869266925845495 	 Accuracy: 0.38722294654498046
Delta: 1.7549553406046816e-05 	  Loss: 1.586861740201819 	 Accuracy: 0.38852672750977835
Delta: 4.3175505174332846e-05 	  Loss: 1.5869614871935833 	 Accuracy: 0.38852672750977835
Delta: 0.002285880152098616 	  Loss: 1.5872180787784893 	 Accuracy: 0.38722294654498046
Delta: 0.003159125468222372 	  Loss: 1.5869817450994492 	 Accuracy: 0.3898305084745763
Delta: 0.0037825464013857557 	  Loss: 1.585866354171742 	 Accuracy: 0.3924380704041721
Delta: 0.0037061334464098747 	  Loss: 1.5849058182410638 	 Accuracy: 0.39374185136897
Delta: 0.0024529298975885603 	  Loss: 1.5846676294646604 	 Accuracy: 0.3924380704041721
Delta: 6.184896138046738e-05 	  Loss: 1.5845780993585545 	 Accuracy: 0.39113428943937417
Delta: 0.0011179852696260905 	  Loss: 1.5846767432171542 	 Accuracy: 0.39113428943937417
Delta: 0.004012384682434715 	  Loss: 1.5848406469727592 	 Accuracy: 0.39504563233376794
Delta: 0.0018165363762694766 	  Loss: 1.584786331506327 	 Accuracy: 0.3924380704041721
Delta: 0.003787655474311207 	  Loss: 1.5835866647935908 	 Accuracy: 0.39374185136897
Delta: 0.003484263368756529 	  Loss: 1.5825800669379073 	 Accuracy: 0.39374185136897
Delta: 0.003515824292037788 	  Loss: 1.583774925028857 	 Accuracy: 0.39504563233376794
Delta: 0.0016344782653175893 	  Loss: 1.5834990423463395 	 Accuracy: 0.39374185136897
Delta: 1.9477472046152645e-05 	  Loss: 1.5835842217092468 	 Accuracy: 0.3924380704041721
Delta: 0.004597845191962796 	  Loss: 1.5827242204080774 	 Accuracy: 0.39374185136897
Delta: 0.004084886984044543 	  Loss: 1.5827158496015996 	 Accuracy: 0.39113428943937417
Delta: 0.0035904332999673024 	  Loss: 1.5838307311445223 	 Accuracy: 0.39374185136897
Delta: 0.002797364662192822 	  Loss: 1.583818232908206 	 Accuracy: 0.39374185136897
Delta: 0.0021904706885193972 	  Loss: 1.583697679401313 	 Accuracy: 0.3924380704041721
Delta: 0.0005595278365137751 	  Loss: 1.583636889046817 	 Accuracy: 0.39374185136897
Delta: 0.0009875915387293232 	  Loss: 1.5836532607183975 	 Accuracy: 0.3924380704041721
Delta: 2.226661525956384e-05 	  Loss: 1.5836906749950797 	 Accuracy: 0.38852672750977835
Delta: 1.2555594820281987e-05 	  Loss: 1.5837841181444774 	 Accuracy: 0.3924380704041721
Delta: 0.0007405324921271028 	  Loss: 1.5836766185551276 	 Accuracy: 0.3898305084745763
Delta: 0.001243622076044564 	  Loss: 1.5836758013315861 	 Accuracy: 0.3924380704041721
Delta: 0.0034434134420239988 	  Loss: 1.5836153786455869 	 Accuracy: 0.39374185136897
Delta: 0.0012396684249987055 	  Loss: 1.5837405791157773 	 Accuracy: 0.39504563233376794
Delta: 0.0024563149307720513 	  Loss: 1.582480722298525 	 Accuracy: 0.39374185136897
Delta: 0.004451690326676915 	  Loss: 1.5843720619430952 	 Accuracy: 0.39504563233376794
Delta: 0.0026968391350072826 	  Loss: 1.5836161188921696 	 Accuracy: 0.39374185136897
Delta: 0.001854784830487599 	  Loss: 1.5835866471758475 	 Accuracy: 0.3963494132985658
Delta: 0.00010010581715231721 	  Loss: 1.5835000013473488 	 Accuracy: 0.39374185136897
Delta: 0.0018134298858898908 	  Loss: 1.5834225061234068 	 Accuracy: 0.39504563233376794
Delta: 0.0014613451104804045 	  Loss: 1.583606438830866 	 Accuracy: 0.39504563233376794
Delta: 0.0024970002258370757 	  Loss: 1.5837974537096355 	 Accuracy: 0.3963494132985658
Delta: 0.0006562911852572827 	  Loss: 1.5834603645286784 	 Accuracy: 0.39504563233376794
Delta: 0.0001301120054099788 	  Loss: 1.5836392670625767 	 Accuracy: 0.38852672750977835
Delta: 0.0045235894356663526 	  Loss: 1.5827316792743547 	 Accuracy: 0.39374185136897
Delta: 0.004044729634108936 	  Loss: 1.582918257381508 	 Accuracy: 0.38852672750977835
Delta: 0.0025555016205549407 	  Loss: 1.5825017900511322 	 Accuracy: 0.39374185136897
Delta: 0.005411018988234371 	  Loss: 1.5820564830908892 	 Accuracy: 0.3924380704041721
Delta: 0.00491588229581298 	  Loss: 1.5825568349983263 	 Accuracy: 0.39765319426336376
Delta: 0.0039190050302875265 	  Loss: 1.5820907104520336 	 Accuracy: 0.39374185136897
Delta: 0.001644965130924378 	  Loss: 1.5814179610601329 	 Accuracy: 0.3924380704041721
Delta: 0.004453165229271604 	  Loss: 1.5831832862662507 	 Accuracy: 0.38461538461538464
Delta: 0.005692141451733246 	  Loss: 1.5847787105617601 	 Accuracy: 0.39113428943937417
Delta: 0.02097844405730894 	  Loss: 2.151527822594572 	 Accuracy: 0.20860495436766624
Delta: 0.0195153338756937 	  Loss: 2.024495487700363 	 Accuracy: 0.28552803129074317
Delta: 0.018541713490072595 	  Loss: 1.7857892919899996 	 Accuracy: 0.3285528031290743
Delta: 0.015433974307266427 	  Loss: 1.643722857724692 	 Accuracy: 0.31029986962190353
Delta: 0.010423329101988146 	  Loss: 1.61716358532529 	 Accuracy: 0.31029986962190353

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008102330607373748 	  Loss: 1.6127365956626825 	 Accuracy: 0.3155149934810952
Delta: 0.006276802226016028 	  Loss: 1.6117445610505365 	 Accuracy: 0.3194263363754889
Delta: 0.006084375659386 	  Loss: 1.6110037905120225 	 Accuracy: 0.31681877444589307
Delta: 0.004641731370649131 	  Loss: 1.6113111291338342 	 Accuracy: 0.31681877444589307
Delta: 0.0029647516287317466 	  Loss: 1.6110608321148827 	 Accuracy: 0.3194263363754889
Delta: 0.0015167084827667188 	  Loss: 1.611017780023716 	 Accuracy: 0.3194263363754889
Delta: 0.0015285325144411216 	  Loss: 1.6108885603279641 	 Accuracy: 0.3194263363754889
Delta: 0.00425711233166899 	  Loss: 1.611127761336054 	 Accuracy: 0.3194263363754889
Delta: 0.0033984669026160966 	  Loss: 1.6118352492640806 	 Accuracy: 0.3220338983050847
Delta: 0.0011562670146390943 	  Loss: 1.611871871300401 	 Accuracy: 0.3220338983050847
Delta: 2.941115099418249e-05 	  Loss: 1.6119202863325897 	 Accuracy: 0.3194263363754889
Delta: 3.545379316541897e-05 	  Loss: 1.6119350733669686 	 Accuracy: 0.32073011734028684
Delta: 8.686010406099488e-06 	  Loss: 1.6119155099958702 	 Accuracy: 0.3220338983050847
Delta: 1.6945463246009164e-05 	  Loss: 1.6119198299449575 	 Accuracy: 0.3194263363754889
Delta: 3.861375646893693e-06 	  Loss: 1.6119106938529968 	 Accuracy: 0.3220338983050847
Delta: 0.0008273904970626812 	  Loss: 1.6118497469354385 	 Accuracy: 0.31290743155149936
Delta: 0.0054494443093678294 	  Loss: 1.6119318846996675 	 Accuracy: 0.318122555410691
Delta: 0.003939083173109056 	  Loss: 1.6124968952166538 	 Accuracy: 0.32073011734028684
Delta: 0.002718733254051002 	  Loss: 1.6124293558866647 	 Accuracy: 0.318122555410691
Delta: 0.0005236211380734769 	  Loss: 1.6124381860734234 	 Accuracy: 0.3194263363754889
Delta: 0.0019073587396240702 	  Loss: 1.6124989606843387 	 Accuracy: 0.3194263363754889
Delta: 0.0006460942004637252 	  Loss: 1.6125014140520522 	 Accuracy: 0.3194263363754889
Delta: 1.76118654177366e-05 	  Loss: 1.6124821274344583 	 Accuracy: 0.3194263363754889
Delta: 0.0009395382342768105 	  Loss: 1.612514000590926 	 Accuracy: 0.3155149934810952
Delta: 1.08542681289425e-05 	  Loss: 1.6125162959255988 	 Accuracy: 0.3155149934810952
Delta: 1.2738940286116503e-05 	  Loss: 1.6125177864055624 	 Accuracy: 0.318122555410691
Delta: 0.0009861330260219638 	  Loss: 1.6123903722487871 	 Accuracy: 0.3194263363754889
Delta: 4.0477340779181314e-05 	  Loss: 1.6125404342307914 	 Accuracy: 0.31421121251629724
Delta: 0.0005476672535306435 	  Loss: 1.6127289049911024 	 Accuracy: 0.3194263363754889
Delta: 6.584769141513873e-06 	  Loss: 1.6127195775632335 	 Accuracy: 0.3194263363754889
Delta: 6.24483833319932e-05 	  Loss: 1.612511751550111 	 Accuracy: 0.318122555410691
Delta: 0.0009476731244716219 	  Loss: 1.6127677685516884 	 Accuracy: 0.318122555410691
Delta: 0.0014526676900009148 	  Loss: 1.612870395810104 	 Accuracy: 0.3194263363754889
Delta: 0.0012588386374719745 	  Loss: 1.612504786495677 	 Accuracy: 0.3220338983050847
Delta: 0.00507618319680864 	  Loss: 1.6117705659837636 	 Accuracy: 0.32073011734028684
Delta: 0.004343178616820777 	  Loss: 1.6116164402315263 	 Accuracy: 0.32333767926988266
Delta: 0.0018674985508304143 	  Loss: 1.6116306431175853 	 Accuracy: 0.318122555410691
Delta: 0.0031370877383863384 	  Loss: 1.6121302178874406 	 Accuracy: 0.318122555410691
Delta: 0.003776700383255081 	  Loss: 1.6123738682558397 	 Accuracy: 0.318122555410691
Delta: 0.003927416910836793 	  Loss: 1.612154367207066 	 Accuracy: 0.3194263363754889
Delta: 0.0022600468167441714 	  Loss: 1.6119317893008538 	 Accuracy: 0.318122555410691
Delta: 0.0013747267052463725 	  Loss: 1.6116601697908925 	 Accuracy: 0.32073011734028684
Delta: 0.0034121305045056766 	  Loss: 1.6117371701043877 	 Accuracy: 0.318122555410691
Delta: 0.002243390582119672 	  Loss: 1.6118905115506776 	 Accuracy: 0.318122555410691
Delta: 7.371147115809233e-06 	  Loss: 1.611904630242352 	 Accuracy: 0.3194263363754889
Delta: 1.3307727277965724e-05 	  Loss: 1.611943701096668 	 Accuracy: 0.3155149934810952
Delta: 0.0022336433434098873 	  Loss: 1.6120651124397023 	 Accuracy: 0.318122555410691
Delta: 0.0008048128165363189 	  Loss: 1.6117490881336503 	 Accuracy: 0.318122555410691
Delta: 5.337030170566987e-05 	  Loss: 1.6116977467767435 	 Accuracy: 0.318122555410691
Delta: 0.0027020049078359037 	  Loss: 1.611650219217403 	 Accuracy: 0.3194263363754889
Delta: 0.0037700872227583453 	  Loss: 1.6102783701640722 	 Accuracy: 0.31421121251629724
Delta: 0.003714883352804449 	  Loss: 1.610481081550974 	 Accuracy: 0.3155149934810952
Delta: 0.0028916037512164887 	  Loss: 1.6092400757034335 	 Accuracy: 0.3155149934810952
Delta: 0.0031592773108611127 	  Loss: 1.6098273013824516 	 Accuracy: 0.31029986962190353
Delta: 0.0018272598158759433 	  Loss: 1.6104520805740075 	 Accuracy: 0.31421121251629724
Delta: 0.0031942137208250676 	  Loss: 1.611218265015057 	 Accuracy: 0.31421121251629724
Delta: 0.003418800511252616 	  Loss: 1.6099890214989525 	 Accuracy: 0.3155149934810952
Delta: 0.0017059704589046682 	  Loss: 1.609590966491103 	 Accuracy: 0.31290743155149936
Delta: 0.001502039097210217 	  Loss: 1.6103444967990086 	 Accuracy: 0.31290743155149936
Delta: 0.0023923876290744646 	  Loss: 1.6100899873116088 	 Accuracy: 0.31681877444589307
Delta: 0.004026757809256033 	  Loss: 1.6097261485108576 	 Accuracy: 0.3155149934810952
Delta: 0.0013960548338355007 	  Loss: 1.6097409293809224 	 Accuracy: 0.3155149934810952
Delta: 2.6663879237128385e-05 	  Loss: 1.609727725161131 	 Accuracy: 0.3155149934810952
Delta: 0.002735631203046378 	  Loss: 1.6097691430894097 	 Accuracy: 0.31421121251629724
Delta: 0.0024250891224743363 	  Loss: 1.6097415854538935 	 Accuracy: 0.3155149934810952
Delta: 0.00332216098113043 	  Loss: 1.608834545473315 	 Accuracy: 0.31421121251629724
Delta: 0.0006214872779903655 	  Loss: 1.6088606314760578 	 Accuracy: 0.31421121251629724
Delta: 0.0050347264922479505 	  Loss: 1.6090287883842 	 Accuracy: 0.3116036505867014
Delta: 0.004345489244207593 	  Loss: 1.609474858762355 	 Accuracy: 0.3116036505867014
Delta: 3.530760248107477e-05 	  Loss: 1.6094790632471794 	 Accuracy: 0.31029986962190353
Delta: 0.0036829532389905124 	  Loss: 1.6096557156318463 	 Accuracy: 0.31290743155149936
Delta: 0.0035877293225394092 	  Loss: 1.608917767335984 	 Accuracy: 0.30638852672750977
Delta: 0.0045091034432981 	  Loss: 1.6090520778324917 	 Accuracy: 0.31029986962190353
Delta: 0.003950228193068188 	  Loss: 1.608495526953123 	 Accuracy: 0.3089960886571056
Delta: 0.004320849014924679 	  Loss: 1.608060107020716 	 Accuracy: 0.3089960886571056
Delta: 0.003233566022932911 	  Loss: 1.6093471482195727 	 Accuracy: 0.3089960886571056
Delta: 0.005154116930087441 	  Loss: 1.608976701920517 	 Accuracy: 0.3089960886571056
Delta: 0.0011066006743418542 	  Loss: 1.609152109451458 	 Accuracy: 0.3076923076923077
Delta: 0.003710302671340805 	  Loss: 1.6094015908871395 	 Accuracy: 0.29726205997392435
Delta: 0.005116888102716354 	  Loss: 1.609881732862162 	 Accuracy: 0.30638852672750977
Delta: 0.005675922491290057 	  Loss: 1.6089155118419198 	 Accuracy: 0.3089960886571056
Delta: 0.00475599033126088 	  Loss: 1.6084211694529804 	 Accuracy: 0.3011734028683181
Delta: 0.003904760840789793 	  Loss: 1.6087390153210444 	 Accuracy: 0.29986962190352023
Delta: 0.004013667865717009 	  Loss: 1.6099916685022144 	 Accuracy: 0.30638852672750977
Delta: 0.003788017282077608 	  Loss: 1.6097446153199053 	 Accuracy: 0.31029986962190353
Delta: 0.004713644883199614 	  Loss: 1.6075027173623084 	 Accuracy: 0.3076923076923077
Delta: 0.002188963693379062 	  Loss: 1.6086646289878668 	 Accuracy: 0.3076923076923077
Delta: 0.0015853299183685493 	  Loss: 1.6081521611148943 	 Accuracy: 0.30247718383311606
Delta: 0.0037281615249253382 	  Loss: 1.6086966724662108 	 Accuracy: 0.3076923076923077
Delta: 0.003072322062887651 	  Loss: 1.6082336109712885 	 Accuracy: 0.3076923076923077
Delta: 0.000541420045174446 	  Loss: 1.608071980151446 	 Accuracy: 0.30638852672750977
Delta: 0.005733460887677422 	  Loss: 1.6096731061127938 	 Accuracy: 0.30247718383311606
Delta: 0.006128256825282325 	  Loss: 1.6105078108416746 	 Accuracy: 0.29726205997392435
Delta: 0.006885877770171328 	  Loss: 1.6126705958225893 	 Accuracy: 0.30638852672750977
Delta: 0.005186453120950086 	  Loss: 1.6099359834653406 	 Accuracy: 0.30638852672750977
Delta: 0.02096709261089508 	  Loss: 2.1517191217412566 	 Accuracy: 0.2046936114732725
Delta: 0.019647475474455008 	  Loss: 2.015413333007877 	 Accuracy: 0.34419817470664926
Delta: 0.01840910490998256 	  Loss: 1.7821534372205612 	 Accuracy: 0.42894393741851367
Delta: 0.016214648762737566 	  Loss: 1.6367524516201999 	 Accuracy: 0.43546284224250326
Delta: 0.011591334129401068 	  Loss: 1.5988964814317652 	 Accuracy: 0.4302477183833116

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008288670130938149 	  Loss: 1.5885670985137597 	 Accuracy: 0.4302477183833116
Delta: 0.006027913541800172 	  Loss: 1.58672871703534 	 Accuracy: 0.4315514993481095
Delta: 0.0035666463501984845 	  Loss: 1.586726336704568 	 Accuracy: 0.42503259452411996
Delta: 0.003839370465855041 	  Loss: 1.5872210753101563 	 Accuracy: 0.42633637548891784
Delta: 0.0028369264395528082 	  Loss: 1.587079169416464 	 Accuracy: 0.42503259452411996
Delta: 0.003077656792195669 	  Loss: 1.5873326999489494 	 Accuracy: 0.42503259452411996
Delta: 0.0007079551281257347 	  Loss: 1.5873157505661357 	 Accuracy: 0.42633637548891784
Delta: 7.592980495655791e-05 	  Loss: 1.587242597344785 	 Accuracy: 0.423728813559322
Delta: 0.00210377264986588 	  Loss: 1.5873640393150568 	 Accuracy: 0.4276401564537158
Delta: 0.0005397243853439217 	  Loss: 1.5870205274138336 	 Accuracy: 0.4276401564537158
Delta: 1.069709990715984e-05 	  Loss: 1.5870751416202062 	 Accuracy: 0.42633637548891784
Delta: 4.451911446753159e-05 	  Loss: 1.5871750890905651 	 Accuracy: 0.42894393741851367
Delta: 1.44919985322261e-05 	  Loss: 1.5871895482711564 	 Accuracy: 0.4276401564537158
Delta: 0.0027645201530553613 	  Loss: 1.5868572522472728 	 Accuracy: 0.4276401564537158
Delta: 0.0007647655115699226 	  Loss: 1.587110889765507 	 Accuracy: 0.4211212516297262
Delta: 0.003756677842169572 	  Loss: 1.5873545279906685 	 Accuracy: 0.42633637548891784
Delta: 0.0016327337467690484 	  Loss: 1.5872824506434569 	 Accuracy: 0.4276401564537158
Delta: 0.002867551099618653 	  Loss: 1.586749290006774 	 Accuracy: 0.4276401564537158
Delta: 0.0018367409471071949 	  Loss: 1.5869477678274633 	 Accuracy: 0.42894393741851367
Delta: 0.0015313894889788394 	  Loss: 1.5868040691318097 	 Accuracy: 0.4276401564537158
Delta: 0.0006333827482287884 	  Loss: 1.5866485784312558 	 Accuracy: 0.42894393741851367
Delta: 0.0025243904410875346 	  Loss: 1.5868736492454416 	 Accuracy: 0.42894393741851367
Delta: 0.0011712423646568402 	  Loss: 1.5866924224778978 	 Accuracy: 0.42633637548891784
Delta: 0.0033319501077947893 	  Loss: 1.5869874711960228 	 Accuracy: 0.4276401564537158
Delta: 3.145600058777188e-05 	  Loss: 1.587000366946508 	 Accuracy: 0.4315514993481095
Delta: 0.003348060158136965 	  Loss: 1.5873613117859633 	 Accuracy: 0.4276401564537158
Delta: 0.0008108424936215098 	  Loss: 1.5874028436437693 	 Accuracy: 0.4276401564537158
Delta: 0.0004918731166570715 	  Loss: 1.587395161377951 	 Accuracy: 0.4276401564537158
Delta: 0.0037512105428401804 	  Loss: 1.5887397444082825 	 Accuracy: 0.42503259452411996
Delta: 0.002272600920595328 	  Loss: 1.5887544883010813 	 Accuracy: 0.42894393741851367
Delta: 0.001861802163822196 	  Loss: 1.5885722838230056 	 Accuracy: 0.42894393741851367
Delta: 0.001265124588841233 	  Loss: 1.5883143667502553 	 Accuracy: 0.42894393741851367
Delta: 2.5955819452757374e-05 	  Loss: 1.5884100574869104 	 Accuracy: 0.42633637548891784
Delta: 0.0001117787145975795 	  Loss: 1.5886099096753938 	 Accuracy: 0.42894393741851367
Delta: 3.302233932288617e-05 	  Loss: 1.5885434084687755 	 Accuracy: 0.4276401564537158
Delta: 0.005662482496378737 	  Loss: 1.5886094133585011 	 Accuracy: 0.42894393741851367
Delta: 0.003479349756688342 	  Loss: 1.5893018305594835 	 Accuracy: 0.4276401564537158
Delta: 0.004764877879584063 	  Loss: 1.589704316200607 	 Accuracy: 0.4302477183833116
Delta: 0.0030234365829733215 	  Loss: 1.5890122264124735 	 Accuracy: 0.43415906127770537
Delta: 0.0041145024284170335 	  Loss: 1.587740075007638 	 Accuracy: 0.43285528031290743
Delta: 0.002191175095909228 	  Loss: 1.5879721989956823 	 Accuracy: 0.43285528031290743
Delta: 0.0010504224393717092 	  Loss: 1.5880657426076537 	 Accuracy: 0.43415906127770537
Delta: 0.0008497000017835046 	  Loss: 1.5878827322011915 	 Accuracy: 0.4315514993481095
Delta: 0.0006282315435780391 	  Loss: 1.5879361261132905 	 Accuracy: 0.43285528031290743
Delta: 2.876550673351255e-05 	  Loss: 1.5879463426067686 	 Accuracy: 0.43285528031290743
Delta: 0.0032306423194702976 	  Loss: 1.5878752295769591 	 Accuracy: 0.43285528031290743
Delta: 0.0035012631511270142 	  Loss: 1.5870763951289553 	 Accuracy: 0.43415906127770537
Delta: 0.0025118174979617963 	  Loss: 1.587227955519111 	 Accuracy: 0.43415906127770537
Delta: 0.0026979786486659263 	  Loss: 1.587283745490104 	 Accuracy: 0.43415906127770537
Delta: 0.0009311104465829657 	  Loss: 1.5873193988774812 	 Accuracy: 0.42894393741851367
Delta: 0.002511549034668553 	  Loss: 1.5875068661573293 	 Accuracy: 0.43415906127770537
Delta: 0.0035115466204120645 	  Loss: 1.587252396412096 	 Accuracy: 0.43415906127770537
Delta: 0.0030801476755663894 	  Loss: 1.5873675589220242 	 Accuracy: 0.43285528031290743
Delta: 0.0005187114791722439 	  Loss: 1.5874488469631425 	 Accuracy: 0.43285528031290743
Delta: 0.0019034489339447211 	  Loss: 1.5872978435163687 	 Accuracy: 0.43415906127770537
Delta: 0.0034773065259136515 	  Loss: 1.5867133521064019 	 Accuracy: 0.43285528031290743
Delta: 0.0032760362433882596 	  Loss: 1.5866288215834983 	 Accuracy: 0.4315514993481095
Delta: 0.0005501636744028905 	  Loss: 1.5866672424918598 	 Accuracy: 0.43285528031290743
Delta: 0.0005344957914364997 	  Loss: 1.5865951865281085 	 Accuracy: 0.43285528031290743
Delta: 5.881095834682058e-07 	  Loss: 1.5865953027705122 	 Accuracy: 0.43285528031290743
Delta: 3.019824018572845e-09 	  Loss: 1.5865952937407188 	 Accuracy: 0.43415906127770537
converged at iter  65
Delta: 0.020963513302869264 	  Loss: 2.151556066120905 	 Accuracy: 0.20208604954367665
Delta: 0.019617308687514014 	  Loss: 2.0128831034727415 	 Accuracy: 0.31290743155149936
Delta: 0.018596685636154443 	  Loss: 1.7857439078292998 	 Accuracy: 0.4172099087353325
Delta: 0.016999689727401193 	  Loss: 1.6379278983223737 	 Accuracy: 0.3963494132985658
Delta: 0.011508142390815513 	  Loss: 1.601215170817959 	 Accuracy: 0.3754889178617992

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008044641725523391 	  Loss: 1.5944013073741283 	 Accuracy: 0.37027379400260757
Delta: 0.00593607238263386 	  Loss: 1.593522254628024 	 Accuracy: 0.36897001303780963
Delta: 0.004778820031283634 	  Loss: 1.5930771599713804 	 Accuracy: 0.3663624511082138
Delta: 0.003962874529817798 	  Loss: 1.5937405969936482 	 Accuracy: 0.3663624511082138
Delta: 0.0015432957057322015 	  Loss: 1.5934776329049658 	 Accuracy: 0.3663624511082138
Delta: 0.0030138181231482717 	  Loss: 1.593834611279899 	 Accuracy: 0.3663624511082138
Delta: 0.0013010625523599887 	  Loss: 1.5939742772896992 	 Accuracy: 0.3663624511082138
Delta: 0.0035472721017617876 	  Loss: 1.5946778265239958 	 Accuracy: 0.3650586701434159
Delta: 0.0015986109664698808 	  Loss: 1.5943731192141626 	 Accuracy: 0.3663624511082138
Delta: 1.832114353560784e-06 	  Loss: 1.594374559776304 	 Accuracy: 0.36766623207301175
Delta: 0.0011176508007753883 	  Loss: 1.5940896568807303 	 Accuracy: 0.3650586701434159
Delta: 0.004260488798290886 	  Loss: 1.5945344914396287 	 Accuracy: 0.3650586701434159
Delta: 0.0018784470593257137 	  Loss: 1.594622429986186 	 Accuracy: 0.3663624511082138
Delta: 6.403432925295976e-06 	  Loss: 1.5946299576230676 	 Accuracy: 0.3663624511082138
Delta: 1.1432694123675809e-06 	  Loss: 1.5946266059836496 	 Accuracy: 0.3663624511082138
Delta: 0.002613834562144949 	  Loss: 1.5944737950227026 	 Accuracy: 0.3663624511082138
Delta: 0.0009854317571237267 	  Loss: 1.5944858059625218 	 Accuracy: 0.3663624511082138
Delta: 0.0010981658277169882 	  Loss: 1.5946621534172691 	 Accuracy: 0.3663624511082138
Delta: 0.0009902020085026297 	  Loss: 1.594620640198264 	 Accuracy: 0.3663624511082138
Delta: 0.000996611870690759 	  Loss: 1.594430153654416 	 Accuracy: 0.3663624511082138
Delta: 0.0005078649532849954 	  Loss: 1.5943294166665907 	 Accuracy: 0.3663624511082138
Delta: 0.0019234034674798432 	  Loss: 1.5946421507662607 	 Accuracy: 0.3663624511082138
Delta: 0.000543580969110755 	  Loss: 1.5944028474881864 	 Accuracy: 0.3728813559322034
Delta: 0.0007429099535082627 	  Loss: 1.5945311669719489 	 Accuracy: 0.3663624511082138
Delta: 0.0011832063247094909 	  Loss: 1.594634523415913 	 Accuracy: 0.3663624511082138
Delta: 0.0010973842818827355 	  Loss: 1.5945982456582997 	 Accuracy: 0.3663624511082138
Delta: 0.0004950331033317833 	  Loss: 1.594589664945425 	 Accuracy: 0.3663624511082138
Delta: 6.535012859573221e-05 	  Loss: 1.594524933859363 	 Accuracy: 0.36766623207301175
Delta: 0.0006373284585961338 	  Loss: 1.5945927144001582 	 Accuracy: 0.3663624511082138
Delta: 0.0005568859598084066 	  Loss: 1.5944046420733724 	 Accuracy: 0.3663624511082138
Delta: 0.0007367901548767018 	  Loss: 1.594688268431184 	 Accuracy: 0.3663624511082138
Delta: 0.0005151709424560206 	  Loss: 1.5944835592389273 	 Accuracy: 0.3663624511082138
Delta: 0.0012104562924881996 	  Loss: 1.5945494013753663 	 Accuracy: 0.36897001303780963
Delta: 0.0018542507131047844 	  Loss: 1.594304765660162 	 Accuracy: 0.3663624511082138
Delta: 0.0016897907510554438 	  Loss: 1.594328693352328 	 Accuracy: 0.3663624511082138
Delta: 0.0035950760436306824 	  Loss: 1.5949413130764725 	 Accuracy: 0.3663624511082138
Delta: 0.0018506671491720329 	  Loss: 1.5942229746608998 	 Accuracy: 0.36114732724902215
Delta: 0.0017448858802519456 	  Loss: 1.5950360328093394 	 Accuracy: 0.3559322033898305
Delta: 0.0023635898985948835 	  Loss: 1.5959794733869905 	 Accuracy: 0.3663624511082138
Delta: 0.0023624389893813456 	  Loss: 1.5950986050391438 	 Accuracy: 0.3624511082138201
Delta: 0.0032848290916447334 	  Loss: 1.5942913445049083 	 Accuracy: 0.363754889178618
Delta: 0.0005086238986230132 	  Loss: 1.5942954948743382 	 Accuracy: 0.363754889178618
Delta: 0.004898556500400549 	  Loss: 1.5948403186089015 	 Accuracy: 0.36766623207301175
Delta: 0.0035111767088592148 	  Loss: 1.5942908349263303 	 Accuracy: 0.3728813559322034
Delta: 0.0030053440276463276 	  Loss: 1.5937509869900501 	 Accuracy: 0.36897001303780963
Delta: 0.0021798938887901604 	  Loss: 1.5938589775603809 	 Accuracy: 0.30247718383311606
Delta: 0.003147938213270814 	  Loss: 1.594203626351354 	 Accuracy: 0.36766623207301175
Delta: 0.002476514617258624 	  Loss: 1.5938994074507424 	 Accuracy: 0.3650586701434159
Delta: 0.002553281259907732 	  Loss: 1.5938568290126152 	 Accuracy: 0.36766623207301175
Delta: 0.0018043615627217548 	  Loss: 1.59343868655019 	 Accuracy: 0.3663624511082138
Delta: 0.0021192955914051377 	  Loss: 1.5936010905487095 	 Accuracy: 0.3650586701434159
Delta: 0.0031797807883695 	  Loss: 1.5943455286510653 	 Accuracy: 0.36766623207301175
Delta: 0.0013196935549689701 	  Loss: 1.5942503213169426 	 Accuracy: 0.3663624511082138
Delta: 0.0018593752888845915 	  Loss: 1.5942419268182895 	 Accuracy: 0.37027379400260757
Delta: 0.0044745512946749565 	  Loss: 1.5936284104799472 	 Accuracy: 0.3650586701434159
Delta: 0.004298490487660935 	  Loss: 1.5939008719497514 	 Accuracy: 0.36766623207301175
Delta: 0.0018574595026070461 	  Loss: 1.5937819758073395 	 Accuracy: 0.3663624511082138
Delta: 0.0033695435886887054 	  Loss: 1.5931595243335446 	 Accuracy: 0.36766623207301175
Delta: 0.003279099774712992 	  Loss: 1.5931016812930832 	 Accuracy: 0.36897001303780963
Delta: 0.0015610426346444055 	  Loss: 1.5931241937807155 	 Accuracy: 0.37027379400260757
Delta: 0.004141501982866402 	  Loss: 1.5931999303666227 	 Accuracy: 0.3650586701434159
Delta: 0.0019297281430319057 	  Loss: 1.5931009773941396 	 Accuracy: 0.3663624511082138
Delta: 0.0011722733463095866 	  Loss: 1.5929662114765342 	 Accuracy: 0.36766623207301175
Delta: 8.211866020802521e-06 	  Loss: 1.5929342942066034 	 Accuracy: 0.3663624511082138
Delta: 3.9883585214590625e-05 	  Loss: 1.5930063040911935 	 Accuracy: 0.36766623207301175
Delta: 3.9883593047765035e-05 	  Loss: 1.59293425573791 	 Accuracy: 0.36766623207301175
Delta: 0.0008679909308752103 	  Loss: 1.592887862334456 	 Accuracy: 0.36766623207301175
Delta: 0.0008679911461876898 	  Loss: 1.5929342916288314 	 Accuracy: 0.36766623207301175
Delta: 8.053521222554139e-07 	  Loss: 1.5929318929790512 	 Accuracy: 0.36766623207301175
Delta: 0.0015492689635170321 	  Loss: 1.592593056082761 	 Accuracy: 0.36766623207301175
Delta: 0.0012609715363000745 	  Loss: 1.5928371983292136 	 Accuracy: 0.36766623207301175
Delta: 4.751890468765758e-05 	  Loss: 1.5929324798495514 	 Accuracy: 0.36766623207301175
Delta: 2.2953231701492127e-06 	  Loss: 1.592934324953801 	 Accuracy: 0.36114732724902215
Delta: 0.0016549076611866473 	  Loss: 1.5931557159771863 	 Accuracy: 0.363754889178618
Delta: 0.0005652510248695267 	  Loss: 1.592960473539235 	 Accuracy: 0.36766623207301175
Delta: 2.4538208116074027e-05 	  Loss: 1.5929337655653113 	 Accuracy: 0.36766623207301175
Delta: 6.716849815865928e-11 	  Loss: 1.5929337657067026 	 Accuracy: 0.36766623207301175
converged at iter  81
Delta: 0.020897488970513127 	  Loss: 2.157915252481497 	 Accuracy: 0.196870925684485
Delta: 0.018216353514319262 	  Loss: 2.088531184215081 	 Accuracy: 0.21773142112125163
Delta: 0.016488627340975927 	  Loss: 1.9931036719210329 	 Accuracy: 0.2242503259452412
Delta: 0.014283218629271026 	  Loss: 1.9094079000738455 	 Accuracy: 0.2633637548891786
Delta: 0.013380670588553134 	  Loss: 1.8434244071314343 	 Accuracy: 0.26597131681877445
Delta: 0.013316493706063979 	  Loss: 1.779501711791934 	 Accuracy: 0.23859191655801826
Delta: 0.011653695601215975 	  Loss: 1.7196198271210812 	 Accuracy: 0.19426336375488917
Delta: 0.00986226159652011 	  Loss: 1.6750559480559715 	 Accuracy: 0.16166883963494133
Delta: 0.008840636458861156 	  Loss: 1.644040785566475 	 Accuracy: 0.12516297262059975
Delta: 0.0077993917966662375 	  Loss: 1.6225072303385315 	 Accuracy: 0.11603650586701435
Delta: 0.007179971523732052 	  Loss: 1.6072601207386916 	 Accuracy: 0.10951760104302477
Delta: 0.006639776245600164 	  Loss: 1.5959282789791087 	 Accuracy: 0.10951760104302477
Delta: 0.00608472569943201 	  Loss: 1.5880445215767147 	 Accuracy: 0.10951760104302477
Delta: 0.006116839767323211 	  Loss: 1.5810954913529076 	 Accuracy: 0.10821382007822686
Delta: 0.005029455722831469 	  Loss: 1.5752370806965266 	 Accuracy: 0.10691003911342895
Delta: 0.004929943871031754 	  Loss: 1.5709835640993692 	 Accuracy: 0.10560625814863103
Delta: 0.004387917933733922 	  Loss: 1.5679974824982628 	 Accuracy: 0.10560625814863103
Delta: 0.0045750392995340125 	  Loss: 1.5651732852264864 	 Accuracy: 0.10560625814863103
Delta: 0.0038813456569205948 	  Loss: 1.5633111463610467 	 Accuracy: 0.10560625814863103
Delta: 0.003150218288501733 	  Loss: 1.5616227386099353 	 Accuracy: 0.10821382007822686
Delta: 0.004988617122795107 	  Loss: 1.560097949728902 	 Accuracy: 0.10560625814863103
Delta: 0.0038515338924955756 	  Loss: 1.5587861596115724 	 Accuracy: 0.10821382007822686
Delta: 0.0027169493173306585 	  Loss: 1.5576211364118464 	 Accuracy: 0.10560625814863103
Delta: 0.0035718886766083987 	  Loss: 1.5566609134061624 	 Accuracy: 0.10951760104302477
Delta: 0.002791215824727046 	  Loss: 1.5560812528467824 	 Accuracy: 0.10560625814863103
Delta: 0.004486165089963119 	  Loss: 1.5553493680328683 	 Accuracy: 0.10691003911342895
Delta: 0.0025252262323962518 	  Loss: 1.5546558792388447 	 Accuracy: 0.10430247718383312
Delta: 0.0037152605687098003 	  Loss: 1.5540770021289765 	 Accuracy: 0.10691003911342895
Delta: 0.002892707097045922 	  Loss: 1.5536486672523333 	 Accuracy: 0.10691003911342895
Delta: 0.0036528227863553858 	  Loss: 1.5532625417786887 	 Accuracy: 0.10430247718383312
Delta: 0.0017263057372633695 	  Loss: 1.552948296403251 	 Accuracy: 0.10821382007822686
Delta: 0.004230163953838822 	  Loss: 1.5525422211104345 	 Accuracy: 0.10299869621903521
Delta: 0.003877320034269654 	  Loss: 1.5521809296852145 	 Accuracy: 0.10299869621903521
Delta: 0.003952955766952684 	  Loss: 1.5516265210439157 	 Accuracy: 0.10299869621903521
Delta: 0.0027506427054586565 	  Loss: 1.5513802022986316 	 Accuracy: 0.10299869621903521
Delta: 0.0019296456475985369 	  Loss: 1.5513121447055203 	 Accuracy: 0.10299869621903521
Delta: 0.002956568872249514 	  Loss: 1.5510838097413577 	 Accuracy: 0.10299869621903521
Delta: 0.0033509259923310683 	  Loss: 1.5507651510804141 	 Accuracy: 0.10299869621903521
Delta: 0.0028904366696892174 	  Loss: 1.5505216274885658 	 Accuracy: 0.10560625814863103
Delta: 0.0016466858053361445 	  Loss: 1.5504146130780634 	 Accuracy: 0.10299869621903521
Delta: 0.0033231654859158 	  Loss: 1.5502394834514868 	 Accuracy: 0.10299869621903521
Delta: 0.003745440926106475 	  Loss: 1.5501074028862982 	 Accuracy: 0.10691003911342895
Delta: 0.002463248638648671 	  Loss: 1.5499895966173425 	 Accuracy: 0.10299869621903521
Delta: 0.0019625891937125267 	  Loss: 1.5499595719173076 	 Accuracy: 0.10299869621903521
Delta: 0.0009731296867848331 	  Loss: 1.5498131667740458 	 Accuracy: 0.10299869621903521
Delta: 0.003612072941677347 	  Loss: 1.549693927298984 	 Accuracy: 0.10299869621903521
Delta: 0.0034915602586847736 	  Loss: 1.5496142848965633 	 Accuracy: 0.10560625814863103

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0017914431371666743 	  Loss: 1.5496048181484157 	 Accuracy: 0.10299869621903521
Delta: 0.0021804775667587334 	  Loss: 1.5494767320222207 	 Accuracy: 0.10299869621903521
Delta: 0.0013706234934644968 	  Loss: 1.5493614237886615 	 Accuracy: 0.10299869621903521
Delta: 0.0011895696807056886 	  Loss: 1.5492911270813798 	 Accuracy: 0.10299869621903521
Delta: 0.0028648125083899642 	  Loss: 1.5491583736552523 	 Accuracy: 0.10430247718383312
Delta: 0.0022668388795952475 	  Loss: 1.5491258586231718 	 Accuracy: 0.1016949152542373
Delta: 0.0008940294268395856 	  Loss: 1.5490543691040715 	 Accuracy: 0.10430247718383312
Delta: 0.0008173097005882921 	  Loss: 1.549019434810226 	 Accuracy: 0.10430247718383312
Delta: 0.001898239800983295 	  Loss: 1.5489729248482949 	 Accuracy: 0.10299869621903521
Delta: 0.001447016771509813 	  Loss: 1.5489171734819176 	 Accuracy: 0.10560625814863103
Delta: 0.0031382722509772374 	  Loss: 1.5489376742363095 	 Accuracy: 0.10299869621903521
Delta: 0.0018730039570040104 	  Loss: 1.5488775271848878 	 Accuracy: 0.10299869621903521
Delta: 0.0018996594515013183 	  Loss: 1.5488223898702658 	 Accuracy: 0.10299869621903521
Delta: 0.0017626642719487627 	  Loss: 1.548757844244105 	 Accuracy: 0.10299869621903521
Delta: 0.0026484022492825757 	  Loss: 1.5486954263314048 	 Accuracy: 0.10299869621903521
Delta: 0.002364601422487747 	  Loss: 1.5487176303239618 	 Accuracy: 0.10299869621903521
Delta: 0.0008157343554386362 	  Loss: 1.5486716281098352 	 Accuracy: 0.10299869621903521
Delta: 0.0017229904120505196 	  Loss: 1.5485702608912608 	 Accuracy: 0.10299869621903521
Delta: 0.001031906677750215 	  Loss: 1.5485292661255112 	 Accuracy: 0.10299869621903521
Delta: 2.917333250790595e-05 	  Loss: 1.5484923751904935 	 Accuracy: 0.10430247718383312
Delta: 0.0024586992911655313 	  Loss: 1.548448652983288 	 Accuracy: 0.10299869621903521
Delta: 0.0014236079774284682 	  Loss: 1.548430647476553 	 Accuracy: 0.10299869621903521
Delta: 0.0011347709254699958 	  Loss: 1.5484019794317394 	 Accuracy: 0.10299869621903521
Delta: 0.0026656330255647063 	  Loss: 1.5483341352528648 	 Accuracy: 0.10299869621903521
Delta: 0.0014992316909854437 	  Loss: 1.5483055878783607 	 Accuracy: 0.10299869621903521
Delta: 0.0028090057342360104 	  Loss: 1.5483177263313448 	 Accuracy: 0.10299869621903521
Delta: 0.0005435947669735133 	  Loss: 1.5482986931366622 	 Accuracy: 0.10299869621903521
Delta: 0.002024726195995966 	  Loss: 1.5483001533533618 	 Accuracy: 0.10299869621903521
Delta: 0.0016981765893028732 	  Loss: 1.5482450115949058 	 Accuracy: 0.10430247718383312
Delta: 0.001336503128435084 	  Loss: 1.5482207232359406 	 Accuracy: 0.10430247718383312
Delta: 0.0005153927928748273 	  Loss: 1.5481917628333184 	 Accuracy: 0.10560625814863103
Delta: 5.540003043520578e-05 	  Loss: 1.5482000812880288 	 Accuracy: 0.10430247718383312
Delta: 0.001812748716989712 	  Loss: 1.5481621773709509 	 Accuracy: 0.10560625814863103
Delta: 0.0009467395182756669 	  Loss: 1.5481604219818916 	 Accuracy: 0.10430247718383312
Delta: 0.0028258547579733417 	  Loss: 1.548158410099188 	 Accuracy: 0.10560625814863103
Delta: 0.0017089899565685296 	  Loss: 1.548109780865677 	 Accuracy: 0.10430247718383312
Delta: 0.0012784321459068599 	  Loss: 1.5480905026725393 	 Accuracy: 0.10430247718383312
Delta: 0.0015263643248555681 	  Loss: 1.5480720037637354 	 Accuracy: 0.10430247718383312
Delta: 0.000875628945695438 	  Loss: 1.5480599828752721 	 Accuracy: 0.10430247718383312
Delta: 0.002415787577145008 	  Loss: 1.5480803470606508 	 Accuracy: 0.10430247718383312
Delta: 4.158712366562307e-05 	  Loss: 1.5480493800216288 	 Accuracy: 0.10430247718383312
Delta: 0.0013383868919646916 	  Loss: 1.5480293277299078 	 Accuracy: 0.10430247718383312
Delta: 0.0005025195678480243 	  Loss: 1.5480161114587876 	 Accuracy: 0.10430247718383312
Delta: 0.000551051508160111 	  Loss: 1.5479945918213818 	 Accuracy: 0.10430247718383312
Delta: 2.360123495593903e-05 	  Loss: 1.5479851320766929 	 Accuracy: 0.10430247718383312
Delta: 3.834529257880756e-05 	  Loss: 1.5479738811676946 	 Accuracy: 0.10430247718383312
Delta: 1.8595854069642748e-05 	  Loss: 1.5479633442055145 	 Accuracy: 0.10430247718383312
Delta: 1.910103013084439e-05 	  Loss: 1.547959671016831 	 Accuracy: 0.10430247718383312
Delta: 0.0007365859726393503 	  Loss: 1.5479525970550019 	 Accuracy: 0.10430247718383312
Delta: 0.001991172511758669 	  Loss: 1.5479452527942943 	 Accuracy: 0.10430247718383312
Delta: 0.0005157369424543506 	  Loss: 1.547932557017178 	 Accuracy: 0.10430247718383312
Delta: 3.705446533528053e-05 	  Loss: 1.5479212376546827 	 Accuracy: 0.10430247718383312
Delta: 0.0014924522625500225 	  Loss: 1.5479237175045484 	 Accuracy: 0.10430247718383312
Delta: 0.020939852565928483 	  Loss: 2.157852269402153 	 Accuracy: 0.19556714471968709
Delta: 0.018397475712928477 	  Loss: 2.0845701844202145 	 Accuracy: 0.21121251629726207
Delta: 0.01660322266032616 	  Loss: 1.9803581497953822 	 Accuracy: 0.2333767926988266
Delta: 0.014857831962843532 	  Loss: 1.8846336469782279 	 Accuracy: 0.20990873533246415
Delta: 0.014275124626199705 	  Loss: 1.801425744686025 	 Accuracy: 0.19165580182529335
Delta: 0.012888061900971921 	  Loss: 1.7254270786318144 	 Accuracy: 0.18122555410691005
Delta: 0.010925329337038268 	  Loss: 1.667975079199822 	 Accuracy: 0.15254237288135594
Delta: 0.009397634589903676 	  Loss: 1.6315795764788088 	 Accuracy: 0.13428943937418514
Delta: 0.008583252821575805 	  Loss: 1.6080143477398283 	 Accuracy: 0.12255541069100391
Delta: 0.007694599470462199 	  Loss: 1.592983862649238 	 Accuracy: 0.121251629726206
Delta: 0.007135952404360376 	  Loss: 1.582078514372704 	 Accuracy: 0.11864406779661017
Delta: 0.006400090866020346 	  Loss: 1.5741049135546188 	 Accuracy: 0.11603650586701435
Delta: 0.005415741200425117 	  Loss: 1.5685356165862516 	 Accuracy: 0.11864406779661017
Delta: 0.005367957583161733 	  Loss: 1.5646638086137399 	 Accuracy: 0.11603650586701435
Delta: 0.004893419328745376 	  Loss: 1.5616239532116336 	 Accuracy: 0.11603650586701435
Delta: 0.005254083565390357 	  Loss: 1.5591974012937244 	 Accuracy: 0.10951760104302477
Delta: 0.0054854680587971974 	  Loss: 1.5571838243793747 	 Accuracy: 0.11082138200782268
Delta: 0.0032369654824129855 	  Loss: 1.5561598346359007 	 Accuracy: 0.11342894393741851
Delta: 0.003568980538586745 	  Loss: 1.555340117690645 	 Accuracy: 0.11342894393741851
Delta: 0.0036670122463254747 	  Loss: 1.5545719917309322 	 Accuracy: 0.11473272490221642
Delta: 0.003404367796714501 	  Loss: 1.554086276904914 	 Accuracy: 0.11082138200782268

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0035348382631258104 	  Loss: 1.5535889687188673 	 Accuracy: 0.1121251629726206
Delta: 0.0029831670199680907 	  Loss: 1.5533774496187311 	 Accuracy: 0.11082138200782268
Delta: 0.0031847844284619777 	  Loss: 1.553259226095258 	 Accuracy: 0.10951760104302477
Delta: 0.0017540172155259522 	  Loss: 1.5530568807721068 	 Accuracy: 0.10951760104302477
Delta: 0.003444569051049647 	  Loss: 1.5529295324078398 	 Accuracy: 0.11082138200782268
Delta: 0.0030235128475347953 	  Loss: 1.5529422421634722 	 Accuracy: 0.10951760104302477
Delta: 0.0025234961246290723 	  Loss: 1.5528374878081643 	 Accuracy: 0.1121251629726206
Delta: 0.0020235574308699092 	  Loss: 1.5528079759115936 	 Accuracy: 0.11342894393741851
Delta: 0.0027931636755421227 	  Loss: 1.552856673007097 	 Accuracy: 0.11082138200782268
Delta: 0.0029058517241250972 	  Loss: 1.5527856535276028 	 Accuracy: 0.1121251629726206
Delta: 0.0033896551972370658 	  Loss: 1.552706529177689 	 Accuracy: 0.1121251629726206
Delta: 0.0020015749739594074 	  Loss: 1.5527206117752677 	 Accuracy: 0.10821382007822686
Delta: 0.0014680674186587517 	  Loss: 1.552578457525116 	 Accuracy: 0.1121251629726206
Delta: 0.0008182638803750978 	  Loss: 1.5525927946255145 	 Accuracy: 0.10951760104302477
Delta: 0.0025027232330531225 	  Loss: 1.5525636889051633 	 Accuracy: 0.10951760104302477
Delta: 4.984229659163982e-05 	  Loss: 1.5525631827514785 	 Accuracy: 0.11082138200782268
Delta: 0.0025094830131926495 	  Loss: 1.552543657682504 	 Accuracy: 0.1121251629726206
Delta: 0.0010977179123872291 	  Loss: 1.5526355590623462 	 Accuracy: 0.1121251629726206
Delta: 0.0019486842833780819 	  Loss: 1.552607615031122 	 Accuracy: 0.11082138200782268
Delta: 0.002349554824008031 	  Loss: 1.5526199767935729 	 Accuracy: 0.10821382007822686
Delta: 0.000651134486150716 	  Loss: 1.5525292909848258 	 Accuracy: 0.10821382007822686
Delta: 0.002072963986653011 	  Loss: 1.5525650552869017 	 Accuracy: 0.11082138200782268
Delta: 0.000534583385409942 	  Loss: 1.5525396944227727 	 Accuracy: 0.10821382007822686
Delta: 0.0005285516842433365 	  Loss: 1.5524616946779588 	 Accuracy: 0.10951760104302477
Delta: 4.207104322152054e-05 	  Loss: 1.552545956284236 	 Accuracy: 0.10951760104302477
Delta: 0.0014538204368379787 	  Loss: 1.5524659537582903 	 Accuracy: 0.11082138200782268
Delta: 0.0012206978376101492 	  Loss: 1.5525206263411315 	 Accuracy: 0.10821382007822686
Delta: 2.427060416236132e-05 	  Loss: 1.55246988300643 	 Accuracy: 0.10821382007822686
Delta: 2.3652658149678602e-05 	  Loss: 1.5524353347275235 	 Accuracy: 0.10951760104302477
Delta: 0.0010883718627438827 	  Loss: 1.5523587075626795 	 Accuracy: 0.10821382007822686
Delta: 0.0029574993629652192 	  Loss: 1.5524727405623873 	 Accuracy: 0.10951760104302477
Delta: 3.483418753004268e-05 	  Loss: 1.55250296702067 	 Accuracy: 0.10951760104302477
Delta: 0.0016449304555547527 	  Loss: 1.552525049278215 	 Accuracy: 0.10951760104302477
Delta: 1.8871589388980552e-05 	  Loss: 1.552516951672848 	 Accuracy: 0.11082138200782268
Delta: 1.6948802871853843e-05 	  Loss: 1.5525251818966308 	 Accuracy: 0.11082138200782268
Delta: 0.0005096584551258703 	  Loss: 1.5525913784314949 	 Accuracy: 0.10951760104302477
Delta: 0.0008772106407929133 	  Loss: 1.552492359519753 	 Accuracy: 0.10951760104302477
Delta: 0.0006086442835194056 	  Loss: 1.5525263733635848 	 Accuracy: 0.11082138200782268
Delta: 0.0006164512816861677 	  Loss: 1.552526713976944 	 Accuracy: 0.10951760104302477
Delta: 0.0016877861351713545 	  Loss: 1.552587123949659 	 Accuracy: 0.10951760104302477
Delta: 0.0005137153996695281 	  Loss: 1.5525915732674327 	 Accuracy: 0.10951760104302477
Delta: 9.971150527395736e-06 	  Loss: 1.5525891822112823 	 Accuracy: 0.10951760104302477
Delta: 2.9602557236298288e-05 	  Loss: 1.5525783863902005 	 Accuracy: 0.10951760104302477
Delta: 1.3886792833839795e-05 	  Loss: 1.5525533856931277 	 Accuracy: 0.11082138200782268
Delta: 2.294972678452733e-05 	  Loss: 1.552519492597381 	 Accuracy: 0.11082138200782268
Delta: 0.0007073208533321019 	  Loss: 1.5525781637460718 	 Accuracy: 0.10951760104302477
Delta: 2.407953263745942e-05 	  Loss: 1.5524643658395894 	 Accuracy: 0.11082138200782268
Delta: 1.6983720644359802e-05 	  Loss: 1.5525265523161784 	 Accuracy: 0.10951760104302477
Delta: 2.419130268679773e-05 	  Loss: 1.5525599386244329 	 Accuracy: 0.10951760104302477
Delta: 1.4403486635507755e-05 	  Loss: 1.552544605424698 	 Accuracy: 0.11082138200782268
Delta: 3.113950270379771e-05 	  Loss: 1.5525837896558552 	 Accuracy: 0.11082138200782268
Delta: 0.0005137500253075846 	  Loss: 1.5526017497514115 	 Accuracy: 0.10951760104302477
Delta: 0.0007066354101756623 	  Loss: 1.5525584001749477 	 Accuracy: 0.11082138200782268
Delta: 1.3557394755829097e-05 	  Loss: 1.5525448412759593 	 Accuracy: 0.11082138200782268
Delta: 1.4040934190923951e-05 	  Loss: 1.5525496028007595 	 Accuracy: 0.10951760104302477
Delta: 0.0009354644373128422 	  Loss: 1.5525546009335696 	 Accuracy: 0.10951760104302477
Delta: 1.4345908376869083e-05 	  Loss: 1.5525043750350962 	 Accuracy: 0.10951760104302477
Delta: 1.7825278733123702e-05 	  Loss: 1.5525279889400676 	 Accuracy: 0.10951760104302477
Delta: 0.0007209794688615643 	  Loss: 1.5525247280328842 	 Accuracy: 0.10951760104302477
Delta: 2.6415532201490347e-05 	  Loss: 1.552523246447906 	 Accuracy: 0.11082138200782268
Delta: 0.0018134260655531572 	  Loss: 1.5525125136910103 	 Accuracy: 0.11082138200782268
Delta: 4.409154389444385e-05 	  Loss: 1.5525517780603422 	 Accuracy: 0.11082138200782268
Delta: 0.0009407020646267777 	  Loss: 1.5526535904048924 	 Accuracy: 0.11082138200782268
Delta: 0.0012271410124056457 	  Loss: 1.5526846092711215 	 Accuracy: 0.11082138200782268
Delta: 0.002255030201990646 	  Loss: 1.552555530253123 	 Accuracy: 0.11082138200782268
Delta: 0.00153834771266149 	  Loss: 1.5528103731688045 	 Accuracy: 0.11082138200782268
Delta: 0.0012439039783325198 	  Loss: 1.5527626053265626 	 Accuracy: 0.11082138200782268
Delta: 0.0018600262024717803 	  Loss: 1.5527824452513852 	 Accuracy: 0.11082138200782268
Delta: 7.157829801929839e-05 	  Loss: 1.552690391356299 	 Accuracy: 0.11082138200782268
Delta: 0.0019365776247122187 	  Loss: 1.5525231510893902 	 Accuracy: 0.11082138200782268
Delta: 0.0009107413750349831 	  Loss: 1.5528683724700465 	 Accuracy: 0.10951760104302477
Delta: 0.0020934443362383296 	  Loss: 1.552671320487462 	 Accuracy: 0.11082138200782268
Delta: 0.0022703824299369394 	  Loss: 1.5525556253447872 	 Accuracy: 0.11082138200782268
Delta: 0.0013463484071040003 	  Loss: 1.5524915845708107 	 Accuracy: 0.11082138200782268
Delta: 0.0018065510361525718 	  Loss: 1.5525700386387407 	 Accuracy: 0.11082138200782268
Delta: 0.0015884088906944864 	  Loss: 1.552681151946486 	 Accuracy: 0.11082138200782268
Delta: 0.0016265737988430894 	  Loss: 1.5524763520462834 	 Accuracy: 0.10951760104302477
Delta: 0.0012741802290497741 	  Loss: 1.5523896665656816 	 Accuracy: 0.11082138200782268
Delta: 0.0024986620508575573 	  Loss: 1.552707622086483 	 Accuracy: 0.11082138200782268
Delta: 0.020945398864821524 	  Loss: 2.157828941373701 	 Accuracy: 0.19556714471968709
Delta: 0.018464327594417455 	  Loss: 2.082732707914899 	 Accuracy: 0.22033898305084745
Delta: 0.016940923355563003 	  Loss: 1.9724972200734006 	 Accuracy: 0.22294654498044328
Delta: 0.015706554415789935 	  Loss: 1.8610540614657998 	 Accuracy: 0.29465449804432853
Delta: 0.014060332383800174 	  Loss: 1.7576881688547674 	 Accuracy: 0.2711864406779661
Delta: 0.011937872701465393 	  Loss: 1.6802277821784366 	 Accuracy: 0.20990873533246415
Delta: 0.010325750433277431 	  Loss: 1.6339117737785724 	 Accuracy: 0.17209908735332463
Delta: 0.009183806460474588 	  Loss: 1.607217178663282 	 Accuracy: 0.15254237288135594
Delta: 0.007989815631888863 	  Loss: 1.590266209026073 	 Accuracy: 0.13820078226857888
Delta: 0.007612173019891508 	  Loss: 1.5796793896356836 	 Accuracy: 0.1303780964797914
Delta: 0.007254332144794761 	  Loss: 1.571526525802048 	 Accuracy: 0.12255541069100391
Delta: 0.005958827473233306 	  Loss: 1.5663028019547816 	 Accuracy: 0.12255541069100391
Delta: 0.005133667364469416 	  Loss: 1.5632649551984619 	 Accuracy: 0.11864406779661017
Delta: 0.005055808952519569 	  Loss: 1.561441986743879 	 Accuracy: 0.12385919165580182

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004728462687923134 	  Loss: 1.5602839619346471 	 Accuracy: 0.1316818774445893
Delta: 0.005128413384194506 	  Loss: 1.559060752146117 	 Accuracy: 0.1303780964797914
Delta: 0.004156712859478667 	  Loss: 1.558366273474626 	 Accuracy: 0.12777053455019557
Delta: 0.004210575591867944 	  Loss: 1.5576903814820255 	 Accuracy: 0.1316818774445893
Delta: 0.004754651081023122 	  Loss: 1.5572538222325383 	 Accuracy: 0.1316818774445893
Delta: 0.0022416756574376766 	  Loss: 1.5570446832828198 	 Accuracy: 0.13298565840938723
Delta: 0.003196821559161843 	  Loss: 1.556979421786198 	 Accuracy: 0.13298565840938723
Delta: 0.003077398560767261 	  Loss: 1.5568438778306781 	 Accuracy: 0.1303780964797914
Delta: 0.0034193904442638094 	  Loss: 1.5568302223367103 	 Accuracy: 0.1316818774445893
Delta: 0.003095929886383231 	  Loss: 1.5568099133189814 	 Accuracy: 0.1316818774445893
Delta: 0.0027594544318571045 	  Loss: 1.5568156652360554 	 Accuracy: 0.1316818774445893
Delta: 0.0018561101865713777 	  Loss: 1.5568597220972553 	 Accuracy: 0.1316818774445893
Delta: 0.0016143579091492837 	  Loss: 1.5569115102760231 	 Accuracy: 0.1316818774445893
Delta: 0.002071332060552612 	  Loss: 1.5568872794083695 	 Accuracy: 0.1316818774445893
Delta: 0.0023400327535694934 	  Loss: 1.556920552939112 	 Accuracy: 0.1316818774445893
Delta: 0.0013010700526935408 	  Loss: 1.5568459585281413 	 Accuracy: 0.1316818774445893
Delta: 0.002530076546191812 	  Loss: 1.5568074496992532 	 Accuracy: 0.1316818774445893
Delta: 0.0008847058183852016 	  Loss: 1.5568527521497253 	 Accuracy: 0.1303780964797914
Delta: 0.0021972787208790635 	  Loss: 1.5567455615436083 	 Accuracy: 0.1303780964797914
Delta: 0.00122708290639421 	  Loss: 1.556761292460787 	 Accuracy: 0.1303780964797914
Delta: 0.0005302839232251597 	  Loss: 1.5566883789720296 	 Accuracy: 0.1316818774445893
Delta: 0.0012740227069841254 	  Loss: 1.5569609519262462 	 Accuracy: 0.1316818774445893
Delta: 0.0008230178353416109 	  Loss: 1.5569061185594915 	 Accuracy: 0.13298565840938723
Delta: 0.002296878798100029 	  Loss: 1.5568033952484843 	 Accuracy: 0.1316818774445893
Delta: 0.0021538713214543734 	  Loss: 1.5567041120770713 	 Accuracy: 0.1316818774445893
Delta: 3.29701612962174e-05 	  Loss: 1.5567196763631528 	 Accuracy: 0.1303780964797914
Delta: 8.341826937439141e-05 	  Loss: 1.556873215140293 	 Accuracy: 0.1303780964797914
Delta: 0.0017656823174012311 	  Loss: 1.5568711173106355 	 Accuracy: 0.1316818774445893
Delta: 0.0005297683972094572 	  Loss: 1.556770090796861 	 Accuracy: 0.1316818774445893
Delta: 0.0021065236284104737 	  Loss: 1.556428256463308 	 Accuracy: 0.1303780964797914
Delta: 3.3133819745757476e-05 	  Loss: 1.5564283492380078 	 Accuracy: 0.1316818774445893
converged at iter  44
Delta: 0.020997006206254287 	  Loss: 2.157606013318839 	 Accuracy: 0.19556714471968709
Delta: 0.018727058937604728 	  Loss: 2.073610652426635 	 Accuracy: 0.258148631029987
Delta: 0.01723027995666721 	  Loss: 1.9340358069237018 	 Accuracy: 0.34810951760104303
Delta: 0.01450275464442223 	  Loss: 1.809040498518503 	 Accuracy: 0.44328552803129073
Delta: 0.012631564923758234 	  Loss: 1.7273004458945014 	 Accuracy: 0.42242503259452413
Delta: 0.011651594641138062 	  Loss: 1.6765824042368211 	 Accuracy: 0.37027379400260757
Delta: 0.010775589517577958 	  Loss: 1.6446269419832478 	 Accuracy: 0.3220338983050847
Delta: 0.009930751028883966 	  Loss: 1.6225110050441178 	 Accuracy: 0.29335071707953064
Delta: 0.008489547311995024 	  Loss: 1.6090515329290778 	 Accuracy: 0.27509778357235987
Delta: 0.007802614067487257 	  Loss: 1.6003433742145596 	 Accuracy: 0.27249022164276404
Delta: 0.0066529093711227855 	  Loss: 1.5943959653979538 	 Accuracy: 0.2633637548891786
Delta: 0.006140321412387067 	  Loss: 1.5908003383089508 	 Accuracy: 0.258148631029987
Delta: 0.006673330497788303 	  Loss: 1.5881339681565245 	 Accuracy: 0.26597131681877445

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005150411056316486 	  Loss: 1.5865087649365455 	 Accuracy: 0.26597131681877445
Delta: 0.005400805666916588 	  Loss: 1.5855371497123742 	 Accuracy: 0.2646675358539765
Delta: 0.005332498221816214 	  Loss: 1.5845794837186706 	 Accuracy: 0.2646675358539765
Delta: 0.0037534791723887982 	  Loss: 1.5837698014072803 	 Accuracy: 0.26988265971316816
Delta: 0.00468573576047841 	  Loss: 1.5830796843016481 	 Accuracy: 0.26988265971316816
Delta: 0.004649024425362815 	  Loss: 1.5825416714776552 	 Accuracy: 0.2711864406779661
Delta: 0.0019046892411471196 	  Loss: 1.5824223591481545 	 Accuracy: 0.2711864406779661
Delta: 0.0027505117602193273 	  Loss: 1.5821450646599198 	 Accuracy: 0.26988265971316816
Delta: 0.003530748798377038 	  Loss: 1.5820037120868882 	 Accuracy: 0.2711864406779661
Delta: 0.004254451942485717 	  Loss: 1.5815432470900594 	 Accuracy: 0.2711864406779661
Delta: 0.0016867409029432449 	  Loss: 1.5814174139420403 	 Accuracy: 0.27509778357235987
Delta: 0.0019621502940580108 	  Loss: 1.5812451840888913 	 Accuracy: 0.2737940026075619
Delta: 0.0036984455690527397 	  Loss: 1.5812476466832448 	 Accuracy: 0.2711864406779661
Delta: 0.00298088454259142 	  Loss: 1.5812683281311235 	 Accuracy: 0.2711864406779661
Delta: 0.001441950522371354 	  Loss: 1.5812295398673708 	 Accuracy: 0.2711864406779661
Delta: 0.0007604877386184529 	  Loss: 1.5812714624795476 	 Accuracy: 0.27249022164276404
Delta: 6.339529889224216e-05 	  Loss: 1.5811574427436503 	 Accuracy: 0.2737940026075619
Delta: 0.0038177996846888583 	  Loss: 1.5813704094757444 	 Accuracy: 0.2711864406779661
Delta: 5.5387615825018946e-05 	  Loss: 1.5814819220150542 	 Accuracy: 0.26988265971316816
Delta: 0.0013897293245959679 	  Loss: 1.58141823916339 	 Accuracy: 0.2711864406779661
Delta: 0.0031920260737386434 	  Loss: 1.5812772384972023 	 Accuracy: 0.26988265971316816
Delta: 0.0018953101817842392 	  Loss: 1.5811654848958594 	 Accuracy: 0.27249022164276404
Delta: 0.001826273217448898 	  Loss: 1.5815427509159108 	 Accuracy: 0.27249022164276404
Delta: 0.0018591930703058532 	  Loss: 1.5814751677707075 	 Accuracy: 0.27249022164276404
Delta: 0.0015444976480291572 	  Loss: 1.5812345598225734 	 Accuracy: 0.2737940026075619
Delta: 0.001988040216631709 	  Loss: 1.5809157281450599 	 Accuracy: 0.27249022164276404
Delta: 0.002145029167283047 	  Loss: 1.5811781313600903 	 Accuracy: 0.2737940026075619
Delta: 0.002438774083738701 	  Loss: 1.5809537459315126 	 Accuracy: 0.27249022164276404
Delta: 0.0005306930300951264 	  Loss: 1.5810353707419902 	 Accuracy: 0.27249022164276404
Delta: 0.0026898881458875786 	  Loss: 1.5809799524762622 	 Accuracy: 0.2711864406779661
Delta: 0.0013850485085777232 	  Loss: 1.5812408577417063 	 Accuracy: 0.26727509778357234
Delta: 0.0035453018657159207 	  Loss: 1.5817668564921163 	 Accuracy: 0.26988265971316816
Delta: 0.0021976951506311577 	  Loss: 1.581931349775047 	 Accuracy: 0.27249022164276404
Delta: 0.003920291034410375 	  Loss: 1.5810703349084585 	 Accuracy: 0.27249022164276404
Delta: 0.0013573063590633927 	  Loss: 1.5810813264891581 	 Accuracy: 0.2711864406779661
Delta: 0.0029562463065345335 	  Loss: 1.581226065066263 	 Accuracy: 0.27249022164276404
Delta: 0.0026737795109498756 	  Loss: 1.58115449757572 	 Accuracy: 0.2737940026075619
Delta: 0.00439903237640825 	  Loss: 1.580937628922602 	 Accuracy: 0.27249022164276404
Delta: 0.001049466926218069 	  Loss: 1.5809844254924554 	 Accuracy: 0.27249022164276404
Delta: 0.002842310310710024 	  Loss: 1.5809090710965439 	 Accuracy: 0.27249022164276404
Delta: 0.0033198651625367813 	  Loss: 1.5808260678754271 	 Accuracy: 0.27249022164276404
Delta: 0.003959248082770382 	  Loss: 1.5808237601376807 	 Accuracy: 0.27249022164276404
Delta: 0.0008779425036834483 	  Loss: 1.5807992496497787 	 Accuracy: 0.2711864406779661
Delta: 0.0015263343686688837 	  Loss: 1.5809460011485377 	 Accuracy: 0.2711864406779661
Delta: 0.0023363916453351613 	  Loss: 1.5808446331506547 	 Accuracy: 0.2711864406779661
Delta: 0.001854108804319897 	  Loss: 1.5810352195259971 	 Accuracy: 0.2711864406779661
Delta: 0.0012053289753321146 	  Loss: 1.5809366259910567 	 Accuracy: 0.2711864406779661
Delta: 0.00011792527229836581 	  Loss: 1.5812971418281847 	 Accuracy: 0.2711864406779661
Delta: 0.002789295644191521 	  Loss: 1.5813777636132837 	 Accuracy: 0.2711864406779661
Delta: 0.0008264667428216989 	  Loss: 1.5811879458986415 	 Accuracy: 0.26988265971316816
Delta: 0.000551413737966926 	  Loss: 1.581203506499053 	 Accuracy: 0.2711864406779661
Delta: 5.592956784750901e-05 	  Loss: 1.581089273061387 	 Accuracy: 0.2711864406779661
Delta: 4.523707982402641e-05 	  Loss: 1.581086903598184 	 Accuracy: 0.2711864406779661
Delta: 4.896157978000012e-05 	  Loss: 1.5812103323094069 	 Accuracy: 0.2711864406779661
Delta: 1.576218581979583e-05 	  Loss: 1.581155865972479 	 Accuracy: 0.2711864406779661
Delta: 3.547543134672185e-05 	  Loss: 1.581226025615661 	 Accuracy: 0.2711864406779661
Delta: 4.039057896486922e-05 	  Loss: 1.5810873309678772 	 Accuracy: 0.2711864406779661
Delta: 3.241647815792531e-05 	  Loss: 1.5811095612805262 	 Accuracy: 0.2711864406779661
Delta: 1.3997400363414062e-05 	  Loss: 1.58111634926227 	 Accuracy: 0.2711864406779661
Delta: 2.526248533552277e-05 	  Loss: 1.5811631035837164 	 Accuracy: 0.2711864406779661
Delta: 3.603341998037915e-05 	  Loss: 1.5810086014348097 	 Accuracy: 0.2711864406779661
Delta: 4.1316761629025874e-05 	  Loss: 1.5811391224427918 	 Accuracy: 0.27249022164276404
Delta: 0.0025226858947623026 	  Loss: 1.5811405944837214 	 Accuracy: 0.2711864406779661
Delta: 0.00011836395424241832 	  Loss: 1.5815368631559892 	 Accuracy: 0.2711864406779661
Delta: 9.22812894962793e-05 	  Loss: 1.5810533756808933 	 Accuracy: 0.2711864406779661
Delta: 0.002774409535362472 	  Loss: 1.5813916446500402 	 Accuracy: 0.2711864406779661
Delta: 0.0009282081257638754 	  Loss: 1.5810721215322725 	 Accuracy: 0.27249022164276404
Delta: 6.379842905239783e-05 	  Loss: 1.5812005043100554 	 Accuracy: 0.27249022164276404
Delta: 4.370331286820266e-05 	  Loss: 1.5810596746176666 	 Accuracy: 0.27249022164276404
Delta: 8.01646603965418e-06 	  Loss: 1.5810727387258363 	 Accuracy: 0.2711864406779661
Delta: 6.567029468208757e-05 	  Loss: 1.58107004029619 	 Accuracy: 0.2711864406779661
Delta: 6.921996337040846e-05 	  Loss: 1.5810690359348092 	 Accuracy: 0.2711864406779661
Delta: 3.9839246670050226e-05 	  Loss: 1.5811317766118507 	 Accuracy: 0.26988265971316816
Delta: 7.248001048531534e-05 	  Loss: 1.5813112010278738 	 Accuracy: 0.26988265971316816
Delta: 0.0026523754769452205 	  Loss: 1.5821129603618207 	 Accuracy: 0.26988265971316816
Delta: 0.0009536746348057371 	  Loss: 1.581117342610472 	 Accuracy: 0.2777053455019557
Delta: 0.001653892492035153 	  Loss: 1.581267966076431 	 Accuracy: 0.26988265971316816
Delta: 0.0014196737471614362 	  Loss: 1.5812262282445428 	 Accuracy: 0.2711864406779661
Delta: 0.0007370574052276924 	  Loss: 1.581325101696558 	 Accuracy: 0.2711864406779661
Delta: 0.0018781193697873034 	  Loss: 1.581068448329011 	 Accuracy: 0.2711864406779661
Delta: 2.945865688750335e-05 	  Loss: 1.5810143984222302 	 Accuracy: 0.2711864406779661
Delta: 9.299640620305614e-05 	  Loss: 1.5813414823934107 	 Accuracy: 0.2711864406779661
Delta: 0.001741109432083611 	  Loss: 1.5815015578126335 	 Accuracy: 0.2711864406779661
Delta: 0.0028389625050585184 	  Loss: 1.5811143823372902 	 Accuracy: 0.2711864406779661
Delta: 0.003764369212572037 	  Loss: 1.5808440642219876 	 Accuracy: 0.2711864406779661
Delta: 4.37141139750681e-05 	  Loss: 1.580832067303429 	 Accuracy: 0.26988265971316816
Delta: 3.386766733829477e-05 	  Loss: 1.5808657432397304 	 Accuracy: 0.2711864406779661
Delta: 0.02095662900139426 	  Loss: 2.1569589390216235 	 Accuracy: 0.19035202086049544
Delta: 0.01842501845763095 	  Loss: 2.0791877880462097 	 Accuracy: 0.29595827900912647
Delta: 0.017302292555890397 	  Loss: 1.946122504463585 	 Accuracy: 0.35071707953063885
Delta: 0.015462288308037891 	  Loss: 1.7904580168769781 	 Accuracy: 0.3194263363754889
Delta: 0.013212065063549126 	  Loss: 1.7024159599630144 	 Accuracy: 0.3533246414602347
Delta: 0.011740668865711994 	  Loss: 1.6564926802224327 	 Accuracy: 0.3728813559322034
Delta: 0.00997766118385365 	  Loss: 1.6294098245960291 	 Accuracy: 0.37809647979139505
Delta: 0.008753351704942356 	  Loss: 1.6130063095488008 	 Accuracy: 0.38852672750977835
Delta: 0.008881004719112457 	  Loss: 1.6023987394792616 	 Accuracy: 0.3859191655801825
Delta: 0.007017423755632661 	  Loss: 1.596507215583232 	 Accuracy: 0.3820078226857888
Delta: 0.007027605210855376 	  Loss: 1.5930905574847454 	 Accuracy: 0.38461538461538464
Delta: 0.006822037758175704 	  Loss: 1.5915062062377694 	 Accuracy: 0.38070404172099087

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004704599059938716 	  Loss: 1.5906965317502986 	 Accuracy: 0.379400260756193
Delta: 0.004024461949428016 	  Loss: 1.590384575484995 	 Accuracy: 0.38461538461538464
Delta: 0.005460301863363817 	  Loss: 1.5902299224793395 	 Accuracy: 0.3833116036505867
Delta: 0.0036962100117457555 	  Loss: 1.590338520877929 	 Accuracy: 0.3833116036505867
Delta: 0.0032365373227438952 	  Loss: 1.5902540827756497 	 Accuracy: 0.3859191655801825
Delta: 0.003974752767035721 	  Loss: 1.5897274512964934 	 Accuracy: 0.3859191655801825
Delta: 0.0025643338640005267 	  Loss: 1.5897502229682499 	 Accuracy: 0.38852672750977835
Delta: 0.002878364436354127 	  Loss: 1.5895728518210595 	 Accuracy: 0.39113428943937417
Delta: 0.0022995762640227843 	  Loss: 1.589295207257081 	 Accuracy: 0.38722294654498046
Delta: 0.001696806707663297 	  Loss: 1.5894727160769202 	 Accuracy: 0.38461538461538464
Delta: 0.002104283002236176 	  Loss: 1.5895390027749423 	 Accuracy: 0.3859191655801825
Delta: 0.0024047286720348753 	  Loss: 1.5895557936880844 	 Accuracy: 0.38722294654498046
Delta: 2.9775216420704693e-05 	  Loss: 1.5895810994494197 	 Accuracy: 0.3859191655801825
Delta: 0.000651076651254425 	  Loss: 1.589528041718884 	 Accuracy: 0.38852672750977835
Delta: 3.671457997923867e-05 	  Loss: 1.5895405659098762 	 Accuracy: 0.38852672750977835
Delta: 0.0013110008883040329 	  Loss: 1.5895790287051788 	 Accuracy: 0.38722294654498046
Delta: 2.222428414205686e-05 	  Loss: 1.5895224965049903 	 Accuracy: 0.38852672750977835
Delta: 0.000805539340610875 	  Loss: 1.5895942089450903 	 Accuracy: 0.38852672750977835
Delta: 0.0027112698901952774 	  Loss: 1.5895959363653756 	 Accuracy: 0.38852672750977835
Delta: 0.0007272559311444886 	  Loss: 1.589507021006594 	 Accuracy: 0.38852672750977835
Delta: 2.2941871028881498e-05 	  Loss: 1.5895947811869644 	 Accuracy: 0.38852672750977835
Delta: 1.745121887571092e-05 	  Loss: 1.5895653132882455 	 Accuracy: 0.38852672750977835
Delta: 3.1093702868919766e-05 	  Loss: 1.5895356558465565 	 Accuracy: 0.38722294654498046
Delta: 3.260876100657789e-05 	  Loss: 1.5895265630898732 	 Accuracy: 0.38852672750977835
Delta: 3.106681194437877e-05 	  Loss: 1.589442273632661 	 Accuracy: 0.38852672750977835
Delta: 3.580731134438539e-05 	  Loss: 1.5894897246642143 	 Accuracy: 0.38852672750977835
Delta: 1.7876391584486855e-05 	  Loss: 1.5895650946041295 	 Accuracy: 0.38722294654498046
Delta: 3.2705198846388377e-05 	  Loss: 1.5894619257118947 	 Accuracy: 0.38852672750977835
Delta: 9.975422412657596e-06 	  Loss: 1.5895116246494352 	 Accuracy: 0.38722294654498046
Delta: 1.9317354447155964e-05 	  Loss: 1.5894371648769687 	 Accuracy: 0.38852672750977835
Delta: 1.4974228715553049e-05 	  Loss: 1.5894188597703192 	 Accuracy: 0.38722294654498046
Delta: 0.000809672191956184 	  Loss: 1.5893642819848643 	 Accuracy: 0.38852672750977835
Delta: 2.3309006256051473e-05 	  Loss: 1.589381700461686 	 Accuracy: 0.39374185136897
Delta: 3.938706593623667e-05 	  Loss: 1.5893622298055048 	 Accuracy: 0.38722294654498046
Delta: 3.4311479432960756e-05 	  Loss: 1.589342182871011 	 Accuracy: 0.38722294654498046
Delta: 6.480428240726536e-06 	  Loss: 1.5893630703627868 	 Accuracy: 0.38852672750977835
Delta: 3.717650879846447e-05 	  Loss: 1.5894400896182987 	 Accuracy: 0.38852672750977835
Delta: 2.62757548837626e-05 	  Loss: 1.5893511023286038 	 Accuracy: 0.38852672750977835
Delta: 4.3854409960585835e-05 	  Loss: 1.5894310083101235 	 Accuracy: 0.3833116036505867
Delta: 3.281371511503265e-05 	  Loss: 1.5894285020161796 	 Accuracy: 0.38722294654498046
Delta: 2.1034220603565196e-05 	  Loss: 1.589423318054191 	 Accuracy: 0.38461538461538464
Delta: 0.001990747468264846 	  Loss: 1.5894111452145452 	 Accuracy: 0.3898305084745763
Delta: 0.0034617672739193648 	  Loss: 1.5895314907395424 	 Accuracy: 0.3898305084745763
Delta: 0.00382545805490076 	  Loss: 1.589783758764403 	 Accuracy: 0.3898305084745763
Delta: 0.00348817859490084 	  Loss: 1.589115135573881 	 Accuracy: 0.38852672750977835
Delta: 0.0009061257540736679 	  Loss: 1.5892139352307972 	 Accuracy: 0.3898305084745763
Delta: 0.0006190027064090934 	  Loss: 1.5892788003710576 	 Accuracy: 0.3898305084745763
Delta: 4.170370342124681e-06 	  Loss: 1.5893052261488587 	 Accuracy: 0.38852672750977835
Delta: 0.0010589490358136784 	  Loss: 1.5898156131095365 	 Accuracy: 0.38852672750977835
Delta: 0.001287004683570525 	  Loss: 1.5898819726803899 	 Accuracy: 0.38852672750977835
Delta: 0.0031855424177307614 	  Loss: 1.5903947176424764 	 Accuracy: 0.3859191655801825
Delta: 0.0021618222222511974 	  Loss: 1.5904593423702882 	 Accuracy: 0.3859191655801825
Delta: 2.5439849626442827e-05 	  Loss: 1.5904720559482635 	 Accuracy: 0.38852672750977835
Delta: 1.9991760411933736e-05 	  Loss: 1.5903990962131411 	 Accuracy: 0.38722294654498046
Delta: 1.3861109774215542e-05 	  Loss: 1.5904292836737388 	 Accuracy: 0.3859191655801825
Delta: 0.0005311135007128857 	  Loss: 1.5901013759333016 	 Accuracy: 0.38722294654498046
Delta: 0.0009249008193805518 	  Loss: 1.5901500226087428 	 Accuracy: 0.39113428943937417
Delta: 0.0033473999287688895 	  Loss: 1.5902595999592786 	 Accuracy: 0.3898305084745763
Delta: 0.0027599703432030606 	  Loss: 1.5901573596368124 	 Accuracy: 0.38852672750977835
Delta: 0.003589926829325889 	  Loss: 1.5904049353219636 	 Accuracy: 0.38722294654498046
Delta: 0.0005473610927086883 	  Loss: 1.5907725652539497 	 Accuracy: 0.38852672750977835
Delta: 0.0027075205061423565 	  Loss: 1.5901156003183279 	 Accuracy: 0.3898305084745763
Delta: 0.0025306742075051 	  Loss: 1.590075225137817 	 Accuracy: 0.38852672750977835
Delta: 0.0034597330064877626 	  Loss: 1.5894241516467522 	 Accuracy: 0.38852672750977835
Delta: 0.0012902027948108524 	  Loss: 1.5898310362999488 	 Accuracy: 0.3898305084745763
Delta: 0.0038064492251603348 	  Loss: 1.588914499769046 	 Accuracy: 0.38852672750977835
Delta: 0.004344762352524868 	  Loss: 1.5886577024195836 	 Accuracy: 0.38722294654498046
Delta: 0.002826514441694979 	  Loss: 1.5885429621734377 	 Accuracy: 0.38722294654498046
Delta: 0.0016729332003098294 	  Loss: 1.5885721655817044 	 Accuracy: 0.38852672750977835
Delta: 0.0020401830098821976 	  Loss: 1.5886524014216743 	 Accuracy: 0.38852672750977835
Delta: 0.0018972552188494048 	  Loss: 1.588720492499709 	 Accuracy: 0.3859191655801825
Delta: 0.0038917063708085366 	  Loss: 1.5895881556427127 	 Accuracy: 0.38722294654498046
Delta: 0.001417300233623687 	  Loss: 1.5896471138662736 	 Accuracy: 0.38852672750977835
Delta: 0.002220308717221476 	  Loss: 1.5895537486933344 	 Accuracy: 0.3859191655801825
Delta: 0.0010768820964689087 	  Loss: 1.589505758194605 	 Accuracy: 0.3859191655801825
Delta: 0.0020824788594899814 	  Loss: 1.5898069895003535 	 Accuracy: 0.38722294654498046
Delta: 0.003295611548343664 	  Loss: 1.5899599868992793 	 Accuracy: 0.38722294654498046
Delta: 6.016544598432271e-05 	  Loss: 1.5900388653442752 	 Accuracy: 0.38722294654498046
Delta: 0.001089028777920209 	  Loss: 1.5901293705644028 	 Accuracy: 0.38852672750977835
Delta: 0.0007470335320877181 	  Loss: 1.5901774364790144 	 Accuracy: 0.38852672750977835
Delta: 0.0015600743191722085 	  Loss: 1.5900835728781912 	 Accuracy: 0.38852672750977835
Delta: 0.0032279833531203422 	  Loss: 1.5900729369151374 	 Accuracy: 0.38852672750977835
Delta: 0.0017030078377766019 	  Loss: 1.5902122148803097 	 Accuracy: 0.38852672750977835
Delta: 0.0031472704049556586 	  Loss: 1.5908356810162674 	 Accuracy: 0.38852672750977835
Delta: 0.002511920247956401 	  Loss: 1.5903254365604063 	 Accuracy: 0.3820078226857888
Delta: 0.0026165170060924803 	  Loss: 1.5904396660682871 	 Accuracy: 0.39504563233376794
Delta: 0.0030329122502266645 	  Loss: 1.590063717769115 	 Accuracy: 0.38722294654498046
Delta: 0.002298318834543322 	  Loss: 1.5898246399062699 	 Accuracy: 0.38852672750977835
Delta: 0.02101611450334308 	  Loss: 2.157029989035096 	 Accuracy: 0.196870925684485
Delta: 0.018564589492060052 	  Loss: 2.0682821467747283 	 Accuracy: 0.19556714471968709
Delta: 0.016841416308821553 	  Loss: 1.9342548015723557 	 Accuracy: 0.2737940026075619
Delta: 0.015242142824930768 	  Loss: 1.8132000482599384 	 Accuracy: 0.3533246414602347
Delta: 0.01413305346725492 	  Loss: 1.7300730363725245 	 Accuracy: 0.3624511082138201
Delta: 0.012257058301743689 	  Loss: 1.6771887319432905 	 Accuracy: 0.34419817470664926
Delta: 0.010402572775125199 	  Loss: 1.6497530000225205 	 Accuracy: 0.318122555410691
Delta: 0.009678111927080084 	  Loss: 1.6333037416734313 	 Accuracy: 0.3155149934810952
Delta: 0.007886047639362109 	  Loss: 1.6249227822803025 	 Accuracy: 0.3220338983050847
Delta: 0.007564323964756974 	  Loss: 1.6195619053712798 	 Accuracy: 0.3246414602346806

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006598804303502778 	  Loss: 1.6166541837162822 	 Accuracy: 0.3194263363754889
Delta: 0.0050336413406779626 	  Loss: 1.6155488383011551 	 Accuracy: 0.318122555410691
Delta: 0.005728290730198325 	  Loss: 1.614583406457086 	 Accuracy: 0.32073011734028684
Delta: 0.004557882028683308 	  Loss: 1.6147875393054543 	 Accuracy: 0.3194263363754889
Delta: 0.0036356922692756294 	  Loss: 1.6147369699166652 	 Accuracy: 0.3194263363754889
Delta: 0.0028635034013723077 	  Loss: 1.6144527078602522 	 Accuracy: 0.3194263363754889
Delta: 0.00197109593606071 	  Loss: 1.6145628703069699 	 Accuracy: 0.3194263363754889
Delta: 0.0015421971213545557 	  Loss: 1.614822602713566 	 Accuracy: 0.32073011734028684
Delta: 0.003148191079419247 	  Loss: 1.6147191190485466 	 Accuracy: 0.3220338983050847
Delta: 0.0014245115295626778 	  Loss: 1.6146824484358195 	 Accuracy: 0.3220338983050847
Delta: 0.002524988181267794 	  Loss: 1.6149827290071164 	 Accuracy: 0.32333767926988266
Delta: 0.0016386248265321285 	  Loss: 1.6147033708469305 	 Accuracy: 0.32333767926988266
Delta: 0.0027227558854958254 	  Loss: 1.614166156262252 	 Accuracy: 0.32333767926988266
Delta: 0.0027356800189783344 	  Loss: 1.6141256435944162 	 Accuracy: 0.3220338983050847
Delta: 0.001916630055358796 	  Loss: 1.614238520026586 	 Accuracy: 0.32333767926988266
Delta: 0.0037231676990785666 	  Loss: 1.6137540067049239 	 Accuracy: 0.3220338983050847
Delta: 0.0030155904882573537 	  Loss: 1.6136008183106099 	 Accuracy: 0.3220338983050847
Delta: 0.0013895776401850772 	  Loss: 1.6140224677974657 	 Accuracy: 0.3220338983050847
Delta: 0.0017319841003212118 	  Loss: 1.6131451096751313 	 Accuracy: 0.32073011734028684
Delta: 0.0023059614653421307 	  Loss: 1.6136559807202773 	 Accuracy: 0.3220338983050847
Delta: 0.0010097431470611382 	  Loss: 1.6135282183871476 	 Accuracy: 0.32073011734028684
Delta: 0.0019332639866774099 	  Loss: 1.6139244227613148 	 Accuracy: 0.3220338983050847
Delta: 0.0009416363160684454 	  Loss: 1.6131590362998671 	 Accuracy: 0.3076923076923077
Delta: 0.001189235735847932 	  Loss: 1.6130607424817842 	 Accuracy: 0.3220338983050847
Delta: 0.0021802114695992194 	  Loss: 1.6130218251761417 	 Accuracy: 0.29595827900912647
Delta: 0.0016748857257470433 	  Loss: 1.6129768304042589 	 Accuracy: 0.3220338983050847
Delta: 0.002956609101740079 	  Loss: 1.6134378297063998 	 Accuracy: 0.3220338983050847
Delta: 0.0021185781209573924 	  Loss: 1.612977946619643 	 Accuracy: 0.3220338983050847
Delta: 0.0009343310927146461 	  Loss: 1.6130039780339673 	 Accuracy: 0.3246414602346806
Delta: 0.0017505285817247989 	  Loss: 1.6135060541845232 	 Accuracy: 0.3220338983050847
Delta: 0.0038179853323370536 	  Loss: 1.613776956225462 	 Accuracy: 0.3220338983050847
Delta: 0.003711817057280963 	  Loss: 1.613857717097786 	 Accuracy: 0.30638852672750977
Delta: 0.00512119295859258 	  Loss: 1.6144282705430673 	 Accuracy: 0.32333767926988266
Delta: 0.0014157639648791145 	  Loss: 1.6144850374618234 	 Accuracy: 0.31681877444589307
Delta: 0.004770302881145674 	  Loss: 1.6155284144353272 	 Accuracy: 0.32073011734028684
Delta: 0.001898345142659776 	  Loss: 1.6150373025468803 	 Accuracy: 0.32073011734028684
Delta: 0.0030503433509409166 	  Loss: 1.61475586524564 	 Accuracy: 0.3220338983050847
Delta: 0.003629637457634812 	  Loss: 1.6134232017495673 	 Accuracy: 0.3220338983050847
Delta: 0.004857672021646701 	  Loss: 1.6137121130096477 	 Accuracy: 0.3220338983050847
Delta: 0.004381155666529421 	  Loss: 1.6132486591760031 	 Accuracy: 0.32333767926988266
Delta: 0.004436304809147187 	  Loss: 1.6141046890743787 	 Accuracy: 0.3220338983050847
Delta: 0.0031490263214235133 	  Loss: 1.6143282428419872 	 Accuracy: 0.3220338983050847
Delta: 0.00350091806989632 	  Loss: 1.614050425556211 	 Accuracy: 0.3220338983050847
Delta: 0.0018899152075629601 	  Loss: 1.6146206557639746 	 Accuracy: 0.3220338983050847
Delta: 0.0013135119544604459 	  Loss: 1.6142699810301782 	 Accuracy: 0.3220338983050847
Delta: 0.0023568053252368097 	  Loss: 1.6142953445632031 	 Accuracy: 0.32333767926988266
Delta: 0.0035215381758269986 	  Loss: 1.6140121002660277 	 Accuracy: 0.3220338983050847
Delta: 0.0013681901733820381 	  Loss: 1.6140105089760324 	 Accuracy: 0.3220338983050847
Delta: 0.0021027813911003237 	  Loss: 1.6138992064135311 	 Accuracy: 0.3246414602346806
Delta: 0.004680222524448056 	  Loss: 1.6139062110764217 	 Accuracy: 0.32333767926988266
Delta: 0.003962753620574355 	  Loss: 1.6132646697305477 	 Accuracy: 0.3246414602346806
Delta: 0.00320418184914733 	  Loss: 1.6128307320392583 	 Accuracy: 0.3272490221642764
Delta: 0.0022197751086390984 	  Loss: 1.6124514897664468 	 Accuracy: 0.3246414602346806
Delta: 0.003974059004098363 	  Loss: 1.6124157646646697 	 Accuracy: 0.3272490221642764
Delta: 0.0033737166224767218 	  Loss: 1.6123870679545065 	 Accuracy: 0.32333767926988266
Delta: 0.003751981739166276 	  Loss: 1.6129696923483512 	 Accuracy: 0.32333767926988266
Delta: 0.002991681269119169 	  Loss: 1.6122810007610706 	 Accuracy: 0.3220338983050847
Delta: 0.004224607149730134 	  Loss: 1.6129201641591375 	 Accuracy: 0.3259452411994785
Delta: 0.003983685516823732 	  Loss: 1.6131637635042673 	 Accuracy: 0.32333767926988266
Delta: 0.002792399775189653 	  Loss: 1.6123728936223483 	 Accuracy: 0.32333767926988266
Delta: 0.001230887084654356 	  Loss: 1.6121211295013325 	 Accuracy: 0.3259452411994785
Delta: 0.0034374584239141442 	  Loss: 1.611119162706609 	 Accuracy: 0.3259452411994785
Delta: 0.004290709205118028 	  Loss: 1.6112916931700563 	 Accuracy: 0.32333767926988266
Delta: 0.0024459841886363574 	  Loss: 1.6110227404111175 	 Accuracy: 0.32333767926988266
Delta: 0.0014713344446052976 	  Loss: 1.611234931635351 	 Accuracy: 0.32333767926988266
Delta: 0.0008289378313819879 	  Loss: 1.6116173557646065 	 Accuracy: 0.3259452411994785
Delta: 0.0031838995213758618 	  Loss: 1.6120803406188804 	 Accuracy: 0.32333767926988266
Delta: 0.002587174761748358 	  Loss: 1.612224448080659 	 Accuracy: 0.3259452411994785
Delta: 5.432178308124658e-05 	  Loss: 1.6123253416798318 	 Accuracy: 0.32333767926988266
Delta: 0.003487865077938478 	  Loss: 1.6121094949417845 	 Accuracy: 0.3259452411994785
Delta: 0.003205788499625779 	  Loss: 1.6109585310517534 	 Accuracy: 0.3350717079530639
Delta: 0.0029487786950709934 	  Loss: 1.610995107183157 	 Accuracy: 0.3272490221642764
Delta: 0.0014457826330222033 	  Loss: 1.6111880632872528 	 Accuracy: 0.3259452411994785
Delta: 0.00538282317406043 	  Loss: 1.6111345924761875 	 Accuracy: 0.3246414602346806
Delta: 0.0028248631827829966 	  Loss: 1.6110359426261465 	 Accuracy: 0.3246414602346806
Delta: 6.837546351662476e-05 	  Loss: 1.6111125917551719 	 Accuracy: 0.3246414602346806
Delta: 1.7178593259210326e-05 	  Loss: 1.6110785056833468 	 Accuracy: 0.3246414602346806
Delta: 0.0008832781198192837 	  Loss: 1.6110763522323508 	 Accuracy: 0.32333767926988266
Delta: 0.004472503303844273 	  Loss: 1.6107635690301674 	 Accuracy: 0.3194263363754889
Delta: 0.0031405479705531782 	  Loss: 1.610849584682841 	 Accuracy: 0.3220338983050847
Delta: 0.0028124541645931415 	  Loss: 1.6104797257964996 	 Accuracy: 0.32333767926988266
Delta: 0.0030708807156681816 	  Loss: 1.6105491343714504 	 Accuracy: 0.32333767926988266
Delta: 0.00466825829768664 	  Loss: 1.610688742674744 	 Accuracy: 0.318122555410691
Delta: 0.0013148084112003895 	  Loss: 1.611234068908451 	 Accuracy: 0.3194263363754889
Delta: 0.001661075022113415 	  Loss: 1.6109289156864768 	 Accuracy: 0.3246414602346806
Delta: 0.0019063604961480577 	  Loss: 1.6111309293283036 	 Accuracy: 0.3246414602346806
Delta: 0.002609513257399657 	  Loss: 1.6111627164016675 	 Accuracy: 0.3246414602346806
Delta: 0.00131503796140452 	  Loss: 1.6114883517292604 	 Accuracy: 0.3259452411994785
Delta: 0.0035704844471646383 	  Loss: 1.6112051563024692 	 Accuracy: 0.3246414602346806
Delta: 0.00551378031386871 	  Loss: 1.6113882568890576 	 Accuracy: 0.31681877444589307
Delta: 0.02098370174183912 	  Loss: 2.1569436559316815 	 Accuracy: 0.18383311603650587
Delta: 0.018777133622324294 	  Loss: 2.0684960603689184 	 Accuracy: 0.28292046936114734
Delta: 0.017606456904038507 	  Loss: 1.914721376986854 	 Accuracy: 0.26727509778357234
Delta: 0.015362654679807602 	  Loss: 1.7694806085486503 	 Accuracy: 0.23859191655801826
Delta: 0.013320179880371555 	  Loss: 1.6726801794412989 	 Accuracy: 0.19165580182529335
Delta: 0.011959132048057418 	  Loss: 1.6222381254478493 	 Accuracy: 0.17470664928292046
Delta: 0.009560395848259124 	  Loss: 1.6006801730481235 	 Accuracy: 0.16036505867014342
Delta: 0.00884061138634775 	  Loss: 1.590858915722853 	 Accuracy: 0.16036505867014342
Delta: 0.0075647314902645086 	  Loss: 1.5856461150208097 	 Accuracy: 0.1590612777053455

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006490882986049424 	  Loss: 1.5831416593219325 	 Accuracy: 0.1577574967405476
Delta: 0.005028933643149737 	  Loss: 1.5820475727817582 	 Accuracy: 0.16297262059973924
Delta: 0.003352091954298085 	  Loss: 1.581848012924913 	 Accuracy: 0.15645371577574968
Delta: 0.004679383932792664 	  Loss: 1.5817814091376907 	 Accuracy: 0.1590612777053455
Delta: 0.003878097484457551 	  Loss: 1.5817742087537117 	 Accuracy: 0.1590612777053455
Delta: 0.0021763225695794067 	  Loss: 1.5817880038785717 	 Accuracy: 0.15645371577574968
Delta: 0.0028328726481236417 	  Loss: 1.5818348565195397 	 Accuracy: 0.1577574967405476
Delta: 0.0024215728512227597 	  Loss: 1.5818800443817673 	 Accuracy: 0.15645371577574968
Delta: 0.001117414769931835 	  Loss: 1.5819010764834394 	 Accuracy: 0.15645371577574968
Delta: 0.0019351222718197955 	  Loss: 1.582152351335376 	 Accuracy: 0.15645371577574968
Delta: 4.4126190394309894e-05 	  Loss: 1.58214587698683 	 Accuracy: 0.15645371577574968
Delta: 0.0008050464577013042 	  Loss: 1.582040794427402 	 Accuracy: 0.1577574967405476
Delta: 0.001353541371546929 	  Loss: 1.5820506724629975 	 Accuracy: 0.1577574967405476
Delta: 0.00159110197759061 	  Loss: 1.5819153115512146 	 Accuracy: 0.15645371577574968
Delta: 0.001874824103594261 	  Loss: 1.582100244771294 	 Accuracy: 0.1590612777053455
Delta: 0.0023928821746109184 	  Loss: 1.582048367835902 	 Accuracy: 0.15645371577574968
Delta: 4.872840501390115e-05 	  Loss: 1.5820105169303158 	 Accuracy: 0.15645371577574968
Delta: 0.002155176135998912 	  Loss: 1.582072456074005 	 Accuracy: 0.15645371577574968
Delta: 0.0006592203966830681 	  Loss: 1.582023680440265 	 Accuracy: 0.15645371577574968
Delta: 0.001535003617436744 	  Loss: 1.5820215910766995 	 Accuracy: 0.15645371577574968
Delta: 0.0019852403939783787 	  Loss: 1.5821379044925243 	 Accuracy: 0.15645371577574968
Delta: 6.183720735734683e-05 	  Loss: 1.5820883203552427 	 Accuracy: 0.15645371577574968
Delta: 0.0008890761791766834 	  Loss: 1.582007026096182 	 Accuracy: 0.1577574967405476
Delta: 3.8299453132604004e-05 	  Loss: 1.5820793424885544 	 Accuracy: 0.1577574967405476
Delta: 0.0044976989921076595 	  Loss: 1.5823665212337366 	 Accuracy: 0.1577574967405476
Delta: 0.0026392077689071547 	  Loss: 1.582420001231152 	 Accuracy: 0.15645371577574968
Delta: 0.001021175324421486 	  Loss: 1.5823315725197586 	 Accuracy: 0.15645371577574968
Delta: 0.0020561494741270303 	  Loss: 1.5821368786011174 	 Accuracy: 0.16036505867014342
Delta: 0.004742590719534245 	  Loss: 1.58264243253225 	 Accuracy: 0.1577574967405476
Delta: 0.004227573218528268 	  Loss: 1.5824086967747024 	 Accuracy: 0.1577574967405476
Delta: 0.003261845206571925 	  Loss: 1.5822548347090826 	 Accuracy: 0.15645371577574968
Delta: 2.814377623152687e-05 	  Loss: 1.5822160955327855 	 Accuracy: 0.15123859191655803
Delta: 0.006034043836245894 	  Loss: 1.5833673169784086 	 Accuracy: 0.1590612777053455
Delta: 0.005092662393490289 	  Loss: 1.58309658032652 	 Accuracy: 0.15645371577574968
Delta: 0.001909576863490666 	  Loss: 1.5830771959152758 	 Accuracy: 0.15645371577574968
Delta: 0.003860160270267524 	  Loss: 1.5832137993486166 	 Accuracy: 0.15645371577574968
Delta: 0.001867211858084093 	  Loss: 1.5831462915486323 	 Accuracy: 0.15384615384615385
Delta: 0.002949328622991507 	  Loss: 1.5832896919414252 	 Accuracy: 0.1577574967405476
Delta: 0.0023831410216911602 	  Loss: 1.5829828906629626 	 Accuracy: 0.1577574967405476
Delta: 0.0007921506089947172 	  Loss: 1.5834100582463546 	 Accuracy: 0.15645371577574968
Delta: 0.0005579958013372184 	  Loss: 1.5828436553694778 	 Accuracy: 0.1577574967405476
Delta: 0.002088846277068263 	  Loss: 1.5834241233134514 	 Accuracy: 0.15645371577574968
Delta: 0.002738303921907456 	  Loss: 1.5835905688856873 	 Accuracy: 0.15645371577574968
Delta: 3.030844139167729e-05 	  Loss: 1.5834224758040598 	 Accuracy: 0.1577574967405476
Delta: 0.0013502788600785504 	  Loss: 1.583645484252633 	 Accuracy: 0.1577574967405476
Delta: 0.003081651038200438 	  Loss: 1.583569333412668 	 Accuracy: 0.1590612777053455
Delta: 0.0024795623670216035 	  Loss: 1.583379709580527 	 Accuracy: 0.15645371577574968
Delta: 0.0007424651182989537 	  Loss: 1.583624888925761 	 Accuracy: 0.15645371577574968
Delta: 7.836575706500549e-05 	  Loss: 1.583279982379525 	 Accuracy: 0.15645371577574968
Delta: 2.0473583854655576e-05 	  Loss: 1.583198694473846 	 Accuracy: 0.15645371577574968
Delta: 0.0005561533590818918 	  Loss: 1.5833467880201146 	 Accuracy: 0.15645371577574968
Delta: 5.836852944144808e-05 	  Loss: 1.583559779294355 	 Accuracy: 0.1577574967405476
Delta: 2.7320833168699342e-05 	  Loss: 1.583453190593045 	 Accuracy: 0.15645371577574968
Delta: 2.767846570560255e-05 	  Loss: 1.5835787788549736 	 Accuracy: 0.1577574967405476
Delta: 2.9072136289695227e-05 	  Loss: 1.5836712761174656 	 Accuracy: 0.1577574967405476
Delta: 4.1057536704158746e-05 	  Loss: 1.5836451571054575 	 Accuracy: 0.15384615384615385
Delta: 3.491619065537733e-05 	  Loss: 1.5835544417000031 	 Accuracy: 0.1577574967405476
Delta: 2.342201971468073e-05 	  Loss: 1.5836118568969173 	 Accuracy: 0.1577574967405476
Delta: 0.0023290754850518497 	  Loss: 1.5836994702648992 	 Accuracy: 0.15645371577574968
Delta: 0.0022248919693826797 	  Loss: 1.583896759337111 	 Accuracy: 0.15645371577574968
Delta: 0.0024616318885057062 	  Loss: 1.5837298999439375 	 Accuracy: 0.1590612777053455
Delta: 0.0011211557053732257 	  Loss: 1.5836338501112717 	 Accuracy: 0.1577574967405476
Delta: 0.0029970841219367546 	  Loss: 1.5833214107952749 	 Accuracy: 0.1590612777053455
Delta: 0.002790702589490288 	  Loss: 1.583206896801677 	 Accuracy: 0.1577574967405476
Delta: 0.004290844710024257 	  Loss: 1.582792250545551 	 Accuracy: 0.1577574967405476
Delta: 0.0035345377041466164 	  Loss: 1.5828372783013553 	 Accuracy: 0.17470664928292046
Delta: 0.0030806539209751196 	  Loss: 1.5854195371393187 	 Accuracy: 0.15514993481095177
Delta: 0.0022550958558826737 	  Loss: 1.5830146789180475 	 Accuracy: 0.15645371577574968
Delta: 0.002393037845636357 	  Loss: 1.5837286190912283 	 Accuracy: 0.1577574967405476
Delta: 0.0030434406219305363 	  Loss: 1.5834526062772032 	 Accuracy: 0.1577574967405476
Delta: 0.002859787322645686 	  Loss: 1.5834713697983935 	 Accuracy: 0.15645371577574968
Delta: 0.0019151294162644925 	  Loss: 1.583425660058042 	 Accuracy: 0.1577574967405476
Delta: 0.0030734919823867737 	  Loss: 1.5842469990419987 	 Accuracy: 0.1577574967405476
Delta: 0.003008688916715361 	  Loss: 1.5840292153776812 	 Accuracy: 0.1590612777053455
Delta: 0.003505479676848402 	  Loss: 1.5847037456747781 	 Accuracy: 0.16036505867014342
Delta: 0.003342948048445014 	  Loss: 1.5849486093578538 	 Accuracy: 0.1590612777053455
Delta: 0.005721874072313396 	  Loss: 1.585923899520245 	 Accuracy: 0.16166883963494133
Delta: 0.005264954998625149 	  Loss: 1.5846213317421844 	 Accuracy: 0.1590612777053455
Delta: 0.0027607349708362347 	  Loss: 1.5841591128161525 	 Accuracy: 0.16036505867014342
Delta: 0.0027422373555803102 	  Loss: 1.584677385972697 	 Accuracy: 0.16036505867014342
Delta: 0.002015776690112438 	  Loss: 1.5849916599922838 	 Accuracy: 0.16166883963494133
Delta: 0.0016173075699243645 	  Loss: 1.5849638181467336 	 Accuracy: 0.15384615384615385
Delta: 0.003014639704322848 	  Loss: 1.584541381008055 	 Accuracy: 0.16036505867014342
Delta: 0.0029356809641189223 	  Loss: 1.5851771992481198 	 Accuracy: 0.1577574967405476
Delta: 2.8794159193183306e-05 	  Loss: 1.5851708270119973 	 Accuracy: 0.16036505867014342
Delta: 0.0011269783815098318 	  Loss: 1.585235696565134 	 Accuracy: 0.16036505867014342
Delta: 0.004770675385059032 	  Loss: 1.5865789561623171 	 Accuracy: 0.16036505867014342
Delta: 0.0034250974234222146 	  Loss: 1.5851899655703163 	 Accuracy: 0.16036505867014342
Delta: 0.0006510801452762197 	  Loss: 1.5853354719613848 	 Accuracy: 0.16036505867014342
Delta: 0.0005232556193743558 	  Loss: 1.58525739826763 	 Accuracy: 0.16036505867014342
Delta: 0.0006583991715983367 	  Loss: 1.5851755888640116 	 Accuracy: 0.16297262059973924
Delta: 0.0209547522983594 	  Loss: 2.157367231733285 	 Accuracy: 0.18383311603650587
Delta: 0.018837693276625562 	  Loss: 2.0675981440885307 	 Accuracy: 0.19035202086049544
Delta: 0.01799549570981637 	  Loss: 1.9131099240007774 	 Accuracy: 0.1773142112125163
Delta: 0.016135056583176315 	  Loss: 1.7580002904380294 	 Accuracy: 0.17470664928292046
Delta: 0.013848231858723565 	  Loss: 1.6537616399308663 	 Accuracy: 0.16036505867014342
Delta: 0.0114826229023478 	  Loss: 1.6070479712377637 	 Accuracy: 0.16427640156453716
Delta: 0.009321054541765591 	  Loss: 1.5895444928359024 	 Accuracy: 0.16166883963494133
Delta: 0.007750561948843073 	  Loss: 1.5840824553969959 	 Accuracy: 0.16688396349413298
Delta: 0.006784858241760591 	  Loss: 1.5814177746372646 	 Accuracy: 0.16688396349413298

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005821589407136284 	  Loss: 1.5804167545195367 	 Accuracy: 0.16688396349413298
Delta: 0.0054076619408962735 	  Loss: 1.5799550455825626 	 Accuracy: 0.16688396349413298
Delta: 0.004332754148113627 	  Loss: 1.5797825065756055 	 Accuracy: 0.16688396349413298
Delta: 0.0039447084040586 	  Loss: 1.5796127279370105 	 Accuracy: 0.16688396349413298
Delta: 0.004487897772946279 	  Loss: 1.5796170921035322 	 Accuracy: 0.16558018252933507
Delta: 0.0031360729078232273 	  Loss: 1.5796727953114664 	 Accuracy: 0.16558018252933507
Delta: 0.0027239212957779163 	  Loss: 1.5797289373157284 	 Accuracy: 0.16558018252933507
Delta: 0.002770433993740611 	  Loss: 1.5794112227448882 	 Accuracy: 0.16558018252933507
Delta: 0.002940788700498686 	  Loss: 1.5798542915686438 	 Accuracy: 0.16427640156453716
Delta: 0.002019067624593414 	  Loss: 1.5800837185755636 	 Accuracy: 0.16558018252933507
Delta: 0.0028496605636222395 	  Loss: 1.5797132752931526 	 Accuracy: 0.16558018252933507
Delta: 0.0015747178894891791 	  Loss: 1.580199308857541 	 Accuracy: 0.16558018252933507
Delta: 0.0026948937043806786 	  Loss: 1.579916446832234 	 Accuracy: 0.16558018252933507
Delta: 0.0005394789715598353 	  Loss: 1.5798957856601008 	 Accuracy: 0.16558018252933507
Delta: 0.0015610041000637233 	  Loss: 1.5801287760669926 	 Accuracy: 0.16688396349413298
Delta: 0.0040863025177932276 	  Loss: 1.5802326476523518 	 Accuracy: 0.16558018252933507
Delta: 0.004176810220268621 	  Loss: 1.5796679030469152 	 Accuracy: 0.16558018252933507
Delta: 0.002457592003589335 	  Loss: 1.579502838212381 	 Accuracy: 0.16427640156453716
Delta: 3.196507769320418e-05 	  Loss: 1.5794493085382717 	 Accuracy: 0.16558018252933507
Delta: 0.002783763184047186 	  Loss: 1.5795669897014655 	 Accuracy: 0.16558018252933507
Delta: 0.002852071022071177 	  Loss: 1.5796487728098751 	 Accuracy: 0.16558018252933507
Delta: 0.0013876712772897008 	  Loss: 1.5795137234002241 	 Accuracy: 0.16558018252933507
Delta: 7.383276040305437e-05 	  Loss: 1.579632219661056 	 Accuracy: 0.16427640156453716
Delta: 0.002150237614561807 	  Loss: 1.5798813616080567 	 Accuracy: 0.16558018252933507
Delta: 0.0021006581305230243 	  Loss: 1.5794797565362317 	 Accuracy: 0.16558018252933507
Delta: 0.0026050462624578248 	  Loss: 1.5795422309143736 	 Accuracy: 0.16558018252933507
Delta: 0.0033686112306661447 	  Loss: 1.5796458842425078 	 Accuracy: 0.16558018252933507
Delta: 3.077356030331128e-05 	  Loss: 1.5796603853123983 	 Accuracy: 0.16688396349413298
Delta: 0.0023513920930230926 	  Loss: 1.5796662799247763 	 Accuracy: 0.16558018252933507
Delta: 0.0007952968154461295 	  Loss: 1.5796643179840113 	 Accuracy: 0.16688396349413298
Delta: 0.0019153093037561808 	  Loss: 1.579224294948352 	 Accuracy: 0.1694915254237288
Delta: 0.002786135891807655 	  Loss: 1.5795004042127334 	 Accuracy: 0.16558018252933507
Delta: 0.00061344171520886 	  Loss: 1.5787239579198042 	 Accuracy: 0.16558018252933507
Delta: 0.002126710320668475 	  Loss: 1.5791600283585483 	 Accuracy: 0.16688396349413298
Delta: 5.289471022285816e-05 	  Loss: 1.5794612899021936 	 Accuracy: 0.16688396349413298
Delta: 9.465502934858123e-05 	  Loss: 1.5791683801371508 	 Accuracy: 0.16558018252933507
Delta: 4.9851276175125176e-05 	  Loss: 1.5789377494257688 	 Accuracy: 0.16558018252933507
Delta: 5.3449207575406194e-05 	  Loss: 1.5787976910036963 	 Accuracy: 0.16558018252933507
Delta: 0.002678201560672697 	  Loss: 1.5795985900790894 	 Accuracy: 0.16558018252933507
Delta: 0.0035597356992612965 	  Loss: 1.5794306969555434 	 Accuracy: 0.16036505867014342
Delta: 0.004098202010961356 	  Loss: 1.5798123562179125 	 Accuracy: 0.1681877444589309
Delta: 0.001222170044986906 	  Loss: 1.5801675252993714 	 Accuracy: 0.15384615384615385
Delta: 0.0005519097830405826 	  Loss: 1.5798266637387366 	 Accuracy: 0.16036505867014342
Delta: 0.0010642640213275507 	  Loss: 1.5798200005138128 	 Accuracy: 0.16558018252933507
Delta: 3.139577207259903e-05 	  Loss: 1.5798100618444681 	 Accuracy: 0.16688396349413298
Delta: 0.0033589251869267827 	  Loss: 1.579923051248017 	 Accuracy: 0.16297262059973924
Delta: 0.0018787093454934458 	  Loss: 1.5798542606863544 	 Accuracy: 0.16558018252933507
Delta: 0.004040452795064534 	  Loss: 1.5800162234490913 	 Accuracy: 0.16558018252933507
Delta: 0.0030531766076947043 	  Loss: 1.579597157702632 	 Accuracy: 0.16558018252933507
Delta: 4.875034966369915e-05 	  Loss: 1.5797313981853258 	 Accuracy: 0.16558018252933507
Delta: 0.0020945865270406315 	  Loss: 1.579961502593245 	 Accuracy: 0.16558018252933507
Delta: 0.0031725619352782003 	  Loss: 1.580062817987089 	 Accuracy: 0.16558018252933507
Delta: 7.215433194620606e-05 	  Loss: 1.580272200970166 	 Accuracy: 0.16558018252933507
Delta: 0.004991231195541263 	  Loss: 1.5790024711071284 	 Accuracy: 0.16688396349413298
Delta: 0.0038593717647352585 	  Loss: 1.57972868177343 	 Accuracy: 0.16688396349413298
Delta: 0.0037839704986916273 	  Loss: 1.578935139897991 	 Accuracy: 0.16688396349413298
Delta: 0.0030454819415314713 	  Loss: 1.5791425913119541 	 Accuracy: 0.1681877444589309
Delta: 0.0012338627541836518 	  Loss: 1.5792057391071106 	 Accuracy: 0.16688396349413298
Delta: 0.002325966581726458 	  Loss: 1.5792127203745783 	 Accuracy: 0.16688396349413298
Delta: 0.000570513693599954 	  Loss: 1.57906148781792 	 Accuracy: 0.16688396349413298
Delta: 8.508474029934645e-06 	  Loss: 1.5790713506361245 	 Accuracy: 0.16558018252933507
Delta: 0.0020965760997799544 	  Loss: 1.5794056883011898 	 Accuracy: 0.16688396349413298
Delta: 0.003408926878654461 	  Loss: 1.5798879273111726 	 Accuracy: 0.16688396349413298
Delta: 0.00338279952156233 	  Loss: 1.5790710859864814 	 Accuracy: 0.16688396349413298
Delta: 0.0041582633493467015 	  Loss: 1.5810024598049628 	 Accuracy: 0.1681877444589309
Delta: 0.002318249870569092 	  Loss: 1.5807465403987369 	 Accuracy: 0.1681877444589309
Delta: 0.0005667910884388674 	  Loss: 1.5805567962823812 	 Accuracy: 0.1681877444589309
Delta: 0.00104619856647702 	  Loss: 1.5805670616110277 	 Accuracy: 0.16688396349413298
Delta: 0.0041242790881850485 	  Loss: 1.5789373688257982 	 Accuracy: 0.16688396349413298
Delta: 0.002537433598105133 	  Loss: 1.578962143730343 	 Accuracy: 0.16688396349413298
Delta: 3.147694452074217e-05 	  Loss: 1.5789145872739003 	 Accuracy: 0.1681877444589309
Delta: 0.0005665045997812548 	  Loss: 1.5788574778973703 	 Accuracy: 0.16688396349413298
Delta: 0.004346542952911903 	  Loss: 1.5792447767889932 	 Accuracy: 0.16688396349413298
Delta: 0.003787306472769618 	  Loss: 1.5790469986539357 	 Accuracy: 0.16688396349413298
Delta: 0.0009156988982049633 	  Loss: 1.5789188478114193 	 Accuracy: 0.16688396349413298
Delta: 0.00313592521042541 	  Loss: 1.5789185014000722 	 Accuracy: 0.16166883963494133
Delta: 0.0028962594430827536 	  Loss: 1.579040130715395 	 Accuracy: 0.16558018252933507
Delta: 0.003932351839878294 	  Loss: 1.5788809716326297 	 Accuracy: 0.16688396349413298
Delta: 0.0036417501794926894 	  Loss: 1.579408696870085 	 Accuracy: 0.16688396349413298
Delta: 0.0012350411252678732 	  Loss: 1.579493963782012 	 Accuracy: 0.16688396349413298
Delta: 0.00227483925875872 	  Loss: 1.579453095203296 	 Accuracy: 0.16688396349413298
Delta: 0.002798456255407658 	  Loss: 1.5792331543338447 	 Accuracy: 0.16688396349413298
Delta: 0.002754619226973544 	  Loss: 1.5795385261750614 	 Accuracy: 0.16558018252933507
Delta: 0.001977107815398243 	  Loss: 1.5797975761449061 	 Accuracy: 0.16688396349413298
Delta: 0.0023015104565499048 	  Loss: 1.5797190073410559 	 Accuracy: 0.16558018252933507
Delta: 0.0011460551259419591 	  Loss: 1.5796548795126006 	 Accuracy: 0.16688396349413298
Delta: 0.003104213963767209 	  Loss: 1.5794315459019295 	 Accuracy: 0.16558018252933507
Delta: 0.00503635352485727 	  Loss: 1.5791764787464349 	 Accuracy: 0.16558018252933507
Delta: 0.0046921575837709385 	  Loss: 1.5789288798392533 	 Accuracy: 0.16558018252933507
Delta: 0.0012822413827991495 	  Loss: 1.578895794804195 	 Accuracy: 0.16558018252933507
Delta: 5.74690531669618e-07 	  Loss: 1.578895765733371 	 Accuracy: 0.16558018252933507
converged at iter  99
Delta: 0.020985633907100912 	  Loss: 2.1575539863512425 	 Accuracy: 0.18904823989569752
Delta: 0.01840526429330071 	  Loss: 2.068651433245969 	 Accuracy: 0.24511082138200782
Delta: 0.01772759407484669 	  Loss: 1.9174189368662584 	 Accuracy: 0.2607561929595828
Delta: 0.016220121121568246 	  Loss: 1.7784131976769575 	 Accuracy: 0.2529335071707953
Delta: 0.0150235238558998 	  Loss: 1.675931276948367 	 Accuracy: 0.22816166883963493
Delta: 0.011895825460590134 	  Loss: 1.6194051928706332 	 Accuracy: 0.21121251629726207
Delta: 0.009257569301601976 	  Loss: 1.5963143249482523 	 Accuracy: 0.20208604954367665
Delta: 0.007356560245718383 	  Loss: 1.5892142338803017 	 Accuracy: 0.1864406779661017

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005815804715461789 	  Loss: 1.5863821984574282 	 Accuracy: 0.1864406779661017
Delta: 0.0051506080174328756 	  Loss: 1.5861120628659262 	 Accuracy: 0.1877444589308996
Delta: 0.0044371937607583295 	  Loss: 1.5859914940769682 	 Accuracy: 0.18383311603650587
Delta: 0.0030451806200421892 	  Loss: 1.5856798157830725 	 Accuracy: 0.18904823989569752
Delta: 0.004149265934848119 	  Loss: 1.585884985461554 	 Accuracy: 0.18513689700130379
Delta: 0.002570491670508509 	  Loss: 1.585714764057474 	 Accuracy: 0.18904823989569752
Delta: 0.0022830870692057024 	  Loss: 1.5856300132265604 	 Accuracy: 0.1877444589308996
Delta: 0.002882741368546651 	  Loss: 1.585436899729373 	 Accuracy: 0.19295958279009126
Delta: 0.0013218422519797402 	  Loss: 1.585363338394086 	 Accuracy: 0.1877444589308996
Delta: 0.0019215617416781568 	  Loss: 1.5852614708270432 	 Accuracy: 0.1877444589308996
Delta: 0.0012311375000718995 	  Loss: 1.585330226812808 	 Accuracy: 0.1877444589308996
Delta: 0.0011203701703606103 	  Loss: 1.5852633278990143 	 Accuracy: 0.1864406779661017
Delta: 0.0005145291740953706 	  Loss: 1.5852540774510753 	 Accuracy: 0.1864406779661017
Delta: 1.894953367678643e-05 	  Loss: 1.5852769013291574 	 Accuracy: 0.1877444589308996
Delta: 0.002103319752006689 	  Loss: 1.5853789500026076 	 Accuracy: 0.1864406779661017
Delta: 0.0013270953626327675 	  Loss: 1.5852491430685478 	 Accuracy: 0.1864406779661017
Delta: 1.4302185666183131e-05 	  Loss: 1.5852289178684298 	 Accuracy: 0.1864406779661017
Delta: 1.3636859317469063e-05 	  Loss: 1.5852226417211641 	 Accuracy: 0.1877444589308996
Delta: 2.7207239495583513e-05 	  Loss: 1.5851801219420236 	 Accuracy: 0.1864406779661017
Delta: 2.3967748574504104e-05 	  Loss: 1.5852597657981509 	 Accuracy: 0.1877444589308996
Delta: 0.0015902476288742167 	  Loss: 1.5855674870544152 	 Accuracy: 0.1864406779661017
Delta: 1.868880237345254e-05 	  Loss: 1.58563082055055 	 Accuracy: 0.1864406779661017
Delta: 2.8151634738487616e-05 	  Loss: 1.58562806248228 	 Accuracy: 0.18904823989569752
Delta: 3.903434186864758e-05 	  Loss: 1.585677618237285 	 Accuracy: 0.1864406779661017
Delta: 0.0019440488636488834 	  Loss: 1.5857432595015477 	 Accuracy: 0.1864406779661017
Delta: 0.0018060889170528841 	  Loss: 1.5856068073543272 	 Accuracy: 0.1864406779661017
Delta: 0.0021124303197406252 	  Loss: 1.5853728825124374 	 Accuracy: 0.1864406779661017
Delta: 0.0038238690006076 	  Loss: 1.5859359706761422 	 Accuracy: 0.1877444589308996
Delta: 0.0019263529897953994 	  Loss: 1.5857594516941382 	 Accuracy: 0.1864406779661017
Delta: 0.0007928220823094869 	  Loss: 1.585731192561846 	 Accuracy: 0.1864406779661017
Delta: 0.0009662714183683184 	  Loss: 1.5861169323654927 	 Accuracy: 0.1864406779661017
Delta: 0.002363918699477055 	  Loss: 1.5852003180325394 	 Accuracy: 0.1864406779661017
Delta: 0.004353590308240384 	  Loss: 1.5855288524713642 	 Accuracy: 0.1864406779661017
Delta: 0.0036629337123939764 	  Loss: 1.5865882542581424 	 Accuracy: 0.1864406779661017
Delta: 0.0015676067206213148 	  Loss: 1.5860815504773833 	 Accuracy: 0.18904823989569752
Delta: 0.0027068691322696603 	  Loss: 1.5857940966959863 	 Accuracy: 0.1864406779661017
Delta: 0.0010603696335197475 	  Loss: 1.585765146159595 	 Accuracy: 0.1864406779661017
Delta: 0.0011367791238139204 	  Loss: 1.5859868975331473 	 Accuracy: 0.1864406779661017
Delta: 0.0005330916081031787 	  Loss: 1.5857899805698086 	 Accuracy: 0.1864406779661017
Delta: 0.0022860349782088457 	  Loss: 1.5866689188693741 	 Accuracy: 0.18513689700130379
Delta: 0.0022473035811954776 	  Loss: 1.5857669851339102 	 Accuracy: 0.1864406779661017
Delta: 0.004085883995821579 	  Loss: 1.5852783047378876 	 Accuracy: 0.1864406779661017
Delta: 0.0010223617752094306 	  Loss: 1.585158078354705 	 Accuracy: 0.18904823989569752
Delta: 0.005587755948810131 	  Loss: 1.5853902654683723 	 Accuracy: 0.1864406779661017
Delta: 0.004865507229606924 	  Loss: 1.5848399954249641 	 Accuracy: 0.18904823989569752
Delta: 0.004277591009532535 	  Loss: 1.5852268083891998 	 Accuracy: 0.19035202086049544
Delta: 0.0032726034551254315 	  Loss: 1.5848407907962578 	 Accuracy: 0.19165580182529335
Delta: 0.0016975142987704765 	  Loss: 1.5848813974790374 	 Accuracy: 0.19035202086049544
Delta: 0.0023994909455188223 	  Loss: 1.5853277787717694 	 Accuracy: 0.19035202086049544
Delta: 0.003580837767750029 	  Loss: 1.5851294990611087 	 Accuracy: 0.19035202086049544
Delta: 0.0028670513545465243 	  Loss: 1.58553853031622 	 Accuracy: 0.18904823989569752
Delta: 0.004164528733370429 	  Loss: 1.5861743912614807 	 Accuracy: 0.18904823989569752
Delta: 0.005014568888214254 	  Loss: 1.5842720512487505 	 Accuracy: 0.19295958279009126
Delta: 0.003269256927903191 	  Loss: 1.5834024472094468 	 Accuracy: 0.1864406779661017
Delta: 0.0032090570143809513 	  Loss: 1.5839373158197931 	 Accuracy: 0.18904823989569752
Delta: 0.0029762042342539046 	  Loss: 1.584137532248156 	 Accuracy: 0.18904823989569752
Delta: 0.003356432187294076 	  Loss: 1.58399394511575 	 Accuracy: 0.18904823989569752
Delta: 0.002689844510585594 	  Loss: 1.5842478122960575 	 Accuracy: 0.19035202086049544
Delta: 0.003293376564916863 	  Loss: 1.5837342353158572 	 Accuracy: 0.18904823989569752
Delta: 0.0034086572563111466 	  Loss: 1.583985137682069 	 Accuracy: 0.18904823989569752
Delta: 0.001465802131703383 	  Loss: 1.5843192073652932 	 Accuracy: 0.18904823989569752
Delta: 0.0050191365326626505 	  Loss: 1.5845205972739596 	 Accuracy: 0.1877444589308996
Delta: 0.0022960559689468034 	  Loss: 1.5843439593189887 	 Accuracy: 0.1877444589308996
Delta: 0.0015176591503605205 	  Loss: 1.5843396749941214 	 Accuracy: 0.18904823989569752
Delta: 2.2417164175719452e-05 	  Loss: 1.5843283610639878 	 Accuracy: 0.1864406779661017
Delta: 0.002617431311520486 	  Loss: 1.584531143502274 	 Accuracy: 0.1877444589308996
Delta: 0.0011932827549 	  Loss: 1.5846920744699045 	 Accuracy: 0.1877444589308996
Delta: 0.0025250616464856054 	  Loss: 1.5847583001577288 	 Accuracy: 0.1877444589308996
Delta: 0.002329696852262687 	  Loss: 1.5849779495176182 	 Accuracy: 0.1877444589308996
Delta: 0.00240656495483073 	  Loss: 1.585398073040171 	 Accuracy: 0.1877444589308996
Delta: 0.0030363380084985183 	  Loss: 1.5848436605917258 	 Accuracy: 0.1877444589308996
Delta: 0.0015535839951898226 	  Loss: 1.5855579291119657 	 Accuracy: 0.18513689700130379
Delta: 9.9124088801855e-05 	  Loss: 1.5849195010526613 	 Accuracy: 0.18904823989569752
Delta: 0.0016611004907011288 	  Loss: 1.5849980344134351 	 Accuracy: 0.1864406779661017
Delta: 4.8217868633371465e-05 	  Loss: 1.5852437994599509 	 Accuracy: 0.19295958279009126
Delta: 0.003224951594903007 	  Loss: 1.5861658670429448 	 Accuracy: 0.1877444589308996
Delta: 0.0038582095026099884 	  Loss: 1.5865558869445657 	 Accuracy: 0.1864406779661017
Delta: 0.0019284427643640623 	  Loss: 1.5862188416366338 	 Accuracy: 0.1864406779661017
Delta: 0.0029787607764823983 	  Loss: 1.5868879238259606 	 Accuracy: 0.1864406779661017
Delta: 0.0007367993034217937 	  Loss: 1.5870531490399689 	 Accuracy: 0.1864406779661017
Delta: 0.0032781795298695167 	  Loss: 1.586296521919633 	 Accuracy: 0.1864406779661017
Delta: 0.0016318527369132124 	  Loss: 1.5868541591504493 	 Accuracy: 0.19035202086049544
Delta: 0.002908070055749741 	  Loss: 1.5871722101414134 	 Accuracy: 0.1877444589308996
Delta: 0.004731386671066087 	  Loss: 1.5861103349086214 	 Accuracy: 0.1877444589308996
Delta: 0.0030139723999050017 	  Loss: 1.5854313857030824 	 Accuracy: 0.1877444589308996
Delta: 0.004538929717471176 	  Loss: 1.5856189693135965 	 Accuracy: 0.1864406779661017
Delta: 0.00383635274248483 	  Loss: 1.5859728057533145 	 Accuracy: 0.1864406779661017
Delta: 0.00198005414236995 	  Loss: 1.5853164865639364 	 Accuracy: 0.18513689700130379
Delta: 0.0031338107351089684 	  Loss: 1.5862597743054243 	 Accuracy: 0.1864406779661017
Delta: 0.003115218911567481 	  Loss: 1.5853131503439473 	 Accuracy: 0.1864406779661017
Delta: 0.0011484160906203957 	  Loss: 1.5859915226948842 	 Accuracy: 0.1864406779661017
Delta: 0.0053392664628122925 	  Loss: 1.5849813401736208 	 Accuracy: 0.19035202086049544
Delta: 0.02110045072306722 	  Loss: 2.1570379593474285 	 Accuracy: 0.2138200782268579
Delta: 0.018711156408865944 	  Loss: 2.0617831176884844 	 Accuracy: 0.3194263363754889
Delta: 0.01826082115555174 	  Loss: 1.889864462551976 	 Accuracy: 0.42503259452411996
Delta: 0.015985076764976177 	  Loss: 1.7245307214651167 	 Accuracy: 0.38070404172099087
Delta: 0.013019440274212805 	  Loss: 1.6433434971586374 	 Accuracy: 0.379400260756193
Delta: 0.010311727931903497 	  Loss: 1.6120172005444795 	 Accuracy: 0.37809647979139505
Delta: 0.008380806202404228 	  Loss: 1.602335218243212 	 Accuracy: 0.3663624511082138

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006820527191393647 	  Loss: 1.59987189549424 	 Accuracy: 0.37157757496740546
Delta: 0.0053035987553272795 	  Loss: 1.599065598055343 	 Accuracy: 0.3767926988265971
Delta: 0.003828380982870446 	  Loss: 1.5987784372856926 	 Accuracy: 0.3728813559322034
Delta: 0.003759078439683339 	  Loss: 1.598912919354764 	 Accuracy: 0.37027379400260757
Delta: 0.004211043294418453 	  Loss: 1.5990622421026521 	 Accuracy: 0.3728813559322034
Delta: 0.002027671457416374 	  Loss: 1.5991427188449827 	 Accuracy: 0.37157757496740546
Delta: 0.0008970753408373268 	  Loss: 1.5990729667179915 	 Accuracy: 0.3728813559322034
Delta: 0.0029095913182672615 	  Loss: 1.598969598593639 	 Accuracy: 0.37157757496740546
Delta: 0.0008852529339269757 	  Loss: 1.5991492067731334 	 Accuracy: 0.37027379400260757
Delta: 2.0005748933432797e-05 	  Loss: 1.5991441452372956 	 Accuracy: 0.37157757496740546
Delta: 2.459822395699733e-05 	  Loss: 1.5991663823624445 	 Accuracy: 0.37027379400260757
Delta: 1.286739527944668e-05 	  Loss: 1.5991395783756293 	 Accuracy: 0.37027379400260757
Delta: 2.4373739786280743e-05 	  Loss: 1.5992118198192191 	 Accuracy: 0.37157757496740546
Delta: 1.2180439896214383e-05 	  Loss: 1.5992103900672436 	 Accuracy: 0.37027379400260757
Delta: 3.3138331707261255e-05 	  Loss: 1.5991552959079485 	 Accuracy: 0.37027379400260757
Delta: 3.258607545546194e-05 	  Loss: 1.5992038995529736 	 Accuracy: 0.37157757496740546
Delta: 0.002939071728815817 	  Loss: 1.5994174902028218 	 Accuracy: 0.3728813559322034
Delta: 0.002643715470286906 	  Loss: 1.599266239277252 	 Accuracy: 0.37027379400260757
Delta: 4.6072012484147785e-05 	  Loss: 1.5993253735644248 	 Accuracy: 0.37027379400260757
Delta: 0.0014126863912426618 	  Loss: 1.599400274385877 	 Accuracy: 0.37027379400260757
Delta: 0.002113808320397559 	  Loss: 1.5993516328718644 	 Accuracy: 0.36897001303780963
Delta: 0.0007181610907023922 	  Loss: 1.5996082910672307 	 Accuracy: 0.37157757496740546
Delta: 0.001520821812221045 	  Loss: 1.5991975306116224 	 Accuracy: 0.3728813559322034
Delta: 0.0028543535062521474 	  Loss: 1.599971704516443 	 Accuracy: 0.37027379400260757
Delta: 0.0022047038086044635 	  Loss: 1.599056608437638 	 Accuracy: 0.37027379400260757
Delta: 0.002076790612730544 	  Loss: 1.5992984971940962 	 Accuracy: 0.37157757496740546
Delta: 0.002998273721043923 	  Loss: 1.5992795451486104 	 Accuracy: 0.37157757496740546
Delta: 0.0022677330449663103 	  Loss: 1.599223115945784 	 Accuracy: 0.37027379400260757
Delta: 6.512298048936435e-05 	  Loss: 1.5992531407944028 	 Accuracy: 0.37157757496740546
Delta: 1.1842321854403936e-05 	  Loss: 1.5992524684519265 	 Accuracy: 0.3728813559322034
Delta: 0.0023509409861610557 	  Loss: 1.5993452332457627 	 Accuracy: 0.37027379400260757
Delta: 0.002372787535355244 	  Loss: 1.599179231330989 	 Accuracy: 0.37027379400260757
Delta: 0.002185486207889555 	  Loss: 1.5994005830313782 	 Accuracy: 0.37027379400260757
Delta: 0.001598388910152276 	  Loss: 1.5993677203461862 	 Accuracy: 0.36897001303780963
Delta: 0.0009551464651023007 	  Loss: 1.5994062359544077 	 Accuracy: 0.37027379400260757
Delta: 0.0018161472431611758 	  Loss: 1.5992812126609108 	 Accuracy: 0.37157757496740546
Delta: 0.0011800096369659926 	  Loss: 1.5993548137519396 	 Accuracy: 0.37157757496740546
Delta: 0.002515113751689706 	  Loss: 1.5992535177188125 	 Accuracy: 0.37157757496740546
Delta: 0.0009288484994951781 	  Loss: 1.599203687949712 	 Accuracy: 0.37157757496740546
Delta: 0.002329150228185226 	  Loss: 1.5990985489640155 	 Accuracy: 0.379400260756193
Delta: 0.0014152002652783055 	  Loss: 1.5993355781334988 	 Accuracy: 0.3728813559322034
Delta: 0.003695725227963458 	  Loss: 1.5994413638401335 	 Accuracy: 0.37157757496740546
Delta: 0.0022438036762002043 	  Loss: 1.5992096281787538 	 Accuracy: 0.363754889178618
Delta: 0.0035849427105546943 	  Loss: 1.5993276627462094 	 Accuracy: 0.3728813559322034
Delta: 0.003015179957679877 	  Loss: 1.5994311532582985 	 Accuracy: 0.37157757496740546
Delta: 4.677136221519029e-05 	  Loss: 1.5994194589870272 	 Accuracy: 0.37027379400260757
Delta: 0.0037363159449144093 	  Loss: 1.599177236245829 	 Accuracy: 0.37027379400260757
Delta: 0.0035655660435575027 	  Loss: 1.5989371841445812 	 Accuracy: 0.36897001303780963
Delta: 0.00474177596627885 	  Loss: 1.599037484699716 	 Accuracy: 0.37157757496740546
Delta: 0.0021646811945793586 	  Loss: 1.5989017490576698 	 Accuracy: 0.36897001303780963
Delta: 0.0017779455351375738 	  Loss: 1.5991339559547841 	 Accuracy: 0.37027379400260757
Delta: 0.0037351794679912225 	  Loss: 1.5986691475880188 	 Accuracy: 0.37027379400260757
Delta: 0.0041571083014608715 	  Loss: 1.599045492007394 	 Accuracy: 0.37027379400260757
Delta: 0.004478739277905409 	  Loss: 1.5990175340683748 	 Accuracy: 0.37027379400260757
Delta: 0.0014138723636799768 	  Loss: 1.5991402228669092 	 Accuracy: 0.37027379400260757
Delta: 0.002701569346628016 	  Loss: 1.5988472185861098 	 Accuracy: 0.37027379400260757
Delta: 0.0010033475892574657 	  Loss: 1.5988492407375854 	 Accuracy: 0.36766623207301175
Delta: 1.2124947656469394e-05 	  Loss: 1.598849051543791 	 Accuracy: 0.36897001303780963
Delta: 0.0020842517284985025 	  Loss: 1.5989289352699978 	 Accuracy: 0.37027379400260757
Delta: 0.0009509473317446861 	  Loss: 1.5988870697297988 	 Accuracy: 0.36766623207301175
Delta: 0.0018720911135265317 	  Loss: 1.5987548310625672 	 Accuracy: 0.3767926988265971
Delta: 0.001299268155640102 	  Loss: 1.5988143555616845 	 Accuracy: 0.37027379400260757
Delta: 0.001211449944379368 	  Loss: 1.599501274962282 	 Accuracy: 0.36766623207301175
Delta: 0.004883941469838676 	  Loss: 1.6003128447701118 	 Accuracy: 0.3741851368970013
Delta: 0.005482812881259877 	  Loss: 1.6017291195578924 	 Accuracy: 0.37157757496740546
Delta: 0.0011156519413930864 	  Loss: 1.601694332714557 	 Accuracy: 0.37027379400260757
Delta: 0.004127710009286936 	  Loss: 1.6014493469541577 	 Accuracy: 0.36897001303780963
Delta: 0.004550120589502838 	  Loss: 1.6016548101439532 	 Accuracy: 0.37027379400260757
Delta: 0.00451830840873117 	  Loss: 1.6030205705148797 	 Accuracy: 0.36897001303780963
Delta: 0.003178991038534052 	  Loss: 1.6017947134624553 	 Accuracy: 0.3650586701434159
Delta: 0.0029964531106868317 	  Loss: 1.601675422120746 	 Accuracy: 0.36897001303780963
Delta: 0.0040943965332016306 	  Loss: 1.603269633638795 	 Accuracy: 0.36897001303780963
Delta: 0.002224804220016758 	  Loss: 1.6031995254757385 	 Accuracy: 0.36897001303780963
Delta: 0.003030720950543925 	  Loss: 1.602388332866184 	 Accuracy: 0.36766623207301175
Delta: 0.0019421949052265389 	  Loss: 1.6023955748609016 	 Accuracy: 0.36897001303780963
Delta: 0.0015304105615602558 	  Loss: 1.6028497844540044 	 Accuracy: 0.36897001303780963
Delta: 0.0017943961572568473 	  Loss: 1.6026638742494352 	 Accuracy: 0.36897001303780963
Delta: 0.0011832845404956159 	  Loss: 1.6023022887176812 	 Accuracy: 0.3728813559322034
Delta: 0.004292961084554173 	  Loss: 1.6022021081856774 	 Accuracy: 0.37027379400260757
Delta: 0.0037301102751279964 	  Loss: 1.6023318106284778 	 Accuracy: 0.36766623207301175
Delta: 0.003384624370644822 	  Loss: 1.6022728193118378 	 Accuracy: 0.36897001303780963
Delta: 0.0021615655973070617 	  Loss: 1.6023469752878747 	 Accuracy: 0.37027379400260757
Delta: 2.7662668662136576e-05 	  Loss: 1.6023749653060184 	 Accuracy: 0.3650586701434159
Delta: 0.0022827104137746034 	  Loss: 1.6020911492192416 	 Accuracy: 0.37157757496740546
Delta: 0.004745599286616702 	  Loss: 1.6020015889789718 	 Accuracy: 0.37157757496740546
Delta: 0.0016597721539795688 	  Loss: 1.6018781178000374 	 Accuracy: 0.3663624511082138
Delta: 0.003495109477969607 	  Loss: 1.601740033447139 	 Accuracy: 0.37027379400260757
Delta: 0.0008982890352786305 	  Loss: 1.6016684660534393 	 Accuracy: 0.37157757496740546
Delta: 0.001619394917577716 	  Loss: 1.6017947612644807 	 Accuracy: 0.36897001303780963
Delta: 0.0011540064459830658 	  Loss: 1.602104023116604 	 Accuracy: 0.37157757496740546
Delta: 0.00465163269975147 	  Loss: 1.6025906957879694 	 Accuracy: 0.36897001303780963
Delta: 0.003218401698805835 	  Loss: 1.6022934442921541 	 Accuracy: 0.36897001303780963
Delta: 1.6686460685989793e-05 	  Loss: 1.6023029661783106 	 Accuracy: 0.3741851368970013
Delta: 0.02102738831666213 	  Loss: 2.157738081238392 	 Accuracy: 0.20860495436766624
Delta: 0.018533572919704467 	  Loss: 2.0636157051513715 	 Accuracy: 0.27509778357235987
Delta: 0.017714653446789633 	  Loss: 1.9054746631734023 	 Accuracy: 0.3050847457627119
Delta: 0.016388817252376318 	  Loss: 1.7524488112192182 	 Accuracy: 0.3194263363754889
Delta: 0.01372676534611295 	  Loss: 1.6649689725209078 	 Accuracy: 0.31290743155149936
Delta: 0.01083015903669283 	  Loss: 1.6266684894082926 	 Accuracy: 0.3011734028683181
Delta: 0.00872918021638557 	  Loss: 1.6145750559128524 	 Accuracy: 0.3011734028683181

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006345467174948013 	  Loss: 1.6115368836037598 	 Accuracy: 0.3011734028683181
Delta: 0.0054289123393462075 	  Loss: 1.610819410745065 	 Accuracy: 0.30247718383311606
Delta: 0.005386634710732788 	  Loss: 1.6107229480254197 	 Accuracy: 0.30247718383311606
Delta: 0.0039479236365153585 	  Loss: 1.6106907117864153 	 Accuracy: 0.3011734028683181
Delta: 0.003259923385371524 	  Loss: 1.6108486987625574 	 Accuracy: 0.3011734028683181
Delta: 0.0021015392945486914 	  Loss: 1.610582946682952 	 Accuracy: 0.30247718383311606
Delta: 0.003883954869687077 	  Loss: 1.6112398216115225 	 Accuracy: 0.30247718383311606
Delta: 0.0031899415188470434 	  Loss: 1.6111367461050774 	 Accuracy: 0.30378096479791394
Delta: 6.258917789618793e-05 	  Loss: 1.6110267007603138 	 Accuracy: 0.3011734028683181
Delta: 0.00402712379568839 	  Loss: 1.6110983519263473 	 Accuracy: 0.30247718383311606
Delta: 0.003982293485827835 	  Loss: 1.6112089354301722 	 Accuracy: 0.3011734028683181
Delta: 0.001672385496648152 	  Loss: 1.611493742741636 	 Accuracy: 0.30247718383311606
Delta: 0.003465893777406765 	  Loss: 1.6112273833751405 	 Accuracy: 0.29986962190352023
Delta: 0.002192388253490766 	  Loss: 1.611264395294022 	 Accuracy: 0.29986962190352023
Delta: 0.0018142360336075771 	  Loss: 1.6108950645665758 	 Accuracy: 0.3011734028683181
Delta: 7.81549802242388e-05 	  Loss: 1.610923793324222 	 Accuracy: 0.3011734028683181
Delta: 0.0014532242303910608 	  Loss: 1.6108737881482211 	 Accuracy: 0.30378096479791394
Delta: 0.002706823552371799 	  Loss: 1.6107601441052988 	 Accuracy: 0.3011734028683181
Delta: 0.002270575272286229 	  Loss: 1.6108797333867888 	 Accuracy: 0.29465449804432853
Delta: 0.0013948250988130304 	  Loss: 1.6109361052475881 	 Accuracy: 0.29986962190352023
Delta: 0.001069267487608822 	  Loss: 1.6109142768380176 	 Accuracy: 0.30378096479791394
Delta: 0.0005659263657355844 	  Loss: 1.6108480381575982 	 Accuracy: 0.30247718383311606
Delta: 0.0005882101252985575 	  Loss: 1.6112589979653722 	 Accuracy: 0.30247718383311606
Delta: 0.003934368954004778 	  Loss: 1.610801811569792 	 Accuracy: 0.3011734028683181
Delta: 0.0031332779129470854 	  Loss: 1.6113308178897094 	 Accuracy: 0.30247718383311606
Delta: 0.002835112396186123 	  Loss: 1.611118737578774 	 Accuracy: 0.30247718383311606
Delta: 0.0016940460724466063 	  Loss: 1.6116059925547408 	 Accuracy: 0.30378096479791394
Delta: 0.0031170330089974503 	  Loss: 1.6109833301404906 	 Accuracy: 0.30378096479791394
Delta: 0.003910740280748696 	  Loss: 1.6105371097342944 	 Accuracy: 0.30378096479791394
Delta: 0.0014708180661363846 	  Loss: 1.6108339299902699 	 Accuracy: 0.30378096479791394
Delta: 0.0013595311520113158 	  Loss: 1.6110859393006578 	 Accuracy: 0.3050847457627119
Delta: 0.0005553213313861377 	  Loss: 1.6111295356754107 	 Accuracy: 0.3050847457627119
Delta: 2.1642368416586315e-05 	  Loss: 1.6111486001214705 	 Accuracy: 0.30247718383311606
Delta: 0.0007871697706133816 	  Loss: 1.6108422101052604 	 Accuracy: 0.30378096479791394
Delta: 0.0022870478294840036 	  Loss: 1.6107482767056094 	 Accuracy: 0.30378096479791394
Delta: 0.0009462309544531555 	  Loss: 1.6108367110690445 	 Accuracy: 0.30378096479791394
Delta: 0.0026760004726581466 	  Loss: 1.6108603028691406 	 Accuracy: 0.30247718383311606
Delta: 0.0014766595461995883 	  Loss: 1.610950175926003 	 Accuracy: 0.30247718383311606
Delta: 0.0008969776887399307 	  Loss: 1.6110127341997944 	 Accuracy: 0.30378096479791394
Delta: 0.0028131862262827535 	  Loss: 1.6110109935568704 	 Accuracy: 0.30247718383311606
Delta: 0.003827875640860595 	  Loss: 1.6107973909711935 	 Accuracy: 0.30247718383311606
Delta: 4.74871811794847e-05 	  Loss: 1.6106943750235205 	 Accuracy: 0.30247718383311606
Delta: 3.6870754622301696e-05 	  Loss: 1.6108047193083919 	 Accuracy: 0.30247718383311606
Delta: 0.0018858415305396767 	  Loss: 1.6109490571636114 	 Accuracy: 0.30247718383311606
Delta: 0.001434012638189055 	  Loss: 1.6103010692890622 	 Accuracy: 0.30378096479791394
Delta: 0.0029944529690557613 	  Loss: 1.6102487654602795 	 Accuracy: 0.29726205997392435
Delta: 0.0005399441685700388 	  Loss: 1.6102752150073782 	 Accuracy: 0.30247718383311606
Delta: 0.0017575291870327876 	  Loss: 1.610517898885372 	 Accuracy: 0.30378096479791394
Delta: 0.0019234653043349128 	  Loss: 1.6107435191302268 	 Accuracy: 0.30378096479791394
Delta: 0.0009552841881192809 	  Loss: 1.6106468362452462 	 Accuracy: 0.30247718383311606
Delta: 0.003549096945283586 	  Loss: 1.610664776767293 	 Accuracy: 0.29986962190352023
Delta: 0.0034788277545180326 	  Loss: 1.6112766321992829 	 Accuracy: 0.3011734028683181
Delta: 0.0021282632593415322 	  Loss: 1.6114018708731679 	 Accuracy: 0.30378096479791394
Delta: 0.001168227737284686 	  Loss: 1.6113640539367038 	 Accuracy: 0.3011734028683181
Delta: 0.0022452988254914198 	  Loss: 1.6109575015213755 	 Accuracy: 0.3011734028683181
Delta: 0.0022489372477804436 	  Loss: 1.6108945238015053 	 Accuracy: 0.30378096479791394
Delta: 0.0033574221991260022 	  Loss: 1.6109331517483754 	 Accuracy: 0.30247718383311606
Delta: 0.003895319172388417 	  Loss: 1.6102289848826237 	 Accuracy: 0.30247718383311606
Delta: 0.004561639258655321 	  Loss: 1.6104419901462625 	 Accuracy: 0.3011734028683181
Delta: 0.0009852095520472746 	  Loss: 1.6106951663200615 	 Accuracy: 0.30247718383311606
Delta: 0.0021011375806691246 	  Loss: 1.6110966958456214 	 Accuracy: 0.30247718383311606
Delta: 0.005773526842579905 	  Loss: 1.6215107247149125 	 Accuracy: 0.29986962190352023
Delta: 0.005271152905298171 	  Loss: 1.6118218327310894 	 Accuracy: 0.30247718383311606
Delta: 0.0032864695499547334 	  Loss: 1.6112236953459491 	 Accuracy: 0.30247718383311606
Delta: 0.0022719926173958974 	  Loss: 1.6109302465576862 	 Accuracy: 0.30247718383311606
Delta: 0.0029327827977272632 	  Loss: 1.6112122689256774 	 Accuracy: 0.2985658409387223
Delta: 0.004527219839723532 	  Loss: 1.612339480237114 	 Accuracy: 0.29986962190352023
Delta: 0.0005558717733790257 	  Loss: 1.612123728341002 	 Accuracy: 0.29986962190352023
Delta: 0.0006046783114516142 	  Loss: 1.6121793858350189 	 Accuracy: 0.3011734028683181
Delta: 9.631691867899958e-05 	  Loss: 1.6121735100187435 	 Accuracy: 0.3011734028683181
Delta: 0.0011255901880098734 	  Loss: 1.6120188889263511 	 Accuracy: 0.30247718383311606
Delta: 0.001017247924481725 	  Loss: 1.6121465124039136 	 Accuracy: 0.3011734028683181
Delta: 8.165925528132731e-05 	  Loss: 1.611984533508861 	 Accuracy: 0.29986962190352023
Delta: 0.0014228368744928742 	  Loss: 1.6119755120232364 	 Accuracy: 0.29986962190352023
Delta: 0.0015200357381999964 	  Loss: 1.612196363779682 	 Accuracy: 0.3011734028683181
Delta: 0.0005941947752474716 	  Loss: 1.612181371971988 	 Accuracy: 0.3011734028683181
Delta: 2.8870745756521552e-05 	  Loss: 1.6121676233227733 	 Accuracy: 0.30378096479791394
Delta: 0.0032900236550387272 	  Loss: 1.612026671794665 	 Accuracy: 0.30247718383311606
Delta: 0.0035954141521007104 	  Loss: 1.6116714922174213 	 Accuracy: 0.30247718383311606
Delta: 0.0022618323331410227 	  Loss: 1.612250895722165 	 Accuracy: 0.29986962190352023
Delta: 0.004557981728582536 	  Loss: 1.6130959371669449 	 Accuracy: 0.2985658409387223
Delta: 0.0027831773572090626 	  Loss: 1.6126668771343922 	 Accuracy: 0.2816166883963494
Delta: 0.0032221863306378658 	  Loss: 1.6127661891008218 	 Accuracy: 0.29986962190352023
Delta: 0.00384687140813342 	  Loss: 1.6117106086327875 	 Accuracy: 0.29986962190352023
Delta: 0.0010110106994060581 	  Loss: 1.6120585839085604 	 Accuracy: 0.3011734028683181
Delta: 0.0012987380720232422 	  Loss: 1.612202903170332 	 Accuracy: 0.29986962190352023
Delta: 0.0036540713242686268 	  Loss: 1.611927516359931 	 Accuracy: 0.29986962190352023
Delta: 0.0010140388290029222 	  Loss: 1.6118199413453653 	 Accuracy: 0.29595827900912647
Delta: 0.003368055608693349 	  Loss: 1.6122205204323117 	 Accuracy: 0.29726205997392435
Delta: 0.0035354234483308856 	  Loss: 1.6118781585753559 	 Accuracy: 0.2985658409387223
Delta: 0.0018213878752524379 	  Loss: 1.6119406136704575 	 Accuracy: 0.2985658409387223
Delta: 0.0014728399325841467 	  Loss: 1.6121110121135072 	 Accuracy: 0.2985658409387223
Delta: 9.633143026436535e-07 	  Loss: 1.6121106267377947 	 Accuracy: 0.3011734028683181
Delta: 0.02097867714507754 	  Loss: 2.1570413033089966 	 Accuracy: 0.1773142112125163
Delta: 0.01881332256830308 	  Loss: 2.061617976901935 	 Accuracy: 0.19947848761408082
Delta: 0.01800411588295406 	  Loss: 1.8993898030367458 	 Accuracy: 0.22294654498044328
Delta: 0.016953599990421293 	  Loss: 1.739559077087681 	 Accuracy: 0.196870925684485
Delta: 0.013864352800670096 	  Loss: 1.6469202277930113 	 Accuracy: 0.1760104302477184
Delta: 0.010694762901084662 	  Loss: 1.615637503774015 	 Accuracy: 0.18122555410691005
Delta: 0.008260147335261082 	  Loss: 1.6072384435286133 	 Accuracy: 0.17470664928292046

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0069413311840030075 	  Loss: 1.6044786859754678 	 Accuracy: 0.17340286831812254
Delta: 0.005586025267365181 	  Loss: 1.603758496990434 	 Accuracy: 0.17470664928292046
Delta: 0.005248161015480081 	  Loss: 1.602526516265589 	 Accuracy: 0.1760104302477184
Delta: 0.004625109974967075 	  Loss: 1.6024667477936827 	 Accuracy: 0.1760104302477184
Delta: 0.0024180342245684583 	  Loss: 1.6024019469880812 	 Accuracy: 0.1760104302477184
Delta: 0.002220944329107494 	  Loss: 1.6023813317263742 	 Accuracy: 0.1760104302477184
Delta: 0.0007202602007624122 	  Loss: 1.602427101030201 	 Accuracy: 0.1773142112125163
Delta: 0.0006520499877423579 	  Loss: 1.6025688382990875 	 Accuracy: 0.1760104302477184
Delta: 0.003448411401469358 	  Loss: 1.6027165535022934 	 Accuracy: 0.1760104302477184
Delta: 0.0020727559256982983 	  Loss: 1.6024711233633888 	 Accuracy: 0.1773142112125163
Delta: 0.002998599835557639 	  Loss: 1.6025412001899721 	 Accuracy: 0.1760104302477184
Delta: 0.003745675822933595 	  Loss: 1.6024790394854291 	 Accuracy: 0.1773142112125163
Delta: 0.00222151763448819 	  Loss: 1.6022771827014224 	 Accuracy: 0.1760104302477184
Delta: 0.0022191215315652186 	  Loss: 1.602941538455349 	 Accuracy: 0.1773142112125163
Delta: 0.003090347171359792 	  Loss: 1.6030433937827722 	 Accuracy: 0.1773142112125163
Delta: 0.0033332017214640613 	  Loss: 1.6024755075449937 	 Accuracy: 0.1760104302477184
Delta: 0.0008930912161998147 	  Loss: 1.6024036630778893 	 Accuracy: 0.17861799217731422
Delta: 3.8786291800611226e-05 	  Loss: 1.602237526791255 	 Accuracy: 0.1760104302477184
Delta: 0.0013355682784338143 	  Loss: 1.6024431791035394 	 Accuracy: 0.1760104302477184
Delta: 0.0015560457038808124 	  Loss: 1.6024657695848605 	 Accuracy: 0.1760104302477184
Delta: 0.0021028202018521895 	  Loss: 1.602401338149761 	 Accuracy: 0.17470664928292046
Delta: 0.001456279298792341 	  Loss: 1.6022933897549971 	 Accuracy: 0.17340286831812254
Delta: 8.925626276453969e-05 	  Loss: 1.6022909997255779 	 Accuracy: 0.1760104302477184
Delta: 0.0012210922419302183 	  Loss: 1.6027184929554565 	 Accuracy: 0.1773142112125163
Delta: 0.0018766022392352319 	  Loss: 1.602545266160734 	 Accuracy: 0.17470664928292046
Delta: 0.0005405462824122806 	  Loss: 1.6023613782047725 	 Accuracy: 0.1760104302477184
Delta: 0.0007972133198621828 	  Loss: 1.6024678363500235 	 Accuracy: 0.1773142112125163
Delta: 0.0033742244812978587 	  Loss: 1.6027187536938676 	 Accuracy: 0.1773142112125163
Delta: 0.0027793932228535904 	  Loss: 1.6026610381847797 	 Accuracy: 0.17340286831812254
Delta: 0.00357352033446333 	  Loss: 1.6025715523834205 	 Accuracy: 0.1760104302477184
Delta: 0.0020813721178894818 	  Loss: 1.6028189964415112 	 Accuracy: 0.1760104302477184
Delta: 0.002124702276356142 	  Loss: 1.6025991235698633 	 Accuracy: 0.1760104302477184
Delta: 0.0010508495705467316 	  Loss: 1.6026792772712168 	 Accuracy: 0.1760104302477184
Delta: 0.0022442384435645223 	  Loss: 1.6025655592505723 	 Accuracy: 0.17470664928292046
Delta: 0.004291555202091536 	  Loss: 1.602764595712838 	 Accuracy: 0.17470664928292046
Delta: 0.0024209267783701625 	  Loss: 1.6026594432329817 	 Accuracy: 0.1760104302477184
Delta: 0.0011955761471511954 	  Loss: 1.602810581223261 	 Accuracy: 0.17340286831812254
Delta: 0.000969951210004089 	  Loss: 1.6027207271192454 	 Accuracy: 0.17209908735332463
Delta: 0.0023528610049018224 	  Loss: 1.6029025127170382 	 Accuracy: 0.1773142112125163
Delta: 0.0033347190128366062 	  Loss: 1.6024129076468903 	 Accuracy: 0.1773142112125163
Delta: 0.0020910675241981717 	  Loss: 1.602373864754724 	 Accuracy: 0.1773142112125163
Delta: 0.0022300052695042776 	  Loss: 1.6026868044077358 	 Accuracy: 0.1773142112125163
Delta: 0.001827571678545619 	  Loss: 1.6024468561126866 	 Accuracy: 0.1773142112125163
Delta: 4.475579987022077e-05 	  Loss: 1.6022008815760227 	 Accuracy: 0.1773142112125163
Delta: 0.0005133454018085416 	  Loss: 1.6021756915104262 	 Accuracy: 0.1773142112125163
Delta: 0.0022385734365081835 	  Loss: 1.6028623306331058 	 Accuracy: 0.17861799217731422
Delta: 0.0025788624520332202 	  Loss: 1.6034740332945816 	 Accuracy: 0.17861799217731422
Delta: 0.0009896478371024745 	  Loss: 1.6028671424192944 	 Accuracy: 0.17861799217731422
Delta: 0.004425687971581851 	  Loss: 1.6023252576676468 	 Accuracy: 0.17861799217731422
Delta: 5.1522176429943435e-05 	  Loss: 1.6025292901946508 	 Accuracy: 0.17861799217731422
Delta: 0.0017742096537157611 	  Loss: 1.6020836589489953 	 Accuracy: 0.1773142112125163
Delta: 0.0027829822232028198 	  Loss: 1.6015999435546897 	 Accuracy: 0.17340286831812254
Delta: 0.0020607147131895586 	  Loss: 1.6025791235882738 	 Accuracy: 0.17992177314211213
Delta: 0.002366240105653764 	  Loss: 1.602387027581687 	 Accuracy: 0.17861799217731422
Delta: 0.0009784731067000354 	  Loss: 1.6024828051358075 	 Accuracy: 0.17861799217731422
Delta: 0.0007446461921420063 	  Loss: 1.6022650896185604 	 Accuracy: 0.17861799217731422
Delta: 0.0016743406339451146 	  Loss: 1.6021519695360786 	 Accuracy: 0.1773142112125163
Delta: 0.0013368417962646992 	  Loss: 1.602491179065208 	 Accuracy: 0.1773142112125163
Delta: 0.0036894560728012314 	  Loss: 1.6006945979888136 	 Accuracy: 0.17992177314211213
Delta: 0.0005592409325184667 	  Loss: 1.6007355131350955 	 Accuracy: 0.1773142112125163
Delta: 0.001108509518891285 	  Loss: 1.6006965681976448 	 Accuracy: 0.1773142112125163
Delta: 0.002368909835055286 	  Loss: 1.6019198932516252 	 Accuracy: 0.17992177314211213
Delta: 0.0031807651747697897 	  Loss: 1.6007423330722714 	 Accuracy: 0.1773142112125163
Delta: 0.0008992186032382693 	  Loss: 1.6007716683914535 	 Accuracy: 0.17470664928292046
Delta: 0.0029129407368787196 	  Loss: 1.6005074025440447 	 Accuracy: 0.17470664928292046
Delta: 0.0020616308942317542 	  Loss: 1.6006866280890955 	 Accuracy: 0.1773142112125163
Delta: 0.0022146942153972184 	  Loss: 1.6006178816791923 	 Accuracy: 0.1773142112125163
Delta: 0.0015885550209200636 	  Loss: 1.6005560264779668 	 Accuracy: 0.17470664928292046
Delta: 0.0026773409486407114 	  Loss: 1.6007911620676472 	 Accuracy: 0.1760104302477184
Delta: 0.0031682485090725448 	  Loss: 1.6010742006071257 	 Accuracy: 0.1760104302477184
Delta: 0.0015285351373034086 	  Loss: 1.6012119175787518 	 Accuracy: 0.1760104302477184
Delta: 0.002755991097897671 	  Loss: 1.6012771359752231 	 Accuracy: 0.1760104302477184
Delta: 7.126938203494839e-05 	  Loss: 1.6011418868839935 	 Accuracy: 0.1760104302477184
Delta: 0.002316253111559556 	  Loss: 1.6016034108131625 	 Accuracy: 0.17470664928292046
Delta: 0.002720752609332187 	  Loss: 1.6019448173924746 	 Accuracy: 0.17470664928292046
Delta: 0.0015263729676478917 	  Loss: 1.601759433245081 	 Accuracy: 0.1760104302477184
Delta: 0.002886730444931608 	  Loss: 1.6011023361015955 	 Accuracy: 0.1760104302477184
Delta: 0.0012673707109792094 	  Loss: 1.601257044716623 	 Accuracy: 0.1760104302477184
Delta: 0.0014337497553269503 	  Loss: 1.6006947540160894 	 Accuracy: 0.18252933507170796
Delta: 0.004129722783108443 	  Loss: 1.6006596579381762 	 Accuracy: 0.1773142112125163
Delta: 0.005145455688644163 	  Loss: 1.6001628256164824 	 Accuracy: 0.1760104302477184
Delta: 0.004090772313766175 	  Loss: 1.600237610782544 	 Accuracy: 0.1773142112125163
Delta: 0.003020536488623907 	  Loss: 1.6003516122238686 	 Accuracy: 0.18122555410691005
Delta: 0.002976363913422902 	  Loss: 1.6006850957501961 	 Accuracy: 0.18383311603650587
Delta: 0.0017212102236370953 	  Loss: 1.6002163297775347 	 Accuracy: 0.17992177314211213
Delta: 0.0005874266528008217 	  Loss: 1.6002850065527685 	 Accuracy: 0.17079530638852672
Delta: 0.007332619079702568 	  Loss: 1.5986282504553329 	 Accuracy: 0.17992177314211213
Delta: 0.0057659700126150015 	  Loss: 1.5970441146000212 	 Accuracy: 0.17340286831812254
Delta: 0.005288450264987846 	  Loss: 1.595787461014876 	 Accuracy: 0.17340286831812254
Delta: 0.0016618240012117984 	  Loss: 1.5966057113501853 	 Accuracy: 0.17340286831812254
Delta: 5.174373054884132e-06 	  Loss: 1.5966006257057899 	 Accuracy: 0.17340286831812254
Delta: 0.003346962722402261 	  Loss: 1.5960028483456639 	 Accuracy: 0.17470664928292046
Delta: 0.0032133155044583093 	  Loss: 1.5966050915714751 	 Accuracy: 0.17340286831812254
Delta: 0.021159867131713122 	  Loss: 2.1566575584119745 	 Accuracy: 0.20208604954367665
Delta: 0.018545981738372585 	  Loss: 2.058439297972855 	 Accuracy: 0.28292046936114734
Delta: 0.017349613611749415 	  Loss: 1.9070046769845082 	 Accuracy: 0.42633637548891784
Delta: 0.016876529599030198 	  Loss: 1.7535626033469491 	 Accuracy: 0.4498044328552803
Delta: 0.013211914374616324 	  Loss: 1.6757287587762069 	 Accuracy: 0.4406779661016949

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010053677118965237 	  Loss: 1.6530599036554716 	 Accuracy: 0.4315514993481095
Delta: 0.008068628366826217 	  Loss: 1.6468130350529373 	 Accuracy: 0.4172099087353325
Delta: 0.006018896005811524 	  Loss: 1.6468306106882853 	 Accuracy: 0.42503259452411996
Delta: 0.005005373607458637 	  Loss: 1.6466282178691414 	 Accuracy: 0.423728813559322
Delta: 0.003938775101483656 	  Loss: 1.6459171436288107 	 Accuracy: 0.42503259452411996
Delta: 0.0033572330308530704 	  Loss: 1.6455937309255992 	 Accuracy: 0.42503259452411996
Delta: 0.0015238666358729457 	  Loss: 1.645476190858008 	 Accuracy: 0.423728813559322
Delta: 0.0035848008224219673 	  Loss: 1.645136321501843 	 Accuracy: 0.4276401564537158
Delta: 0.003892194006942855 	  Loss: 1.6450459006734404 	 Accuracy: 0.42242503259452413
Delta: 0.004347334380024029 	  Loss: 1.6453798515367937 	 Accuracy: 0.4276401564537158
Delta: 0.0019373425465551242 	  Loss: 1.6453354090953147 	 Accuracy: 0.4276401564537158
Delta: 0.0011309944093980348 	  Loss: 1.6451966356481555 	 Accuracy: 0.4276401564537158
Delta: 0.0009484589725382733 	  Loss: 1.645240550920735 	 Accuracy: 0.4276401564537158
Delta: 3.0657401207269116e-05 	  Loss: 1.6453996502448849 	 Accuracy: 0.4276401564537158
Delta: 0.0018516591445003029 	  Loss: 1.6454921063996637 	 Accuracy: 0.4276401564537158
Delta: 3.7936869364470675e-05 	  Loss: 1.6451932648253065 	 Accuracy: 0.4276401564537158
Delta: 0.0007447436325571829 	  Loss: 1.6449608048281035 	 Accuracy: 0.4276401564537158
Delta: 0.0007871939945912433 	  Loss: 1.6451431146576594 	 Accuracy: 0.42894393741851367
Delta: 0.0030282881223953656 	  Loss: 1.645258756616173 	 Accuracy: 0.42894393741851367
Delta: 0.0010606900179383457 	  Loss: 1.645000745980469 	 Accuracy: 0.42894393741851367
Delta: 0.0009225163211734883 	  Loss: 1.6450719178962667 	 Accuracy: 0.4276401564537158
Delta: 0.0008351123551769947 	  Loss: 1.6451537217757455 	 Accuracy: 0.4276401564537158
Delta: 0.0025280048298111325 	  Loss: 1.6451840678734793 	 Accuracy: 0.42894393741851367
Delta: 0.002721863182544539 	  Loss: 1.6448160228063595 	 Accuracy: 0.4276401564537158
Delta: 0.002062001788463349 	  Loss: 1.6450914501877856 	 Accuracy: 0.4276401564537158
Delta: 0.0008231777587873287 	  Loss: 1.6452991020266428 	 Accuracy: 0.4276401564537158
Delta: 0.002135800643302941 	  Loss: 1.6449365294831746 	 Accuracy: 0.42894393741851367
Delta: 0.0028519825352104314 	  Loss: 1.6443197639046754 	 Accuracy: 0.42894393741851367
Delta: 0.0015105508123015696 	  Loss: 1.6444656049131678 	 Accuracy: 0.42894393741851367
Delta: 0.003916749959114108 	  Loss: 1.6423486282719126 	 Accuracy: 0.4302477183833116
Delta: 0.00376902036887045 	  Loss: 1.6425242077444686 	 Accuracy: 0.42894393741851367
Delta: 0.004870335322917446 	  Loss: 1.6432199542283665 	 Accuracy: 0.4315514993481095
Delta: 0.004870340591164599 	  Loss: 1.6437019641588817 	 Accuracy: 0.4276401564537158
Delta: 0.0008032650575620156 	  Loss: 1.64365358471266 	 Accuracy: 0.42894393741851367
Delta: 0.0028655543372317904 	  Loss: 1.6424291982722803 	 Accuracy: 0.42503259452411996
Delta: 0.000575361543974654 	  Loss: 1.6423520389005257 	 Accuracy: 0.42894393741851367
Delta: 0.003200253766785273 	  Loss: 1.6427319666967368 	 Accuracy: 0.42894393741851367
Delta: 0.0007514929440712894 	  Loss: 1.6427338874933273 	 Accuracy: 0.42894393741851367
Delta: 5.844856150375373e-05 	  Loss: 1.642806933848526 	 Accuracy: 0.4276401564537158
Delta: 2.5936268523036428e-05 	  Loss: 1.6428372733751995 	 Accuracy: 0.4276401564537158
Delta: 0.0013817328921044852 	  Loss: 1.6432799132555265 	 Accuracy: 0.4276401564537158
Delta: 1.1822269106675974e-05 	  Loss: 1.6432844221409657 	 Accuracy: 0.42894393741851367
Delta: 0.0023847560251928513 	  Loss: 1.6434994628611648 	 Accuracy: 0.4315514993481095
Delta: 9.126743059584711e-05 	  Loss: 1.643106010869571 	 Accuracy: 0.42503259452411996
Delta: 0.0005601195061326404 	  Loss: 1.6433205772129489 	 Accuracy: 0.42894393741851367
Delta: 0.001738438823236564 	  Loss: 1.6431797406699247 	 Accuracy: 0.4276401564537158
Delta: 0.0010222553567768512 	  Loss: 1.6433805078620072 	 Accuracy: 0.4276401564537158
Delta: 4.4736865264744084e-05 	  Loss: 1.6432844502219353 	 Accuracy: 0.42242503259452413
Delta: 4.463174803489493e-05 	  Loss: 1.6433884848800977 	 Accuracy: 0.42894393741851367
Delta: 0.0008050316169902947 	  Loss: 1.6433335023328015 	 Accuracy: 0.4276401564537158
Delta: 0.0012322560781531926 	  Loss: 1.6439342487908024 	 Accuracy: 0.42894393741851367
Delta: 0.002459651580468077 	  Loss: 1.6432098498333356 	 Accuracy: 0.41851368970013036
Delta: 0.0014279894494819228 	  Loss: 1.642885924022246 	 Accuracy: 0.4276401564537158
Delta: 0.0005786929826282808 	  Loss: 1.6427328635070237 	 Accuracy: 0.42894393741851367
Delta: 0.002719022788651835 	  Loss: 1.6425331338411557 	 Accuracy: 0.4302477183833116
Delta: 0.0012673709355452314 	  Loss: 1.6422408861485582 	 Accuracy: 0.42503259452411996
Delta: 0.002468951189887082 	  Loss: 1.642197272106844 	 Accuracy: 0.42894393741851367
Delta: 0.0008966770914692388 	  Loss: 1.642322429485508 	 Accuracy: 0.42894393741851367
Delta: 3.170734348262474e-05 	  Loss: 1.6424022862719858 	 Accuracy: 0.42894393741851367
Delta: 7.026509652635792e-05 	  Loss: 1.6425944587824115 	 Accuracy: 0.4302477183833116
Delta: 0.003507459163885358 	  Loss: 1.6437543763728448 	 Accuracy: 0.4302477183833116
Delta: 0.0023147606047368924 	  Loss: 1.643528898313167 	 Accuracy: 0.4302477183833116
Delta: 0.0017316396393864107 	  Loss: 1.6435719362911847 	 Accuracy: 0.4315514993481095
Delta: 0.004023957899456287 	  Loss: 1.6438304715311625 	 Accuracy: 0.4302477183833116
Delta: 0.004383226485135755 	  Loss: 1.6440526469062757 	 Accuracy: 0.4315514993481095
Delta: 0.004444945768209268 	  Loss: 1.6443507900207959 	 Accuracy: 0.4302477183833116
Delta: 0.0028927242460544426 	  Loss: 1.6442593171653428 	 Accuracy: 0.43415906127770537
Delta: 0.004295599612981491 	  Loss: 1.6438539944071104 	 Accuracy: 0.4315514993481095
Delta: 0.0011610690441019571 	  Loss: 1.6438339990222395 	 Accuracy: 0.4315514993481095
Delta: 0.0005084936696648407 	  Loss: 1.6438519099864983 	 Accuracy: 0.4315514993481095
Delta: 0.0015911753483967552 	  Loss: 1.6435187567883125 	 Accuracy: 0.42633637548891784
Delta: 0.00444566096791474 	  Loss: 1.6439932694566823 	 Accuracy: 0.4315514993481095
Delta: 0.0048854830307468395 	  Loss: 1.6450327168470638 	 Accuracy: 0.43285528031290743
Delta: 0.005731197186505246 	  Loss: 1.6449927334641086 	 Accuracy: 0.4315514993481095
Delta: 0.0015284593582021526 	  Loss: 1.6453979672425367 	 Accuracy: 0.4302477183833116
Delta: 0.0029399139892403456 	  Loss: 1.645782706445618 	 Accuracy: 0.4302477183833116
Delta: 0.0005074312126258142 	  Loss: 1.645776119669847 	 Accuracy: 0.42894393741851367
Delta: 0.002995300473050105 	  Loss: 1.6449151859379492 	 Accuracy: 0.4315514993481095
Delta: 0.0022612981429095584 	  Loss: 1.645468886527234 	 Accuracy: 0.4302477183833116
Delta: 0.002584810517295322 	  Loss: 1.644971214778684 	 Accuracy: 0.42894393741851367
Delta: 0.002323536510768872 	  Loss: 1.645483364369067 	 Accuracy: 0.4302477183833116
Delta: 0.001509801035820898 	  Loss: 1.6457598975706427 	 Accuracy: 0.42633637548891784
Delta: 0.0015750806249844858 	  Loss: 1.6463541123265144 	 Accuracy: 0.42894393741851367
Delta: 0.0027384584076499386 	  Loss: 1.6469742321797016 	 Accuracy: 0.42894393741851367
Delta: 8.173125470657311e-06 	  Loss: 1.646983743585382 	 Accuracy: 0.4367666232073012
Delta: 0.0020430454899003016 	  Loss: 1.6469951971218082 	 Accuracy: 0.42894393741851367
Delta: 0.004263509664871066 	  Loss: 1.647589205725704 	 Accuracy: 0.42633637548891784
Delta: 0.0017709148532969066 	  Loss: 1.6474767452043002 	 Accuracy: 0.42633637548891784
Delta: 0.0033389962802533187 	  Loss: 1.6480182712468852 	 Accuracy: 0.42633637548891784
Delta: 0.003866273530137008 	  Loss: 1.647216134264835 	 Accuracy: 0.423728813559322
Delta: 0.004439845527732298 	  Loss: 1.6483470314302502 	 Accuracy: 0.42242503259452413
Delta: 0.002032968713580941 	  Loss: 1.6478543605382243 	 Accuracy: 0.42503259452411996
Delta: 0.005071982909198259 	  Loss: 1.6457744787005404 	 Accuracy: 0.4315514993481095
Delta: 0.003829108485839147 	  Loss: 1.644359632868928 	 Accuracy: 0.42633637548891784
Delta: 0.002635612004202107 	  Loss: 1.6463582377747474 	 Accuracy: 0.42242503259452413
Delta: 0.021239563768903215 	  Loss: 2.155912747070661 	 Accuracy: 0.23076923076923078
Delta: 0.01861964093603935 	  Loss: 2.0464236504601803 	 Accuracy: 0.3116036505867014
Delta: 0.01723073371033003 	  Loss: 1.8755551509971187 	 Accuracy: 0.3468057366362451
Delta: 0.016455194493397687 	  Loss: 1.7400854768696559 	 Accuracy: 0.3520208604954368
Delta: 0.01355825060520953 	  Loss: 1.6794630315259984 	 Accuracy: 0.3324641460234681
Delta: 0.010010052500310522 	  Loss: 1.6614977176746044 	 Accuracy: 0.3389830508474576

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008202779916894913 	  Loss: 1.6586552238857732 	 Accuracy: 0.3363754889178618
Delta: 0.0065329308278892426 	  Loss: 1.6566930181304331 	 Accuracy: 0.34159061277705344
Delta: 0.0037660880785926817 	  Loss: 1.6567989036004633 	 Accuracy: 0.3376792698826597
Delta: 0.00365186496784807 	  Loss: 1.6568519933147332 	 Accuracy: 0.3376792698826597
Delta: 0.0023728432971630176 	  Loss: 1.6568279046941004 	 Accuracy: 0.3376792698826597
Delta: 0.003129156088978172 	  Loss: 1.6569731549423006 	 Accuracy: 0.3376792698826597
Delta: 0.001212948248428992 	  Loss: 1.6568709377424877 	 Accuracy: 0.3376792698826597
Delta: 0.0006447114019401274 	  Loss: 1.6566967356557745 	 Accuracy: 0.3376792698826597
Delta: 0.0015770969806817798 	  Loss: 1.6567057999752728 	 Accuracy: 0.34028683181225555
Delta: 0.0020643662720839047 	  Loss: 1.6565902094993206 	 Accuracy: 0.3389830508474576
Delta: 0.0029808639342904348 	  Loss: 1.6563779795147455 	 Accuracy: 0.34028683181225555
Delta: 0.0013935662377845518 	  Loss: 1.656284049923941 	 Accuracy: 0.3389830508474576
Delta: 0.0037503931754123082 	  Loss: 1.656093468373378 	 Accuracy: 0.3389830508474576
Delta: 0.0029485677016608427 	  Loss: 1.6560458151562272 	 Accuracy: 0.34028683181225555
Delta: 0.0019194253951396846 	  Loss: 1.656034318710105 	 Accuracy: 0.3389830508474576
Delta: 0.003976702536545854 	  Loss: 1.6558741474173457 	 Accuracy: 0.34028683181225555
Delta: 0.003520730801580854 	  Loss: 1.6557845371413966 	 Accuracy: 0.3559322033898305
Delta: 0.0030328161909918983 	  Loss: 1.6561403770384722 	 Accuracy: 0.34028683181225555
Delta: 0.004252933037102349 	  Loss: 1.656193867216971 	 Accuracy: 0.34028683181225555
Delta: 7.207864475294844e-05 	  Loss: 1.6565418092850586 	 Accuracy: 0.34028683181225555
Delta: 0.0007972317586706137 	  Loss: 1.6562912183258114 	 Accuracy: 0.34028683181225555
Delta: 0.00011232527792708725 	  Loss: 1.6564501822678475 	 Accuracy: 0.34159061277705344
Delta: 0.0010013973688966257 	  Loss: 1.6567476226049551 	 Accuracy: 0.34028683181225555
Delta: 6.01905233487072e-05 	  Loss: 1.6565286774007713 	 Accuracy: 0.3389830508474576
Delta: 0.0010606136626968546 	  Loss: 1.6562532793878089 	 Accuracy: 0.34028683181225555
Delta: 0.0023080461995843493 	  Loss: 1.6563133248697808 	 Accuracy: 0.3376792698826597
Delta: 0.00377958204410179 	  Loss: 1.656095700976002 	 Accuracy: 0.34028683181225555
Delta: 0.003994270662644946 	  Loss: 1.6568555185157652 	 Accuracy: 0.3389830508474576
Delta: 0.002957177085342049 	  Loss: 1.6570304456352891 	 Accuracy: 0.3363754889178618
Delta: 0.0010714012680632429 	  Loss: 1.6571007410042353 	 Accuracy: 0.3389830508474576
Delta: 0.0038211482975142267 	  Loss: 1.6574501338699383 	 Accuracy: 0.3376792698826597
Delta: 0.002792673392236264 	  Loss: 1.6572328450207987 	 Accuracy: 0.3363754889178618
Delta: 0.004110637760371596 	  Loss: 1.6573302864931303 	 Accuracy: 0.3363754889178618
Delta: 0.0027931206813407044 	  Loss: 1.6571454381308404 	 Accuracy: 0.34028683181225555
Delta: 0.004769265835085156 	  Loss: 1.6575449040656283 	 Accuracy: 0.3376792698826597
Delta: 0.0010245812197925814 	  Loss: 1.6577097836655899 	 Accuracy: 0.3389830508474576
Delta: 0.0028374436075099658 	  Loss: 1.657912946737465 	 Accuracy: 0.3389830508474576
Delta: 0.0008795320509434094 	  Loss: 1.6572923078805752 	 Accuracy: 0.3389830508474576
Delta: 0.0005677105808855437 	  Loss: 1.6576274073342487 	 Accuracy: 0.34159061277705344
Delta: 0.005321498640136025 	  Loss: 1.6582838977637846 	 Accuracy: 0.34028683181225555
Delta: 0.0018234963163350653 	  Loss: 1.6581646925975249 	 Accuracy: 0.33376792698826596
Delta: 0.003772014598657455 	  Loss: 1.658214899207036 	 Accuracy: 0.32985658409387225
Delta: 0.004150399591069524 	  Loss: 1.657915238975844 	 Accuracy: 0.34419817470664926
Delta: 0.0038415418417344182 	  Loss: 1.657514166858745 	 Accuracy: 0.3324641460234681
Delta: 0.004811775703042529 	  Loss: 1.6568359293939876 	 Accuracy: 0.3285528031290743
Delta: 0.0021837739593288255 	  Loss: 1.6570397625362752 	 Accuracy: 0.33116036505867014
Delta: 0.0037937244377535344 	  Loss: 1.6581084605662864 	 Accuracy: 0.33116036505867014
Delta: 0.0028781139022056893 	  Loss: 1.6582271631558059 	 Accuracy: 0.3324641460234681
Delta: 0.0036634264664713104 	  Loss: 1.6585524572642 	 Accuracy: 0.3324641460234681
Delta: 0.004597409480909724 	  Loss: 1.6588373668067766 	 Accuracy: 0.33116036505867014
Delta: 3.481079495663209e-05 	  Loss: 1.6588249949660883 	 Accuracy: 0.3324641460234681
Delta: 0.003205371688396929 	  Loss: 1.6587912457301794 	 Accuracy: 0.3324641460234681
Delta: 0.0033230617563523397 	  Loss: 1.6590730975756596 	 Accuracy: 0.3324641460234681
Delta: 0.0008903429889607553 	  Loss: 1.659019090971938 	 Accuracy: 0.3324641460234681
Delta: 0.0007190627979827412 	  Loss: 1.6589215124833783 	 Accuracy: 0.32985658409387225
Delta: 0.0022225189211854996 	  Loss: 1.6593162678659645 	 Accuracy: 0.32985658409387225
Delta: 0.0015920891640823789 	  Loss: 1.6588481773460713 	 Accuracy: 0.3324641460234681
Delta: 0.0007770536022488845 	  Loss: 1.6589968148301348 	 Accuracy: 0.3324641460234681
Delta: 8.693679796606393e-06 	  Loss: 1.6590224604004904 	 Accuracy: 0.3350717079530639
Delta: 0.005016235164493225 	  Loss: 1.6589985268512697 	 Accuracy: 0.3324641460234681
Delta: 0.0025659029499497587 	  Loss: 1.6592114998522693 	 Accuracy: 0.33376792698826596
Delta: 0.003256033598387261 	  Loss: 1.659010943430882 	 Accuracy: 0.33116036505867014
Delta: 0.004019946293184922 	  Loss: 1.659502962512762 	 Accuracy: 0.3324641460234681
Delta: 0.0036339317686613095 	  Loss: 1.6591430180795776 	 Accuracy: 0.33376792698826596
Delta: 0.005155677950070621 	  Loss: 1.6582073015762675 	 Accuracy: 0.3363754889178618
Delta: 0.005955761433091807 	  Loss: 1.6578060158098333 	 Accuracy: 0.3350717079530639
Delta: 0.00334132074151635 	  Loss: 1.6571905600488912 	 Accuracy: 0.3363754889178618
Delta: 0.004619084096712219 	  Loss: 1.6573526051361922 	 Accuracy: 0.3350717079530639
Delta: 0.0026757103190110376 	  Loss: 1.6570121172572223 	 Accuracy: 0.3350717079530639
Delta: 0.003417845670471427 	  Loss: 1.6571463174603243 	 Accuracy: 0.3363754889178618
Delta: 0.002373109407180913 	  Loss: 1.6569728611753727 	 Accuracy: 0.3350717079530639
Delta: 0.000653558740298636 	  Loss: 1.6570371614342976 	 Accuracy: 0.3363754889178618
Delta: 0.002550390093383791 	  Loss: 1.6574544166198686 	 Accuracy: 0.3389830508474576
Delta: 0.0044603725040929165 	  Loss: 1.6572855104973567 	 Accuracy: 0.3363754889178618
Delta: 0.0031772583908812346 	  Loss: 1.6572399345353865 	 Accuracy: 0.3376792698826597
Delta: 0.000513406737199317 	  Loss: 1.6572524026684166 	 Accuracy: 0.3363754889178618
Delta: 0.0045786590727977475 	  Loss: 1.6569179632628086 	 Accuracy: 0.33376792698826596
Delta: 0.0037924198623782556 	  Loss: 1.6567607333324095 	 Accuracy: 0.3363754889178618
Delta: 0.001817354766443487 	  Loss: 1.6565359687420373 	 Accuracy: 0.3350717079530639
Delta: 0.0011661977019085468 	  Loss: 1.6567348577424612 	 Accuracy: 0.3350717079530639
Delta: 0.001543787789720265 	  Loss: 1.65665941836805 	 Accuracy: 0.3324641460234681
Delta: 0.004057398988243097 	  Loss: 1.6567663791624416 	 Accuracy: 0.33376792698826596
Delta: 0.0014493875801906621 	  Loss: 1.656472072324342 	 Accuracy: 0.3324641460234681
Delta: 0.0038318727492853374 	  Loss: 1.6566996367902496 	 Accuracy: 0.32985658409387225
Delta: 0.00478934043546463 	  Loss: 1.6567515273950986 	 Accuracy: 0.3272490221642764
Delta: 0.004685586568702911 	  Loss: 1.6568051886567918 	 Accuracy: 0.32985658409387225
Delta: 6.485496324067226e-05 	  Loss: 1.6566604920075632 	 Accuracy: 0.33116036505867014
Delta: 0.0011797487846179466 	  Loss: 1.65642424854034 	 Accuracy: 0.33376792698826596
Delta: 0.00433280331408228 	  Loss: 1.6570475917221592 	 Accuracy: 0.3324641460234681
Delta: 0.0005309142522437215 	  Loss: 1.656789903517386 	 Accuracy: 0.32985658409387225
Delta: 0.004772132719677048 	  Loss: 1.6572070638051433 	 Accuracy: 0.3324641460234681
Delta: 0.004478941013454294 	  Loss: 1.6569754828205618 	 Accuracy: 0.33116036505867014
Delta: 0.0034746990524822576 	  Loss: 1.656944731736985 	 Accuracy: 0.33116036505867014
Delta: 0.0027122723059478334 	  Loss: 1.6566893578373945 	 Accuracy: 0.33116036505867014
Delta: 0.020958989988932843 	  Loss: 2.157632520228294 	 Accuracy: 0.19035202086049544
Delta: 0.018981584221147138 	  Loss: 2.0516595690172506 	 Accuracy: 0.2438070404172099
Delta: 0.018757564669729856 	  Loss: 1.8682903887357298 	 Accuracy: 0.2842242503259452
Delta: 0.01670166363044475 	  Loss: 1.7177701465755593 	 Accuracy: 0.21642764015645372
Delta: 0.01379820235591957 	  Loss: 1.6417164680169485 	 Accuracy: 0.18904823989569752
Delta: 0.010363279224155772 	  Loss: 1.617765099072 	 Accuracy: 0.19035202086049544

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00746553888528805 	  Loss: 1.612791707951887 	 Accuracy: 0.19165580182529335
Delta: 0.006084082385716458 	  Loss: 1.610124140399893 	 Accuracy: 0.19295958279009126
Delta: 0.004798642387849645 	  Loss: 1.6090290773687093 	 Accuracy: 0.19295958279009126
Delta: 0.002853127094492256 	  Loss: 1.609100268899229 	 Accuracy: 0.19165580182529335
Delta: 0.0030490931683710473 	  Loss: 1.609032343536148 	 Accuracy: 0.19295958279009126
Delta: 0.003667258972554226 	  Loss: 1.6087994159389065 	 Accuracy: 0.19295958279009126
Delta: 0.0021732747477995057 	  Loss: 1.608558100852277 	 Accuracy: 0.19165580182529335
Delta: 0.002397180940113009 	  Loss: 1.6088831672242803 	 Accuracy: 0.19165580182529335
Delta: 0.0011459916505491294 	  Loss: 1.6086914172326698 	 Accuracy: 0.19165580182529335
Delta: 0.0031607269035740368 	  Loss: 1.6087516147922911 	 Accuracy: 0.19165580182529335
Delta: 0.0007952809364599358 	  Loss: 1.6090700677409973 	 Accuracy: 0.19165580182529335
Delta: 0.0010009923926753309 	  Loss: 1.609111504729254 	 Accuracy: 0.19165580182529335
Delta: 7.582316961809733e-05 	  Loss: 1.6093061513253397 	 Accuracy: 0.19295958279009126
Delta: 0.0015065631682812481 	  Loss: 1.609238653123614 	 Accuracy: 0.19165580182529335
Delta: 0.0011088706816819612 	  Loss: 1.6091024388835002 	 Accuracy: 0.19556714471968709
Delta: 0.004990532521845668 	  Loss: 1.6090192071450444 	 Accuracy: 0.19426336375488917
Delta: 0.0036640036759252436 	  Loss: 1.6093912239665786 	 Accuracy: 0.19165580182529335
Delta: 0.0058698982526739696 	  Loss: 1.6090021033713882 	 Accuracy: 0.19556714471968709
Delta: 0.004991597474937917 	  Loss: 1.608994552181767 	 Accuracy: 0.19295958279009126
Delta: 0.0040061980831815076 	  Loss: 1.6082543818287247 	 Accuracy: 0.196870925684485
Delta: 0.00293525219620756 	  Loss: 1.6092749166961702 	 Accuracy: 0.196870925684485
Delta: 0.0012612013893345997 	  Loss: 1.6086610440912046 	 Accuracy: 0.196870925684485
Delta: 0.0038674549523954956 	  Loss: 1.6091337908881804 	 Accuracy: 0.196870925684485
Delta: 0.0027358358337148904 	  Loss: 1.6082311045473605 	 Accuracy: 0.19556714471968709
Delta: 0.002522055322095459 	  Loss: 1.6083783712293536 	 Accuracy: 0.1981747066492829
Delta: 0.00204016965836871 	  Loss: 1.6089679673850843 	 Accuracy: 0.196870925684485
Delta: 0.00011147369432979348 	  Loss: 1.608381259647072 	 Accuracy: 0.196870925684485
Delta: 0.0032539507463340725 	  Loss: 1.6079594317391845 	 Accuracy: 0.19035202086049544
Delta: 0.006296989041867928 	  Loss: 1.6091906161228957 	 Accuracy: 0.19556714471968709
Delta: 0.003552774209643903 	  Loss: 1.6081816303533603 	 Accuracy: 0.19426336375488917
Delta: 0.0024856555120384375 	  Loss: 1.6087236999221695 	 Accuracy: 0.19426336375488917
Delta: 8.724137546683834e-05 	  Loss: 1.6081063665739894 	 Accuracy: 0.19295958279009126
Delta: 0.0024213854943368807 	  Loss: 1.607831206747023 	 Accuracy: 0.19295958279009126
Delta: 0.002154585029381709 	  Loss: 1.6082042091086108 	 Accuracy: 0.19295958279009126
Delta: 0.00011182975808756743 	  Loss: 1.6086979685614882 	 Accuracy: 0.19295958279009126
Delta: 8.376073208563273e-05 	  Loss: 1.6087047499772367 	 Accuracy: 0.19295958279009126
Delta: 7.282703585850582e-05 	  Loss: 1.6087354471794097 	 Accuracy: 0.19426336375488917
Delta: 0.0020723724189492736 	  Loss: 1.6087957989181563 	 Accuracy: 0.19426336375488917
Delta: 0.0013802062744449452 	  Loss: 1.607845687040081 	 Accuracy: 0.19165580182529335
Delta: 0.0010205697246672845 	  Loss: 1.60837653708183 	 Accuracy: 0.1981747066492829
Delta: 0.002154851108478432 	  Loss: 1.6079786850591968 	 Accuracy: 0.19165580182529335
Delta: 0.003061789046604615 	  Loss: 1.6080489048825477 	 Accuracy: 0.19426336375488917
Delta: 0.0035768452137273834 	  Loss: 1.6089901333690575 	 Accuracy: 0.19295958279009126
Delta: 0.002829766728320126 	  Loss: 1.6095264404783798 	 Accuracy: 0.19426336375488917
Delta: 0.003548683942924862 	  Loss: 1.609397540254238 	 Accuracy: 0.19295958279009126
Delta: 0.002859079449701032 	  Loss: 1.6088108691465568 	 Accuracy: 0.1981747066492829
Delta: 0.005137433510448714 	  Loss: 1.6092865349516567 	 Accuracy: 0.19426336375488917
Delta: 0.0019580120547475306 	  Loss: 1.6093476924122367 	 Accuracy: 0.19165580182529335
Delta: 0.004344917074938339 	  Loss: 1.6096247633936343 	 Accuracy: 0.19295958279009126
Delta: 0.0017982503152567993 	  Loss: 1.6092064058768567 	 Accuracy: 0.19426336375488917
Delta: 0.0014307754260741655 	  Loss: 1.6095174978848283 	 Accuracy: 0.19556714471968709
Delta: 0.004111240974428853 	  Loss: 1.6106070813913853 	 Accuracy: 0.19165580182529335
Delta: 0.003167425934416379 	  Loss: 1.6107473975113078 	 Accuracy: 0.19295958279009126
Delta: 0.0021672795778871737 	  Loss: 1.6100772549929048 	 Accuracy: 0.19295958279009126
Delta: 0.0022374008345981532 	  Loss: 1.610157309627896 	 Accuracy: 0.19295958279009126
Delta: 0.002683216794461566 	  Loss: 1.6093174926610279 	 Accuracy: 0.19295958279009126
Delta: 0.0034546397795632068 	  Loss: 1.6091515305950395 	 Accuracy: 0.19295958279009126
Delta: 0.0031879872376137947 	  Loss: 1.6100775519706285 	 Accuracy: 0.19295958279009126
Delta: 0.0027588211831747838 	  Loss: 1.6098240554802052 	 Accuracy: 0.19295958279009126
Delta: 0.004658527833706314 	  Loss: 1.6100194363904499 	 Accuracy: 0.19165580182529335
Delta: 0.005056964686624997 	  Loss: 1.6104242054481355 	 Accuracy: 0.19165580182529335
Delta: 0.0022169343609029714 	  Loss: 1.6105799467906876 	 Accuracy: 0.19165580182529335
Delta: 0.003532488320040187 	  Loss: 1.610143559860321 	 Accuracy: 0.19165580182529335
Delta: 3.951340902314322e-05 	  Loss: 1.6101670184992587 	 Accuracy: 0.19295958279009126
Delta: 0.0005256167934834877 	  Loss: 1.6101382738791215 	 Accuracy: 0.19295958279009126
Delta: 0.0012497858670183252 	  Loss: 1.6099502258374798 	 Accuracy: 0.19295958279009126
Delta: 0.0009680782753438608 	  Loss: 1.6101841492811468 	 Accuracy: 0.19426336375488917
Delta: 2.643201371531036e-05 	  Loss: 1.6101735657261038 	 Accuracy: 0.19295958279009126
Delta: 1.7729944200296424e-06 	  Loss: 1.6101654896960917 	 Accuracy: 0.19165580182529335
Delta: 0.0015439542311997388 	  Loss: 1.6103359136937112 	 Accuracy: 0.19295958279009126
Delta: 0.0014284837916597056 	  Loss: 1.6101796967967439 	 Accuracy: 0.19165580182529335
Delta: 3.609986585650101e-05 	  Loss: 1.6101211280956669 	 Accuracy: 0.19165580182529335
Delta: 0.0009845997622428661 	  Loss: 1.6102300453710252 	 Accuracy: 0.19295958279009126
Delta: 0.0026086234747543058 	  Loss: 1.6102471012303425 	 Accuracy: 0.19165580182529335
Delta: 0.0016557744074838891 	  Loss: 1.6100780601103708 	 Accuracy: 0.19035202086049544
Delta: 0.0007999440015370281 	  Loss: 1.6103287781651094 	 Accuracy: 0.18513689700130379
Delta: 0.0035859559578522793 	  Loss: 1.6113900831124042 	 Accuracy: 0.19035202086049544
Delta: 0.0036540870228254046 	  Loss: 1.6118011107305965 	 Accuracy: 0.19165580182529335
Delta: 0.001423849456547977 	  Loss: 1.611739755840482 	 Accuracy: 0.19035202086049544
Delta: 0.002006535912270284 	  Loss: 1.6116773050616917 	 Accuracy: 0.19035202086049544
Delta: 3.4575978864022486e-05 	  Loss: 1.6117112440495183 	 Accuracy: 0.19035202086049544
Delta: 0.001681083899192467 	  Loss: 1.612149643617752 	 Accuracy: 0.19295958279009126
Delta: 0.0001230936974593204 	  Loss: 1.6117035907181025 	 Accuracy: 0.19035202086049544
Delta: 0.001227306639964517 	  Loss: 1.6123564386764244 	 Accuracy: 0.19035202086049544
Delta: 0.0008284924690991543 	  Loss: 1.6122432932872153 	 Accuracy: 0.1877444589308996
Delta: 0.003747288586841214 	  Loss: 1.612913245371063 	 Accuracy: 0.19035202086049544
Delta: 0.000563992759223177 	  Loss: 1.6129504068334921 	 Accuracy: 0.19165580182529335
Delta: 0.0020818363000845073 	  Loss: 1.6126064389815464 	 Accuracy: 0.19165580182529335
Delta: 0.003937319905274091 	  Loss: 1.6117128305921378 	 Accuracy: 0.18904823989569752
Delta: 0.0019680728528246737 	  Loss: 1.6122594907841343 	 Accuracy: 0.19035202086049544
Delta: 0.003752937589755415 	  Loss: 1.6119065550919405 	 Accuracy: 0.19165580182529335
Delta: 0.003617487191498779 	  Loss: 1.6125304382876076 	 Accuracy: 0.19035202086049544
Delta: 0.0007688432736243106 	  Loss: 1.6125418216574472 	 Accuracy: 0.19035202086049544
Delta: 0.0029997948543032268 	  Loss: 1.6121586029506445 	 Accuracy: 0.19165580182529335
Delta: 0.021189230608415027 	  Loss: 2.1582348487772913 	 Accuracy: 0.1864406779661017
Delta: 0.01919441952616921 	  Loss: 2.049533669270817 	 Accuracy: 0.27249022164276404
Delta: 0.018378411292034026 	  Loss: 1.84903159602242 	 Accuracy: 0.35071707953063885
Delta: 0.015987442500347736 	  Loss: 1.7174310128891865 	 Accuracy: 0.32073011734028684
Delta: 0.01213339007810157 	  Loss: 1.6788112330367686 	 Accuracy: 0.32333767926988266
Delta: 0.009729653692934841 	  Loss: 1.6702861030747918 	 Accuracy: 0.3155149934810952

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007768294311375985 	  Loss: 1.6670768509633596 	 Accuracy: 0.3089960886571056
Delta: 0.0074988371333695346 	  Loss: 1.6661216863656112 	 Accuracy: 0.3089960886571056
Delta: 0.004445443032175098 	  Loss: 1.666032830602856 	 Accuracy: 0.3076923076923077
Delta: 0.003570398416563403 	  Loss: 1.6659337055213919 	 Accuracy: 0.3076923076923077
Delta: 0.004464077271671554 	  Loss: 1.6658299281686 	 Accuracy: 0.3089960886571056
Delta: 0.004420619870291883 	  Loss: 1.665049899017828 	 Accuracy: 0.31029986962190353
Delta: 0.0030646364555366747 	  Loss: 1.6650643827619258 	 Accuracy: 0.3089960886571056
Delta: 0.003151994572388335 	  Loss: 1.6651147252853766 	 Accuracy: 0.3089960886571056
Delta: 0.0027956855902913007 	  Loss: 1.6651962558827933 	 Accuracy: 0.3089960886571056
Delta: 0.0016364721027838697 	  Loss: 1.6653041119310719 	 Accuracy: 0.3076923076923077
Delta: 0.0037532597779346027 	  Loss: 1.6651144598942076 	 Accuracy: 0.3089960886571056
Delta: 0.0024744966144991582 	  Loss: 1.6649851145539554 	 Accuracy: 0.31029986962190353
Delta: 0.0024908689468996995 	  Loss: 1.6647404994654824 	 Accuracy: 0.3220338983050847
Delta: 0.0025529114964521213 	  Loss: 1.6647326689580166 	 Accuracy: 0.31029986962190353
Delta: 0.0010682307949293557 	  Loss: 1.664983955991889 	 Accuracy: 0.3050847457627119
Delta: 0.0014408117131160237 	  Loss: 1.6651823948593063 	 Accuracy: 0.3089960886571056
Delta: 0.002337016084052726 	  Loss: 1.6652306221467157 	 Accuracy: 0.30638852672750977
Delta: 0.005122431553095183 	  Loss: 1.6656440087999176 	 Accuracy: 0.30638852672750977
Delta: 0.005241885961665853 	  Loss: 1.665982255473117 	 Accuracy: 0.3076923076923077
Delta: 0.0019204327183563656 	  Loss: 1.66572413352011 	 Accuracy: 0.3076923076923077
Delta: 0.003900643674145868 	  Loss: 1.6657601863014286 	 Accuracy: 0.3089960886571056
Delta: 0.0023980135937902622 	  Loss: 1.6658575229952415 	 Accuracy: 0.30638852672750977
Delta: 0.005421084966357028 	  Loss: 1.665238066194373 	 Accuracy: 0.3076923076923077
Delta: 0.005690383299461071 	  Loss: 1.664661471197201 	 Accuracy: 0.3089960886571056
Delta: 0.005093659578054715 	  Loss: 1.6656410612882224 	 Accuracy: 0.3116036505867014
Delta: 0.003026289421046681 	  Loss: 1.6652985938165332 	 Accuracy: 0.3089960886571056
Delta: 0.0023372177613342495 	  Loss: 1.665128947578192 	 Accuracy: 0.3089960886571056
Delta: 0.0007915542975228655 	  Loss: 1.6651032133356343 	 Accuracy: 0.3089960886571056
Delta: 1.979706500587465e-05 	  Loss: 1.6650058896756246 	 Accuracy: 0.3089960886571056
Delta: 0.002078785449413882 	  Loss: 1.6647972347999849 	 Accuracy: 0.3089960886571056
Delta: 0.0007848533550654423 	  Loss: 1.6654032528805196 	 Accuracy: 0.3089960886571056
Delta: 0.003937256118443833 	  Loss: 1.6653752974185867 	 Accuracy: 0.3089960886571056
Delta: 7.2111172086884e-05 	  Loss: 1.6654954519348235 	 Accuracy: 0.3089960886571056
Delta: 0.0020689996712092394 	  Loss: 1.6660621520920418 	 Accuracy: 0.3089960886571056
Delta: 0.0001202193267538752 	  Loss: 1.6659303597348092 	 Accuracy: 0.3089960886571056
Delta: 0.0015442289649602794 	  Loss: 1.665632613073377 	 Accuracy: 0.30638852672750977
Delta: 0.004183527862861373 	  Loss: 1.665455453506046 	 Accuracy: 0.3089960886571056
Delta: 0.0012332949034881396 	  Loss: 1.665617914488911 	 Accuracy: 0.3076923076923077
Delta: 0.0018386862820616145 	  Loss: 1.6655616850723836 	 Accuracy: 0.3076923076923077
Delta: 0.003344671444468184 	  Loss: 1.6649980392413495 	 Accuracy: 0.3076923076923077
Delta: 0.005254941199311891 	  Loss: 1.6643507621013627 	 Accuracy: 0.30638852672750977
Delta: 0.004715119189041826 	  Loss: 1.6654690425243497 	 Accuracy: 0.30638852672750977
Delta: 0.0032225292174064895 	  Loss: 1.6650505868877872 	 Accuracy: 0.30247718383311606
Delta: 1.4613440051270795e-05 	  Loss: 1.6650597306015396 	 Accuracy: 0.30638852672750977
Delta: 0.0041032273820491814 	  Loss: 1.6647488292470585 	 Accuracy: 0.30638852672750977
Delta: 0.0028187505638772453 	  Loss: 1.6644438182803156 	 Accuracy: 0.3050847457627119
Delta: 0.004596727944107414 	  Loss: 1.665795521425333 	 Accuracy: 0.3050847457627119
Delta: 0.004507832168430683 	  Loss: 1.6658417058908381 	 Accuracy: 0.3050847457627119
Delta: 0.0006160051134806272 	  Loss: 1.665876534899643 	 Accuracy: 0.30378096479791394
Delta: 0.0027574977300538137 	  Loss: 1.6658419085854803 	 Accuracy: 0.30247718383311606
Delta: 0.0029526435181548376 	  Loss: 1.6661670248451652 	 Accuracy: 0.30378096479791394
Delta: 0.002709591713232197 	  Loss: 1.6660169046472566 	 Accuracy: 0.3050847457627119
Delta: 0.0016354538913716955 	  Loss: 1.665620644397987 	 Accuracy: 0.3050847457627119
Delta: 0.001519081868425329 	  Loss: 1.6659543505529064 	 Accuracy: 0.3076923076923077
Delta: 0.003013640408211031 	  Loss: 1.665547198654444 	 Accuracy: 0.3089960886571056
Delta: 0.003542006605794435 	  Loss: 1.6659310632989535 	 Accuracy: 0.3076923076923077
Delta: 0.00446971466050678 	  Loss: 1.6662867339655256 	 Accuracy: 0.30638852672750977
Delta: 0.0025188565062190644 	  Loss: 1.66643908993585 	 Accuracy: 0.3076923076923077
Delta: 0.0027972884283650424 	  Loss: 1.6667253161645594 	 Accuracy: 0.30638852672750977
Delta: 9.535532921777545e-05 	  Loss: 1.6665160447182628 	 Accuracy: 0.30247718383311606
Delta: 0.006137180725977373 	  Loss: 1.666279843021581 	 Accuracy: 0.3050847457627119
Delta: 0.003955333568942773 	  Loss: 1.666678241444485 	 Accuracy: 0.3050847457627119
Delta: 3.2619714510825134e-05 	  Loss: 1.6666524826390383 	 Accuracy: 0.31681877444589307
Delta: 0.004158276045732707 	  Loss: 1.6667973877198907 	 Accuracy: 0.30638852672750977
Delta: 0.0032471785842672204 	  Loss: 1.6672458791105176 	 Accuracy: 0.3089960886571056
Delta: 0.006001071974483159 	  Loss: 1.6669377392569737 	 Accuracy: 0.30638852672750977
Delta: 0.0037174736100476715 	  Loss: 1.6669194045138962 	 Accuracy: 0.3050847457627119
Delta: 0.0016846475094588237 	  Loss: 1.6674978262908495 	 Accuracy: 0.3076923076923077
Delta: 0.0027949065456307613 	  Loss: 1.667880652339102 	 Accuracy: 0.3050847457627119
Delta: 0.0049841197606764085 	  Loss: 1.6690292475734023 	 Accuracy: 0.30638852672750977
Delta: 0.0036318323888562118 	  Loss: 1.6682453018387822 	 Accuracy: 0.3050847457627119
Delta: 0.004029439822175554 	  Loss: 1.6697645863037471 	 Accuracy: 0.30378096479791394
Delta: 0.0031483179601347368 	  Loss: 1.6698687276989514 	 Accuracy: 0.30378096479791394
Delta: 0.002124384850885018 	  Loss: 1.669557647991291 	 Accuracy: 0.30638852672750977
Delta: 0.003534847378116823 	  Loss: 1.6697264606310278 	 Accuracy: 0.3050847457627119
Delta: 0.002932288337179081 	  Loss: 1.669802313440479 	 Accuracy: 0.3050847457627119
Delta: 0.0008438124538490906 	  Loss: 1.669567605902016 	 Accuracy: 0.30378096479791394
Delta: 0.0006614043643043732 	  Loss: 1.6697135407199704 	 Accuracy: 0.3011734028683181
Delta: 0.004951446572070004 	  Loss: 1.6703747501495054 	 Accuracy: 0.3011734028683181
Delta: 0.002147859616919035 	  Loss: 1.6704824110865095 	 Accuracy: 0.3011734028683181
Delta: 0.002470243693135282 	  Loss: 1.6709780052825574 	 Accuracy: 0.3011734028683181
Delta: 0.0024482394035493615 	  Loss: 1.671122145399967 	 Accuracy: 0.29595827900912647
Delta: 0.0047675189286597005 	  Loss: 1.6717102417085017 	 Accuracy: 0.29986962190352023
Delta: 0.006671009836107799 	  Loss: 1.673656329946224 	 Accuracy: 0.29986962190352023
Delta: 0.00472798400187648 	  Loss: 1.6736729381374222 	 Accuracy: 0.29986962190352023
Delta: 0.0022873925900712294 	  Loss: 1.6733482706003864 	 Accuracy: 0.29726205997392435
Delta: 0.006925996646224506 	  Loss: 1.6725172869920735 	 Accuracy: 0.29726205997392435
Delta: 0.003936135759965733 	  Loss: 1.6725202566503627 	 Accuracy: 0.29986962190352023
Delta: 0.0054593719050463445 	  Loss: 1.6730937195704056 	 Accuracy: 0.2985658409387223
Delta: 0.0023921088981207076 	  Loss: 1.6734510357396124 	 Accuracy: 0.2985658409387223
Delta: 0.0018162006438435655 	  Loss: 1.6733487668349878 	 Accuracy: 0.2985658409387223
Delta: 2.9329110853616058e-05 	  Loss: 1.6733697640573515 	 Accuracy: 0.3011734028683181
Delta: 0.002119483522762147 	  Loss: 1.6729685148867546 	 Accuracy: 0.2985658409387223
Delta: 0.0020880579941244598 	  Loss: 1.6733545765322115 	 Accuracy: 0.2985658409387223
Delta: 0.020948081340665354 	  Loss: 2.157518444320613 	 Accuracy: 0.19295958279009126
Delta: 0.019208123310854558 	  Loss: 2.0470691627708963 	 Accuracy: 0.2320730117340287
Delta: 0.018316339732182826 	  Loss: 1.8638991201929 	 Accuracy: 0.27249022164276404
Delta: 0.01698109447603887 	  Loss: 1.7296346333511534 	 Accuracy: 0.23989569752281617
Delta: 0.01371744088400429 	  Loss: 1.6661682704267888 	 Accuracy: 0.2242503259452412
Delta: 0.011280850904084355 	  Loss: 1.6415292888468411 	 Accuracy: 0.2255541069100391

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008339264577519618 	  Loss: 1.6336259949745224 	 Accuracy: 0.21251629726205998
Delta: 0.00662226007715155 	  Loss: 1.6303156048609462 	 Accuracy: 0.21121251629726207
Delta: 0.004184841228631508 	  Loss: 1.629764011642771 	 Accuracy: 0.21251629726205998
Delta: 0.002556471439226976 	  Loss: 1.6302235317271196 	 Accuracy: 0.20990873533246415
Delta: 0.0034773082013832843 	  Loss: 1.6300225129774022 	 Accuracy: 0.20990873533246415
Delta: 0.0025344537444954617 	  Loss: 1.6301947119511209 	 Accuracy: 0.20860495436766624
Delta: 0.002007578903291581 	  Loss: 1.6297563510388957 	 Accuracy: 0.20860495436766624
Delta: 0.0015898326637049124 	  Loss: 1.6297414308911073 	 Accuracy: 0.20860495436766624
Delta: 0.001295071482923525 	  Loss: 1.6298396596560476 	 Accuracy: 0.20730117340286833
Delta: 0.0017191605852186135 	  Loss: 1.6298501651833437 	 Accuracy: 0.20860495436766624
Delta: 0.0009781956262504934 	  Loss: 1.629701375711289 	 Accuracy: 0.20860495436766624
Delta: 0.0012355064869159905 	  Loss: 1.6294953164951045 	 Accuracy: 0.20860495436766624
Delta: 0.0034970770982856343 	  Loss: 1.6306114014072035 	 Accuracy: 0.20860495436766624
Delta: 0.0025374792248112057 	  Loss: 1.6299394596423444 	 Accuracy: 0.20860495436766624
Delta: 0.0026755598193776422 	  Loss: 1.6305434913502737 	 Accuracy: 0.20860495436766624
Delta: 0.001571934147935755 	  Loss: 1.6297372733760134 	 Accuracy: 0.20860495436766624
Delta: 0.0021677010674330454 	  Loss: 1.629847960167618 	 Accuracy: 0.20990873533246415
Delta: 0.0020290400426911073 	  Loss: 1.6305753214056136 	 Accuracy: 0.20860495436766624
Delta: 0.000663951241471243 	  Loss: 1.630418737569951 	 Accuracy: 0.2046936114732725
Delta: 0.001265008799790839 	  Loss: 1.6305562560801699 	 Accuracy: 0.20860495436766624
Delta: 0.0021537146739033773 	  Loss: 1.6304872733206515 	 Accuracy: 0.20860495436766624
Delta: 0.0018983770326847767 	  Loss: 1.630566362323147 	 Accuracy: 0.20599739243807041
Delta: 0.0018806968321295801 	  Loss: 1.6302995260876565 	 Accuracy: 0.20990873533246415
Delta: 0.0025018588102160015 	  Loss: 1.6295000950376037 	 Accuracy: 0.20990873533246415
Delta: 0.0005233066721389847 	  Loss: 1.6295694521081758 	 Accuracy: 0.20860495436766624
Delta: 3.6988635363828145e-05 	  Loss: 1.6294730918448161 	 Accuracy: 0.20860495436766624
Delta: 0.0041306007096112715 	  Loss: 1.6288135038316702 	 Accuracy: 0.20599739243807041
Delta: 0.0014671732083565482 	  Loss: 1.6285043214941637 	 Accuracy: 0.20860495436766624
Delta: 0.0008377643488668153 	  Loss: 1.6286104087971074 	 Accuracy: 0.21121251629726207
Delta: 0.003236137224559472 	  Loss: 1.6290862227713756 	 Accuracy: 0.20990873533246415
Delta: 0.003426072140846699 	  Loss: 1.6296795271641646 	 Accuracy: 0.21121251629726207
Delta: 0.0024248867005977823 	  Loss: 1.6293482428252462 	 Accuracy: 0.20990873533246415
Delta: 0.0006754982761504242 	  Loss: 1.629497250275223 	 Accuracy: 0.20990873533246415
Delta: 0.002174696723787446 	  Loss: 1.6288077414373043 	 Accuracy: 0.20990873533246415
Delta: 0.003793325135114889 	  Loss: 1.6279479923061908 	 Accuracy: 0.20990873533246415
Delta: 0.0027006411675471777 	  Loss: 1.6286491190517207 	 Accuracy: 0.20990873533246415
Delta: 0.0020340898584619927 	  Loss: 1.6284210098585348 	 Accuracy: 0.21121251629726207
Delta: 0.0012769185652983868 	  Loss: 1.6286264892872337 	 Accuracy: 0.21121251629726207
Delta: 0.004876162564275774 	  Loss: 1.6283579660729979 	 Accuracy: 0.2138200782268579
Delta: 0.004415301367971254 	  Loss: 1.6280544040234068 	 Accuracy: 0.21251629726205998
Delta: 0.003515661808563637 	  Loss: 1.62811504041017 	 Accuracy: 0.2151238591916558
Delta: 0.003044118106948825 	  Loss: 1.6280457698005402 	 Accuracy: 0.21251629726205998
Delta: 0.002241657255617136 	  Loss: 1.6283039849122258 	 Accuracy: 0.2138200782268579
Delta: 0.0032091326742667023 	  Loss: 1.628236775041016 	 Accuracy: 0.2151238591916558
Delta: 0.0014644776662905649 	  Loss: 1.6281887485603117 	 Accuracy: 0.2138200782268579
Delta: 7.812733860034148e-06 	  Loss: 1.6281989830963317 	 Accuracy: 0.2138200782268579
Delta: 9.522210080593394e-05 	  Loss: 1.6283002414222005 	 Accuracy: 0.21642764015645372
Delta: 0.003226293377728418 	  Loss: 1.6284302258455186 	 Accuracy: 0.21251629726205998
Delta: 0.002825948611958391 	  Loss: 1.6278465371954538 	 Accuracy: 0.2151238591916558
Delta: 0.0017629108243612378 	  Loss: 1.6283204801479445 	 Accuracy: 0.2138200782268579
Delta: 0.0021648861025645445 	  Loss: 1.6277404735049752 	 Accuracy: 0.2138200782268579
Delta: 0.0016318737250190704 	  Loss: 1.6278341140263093 	 Accuracy: 0.2138200782268579
Delta: 0.003146548739027199 	  Loss: 1.6274094147684144 	 Accuracy: 0.2138200782268579
Delta: 4.1328552738014384e-05 	  Loss: 1.6273160345551765 	 Accuracy: 0.21251629726205998
Delta: 0.0010720034826834247 	  Loss: 1.6270216812643317 	 Accuracy: 0.2138200782268579
Delta: 0.0006841475955340758 	  Loss: 1.6272273800828982 	 Accuracy: 0.2138200782268579
Delta: 0.0007280348317529699 	  Loss: 1.627115633963877 	 Accuracy: 0.20990873533246415
Delta: 0.005432204764806512 	  Loss: 1.6273468926442787 	 Accuracy: 0.21642764015645372
Delta: 0.004493689898290804 	  Loss: 1.626858359228439 	 Accuracy: 0.21251629726205998
Delta: 0.002124725205845464 	  Loss: 1.6271176248280004 	 Accuracy: 0.2151238591916558
Delta: 0.004639177982659306 	  Loss: 1.6293062688609923 	 Accuracy: 0.21642764015645372
Delta: 0.0035610067716440896 	  Loss: 1.6293532208311239 	 Accuracy: 0.2151238591916558
Delta: 0.0019618160837133634 	  Loss: 1.6295050845660932 	 Accuracy: 0.2151238591916558
Delta: 0.004384311953064102 	  Loss: 1.6281341098735127 	 Accuracy: 0.2138200782268579
Delta: 0.0017960488638718837 	  Loss: 1.628047422682151 	 Accuracy: 0.21251629726205998
Delta: 1.6632417842797515e-05 	  Loss: 1.628031909019783 	 Accuracy: 0.21251629726205998
Delta: 0.0037728653821084597 	  Loss: 1.6285841362603022 	 Accuracy: 0.21251629726205998
Delta: 0.001351565057210427 	  Loss: 1.6283900370718136 	 Accuracy: 0.21251629726205998
Delta: 0.0008194239263291331 	  Loss: 1.6283606171519085 	 Accuracy: 0.21121251629726207
Delta: 3.723488920006661e-05 	  Loss: 1.628366597002559 	 Accuracy: 0.21251629726205998
Delta: 3.4100907170582485e-05 	  Loss: 1.6284337027586835 	 Accuracy: 0.20990873533246415
Delta: 0.00201293576737878 	  Loss: 1.6285079183234985 	 Accuracy: 0.2151238591916558
Delta: 0.003651465367568342 	  Loss: 1.6274972116378317 	 Accuracy: 0.2151238591916558
Delta: 0.0036930785974708807 	  Loss: 1.6275080204522858 	 Accuracy: 0.2138200782268579
Delta: 0.004204495273232876 	  Loss: 1.627335821048871 	 Accuracy: 0.2138200782268579
Delta: 0.0015611884643015371 	  Loss: 1.627635509121012 	 Accuracy: 0.2151238591916558
Delta: 0.002660842878507259 	  Loss: 1.6273274294990059 	 Accuracy: 0.21251629726205998
Delta: 0.004217135716895257 	  Loss: 1.6287064800275846 	 Accuracy: 0.21121251629726207
Delta: 0.004551739582660073 	  Loss: 1.628164691876957 	 Accuracy: 0.22946544980443284
Delta: 0.004326711496553169 	  Loss: 1.6294126534346363 	 Accuracy: 0.2151238591916558
Delta: 0.004904646990576168 	  Loss: 1.6299215329291914 	 Accuracy: 0.21773142112125163
Delta: 0.007860783031315184 	  Loss: 1.6312672472472833 	 Accuracy: 0.21903520208604954
Delta: 0.007605585710142583 	  Loss: 1.6298394936566654 	 Accuracy: 0.21903520208604954
Delta: 0.002121991477294154 	  Loss: 1.629674307334775 	 Accuracy: 0.21642764015645372
Delta: 0.00229656980153367 	  Loss: 1.6297892407429733 	 Accuracy: 0.21251629726205998
Delta: 0.003960777663124189 	  Loss: 1.6322314774955864 	 Accuracy: 0.21903520208604954
Delta: 4.8605200732913384e-05 	  Loss: 1.6323397598785703 	 Accuracy: 0.21642764015645372
Delta: 0.004801262109733532 	  Loss: 1.63443088990508 	 Accuracy: 0.2138200782268579
Delta: 0.004061440117769332 	  Loss: 1.6332807975344896 	 Accuracy: 0.21903520208604954
Delta: 0.0048345894034620245 	  Loss: 1.6320995559581215 	 Accuracy: 0.21642764015645372
Delta: 0.0033718099826395486 	  Loss: 1.633087269974876 	 Accuracy: 0.21773142112125163
Delta: 0.004091668156878067 	  Loss: 1.6305548869879212 	 Accuracy: 0.21642764015645372
Delta: 0.001332722855924519 	  Loss: 1.630564645667936 	 Accuracy: 0.21773142112125163
Delta: 3.200388942093695e-05 	  Loss: 1.6306209085217125 	 Accuracy: 0.2138200782268579
Delta: 0.0209897725981931 	  Loss: 2.1574108916093206 	 Accuracy: 0.1981747066492829
Delta: 0.019431017928204352 	  Loss: 2.0342256129058094 	 Accuracy: 0.23728813559322035
Delta: 0.019046406892962005 	  Loss: 1.8204569469471232 	 Accuracy: 0.3428943937418514
Delta: 0.016031581264545607 	  Loss: 1.675233617192681 	 Accuracy: 0.3116036505867014
Delta: 0.012132068358171162 	  Loss: 1.6269432009747846 	 Accuracy: 0.29986962190352023

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010246793172181384 	  Loss: 1.6163465079668682 	 Accuracy: 0.29595827900912647
Delta: 0.00838066626987015 	  Loss: 1.6114202830381743 	 Accuracy: 0.29465449804432853
Delta: 0.006370699669646367 	  Loss: 1.610533794330423 	 Accuracy: 0.3011734028683181
Delta: 0.004121106785490849 	  Loss: 1.6105616397146045 	 Accuracy: 0.30247718383311606
Delta: 0.004562470680564211 	  Loss: 1.6103461641755832 	 Accuracy: 0.3011734028683181
Delta: 0.0015946687661219346 	  Loss: 1.6101199728147035 	 Accuracy: 0.30247718383311606
Delta: 0.002279881935873626 	  Loss: 1.610249911663312 	 Accuracy: 0.3011734028683181
Delta: 0.0031785721894376814 	  Loss: 1.6095618474554905 	 Accuracy: 0.30247718383311606
Delta: 0.0039764861485881865 	  Loss: 1.609726677958391 	 Accuracy: 0.30378096479791394
Delta: 0.0022033009200924042 	  Loss: 1.6099729384942232 	 Accuracy: 0.3011734028683181
Delta: 0.00312442488554395 	  Loss: 1.6101104377248667 	 Accuracy: 0.2985658409387223
Delta: 0.004606729089580986 	  Loss: 1.6105154252176694 	 Accuracy: 0.3011734028683181
Delta: 0.002064535542553729 	  Loss: 1.6101914536037603 	 Accuracy: 0.3011734028683181
Delta: 0.0015964801624025555 	  Loss: 1.6101781395593782 	 Accuracy: 0.30378096479791394
Delta: 0.0023749496956607017 	  Loss: 1.6101313622073494 	 Accuracy: 0.3011734028683181
Delta: 0.0014501789359965002 	  Loss: 1.6102170004142993 	 Accuracy: 0.30247718383311606
Delta: 0.002704536668924531 	  Loss: 1.6104332262939165 	 Accuracy: 0.29986962190352023
Delta: 0.0018486762029623046 	  Loss: 1.6104038229709503 	 Accuracy: 0.29986962190352023
Delta: 0.0022777548267817077 	  Loss: 1.609886319598648 	 Accuracy: 0.3011734028683181
Delta: 0.0006622332689651832 	  Loss: 1.6100035425477337 	 Accuracy: 0.3011734028683181
Delta: 0.0016561690197699824 	  Loss: 1.610248394264039 	 Accuracy: 0.3011734028683181
Delta: 0.0015630968046963397 	  Loss: 1.6095877111289507 	 Accuracy: 0.29986962190352023
Delta: 0.0009863769217344932 	  Loss: 1.610203184477613 	 Accuracy: 0.3011734028683181
Delta: 0.000562577249533245 	  Loss: 1.6096793586313107 	 Accuracy: 0.3011734028683181
Delta: 0.001058931559471354 	  Loss: 1.6098598447089403 	 Accuracy: 0.29986962190352023
Delta: 0.003931616732068198 	  Loss: 1.6091279928206448 	 Accuracy: 0.29986962190352023
Delta: 0.0022086171064557045 	  Loss: 1.6087860224494865 	 Accuracy: 0.3011734028683181
Delta: 0.0034177580059735167 	  Loss: 1.6087165418577056 	 Accuracy: 0.3011734028683181
Delta: 0.005429548926324853 	  Loss: 1.6084714975202057 	 Accuracy: 0.29986962190352023
Delta: 0.005406244858867812 	  Loss: 1.609188809480617 	 Accuracy: 0.29726205997392435
Delta: 0.0026787439656521766 	  Loss: 1.609403099185399 	 Accuracy: 0.30247718383311606
Delta: 0.00375123093853328 	  Loss: 1.6086188446929164 	 Accuracy: 0.2985658409387223
Delta: 0.003112655567347747 	  Loss: 1.6083741046240727 	 Accuracy: 0.3011734028683181
Delta: 0.004361947439516492 	  Loss: 1.6087916237479911 	 Accuracy: 0.29595827900912647
Delta: 0.0018978783674546687 	  Loss: 1.6085512913363393 	 Accuracy: 0.29986962190352023
Delta: 0.0023640133004038284 	  Loss: 1.6081637956127741 	 Accuracy: 0.29595827900912647
Delta: 0.003131398310048957 	  Loss: 1.6077222648445308 	 Accuracy: 0.29986962190352023
Delta: 0.0030657862802330868 	  Loss: 1.6080749425682923 	 Accuracy: 0.30247718383311606
Delta: 0.002096780134057553 	  Loss: 1.6076989157288861 	 Accuracy: 0.3011734028683181
Delta: 0.0013508213311452181 	  Loss: 1.6078455655501598 	 Accuracy: 0.30247718383311606
Delta: 0.004409641266927858 	  Loss: 1.6079165099125101 	 Accuracy: 0.30247718383311606
Delta: 0.0030557590726669986 	  Loss: 1.6088150966452366 	 Accuracy: 0.30378096479791394
Delta: 0.0028337807095277605 	  Loss: 1.6092804168084354 	 Accuracy: 0.30378096479791394
Delta: 0.0009989665280015904 	  Loss: 1.6093082358553144 	 Accuracy: 0.30378096479791394
Delta: 0.0005462304384586708 	  Loss: 1.6092568390574353 	 Accuracy: 0.30378096479791394
Delta: 4.525487861305633e-05 	  Loss: 1.6092903224989934 	 Accuracy: 0.30378096479791394
Delta: 2.9484830704537033e-05 	  Loss: 1.6093043378589504 	 Accuracy: 0.30378096479791394
Delta: 3.0925954662049994e-05 	  Loss: 1.609320021241915 	 Accuracy: 0.30378096479791394
Delta: 0.004849499744792834 	  Loss: 1.6092024911999485 	 Accuracy: 0.30378096479791394
Delta: 3.5348576208848906e-05 	  Loss: 1.609247743178591 	 Accuracy: 0.30378096479791394
Delta: 0.003937985910526052 	  Loss: 1.6094403323722855 	 Accuracy: 0.30247718383311606
Delta: 0.003131203901127449 	  Loss: 1.608752978340733 	 Accuracy: 0.30378096479791394
Delta: 0.0043912030855647825 	  Loss: 1.6096515501956958 	 Accuracy: 0.3011734028683181
Delta: 0.0053672519213124135 	  Loss: 1.6095600429539347 	 Accuracy: 0.29986962190352023
Delta: 0.001773172339451764 	  Loss: 1.6096057523057177 	 Accuracy: 0.30247718383311606
Delta: 0.0030645352839615346 	  Loss: 1.6098841354232007 	 Accuracy: 0.3011734028683181
Delta: 0.0016845720984449224 	  Loss: 1.609547948574981 	 Accuracy: 0.3011734028683181
Delta: 0.001361348210193684 	  Loss: 1.6092093095571225 	 Accuracy: 0.3011734028683181
Delta: 0.0017867199040001024 	  Loss: 1.6089711307622219 	 Accuracy: 0.30247718383311606
Delta: 0.0048397136026611005 	  Loss: 1.6086469611821528 	 Accuracy: 0.30378096479791394
Delta: 0.0038198622152312385 	  Loss: 1.610748056378745 	 Accuracy: 0.3050847457627119
Delta: 0.0012101192599085564 	  Loss: 1.6109450111927917 	 Accuracy: 0.30638852672750977
Delta: 0.0005056572422774551 	  Loss: 1.6109412068700024 	 Accuracy: 0.3050847457627119
Delta: 0.00297275006248925 	  Loss: 1.6109110633970825 	 Accuracy: 0.3050847457627119
Delta: 0.002321917299405526 	  Loss: 1.6110160447349016 	 Accuracy: 0.30378096479791394
Delta: 0.004460221341349852 	  Loss: 1.610342771059798 	 Accuracy: 0.3050847457627119
Delta: 0.0023931029529919495 	  Loss: 1.6110595835097627 	 Accuracy: 0.30378096479791394
Delta: 0.004489364866590451 	  Loss: 1.6109495832435186 	 Accuracy: 0.30378096479791394
Delta: 0.0034458151879116533 	  Loss: 1.6111358830018747 	 Accuracy: 0.30378096479791394
Delta: 0.0019573054137938988 	  Loss: 1.6112673543268325 	 Accuracy: 0.30247718383311606
Delta: 0.003555755424659541 	  Loss: 1.6122217099283793 	 Accuracy: 0.30378096479791394
Delta: 0.001103233135906175 	  Loss: 1.6122015315242009 	 Accuracy: 0.30247718383311606
Delta: 0.003920807928347978 	  Loss: 1.610912026765016 	 Accuracy: 0.30378096479791394
Delta: 0.003076239016693705 	  Loss: 1.6110145515495364 	 Accuracy: 0.30247718383311606
Delta: 0.0032689886972154035 	  Loss: 1.6091181428131311 	 Accuracy: 0.30247718383311606
Delta: 7.147665214367557e-05 	  Loss: 1.6090959305172103 	 Accuracy: 0.30247718383311606
Delta: 6.933340005779915e-05 	  Loss: 1.609083136990436 	 Accuracy: 0.30247718383311606
Delta: 4.417747698235592e-05 	  Loss: 1.6090999450294372 	 Accuracy: 0.3076923076923077
Delta: 0.002940461035858122 	  Loss: 1.61094143583427 	 Accuracy: 0.30378096479791394
Delta: 4.268758778935027e-05 	  Loss: 1.6109496414655116 	 Accuracy: 0.30378096479791394
Delta: 0.0041634241658204075 	  Loss: 1.6101999547245285 	 Accuracy: 0.30378096479791394
Delta: 0.0007548390783212974 	  Loss: 1.6105153748937255 	 Accuracy: 0.30378096479791394
Delta: 6.488919993917483e-05 	  Loss: 1.6101491064134952 	 Accuracy: 0.3050847457627119
Delta: 0.0005288118269204484 	  Loss: 1.6101247723748044 	 Accuracy: 0.30378096479791394
Delta: 0.0007600452798937567 	  Loss: 1.6103092938535877 	 Accuracy: 0.30378096479791394
Delta: 4.6113832087480776e-05 	  Loss: 1.610161953776122 	 Accuracy: 0.30378096479791394
Delta: 1.7269169143963084e-07 	  Loss: 1.6101616338764542 	 Accuracy: 0.30378096479791394
Delta: 4.653555915763451e-08 	  Loss: 1.6101613103060177 	 Accuracy: 0.3011734028683181
Delta: 0.003296195001526214 	  Loss: 1.6098805415519364 	 Accuracy: 0.3011734028683181
Delta: 0.004854252841322503 	  Loss: 1.6080247399401157 	 Accuracy: 0.3011734028683181
Delta: 0.0030663341531031434 	  Loss: 1.6098544053951476 	 Accuracy: 0.29986962190352023
Delta: 0.0020178722344470585 	  Loss: 1.6097554432969083 	 Accuracy: 0.2985658409387223
Delta: 0.0013892540420666602 	  Loss: 1.609985304651476 	 Accuracy: 0.29986962190352023
Delta: 0.0016600383169166008 	  Loss: 1.609705146831277 	 Accuracy: 0.2985658409387223
Delta: 0.002373560065352698 	  Loss: 1.6079052456543996 	 Accuracy: 0.29986962190352023
Delta: 0.02107250822173964 	  Loss: 2.1560713158859937 	 Accuracy: 0.1981747066492829
Delta: 0.019232021077950003 	  Loss: 2.043701827028813 	 Accuracy: 0.2816166883963494
Delta: 0.019013553950605503 	  Loss: 1.8463377484370729 	 Accuracy: 0.3924380704041721
Delta: 0.016510898969271486 	  Loss: 1.7083898382560827 	 Accuracy: 0.34159061277705344
Delta: 0.01321120174919984 	  Loss: 1.6635212134680506 	 Accuracy: 0.3376792698826597

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01054561870374208 	  Loss: 1.6496667949123143 	 Accuracy: 0.3324641460234681
Delta: 0.00755842612527626 	  Loss: 1.6471514973939234 	 Accuracy: 0.33376792698826596
Delta: 0.005963446317255184 	  Loss: 1.645743610284806 	 Accuracy: 0.33376792698826596
Delta: 0.00426109275268911 	  Loss: 1.645688816263714 	 Accuracy: 0.3324641460234681
Delta: 0.004504763172563766 	  Loss: 1.6453647260916746 	 Accuracy: 0.3324641460234681
Delta: 0.0010655384489005558 	  Loss: 1.6453113544015001 	 Accuracy: 0.33376792698826596
Delta: 0.0019341637498771335 	  Loss: 1.6452920772447945 	 Accuracy: 0.33376792698826596
Delta: 0.001311924903043624 	  Loss: 1.6453454334357622 	 Accuracy: 0.33376792698826596
Delta: 0.0012358644452532238 	  Loss: 1.6449365767260515 	 Accuracy: 0.3350717079530639
Delta: 0.0009907197029847311 	  Loss: 1.6453814947469576 	 Accuracy: 0.33376792698826596
Delta: 0.0007489153844641677 	  Loss: 1.6451240929688367 	 Accuracy: 0.3350717079530639
Delta: 0.0016591561619418833 	  Loss: 1.6452953825030763 	 Accuracy: 0.3350717079530639
Delta: 0.0022967678426590045 	  Loss: 1.6460799932220758 	 Accuracy: 0.33376792698826596
Delta: 0.0020498014145446043 	  Loss: 1.6457728502262887 	 Accuracy: 0.3350717079530639
Delta: 0.0023811830306505136 	  Loss: 1.6452151786770766 	 Accuracy: 0.3350717079530639
Delta: 0.004769106853098074 	  Loss: 1.6441197894574517 	 Accuracy: 0.34159061277705344
Delta: 0.0009852083900798482 	  Loss: 1.6439737707793822 	 Accuracy: 0.3363754889178618
Delta: 0.0027450957056024544 	  Loss: 1.6436219333359992 	 Accuracy: 0.33376792698826596
Delta: 0.004406743361739854 	  Loss: 1.6433759726494166 	 Accuracy: 0.3376792698826597
Delta: 0.0027335256609211348 	  Loss: 1.6441991371588918 	 Accuracy: 0.3376792698826597
Delta: 0.002294426615359809 	  Loss: 1.643499034284594 	 Accuracy: 0.3376792698826597
Delta: 0.003840421714472681 	  Loss: 1.6436996192548226 	 Accuracy: 0.3376792698826597
Delta: 0.0023586977224269966 	  Loss: 1.6434914806697565 	 Accuracy: 0.3363754889178618
Delta: 0.002330668808688442 	  Loss: 1.6437170318525078 	 Accuracy: 0.3350717079530639
Delta: 0.0037744376051620115 	  Loss: 1.6433153618945808 	 Accuracy: 0.3350717079530639
Delta: 0.003060328233998278 	  Loss: 1.6438375422789617 	 Accuracy: 0.3350717079530639
Delta: 0.003695125825498988 	  Loss: 1.64378096751546 	 Accuracy: 0.3324641460234681
Delta: 0.005133369241337041 	  Loss: 1.6430564286722853 	 Accuracy: 0.33376792698826596
Delta: 0.00220986908505878 	  Loss: 1.642980202322994 	 Accuracy: 0.3350717079530639
Delta: 0.0015374513636474798 	  Loss: 1.6430335532168483 	 Accuracy: 0.3350717079530639
Delta: 0.0016318675684151638 	  Loss: 1.6428958395642552 	 Accuracy: 0.33376792698826596
Delta: 0.0014663566318348857 	  Loss: 1.6426312861627728 	 Accuracy: 0.3324641460234681
Delta: 0.0038352109512008394 	  Loss: 1.642410377438686 	 Accuracy: 0.3324641460234681
Delta: 0.0017726043062723286 	  Loss: 1.6421899744837463 	 Accuracy: 0.3363754889178618
Delta: 0.0031586131187529127 	  Loss: 1.642475300598979 	 Accuracy: 0.3272490221642764
Delta: 0.0037419678585382415 	  Loss: 1.6433491156155742 	 Accuracy: 0.3324641460234681
Delta: 0.003333348361886219 	  Loss: 1.6432010342729138 	 Accuracy: 0.33376792698826596
Delta: 0.002575440700705075 	  Loss: 1.6433217490613021 	 Accuracy: 0.33376792698826596
Delta: 0.0024216609821819824 	  Loss: 1.6436794423091594 	 Accuracy: 0.3350717079530639
Delta: 0.003919534601686704 	  Loss: 1.6439793537380305 	 Accuracy: 0.33376792698826596
Delta: 0.0013624310727538144 	  Loss: 1.6434673119492804 	 Accuracy: 0.3350717079530639
Delta: 0.0041775583437959505 	  Loss: 1.6435243509088107 	 Accuracy: 0.3363754889178618
Delta: 0.002770041346605763 	  Loss: 1.6435730911810442 	 Accuracy: 0.33376792698826596
Delta: 0.002589670945424438 	  Loss: 1.6434144713327297 	 Accuracy: 0.33116036505867014
Delta: 0.0046474025610116106 	  Loss: 1.6429894073596616 	 Accuracy: 0.33116036505867014
Delta: 0.004430651316695543 	  Loss: 1.643277274064941 	 Accuracy: 0.33376792698826596
Delta: 0.0013849466726939229 	  Loss: 1.643743125259382 	 Accuracy: 0.32985658409387225
Delta: 8.257907375232415e-05 	  Loss: 1.643741198361854 	 Accuracy: 0.3363754889178618
Delta: 0.00011180783829922147 	  Loss: 1.6433518609423166 	 Accuracy: 0.32985658409387225
Delta: 0.0007985093601659934 	  Loss: 1.6432075675606495 	 Accuracy: 0.3324641460234681
Delta: 0.0023291401387914466 	  Loss: 1.6439198959152668 	 Accuracy: 0.33116036505867014
Delta: 0.002702498953577253 	  Loss: 1.6443875738928568 	 Accuracy: 0.33116036505867014
Delta: 0.0037199878570587843 	  Loss: 1.6457238320016163 	 Accuracy: 0.33116036505867014
Delta: 0.0008178869336813944 	  Loss: 1.6453505517399691 	 Accuracy: 0.33116036505867014
Delta: 0.0010859400542125189 	  Loss: 1.6457519934578615 	 Accuracy: 0.33116036505867014
Delta: 0.002438870880522576 	  Loss: 1.6455220903404537 	 Accuracy: 0.33116036505867014
Delta: 0.0017666876357016097 	  Loss: 1.6452526299470944 	 Accuracy: 0.33116036505867014
Delta: 5.428809497561833e-05 	  Loss: 1.644981407248216 	 Accuracy: 0.33116036505867014
Delta: 0.0029468797509897286 	  Loss: 1.645382432737183 	 Accuracy: 0.32985658409387225
Delta: 0.0005269828534661293 	  Loss: 1.6454181227191318 	 Accuracy: 0.3272490221642764
Delta: 0.001287489963913409 	  Loss: 1.6452797686727996 	 Accuracy: 0.32985658409387225
Delta: 0.0030318680722069163 	  Loss: 1.6450376780041693 	 Accuracy: 0.3324641460234681
Delta: 0.0012280851287362654 	  Loss: 1.6452570684312868 	 Accuracy: 0.3324641460234681
Delta: 0.003012232027636337 	  Loss: 1.6456483057949862 	 Accuracy: 0.33116036505867014
Delta: 0.0037079298958169584 	  Loss: 1.6463610577800756 	 Accuracy: 0.3376792698826597
Delta: 0.0032358481516803444 	  Loss: 1.6454647341072923 	 Accuracy: 0.33116036505867014
Delta: 4.4508062093778796e-05 	  Loss: 1.6453435470225548 	 Accuracy: 0.3350717079530639
Delta: 0.004798074493679926 	  Loss: 1.646012080321246 	 Accuracy: 0.33116036505867014
Delta: 0.003153344635489745 	  Loss: 1.6463437815944089 	 Accuracy: 0.3324641460234681
Delta: 0.00244842241017953 	  Loss: 1.6459847463963537 	 Accuracy: 0.33116036505867014
Delta: 0.004359044539118659 	  Loss: 1.6463786300957912 	 Accuracy: 0.3285528031290743
Delta: 0.0032338522399756606 	  Loss: 1.6459959550727157 	 Accuracy: 0.3324641460234681
Delta: 0.004156201445659414 	  Loss: 1.6460605095255516 	 Accuracy: 0.33116036505867014
Delta: 0.0009706322672613279 	  Loss: 1.6457990035016532 	 Accuracy: 0.3363754889178618
Delta: 0.004718587633135462 	  Loss: 1.6448232151034574 	 Accuracy: 0.3350717079530639
Delta: 0.004611493561194512 	  Loss: 1.6462621269821534 	 Accuracy: 0.3324641460234681
Delta: 0.003547449206431205 	  Loss: 1.6462989654043552 	 Accuracy: 0.3363754889178618
Delta: 0.000739857839812618 	  Loss: 1.6465196909661437 	 Accuracy: 0.33376792698826596
Delta: 0.003498352579229973 	  Loss: 1.6459277939884993 	 Accuracy: 0.33376792698826596
Delta: 0.0010184152475839767 	  Loss: 1.645571658337668 	 Accuracy: 0.33376792698826596
Delta: 0.0010115513292755752 	  Loss: 1.6459048266825402 	 Accuracy: 0.33376792698826596
Delta: 2.71516049328186e-05 	  Loss: 1.6459401674896026 	 Accuracy: 0.33376792698826596
Delta: 0.001555325056257761 	  Loss: 1.645499065764865 	 Accuracy: 0.3363754889178618
Delta: 0.0017060997494036056 	  Loss: 1.6447565731794813 	 Accuracy: 0.3376792698826597
Delta: 1.8237834926022703e-05 	  Loss: 1.6447856194827577 	 Accuracy: 0.33376792698826596
Delta: 0.005951762892494195 	  Loss: 1.6455452722709594 	 Accuracy: 0.3363754889178618
Delta: 0.0036372794359906596 	  Loss: 1.6452954590103772 	 Accuracy: 0.3363754889178618
Delta: 0.0014174573545983954 	  Loss: 1.6451258291575768 	 Accuracy: 0.3324641460234681
Delta: 0.006036101685454944 	  Loss: 1.644327552956622 	 Accuracy: 0.33116036505867014
Delta: 0.004614721852021186 	  Loss: 1.6452273791302647 	 Accuracy: 0.33116036505867014
Delta: 0.0036919708941586383 	  Loss: 1.6447798994931624 	 Accuracy: 0.33116036505867014
Delta: 0.003744730942623249 	  Loss: 1.6447016178067522 	 Accuracy: 0.3350717079530639
Delta: 0.0030761517036625306 	  Loss: 1.6445280524012413 	 Accuracy: 0.3350717079530639
Delta: 0.0019127294577661181 	  Loss: 1.6444862178767656 	 Accuracy: 0.33376792698826596
Delta: 0.0019809439034752557 	  Loss: 1.6451849997196901 	 Accuracy: 0.33376792698826596
Delta: 0.02100654205451746 	  Loss: 2.1566501721881366 	 Accuracy: 0.196870925684485
Delta: 0.019177711551100714 	  Loss: 2.0403233515061343 	 Accuracy: 0.196870925684485
Delta: 0.01862659259271669 	  Loss: 1.8484760918793264 	 Accuracy: 0.17079530638852672
Delta: 0.016844851593641828 	  Loss: 1.7000946884723103 	 Accuracy: 0.1694915254237288
Delta: 0.013164312542067274 	  Loss: 1.6429964017610146 	 Accuracy: 0.17340286831812254

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009883964328333964 	  Loss: 1.6270444883750605 	 Accuracy: 0.17079530638852672
Delta: 0.007271070842216716 	  Loss: 1.6243392097981064 	 Accuracy: 0.1681877444589309
Delta: 0.004734138605011619 	  Loss: 1.6237892700120171 	 Accuracy: 0.1681877444589309
Delta: 0.003935239885393922 	  Loss: 1.6239181578733402 	 Accuracy: 0.1694915254237288
Delta: 0.0037197006342171842 	  Loss: 1.623432122126006 	 Accuracy: 0.17079530638852672
Delta: 0.0019553401439549875 	  Loss: 1.622968448885714 	 Accuracy: 0.1694915254237288
Delta: 0.0028051626669738793 	  Loss: 1.6236102154870822 	 Accuracy: 0.1694915254237288
Delta: 0.002437493010710221 	  Loss: 1.623602000421866 	 Accuracy: 0.17209908735332463
Delta: 0.0036427397524317453 	  Loss: 1.624136659528074 	 Accuracy: 0.16688396349413298
Delta: 0.003118539602736899 	  Loss: 1.6242883499572767 	 Accuracy: 0.1694915254237288
Delta: 0.0025232321838892626 	  Loss: 1.6237524749087031 	 Accuracy: 0.1694915254237288
Delta: 0.007424459565763417 	  Loss: 1.6220932205671037 	 Accuracy: 0.1681877444589309
Delta: 0.00331177778758318 	  Loss: 1.6220989831112114 	 Accuracy: 0.17079530638852672
Delta: 0.002770434197692599 	  Loss: 1.6220888363889383 	 Accuracy: 0.1694915254237288
Delta: 0.004601768501663412 	  Loss: 1.622649495201098 	 Accuracy: 0.1694915254237288
Delta: 0.001145231792914873 	  Loss: 1.6224400376852999 	 Accuracy: 0.1694915254237288
Delta: 0.0011299203108313352 	  Loss: 1.6226561268818462 	 Accuracy: 0.17079530638852672
Delta: 0.0036959861839762614 	  Loss: 1.6229469527140943 	 Accuracy: 0.17079530638852672
Delta: 6.724647582680211e-05 	  Loss: 1.6225486681431478 	 Accuracy: 0.16427640156453716
Delta: 0.0037555597061206866 	  Loss: 1.622743805611326 	 Accuracy: 0.17079530638852672
Delta: 0.0013649461770733893 	  Loss: 1.6228495330285768 	 Accuracy: 0.17340286831812254
Delta: 0.002224578866650204 	  Loss: 1.6229326882467061 	 Accuracy: 0.17209908735332463
Delta: 0.0036785586175818413 	  Loss: 1.6228624633613302 	 Accuracy: 0.17209908735332463
Delta: 0.0008635916849903428 	  Loss: 1.6222049432325703 	 Accuracy: 0.17209908735332463
Delta: 0.0009153987320677339 	  Loss: 1.62285524829209 	 Accuracy: 0.17209908735332463
Delta: 5.076522361003188e-05 	  Loss: 1.623049074806697 	 Accuracy: 0.17209908735332463
Delta: 5.447742027984387e-05 	  Loss: 1.6228225758000643 	 Accuracy: 0.17209908735332463
Delta: 0.0005480692100205423 	  Loss: 1.6230343634988365 	 Accuracy: 0.17079530638852672
Delta: 0.0022824486330679738 	  Loss: 1.6229423165678625 	 Accuracy: 0.17209908735332463
Delta: 0.0023042610472487953 	  Loss: 1.6228224300641148 	 Accuracy: 0.17209908735332463
Delta: 0.004872815488625656 	  Loss: 1.6227361716881514 	 Accuracy: 0.17470664928292046
Delta: 0.0036835983796467495 	  Loss: 1.6222207704429328 	 Accuracy: 0.17470664928292046
Delta: 0.003114197096169881 	  Loss: 1.6220527243611929 	 Accuracy: 0.17209908735332463
Delta: 0.0017270180566536513 	  Loss: 1.6216096180477506 	 Accuracy: 0.1694915254237288
Delta: 0.003304332671774005 	  Loss: 1.6226700177699462 	 Accuracy: 0.17079530638852672
Delta: 0.0018971736611516688 	  Loss: 1.6226235328127512 	 Accuracy: 0.1694915254237288
Delta: 0.002135310262585476 	  Loss: 1.621978424817839 	 Accuracy: 0.17340286831812254
Delta: 0.002616128066816166 	  Loss: 1.621508790794148 	 Accuracy: 0.17470664928292046
Delta: 0.004657582721734958 	  Loss: 1.621208836549585 	 Accuracy: 0.1760104302477184
Delta: 0.004419978805638215 	  Loss: 1.6208673199317207 	 Accuracy: 0.17470664928292046
Delta: 0.0009162053822518357 	  Loss: 1.621195328830566 	 Accuracy: 0.1694915254237288
Delta: 0.0040461619949218675 	  Loss: 1.6219189452019833 	 Accuracy: 0.17340286831812254
Delta: 0.0024336519811403445 	  Loss: 1.6217038085207496 	 Accuracy: 0.17470664928292046
Delta: 0.0040177927818154276 	  Loss: 1.6221112602870564 	 Accuracy: 0.17470664928292046
Delta: 0.0025731958235096354 	  Loss: 1.6225693368881275 	 Accuracy: 0.17340286831812254
Delta: 0.00297279659833284 	  Loss: 1.6225575889917518 	 Accuracy: 0.17340286831812254
Delta: 0.004014957939315597 	  Loss: 1.6233101411820332 	 Accuracy: 0.17340286831812254
Delta: 0.002414649664998788 	  Loss: 1.622350270436978 	 Accuracy: 0.1694915254237288
Delta: 0.003580058529949655 	  Loss: 1.6215465605989992 	 Accuracy: 0.17340286831812254
Delta: 0.001894437500404386 	  Loss: 1.6213517637003103 	 Accuracy: 0.17340286831812254
Delta: 9.959992956522233e-06 	  Loss: 1.621284046457824 	 Accuracy: 0.17340286831812254
Delta: 0.0012879682423215617 	  Loss: 1.621593283047019 	 Accuracy: 0.17340286831812254
Delta: 0.00207718772950907 	  Loss: 1.6210807566993517 	 Accuracy: 0.17340286831812254
Delta: 0.0010874198844707408 	  Loss: 1.6213543743790102 	 Accuracy: 0.17340286831812254
Delta: 0.0013706215346238836 	  Loss: 1.621288023233563 	 Accuracy: 0.17340286831812254
Delta: 1.2834573554616329e-05 	  Loss: 1.621296122645465 	 Accuracy: 0.17340286831812254
Delta: 3.863231915950488e-05 	  Loss: 1.6211566026536928 	 Accuracy: 0.17340286831812254
Delta: 3.6485959688726674e-05 	  Loss: 1.6212884865729058 	 Accuracy: 0.17340286831812254
Delta: 0.0021953767808683996 	  Loss: 1.622019716983278 	 Accuracy: 0.17209908735332463
Delta: 0.0036518378171621437 	  Loss: 1.6229613415281379 	 Accuracy: 0.17079530638852672
Delta: 0.000956866922380631 	  Loss: 1.622432004743819 	 Accuracy: 0.17209908735332463
Delta: 0.00195105131919133 	  Loss: 1.6220029036770809 	 Accuracy: 0.17079530638852672
Delta: 0.0018545796304262569 	  Loss: 1.6220678524314114 	 Accuracy: 0.17079530638852672
Delta: 0.001207997983369684 	  Loss: 1.6219529983395091 	 Accuracy: 0.17209908735332463
Delta: 0.00010675550134280313 	  Loss: 1.622386221065514 	 Accuracy: 0.17340286831812254
Delta: 3.270911934664529e-05 	  Loss: 1.6222918218254831 	 Accuracy: 0.17209908735332463
Delta: 8.877651651597255e-05 	  Loss: 1.6218432845814892 	 Accuracy: 0.17340286831812254
Delta: 0.0005267822485933645 	  Loss: 1.6218709548649837 	 Accuracy: 0.17079530638852672
Delta: 4.356745988845089e-05 	  Loss: 1.6218566044542384 	 Accuracy: 0.17209908735332463
Delta: 2.025932118090454e-05 	  Loss: 1.6218434872383676 	 Accuracy: 0.17470664928292046
Delta: 0.004967103682218771 	  Loss: 1.6221615289502562 	 Accuracy: 0.17340286831812254
Delta: 2.2118321237457507e-05 	  Loss: 1.6221731611260828 	 Accuracy: 0.17340286831812254
Delta: 0.003922451813703921 	  Loss: 1.620682630899567 	 Accuracy: 0.17340286831812254
Delta: 0.0021363988962991376 	  Loss: 1.621230176561628 	 Accuracy: 0.17209908735332463
Delta: 0.0034183069512899278 	  Loss: 1.6206164424368459 	 Accuracy: 0.17079530638852672
Delta: 0.004308162840453427 	  Loss: 1.6214426794595955 	 Accuracy: 0.17340286831812254
Delta: 0.004889887464131786 	  Loss: 1.6211001807959304 	 Accuracy: 0.17340286831812254
Delta: 0.004862899291841656 	  Loss: 1.620560118158425 	 Accuracy: 0.17340286831812254
Delta: 0.002265516220723784 	  Loss: 1.6213119444360364 	 Accuracy: 0.1760104302477184
Delta: 0.0050916768885542465 	  Loss: 1.6222942690469069 	 Accuracy: 0.1760104302477184
Delta: 0.0017582262117306605 	  Loss: 1.6229848093754915 	 Accuracy: 0.1773142112125163
Delta: 0.00669080497347684 	  Loss: 1.6195939385053215 	 Accuracy: 0.1760104302477184
Delta: 0.004613206686006177 	  Loss: 1.6197986421612152 	 Accuracy: 0.17861799217731422
Delta: 0.00551625186320286 	  Loss: 1.6202457196600961 	 Accuracy: 0.1760104302477184
Delta: 0.0034428775215767284 	  Loss: 1.620541328365457 	 Accuracy: 0.17470664928292046
Delta: 0.001625898554455375 	  Loss: 1.6200748907826752 	 Accuracy: 0.1773142112125163
Delta: 0.0012347630725247504 	  Loss: 1.6205926919378912 	 Accuracy: 0.17861799217731422
Delta: 0.0038981743441511346 	  Loss: 1.619779684039179 	 Accuracy: 0.1773142112125163
Delta: 0.0010502298698747633 	  Loss: 1.6196142888297582 	 Accuracy: 0.1760104302477184
Delta: 0.0009259330568781901 	  Loss: 1.6198792439246121 	 Accuracy: 0.1760104302477184
Delta: 0.0027532870226937376 	  Loss: 1.6203037740849604 	 Accuracy: 0.1760104302477184
Delta: 0.001971537121830138 	  Loss: 1.620287372417482 	 Accuracy: 0.1760104302477184
Delta: 0.0010304040033134892 	  Loss: 1.6202988489916659 	 Accuracy: 0.1760104302477184
Delta: 0.0023952637710504265 	  Loss: 1.6195665025772539 	 Accuracy: 0.1760104302477184
Delta: 0.0054535228871940445 	  Loss: 1.6186593484521112 	 Accuracy: 0.17470664928292046
Delta: 0.02097593066085312 	  Loss: 2.1572278784604144 	 Accuracy: 0.19426336375488917
Delta: 0.01912101397886774 	  Loss: 2.0434957321546983 	 Accuracy: 0.20730117340286833
Delta: 0.01894207246777149 	  Loss: 1.8457705107933127 	 Accuracy: 0.23989569752281617
Delta: 0.016287881192996918 	  Loss: 1.725561217336347 	 Accuracy: 0.21773142112125163
Delta: 0.012399543177560531 	  Loss: 1.6913387487986107 	 Accuracy: 0.20730117340286833

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010530761067209187 	  Loss: 1.6819600038903153 	 Accuracy: 0.20599739243807041
Delta: 0.008064725618724292 	  Loss: 1.6783820720299683 	 Accuracy: 0.2046936114732725
Delta: 0.004351360548799826 	  Loss: 1.6782534645706062 	 Accuracy: 0.20599739243807041
Delta: 0.0040307978159857755 	  Loss: 1.6780992654175684 	 Accuracy: 0.2033898305084746
Delta: 0.002658661520827105 	  Loss: 1.6782166920164556 	 Accuracy: 0.2033898305084746
Delta: 0.0028585230477664292 	  Loss: 1.6782289606144762 	 Accuracy: 0.2033898305084746
Delta: 0.003259349728696153 	  Loss: 1.6784462234751973 	 Accuracy: 0.2033898305084746
Delta: 0.000532935939805759 	  Loss: 1.6786051637529902 	 Accuracy: 0.2033898305084746
Delta: 4.052851614538959e-05 	  Loss: 1.6785383890776049 	 Accuracy: 0.20208604954367665
Delta: 0.004661805730777023 	  Loss: 1.6779963195944112 	 Accuracy: 0.2033898305084746
Delta: 0.0013431664555036101 	  Loss: 1.6781138095686174 	 Accuracy: 0.2033898305084746
Delta: 2.833455728600314e-05 	  Loss: 1.6782160820178014 	 Accuracy: 0.2033898305084746
Delta: 3.143822040449526e-05 	  Loss: 1.6780597597261093 	 Accuracy: 0.2046936114732725
Delta: 1.8496944240792252e-05 	  Loss: 1.678108060345783 	 Accuracy: 0.2033898305084746
Delta: 0.0023023888860026144 	  Loss: 1.678169742938572 	 Accuracy: 0.2033898305084746
Delta: 0.0015693593468507016 	  Loss: 1.6781941729491912 	 Accuracy: 0.2033898305084746
Delta: 6.175218508004186e-05 	  Loss: 1.6782492894135517 	 Accuracy: 0.2033898305084746
Delta: 0.0016736608801797388 	  Loss: 1.678396110468443 	 Accuracy: 0.19947848761408082
Delta: 0.003782339916517923 	  Loss: 1.677948025820648 	 Accuracy: 0.2033898305084746
Delta: 0.002600901705320701 	  Loss: 1.6777666592214562 	 Accuracy: 0.20599739243807041
Delta: 0.003813589521860647 	  Loss: 1.6779160484439422 	 Accuracy: 0.2046936114732725
Delta: 0.002963207642972896 	  Loss: 1.6771319620613956 	 Accuracy: 0.2033898305084746
Delta: 0.00328360032072962 	  Loss: 1.677077345177529 	 Accuracy: 0.2033898305084746
Delta: 0.0007676983291821767 	  Loss: 1.6774261080679076 	 Accuracy: 0.20208604954367665
Delta: 0.0024615392496788366 	  Loss: 1.6784024832377837 	 Accuracy: 0.2033898305084746
Delta: 0.003918402453012012 	  Loss: 1.6779541120456645 	 Accuracy: 0.2033898305084746
Delta: 0.0028771958739505494 	  Loss: 1.6780418718652066 	 Accuracy: 0.2033898305084746
Delta: 0.0033480324922984077 	  Loss: 1.678456708709235 	 Accuracy: 0.19947848761408082
Delta: 0.0024304812068003906 	  Loss: 1.6789792015356726 	 Accuracy: 0.2046936114732725
Delta: 0.0011283596491783732 	  Loss: 1.6783288644825891 	 Accuracy: 0.20208604954367665
Delta: 0.002970487342293476 	  Loss: 1.6783022392080897 	 Accuracy: 0.2033898305084746
Delta: 0.0033886198825639037 	  Loss: 1.6790117181414925 	 Accuracy: 0.2046936114732725
Delta: 0.0032156002329929902 	  Loss: 1.6781661348466446 	 Accuracy: 0.2033898305084746
Delta: 0.0015125077231142702 	  Loss: 1.6785644384030598 	 Accuracy: 0.2033898305084746
Delta: 0.0034764464951309785 	  Loss: 1.6777383024845287 	 Accuracy: 0.2033898305084746
Delta: 0.0035403804339865608 	  Loss: 1.6776744787773787 	 Accuracy: 0.2033898305084746
Delta: 0.0018038927828926336 	  Loss: 1.6780298187796383 	 Accuracy: 0.2033898305084746
Delta: 5.4267430052247517e-05 	  Loss: 1.677804089096059 	 Accuracy: 0.20860495436766624
Delta: 0.005031529946790527 	  Loss: 1.678310581322979 	 Accuracy: 0.2033898305084746
Delta: 0.0037526380715375623 	  Loss: 1.6785381409154758 	 Accuracy: 0.20078226857887874
Delta: 0.0057537538684902835 	  Loss: 1.6796709304300306 	 Accuracy: 0.2033898305084746
Delta: 0.003021614033043957 	  Loss: 1.6796287455813816 	 Accuracy: 0.2033898305084746
Delta: 0.002554942803661332 	  Loss: 1.6793419648268166 	 Accuracy: 0.2033898305084746
Delta: 0.002564329191147235 	  Loss: 1.679971951638596 	 Accuracy: 0.2033898305084746
Delta: 0.005551943932138522 	  Loss: 1.6789853624706692 	 Accuracy: 0.20208604954367665
Delta: 0.005220908188974082 	  Loss: 1.6791507957309235 	 Accuracy: 0.20208604954367665
Delta: 0.0023452048848631676 	  Loss: 1.6792197834193994 	 Accuracy: 0.20208604954367665
Delta: 0.0042693687976424815 	  Loss: 1.678596643920744 	 Accuracy: 0.20208604954367665
Delta: 0.0027968402983702227 	  Loss: 1.6795938856037984 	 Accuracy: 0.20208604954367665
Delta: 2.9111602556158726e-05 	  Loss: 1.6795742065926893 	 Accuracy: 0.2033898305084746
Delta: 0.005986149658045002 	  Loss: 1.678752268695225 	 Accuracy: 0.20078226857887874
Delta: 0.00399959338993955 	  Loss: 1.6788673900693327 	 Accuracy: 0.20208604954367665
Delta: 0.004244112579227041 	  Loss: 1.6786074197834733 	 Accuracy: 0.20599739243807041
Delta: 0.006095848407640936 	  Loss: 1.6785705501960693 	 Accuracy: 0.20208604954367665
Delta: 0.005702055124382824 	  Loss: 1.6800385386558725 	 Accuracy: 0.21251629726205998
Delta: 0.00539619766629215 	  Loss: 1.6811325731630302 	 Accuracy: 0.21121251629726207
Delta: 0.004168798903835219 	  Loss: 1.6811610301111566 	 Accuracy: 0.2046936114732725
Delta: 0.002682776635813353 	  Loss: 1.6808732217426177 	 Accuracy: 0.2046936114732725
Delta: 0.0011136045429277492 	  Loss: 1.6808844484348584 	 Accuracy: 0.2046936114732725
Delta: 0.005117096053173234 	  Loss: 1.6806433273230688 	 Accuracy: 0.2046936114732725
Delta: 0.0044082672697919045 	  Loss: 1.6802764234150467 	 Accuracy: 0.20599739243807041
Delta: 0.004141979012925033 	  Loss: 1.679654784464276 	 Accuracy: 0.2046936114732725
Delta: 0.0017801617635741084 	  Loss: 1.6794024247100607 	 Accuracy: 0.20599739243807041
Delta: 0.0010581439089059946 	  Loss: 1.6796416403623002 	 Accuracy: 0.2033898305084746
Delta: 0.004196680422543563 	  Loss: 1.6799258002480817 	 Accuracy: 0.20599739243807041
Delta: 0.0020296418407206606 	  Loss: 1.6797704734086718 	 Accuracy: 0.2033898305084746
Delta: 0.006292255352890087 	  Loss: 1.6820005774878584 	 Accuracy: 0.2033898305084746
Delta: 0.0040527213120045 	  Loss: 1.6811597924034474 	 Accuracy: 0.20078226857887874
Delta: 0.003238095647634414 	  Loss: 1.680583815677772 	 Accuracy: 0.2046936114732725
Delta: 0.004153498106408602 	  Loss: 1.679513178264577 	 Accuracy: 0.2033898305084746
Delta: 0.004817986309793996 	  Loss: 1.6793318971393556 	 Accuracy: 0.20990873533246415
Delta: 0.002339406055162892 	  Loss: 1.6793759607069976 	 Accuracy: 0.2033898305084746
Delta: 0.0033538711258413725 	  Loss: 1.6791861972645188 	 Accuracy: 0.2046936114732725
Delta: 0.0018886968163281178 	  Loss: 1.6790887112562953 	 Accuracy: 0.2046936114732725
Delta: 0.0027372195580274506 	  Loss: 1.6789327852377869 	 Accuracy: 0.2033898305084746
Delta: 0.0010137051736959473 	  Loss: 1.6788606969729687 	 Accuracy: 0.2046936114732725
Delta: 3.319376726293438e-05 	  Loss: 1.6789170526093793 	 Accuracy: 0.20599739243807041
Delta: 0.0024956838098924967 	  Loss: 1.6787874831711114 	 Accuracy: 0.20599739243807041
Delta: 0.0007259158994940729 	  Loss: 1.678746441252044 	 Accuracy: 0.20599739243807041
Delta: 0.003856956931173246 	  Loss: 1.6785297840525673 	 Accuracy: 0.20599739243807041
Delta: 0.0012912217531345597 	  Loss: 1.678316516199779 	 Accuracy: 0.20599739243807041
Delta: 0.0027613908501317825 	  Loss: 1.6784804843502514 	 Accuracy: 0.20730117340286833
Delta: 0.0033381782994764088 	  Loss: 1.6786431433044513 	 Accuracy: 0.20730117340286833
Delta: 0.006719872853828886 	  Loss: 1.678916861144912 	 Accuracy: 0.21121251629726207
Delta: 0.005537625437276677 	  Loss: 1.6778623881076562 	 Accuracy: 0.20730117340286833
Delta: 0.0008792990356271463 	  Loss: 1.677995163971202 	 Accuracy: 0.21121251629726207
Delta: 0.00542221775777747 	  Loss: 1.6778215118478903 	 Accuracy: 0.21121251629726207
Delta: 0.004934427345707837 	  Loss: 1.6778484686780888 	 Accuracy: 0.21121251629726207
Delta: 0.002835267436048607 	  Loss: 1.6782464581137249 	 Accuracy: 0.21121251629726207
Delta: 0.0025308977581567555 	  Loss: 1.6778707233914676 	 Accuracy: 0.21121251629726207
Delta: 0.0016323522297452117 	  Loss: 1.6767728452613337 	 Accuracy: 0.21121251629726207
Delta: 0.0009875016491158746 	  Loss: 1.6768551219844474 	 Accuracy: 0.20990873533246415
Delta: 0.003952991588838138 	  Loss: 1.6767401318583297 	 Accuracy: 0.20860495436766624
Delta: 0.003223745359005054 	  Loss: 1.676766983894511 	 Accuracy: 0.21121251629726207
Delta: 0.0044178342128043955 	  Loss: 1.6765867218545196 	 Accuracy: 0.21251629726205998
Delta: 0.020899062453426646 	  Loss: 2.1569021866098645 	 Accuracy: 0.19426336375488917
Delta: 0.018632136452903965 	  Loss: 2.0639960333647984 	 Accuracy: 0.2777053455019557
Delta: 0.016003734327487282 	  Loss: 1.9486718068559474 	 Accuracy: 0.3663624511082138
Delta: 0.013502579325579678 	  Loss: 1.8509101095052483 	 Accuracy: 0.32985658409387225
Delta: 0.011910551801339278 	  Loss: 1.777545863467484 	 Accuracy: 0.30638852672750977
Delta: 0.010407315257400955 	  Loss: 1.722580658321404 	 Accuracy: 0.29986962190352023
Delta: 0.010057677551930894 	  Loss: 1.6799181156919414 	 Accuracy: 0.29595827900912647
Delta: 0.008704128869221998 	  Loss: 1.648388215792556 	 Accuracy: 0.29335071707953064
Delta: 0.008028309730563869 	  Loss: 1.6246850257790517 	 Accuracy: 0.29335071707953064
Delta: 0.007205948023602164 	  Loss: 1.6072082362888782 	 Accuracy: 0.2894393741851369
Delta: 0.0061100781900931015 	  Loss: 1.5944852639641542 	 Accuracy: 0.288135593220339
Delta: 0.005601500835378031 	  Loss: 1.5854965526769975 	 Accuracy: 0.28683181225554105
Delta: 0.005819278582349254 	  Loss: 1.5786287267403734 	 Accuracy: 0.2894393741851369
Delta: 0.004737415586978186 	  Loss: 1.5734117777487804 	 Accuracy: 0.288135593220339
Delta: 0.00556704361307348 	  Loss: 1.5693033399197565 	 Accuracy: 0.288135593220339
Delta: 0.004572050700519465 	  Loss: 1.565898078569437 	 Accuracy: 0.2894393741851369
Delta: 0.005248350314728563 	  Loss: 1.563182407655576 	 Accuracy: 0.2907431551499348
Delta: 0.004177735469238928 	  Loss: 1.5608819226023467 	 Accuracy: 0.2894393741851369
Delta: 0.004661042485406307 	  Loss: 1.5593158549164872 	 Accuracy: 0.2907431551499348
Delta: 0.004354733457741936 	  Loss: 1.5577577790233084 	 Accuracy: 0.2907431551499348
Delta: 0.0037271075836209757 	  Loss: 1.5562861201555354 	 Accuracy: 0.2907431551499348
Delta: 0.0036675885019560152 	  Loss: 1.554935375364412 	 Accuracy: 0.2907431551499348
Delta: 0.005004348703585741 	  Loss: 1.5538916155208882 	 Accuracy: 0.2907431551499348
Delta: 0.003733564658106274 	  Loss: 1.552833714459115 	 Accuracy: 0.2920469361147327

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.003990264872365527 	  Loss: 1.5520748058033296 	 Accuracy: 0.2920469361147327
Delta: 0.003065242176532654 	  Loss: 1.551434961434636 	 Accuracy: 0.2907431551499348
Delta: 0.002791855741734586 	  Loss: 1.5506946789499443 	 Accuracy: 0.2920469361147327
Delta: 0.002380283998969764 	  Loss: 1.5501604628923917 	 Accuracy: 0.2907431551499348
Delta: 0.0033647628267316943 	  Loss: 1.549659169418648 	 Accuracy: 0.2920469361147327
Delta: 0.0017632270481168452 	  Loss: 1.549252140581381 	 Accuracy: 0.2920469361147327
Delta: 0.003827014734950274 	  Loss: 1.5488587876995028 	 Accuracy: 0.2907431551499348
Delta: 0.0033859451679295475 	  Loss: 1.5485607516248288 	 Accuracy: 0.2907431551499348
Delta: 0.0016083647463674823 	  Loss: 1.5481884368682632 	 Accuracy: 0.2907431551499348
Delta: 0.002947110669109603 	  Loss: 1.5479832613748177 	 Accuracy: 0.2907431551499348
Delta: 0.0010197734705168408 	  Loss: 1.5477234265787576 	 Accuracy: 0.2907431551499348
Delta: 0.003387090362751573 	  Loss: 1.5475632586481751 	 Accuracy: 0.2907431551499348
Delta: 0.002000406022453377 	  Loss: 1.5473832091983348 	 Accuracy: 0.2920469361147327
Delta: 0.002234331169583344 	  Loss: 1.5472186634098803 	 Accuracy: 0.2907431551499348
Delta: 0.003176989034211779 	  Loss: 1.5471247654906368 	 Accuracy: 0.29335071707953064
Delta: 0.0005339747981158715 	  Loss: 1.5470636028822207 	 Accuracy: 0.2907431551499348
Delta: 0.0014202323906693096 	  Loss: 1.547029114437827 	 Accuracy: 0.2920469361147327
Delta: 0.0009503095759787372 	  Loss: 1.546914995647614 	 Accuracy: 0.2920469361147327
Delta: 0.0005257291436648375 	  Loss: 1.5467951762309395 	 Accuracy: 0.2920469361147327
Delta: 0.0020955371908630144 	  Loss: 1.5466706417952583 	 Accuracy: 0.2920469361147327
Delta: 0.0027161878377156196 	  Loss: 1.5465441139847782 	 Accuracy: 0.2920469361147327
Delta: 0.0006617820181961464 	  Loss: 1.546477521010703 	 Accuracy: 0.2920469361147327
Delta: 0.002466780279332118 	  Loss: 1.5463940018107811 	 Accuracy: 0.2920469361147327
Delta: 0.00138343367381673 	  Loss: 1.5463213618995952 	 Accuracy: 0.2920469361147327
Delta: 6.230442565822742e-05 	  Loss: 1.5462423300807073 	 Accuracy: 0.2920469361147327
Delta: 0.0006313658700949777 	  Loss: 1.54616391373923 	 Accuracy: 0.2920469361147327
Delta: 0.0010175057904552455 	  Loss: 1.5460882849583393 	 Accuracy: 0.2920469361147327
Delta: 0.0009808134594306856 	  Loss: 1.5460651688995157 	 Accuracy: 0.2907431551499348
Delta: 0.0006544281537013181 	  Loss: 1.5460743640855448 	 Accuracy: 0.2907431551499348
Delta: 0.0011464058914607746 	  Loss: 1.5459890993989402 	 Accuracy: 0.2907431551499348
Delta: 0.0007456930816077321 	  Loss: 1.5459797864412492 	 Accuracy: 0.2907431551499348
Delta: 3.810417243625488e-05 	  Loss: 1.545937337417722 	 Accuracy: 0.2920469361147327
Delta: 0.002306551281931035 	  Loss: 1.545888748181504 	 Accuracy: 0.2920469361147327
Delta: 2.9313355660847607e-05 	  Loss: 1.5458497583078854 	 Accuracy: 0.2920469361147327
Delta: 0.002005359012513986 	  Loss: 1.5457989498681037 	 Accuracy: 0.2920469361147327
Delta: 0.0026274182076315386 	  Loss: 1.5457563956070972 	 Accuracy: 0.2920469361147327
Delta: 5.1003572081902066e-05 	  Loss: 1.5457108407119986 	 Accuracy: 0.2920469361147327
Delta: 0.0005241012444025335 	  Loss: 1.5456772499030993 	 Accuracy: 0.2920469361147327
Delta: 7.052732897305456e-05 	  Loss: 1.5457072664220013 	 Accuracy: 0.2920469361147327
Delta: 2.643495648821513e-05 	  Loss: 1.5456772443348092 	 Accuracy: 0.2920469361147327
Delta: 0.0015224122803113576 	  Loss: 1.5456653662487372 	 Accuracy: 0.2920469361147327
Delta: 2.7023361045104497e-05 	  Loss: 1.5456395783958872 	 Accuracy: 0.2920469361147327
Delta: 2.1777037378355428e-05 	  Loss: 1.54560989234445 	 Accuracy: 0.2907431551499348
Delta: 0.0012160336109199683 	  Loss: 1.5455692708813045 	 Accuracy: 0.2920469361147327
Delta: 4.4381385567382445e-05 	  Loss: 1.545571968233503 	 Accuracy: 0.2907431551499348
Delta: 0.0010892235601780733 	  Loss: 1.5455698329011267 	 Accuracy: 0.2907431551499348
Delta: 0.0011045866703560106 	  Loss: 1.5455390319654414 	 Accuracy: 0.2907431551499348
Delta: 4.490089585626273e-05 	  Loss: 1.5455166312353554 	 Accuracy: 0.2907431551499348
Delta: 0.0005365973547706258 	  Loss: 1.545529328117056 	 Accuracy: 0.2907431551499348
Delta: 0.0009612135326399864 	  Loss: 1.5454723851625292 	 Accuracy: 0.2920469361147327
Delta: 0.0005293890660600128 	  Loss: 1.545448734295997 	 Accuracy: 0.2907431551499348
Delta: 0.0011927360826239858 	  Loss: 1.545432905186665 	 Accuracy: 0.2907431551499348
Delta: 0.0026078648103086076 	  Loss: 1.545392471702586 	 Accuracy: 0.2907431551499348
Delta: 0.0025271416818838303 	  Loss: 1.5453928070576435 	 Accuracy: 0.2907431551499348
Delta: 0.0018328882364699326 	  Loss: 1.5453391110288455 	 Accuracy: 0.2907431551499348
Delta: 3.088583648796613e-05 	  Loss: 1.5453070099920643 	 Accuracy: 0.2920469361147327
Delta: 4.132042943370499e-05 	  Loss: 1.545273245796261 	 Accuracy: 0.2907431551499348
Delta: 6.56695288635682e-05 	  Loss: 1.5452703920285398 	 Accuracy: 0.2907431551499348
Delta: 0.0005238749843798501 	  Loss: 1.5452577259507225 	 Accuracy: 0.2920469361147327
Delta: 2.014187776724592e-05 	  Loss: 1.545240018918864 	 Accuracy: 0.29335071707953064
Delta: 3.306693301616964e-05 	  Loss: 1.5452318713140398 	 Accuracy: 0.2907431551499348
Delta: 0.0010703360688893728 	  Loss: 1.54523566463454 	 Accuracy: 0.2907431551499348
Delta: 4.8222107371482826e-05 	  Loss: 1.5452151464841775 	 Accuracy: 0.2907431551499348
Delta: 0.0005428196748540586 	  Loss: 1.5452557739494852 	 Accuracy: 0.2907431551499348
Delta: 1.4329425104811173e-05 	  Loss: 1.5452358182452435 	 Accuracy: 0.2907431551499348
Delta: 0.0009859451555633031 	  Loss: 1.5452212732728887 	 Accuracy: 0.2907431551499348
Delta: 2.0222707114405336e-05 	  Loss: 1.5451981806679729 	 Accuracy: 0.2907431551499348
Delta: 0.0025922790656649165 	  Loss: 1.5451927743216212 	 Accuracy: 0.2907431551499348
Delta: 0.0017973997854011745 	  Loss: 1.5451882099325274 	 Accuracy: 0.2907431551499348
Delta: 0.0015073638555528645 	  Loss: 1.5451541041317847 	 Accuracy: 0.2907431551499348
Delta: 1.0523236990432426e-05 	  Loss: 1.545138574795335 	 Accuracy: 0.2920469361147327
Delta: 1.3100861836236383e-05 	  Loss: 1.5451397481162532 	 Accuracy: 0.2920469361147327
Delta: 0.000515981993620921 	  Loss: 1.5451311150406806 	 Accuracy: 0.2907431551499348
Delta: 0.0006093723084303677 	  Loss: 1.5451228452734185 	 Accuracy: 0.2907431551499348
Delta: 3.6111532997099785e-05 	  Loss: 1.5451021986902105 	 Accuracy: 0.2920469361147327
Delta: 0.0010046538539695805 	  Loss: 1.5450874771717809 	 Accuracy: 0.29335071707953064
Delta: 0.020906117044171946 	  Loss: 2.1567762962185473 	 Accuracy: 0.19556714471968709
Delta: 0.018732298738760648 	  Loss: 2.0597245041627894 	 Accuracy: 0.30638852672750977
Delta: 0.01633788527450588 	  Loss: 1.9272073839046695 	 Accuracy: 0.39765319426336376
Delta: 0.014060802241315725 	  Loss: 1.8164072212711233 	 Accuracy: 0.37809647979139505
Delta: 0.012172139826149751 	  Loss: 1.7346280012127053 	 Accuracy: 0.39765319426336376
Delta: 0.010558311635098447 	  Loss: 1.6759443964002796 	 Accuracy: 0.4758800521512386
Delta: 0.009742398920456823 	  Loss: 1.6349549871381972 	 Accuracy: 0.4784876140808344
Delta: 0.008752541478468372 	  Loss: 1.606747735198915 	 Accuracy: 0.4810951760104302
Delta: 0.007946553115770215 	  Loss: 1.5877219382711552 	 Accuracy: 0.485006518904824
Delta: 0.006964543856379509 	  Loss: 1.5750864276698588 	 Accuracy: 0.49022164276401564
Delta: 0.006390972355022033 	  Loss: 1.566788705812968 	 Accuracy: 0.5045632333767927
Delta: 0.0062411749524833434 	  Loss: 1.5608908480004617 	 Accuracy: 0.5149934810951761
Delta: 0.005575255297407662 	  Loss: 1.5566825911133968 	 Accuracy: 0.530638852672751
Delta: 0.005887011312835715 	  Loss: 1.553264433330455 	 Accuracy: 0.5280312907431551
Delta: 0.005548676057245179 	  Loss: 1.5503590262534104 	 Accuracy: 0.529335071707953
Delta: 0.005755813315880056 	  Loss: 1.5479076415740494 	 Accuracy: 0.5280312907431551
Delta: 0.004427449198119428 	  Loss: 1.5457912161303218 	 Accuracy: 0.5371577574967406

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005127092386094775 	  Loss: 1.5436197885332081 	 Accuracy: 0.5332464146023468
Delta: 0.004219539173735046 	  Loss: 1.5421667914493729 	 Accuracy: 0.5397653194263363
Delta: 0.00346654794352773 	  Loss: 1.540973186021706 	 Accuracy: 0.5384615384615384
Delta: 0.0036601140280441884 	  Loss: 1.5399861088162248 	 Accuracy: 0.5358539765319427
Delta: 0.004183577156290608 	  Loss: 1.5392158345367686 	 Accuracy: 0.5371577574967406
Delta: 0.0037787323815104187 	  Loss: 1.5386175171596121 	 Accuracy: 0.5397653194263363
Delta: 0.002493123647942087 	  Loss: 1.538279119707176 	 Accuracy: 0.5371577574967406
Delta: 0.0026754438252114604 	  Loss: 1.5378790433261487 	 Accuracy: 0.5397653194263363
Delta: 0.0033035964119621686 	  Loss: 1.537759339423888 	 Accuracy: 0.5397653194263363
Delta: 0.003397332705828687 	  Loss: 1.537458883736475 	 Accuracy: 0.5371577574967406
Delta: 0.0022517893342805188 	  Loss: 1.5372838758333047 	 Accuracy: 0.5371577574967406
Delta: 0.003125039285446042 	  Loss: 1.5371241120670014 	 Accuracy: 0.5371577574967406
Delta: 0.0035505964100854656 	  Loss: 1.5370908378748225 	 Accuracy: 0.5384615384615384
Delta: 0.00099025737763848 	  Loss: 1.5370885424106433 	 Accuracy: 0.5397653194263363
Delta: 0.0015400965149680724 	  Loss: 1.537063086742886 	 Accuracy: 0.5397653194263363
Delta: 0.0008205972173165009 	  Loss: 1.5369667996113545 	 Accuracy: 0.5397653194263363
Delta: 0.002269637395542501 	  Loss: 1.5369345940710653 	 Accuracy: 0.5397653194263363
Delta: 0.0015854009239072576 	  Loss: 1.5369238961125524 	 Accuracy: 0.5397653194263363
Delta: 0.0025326029359991472 	  Loss: 1.5368855415830378 	 Accuracy: 0.5397653194263363
Delta: 0.0015783960858350655 	  Loss: 1.5368607888967025 	 Accuracy: 0.5397653194263363
Delta: 0.002156875663061595 	  Loss: 1.5368461324599176 	 Accuracy: 0.5397653194263363
Delta: 0.0008019184530185373 	  Loss: 1.5368441877657286 	 Accuracy: 0.5397653194263363
Delta: 0.0007275290060409287 	  Loss: 1.5368458490126484 	 Accuracy: 0.5397653194263363
Delta: 0.0013679103372507373 	  Loss: 1.5368280740353508 	 Accuracy: 0.5397653194263363
Delta: 0.0019753352805617903 	  Loss: 1.5367825028480953 	 Accuracy: 0.5397653194263363
Delta: 0.0025313988061456153 	  Loss: 1.5368116056514503 	 Accuracy: 0.5397653194263363
Delta: 0.000711255478179785 	  Loss: 1.5368219639574672 	 Accuracy: 0.5397653194263363
Delta: 2.5001389295091707e-05 	  Loss: 1.536800669444546 	 Accuracy: 0.5397653194263363
Delta: 0.002584417149512771 	  Loss: 1.5367652280711106 	 Accuracy: 0.5397653194263363
Delta: 2.794984235715984e-05 	  Loss: 1.5367668045208327 	 Accuracy: 0.5397653194263363
Delta: 0.0017120668948511818 	  Loss: 1.5367877978112443 	 Accuracy: 0.5397653194263363
Delta: 0.0010286094319580425 	  Loss: 1.5367397206175757 	 Accuracy: 0.5397653194263363
Delta: 1.4568024090779646e-05 	  Loss: 1.5367723752401201 	 Accuracy: 0.5384615384615384
Delta: 2.4415114454625677e-05 	  Loss: 1.5367764162065263 	 Accuracy: 0.5397653194263363
Delta: 0.0011738471979288413 	  Loss: 1.5367514086949692 	 Accuracy: 0.5397653194263363
Delta: 0.0007214426647512229 	  Loss: 1.5368402565125068 	 Accuracy: 0.5397653194263363
Delta: 0.0014544622277474814 	  Loss: 1.5368436285615195 	 Accuracy: 0.5397653194263363
Delta: 2.1861258524548638e-05 	  Loss: 1.5368294485826612 	 Accuracy: 0.5397653194263363
Delta: 2.3538011415613318e-05 	  Loss: 1.5367794765742842 	 Accuracy: 0.5397653194263363
Delta: 2.6892102394473904e-05 	  Loss: 1.5368751755319598 	 Accuracy: 0.5397653194263363
Delta: 0.0011573868842416758 	  Loss: 1.5368855858058503 	 Accuracy: 0.5397653194263363
Delta: 1.558715959904354e-05 	  Loss: 1.5368394073619327 	 Accuracy: 0.5397653194263363
Delta: 8.664963608516856e-06 	  Loss: 1.5368824855399792 	 Accuracy: 0.5397653194263363
Delta: 3.5777302776193955e-05 	  Loss: 1.5368321238324436 	 Accuracy: 0.5397653194263363
Delta: 0.0011832468211605768 	  Loss: 1.536731529068335 	 Accuracy: 0.5397653194263363
Delta: 1.5670213385463325e-05 	  Loss: 1.5367562022221626 	 Accuracy: 0.5384615384615384
Delta: 1.3345955861076094e-05 	  Loss: 1.5367617837942134 	 Accuracy: 0.5397653194263363
Delta: 2.777448507246375e-05 	  Loss: 1.5367292583876626 	 Accuracy: 0.5397653194263363
Delta: 2.9900418310369533e-05 	  Loss: 1.536768534842345 	 Accuracy: 0.5319426336375489
Delta: 2.3706768343833117e-05 	  Loss: 1.5367175337021532 	 Accuracy: 0.5397653194263363
Delta: 3.56652052258893e-05 	  Loss: 1.5367671837728842 	 Accuracy: 0.5397653194263363
Delta: 2.023812717712514e-05 	  Loss: 1.5367027787162575 	 Accuracy: 0.5397653194263363
Delta: 2.012799238614332e-05 	  Loss: 1.5367810736700067 	 Accuracy: 0.5397653194263363
Delta: 4.161882857850385e-05 	  Loss: 1.5367584723389238 	 Accuracy: 0.5397653194263363
Delta: 3.8350742067411964e-05 	  Loss: 1.5367274820124552 	 Accuracy: 0.5384615384615384
Delta: 2.3826862627113433e-05 	  Loss: 1.5366600942643744 	 Accuracy: 0.5397653194263363
Delta: 8.568335683639548e-06 	  Loss: 1.536682634955235 	 Accuracy: 0.5397653194263363
Delta: 1.8384799085643113e-05 	  Loss: 1.5366694883465999 	 Accuracy: 0.5384615384615384
Delta: 1.559284406662307e-05 	  Loss: 1.53669787662633 	 Accuracy: 0.5397653194263363
Delta: 0.0011651417471420218 	  Loss: 1.5367139849777416 	 Accuracy: 0.5397653194263363
Delta: 3.4713772252340835e-05 	  Loss: 1.5366901096824548 	 Accuracy: 0.5410691003911343
Delta: 0.0007008612733290521 	  Loss: 1.5369547981943437 	 Accuracy: 0.5397653194263363
Delta: 0.0014490825932036988 	  Loss: 1.5367038349109992 	 Accuracy: 0.5397653194263363
Delta: 0.0016886098286846524 	  Loss: 1.536683924039353 	 Accuracy: 0.5384615384615384
Delta: 0.0016230659906851335 	  Loss: 1.5367384771644124 	 Accuracy: 0.5397653194263363
Delta: 2.3340186954643935e-05 	  Loss: 1.5367204584348908 	 Accuracy: 0.5397653194263363
Delta: 0.0016110938818728647 	  Loss: 1.5368011767886363 	 Accuracy: 0.5410691003911343
Delta: 0.0016251919735220221 	  Loss: 1.5367607375601922 	 Accuracy: 0.5397653194263363
Delta: 7.475457444215072e-05 	  Loss: 1.5366590197060597 	 Accuracy: 0.5397653194263363
Delta: 7.859604516398424e-05 	  Loss: 1.5367074767817113 	 Accuracy: 0.5397653194263363
Delta: 7.085026492603731e-05 	  Loss: 1.5367732053779433 	 Accuracy: 0.5397653194263363
Delta: 6.35840643560101e-05 	  Loss: 1.536648998784391 	 Accuracy: 0.5397653194263363
Delta: 3.962317382535945e-05 	  Loss: 1.536647610297063 	 Accuracy: 0.5397653194263363
Delta: 0.002118447771895654 	  Loss: 1.5369002403224388 	 Accuracy: 0.5397653194263363
Delta: 0.0025301017351048614 	  Loss: 1.5371194694673513 	 Accuracy: 0.5397653194263363
Delta: 0.0005466917877436611 	  Loss: 1.5371559053151866 	 Accuracy: 0.5397653194263363
Delta: 0.0012646912616275103 	  Loss: 1.5374071128219353 	 Accuracy: 0.546284224250326
Delta: 0.0015734532765579747 	  Loss: 1.5366345645697537 	 Accuracy: 0.5397653194263363
Delta: 0.0017522728302651642 	  Loss: 1.5366961658501133 	 Accuracy: 0.5384615384615384
Delta: 0.0023586934060549234 	  Loss: 1.5372922798362894 	 Accuracy: 0.5397653194263363
Delta: 0.00227722040671241 	  Loss: 1.5367338159178816 	 Accuracy: 0.5371577574967406
Delta: 0.002055785044376276 	  Loss: 1.5369066536707416 	 Accuracy: 0.5397653194263363
Delta: 0.0005321801462858305 	  Loss: 1.536801776660816 	 Accuracy: 0.5397653194263363
Delta: 0.021007034908620915 	  Loss: 2.1549931141992715 	 Accuracy: 0.20078226857887874
Delta: 0.01854528331078983 	  Loss: 2.0595551362538522 	 Accuracy: 0.3285528031290743
Delta: 0.01580602876399995 	  Loss: 1.9354769177914473 	 Accuracy: 0.4211212516297262
Delta: 0.014416917024935508 	  Loss: 1.8337011796778953 	 Accuracy: 0.4654498044328553
Delta: 0.014062608141603712 	  Loss: 1.7512581002885317 	 Accuracy: 0.4954367666232073
Delta: 0.012984245796240565 	  Loss: 1.682865557024403 	 Accuracy: 0.47979139504563234
Delta: 0.011605414499938026 	  Loss: 1.6274134014911632 	 Accuracy: 0.4941329856584094
Delta: 0.009593035104178105 	  Loss: 1.5910758419257955 	 Accuracy: 0.5097783572359843
Delta: 0.00797189069783203 	  Loss: 1.570344672637801 	 Accuracy: 0.5215123859191656
Delta: 0.007310691913823155 	  Loss: 1.5591094643953483 	 Accuracy: 0.530638852672751
Delta: 0.005685929978414571 	  Loss: 1.5521619423750654 	 Accuracy: 0.530638852672751

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006655566631419836 	  Loss: 1.5482964182589567 	 Accuracy: 0.530638852672751
Delta: 0.00531443742699037 	  Loss: 1.5455659035690812 	 Accuracy: 0.530638852672751
Delta: 0.005177937084975849 	  Loss: 1.5435771423219635 	 Accuracy: 0.5319426336375489
Delta: 0.004729103366197304 	  Loss: 1.54210392847234 	 Accuracy: 0.5345501955671447
Delta: 0.005543456671714291 	  Loss: 1.5410184069530652 	 Accuracy: 0.5332464146023468
Delta: 0.0030263502631816238 	  Loss: 1.54021640440995 	 Accuracy: 0.5332464146023468
Delta: 0.002167010349130292 	  Loss: 1.539832138388428 	 Accuracy: 0.5332464146023468
Delta: 0.003058200742641723 	  Loss: 1.539507812124873 	 Accuracy: 0.5358539765319427
Delta: 0.002696468502930107 	  Loss: 1.5393481918580374 	 Accuracy: 0.5345501955671447
Delta: 0.0038588728570546635 	  Loss: 1.5392969378595411 	 Accuracy: 0.5345501955671447
Delta: 0.001537221845046423 	  Loss: 1.5393579896561322 	 Accuracy: 0.5332464146023468
Delta: 0.0021653891517005005 	  Loss: 1.539330849667869 	 Accuracy: 0.5345501955671447
Delta: 0.0017766446911333617 	  Loss: 1.5393473430546731 	 Accuracy: 0.5345501955671447
Delta: 0.0009542518486656314 	  Loss: 1.5393347077860136 	 Accuracy: 0.5358539765319427
Delta: 0.002439070174851222 	  Loss: 1.539277734018742 	 Accuracy: 0.5358539765319427
Delta: 2.6108849906855334e-05 	  Loss: 1.539284569573483 	 Accuracy: 0.5358539765319427
Delta: 0.001875210178677154 	  Loss: 1.5393080846494311 	 Accuracy: 0.5345501955671447
Delta: 0.000815920266973604 	  Loss: 1.53935181234463 	 Accuracy: 0.5345501955671447
Delta: 0.0017109137754858486 	  Loss: 1.5394107625402684 	 Accuracy: 0.5345501955671447
Delta: 0.0010593719506433509 	  Loss: 1.5393900413137709 	 Accuracy: 0.5345501955671447
Delta: 0.0018082863803011964 	  Loss: 1.5394396258442216 	 Accuracy: 0.5345501955671447
Delta: 0.0005246911723876321 	  Loss: 1.5394837311295313 	 Accuracy: 0.5358539765319427
Delta: 0.00100674306543103 	  Loss: 1.539389518013678 	 Accuracy: 0.5358539765319427
Delta: 0.0022735979046696994 	  Loss: 1.5394139791803758 	 Accuracy: 0.5358539765319427
Delta: 0.0013818988493117757 	  Loss: 1.5394603012491124 	 Accuracy: 0.5332464146023468
Delta: 0.0011033555441330193 	  Loss: 1.5393797706546473 	 Accuracy: 0.5345501955671447
Delta: 0.0010944092060135747 	  Loss: 1.539353679597491 	 Accuracy: 0.5345501955671447
Delta: 0.001335684134259439 	  Loss: 1.539465249463439 	 Accuracy: 0.5358539765319427
Delta: 0.002596296675812477 	  Loss: 1.5395582575349733 	 Accuracy: 0.5345501955671447
Delta: 0.0014196693754060245 	  Loss: 1.53941443699566 	 Accuracy: 0.5345501955671447
Delta: 0.0015886903502716548 	  Loss: 1.539562284762742 	 Accuracy: 0.5332464146023468
Delta: 0.0021065680469750402 	  Loss: 1.5395622692185564 	 Accuracy: 0.5345501955671447
converged at iter  42
Delta: 0.020901710924605955 	  Loss: 2.1573620257967816 	 Accuracy: 0.19556714471968709
Delta: 0.018907826568682076 	  Loss: 2.056248923047363 	 Accuracy: 0.31290743155149936
Delta: 0.016923473559313222 	  Loss: 1.908442938897604 	 Accuracy: 0.3898305084745763
Delta: 0.014793371504789939 	  Loss: 1.7788138630368309 	 Accuracy: 0.39895697522816165
Delta: 0.012923001165118922 	  Loss: 1.686122494979748 	 Accuracy: 0.47979139504563234
Delta: 0.011345215001603133 	  Loss: 1.626129708670981 	 Accuracy: 0.485006518904824
Delta: 0.009578790212334796 	  Loss: 1.5914190370777521 	 Accuracy: 0.4863102998696219
Delta: 0.007815014498402547 	  Loss: 1.5728711446478336 	 Accuracy: 0.48370273794002605
Delta: 0.007466232940713225 	  Loss: 1.5628117968740325 	 Accuracy: 0.4706649282920469

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0067841114270388945 	  Loss: 1.556878806582533 	 Accuracy: 0.455019556714472
Delta: 0.005850759736808397 	  Loss: 1.5536621725877584 	 Accuracy: 0.4380704041720991
Delta: 0.005242544874498328 	  Loss: 1.5512843954593665 	 Accuracy: 0.43415906127770537
Delta: 0.005767767993236262 	  Loss: 1.549091976314999 	 Accuracy: 0.4172099087353325
Delta: 0.006023268355941974 	  Loss: 1.5473338672569363 	 Accuracy: 0.42503259452411996
Delta: 0.005625960466284599 	  Loss: 1.5458346586161658 	 Accuracy: 0.4211212516297262
Delta: 0.004899148164824849 	  Loss: 1.544605080584872 	 Accuracy: 0.42242503259452413
Delta: 0.004260958349587988 	  Loss: 1.5436680218323235 	 Accuracy: 0.4172099087353325
Delta: 0.0031412681530976253 	  Loss: 1.5432891938618523 	 Accuracy: 0.4198174706649283
Delta: 0.002936387543242732 	  Loss: 1.5430487288230008 	 Accuracy: 0.41851368970013036
Delta: 0.003328973941137111 	  Loss: 1.5427994529414164 	 Accuracy: 0.4211212516297262
Delta: 0.0031516550227471468 	  Loss: 1.5426637221338189 	 Accuracy: 0.4211212516297262
Delta: 0.0032618794484389904 	  Loss: 1.5427097552671032 	 Accuracy: 0.42242503259452413
Delta: 0.0017513906075384176 	  Loss: 1.5426418381329348 	 Accuracy: 0.4198174706649283
Delta: 0.0022520173169090544 	  Loss: 1.5425162205365361 	 Accuracy: 0.42242503259452413
Delta: 0.002968809547892523 	  Loss: 1.5425519802970804 	 Accuracy: 0.4211212516297262
Delta: 0.0016570130458917888 	  Loss: 1.5424478681048215 	 Accuracy: 0.4211212516297262
Delta: 0.0007301022205125562 	  Loss: 1.54248594998543 	 Accuracy: 0.4198174706649283
Delta: 0.0014452734188645116 	  Loss: 1.5424334655382572 	 Accuracy: 0.42242503259452413
Delta: 0.002697477287801532 	  Loss: 1.5424145587683005 	 Accuracy: 0.4198174706649283
Delta: 0.001482726964655899 	  Loss: 1.5424038294313664 	 Accuracy: 0.4198174706649283
Delta: 4.8738084660931226e-05 	  Loss: 1.5424470801113226 	 Accuracy: 0.4211212516297262
Delta: 0.0007064883198887003 	  Loss: 1.54243504789308 	 Accuracy: 0.4211212516297262
Delta: 2.725436400027786e-05 	  Loss: 1.5424852487229184 	 Accuracy: 0.4211212516297262
Delta: 0.001877828133309165 	  Loss: 1.5424249984513714 	 Accuracy: 0.4211212516297262
Delta: 5.333753025223395e-05 	  Loss: 1.542420252554919 	 Accuracy: 0.4211212516297262
Delta: 4.355403870576896e-05 	  Loss: 1.542460996587172 	 Accuracy: 0.4211212516297262
Delta: 1.9928637416463466e-05 	  Loss: 1.5424507420268527 	 Accuracy: 0.4211212516297262
Delta: 9.72048007818214e-06 	  Loss: 1.5424286112784973 	 Accuracy: 0.42242503259452413
Delta: 0.0017840225874370085 	  Loss: 1.5424292236264416 	 Accuracy: 0.42242503259452413
Delta: 0.001945690667107046 	  Loss: 1.542346701000135 	 Accuracy: 0.4211212516297262
Delta: 0.0005313608553483316 	  Loss: 1.5423558956776906 	 Accuracy: 0.423728813559322
Delta: 0.0005635652790294074 	  Loss: 1.5423294422968752 	 Accuracy: 0.42503259452411996
Delta: 0.0016059883438283855 	  Loss: 1.542366060021497 	 Accuracy: 0.42242503259452413
Delta: 0.0008247549106261893 	  Loss: 1.5422918879876226 	 Accuracy: 0.42242503259452413
Delta: 0.001816220646669523 	  Loss: 1.5423496736336173 	 Accuracy: 0.42503259452411996
Delta: 0.002273735262116838 	  Loss: 1.5423636703675154 	 Accuracy: 0.423728813559322
Delta: 0.0011165088508228742 	  Loss: 1.5422584726057498 	 Accuracy: 0.42242503259452413
Delta: 3.7983289884748684e-05 	  Loss: 1.5423089948369042 	 Accuracy: 0.423728813559322
Delta: 2.2089706033403194e-05 	  Loss: 1.5423004682143924 	 Accuracy: 0.423728813559322
Delta: 4.510461793557535e-05 	  Loss: 1.5422871366290076 	 Accuracy: 0.42242503259452413
Delta: 0.0008350428664135093 	  Loss: 1.5423584067593201 	 Accuracy: 0.42242503259452413
Delta: 4.3480818837763915e-05 	  Loss: 1.542430120825771 	 Accuracy: 0.42242503259452413
Delta: 0.0012126620406069002 	  Loss: 1.5426187474029978 	 Accuracy: 0.42242503259452413
Delta: 0.0010320343943973312 	  Loss: 1.5424563545529175 	 Accuracy: 0.423728813559322
Delta: 0.0005323727179544414 	  Loss: 1.5423653668600872 	 Accuracy: 0.42242503259452413
Delta: 6.45465985909825e-05 	  Loss: 1.5424482678551419 	 Accuracy: 0.42242503259452413
Delta: 0.0005305857739613791 	  Loss: 1.5425319006926754 	 Accuracy: 0.42242503259452413
Delta: 9.480433545637296e-05 	  Loss: 1.542456261372304 	 Accuracy: 0.42242503259452413
Delta: 7.912120507149272e-05 	  Loss: 1.5426613059293461 	 Accuracy: 0.42242503259452413
Delta: 7.127957042270724e-05 	  Loss: 1.5425289915558702 	 Accuracy: 0.4211212516297262
Delta: 0.0025051694185927705 	  Loss: 1.5426279716635463 	 Accuracy: 0.42242503259452413
Delta: 0.0012349235047265585 	  Loss: 1.5425151471748801 	 Accuracy: 0.4276401564537158
Delta: 5.260791585605205e-05 	  Loss: 1.5425808575794464 	 Accuracy: 0.42503259452411996
Delta: 0.0007754473900412497 	  Loss: 1.5424785730156643 	 Accuracy: 0.42242503259452413
Delta: 0.0008153898184779954 	  Loss: 1.542519076897406 	 Accuracy: 0.42242503259452413
Delta: 0.0007473733522294466 	  Loss: 1.542556173934549 	 Accuracy: 0.423728813559322
Delta: 0.0009491738492161702 	  Loss: 1.5426019897405303 	 Accuracy: 0.4211212516297262
Delta: 0.0020931235470053543 	  Loss: 1.5430235515867103 	 Accuracy: 0.423728813559322
Delta: 0.000797565731129639 	  Loss: 1.5424723462086578 	 Accuracy: 0.423728813559322
Delta: 0.0013180748661791538 	  Loss: 1.5428733458932626 	 Accuracy: 0.423728813559322
Delta: 7.904270708065468e-05 	  Loss: 1.542401033123605 	 Accuracy: 0.42242503259452413
Delta: 0.001221233618173841 	  Loss: 1.5425258854902602 	 Accuracy: 0.423728813559322
Delta: 0.0011470820588001939 	  Loss: 1.5423086488678583 	 Accuracy: 0.42242503259452413
Delta: 0.0010670922137805186 	  Loss: 1.5425115412708674 	 Accuracy: 0.423728813559322
Delta: 0.0005964937447864575 	  Loss: 1.542785115400596 	 Accuracy: 0.42242503259452413
Delta: 7.831513952482721e-05 	  Loss: 1.5424051547512698 	 Accuracy: 0.423728813559322
Delta: 0.0010652190267362678 	  Loss: 1.5426659423000855 	 Accuracy: 0.42242503259452413
Delta: 0.0011104649606621978 	  Loss: 1.5424619254224654 	 Accuracy: 0.42242503259452413
Delta: 7.278638348242721e-05 	  Loss: 1.5425418258684722 	 Accuracy: 0.423728813559322
Delta: 5.219073711039805e-05 	  Loss: 1.5423419122622524 	 Accuracy: 0.42242503259452413
Delta: 0.0010501037352955364 	  Loss: 1.5425234047904033 	 Accuracy: 0.42242503259452413
Delta: 0.0005715300126168338 	  Loss: 1.5423330499103076 	 Accuracy: 0.42242503259452413
Delta: 0.001086403629396624 	  Loss: 1.5423708987661737 	 Accuracy: 0.42242503259452413
Delta: 3.027017916149595e-05 	  Loss: 1.5424825699394022 	 Accuracy: 0.42242503259452413
Delta: 1.508957157418003e-05 	  Loss: 1.5423612631815455 	 Accuracy: 0.42242503259452413
Delta: 5.984193468140081e-06 	  Loss: 1.542356382337019 	 Accuracy: 0.4211212516297262
Delta: 4.023908487783359e-05 	  Loss: 1.5424411155162017 	 Accuracy: 0.42242503259452413
Delta: 0.0027234145539135847 	  Loss: 1.5422937927216056 	 Accuracy: 0.42242503259452413
Delta: 0.00128414514809697 	  Loss: 1.5423974741450341 	 Accuracy: 0.42242503259452413
Delta: 3.643403529089105e-05 	  Loss: 1.54238373586771 	 Accuracy: 0.42242503259452413
Delta: 3.2795436989827475e-05 	  Loss: 1.5423933736593591 	 Accuracy: 0.42242503259452413
Delta: 4.3790194710520506e-05 	  Loss: 1.5423971256716063 	 Accuracy: 0.42242503259452413
Delta: 0.0012320408133009802 	  Loss: 1.5424602263678788 	 Accuracy: 0.42894393741851367
Delta: 0.0008183292041107968 	  Loss: 1.5423629671182013 	 Accuracy: 0.42242503259452413
Delta: 0.0005643001037404365 	  Loss: 1.5422480924939803 	 Accuracy: 0.42242503259452413
Delta: 6.07399652924805e-05 	  Loss: 1.5423954044206405 	 Accuracy: 0.42242503259452413
Delta: 4.962701722652449e-05 	  Loss: 1.5423825339411694 	 Accuracy: 0.42242503259452413
Delta: 0.002664337428158312 	  Loss: 1.5425257232125598 	 Accuracy: 0.42242503259452413
Delta: 0.0006773712373286983 	  Loss: 1.5424585832612752 	 Accuracy: 0.42242503259452413
Delta: 0.0010750241207191453 	  Loss: 1.5424835689458516 	 Accuracy: 0.42242503259452413
Delta: 0.020921242120449653 	  Loss: 2.157028171836089 	 Accuracy: 0.19556714471968709
Delta: 0.01899532725751255 	  Loss: 2.0503324032508647 	 Accuracy: 0.27509778357235987
Delta: 0.016709868003126637 	  Loss: 1.8965701013189054 	 Accuracy: 0.3663624511082138
Delta: 0.014468468868023143 	  Loss: 1.7700993207358864 	 Accuracy: 0.3272490221642764
Delta: 0.013541719038919427 	  Loss: 1.6845542232247595 	 Accuracy: 0.3076923076923077
Delta: 0.01189305223407684 	  Loss: 1.6275749633526249 	 Accuracy: 0.3089960886571056
Delta: 0.010021214514165034 	  Loss: 1.5927339742076945 	 Accuracy: 0.3155149934810952
Delta: 0.008813902079876592 	  Loss: 1.5735084032127218 	 Accuracy: 0.3259452411994785
Delta: 0.007526513694990557 	  Loss: 1.562559628765238 	 Accuracy: 0.3376792698826597

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006481161979452796 	  Loss: 1.556115934818588 	 Accuracy: 0.3324641460234681
Delta: 0.005838184531482914 	  Loss: 1.5527457039764196 	 Accuracy: 0.3363754889178618
Delta: 0.0035900838147193167 	  Loss: 1.551297391197077 	 Accuracy: 0.34028683181225555
Delta: 0.005250009769806438 	  Loss: 1.5500844745200337 	 Accuracy: 0.3363754889178618
Delta: 0.004491416895602027 	  Loss: 1.5495947471024465 	 Accuracy: 0.33116036505867014
Delta: 0.0035139246418839196 	  Loss: 1.5494525029798485 	 Accuracy: 0.3350717079530639
Delta: 0.003278137556212632 	  Loss: 1.5493201486525383 	 Accuracy: 0.3350717079530639
Delta: 0.0029524238109987326 	  Loss: 1.5492349649099264 	 Accuracy: 0.3363754889178618
Delta: 0.0036354494448155657 	  Loss: 1.5491123939684677 	 Accuracy: 0.3350717079530639
Delta: 0.0018301229257502208 	  Loss: 1.549069634172215 	 Accuracy: 0.3350717079530639
Delta: 0.0019532973957300695 	  Loss: 1.5490520563050947 	 Accuracy: 0.3363754889178618
Delta: 0.0018805357224121843 	  Loss: 1.5491129329500328 	 Accuracy: 0.3363754889178618
Delta: 0.00251930922366628 	  Loss: 1.5491700864285751 	 Accuracy: 0.3363754889178618
Delta: 0.0014787811216101783 	  Loss: 1.549144532484132 	 Accuracy: 0.3363754889178618
Delta: 0.0017276797747548622 	  Loss: 1.5491863599355722 	 Accuracy: 0.3363754889178618
Delta: 0.002059181020505605 	  Loss: 1.5491165729812155 	 Accuracy: 0.3363754889178618
Delta: 0.0025869730200158863 	  Loss: 1.5491914303477627 	 Accuracy: 0.3363754889178618
Delta: 0.0008820945092751506 	  Loss: 1.549079311696341 	 Accuracy: 0.3376792698826597
Delta: 0.0019873655083649726 	  Loss: 1.5490053810756819 	 Accuracy: 0.3363754889178618
Delta: 0.0027076531780565833 	  Loss: 1.5493207188207712 	 Accuracy: 0.3363754889178618
Delta: 0.0005445639061458063 	  Loss: 1.5492778044219966 	 Accuracy: 0.3363754889178618
Delta: 4.2794222367302046e-05 	  Loss: 1.5493637337825676 	 Accuracy: 0.3363754889178618
Delta: 7.357586480525359e-05 	  Loss: 1.5491808151566446 	 Accuracy: 0.3363754889178618
Delta: 5.723264504490753e-05 	  Loss: 1.5491251913652082 	 Accuracy: 0.3376792698826597
Delta: 0.003941320070060695 	  Loss: 1.5490244574761873 	 Accuracy: 0.3363754889178618
Delta: 0.0024209240258702097 	  Loss: 1.5492532832251347 	 Accuracy: 0.3389830508474576
Delta: 0.0015839861716933049 	  Loss: 1.5493818833833501 	 Accuracy: 0.3363754889178618
Delta: 0.0014856637896730393 	  Loss: 1.5491525492441542 	 Accuracy: 0.3363754889178618
Delta: 0.001009348884369886 	  Loss: 1.5489969011132383 	 Accuracy: 0.3363754889178618
Delta: 0.005041607658318689 	  Loss: 1.5496311785153682 	 Accuracy: 0.3389830508474576
Delta: 0.002042931409580079 	  Loss: 1.5499835117606837 	 Accuracy: 0.3376792698826597
Delta: 0.00311684931890238 	  Loss: 1.5497712797731693 	 Accuracy: 0.3376792698826597
Delta: 0.002130453512814104 	  Loss: 1.5498960765614391 	 Accuracy: 0.3376792698826597
Delta: 0.0005344327197904786 	  Loss: 1.549584493920636 	 Accuracy: 0.3363754889178618
Delta: 0.0011873351139820834 	  Loss: 1.549809470771176 	 Accuracy: 0.3363754889178618
Delta: 0.000847090327182808 	  Loss: 1.5508011816100926 	 Accuracy: 0.3350717079530639
Delta: 5.321194615846806e-05 	  Loss: 1.550377062861961 	 Accuracy: 0.3376792698826597
Delta: 7.170540390327945e-05 	  Loss: 1.5496692578056526 	 Accuracy: 0.3389830508474576
Delta: 3.5983998487732536e-05 	  Loss: 1.5496793967446898 	 Accuracy: 0.3363754889178618
Delta: 2.7836892538100915e-05 	  Loss: 1.5497256815850455 	 Accuracy: 0.3376792698826597
Delta: 3.1323278266037164e-05 	  Loss: 1.5496927088690096 	 Accuracy: 0.3363754889178618
Delta: 6.079370699161698e-05 	  Loss: 1.5496800825877886 	 Accuracy: 0.34028683181225555
Delta: 0.0020249460228174833 	  Loss: 1.5493567967808402 	 Accuracy: 0.3389830508474576
Delta: 0.004309827741137371 	  Loss: 1.5495224413015263 	 Accuracy: 0.3389830508474576
Delta: 0.0028190461253094516 	  Loss: 1.5494579750541284 	 Accuracy: 0.3363754889178618
Delta: 0.004466892944282708 	  Loss: 1.5484426489765746 	 Accuracy: 0.3376792698826597
Delta: 0.0029129839515469524 	  Loss: 1.5484272021132892 	 Accuracy: 0.3376792698826597
Delta: 6.493232635194575e-05 	  Loss: 1.5485192148085936 	 Accuracy: 0.3376792698826597
Delta: 2.4825661013749386e-05 	  Loss: 1.548500477959455 	 Accuracy: 0.3376792698826597
Delta: 0.00283813646738353 	  Loss: 1.548618112138446 	 Accuracy: 0.34159061277705344
Delta: 0.0037252567817182064 	  Loss: 1.5488955203570531 	 Accuracy: 0.3376792698826597
Delta: 0.0015337174797150934 	  Loss: 1.5486275766719855 	 Accuracy: 0.3376792698826597
Delta: 0.0012291580435359142 	  Loss: 1.5486958476611008 	 Accuracy: 0.3363754889178618
Delta: 0.0005703217628805534 	  Loss: 1.5485569894392432 	 Accuracy: 0.3376792698826597
Delta: 0.003337770816259647 	  Loss: 1.548484103463156 	 Accuracy: 0.3376792698826597
Delta: 3.632809614249932e-05 	  Loss: 1.5484097990738892 	 Accuracy: 0.3376792698826597
Delta: 5.91285508654966e-05 	  Loss: 1.5484616329501921 	 Accuracy: 0.3376792698826597
Delta: 0.0007750175863983776 	  Loss: 1.548633331576671 	 Accuracy: 0.3376792698826597
Delta: 5.013513551408595e-05 	  Loss: 1.5485586630219055 	 Accuracy: 0.34159061277705344
Delta: 0.0017668597378963566 	  Loss: 1.5485605556944124 	 Accuracy: 0.3376792698826597
Delta: 0.0012406245481689257 	  Loss: 1.54854279975574 	 Accuracy: 0.3376792698826597
Delta: 0.0013077387186965345 	  Loss: 1.5485165116988542 	 Accuracy: 0.3376792698826597
Delta: 0.0012926813584376042 	  Loss: 1.5488985266913406 	 Accuracy: 0.3376792698826597
Delta: 8.130158021619944e-05 	  Loss: 1.548560864487192 	 Accuracy: 0.3376792698826597
Delta: 1.048320750155924e-05 	  Loss: 1.5485712820479056 	 Accuracy: 0.3376792698826597
Delta: 2.68139186739282e-05 	  Loss: 1.5485387280111347 	 Accuracy: 0.3376792698826597
Delta: 3.1612513874845916e-05 	  Loss: 1.5485378349104941 	 Accuracy: 0.3376792698826597
Delta: 0.0013197473045279031 	  Loss: 1.548931430479858 	 Accuracy: 0.3376792698826597
Delta: 0.0007031008894701009 	  Loss: 1.5485166978387337 	 Accuracy: 0.3376792698826597
Delta: 0.0019278435632198142 	  Loss: 1.5484452991843223 	 Accuracy: 0.3376792698826597
Delta: 0.0008777580953784085 	  Loss: 1.5484900635244534 	 Accuracy: 0.3376792698826597
Delta: 0.0016939816804772579 	  Loss: 1.5485454428987873 	 Accuracy: 0.3376792698826597
Delta: 1.2293201673573067e-05 	  Loss: 1.5485781213016756 	 Accuracy: 0.3376792698826597
Delta: 2.1376439260580226e-06 	  Loss: 1.548571555110731 	 Accuracy: 0.3363754889178618
Delta: 4.431675666954475e-06 	  Loss: 1.5485746557851996 	 Accuracy: 0.3376792698826597
Delta: 1.0719004814660549e-05 	  Loss: 1.548545401381392 	 Accuracy: 0.3376792698826597
Delta: 9.940233273331417e-06 	  Loss: 1.5485696904553041 	 Accuracy: 0.34159061277705344
Delta: 4.8156042741724315e-05 	  Loss: 1.5488267241499911 	 Accuracy: 0.3376792698826597
Delta: 4.8147479105718435e-05 	  Loss: 1.5485565829005925 	 Accuracy: 0.3389830508474576
Delta: 5.33447201980488e-06 	  Loss: 1.548570253496298 	 Accuracy: 0.3376792698826597
Delta: 0.0025763377107874946 	  Loss: 1.548307997931265 	 Accuracy: 0.3376792698826597
Delta: 0.0015662824735743971 	  Loss: 1.5482721095027046 	 Accuracy: 0.34028683181225555
Delta: 0.001190174077179217 	  Loss: 1.5483604794506962 	 Accuracy: 0.3389830508474576
Delta: 0.0010468882714498458 	  Loss: 1.5483630722515183 	 Accuracy: 0.3376792698826597
Delta: 1.9155552978092036e-05 	  Loss: 1.5483669200718158 	 Accuracy: 0.3389830508474576
Delta: 0.0033373119807157303 	  Loss: 1.5483849181492197 	 Accuracy: 0.3389830508474576
Delta: 2.1837315276485028e-05 	  Loss: 1.5484128828212704 	 Accuracy: 0.3389830508474576
Delta: 7.196114140490565e-05 	  Loss: 1.54837495006861 	 Accuracy: 0.3363754889178618
Delta: 0.0013022234345319394 	  Loss: 1.5486433467055492 	 Accuracy: 0.3389830508474576
Delta: 0.00010242915856344027 	  Loss: 1.5483927850416275 	 Accuracy: 0.3389830508474576
Delta: 0.0043824972788131565 	  Loss: 1.5497833152331442 	 Accuracy: 0.3389830508474576
Delta: 0.020898196287193426 	  Loss: 2.1570685097440894 	 Accuracy: 0.19556714471968709
Delta: 0.018827346349270063 	  Loss: 2.051685053137649 	 Accuracy: 0.3194263363754889
Delta: 0.017196870503442218 	  Loss: 1.8804394460722462 	 Accuracy: 0.34028683181225555
Delta: 0.014722146868274812 	  Loss: 1.7479912376361124 	 Accuracy: 0.32333767926988266
Delta: 0.013321475555113068 	  Loss: 1.6685269291833664 	 Accuracy: 0.3259452411994785
Delta: 0.011869087075784249 	  Loss: 1.6213884870885726 	 Accuracy: 0.31681877444589307
Delta: 0.010343053609614997 	  Loss: 1.5928948027550462 	 Accuracy: 0.31681877444589307
Delta: 0.009102418867445748 	  Loss: 1.5752680132798194 	 Accuracy: 0.3076923076923077

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0070972128987051445 	  Loss: 1.5667293850253596 	 Accuracy: 0.30638852672750977
Delta: 0.006722286534187408 	  Loss: 1.5622294642979961 	 Accuracy: 0.3076923076923077
Delta: 0.005680392499501058 	  Loss: 1.5606075488475584 	 Accuracy: 0.31029986962190353
Delta: 0.00483326377508814 	  Loss: 1.559406303236598 	 Accuracy: 0.3050847457627119
Delta: 0.0038909437250775453 	  Loss: 1.5588493384194573 	 Accuracy: 0.3050847457627119
Delta: 0.003700749303655498 	  Loss: 1.5585094785222307 	 Accuracy: 0.3076923076923077
Delta: 0.0036473202555436556 	  Loss: 1.5583793270438382 	 Accuracy: 0.3050847457627119
Delta: 0.0022840854757945526 	  Loss: 1.5581808309152985 	 Accuracy: 0.3050847457627119
Delta: 0.0030264591371689117 	  Loss: 1.558041807593677 	 Accuracy: 0.3050847457627119
Delta: 0.0036195756011256582 	  Loss: 1.5578950844394979 	 Accuracy: 0.3050847457627119
Delta: 0.0020635328166790784 	  Loss: 1.557865937799189 	 Accuracy: 0.30638852672750977
Delta: 0.0011321738113124057 	  Loss: 1.5578605219779804 	 Accuracy: 0.3050847457627119
Delta: 0.0005438784054380429 	  Loss: 1.5578811099293237 	 Accuracy: 0.3050847457627119
Delta: 0.0008990070180974178 	  Loss: 1.5578840789387187 	 Accuracy: 0.30638852672750977
Delta: 0.0028494237119894494 	  Loss: 1.558103597503428 	 Accuracy: 0.30638852672750977
Delta: 3.3175289636207975e-05 	  Loss: 1.5579996639988454 	 Accuracy: 0.30638852672750977
Delta: 0.0011928154288363413 	  Loss: 1.55807888784313 	 Accuracy: 0.3076923076923077
Delta: 0.0038985816864762777 	  Loss: 1.5582518341387086 	 Accuracy: 0.3050847457627119
Delta: 0.0027618200363549498 	  Loss: 1.5581102405056413 	 Accuracy: 0.30638852672750977
Delta: 0.0034739800518980347 	  Loss: 1.5579119779354058 	 Accuracy: 0.30638852672750977
Delta: 0.001887201104011037 	  Loss: 1.558207881827179 	 Accuracy: 0.30638852672750977
Delta: 0.0007725709976948662 	  Loss: 1.5582119506767222 	 Accuracy: 0.30638852672750977
Delta: 0.0014572277104075286 	  Loss: 1.5582363060207958 	 Accuracy: 0.3050847457627119
Delta: 0.0020589646188925756 	  Loss: 1.5584126148762034 	 Accuracy: 0.30638852672750977
Delta: 0.0011030573199185463 	  Loss: 1.5581252624681874 	 Accuracy: 0.3050847457627119
Delta: 4.988562097873612e-05 	  Loss: 1.5581070949318065 	 Accuracy: 0.3050847457627119
Delta: 0.0018020888697001217 	  Loss: 1.5583853311604945 	 Accuracy: 0.3050847457627119
Delta: 0.00011581902008647179 	  Loss: 1.5579852681413704 	 Accuracy: 0.30638852672750977
Delta: 9.711296964763921e-05 	  Loss: 1.5578941670251576 	 Accuracy: 0.3050847457627119
Delta: 4.6321780587208883e-05 	  Loss: 1.5579772476341787 	 Accuracy: 0.3050847457627119
Delta: 0.002634991559711343 	  Loss: 1.5583255056639054 	 Accuracy: 0.30638852672750977
Delta: 0.00011800720148575919 	  Loss: 1.5580776954648476 	 Accuracy: 0.3050847457627119
Delta: 0.0019958525184604545 	  Loss: 1.5578462535322823 	 Accuracy: 0.3076923076923077
Delta: 0.001086790488558376 	  Loss: 1.558153018515013 	 Accuracy: 0.30378096479791394
Delta: 0.0030431005570008174 	  Loss: 1.5582150044771665 	 Accuracy: 0.3050847457627119
Delta: 0.003326540301239502 	  Loss: 1.558354039191941 	 Accuracy: 0.3050847457627119
Delta: 0.002388306982548427 	  Loss: 1.558277467488725 	 Accuracy: 0.30638852672750977
Delta: 0.0007818543396892086 	  Loss: 1.5584382684456912 	 Accuracy: 0.29986962190352023
Delta: 0.0014821482056985495 	  Loss: 1.5583859056516673 	 Accuracy: 0.3050847457627119
Delta: 0.0005226068882622833 	  Loss: 1.5583902690658595 	 Accuracy: 0.3050847457627119
Delta: 0.0015185560110208343 	  Loss: 1.5584637638561452 	 Accuracy: 0.30378096479791394
Delta: 0.0017397496314428484 	  Loss: 1.558476488237151 	 Accuracy: 0.30378096479791394
Delta: 0.0016341270480251624 	  Loss: 1.5582112385107825 	 Accuracy: 0.3050847457627119
Delta: 0.002718609972471374 	  Loss: 1.5580850167519202 	 Accuracy: 0.30378096479791394
Delta: 0.0012400174534269867 	  Loss: 1.5584498914384928 	 Accuracy: 0.30378096479791394
Delta: 7.042069758616675e-05 	  Loss: 1.558173851712438 	 Accuracy: 0.3050847457627119
Delta: 0.0016010828308729026 	  Loss: 1.5584210945403962 	 Accuracy: 0.30378096479791394
Delta: 1.5505785458641346e-05 	  Loss: 1.558453354263774 	 Accuracy: 0.30378096479791394
Delta: 0.0005421205706964852 	  Loss: 1.5582772922864372 	 Accuracy: 0.30378096479791394
Delta: 4.466618184222821e-05 	  Loss: 1.5582284317532968 	 Accuracy: 0.3050847457627119
Delta: 0.0008416181950844104 	  Loss: 1.5583645122713463 	 Accuracy: 0.30378096479791394
Delta: 0.0017310459591758946 	  Loss: 1.5581225854079883 	 Accuracy: 0.3050847457627119
Delta: 0.0014786655824663947 	  Loss: 1.5583493060284463 	 Accuracy: 0.3050847457627119
Delta: 3.909046889645527e-05 	  Loss: 1.5583275470281936 	 Accuracy: 0.3050847457627119
Delta: 0.0036407514275491517 	  Loss: 1.5589331635391286 	 Accuracy: 0.30638852672750977
Delta: 0.00411061529491743 	  Loss: 1.5584300919688405 	 Accuracy: 0.30638852672750977
Delta: 0.0018523708507790875 	  Loss: 1.558497413296752 	 Accuracy: 0.3050847457627119
Delta: 2.4669757394068094e-05 	  Loss: 1.5585002851998655 	 Accuracy: 0.30247718383311606
Delta: 0.0056371525395416495 	  Loss: 1.5584608786080185 	 Accuracy: 0.30378096479791394
Delta: 0.002707556472690269 	  Loss: 1.5590887975073326 	 Accuracy: 0.3050847457627119
Delta: 0.002765112958731006 	  Loss: 1.5582716854919538 	 Accuracy: 0.3050847457627119
Delta: 0.0023620473625373278 	  Loss: 1.5591022382915214 	 Accuracy: 0.30378096479791394
Delta: 0.0035652810667211525 	  Loss: 1.5597892110201954 	 Accuracy: 0.30378096479791394
Delta: 0.0005816414572825364 	  Loss: 1.559938584274591 	 Accuracy: 0.30247718383311606
Delta: 0.003237957899154178 	  Loss: 1.5586237011068715 	 Accuracy: 0.30378096479791394
Delta: 0.0020734022245384853 	  Loss: 1.5592615445532636 	 Accuracy: 0.3011734028683181
Delta: 0.00224579620986805 	  Loss: 1.559452673487451 	 Accuracy: 0.3050847457627119
Delta: 0.0021348525981771333 	  Loss: 1.5581244104193952 	 Accuracy: 0.29986962190352023
Delta: 0.005079330734362793 	  Loss: 1.5592486368583955 	 Accuracy: 0.30247718383311606
Delta: 0.0039001840044773587 	  Loss: 1.5583923331228995 	 Accuracy: 0.30247718383311606
Delta: 0.002168225191513423 	  Loss: 1.5586836698041693 	 Accuracy: 0.30247718383311606
Delta: 0.002111227518894344 	  Loss: 1.5596218210482062 	 Accuracy: 0.30247718383311606
Delta: 0.0011940570542965019 	  Loss: 1.5587556658729054 	 Accuracy: 0.30247718383311606
Delta: 0.004104895516061649 	  Loss: 1.558954288545865 	 Accuracy: 0.3050847457627119
Delta: 0.0029453216420389063 	  Loss: 1.5590039963185198 	 Accuracy: 0.30378096479791394
Delta: 0.003477560324878561 	  Loss: 1.5589269954510272 	 Accuracy: 0.30378096479791394
Delta: 0.0010743443245618122 	  Loss: 1.5591466655567494 	 Accuracy: 0.30378096479791394
Delta: 0.0036474097520878077 	  Loss: 1.5591288303955353 	 Accuracy: 0.30378096479791394
Delta: 0.00010680589560992354 	  Loss: 1.5590404380903087 	 Accuracy: 0.30378096479791394
Delta: 0.001939776046810797 	  Loss: 1.5595453470729619 	 Accuracy: 0.30247718383311606
Delta: 0.004438302495723942 	  Loss: 1.560277590353304 	 Accuracy: 0.30247718383311606
Delta: 0.0050498837218595554 	  Loss: 1.561202211663042 	 Accuracy: 0.3050847457627119
Delta: 0.003976193470018129 	  Loss: 1.5602728213267727 	 Accuracy: 0.30247718383311606
Delta: 0.0015054238287018295 	  Loss: 1.5604260288566518 	 Accuracy: 0.30247718383311606
Delta: 0.0033682964381935676 	  Loss: 1.5605828677546303 	 Accuracy: 0.30247718383311606
Delta: 0.003248421129896901 	  Loss: 1.5604047771091194 	 Accuracy: 0.30247718383311606
Delta: 0.002331743758165528 	  Loss: 1.5599816359041974 	 Accuracy: 0.3050847457627119
Delta: 0.001515674171508035 	  Loss: 1.5598319889200791 	 Accuracy: 0.30247718383311606
Delta: 0.0014597530902223264 	  Loss: 1.55979827016449 	 Accuracy: 0.30378096479791394
Delta: 0.0008966802010314122 	  Loss: 1.5596685161549915 	 Accuracy: 0.3050847457627119
Delta: 0.002841894740399733 	  Loss: 1.5590457821665407 	 Accuracy: 0.30378096479791394
Delta: 9.241736617056347e-05 	  Loss: 1.5592256708761338 	 Accuracy: 0.30378096479791394
Delta: 0.020931004200972287 	  Loss: 2.156988488724131 	 Accuracy: 0.19426336375488917
Delta: 0.018944926570683515 	  Loss: 2.0481754843825954 	 Accuracy: 0.3155149934810952
Delta: 0.017110464354243383 	  Loss: 1.871572684825284 	 Accuracy: 0.3833116036505867
Delta: 0.014983739601841389 	  Loss: 1.734880589466736 	 Accuracy: 0.318122555410691
Delta: 0.013542058273549179 	  Loss: 1.6563904247410675 	 Accuracy: 0.31681877444589307
Delta: 0.011819745787563802 	  Loss: 1.6138031637901358 	 Accuracy: 0.3272490221642764
Delta: 0.010084796522100144 	  Loss: 1.5888768843990149 	 Accuracy: 0.3324641460234681

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008950217983877925 	  Loss: 1.573308554003979 	 Accuracy: 0.3285528031290743
Delta: 0.007569576489061174 	  Loss: 1.5648960673579595 	 Accuracy: 0.33376792698826596
Delta: 0.005815861650600838 	  Loss: 1.5606776093422465 	 Accuracy: 0.3376792698826597
Delta: 0.004826623591519632 	  Loss: 1.5594331853762369 	 Accuracy: 0.3376792698826597
Delta: 0.004856254846278846 	  Loss: 1.5591118319724369 	 Accuracy: 0.3376792698826597
Delta: 0.00420444870652439 	  Loss: 1.5590048038038442 	 Accuracy: 0.3350717079530639
Delta: 0.003612603195552322 	  Loss: 1.5587304201473984 	 Accuracy: 0.3376792698826597
Delta: 0.004178400117593734 	  Loss: 1.558371963473773 	 Accuracy: 0.3389830508474576
Delta: 0.0030095251127584097 	  Loss: 1.558253643365461 	 Accuracy: 0.3389830508474576
Delta: 0.002685843932137672 	  Loss: 1.5580881380462948 	 Accuracy: 0.3389830508474576
Delta: 2.61977837377097e-05 	  Loss: 1.5581139830069826 	 Accuracy: 0.3363754889178618
Delta: 0.0007141829673066621 	  Loss: 1.5580410261661908 	 Accuracy: 0.3376792698826597
Delta: 0.0010410421707649125 	  Loss: 1.5579542708009568 	 Accuracy: 0.3376792698826597
Delta: 0.0020990830887442483 	  Loss: 1.5579967375614892 	 Accuracy: 0.3376792698826597
Delta: 2.5726549201012776e-05 	  Loss: 1.5579975540390094 	 Accuracy: 0.3376792698826597
Delta: 4.850591187005999e-05 	  Loss: 1.557885872661927 	 Accuracy: 0.3389830508474576
Delta: 2.8248792552204012e-05 	  Loss: 1.5580113006849003 	 Accuracy: 0.3389830508474576
Delta: 0.0005249649894597555 	  Loss: 1.5579141587117693 	 Accuracy: 0.3389830508474576
Delta: 2.4733644430436523e-05 	  Loss: 1.5579071428848015 	 Accuracy: 0.3376792698826597
Delta: 2.3187147205326948e-05 	  Loss: 1.557995615663053 	 Accuracy: 0.3389830508474576
Delta: 3.214882811429377e-05 	  Loss: 1.5579061136257482 	 Accuracy: 0.3389830508474576
Delta: 0.0023472035958821105 	  Loss: 1.5579471037392998 	 Accuracy: 0.3389830508474576
Delta: 0.0011479659136306446 	  Loss: 1.5579185285624502 	 Accuracy: 0.3389830508474576
Delta: 0.0009692651823055413 	  Loss: 1.5578441552872149 	 Accuracy: 0.34028683181225555
Delta: 0.0032220182532440604 	  Loss: 1.5582868153454164 	 Accuracy: 0.3389830508474576
Delta: 0.0015129028518025712 	  Loss: 1.5581307458640437 	 Accuracy: 0.3389830508474576
Delta: 0.0009128998710529203 	  Loss: 1.5583112266630188 	 Accuracy: 0.3389830508474576
Delta: 0.0005234910722786869 	  Loss: 1.5582150073666894 	 Accuracy: 0.34028683181225555
Delta: 0.0015793089309319398 	  Loss: 1.5583598031032595 	 Accuracy: 0.3389830508474576
Delta: 0.0007750955180236309 	  Loss: 1.5584326429291013 	 Accuracy: 0.3389830508474576
Delta: 0.0010516700915369004 	  Loss: 1.5582206256736697 	 Accuracy: 0.3389830508474576
Delta: 0.0015007960399635802 	  Loss: 1.558473225857578 	 Accuracy: 0.3389830508474576
Delta: 0.0029231154757802555 	  Loss: 1.5583518818269766 	 Accuracy: 0.3389830508474576
Delta: 0.000930660789361011 	  Loss: 1.558150814545951 	 Accuracy: 0.3389830508474576
Delta: 0.0009345136441026098 	  Loss: 1.5581729982177202 	 Accuracy: 0.3389830508474576
Delta: 0.003104945764670331 	  Loss: 1.5585360930501997 	 Accuracy: 0.3389830508474576
Delta: 0.0027002670254537187 	  Loss: 1.5582535561306483 	 Accuracy: 0.3389830508474576
Delta: 0.0007328837331377179 	  Loss: 1.5583686441486235 	 Accuracy: 0.3428943937418514
Delta: 0.0026613053937227862 	  Loss: 1.558177868573423 	 Accuracy: 0.3389830508474576
Delta: 0.0014268705365049887 	  Loss: 1.5582182839633565 	 Accuracy: 0.3389830508474576
Delta: 0.0017752234459388607 	  Loss: 1.5583078031591837 	 Accuracy: 0.3520208604954368
Delta: 0.003521361298689589 	  Loss: 1.5595033950080404 	 Accuracy: 0.3389830508474576
Delta: 0.002310521723503656 	  Loss: 1.5591219534171086 	 Accuracy: 0.3389830508474576
Delta: 0.0005567427101609765 	  Loss: 1.5591197726371693 	 Accuracy: 0.34028683181225555
Delta: 0.0023931630100946124 	  Loss: 1.557972507267646 	 Accuracy: 0.3376792698826597
Delta: 0.002535522704259168 	  Loss: 1.5583092801107348 	 Accuracy: 0.34028683181225555
Delta: 0.0006587823763310961 	  Loss: 1.5581000705257848 	 Accuracy: 0.3389830508474576
Delta: 0.0019438200020512088 	  Loss: 1.5584151885504163 	 Accuracy: 0.3389830508474576
Delta: 3.303103366431358e-05 	  Loss: 1.5583168224711297 	 Accuracy: 0.3389830508474576
Delta: 0.0005622764182206058 	  Loss: 1.5583184606251583 	 Accuracy: 0.3389830508474576
Delta: 0.00224114920049785 	  Loss: 1.5582897890036653 	 Accuracy: 0.3389830508474576
Delta: 0.004077119002713042 	  Loss: 1.5586586703241712 	 Accuracy: 0.3363754889178618
Delta: 0.005808793364977908 	  Loss: 1.5594290410314686 	 Accuracy: 0.3363754889178618
Delta: 0.00364984871242805 	  Loss: 1.5590950896624582 	 Accuracy: 0.34028683181225555
Delta: 0.003129618311683948 	  Loss: 1.558391916026868 	 Accuracy: 0.3363754889178618
Delta: 0.002178852236024233 	  Loss: 1.5584565705663942 	 Accuracy: 0.3376792698826597
Delta: 0.004386897421016641 	  Loss: 1.5583053349363754 	 Accuracy: 0.3376792698826597
Delta: 0.0037974894132971003 	  Loss: 1.557434451158856 	 Accuracy: 0.3376792698826597
Delta: 1.3512212003081776e-05 	  Loss: 1.5574309163051097 	 Accuracy: 0.3376792698826597
Delta: 0.0012664657580022415 	  Loss: 1.5574765983007104 	 Accuracy: 0.3350717079530639
Delta: 0.004748137075207338 	  Loss: 1.557595857487193 	 Accuracy: 0.3363754889178618
Delta: 0.0026629376169499917 	  Loss: 1.5574969511794543 	 Accuracy: 0.3363754889178618
Delta: 0.003042457230762181 	  Loss: 1.5572856562286823 	 Accuracy: 0.3363754889178618
Delta: 0.0014831491574125713 	  Loss: 1.5578410008257215 	 Accuracy: 0.3350717079530639
Delta: 0.0001154662833668885 	  Loss: 1.5576285461411283 	 Accuracy: 0.3376792698826597
Delta: 0.0009715087578546631 	  Loss: 1.5580917484239258 	 Accuracy: 0.3376792698826597
Delta: 0.002653518880685576 	  Loss: 1.5582149118852482 	 Accuracy: 0.3376792698826597
Delta: 5.645095997485164e-05 	  Loss: 1.5581079722261888 	 Accuracy: 0.3376792698826597
Delta: 8.549368699322636e-05 	  Loss: 1.5577848640062941 	 Accuracy: 0.3376792698826597
Delta: 6.936527143298447e-05 	  Loss: 1.55778718580955 	 Accuracy: 0.3376792698826597
Delta: 0.00011569273351326643 	  Loss: 1.5578430663737899 	 Accuracy: 0.3376792698826597
Delta: 0.0017005796654605621 	  Loss: 1.558024107284535 	 Accuracy: 0.3363754889178618
Delta: 0.001521540077241725 	  Loss: 1.5580164133835386 	 Accuracy: 0.3376792698826597
Delta: 0.00104188199868381 	  Loss: 1.558196244699402 	 Accuracy: 0.3376792698826597
Delta: 6.675821912720321e-05 	  Loss: 1.5583984429278899 	 Accuracy: 0.3363754889178618
Delta: 0.0012433268939615815 	  Loss: 1.5582678372373002 	 Accuracy: 0.3363754889178618
Delta: 7.389265271281239e-05 	  Loss: 1.558189672588612 	 Accuracy: 0.3376792698826597
Delta: 0.0006385393206370778 	  Loss: 1.557969167188733 	 Accuracy: 0.3376792698826597
Delta: 0.0010783591436025856 	  Loss: 1.5578433392534041 	 Accuracy: 0.3376792698826597
Delta: 9.350810245203862e-05 	  Loss: 1.5577570749965854 	 Accuracy: 0.3376792698826597
Delta: 5.611283675495118e-09 	  Loss: 1.5577570816480666 	 Accuracy: 0.3389830508474576
converged at iter  87
Delta: 0.0209101155543851 	  Loss: 2.156859413979162 	 Accuracy: 0.19295958279009126
Delta: 0.01903616092915713 	  Loss: 2.044092531840633 	 Accuracy: 0.29726205997392435
Delta: 0.017140501220510872 	  Loss: 1.8637280694997322 	 Accuracy: 0.3650586701434159
Delta: 0.015103086570357712 	  Loss: 1.7311848878754883 	 Accuracy: 0.2790091264667536
Delta: 0.0133389969585329 	  Loss: 1.653292321267363 	 Accuracy: 0.288135593220339
Delta: 0.011507602829028376 	  Loss: 1.6093586820712593 	 Accuracy: 0.29986962190352023
Delta: 0.009810383463382373 	  Loss: 1.5885615973399718 	 Accuracy: 0.3089960886571056

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00803777780626037 	  Loss: 1.5790586316335373 	 Accuracy: 0.31290743155149936
Delta: 0.007233185716693784 	  Loss: 1.5738360016304247 	 Accuracy: 0.3155149934810952
Delta: 0.005052186622847221 	  Loss: 1.572564362496514 	 Accuracy: 0.3155149934810952
Delta: 0.004395401810569309 	  Loss: 1.5721004598673602 	 Accuracy: 0.31421121251629724
Delta: 0.004675945543055911 	  Loss: 1.5718919577825214 	 Accuracy: 0.3155149934810952
Delta: 0.004745436036355716 	  Loss: 1.5711318364293017 	 Accuracy: 0.318122555410691
Delta: 0.0035486580519878317 	  Loss: 1.5710856775960533 	 Accuracy: 0.3155149934810952
Delta: 0.001792851887986137 	  Loss: 1.5712587973067782 	 Accuracy: 0.31681877444589307
Delta: 0.0022375334136787396 	  Loss: 1.5707467586342498 	 Accuracy: 0.31681877444589307
Delta: 0.0005325306756092952 	  Loss: 1.5707625899114244 	 Accuracy: 0.3155149934810952
Delta: 3.490290617505664e-05 	  Loss: 1.570770714294131 	 Accuracy: 0.31681877444589307
Delta: 0.0012073881926302446 	  Loss: 1.5707507539507968 	 Accuracy: 0.31421121251629724
Delta: 3.428659802257457e-05 	  Loss: 1.5706904519970353 	 Accuracy: 0.3155149934810952
Delta: 0.0020863988151020034 	  Loss: 1.5706581032138622 	 Accuracy: 0.3155149934810952
Delta: 2.0734587049757582e-05 	  Loss: 1.5706534665874914 	 Accuracy: 0.3155149934810952
Delta: 0.0005495758816514078 	  Loss: 1.5706295633606961 	 Accuracy: 0.31681877444589307
Delta: 0.0016946533941192734 	  Loss: 1.5705230241508183 	 Accuracy: 0.318122555410691
Delta: 2.3379825999329526e-05 	  Loss: 1.5705392323980423 	 Accuracy: 0.31681877444589307
Delta: 2.7171499384550742e-05 	  Loss: 1.570561811426896 	 Accuracy: 0.31681877444589307
Delta: 2.3890042374070364e-05 	  Loss: 1.5705042528011122 	 Accuracy: 0.3155149934810952
Delta: 0.0006256348281150285 	  Loss: 1.5705452252422187 	 Accuracy: 0.31681877444589307
Delta: 1.6305070221430383e-05 	  Loss: 1.5705450897059228 	 Accuracy: 0.31681877444589307
Delta: 0.0005180237879243234 	  Loss: 1.5705705758225517 	 Accuracy: 0.318122555410691
Delta: 1.3127607063244813e-05 	  Loss: 1.5705387616645163 	 Accuracy: 0.31681877444589307
Delta: 1.53428500844449e-05 	  Loss: 1.5705409951769118 	 Accuracy: 0.3116036505867014
Delta: 2.1600872415365674e-05 	  Loss: 1.5705709717637715 	 Accuracy: 0.3155149934810952
Delta: 0.0013672374147688463 	  Loss: 1.570531974112482 	 Accuracy: 0.31681877444589307
Delta: 0.0012671183600202482 	  Loss: 1.5706094913677662 	 Accuracy: 0.318122555410691
Delta: 0.0006233009924716146 	  Loss: 1.5705698553054086 	 Accuracy: 0.3155149934810952
Delta: 2.2971758832912035e-05 	  Loss: 1.5705588922749771 	 Accuracy: 0.318122555410691
Delta: 3.763818548592138e-05 	  Loss: 1.5705409413034022 	 Accuracy: 0.31681877444589307
Delta: 3.024762392202126e-05 	  Loss: 1.5705589380506162 	 Accuracy: 0.31681877444589307
Delta: 2.938913200709681e-05 	  Loss: 1.5705135177645952 	 Accuracy: 0.318122555410691
Delta: 0.0032925453155110336 	  Loss: 1.5703162989819828 	 Accuracy: 0.31681877444589307
Delta: 0.0026616629790274814 	  Loss: 1.5703215069703844 	 Accuracy: 0.31681877444589307
Delta: 0.0016156982437970334 	  Loss: 1.5704817054680182 	 Accuracy: 0.318122555410691
Delta: 0.0013653838927597155 	  Loss: 1.5705950406607134 	 Accuracy: 0.31681877444589307
Delta: 5.549710895876343e-05 	  Loss: 1.5704383998021796 	 Accuracy: 0.318122555410691
Delta: 0.0006563758404342414 	  Loss: 1.5704928797826612 	 Accuracy: 0.31681877444589307
Delta: 0.000110698275776918 	  Loss: 1.5702683856731718 	 Accuracy: 0.318122555410691
Delta: 0.0029351612723808006 	  Loss: 1.5709313846330941 	 Accuracy: 0.3194263363754889
Delta: 0.0006291385981244055 	  Loss: 1.5703095015539454 	 Accuracy: 0.31681877444589307
Delta: 0.0027877191959391097 	  Loss: 1.5699821319178686 	 Accuracy: 0.31421121251629724
Delta: 0.0016389070371440142 	  Loss: 1.5702628100463034 	 Accuracy: 0.31681877444589307
Delta: 0.0015207109245324556 	  Loss: 1.5702318648822369 	 Accuracy: 0.31681877444589307
Delta: 0.000515658530571508 	  Loss: 1.5702637585982249 	 Accuracy: 0.31681877444589307
Delta: 0.0023093550800069307 	  Loss: 1.5706254632824137 	 Accuracy: 0.31681877444589307
Delta: 0.003815669906174385 	  Loss: 1.570962852519195 	 Accuracy: 0.31681877444589307
Delta: 0.0025491647253326408 	  Loss: 1.5709882452320683 	 Accuracy: 0.318122555410691
Delta: 0.0025790193699947806 	  Loss: 1.570864158164206 	 Accuracy: 0.31681877444589307
Delta: 0.003964289824241943 	  Loss: 1.5706502872508976 	 Accuracy: 0.31681877444589307
Delta: 0.0010629328842369306 	  Loss: 1.571087237650762 	 Accuracy: 0.31681877444589307
Delta: 0.0033719978932756096 	  Loss: 1.5709469473960067 	 Accuracy: 0.31681877444589307
Delta: 2.110396656622177e-05 	  Loss: 1.5709642453992883 	 Accuracy: 0.31681877444589307
Delta: 0.002315218176189696 	  Loss: 1.5705242086191613 	 Accuracy: 0.31681877444589307
Delta: 0.0001075605383197711 	  Loss: 1.5706831855860655 	 Accuracy: 0.31681877444589307
Delta: 0.003506952767752026 	  Loss: 1.5704201089611942 	 Accuracy: 0.31681877444589307
Delta: 8.373825075309523e-05 	  Loss: 1.570693442159452 	 Accuracy: 0.31681877444589307
Delta: 0.002636409170288494 	  Loss: 1.5706329346864636 	 Accuracy: 0.31681877444589307
Delta: 0.0015105704149123648 	  Loss: 1.5707742909850035 	 Accuracy: 0.3155149934810952
Delta: 5.7923099984514064e-05 	  Loss: 1.5709340142790496 	 Accuracy: 0.3155149934810952
Delta: 0.002211861066454729 	  Loss: 1.57087447388761 	 Accuracy: 0.318122555410691
Delta: 0.001516205267645244 	  Loss: 1.5708286639322844 	 Accuracy: 0.3155149934810952
Delta: 0.002275323542677146 	  Loss: 1.571054598841454 	 Accuracy: 0.3155149934810952
Delta: 2.272738278277114e-05 	  Loss: 1.5710780674232327 	 Accuracy: 0.3155149934810952
Delta: 5.524897297952902e-05 	  Loss: 1.5711134918950542 	 Accuracy: 0.3155149934810952
Delta: 0.001100787031518368 	  Loss: 1.5712019806120954 	 Accuracy: 0.31421121251629724
Delta: 0.0011717588944679584 	  Loss: 1.5711427559240208 	 Accuracy: 0.3155149934810952
Delta: 0.0005917879320663696 	  Loss: 1.570920622490262 	 Accuracy: 0.3155149934810952
Delta: 0.0017605081277018942 	  Loss: 1.5710357863637316 	 Accuracy: 0.3155149934810952
Delta: 0.0007200538704694951 	  Loss: 1.5710568584961289 	 Accuracy: 0.3089960886571056
Delta: 6.040127038815289e-06 	  Loss: 1.5710553627871047 	 Accuracy: 0.3155149934810952
Delta: 0.0005286729175978811 	  Loss: 1.5710150007902688 	 Accuracy: 0.31421121251629724
Delta: 0.0028828399977498887 	  Loss: 1.5714156001171364 	 Accuracy: 0.3155149934810952
Delta: 0.0017737136359715212 	  Loss: 1.5710123675400856 	 Accuracy: 0.3155149934810952
Delta: 0.001946860820221713 	  Loss: 1.5715726434746693 	 Accuracy: 0.3155149934810952
Delta: 3.197911300445104e-05 	  Loss: 1.5713995244814 	 Accuracy: 0.3155149934810952
Delta: 0.0006156007447597058 	  Loss: 1.5713693789616454 	 Accuracy: 0.3155149934810952
Delta: 0.0015493679965182248 	  Loss: 1.5714089140190795 	 Accuracy: 0.3155149934810952
Delta: 0.001477871652693403 	  Loss: 1.5714845079161153 	 Accuracy: 0.3155149934810952
Delta: 0.0011311554214483732 	  Loss: 1.571359251972462 	 Accuracy: 0.3155149934810952
Delta: 0.0013065401648571086 	  Loss: 1.5713267125077723 	 Accuracy: 0.31421121251629724
Delta: 0.0028239687260807307 	  Loss: 1.5711148580070144 	 Accuracy: 0.3155149934810952
Delta: 0.0008958200014141435 	  Loss: 1.571229784835824 	 Accuracy: 0.3155149934810952
Delta: 0.0016277416215963601 	  Loss: 1.5713121844353337 	 Accuracy: 0.3116036505867014
Delta: 0.0016395017464958797 	  Loss: 1.5714529493623024 	 Accuracy: 0.3155149934810952
Delta: 0.001443994161590393 	  Loss: 1.5713762624313332 	 Accuracy: 0.31029986962190353
Delta: 4.263231500844918e-05 	  Loss: 1.5714751924183852 	 Accuracy: 0.31421121251629724
Delta: 0.0005841471896390002 	  Loss: 1.571336628684402 	 Accuracy: 0.3155149934810952
Delta: 9.647464431693677e-05 	  Loss: 1.5713533923170784 	 Accuracy: 0.3155149934810952
Delta: 5.029390637353868e-09 	  Loss: 1.57135339345126 	 Accuracy: 0.3155149934810952
converged at iter  97
Delta: 0.020903104174611983 	  Loss: 2.1567738992443575 	 Accuracy: 0.1981747066492829
Delta: 0.0191168170596221 	  Loss: 2.0414506025958703 	 Accuracy: 0.2620599739243807
Delta: 0.01741218892043589 	  Loss: 1.8517663532986302 	 Accuracy: 0.3259452411994785
Delta: 0.015006846223914065 	  Loss: 1.721718510695612 	 Accuracy: 0.3741851368970013
Delta: 0.013336188518202554 	  Loss: 1.652393386033974 	 Accuracy: 0.40808344198174706
Delta: 0.011243371042722848 	  Loss: 1.613492736497452 	 Accuracy: 0.4067796610169492

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009643453418085167 	  Loss: 1.5947341772655839 	 Accuracy: 0.39765319426336376
Delta: 0.008191478014321976 	  Loss: 1.5867578443891868 	 Accuracy: 0.3963494132985658
Delta: 0.007910253249848767 	  Loss: 1.5834152757580902 	 Accuracy: 0.3859191655801825
Delta: 0.0061453689231187525 	  Loss: 1.5820483225049033 	 Accuracy: 0.3820078226857888
Delta: 0.006472619132619225 	  Loss: 1.5813180178874209 	 Accuracy: 0.3820078226857888
Delta: 0.004801111295603439 	  Loss: 1.5810173581564235 	 Accuracy: 0.379400260756193
Delta: 0.004844609049291909 	  Loss: 1.5809741701075775 	 Accuracy: 0.38070404172099087
Delta: 0.0020852083425770894 	  Loss: 1.5807462411513127 	 Accuracy: 0.3820078226857888
Delta: 0.0034504693511155588 	  Loss: 1.5806262960099318 	 Accuracy: 0.3820078226857888
Delta: 0.0008102780053703991 	  Loss: 1.5806007430768367 	 Accuracy: 0.3820078226857888
Delta: 0.0009499096263936259 	  Loss: 1.5805838258090152 	 Accuracy: 0.38070404172099087
Delta: 0.0020462405187114474 	  Loss: 1.5807164392575808 	 Accuracy: 0.3820078226857888
Delta: 2.1941282197906775e-05 	  Loss: 1.5806746403458343 	 Accuracy: 0.38070404172099087
Delta: 0.0023994965675922923 	  Loss: 1.5806539668544937 	 Accuracy: 0.38070404172099087
Delta: 1.055479449100336e-05 	  Loss: 1.5806748555785255 	 Accuracy: 0.3820078226857888
Delta: 5.981247270414703e-05 	  Loss: 1.5808137283727102 	 Accuracy: 0.3833116036505867
Delta: 0.0026607207485318937 	  Loss: 1.5810078308097029 	 Accuracy: 0.3833116036505867
Delta: 0.002551509232919456 	  Loss: 1.58090160059436 	 Accuracy: 0.3833116036505867
Delta: 3.0872928627231486e-05 	  Loss: 1.5808024085290704 	 Accuracy: 0.3833116036505867
Delta: 4.03352706408441e-05 	  Loss: 1.5807745562165016 	 Accuracy: 0.3898305084745763
Delta: 0.0010027701225868194 	  Loss: 1.5807290305118245 	 Accuracy: 0.3820078226857888
Delta: 0.0028075575726861203 	  Loss: 1.5806165344501457 	 Accuracy: 0.3820078226857888
Delta: 5.5697713785950084e-05 	  Loss: 1.5805652318568053 	 Accuracy: 0.3820078226857888
Delta: 0.0020782466082250716 	  Loss: 1.580767688917781 	 Accuracy: 0.3820078226857888
Delta: 0.00467309231397479 	  Loss: 1.5809042342184965 	 Accuracy: 0.3820078226857888
Delta: 0.0023899146929995305 	  Loss: 1.5806485184670305 	 Accuracy: 0.3820078226857888
Delta: 0.0012940428453195663 	  Loss: 1.5809731128344175 	 Accuracy: 0.38070404172099087
Delta: 0.003409800369048779 	  Loss: 1.5809523590304029 	 Accuracy: 0.38070404172099087
Delta: 0.0013989292923692837 	  Loss: 1.5809873619087642 	 Accuracy: 0.38070404172099087
Delta: 0.000795551084926208 	  Loss: 1.5806377487540537 	 Accuracy: 0.3820078226857888
Delta: 0.0030013923127682053 	  Loss: 1.5810370798583229 	 Accuracy: 0.3820078226857888
Delta: 0.0020609561796792594 	  Loss: 1.5808447592654642 	 Accuracy: 0.38070404172099087
Delta: 0.0025050709652669955 	  Loss: 1.5807891720153662 	 Accuracy: 0.3820078226857888
Delta: 0.0018490042191032202 	  Loss: 1.5808303580683347 	 Accuracy: 0.3820078226857888
Delta: 0.0009060819077966169 	  Loss: 1.5807059978503135 	 Accuracy: 0.3820078226857888
Delta: 5.167706663387677e-05 	  Loss: 1.580758355929663 	 Accuracy: 0.3820078226857888
Delta: 7.625703779392578e-05 	  Loss: 1.5807227818692362 	 Accuracy: 0.3833116036505867
Delta: 0.0026683130773292106 	  Loss: 1.5810249414282171 	 Accuracy: 0.3820078226857888
Delta: 0.0028730903289956307 	  Loss: 1.580444605828396 	 Accuracy: 0.3833116036505867
Delta: 0.002642177918430465 	  Loss: 1.5804302897120226 	 Accuracy: 0.3820078226857888
Delta: 0.0009487154091871085 	  Loss: 1.5804207290319923 	 Accuracy: 0.3820078226857888
Delta: 0.000511044291346323 	  Loss: 1.5804440710698997 	 Accuracy: 0.38461538461538464
Delta: 0.0018400517495885463 	  Loss: 1.5803422772294322 	 Accuracy: 0.38722294654498046
Delta: 0.000882310000255079 	  Loss: 1.580375075081883 	 Accuracy: 0.3820078226857888
Delta: 0.0033711261940047865 	  Loss: 1.580785582701918 	 Accuracy: 0.3820078226857888
Delta: 0.003955153862605081 	  Loss: 1.580188555042327 	 Accuracy: 0.379400260756193
Delta: 0.0025443863140735567 	  Loss: 1.579939806941793 	 Accuracy: 0.3833116036505867
Delta: 0.0036195055813835635 	  Loss: 1.5798142392469412 	 Accuracy: 0.3820078226857888
Delta: 0.00010222742419634843 	  Loss: 1.5800113636093192 	 Accuracy: 0.3833116036505867
Delta: 5.004379215187758e-05 	  Loss: 1.5800304575498976 	 Accuracy: 0.3820078226857888
Delta: 9.2418933746743e-05 	  Loss: 1.579810323506671 	 Accuracy: 0.3833116036505867
Delta: 0.0036067239686283135 	  Loss: 1.5797067486059633 	 Accuracy: 0.3833116036505867
Delta: 0.004349587554544909 	  Loss: 1.5802465553349885 	 Accuracy: 0.379400260756193
Delta: 0.0019647106800676755 	  Loss: 1.580143623011128 	 Accuracy: 0.3833116036505867
Delta: 0.004296530551207917 	  Loss: 1.5798364409105334 	 Accuracy: 0.3833116036505867
Delta: 0.001998838913126598 	  Loss: 1.5795609487315083 	 Accuracy: 0.3833116036505867
Delta: 0.0036667427944181005 	  Loss: 1.5798735186653534 	 Accuracy: 0.3833116036505867
Delta: 0.003152209402020785 	  Loss: 1.5795059541470176 	 Accuracy: 0.3833116036505867
Delta: 0.003478962435390942 	  Loss: 1.580586797728051 	 Accuracy: 0.3820078226857888
Delta: 0.002890117865905728 	  Loss: 1.580758719262968 	 Accuracy: 0.38070404172099087
Delta: 0.002313624027692918 	  Loss: 1.5807959379959167 	 Accuracy: 0.38070404172099087
Delta: 0.0038562548461090695 	  Loss: 1.5817731675727342 	 Accuracy: 0.379400260756193
Delta: 0.0013675521523544188 	  Loss: 1.5820221350796595 	 Accuracy: 0.38070404172099087
Delta: 0.0009026439022858081 	  Loss: 1.5819014827825062 	 Accuracy: 0.38070404172099087
Delta: 0.004372057026754451 	  Loss: 1.5823428385920317 	 Accuracy: 0.3754889178617992
Delta: 0.003982482651891812 	  Loss: 1.5819078877672559 	 Accuracy: 0.3820078226857888
Delta: 0.003104429241539106 	  Loss: 1.5824872745523328 	 Accuracy: 0.379400260756193
Delta: 0.001456472465989241 	  Loss: 1.5824417116239475 	 Accuracy: 0.3820078226857888
Delta: 0.000857078869937134 	  Loss: 1.5823621488432198 	 Accuracy: 0.3820078226857888
Delta: 0.0038514219989610665 	  Loss: 1.5824504502225496 	 Accuracy: 0.38461538461538464
Delta: 2.7708046367638224e-05 	  Loss: 1.5824209216786425 	 Accuracy: 0.3820078226857888
Delta: 0.0025252563128426767 	  Loss: 1.5823691190717946 	 Accuracy: 0.3820078226857888
Delta: 0.001496054124683236 	  Loss: 1.5823540858590612 	 Accuracy: 0.3820078226857888
Delta: 0.0018257057985206452 	  Loss: 1.5822814169894273 	 Accuracy: 0.3820078226857888
Delta: 0.0010351727663451915 	  Loss: 1.5822621949264122 	 Accuracy: 0.3820078226857888
Delta: 6.087261395579116e-06 	  Loss: 1.5822631642623186 	 Accuracy: 0.38070404172099087
Delta: 0.006770935820045847 	  Loss: 1.5906042311488373 	 Accuracy: 0.3833116036505867
Delta: 0.005166856243352829 	  Loss: 1.586544048803042 	 Accuracy: 0.3859191655801825
Delta: 0.0035836473425005567 	  Loss: 1.5868688108843316 	 Accuracy: 0.3859191655801825
Delta: 0.0034370603682932826 	  Loss: 1.586115426308097 	 Accuracy: 0.38461538461538464
Delta: 0.0026664539913489093 	  Loss: 1.5861938004722989 	 Accuracy: 0.3859191655801825
Delta: 0.002599750258124381 	  Loss: 1.5861997836357995 	 Accuracy: 0.3859191655801825
Delta: 0.0021763573768314387 	  Loss: 1.5849979439718633 	 Accuracy: 0.38461538461538464
Delta: 0.0020598838276455747 	  Loss: 1.5854650059052684 	 Accuracy: 0.38722294654498046
Delta: 0.0028691925614798166 	  Loss: 1.5860889036167873 	 Accuracy: 0.38722294654498046
Delta: 0.004370693653018605 	  Loss: 1.58915074463074 	 Accuracy: 0.38722294654498046
Delta: 0.004950158125466973 	  Loss: 1.5930550708278188 	 Accuracy: 0.3833116036505867
Delta: 0.003952433447949631 	  Loss: 1.5880271149679233 	 Accuracy: 0.38722294654498046
Delta: 8.615278478237618e-05 	  Loss: 1.5884899079031845 	 Accuracy: 0.3833116036505867
Delta: 0.0010609476568250596 	  Loss: 1.5890716568656775 	 Accuracy: 0.3859191655801825
Delta: 0.004779548987439659 	  Loss: 1.5878768131639573 	 Accuracy: 0.3859191655801825
Delta: 0.0028206042817472366 	  Loss: 1.5884918838283255 	 Accuracy: 0.3859191655801825
Delta: 0.001961307116486535 	  Loss: 1.5884949701912987 	 Accuracy: 0.3859191655801825
Delta: 0.002380823334365405 	  Loss: 1.58834415034636 	 Accuracy: 0.3859191655801825
Delta: 0.02106152637656542 	  Loss: 2.1558911430602947 	 Accuracy: 0.2033898305084746
Delta: 0.01888292892799728 	  Loss: 2.0414167308097992 	 Accuracy: 0.32073011734028684
Delta: 0.017551930587080652 	  Loss: 1.856488091666926 	 Accuracy: 0.26727509778357234
Delta: 0.01595097325311732 	  Loss: 1.7059999641406225 	 Accuracy: 0.23989569752281617
Delta: 0.01309009743682921 	  Loss: 1.6176567583320156 	 Accuracy: 0.23468057366362452
Delta: 0.009601210176976542 	  Loss: 1.5888998832155719 	 Accuracy: 0.23859191655801826
Delta: 0.007562191997248088 	  Loss: 1.5805226315585665 	 Accuracy: 0.2516297262059974

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006274856816543537 	  Loss: 1.5775377864584126 	 Accuracy: 0.24902216427640156
Delta: 0.00532746836167617 	  Loss: 1.5764045985171822 	 Accuracy: 0.2516297262059974
Delta: 0.00393059353935458 	  Loss: 1.5760459376697127 	 Accuracy: 0.2503259452411995
Delta: 0.0032604885447593502 	  Loss: 1.5758331487523995 	 Accuracy: 0.2503259452411995
Delta: 0.0024519962063443927 	  Loss: 1.5758721376230056 	 Accuracy: 0.2503259452411995
Delta: 0.0029420212909372473 	  Loss: 1.5757713247195548 	 Accuracy: 0.2503259452411995
Delta: 0.0031090759139458294 	  Loss: 1.5757426588769237 	 Accuracy: 0.2516297262059974
Delta: 0.0007718065949176911 	  Loss: 1.575770768754046 	 Accuracy: 0.2503259452411995
Delta: 0.0013624575552316526 	  Loss: 1.5757483606597305 	 Accuracy: 0.2503259452411995
Delta: 2.6499095770371663e-05 	  Loss: 1.575751009481574 	 Accuracy: 0.2503259452411995
Delta: 9.532886470068911e-06 	  Loss: 1.5757476565593183 	 Accuracy: 0.2516297262059974
Delta: 0.0007218082902752246 	  Loss: 1.5757135366482684 	 Accuracy: 0.2503259452411995
Delta: 0.0007291152730583533 	  Loss: 1.5757531715869595 	 Accuracy: 0.2503259452411995
Delta: 0.000979619881137763 	  Loss: 1.575778000861097 	 Accuracy: 0.2503259452411995
Delta: 0.0033075984842430243 	  Loss: 1.575606880410156 	 Accuracy: 0.2516297262059974
Delta: 0.002609695988561914 	  Loss: 1.5757894482761898 	 Accuracy: 0.2516297262059974
Delta: 9.152199858975771e-05 	  Loss: 1.5756434423270234 	 Accuracy: 0.24902216427640156
Delta: 0.0012656105521033168 	  Loss: 1.5758981870002504 	 Accuracy: 0.2516297262059974
Delta: 0.0016781172837142132 	  Loss: 1.5757483038322477 	 Accuracy: 0.2516297262059974
Delta: 8.174771077845254e-05 	  Loss: 1.575321153827272 	 Accuracy: 0.2516297262059974
Delta: 6.733376571609311e-05 	  Loss: 1.5755325461440213 	 Accuracy: 0.2516297262059974
Delta: 8.090243243276126e-05 	  Loss: 1.5756731647128286 	 Accuracy: 0.2516297262059974
Delta: 0.0023257077805666575 	  Loss: 1.5754411970668216 	 Accuracy: 0.25554106910039115
Delta: 0.0007645523443877016 	  Loss: 1.5755587870273078 	 Accuracy: 0.2503259452411995
Delta: 0.001024890524760131 	  Loss: 1.5755640195734584 	 Accuracy: 0.2503259452411995
Delta: 0.0012205642960425186 	  Loss: 1.5755036000259999 	 Accuracy: 0.2503259452411995
Delta: 4.916775578339784e-05 	  Loss: 1.5755187667358188 	 Accuracy: 0.2503259452411995
Delta: 0.0024025507358210224 	  Loss: 1.575611993873527 	 Accuracy: 0.2516297262059974
Delta: 0.00011177409340691307 	  Loss: 1.5755494182803038 	 Accuracy: 0.2529335071707953
Delta: 7.081700817351048e-05 	  Loss: 1.5755168675632483 	 Accuracy: 0.2503259452411995
Delta: 0.0007951493759092445 	  Loss: 1.5757516214279992 	 Accuracy: 0.2503259452411995
Delta: 0.0007472521683521603 	  Loss: 1.5756093480538498 	 Accuracy: 0.2516297262059974
Delta: 5.381496258709699e-05 	  Loss: 1.5756184323534934 	 Accuracy: 0.2503259452411995
Delta: 3.355953963077201e-05 	  Loss: 1.5755164568097233 	 Accuracy: 0.2529335071707953
Delta: 0.0022876648756450933 	  Loss: 1.5753345914172523 	 Accuracy: 0.2503259452411995
Delta: 0.0028700132640369267 	  Loss: 1.575151205848419 	 Accuracy: 0.25554106910039115
Delta: 0.005360280861543482 	  Loss: 1.575693293364745 	 Accuracy: 0.258148631029987
Delta: 0.00433583213335551 	  Loss: 1.5758452917674157 	 Accuracy: 0.24902216427640156
Delta: 0.0024666622664647076 	  Loss: 1.5757261088094832 	 Accuracy: 0.2542372881355932
Delta: 0.0037963162729996933 	  Loss: 1.5755718463850474 	 Accuracy: 0.2542372881355932
Delta: 0.0031428269208091416 	  Loss: 1.5757496978045307 	 Accuracy: 0.25554106910039115
Delta: 0.00333060120473926 	  Loss: 1.575090438907118 	 Accuracy: 0.2542372881355932
Delta: 0.004444210671136879 	  Loss: 1.57519917618015 	 Accuracy: 0.2542372881355932
Delta: 0.0040190287185140885 	  Loss: 1.575499746134022 	 Accuracy: 0.24641460234680573
Delta: 0.00373462217739647 	  Loss: 1.5746761574854178 	 Accuracy: 0.2542372881355932
Delta: 0.0017030970508383162 	  Loss: 1.5749077390713422 	 Accuracy: 0.2542372881355932
Delta: 0.002225046159318467 	  Loss: 1.5747236157464561 	 Accuracy: 0.2516297262059974
Delta: 0.001818462502005544 	  Loss: 1.5753489234024833 	 Accuracy: 0.2529335071707953
Delta: 0.0029397356229156945 	  Loss: 1.5759303872929218 	 Accuracy: 0.25554106910039115
Delta: 0.0027454285385862137 	  Loss: 1.5757605017598384 	 Accuracy: 0.2516297262059974
Delta: 0.0035039603970187937 	  Loss: 1.5760716465695555 	 Accuracy: 0.2529335071707953
Delta: 0.0008086345871702194 	  Loss: 1.5756375256446589 	 Accuracy: 0.25554106910039115
Delta: 5.29502483195798e-05 	  Loss: 1.5755666691673005 	 Accuracy: 0.25554106910039115
Delta: 0.0021896419051129533 	  Loss: 1.5754308303366464 	 Accuracy: 0.25554106910039115
Delta: 0.003106265857889924 	  Loss: 1.575368357209266 	 Accuracy: 0.25554106910039115
Delta: 0.0031865927609553697 	  Loss: 1.5754680964484489 	 Accuracy: 0.2529335071707953
Delta: 0.0028918394051682937 	  Loss: 1.5756171156284016 	 Accuracy: 0.2529335071707953
Delta: 0.0035298285659048946 	  Loss: 1.5760673864268109 	 Accuracy: 0.2529335071707953
Delta: 0.0017342861623256154 	  Loss: 1.5758168670967856 	 Accuracy: 0.2529335071707953
Delta: 0.0009747499613057496 	  Loss: 1.5760007350237268 	 Accuracy: 0.2529335071707953
Delta: 0.00107874146470415 	  Loss: 1.5759194732777635 	 Accuracy: 0.2542372881355932
Delta: 0.0006868088735097766 	  Loss: 1.5761201593933318 	 Accuracy: 0.2529335071707953
Delta: 4.8694302971737235e-05 	  Loss: 1.5760350671603804 	 Accuracy: 0.2542372881355932
Delta: 0.0011865217215281043 	  Loss: 1.5759888044911312 	 Accuracy: 0.25554106910039115
Delta: 0.0029784027999734753 	  Loss: 1.575896692285334 	 Accuracy: 0.2503259452411995
Delta: 0.001980880241118042 	  Loss: 1.5762761976582715 	 Accuracy: 0.25554106910039115
Delta: 0.001161498420204016 	  Loss: 1.5762051072577903 	 Accuracy: 0.2529335071707953
Delta: 0.0015744852614058551 	  Loss: 1.5764616040620276 	 Accuracy: 0.2542372881355932
Delta: 0.0022983935529384543 	  Loss: 1.5765615504185595 	 Accuracy: 0.2542372881355932
Delta: 0.0026219517144203267 	  Loss: 1.576657068869341 	 Accuracy: 0.25554106910039115
Delta: 0.002246623309135724 	  Loss: 1.5767098405445485 	 Accuracy: 0.2542372881355932
Delta: 0.004544344457178202 	  Loss: 1.576895801993027 	 Accuracy: 0.25554106910039115
Delta: 0.004032645100298123 	  Loss: 1.5764165748022143 	 Accuracy: 0.2542372881355932
Delta: 0.0008395546367353939 	  Loss: 1.5763242657358751 	 Accuracy: 0.2542372881355932
Delta: 0.00314637786272425 	  Loss: 1.577187434096294 	 Accuracy: 0.25684485006518903
Delta: 0.003783960721023301 	  Loss: 1.5768580802597163 	 Accuracy: 0.25554106910039115
Delta: 0.002174537066517739 	  Loss: 1.5764537335834943 	 Accuracy: 0.2542372881355932
Delta: 0.003646423424982836 	  Loss: 1.5762637787302711 	 Accuracy: 0.2542372881355932
Delta: 0.001724051745595973 	  Loss: 1.5758092126824454 	 Accuracy: 0.2529335071707953
Delta: 0.00356468477323086 	  Loss: 1.576750061495431 	 Accuracy: 0.2529335071707953
Delta: 0.002944758719165895 	  Loss: 1.5760092543627868 	 Accuracy: 0.2529335071707953
Delta: 0.004568749573250275 	  Loss: 1.5772078288635052 	 Accuracy: 0.2529335071707953
Delta: 0.0035968697934309697 	  Loss: 1.57651848173932 	 Accuracy: 0.25684485006518903
Delta: 0.005057500352642928 	  Loss: 1.5775410974298862 	 Accuracy: 0.25554106910039115
Delta: 0.005522438299505863 	  Loss: 1.5768259074984248 	 Accuracy: 0.25554106910039115
Delta: 0.0039613764445229635 	  Loss: 1.5769141576634205 	 Accuracy: 0.25554106910039115
Delta: 0.0022621161952635716 	  Loss: 1.577735581486491 	 Accuracy: 0.25554106910039115
Delta: 0.0022431782996333253 	  Loss: 1.5777241242081441 	 Accuracy: 0.258148631029987
Delta: 0.00440258597642792 	  Loss: 1.5778957027294571 	 Accuracy: 0.25945241199478486
Delta: 0.004832367879027029 	  Loss: 1.5776638801143992 	 Accuracy: 0.25554106910039115
Delta: 0.001609340690135568 	  Loss: 1.577265327887133 	 Accuracy: 0.2529335071707953
Delta: 0.001990960153107071 	  Loss: 1.5771041232105165 	 Accuracy: 0.2542372881355932
Delta: 0.0013779074226558485 	  Loss: 1.5780205375594827 	 Accuracy: 0.25554106910039115
Delta: 0.021012932836296787 	  Loss: 2.1559294697095446 	 Accuracy: 0.196870925684485
Delta: 0.01914488448768279 	  Loss: 2.0345953256876634 	 Accuracy: 0.2985658409387223
Delta: 0.017754079316086115 	  Loss: 1.8303335357318251 	 Accuracy: 0.3650586701434159
Delta: 0.015572659034540127 	  Loss: 1.6950797244193363 	 Accuracy: 0.4002607561929596
Delta: 0.013275460577362801 	  Loss: 1.6298010571233323 	 Accuracy: 0.39113428943937417
Delta: 0.010765284778143364 	  Loss: 1.6015214371744002 	 Accuracy: 0.4067796610169492

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009063041502483363 	  Loss: 1.589150560004133 	 Accuracy: 0.40808344198174706
Delta: 0.007696364030423201 	  Loss: 1.5838442687129888 	 Accuracy: 0.4067796610169492
Delta: 0.00555401046846262 	  Loss: 1.5825687107925037 	 Accuracy: 0.4067796610169492
Delta: 0.0043799200826590695 	  Loss: 1.5821523824937846 	 Accuracy: 0.40808344198174706
Delta: 0.0036170765504472684 	  Loss: 1.5823308183921179 	 Accuracy: 0.4067796610169492
Delta: 0.0019597554786871425 	  Loss: 1.5821150744271837 	 Accuracy: 0.409387222946545
Delta: 0.0030022751207606224 	  Loss: 1.5816742047105674 	 Accuracy: 0.409387222946545
Delta: 0.00225124750924842 	  Loss: 1.5819672860289424 	 Accuracy: 0.409387222946545
Delta: 5.260420735605224e-05 	  Loss: 1.5817510026698602 	 Accuracy: 0.409387222946545
Delta: 0.0015430677796939441 	  Loss: 1.5816209045787657 	 Accuracy: 0.409387222946545
Delta: 2.542520668496211e-05 	  Loss: 1.5815512877643847 	 Accuracy: 0.4106910039113429
Delta: 3.780759914569287e-05 	  Loss: 1.581514286486094 	 Accuracy: 0.40808344198174706
Delta: 0.0016204377653094375 	  Loss: 1.5814304614800196 	 Accuracy: 0.409387222946545
Delta: 8.460017206746767e-05 	  Loss: 1.5815942160590128 	 Accuracy: 0.4106910039113429
Delta: 9.405096884020616e-05 	  Loss: 1.581650527783325 	 Accuracy: 0.4106910039113429
Delta: 0.0010045533141085864 	  Loss: 1.5814131672917813 	 Accuracy: 0.4106910039113429
Delta: 0.0020427643495253586 	  Loss: 1.5813425921175124 	 Accuracy: 0.4106910039113429
Delta: 0.0009558214687951956 	  Loss: 1.581300317136598 	 Accuracy: 0.4106910039113429
Delta: 0.00155605544579444 	  Loss: 1.5812931762006808 	 Accuracy: 0.4106910039113429
Delta: 0.0010262693872974504 	  Loss: 1.5816209605352576 	 Accuracy: 0.4106910039113429
Delta: 0.0010387545099963089 	  Loss: 1.581342297461369 	 Accuracy: 0.41199478487614083
Delta: 0.0022476914728562897 	  Loss: 1.5813770102067832 	 Accuracy: 0.4106910039113429
Delta: 0.0022567158045312305 	  Loss: 1.5814120376177163 	 Accuracy: 0.41199478487614083
Delta: 0.0025005285803771844 	  Loss: 1.580941220399231 	 Accuracy: 0.4106910039113429
Delta: 0.0013839075747858335 	  Loss: 1.5813013379634753 	 Accuracy: 0.4106910039113429
Delta: 8.878010692978839e-05 	  Loss: 1.5812893234991927 	 Accuracy: 0.4106910039113429
Delta: 0.0008388069018177236 	  Loss: 1.5812595515746144 	 Accuracy: 0.4106910039113429
Delta: 0.003331744604700075 	  Loss: 1.581901830124353 	 Accuracy: 0.41199478487614083
Delta: 0.0009808797729142311 	  Loss: 1.5813631775272574 	 Accuracy: 0.4106910039113429
Delta: 0.0031257146441810674 	  Loss: 1.5812677407993543 	 Accuracy: 0.41199478487614083
Delta: 0.003595518829936679 	  Loss: 1.580825443165442 	 Accuracy: 0.4106910039113429
Delta: 0.0011088840099887343 	  Loss: 1.5812430549366479 	 Accuracy: 0.4106910039113429
Delta: 0.0023644773512231623 	  Loss: 1.5813848647049233 	 Accuracy: 0.41199478487614083
Delta: 0.0019980005646988443 	  Loss: 1.5812231768866603 	 Accuracy: 0.41199478487614083
Delta: 0.0017528635567229133 	  Loss: 1.5814072986420946 	 Accuracy: 0.4106910039113429
Delta: 0.0025508256698476756 	  Loss: 1.5813272894151742 	 Accuracy: 0.4106910039113429
Delta: 7.743033761228867e-05 	  Loss: 1.5813400864926725 	 Accuracy: 0.4106910039113429
Delta: 8.962554333812204e-05 	  Loss: 1.5812977539654418 	 Accuracy: 0.4106910039113429
Delta: 0.0005144811283896751 	  Loss: 1.5813388949409122 	 Accuracy: 0.41199478487614083
Delta: 3.79318528139782e-05 	  Loss: 1.5812489488000487 	 Accuracy: 0.41199478487614083
Delta: 3.426890127834681e-05 	  Loss: 1.5811862458092123 	 Accuracy: 0.4106910039113429
Delta: 0.0019000536378708094 	  Loss: 1.5813037114737143 	 Accuracy: 0.4106910039113429
Delta: 0.0021214675758222663 	  Loss: 1.581394617965569 	 Accuracy: 0.41199478487614083
Delta: 0.002189429137398813 	  Loss: 1.5819063258269748 	 Accuracy: 0.4132985658409387
Delta: 0.003260983657334327 	  Loss: 1.5819899755257725 	 Accuracy: 0.4106910039113429
Delta: 4.660947146715269e-05 	  Loss: 1.5816797364204311 	 Accuracy: 0.4106910039113429
Delta: 9.250351533037446e-05 	  Loss: 1.5818577416167825 	 Accuracy: 0.4106910039113429
Delta: 0.0008251187147234025 	  Loss: 1.58181237310749 	 Accuracy: 0.4106910039113429
Delta: 9.430150398085872e-05 	  Loss: 1.5819884959760513 	 Accuracy: 0.409387222946545
Delta: 0.002982033714639465 	  Loss: 1.5815734823810186 	 Accuracy: 0.41199478487614083
Delta: 0.00296721971527887 	  Loss: 1.5826939601900503 	 Accuracy: 0.4106910039113429
Delta: 0.003476962619952939 	  Loss: 1.582313450657113 	 Accuracy: 0.4106910039113429
Delta: 0.002982250164689643 	  Loss: 1.5823391474177677 	 Accuracy: 0.41199478487614083
Delta: 0.0018506497926243785 	  Loss: 1.5823853364975125 	 Accuracy: 0.4106910039113429
Delta: 3.0834129251105454e-05 	  Loss: 1.5823067745227395 	 Accuracy: 0.41199478487614083
Delta: 0.002236071126600437 	  Loss: 1.5808758587801148 	 Accuracy: 0.409387222946545
Delta: 0.0029951212298485316 	  Loss: 1.5810059261854756 	 Accuracy: 0.4106910039113429
Delta: 0.00125976521051498 	  Loss: 1.582398639352137 	 Accuracy: 0.4106910039113429
Delta: 0.003475866530069116 	  Loss: 1.5830805992895933 	 Accuracy: 0.409387222946545
Delta: 0.001968364334059673 	  Loss: 1.5836450159277233 	 Accuracy: 0.4067796610169492
Delta: 0.003294042886709189 	  Loss: 1.584339647051402 	 Accuracy: 0.409387222946545
Delta: 0.0045729997237870315 	  Loss: 1.583873225121186 	 Accuracy: 0.40808344198174706
Delta: 0.0008314482999618157 	  Loss: 1.583859401159125 	 Accuracy: 0.40808344198174706
Delta: 0.0028065671578180857 	  Loss: 1.583737198892274 	 Accuracy: 0.40808344198174706
Delta: 1.7901933438920306e-05 	  Loss: 1.5838242599154673 	 Accuracy: 0.4172099087353325
Delta: 0.0015732923045484917 	  Loss: 1.5840914591917565 	 Accuracy: 0.4067796610169492
Delta: 0.0023970266094466334 	  Loss: 1.583436629758178 	 Accuracy: 0.40547588005215124
Delta: 0.0006194968966856031 	  Loss: 1.5836290485514506 	 Accuracy: 0.4067796610169492
Delta: 0.0017020298337347948 	  Loss: 1.5837829198350684 	 Accuracy: 0.4067796610169492
Delta: 0.0006426915378651676 	  Loss: 1.5825821384030192 	 Accuracy: 0.409387222946545
Delta: 0.001289956345548744 	  Loss: 1.5826050256071365 	 Accuracy: 0.409387222946545
Delta: 0.002265068036735161 	  Loss: 1.5829371433762787 	 Accuracy: 0.409387222946545
Delta: 0.0015841771535999888 	  Loss: 1.5836869924805683 	 Accuracy: 0.409387222946545
Delta: 0.0024487677365585773 	  Loss: 1.583811744962318 	 Accuracy: 0.409387222946545
Delta: 0.0030893489711023773 	  Loss: 1.583700972877423 	 Accuracy: 0.409387222946545
Delta: 0.0037740859679860454 	  Loss: 1.5835991029588827 	 Accuracy: 0.4067796610169492
Delta: 0.004231541347692075 	  Loss: 1.5859411771679717 	 Accuracy: 0.40808344198174706
Delta: 0.004426734136156642 	  Loss: 1.5855070493480743 	 Accuracy: 0.4106910039113429
Delta: 0.003619921547832065 	  Loss: 1.585563449588264 	 Accuracy: 0.4106910039113429
Delta: 0.002308897615719259 	  Loss: 1.585636765751028 	 Accuracy: 0.4067796610169492
Delta: 0.0028718713603932172 	  Loss: 1.5858237150939316 	 Accuracy: 0.40808344198174706
Delta: 0.004452781908097765 	  Loss: 1.586238080580671 	 Accuracy: 0.4106910039113429
Delta: 0.0020468452453454964 	  Loss: 1.5860595308585954 	 Accuracy: 0.409387222946545
Delta: 0.0021177006731156866 	  Loss: 1.5859664418491843 	 Accuracy: 0.4106910039113429
Delta: 7.810824354056877e-05 	  Loss: 1.586170993586248 	 Accuracy: 0.40808344198174706
Delta: 0.0028424242830892344 	  Loss: 1.5859758646347526 	 Accuracy: 0.40808344198174706
Delta: 0.002537483548709482 	  Loss: 1.5860295282789358 	 Accuracy: 0.409387222946545
Delta: 0.002027533590339277 	  Loss: 1.5861102577503154 	 Accuracy: 0.40808344198174706
Delta: 0.002794607525982154 	  Loss: 1.5865349934999977 	 Accuracy: 0.4106910039113429
Delta: 0.002509307586491796 	  Loss: 1.5862007360507613 	 Accuracy: 0.41199478487614083
Delta: 0.003589705391563009 	  Loss: 1.585732150131068 	 Accuracy: 0.4106910039113429
Delta: 0.0016711747987663123 	  Loss: 1.5853358289815067 	 Accuracy: 0.41199478487614083
Delta: 0.00264815001686806 	  Loss: 1.5853630952648867 	 Accuracy: 0.4106910039113429
Delta: 0.001642152467097702 	  Loss: 1.5864485595300692 	 Accuracy: 0.4106910039113429
Delta: 0.020921969827304862 	  Loss: 2.157614898674953 	 Accuracy: 0.20078226857887874
Delta: 0.01927151957793102 	  Loss: 2.0300987781927167 	 Accuracy: 0.2685788787483703
Delta: 0.01754338707872064 	  Loss: 1.8227888295574552 	 Accuracy: 0.3011734028683181
Delta: 0.015213811382497803 	  Loss: 1.696984764435293 	 Accuracy: 0.28552803129074317
Delta: 0.013274379686024233 	  Loss: 1.6419388403653192 	 Accuracy: 0.28292046936114734

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.011054607642268545 	  Loss: 1.6138166729096646 	 Accuracy: 0.29726205997392435
Delta: 0.009106958827334612 	  Loss: 1.6025385370659038 	 Accuracy: 0.2920469361147327
Delta: 0.006168616169419669 	  Loss: 1.5998037553221018 	 Accuracy: 0.29595827900912647
Delta: 0.005019529426484616 	  Loss: 1.5991845154635957 	 Accuracy: 0.29465449804432853
Delta: 0.0030798698498188232 	  Loss: 1.599781155118174 	 Accuracy: 0.29465449804432853
Delta: 0.0020536774887104157 	  Loss: 1.5997721007460524 	 Accuracy: 0.29465449804432853
Delta: 0.0026957054748717978 	  Loss: 1.599827794577371 	 Accuracy: 0.29465449804432853
Delta: 0.0012299333079457953 	  Loss: 1.5993774408609092 	 Accuracy: 0.29595827900912647
Delta: 0.0021396108974146557 	  Loss: 1.599100637049855 	 Accuracy: 0.29595827900912647
Delta: 0.003485690800736368 	  Loss: 1.599384701786476 	 Accuracy: 0.29595827900912647
Delta: 0.0023912723047723734 	  Loss: 1.5995173128209783 	 Accuracy: 0.29595827900912647
Delta: 0.0008277170156183797 	  Loss: 1.599825664945255 	 Accuracy: 0.29465449804432853
Delta: 0.0007326699648414165 	  Loss: 1.5997817483369574 	 Accuracy: 0.29595827900912647
Delta: 0.0007456855033456074 	  Loss: 1.5995652906808764 	 Accuracy: 0.29465449804432853
Delta: 0.0005301285761888486 	  Loss: 1.5994976870393085 	 Accuracy: 0.29595827900912647
Delta: 0.00087314870546316 	  Loss: 1.5994509530058965 	 Accuracy: 0.29595827900912647
Delta: 0.0007280673840493054 	  Loss: 1.5994825355439026 	 Accuracy: 0.29465449804432853
Delta: 4.31347493982764e-05 	  Loss: 1.5997377088294138 	 Accuracy: 0.29465449804432853
Delta: 0.003987773682273895 	  Loss: 1.599689383807822 	 Accuracy: 0.29465449804432853
Delta: 0.0023721682333101538 	  Loss: 1.5994156171863976 	 Accuracy: 0.29465449804432853
Delta: 0.0018243929500990864 	  Loss: 1.599563905636336 	 Accuracy: 0.29465449804432853
Delta: 0.0007592027658587389 	  Loss: 1.599870722685435 	 Accuracy: 0.29465449804432853
Delta: 2.4287070274743615e-05 	  Loss: 1.59984603727204 	 Accuracy: 0.29595827900912647
Delta: 0.0026850056801155267 	  Loss: 1.6001732500201702 	 Accuracy: 0.29465449804432853
Delta: 0.0017715658984801157 	  Loss: 1.6003480883356866 	 Accuracy: 0.29465449804432853
Delta: 0.003336611542219498 	  Loss: 1.6001774280525507 	 Accuracy: 0.29595827900912647
Delta: 0.003085362812963387 	  Loss: 1.6001409476053101 	 Accuracy: 0.29595827900912647
Delta: 0.001437403891711723 	  Loss: 1.5997667120565071 	 Accuracy: 0.29595827900912647
Delta: 4.515701018771763e-05 	  Loss: 1.5998629082724452 	 Accuracy: 0.29595827900912647
Delta: 0.002771970236205742 	  Loss: 1.5997973609013136 	 Accuracy: 0.29595827900912647
Delta: 0.0019821840616038207 	  Loss: 1.6000448445210813 	 Accuracy: 0.29595827900912647
Delta: 0.0021602043368723328 	  Loss: 1.6000108533089727 	 Accuracy: 0.29465449804432853
Delta: 0.0013231322885829352 	  Loss: 1.600173875107163 	 Accuracy: 0.29465449804432853
Delta: 2.2013190188242797e-05 	  Loss: 1.600094316452973 	 Accuracy: 0.29465449804432853
Delta: 0.002107680506636954 	  Loss: 1.6002643528740899 	 Accuracy: 0.29595827900912647
Delta: 0.0005200108426541798 	  Loss: 1.6002479164254535 	 Accuracy: 0.29465449804432853
Delta: 0.004208101188905497 	  Loss: 1.60047115122459 	 Accuracy: 0.29465449804432853
Delta: 0.0009105705474449394 	  Loss: 1.6006074982668217 	 Accuracy: 0.29465449804432853
Delta: 0.0009725164202880821 	  Loss: 1.6005204643330004 	 Accuracy: 0.29335071707953064
Delta: 0.0033778137196428916 	  Loss: 1.6011010130895067 	 Accuracy: 0.29465449804432853
Delta: 0.0038607053631277313 	  Loss: 1.6007876733790694 	 Accuracy: 0.29465449804432853
Delta: 0.0011549444621977362 	  Loss: 1.6005419922280324 	 Accuracy: 0.29465449804432853
Delta: 0.004310571650144117 	  Loss: 1.600537753495104 	 Accuracy: 0.29465449804432853
Delta: 0.0030183536740930384 	  Loss: 1.5998160037156268 	 Accuracy: 0.29595827900912647
Delta: 0.0028927740995776953 	  Loss: 1.600476271744855 	 Accuracy: 0.29465449804432853
Delta: 0.0015735610167869616 	  Loss: 1.5999623723525238 	 Accuracy: 0.29465449804432853
Delta: 0.003636020696281113 	  Loss: 1.5997263500789667 	 Accuracy: 0.29465449804432853
Delta: 0.0008775968473346589 	  Loss: 1.5997364386844897 	 Accuracy: 0.29465449804432853
Delta: 0.0007013666337094058 	  Loss: 1.599658317061201 	 Accuracy: 0.29465449804432853
Delta: 0.0014353406877567606 	  Loss: 1.5997946848489797 	 Accuracy: 0.29465449804432853
Delta: 0.0055254592826250734 	  Loss: 1.5985929294965262 	 Accuracy: 0.29465449804432853
Delta: 0.0038542100310742598 	  Loss: 1.5996298445045136 	 Accuracy: 0.29465449804432853
Delta: 0.006283812795043595 	  Loss: 1.5994581826485819 	 Accuracy: 0.2894393741851369
Delta: 0.007120494173139113 	  Loss: 1.6003776819945479 	 Accuracy: 0.2920469361147327
Delta: 0.0032954680453711944 	  Loss: 1.5995667301080685 	 Accuracy: 0.29465449804432853
Delta: 0.004309502264922509 	  Loss: 1.5993092870497772 	 Accuracy: 0.29465449804432853
Delta: 0.0040106314025505335 	  Loss: 1.5999143755748246 	 Accuracy: 0.29335071707953064
Delta: 0.0031822176173066175 	  Loss: 1.599942658334264 	 Accuracy: 0.29335071707953064
Delta: 0.000739162331282989 	  Loss: 1.5999296524622246 	 Accuracy: 0.29595827900912647
Delta: 0.0013620157903622581 	  Loss: 1.5999434741814664 	 Accuracy: 0.2920469361147327
Delta: 0.0030200611136738703 	  Loss: 1.5996149442866068 	 Accuracy: 0.29335071707953064
Delta: 0.001832343736732315 	  Loss: 1.5997629895909748 	 Accuracy: 0.29465449804432853
Delta: 0.002383720921221846 	  Loss: 1.5997403171042097 	 Accuracy: 0.29465449804432853
Delta: 0.002527972831774414 	  Loss: 1.599955972716475 	 Accuracy: 0.29465449804432853
Delta: 9.506084550388139e-05 	  Loss: 1.599901600903491 	 Accuracy: 0.29465449804432853
Delta: 0.0010275976257533809 	  Loss: 1.5997300483937287 	 Accuracy: 0.29465449804432853
Delta: 0.0012262500901992943 	  Loss: 1.5999892034651528 	 Accuracy: 0.29465449804432853
Delta: 0.0027710526277069394 	  Loss: 1.60021592285294 	 Accuracy: 0.29335071707953064
Delta: 0.005464537088770093 	  Loss: 1.5999984229574284 	 Accuracy: 0.29595827900912647
Delta: 0.0030268945796587078 	  Loss: 1.5994165411491674 	 Accuracy: 0.29465449804432853
Delta: 0.003802200264199286 	  Loss: 1.5991680173507135 	 Accuracy: 0.29465449804432853
Delta: 0.0025697477657952213 	  Loss: 1.5994346669219643 	 Accuracy: 0.29465449804432853
Delta: 0.0043110430281935895 	  Loss: 1.5992927450249492 	 Accuracy: 0.29465449804432853
Delta: 0.0005607164570808775 	  Loss: 1.5993457098039665 	 Accuracy: 0.29465449804432853
Delta: 0.0036660585841222547 	  Loss: 1.5992359986889033 	 Accuracy: 0.29726205997392435
Delta: 0.0031961523118163603 	  Loss: 1.599332072574008 	 Accuracy: 0.29726205997392435
Delta: 0.0021634751737542282 	  Loss: 1.599988833675174 	 Accuracy: 0.29726205997392435
Delta: 0.00400822825925696 	  Loss: 1.5992174588314052 	 Accuracy: 0.2985658409387223
Delta: 0.0011900546520429603 	  Loss: 1.5990684607982657 	 Accuracy: 0.29986962190352023
Delta: 0.0028550050289331756 	  Loss: 1.598720322951754 	 Accuracy: 0.2985658409387223
Delta: 0.0048564014302329385 	  Loss: 1.5994544144464093 	 Accuracy: 0.2985658409387223
Delta: 0.0044658393332614385 	  Loss: 1.5997135694761684 	 Accuracy: 0.29986962190352023
Delta: 0.005765909741596458 	  Loss: 1.5992482188074657 	 Accuracy: 0.29726205997392435
Delta: 0.004820727816206921 	  Loss: 1.599109972218188 	 Accuracy: 0.30247718383311606
Delta: 0.004835259195973106 	  Loss: 1.5984418205520612 	 Accuracy: 0.2985658409387223
Delta: 0.0042633650957122115 	  Loss: 1.5984964399948756 	 Accuracy: 0.29986962190352023
Delta: 0.003248485120637371 	  Loss: 1.5987434920058374 	 Accuracy: 0.29986962190352023
Delta: 0.004115896247771948 	  Loss: 1.5990660227855154 	 Accuracy: 0.2985658409387223
Delta: 0.0017399260854924668 	  Loss: 1.5986677957303574 	 Accuracy: 0.29986962190352023
Delta: 0.003260586688352793 	  Loss: 1.5986254349065123 	 Accuracy: 0.29986962190352023
Delta: 0.0026461560941997233 	  Loss: 1.598718030666479 	 Accuracy: 0.29986962190352023
Delta: 0.0020092394721227622 	  Loss: 1.5989112180533827 	 Accuracy: 0.3011734028683181
Delta: 0.00013238690744428163 	  Loss: 1.5991397664840532 	 Accuracy: 0.29986962190352023
Delta: 0.0016658582497859219 	  Loss: 1.599340713024712 	 Accuracy: 0.3011734028683181
Delta: 4.060508432432691e-05 	  Loss: 1.5992993090784715 	 Accuracy: 0.29986962190352023
Delta: 0.02095565470684364 	  Loss: 2.1565313991115316 	 Accuracy: 0.2046936114732725
Delta: 0.01912656087792694 	  Loss: 2.0284881546467664 	 Accuracy: 0.3455019556714472
Delta: 0.017776194738250404 	  Loss: 1.8206608168675316 	 Accuracy: 0.32073011734028684
Delta: 0.015805865161262197 	  Loss: 1.6850679673177034 	 Accuracy: 0.2542372881355932
Delta: 0.013035864995084625 	  Loss: 1.6225633142013351 	 Accuracy: 0.24902216427640156

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009731259616915566 	  Loss: 1.6023899975126215 	 Accuracy: 0.24641460234680573
Delta: 0.007246904137761985 	  Loss: 1.5978156745719156 	 Accuracy: 0.24771838331160365
Delta: 0.005839116624240441 	  Loss: 1.5971919313596445 	 Accuracy: 0.24641460234680573
Delta: 0.0049761930189475174 	  Loss: 1.5975071779892964 	 Accuracy: 0.242503259452412
Delta: 0.004697213790438943 	  Loss: 1.597408111215525 	 Accuracy: 0.242503259452412
Delta: 0.002478275496995056 	  Loss: 1.5972520741485607 	 Accuracy: 0.242503259452412
Delta: 0.002248176330224266 	  Loss: 1.5973032229323103 	 Accuracy: 0.242503259452412
Delta: 0.0019554304477994704 	  Loss: 1.5974258709085465 	 Accuracy: 0.242503259452412
Delta: 0.001479739207588207 	  Loss: 1.5973483163739466 	 Accuracy: 0.242503259452412
Delta: 0.0017466174311196324 	  Loss: 1.597562803046527 	 Accuracy: 0.242503259452412
Delta: 0.001093843342808199 	  Loss: 1.5975491315520274 	 Accuracy: 0.242503259452412
Delta: 0.0011559555880021471 	  Loss: 1.5974794168931563 	 Accuracy: 0.242503259452412
Delta: 8.357840893799078e-05 	  Loss: 1.5975509045805243 	 Accuracy: 0.242503259452412
Delta: 0.0005022228409057538 	  Loss: 1.5975747785986938 	 Accuracy: 0.24119947848761408
Delta: 0.0034328709662034716 	  Loss: 1.5975631774629755 	 Accuracy: 0.242503259452412
Delta: 0.003400120508079356 	  Loss: 1.5973197610153727 	 Accuracy: 0.242503259452412
Delta: 0.004227055371550585 	  Loss: 1.5974438498844692 	 Accuracy: 0.2438070404172099
Delta: 0.004005246531150725 	  Loss: 1.597540501852951 	 Accuracy: 0.242503259452412
Delta: 0.0033380349839342255 	  Loss: 1.597448490313131 	 Accuracy: 0.2438070404172099
Delta: 0.0009057577369759249 	  Loss: 1.597558131430699 	 Accuracy: 0.2438070404172099
Delta: 0.003681913106339304 	  Loss: 1.5974346341643968 	 Accuracy: 0.242503259452412
Delta: 0.0032017307109934155 	  Loss: 1.5973575087187148 	 Accuracy: 0.242503259452412
Delta: 0.002816474531463294 	  Loss: 1.597508066401757 	 Accuracy: 0.242503259452412
Delta: 0.0005620679964607564 	  Loss: 1.5975664592818142 	 Accuracy: 0.242503259452412
Delta: 0.0005603217813472233 	  Loss: 1.597579191143856 	 Accuracy: 0.242503259452412
Delta: 0.0021462973260016074 	  Loss: 1.597311333357395 	 Accuracy: 0.242503259452412
Delta: 0.002328686033491802 	  Loss: 1.5974767143613517 	 Accuracy: 0.242503259452412
Delta: 0.0024182162931780933 	  Loss: 1.5974537525745198 	 Accuracy: 0.24119947848761408
Delta: 0.0038750841461355425 	  Loss: 1.5975125706827893 	 Accuracy: 0.23989569752281617
Delta: 0.0037867570780858424 	  Loss: 1.5975037667399166 	 Accuracy: 0.24119947848761408
Delta: 0.0017275859764487454 	  Loss: 1.5975404345015582 	 Accuracy: 0.24119947848761408
Delta: 0.0023587624423718812 	  Loss: 1.5975998269857727 	 Accuracy: 0.24119947848761408
Delta: 0.004915176185388036 	  Loss: 1.597400619567179 	 Accuracy: 0.242503259452412
Delta: 0.004605707602885302 	  Loss: 1.5971623630296672 	 Accuracy: 0.24771838331160365
Delta: 0.006964256548047117 	  Loss: 1.5996912704853312 	 Accuracy: 0.2438070404172099
Delta: 0.005879395438484783 	  Loss: 1.5984175744208047 	 Accuracy: 0.2438070404172099
Delta: 0.0023542386591450517 	  Loss: 1.5988639693438307 	 Accuracy: 0.2438070404172099
Delta: 0.0019047556325644246 	  Loss: 1.5991292771540113 	 Accuracy: 0.24511082138200782
Delta: 0.002307290458932636 	  Loss: 1.5991723614967936 	 Accuracy: 0.2438070404172099
Delta: 0.0038544039727259165 	  Loss: 1.5984295505568942 	 Accuracy: 0.2438070404172099
Delta: 0.003128727419775991 	  Loss: 1.5985885737393755 	 Accuracy: 0.24511082138200782
Delta: 0.002534538580018944 	  Loss: 1.5984872923550004 	 Accuracy: 0.242503259452412
Delta: 0.0021101749099475997 	  Loss: 1.598606847059512 	 Accuracy: 0.242503259452412
Delta: 0.0006335489994836312 	  Loss: 1.598524384048466 	 Accuracy: 0.242503259452412
Delta: 0.0016387240565471771 	  Loss: 1.5983424083018298 	 Accuracy: 0.242503259452412
Delta: 0.0019270049654534348 	  Loss: 1.5986260393363412 	 Accuracy: 0.24119947848761408
Delta: 0.003973551468646896 	  Loss: 1.5985616362488524 	 Accuracy: 0.24119947848761408
Delta: 0.004748637327654702 	  Loss: 1.5992398746420244 	 Accuracy: 0.242503259452412
Delta: 0.004862618589654703 	  Loss: 1.5985658318559919 	 Accuracy: 0.242503259452412
Delta: 0.0026471036962621135 	  Loss: 1.5984927979681935 	 Accuracy: 0.24902216427640156
Delta: 0.002750259217214706 	  Loss: 1.5982821815106008 	 Accuracy: 0.242503259452412
Delta: 0.0030064636475787454 	  Loss: 1.5982882122968594 	 Accuracy: 0.24119947848761408
Delta: 0.0023788132378604492 	  Loss: 1.5982059590893103 	 Accuracy: 0.242503259452412
Delta: 0.004207219619333269 	  Loss: 1.5985405930767902 	 Accuracy: 0.242503259452412
Delta: 0.002397844126787472 	  Loss: 1.598318021832136 	 Accuracy: 0.242503259452412
Delta: 0.005428848735075911 	  Loss: 1.5989191040481177 	 Accuracy: 0.242503259452412
Delta: 0.003877894807513685 	  Loss: 1.5990532386938923 	 Accuracy: 0.242503259452412
Delta: 0.0033309432388706137 	  Loss: 1.5990125836751852 	 Accuracy: 0.242503259452412
Delta: 0.0005573432326901258 	  Loss: 1.5990133714438826 	 Accuracy: 0.242503259452412
Delta: 6.271407632136532e-05 	  Loss: 1.598988504771527 	 Accuracy: 0.242503259452412
Delta: 0.0012890031121528917 	  Loss: 1.599137987632052 	 Accuracy: 0.242503259452412
Delta: 0.0032636126006426788 	  Loss: 1.5993453988217756 	 Accuracy: 0.242503259452412
Delta: 0.003414717171906277 	  Loss: 1.599432176124959 	 Accuracy: 0.24119947848761408
Delta: 0.0040106614121899736 	  Loss: 1.599812952865803 	 Accuracy: 0.24119947848761408
Delta: 0.002601331154291767 	  Loss: 1.5996836366130762 	 Accuracy: 0.24119947848761408
Delta: 0.002734354743992176 	  Loss: 1.5996729031292827 	 Accuracy: 0.24119947848761408
Delta: 0.0032494400738906533 	  Loss: 1.6011396850787902 	 Accuracy: 0.24511082138200782
Delta: 0.0018293694281028615 	  Loss: 1.5998480045906853 	 Accuracy: 0.23989569752281617
Delta: 0.004959402757646193 	  Loss: 1.6002412859140016 	 Accuracy: 0.2438070404172099
Delta: 0.0011356141868361141 	  Loss: 1.6002886499946238 	 Accuracy: 0.24119947848761408
Delta: 0.0030583057597595507 	  Loss: 1.6001602815676366 	 Accuracy: 0.2438070404172099
Delta: 1.9865671939797583e-05 	  Loss: 1.6001542151781796 	 Accuracy: 0.24119947848761408
Delta: 0.004314713640621795 	  Loss: 1.6002905348002172 	 Accuracy: 0.24119947848761408
Delta: 0.004422287579052298 	  Loss: 1.5998769419599772 	 Accuracy: 0.24119947848761408
Delta: 0.0023787789054489847 	  Loss: 1.5999571096268 	 Accuracy: 0.23468057366362452
Delta: 0.002278320449726402 	  Loss: 1.5998513969684645 	 Accuracy: 0.24119947848761408
Delta: 0.0031626473385454055 	  Loss: 1.6000071523273416 	 Accuracy: 0.24119947848761408
Delta: 1.2749980641558392e-05 	  Loss: 1.6000030183465968 	 Accuracy: 0.24119947848761408
Delta: 0.0006165566509239479 	  Loss: 1.5998920056910872 	 Accuracy: 0.24119947848761408
Delta: 0.0019218131543783184 	  Loss: 1.59959623400191 	 Accuracy: 0.24119947848761408
Delta: 0.000634692575313686 	  Loss: 1.5996397204144888 	 Accuracy: 0.24119947848761408
Delta: 0.0043362578075990645 	  Loss: 1.59895004038439 	 Accuracy: 0.24119947848761408
Delta: 0.0010128140429695365 	  Loss: 1.5988990569359987 	 Accuracy: 0.24119947848761408
Delta: 0.0008700646163027556 	  Loss: 1.5995625445310901 	 Accuracy: 0.24119947848761408
Delta: 0.0005170135340924312 	  Loss: 1.5996045429409587 	 Accuracy: 0.24119947848761408
Delta: 0.005587356902708883 	  Loss: 1.603914270250772 	 Accuracy: 0.24119947848761408
Delta: 0.0023681284843382884 	  Loss: 1.6031231644636703 	 Accuracy: 0.24119947848761408
Delta: 0.004105234859883754 	  Loss: 1.6007316376601333 	 Accuracy: 0.24119947848761408
Delta: 0.002661240470097242 	  Loss: 1.6003504406903735 	 Accuracy: 0.24119947848761408
Delta: 0.0008204931940698868 	  Loss: 1.6002856942314978 	 Accuracy: 0.24119947848761408
Delta: 2.691827256796254e-05 	  Loss: 1.6003309292587984 	 Accuracy: 0.24902216427640156
Delta: 0.006789054795837728 	  Loss: 1.5997219443705357 	 Accuracy: 0.24119947848761408
Delta: 0.0061321016207479834 	  Loss: 1.598722269666263 	 Accuracy: 0.242503259452412
Delta: 0.005505934422321255 	  Loss: 1.598681114988252 	 Accuracy: 0.23859191655801826
Delta: 0.00499086463100103 	  Loss: 1.5996015425304786 	 Accuracy: 0.23989569752281617
Delta: 0.021077108644901397 	  Loss: 2.154450553103326 	 Accuracy: 0.18904823989569752
Delta: 0.019055336503114105 	  Loss: 2.0231555233989527 	 Accuracy: 0.3468057366362451
Delta: 0.017880499441512765 	  Loss: 1.8053254970112622 	 Accuracy: 0.4015645371577575
Delta: 0.016140497173486094 	  Loss: 1.676190060105819 	 Accuracy: 0.3833116036505867
Delta: 0.012125305265718563 	  Loss: 1.6284415919092292 	 Accuracy: 0.36766623207301175
Delta: 0.008652951448473115 	  Loss: 1.6149929416249689 	 Accuracy: 0.3650586701434159

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007440754898560382 	  Loss: 1.6114366884733733 	 Accuracy: 0.3650586701434159
Delta: 0.005453047531436428 	  Loss: 1.6103233691004162 	 Accuracy: 0.363754889178618
Delta: 0.004402772456456373 	  Loss: 1.6098081389579995 	 Accuracy: 0.363754889178618
Delta: 0.0022124713723184037 	  Loss: 1.6098432384173331 	 Accuracy: 0.35984354628422427
Delta: 0.0040598758355872705 	  Loss: 1.6096331343653132 	 Accuracy: 0.3624511082138201
Delta: 0.003311471092772493 	  Loss: 1.6098517287574676 	 Accuracy: 0.36114732724902215
Delta: 0.0029868045911485013 	  Loss: 1.6098732461949827 	 Accuracy: 0.35984354628422427
Delta: 1.708234233886855e-05 	  Loss: 1.6098525050036754 	 Accuracy: 0.35984354628422427
Delta: 7.260402929304219e-06 	  Loss: 1.6098427153894255 	 Accuracy: 0.36114732724902215
Delta: 2.226489079669032e-05 	  Loss: 1.6098729849776463 	 Accuracy: 0.35984354628422427
Delta: 2.24321560430088e-05 	  Loss: 1.609847906993004 	 Accuracy: 0.35984354628422427
Delta: 7.789682135610214e-06 	  Loss: 1.6098495705203733 	 Accuracy: 0.3624511082138201
Delta: 1.6593630529943184e-05 	  Loss: 1.609824337776433 	 Accuracy: 0.36114732724902215
Delta: 1.7213835039464014e-05 	  Loss: 1.6098368420881917 	 Accuracy: 0.36114732724902215
Delta: 1.177475547666384e-05 	  Loss: 1.609851061403718 	 Accuracy: 0.36114732724902215
Delta: 0.0028899734216923014 	  Loss: 1.6099255843816662 	 Accuracy: 0.36114732724902215
Delta: 0.0022098137784168055 	  Loss: 1.6100166028611955 	 Accuracy: 0.35984354628422427
Delta: 0.0030114170676648865 	  Loss: 1.6103997264473693 	 Accuracy: 0.36114732724902215
Delta: 0.0010151360827850245 	  Loss: 1.6104625489052724 	 Accuracy: 0.3624511082138201
Delta: 0.0016193879659149007 	  Loss: 1.6104102151110422 	 Accuracy: 0.363754889178618
Delta: 0.004164405128299406 	  Loss: 1.61055654263334 	 Accuracy: 0.36114732724902215
Delta: 0.0017440243289203986 	  Loss: 1.6102840149497095 	 Accuracy: 0.36114732724902215
Delta: 6.234061505051839e-05 	  Loss: 1.6101527652202667 	 Accuracy: 0.35984354628422427
Delta: 2.989425075641065e-06 	  Loss: 1.6101704672075785 	 Accuracy: 0.35984354628422427
Delta: 8.458690242459818e-05 	  Loss: 1.6098921224734646 	 Accuracy: 0.3624511082138201
Delta: 0.0011019148450730817 	  Loss: 1.6102228169371458 	 Accuracy: 0.3624511082138201
Delta: 2.270833220405469e-05 	  Loss: 1.6101184019614871 	 Accuracy: 0.36114732724902215
Delta: 0.0026799666042666695 	  Loss: 1.6103935384094714 	 Accuracy: 0.36114732724902215
Delta: 0.0011763541877873114 	  Loss: 1.610249217103569 	 Accuracy: 0.3624511082138201
Delta: 0.00010712763138146525 	  Loss: 1.6100271234813384 	 Accuracy: 0.36114732724902215
Delta: 0.0013116289935945792 	  Loss: 1.6098076367667815 	 Accuracy: 0.36114732724902215
Delta: 0.0016660373303039036 	  Loss: 1.6101974717936027 	 Accuracy: 0.36114732724902215
Delta: 0.0024988324646200094 	  Loss: 1.6100472638954 	 Accuracy: 0.3624511082138201
Delta: 0.0024145492625398048 	  Loss: 1.6104133081697785 	 Accuracy: 0.3624511082138201
Delta: 0.0017676134757943223 	  Loss: 1.6103808148283747 	 Accuracy: 0.3624511082138201
Delta: 0.003116608818870618 	  Loss: 1.610636779183317 	 Accuracy: 0.3624511082138201
Delta: 0.001982877880039066 	  Loss: 1.61066943205397 	 Accuracy: 0.36114732724902215
Delta: 0.0022050304864548935 	  Loss: 1.6104597648074437 	 Accuracy: 0.36114732724902215
Delta: 0.0026140280939732866 	  Loss: 1.6104691534777769 	 Accuracy: 0.36114732724902215
Delta: 0.0022942743960449054 	  Loss: 1.6096287900657487 	 Accuracy: 0.35984354628422427
Delta: 0.00253609351147841 	  Loss: 1.6092415534968827 	 Accuracy: 0.3624511082138201
Delta: 6.478614609915666e-05 	  Loss: 1.609617871334793 	 Accuracy: 0.35853976531942633
Delta: 0.0024908831763581015 	  Loss: 1.6089249268990682 	 Accuracy: 0.36114732724902215
Delta: 0.004797461878056002 	  Loss: 1.6111786053630706 	 Accuracy: 0.363754889178618
Delta: 0.004015557036354609 	  Loss: 1.6114750111182947 	 Accuracy: 0.3650586701434159
Delta: 0.0008141852867160286 	  Loss: 1.6113751902425872 	 Accuracy: 0.363754889178618
Delta: 1.5820388977316317e-05 	  Loss: 1.6113338730219913 	 Accuracy: 0.36766623207301175
Delta: 0.0018072926703326065 	  Loss: 1.6107005204801856 	 Accuracy: 0.36114732724902215
Delta: 0.0015940298862219986 	  Loss: 1.6111814363296277 	 Accuracy: 0.3650586701434159
Delta: 0.0012947338552317341 	  Loss: 1.6113344115917325 	 Accuracy: 0.3624511082138201
Delta: 0.0027609203460094494 	  Loss: 1.6111446383325614 	 Accuracy: 0.3624511082138201
Delta: 0.0021761521891957183 	  Loss: 1.611146292897375 	 Accuracy: 0.363754889178618
Delta: 0.0005145994732986934 	  Loss: 1.6111532787737524 	 Accuracy: 0.363754889178618
Delta: 0.0010509047606724164 	  Loss: 1.6111270523615184 	 Accuracy: 0.363754889178618
Delta: 0.0037832511196955656 	  Loss: 1.610681642067494 	 Accuracy: 0.36114732724902215
Delta: 0.003572434128243706 	  Loss: 1.6104302223548792 	 Accuracy: 0.36114732724902215
Delta: 0.0018494061577992917 	  Loss: 1.610459665061816 	 Accuracy: 0.3624511082138201
Delta: 0.0033503709159959415 	  Loss: 1.6108037903443906 	 Accuracy: 0.35984354628422427
Delta: 0.0038406264064162403 	  Loss: 1.611252572916701 	 Accuracy: 0.35984354628422427
Delta: 0.0022448485224141647 	  Loss: 1.6108692718778987 	 Accuracy: 0.36114732724902215
Delta: 0.00382285452854174 	  Loss: 1.6115360632544875 	 Accuracy: 0.35853976531942633
Delta: 0.003683552265733042 	  Loss: 1.6118244486162756 	 Accuracy: 0.35853976531942633
Delta: 0.0032950461399074878 	  Loss: 1.6120106172799953 	 Accuracy: 0.35853976531942633
Delta: 0.0030586584641887366 	  Loss: 1.6120604014691338 	 Accuracy: 0.35853976531942633
Delta: 4.41530186910493e-05 	  Loss: 1.6120175429762582 	 Accuracy: 0.35723598435462844
Delta: 0.0012123723568394427 	  Loss: 1.6121000997101655 	 Accuracy: 0.35723598435462844
Delta: 0.002913742463208859 	  Loss: 1.6121220959921714 	 Accuracy: 0.35853976531942633
Delta: 0.0005772723750459591 	  Loss: 1.6120817482232803 	 Accuracy: 0.35853976531942633
Delta: 0.0015604128812058845 	  Loss: 1.6121047547446232 	 Accuracy: 0.35853976531942633
Delta: 0.0022533876192300925 	  Loss: 1.6120052284419217 	 Accuracy: 0.35723598435462844
Delta: 0.0012098136615501024 	  Loss: 1.6120242524597543 	 Accuracy: 0.3559322033898305
Delta: 0.003146307374198767 	  Loss: 1.6103559280582918 	 Accuracy: 0.3559322033898305
Delta: 0.0027615299377437524 	  Loss: 1.6119117422214417 	 Accuracy: 0.3559322033898305
Delta: 6.015002843632051e-05 	  Loss: 1.611919122081435 	 Accuracy: 0.35723598435462844
Delta: 5.4616205201649496e-05 	  Loss: 1.6117951361346192 	 Accuracy: 0.35723598435462844
Delta: 0.0014971266275053715 	  Loss: 1.6117228970107065 	 Accuracy: 0.35984354628422427
Delta: 0.0005292536508501886 	  Loss: 1.6117565758683172 	 Accuracy: 0.35723598435462844
Delta: 0.002217099615268058 	  Loss: 1.6123651699973873 	 Accuracy: 0.36114732724902215
Delta: 0.005494314420853004 	  Loss: 1.6129441758672756 	 Accuracy: 0.35984354628422427
Delta: 0.004465312985782078 	  Loss: 1.612072770590663 	 Accuracy: 0.35984354628422427
Delta: 0.0007252991644746869 	  Loss: 1.6120120925846946 	 Accuracy: 0.36897001303780963
Delta: 0.0036774041144019974 	  Loss: 1.612228674239502 	 Accuracy: 0.36114732724902215
Delta: 0.004269193892717697 	  Loss: 1.613734828423916 	 Accuracy: 0.35853976531942633
Delta: 0.0046690987279558276 	  Loss: 1.6130461078781426 	 Accuracy: 0.35984354628422427
Delta: 0.0007620696529204152 	  Loss: 1.6129142314864975 	 Accuracy: 0.35984354628422427
Delta: 0.0020103701177301165 	  Loss: 1.6129096604471047 	 Accuracy: 0.35984354628422427
Delta: 0.0028271251676545 	  Loss: 1.6127588192247186 	 Accuracy: 0.3624511082138201
Delta: 0.0042929686758578925 	  Loss: 1.612263995574808 	 Accuracy: 0.36114732724902215
Delta: 0.0009372068127020472 	  Loss: 1.61228606966047 	 Accuracy: 0.3624511082138201
Delta: 0.003994537611439733 	  Loss: 1.6119980950786914 	 Accuracy: 0.363754889178618
Delta: 0.003993401079985102 	  Loss: 1.6135586597322469 	 Accuracy: 0.363754889178618
Delta: 0.003178008252882461 	  Loss: 1.6138833211180508 	 Accuracy: 0.3624511082138201
Delta: 0.0033290370311623227 	  Loss: 1.611502543606101 	 Accuracy: 0.3663624511082138
Delta: 0.0029731146344529795 	  Loss: 1.6133859028344224 	 Accuracy: 0.3650586701434159
Delta: 0.020949639374162107 	  Loss: 2.155284643604281 	 Accuracy: 0.19556714471968709
Delta: 0.019384247761001255 	  Loss: 2.0197020961472467 	 Accuracy: 0.2907431551499348
Delta: 0.01791150230024808 	  Loss: 1.799861245789364 	 Accuracy: 0.3324641460234681
Delta: 0.015447829893908109 	  Loss: 1.682062270983078 	 Accuracy: 0.38461538461538464
Delta: 0.012535492936458096 	  Loss: 1.635778981203107 	 Accuracy: 0.409387222946545

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010762745693368263 	  Loss: 1.6140224376376309 	 Accuracy: 0.40808344198174706
Delta: 0.008039168917460019 	  Loss: 1.6075866559104268 	 Accuracy: 0.41590612777053454
Delta: 0.005753411579589867 	  Loss: 1.6063317112778217 	 Accuracy: 0.4132985658409387
Delta: 0.005800254133354611 	  Loss: 1.6054185897023783 	 Accuracy: 0.409387222946545
Delta: 0.0031451025627898953 	  Loss: 1.605372206090034 	 Accuracy: 0.4106910039113429
Delta: 0.003183658603944944 	  Loss: 1.6052056113289175 	 Accuracy: 0.41199478487614083
Delta: 0.0016020648047040086 	  Loss: 1.6051881363805012 	 Accuracy: 0.41199478487614083
Delta: 0.0017157589292615147 	  Loss: 1.6051482201584202 	 Accuracy: 0.4106910039113429
Delta: 0.002643996568838598 	  Loss: 1.605213055371113 	 Accuracy: 0.42503259452411996
Delta: 0.003805103766272758 	  Loss: 1.6051563786383523 	 Accuracy: 0.41199478487614083
Delta: 0.0005368828576324733 	  Loss: 1.6051151701797162 	 Accuracy: 0.4106910039113429
Delta: 0.004282100021464617 	  Loss: 1.6046917219255004 	 Accuracy: 0.4106910039113429
Delta: 0.002288403411441951 	  Loss: 1.60515883730426 	 Accuracy: 0.4132985658409387
Delta: 0.0005835202933504172 	  Loss: 1.6050825008755742 	 Accuracy: 0.4132985658409387
Delta: 0.003432108056123956 	  Loss: 1.604675372391871 	 Accuracy: 0.41460234680573665
Delta: 0.0005580680630509419 	  Loss: 1.6046180928475278 	 Accuracy: 0.4132985658409387
Delta: 0.0009438408691606702 	  Loss: 1.604654240698315 	 Accuracy: 0.4132985658409387
Delta: 1.5993862474343128e-05 	  Loss: 1.6046247307063206 	 Accuracy: 0.41460234680573665
Delta: 0.0030926404971457285 	  Loss: 1.6044571187283205 	 Accuracy: 0.41460234680573665
Delta: 0.002924919110358362 	  Loss: 1.6042562268861364 	 Accuracy: 0.4132985658409387
Delta: 0.0011665922356501076 	  Loss: 1.604334347597513 	 Accuracy: 0.4132985658409387
Delta: 0.0008042667381963453 	  Loss: 1.6044161980040852 	 Accuracy: 0.4132985658409387
Delta: 5.504997070423499e-05 	  Loss: 1.6041249069421344 	 Accuracy: 0.4132985658409387
Delta: 0.002472951011954132 	  Loss: 1.6045412365390208 	 Accuracy: 0.4106910039113429
Delta: 0.0041634329322410195 	  Loss: 1.6053516776072654 	 Accuracy: 0.4106910039113429
Delta: 0.0031553799150488547 	  Loss: 1.6055090593115566 	 Accuracy: 0.41590612777053454
Delta: 0.00010307759041191894 	  Loss: 1.6051623923539808 	 Accuracy: 0.4132985658409387
Delta: 0.003602790122175565 	  Loss: 1.6054369877781427 	 Accuracy: 0.41199478487614083
Delta: 0.0038107416572550944 	  Loss: 1.6056857314607067 	 Accuracy: 0.4132985658409387
Delta: 0.003232740920619812 	  Loss: 1.6053541377466658 	 Accuracy: 0.41199478487614083
Delta: 0.002625516605828395 	  Loss: 1.6056377120835108 	 Accuracy: 0.40808344198174706
Delta: 0.0010719237503573746 	  Loss: 1.6058706508048421 	 Accuracy: 0.4106910039113429
Delta: 0.003161605787964388 	  Loss: 1.6057901702015227 	 Accuracy: 0.409387222946545
Delta: 0.0006413266154299327 	  Loss: 1.6056698305838342 	 Accuracy: 0.4106910039113429
Delta: 0.0009781982938237813 	  Loss: 1.6056105002471708 	 Accuracy: 0.4106910039113429
Delta: 0.0025808119538074763 	  Loss: 1.6055299258505895 	 Accuracy: 0.4106910039113429
Delta: 0.002683504599899653 	  Loss: 1.6055032442571993 	 Accuracy: 0.4106910039113429
Delta: 0.002555364572664989 	  Loss: 1.6053882147529521 	 Accuracy: 0.41199478487614083
Delta: 0.0030031124359863794 	  Loss: 1.6050160142711822 	 Accuracy: 0.41199478487614083
Delta: 0.0014248029424673372 	  Loss: 1.6050447178204417 	 Accuracy: 0.40547588005215124
Delta: 0.00214289977743898 	  Loss: 1.6049718496423806 	 Accuracy: 0.409387222946545
Delta: 0.001839900050952125 	  Loss: 1.6050227845200045 	 Accuracy: 0.4132985658409387
Delta: 0.0011374118189201637 	  Loss: 1.6047381187870609 	 Accuracy: 0.4067796610169492
Delta: 0.0026682415247464273 	  Loss: 1.6047454769291478 	 Accuracy: 0.4106910039113429
Delta: 0.001129071000108446 	  Loss: 1.6052788777582951 	 Accuracy: 0.4106910039113429
Delta: 8.49741140224238e-05 	  Loss: 1.6052593053390491 	 Accuracy: 0.40808344198174706
Delta: 0.0011253670348491474 	  Loss: 1.6052572134029865 	 Accuracy: 0.409387222946545
Delta: 5.169397630022955e-05 	  Loss: 1.6054021277725423 	 Accuracy: 0.4106910039113429
Delta: 4.288148529311667e-05 	  Loss: 1.6052653932474987 	 Accuracy: 0.40808344198174706
Delta: 0.0028817129162865035 	  Loss: 1.6056618941350913 	 Accuracy: 0.409387222946545
Delta: 0.00332737722605266 	  Loss: 1.6057615827713674 	 Accuracy: 0.4106910039113429
Delta: 0.0024113763418763716 	  Loss: 1.6060223951872965 	 Accuracy: 0.4106910039113429
Delta: 0.0037343556823713204 	  Loss: 1.6057363667152234 	 Accuracy: 0.4106910039113429
Delta: 0.004781125952751216 	  Loss: 1.606117480600013 	 Accuracy: 0.409387222946545
Delta: 0.0018027666668978953 	  Loss: 1.6063030181050881 	 Accuracy: 0.4106910039113429
Delta: 0.0014709067944120378 	  Loss: 1.606303649474232 	 Accuracy: 0.40808344198174706
Delta: 0.0035302991101241565 	  Loss: 1.6072586751790077 	 Accuracy: 0.4067796610169492
Delta: 0.0028463661928343643 	  Loss: 1.608132399253022 	 Accuracy: 0.4067796610169492
Delta: 0.0019249947183264948 	  Loss: 1.6076427368945443 	 Accuracy: 0.40808344198174706
Delta: 1.5055975606792004e-05 	  Loss: 1.6076143158118024 	 Accuracy: 0.41590612777053454
Delta: 0.0018913011454959516 	  Loss: 1.607404275227478 	 Accuracy: 0.40808344198174706
Delta: 0.002831222958402981 	  Loss: 1.607244255744734 	 Accuracy: 0.4106910039113429
Delta: 0.0027387708803065475 	  Loss: 1.6068168141563666 	 Accuracy: 0.40547588005215124
Delta: 0.005471638426379391 	  Loss: 1.607035557109445 	 Accuracy: 0.409387222946545
Delta: 0.001717225423797341 	  Loss: 1.6069228270477685 	 Accuracy: 0.4106910039113429
Delta: 0.0006022626855945012 	  Loss: 1.606677148363484 	 Accuracy: 0.409387222946545
Delta: 0.000982015704473299 	  Loss: 1.606621360100826 	 Accuracy: 0.4106910039113429
Delta: 0.0013856844892294283 	  Loss: 1.6065592772526176 	 Accuracy: 0.4106910039113429
Delta: 0.004687973719502852 	  Loss: 1.605083729970652 	 Accuracy: 0.4106910039113429
Delta: 0.002571544311614656 	  Loss: 1.605382929932731 	 Accuracy: 0.41460234680573665
Delta: 0.0021393545427505164 	  Loss: 1.6050788440351003 	 Accuracy: 0.41460234680573665
Delta: 0.003070867768727895 	  Loss: 1.6052675911955965 	 Accuracy: 0.4106910039113429
Delta: 0.0026197242027166823 	  Loss: 1.6058999581181859 	 Accuracy: 0.4106910039113429
Delta: 0.0032566880700049755 	  Loss: 1.605745980509637 	 Accuracy: 0.41199478487614083
Delta: 0.001799611662767778 	  Loss: 1.6052682663858917 	 Accuracy: 0.41199478487614083
Delta: 0.0021843241396510083 	  Loss: 1.605074072708252 	 Accuracy: 0.41199478487614083
Delta: 0.00013078193366201812 	  Loss: 1.605365206092999 	 Accuracy: 0.41199478487614083
Delta: 0.0007077482855748028 	  Loss: 1.6057215093171084 	 Accuracy: 0.41199478487614083
Delta: 0.001163501337756412 	  Loss: 1.6055522160084068 	 Accuracy: 0.41199478487614083
Delta: 0.00328106453140755 	  Loss: 1.6056261586849045 	 Accuracy: 0.41199478487614083
Delta: 0.0022866476619285356 	  Loss: 1.6056860788829752 	 Accuracy: 0.409387222946545
Delta: 0.0019844738908541652 	  Loss: 1.6059675942133342 	 Accuracy: 0.41199478487614083
Delta: 0.0007757111193260406 	  Loss: 1.6057050877568222 	 Accuracy: 0.41460234680573665
Delta: 0.0022109456089375265 	  Loss: 1.6060292268411553 	 Accuracy: 0.41199478487614083
Delta: 4.057491280040677e-05 	  Loss: 1.6058395043794 	 Accuracy: 0.41199478487614083
Delta: 4.99102157759134e-06 	  Loss: 1.605837613786917 	 Accuracy: 0.41199478487614083
Delta: 4.991024909015071e-06 	  Loss: 1.60583950007618 	 Accuracy: 0.41199478487614083
Delta: 7.905709586896218e-05 	  Loss: 1.605693919195921 	 Accuracy: 0.4132985658409387
Delta: 4.550273494825746e-05 	  Loss: 1.6057675496002137 	 Accuracy: 0.41199478487614083
Delta: 0.0005594607442610023 	  Loss: 1.6059420061223442 	 Accuracy: 0.41199478487614083
Delta: 0.0007446332138391486 	  Loss: 1.6057336467305205 	 Accuracy: 0.41460234680573665
Delta: 0.0017883924041473165 	  Loss: 1.6056622781080374 	 Accuracy: 0.41199478487614083
Delta: 0.0023167104731863235 	  Loss: 1.6065414842237407 	 Accuracy: 0.4106910039113429
Delta: 4.594496403700191e-06 	  Loss: 1.606543260256116 	 Accuracy: 0.41199478487614083
Delta: 0.003336218470268929 	  Loss: 1.6066743980139935 	 Accuracy: 0.41199478487614083
Delta: 0.02105423787825043 	  Loss: 2.1541126824795316 	 Accuracy: 0.20599739243807041
Delta: 0.019455198695046555 	  Loss: 2.015740114876336 	 Accuracy: 0.4132985658409387
Delta: 0.01801966943288819 	  Loss: 1.8022267781220553 	 Accuracy: 0.46284224250325945
Delta: 0.016129569945963398 	  Loss: 1.6779100949025323 	 Accuracy: 0.4067796610169492
Delta: 0.012960738920661977 	  Loss: 1.6282115165035511 	 Accuracy: 0.3767926988265971

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009419939583106614 	  Loss: 1.6130150985591343 	 Accuracy: 0.37027379400260757
Delta: 0.007069166535091986 	  Loss: 1.6105858873329475 	 Accuracy: 0.3663624511082138
Delta: 0.005398321391479721 	  Loss: 1.610019403573153 	 Accuracy: 0.36897001303780963
Delta: 0.005057495790349688 	  Loss: 1.609947883412887 	 Accuracy: 0.3650586701434159
Delta: 0.002664003705930675 	  Loss: 1.6098128754872603 	 Accuracy: 0.3663624511082138
Delta: 0.001040260759201402 	  Loss: 1.6098333100614597 	 Accuracy: 0.363754889178618
Delta: 0.002678124583174966 	  Loss: 1.6097688688267082 	 Accuracy: 0.3663624511082138
Delta: 0.002216223025911499 	  Loss: 1.6097990496544015 	 Accuracy: 0.3650586701434159
Delta: 0.0011470734448640978 	  Loss: 1.609816172196004 	 Accuracy: 0.3650586701434159
Delta: 5.438917811250029e-06 	  Loss: 1.6097988800679364 	 Accuracy: 0.363754889178618
Delta: 0.0005448649073816799 	  Loss: 1.609988368058602 	 Accuracy: 0.363754889178618
Delta: 0.0033494091221542045 	  Loss: 1.609913356965086 	 Accuracy: 0.3650586701434159
Delta: 0.00250890273352639 	  Loss: 1.609498651725758 	 Accuracy: 0.363754889178618
Delta: 3.7524008861550655e-05 	  Loss: 1.6096553229761428 	 Accuracy: 0.3650586701434159
Delta: 0.0008375472921256646 	  Loss: 1.6098220244682837 	 Accuracy: 0.363754889178618
Delta: 4.601880166765287e-05 	  Loss: 1.6096916152458185 	 Accuracy: 0.3650586701434159
Delta: 0.0006908711865921143 	  Loss: 1.609594343348232 	 Accuracy: 0.363754889178618
Delta: 0.0010882877925841518 	  Loss: 1.6097501887653212 	 Accuracy: 0.363754889178618
Delta: 0.0037557550018180235 	  Loss: 1.6092218222752122 	 Accuracy: 0.3624511082138201
Delta: 0.0017917027997894435 	  Loss: 1.609615866401603 	 Accuracy: 0.363754889178618
Delta: 0.00276899306839984 	  Loss: 1.6095982626367684 	 Accuracy: 0.363754889178618
Delta: 0.0029160112253896467 	  Loss: 1.609619474017777 	 Accuracy: 0.363754889178618
Delta: 0.0005874483217542074 	  Loss: 1.6093241750086444 	 Accuracy: 0.3650586701434159
Delta: 0.002866884490342399 	  Loss: 1.6093653403927943 	 Accuracy: 0.363754889178618
Delta: 0.002435890480016176 	  Loss: 1.609405530720303 	 Accuracy: 0.3624511082138201
Delta: 0.0018670036633074542 	  Loss: 1.609108305870889 	 Accuracy: 0.363754889178618
Delta: 0.0024182432965964232 	  Loss: 1.609412360281226 	 Accuracy: 0.363754889178618
Delta: 0.0026183107924988695 	  Loss: 1.6095648779634066 	 Accuracy: 0.363754889178618
Delta: 0.0013013267351723835 	  Loss: 1.6099451161736829 	 Accuracy: 0.363754889178618
Delta: 0.0018526955565891187 	  Loss: 1.609914488181118 	 Accuracy: 0.363754889178618
Delta: 0.003406054725134576 	  Loss: 1.6097743264614484 	 Accuracy: 0.3650586701434159
Delta: 0.0006631777792265109 	  Loss: 1.6098489286571964 	 Accuracy: 0.363754889178618
Delta: 2.7987221926313682e-06 	  Loss: 1.6098417518091912 	 Accuracy: 0.363754889178618
Delta: 0.001795986469020593 	  Loss: 1.6094832879827043 	 Accuracy: 0.3624511082138201
Delta: 0.0005401343060169206 	  Loss: 1.6094290386554695 	 Accuracy: 0.363754889178618
Delta: 3.462232731257698e-05 	  Loss: 1.6095205897974303 	 Accuracy: 0.363754889178618
Delta: 2.4062813276239192e-06 	  Loss: 1.6095208592515047 	 Accuracy: 0.363754889178618
Delta: 3.479633848837828e-05 	  Loss: 1.6097577285303188 	 Accuracy: 0.363754889178618
Delta: 0.0029557024317519113 	  Loss: 1.6099676217624816 	 Accuracy: 0.363754889178618
Delta: 0.0035877838105247708 	  Loss: 1.6104160209135103 	 Accuracy: 0.3624511082138201
Delta: 0.002058839571341576 	  Loss: 1.6100915589602875 	 Accuracy: 0.36114732724902215
Delta: 0.0026573128498195786 	  Loss: 1.6098534009994308 	 Accuracy: 0.3624511082138201
Delta: 0.0029016620309221257 	  Loss: 1.6100039347488866 	 Accuracy: 0.3624511082138201
Delta: 0.0020882641943780885 	  Loss: 1.609712349349615 	 Accuracy: 0.35853976531942633
Delta: 0.003262207525722192 	  Loss: 1.6101998904171797 	 Accuracy: 0.35984354628422427
Delta: 0.00434102591669168 	  Loss: 1.6106447569256037 	 Accuracy: 0.3559322033898305
Delta: 0.003914419357088749 	  Loss: 1.611094184310456 	 Accuracy: 0.36114732724902215
Delta: 0.0033487458250262706 	  Loss: 1.6108646844524823 	 Accuracy: 0.363754889178618
Delta: 0.003171618382445209 	  Loss: 1.610891933105141 	 Accuracy: 0.3624511082138201
Delta: 0.00179667110114534 	  Loss: 1.6107908132626587 	 Accuracy: 0.3624511082138201
Delta: 0.0024819362208127185 	  Loss: 1.6109198718049513 	 Accuracy: 0.36114732724902215
Delta: 0.0005475646036334984 	  Loss: 1.6111426119404413 	 Accuracy: 0.3624511082138201
Delta: 0.0017093444001306042 	  Loss: 1.6109980424467532 	 Accuracy: 0.36114732724902215
Delta: 0.005298481885599709 	  Loss: 1.6106954441133485 	 Accuracy: 0.35984354628422427
Delta: 0.0015489703505977925 	  Loss: 1.6111739631347681 	 Accuracy: 0.36114732724902215
Delta: 0.0018609080980560764 	  Loss: 1.6112008092139103 	 Accuracy: 0.35984354628422427
Delta: 0.004648649436724574 	  Loss: 1.6110480451884408 	 Accuracy: 0.363754889178618
Delta: 0.0022838379185221836 	  Loss: 1.6114087494663911 	 Accuracy: 0.36114732724902215
Delta: 0.0014918033907728898 	  Loss: 1.6114039254587418 	 Accuracy: 0.36114732724902215
Delta: 8.37559967109442e-05 	  Loss: 1.6111924001754272 	 Accuracy: 0.36114732724902215
Delta: 0.0013322168207122807 	  Loss: 1.6110531538725774 	 Accuracy: 0.35984354628422427
Delta: 0.0014862962440018994 	  Loss: 1.6115797549884874 	 Accuracy: 0.35984354628422427
Delta: 0.0009246860015925925 	  Loss: 1.6111304073973929 	 Accuracy: 0.36114732724902215
Delta: 3.882328850782443e-05 	  Loss: 1.611332020235871 	 Accuracy: 0.36114732724902215
Delta: 0.0023354601833635216 	  Loss: 1.6114903722874936 	 Accuracy: 0.363754889178618
Delta: 0.0031574034965178794 	  Loss: 1.6124531857838247 	 Accuracy: 0.35984354628422427
Delta: 0.0011491515248044024 	  Loss: 1.6113762992275993 	 Accuracy: 0.36114732724902215
Delta: 2.1763269308250227e-06 	  Loss: 1.6113747592963525 	 Accuracy: 0.36114732724902215
Delta: 0.0015313102300682448 	  Loss: 1.6112636203158304 	 Accuracy: 0.36114732724902215
Delta: 0.0005229024805412519 	  Loss: 1.611302781183912 	 Accuracy: 0.36114732724902215
Delta: 0.0005845310123104159 	  Loss: 1.61118757518956 	 Accuracy: 0.36114732724902215
Delta: 0.0005129342878407197 	  Loss: 1.6112105507843069 	 Accuracy: 0.36114732724902215
Delta: 7.61628803244778e-05 	  Loss: 1.6113718810018116 	 Accuracy: 0.36114732724902215
Delta: 0.0025090347880108183 	  Loss: 1.6114015017916725 	 Accuracy: 0.36114732724902215
Delta: 0.002269874666800276 	  Loss: 1.6111644291905027 	 Accuracy: 0.36114732724902215
Delta: 0.0006516398027361892 	  Loss: 1.611377537216617 	 Accuracy: 0.36114732724902215
Delta: 0.0028013602938151234 	  Loss: 1.611569174927007 	 Accuracy: 0.37809647979139505
Delta: 0.0026540407024135317 	  Loss: 1.6115531111730985 	 Accuracy: 0.36114732724902215
Delta: 0.00358042791381361 	  Loss: 1.6112076709785774 	 Accuracy: 0.36114732724902215
Delta: 0.0014662346628623616 	  Loss: 1.611307063399601 	 Accuracy: 0.35984354628422427
Delta: 0.0018508870666646257 	  Loss: 1.6112927708643199 	 Accuracy: 0.36114732724902215
Delta: 0.001618973840572525 	  Loss: 1.6113523498151867 	 Accuracy: 0.35853976531942633
Delta: 0.0007260353205842145 	  Loss: 1.6112425023449228 	 Accuracy: 0.36114732724902215
Delta: 5.362514725602742e-05 	  Loss: 1.6112166021165109 	 Accuracy: 0.35984354628422427
Delta: 0.0035665919421523393 	  Loss: 1.611409000056011 	 Accuracy: 0.35853976531942633
Delta: 0.00502719599998323 	  Loss: 1.6102708438959454 	 Accuracy: 0.35984354628422427
Delta: 0.0038931597404807455 	  Loss: 1.609695239532054 	 Accuracy: 0.35984354628422427
Delta: 0.00010144320798019479 	  Loss: 1.609810686202617 	 Accuracy: 0.35853976531942633
Delta: 2.2415766686903385e-05 	  Loss: 1.6098668237532645 	 Accuracy: 0.36114732724902215
Delta: 0.0035737182237450126 	  Loss: 1.6088729327557605 	 Accuracy: 0.35853976531942633
Delta: 0.003809996872802891 	  Loss: 1.610583918957821 	 Accuracy: 0.35984354628422427
Delta: 0.0024717093542275144 	  Loss: 1.6099492069083965 	 Accuracy: 0.35984354628422427
Delta: 0.002610426724870302 	  Loss: 1.6107146003643997 	 Accuracy: 0.36114732724902215
Delta: 0.004872372570577695 	  Loss: 1.6113999012768923 	 Accuracy: 0.37027379400260757
Delta: 0.005621804642287069 	  Loss: 1.610945566252298 	 Accuracy: 0.35984354628422427
Delta: 0.02095512526120175 	  Loss: 2.156850535172092 	 Accuracy: 0.196870925684485
Delta: 0.019021556508359055 	  Loss: 2.027199116422859 	 Accuracy: 0.3428943937418514
Delta: 0.01812529964053354 	  Loss: 1.8226168204475997 	 Accuracy: 0.4511082138200782
Delta: 0.01671580328052227 	  Loss: 1.6994940956853117 	 Accuracy: 0.42242503259452413
Delta: 0.013941996834469669 	  Loss: 1.6359882755804973 	 Accuracy: 0.39765319426336376

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010089559614547734 	  Loss: 1.613027879873659 	 Accuracy: 0.4002607561929596
Delta: 0.007470080716160646 	  Loss: 1.6096002453252 	 Accuracy: 0.39504563233376794
Delta: 0.005298425153535661 	  Loss: 1.6081994863728792 	 Accuracy: 0.39765319426336376
Delta: 0.003972478231942595 	  Loss: 1.6075181521579252 	 Accuracy: 0.39504563233376794
Delta: 0.003945609262937482 	  Loss: 1.606907022449704 	 Accuracy: 0.39374185136897
Delta: 0.0011885304669822683 	  Loss: 1.6071112242231145 	 Accuracy: 0.3963494132985658
Delta: 0.0018565120856759482 	  Loss: 1.6071495227125425 	 Accuracy: 0.39374185136897
Delta: 0.0020405285682883953 	  Loss: 1.607283258271285 	 Accuracy: 0.39504563233376794
Delta: 0.0038335868178147633 	  Loss: 1.6076762580175685 	 Accuracy: 0.39504563233376794
Delta: 0.001130318315617915 	  Loss: 1.607728249690203 	 Accuracy: 0.3963494132985658
Delta: 0.0014179474766210657 	  Loss: 1.6077211675961571 	 Accuracy: 0.3963494132985658
Delta: 0.0024695026610289206 	  Loss: 1.6079252789144547 	 Accuracy: 0.3963494132985658
Delta: 7.756687907086429e-05 	  Loss: 1.6078112909578144 	 Accuracy: 0.39504563233376794
Delta: 0.001611005688246958 	  Loss: 1.6078589509050114 	 Accuracy: 0.3963494132985658
Delta: 0.002964097729784617 	  Loss: 1.6078173558670847 	 Accuracy: 0.39504563233376794
Delta: 0.0014668207688699937 	  Loss: 1.6078349840315829 	 Accuracy: 0.39504563233376794
Delta: 0.0019344615498581015 	  Loss: 1.607825162012849 	 Accuracy: 0.3963494132985658
Delta: 0.003446554477265149 	  Loss: 1.6073958186728965 	 Accuracy: 0.39504563233376794
Delta: 0.0021954365495437844 	  Loss: 1.607080050239254 	 Accuracy: 0.39504563233376794
Delta: 0.0018345094712920577 	  Loss: 1.6070387376816777 	 Accuracy: 0.39504563233376794
Delta: 0.0022710072654209433 	  Loss: 1.6076805125778708 	 Accuracy: 0.3963494132985658
Delta: 6.050518368893911e-05 	  Loss: 1.6076618904570317 	 Accuracy: 0.3963494132985658
Delta: 0.00213452449742888 	  Loss: 1.6073769203091142 	 Accuracy: 0.39113428943937417
Delta: 0.0018795406021699908 	  Loss: 1.6078661601306876 	 Accuracy: 0.39765319426336376
Delta: 0.0010989055486350415 	  Loss: 1.6077993201043994 	 Accuracy: 0.39895697522816165
Delta: 0.004115719993330687 	  Loss: 1.6077626228414794 	 Accuracy: 0.39765319426336376
Delta: 0.0011091876536999752 	  Loss: 1.6079410899708786 	 Accuracy: 0.39765319426336376
Delta: 0.0023109502466351095 	  Loss: 1.6081000817262756 	 Accuracy: 0.3963494132985658
Delta: 0.003843740854463338 	  Loss: 1.6085130719879042 	 Accuracy: 0.3963494132985658
Delta: 0.0034385816117802723 	  Loss: 1.6087375180351926 	 Accuracy: 0.3963494132985658
Delta: 0.002408692792560258 	  Loss: 1.6083126806713237 	 Accuracy: 0.39895697522816165
Delta: 0.0011178007979251812 	  Loss: 1.6082029090990513 	 Accuracy: 0.3963494132985658
Delta: 0.0016320826661485933 	  Loss: 1.6080696805961363 	 Accuracy: 0.39504563233376794
Delta: 0.002823186252052426 	  Loss: 1.6080419924770504 	 Accuracy: 0.39765319426336376
Delta: 0.0008569639953019369 	  Loss: 1.6084083170561554 	 Accuracy: 0.39765319426336376
Delta: 0.003098029279357154 	  Loss: 1.6089554916029472 	 Accuracy: 0.39504563233376794
Delta: 0.0020146507522990575 	  Loss: 1.6084772923673865 	 Accuracy: 0.39765319426336376
Delta: 0.00339129587419874 	  Loss: 1.6083405242279476 	 Accuracy: 0.39895697522816165
Delta: 0.0018539118246198537 	  Loss: 1.6083851539365674 	 Accuracy: 0.39504563233376794
Delta: 5.795716598433718e-05 	  Loss: 1.6083481757614635 	 Accuracy: 0.39765319426336376
Delta: 0.003955526984469927 	  Loss: 1.609346752757538 	 Accuracy: 0.3963494132985658
Delta: 0.0037090731379458225 	  Loss: 1.6087979910454204 	 Accuracy: 0.39504563233376794
Delta: 0.002900774216989142 	  Loss: 1.6090995057375914 	 Accuracy: 0.39765319426336376
Delta: 0.002814807940586901 	  Loss: 1.6088104315916552 	 Accuracy: 0.39765319426336376
Delta: 0.004898554575056766 	  Loss: 1.608356522725623 	 Accuracy: 0.3963494132985658
Delta: 0.0028471832774254794 	  Loss: 1.607568647022328 	 Accuracy: 0.39765319426336376
Delta: 0.000995713163052421 	  Loss: 1.6075112721857074 	 Accuracy: 0.39765319426336376
Delta: 0.002459484865872166 	  Loss: 1.6074584842751634 	 Accuracy: 0.39765319426336376
Delta: 0.0005961204511865063 	  Loss: 1.607819827434676 	 Accuracy: 0.3963494132985658
Delta: 0.004297600882571786 	  Loss: 1.6080633063682463 	 Accuracy: 0.39765319426336376
Delta: 0.004770434014504821 	  Loss: 1.6088038379906817 	 Accuracy: 0.4028683181225554
Delta: 0.002113112378475679 	  Loss: 1.6084287599929006 	 Accuracy: 0.39113428943937417
Delta: 0.00390943820136508 	  Loss: 1.60812340622948 	 Accuracy: 0.39504563233376794
Delta: 0.0027417280262401343 	  Loss: 1.6077475555918885 	 Accuracy: 0.3963494132985658
Delta: 0.0014623610775572485 	  Loss: 1.6080362344491101 	 Accuracy: 0.3963494132985658
Delta: 0.0014097887333486927 	  Loss: 1.608058632043757 	 Accuracy: 0.3963494132985658
Delta: 0.00282539818562966 	  Loss: 1.607874714703195 	 Accuracy: 0.39504563233376794
Delta: 0.0024165353325277914 	  Loss: 1.607601602775695 	 Accuracy: 0.39765319426336376
Delta: 0.002889115211897158 	  Loss: 1.6075420525760682 	 Accuracy: 0.3963494132985658
Delta: 0.0018007671002777486 	  Loss: 1.6076634612171063 	 Accuracy: 0.39374185136897
Delta: 0.0006009336789502546 	  Loss: 1.6077470319529754 	 Accuracy: 0.3963494132985658
Delta: 0.0026918168189477114 	  Loss: 1.6078367563016691 	 Accuracy: 0.3924380704041721
Delta: 0.0026897864581508038 	  Loss: 1.6076230949106622 	 Accuracy: 0.39113428943937417
Delta: 0.0011869949773083864 	  Loss: 1.607973399506999 	 Accuracy: 0.39504563233376794
Delta: 0.002069827852939874 	  Loss: 1.607681895786259 	 Accuracy: 0.39504563233376794
Delta: 0.0005669903917944555 	  Loss: 1.6078014096859468 	 Accuracy: 0.39765319426336376
Delta: 9.552328733393547e-05 	  Loss: 1.607490423853382 	 Accuracy: 0.3963494132985658
Delta: 0.0010855141340343675 	  Loss: 1.6076674310400547 	 Accuracy: 0.39504563233376794
Delta: 0.0009478610005729415 	  Loss: 1.6077780304033622 	 Accuracy: 0.39765319426336376
Delta: 0.0011048492482216904 	  Loss: 1.6079200137780814 	 Accuracy: 0.39504563233376794
Delta: 7.290952855036284e-05 	  Loss: 1.6077844886102088 	 Accuracy: 0.39374185136897
Delta: 0.004152389114516385 	  Loss: 1.6080734198535045 	 Accuracy: 0.39895697522816165
Delta: 0.005595646819824444 	  Loss: 1.6067680218399492 	 Accuracy: 0.3963494132985658
Delta: 0.004492037499402938 	  Loss: 1.6075552679779295 	 Accuracy: 0.39765319426336376
Delta: 0.0026066742473585345 	  Loss: 1.6075179756137021 	 Accuracy: 0.39765319426336376
Delta: 0.0030974925969212597 	  Loss: 1.6075831088769117 	 Accuracy: 0.39504563233376794
Delta: 0.0022861888315948487 	  Loss: 1.6074966474321788 	 Accuracy: 0.39765319426336376
Delta: 0.001983749949231105 	  Loss: 1.607651807902437 	 Accuracy: 0.39504563233376794
Delta: 0.0013364302096990038 	  Loss: 1.6075187653611045 	 Accuracy: 0.39765319426336376
Delta: 0.003855309549291916 	  Loss: 1.607248312318453 	 Accuracy: 0.4002607561929596
Delta: 0.004786372763872624 	  Loss: 1.606657746620967 	 Accuracy: 0.39765319426336376
Delta: 0.0036356153826585234 	  Loss: 1.6065675151440262 	 Accuracy: 0.39895697522816165
Delta: 0.00694025165653803 	  Loss: 1.6067036243038642 	 Accuracy: 0.39895697522816165
Delta: 0.002887288862698365 	  Loss: 1.6068823013116271 	 Accuracy: 0.39895697522816165
Delta: 5.126454598304189e-05 	  Loss: 1.607099954524998 	 Accuracy: 0.39765319426336376
Delta: 0.003633301094029532 	  Loss: 1.6074193189222274 	 Accuracy: 0.3963494132985658
Delta: 0.0021941962741364755 	  Loss: 1.606946635396848 	 Accuracy: 0.39895697522816165
Delta: 0.0006356227349940365 	  Loss: 1.6068872930621008 	 Accuracy: 0.39895697522816165
Delta: 0.003716279544831488 	  Loss: 1.6068199645865457 	 Accuracy: 0.39504563233376794
Delta: 0.0016316065748154668 	  Loss: 1.607000331987195 	 Accuracy: 0.39895697522816165
Delta: 0.0030294619956504954 	  Loss: 1.6066189023156707 	 Accuracy: 0.4002607561929596
Delta: 0.0019719011214694524 	  Loss: 1.6064079981200061 	 Accuracy: 0.4002607561929596
Delta: 0.0014890451121800077 	  Loss: 1.6066143330172595 	 Accuracy: 0.4002607561929596
Delta: 3.187104029903083e-06 	  Loss: 1.6066135464955866 	 Accuracy: 0.39895697522816165
Delta: 0.0033714627881575652 	  Loss: 1.6067396174525013 	 Accuracy: 0.4002607561929596
Delta: 0.02107594712053077 	  Loss: 2.1558945617182887 	 Accuracy: 0.1864406779661017
Delta: 0.019281534591621456 	  Loss: 2.021764637534843 	 Accuracy: 0.2737940026075619
Delta: 0.01855126013923739 	  Loss: 1.7964267106397782 	 Accuracy: 0.32333767926988266
Delta: 0.015848263740034875 	  Loss: 1.6785882805219376 	 Accuracy: 0.34028683181225555
Delta: 0.011896342282138015 	  Loss: 1.6379740231901412 	 Accuracy: 0.3376792698826597

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009347939469590326 	  Loss: 1.628668860522758 	 Accuracy: 0.33376792698826596
Delta: 0.007093667875603541 	  Loss: 1.6240335421614915 	 Accuracy: 0.3246414602346806
Delta: 0.006610112026878287 	  Loss: 1.6230935347124251 	 Accuracy: 0.3220338983050847
Delta: 0.004353584066959736 	  Loss: 1.6236460042923655 	 Accuracy: 0.3220338983050847
Delta: 0.003554845071760903 	  Loss: 1.6232319894619103 	 Accuracy: 0.3220338983050847
Delta: 0.0016041111367620137 	  Loss: 1.6229932104956954 	 Accuracy: 0.32333767926988266
Delta: 0.0015489249458247613 	  Loss: 1.622822652970744 	 Accuracy: 0.32333767926988266
Delta: 0.0027814198452142955 	  Loss: 1.6234139439845467 	 Accuracy: 0.3220338983050847
Delta: 0.0036764115315372392 	  Loss: 1.6234536029847728 	 Accuracy: 0.32333767926988266
Delta: 0.0022203426872554003 	  Loss: 1.6235035479837938 	 Accuracy: 0.32333767926988266
Delta: 0.0015429300633784046 	  Loss: 1.6233581241503823 	 Accuracy: 0.32333767926988266
Delta: 0.0013608897395376949 	  Loss: 1.6237472978710477 	 Accuracy: 0.3220338983050847
Delta: 0.0015817166921177556 	  Loss: 1.6236498962122052 	 Accuracy: 0.32333767926988266
Delta: 0.0025729433902005323 	  Loss: 1.6239465336070988 	 Accuracy: 0.32333767926988266
Delta: 0.00169206777032351 	  Loss: 1.6238959164615443 	 Accuracy: 0.32333767926988266
Delta: 0.001687314320101627 	  Loss: 1.6238544459711965 	 Accuracy: 0.3220338983050847
Delta: 0.003229252197205336 	  Loss: 1.6235151987504097 	 Accuracy: 0.32073011734028684
Delta: 0.0014195132548480963 	  Loss: 1.6235685276748097 	 Accuracy: 0.3220338983050847
Delta: 0.0013337404951662749 	  Loss: 1.6232204193594424 	 Accuracy: 0.3220338983050847
Delta: 0.0005631905751056543 	  Loss: 1.6235808353310277 	 Accuracy: 0.318122555410691
Delta: 0.002715361848076695 	  Loss: 1.6237432303527448 	 Accuracy: 0.3194263363754889
Delta: 0.001340969495527458 	  Loss: 1.6236477749891276 	 Accuracy: 0.32333767926988266
Delta: 0.0007658998811869947 	  Loss: 1.6237004495420047 	 Accuracy: 0.32073011734028684
Delta: 0.0011860240219543703 	  Loss: 1.6235357382082507 	 Accuracy: 0.32333767926988266
Delta: 0.0006856873489139867 	  Loss: 1.6232410005798834 	 Accuracy: 0.3220338983050847
Delta: 0.0026220351785449423 	  Loss: 1.6241578447908003 	 Accuracy: 0.3220338983050847
Delta: 0.002158861737847919 	  Loss: 1.6234980782116186 	 Accuracy: 0.3220338983050847
Delta: 0.0012099645570438965 	  Loss: 1.623043209672459 	 Accuracy: 0.3220338983050847
Delta: 0.0019228718451229348 	  Loss: 1.6232983995277421 	 Accuracy: 0.3220338983050847
Delta: 0.0012641865148188985 	  Loss: 1.6234752220919626 	 Accuracy: 0.32333767926988266
Delta: 2.840610699709642e-05 	  Loss: 1.6234808612295009 	 Accuracy: 0.3220338983050847
Delta: 0.0008485989356245039 	  Loss: 1.623466572548889 	 Accuracy: 0.3220338983050847
Delta: 0.0024296244477796983 	  Loss: 1.623514090636164 	 Accuracy: 0.32333767926988266
Delta: 0.004610875500068561 	  Loss: 1.6252279253261877 	 Accuracy: 0.32333767926988266
Delta: 0.0026405917145959548 	  Loss: 1.6242006655840813 	 Accuracy: 0.32333767926988266
Delta: 0.0016438777271866295 	  Loss: 1.6237452431266002 	 Accuracy: 0.3220338983050847
Delta: 0.002083599975412169 	  Loss: 1.6243477445832837 	 Accuracy: 0.32333767926988266
Delta: 0.0038989947308353083 	  Loss: 1.6242484654168372 	 Accuracy: 0.32333767926988266
Delta: 0.003939346066665318 	  Loss: 1.623601996324616 	 Accuracy: 0.32333767926988266
Delta: 0.0025770296294637183 	  Loss: 1.6241845457746908 	 Accuracy: 0.3246414602346806
Delta: 0.00437531068606224 	  Loss: 1.6240167886447496 	 Accuracy: 0.3259452411994785
Delta: 0.0023280679527251467 	  Loss: 1.6237786555432343 	 Accuracy: 0.3246414602346806
Delta: 0.0011474564852492408 	  Loss: 1.6243044070059467 	 Accuracy: 0.3246414602346806
Delta: 0.0006746818808662427 	  Loss: 1.6241117201991313 	 Accuracy: 0.32333767926988266
Delta: 0.0031136790473644095 	  Loss: 1.6249705771962533 	 Accuracy: 0.3220338983050847
Delta: 0.001885603630698829 	  Loss: 1.6245050309916562 	 Accuracy: 0.3220338983050847
Delta: 0.0006510107716439966 	  Loss: 1.6245024964340384 	 Accuracy: 0.3220338983050847
Delta: 0.0031075996502025393 	  Loss: 1.6244215560275062 	 Accuracy: 0.32073011734028684
Delta: 0.0011416232086722672 	  Loss: 1.6241967460192979 	 Accuracy: 0.32333767926988266
Delta: 0.001307773771075203 	  Loss: 1.6244198811369235 	 Accuracy: 0.32333767926988266
Delta: 0.0008693378364355831 	  Loss: 1.6242114563476786 	 Accuracy: 0.32333767926988266
Delta: 0.003098659007878071 	  Loss: 1.6242015176170053 	 Accuracy: 0.318122555410691
Delta: 0.0031196040810819703 	  Loss: 1.624560994635631 	 Accuracy: 0.3259452411994785
Delta: 0.0032094087176520888 	  Loss: 1.6234814589697215 	 Accuracy: 0.32333767926988266
Delta: 0.0020586284566945726 	  Loss: 1.6230983569470765 	 Accuracy: 0.3259452411994785
Delta: 0.004028554898019134 	  Loss: 1.6240726343955754 	 Accuracy: 0.33116036505867014
Delta: 0.004834873479065424 	  Loss: 1.6248866247868174 	 Accuracy: 0.3285528031290743
Delta: 0.002031106408737836 	  Loss: 1.6247187562513266 	 Accuracy: 0.3285528031290743
Delta: 0.002955481909419368 	  Loss: 1.623961653228127 	 Accuracy: 0.3246414602346806
Delta: 0.0036816154686239427 	  Loss: 1.623970414874006 	 Accuracy: 0.32985658409387225
Delta: 0.0034314879645782406 	  Loss: 1.6246881589785211 	 Accuracy: 0.3272490221642764
Delta: 0.003121773974817159 	  Loss: 1.6248940302561126 	 Accuracy: 0.3246414602346806
Delta: 0.002243637709662303 	  Loss: 1.6251324053236287 	 Accuracy: 0.3285528031290743
Delta: 0.0016298893947915172 	  Loss: 1.624873686978948 	 Accuracy: 0.3272490221642764
Delta: 4.163532713177112e-05 	  Loss: 1.6249015166120087 	 Accuracy: 0.32333767926988266
Delta: 0.0023802021150296686 	  Loss: 1.6233952609909768 	 Accuracy: 0.3272490221642764
Delta: 0.002444278757386962 	  Loss: 1.6236388111226985 	 Accuracy: 0.3272490221642764
Delta: 5.2634900778356615e-06 	  Loss: 1.6236383248449502 	 Accuracy: 0.32985658409387225
Delta: 0.003846164084119256 	  Loss: 1.6227732350102457 	 Accuracy: 0.32985658409387225
Delta: 0.004332140466339288 	  Loss: 1.622527540343008 	 Accuracy: 0.3285528031290743
Delta: 0.003468815806331789 	  Loss: 1.622802500313481 	 Accuracy: 0.3285528031290743
Delta: 0.004420762979306598 	  Loss: 1.6220843480067506 	 Accuracy: 0.3246414602346806
Delta: 0.005931901108199187 	  Loss: 1.6235537486361196 	 Accuracy: 0.3259452411994785
Delta: 0.00413964697574358 	  Loss: 1.622538717576198 	 Accuracy: 0.3246414602346806
Delta: 0.004900164722133743 	  Loss: 1.6206787321673766 	 Accuracy: 0.3220338983050847
Delta: 0.004840882986003539 	  Loss: 1.6208320521811044 	 Accuracy: 0.3259452411994785
Delta: 0.0025774332640162026 	  Loss: 1.6207624680911947 	 Accuracy: 0.32985658409387225
Delta: 0.001896361557977224 	  Loss: 1.6208029466095386 	 Accuracy: 0.3272490221642764
Delta: 0.0021256442640644837 	  Loss: 1.6208477328974145 	 Accuracy: 0.3259452411994785
Delta: 0.0031578573534066456 	  Loss: 1.6212504049689733 	 Accuracy: 0.3259452411994785
Delta: 0.002992510800905808 	  Loss: 1.6210524105449733 	 Accuracy: 0.32985658409387225
Delta: 0.0021219046881252313 	  Loss: 1.6209515939892807 	 Accuracy: 0.3272490221642764
Delta: 0.0027788879839361885 	  Loss: 1.6206119691402443 	 Accuracy: 0.3272490221642764
Delta: 0.003434858575048213 	  Loss: 1.621507868572148 	 Accuracy: 0.3285528031290743
Delta: 0.00408033507094667 	  Loss: 1.621582570213495 	 Accuracy: 0.3272490221642764
Delta: 0.004243986227220628 	  Loss: 1.6224764031452406 	 Accuracy: 0.3246414602346806
Delta: 0.0051630838299097735 	  Loss: 1.623053939820206 	 Accuracy: 0.32985658409387225
Delta: 0.003779773678004828 	  Loss: 1.6227229109849148 	 Accuracy: 0.3272490221642764
Delta: 0.002340931136380712 	  Loss: 1.6229509875667973 	 Accuracy: 0.3272490221642764
Delta: 0.0024108492222445366 	  Loss: 1.623020730254193 	 Accuracy: 0.3272490221642764
Delta: 0.003661371703832322 	  Loss: 1.6234935459545652 	 Accuracy: 0.3272490221642764
Delta: 0.0014155250840385495 	  Loss: 1.6234132422590655 	 Accuracy: 0.3272490221642764
Delta: 4.118865490201376e-06 	  Loss: 1.6234109251233786 	 Accuracy: 0.3272490221642764
Delta: 0.0017859302563617706 	  Loss: 1.6236252138763287 	 Accuracy: 0.3259452411994785
Delta: 0.0025115583454685293 	  Loss: 1.6234292416033238 	 Accuracy: 0.3272490221642764
Delta: 0.020945734450510834 	  Loss: 2.156854566421472 	 Accuracy: 0.1981747066492829
Delta: 0.01946772057995454 	  Loss: 2.0205439425255873 	 Accuracy: 0.29986962190352023
Delta: 0.01839284887153412 	  Loss: 1.7895431544586022 	 Accuracy: 0.2685788787483703
Delta: 0.01608977634747545 	  Loss: 1.6577666385531202 	 Accuracy: 0.25945241199478486
Delta: 0.011973716926176683 	  Loss: 1.6178403391799412 	 Accuracy: 0.2777053455019557

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00913474422136467 	  Loss: 1.6082989129591203 	 Accuracy: 0.2777053455019557
Delta: 0.006931673190884337 	  Loss: 1.606830987691616 	 Accuracy: 0.28292046936114734
Delta: 0.005208211216485192 	  Loss: 1.6066910526702427 	 Accuracy: 0.27640156453715775
Delta: 0.00428034987916291 	  Loss: 1.6066269732147878 	 Accuracy: 0.2790091264667536
Delta: 0.00346257840238859 	  Loss: 1.6069868450114557 	 Accuracy: 0.2803129074315515
Delta: 0.0028365402285829896 	  Loss: 1.6066389504570144 	 Accuracy: 0.2790091264667536
Delta: 0.002593351520687745 	  Loss: 1.6063443328818772 	 Accuracy: 0.2803129074315515
Delta: 0.0023619357871137348 	  Loss: 1.6068149511082526 	 Accuracy: 0.2790091264667536
Delta: 0.0034374412768656817 	  Loss: 1.6067227717158596 	 Accuracy: 0.2803129074315515
Delta: 0.0020241215910667635 	  Loss: 1.606634133485724 	 Accuracy: 0.2803129074315515
Delta: 3.4552706782956865e-05 	  Loss: 1.6067069899314617 	 Accuracy: 0.2803129074315515
Delta: 3.3501173137549135e-05 	  Loss: 1.606754615653108 	 Accuracy: 0.2803129074315515
Delta: 0.002890984924975299 	  Loss: 1.6068606328855362 	 Accuracy: 0.2803129074315515
Delta: 0.002597964266453934 	  Loss: 1.6067545243399897 	 Accuracy: 0.2790091264667536
Delta: 0.0010878204032211119 	  Loss: 1.6067980736270102 	 Accuracy: 0.2816166883963494
Delta: 0.0018279929494621294 	  Loss: 1.606793176203473 	 Accuracy: 0.2790091264667536
Delta: 0.001039208331318785 	  Loss: 1.6066949728099635 	 Accuracy: 0.2816166883963494
Delta: 0.0008868793665208615 	  Loss: 1.6069657295190303 	 Accuracy: 0.28292046936114734
Delta: 0.004993389711009128 	  Loss: 1.6081346558613134 	 Accuracy: 0.28292046936114734
Delta: 0.002141071584593655 	  Loss: 1.6074407012919525 	 Accuracy: 0.28292046936114734
Delta: 0.0026847773183410733 	  Loss: 1.6072640197258516 	 Accuracy: 0.28292046936114734
Delta: 0.002056390378840381 	  Loss: 1.6069920545242278 	 Accuracy: 0.28292046936114734
Delta: 0.0009265577003039485 	  Loss: 1.6072950964008461 	 Accuracy: 0.28292046936114734
Delta: 0.003115893535305267 	  Loss: 1.6075915073595515 	 Accuracy: 0.28292046936114734
Delta: 0.0016113503524005045 	  Loss: 1.6075860502973576 	 Accuracy: 0.28292046936114734
Delta: 0.0038990536952662235 	  Loss: 1.6078462788783785 	 Accuracy: 0.28552803129074317
Delta: 0.0029298187235316637 	  Loss: 1.6071729995201878 	 Accuracy: 0.2842242503259452
Delta: 0.0049651095058093776 	  Loss: 1.607634403290793 	 Accuracy: 0.28292046936114734
Delta: 0.0027231142547145585 	  Loss: 1.6071135605560067 	 Accuracy: 0.28292046936114734
Delta: 0.0017968304739899065 	  Loss: 1.6077764776154724 	 Accuracy: 0.2842242503259452
Delta: 0.0031939610563759967 	  Loss: 1.6073144598417493 	 Accuracy: 0.28292046936114734
Delta: 0.0012224221087670621 	  Loss: 1.6074958964620985 	 Accuracy: 0.28292046936114734
Delta: 0.001966834552249394 	  Loss: 1.6074258538310429 	 Accuracy: 0.28292046936114734
Delta: 0.0016438287137064546 	  Loss: 1.6076386508428926 	 Accuracy: 0.2777053455019557
Delta: 0.003143235080109086 	  Loss: 1.607422222665406 	 Accuracy: 0.2842242503259452
Delta: 0.003859798633882947 	  Loss: 1.606720207165059 	 Accuracy: 0.2816166883963494
Delta: 0.003779803733370673 	  Loss: 1.6055394715403781 	 Accuracy: 0.2737940026075619
Delta: 0.004976194374645314 	  Loss: 1.6067038695971934 	 Accuracy: 0.28292046936114734
Delta: 0.005579782842390132 	  Loss: 1.6053285018933543 	 Accuracy: 0.2777053455019557
Delta: 0.0007364225653446359 	  Loss: 1.6052402080682433 	 Accuracy: 0.2790091264667536
Delta: 0.003772954538343124 	  Loss: 1.6044233712046962 	 Accuracy: 0.2737940026075619
Delta: 0.00259898597599656 	  Loss: 1.6040017233267774 	 Accuracy: 0.2790091264667536
Delta: 0.0027408833216845713 	  Loss: 1.6040583620557327 	 Accuracy: 0.27640156453715775
Delta: 0.0049680557137530435 	  Loss: 1.605392329192874 	 Accuracy: 0.2803129074315515
Delta: 0.004778497343718123 	  Loss: 1.6042740612387223 	 Accuracy: 0.2790091264667536
Delta: 0.0012812906164683636 	  Loss: 1.6046285001423306 	 Accuracy: 0.2790091264667536
Delta: 8.5989045968151e-05 	  Loss: 1.6042559550582782 	 Accuracy: 0.2777053455019557
Delta: 0.0008777644881369989 	  Loss: 1.6042801923600283 	 Accuracy: 0.2790091264667536
Delta: 7.377737050128701e-05 	  Loss: 1.6042542385495933 	 Accuracy: 0.2790091264667536
Delta: 5.951608785081793e-05 	  Loss: 1.6043701301823918 	 Accuracy: 0.27640156453715775
Delta: 2.8417257509614536e-05 	  Loss: 1.604317126112993 	 Accuracy: 0.2803129074315515
Delta: 2.7031919801646204e-05 	  Loss: 1.6043941027496955 	 Accuracy: 0.2790091264667536
Delta: 0.0020888171419310175 	  Loss: 1.604204540607491 	 Accuracy: 0.2790091264667536
Delta: 0.002473965641445952 	  Loss: 1.6041014864864982 	 Accuracy: 0.2790091264667536
Delta: 9.839712376218672e-06 	  Loss: 1.6041012447096592 	 Accuracy: 0.2790091264667536
Delta: 3.4647528745854537e-06 	  Loss: 1.6041025461130571 	 Accuracy: 0.2803129074315515
Delta: 0.0034754377193181437 	  Loss: 1.6033383959794372 	 Accuracy: 0.2803129074315515
Delta: 0.0017184175924148607 	  Loss: 1.6033159375245107 	 Accuracy: 0.2777053455019557
Delta: 0.0029752583179722624 	  Loss: 1.6029804717599312 	 Accuracy: 0.2777053455019557
Delta: 0.002196598629909188 	  Loss: 1.6027931821999186 	 Accuracy: 0.2790091264667536
Delta: 0.0011615446376868669 	  Loss: 1.6029124086341484 	 Accuracy: 0.2803129074315515
Delta: 0.0008048491972272552 	  Loss: 1.6028719617216276 	 Accuracy: 0.2816166883963494
Delta: 0.002672039451423306 	  Loss: 1.6031194686226826 	 Accuracy: 0.2790091264667536
Delta: 0.0010438666360289297 	  Loss: 1.602848586013808 	 Accuracy: 0.2790091264667536
Delta: 7.484116267568071e-06 	  Loss: 1.602872164238164 	 Accuracy: 0.2790091264667536
Delta: 0.001319084850010585 	  Loss: 1.603044199163063 	 Accuracy: 0.2803129074315515
Delta: 0.0046813894739236835 	  Loss: 1.6034880058129637 	 Accuracy: 0.2816166883963494
Delta: 0.0035836455903171696 	  Loss: 1.6025578201108481 	 Accuracy: 0.2803129074315515
Delta: 0.003201242552115584 	  Loss: 1.602417692840906 	 Accuracy: 0.2842242503259452
Delta: 0.003456552701448036 	  Loss: 1.6022722060348333 	 Accuracy: 0.2777053455019557
Delta: 0.004858552502971191 	  Loss: 1.6019645842854324 	 Accuracy: 0.28292046936114734
Delta: 0.002046120127898591 	  Loss: 1.6021640150336902 	 Accuracy: 0.28292046936114734
Delta: 0.0054998009614779545 	  Loss: 1.6018773025641995 	 Accuracy: 0.2816166883963494
Delta: 0.003047649200100414 	  Loss: 1.6025740832514086 	 Accuracy: 0.2816166883963494
Delta: 0.0070006812712653296 	  Loss: 1.6006177722484702 	 Accuracy: 0.2803129074315515
Delta: 0.005105559428456704 	  Loss: 1.6014033607401335 	 Accuracy: 0.28292046936114734
Delta: 0.004966158961194167 	  Loss: 1.6009173762630429 	 Accuracy: 0.2816166883963494
Delta: 0.00508904447078426 	  Loss: 1.6004299518808693 	 Accuracy: 0.28292046936114734
Delta: 0.004758489327642716 	  Loss: 1.6001460407785588 	 Accuracy: 0.28292046936114734
Delta: 0.001325998543941783 	  Loss: 1.600350568835573 	 Accuracy: 0.28292046936114734
Delta: 0.005007727837614543 	  Loss: 1.6006907772098784 	 Accuracy: 0.2816166883963494
Delta: 0.00161685865415909 	  Loss: 1.6007135027429145 	 Accuracy: 0.2816166883963494
Delta: 0.0005092055248636033 	  Loss: 1.6007393819016 	 Accuracy: 0.2816166883963494
Delta: 0.00297984215291012 	  Loss: 1.6006759468222325 	 Accuracy: 0.2816166883963494
Delta: 0.0013146665440094093 	  Loss: 1.600676263272307 	 Accuracy: 0.2816166883963494
Delta: 4.3052047611072894e-05 	  Loss: 1.6006508729265336 	 Accuracy: 0.288135593220339
Delta: 0.002121257559374266 	  Loss: 1.600340015168429 	 Accuracy: 0.28292046936114734
Delta: 0.0031271913862536338 	  Loss: 1.6001723975748312 	 Accuracy: 0.28292046936114734
Delta: 0.0036439577613305925 	  Loss: 1.6001782332975858 	 Accuracy: 0.28292046936114734
Delta: 0.0034807199657499485 	  Loss: 1.6005509451625373 	 Accuracy: 0.28292046936114734
Delta: 0.004203503691647077 	  Loss: 1.6009843878555203 	 Accuracy: 0.2803129074315515
Delta: 0.0032426061595775095 	  Loss: 1.600946009857594 	 Accuracy: 0.2816166883963494
Delta: 0.002062456575159518 	  Loss: 1.600918193820855 	 Accuracy: 0.2803129074315515
Delta: 0.0005056523374803042 	  Loss: 1.6009360294149242 	 Accuracy: 0.2803129074315515
Delta: 0.0007796246821815066 	  Loss: 1.6009875774009286 	 Accuracy: 0.2803129074315515
Delta: 0.02107961955599021 	  Loss: 2.1561362104847377 	 Accuracy: 0.19947848761408082
Delta: 0.019290300673377735 	  Loss: 2.0161123497878273 	 Accuracy: 0.30378096479791394
Delta: 0.01835608300423281 	  Loss: 1.786522476364845 	 Accuracy: 0.30247718383311606
Delta: 0.01571817614250897 	  Loss: 1.6841326692815177 	 Accuracy: 0.30638852672750977

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.011487263815844907 	  Loss: 1.6591446607769873 	 Accuracy: 0.31029986962190353
Delta: 0.008752186890180008 	  Loss: 1.6533162116856621 	 Accuracy: 0.3155149934810952
Delta: 0.007580311016081878 	  Loss: 1.6524675763543035 	 Accuracy: 0.3155149934810952
Delta: 0.005915255798092905 	  Loss: 1.6529849901236902 	 Accuracy: 0.31421121251629724
Delta: 0.004214143145780066 	  Loss: 1.6521195927259724 	 Accuracy: 0.3155149934810952
Delta: 0.0018355373935645541 	  Loss: 1.6518721404553882 	 Accuracy: 0.31681877444589307
Delta: 0.002170389704765214 	  Loss: 1.6519596986472176 	 Accuracy: 0.3155149934810952
Delta: 0.00298037647264233 	  Loss: 1.6515567947456335 	 Accuracy: 0.318122555410691
Delta: 0.0020445115426073242 	  Loss: 1.6519082693106006 	 Accuracy: 0.318122555410691
Delta: 0.0024063404811233836 	  Loss: 1.651540249463788 	 Accuracy: 0.31681877444589307
Delta: 0.0015312381864087765 	  Loss: 1.6515190436488136 	 Accuracy: 0.31681877444589307
Delta: 0.0019667136846558664 	  Loss: 1.6515446026718048 	 Accuracy: 0.31681877444589307
Delta: 0.0008300592780216343 	  Loss: 1.6515934640734382 	 Accuracy: 0.3155149934810952
Delta: 0.0018295793345033961 	  Loss: 1.6515338739527978 	 Accuracy: 0.31681877444589307
Delta: 5.822034004486107e-05 	  Loss: 1.6514427542385905 	 Accuracy: 0.318122555410691
Delta: 0.0014879805718047083 	  Loss: 1.6513096786946804 	 Accuracy: 0.3155149934810952
Delta: 0.005214446823994266 	  Loss: 1.6506719046401335 	 Accuracy: 0.318122555410691
Delta: 0.0030912344908605623 	  Loss: 1.6503225641550117 	 Accuracy: 0.31681877444589307
Delta: 0.002964040091241547 	  Loss: 1.650962834622969 	 Accuracy: 0.31681877444589307
Delta: 0.0018417866719947363 	  Loss: 1.650311423174776 	 Accuracy: 0.31681877444589307
Delta: 0.0018283463838911485 	  Loss: 1.6506445716994977 	 Accuracy: 0.318122555410691
Delta: 0.00097824202939269 	  Loss: 1.6504407672047785 	 Accuracy: 0.31681877444589307
Delta: 0.002721108897738532 	  Loss: 1.6500787909426715 	 Accuracy: 0.31681877444589307
Delta: 0.002784369108922087 	  Loss: 1.6508250878240078 	 Accuracy: 0.31681877444589307
Delta: 0.001249222326709945 	  Loss: 1.6508780810303865 	 Accuracy: 0.31681877444589307
Delta: 0.001490800581328997 	  Loss: 1.6510704159111187 	 Accuracy: 0.3194263363754889
Delta: 0.0031097849459312903 	  Loss: 1.6506569430557885 	 Accuracy: 0.318122555410691
Delta: 0.004102847090497893 	  Loss: 1.6503430784443056 	 Accuracy: 0.318122555410691
Delta: 0.005219007126167314 	  Loss: 1.6505119640037138 	 Accuracy: 0.3155149934810952
Delta: 0.0034214179133689533 	  Loss: 1.6514259534850917 	 Accuracy: 0.3155149934810952
Delta: 0.00215313229312619 	  Loss: 1.6511863969823386 	 Accuracy: 0.31681877444589307
Delta: 0.0018964607110701487 	  Loss: 1.6511652076581815 	 Accuracy: 0.31681877444589307
Delta: 7.084970606323006e-05 	  Loss: 1.6512764214847349 	 Accuracy: 0.3155149934810952
Delta: 0.0028513709151586257 	  Loss: 1.6508179363266906 	 Accuracy: 0.31421121251629724
Delta: 0.0028049988349889534 	  Loss: 1.651315348128386 	 Accuracy: 0.3155149934810952
Delta: 5.426983716588768e-05 	  Loss: 1.6514088847025348 	 Accuracy: 0.3155149934810952
Delta: 0.0029147411954246753 	  Loss: 1.6507560702602753 	 Accuracy: 0.31421121251629724
Delta: 0.002815722520808482 	  Loss: 1.650897161573906 	 Accuracy: 0.3155149934810952
Delta: 0.001747701790836183 	  Loss: 1.650800025488488 	 Accuracy: 0.318122555410691
Delta: 0.0026673754059890246 	  Loss: 1.6508067278892113 	 Accuracy: 0.31681877444589307
Delta: 0.0027519702285693183 	  Loss: 1.6510080658507 	 Accuracy: 0.318122555410691
Delta: 0.0023993158328627913 	  Loss: 1.651066249803479 	 Accuracy: 0.31681877444589307
Delta: 0.004507748533548959 	  Loss: 1.6516006631057187 	 Accuracy: 0.31681877444589307
Delta: 0.0030341381114051824 	  Loss: 1.6510790572644707 	 Accuracy: 0.31681877444589307
Delta: 0.0005311728292316253 	  Loss: 1.6511195813326098 	 Accuracy: 0.318122555410691
Delta: 0.0023137364815715333 	  Loss: 1.6525516132998013 	 Accuracy: 0.3155149934810952
Delta: 0.003863704978296756 	  Loss: 1.6527086722035034 	 Accuracy: 0.3155149934810952
Delta: 0.0024779915596102363 	  Loss: 1.6533084121579056 	 Accuracy: 0.3155149934810952
Delta: 0.002099212042363912 	  Loss: 1.6534862762816083 	 Accuracy: 0.3155149934810952
Delta: 0.002797779343186649 	  Loss: 1.6534441683555805 	 Accuracy: 0.3155149934810952
Delta: 0.00293792449836673 	  Loss: 1.6536707867604854 	 Accuracy: 0.31681877444589307
Delta: 0.0005744038939648436 	  Loss: 1.6536673335426597 	 Accuracy: 0.3155149934810952
Delta: 0.0027216890695962812 	  Loss: 1.6533788739475785 	 Accuracy: 0.31290743155149936
Delta: 0.004156130363988674 	  Loss: 1.6537641122823339 	 Accuracy: 0.31421121251629724
Delta: 0.0038068804896687113 	  Loss: 1.6530730621257468 	 Accuracy: 0.3155149934810952
Delta: 0.002556667371860484 	  Loss: 1.652818739122809 	 Accuracy: 0.31681877444589307
Delta: 0.0029638985599926564 	  Loss: 1.6523050943164868 	 Accuracy: 0.3194263363754889
Delta: 0.003751228817421571 	  Loss: 1.651429695983818 	 Accuracy: 0.318122555410691
Delta: 0.0029403154755278014 	  Loss: 1.6512027819069484 	 Accuracy: 0.318122555410691
Delta: 0.0007037719861459677 	  Loss: 1.651178004101553 	 Accuracy: 0.318122555410691
Delta: 0.0004900927923323007 	  Loss: 1.6511772469895465 	 Accuracy: 0.32073011734028684
Delta: 0.0012299572232918861 	  Loss: 1.6511879482716258 	 Accuracy: 0.3194263363754889
Delta: 0.0014210173754153719 	  Loss: 1.6511898981334825 	 Accuracy: 0.3155149934810952
Delta: 0.0014345492236583143 	  Loss: 1.6513806151782817 	 Accuracy: 0.318122555410691
Delta: 0.0010031080009066885 	  Loss: 1.6514777458066652 	 Accuracy: 0.31421121251629724
Delta: 0.0033515947116862627 	  Loss: 1.6524192875425021 	 Accuracy: 0.31681877444589307
Delta: 0.004033067367935001 	  Loss: 1.6520472981704213 	 Accuracy: 0.31681877444589307
Delta: 0.0024972780122481573 	  Loss: 1.652026441256882 	 Accuracy: 0.318122555410691
Delta: 0.00263747877903943 	  Loss: 1.651948458812959 	 Accuracy: 0.31681877444589307
Delta: 0.0031955469121366198 	  Loss: 1.651787835347931 	 Accuracy: 0.31681877444589307
Delta: 0.0037800078756906976 	  Loss: 1.65090492620835 	 Accuracy: 0.31681877444589307
Delta: 0.0038063579127017157 	  Loss: 1.6525076534473095 	 Accuracy: 0.31681877444589307
Delta: 0.0033763728939061426 	  Loss: 1.65221676357949 	 Accuracy: 0.3155149934810952
Delta: 0.0023740336718137455 	  Loss: 1.6524282226325682 	 Accuracy: 0.3155149934810952
Delta: 0.001836313837638514 	  Loss: 1.6527419993219779 	 Accuracy: 0.3155149934810952
Delta: 0.0016570282791762813 	  Loss: 1.652546966511176 	 Accuracy: 0.3155149934810952
Delta: 0.0025682176864106677 	  Loss: 1.6527785774738661 	 Accuracy: 0.31421121251629724
Delta: 0.00415062418186868 	  Loss: 1.6518401732210952 	 Accuracy: 0.3155149934810952
Delta: 0.002532638760321057 	  Loss: 1.6523833125554983 	 Accuracy: 0.3155149934810952
Delta: 0.002067384303072835 	  Loss: 1.6518624420713632 	 Accuracy: 0.3155149934810952
Delta: 0.003174763179890788 	  Loss: 1.6522207387178378 	 Accuracy: 0.31681877444589307
Delta: 0.003367884845210137 	  Loss: 1.6506845423911334 	 Accuracy: 0.3155149934810952
Delta: 0.001717129757401569 	  Loss: 1.6509913897728778 	 Accuracy: 0.31681877444589307
Delta: 0.004889421209348328 	  Loss: 1.6502741744798222 	 Accuracy: 0.3155149934810952
Delta: 0.002580788968608 	  Loss: 1.651393697533245 	 Accuracy: 0.31421121251629724
Delta: 0.00354303533073351 	  Loss: 1.6528984643862246 	 Accuracy: 0.31290743155149936
Delta: 0.0026366093304672606 	  Loss: 1.6532470227999343 	 Accuracy: 0.31681877444589307
Delta: 0.0052704697450961955 	  Loss: 1.6531199922677242 	 Accuracy: 0.3155149934810952
Delta: 0.004651702165065447 	  Loss: 1.652139249547185 	 Accuracy: 0.3155149934810952
Delta: 0.0019219563717942458 	  Loss: 1.652113231998345 	 Accuracy: 0.3155149934810952
Delta: 0.0017641754177739844 	  Loss: 1.6521687722471503 	 Accuracy: 0.31421121251629724
Delta: 0.0032785336175564514 	  Loss: 1.65285251635074 	 Accuracy: 0.31421121251629724
Delta: 0.0034206020614532236 	  Loss: 1.6532272340332659 	 Accuracy: 0.31421121251629724
Delta: 0.005321539455974939 	  Loss: 1.6528530492386446 	 Accuracy: 0.31681877444589307
Delta: 0.004703943126064812 	  Loss: 1.6534309621631764 	 Accuracy: 0.31681877444589307
Delta: 0.003008372378967748 	  Loss: 1.6538455306480881 	 Accuracy: 0.31421121251629724
Delta: 0.021142601006649633 	  Loss: 2.15604533806953 	 Accuracy: 0.18252933507170796
Delta: 0.01943191372796628 	  Loss: 2.014571921307528 	 Accuracy: 0.31029986962190353
Delta: 0.018086268915739123 	  Loss: 1.7925658312842834 	 Accuracy: 0.29726205997392435
Delta: 0.015834753499304088 	  Loss: 1.685041934803522 	 Accuracy: 0.28683181225554105
Delta: 0.011577965812158678 	  Loss: 1.6563339159924237 	 Accuracy: 0.27640156453715775

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007903079550316171 	  Loss: 1.650747726384008 	 Accuracy: 0.2777053455019557
Delta: 0.005852362790816444 	  Loss: 1.6490848847665076 	 Accuracy: 0.2816166883963494
Delta: 0.005459624997164233 	  Loss: 1.6492992399117494 	 Accuracy: 0.2816166883963494
Delta: 0.004073771969579393 	  Loss: 1.6491874913730253 	 Accuracy: 0.2816166883963494
Delta: 0.003143451406375056 	  Loss: 1.6492246422469328 	 Accuracy: 0.28292046936114734
Delta: 0.0031887738485051804 	  Loss: 1.6491577192121079 	 Accuracy: 0.2816166883963494
Delta: 2.7524352533346698e-05 	  Loss: 1.6492171325963805 	 Accuracy: 0.2816166883963494
Delta: 0.0033435731143551238 	  Loss: 1.6491746511140657 	 Accuracy: 0.2816166883963494
Delta: 0.0019701209810821666 	  Loss: 1.6491163644689038 	 Accuracy: 0.2816166883963494
Delta: 0.002367759235693709 	  Loss: 1.649273217709729 	 Accuracy: 0.28292046936114734
Delta: 3.2284290284231844e-05 	  Loss: 1.6492150916576551 	 Accuracy: 0.2816166883963494
Delta: 0.002136777699049125 	  Loss: 1.6489688890201721 	 Accuracy: 0.2816166883963494
Delta: 0.0011422299670012226 	  Loss: 1.6491397662073026 	 Accuracy: 0.2816166883963494
Delta: 4.46555530514591e-05 	  Loss: 1.6491626678169895 	 Accuracy: 0.2816166883963494
Delta: 0.0009352716161868938 	  Loss: 1.6490031081276586 	 Accuracy: 0.2816166883963494
Delta: 0.002412850467296548 	  Loss: 1.648804241179581 	 Accuracy: 0.2803129074315515
Delta: 0.0026757552711443636 	  Loss: 1.6485763611100208 	 Accuracy: 0.2816166883963494
Delta: 0.0019522006626928423 	  Loss: 1.6490549827061347 	 Accuracy: 0.2816166883963494
Delta: 0.0017401623368145872 	  Loss: 1.6489576660847267 	 Accuracy: 0.2816166883963494
Delta: 0.0014658532135741174 	  Loss: 1.648942637823434 	 Accuracy: 0.28292046936114734
Delta: 0.0020892498960326934 	  Loss: 1.6486611969617164 	 Accuracy: 0.28292046936114734
Delta: 0.003919347168528749 	  Loss: 1.6478315682669766 	 Accuracy: 0.28292046936114734
Delta: 0.0024261253171335077 	  Loss: 1.6478773300138663 	 Accuracy: 0.2842242503259452
Delta: 0.0019209113898630435 	  Loss: 1.647462312660366 	 Accuracy: 0.2842242503259452
Delta: 0.003224394941075275 	  Loss: 1.6473822566030334 	 Accuracy: 0.27509778357235987
Delta: 0.0038784092274466143 	  Loss: 1.6476472552123846 	 Accuracy: 0.2894393741851369
Delta: 0.003859150184556146 	  Loss: 1.6470168972728634 	 Accuracy: 0.28292046936114734
Delta: 0.0022990777329604585 	  Loss: 1.6475576958086515 	 Accuracy: 0.28292046936114734
Delta: 0.003449827035567727 	  Loss: 1.6472343389803465 	 Accuracy: 0.2685788787483703
Delta: 0.00584109735081868 	  Loss: 1.6466205514821721 	 Accuracy: 0.28292046936114734
Delta: 0.0027981876090306043 	  Loss: 1.6466162246771672 	 Accuracy: 0.28292046936114734
Delta: 0.0016374621483351607 	  Loss: 1.6466761102005152 	 Accuracy: 0.28292046936114734
Delta: 0.0007925223560088265 	  Loss: 1.6467883161779002 	 Accuracy: 0.2842242503259452
Delta: 0.001709313709863444 	  Loss: 1.646356437154151 	 Accuracy: 0.2816166883963494
Delta: 0.0021589151489708478 	  Loss: 1.6465622438264709 	 Accuracy: 0.28292046936114734
Delta: 0.0021071971028353786 	  Loss: 1.6465177704559228 	 Accuracy: 0.28292046936114734
Delta: 0.0014461500998423987 	  Loss: 1.6462847774435458 	 Accuracy: 0.2803129074315515
Delta: 0.00011396436508394986 	  Loss: 1.6462561134996534 	 Accuracy: 0.28292046936114734
Delta: 0.003954928555339547 	  Loss: 1.6470784718677902 	 Accuracy: 0.28292046936114734
Delta: 0.0016666397057853001 	  Loss: 1.6473353030486046 	 Accuracy: 0.2816166883963494
Delta: 0.00010426197108450836 	  Loss: 1.6473026967795783 	 Accuracy: 0.2816166883963494
Delta: 0.0012634776769898208 	  Loss: 1.6470363232622818 	 Accuracy: 0.28292046936114734
Delta: 0.003224331059361387 	  Loss: 1.646211169627723 	 Accuracy: 0.2790091264667536
Delta: 0.0036196857038744553 	  Loss: 1.646265020310922 	 Accuracy: 0.28292046936114734
Delta: 0.003504582767380568 	  Loss: 1.6462699519230442 	 Accuracy: 0.28292046936114734
Delta: 0.0017543648994328665 	  Loss: 1.6461329883878049 	 Accuracy: 0.2790091264667536
Delta: 0.002274684421454229 	  Loss: 1.646521118237661 	 Accuracy: 0.2816166883963494
Delta: 0.004519976643379885 	  Loss: 1.6470477996608484 	 Accuracy: 0.28292046936114734
Delta: 0.003444986612020052 	  Loss: 1.6467794150615167 	 Accuracy: 0.2842242503259452
Delta: 0.002632874079459791 	  Loss: 1.6459547549733469 	 Accuracy: 0.2842242503259452
Delta: 0.0012995090052222013 	  Loss: 1.6456570211184665 	 Accuracy: 0.2816166883963494
Delta: 0.004443511624204595 	  Loss: 1.6451557925619442 	 Accuracy: 0.2842242503259452
Delta: 0.002267951390012216 	  Loss: 1.6450037657630907 	 Accuracy: 0.28292046936114734
Delta: 0.003497594634109243 	  Loss: 1.6460050605514505 	 Accuracy: 0.28292046936114734
Delta: 0.003907728184053724 	  Loss: 1.646008054059159 	 Accuracy: 0.2842242503259452
Delta: 0.005324705991110169 	  Loss: 1.6463572219910518 	 Accuracy: 0.2920469361147327
Delta: 0.006382475968211179 	  Loss: 1.64643074958079 	 Accuracy: 0.28683181225554105
Delta: 0.005104646489651486 	  Loss: 1.646725661999052 	 Accuracy: 0.2842242503259452
Delta: 0.003426172301795176 	  Loss: 1.6476427346481946 	 Accuracy: 0.28552803129074317
Delta: 0.0009132283896716206 	  Loss: 1.6472200975749827 	 Accuracy: 0.288135593220339
Delta: 0.002558888167709485 	  Loss: 1.6471971727712127 	 Accuracy: 0.2842242503259452
Delta: 0.004529596329352031 	  Loss: 1.6468141096604283 	 Accuracy: 0.27249022164276404
Delta: 0.0049250243301207355 	  Loss: 1.6463365751406516 	 Accuracy: 0.28292046936114734
Delta: 0.0024592461458425256 	  Loss: 1.6462326290564988 	 Accuracy: 0.2842242503259452
Delta: 0.003711256237210538 	  Loss: 1.6464455713039194 	 Accuracy: 0.2842242503259452
Delta: 0.0020573674219196555 	  Loss: 1.646736403990432 	 Accuracy: 0.2842242503259452
Delta: 0.0023872137349210004 	  Loss: 1.646392793821745 	 Accuracy: 0.2842242503259452
Delta: 0.0012156229128427165 	  Loss: 1.6462009066639158 	 Accuracy: 0.2842242503259452
Delta: 0.0012941869906874558 	  Loss: 1.6465457472777838 	 Accuracy: 0.2842242503259452
Delta: 0.003281871500958203 	  Loss: 1.6465463385635848 	 Accuracy: 0.28292046936114734
Delta: 0.002338527252353366 	  Loss: 1.6461363146640255 	 Accuracy: 0.28552803129074317
Delta: 0.004522703105739067 	  Loss: 1.6458372198434308 	 Accuracy: 0.28292046936114734
Delta: 0.005882335509274409 	  Loss: 1.6419376526088694 	 Accuracy: 0.28292046936114734
Delta: 0.004509479514465387 	  Loss: 1.642802295052309 	 Accuracy: 0.2816166883963494
Delta: 0.004409412187160856 	  Loss: 1.6425620801867968 	 Accuracy: 0.28292046936114734
Delta: 0.0042701967915978935 	  Loss: 1.6425554521749777 	 Accuracy: 0.2842242503259452
Delta: 0.0006294435840172853 	  Loss: 1.6425643562043484 	 Accuracy: 0.2816166883963494
Delta: 0.00339643245855668 	  Loss: 1.6426568440379912 	 Accuracy: 0.28292046936114734
Delta: 0.0004990837746916375 	  Loss: 1.642644664320946 	 Accuracy: 0.2842242503259452
Delta: 5.185188431796824e-06 	  Loss: 1.6426532781799188 	 Accuracy: 0.2777053455019557
Delta: 0.0054323454747754055 	  Loss: 1.6433033593359037 	 Accuracy: 0.28683181225554105
Delta: 0.004699533077546495 	  Loss: 1.6425359689299943 	 Accuracy: 0.2842242503259452
Delta: 0.00241569921015709 	  Loss: 1.6418767282590547 	 Accuracy: 0.28683181225554105
Delta: 0.0024444825092526327 	  Loss: 1.6420351722325748 	 Accuracy: 0.28552803129074317
Delta: 0.004833464594754154 	  Loss: 1.64188055004184 	 Accuracy: 0.28552803129074317
Delta: 0.002660889405576468 	  Loss: 1.6417319911014965 	 Accuracy: 0.2920469361147327
Delta: 0.0055073585970761485 	  Loss: 1.6424463105481717 	 Accuracy: 0.28552803129074317
Delta: 0.005469348005325065 	  Loss: 1.6439919822599953 	 Accuracy: 0.28552803129074317
Delta: 0.005813154857256881 	  Loss: 1.6434461911815401 	 Accuracy: 0.2920469361147327
Delta: 0.00328540663931386 	  Loss: 1.643881639850056 	 Accuracy: 0.28552803129074317
Delta: 0.0007066614647257592 	  Loss: 1.643855886170787 	 Accuracy: 0.27509778357235987
Delta: 0.0033983191694971415 	  Loss: 1.6444264539638356 	 Accuracy: 0.28292046936114734
Delta: 0.004380716217137313 	  Loss: 1.6439586148309902 	 Accuracy: 0.2842242503259452
Delta: 0.0017640608927813018 	  Loss: 1.6442084565092219 	 Accuracy: 0.2777053455019557
Delta: 0.004412155420617473 	  Loss: 1.644770698375472 	 Accuracy: 0.2803129074315515
Delta: 0.020901993367807268 	  Loss: 2.1472611615529478 	 Accuracy: 0.19947848761408082
Delta: 0.018112048670602073 	  Loss: 2.0713121813044797 	 Accuracy: 0.2333767926988266
Delta: 0.01567756875160705 	  Loss: 1.9700480227557255 	 Accuracy: 0.27509778357235987
Delta: 0.012965727027255632 	  Loss: 1.8682644010280947 	 Accuracy: 0.3650586701434159
Delta: 0.011061327931002155 	  Loss: 1.7900790353742784 	 Accuracy: 0.4041720990873533
Delta: 0.010003659090874353 	  Loss: 1.7376338373194353 	 Accuracy: 0.4106910039113429
Delta: 0.009388116397628033 	  Loss: 1.7013232624499213 	 Accuracy: 0.41199478487614083
Delta: 0.008540878839187827 	  Loss: 1.6764799273702695 	 Accuracy: 0.41590612777053454
Delta: 0.007915151631948444 	  Loss: 1.6584584938777733 	 Accuracy: 0.42242503259452413
Delta: 0.007765346981888542 	  Loss: 1.644599293993246 	 Accuracy: 0.4302477183833116
Delta: 0.008272342905751417 	  Loss: 1.6337458795529167 	 Accuracy: 0.4380704041720991
Delta: 0.007577734873908724 	  Loss: 1.6245999858305034 	 Accuracy: 0.44198174706649285
Delta: 0.007096443013442342 	  Loss: 1.617060849495351 	 Accuracy: 0.44198174706649285
Delta: 0.006762599798184216 	  Loss: 1.6109818103379134 	 Accuracy: 0.4471968709256845
Delta: 0.006898682615736291 	  Loss: 1.6057546441522321 	 Accuracy: 0.45371577574967403
Delta: 0.007247333830793011 	  Loss: 1.6013614799470717 	 Accuracy: 0.46153846153846156
Delta: 0.006440079964047073 	  Loss: 1.5975434706800251 	 Accuracy: 0.47196870925684486
Delta: 0.006902001939621615 	  Loss: 1.5934796711476247 	 Accuracy: 0.48370273794002605
Delta: 0.006774970851561533 	  Loss: 1.5896126747803407 	 Accuracy: 0.4915254237288136
Delta: 0.007343578788395388 	  Loss: 1.5852688928376142 	 Accuracy: 0.4980443285528031
Delta: 0.008599701390195776 	  Loss: 1.5806012045208668 	 Accuracy: 0.5019556714471969
Delta: 0.00819185021092701 	  Loss: 1.575584010366395 	 Accuracy: 0.5071707953063885
Delta: 0.00776897882748003 	  Loss: 1.5710287627480923 	 Accuracy: 0.5123859191655802
Delta: 0.0074090031940437905 	  Loss: 1.5666199674753651 	 Accuracy: 0.5176010430247718
Delta: 0.007375326971462557 	  Loss: 1.5618053323333434 	 Accuracy: 0.5241199478487614
Delta: 0.007099786100173698 	  Loss: 1.5567287180962057 	 Accuracy: 0.5202086049543677
Delta: 0.006104479578679098 	  Loss: 1.5529549751406115 	 Accuracy: 0.529335071707953
Delta: 0.006976971168099038 	  Loss: 1.5489565422848939 	 Accuracy: 0.5267275097783573
Delta: 0.006106672146965251 	  Loss: 1.5456819069392145 	 Accuracy: 0.5332464146023468
Delta: 0.00440959545339774 	  Loss: 1.543726971441349 	 Accuracy: 0.5319426336375489
Delta: 0.004706365286816599 	  Loss: 1.5417640171037743 	 Accuracy: 0.529335071707953
Delta: 0.0030587587389626653 	  Loss: 1.5405900362808271 	 Accuracy: 0.5345501955671447
Delta: 0.004682500490009277 	  Loss: 1.5387197649379374 	 Accuracy: 0.5371577574967406
Delta: 0.0036986734772195017 	  Loss: 1.537534083511686 	 Accuracy: 0.5384615384615384

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.003907232778332721 	  Loss: 1.5364910788746848 	 Accuracy: 0.5397653194263363
Delta: 0.003470411683006473 	  Loss: 1.535693154174484 	 Accuracy: 0.5475880052151239
Delta: 0.004630876921801057 	  Loss: 1.5346380128293502 	 Accuracy: 0.5423728813559322
Delta: 0.0037771762104159045 	  Loss: 1.5338951328692332 	 Accuracy: 0.5436766623207301
Delta: 0.0030094341212959816 	  Loss: 1.5333858073489792 	 Accuracy: 0.5436766623207301
Delta: 0.0025668913409948734 	  Loss: 1.5330171793218956 	 Accuracy: 0.5423728813559322
Delta: 0.003432548544473749 	  Loss: 1.5326153630328478 	 Accuracy: 0.5358539765319427
Delta: 0.0005382717960109835 	  Loss: 1.5322736689362901 	 Accuracy: 0.5423728813559322
Delta: 0.002563529376245245 	  Loss: 1.5320003189178988 	 Accuracy: 0.5397653194263363
Delta: 0.003945951776939904 	  Loss: 1.5318645705990428 	 Accuracy: 0.5397653194263363
Delta: 0.002762793290988898 	  Loss: 1.5315870127584597 	 Accuracy: 0.5384615384615384
Delta: 0.0020050236522472327 	  Loss: 1.5314092854648713 	 Accuracy: 0.5423728813559322
Delta: 0.002041739712014012 	  Loss: 1.5312912252017767 	 Accuracy: 0.5436766623207301
Delta: 0.001734944354912614 	  Loss: 1.531156009761431 	 Accuracy: 0.5436766623207301
Delta: 0.001429039514373162 	  Loss: 1.5310918938521647 	 Accuracy: 0.5423728813559322
Delta: 0.0033761176442578308 	  Loss: 1.5310555727149353 	 Accuracy: 0.5423728813559322
Delta: 0.0017870323862010725 	  Loss: 1.5309912893109885 	 Accuracy: 0.5436766623207301
Delta: 0.00095561070865543 	  Loss: 1.5308386336227002 	 Accuracy: 0.5423728813559322
Delta: 0.0018465751083331214 	  Loss: 1.5308511109702887 	 Accuracy: 0.5436766623207301
Delta: 0.0009603815090405173 	  Loss: 1.5306878621036102 	 Accuracy: 0.5436766623207301
Delta: 0.0010083303285372588 	  Loss: 1.5305873301867559 	 Accuracy: 0.5423728813559322
Delta: 0.0033431147570410044 	  Loss: 1.5304910067179949 	 Accuracy: 0.5423728813559322
Delta: 0.0012033032525572192 	  Loss: 1.5304203056478909 	 Accuracy: 0.5436766623207301
Delta: 0.0018157367768394052 	  Loss: 1.530374832431369 	 Accuracy: 0.5423728813559322
Delta: 0.001610723110302364 	  Loss: 1.5303232362301604 	 Accuracy: 0.5436766623207301
Delta: 0.002128685786080887 	  Loss: 1.5302192527639205 	 Accuracy: 0.5423728813559322
Delta: 0.001288549040255003 	  Loss: 1.5301346732699836 	 Accuracy: 0.5436766623207301
Delta: 0.002939614601117669 	  Loss: 1.530116612402827 	 Accuracy: 0.5436766623207301
Delta: 0.0008895900186814865 	  Loss: 1.530081436051942 	 Accuracy: 0.5397653194263363
Delta: 0.002175844054380496 	  Loss: 1.5300414282661836 	 Accuracy: 0.5436766623207301
Delta: 0.0027202803362428233 	  Loss: 1.5299604924572852 	 Accuracy: 0.5423728813559322
Delta: 0.0007276529084580107 	  Loss: 1.529925589270906 	 Accuracy: 0.5423728813559322
Delta: 0.0016000400711418431 	  Loss: 1.5299081353175756 	 Accuracy: 0.5423728813559322
Delta: 0.0015784337970259769 	  Loss: 1.5298904697702052 	 Accuracy: 0.5423728813559322
Delta: 0.0011846134789629506 	  Loss: 1.5298688339678495 	 Accuracy: 0.5423728813559322
Delta: 0.000950331877248966 	  Loss: 1.5298312387409874 	 Accuracy: 0.5397653194263363
Delta: 0.001703725385571024 	  Loss: 1.5297718554417115 	 Accuracy: 0.5410691003911343
Delta: 0.001701447020663038 	  Loss: 1.5297743546181604 	 Accuracy: 0.5410691003911343
Delta: 0.0015090247738566173 	  Loss: 1.5297276885405031 	 Accuracy: 0.5410691003911343
Delta: 0.0019233345055530934 	  Loss: 1.5297164990744596 	 Accuracy: 0.5410691003911343
Delta: 0.0007273796325556617 	  Loss: 1.529697998146966 	 Accuracy: 0.5410691003911343
Delta: 0.0007221849831102131 	  Loss: 1.5296628162211707 	 Accuracy: 0.5384615384615384
Delta: 0.0019409453994090266 	  Loss: 1.529650445857237 	 Accuracy: 0.5410691003911343
Delta: 0.0018188623429969519 	  Loss: 1.5296330535245328 	 Accuracy: 0.5410691003911343
Delta: 0.0005088934144394402 	  Loss: 1.5296115293426178 	 Accuracy: 0.5371577574967406
Delta: 0.001132168208771061 	  Loss: 1.5295978375074033 	 Accuracy: 0.5371577574967406
Delta: 0.0023250607480957293 	  Loss: 1.5295772292849357 	 Accuracy: 0.5384615384615384
Delta: 0.002623456449271811 	  Loss: 1.5295689019161443 	 Accuracy: 0.5397653194263363
Delta: 0.0015447088080987265 	  Loss: 1.5295316705983106 	 Accuracy: 0.5436766623207301
Delta: 0.0023657562008815728 	  Loss: 1.529477577905833 	 Accuracy: 0.5423728813559322
Delta: 0.0010114490441468134 	  Loss: 1.529443925590103 	 Accuracy: 0.5423728813559322
Delta: 0.000621224536836405 	  Loss: 1.5294332321129467 	 Accuracy: 0.5436766623207301
Delta: 0.0005238197900279952 	  Loss: 1.5293902887441906 	 Accuracy: 0.5410691003911343
Delta: 0.001553070156010477 	  Loss: 1.5293692214895764 	 Accuracy: 0.5423728813559322
Delta: 0.0025965580673302222 	  Loss: 1.5293315821626754 	 Accuracy: 0.5423728813559322
Delta: 0.0006222510389233656 	  Loss: 1.5293188406002904 	 Accuracy: 0.5436766623207301
Delta: 0.0019889693732476252 	  Loss: 1.5293289899990317 	 Accuracy: 0.5436766623207301
Delta: 3.0464776602710936e-05 	  Loss: 1.5292884203834594 	 Accuracy: 0.5436766623207301
Delta: 0.0004961639430172907 	  Loss: 1.5292620579682288 	 Accuracy: 0.5449804432855281
Delta: 0.0007203603354998938 	  Loss: 1.5292461157503145 	 Accuracy: 0.5423728813559322
Delta: 0.002619570234480246 	  Loss: 1.529187300754115 	 Accuracy: 0.5436766623207301
Delta: 0.0017583887030248847 	  Loss: 1.5291821639198082 	 Accuracy: 0.5423728813559322
Delta: 0.0030198089116170623 	  Loss: 1.5291323845992228 	 Accuracy: 0.5436766623207301
Delta: 0.0016519506118452033 	  Loss: 1.5290996183950902 	 Accuracy: 0.5436766623207301
Delta: 0.0009459245081736572 	  Loss: 1.5290841476088257 	 Accuracy: 0.5449804432855281
Delta: 0.001692077299105884 	  Loss: 1.5290487983427445 	 Accuracy: 0.5449804432855281
Delta: 0.020973435210308325 	  Loss: 2.147513905736981 	 Accuracy: 0.1981747066492829
Delta: 0.018272201492649277 	  Loss: 2.065429597912349 	 Accuracy: 0.30638852672750977
Delta: 0.016139040828416076 	  Loss: 1.9455748862746716 	 Accuracy: 0.4915254237288136
Delta: 0.014171817821408668 	  Loss: 1.8305631916892335 	 Accuracy: 0.5267275097783573
Delta: 0.013040004352469974 	  Loss: 1.7435860402390388 	 Accuracy: 0.5345501955671447
Delta: 0.01138547230455449 	  Loss: 1.682518458076327 	 Accuracy: 0.5319426336375489
Delta: 0.010880414003290829 	  Loss: 1.6405807946749233 	 Accuracy: 0.4980443285528031
Delta: 0.010370145019933151 	  Loss: 1.6108110341627904 	 Accuracy: 0.4810951760104302
Delta: 0.009024483935845934 	  Loss: 1.5894098569383042 	 Accuracy: 0.49022164276401564
Delta: 0.008553565827429964 	  Loss: 1.574415394651474 	 Accuracy: 0.5071707953063885
Delta: 0.007676198598533288 	  Loss: 1.5637521190088362 	 Accuracy: 0.5097783572359843
Delta: 0.007385957576741726 	  Loss: 1.5560626183757336 	 Accuracy: 0.5280312907431551
Delta: 0.0064437098994221675 	  Loss: 1.550421434605358 	 Accuracy: 0.5267275097783573
Delta: 0.006116386423697806 	  Loss: 1.546046169917454 	 Accuracy: 0.5345501955671447
Delta: 0.005584339066999066 	  Loss: 1.5422769558160778 	 Accuracy: 0.5371577574967406

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005127541786134855 	  Loss: 1.5395221125986986 	 Accuracy: 0.5397653194263363
Delta: 0.004680161967327944 	  Loss: 1.5375514962288288 	 Accuracy: 0.5371577574967406
Delta: 0.003838314175114769 	  Loss: 1.5359923297115308 	 Accuracy: 0.5371577574967406
Delta: 0.004617593955438972 	  Loss: 1.534749194559316 	 Accuracy: 0.5410691003911343
Delta: 0.0032226226533339547 	  Loss: 1.533697618012705 	 Accuracy: 0.5410691003911343
Delta: 0.004685982924249026 	  Loss: 1.533033576873942 	 Accuracy: 0.5410691003911343
Delta: 0.003220819752256372 	  Loss: 1.5324023254889476 	 Accuracy: 0.5397653194263363
Delta: 0.0033122839245783102 	  Loss: 1.5320180927392304 	 Accuracy: 0.5384615384615384
Delta: 0.0017352191449959992 	  Loss: 1.531759886830835 	 Accuracy: 0.5397653194263363
Delta: 0.00223426389328964 	  Loss: 1.531605710659866 	 Accuracy: 0.5384615384615384
Delta: 0.0012683032745782526 	  Loss: 1.5314618187447226 	 Accuracy: 0.5384615384615384
Delta: 0.0026068265859360623 	  Loss: 1.5313496780754983 	 Accuracy: 0.5397653194263363
Delta: 0.0016814384141778632 	  Loss: 1.5311986962036574 	 Accuracy: 0.5384615384615384
Delta: 0.002231609240049125 	  Loss: 1.5311310731876655 	 Accuracy: 0.5384615384615384
Delta: 0.002556357363845135 	  Loss: 1.531089015793267 	 Accuracy: 0.5384615384615384
Delta: 0.0006537784631670898 	  Loss: 1.531064472300646 	 Accuracy: 0.5397653194263363
Delta: 0.002525768818395306 	  Loss: 1.531060918060644 	 Accuracy: 0.5384615384615384
Delta: 0.0008850165602834191 	  Loss: 1.5309875872805594 	 Accuracy: 0.5384615384615384
Delta: 0.0016110643659782682 	  Loss: 1.5309428842802364 	 Accuracy: 0.5384615384615384
Delta: 0.0019379865888464961 	  Loss: 1.5309636906126707 	 Accuracy: 0.5371577574967406
Delta: 0.002289673256959085 	  Loss: 1.53091011431416 	 Accuracy: 0.5384615384615384
Delta: 0.0005222888541891584 	  Loss: 1.5308432967029928 	 Accuracy: 0.5384615384615384
Delta: 0.0016596602197923578 	  Loss: 1.5307823661974105 	 Accuracy: 0.5384615384615384
Delta: 2.799810809987642e-05 	  Loss: 1.5307633418728266 	 Accuracy: 0.5384615384615384
Delta: 0.0024268528356517684 	  Loss: 1.5308714387315945 	 Accuracy: 0.5371577574967406
Delta: 0.0005485199824205226 	  Loss: 1.5308659504490225 	 Accuracy: 0.5384615384615384
Delta: 0.0013023196466879629 	  Loss: 1.5307807729549308 	 Accuracy: 0.5384615384615384
Delta: 0.0008877535754154772 	  Loss: 1.5307100687300483 	 Accuracy: 0.5384615384615384
Delta: 0.0009086803129267794 	  Loss: 1.530760994761097 	 Accuracy: 0.5384615384615384
Delta: 0.0005218656460734705 	  Loss: 1.5307293230327643 	 Accuracy: 0.5397653194263363
Delta: 0.0021118751280660795 	  Loss: 1.5306003171747342 	 Accuracy: 0.5384615384615384
Delta: 0.0015810341731205102 	  Loss: 1.5308302222290995 	 Accuracy: 0.5384615384615384
Delta: 0.0023945564368183475 	  Loss: 1.530649751521766 	 Accuracy: 0.5384615384615384
Delta: 0.0005601519476737621 	  Loss: 1.5306965260731271 	 Accuracy: 0.5397653194263363
Delta: 5.52340308419784e-05 	  Loss: 1.5305945162551051 	 Accuracy: 0.5384615384615384
Delta: 2.379335811320175e-05 	  Loss: 1.5305823821800584 	 Accuracy: 0.5410691003911343
Delta: 0.0012532005014034334 	  Loss: 1.5305526859777112 	 Accuracy: 0.5384615384615384
Delta: 3.5670411090557377e-05 	  Loss: 1.5306229372806102 	 Accuracy: 0.5397653194263363
Delta: 4.4246469831030685e-05 	  Loss: 1.5306508893444262 	 Accuracy: 0.5410691003911343
Delta: 5.375947676215906e-05 	  Loss: 1.5305213893587244 	 Accuracy: 0.5397653194263363
Delta: 0.0010438171800920162 	  Loss: 1.530762981685393 	 Accuracy: 0.5397653194263363
Delta: 5.106703362781196e-05 	  Loss: 1.5305588408011963 	 Accuracy: 0.5384615384615384
Delta: 0.0007271002053206042 	  Loss: 1.5306948994513694 	 Accuracy: 0.5397653194263363
Delta: 0.0018278466222246027 	  Loss: 1.5306310567047663 	 Accuracy: 0.5423728813559322
Delta: 0.0017255364805148872 	  Loss: 1.530576345734856 	 Accuracy: 0.5397653194263363
Delta: 0.0028634422965093617 	  Loss: 1.5307651323327085 	 Accuracy: 0.5397653194263363
Delta: 7.714003993831066e-05 	  Loss: 1.5306177271731558 	 Accuracy: 0.5410691003911343
Delta: 0.002281110000218488 	  Loss: 1.5306925350801404 	 Accuracy: 0.5397653194263363
Delta: 0.0005616230034652692 	  Loss: 1.5306466959308578 	 Accuracy: 0.5410691003911343
Delta: 0.001732043424528197 	  Loss: 1.5305727611493294 	 Accuracy: 0.5384615384615384
Delta: 8.376195859489206e-05 	  Loss: 1.530747047533191 	 Accuracy: 0.5397653194263363
Delta: 9.773965621938622e-05 	  Loss: 1.5307279783739989 	 Accuracy: 0.5397653194263363
Delta: 4.04823176499921e-05 	  Loss: 1.5306793930584792 	 Accuracy: 0.5397653194263363
Delta: 3.703029810539354e-05 	  Loss: 1.5305945514912673 	 Accuracy: 0.5410691003911343
Delta: 5.063968106064976e-05 	  Loss: 1.5307442847765014 	 Accuracy: 0.5397653194263363
Delta: 4.855439573852606e-05 	  Loss: 1.5306288789970501 	 Accuracy: 0.5397653194263363
Delta: 3.6795670600353536e-05 	  Loss: 1.530643942542731 	 Accuracy: 0.5410691003911343
Delta: 4.9154143682072436e-05 	  Loss: 1.5306322602702258 	 Accuracy: 0.5397653194263363
Delta: 0.001045717620727656 	  Loss: 1.5306787115286202 	 Accuracy: 0.5384615384615384
Delta: 6.282879901862413e-05 	  Loss: 1.5306883640304512 	 Accuracy: 0.5410691003911343
Delta: 5.52258612316384e-05 	  Loss: 1.5307375165234984 	 Accuracy: 0.5384615384615384
Delta: 0.0017745085508835206 	  Loss: 1.5310149417273071 	 Accuracy: 0.5371577574967406
Delta: 0.0018333174806312576 	  Loss: 1.5310407844348566 	 Accuracy: 0.5397653194263363
Delta: 0.0009463151221849276 	  Loss: 1.5309549398713358 	 Accuracy: 0.5410691003911343
Delta: 0.0018630253469021137 	  Loss: 1.5308596835437207 	 Accuracy: 0.5410691003911343
Delta: 0.003406575230668419 	  Loss: 1.5306711572941896 	 Accuracy: 0.5410691003911343
Delta: 0.002856832841152068 	  Loss: 1.5313839570267405 	 Accuracy: 0.5423728813559322
Delta: 0.0028535938155856626 	  Loss: 1.5315347028225186 	 Accuracy: 0.5410691003911343
Delta: 0.003047176511375406 	  Loss: 1.5310538681438528 	 Accuracy: 0.5410691003911343
Delta: 0.003148715547282275 	  Loss: 1.5312485954955 	 Accuracy: 0.5397653194263363
Delta: 0.0036346723789175816 	  Loss: 1.531105379810908 	 Accuracy: 0.5345501955671447
Delta: 0.0029232932784180573 	  Loss: 1.5312932863262947 	 Accuracy: 0.5410691003911343
Delta: 0.0007666815016409786 	  Loss: 1.5308806299492799 	 Accuracy: 0.5397653194263363
Delta: 1.5672714993922794e-05 	  Loss: 1.530856020919228 	 Accuracy: 0.5397653194263363
Delta: 0.002339313351654349 	  Loss: 1.5308803659719734 	 Accuracy: 0.5397653194263363
Delta: 0.001302663996857741 	  Loss: 1.5310830415461831 	 Accuracy: 0.5332464146023468
Delta: 0.0020812609799956846 	  Loss: 1.532219862612456 	 Accuracy: 0.5384615384615384
Delta: 0.002865942098561842 	  Loss: 1.532757750414335 	 Accuracy: 0.5410691003911343
Delta: 0.003889155527729877 	  Loss: 1.5323573342597892 	 Accuracy: 0.5384615384615384
Delta: 0.001545399827256009 	  Loss: 1.5327810938478248 	 Accuracy: 0.5371577574967406
Delta: 0.00196866610481736 	  Loss: 1.532621230041335 	 Accuracy: 0.5371577574967406
Delta: 0.0017082565961076862 	  Loss: 1.5328337315308385 	 Accuracy: 0.5384615384615384
Delta: 0.00220111950970046 	  Loss: 1.5323303856029589 	 Accuracy: 0.5371577574967406
Delta: 0.003493868731018566 	  Loss: 1.5321707030111136 	 Accuracy: 0.5371577574967406
Delta: 0.0014046419009767568 	  Loss: 1.5319501104040771 	 Accuracy: 0.5384615384615384
Delta: 0.020944594104602886 	  Loss: 2.1470544219248398 	 Accuracy: 0.19947848761408082
Delta: 0.01831473073816454 	  Loss: 2.0668853419223527 	 Accuracy: 0.22033898305084745
Delta: 0.01587986881499449 	  Loss: 1.9460917744503776 	 Accuracy: 0.3494132985658409
Delta: 0.013488683740132826 	  Loss: 1.8221730375228522 	 Accuracy: 0.3859191655801825
Delta: 0.011278386513612767 	  Loss: 1.7355564044884306 	 Accuracy: 0.41199478487614083
Delta: 0.010857831944521796 	  Loss: 1.6839861308272455 	 Accuracy: 0.41199478487614083
Delta: 0.010562530308737607 	  Loss: 1.6520106371079146 	 Accuracy: 0.4172099087353325
Delta: 0.010143472830280149 	  Loss: 1.629856340558402 	 Accuracy: 0.4302477183833116
Delta: 0.00994869645690512 	  Loss: 1.6126369812126384 	 Accuracy: 0.44328552803129073
Delta: 0.009302910205451997 	  Loss: 1.5990961834387794 	 Accuracy: 0.4576271186440678
Delta: 0.008118989099180384 	  Loss: 1.5890749393053805 	 Accuracy: 0.4706649282920469
Delta: 0.007637383122554859 	  Loss: 1.5813099259668026 	 Accuracy: 0.48239895697522817
Delta: 0.006995081779226312 	  Loss: 1.5751558478528347 	 Accuracy: 0.485006518904824
Delta: 0.006486223837119798 	  Loss: 1.5708586402036295 	 Accuracy: 0.48891786179921776
Delta: 0.005013539418130692 	  Loss: 1.5676105567283645 	 Accuracy: 0.49282920469361147
Delta: 0.005048064399052115 	  Loss: 1.565546612636923 	 Accuracy: 0.49674054758800523

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004730961631543519 	  Loss: 1.5644914949797983 	 Accuracy: 0.4980443285528031
Delta: 0.0036693998869642224 	  Loss: 1.5638862625625698 	 Accuracy: 0.4876140808344198
Delta: 0.0038450951213481843 	  Loss: 1.5631744015562314 	 Accuracy: 0.4941329856584094
Delta: 0.0028762639746706888 	  Loss: 1.5626594821892639 	 Accuracy: 0.49934810951760106
Delta: 0.003737339697453478 	  Loss: 1.5619079363225574 	 Accuracy: 0.4954367666232073
Delta: 0.002582888060064826 	  Loss: 1.561536069843166 	 Accuracy: 0.49674054758800523
Delta: 0.0018211577122472543 	  Loss: 1.5616550686364525 	 Accuracy: 0.5032594524119948
Delta: 0.003684638574840018 	  Loss: 1.5614617752833997 	 Accuracy: 0.500651890482399
Delta: 0.002803940437414403 	  Loss: 1.5613255405872282 	 Accuracy: 0.500651890482399
Delta: 0.002994866950239306 	  Loss: 1.5609759876952483 	 Accuracy: 0.4980443285528031
Delta: 0.0031608825301410884 	  Loss: 1.5603714904767731 	 Accuracy: 0.4980443285528031
Delta: 0.002431313692680368 	  Loss: 1.560287229951982 	 Accuracy: 0.5019556714471969
Delta: 0.0029758497703950186 	  Loss: 1.5602252196763002 	 Accuracy: 0.5019556714471969
Delta: 0.0018823297668336225 	  Loss: 1.5600871242272605 	 Accuracy: 0.500651890482399
Delta: 0.002485299094522587 	  Loss: 1.5598259029274013 	 Accuracy: 0.5019556714471969
Delta: 0.0032798396555665313 	  Loss: 1.5598805826352684 	 Accuracy: 0.5019556714471969
Delta: 4.676540938266197e-05 	  Loss: 1.5598452544278354 	 Accuracy: 0.5019556714471969
Delta: 0.0006177600207336539 	  Loss: 1.5597923839179488 	 Accuracy: 0.5019556714471969
Delta: 2.5362909258278915e-05 	  Loss: 1.5597986885247757 	 Accuracy: 0.500651890482399
Delta: 0.001333999754269296 	  Loss: 1.5597166010808579 	 Accuracy: 0.500651890482399
Delta: 1.8209544948394188e-05 	  Loss: 1.5597569413994912 	 Accuracy: 0.5019556714471969
Delta: 1.6826581049747526e-05 	  Loss: 1.5598219952655241 	 Accuracy: 0.5019556714471969
Delta: 2.3622398008800168e-05 	  Loss: 1.559805869027775 	 Accuracy: 0.5019556714471969
Delta: 0.000509189345358795 	  Loss: 1.559874611145084 	 Accuracy: 0.5019556714471969
Delta: 0.000985843363277831 	  Loss: 1.5598841723600152 	 Accuracy: 0.49934810951760106
Delta: 0.0011903690091345726 	  Loss: 1.55980245968563 	 Accuracy: 0.500651890482399
Delta: 3.595774074343578e-05 	  Loss: 1.5598058367748693 	 Accuracy: 0.500651890482399
Delta: 0.0015328454336462894 	  Loss: 1.5598604095443314 	 Accuracy: 0.5019556714471969
Delta: 6.604183908324799e-05 	  Loss: 1.5597430173155649 	 Accuracy: 0.5019556714471969
Delta: 2.8746284388987185e-05 	  Loss: 1.5597181637296589 	 Accuracy: 0.5019556714471969
Delta: 3.209423924219166e-05 	  Loss: 1.5598608188841423 	 Accuracy: 0.500651890482399
Delta: 0.0014815988770928016 	  Loss: 1.559920192434772 	 Accuracy: 0.500651890482399
Delta: 0.002226827265911241 	  Loss: 1.5599743701357427 	 Accuracy: 0.500651890482399
Delta: 0.0020942235174806266 	  Loss: 1.5598698817686518 	 Accuracy: 0.5019556714471969
Delta: 5.985964988033567e-05 	  Loss: 1.5598053790304192 	 Accuracy: 0.5032594524119948
Delta: 0.0025215347473170353 	  Loss: 1.5595477268092326 	 Accuracy: 0.5058670143415906
Delta: 0.0019274125345816549 	  Loss: 1.5595995445456845 	 Accuracy: 0.5019556714471969
Delta: 0.0009996878374915132 	  Loss: 1.5598292075674622 	 Accuracy: 0.500651890482399
Delta: 0.0007501270273772028 	  Loss: 1.5599154960620067 	 Accuracy: 0.5019556714471969
Delta: 0.0012060221810125066 	  Loss: 1.5597616233318914 	 Accuracy: 0.5019556714471969
Delta: 0.0027958862422632204 	  Loss: 1.559922161090715 	 Accuracy: 0.5019556714471969
Delta: 0.002019907944934642 	  Loss: 1.5598259810558928 	 Accuracy: 0.500651890482399
Delta: 0.0007382713253138961 	  Loss: 1.5596969989017309 	 Accuracy: 0.500651890482399
Delta: 0.0022185834134830842 	  Loss: 1.5597624254811033 	 Accuracy: 0.5019556714471969
Delta: 0.002380721396612132 	  Loss: 1.5598473888014688 	 Accuracy: 0.500651890482399
Delta: 0.0019739515392372944 	  Loss: 1.5596767025386926 	 Accuracy: 0.49934810951760106
Delta: 0.0027480356863595398 	  Loss: 1.5594670994089628 	 Accuracy: 0.49934810951760106
Delta: 0.0035394983735298896 	  Loss: 1.559095955337067 	 Accuracy: 0.5019556714471969
Delta: 0.002381098184578845 	  Loss: 1.5591680914480035 	 Accuracy: 0.500651890482399
Delta: 0.002124487781709017 	  Loss: 1.5598860697562094 	 Accuracy: 0.5019556714471969
Delta: 0.0011962426171898805 	  Loss: 1.559317428101421 	 Accuracy: 0.5032594524119948
Delta: 0.0031703875012259342 	  Loss: 1.559711884712673 	 Accuracy: 0.5032594524119948
Delta: 0.00255725370791691 	  Loss: 1.5594219017934563 	 Accuracy: 0.500651890482399
Delta: 2.189861274714721e-05 	  Loss: 1.5595486552169824 	 Accuracy: 0.5019556714471969
Delta: 0.001274946014637225 	  Loss: 1.5594538780279228 	 Accuracy: 0.5019556714471969
Delta: 0.0005611491522527819 	  Loss: 1.559397091118948 	 Accuracy: 0.5019556714471969
Delta: 0.001652635469777143 	  Loss: 1.5593640567069484 	 Accuracy: 0.5032594524119948
Delta: 6.073281328455081e-05 	  Loss: 1.5593972786076544 	 Accuracy: 0.500651890482399
Delta: 0.0008475051857662497 	  Loss: 1.5595667260926338 	 Accuracy: 0.49282920469361147
Delta: 0.00353947666998258 	  Loss: 1.5592168486323406 	 Accuracy: 0.48239895697522817
Delta: 0.0017523205170630958 	  Loss: 1.5595473057183926 	 Accuracy: 0.5019556714471969
Delta: 0.002162114192831236 	  Loss: 1.5591931909818892 	 Accuracy: 0.500651890482399
Delta: 0.0027494297140895694 	  Loss: 1.559697638905567 	 Accuracy: 0.49934810951760106
Delta: 0.002058795191363155 	  Loss: 1.5593746153230814 	 Accuracy: 0.500651890482399
Delta: 0.0010884346823074407 	  Loss: 1.5596003588094993 	 Accuracy: 0.5019556714471969
Delta: 0.0010141468928129673 	  Loss: 1.5596157115896 	 Accuracy: 0.5032594524119948
Delta: 0.004674108908877783 	  Loss: 1.5603023357334365 	 Accuracy: 0.5045632333767927
Delta: 0.00181227127605676 	  Loss: 1.55997220089664 	 Accuracy: 0.500651890482399
Delta: 0.0018383905763532048 	  Loss: 1.5602925199467033 	 Accuracy: 0.500651890482399
Delta: 0.0019943303533777835 	  Loss: 1.5600926675991067 	 Accuracy: 0.5019556714471969
Delta: 0.002119313854713393 	  Loss: 1.5599206956696334 	 Accuracy: 0.49934810951760106
Delta: 0.002661069971714252 	  Loss: 1.5606054301418686 	 Accuracy: 0.500651890482399
Delta: 0.0017182569408609153 	  Loss: 1.5606008774161548 	 Accuracy: 0.5032594524119948
Delta: 0.003956897524829614 	  Loss: 1.5601563770348377 	 Accuracy: 0.500651890482399
Delta: 0.003452867272354967 	  Loss: 1.5621796894776756 	 Accuracy: 0.5019556714471969
Delta: 0.0037774059222429285 	  Loss: 1.5615293773648125 	 Accuracy: 0.5032594524119948
Delta: 0.0015923695885386646 	  Loss: 1.5618816472507628 	 Accuracy: 0.5019556714471969
Delta: 0.0026013652075062366 	  Loss: 1.5622403284973059 	 Accuracy: 0.5058670143415906
Delta: 0.0031765055251628104 	  Loss: 1.5613848666533652 	 Accuracy: 0.5019556714471969
Delta: 6.110858873849818e-05 	  Loss: 1.5612450032213356 	 Accuracy: 0.5032594524119948
Delta: 0.003216612993985165 	  Loss: 1.5615996534068497 	 Accuracy: 0.5032594524119948
Delta: 0.003068169348778768 	  Loss: 1.5615177923100672 	 Accuracy: 0.5019556714471969
Delta: 0.0021062046275882357 	  Loss: 1.5613045485818082 	 Accuracy: 0.49934810951760106
Delta: 0.0014856024600810181 	  Loss: 1.56168332921515 	 Accuracy: 0.500651890482399
Delta: 0.020927595704542116 	  Loss: 2.1470825099020865 	 Accuracy: 0.20078226857887874
Delta: 0.018334456154001793 	  Loss: 2.0617458349757514 	 Accuracy: 0.24119947848761408
Delta: 0.016238025811567035 	  Loss: 1.9335306960331433 	 Accuracy: 0.29595827900912647
Delta: 0.014132484011055565 	  Loss: 1.8012126977055551 	 Accuracy: 0.4106910039113429
Delta: 0.012088928521249277 	  Loss: 1.71348953862437 	 Accuracy: 0.41851368970013036
Delta: 0.010757703259057111 	  Loss: 1.6648911409370286 	 Accuracy: 0.43546284224250326
Delta: 0.01015712765591818 	  Loss: 1.6372998880573892 	 Accuracy: 0.4302477183833116
Delta: 0.009060006380458384 	  Loss: 1.6210236436909815 	 Accuracy: 0.4380704041720991
Delta: 0.008428729758521353 	  Loss: 1.6100081340435914 	 Accuracy: 0.4380704041720991
Delta: 0.0075870141114898985 	  Loss: 1.6030978450346032 	 Accuracy: 0.44589308996088656
Delta: 0.007357494922833949 	  Loss: 1.5972135605386868 	 Accuracy: 0.4406779661016949
Delta: 0.006704548110282661 	  Loss: 1.5935860187130213 	 Accuracy: 0.4498044328552803
Delta: 0.006370414965047678 	  Loss: 1.5905879875048716 	 Accuracy: 0.45241199478487615

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006977198188303048 	  Loss: 1.588076554452958 	 Accuracy: 0.4511082138200782
Delta: 0.005576177569010622 	  Loss: 1.5867580503849437 	 Accuracy: 0.45371577574967403
Delta: 0.004755934474323608 	  Loss: 1.5861559283080584 	 Accuracy: 0.455019556714472
Delta: 0.005324423630568224 	  Loss: 1.585246886948838 	 Accuracy: 0.45371577574967403
Delta: 0.004149379409614293 	  Loss: 1.5845731242177983 	 Accuracy: 0.455019556714472
Delta: 0.0017542563311061562 	  Loss: 1.5843758346556975 	 Accuracy: 0.4498044328552803
Delta: 0.0031275854300188855 	  Loss: 1.5843212434861114 	 Accuracy: 0.455019556714472
Delta: 0.0029680593750941405 	  Loss: 1.584300582039617 	 Accuracy: 0.4511082138200782
Delta: 0.0022471151066489363 	  Loss: 1.5843442542610624 	 Accuracy: 0.4511082138200782
Delta: 0.0027046067017256785 	  Loss: 1.5843442638907081 	 Accuracy: 0.4511082138200782
converged at iter  22
Delta: 0.020965143107047633 	  Loss: 2.1471894103185116 	 Accuracy: 0.1981747066492829
Delta: 0.018245933183019033 	  Loss: 2.0594510042937686 	 Accuracy: 0.2255541069100391
Delta: 0.01647185482249543 	  Loss: 1.9173614493719606 	 Accuracy: 0.27509778357235987
Delta: 0.013764232232867834 	  Loss: 1.7818959769686162 	 Accuracy: 0.38722294654498046
Delta: 0.012151656072600464 	  Loss: 1.6978287105084253 	 Accuracy: 0.4198174706649283
Delta: 0.010897790874354756 	  Loss: 1.6541829349079014 	 Accuracy: 0.42633637548891784
Delta: 0.009916488362591463 	  Loss: 1.6313162660137432 	 Accuracy: 0.42242503259452413
Delta: 0.009113324756539795 	  Loss: 1.6184488664916663 	 Accuracy: 0.4276401564537158
Delta: 0.008539769222592237 	  Loss: 1.610527407206236 	 Accuracy: 0.44328552803129073
Delta: 0.008407019739220811 	  Loss: 1.604449648116426 	 Accuracy: 0.46153846153846156
Delta: 0.007649624227032233 	  Loss: 1.5992635962979946 	 Accuracy: 0.4667535853976532

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006271259331200146 	  Loss: 1.5955794611536351 	 Accuracy: 0.46936114732724904
Delta: 0.006285617911049916 	  Loss: 1.5932883000857614 	 Accuracy: 0.4758800521512386
Delta: 0.004958527964942193 	  Loss: 1.5917896809183567 	 Accuracy: 0.47196870925684486
Delta: 0.004265458372123654 	  Loss: 1.591201089716065 	 Accuracy: 0.4784876140808344
Delta: 0.003704481799677952 	  Loss: 1.5910059676628292 	 Accuracy: 0.4758800521512386
Delta: 0.003213597178220915 	  Loss: 1.5910558157072288 	 Accuracy: 0.47327249022164275
Delta: 0.0028224999035613508 	  Loss: 1.5912589962626913 	 Accuracy: 0.4758800521512386
Delta: 0.002079039558655414 	  Loss: 1.5914708574195844 	 Accuracy: 0.47327249022164275
Delta: 0.002386624512268588 	  Loss: 1.5915100041832653 	 Accuracy: 0.47196870925684486
Delta: 0.002863373318966789 	  Loss: 1.5915008967485695 	 Accuracy: 0.4745762711864407
Delta: 3.581426601670257e-05 	  Loss: 1.5914625212746005 	 Accuracy: 0.47327249022164275
Delta: 3.4855009800120246e-05 	  Loss: 1.5914737486902797 	 Accuracy: 0.47196870925684486
Delta: 2.534861328465405e-05 	  Loss: 1.5914707772821095 	 Accuracy: 0.47327249022164275
Delta: 0.00011078441788214737 	  Loss: 1.591749504221362 	 Accuracy: 0.47196870925684486
Delta: 0.001785853712340805 	  Loss: 1.5916799868695326 	 Accuracy: 0.47196870925684486
Delta: 0.0027616298808268557 	  Loss: 1.5917040484946474 	 Accuracy: 0.47327249022164275
Delta: 0.0007389208620299006 	  Loss: 1.5915201193054958 	 Accuracy: 0.47327249022164275
Delta: 0.0007248291238410256 	  Loss: 1.5916039166009255 	 Accuracy: 0.4706649282920469
Delta: 3.6882250393564644e-05 	  Loss: 1.5917509156405891 	 Accuracy: 0.4706649282920469
Delta: 0.0020099446805981296 	  Loss: 1.591648210140605 	 Accuracy: 0.47327249022164275
Delta: 2.48941119039459e-05 	  Loss: 1.591593302331384 	 Accuracy: 0.47327249022164275
Delta: 1.866899983722183e-05 	  Loss: 1.59163137192053 	 Accuracy: 0.4745762711864407
Delta: 5.509026922767191e-05 	  Loss: 1.5919519449194826 	 Accuracy: 0.47327249022164275
Delta: 0.003210278512446788 	  Loss: 1.5928899014663762 	 Accuracy: 0.47196870925684486
Delta: 0.004183797313917659 	  Loss: 1.5926259279564339 	 Accuracy: 0.47327249022164275
Delta: 0.00223282563056339 	  Loss: 1.5926589988821496 	 Accuracy: 0.47327249022164275
Delta: 0.0011335572546113885 	  Loss: 1.5924193170089556 	 Accuracy: 0.47196870925684486
Delta: 0.0007015559480406107 	  Loss: 1.5928039651884518 	 Accuracy: 0.47196870925684486
Delta: 0.0009093744299741658 	  Loss: 1.5927975760663182 	 Accuracy: 0.47327249022164275
Delta: 0.0016212499502062958 	  Loss: 1.5928119613192289 	 Accuracy: 0.47327249022164275
Delta: 0.001373476001615003 	  Loss: 1.592822094746856 	 Accuracy: 0.4745762711864407
Delta: 0.0016970186931128135 	  Loss: 1.5924468913862642 	 Accuracy: 0.4745762711864407
Delta: 0.001142788164968449 	  Loss: 1.5924705693623826 	 Accuracy: 0.4745762711864407
Delta: 0.0027309321741096214 	  Loss: 1.5922791539878527 	 Accuracy: 0.4745762711864407
Delta: 0.0008483829903923086 	  Loss: 1.5925159437548961 	 Accuracy: 0.47327249022164275
Delta: 0.0016633276283486238 	  Loss: 1.592301549670704 	 Accuracy: 0.4745762711864407
Delta: 0.001004786292368454 	  Loss: 1.5923809664379118 	 Accuracy: 0.4745762711864407
Delta: 0.001880696892307984 	  Loss: 1.5924758204904605 	 Accuracy: 0.4745762711864407
Delta: 2.1584545924087053e-05 	  Loss: 1.592497210220946 	 Accuracy: 0.47327249022164275
Delta: 5.913861558053166e-05 	  Loss: 1.5923592854214366 	 Accuracy: 0.4745762711864407
Delta: 0.0014000851729315813 	  Loss: 1.592312888531863 	 Accuracy: 0.4706649282920469
Delta: 0.001956241707591501 	  Loss: 1.5929169000982202 	 Accuracy: 0.47327249022164275
Delta: 9.127644241192937e-05 	  Loss: 1.5922091370309581 	 Accuracy: 0.47196870925684486
Delta: 0.0027994030354042184 	  Loss: 1.5924941390359468 	 Accuracy: 0.4745762711864407
Delta: 0.0017084350377630571 	  Loss: 1.5922273214991773 	 Accuracy: 0.47327249022164275
Delta: 0.002083669802664546 	  Loss: 1.5922603941257398 	 Accuracy: 0.4758800521512386
Delta: 0.0013107190389687591 	  Loss: 1.5922162654537302 	 Accuracy: 0.4745762711864407
Delta: 0.0008542377556194955 	  Loss: 1.5923044440355172 	 Accuracy: 0.4745762711864407
Delta: 0.0009313904104434426 	  Loss: 1.5922152107313754 	 Accuracy: 0.47327249022164275
Delta: 0.0005544859926745184 	  Loss: 1.5922727571988153 	 Accuracy: 0.4745762711864407
Delta: 0.0017090143449171114 	  Loss: 1.5923106752696805 	 Accuracy: 0.47327249022164275
Delta: 6.970105233452753e-05 	  Loss: 1.5923738159537115 	 Accuracy: 0.4745762711864407
Delta: 6.70860445591929e-05 	  Loss: 1.59225159662801 	 Accuracy: 0.47196870925684486
Delta: 0.002065440880616958 	  Loss: 1.592448968465838 	 Accuracy: 0.47327249022164275
Delta: 0.0007579111943597761 	  Loss: 1.5921388846226894 	 Accuracy: 0.4745762711864407
Delta: 4.80131381242006e-05 	  Loss: 1.5922768105405978 	 Accuracy: 0.4745762711864407
Delta: 0.0009005223171491953 	  Loss: 1.5923202432486405 	 Accuracy: 0.4745762711864407
Delta: 4.7114592552196095e-05 	  Loss: 1.5925522627330593 	 Accuracy: 0.47327249022164275
Delta: 6.169156450547178e-05 	  Loss: 1.5923838713216765 	 Accuracy: 0.4758800521512386
Delta: 0.0015287520593562933 	  Loss: 1.5925538518681863 	 Accuracy: 0.47327249022164275
Delta: 7.581422824086089e-05 	  Loss: 1.592532665135605 	 Accuracy: 0.4706649282920469
Delta: 3.0240567030872667e-05 	  Loss: 1.5924998064914027 	 Accuracy: 0.47327249022164275
Delta: 0.0016129829061875954 	  Loss: 1.5927223910849753 	 Accuracy: 0.4706649282920469
Delta: 0.0024824725889682586 	  Loss: 1.5932135998351549 	 Accuracy: 0.4706649282920469
Delta: 7.584716091642842e-05 	  Loss: 1.593318127586158 	 Accuracy: 0.47327249022164275
Delta: 0.0007861196278872661 	  Loss: 1.593597693715181 	 Accuracy: 0.47196870925684486
Delta: 0.00010532006749023463 	  Loss: 1.5935016212454713 	 Accuracy: 0.4706649282920469
Delta: 8.180142081707929e-05 	  Loss: 1.5933061643908966 	 Accuracy: 0.47196870925684486
Delta: 9.005828676114365e-05 	  Loss: 1.5930768605093877 	 Accuracy: 0.47327249022164275
Delta: 0.0007829933850987497 	  Loss: 1.592543820577305 	 Accuracy: 0.4745762711864407
Delta: 0.0009023299355332186 	  Loss: 1.5927657521661855 	 Accuracy: 0.47327249022164275
Delta: 5.0759309431363026e-05 	  Loss: 1.5925933947336013 	 Accuracy: 0.4745762711864407
Delta: 0.0007332115543266475 	  Loss: 1.592590481021324 	 Accuracy: 0.47327249022164275
Delta: 1.7769991785504094e-05 	  Loss: 1.592612875884433 	 Accuracy: 0.4680573663624511
Delta: 6.740200420802537e-05 	  Loss: 1.592561015627483 	 Accuracy: 0.47327249022164275
Delta: 0.0035869972530256293 	  Loss: 1.593106301201566 	 Accuracy: 0.47327249022164275
Delta: 0.0010373951350392749 	  Loss: 1.593336478571609 	 Accuracy: 0.4667535853976532
Delta: 0.004283036061141819 	  Loss: 1.5926173590118755 	 Accuracy: 0.4706649282920469
Delta: 0.003049524882754858 	  Loss: 1.5921891393103107 	 Accuracy: 0.47196870925684486
Delta: 0.001875855850076626 	  Loss: 1.5922674501226433 	 Accuracy: 0.47196870925684486
Delta: 3.246119502587655e-05 	  Loss: 1.5921807170704996 	 Accuracy: 0.4706649282920469
Delta: 0.002667676909025173 	  Loss: 1.5921325824946662 	 Accuracy: 0.4706649282920469
Delta: 0.0018549889690520332 	  Loss: 1.5919476209378733 	 Accuracy: 0.4706649282920469
Delta: 0.0010895097727546138 	  Loss: 1.592232118489906 	 Accuracy: 0.4667535853976532
Delta: 0.0016283915051671127 	  Loss: 1.592779983739038 	 Accuracy: 0.46936114732724904
Delta: 0.0013837564269164047 	  Loss: 1.59275676527721 	 Accuracy: 0.4680573663624511
Delta: 0.003478728940585917 	  Loss: 1.5921949983125834 	 Accuracy: 0.4706649282920469
Delta: 0.002574592249310552 	  Loss: 1.5927298240369079 	 Accuracy: 0.4706649282920469
Delta: 0.0016890972773277466 	  Loss: 1.592309363366429 	 Accuracy: 0.46936114732724904
Delta: 0.020982751622208386 	  Loss: 2.1478080228120637 	 Accuracy: 0.19947848761408082
Delta: 0.018499176108472064 	  Loss: 2.061545417652944 	 Accuracy: 0.242503259452412
Delta: 0.016618550378602482 	  Loss: 1.9168639510968848 	 Accuracy: 0.28292046936114734
Delta: 0.015089225608721385 	  Loss: 1.7565727162545894 	 Accuracy: 0.3272490221642764
Delta: 0.012544311854760012 	  Loss: 1.6555064793522187 	 Accuracy: 0.33376792698826596
Delta: 0.009805501277498933 	  Loss: 1.6146584172211238 	 Accuracy: 0.3246414602346806
Delta: 0.008488221899934808 	  Loss: 1.5995498503090873 	 Accuracy: 0.318122555410691
Delta: 0.007659988529711016 	  Loss: 1.5922728332427636 	 Accuracy: 0.30378096479791394
Delta: 0.006890653204003014 	  Loss: 1.588210958262862 	 Accuracy: 0.29726205997392435

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0062524286912553455 	  Loss: 1.5860753487623334 	 Accuracy: 0.288135593220339
Delta: 0.005970240591315978 	  Loss: 1.5850197132050208 	 Accuracy: 0.288135593220339
Delta: 0.005224100455070495 	  Loss: 1.5841015217652168 	 Accuracy: 0.2894393741851369
Delta: 0.004829035637644166 	  Loss: 1.5836922341817925 	 Accuracy: 0.288135593220339
Delta: 0.0048696391177610555 	  Loss: 1.5835135584790536 	 Accuracy: 0.28683181225554105
Delta: 0.004151378146399586 	  Loss: 1.5833259137221964 	 Accuracy: 0.288135593220339
Delta: 0.0011394892289178248 	  Loss: 1.5833363551388238 	 Accuracy: 0.288135593220339
Delta: 0.0021736504547148227 	  Loss: 1.5832419929742447 	 Accuracy: 0.288135593220339
Delta: 0.0026094543017246403 	  Loss: 1.583289933730303 	 Accuracy: 0.288135593220339
Delta: 0.0007746733176206482 	  Loss: 1.5833482634674882 	 Accuracy: 0.288135593220339
Delta: 0.0008025997879408273 	  Loss: 1.5833626810283676 	 Accuracy: 0.288135593220339
Delta: 2.441350033032657e-05 	  Loss: 1.5833802071659575 	 Accuracy: 0.28683181225554105
Delta: 0.0005237631262698765 	  Loss: 1.583344180385863 	 Accuracy: 0.288135593220339
Delta: 0.0006485055453683844 	  Loss: 1.583237827105058 	 Accuracy: 0.288135593220339
Delta: 0.0005588018091214777 	  Loss: 1.583323137104927 	 Accuracy: 0.288135593220339
Delta: 6.73949454644567e-05 	  Loss: 1.5832174740553429 	 Accuracy: 0.288135593220339
Delta: 4.493840251721856e-05 	  Loss: 1.5832845380788254 	 Accuracy: 0.288135593220339
Delta: 4.619315694956047e-05 	  Loss: 1.5832638045308987 	 Accuracy: 0.28683181225554105
Delta: 0.0007844671483401497 	  Loss: 1.5832730927073158 	 Accuracy: 0.288135593220339
Delta: 2.4664687129243237e-05 	  Loss: 1.5832992725784871 	 Accuracy: 0.288135593220339
Delta: 1.9379204013089505e-05 	  Loss: 1.5832770739629511 	 Accuracy: 0.28683181225554105
Delta: 1.6468659436064946e-05 	  Loss: 1.583282642218248 	 Accuracy: 0.288135593220339
Delta: 0.0015608555170757853 	  Loss: 1.583283995266334 	 Accuracy: 0.2894393741851369
Delta: 0.0013538987474523622 	  Loss: 1.5832739618913694 	 Accuracy: 0.288135593220339
Delta: 3.926593631668283e-05 	  Loss: 1.5833158925689235 	 Accuracy: 0.288135593220339
Delta: 5.9174538645499406e-05 	  Loss: 1.5832979287068834 	 Accuracy: 0.288135593220339
Delta: 0.0005483207952396857 	  Loss: 1.583253295329966 	 Accuracy: 0.288135593220339
Delta: 0.0012064453436532456 	  Loss: 1.583283108816989 	 Accuracy: 0.28683181225554105
Delta: 0.001982851761595535 	  Loss: 1.583376548169344 	 Accuracy: 0.28552803129074317
Delta: 0.0030789824457092226 	  Loss: 1.583463729229657 	 Accuracy: 0.28552803129074317
Delta: 0.003427805606577474 	  Loss: 1.5835834224632286 	 Accuracy: 0.28552803129074317
Delta: 0.0033404734392282836 	  Loss: 1.5836629698314537 	 Accuracy: 0.28552803129074317
Delta: 0.0026373544013872496 	  Loss: 1.5837540120754485 	 Accuracy: 0.28683181225554105
Delta: 0.0017787366643823273 	  Loss: 1.5834179264997503 	 Accuracy: 0.28683181225554105
Delta: 0.0019427827176488964 	  Loss: 1.5834398667930425 	 Accuracy: 0.28552803129074317
Delta: 3.5345309305775546e-05 	  Loss: 1.583465151696889 	 Accuracy: 0.28552803129074317
Delta: 0.0017312193474206786 	  Loss: 1.5836305628079814 	 Accuracy: 0.28683181225554105
Delta: 0.0013506827891329968 	  Loss: 1.5834953742497422 	 Accuracy: 0.28552803129074317
Delta: 0.0008205823149099924 	  Loss: 1.5835367655390808 	 Accuracy: 0.28552803129074317
Delta: 0.003536046243833033 	  Loss: 1.584357831183202 	 Accuracy: 0.28552803129074317
Delta: 0.0012454385570736218 	  Loss: 1.584422535871375 	 Accuracy: 0.28552803129074317
Delta: 0.0005751183903355652 	  Loss: 1.5843656687760643 	 Accuracy: 0.28552803129074317
Delta: 9.421763912054235e-05 	  Loss: 1.5846504390708467 	 Accuracy: 0.28552803129074317
Delta: 0.0022114435787454175 	  Loss: 1.5845542536373807 	 Accuracy: 0.288135593220339
Delta: 0.005115113672858496 	  Loss: 1.584981108492192 	 Accuracy: 0.28552803129074317
Delta: 0.003049420940917596 	  Loss: 1.5851089064418926 	 Accuracy: 0.2894393741851369
Delta: 0.0059142048701192225 	  Loss: 1.5849560723140983 	 Accuracy: 0.2842242503259452
Delta: 0.003566588041336531 	  Loss: 1.5852930177144695 	 Accuracy: 0.28552803129074317
Delta: 0.0046287323502606365 	  Loss: 1.5857097010769312 	 Accuracy: 0.28552803129074317
Delta: 0.002577131457167624 	  Loss: 1.5858448018032945 	 Accuracy: 0.2842242503259452
Delta: 0.004932838798146364 	  Loss: 1.5859114715293043 	 Accuracy: 0.2816166883963494
Delta: 0.0015942556444089374 	  Loss: 1.5859784669385517 	 Accuracy: 0.2842242503259452
Delta: 0.002375866759966387 	  Loss: 1.585981604211792 	 Accuracy: 0.28552803129074317
Delta: 0.0015900232996644155 	  Loss: 1.5860374591276885 	 Accuracy: 0.28292046936114734
Delta: 0.003468512594552923 	  Loss: 1.5860243942090437 	 Accuracy: 0.28292046936114734
Delta: 0.0017611125737415551 	  Loss: 1.5863109154031372 	 Accuracy: 0.28292046936114734
Delta: 0.0010597661936016245 	  Loss: 1.5863161159004215 	 Accuracy: 0.28292046936114734
Delta: 2.872470331347401e-05 	  Loss: 1.5863243291993405 	 Accuracy: 0.28292046936114734
Delta: 0.002536460962950558 	  Loss: 1.586098183692517 	 Accuracy: 0.28292046936114734
Delta: 0.003582555450014992 	  Loss: 1.5859656569323555 	 Accuracy: 0.28292046936114734
Delta: 0.0005435194611779303 	  Loss: 1.5857766351418774 	 Accuracy: 0.2894393741851369
Delta: 0.004039210013526742 	  Loss: 1.5853921110437135 	 Accuracy: 0.2816166883963494
Delta: 0.0036146324728081407 	  Loss: 1.585475264938205 	 Accuracy: 0.28292046936114734
Delta: 0.003712917980050273 	  Loss: 1.5854674838564864 	 Accuracy: 0.28292046936114734
Delta: 0.002047837572848568 	  Loss: 1.5855722161120247 	 Accuracy: 0.28292046936114734
Delta: 0.0016488075144412383 	  Loss: 1.5857904489828378 	 Accuracy: 0.28292046936114734
Delta: 0.0032527192025855797 	  Loss: 1.585435324252026 	 Accuracy: 0.288135593220339
Delta: 0.0023344562362072273 	  Loss: 1.5854546226406367 	 Accuracy: 0.2842242503259452
Delta: 0.003850394112217808 	  Loss: 1.5852102876311176 	 Accuracy: 0.2842242503259452
Delta: 0.003646931243086969 	  Loss: 1.5857936627814013 	 Accuracy: 0.28292046936114734
Delta: 0.0023082651675505753 	  Loss: 1.5858580606719377 	 Accuracy: 0.28292046936114734
Delta: 0.0006304558299353479 	  Loss: 1.5858063318417643 	 Accuracy: 0.28292046936114734
Delta: 0.0025967845001951266 	  Loss: 1.585788737093862 	 Accuracy: 0.28292046936114734
Delta: 0.0020613428380297965 	  Loss: 1.5858715893373057 	 Accuracy: 0.28292046936114734
Delta: 0.004031422651000782 	  Loss: 1.5861611350641125 	 Accuracy: 0.28292046936114734
Delta: 0.002119142762371301 	  Loss: 1.5860942460393999 	 Accuracy: 0.28292046936114734
Delta: 0.001250155770848038 	  Loss: 1.5861053157109157 	 Accuracy: 0.27509778357235987
Delta: 0.002072235754615139 	  Loss: 1.5862995921358427 	 Accuracy: 0.2842242503259452
Delta: 0.003935485485121215 	  Loss: 1.5864886460630836 	 Accuracy: 0.2842242503259452
Delta: 0.0035400090359019834 	  Loss: 1.5861901637856246 	 Accuracy: 0.2842242503259452
Delta: 0.0034134862246536866 	  Loss: 1.5863914127470875 	 Accuracy: 0.2816166883963494
Delta: 0.0035772618547552596 	  Loss: 1.5860172385405717 	 Accuracy: 0.28292046936114734
Delta: 0.0023206125403601864 	  Loss: 1.586126433674325 	 Accuracy: 0.2790091264667536
Delta: 0.003103228680070504 	  Loss: 1.5854454574962267 	 Accuracy: 0.2816166883963494
Delta: 0.004312903281107088 	  Loss: 1.5861742372839402 	 Accuracy: 0.2816166883963494
Delta: 0.0058692223301434285 	  Loss: 1.5874820938858405 	 Accuracy: 0.2816166883963494
Delta: 0.004769701599083537 	  Loss: 1.5880899727840574 	 Accuracy: 0.28292046936114734
Delta: 0.00290911106286137 	  Loss: 1.5882766739719147 	 Accuracy: 0.2816166883963494
Delta: 0.005905816774465328 	  Loss: 1.5884614927168297 	 Accuracy: 0.28292046936114734
Delta: 0.0036589325491625407 	  Loss: 1.5891242406103727 	 Accuracy: 0.28292046936114734
Delta: 0.005055830476178199 	  Loss: 1.5899484205145222 	 Accuracy: 0.28292046936114734
Delta: 0.021042440017727163 	  Loss: 2.146152248203192 	 Accuracy: 0.20208604954367665
Delta: 0.018486205269643292 	  Loss: 2.0530343957373502 	 Accuracy: 0.26727509778357234
Delta: 0.01636484950633734 	  Loss: 1.9131190211595799 	 Accuracy: 0.2438070404172099
Delta: 0.015855547410869482 	  Loss: 1.7748210077405069 	 Accuracy: 0.22294654498044328
Delta: 0.014529736253454483 	  Loss: 1.6709212183398683 	 Accuracy: 0.22816166883963493
Delta: 0.01126271341895707 	  Loss: 1.6137492051261848 	 Accuracy: 0.23728813559322035
Delta: 0.008394514405381387 	  Loss: 1.5947007800886492 	 Accuracy: 0.25684485006518903
Delta: 0.007552829059730782 	  Loss: 1.588151159440379 	 Accuracy: 0.258148631029987

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006449848881125974 	  Loss: 1.5847346598871137 	 Accuracy: 0.2503259452411995
Delta: 0.005851411594065347 	  Loss: 1.5824829114343415 	 Accuracy: 0.2503259452411995
Delta: 0.00498601641376533 	  Loss: 1.5816895239569901 	 Accuracy: 0.24902216427640156
Delta: 0.004145776378812932 	  Loss: 1.5810942212658177 	 Accuracy: 0.24902216427640156
Delta: 0.003824929029004524 	  Loss: 1.5808123348883798 	 Accuracy: 0.24771838331160365
Delta: 0.001837301822056218 	  Loss: 1.5805709461185373 	 Accuracy: 0.24902216427640156
Delta: 0.001759118594705545 	  Loss: 1.5805478851800105 	 Accuracy: 0.2438070404172099
Delta: 0.0016933027346756678 	  Loss: 1.58015137870083 	 Accuracy: 0.24771838331160365
Delta: 9.760759738900623e-05 	  Loss: 1.5804366122882108 	 Accuracy: 0.24641460234680573
Delta: 5.937519607312655e-05 	  Loss: 1.5805844589704838 	 Accuracy: 0.24771838331160365
Delta: 0.0012904738674560756 	  Loss: 1.5806261256401566 	 Accuracy: 0.24771838331160365
Delta: 0.0013384853849253441 	  Loss: 1.5807417747874446 	 Accuracy: 0.24902216427640156
Delta: 0.0005376970269507065 	  Loss: 1.5806774121000935 	 Accuracy: 0.24902216427640156
Delta: 1.697244463694809e-05 	  Loss: 1.580693721814389 	 Accuracy: 0.24902216427640156
Delta: 0.0005332588790336117 	  Loss: 1.5805838116852708 	 Accuracy: 0.24902216427640156
Delta: 0.000512427249104179 	  Loss: 1.5807042932989455 	 Accuracy: 0.24902216427640156
Delta: 0.0010538093651538839 	  Loss: 1.5806292648492373 	 Accuracy: 0.24902216427640156
Delta: 0.0005630409659802524 	  Loss: 1.5806336005573516 	 Accuracy: 0.24902216427640156
Delta: 4.797213695246521e-05 	  Loss: 1.5807483286862112 	 Accuracy: 0.2503259452411995
Delta: 6.608982958249982e-05 	  Loss: 1.5806549763719164 	 Accuracy: 0.24771838331160365
Delta: 3.9436462354468615e-05 	  Loss: 1.580636615258581 	 Accuracy: 0.2503259452411995
Delta: 0.0010078983905609372 	  Loss: 1.5807010618554127 	 Accuracy: 0.24902216427640156
Delta: 0.0009094682954290229 	  Loss: 1.5806356742541627 	 Accuracy: 0.24902216427640156
Delta: 7.119988173693829e-05 	  Loss: 1.580621307075956 	 Accuracy: 0.24902216427640156
Delta: 5.09222993921781e-05 	  Loss: 1.580697905826987 	 Accuracy: 0.24902216427640156
Delta: 0.0025233397502781112 	  Loss: 1.5807079054191924 	 Accuracy: 0.24771838331160365
Delta: 0.0011540123464225552 	  Loss: 1.5807343142856014 	 Accuracy: 0.24771838331160365
Delta: 0.0016761047721474706 	  Loss: 1.5807421851367867 	 Accuracy: 0.24902216427640156
Delta: 0.0009155568384629201 	  Loss: 1.580718210924805 	 Accuracy: 0.24902216427640156
Delta: 0.0007053893468765425 	  Loss: 1.5806380615430817 	 Accuracy: 0.24771838331160365
Delta: 7.401716258890929e-05 	  Loss: 1.5808104313864284 	 Accuracy: 0.24902216427640156
Delta: 7.138693936156551e-05 	  Loss: 1.5806196315520005 	 Accuracy: 0.2516297262059974
Delta: 0.0036661934471206655 	  Loss: 1.5806004172626535 	 Accuracy: 0.24902216427640156
Delta: 0.0017885548085229688 	  Loss: 1.5805025826863588 	 Accuracy: 0.2516297262059974
Delta: 0.0027061720486345284 	  Loss: 1.580279023894127 	 Accuracy: 0.2516297262059974
Delta: 0.0005314154984037933 	  Loss: 1.5802620864682506 	 Accuracy: 0.2516297262059974
Delta: 0.0019747473389546398 	  Loss: 1.58035051518497 	 Accuracy: 0.2503259452411995
Delta: 0.000124360737011153 	  Loss: 1.5802113770156039 	 Accuracy: 0.2503259452411995
Delta: 0.0007917032678573415 	  Loss: 1.5803666703799295 	 Accuracy: 0.2516297262059974
Delta: 0.003530607676530399 	  Loss: 1.5807891299794012 	 Accuracy: 0.24641460234680573
Delta: 0.002780527724027137 	  Loss: 1.5803091426760485 	 Accuracy: 0.2503259452411995
Delta: 0.0019717426651900587 	  Loss: 1.5806586776678229 	 Accuracy: 0.2516297262059974
Delta: 0.0025120141164652644 	  Loss: 1.5811031098744794 	 Accuracy: 0.2503259452411995
Delta: 0.002400707094823285 	  Loss: 1.5804024948885085 	 Accuracy: 0.2503259452411995
Delta: 0.002540545613393639 	  Loss: 1.5802387004076865 	 Accuracy: 0.24902216427640156
Delta: 0.0044960345594830175 	  Loss: 1.5804182391767103 	 Accuracy: 0.24641460234680573
Delta: 0.0025656908035134054 	  Loss: 1.580425376456939 	 Accuracy: 0.24902216427640156
Delta: 0.003444840648930758 	  Loss: 1.5810134037492962 	 Accuracy: 0.24771838331160365
Delta: 0.002065071586756251 	  Loss: 1.5803518891715234 	 Accuracy: 0.24641460234680573
Delta: 0.0021625007042020967 	  Loss: 1.5805315586647828 	 Accuracy: 0.24771838331160365
Delta: 0.001780316486391547 	  Loss: 1.5800954685369755 	 Accuracy: 0.24771838331160365
Delta: 0.00013245928375415177 	  Loss: 1.5805642528605706 	 Accuracy: 0.24641460234680573
Delta: 0.003646369732685889 	  Loss: 1.5811926419636022 	 Accuracy: 0.24641460234680573
Delta: 0.002246193866274348 	  Loss: 1.5807642771481851 	 Accuracy: 0.24771838331160365
Delta: 0.0034947674632389335 	  Loss: 1.5810487394398973 	 Accuracy: 0.24771838331160365
Delta: 0.003285331697083922 	  Loss: 1.5812349510084445 	 Accuracy: 0.24641460234680573
Delta: 0.002629807993600205 	  Loss: 1.5812606750437403 	 Accuracy: 0.2438070404172099
Delta: 0.0040133367744498325 	  Loss: 1.5817124364915967 	 Accuracy: 0.2503259452411995
Delta: 0.004428698768499425 	  Loss: 1.5807524207325434 	 Accuracy: 0.24771838331160365
Delta: 0.0017651810782849697 	  Loss: 1.580584313932313 	 Accuracy: 0.24771838331160365
Delta: 7.99688595282504e-05 	  Loss: 1.5805814590641445 	 Accuracy: 0.24771838331160365
Delta: 2.62391617612371e-05 	  Loss: 1.5805196117455855 	 Accuracy: 0.24771838331160365
Delta: 2.1665358485913077e-05 	  Loss: 1.5804882678362528 	 Accuracy: 0.24771838331160365
Delta: 0.0017372666610620134 	  Loss: 1.5807882088640604 	 Accuracy: 0.24902216427640156
Delta: 0.0006108165913390243 	  Loss: 1.5806162417117542 	 Accuracy: 0.24641460234680573
Delta: 0.0034173508604705425 	  Loss: 1.5804896433345301 	 Accuracy: 0.24641460234680573
Delta: 0.003432362081769811 	  Loss: 1.5809029462439388 	 Accuracy: 0.24641460234680573
Delta: 0.0009012441880510997 	  Loss: 1.5805478467248069 	 Accuracy: 0.24641460234680573
Delta: 4.473372296380468e-05 	  Loss: 1.580781313961601 	 Accuracy: 0.24641460234680573
Delta: 4.473378437238412e-05 	  Loss: 1.580547649259247 	 Accuracy: 0.24641460234680573
Delta: 0.0007619951712038243 	  Loss: 1.5802656145126122 	 Accuracy: 0.24641460234680573
Delta: 7.156629220437623e-05 	  Loss: 1.580554691773073 	 Accuracy: 0.24641460234680573
Delta: 0.0017208094360325844 	  Loss: 1.5806896186579564 	 Accuracy: 0.24641460234680573
Delta: 0.0032224579509861563 	  Loss: 1.5813078549128479 	 Accuracy: 0.24641460234680573
Delta: 0.0008133267097134934 	  Loss: 1.5813975748063664 	 Accuracy: 0.24641460234680573
Delta: 6.802158155840593e-05 	  Loss: 1.5813404581598558 	 Accuracy: 0.24641460234680573
Delta: 0.0026790702037532564 	  Loss: 1.581293880269286 	 Accuracy: 0.23989569752281617
Delta: 0.002738892260019554 	  Loss: 1.5813505710073628 	 Accuracy: 0.23989569752281617
Delta: 0.002316960154696737 	  Loss: 1.5813837991277024 	 Accuracy: 0.242503259452412
Delta: 0.004074254991742834 	  Loss: 1.5816316325611246 	 Accuracy: 0.242503259452412
Delta: 0.0014921554556582453 	  Loss: 1.5816297100508974 	 Accuracy: 0.242503259452412
Delta: 0.0035094020051119742 	  Loss: 1.5826338925786443 	 Accuracy: 0.24119947848761408
Delta: 0.002482933229544761 	  Loss: 1.582681323650153 	 Accuracy: 0.242503259452412
Delta: 0.0013890251064495173 	  Loss: 1.582324120861384 	 Accuracy: 0.242503259452412
Delta: 0.0015616842043465848 	  Loss: 1.5824827496240434 	 Accuracy: 0.24119947848761408
Delta: 0.003268824373707417 	  Loss: 1.5816234531259097 	 Accuracy: 0.242503259452412
Delta: 0.0024090666543112333 	  Loss: 1.5816698180255462 	 Accuracy: 0.242503259452412
Delta: 0.001373927759808876 	  Loss: 1.581820160389451 	 Accuracy: 0.2438070404172099
Delta: 0.003437614063863083 	  Loss: 1.5807805370371903 	 Accuracy: 0.2438070404172099
Delta: 0.002465279777793476 	  Loss: 1.5813484374760205 	 Accuracy: 0.24511082138200782
Delta: 0.003054031718537276 	  Loss: 1.5805933964872456 	 Accuracy: 0.24119947848761408
Delta: 0.0024791511303912384 	  Loss: 1.5809660388990001 	 Accuracy: 0.242503259452412
Delta: 0.021011673818190194 	  Loss: 2.147075024555636 	 Accuracy: 0.18252933507170796
Delta: 0.018571520212224458 	  Loss: 2.05193347311112 	 Accuracy: 0.25554106910039115
Delta: 0.016944640727116433 	  Loss: 1.8766316964648238 	 Accuracy: 0.3468057366362451
Delta: 0.0144571258639863 	  Loss: 1.7307518599566531 	 Accuracy: 0.37157757496740546
Delta: 0.01248135316776229 	  Loss: 1.6646326842803831 	 Accuracy: 0.3650586701434159
Delta: 0.01094097105236182 	  Loss: 1.6374767494168025 	 Accuracy: 0.3624511082138201
Delta: 0.010144104342830456 	  Loss: 1.6242515644670963 	 Accuracy: 0.35723598435462844
Delta: 0.008264835023851683 	  Loss: 1.618384697128906 	 Accuracy: 0.3428943937418514

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007444892891089992 	  Loss: 1.614895713515613 	 Accuracy: 0.3363754889178618
Delta: 0.006901090260406422 	  Loss: 1.6139223277568995 	 Accuracy: 0.3363754889178618
Delta: 0.005109999652184323 	  Loss: 1.6138964522464312 	 Accuracy: 0.3350717079530639
Delta: 0.004418988303665139 	  Loss: 1.6136535300706203 	 Accuracy: 0.3376792698826597
Delta: 0.003646918013803989 	  Loss: 1.6134694510223582 	 Accuracy: 0.33376792698826596
Delta: 0.0032348032410486364 	  Loss: 1.6134779726228357 	 Accuracy: 0.3363754889178618
Delta: 0.0011052623353976086 	  Loss: 1.6135239498873721 	 Accuracy: 0.3350717079530639
Delta: 0.0021069150188175127 	  Loss: 1.6134793021048792 	 Accuracy: 0.3350717079530639
Delta: 0.0014941476833183268 	  Loss: 1.6134813095137432 	 Accuracy: 0.3350717079530639
Delta: 0.0012957344255877254 	  Loss: 1.6135126082496218 	 Accuracy: 0.3363754889178618
Delta: 0.0017820086894996124 	  Loss: 1.6135259834129982 	 Accuracy: 0.3363754889178618
Delta: 0.002026790975460356 	  Loss: 1.6133632420828463 	 Accuracy: 0.3363754889178618
Delta: 5.773269128947037e-05 	  Loss: 1.6134898762826633 	 Accuracy: 0.3363754889178618
Delta: 0.0015441397494976644 	  Loss: 1.6134395228005802 	 Accuracy: 0.3350717079530639
Delta: 0.0016413779786414253 	  Loss: 1.6135987576232098 	 Accuracy: 0.3350717079530639
Delta: 0.0009596491294124116 	  Loss: 1.613500421322872 	 Accuracy: 0.3350717079530639
Delta: 0.0013827058385571798 	  Loss: 1.6134535018438654 	 Accuracy: 0.3363754889178618
Delta: 0.0012663375717986594 	  Loss: 1.6133878611488135 	 Accuracy: 0.3350717079530639
Delta: 5.2721685790545864e-05 	  Loss: 1.61354623877244 	 Accuracy: 0.33376792698826596
Delta: 6.910622820620164e-05 	  Loss: 1.6135122190549929 	 Accuracy: 0.3363754889178618
Delta: 1.4634572854276194e-05 	  Loss: 1.6135003879195602 	 Accuracy: 0.3350717079530639
Delta: 4.913700944164815e-05 	  Loss: 1.6135111942895113 	 Accuracy: 0.33376792698826596
Delta: 2.030950253583543e-05 	  Loss: 1.6135483318132142 	 Accuracy: 0.33376792698826596
Delta: 0.002001625122624568 	  Loss: 1.6133636873168755 	 Accuracy: 0.3363754889178618
Delta: 9.320464849507598e-05 	  Loss: 1.6135676378851407 	 Accuracy: 0.3363754889178618
Delta: 0.00010899787054810298 	  Loss: 1.613530256686406 	 Accuracy: 0.3350717079530639
Delta: 2.9977427864830694e-05 	  Loss: 1.6134757998975107 	 Accuracy: 0.33376792698826596
Delta: 9.363361937513095e-05 	  Loss: 1.613594567815099 	 Accuracy: 0.33376792698826596
Delta: 5.0523739802183134e-05 	  Loss: 1.6135297155983217 	 Accuracy: 0.3350717079530639
Delta: 0.0005441687831705916 	  Loss: 1.6135464781902766 	 Accuracy: 0.3350717079530639
Delta: 0.0022746995150927265 	  Loss: 1.613452777142506 	 Accuracy: 0.33376792698826596
Delta: 0.0006743041843728316 	  Loss: 1.6135716914621212 	 Accuracy: 0.3350717079530639
Delta: 0.0005689200387314343 	  Loss: 1.6135664379916628 	 Accuracy: 0.3350717079530639
Delta: 8.200121406932606e-05 	  Loss: 1.6134192534596092 	 Accuracy: 0.3350717079530639
Delta: 0.002430698264411986 	  Loss: 1.6136090406416637 	 Accuracy: 0.33376792698826596
Delta: 0.0032720886982603088 	  Loss: 1.6139110767389129 	 Accuracy: 0.3363754889178618
Delta: 0.0030965537418151784 	  Loss: 1.6147449835246888 	 Accuracy: 0.33376792698826596
Delta: 0.0024777711538331005 	  Loss: 1.614504119340538 	 Accuracy: 0.3363754889178618
Delta: 0.0008867421485318465 	  Loss: 1.61470384667189 	 Accuracy: 0.3350717079530639
Delta: 0.0019261678336333291 	  Loss: 1.6147660440504379 	 Accuracy: 0.3363754889178618
Delta: 0.002381390362195774 	  Loss: 1.6145147006589489 	 Accuracy: 0.3350717079530639
Delta: 0.002779501892954586 	  Loss: 1.614001575169695 	 Accuracy: 0.3363754889178618
Delta: 0.004225161496976678 	  Loss: 1.6133173891071708 	 Accuracy: 0.3363754889178618
Delta: 0.0017458288883363455 	  Loss: 1.613677197388081 	 Accuracy: 0.3363754889178618
Delta: 0.0024691529956375963 	  Loss: 1.6140616311876355 	 Accuracy: 0.34028683181225555
Delta: 0.0035880304861920153 	  Loss: 1.6137560244134304 	 Accuracy: 0.3363754889178618
Delta: 0.002214326671769454 	  Loss: 1.6140235276108874 	 Accuracy: 0.3376792698826597
Delta: 0.0016005173127473776 	  Loss: 1.613921141593152 	 Accuracy: 0.3376792698826597
Delta: 0.00496898474343684 	  Loss: 1.6142176264916943 	 Accuracy: 0.3389830508474576
Delta: 0.003251579773870638 	  Loss: 1.6146469290116041 	 Accuracy: 0.34028683181225555
Delta: 0.004618665716533457 	  Loss: 1.6149851550605003 	 Accuracy: 0.3389830508474576
Delta: 0.0009000950822398769 	  Loss: 1.6150666533596152 	 Accuracy: 0.3376792698826597
Delta: 0.004369623539877896 	  Loss: 1.6146009974716096 	 Accuracy: 0.3376792698826597
Delta: 0.001837672329532505 	  Loss: 1.6145215138410247 	 Accuracy: 0.3389830508474576
Delta: 0.00359039712405621 	  Loss: 1.6145156455864988 	 Accuracy: 0.3389830508474576
Delta: 0.0030263547113072845 	  Loss: 1.6144337742246 	 Accuracy: 0.34028683181225555
Delta: 0.003415737877717955 	  Loss: 1.6145808457737678 	 Accuracy: 0.3389830508474576
Delta: 0.0029567712718872093 	  Loss: 1.6142480037324134 	 Accuracy: 0.34028683181225555
Delta: 3.944871611938235e-05 	  Loss: 1.6142043462868647 	 Accuracy: 0.3389830508474576
Delta: 0.0006476353524387514 	  Loss: 1.6144305167315054 	 Accuracy: 0.3389830508474576
Delta: 0.003007181254982693 	  Loss: 1.614584165290781 	 Accuracy: 0.34159061277705344
Delta: 0.003305129094197912 	  Loss: 1.6152567250811707 	 Accuracy: 0.3376792698826597
Delta: 3.4714932128856e-05 	  Loss: 1.6153630244923698 	 Accuracy: 0.3389830508474576
Delta: 0.0032644527742834895 	  Loss: 1.615664053352448 	 Accuracy: 0.34419817470664926
Delta: 7.566792424074689e-05 	  Loss: 1.6154111278191867 	 Accuracy: 0.3389830508474576
Delta: 1.377379466142386e-05 	  Loss: 1.6153725415756184 	 Accuracy: 0.3389830508474576
Delta: 0.005384630711808704 	  Loss: 1.616061177846884 	 Accuracy: 0.3363754889178618
Delta: 0.004142567821782618 	  Loss: 1.6157198292523884 	 Accuracy: 0.3389830508474576
Delta: 0.0015158525869612748 	  Loss: 1.6158371717540205 	 Accuracy: 0.3363754889178618
Delta: 0.0005830310744315502 	  Loss: 1.6159063721556666 	 Accuracy: 0.3363754889178618
Delta: 0.003983045076113454 	  Loss: 1.6160970002614057 	 Accuracy: 0.3376792698826597
Delta: 0.003218789459347168 	  Loss: 1.616224582183749 	 Accuracy: 0.3363754889178618
Delta: 0.0027878648219107423 	  Loss: 1.6163673045093747 	 Accuracy: 0.3363754889178618
Delta: 0.003418261601653486 	  Loss: 1.6164372482946785 	 Accuracy: 0.3363754889178618
Delta: 0.002882779695835727 	  Loss: 1.617029025036027 	 Accuracy: 0.3350717079530639
Delta: 0.00011252365750634635 	  Loss: 1.6165466476226378 	 Accuracy: 0.3363754889178618
Delta: 0.0012109135742465046 	  Loss: 1.6167507391818845 	 Accuracy: 0.3350717079530639
Delta: 0.0016717023106709746 	  Loss: 1.6169642007395568 	 Accuracy: 0.3350717079530639
Delta: 0.002908622827925601 	  Loss: 1.616644167973496 	 Accuracy: 0.3350717079530639
Delta: 0.0033212763993366767 	  Loss: 1.6163634863549097 	 Accuracy: 0.3363754889178618
Delta: 0.002616970988488785 	  Loss: 1.6162890032350008 	 Accuracy: 0.3376792698826597
Delta: 0.0020083465833936748 	  Loss: 1.6164820008475087 	 Accuracy: 0.3363754889178618
Delta: 0.0025873826728747625 	  Loss: 1.6163814277618564 	 Accuracy: 0.33376792698826596
Delta: 0.003985063445044384 	  Loss: 1.6162867181578813 	 Accuracy: 0.3350717079530639
Delta: 0.0022749696310693924 	  Loss: 1.616557836629803 	 Accuracy: 0.33376792698826596
Delta: 0.0039717824477618225 	  Loss: 1.6168482191704105 	 Accuracy: 0.33376792698826596
Delta: 0.001380706024007743 	  Loss: 1.617134557967559 	 Accuracy: 0.3350717079530639
Delta: 0.0010257278111192936 	  Loss: 1.6167429868549126 	 Accuracy: 0.33376792698826596
Delta: 0.0020950405128946884 	  Loss: 1.6167568259365228 	 Accuracy: 0.33376792698826596
Delta: 0.0018023483784344143 	  Loss: 1.6167336906223946 	 Accuracy: 0.33376792698826596
Delta: 0.0007860738114662277 	  Loss: 1.6166457278848543 	 Accuracy: 0.33376792698826596
Delta: 8.475007396842808e-05 	  Loss: 1.6167563894309978 	 Accuracy: 0.33376792698826596
Delta: 0.020982351009373887 	  Loss: 2.146896361966264 	 Accuracy: 0.1981747066492829
Delta: 0.01861734447205971 	  Loss: 2.047537543591717 	 Accuracy: 0.2607561929595828
Delta: 0.01690418218619985 	  Loss: 1.8762694229958756 	 Accuracy: 0.3468057366362451
Delta: 0.015294705623742919 	  Loss: 1.7199314957867813 	 Accuracy: 0.379400260756193
Delta: 0.013366962519542131 	  Loss: 1.6370891976033564 	 Accuracy: 0.3767926988265971
Delta: 0.010786471124121079 	  Loss: 1.6068570966506988 	 Accuracy: 0.3820078226857888
Delta: 0.008652132762751914 	  Loss: 1.5965460034266055 	 Accuracy: 0.37809647979139505

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00757598073283815 	  Loss: 1.591908025790639 	 Accuracy: 0.379400260756193
Delta: 0.006352127472398881 	  Loss: 1.5900509936865548 	 Accuracy: 0.37809647979139505
Delta: 0.005562572658861397 	  Loss: 1.5881743419249332 	 Accuracy: 0.37809647979139505
Delta: 0.004842360048420565 	  Loss: 1.5884249356199185 	 Accuracy: 0.3741851368970013
Delta: 0.004557157677866435 	  Loss: 1.5879142650957592 	 Accuracy: 0.3754889178617992
Delta: 0.002402869798139499 	  Loss: 1.5877382175357544 	 Accuracy: 0.3754889178617992
Delta: 0.0015906229277514122 	  Loss: 1.587741967239534 	 Accuracy: 0.3767926988265971
Delta: 0.002731082581921113 	  Loss: 1.5876058626577072 	 Accuracy: 0.3754889178617992
Delta: 0.0018970264828456205 	  Loss: 1.5874405256004949 	 Accuracy: 0.3754889178617992
Delta: 0.0022220922415020763 	  Loss: 1.5874793812253198 	 Accuracy: 0.3924380704041721
Delta: 0.001359889078351208 	  Loss: 1.5873154219296317 	 Accuracy: 0.3767926988265971
Delta: 5.626570550993305e-05 	  Loss: 1.5872306196017658 	 Accuracy: 0.3767926988265971
Delta: 0.002266783817814016 	  Loss: 1.5871546482752772 	 Accuracy: 0.37809647979139505
Delta: 0.0016321788675667708 	  Loss: 1.587278849577272 	 Accuracy: 0.38070404172099087
Delta: 0.0024382203051776705 	  Loss: 1.5872573835765804 	 Accuracy: 0.379400260756193
Delta: 0.0026282385647353078 	  Loss: 1.587343897687515 	 Accuracy: 0.37809647979139505
Delta: 4.8492408987434105e-05 	  Loss: 1.5873587291182527 	 Accuracy: 0.379400260756193
Delta: 8.070256893433363e-05 	  Loss: 1.5873066309589074 	 Accuracy: 0.3767926988265971
Delta: 0.0013237307537711746 	  Loss: 1.5871977283672227 	 Accuracy: 0.36897001303780963
Delta: 0.00439095392237455 	  Loss: 1.587517732045593 	 Accuracy: 0.37809647979139505
Delta: 0.0023779566911187626 	  Loss: 1.587635689019023 	 Accuracy: 0.3767926988265971
Delta: 0.0029942424148414483 	  Loss: 1.5874293725237798 	 Accuracy: 0.38070404172099087
Delta: 0.001119435768058012 	  Loss: 1.5874209689614918 	 Accuracy: 0.3833116036505867
Delta: 0.004641738328677928 	  Loss: 1.587132648218182 	 Accuracy: 0.379400260756193
Delta: 0.003354524904338349 	  Loss: 1.5868462419388882 	 Accuracy: 0.38070404172099087
Delta: 0.0005320310777084706 	  Loss: 1.586857928434938 	 Accuracy: 0.379400260756193
Delta: 0.0021056415434471645 	  Loss: 1.5867786841227358 	 Accuracy: 0.38070404172099087
Delta: 0.0012608021175464271 	  Loss: 1.586864805335801 	 Accuracy: 0.379400260756193
Delta: 0.0006322296049633939 	  Loss: 1.5868651352755587 	 Accuracy: 0.379400260756193
Delta: 6.009177277448371e-05 	  Loss: 1.5868010960253631 	 Accuracy: 0.379400260756193
Delta: 0.0021349744873817864 	  Loss: 1.5868540891128284 	 Accuracy: 0.379400260756193
Delta: 0.0034700730187195656 	  Loss: 1.5868484343251625 	 Accuracy: 0.379400260756193
Delta: 0.0014579067615214244 	  Loss: 1.5868122346435225 	 Accuracy: 0.3820078226857888
Delta: 3.415926157109051e-05 	  Loss: 1.5868313366599853 	 Accuracy: 0.379400260756193
Delta: 0.002315879981243339 	  Loss: 1.5867685402776233 	 Accuracy: 0.379400260756193
Delta: 0.004173607641565876 	  Loss: 1.586580759387871 	 Accuracy: 0.379400260756193
Delta: 0.0013472412781370265 	  Loss: 1.58703130826112 	 Accuracy: 0.379400260756193
Delta: 0.0024304365542612834 	  Loss: 1.5870417346702583 	 Accuracy: 0.37809647979139505
Delta: 3.8091074773515205e-05 	  Loss: 1.5870698258074554 	 Accuracy: 0.379400260756193
Delta: 0.0015950910499299262 	  Loss: 1.5871025660747136 	 Accuracy: 0.379400260756193
Delta: 0.0033822815566081923 	  Loss: 1.5865839660021652 	 Accuracy: 0.3820078226857888
Delta: 0.003418831147693135 	  Loss: 1.5868251798458557 	 Accuracy: 0.3820078226857888
Delta: 4.8067049812696644e-05 	  Loss: 1.587024328690042 	 Accuracy: 0.3820078226857888
Delta: 0.0007830524534928429 	  Loss: 1.5864861065030877 	 Accuracy: 0.38070404172099087
Delta: 0.0018330185004791434 	  Loss: 1.5873216969325068 	 Accuracy: 0.37809647979139505
Delta: 0.0012015886589450625 	  Loss: 1.5868250394903098 	 Accuracy: 0.37809647979139505
Delta: 0.0014221292343934806 	  Loss: 1.5867404968749645 	 Accuracy: 0.3820078226857888
Delta: 0.0024683608307107478 	  Loss: 1.586594306873073 	 Accuracy: 0.38070404172099087
Delta: 5.887178265505222e-05 	  Loss: 1.5865617483139676 	 Accuracy: 0.38070404172099087
Delta: 0.0052063686635227206 	  Loss: 1.58730601986377 	 Accuracy: 0.38070404172099087
Delta: 0.002209121427354607 	  Loss: 1.5874043560558566 	 Accuracy: 0.379400260756193
Delta: 4.561081844909123e-05 	  Loss: 1.5875465531024249 	 Accuracy: 0.38070404172099087
Delta: 0.0034272754618182434 	  Loss: 1.5872021897026274 	 Accuracy: 0.38070404172099087
Delta: 0.0025470863520358424 	  Loss: 1.5875621726530018 	 Accuracy: 0.3898305084745763
Delta: 0.001084700630512593 	  Loss: 1.5876245789094559 	 Accuracy: 0.3820078226857888
Delta: 0.001047418727768247 	  Loss: 1.5874933939561597 	 Accuracy: 0.38070404172099087
Delta: 8.489176753589068e-05 	  Loss: 1.5876253462820418 	 Accuracy: 0.38070404172099087
Delta: 0.005145979343819097 	  Loss: 1.5885898208216762 	 Accuracy: 0.38070404172099087
Delta: 0.003743886806469471 	  Loss: 1.5887617023054448 	 Accuracy: 0.3820078226857888
Delta: 0.0058100235916646245 	  Loss: 1.5872037851762113 	 Accuracy: 0.37809647979139505
Delta: 0.0017020648247540017 	  Loss: 1.587336341319991 	 Accuracy: 0.379400260756193
Delta: 0.004480377392099279 	  Loss: 1.587596406015686 	 Accuracy: 0.379400260756193
Delta: 0.001242079361448154 	  Loss: 1.5877101423445057 	 Accuracy: 0.37809647979139505
Delta: 0.004766408968499821 	  Loss: 1.5874262458917503 	 Accuracy: 0.37809647979139505
Delta: 0.0029012889035004057 	  Loss: 1.5873217274904041 	 Accuracy: 0.379400260756193
Delta: 0.0008481483907579356 	  Loss: 1.5872932425125614 	 Accuracy: 0.37809647979139505
Delta: 0.0014255177308077434 	  Loss: 1.5874324943398594 	 Accuracy: 0.37809647979139505
Delta: 0.0023233863395118247 	  Loss: 1.5876269593284809 	 Accuracy: 0.3767926988265971
Delta: 0.004949319536523744 	  Loss: 1.5867849710266477 	 Accuracy: 0.3767926988265971
Delta: 0.004225202211531772 	  Loss: 1.5868178839743596 	 Accuracy: 0.37809647979139505
Delta: 0.004157175932111675 	  Loss: 1.5867143132450479 	 Accuracy: 0.37157757496740546
Delta: 0.0030756154910270526 	  Loss: 1.587224508371547 	 Accuracy: 0.3767926988265971
Delta: 0.004634936802317518 	  Loss: 1.5877792787406526 	 Accuracy: 0.3741851368970013
Delta: 0.003051399229400651 	  Loss: 1.587610747002741 	 Accuracy: 0.3741851368970013
Delta: 0.0005037991676369462 	  Loss: 1.5876195065216385 	 Accuracy: 0.3741851368970013
Delta: 0.0011162262912705096 	  Loss: 1.5878074823567734 	 Accuracy: 0.3741851368970013
Delta: 0.0010354921602648889 	  Loss: 1.5876232557154042 	 Accuracy: 0.3728813559322034
Delta: 0.0007505383427026028 	  Loss: 1.5875789377387743 	 Accuracy: 0.3741851368970013
Delta: 0.003066540107055486 	  Loss: 1.5877563908693135 	 Accuracy: 0.3741851368970013
Delta: 0.0010746871755859125 	  Loss: 1.5875429977477498 	 Accuracy: 0.37157757496740546
Delta: 0.004778000748105053 	  Loss: 1.5883905036730028 	 Accuracy: 0.37157757496740546
Delta: 0.0019341639661699967 	  Loss: 1.587841723342255 	 Accuracy: 0.3728813559322034
Delta: 0.0027293969103872294 	  Loss: 1.5880866236639515 	 Accuracy: 0.36766623207301175
Delta: 0.0016353832997301162 	  Loss: 1.5886001546322466 	 Accuracy: 0.37027379400260757
Delta: 0.003749600163169553 	  Loss: 1.58830013555926 	 Accuracy: 0.37027379400260757
Delta: 0.0028366147162106744 	  Loss: 1.5886098977261436 	 Accuracy: 0.37157757496740546
Delta: 0.001542716610458095 	  Loss: 1.5887490989767084 	 Accuracy: 0.37027379400260757
Delta: 0.002835018200393833 	  Loss: 1.5888743361169468 	 Accuracy: 0.37027379400260757
Delta: 0.002706845195776931 	  Loss: 1.588805623387678 	 Accuracy: 0.37027379400260757
Delta: 0.003039155134756788 	  Loss: 1.588747109269392 	 Accuracy: 0.37027379400260757
Delta: 0.0011501563412159876 	  Loss: 1.5883639630561168 	 Accuracy: 0.3728813559322034
Delta: 0.0020536640661362664 	  Loss: 1.5892386548454167 	 Accuracy: 0.37027379400260757
Delta: 0.0023667714001389035 	  Loss: 1.5889051948320287 	 Accuracy: 0.37157757496740546
Delta: 0.02098018753863444 	  Loss: 2.1469649709051093 	 Accuracy: 0.1981747066492829
Delta: 0.01874005879880678 	  Loss: 2.044288086218333 	 Accuracy: 0.24119947848761408
Delta: 0.017119979452127235 	  Loss: 1.8680417392269217 	 Accuracy: 0.2503259452411995
Delta: 0.015468208145538518 	  Loss: 1.7145727093140213 	 Accuracy: 0.25684485006518903
Delta: 0.012617447581947777 	  Loss: 1.6457366168453351 	 Accuracy: 0.2542372881355932
Delta: 0.00944973062113111 	  Loss: 1.624184446232436 	 Accuracy: 0.24641460234680573
Delta: 0.007740877636370391 	  Loss: 1.61752201154675 	 Accuracy: 0.24771838331160365
Delta: 0.007286405629440992 	  Loss: 1.6158145105241848 	 Accuracy: 0.24641460234680573

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0070309333783726245 	  Loss: 1.6148771034194622 	 Accuracy: 0.2438070404172099
Delta: 0.005056782483772937 	  Loss: 1.6145164167576427 	 Accuracy: 0.23989569752281617
Delta: 0.004660381483044992 	  Loss: 1.6142708558066408 	 Accuracy: 0.23989569752281617
Delta: 0.0034282576128080917 	  Loss: 1.614005114096979 	 Accuracy: 0.23989569752281617
Delta: 0.002478105511874779 	  Loss: 1.613945442173783 	 Accuracy: 0.23989569752281617
Delta: 0.0008083076952466271 	  Loss: 1.6139378846836112 	 Accuracy: 0.23989569752281617
Delta: 0.0030689232066525964 	  Loss: 1.6138385406312532 	 Accuracy: 0.242503259452412
Delta: 0.0005622294310971467 	  Loss: 1.6137862151898514 	 Accuracy: 0.23989569752281617
Delta: 3.1904572980817474e-05 	  Loss: 1.6137868374228166 	 Accuracy: 0.23989569752281617
Delta: 0.003280715207100812 	  Loss: 1.6137014625606327 	 Accuracy: 0.23859191655801826
Delta: 0.0014074980267347204 	  Loss: 1.6136879321889015 	 Accuracy: 0.24119947848761408
Delta: 0.002642440894230028 	  Loss: 1.613758555757046 	 Accuracy: 0.23859191655801826
Delta: 0.0015310694092746148 	  Loss: 1.6136430978931857 	 Accuracy: 0.23859191655801826
Delta: 0.0020031486866206516 	  Loss: 1.6137483267359154 	 Accuracy: 0.23859191655801826
Delta: 0.0012591649422661582 	  Loss: 1.6136944452420074 	 Accuracy: 0.23989569752281617
Delta: 0.0016468087951476383 	  Loss: 1.6135863153612582 	 Accuracy: 0.23859191655801826
Delta: 2.1285692784859943e-05 	  Loss: 1.6136592417866868 	 Accuracy: 0.23989569752281617
Delta: 0.002139257752110344 	  Loss: 1.613748451568874 	 Accuracy: 0.23859191655801826
Delta: 0.0023689299236384345 	  Loss: 1.6139491639979417 	 Accuracy: 0.23859191655801826
Delta: 0.0016182891719021012 	  Loss: 1.6136390194752366 	 Accuracy: 0.23989569752281617
Delta: 7.350067374854884e-05 	  Loss: 1.613499523408439 	 Accuracy: 0.23989569752281617
Delta: 6.62584667637036e-05 	  Loss: 1.6137135578004242 	 Accuracy: 0.23989569752281617
Delta: 0.0007477477329456495 	  Loss: 1.6138037416251847 	 Accuracy: 0.23989569752281617
Delta: 0.002112628770641542 	  Loss: 1.6139157281199548 	 Accuracy: 0.23859191655801826
Delta: 0.0007841176468227947 	  Loss: 1.613552575778675 	 Accuracy: 0.23989569752281617
Delta: 0.0008537310648698078 	  Loss: 1.6137035841924512 	 Accuracy: 0.23989569752281617
Delta: 0.0030922955393592956 	  Loss: 1.6139933212592448 	 Accuracy: 0.23989569752281617
Delta: 0.004354401375963433 	  Loss: 1.61408747807623 	 Accuracy: 0.24119947848761408
Delta: 0.002781594277819559 	  Loss: 1.6140092084557311 	 Accuracy: 0.23989569752281617
Delta: 0.0041897911356215565 	  Loss: 1.613641946844345 	 Accuracy: 0.23859191655801826
Delta: 0.00321165496721852 	  Loss: 1.6136078853010996 	 Accuracy: 0.23989569752281617
Delta: 0.005170621471631761 	  Loss: 1.613848092935025 	 Accuracy: 0.23989569752281617
Delta: 0.003899326052692705 	  Loss: 1.61379650971922 	 Accuracy: 0.23989569752281617
Delta: 0.001846101536014332 	  Loss: 1.6138936363299503 	 Accuracy: 0.23989569752281617
Delta: 0.002547831178443551 	  Loss: 1.6139112759485825 	 Accuracy: 0.24119947848761408
Delta: 0.001940830439194318 	  Loss: 1.61389190453842 	 Accuracy: 0.242503259452412
Delta: 0.0005625535097669359 	  Loss: 1.6136496602831207 	 Accuracy: 0.24119947848761408
Delta: 0.0021688628763228608 	  Loss: 1.6140024329618023 	 Accuracy: 0.23989569752281617
Delta: 0.0005415569923525431 	  Loss: 1.6138115103841466 	 Accuracy: 0.23989569752281617
Delta: 0.0009066676351533143 	  Loss: 1.6137189221010135 	 Accuracy: 0.242503259452412
Delta: 0.002126874792167276 	  Loss: 1.6136650499920608 	 Accuracy: 0.242503259452412
Delta: 0.0005682014992732354 	  Loss: 1.6138408044188637 	 Accuracy: 0.24119947848761408
Delta: 0.001133091410299964 	  Loss: 1.613797261129484 	 Accuracy: 0.242503259452412
Delta: 7.38953200377378e-05 	  Loss: 1.613668370575226 	 Accuracy: 0.24119947848761408
Delta: 0.0014113224287147967 	  Loss: 1.6135424621593193 	 Accuracy: 0.24119947848761408
Delta: 0.00141312744582287 	  Loss: 1.6135713782225272 	 Accuracy: 0.23989569752281617
Delta: 0.003924807708833784 	  Loss: 1.6136090312097875 	 Accuracy: 0.23989569752281617
Delta: 0.0037524079050198626 	  Loss: 1.6137308025576522 	 Accuracy: 0.24119947848761408
Delta: 0.002161119715635428 	  Loss: 1.613866196443846 	 Accuracy: 0.242503259452412
Delta: 0.004365613264739849 	  Loss: 1.6142382451791377 	 Accuracy: 0.242503259452412
Delta: 0.003528709523518697 	  Loss: 1.6144792021986976 	 Accuracy: 0.242503259452412
Delta: 0.0035240638007816385 	  Loss: 1.6144590631003177 	 Accuracy: 0.24119947848761408
Delta: 0.0012936417517321556 	  Loss: 1.6141973813139008 	 Accuracy: 0.242503259452412
Delta: 0.0008284834413165623 	  Loss: 1.6145659435956443 	 Accuracy: 0.24511082138200782
Delta: 0.0015274394416972786 	  Loss: 1.614429245485043 	 Accuracy: 0.23859191655801826
Delta: 0.0030498648174623897 	  Loss: 1.6146748180011996 	 Accuracy: 0.24119947848761408
Delta: 0.0037836620362323905 	  Loss: 1.6143817306446004 	 Accuracy: 0.24119947848761408
Delta: 0.002148465218727669 	  Loss: 1.6144704871948106 	 Accuracy: 0.23989569752281617
Delta: 0.0016077023488415272 	  Loss: 1.6146221345504896 	 Accuracy: 0.24119947848761408
Delta: 0.0012509606948066492 	  Loss: 1.6142287498611063 	 Accuracy: 0.23989569752281617
Delta: 0.0022255964340563107 	  Loss: 1.6142612907315264 	 Accuracy: 0.23989569752281617
Delta: 0.001186238730016975 	  Loss: 1.6142223864437533 	 Accuracy: 0.24119947848761408
Delta: 0.0036367301998244546 	  Loss: 1.6143821356120658 	 Accuracy: 0.23598435462842243
Delta: 0.003178927430542868 	  Loss: 1.6142739645995159 	 Accuracy: 0.24119947848761408
Delta: 7.80792708999279e-05 	  Loss: 1.6145081673097381 	 Accuracy: 0.24119947848761408
Delta: 0.0011997601883506077 	  Loss: 1.6145360500576955 	 Accuracy: 0.24119947848761408
Delta: 0.0019325752307935466 	  Loss: 1.6145219920145129 	 Accuracy: 0.23859191655801826
Delta: 0.00502171293325021 	  Loss: 1.6148906071632223 	 Accuracy: 0.24119947848761408
Delta: 0.0037441398496171423 	  Loss: 1.6153686219340455 	 Accuracy: 0.24119947848761408
Delta: 0.004262401764807102 	  Loss: 1.6156306078262368 	 Accuracy: 0.23859191655801826
Delta: 0.0035062569677147743 	  Loss: 1.616009853031401 	 Accuracy: 0.23859191655801826
Delta: 0.0021744217224214796 	  Loss: 1.6156751478593407 	 Accuracy: 0.23859191655801826
Delta: 0.002757270804632708 	  Loss: 1.6158070230704935 	 Accuracy: 0.23989569752281617
Delta: 0.0019228278081706402 	  Loss: 1.6155818326672335 	 Accuracy: 0.23859191655801826
Delta: 0.004819501431235538 	  Loss: 1.6149660580750294 	 Accuracy: 0.23859191655801826
Delta: 0.004841262000764145 	  Loss: 1.6157219358792134 	 Accuracy: 0.23468057366362452
Delta: 0.001829487962761277 	  Loss: 1.615697665494988 	 Accuracy: 0.23859191655801826
Delta: 0.0022438351352988663 	  Loss: 1.6156709496143917 	 Accuracy: 0.23728813559322035
Delta: 0.002302636850688743 	  Loss: 1.615706633640555 	 Accuracy: 0.23728813559322035
Delta: 0.003956402532623259 	  Loss: 1.615553959189514 	 Accuracy: 0.23859191655801826
Delta: 0.0036597417503750856 	  Loss: 1.6155026245932422 	 Accuracy: 0.23859191655801826
Delta: 0.0012997995547509213 	  Loss: 1.6155883095544916 	 Accuracy: 0.23859191655801826
Delta: 0.0037457850493574484 	  Loss: 1.615767728341654 	 Accuracy: 0.23859191655801826
Delta: 0.0017517348709330692 	  Loss: 1.61561709533692 	 Accuracy: 0.23859191655801826
Delta: 0.003279448468200058 	  Loss: 1.6164827277957887 	 Accuracy: 0.23859191655801826
Delta: 0.0016819831509738959 	  Loss: 1.6163035829099406 	 Accuracy: 0.23859191655801826
Delta: 0.0010630438402862462 	  Loss: 1.6160609391458067 	 Accuracy: 0.242503259452412
Delta: 0.004212517135751322 	  Loss: 1.616907271390342 	 Accuracy: 0.242503259452412
Delta: 0.002750406195290451 	  Loss: 1.616632186594849 	 Accuracy: 0.23859191655801826
Delta: 0.0007829234539359851 	  Loss: 1.616783414753788 	 Accuracy: 0.23859191655801826
Delta: 0.0038852530758224056 	  Loss: 1.616928560700614 	 Accuracy: 0.23989569752281617
Delta: 0.003565695102421789 	  Loss: 1.6166902689861473 	 Accuracy: 0.24119947848761408
Delta: 0.020920653644886586 	  Loss: 2.147038474559963 	 Accuracy: 0.20208604954367665
Delta: 0.018857109230073263 	  Loss: 2.0437875127829352 	 Accuracy: 0.23728813559322035
Delta: 0.0173523854727687 	  Loss: 1.8553242943209352 	 Accuracy: 0.3376792698826597
Delta: 0.01524894306332891 	  Loss: 1.7117061328382932 	 Accuracy: 0.35853976531942633
Delta: 0.012459035385915774 	  Loss: 1.6520230534349092 	 Accuracy: 0.3624511082138201
Delta: 0.009944813054148995 	  Loss: 1.6315103196842626 	 Accuracy: 0.35071707953063885
Delta: 0.008862450222611212 	  Loss: 1.6241596529917364 	 Accuracy: 0.34028683181225555

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008048188632734864 	  Loss: 1.620881070456889 	 Accuracy: 0.3428943937418514
Delta: 0.005414947198525369 	  Loss: 1.6197071177692013 	 Accuracy: 0.34419817470664926
Delta: 0.0038745985184912286 	  Loss: 1.619533445655044 	 Accuracy: 0.34159061277705344
Delta: 0.004450118968826837 	  Loss: 1.6194021412474926 	 Accuracy: 0.3363754889178618
Delta: 0.0017250132870556755 	  Loss: 1.619380845194593 	 Accuracy: 0.3389830508474576
Delta: 0.002262062457851713 	  Loss: 1.6195850784226224 	 Accuracy: 0.3389830508474576
Delta: 0.0016505295651990423 	  Loss: 1.6194130666355664 	 Accuracy: 0.3376792698826597
Delta: 0.0037451061472391156 	  Loss: 1.61958263086937 	 Accuracy: 0.3376792698826597
Delta: 0.001052573387250489 	  Loss: 1.6195769569201537 	 Accuracy: 0.3389830508474576
Delta: 0.0018472315303671306 	  Loss: 1.619308448630501 	 Accuracy: 0.3389830508474576
Delta: 0.002188809338032888 	  Loss: 1.619894683969861 	 Accuracy: 0.3389830508474576
Delta: 0.0005370043861703548 	  Loss: 1.6194312752441131 	 Accuracy: 0.34028683181225555
Delta: 6.25097787215009e-05 	  Loss: 1.6191612533850306 	 Accuracy: 0.3389830508474576
Delta: 6.628545052707556e-05 	  Loss: 1.6194043231624078 	 Accuracy: 0.34028683181225555
Delta: 0.002142599476155008 	  Loss: 1.6194626198446267 	 Accuracy: 0.3389830508474576
Delta: 0.0007215566664940383 	  Loss: 1.619508286069392 	 Accuracy: 0.3389830508474576
Delta: 0.000937959572135054 	  Loss: 1.6201187054921378 	 Accuracy: 0.34028683181225555
Delta: 0.001488195179008625 	  Loss: 1.6197340927225907 	 Accuracy: 0.34159061277705344
Delta: 0.0042902612735666425 	  Loss: 1.6196415691730102 	 Accuracy: 0.34028683181225555
Delta: 0.0031479464250781844 	  Loss: 1.619423637520111 	 Accuracy: 0.3389830508474576
Delta: 0.0024023125092804635 	  Loss: 1.6194133715914862 	 Accuracy: 0.3376792698826597
Delta: 0.0012338004115287375 	  Loss: 1.6193236489058753 	 Accuracy: 0.3389830508474576
Delta: 0.0017739610728384455 	  Loss: 1.6198684059177093 	 Accuracy: 0.3376792698826597
Delta: 0.001013758488636406 	  Loss: 1.6199672036016255 	 Accuracy: 0.3389830508474576
Delta: 5.783932978056017e-05 	  Loss: 1.6196589570167683 	 Accuracy: 0.3376792698826597
Delta: 0.0007604489871694199 	  Loss: 1.619581109381571 	 Accuracy: 0.3389830508474576
Delta: 0.0027712707633486687 	  Loss: 1.6194342832415156 	 Accuracy: 0.34028683181225555
Delta: 0.001333588651120097 	  Loss: 1.619498040640872 	 Accuracy: 0.34028683181225555
Delta: 0.004024717566267253 	  Loss: 1.6194913606800514 	 Accuracy: 0.3350717079530639
Delta: 0.002162384845837146 	  Loss: 1.6195793647173342 	 Accuracy: 0.3494132985658409
Delta: 0.002977593288353914 	  Loss: 1.6195743663691362 	 Accuracy: 0.3389830508474576
Delta: 0.0013540273425294957 	  Loss: 1.6191960108594885 	 Accuracy: 0.3376792698826597
Delta: 0.004757931390668663 	  Loss: 1.619534205661631 	 Accuracy: 0.3389830508474576
Delta: 0.004037990754782335 	  Loss: 1.6188032032070196 	 Accuracy: 0.3376792698826597
Delta: 0.004082699387952736 	  Loss: 1.6192987331641466 	 Accuracy: 0.3376792698826597
Delta: 0.0010458263230279639 	  Loss: 1.6192245219510664 	 Accuracy: 0.3376792698826597
Delta: 0.0010381483697326727 	  Loss: 1.6192306047654934 	 Accuracy: 0.3389830508474576
Delta: 0.0017287301223953661 	  Loss: 1.6194166129681284 	 Accuracy: 0.33376792698826596
Delta: 0.0034903397266177185 	  Loss: 1.6190947317133364 	 Accuracy: 0.3376792698826597
Delta: 0.0022863139941995585 	  Loss: 1.6192649861468622 	 Accuracy: 0.3376792698826597
Delta: 0.0008674104851987 	  Loss: 1.6191649033425248 	 Accuracy: 0.3363754889178618
Delta: 2.4476311907486348e-05 	  Loss: 1.6191446819271924 	 Accuracy: 0.3350717079530639
Delta: 3.613273597455802e-05 	  Loss: 1.6191233050138738 	 Accuracy: 0.3324641460234681
Delta: 0.0005410029366973959 	  Loss: 1.619188284934919 	 Accuracy: 0.3363754889178618
Delta: 0.0035546011980538764 	  Loss: 1.619111000227579 	 Accuracy: 0.34028683181225555
Delta: 0.003077689072609747 	  Loss: 1.619379371973331 	 Accuracy: 0.3363754889178618
Delta: 0.0016286231713394687 	  Loss: 1.619429185079132 	 Accuracy: 0.3376792698826597
Delta: 0.002342782845263146 	  Loss: 1.6189954435038518 	 Accuracy: 0.3389830508474576
Delta: 0.00455011176298709 	  Loss: 1.6188475622396452 	 Accuracy: 0.3376792698826597
Delta: 0.004262400809639966 	  Loss: 1.618809503371895 	 Accuracy: 0.3376792698826597
Delta: 0.0016086342763497268 	  Loss: 1.618589227056572 	 Accuracy: 0.3363754889178618
Delta: 0.001355013057942878 	  Loss: 1.6185659465128055 	 Accuracy: 0.3363754889178618
Delta: 0.003299011397861445 	  Loss: 1.6185192882835733 	 Accuracy: 0.3363754889178618
Delta: 0.0029663618487316716 	  Loss: 1.6184591162777004 	 Accuracy: 0.3363754889178618
Delta: 0.002865966821239861 	  Loss: 1.6187417726225855 	 Accuracy: 0.3376792698826597
Delta: 0.002574052883612292 	  Loss: 1.618459511895249 	 Accuracy: 0.3376792698826597
Delta: 0.0024817760795842244 	  Loss: 1.6181156743434557 	 Accuracy: 0.3363754889178618
Delta: 0.0025154222875202474 	  Loss: 1.6185080347786704 	 Accuracy: 0.3376792698826597
Delta: 0.0022196151525198673 	  Loss: 1.6185598429765955 	 Accuracy: 0.34159061277705344
Delta: 0.003980410614881324 	  Loss: 1.61855133447614 	 Accuracy: 0.34028683181225555
Delta: 0.0030776671936596917 	  Loss: 1.618853715327461 	 Accuracy: 0.3389830508474576
Delta: 0.0018140821910799644 	  Loss: 1.6186200196741862 	 Accuracy: 0.3376792698826597
Delta: 0.0016428834356812816 	  Loss: 1.6185991475937542 	 Accuracy: 0.3376792698826597
Delta: 0.002696899863582525 	  Loss: 1.618241931525718 	 Accuracy: 0.3389830508474576
Delta: 0.0018576306958613571 	  Loss: 1.6182780141888613 	 Accuracy: 0.3376792698826597
Delta: 0.0037480579460024473 	  Loss: 1.6181902895955125 	 Accuracy: 0.3376792698826597
Delta: 0.0018990466257590823 	  Loss: 1.618337066346561 	 Accuracy: 0.3376792698826597
Delta: 0.0006103005447504362 	  Loss: 1.6181912190691292 	 Accuracy: 0.3376792698826597
Delta: 0.0032371260087514023 	  Loss: 1.6183175520983542 	 Accuracy: 0.3389830508474576
Delta: 0.001677223318535181 	  Loss: 1.6183099920989976 	 Accuracy: 0.3389830508474576
Delta: 0.00399849114557965 	  Loss: 1.6181343226345914 	 Accuracy: 0.3376792698826597
Delta: 0.001029987139997736 	  Loss: 1.61822059499718 	 Accuracy: 0.3376792698826597
Delta: 0.0005717139329819307 	  Loss: 1.6181308929414193 	 Accuracy: 0.3376792698826597
Delta: 0.00246701412354041 	  Loss: 1.6181924933567922 	 Accuracy: 0.3389830508474576
Delta: 0.0034887578653694388 	  Loss: 1.6181160230884384 	 Accuracy: 0.3376792698826597
Delta: 0.003100179377792075 	  Loss: 1.6181995188885128 	 Accuracy: 0.34028683181225555
Delta: 0.002818115508465935 	  Loss: 1.6181888038876064 	 Accuracy: 0.34028683181225555
Delta: 0.004686202804198393 	  Loss: 1.6188024531832763 	 Accuracy: 0.3350717079530639
Delta: 0.003858656591287538 	  Loss: 1.619130113400756 	 Accuracy: 0.3363754889178618
Delta: 0.002453412659748098 	  Loss: 1.618750102603594 	 Accuracy: 0.33376792698826596
Delta: 0.0009163086717968517 	  Loss: 1.6186964307735208 	 Accuracy: 0.3376792698826597
Delta: 0.0005291228513407123 	  Loss: 1.618787780678534 	 Accuracy: 0.3363754889178618
Delta: 0.001475003896699691 	  Loss: 1.6187160354065009 	 Accuracy: 0.3376792698826597
Delta: 0.003209586582051409 	  Loss: 1.6187298931566168 	 Accuracy: 0.3376792698826597
Delta: 0.0024059748860762436 	  Loss: 1.6188018511171365 	 Accuracy: 0.3350717079530639
Delta: 0.0032890397130700606 	  Loss: 1.6190014808315718 	 Accuracy: 0.3376792698826597
Delta: 0.0014096612272685844 	  Loss: 1.6192292034860571 	 Accuracy: 0.3363754889178618
Delta: 0.001401794836588192 	  Loss: 1.6188873230826775 	 Accuracy: 0.3363754889178618
Delta: 0.0033768990232138744 	  Loss: 1.618848502549056 	 Accuracy: 0.3324641460234681
Delta: 0.0029784977678619425 	  Loss: 1.6193361678850873 	 Accuracy: 0.3350717079530639
Delta: 0.003514509815778674 	  Loss: 1.6196134830797315 	 Accuracy: 0.3350717079530639
Delta: 0.0029818863012856015 	  Loss: 1.6193815187093734 	 Accuracy: 0.3363754889178618
Delta: 0.0014303894419337956 	  Loss: 1.6192579111117982 	 Accuracy: 0.3350717079530639
Delta: 0.020983071918450565 	  Loss: 2.1472048931604637 	 Accuracy: 0.20078226857887874
Delta: 0.01864794310597208 	  Loss: 2.040259051101894 	 Accuracy: 0.2803129074315515
Delta: 0.0172915754696703 	  Loss: 1.8515841142524776 	 Accuracy: 0.3741851368970013
Delta: 0.015080008898965162 	  Loss: 1.7063434112906999 	 Accuracy: 0.4067796610169492
Delta: 0.013281926804626901 	  Loss: 1.6436940457207734 	 Accuracy: 0.39113428943937417
Delta: 0.011018063068357915 	  Loss: 1.624275730275363 	 Accuracy: 0.37027379400260757

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009417916049536823 	  Loss: 1.6186861210529209 	 Accuracy: 0.37809647979139505
Delta: 0.006755855795991126 	  Loss: 1.616799706685146 	 Accuracy: 0.36897001303780963
Delta: 0.005859648139704297 	  Loss: 1.6163131861594104 	 Accuracy: 0.363754889178618
Delta: 0.005378909677294504 	  Loss: 1.6155440833200627 	 Accuracy: 0.3650586701434159
Delta: 0.003583212278809899 	  Loss: 1.6155459464952924 	 Accuracy: 0.3650586701434159
Delta: 0.002039695207436316 	  Loss: 1.6155813967916512 	 Accuracy: 0.363754889178618
Delta: 0.0012978176620300807 	  Loss: 1.6155754500806316 	 Accuracy: 0.363754889178618
Delta: 0.003424691769722226 	  Loss: 1.6158766233469346 	 Accuracy: 0.363754889178618
Delta: 0.0007432366126192053 	  Loss: 1.6157652121296304 	 Accuracy: 0.3624511082138201
Delta: 0.002947850578551705 	  Loss: 1.6159178407272294 	 Accuracy: 0.3624511082138201
Delta: 0.0023960669778248563 	  Loss: 1.6154819497407287 	 Accuracy: 0.3650586701434159
Delta: 0.0014800258515695504 	  Loss: 1.6153895827033329 	 Accuracy: 0.3650586701434159
Delta: 5.072395254438821e-05 	  Loss: 1.615509774579186 	 Accuracy: 0.363754889178618
Delta: 0.0008329333281096497 	  Loss: 1.6154996304001252 	 Accuracy: 0.363754889178618
Delta: 0.0009941308073643418 	  Loss: 1.6158178039502595 	 Accuracy: 0.3624511082138201
Delta: 0.0009961396557870684 	  Loss: 1.615384224150841 	 Accuracy: 0.3663624511082138
Delta: 0.0019134702549497334 	  Loss: 1.615340313567173 	 Accuracy: 0.3650586701434159
Delta: 0.0019174312797303585 	  Loss: 1.615452361631105 	 Accuracy: 0.363754889178618
Delta: 1.8446172065211677e-05 	  Loss: 1.6155531675376182 	 Accuracy: 0.3663624511082138
Delta: 5.870250726948347e-05 	  Loss: 1.6154919907630967 	 Accuracy: 0.3650586701434159
Delta: 8.372018498748521e-05 	  Loss: 1.6157104901971393 	 Accuracy: 0.3663624511082138
Delta: 0.002260587524122115 	  Loss: 1.6158925939481599 	 Accuracy: 0.363754889178618
Delta: 0.001675927666093195 	  Loss: 1.615472182895437 	 Accuracy: 0.363754889178618
Delta: 0.0005611997543778025 	  Loss: 1.6155611149959719 	 Accuracy: 0.3624511082138201
Delta: 0.0024307393141742976 	  Loss: 1.615797202671514 	 Accuracy: 0.363754889178618
Delta: 0.0021175691457126057 	  Loss: 1.6151330393731418 	 Accuracy: 0.363754889178618
Delta: 0.0005009220123578039 	  Loss: 1.6151006131301506 	 Accuracy: 0.3650586701434159
Delta: 0.003290194450133882 	  Loss: 1.6154163672313433 	 Accuracy: 0.363754889178618
Delta: 0.0006446526686329918 	  Loss: 1.6154588721043055 	 Accuracy: 0.3663624511082138
Delta: 0.0027196220264089632 	  Loss: 1.6158131608001698 	 Accuracy: 0.3650586701434159
Delta: 3.2826231350584524e-05 	  Loss: 1.6158227985084985 	 Accuracy: 0.3650586701434159
Delta: 0.0022329523581262035 	  Loss: 1.615786284598297 	 Accuracy: 0.3650586701434159
Delta: 0.0005261372202932047 	  Loss: 1.6157918338087154 	 Accuracy: 0.3624511082138201
Delta: 0.0040287482823917545 	  Loss: 1.616073882571461 	 Accuracy: 0.3650586701434159
Delta: 9.189348546391802e-05 	  Loss: 1.6158928398379522 	 Accuracy: 0.363754889178618
Delta: 0.0037202541686290162 	  Loss: 1.6157695395885396 	 Accuracy: 0.3663624511082138
Delta: 0.005084979163331471 	  Loss: 1.615997625742077 	 Accuracy: 0.3650586701434159
Delta: 0.0005290803650841171 	  Loss: 1.6159108165750613 	 Accuracy: 0.3650586701434159
Delta: 0.002280354820053378 	  Loss: 1.6163110082766519 	 Accuracy: 0.3650586701434159
Delta: 0.0008779180987317965 	  Loss: 1.6160293168733215 	 Accuracy: 0.3663624511082138
Delta: 0.004152527131467961 	  Loss: 1.6156717039623019 	 Accuracy: 0.3624511082138201
Delta: 0.002535599933126467 	  Loss: 1.615880985299239 	 Accuracy: 0.3650586701434159
Delta: 0.0035365130616202335 	  Loss: 1.6158308618711732 	 Accuracy: 0.3624511082138201
Delta: 0.0024903565989742964 	  Loss: 1.6163333609008195 	 Accuracy: 0.363754889178618
Delta: 0.0012825688429540594 	  Loss: 1.616027022215613 	 Accuracy: 0.363754889178618
Delta: 0.003469005503724705 	  Loss: 1.6166299223696305 	 Accuracy: 0.3624511082138201
Delta: 0.0018856314123510333 	  Loss: 1.616157167423756 	 Accuracy: 0.3624511082138201
Delta: 0.003046904990307941 	  Loss: 1.6157838170758654 	 Accuracy: 0.3650586701434159
Delta: 0.004183270024873172 	  Loss: 1.6150638666614068 	 Accuracy: 0.3663624511082138
Delta: 0.0014188794921369341 	  Loss: 1.6151490561724866 	 Accuracy: 0.3663624511082138
Delta: 0.0031531475257565657 	  Loss: 1.6160350834549848 	 Accuracy: 0.3650586701434159
Delta: 0.0013707155317344722 	  Loss: 1.6154152883019215 	 Accuracy: 0.3650586701434159
Delta: 0.0013758432979789495 	  Loss: 1.6151706989652799 	 Accuracy: 0.3650586701434159
Delta: 0.0023174230658259153 	  Loss: 1.6151720303585893 	 Accuracy: 0.35723598435462844
Delta: 0.0012752117093777753 	  Loss: 1.6152778659313043 	 Accuracy: 0.3650586701434159
Delta: 0.0020426011005568964 	  Loss: 1.6151413340030993 	 Accuracy: 0.3650586701434159
Delta: 0.0035465608139283416 	  Loss: 1.6152428467512174 	 Accuracy: 0.3663624511082138
Delta: 0.0021043189831962314 	  Loss: 1.615356256716927 	 Accuracy: 0.36766623207301175
Delta: 0.0048924881267003355 	  Loss: 1.6150997869792383 	 Accuracy: 0.36897001303780963
Delta: 0.0026132742899041784 	  Loss: 1.6144988340439634 	 Accuracy: 0.3663624511082138
Delta: 0.0031448961124942343 	  Loss: 1.6154815807570684 	 Accuracy: 0.3663624511082138
Delta: 0.003939631442307271 	  Loss: 1.6154081070134503 	 Accuracy: 0.3663624511082138
Delta: 1.885786553067178e-05 	  Loss: 1.615406906776179 	 Accuracy: 0.36766623207301175
Delta: 9.902041770773563e-06 	  Loss: 1.6153938412107056 	 Accuracy: 0.36766623207301175
Delta: 3.4113956924530165e-05 	  Loss: 1.615401956643501 	 Accuracy: 0.3650586701434159
Delta: 0.0020029794888077723 	  Loss: 1.616168069515097 	 Accuracy: 0.36766623207301175
Delta: 0.004865302575597527 	  Loss: 1.6167428285739307 	 Accuracy: 0.363754889178618
Delta: 0.0047408569514845724 	  Loss: 1.6158136284696247 	 Accuracy: 0.363754889178618
Delta: 0.0023850912683177554 	  Loss: 1.615651002959216 	 Accuracy: 0.363754889178618
Delta: 0.0007059458210404835 	  Loss: 1.6156428922795723 	 Accuracy: 0.3650586701434159
Delta: 0.004186965386720357 	  Loss: 1.6156436373421765 	 Accuracy: 0.363754889178618
Delta: 0.0014688421692892618 	  Loss: 1.615871575607101 	 Accuracy: 0.3650586701434159
Delta: 0.002647887292528682 	  Loss: 1.6157023266330712 	 Accuracy: 0.3663624511082138
Delta: 0.0006010643533522081 	  Loss: 1.6159298534303999 	 Accuracy: 0.3650586701434159
Delta: 0.000995335386371421 	  Loss: 1.6159416762215542 	 Accuracy: 0.37157757496740546
Delta: 0.0041416649347124765 	  Loss: 1.6173116875131939 	 Accuracy: 0.3650586701434159
Delta: 0.0042779489529561985 	  Loss: 1.617231099518119 	 Accuracy: 0.3624511082138201
Delta: 0.0031783864211786823 	  Loss: 1.6164076373697713 	 Accuracy: 0.3650586701434159
Delta: 0.0025015208477958983 	  Loss: 1.6163534262001757 	 Accuracy: 0.363754889178618
Delta: 0.003575153189692936 	  Loss: 1.6169509069670225 	 Accuracy: 0.363754889178618
Delta: 0.006422081911438874 	  Loss: 1.6146372182213589 	 Accuracy: 0.36114732724902215
Delta: 0.0017462747140118526 	  Loss: 1.6147511897541444 	 Accuracy: 0.3650586701434159
Delta: 0.003757264426209144 	  Loss: 1.615498009225516 	 Accuracy: 0.3663624511082138
Delta: 0.0026216652060051687 	  Loss: 1.6154736480465406 	 Accuracy: 0.3650586701434159
Delta: 0.003829758935696209 	  Loss: 1.614643773834442 	 Accuracy: 0.3663624511082138
Delta: 0.0008272850846193139 	  Loss: 1.6147213180617148 	 Accuracy: 0.36766623207301175
Delta: 0.00010537212124654416 	  Loss: 1.6147211875804248 	 Accuracy: 0.36766623207301175
Delta: 0.0032036190029612857 	  Loss: 1.6149676256562822 	 Accuracy: 0.36766623207301175
Delta: 0.0005820776414357609 	  Loss: 1.614838860126882 	 Accuracy: 0.36766623207301175
Delta: 9.70714210572719e-05 	  Loss: 1.6145493825639954 	 Accuracy: 0.36766623207301175
Delta: 0.0028115848753373462 	  Loss: 1.6150729868046683 	 Accuracy: 0.36766623207301175
Delta: 0.0012673252775713588 	  Loss: 1.6149906964721632 	 Accuracy: 0.36766623207301175
Delta: 0.005190943346798315 	  Loss: 1.6150951082251752 	 Accuracy: 0.363754889178618
Delta: 0.002167504716948232 	  Loss: 1.61525320845021 	 Accuracy: 0.36766623207301175
Delta: 0.021091509575932168 	  Loss: 2.1461187347661657 	 Accuracy: 0.2151238591916558
Delta: 0.01878941403683067 	  Loss: 2.0276322696329583 	 Accuracy: 0.2620599739243807
Delta: 0.017446235674484924 	  Loss: 1.8340097487628706 	 Accuracy: 0.32073011734028684
Delta: 0.014874697183833727 	  Loss: 1.7083484275072929 	 Accuracy: 0.34159061277705344
Delta: 0.012574500617421021 	  Loss: 1.6640123183548146 	 Accuracy: 0.32073011734028684
Delta: 0.010255836908791557 	  Loss: 1.6523209597405883 	 Accuracy: 0.31421121251629724

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008310220308530725 	  Loss: 1.6493617726619396 	 Accuracy: 0.3116036505867014
Delta: 0.006785750673811917 	  Loss: 1.6485765366785043 	 Accuracy: 0.3155149934810952
Delta: 0.005913867098847785 	  Loss: 1.6484697378669844 	 Accuracy: 0.31421121251629724
Delta: 0.004407214701744583 	  Loss: 1.6478357856300225 	 Accuracy: 0.3116036505867014
Delta: 0.0024778851684718354 	  Loss: 1.647777116269204 	 Accuracy: 0.3116036505867014
Delta: 0.002064859385797177 	  Loss: 1.6477691506836876 	 Accuracy: 0.31029986962190353
Delta: 0.0012342558070652782 	  Loss: 1.6477079255460612 	 Accuracy: 0.3116036505867014
Delta: 0.0026022745019313323 	  Loss: 1.6476134379883591 	 Accuracy: 0.3116036505867014
Delta: 0.0015850944393639987 	  Loss: 1.6475715024247912 	 Accuracy: 0.31029986962190353
Delta: 0.0014414982416197067 	  Loss: 1.6474568805547172 	 Accuracy: 0.3116036505867014
Delta: 0.0014285591754393235 	  Loss: 1.6476663929923236 	 Accuracy: 0.31029986962190353
Delta: 0.00657627200687903 	  Loss: 1.6474796886445722 	 Accuracy: 0.31290743155149936
Delta: 0.005062811627806576 	  Loss: 1.6472019882040978 	 Accuracy: 0.31290743155149936
Delta: 0.004243416910845679 	  Loss: 1.646956467807553 	 Accuracy: 0.3116036505867014
Delta: 0.002770492082190689 	  Loss: 1.6467622300688771 	 Accuracy: 0.3076923076923077
Delta: 0.004049911328388599 	  Loss: 1.6474531037781535 	 Accuracy: 0.3116036505867014
Delta: 0.0028258734697300587 	  Loss: 1.647109074092896 	 Accuracy: 0.3116036505867014
Delta: 0.001998315086643301 	  Loss: 1.6468203874388916 	 Accuracy: 0.3116036505867014
Delta: 0.0008461982308656231 	  Loss: 1.6467272400661497 	 Accuracy: 0.31421121251629724
Delta: 0.004639189206484847 	  Loss: 1.6479078185039961 	 Accuracy: 0.31290743155149936
Delta: 0.0021516804035197554 	  Loss: 1.647638024072285 	 Accuracy: 0.3116036505867014
Delta: 0.0014098543358927497 	  Loss: 1.6477044713500693 	 Accuracy: 0.31290743155149936
Delta: 0.0013440324659702875 	  Loss: 1.6471836730977898 	 Accuracy: 0.31290743155149936
Delta: 0.0013331749964998745 	  Loss: 1.6476328907958333 	 Accuracy: 0.31029986962190353
Delta: 0.002625257448173338 	  Loss: 1.6479490480669883 	 Accuracy: 0.3089960886571056
Delta: 0.00485195844021258 	  Loss: 1.647346179033752 	 Accuracy: 0.3116036505867014
Delta: 0.003381866162224632 	  Loss: 1.6479916830396264 	 Accuracy: 0.31029986962190353
Delta: 0.0019526035684686567 	  Loss: 1.6475424162415409 	 Accuracy: 0.3089960886571056
Delta: 4.561363546806349e-05 	  Loss: 1.647517713871517 	 Accuracy: 0.3116036505867014
Delta: 0.0014620933806956148 	  Loss: 1.6473023112917944 	 Accuracy: 0.3116036505867014
Delta: 0.004242733897082528 	  Loss: 1.6474524038807123 	 Accuracy: 0.3116036505867014
Delta: 0.001217318119783009 	  Loss: 1.6475144469373304 	 Accuracy: 0.3089960886571056
Delta: 0.002053551211428377 	  Loss: 1.647645163181295 	 Accuracy: 0.3116036505867014
Delta: 0.0038220637423755726 	  Loss: 1.647395383953584 	 Accuracy: 0.3116036505867014
Delta: 0.00245986313839366 	  Loss: 1.647255764891841 	 Accuracy: 0.3116036505867014
Delta: 0.0034032279624806885 	  Loss: 1.6474350214112592 	 Accuracy: 0.3116036505867014
Delta: 0.001725121964230571 	  Loss: 1.6474238642573784 	 Accuracy: 0.31029986962190353
Delta: 0.004114617320950686 	  Loss: 1.6473744932215209 	 Accuracy: 0.3116036505867014
Delta: 0.001999128672712243 	  Loss: 1.6471902586027523 	 Accuracy: 0.3116036505867014
Delta: 0.002243357579571143 	  Loss: 1.6470846862523056 	 Accuracy: 0.3116036505867014
Delta: 0.0024791434977093573 	  Loss: 1.6473019493966357 	 Accuracy: 0.31421121251629724
Delta: 0.0025005129239583815 	  Loss: 1.6474037030522939 	 Accuracy: 0.31290743155149936
Delta: 0.0013702698956086358 	  Loss: 1.6473557746369722 	 Accuracy: 0.31029986962190353
Delta: 0.0018723471737211116 	  Loss: 1.6472914833522923 	 Accuracy: 0.3116036505867014
Delta: 0.0037416561332134037 	  Loss: 1.6473932453234068 	 Accuracy: 0.3116036505867014
Delta: 0.0017945336202805353 	  Loss: 1.6472984999904872 	 Accuracy: 0.3116036505867014
Delta: 0.0012886647600253772 	  Loss: 1.6474356515344675 	 Accuracy: 0.3076923076923077
Delta: 0.003083341257938173 	  Loss: 1.6476217361193986 	 Accuracy: 0.31421121251629724
Delta: 0.0036905475424800467 	  Loss: 1.6473258550527965 	 Accuracy: 0.31681877444589307
Delta: 0.002360784670831325 	  Loss: 1.6473540528235606 	 Accuracy: 0.3116036505867014
Delta: 0.004110895732727847 	  Loss: 1.6471395680626801 	 Accuracy: 0.3116036505867014
Delta: 0.0035983790754362775 	  Loss: 1.6472526240837158 	 Accuracy: 0.31290743155149936
Delta: 0.0015634180823235271 	  Loss: 1.6474104866209833 	 Accuracy: 0.3116036505867014
Delta: 0.0017044129677056031 	  Loss: 1.6475378987196474 	 Accuracy: 0.3155149934810952
Delta: 0.0028381661406448808 	  Loss: 1.6476879489434606 	 Accuracy: 0.3076923076923077
Delta: 0.003704887125701239 	  Loss: 1.6477295680120752 	 Accuracy: 0.31421121251629724
Delta: 0.006265301782121178 	  Loss: 1.6495294852559215 	 Accuracy: 0.3155149934810952
Delta: 0.006142624230039341 	  Loss: 1.6481784562371238 	 Accuracy: 0.318122555410691
Delta: 0.006225324981792606 	  Loss: 1.649495882388789 	 Accuracy: 0.318122555410691
Delta: 0.003711032360639958 	  Loss: 1.6494746835036942 	 Accuracy: 0.31681877444589307
Delta: 0.0028864127136481684 	  Loss: 1.6496017399069498 	 Accuracy: 0.3155149934810952
Delta: 0.0043383409494335 	  Loss: 1.6497050779256295 	 Accuracy: 0.31421121251629724
Delta: 0.003293674891668794 	  Loss: 1.6497617162049005 	 Accuracy: 0.3155149934810952
Delta: 0.005640183245184375 	  Loss: 1.6501481271558545 	 Accuracy: 0.31681877444589307
Delta: 0.005417895935478058 	  Loss: 1.6508134494241384 	 Accuracy: 0.31290743155149936
Delta: 0.005373262008584951 	  Loss: 1.6508260265834966 	 Accuracy: 0.31681877444589307
Delta: 0.0032009104534332145 	  Loss: 1.6506950397821967 	 Accuracy: 0.31421121251629724
Delta: 0.004767934516787311 	  Loss: 1.6499424278278536 	 Accuracy: 0.31421121251629724
Delta: 0.0035499533604869222 	  Loss: 1.6500745878393501 	 Accuracy: 0.31421121251629724
Delta: 0.0030662503084473553 	  Loss: 1.6498478600998647 	 Accuracy: 0.3155149934810952
Delta: 0.002334224560657387 	  Loss: 1.6498686212747664 	 Accuracy: 0.31421121251629724
Delta: 0.0048385053003033125 	  Loss: 1.6501821540385955 	 Accuracy: 0.31290743155149936
Delta: 0.0056838861365143736 	  Loss: 1.6503710905025677 	 Accuracy: 0.31290743155149936
Delta: 0.0039941864846218395 	  Loss: 1.650145388938388 	 Accuracy: 0.3155149934810952
Delta: 0.003650884730419739 	  Loss: 1.6500581003560546 	 Accuracy: 0.31421121251629724
Delta: 0.0010056833262477405 	  Loss: 1.6500248804235396 	 Accuracy: 0.31421121251629724
Delta: 0.004299049890188313 	  Loss: 1.6508028584764738 	 Accuracy: 0.31290743155149936
Delta: 0.0023249829377819282 	  Loss: 1.6508157589615262 	 Accuracy: 0.31290743155149936
Delta: 0.0025170842796798515 	  Loss: 1.6507502225193353 	 Accuracy: 0.31290743155149936
Delta: 0.0048310311254243 	  Loss: 1.650303228707172 	 Accuracy: 0.3116036505867014
Delta: 0.0005391717715231307 	  Loss: 1.6500991627620012 	 Accuracy: 0.32073011734028684
Delta: 0.003840308241107999 	  Loss: 1.650004592426827 	 Accuracy: 0.31290743155149936
Delta: 0.0026858278372584366 	  Loss: 1.6503739780081537 	 Accuracy: 0.3116036505867014
Delta: 0.0035717213441103257 	  Loss: 1.6506522713567922 	 Accuracy: 0.31290743155149936
Delta: 0.002804238523598652 	  Loss: 1.6508252550831903 	 Accuracy: 0.31290743155149936
Delta: 0.003906118792551778 	  Loss: 1.6503790924725146 	 Accuracy: 0.31290743155149936
Delta: 0.004203482128618502 	  Loss: 1.650030362171971 	 Accuracy: 0.31290743155149936
Delta: 0.0020086273956457373 	  Loss: 1.6500225197610137 	 Accuracy: 0.31290743155149936
Delta: 8.015244147006954e-05 	  Loss: 1.6499666815254133 	 Accuracy: 0.3155149934810952
Delta: 0.002644895375933472 	  Loss: 1.6501225362997611 	 Accuracy: 0.31290743155149936
Delta: 0.003912412727985399 	  Loss: 1.6499340176054307 	 Accuracy: 0.31421121251629724
Delta: 0.003932503239524755 	  Loss: 1.6501842307215138 	 Accuracy: 0.3155149934810952
Delta: 2.0608187379533673e-05 	  Loss: 1.6501575987957349 	 Accuracy: 0.31421121251629724
Delta: 0.0031841214368108074 	  Loss: 1.6499929351800144 	 Accuracy: 0.31681877444589307
Delta: 0.021150530681639853 	  Loss: 2.1464279339577983 	 Accuracy: 0.20730117340286833
Delta: 0.018646194368247587 	  Loss: 2.036087743740173 	 Accuracy: 0.22294654498044328
Delta: 0.017580056846051052 	  Loss: 1.8437664615324998 	 Accuracy: 0.23728813559322035
Delta: 0.01565010106800783 	  Loss: 1.7074015636027324 	 Accuracy: 0.24641460234680573
Delta: 0.012216061139989461 	  Loss: 1.656538718624126 	 Accuracy: 0.25945241199478486
Delta: 0.009016439149496298 	  Loss: 1.6446335447999942 	 Accuracy: 0.2529335071707953

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00697570859619358 	  Loss: 1.6419245268733675 	 Accuracy: 0.2516297262059974
Delta: 0.00486193776641275 	  Loss: 1.6410663281229305 	 Accuracy: 0.2516297262059974
Delta: 0.004141799214358986 	  Loss: 1.641018754663233 	 Accuracy: 0.2503259452411995
Delta: 0.003736948916214037 	  Loss: 1.6411200172680878 	 Accuracy: 0.2503259452411995
Delta: 0.002806012220622571 	  Loss: 1.6409037383070901 	 Accuracy: 0.24771838331160365
Delta: 0.002109375383197282 	  Loss: 1.6406670958718201 	 Accuracy: 0.24902216427640156
Delta: 2.5436197728776916e-05 	  Loss: 1.6407185752432645 	 Accuracy: 0.24902216427640156
Delta: 0.0006636479332943041 	  Loss: 1.6408947694699745 	 Accuracy: 0.2503259452411995
Delta: 0.001692815434503976 	  Loss: 1.6409658262315805 	 Accuracy: 0.24902216427640156
Delta: 0.0006307730482347074 	  Loss: 1.6409619643103457 	 Accuracy: 0.24902216427640156
Delta: 7.726857157984336e-06 	  Loss: 1.640941985628948 	 Accuracy: 0.2503259452411995
Delta: 0.001978389708636004 	  Loss: 1.6412566996524456 	 Accuracy: 0.24902216427640156
Delta: 0.0008019524236197863 	  Loss: 1.641270480330792 	 Accuracy: 0.2503259452411995
Delta: 0.0008754795931560058 	  Loss: 1.641238272030626 	 Accuracy: 0.2503259452411995
Delta: 0.0035813314571806706 	  Loss: 1.6413683599325717 	 Accuracy: 0.2503259452411995
Delta: 0.0032259032083325335 	  Loss: 1.6413961518715092 	 Accuracy: 0.2503259452411995
Delta: 0.004068309940301572 	  Loss: 1.6418543294820962 	 Accuracy: 0.2503259452411995
Delta: 0.002065807152265545 	  Loss: 1.6419173563533223 	 Accuracy: 0.2516297262059974
Delta: 0.0031880471373333364 	  Loss: 1.6423334501012454 	 Accuracy: 0.2516297262059974
Delta: 0.0025866151967118825 	  Loss: 1.6423495238051473 	 Accuracy: 0.2516297262059974
Delta: 0.0020253006988439743 	  Loss: 1.642938136971945 	 Accuracy: 0.2503259452411995
Delta: 0.003056046319088427 	  Loss: 1.6423017774456639 	 Accuracy: 0.2503259452411995
Delta: 0.0027314780800599633 	  Loss: 1.6418890597650058 	 Accuracy: 0.2503259452411995
Delta: 6.426998874271803e-05 	  Loss: 1.6417647328598692 	 Accuracy: 0.2503259452411995
Delta: 0.002578601609002687 	  Loss: 1.6417197222457207 	 Accuracy: 0.2503259452411995
Delta: 0.001572854219576674 	  Loss: 1.6417962798787753 	 Accuracy: 0.24902216427640156
Delta: 0.0022760928064283308 	  Loss: 1.6415463534664383 	 Accuracy: 0.2503259452411995
Delta: 0.0022887789342840486 	  Loss: 1.6416262157515753 	 Accuracy: 0.2503259452411995
Delta: 0.0020852860702306013 	  Loss: 1.6416108127418236 	 Accuracy: 0.2503259452411995
Delta: 0.005388778416817225 	  Loss: 1.6420305010787066 	 Accuracy: 0.2333767926988266
Delta: 0.0028053296746228763 	  Loss: 1.642186371669148 	 Accuracy: 0.2516297262059974
Delta: 0.0010845275800576044 	  Loss: 1.642463930700947 	 Accuracy: 0.2516297262059974
Delta: 0.0036922382605060226 	  Loss: 1.6436861253725583 	 Accuracy: 0.24641460234680573
Delta: 0.0009859455037302864 	  Loss: 1.6424936727848132 	 Accuracy: 0.24902216427640156
Delta: 0.0031578955715996808 	  Loss: 1.6421934938894593 	 Accuracy: 0.2516297262059974
Delta: 0.005120845010711068 	  Loss: 1.6424120613626896 	 Accuracy: 0.24771838331160365
Delta: 0.003255759270310197 	  Loss: 1.6417089167879546 	 Accuracy: 0.24771838331160365
Delta: 0.000798564610469634 	  Loss: 1.6416800725016087 	 Accuracy: 0.24771838331160365
Delta: 0.0025919809833692404 	  Loss: 1.6410044034626365 	 Accuracy: 0.24771838331160365
Delta: 0.000111651875356711 	  Loss: 1.6413946375721575 	 Accuracy: 0.24771838331160365
Delta: 0.0017139967790965886 	  Loss: 1.6417389315782371 	 Accuracy: 0.24771838331160365
Delta: 0.0019133626656159487 	  Loss: 1.6409771617011346 	 Accuracy: 0.24771838331160365
Delta: 0.0031262956622805814 	  Loss: 1.6412354881284232 	 Accuracy: 0.24641460234680573
Delta: 0.0023032471278662415 	  Loss: 1.6410385498822748 	 Accuracy: 0.24511082138200782
Delta: 0.002515272992413405 	  Loss: 1.6407858858554327 	 Accuracy: 0.24771838331160365
Delta: 0.0006906053012660596 	  Loss: 1.6406527226647578 	 Accuracy: 0.24902216427640156
Delta: 0.0036654468597047754 	  Loss: 1.6412911311478204 	 Accuracy: 0.24902216427640156
Delta: 0.003813573043072339 	  Loss: 1.64059645127487 	 Accuracy: 0.24641460234680573
Delta: 0.003165072829522144 	  Loss: 1.6406639069062467 	 Accuracy: 0.24771838331160365
Delta: 0.0007081305005259516 	  Loss: 1.6411328163654475 	 Accuracy: 0.24641460234680573
Delta: 0.0048567399733478065 	  Loss: 1.640952991245879 	 Accuracy: 0.24641460234680573
Delta: 0.0035216660754360356 	  Loss: 1.6406359341658552 	 Accuracy: 0.24641460234680573
Delta: 0.002294445989637269 	  Loss: 1.6408971209943024 	 Accuracy: 0.24511082138200782
Delta: 0.004606027592728078 	  Loss: 1.6404313399693273 	 Accuracy: 0.24511082138200782
Delta: 0.004885341053275402 	  Loss: 1.6399984302149027 	 Accuracy: 0.242503259452412
Delta: 0.0044223709128186125 	  Loss: 1.6394485521517073 	 Accuracy: 0.242503259452412
Delta: 0.0026193964231940913 	  Loss: 1.6390706348512183 	 Accuracy: 0.24641460234680573
Delta: 0.003360180185426886 	  Loss: 1.6397235562961323 	 Accuracy: 0.2438070404172099
Delta: 0.0005940462282807914 	  Loss: 1.639458746091977 	 Accuracy: 0.242503259452412
Delta: 0.0027710618314199203 	  Loss: 1.6391792757734662 	 Accuracy: 0.242503259452412
Delta: 0.0008680502778110417 	  Loss: 1.6392841753574567 	 Accuracy: 0.242503259452412
Delta: 0.0042616925884406895 	  Loss: 1.6396494934436097 	 Accuracy: 0.2438070404172099
Delta: 0.003935272953195561 	  Loss: 1.638459786060924 	 Accuracy: 0.24771838331160365
Delta: 0.004019922803003131 	  Loss: 1.6393891658565078 	 Accuracy: 0.24511082138200782
Delta: 0.0035269469395628767 	  Loss: 1.6386354176395164 	 Accuracy: 0.24511082138200782
Delta: 0.0020098789939231245 	  Loss: 1.6392005210362504 	 Accuracy: 0.24511082138200782
Delta: 0.0008563162554061718 	  Loss: 1.6392827837296537 	 Accuracy: 0.24511082138200782
Delta: 0.0029817183510152693 	  Loss: 1.639274148233309 	 Accuracy: 0.24511082138200782
Delta: 0.004772647479938476 	  Loss: 1.6405930650377838 	 Accuracy: 0.2438070404172099
Delta: 0.0032100686802354677 	  Loss: 1.638777665011975 	 Accuracy: 0.2438070404172099
Delta: 0.0017584050598488394 	  Loss: 1.6393049936980064 	 Accuracy: 0.2438070404172099
Delta: 0.004951977005167532 	  Loss: 1.6406343252918936 	 Accuracy: 0.2438070404172099
Delta: 0.004637020010057119 	  Loss: 1.6386000088945458 	 Accuracy: 0.2438070404172099
Delta: 0.00414094544856074 	  Loss: 1.63869329229178 	 Accuracy: 0.2438070404172099
Delta: 0.0054554311252057956 	  Loss: 1.6390906651480228 	 Accuracy: 0.2438070404172099
Delta: 0.00389284678417242 	  Loss: 1.639454939130819 	 Accuracy: 0.2438070404172099
Delta: 0.0029780735993960696 	  Loss: 1.6398931775557468 	 Accuracy: 0.2438070404172099
Delta: 0.0039903607272172995 	  Loss: 1.639132378917111 	 Accuracy: 0.2438070404172099
Delta: 0.003038895418303353 	  Loss: 1.6391488866045094 	 Accuracy: 0.242503259452412
Delta: 0.0020448868283748714 	  Loss: 1.6389664461878182 	 Accuracy: 0.2438070404172099
Delta: 0.0044470113570363855 	  Loss: 1.6389405542232942 	 Accuracy: 0.24511082138200782
Delta: 0.0036683307146696533 	  Loss: 1.6386787762954578 	 Accuracy: 0.24641460234680573
Delta: 0.004335727083897097 	  Loss: 1.6391522814231192 	 Accuracy: 0.2438070404172099
Delta: 0.0026862784161621194 	  Loss: 1.6391910853074088 	 Accuracy: 0.242503259452412
Delta: 0.004246021649020298 	  Loss: 1.6393286826851332 	 Accuracy: 0.242503259452412
Delta: 0.0005719053501751653 	  Loss: 1.6392762213269365 	 Accuracy: 0.242503259452412
Delta: 0.0023857528686527817 	  Loss: 1.639007317658527 	 Accuracy: 0.242503259452412
Delta: 0.0019821426092391137 	  Loss: 1.63926232895199 	 Accuracy: 0.2438070404172099
Delta: 0.0025568228424993006 	  Loss: 1.639799022303945 	 Accuracy: 0.24771838331160365
Delta: 0.004421571193155352 	  Loss: 1.6386869047759558 	 Accuracy: 0.242503259452412
Delta: 0.0026043530055777685 	  Loss: 1.6382957751282536 	 Accuracy: 0.23989569752281617
Delta: 0.004364111283811846 	  Loss: 1.637935873153742 	 Accuracy: 0.242503259452412
Delta: 0.004660219762071702 	  Loss: 1.637801980069173 	 Accuracy: 0.2438070404172099
Delta: 0.0013901752364198258 	  Loss: 1.6377393867824135 	 Accuracy: 0.242503259452412
Delta: 0.021075165385581927 	  Loss: 2.1473571910267735 	 Accuracy: 0.2033898305084746
Delta: 0.019260744690072936 	  Loss: 2.017187183958013 	 Accuracy: 0.38461538461538464
Delta: 0.01738504423243792 	  Loss: 1.7813367152117507 	 Accuracy: 0.4771838331160365
Delta: 0.014885807854157268 	  Loss: 1.6585599278370755 	 Accuracy: 0.500651890482399
Delta: 0.011754860597838744 	  Loss: 1.6186615519341274 	 Accuracy: 0.48239895697522817

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009512488470027693 	  Loss: 1.608093638250788 	 Accuracy: 0.48239895697522817
Delta: 0.007070811333201166 	  Loss: 1.6046866401764381 	 Accuracy: 0.4758800521512386
Delta: 0.005392964319832486 	  Loss: 1.604774838763463 	 Accuracy: 0.47979139504563234
Delta: 0.004029065470541038 	  Loss: 1.6049317754899062 	 Accuracy: 0.4784876140808344
Delta: 0.002113087685344263 	  Loss: 1.6050829344797282 	 Accuracy: 0.4784876140808344
Delta: 0.002621446591334858 	  Loss: 1.6050101486470663 	 Accuracy: 0.4771838331160365
Delta: 0.0029949946707033704 	  Loss: 1.6051216408028388 	 Accuracy: 0.4810951760104302
Delta: 0.0011483116986371255 	  Loss: 1.6051399523713317 	 Accuracy: 0.4771838331160365
Delta: 0.002295251606293513 	  Loss: 1.6052347230180597 	 Accuracy: 0.4784876140808344
Delta: 0.002517371285571201 	  Loss: 1.605275464220737 	 Accuracy: 0.4784876140808344
Delta: 0.003342977812048594 	  Loss: 1.605371932626865 	 Accuracy: 0.4784876140808344
Delta: 0.0015494444556315898 	  Loss: 1.6052958007801248 	 Accuracy: 0.47979139504563234
Delta: 0.00471884268207316 	  Loss: 1.6045120978193772 	 Accuracy: 0.4771838331160365
Delta: 0.0029956760615828556 	  Loss: 1.6046263198849573 	 Accuracy: 0.4784876140808344
Delta: 0.0023562275111824213 	  Loss: 1.604496063687681 	 Accuracy: 0.4784876140808344
Delta: 0.0014100595050775212 	  Loss: 1.6050389865513008 	 Accuracy: 0.4771838331160365
Delta: 0.002747805923673677 	  Loss: 1.6046932049768248 	 Accuracy: 0.47979139504563234
Delta: 0.003927859097078006 	  Loss: 1.6037103033707756 	 Accuracy: 0.47979139504563234
Delta: 0.002077358625497131 	  Loss: 1.6043142327386204 	 Accuracy: 0.4784876140808344
Delta: 0.004533816577994303 	  Loss: 1.6050324565386775 	 Accuracy: 0.4771838331160365
Delta: 0.004314299942549 	  Loss: 1.605242156782882 	 Accuracy: 0.4784876140808344
Delta: 0.002716247102006039 	  Loss: 1.6049284664237042 	 Accuracy: 0.47979139504563234
Delta: 0.004093443942101014 	  Loss: 1.6045939990006586 	 Accuracy: 0.4784876140808344
Delta: 0.0022767250076909554 	  Loss: 1.6048669295399114 	 Accuracy: 0.4784876140808344
Delta: 0.0015547576690830413 	  Loss: 1.604933446100022 	 Accuracy: 0.4784876140808344
Delta: 0.0015548450332952153 	  Loss: 1.6048217671732226 	 Accuracy: 0.47979139504563234
Delta: 0.0008334433588544077 	  Loss: 1.6048211472891238 	 Accuracy: 0.4784876140808344
Delta: 6.454627566901107e-05 	  Loss: 1.6047661182947224 	 Accuracy: 0.4758800521512386
Delta: 0.001642271730606961 	  Loss: 1.6050868545427406 	 Accuracy: 0.47979139504563234
Delta: 0.001370420480952585 	  Loss: 1.604554016572866 	 Accuracy: 0.47979139504563234
Delta: 0.002344274996027503 	  Loss: 1.6043694687370076 	 Accuracy: 0.4784876140808344
Delta: 0.0029591551924225 	  Loss: 1.6051145652773848 	 Accuracy: 0.4771838331160365
Delta: 0.0031583587250256402 	  Loss: 1.6047878086002272 	 Accuracy: 0.48239895697522817
Delta: 0.0028229271811960528 	  Loss: 1.6051654322448992 	 Accuracy: 0.4784876140808344
Delta: 3.5735923701100555e-05 	  Loss: 1.6051466613371912 	 Accuracy: 0.4784876140808344
Delta: 0.0015175320523000751 	  Loss: 1.6051425361118206 	 Accuracy: 0.4810951760104302
Delta: 0.0008971554586043318 	  Loss: 1.6053600845123617 	 Accuracy: 0.47979139504563234
Delta: 0.002263276111671164 	  Loss: 1.6049900069659073 	 Accuracy: 0.47979139504563234
Delta: 0.004163667761641051 	  Loss: 1.6045827488750009 	 Accuracy: 0.47196870925684486
Delta: 0.005867005286623065 	  Loss: 1.6052954392511216 	 Accuracy: 0.4758800521512386
Delta: 0.004099705546552704 	  Loss: 1.6060158044714365 	 Accuracy: 0.4771838331160365
Delta: 0.0011607653029441915 	  Loss: 1.6063155198795875 	 Accuracy: 0.4784876140808344
Delta: 0.004383082356681317 	  Loss: 1.606058369240853 	 Accuracy: 0.4784876140808344
Delta: 0.0008288797317857543 	  Loss: 1.6062218108989454 	 Accuracy: 0.4758800521512386
Delta: 0.002763837429621918 	  Loss: 1.6062132664504802 	 Accuracy: 0.47196870925684486
Delta: 0.0007442626328761584 	  Loss: 1.6061134547302547 	 Accuracy: 0.4784876140808344
Delta: 0.0023817689419593563 	  Loss: 1.6063979420942416 	 Accuracy: 0.4771838331160365
Delta: 0.0017222742450076515 	  Loss: 1.6061713164277505 	 Accuracy: 0.4758800521512386
Delta: 0.0019315382558367515 	  Loss: 1.6063559490473605 	 Accuracy: 0.4771838331160365
Delta: 0.0020368056504248074 	  Loss: 1.606137104372454 	 Accuracy: 0.4771838331160365
Delta: 0.0006371970008832066 	  Loss: 1.6059997561079515 	 Accuracy: 0.48370273794002605
Delta: 0.002980406336585245 	  Loss: 1.6063292880924651 	 Accuracy: 0.4745762711864407
Delta: 0.006231949696826612 	  Loss: 1.6079003317508933 	 Accuracy: 0.47327249022164275
Delta: 0.002699709240978637 	  Loss: 1.6081575705266853 	 Accuracy: 0.47196870925684486
Delta: 0.0038650699848679004 	  Loss: 1.6080244217649808 	 Accuracy: 0.4771838331160365
Delta: 0.0036185820535681356 	  Loss: 1.6076545546405558 	 Accuracy: 0.4745762711864407
Delta: 0.0033325911683107687 	  Loss: 1.6070986334301551 	 Accuracy: 0.4771838331160365
Delta: 0.0026918561607801837 	  Loss: 1.6088652206241034 	 Accuracy: 0.4771838331160365
Delta: 0.0038510698839165384 	  Loss: 1.6096275889143838 	 Accuracy: 0.4771838331160365
Delta: 0.002760831354910062 	  Loss: 1.6097230921283985 	 Accuracy: 0.4784876140808344
Delta: 2.0897830552579996e-05 	  Loss: 1.609702675230483 	 Accuracy: 0.4758800521512386
Delta: 0.003528903253455068 	  Loss: 1.609902038116247 	 Accuracy: 0.4745762711864407
Delta: 0.0039997068527937675 	  Loss: 1.6096338618832058 	 Accuracy: 0.4771838331160365
Delta: 0.004362268368760207 	  Loss: 1.6092837761303325 	 Accuracy: 0.4758800521512386
Delta: 0.002064767466458052 	  Loss: 1.6092971189440481 	 Accuracy: 0.4771838331160365
Delta: 0.0019690814989100527 	  Loss: 1.6091960642195995 	 Accuracy: 0.4758800521512386
Delta: 0.0025677583771231915 	  Loss: 1.6097285811791338 	 Accuracy: 0.4758800521512386
Delta: 0.003935799693945485 	  Loss: 1.609935415227262 	 Accuracy: 0.4758800521512386
Delta: 0.003029156805357465 	  Loss: 1.6097263829068815 	 Accuracy: 0.4758800521512386
Delta: 0.00075941635808838 	  Loss: 1.6097574361330442 	 Accuracy: 0.4758800521512386
Delta: 0.0005724257113982366 	  Loss: 1.6097980190209245 	 Accuracy: 0.4758800521512386
Delta: 0.005340494128050342 	  Loss: 1.6097211537173886 	 Accuracy: 0.4784876140808344
Delta: 0.0034785249406167236 	  Loss: 1.6102579361413403 	 Accuracy: 0.47979139504563234
Delta: 0.005920257734980701 	  Loss: 1.6105253726397188 	 Accuracy: 0.4784876140808344
Delta: 0.0027103378692516543 	  Loss: 1.6105730195210155 	 Accuracy: 0.47979139504563234
Delta: 0.003527200391899503 	  Loss: 1.610559220852281 	 Accuracy: 0.4758800521512386
Delta: 0.0018848052768405878 	  Loss: 1.6110155412209632 	 Accuracy: 0.4784876140808344
Delta: 0.0035683529844303392 	  Loss: 1.6102331606851097 	 Accuracy: 0.4771838331160365
Delta: 0.003307779886056656 	  Loss: 1.6111608615923791 	 Accuracy: 0.4745762711864407
Delta: 0.003916569035772256 	  Loss: 1.6115313162228966 	 Accuracy: 0.4758800521512386
Delta: 0.004303357406890749 	  Loss: 1.6125192508109318 	 Accuracy: 0.47979139504563234
Delta: 0.0032094018526589046 	  Loss: 1.6118289316113217 	 Accuracy: 0.4771838331160365
Delta: 0.0018270514100532488 	  Loss: 1.6119191876492824 	 Accuracy: 0.4771838331160365
Delta: 0.004304108686598395 	  Loss: 1.6110097896248499 	 Accuracy: 0.4771838331160365
Delta: 0.004153674386532361 	  Loss: 1.6096217474418864 	 Accuracy: 0.4745762711864407
Delta: 0.005085249069214636 	  Loss: 1.6119325769861756 	 Accuracy: 0.4771838331160365
Delta: 0.0037641313077668363 	  Loss: 1.6118953901245754 	 Accuracy: 0.4771838331160365
Delta: 0.004065230693806552 	  Loss: 1.612180342603825 	 Accuracy: 0.4771838331160365
Delta: 0.0037179949251096257 	  Loss: 1.6121473981690095 	 Accuracy: 0.47979139504563234
Delta: 0.0014911191977732196 	  Loss: 1.6116616103232262 	 Accuracy: 0.4771838331160365
Delta: 0.003142250706318246 	  Loss: 1.610757106655746 	 Accuracy: 0.4784876140808344
Delta: 0.0022428618379181273 	  Loss: 1.6120524607192213 	 Accuracy: 0.4784876140808344
Delta: 3.315101204795893e-05 	  Loss: 1.6118219209896476 	 Accuracy: 0.4745762711864407
Delta: 0.0015085881616059478 	  Loss: 1.6121814983052918 	 Accuracy: 0.4771838331160365
Delta: 8.798903864263873e-05 	  Loss: 1.6119735472638053 	 Accuracy: 0.4784876140808344
Delta: 0.020932862041043082 	  Loss: 2.147269757005891 	 Accuracy: 0.19947848761408082
Delta: 0.01892981833710508 	  Loss: 2.029795854816504 	 Accuracy: 0.242503259452412
Delta: 0.018118639869950007 	  Loss: 1.8134402657073176 	 Accuracy: 0.38461538461538464
Delta: 0.01612634099719625 	  Loss: 1.6553511289551204 	 Accuracy: 0.42242503259452413
Delta: 0.012238924764668058 	  Loss: 1.6020293960389755 	 Accuracy: 0.3924380704041721

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009529389595272825 	  Loss: 1.5904750294386034 	 Accuracy: 0.37809647979139505
Delta: 0.007853141143039815 	  Loss: 1.5860008684455833 	 Accuracy: 0.3728813559322034
Delta: 0.007089036241380234 	  Loss: 1.5840564950934997 	 Accuracy: 0.36766623207301175
Delta: 0.005178720020441395 	  Loss: 1.5832945439812418 	 Accuracy: 0.3650586701434159
Delta: 0.003921081777644932 	  Loss: 1.5829481998195076 	 Accuracy: 0.3663624511082138
Delta: 0.002667798288092405 	  Loss: 1.5827882186973823 	 Accuracy: 0.3650586701434159
Delta: 0.0036257375812560107 	  Loss: 1.5827430169290355 	 Accuracy: 0.3663624511082138
Delta: 0.000764257725433725 	  Loss: 1.582720945557612 	 Accuracy: 0.3650586701434159
Delta: 4.4317110905547085e-05 	  Loss: 1.5827379204793757 	 Accuracy: 0.3650586701434159
Delta: 3.7023055270075966e-05 	  Loss: 1.582643350937986 	 Accuracy: 0.363754889178618
Delta: 0.002449578067619977 	  Loss: 1.5824361641805063 	 Accuracy: 0.363754889178618
Delta: 0.0007690662920774846 	  Loss: 1.582489197891702 	 Accuracy: 0.3650586701434159
Delta: 4.2590772157368377e-05 	  Loss: 1.5826763574823368 	 Accuracy: 0.3650586701434159
Delta: 2.337996948130686e-05 	  Loss: 1.5825763384092992 	 Accuracy: 0.3650586701434159
Delta: 0.0010591484962304027 	  Loss: 1.5824971659159763 	 Accuracy: 0.3663624511082138
Delta: 0.0020507007664666813 	  Loss: 1.5821903579343068 	 Accuracy: 0.363754889178618
Delta: 0.0011829388441352076 	  Loss: 1.58280378517113 	 Accuracy: 0.363754889178618
Delta: 9.786382378436378e-05 	  Loss: 1.5821007129841351 	 Accuracy: 0.3650586701434159
Delta: 0.001582040841599797 	  Loss: 1.5820323339819473 	 Accuracy: 0.3650586701434159
Delta: 0.0035579674889612764 	  Loss: 1.582337914232491 	 Accuracy: 0.3650586701434159
Delta: 0.0032473951248519328 	  Loss: 1.582050660554348 	 Accuracy: 0.3650586701434159
Delta: 0.002670276583329398 	  Loss: 1.5823284160411566 	 Accuracy: 0.3650586701434159
Delta: 3.638919637400541e-05 	  Loss: 1.5823650527633082 	 Accuracy: 0.3650586701434159
Delta: 0.0037579598124158767 	  Loss: 1.5830724266244591 	 Accuracy: 0.3650586701434159
Delta: 0.0032219880052163693 	  Loss: 1.5822132553523387 	 Accuracy: 0.3650586701434159
Delta: 0.003349419973162667 	  Loss: 1.5816159359696664 	 Accuracy: 0.36897001303780963
Delta: 0.0014780300565460504 	  Loss: 1.5817325980737738 	 Accuracy: 0.36897001303780963
Delta: 0.005338733782341543 	  Loss: 1.5814215423011837 	 Accuracy: 0.37027379400260757
Delta: 0.002410884485045368 	  Loss: 1.5813442638326876 	 Accuracy: 0.36766623207301175
Delta: 0.004072335495455475 	  Loss: 1.5810417913251178 	 Accuracy: 0.3663624511082138
Delta: 0.0032022473104960343 	  Loss: 1.5815152946245232 	 Accuracy: 0.3663624511082138
Delta: 0.002371762822897764 	  Loss: 1.581186837843695 	 Accuracy: 0.3650586701434159
Delta: 0.0028756734489974955 	  Loss: 1.5809344276952835 	 Accuracy: 0.3663624511082138
Delta: 0.004663521201319252 	  Loss: 1.5805379030899105 	 Accuracy: 0.3650586701434159
Delta: 0.001069094099970241 	  Loss: 1.5804281129471605 	 Accuracy: 0.3663624511082138
Delta: 0.0011603537235125331 	  Loss: 1.5809253601528257 	 Accuracy: 0.3650586701434159
Delta: 0.0031688179393387843 	  Loss: 1.5811899346005476 	 Accuracy: 0.3663624511082138
Delta: 0.0027087884386702383 	  Loss: 1.581188511902897 	 Accuracy: 0.3650586701434159
Delta: 0.0034522100195712294 	  Loss: 1.5810594133445144 	 Accuracy: 0.3650586701434159
Delta: 0.003547030871515072 	  Loss: 1.5811357684311595 	 Accuracy: 0.3650586701434159
Delta: 0.0009596483132834486 	  Loss: 1.5811598406664134 	 Accuracy: 0.3650586701434159
Delta: 0.0029516436805246222 	  Loss: 1.5808029281413591 	 Accuracy: 0.3650586701434159
Delta: 0.001183422472245882 	  Loss: 1.5806506667894602 	 Accuracy: 0.3650586701434159
Delta: 0.005929166984628451 	  Loss: 1.5813887385105243 	 Accuracy: 0.363754889178618
Delta: 0.0011942497871257444 	  Loss: 1.5814567050002302 	 Accuracy: 0.35984354628422427
Delta: 0.0015867855217619523 	  Loss: 1.5815519389878467 	 Accuracy: 0.3650586701434159
Delta: 0.0023943769927627164 	  Loss: 1.5811186480807566 	 Accuracy: 0.3624511082138201
Delta: 0.0008836212527875702 	  Loss: 1.5812062688298907 	 Accuracy: 0.363754889178618
Delta: 0.0007380709709877653 	  Loss: 1.5813395434564717 	 Accuracy: 0.363754889178618
Delta: 0.00011119363156418049 	  Loss: 1.5812973414822276 	 Accuracy: 0.3624511082138201
Delta: 0.00266233662959124 	  Loss: 1.5819219696855809 	 Accuracy: 0.363754889178618
Delta: 0.0010702876334657701 	  Loss: 1.581614052610542 	 Accuracy: 0.363754889178618
Delta: 0.003671373882325041 	  Loss: 1.5817890181230392 	 Accuracy: 0.36766623207301175
Delta: 0.0018835944776491706 	  Loss: 1.5808857178820397 	 Accuracy: 0.37027379400260757
Delta: 0.0032524286188115492 	  Loss: 1.5806847289870882 	 Accuracy: 0.3650586701434159
Delta: 0.0028315141029573196 	  Loss: 1.580970322252781 	 Accuracy: 0.3663624511082138
Delta: 0.0019121961216848147 	  Loss: 1.580864157857384 	 Accuracy: 0.3650586701434159
Delta: 8.829691922686629e-05 	  Loss: 1.580822097116318 	 Accuracy: 0.363754889178618
Delta: 0.0009634131280285506 	  Loss: 1.581294041831915 	 Accuracy: 0.3624511082138201
Delta: 0.0027819474944235597 	  Loss: 1.582258811043372 	 Accuracy: 0.363754889178618
Delta: 0.0025659859292601612 	  Loss: 1.581660494664354 	 Accuracy: 0.363754889178618
Delta: 1.402365433893455e-05 	  Loss: 1.5816966084800272 	 Accuracy: 0.363754889178618
Delta: 0.002482374933543365 	  Loss: 1.5812479655671146 	 Accuracy: 0.3650586701434159
Delta: 0.0005385385309703227 	  Loss: 1.5815253813979695 	 Accuracy: 0.363754889178618
Delta: 0.003632402043063249 	  Loss: 1.5817413264103655 	 Accuracy: 0.36766623207301175
Delta: 0.0013184341277235735 	  Loss: 1.581794325332341 	 Accuracy: 0.36897001303780963
Delta: 0.003092171175532504 	  Loss: 1.5816367131161142 	 Accuracy: 0.3650586701434159
Delta: 0.0023424827143431306 	  Loss: 1.5816157433499973 	 Accuracy: 0.3624511082138201
Delta: 0.0007770056804790493 	  Loss: 1.5817367040674954 	 Accuracy: 0.363754889178618
Delta: 0.000795730913166687 	  Loss: 1.5816957619698053 	 Accuracy: 0.3650586701434159
Delta: 0.003968461511197706 	  Loss: 1.5820410802680998 	 Accuracy: 0.3624511082138201
Delta: 0.0019469648375855008 	  Loss: 1.5820387080131213 	 Accuracy: 0.3624511082138201
Delta: 0.002590875365722976 	  Loss: 1.5819192882072672 	 Accuracy: 0.35984354628422427
Delta: 0.0017866823095039834 	  Loss: 1.5820070150517882 	 Accuracy: 0.363754889178618
Delta: 0.001643974413036075 	  Loss: 1.5821323519591537 	 Accuracy: 0.3624511082138201
Delta: 0.0005407416077851828 	  Loss: 1.5820834799423706 	 Accuracy: 0.3624511082138201
Delta: 0.0025605381085191713 	  Loss: 1.5821923895638723 	 Accuracy: 0.363754889178618
Delta: 0.004130522475120729 	  Loss: 1.5819641372675368 	 Accuracy: 0.363754889178618
Delta: 0.00230563603853297 	  Loss: 1.5822504577470204 	 Accuracy: 0.36766623207301175
Delta: 0.0043143109311156655 	  Loss: 1.5816099466808173 	 Accuracy: 0.363754889178618
Delta: 0.00015738212547594988 	  Loss: 1.5818513850189606 	 Accuracy: 0.3650586701434159
Delta: 0.0030204358130850577 	  Loss: 1.5816995762281332 	 Accuracy: 0.3624511082138201
Delta: 0.0015966271878520635 	  Loss: 1.5828107271777834 	 Accuracy: 0.3624511082138201
Delta: 0.0030184862387076144 	  Loss: 1.5832346822285057 	 Accuracy: 0.36114732724902215
Delta: 0.0017210616927065246 	  Loss: 1.58274345425853 	 Accuracy: 0.36114732724902215
Delta: 0.006254252384084435 	  Loss: 1.5843287979564562 	 Accuracy: 0.35984354628422427
Delta: 0.003916997187853324 	  Loss: 1.5844989968530852 	 Accuracy: 0.35853976531942633
Delta: 0.0023321378189758183 	  Loss: 1.584463172946081 	 Accuracy: 0.36114732724902215
Delta: 0.0030021905381452793 	  Loss: 1.5836681791541194 	 Accuracy: 0.36114732724902215
Delta: 0.0019630653975714796 	  Loss: 1.583651472477623 	 Accuracy: 0.36114732724902215
Delta: 0.002515919040339612 	  Loss: 1.5837807626659293 	 Accuracy: 0.35984354628422427
Delta: 0.0023785522300601336 	  Loss: 1.583624417522778 	 Accuracy: 0.35853976531942633
Delta: 0.0030771243926535617 	  Loss: 1.5837091761643958 	 Accuracy: 0.35723598435462844
Delta: 0.003570309699381625 	  Loss: 1.5835332101479347 	 Accuracy: 0.35984354628422427
Delta: 0.0005588070160488453 	  Loss: 1.5835635690876875 	 Accuracy: 0.36114732724902215
Delta: 0.020977687450222424 	  Loss: 2.146946412836332 	 Accuracy: 0.19165580182529335
Delta: 0.018638066755580246 	  Loss: 2.0348277227691494 	 Accuracy: 0.23728813559322035
Delta: 0.017898002981834006 	  Loss: 1.8414116925076842 	 Accuracy: 0.3455019556714472
Delta: 0.016051602078699777 	  Loss: 1.7040393983692308 	 Accuracy: 0.39374185136897
Delta: 0.012970363748919215 	  Loss: 1.656855080879067 	 Accuracy: 0.39895697522816165

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009111443549097376 	  Loss: 1.645726954426893 	 Accuracy: 0.41199478487614083
Delta: 0.007941198588471896 	  Loss: 1.642638308205267 	 Accuracy: 0.4132985658409387
Delta: 0.005296889109763376 	  Loss: 1.6415843477828709 	 Accuracy: 0.41460234680573665
Delta: 0.004165805444131278 	  Loss: 1.641585848408525 	 Accuracy: 0.41460234680573665
Delta: 0.0035475190915075245 	  Loss: 1.6413760635552719 	 Accuracy: 0.4132985658409387
Delta: 0.0013227923623830423 	  Loss: 1.6411042565152758 	 Accuracy: 0.4132985658409387
Delta: 0.0018306324993507157 	  Loss: 1.6410003894896752 	 Accuracy: 0.41590612777053454
Delta: 2.9138251497663377e-05 	  Loss: 1.6409680314188133 	 Accuracy: 0.4132985658409387
Delta: 0.0021905972974949105 	  Loss: 1.6407818425973262 	 Accuracy: 0.41199478487614083
Delta: 0.002208893357546447 	  Loss: 1.640827305368255 	 Accuracy: 0.4132985658409387
Delta: 0.0015811521525557026 	  Loss: 1.6410506489512224 	 Accuracy: 0.4172099087353325
Delta: 0.001093464020454367 	  Loss: 1.6409886718459399 	 Accuracy: 0.4172099087353325
Delta: 0.0005816174592495779 	  Loss: 1.6410868613595762 	 Accuracy: 0.4132985658409387
Delta: 0.0018539198035748307 	  Loss: 1.6408307779383446 	 Accuracy: 0.41460234680573665
Delta: 1.790636874055497e-05 	  Loss: 1.6408368037693584 	 Accuracy: 0.4132985658409387
Delta: 0.0036096266877341443 	  Loss: 1.6409793554306251 	 Accuracy: 0.41590612777053454
Delta: 0.003154842586841793 	  Loss: 1.6409808635807421 	 Accuracy: 0.41590612777053454
Delta: 0.0023187263624701625 	  Loss: 1.6409380329693894 	 Accuracy: 0.41590612777053454
Delta: 0.0019632098129040345 	  Loss: 1.640905494646308 	 Accuracy: 0.41590612777053454
Delta: 0.002830472344424259 	  Loss: 1.6411490517520733 	 Accuracy: 0.41590612777053454
Delta: 0.001169969959523368 	  Loss: 1.6408072185922364 	 Accuracy: 0.41590612777053454
Delta: 0.0009255465147648915 	  Loss: 1.6408321920131617 	 Accuracy: 0.41590612777053454
Delta: 0.00233133942473552 	  Loss: 1.6408770081917132 	 Accuracy: 0.4172099087353325
Delta: 0.004558785360905485 	  Loss: 1.641782511546725 	 Accuracy: 0.409387222946545
Delta: 0.004335366844649718 	  Loss: 1.641429472746504 	 Accuracy: 0.43285528031290743
Delta: 0.005018047598762498 	  Loss: 1.6397791824339776 	 Accuracy: 0.41851368970013036
Delta: 0.0010770169793998736 	  Loss: 1.639769411650704 	 Accuracy: 0.41590612777053454
Delta: 0.004731700339883645 	  Loss: 1.6408382319209887 	 Accuracy: 0.41590612777053454
Delta: 0.004267798705364204 	  Loss: 1.6416290764738464 	 Accuracy: 0.41590612777053454
Delta: 0.004484398541967473 	  Loss: 1.6420362369496695 	 Accuracy: 0.41590612777053454
Delta: 0.0020883787356449773 	  Loss: 1.6422800832122382 	 Accuracy: 0.41460234680573665
Delta: 0.0026632133237023013 	  Loss: 1.6425063399923236 	 Accuracy: 0.41851368970013036
Delta: 0.0029014760826157697 	  Loss: 1.6417962862827737 	 Accuracy: 0.41590612777053454
Delta: 7.078792472395087e-05 	  Loss: 1.6416427918786627 	 Accuracy: 0.41460234680573665
Delta: 0.003168033454783428 	  Loss: 1.6425956131764852 	 Accuracy: 0.41590612777053454
Delta: 0.0026146817226157986 	  Loss: 1.642670239995924 	 Accuracy: 0.41460234680573665
Delta: 0.0035481756765439174 	  Loss: 1.6425428844928869 	 Accuracy: 0.41460234680573665
Delta: 0.003468910889707985 	  Loss: 1.642403577551029 	 Accuracy: 0.41590612777053454
Delta: 0.0011059576144767994 	  Loss: 1.6427101474518522 	 Accuracy: 0.41460234680573665
Delta: 0.0028785077809409484 	  Loss: 1.642679152763837 	 Accuracy: 0.41590612777053454
Delta: 0.0017894985535183495 	  Loss: 1.6424357594727566 	 Accuracy: 0.4172099087353325
Delta: 3.9108785054042904e-05 	  Loss: 1.642288785575806 	 Accuracy: 0.41590612777053454
Delta: 7.56893406253617e-05 	  Loss: 1.6427254561250142 	 Accuracy: 0.41460234680573665
Delta: 2.211850402178478e-05 	  Loss: 1.6428160350093295 	 Accuracy: 0.39895697522816165
Delta: 0.002489487455927905 	  Loss: 1.6432417426817765 	 Accuracy: 0.41460234680573665
Delta: 0.0018576732120686632 	  Loss: 1.6435555130443706 	 Accuracy: 0.41460234680573665
Delta: 0.0020527569614425716 	  Loss: 1.6435148557845594 	 Accuracy: 0.4132985658409387
Delta: 0.0020674239339088076 	  Loss: 1.6433583288686544 	 Accuracy: 0.41460234680573665
Delta: 0.0026439373082021785 	  Loss: 1.643716282156319 	 Accuracy: 0.4106910039113429
Delta: 0.007190201112881089 	  Loss: 1.6452705868630073 	 Accuracy: 0.41460234680573665
Delta: 0.007393531852423561 	  Loss: 1.643534569807234 	 Accuracy: 0.41590612777053454
Delta: 0.004382900028418239 	  Loss: 1.6427802705774825 	 Accuracy: 0.41590612777053454
Delta: 0.00552725344127965 	  Loss: 1.642453949069595 	 Accuracy: 0.4172099087353325
Delta: 0.005065910274639143 	  Loss: 1.6416226141701111 	 Accuracy: 0.41851368970013036
Delta: 0.004269364696482519 	  Loss: 1.641317814352702 	 Accuracy: 0.4172099087353325
Delta: 0.000990809689548455 	  Loss: 1.6418700348424267 	 Accuracy: 0.4172099087353325
Delta: 0.0008396362592105761 	  Loss: 1.641993947943662 	 Accuracy: 0.4172099087353325
Delta: 0.0023552967549483332 	  Loss: 1.642079005332488 	 Accuracy: 0.4172099087353325
Delta: 0.0014448276225943444 	  Loss: 1.6419664474715305 	 Accuracy: 0.41590612777053454
Delta: 0.0033754372278915925 	  Loss: 1.6409422779832408 	 Accuracy: 0.4172099087353325
Delta: 0.0035381521147720405 	  Loss: 1.6419316062334461 	 Accuracy: 0.4172099087353325
Delta: 0.0007722659385166314 	  Loss: 1.6419231545243165 	 Accuracy: 0.4172099087353325
Delta: 0.0024814327367516003 	  Loss: 1.6420880235283382 	 Accuracy: 0.41851368970013036
Delta: 0.0052494540374044725 	  Loss: 1.642303125585024 	 Accuracy: 0.4172099087353325
Delta: 0.001942570014396219 	  Loss: 1.6420575472592431 	 Accuracy: 0.4172099087353325
Delta: 0.0020344473447265316 	  Loss: 1.6422802917784776 	 Accuracy: 0.4172099087353325
Delta: 0.004276920219381305 	  Loss: 1.6415159289345336 	 Accuracy: 0.41851368970013036
Delta: 0.0029195094196523704 	  Loss: 1.6414665872204686 	 Accuracy: 0.41851368970013036
Delta: 0.003220536246757339 	  Loss: 1.6413651259759847 	 Accuracy: 0.41851368970013036
Delta: 0.003008555329999391 	  Loss: 1.6412828631010938 	 Accuracy: 0.41851368970013036
Delta: 0.0023033794327450554 	  Loss: 1.6413839134933008 	 Accuracy: 0.41851368970013036
Delta: 0.0018080352403899043 	  Loss: 1.6415884268150371 	 Accuracy: 0.41199478487614083
Delta: 0.004830403343407049 	  Loss: 1.6429373962600435 	 Accuracy: 0.40808344198174706
Delta: 0.006109375370095703 	  Loss: 1.6456771946339694 	 Accuracy: 0.41851368970013036
Delta: 0.004845010906169512 	  Loss: 1.6452915075527317 	 Accuracy: 0.4172099087353325
Delta: 0.0042783075311768285 	  Loss: 1.6467926994198545 	 Accuracy: 0.42503259452411996
Delta: 0.006925763759863871 	  Loss: 1.6430577642978346 	 Accuracy: 0.4211212516297262
Delta: 0.0049995560620553865 	  Loss: 1.6433362914538248 	 Accuracy: 0.423728813559322
Delta: 0.00396890365068139 	  Loss: 1.6428505974684684 	 Accuracy: 0.4211212516297262
Delta: 0.0055867368291934805 	  Loss: 1.6442962564027197 	 Accuracy: 0.42242503259452413
Delta: 0.0028496562527103734 	  Loss: 1.6444856948548634 	 Accuracy: 0.42242503259452413
Delta: 0.0013044208337926635 	  Loss: 1.6444299423859845 	 Accuracy: 0.42242503259452413
Delta: 0.004497609924557507 	  Loss: 1.6430966560714788 	 Accuracy: 0.4198174706649283
Delta: 0.004118520614446692 	  Loss: 1.6438199628577501 	 Accuracy: 0.42633637548891784
Delta: 0.0027892844000961944 	  Loss: 1.6431536573865637 	 Accuracy: 0.42503259452411996
Delta: 0.004387674301700172 	  Loss: 1.6430377956883784 	 Accuracy: 0.423728813559322
Delta: 0.000998485443090645 	  Loss: 1.6424429419161126 	 Accuracy: 0.423728813559322
Delta: 0.0005268582622403028 	  Loss: 1.6424121807954686 	 Accuracy: 0.4211212516297262
Delta: 0.003121082415612752 	  Loss: 1.6428372037809584 	 Accuracy: 0.423728813559322
Delta: 0.002993679700480907 	  Loss: 1.642518835817342 	 Accuracy: 0.4302477183833116
Delta: 1.4460461680618806e-05 	  Loss: 1.6425130166883792 	 Accuracy: 0.4211212516297262
Delta: 0.005097101582450731 	  Loss: 1.6432539279861411 	 Accuracy: 0.4211212516297262
Delta: 0.0056370151973557025 	  Loss: 1.643203335595359 	 Accuracy: 0.4211212516297262
Delta: 0.0021912354834358262 	  Loss: 1.6434149355480832 	 Accuracy: 0.4211212516297262
Delta: 0.0031111419657306313 	  Loss: 1.643190115389278 	 Accuracy: 0.41851368970013036
Delta: 0.021004085310030226 	  Loss: 2.1453004777251987 	 Accuracy: 0.19947848761408082
Delta: 0.018688459665957263 	  Loss: 2.030069123778057 	 Accuracy: 0.3011734028683181
Delta: 0.01811649759237398 	  Loss: 1.8398418510906438 	 Accuracy: 0.32985658409387225
Delta: 0.016417529021109784 	  Loss: 1.7015513656571486 	 Accuracy: 0.318122555410691
Delta: 0.011942764326175767 	  Loss: 1.663175325220346 	 Accuracy: 0.3155149934810952

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008382242061020957 	  Loss: 1.6539711770508614 	 Accuracy: 0.3116036505867014
Delta: 0.007318406182200828 	  Loss: 1.6532109930830632 	 Accuracy: 0.3116036505867014
Delta: 0.005688104563996993 	  Loss: 1.653368877011018 	 Accuracy: 0.31029986962190353
Delta: 0.004709665194004005 	  Loss: 1.6527582752253918 	 Accuracy: 0.32073011734028684
Delta: 0.0030675957611140743 	  Loss: 1.653532744042633 	 Accuracy: 0.31421121251629724
Delta: 0.0021164312939239683 	  Loss: 1.6526955499099938 	 Accuracy: 0.3116036505867014
Delta: 0.003023205891407892 	  Loss: 1.6529129570138585 	 Accuracy: 0.31290743155149936
Delta: 0.0016841444329699447 	  Loss: 1.6528868847714122 	 Accuracy: 0.3116036505867014
Delta: 0.0033014659675934407 	  Loss: 1.6522390199526789 	 Accuracy: 0.3116036505867014
Delta: 0.0017567000225981576 	  Loss: 1.6520632299440163 	 Accuracy: 0.31681877444589307
Delta: 0.004553749165797286 	  Loss: 1.6524074055625655 	 Accuracy: 0.31290743155149936
Delta: 0.003242945071811583 	  Loss: 1.6527951041039295 	 Accuracy: 0.31290743155149936
Delta: 0.001954127826912323 	  Loss: 1.6525275036452953 	 Accuracy: 0.31421121251629724
Delta: 0.0021522563782192515 	  Loss: 1.6525085867738563 	 Accuracy: 0.31421121251629724
Delta: 0.0013611208982612763 	  Loss: 1.6527226603378375 	 Accuracy: 0.31290743155149936
Delta: 0.0018977863889517688 	  Loss: 1.652202593968996 	 Accuracy: 0.31421121251629724
Delta: 0.0034450784209480324 	  Loss: 1.6532610031304311 	 Accuracy: 0.31421121251629724
Delta: 0.0034977493262454817 	  Loss: 1.653098998794573 	 Accuracy: 0.3155149934810952
Delta: 0.0027377143091066214 	  Loss: 1.652311311050787 	 Accuracy: 0.31421121251629724
Delta: 0.0023674747781187223 	  Loss: 1.6520705206918005 	 Accuracy: 0.31421121251629724
Delta: 0.0032117014565581315 	  Loss: 1.651950816107338 	 Accuracy: 0.3155149934810952
Delta: 0.0026021502601328117 	  Loss: 1.652596049804903 	 Accuracy: 0.3155149934810952
Delta: 0.003548388698265077 	  Loss: 1.652949500758978 	 Accuracy: 0.3116036505867014
Delta: 0.0026041965941291326 	  Loss: 1.6529167589155866 	 Accuracy: 0.31421121251629724
Delta: 0.0013000114985996978 	  Loss: 1.6529877635409462 	 Accuracy: 0.3155149934810952
Delta: 0.0022839105400538117 	  Loss: 1.652186360535464 	 Accuracy: 0.31421121251629724
Delta: 0.001377664829433191 	  Loss: 1.6528832908485875 	 Accuracy: 0.31421121251629724
Delta: 0.0014952901548780256 	  Loss: 1.6525380657456232 	 Accuracy: 0.31421121251629724
Delta: 0.0023875905089842217 	  Loss: 1.6530073850249536 	 Accuracy: 0.3116036505867014
Delta: 0.0032335019489834575 	  Loss: 1.652267435837178 	 Accuracy: 0.31421121251629724
Delta: 0.0019419426150460383 	  Loss: 1.6526216718125222 	 Accuracy: 0.3155149934810952
Delta: 0.0018200305557792024 	  Loss: 1.6525380167698038 	 Accuracy: 0.31681877444589307
Delta: 0.003977936990597781 	  Loss: 1.652914695359462 	 Accuracy: 0.31421121251629724
Delta: 0.00273114680334918 	  Loss: 1.6534708473757935 	 Accuracy: 0.3155149934810952
Delta: 0.0019732238366042985 	  Loss: 1.6529750785989998 	 Accuracy: 0.31290743155149936
Delta: 0.003999780536072997 	  Loss: 1.6525966090284263 	 Accuracy: 0.31290743155149936
Delta: 0.002515756633531531 	  Loss: 1.652660936853676 	 Accuracy: 0.31421121251629724
Delta: 0.0013878299550253862 	  Loss: 1.6524962608238272 	 Accuracy: 0.31290743155149936
Delta: 0.001703751136495228 	  Loss: 1.6519523324847936 	 Accuracy: 0.31290743155149936
Delta: 0.004304635916135767 	  Loss: 1.6515912395253953 	 Accuracy: 0.318122555410691
Delta: 0.0026824276894171144 	  Loss: 1.6513309368077094 	 Accuracy: 0.31290743155149936
Delta: 0.0019941557156717225 	  Loss: 1.6520294463740117 	 Accuracy: 0.3155149934810952
Delta: 0.0029681966524699706 	  Loss: 1.6531626243057707 	 Accuracy: 0.3155149934810952
Delta: 0.0018707957453336223 	  Loss: 1.6534423597096055 	 Accuracy: 0.31290743155149936
Delta: 0.0010692087820649342 	  Loss: 1.6528982573619058 	 Accuracy: 0.31421121251629724
Delta: 0.0019214409779392712 	  Loss: 1.6530615701587612 	 Accuracy: 0.3155149934810952
Delta: 0.005454613835997068 	  Loss: 1.6542768784620936 	 Accuracy: 0.31421121251629724
Delta: 0.0016525410274148451 	  Loss: 1.6536677710932204 	 Accuracy: 0.3155149934810952
Delta: 0.0035614068653181024 	  Loss: 1.653664501167563 	 Accuracy: 0.31421121251629724
Delta: 0.0049785311591358005 	  Loss: 1.6531912499947996 	 Accuracy: 0.3089960886571056
Delta: 0.005110792758429022 	  Loss: 1.6543074718529724 	 Accuracy: 0.3116036505867014
Delta: 0.004144281064211951 	  Loss: 1.6546794869098864 	 Accuracy: 0.31029986962190353
Delta: 0.004374077130952097 	  Loss: 1.6527737540111782 	 Accuracy: 0.31029986962190353
Delta: 0.005354908285458465 	  Loss: 1.653651177268777 	 Accuracy: 0.3089960886571056
Delta: 0.0046695277352662296 	  Loss: 1.65409739997492 	 Accuracy: 0.3116036505867014
Delta: 0.003476255859796791 	  Loss: 1.6545744601755006 	 Accuracy: 0.3089960886571056
Delta: 0.003174632608448863 	  Loss: 1.6550973094196224 	 Accuracy: 0.3050847457627119
Delta: 0.002785254171652316 	  Loss: 1.6553064885853228 	 Accuracy: 0.3076923076923077
Delta: 0.003859601104818835 	  Loss: 1.6566149214634072 	 Accuracy: 0.3076923076923077
Delta: 0.005263960842459017 	  Loss: 1.655390285672271 	 Accuracy: 0.3089960886571056
Delta: 0.0030660653636138354 	  Loss: 1.6557714430658774 	 Accuracy: 0.3076923076923077
Delta: 0.0033813487076909594 	  Loss: 1.6559330777550714 	 Accuracy: 0.3076923076923077
Delta: 0.003615119404181019 	  Loss: 1.6558431186656204 	 Accuracy: 0.31029986962190353
Delta: 0.0019647016008860294 	  Loss: 1.655765210522556 	 Accuracy: 0.3076923076923077
Delta: 0.004413307089096494 	  Loss: 1.654899785787838 	 Accuracy: 0.31290743155149936
Delta: 0.004895099307562633 	  Loss: 1.6539314260221523 	 Accuracy: 0.31421121251629724
Delta: 0.004442726550832156 	  Loss: 1.6537878012628457 	 Accuracy: 0.31290743155149936
Delta: 0.003856855000215244 	  Loss: 1.6542408105700535 	 Accuracy: 0.3116036505867014
Delta: 0.004204379875150393 	  Loss: 1.6545198172086488 	 Accuracy: 0.31290743155149936
Delta: 0.00188209536279588 	  Loss: 1.6547773140407558 	 Accuracy: 0.31290743155149936
Delta: 0.0014997002394225604 	  Loss: 1.6546445617952963 	 Accuracy: 0.31290743155149936
Delta: 0.001544997872617734 	  Loss: 1.654778493191889 	 Accuracy: 0.31421121251629724
Delta: 0.0027862456167292615 	  Loss: 1.6534607164875048 	 Accuracy: 0.3116036505867014
Delta: 0.005303203963939043 	  Loss: 1.6528746752198238 	 Accuracy: 0.33376792698826596
Delta: 0.006361980016077125 	  Loss: 1.654198906433311 	 Accuracy: 0.31421121251629724
Delta: 0.006682878264952635 	  Loss: 1.6509506977486827 	 Accuracy: 0.3116036505867014
Delta: 0.005997649175806401 	  Loss: 1.6526196079601503 	 Accuracy: 0.3155149934810952
Delta: 0.006159753253869134 	  Loss: 1.6543085750716413 	 Accuracy: 0.31421121251629724
Delta: 0.0017840342627275976 	  Loss: 1.6542092130538655 	 Accuracy: 0.3155149934810952
Delta: 0.004617803241313031 	  Loss: 1.653035575262514 	 Accuracy: 0.3076923076923077
Delta: 0.007287886354352168 	  Loss: 1.646952624031257 	 Accuracy: 0.30638852672750977
Delta: 0.006334295664443297 	  Loss: 1.6498020352315024 	 Accuracy: 0.3050847457627119
Delta: 0.005463941798182666 	  Loss: 1.6467355259025083 	 Accuracy: 0.30638852672750977
Delta: 0.004733267253052879 	  Loss: 1.64613125697842 	 Accuracy: 0.3089960886571056
Delta: 0.004647180654560803 	  Loss: 1.6459582078283952 	 Accuracy: 0.30638852672750977
Delta: 0.0035270255341414893 	  Loss: 1.6457093949464117 	 Accuracy: 0.29595827900912647
Delta: 0.006560727975299634 	  Loss: 1.643813503516435 	 Accuracy: 0.30247718383311606
Delta: 0.0010002650268116657 	  Loss: 1.6436814348728845 	 Accuracy: 0.3011734028683181
Delta: 0.003004606177248171 	  Loss: 1.6431623966197515 	 Accuracy: 0.29726205997392435
Delta: 0.0036544006015741164 	  Loss: 1.6435808062282597 	 Accuracy: 0.29986962190352023
Delta: 0.0036143927159318955 	  Loss: 1.6438240194744838 	 Accuracy: 0.29726205997392435
Delta: 0.0017031751882832285 	  Loss: 1.6435484211622184 	 Accuracy: 0.3011734028683181
Delta: 0.004597365986446317 	  Loss: 1.642704614186371 	 Accuracy: 0.3011734028683181
Delta: 0.0013211584159324972 	  Loss: 1.6426348437700489 	 Accuracy: 0.29986962190352023
Delta: 0.0019616721518721284 	  Loss: 1.6413522084493997 	 Accuracy: 0.30247718383311606
Delta: 0.020932478887453233 	  Loss: 2.146865133317835 	 Accuracy: 0.19947848761408082
Delta: 0.019024920626426946 	  Loss: 2.026763141035606 	 Accuracy: 0.242503259452412
Delta: 0.0178260279626126 	  Loss: 1.8162445305544261 	 Accuracy: 0.38070404172099087
Delta: 0.016328000831587856 	  Loss: 1.6732564790817959 	 Accuracy: 0.39113428943937417
Delta: 0.012611915918770797 	  Loss: 1.6291512385749152 	 Accuracy: 0.39113428943937417

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009388166099106011 	  Loss: 1.6212672462327942 	 Accuracy: 0.39504563233376794
Delta: 0.007938803159335244 	  Loss: 1.6198572931195767 	 Accuracy: 0.3898305084745763
Delta: 0.00606667578390042 	  Loss: 1.6195670543795395 	 Accuracy: 0.3898305084745763
Delta: 0.005477011835413127 	  Loss: 1.6196267430241809 	 Accuracy: 0.3859191655801825
Delta: 0.004159509867245751 	  Loss: 1.6196448659425862 	 Accuracy: 0.38722294654498046
Delta: 0.0035209255008191386 	  Loss: 1.619608051321896 	 Accuracy: 0.38852672750977835
Delta: 0.001571153598672021 	  Loss: 1.619905712714833 	 Accuracy: 0.39113428943937417
Delta: 0.0022102782043851386 	  Loss: 1.61968073977295 	 Accuracy: 0.38852672750977835
Delta: 1.968799169654906e-05 	  Loss: 1.6197031470574728 	 Accuracy: 0.39374185136897
Delta: 0.004393830449770218 	  Loss: 1.619685078995558 	 Accuracy: 0.39113428943937417
Delta: 0.0013436128591983378 	  Loss: 1.6191110764000216 	 Accuracy: 0.39113428943937417
Delta: 0.0033167560781844087 	  Loss: 1.6189253678739073 	 Accuracy: 0.3898305084745763
Delta: 0.0014625789132890654 	  Loss: 1.6189481092512281 	 Accuracy: 0.3898305084745763
Delta: 0.000691250121528589 	  Loss: 1.6190067021611656 	 Accuracy: 0.39895697522816165
Delta: 0.0021150732954167066 	  Loss: 1.6187080439949377 	 Accuracy: 0.3924380704041721
Delta: 0.0033270566984290725 	  Loss: 1.6183529818526063 	 Accuracy: 0.3898305084745763
Delta: 0.002867700185115314 	  Loss: 1.6185810808385455 	 Accuracy: 0.3924380704041721
Delta: 0.003309455404572609 	  Loss: 1.618839892058575 	 Accuracy: 0.3859191655801825
Delta: 0.001190452225501719 	  Loss: 1.6188764787781715 	 Accuracy: 0.3898305084745763
Delta: 0.000794659206741585 	  Loss: 1.6187283878315857 	 Accuracy: 0.3898305084745763
Delta: 0.003156799377292427 	  Loss: 1.6188939572470313 	 Accuracy: 0.39113428943937417
Delta: 0.0009462367424501092 	  Loss: 1.6187205716022306 	 Accuracy: 0.39113428943937417
Delta: 0.002973468987854233 	  Loss: 1.6184286730381665 	 Accuracy: 0.39113428943937417
Delta: 0.0020544950032455925 	  Loss: 1.6179626103773859 	 Accuracy: 0.36897001303780963
Delta: 4.588361675658697e-05 	  Loss: 1.6179789313778379 	 Accuracy: 0.3898305084745763
Delta: 0.001006892457363418 	  Loss: 1.6185852782867172 	 Accuracy: 0.39113428943937417
Delta: 0.0027462767192931448 	  Loss: 1.6177548440621898 	 Accuracy: 0.3767926988265971
Delta: 0.00010781650796590094 	  Loss: 1.6179511366412616 	 Accuracy: 0.38852672750977835
Delta: 0.0034724226182409404 	  Loss: 1.6172677116730885 	 Accuracy: 0.38852672750977835
Delta: 0.002111848318761565 	  Loss: 1.6174372105644155 	 Accuracy: 0.3898305084745763
Delta: 0.004058776861473494 	  Loss: 1.6181278860597614 	 Accuracy: 0.3924380704041721
Delta: 0.00387925735935344 	  Loss: 1.6178151638502616 	 Accuracy: 0.3924380704041721
Delta: 0.000806117954693967 	  Loss: 1.617874177652995 	 Accuracy: 0.3898305084745763
Delta: 0.0024317187936913824 	  Loss: 1.6176513538445028 	 Accuracy: 0.3898305084745763
Delta: 0.004623416262465766 	  Loss: 1.6158363697835059 	 Accuracy: 0.379400260756193
Delta: 0.00528190241535428 	  Loss: 1.6186746965105139 	 Accuracy: 0.39113428943937417
Delta: 0.0026129364489256147 	  Loss: 1.616759000933238 	 Accuracy: 0.38461538461538464
Delta: 0.00630214935846343 	  Loss: 1.6188443685123042 	 Accuracy: 0.38722294654498046
Delta: 0.002742889860775829 	  Loss: 1.6186163455954805 	 Accuracy: 0.38852672750977835
Delta: 0.004361273414492366 	  Loss: 1.6179717242042615 	 Accuracy: 0.38722294654498046
Delta: 0.0031885349355956745 	  Loss: 1.6180068034311796 	 Accuracy: 0.38722294654498046
Delta: 0.001457483399757306 	  Loss: 1.6185628174241526 	 Accuracy: 0.3859191655801825
Delta: 0.0018732316183935744 	  Loss: 1.618511883883437 	 Accuracy: 0.38852672750977835
Delta: 0.0035703431347540522 	  Loss: 1.6177936254495733 	 Accuracy: 0.38722294654498046
Delta: 0.002422703739687257 	  Loss: 1.6176326275043946 	 Accuracy: 0.38852672750977835
Delta: 0.00010961921599999694 	  Loss: 1.6180636229881316 	 Accuracy: 0.38852672750977835
Delta: 0.0005834290009059558 	  Loss: 1.61770813265269 	 Accuracy: 0.3898305084745763
Delta: 0.0032743034030549073 	  Loss: 1.6171222251805037 	 Accuracy: 0.3859191655801825
Delta: 0.0034724282400916333 	  Loss: 1.6173968915456465 	 Accuracy: 0.3898305084745763
Delta: 0.0022908765246051565 	  Loss: 1.617358730913817 	 Accuracy: 0.3898305084745763
Delta: 0.002611964500995727 	  Loss: 1.617617695555717 	 Accuracy: 0.39113428943937417
Delta: 0.004558733759631344 	  Loss: 1.6170059323269763 	 Accuracy: 0.38852672750977835
Delta: 0.003474453734486177 	  Loss: 1.617081215588253 	 Accuracy: 0.3898305084745763
Delta: 0.0005258179679083928 	  Loss: 1.6171664105093575 	 Accuracy: 0.3859191655801825
Delta: 4.1473219393592446e-05 	  Loss: 1.6170637006834534 	 Accuracy: 0.38852672750977835
Delta: 0.0006723130273652479 	  Loss: 1.6174665392481453 	 Accuracy: 0.3898305084745763
Delta: 0.0028109040230244373 	  Loss: 1.6174996534144368 	 Accuracy: 0.3898305084745763
Delta: 0.0027309427386262505 	  Loss: 1.6169078350417978 	 Accuracy: 0.38852672750977835
Delta: 0.0039002506527829597 	  Loss: 1.617233779004375 	 Accuracy: 0.38722294654498046
Delta: 0.0022363448461376672 	  Loss: 1.6168968957145569 	 Accuracy: 0.38722294654498046
Delta: 0.005725273582217904 	  Loss: 1.6177781470858619 	 Accuracy: 0.3898305084745763
Delta: 0.0013041650300212022 	  Loss: 1.6178670149142915 	 Accuracy: 0.39504563233376794
Delta: 0.002852911767767217 	  Loss: 1.616975463727452 	 Accuracy: 0.3963494132985658
Delta: 0.004370863283542276 	  Loss: 1.6168440389736967 	 Accuracy: 0.39374185136897
Delta: 0.0009482265684495504 	  Loss: 1.6173681503630637 	 Accuracy: 0.39374185136897
Delta: 0.00504995318518225 	  Loss: 1.6162297395602887 	 Accuracy: 0.39374185136897
Delta: 0.004360051307660681 	  Loss: 1.615518905832861 	 Accuracy: 0.3924380704041721
Delta: 0.004963598122612951 	  Loss: 1.6161952279460645 	 Accuracy: 0.39374185136897
Delta: 0.0022462880727279508 	  Loss: 1.616105484907988 	 Accuracy: 0.39374185136897
Delta: 0.0006481879450928543 	  Loss: 1.615937232517387 	 Accuracy: 0.39374185136897
Delta: 1.3802231915451227e-07 	  Loss: 1.6159373130702457 	 Accuracy: 0.3924380704041721
converged at iter  75
Delta: 0.02095181962168015 	  Loss: 2.146767709715678 	 Accuracy: 0.196870925684485
Delta: 0.018777655063250166 	  Loss: 2.0244786919819813 	 Accuracy: 0.23728813559322035
Delta: 0.01800944597418582 	  Loss: 1.8295652221854342 	 Accuracy: 0.258148631029987
Delta: 0.01612060172318805 	  Loss: 1.7144132788435478 	 Accuracy: 0.3011734028683181
Delta: 0.01371316237834443 	  Loss: 1.663969922147964 	 Accuracy: 0.31029986962190353

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010426478854134604 	  Loss: 1.6501647642309722 	 Accuracy: 0.3089960886571056
Delta: 0.007364717786186933 	  Loss: 1.6489585648400458 	 Accuracy: 0.31029986962190353
Delta: 0.005338508750730719 	  Loss: 1.6486145740803775 	 Accuracy: 0.3076923076923077
Delta: 0.0032700592438475733 	  Loss: 1.648551169460347 	 Accuracy: 0.3089960886571056
Delta: 0.0024406659566480224 	  Loss: 1.6485158684380492 	 Accuracy: 0.30638852672750977
Delta: 0.0027126850931784704 	  Loss: 1.6481669987480747 	 Accuracy: 0.30638852672750977
Delta: 0.0007676387624675331 	  Loss: 1.647997478794463 	 Accuracy: 0.30638852672750977
Delta: 0.0026260745040240035 	  Loss: 1.6482343128838395 	 Accuracy: 0.3076923076923077
Delta: 0.0015691209098232168 	  Loss: 1.6482562054295786 	 Accuracy: 0.3076923076923077
Delta: 0.001168356984198854 	  Loss: 1.6479529059901936 	 Accuracy: 0.30638852672750977
Delta: 4.9323829390444455e-05 	  Loss: 1.6481316466833387 	 Accuracy: 0.30638852672750977
Delta: 0.003659381096297257 	  Loss: 1.6484513286696014 	 Accuracy: 0.3076923076923077
Delta: 6.470745446762043e-05 	  Loss: 1.648425759953445 	 Accuracy: 0.3089960886571056
Delta: 0.003187321223758231 	  Loss: 1.6484480259321823 	 Accuracy: 0.30638852672750977
Delta: 0.0026581619233320745 	  Loss: 1.6483714961864488 	 Accuracy: 0.30638852672750977
Delta: 7.142578646975114e-05 	  Loss: 1.6484054377370303 	 Accuracy: 0.3076923076923077
Delta: 0.0016107646033228311 	  Loss: 1.6483350530557461 	 Accuracy: 0.3089960886571056
Delta: 0.001150098478734016 	  Loss: 1.648320055319516 	 Accuracy: 0.3089960886571056
Delta: 0.0025219555602471076 	  Loss: 1.648465357500755 	 Accuracy: 0.3076923076923077
Delta: 0.0013176026233802402 	  Loss: 1.6482943557999463 	 Accuracy: 0.3089960886571056
Delta: 0.0010040630120518158 	  Loss: 1.6486873923322432 	 Accuracy: 0.3155149934810952
Delta: 0.0032548024622982273 	  Loss: 1.649364783984808 	 Accuracy: 0.3076923076923077
Delta: 0.003944936621239997 	  Loss: 1.6485546220438436 	 Accuracy: 0.3116036505867014
Delta: 0.0027830816954257298 	  Loss: 1.6492811297811643 	 Accuracy: 0.31029986962190353
Delta: 0.0029070151393660857 	  Loss: 1.6490734782921947 	 Accuracy: 0.31029986962190353
Delta: 0.0031283366686576256 	  Loss: 1.6492704302122783 	 Accuracy: 0.3089960886571056
Delta: 0.0037027531476468744 	  Loss: 1.649793615941191 	 Accuracy: 0.3076923076923077
Delta: 0.0028735645930281577 	  Loss: 1.6498894212756692 	 Accuracy: 0.3076923076923077
Delta: 0.0019824834465131153 	  Loss: 1.6497536957705425 	 Accuracy: 0.3076923076923077
Delta: 0.001091380870513183 	  Loss: 1.6492397323517456 	 Accuracy: 0.3089960886571056
Delta: 0.0018704268625673516 	  Loss: 1.649324753092495 	 Accuracy: 0.3089960886571056
Delta: 0.00507300021977022 	  Loss: 1.6494522497577075 	 Accuracy: 0.30247718383311606
Delta: 0.002842573264352708 	  Loss: 1.6495412931241196 	 Accuracy: 0.3050847457627119
Delta: 0.0012050992690682517 	  Loss: 1.649494312345269 	 Accuracy: 0.3076923076923077
Delta: 0.002050429099065897 	  Loss: 1.6493987069882903 	 Accuracy: 0.30638852672750977
Delta: 0.0033431722475189924 	  Loss: 1.6498630983360338 	 Accuracy: 0.3076923076923077
Delta: 0.0042514170917776995 	  Loss: 1.649125228655623 	 Accuracy: 0.3050847457627119
Delta: 0.004829323511355094 	  Loss: 1.6481646344628957 	 Accuracy: 0.31421121251629724
Delta: 0.002589858901004227 	  Loss: 1.648485069318961 	 Accuracy: 0.3076923076923077
Delta: 0.004567644051894984 	  Loss: 1.6490089004271158 	 Accuracy: 0.3089960886571056
Delta: 0.004322067257683254 	  Loss: 1.6497031542278315 	 Accuracy: 0.31029986962190353
Delta: 0.0025056918744007332 	  Loss: 1.6498699278984272 	 Accuracy: 0.31029986962190353
Delta: 0.0019287754161632057 	  Loss: 1.6498020432380933 	 Accuracy: 0.3116036505867014
Delta: 0.003215565605482341 	  Loss: 1.6495289803270232 	 Accuracy: 0.3076923076923077
Delta: 0.003652692199603608 	  Loss: 1.6501591064801113 	 Accuracy: 0.3089960886571056
Delta: 0.0018838247545490668 	  Loss: 1.6499220737415277 	 Accuracy: 0.3089960886571056
Delta: 0.0018071251120828518 	  Loss: 1.6508632904302125 	 Accuracy: 0.30638852672750977
Delta: 0.004214701234761158 	  Loss: 1.6509621136633892 	 Accuracy: 0.3116036505867014
Delta: 0.004827210193638885 	  Loss: 1.6498891135447669 	 Accuracy: 0.31421121251629724
Delta: 0.0021295510167920586 	  Loss: 1.6498715135577044 	 Accuracy: 0.31029986962190353
Delta: 0.0015018541231951493 	  Loss: 1.6495710586516825 	 Accuracy: 0.3089960886571056
Delta: 0.003271712564864789 	  Loss: 1.6498581388232307 	 Accuracy: 0.31029986962190353
Delta: 0.0013369973838648895 	  Loss: 1.6499648822094777 	 Accuracy: 0.3116036505867014
Delta: 0.0023366441443771445 	  Loss: 1.6501170078229777 	 Accuracy: 0.3116036505867014
Delta: 0.003319412445135046 	  Loss: 1.6494871245532958 	 Accuracy: 0.3116036505867014
Delta: 0.003404800750537466 	  Loss: 1.6492176042877358 	 Accuracy: 0.32073011734028684
Delta: 0.0042076286937513425 	  Loss: 1.6494220451069048 	 Accuracy: 0.31290743155149936
Delta: 0.002785545934335681 	  Loss: 1.6493153839778476 	 Accuracy: 0.3116036505867014
Delta: 0.0005684049950577311 	  Loss: 1.6493973739655718 	 Accuracy: 0.31290743155149936
Delta: 0.0012477429912151896 	  Loss: 1.6495211307197133 	 Accuracy: 0.3155149934810952
Delta: 0.00279184410295038 	  Loss: 1.648999079499891 	 Accuracy: 0.3116036505867014
Delta: 0.003993806655174856 	  Loss: 1.6506186292661478 	 Accuracy: 0.31029986962190353
Delta: 0.0018899988348244428 	  Loss: 1.6503389163029678 	 Accuracy: 0.31029986962190353
Delta: 0.0037394628567781973 	  Loss: 1.6497030757605597 	 Accuracy: 0.3089960886571056
Delta: 0.004251844245339861 	  Loss: 1.6498256379744598 	 Accuracy: 0.31029986962190353
Delta: 0.004046009136849668 	  Loss: 1.6495080951750647 	 Accuracy: 0.3076923076923077
Delta: 0.0027584931166510034 	  Loss: 1.649544962885563 	 Accuracy: 0.31029986962190353
Delta: 0.003935727111198632 	  Loss: 1.649616714503983 	 Accuracy: 0.3116036505867014
Delta: 0.005055830891718572 	  Loss: 1.6493936196180627 	 Accuracy: 0.3116036505867014
Delta: 0.005128872609197821 	  Loss: 1.6492707644608018 	 Accuracy: 0.31029986962190353
Delta: 0.002900808314669316 	  Loss: 1.6494603164959107 	 Accuracy: 0.31029986962190353
Delta: 0.004766837966744093 	  Loss: 1.6491186725515514 	 Accuracy: 0.31029986962190353
Delta: 0.0026507272140975312 	  Loss: 1.6492399470474126 	 Accuracy: 0.31290743155149936
Delta: 0.0050948204337910785 	  Loss: 1.6500781581984802 	 Accuracy: 0.32333767926988266
Delta: 0.003998806079306871 	  Loss: 1.6490538512146244 	 Accuracy: 0.3116036505867014
Delta: 0.00013943411237829468 	  Loss: 1.6495354426860778 	 Accuracy: 0.31029986962190353
Delta: 0.0029402901250467598 	  Loss: 1.6501052642808367 	 Accuracy: 0.31290743155149936
Delta: 0.005149183003695478 	  Loss: 1.6484876037884375 	 Accuracy: 0.31290743155149936
Delta: 0.005739524091396911 	  Loss: 1.6488570352932284 	 Accuracy: 0.31681877444589307
Delta: 0.00455411658313694 	  Loss: 1.6486580869548395 	 Accuracy: 0.3116036505867014
Delta: 0.0005814663371662247 	  Loss: 1.6485190283719473 	 Accuracy: 0.31290743155149936
Delta: 0.004928877288789327 	  Loss: 1.6488543014775612 	 Accuracy: 0.31421121251629724
Delta: 0.005444978734693117 	  Loss: 1.6508186143760866 	 Accuracy: 0.31421121251629724
Delta: 0.003511695550633403 	  Loss: 1.6505383748914073 	 Accuracy: 0.31421121251629724
Delta: 0.004711999445096642 	  Loss: 1.6503072932665914 	 Accuracy: 0.31421121251629724
Delta: 0.002339466534701354 	  Loss: 1.6506099036878183 	 Accuracy: 0.3116036505867014
Delta: 0.0019655124750000965 	  Loss: 1.6507132562350357 	 Accuracy: 0.31290743155149936
Delta: 0.002640174175133832 	  Loss: 1.6503051038831271 	 Accuracy: 0.31421121251629724
Delta: 0.0025130370327618454 	  Loss: 1.6496496866438282 	 Accuracy: 0.31421121251629724
Delta: 0.001995522526191064 	  Loss: 1.6499825815227671 	 Accuracy: 0.31290743155149936
Delta: 0.004201471821061933 	  Loss: 1.6497306514281522 	 Accuracy: 0.31290743155149936
Delta: 0.0018772909069347833 	  Loss: 1.6496356068483355 	 Accuracy: 0.33116036505867014
Delta: 0.004979541763207894 	  Loss: 1.6503675446966048 	 Accuracy: 0.3155149934810952
Delta: 0.004412827774471272 	  Loss: 1.6496490704534312 	 Accuracy: 0.31290743155149936
Delta: 0.004654532370915848 	  Loss: 1.6498444468127813 	 Accuracy: 0.31421121251629724
Delta: 0.021188955858364375 	  Loss: 2.144175442619747 	 Accuracy: 0.19426336375488917
Delta: 0.018891112524559574 	  Loss: 2.000795151795879 	 Accuracy: 0.24771838331160365
Delta: 0.017304576960559554 	  Loss: 1.7885542832101038 	 Accuracy: 0.2842242503259452
Delta: 0.014433546187827476 	  Loss: 1.706970133557475 	 Accuracy: 0.29986962190352023
Delta: 0.01160744444168292 	  Loss: 1.6854111390723954 	 Accuracy: 0.29986962190352023

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008580829347127537 	  Loss: 1.6829303400316968 	 Accuracy: 0.3011734028683181
Delta: 0.0062965377605114095 	  Loss: 1.6826016227728742 	 Accuracy: 0.29986962190352023
Delta: 0.005070517755073549 	  Loss: 1.6825560895113696 	 Accuracy: 0.2985658409387223
Delta: 0.003040333095223845 	  Loss: 1.682429449507966 	 Accuracy: 0.29726205997392435
Delta: 0.0017218530669094534 	  Loss: 1.6826137311939162 	 Accuracy: 0.29726205997392435
Delta: 0.00230376409478705 	  Loss: 1.682744079258871 	 Accuracy: 0.29726205997392435
Delta: 0.0028536788019548503 	  Loss: 1.6828515732957379 	 Accuracy: 0.29986962190352023
Delta: 0.00212493084184021 	  Loss: 1.6827644916695843 	 Accuracy: 0.29726205997392435
Delta: 0.0030258939049419837 	  Loss: 1.683039285468766 	 Accuracy: 0.29726205997392435
Delta: 0.0025538257673605666 	  Loss: 1.6832031986464582 	 Accuracy: 0.29726205997392435
Delta: 0.0007334545072551339 	  Loss: 1.683017491695395 	 Accuracy: 0.29595827900912647
Delta: 0.001799473900448463 	  Loss: 1.6831542281795797 	 Accuracy: 0.29986962190352023
Delta: 0.0010105066371432036 	  Loss: 1.683351802469064 	 Accuracy: 0.2985658409387223
Delta: 0.002134751273455385 	  Loss: 1.6833271368637095 	 Accuracy: 0.29986962190352023
Delta: 0.002264839433567149 	  Loss: 1.6829089199363148 	 Accuracy: 0.2985658409387223
Delta: 0.0010928219551543396 	  Loss: 1.6832561118656861 	 Accuracy: 0.29465449804432853
Delta: 0.0013230368959487163 	  Loss: 1.683259094134296 	 Accuracy: 0.2985658409387223
Delta: 0.001217247539438278 	  Loss: 1.6832343334569089 	 Accuracy: 0.29726205997392435
Delta: 4.7612427571776695e-05 	  Loss: 1.6831333138055353 	 Accuracy: 0.29595827900912647
Delta: 0.003355357273788967 	  Loss: 1.6832065797520217 	 Accuracy: 0.2985658409387223
Delta: 0.0034921576462208755 	  Loss: 1.6829602499580485 	 Accuracy: 0.29595827900912647
Delta: 0.0025317035708124526 	  Loss: 1.6830154711358607 	 Accuracy: 0.2907431551499348
Delta: 0.0015611399232384952 	  Loss: 1.6829572689438133 	 Accuracy: 0.2985658409387223
Delta: 0.002894678998026579 	  Loss: 1.6829012385807032 	 Accuracy: 0.29726205997392435
Delta: 0.001701542670675419 	  Loss: 1.6830482807266236 	 Accuracy: 0.29595827900912647
Delta: 0.003137587440398197 	  Loss: 1.6833284142645617 	 Accuracy: 0.29595827900912647
Delta: 0.003979069651416957 	  Loss: 1.6833721495199734 	 Accuracy: 0.29726205997392435
Delta: 0.004744806602058351 	  Loss: 1.6837449060564764 	 Accuracy: 0.29726205997392435
Delta: 0.004523145879131692 	  Loss: 1.683914773689028 	 Accuracy: 0.29595827900912647
Delta: 0.004522862859908078 	  Loss: 1.6841025362353035 	 Accuracy: 0.29595827900912647
Delta: 0.0019325170347400833 	  Loss: 1.6833714415463619 	 Accuracy: 0.29595827900912647
Delta: 0.0024782672311218367 	  Loss: 1.6835363540027282 	 Accuracy: 0.29335071707953064
Delta: 0.0019692221635265383 	  Loss: 1.6835883123950026 	 Accuracy: 0.29595827900912647
Delta: 0.0020441650662517165 	  Loss: 1.683630156487828 	 Accuracy: 0.29726205997392435
Delta: 0.0025999665676670154 	  Loss: 1.684259917663891 	 Accuracy: 0.2985658409387223
Delta: 0.002460753502734375 	  Loss: 1.6840676987303533 	 Accuracy: 0.29465449804432853
Delta: 0.0019873177020717134 	  Loss: 1.6836760205943397 	 Accuracy: 0.29595827900912647
Delta: 0.0025124705593349713 	  Loss: 1.6835945966426489 	 Accuracy: 0.29465449804432853
Delta: 0.004962524516847921 	  Loss: 1.684502148566524 	 Accuracy: 0.2894393741851369
Delta: 0.005414957050330808 	  Loss: 1.6840642590376267 	 Accuracy: 0.2920469361147327
Delta: 0.005272454609083655 	  Loss: 1.6838598930462638 	 Accuracy: 0.29335071707953064
Delta: 0.0037517874843822417 	  Loss: 1.6838311033155673 	 Accuracy: 0.2907431551499348
Delta: 0.004613451897145444 	  Loss: 1.6838590740448698 	 Accuracy: 0.29335071707953064
Delta: 0.0010656346603378469 	  Loss: 1.6838994290075553 	 Accuracy: 0.29465449804432853
Delta: 0.004640895641778038 	  Loss: 1.6825658337401783 	 Accuracy: 0.29595827900912647
Delta: 0.004792259013877547 	  Loss: 1.6823613990093946 	 Accuracy: 0.29595827900912647
Delta: 0.003339104393752666 	  Loss: 1.6820778662301445 	 Accuracy: 0.29595827900912647
Delta: 0.00365159520491925 	  Loss: 1.682083965045298 	 Accuracy: 0.29595827900912647
Delta: 0.004008326250564311 	  Loss: 1.682215021983494 	 Accuracy: 0.29595827900912647
Delta: 0.00448251420660946 	  Loss: 1.6815486683202556 	 Accuracy: 0.29595827900912647
Delta: 0.003712053966345136 	  Loss: 1.6815224361027252 	 Accuracy: 0.29465449804432853
Delta: 0.004109871034485018 	  Loss: 1.6823901811110848 	 Accuracy: 0.29595827900912647
Delta: 0.002946869661350757 	  Loss: 1.6821124670199061 	 Accuracy: 0.29726205997392435
Delta: 0.0008060792466735144 	  Loss: 1.6820445306616976 	 Accuracy: 0.29726205997392435
Delta: 0.0015994957795143526 	  Loss: 1.6822230868363726 	 Accuracy: 0.29595827900912647
Delta: 0.0034389212611987243 	  Loss: 1.6821323425419126 	 Accuracy: 0.29595827900912647
Delta: 0.004441351290704779 	  Loss: 1.6817510418733492 	 Accuracy: 0.29595827900912647
Delta: 0.0032206753121323977 	  Loss: 1.6817661565786168 	 Accuracy: 0.29595827900912647
Delta: 0.004625369796309708 	  Loss: 1.6816044707673776 	 Accuracy: 0.29595827900912647
Delta: 0.0037789715159662843 	  Loss: 1.6815314681582234 	 Accuracy: 0.29465449804432853
Delta: 0.002786234444978669 	  Loss: 1.6820648520639234 	 Accuracy: 0.29726205997392435
Delta: 0.002213103189009626 	  Loss: 1.6817168539529757 	 Accuracy: 0.29465449804432853
Delta: 0.001900996886733778 	  Loss: 1.68119514351912 	 Accuracy: 0.29595827900912647
Delta: 0.002404627065875396 	  Loss: 1.682232461950174 	 Accuracy: 0.29595827900912647
Delta: 0.0019860386230064857 	  Loss: 1.6813501468858525 	 Accuracy: 0.2985658409387223
Delta: 0.00346901847798098 	  Loss: 1.6815465516696015 	 Accuracy: 0.29595827900912647
Delta: 0.0006751361411352686 	  Loss: 1.6816878928086718 	 Accuracy: 0.29595827900912647
Delta: 0.0019057206789950564 	  Loss: 1.6816098806352204 	 Accuracy: 0.29595827900912647
Delta: 0.001318823309277442 	  Loss: 1.6816541522189752 	 Accuracy: 0.2985658409387223
Delta: 0.0018458372608112698 	  Loss: 1.6816180487040966 	 Accuracy: 0.29595827900912647
Delta: 9.410538675954134e-05 	  Loss: 1.68159630909237 	 Accuracy: 0.29726205997392435
Delta: 0.0019156092560183521 	  Loss: 1.681614706088327 	 Accuracy: 0.2985658409387223
Delta: 0.004386369070599015 	  Loss: 1.6823565762012223 	 Accuracy: 0.29595827900912647
Delta: 0.0025994507472018326 	  Loss: 1.6822159764446578 	 Accuracy: 0.29726205997392435
Delta: 0.004207394298648832 	  Loss: 1.6822080353864708 	 Accuracy: 0.3011734028683181
Delta: 0.0028543193229234537 	  Loss: 1.682273506578039 	 Accuracy: 0.2985658409387223
Delta: 0.004110770654645562 	  Loss: 1.681531183724872 	 Accuracy: 0.2985658409387223
Delta: 0.003006379556614507 	  Loss: 1.6816902227258526 	 Accuracy: 0.2985658409387223
Delta: 0.0014515202204570298 	  Loss: 1.6816590284740287 	 Accuracy: 0.2985658409387223
Delta: 0.0036575741749600606 	  Loss: 1.6823260886158642 	 Accuracy: 0.2985658409387223
Delta: 0.0019021888982575783 	  Loss: 1.6822723808568767 	 Accuracy: 0.2985658409387223
Delta: 0.0007573541175096913 	  Loss: 1.6822861993805287 	 Accuracy: 0.29726205997392435
Delta: 0.003699121552916296 	  Loss: 1.6823334991389691 	 Accuracy: 0.30247718383311606
Delta: 0.005296930453825987 	  Loss: 1.6824526950945575 	 Accuracy: 0.29595827900912647
Delta: 0.002845377397155571 	  Loss: 1.682531468128392 	 Accuracy: 0.29595827900912647
Delta: 0.004847665676235097 	  Loss: 1.682367295010906 	 Accuracy: 0.29595827900912647
Delta: 0.0014503085342129928 	  Loss: 1.6823507908813342 	 Accuracy: 0.29595827900912647
Delta: 0.002136014975135459 	  Loss: 1.6817999275218278 	 Accuracy: 0.29595827900912647
Delta: 0.001200692237357794 	  Loss: 1.6825330954150837 	 Accuracy: 0.29465449804432853
Delta: 0.004303619443655474 	  Loss: 1.6832945765253162 	 Accuracy: 0.29595827900912647
Delta: 0.003270745794597081 	  Loss: 1.6822398797840357 	 Accuracy: 0.28683181225554105
Delta: 0.0005975948635318523 	  Loss: 1.6827279865052338 	 Accuracy: 0.29595827900912647
Delta: 0.002598443203956446 	  Loss: 1.6825712885491952 	 Accuracy: 0.29595827900912647
Delta: 0.0005734489585499118 	  Loss: 1.6825566077567191 	 Accuracy: 0.29726205997392435
Delta: 0.0046600701267158 	  Loss: 1.682183056093799 	 Accuracy: 0.2985658409387223
Delta: 0.02090425380588157 	  Loss: 2.159091085494067 	 Accuracy: 0.21251629726205998
Delta: 0.018541398383313402 	  Loss: 2.0826727879345865 	 Accuracy: 0.29726205997392435
Delta: 0.016198374744852286 	  Loss: 1.9726298642049471 	 Accuracy: 0.3376792698826597
Delta: 0.013776338206391282 	  Loss: 1.8643077426187722 	 Accuracy: 0.3389830508474576
Delta: 0.011784953376011981 	  Loss: 1.782319201238987 	 Accuracy: 0.31421121251629724
Delta: 0.009659933882415974 	  Loss: 1.7266300540254425 	 Accuracy: 0.30378096479791394
Delta: 0.008678940667860322 	  Loss: 1.6896131640681435 	 Accuracy: 0.29465449804432853
Delta: 0.007988878530469729 	  Loss: 1.6648449029237635 	 Accuracy: 0.29986962190352023
Delta: 0.008265275818999206 	  Loss: 1.6461766772603472 	 Accuracy: 0.29726205997392435
Delta: 0.00834240485417373 	  Loss: 1.6311101908548191 	 Accuracy: 0.30638852672750977
Delta: 0.0078363395545728 	  Loss: 1.618654005481201 	 Accuracy: 0.3089960886571056
Delta: 0.008065998266108208 	  Loss: 1.6081346030375108 	 Accuracy: 0.31029986962190353
Delta: 0.007246919665650608 	  Loss: 1.5987071668873791 	 Accuracy: 0.31290743155149936
Delta: 0.006932759226513928 	  Loss: 1.591172773081284 	 Accuracy: 0.3089960886571056
Delta: 0.005565868676403645 	  Loss: 1.5860492000807793 	 Accuracy: 0.3116036505867014
Delta: 0.0056077511983906895 	  Loss: 1.581283921878001 	 Accuracy: 0.3089960886571056
Delta: 0.005993592423245481 	  Loss: 1.5775332565022404 	 Accuracy: 0.3076923076923077
Delta: 0.005218201168068482 	  Loss: 1.574113919601187 	 Accuracy: 0.3076923076923077
Delta: 0.004022419850913535 	  Loss: 1.5713460553851697 	 Accuracy: 0.3076923076923077
Delta: 0.004800338145203417 	  Loss: 1.569381088208361 	 Accuracy: 0.30638852672750977
Delta: 0.0041407553975736176 	  Loss: 1.5676768247979234 	 Accuracy: 0.3076923076923077
Delta: 0.003930416204670146 	  Loss: 1.566265538253519 	 Accuracy: 0.3050847457627119
Delta: 0.004795837984766261 	  Loss: 1.56495425026227 	 Accuracy: 0.30638852672750977
Delta: 0.0035062960075331164 	  Loss: 1.5639374315515406 	 Accuracy: 0.3050847457627119
Delta: 0.0033418156565885693 	  Loss: 1.5630871874593881 	 Accuracy: 0.30378096479791394
Delta: 0.004307902572998676 	  Loss: 1.5623189503392658 	 Accuracy: 0.29986962190352023
Delta: 0.004126770638013735 	  Loss: 1.5615319606082134 	 Accuracy: 0.3011734028683181
Delta: 0.0027043077297475918 	  Loss: 1.560853230683294 	 Accuracy: 0.30247718383311606
Delta: 0.0040350468012198245 	  Loss: 1.5603353026163744 	 Accuracy: 0.30247718383311606
Delta: 0.0034144057245382694 	  Loss: 1.5598973593892538 	 Accuracy: 0.30247718383311606
Delta: 0.003420412536410499 	  Loss: 1.5591747816377954 	 Accuracy: 0.30247718383311606
Delta: 0.0032241774845212373 	  Loss: 1.558755877036297 	 Accuracy: 0.3011734028683181
Delta: 0.002178570459906904 	  Loss: 1.558433073389863 	 Accuracy: 0.3011734028683181
Delta: 0.0038208134279191152 	  Loss: 1.5581339602754387 	 Accuracy: 0.30247718383311606
Delta: 0.0022239782508051385 	  Loss: 1.557787944564415 	 Accuracy: 0.29986962190352023

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0023089793453833145 	  Loss: 1.5575376144921047 	 Accuracy: 0.29595827900912647
Delta: 0.0030536337359988288 	  Loss: 1.5573441821097855 	 Accuracy: 0.29726205997392435
Delta: 0.0008040372029947022 	  Loss: 1.5571468442866352 	 Accuracy: 0.29595827900912647
Delta: 0.0028198665084575385 	  Loss: 1.5571517605686123 	 Accuracy: 0.29595827900912647
Delta: 0.0033925350393149718 	  Loss: 1.5569632444866288 	 Accuracy: 0.29465449804432853
Delta: 0.0023035316029663896 	  Loss: 1.556721147998228 	 Accuracy: 0.29595827900912647
Delta: 0.000531594104449459 	  Loss: 1.5565531434294495 	 Accuracy: 0.29726205997392435
Delta: 0.0024203930962297666 	  Loss: 1.5563973684871963 	 Accuracy: 0.2985658409387223
Delta: 0.0027712614164216044 	  Loss: 1.5563274672398062 	 Accuracy: 0.29726205997392435
Delta: 0.0007161904917358927 	  Loss: 1.5562040875084608 	 Accuracy: 0.29595827900912647
Delta: 0.0034650364577998556 	  Loss: 1.5561576804526076 	 Accuracy: 0.29595827900912647
Delta: 0.001145275439254057 	  Loss: 1.5560654554605833 	 Accuracy: 0.2920469361147327
Delta: 0.002961698945283113 	  Loss: 1.5559810746494858 	 Accuracy: 0.29335071707953064
Delta: 0.001735671607726534 	  Loss: 1.5558592986364705 	 Accuracy: 0.29595827900912647
Delta: 0.0007279720231823487 	  Loss: 1.555787193156929 	 Accuracy: 0.2920469361147327
Delta: 0.000958760064737399 	  Loss: 1.5556817423572076 	 Accuracy: 0.29335071707953064
Delta: 0.0027586543083949837 	  Loss: 1.5555669606630638 	 Accuracy: 0.29465449804432853
Delta: 0.0035758135938525545 	  Loss: 1.5555329945746061 	 Accuracy: 0.29465449804432853
Delta: 0.0016336338232164334 	  Loss: 1.5554505775079819 	 Accuracy: 0.29465449804432853
Delta: 0.002756837030820071 	  Loss: 1.5553876310693187 	 Accuracy: 0.29726205997392435
Delta: 0.0018528269192551966 	  Loss: 1.5553588385388344 	 Accuracy: 0.29726205997392435
Delta: 0.0016477538669932286 	  Loss: 1.5552946654525674 	 Accuracy: 0.29595827900912647
Delta: 0.0012406134253841285 	  Loss: 1.555274203091397 	 Accuracy: 0.29465449804432853
Delta: 0.0025400449539182525 	  Loss: 1.5551655707515417 	 Accuracy: 0.2985658409387223
Delta: 0.0015898979600866506 	  Loss: 1.5551298437362915 	 Accuracy: 0.29595827900912647
Delta: 0.001404275276749789 	  Loss: 1.5551333324847376 	 Accuracy: 0.29595827900912647
Delta: 0.0010126748066886639 	  Loss: 1.5550676726878805 	 Accuracy: 0.29465449804432853
Delta: 0.001497472341630171 	  Loss: 1.5550595757448065 	 Accuracy: 0.29726205997392435
Delta: 0.0016752378099855404 	  Loss: 1.555055517669861 	 Accuracy: 0.29595827900912647
Delta: 0.0016027234104916256 	  Loss: 1.5550466800545397 	 Accuracy: 0.29595827900912647
Delta: 0.0007302052878081711 	  Loss: 1.555044896085796 	 Accuracy: 0.29465449804432853
Delta: 0.0012299599264367694 	  Loss: 1.5550190115898261 	 Accuracy: 0.29595827900912647
Delta: 0.0026084004691508066 	  Loss: 1.5549746720883042 	 Accuracy: 0.29595827900912647
Delta: 0.0011222357095723194 	  Loss: 1.5549588553632185 	 Accuracy: 0.29726205997392435
Delta: 0.0008243639848186179 	  Loss: 1.5549412027565825 	 Accuracy: 0.29465449804432853
Delta: 0.0008992234480344031 	  Loss: 1.5549020940794596 	 Accuracy: 0.29595827900912647
Delta: 0.0005218622301487212 	  Loss: 1.5548775823523453 	 Accuracy: 0.29465449804432853
Delta: 0.002117206363349194 	  Loss: 1.5548824212835926 	 Accuracy: 0.29465449804432853
Delta: 0.0014560153192882783 	  Loss: 1.5548593472429202 	 Accuracy: 0.29335071707953064
Delta: 6.377899015778776e-05 	  Loss: 1.5548537326682519 	 Accuracy: 0.29595827900912647
Delta: 0.0008130056742398726 	  Loss: 1.5548298057600973 	 Accuracy: 0.29595827900912647
Delta: 0.0006342525254772708 	  Loss: 1.5548186866615106 	 Accuracy: 0.29726205997392435
Delta: 0.002664810708518873 	  Loss: 1.5548113079589339 	 Accuracy: 0.29465449804432853
Delta: 0.0009503102464376856 	  Loss: 1.5547889082049582 	 Accuracy: 0.29595827900912647
Delta: 0.000539635306982502 	  Loss: 1.5547580053845715 	 Accuracy: 0.29595827900912647
Delta: 0.0008842651313288229 	  Loss: 1.5547293549653696 	 Accuracy: 0.29726205997392435
Delta: 0.0008097415446145692 	  Loss: 1.5547329854670808 	 Accuracy: 0.29595827900912647
Delta: 0.0024174668903414707 	  Loss: 1.554710639405521 	 Accuracy: 0.29595827900912647
Delta: 0.0017300196731967893 	  Loss: 1.5547224265705588 	 Accuracy: 0.29595827900912647
Delta: 0.0009368259801800238 	  Loss: 1.5547084157658713 	 Accuracy: 0.29465449804432853
Delta: 0.002740013704681251 	  Loss: 1.5546515508597096 	 Accuracy: 0.29465449804432853
Delta: 0.0005335093874195464 	  Loss: 1.5546013015551727 	 Accuracy: 0.29465449804432853
Delta: 0.0020380252626274863 	  Loss: 1.5546085320732035 	 Accuracy: 0.29726205997392435
Delta: 0.0005371833802651258 	  Loss: 1.5546095365529102 	 Accuracy: 0.29465449804432853
Delta: 1.7783027462761095e-05 	  Loss: 1.554611332504546 	 Accuracy: 0.29465449804432853
Delta: 2.6470606426177485e-05 	  Loss: 1.5545995567186472 	 Accuracy: 0.29726205997392435
Delta: 0.0008139377481890274 	  Loss: 1.554600825976768 	 Accuracy: 0.29465449804432853
Delta: 3.292775612387262e-05 	  Loss: 1.5545913066482235 	 Accuracy: 0.29595827900912647
Delta: 0.000525474239579956 	  Loss: 1.5545731286823754 	 Accuracy: 0.29335071707953064
Delta: 0.00278930850698166 	  Loss: 1.5545222954883566 	 Accuracy: 0.29465449804432853
Delta: 0.0016313874323568363 	  Loss: 1.5544433624579859 	 Accuracy: 0.29595827900912647
Delta: 5.0413233786217626e-05 	  Loss: 1.5544462115787319 	 Accuracy: 0.29335071707953064
Delta: 0.0010263193037246124 	  Loss: 1.5544342420125572 	 Accuracy: 0.29595827900912647
Delta: 0.002028665260318697 	  Loss: 1.5544368612181536 	 Accuracy: 0.29595827900912647
Delta: 0.0029081061149488566 	  Loss: 1.5544114068709654 	 Accuracy: 0.29595827900912647
Delta: 0.02095020941646766 	  Loss: 2.1584658888510013 	 Accuracy: 0.20860495436766624
Delta: 0.01838690735601356 	  Loss: 2.0805391741237456 	 Accuracy: 0.2620599739243807
Delta: 0.016412942869973256 	  Loss: 1.9584936669597244 	 Accuracy: 0.31681877444589307
Delta: 0.014504086735450675 	  Loss: 1.8361450110886952 	 Accuracy: 0.3389830508474576
Delta: 0.011899921494713443 	  Loss: 1.7395662312325935 	 Accuracy: 0.32985658409387225
Delta: 0.010554790584341806 	  Loss: 1.6757014195783722 	 Accuracy: 0.29726205997392435
Delta: 0.00894755421766419 	  Loss: 1.6359224413260924 	 Accuracy: 0.29335071707953064
Delta: 0.00825064520262747 	  Loss: 1.6111937418790019 	 Accuracy: 0.3050847457627119
Delta: 0.00704918602849821 	  Loss: 1.5966828912131783 	 Accuracy: 0.3116036505867014
Delta: 0.006476110174401141 	  Loss: 1.5874676696040546 	 Accuracy: 0.3220338983050847
Delta: 0.006457446898694378 	  Loss: 1.5809246950289928 	 Accuracy: 0.3285528031290743
Delta: 0.005487925590629628 	  Loss: 1.5763671391332026 	 Accuracy: 0.3350717079530639
Delta: 0.006074648670211144 	  Loss: 1.5731079931376737 	 Accuracy: 0.3350717079530639
Delta: 0.004977763723006693 	  Loss: 1.570430820979344 	 Accuracy: 0.3350717079530639
Delta: 0.004370966719930318 	  Loss: 1.5689751166080907 	 Accuracy: 0.3428943937418514
Delta: 0.004331331627740182 	  Loss: 1.567355371487991 	 Accuracy: 0.34159061277705344

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004908755169273212 	  Loss: 1.5658902645035822 	 Accuracy: 0.34419817470664926
Delta: 0.003933728302600484 	  Loss: 1.5645504746159191 	 Accuracy: 0.3389830508474576
Delta: 0.003554028099854556 	  Loss: 1.5638559255595068 	 Accuracy: 0.3389830508474576
Delta: 0.0034843258922846072 	  Loss: 1.563266358837851 	 Accuracy: 0.34159061277705344
Delta: 0.0043081677158347586 	  Loss: 1.562635826397527 	 Accuracy: 0.3468057366362451
Delta: 0.004199488860850312 	  Loss: 1.562330198064532 	 Accuracy: 0.3389830508474576
Delta: 0.004039982544126166 	  Loss: 1.5615896657052901 	 Accuracy: 0.3428943937418514
Delta: 0.003233110818372512 	  Loss: 1.561225976130954 	 Accuracy: 0.3455019556714472
Delta: 0.004576071014330362 	  Loss: 1.5608334185859576 	 Accuracy: 0.3468057366362451
Delta: 0.0031567186686764287 	  Loss: 1.5606167812254699 	 Accuracy: 0.34810951760104303
Delta: 0.002562025285858644 	  Loss: 1.560389595641571 	 Accuracy: 0.3468057366362451
Delta: 0.003164751827038509 	  Loss: 1.5601770292722539 	 Accuracy: 0.34810951760104303
Delta: 0.0032755835493087984 	  Loss: 1.559984677820207 	 Accuracy: 0.34810951760104303
Delta: 0.0010467192737251747 	  Loss: 1.5598287187303144 	 Accuracy: 0.34810951760104303
Delta: 0.0034647261707970926 	  Loss: 1.5597803605998524 	 Accuracy: 0.34810951760104303
Delta: 0.002471382926425948 	  Loss: 1.5598294919825957 	 Accuracy: 0.34810951760104303
Delta: 0.0024371088469523757 	  Loss: 1.5597935225451418 	 Accuracy: 0.3468057366362451
Delta: 0.0018054441028069227 	  Loss: 1.559785893097106 	 Accuracy: 0.3468057366362451
Delta: 0.0022313296178081473 	  Loss: 1.559699765111096 	 Accuracy: 0.3455019556714472
Delta: 0.0030715278999714603 	  Loss: 1.5596550811003613 	 Accuracy: 0.34810951760104303
Delta: 0.0017365232002121169 	  Loss: 1.559617747810805 	 Accuracy: 0.34810951760104303
Delta: 0.000975907969187088 	  Loss: 1.559537549614701 	 Accuracy: 0.34419817470664926
Delta: 0.0027924630895109206 	  Loss: 1.5594148909904297 	 Accuracy: 0.3455019556714472
Delta: 0.0005292238175364188 	  Loss: 1.5594129396184995 	 Accuracy: 0.34419817470664926
Delta: 0.0009666637801732547 	  Loss: 1.5594014581556301 	 Accuracy: 0.34419817470664926
Delta: 0.002538745379893395 	  Loss: 1.55946682695954 	 Accuracy: 0.3468057366362451
Delta: 0.0016933105802410743 	  Loss: 1.5594315981325197 	 Accuracy: 0.3455019556714472
Delta: 0.0005263913114380459 	  Loss: 1.559431260737954 	 Accuracy: 0.3455019556714472
Delta: 0.0020991785583747953 	  Loss: 1.5594729511641345 	 Accuracy: 0.3455019556714472
Delta: 0.0028383196771770845 	  Loss: 1.5594413066988744 	 Accuracy: 0.3455019556714472
Delta: 0.001733550061323345 	  Loss: 1.5594784329045974 	 Accuracy: 0.3468057366362451
Delta: 0.0007354235983699136 	  Loss: 1.5595198611499566 	 Accuracy: 0.34419817470664926
Delta: 0.0012712311409457694 	  Loss: 1.5595834433528133 	 Accuracy: 0.3468057366362451
Delta: 0.002072693374467147 	  Loss: 1.5595592656054402 	 Accuracy: 0.3455019556714472
Delta: 5.4676992944637424e-05 	  Loss: 1.559555570014417 	 Accuracy: 0.34419817470664926
Delta: 0.000806142812682925 	  Loss: 1.5595579988271062 	 Accuracy: 0.34419817470664926
Delta: 0.0014428658641917344 	  Loss: 1.559621807244685 	 Accuracy: 0.3468057366362451
Delta: 0.0031445576703580413 	  Loss: 1.5597009160363324 	 Accuracy: 0.34419817470664926
Delta: 0.002273388273576739 	  Loss: 1.5595728232543853 	 Accuracy: 0.34419817470664926
Delta: 0.0005429583770254771 	  Loss: 1.559503908385953 	 Accuracy: 0.3455019556714472
Delta: 0.0012318762658549655 	  Loss: 1.5595378273630431 	 Accuracy: 0.34419817470664926
Delta: 0.0011291837551455513 	  Loss: 1.5595268268788929 	 Accuracy: 0.34419817470664926
Delta: 0.0014878689963665895 	  Loss: 1.5596905916031665 	 Accuracy: 0.34810951760104303
Delta: 0.0032384832700463086 	  Loss: 1.5597947693846703 	 Accuracy: 0.3428943937418514
Delta: 0.0011285796296334825 	  Loss: 1.5598812717758062 	 Accuracy: 0.3455019556714472
Delta: 0.0007687185441516575 	  Loss: 1.559813140560367 	 Accuracy: 0.34028683181225555
Delta: 0.001668956092533192 	  Loss: 1.5598995501858761 	 Accuracy: 0.34419817470664926
Delta: 0.0009814122182328772 	  Loss: 1.5598909735942716 	 Accuracy: 0.34419817470664926
Delta: 0.0019252548551167929 	  Loss: 1.5597297674083879 	 Accuracy: 0.34419817470664926
Delta: 0.0022716401264098844 	  Loss: 1.5596785545593765 	 Accuracy: 0.3455019556714472
Delta: 0.001560193279952908 	  Loss: 1.5602007452703153 	 Accuracy: 0.3455019556714472
Delta: 0.0032347591155608394 	  Loss: 1.5602134811566506 	 Accuracy: 0.34419817470664926
Delta: 0.0025744914403741286 	  Loss: 1.5602384578908044 	 Accuracy: 0.3455019556714472
Delta: 0.0035188536144298253 	  Loss: 1.5608537500410224 	 Accuracy: 0.3455019556714472
Delta: 0.00014026860414776668 	  Loss: 1.5608924451523751 	 Accuracy: 0.3455019556714472
Delta: 0.00014082606042749795 	  Loss: 1.5604807528581424 	 Accuracy: 0.3468057366362451
Delta: 0.0014723505409885533 	  Loss: 1.5605360751354747 	 Accuracy: 0.3455019556714472
Delta: 3.45927742643148e-05 	  Loss: 1.560551451563838 	 Accuracy: 0.3455019556714472
Delta: 0.0017955007362904327 	  Loss: 1.5606020414589812 	 Accuracy: 0.3455019556714472
Delta: 2.837810360201939e-05 	  Loss: 1.5605467753121194 	 Accuracy: 0.3428943937418514
Delta: 0.0037379696870572508 	  Loss: 1.5605802820623076 	 Accuracy: 0.34419817470664926
Delta: 0.003095637119456779 	  Loss: 1.5598335603831 	 Accuracy: 0.3428943937418514
Delta: 0.0025489486308439098 	  Loss: 1.5597679268321167 	 Accuracy: 0.3428943937418514
Delta: 2.3538691168950273e-05 	  Loss: 1.5597145785971105 	 Accuracy: 0.3428943937418514
Delta: 1.8648498025281627e-05 	  Loss: 1.559763989787599 	 Accuracy: 0.3428943937418514
Delta: 0.0009009876370730873 	  Loss: 1.5598242415417942 	 Accuracy: 0.34159061277705344
Delta: 7.70077109215042e-05 	  Loss: 1.5601421118901053 	 Accuracy: 0.3428943937418514
Delta: 0.0013660162432963313 	  Loss: 1.559586886575552 	 Accuracy: 0.3428943937418514
Delta: 0.002135650067393885 	  Loss: 1.5597986103944521 	 Accuracy: 0.3428943937418514
Delta: 0.0008010696262515947 	  Loss: 1.5598494799161942 	 Accuracy: 0.3428943937418514
Delta: 0.0005394728908434476 	  Loss: 1.5597574289974145 	 Accuracy: 0.3389830508474576
Delta: 0.0005447318232573284 	  Loss: 1.559984270852648 	 Accuracy: 0.3428943937418514
Delta: 3.802309298628495e-05 	  Loss: 1.5597893062434225 	 Accuracy: 0.34159061277705344
Delta: 0.001082690779492999 	  Loss: 1.559946057786951 	 Accuracy: 0.34028683181225555
Delta: 0.0010798768020850364 	  Loss: 1.559978303551814 	 Accuracy: 0.3428943937418514
Delta: 0.0006689739286711014 	  Loss: 1.5596233276041394 	 Accuracy: 0.3428943937418514
Delta: 0.0008768025302365723 	  Loss: 1.5595949476913356 	 Accuracy: 0.3428943937418514
Delta: 0.0008810475618155044 	  Loss: 1.5596999914519647 	 Accuracy: 0.3428943937418514
Delta: 3.0834972605172314e-05 	  Loss: 1.559653710302166 	 Accuracy: 0.3428943937418514
Delta: 0.0016257686308235595 	  Loss: 1.5598562997823737 	 Accuracy: 0.3428943937418514
Delta: 1.9649420728100624e-05 	  Loss: 1.5599014531557107 	 Accuracy: 0.3428943937418514
Delta: 0.000543353239773627 	  Loss: 1.5596360538093834 	 Accuracy: 0.3428943937418514
Delta: 3.700936860413381e-05 	  Loss: 1.559590337185575 	 Accuracy: 0.3428943937418514
Delta: 0.0005221660892058634 	  Loss: 1.5597870576099813 	 Accuracy: 0.3428943937418514
Delta: 0.02086990723422256 	  Loss: 2.159354493716248 	 Accuracy: 0.19556714471968709
Delta: 0.018492809548137645 	  Loss: 2.0800312023938967 	 Accuracy: 0.23728813559322035
Delta: 0.01688568761421768 	  Loss: 1.9516375476877315 	 Accuracy: 0.2816166883963494
Delta: 0.015019618713267796 	  Loss: 1.818241420736285 	 Accuracy: 0.2803129074315515
Delta: 0.012637277235277643 	  Loss: 1.7158698151138458 	 Accuracy: 0.26988265971316816
Delta: 0.010467435281508935 	  Loss: 1.6523313175280119 	 Accuracy: 0.2620599739243807
Delta: 0.00860176946292369 	  Loss: 1.6181830599408555 	 Accuracy: 0.2607561929595828
Delta: 0.0074411348104900755 	  Loss: 1.59921479135497 	 Accuracy: 0.2516297262059974
Delta: 0.007107209341529658 	  Loss: 1.5881307366491049 	 Accuracy: 0.24119947848761408
Delta: 0.006523462568006564 	  Loss: 1.581255915234327 	 Accuracy: 0.23598435462842243
Delta: 0.005788764510875762 	  Loss: 1.5770383403513428 	 Accuracy: 0.23468057366362452
Delta: 0.004949941846973533 	  Loss: 1.5744017228864697 	 Accuracy: 0.23468057366362452
Delta: 0.004864617428569005 	  Loss: 1.572737214358307 	 Accuracy: 0.22033898305084745
Delta: 0.004449595654607771 	  Loss: 1.5717082662686706 	 Accuracy: 0.2255541069100391
Delta: 0.004035644538430824 	  Loss: 1.5711507786503933 	 Accuracy: 0.22033898305084745
Delta: 0.004580060801384908 	  Loss: 1.570682352413617 	 Accuracy: 0.21773142112125163

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0035816486201440648 	  Loss: 1.5703508213581387 	 Accuracy: 0.21773142112125163
Delta: 0.003137004224515175 	  Loss: 1.5700933674431101 	 Accuracy: 0.21642764015645372
Delta: 0.0031171703107661796 	  Loss: 1.5699249676968745 	 Accuracy: 0.21642764015645372
Delta: 0.0035692172631878374 	  Loss: 1.5698442015149148 	 Accuracy: 0.21773142112125163
Delta: 0.00286291911388282 	  Loss: 1.5698487771508458 	 Accuracy: 0.2151238591916558
Delta: 0.0009127002650836303 	  Loss: 1.5697921898893483 	 Accuracy: 0.2138200782268579
Delta: 0.003025586405174225 	  Loss: 1.5697358719155603 	 Accuracy: 0.21773142112125163
Delta: 0.0032642818823679 	  Loss: 1.5697623533438327 	 Accuracy: 0.21773142112125163
Delta: 0.0033011682037941024 	  Loss: 1.5698091356595993 	 Accuracy: 0.21773142112125163
Delta: 0.0023509354923818408 	  Loss: 1.5697564128349484 	 Accuracy: 0.21773142112125163
Delta: 0.000921784120115525 	  Loss: 1.5697595169340592 	 Accuracy: 0.21773142112125163
Delta: 0.001539267948346278 	  Loss: 1.569761233323315 	 Accuracy: 0.21773142112125163
Delta: 0.0021340217358507426 	  Loss: 1.5697396917645872 	 Accuracy: 0.21773142112125163
Delta: 0.0008108806409894143 	  Loss: 1.569745862241891 	 Accuracy: 0.21642764015645372
Delta: 1.6012454448550096e-05 	  Loss: 1.569755027598537 	 Accuracy: 0.21642764015645372
Delta: 0.0009960956748028141 	  Loss: 1.5697584281684551 	 Accuracy: 0.21773142112125163
Delta: 0.0011359626133165084 	  Loss: 1.5697422432329637 	 Accuracy: 0.21773142112125163
Delta: 1.9333095141661103e-05 	  Loss: 1.5697568590898783 	 Accuracy: 0.21773142112125163
Delta: 0.0005138056380962883 	  Loss: 1.5697840758236286 	 Accuracy: 0.21773142112125163
Delta: 2.7923331629624085e-05 	  Loss: 1.5697569300776968 	 Accuracy: 0.21773142112125163
Delta: 0.0007309761208496669 	  Loss: 1.5697850694027322 	 Accuracy: 0.21773142112125163
Delta: 0.0021064141340293475 	  Loss: 1.569767974061012 	 Accuracy: 0.21773142112125163
Delta: 1.9370857627354153e-05 	  Loss: 1.569729647539121 	 Accuracy: 0.21773142112125163
Delta: 1.3200295801470861e-05 	  Loss: 1.5697394595993925 	 Accuracy: 0.21773142112125163
Delta: 0.0015418168705517187 	  Loss: 1.5697460118479527 	 Accuracy: 0.21773142112125163
Delta: 0.0021613364239553056 	  Loss: 1.5698971415964382 	 Accuracy: 0.21773142112125163
Delta: 0.001376437119507004 	  Loss: 1.5696866429131382 	 Accuracy: 0.21773142112125163
Delta: 3.301165277217506e-05 	  Loss: 1.5696989336742775 	 Accuracy: 0.21773142112125163
Delta: 0.00152547683520342 	  Loss: 1.569638564580558 	 Accuracy: 0.21773142112125163
Delta: 0.000969143891325171 	  Loss: 1.5696924605382974 	 Accuracy: 0.21773142112125163
Delta: 0.0005059546107964737 	  Loss: 1.569698969980906 	 Accuracy: 0.21773142112125163
Delta: 0.0008279615226864169 	  Loss: 1.569652684955321 	 Accuracy: 0.21773142112125163
Delta: 5.087818485213268e-05 	  Loss: 1.5696879919637836 	 Accuracy: 0.21773142112125163
Delta: 0.000655142459496556 	  Loss: 1.5695266795520173 	 Accuracy: 0.21773142112125163
Delta: 7.776488537602072e-05 	  Loss: 1.5694314991971394 	 Accuracy: 0.21773142112125163
Delta: 0.000551350891585695 	  Loss: 1.5696466570688412 	 Accuracy: 0.21773142112125163
Delta: 0.0005378358152588652 	  Loss: 1.569707449120402 	 Accuracy: 0.21773142112125163
Delta: 0.0038451169991287623 	  Loss: 1.5700152259180933 	 Accuracy: 0.21642764015645372
Delta: 0.0015239574208256495 	  Loss: 1.5702023934463798 	 Accuracy: 0.21903520208604954
Delta: 0.0029135075657851137 	  Loss: 1.5699866215994323 	 Accuracy: 0.21773142112125163
Delta: 0.001502042825503717 	  Loss: 1.570170980016341 	 Accuracy: 0.21903520208604954
Delta: 0.0017444071058445702 	  Loss: 1.5699611101162851 	 Accuracy: 0.21773142112125163
Delta: 0.0029230318773630524 	  Loss: 1.5698132012821806 	 Accuracy: 0.21773142112125163
Delta: 0.0023166348679438155 	  Loss: 1.5697915745605004 	 Accuracy: 0.21773142112125163
Delta: 0.0014171514419986668 	  Loss: 1.5697812681622572 	 Accuracy: 0.21642764015645372
Delta: 0.0013471183377998584 	  Loss: 1.5700321072659216 	 Accuracy: 0.21773142112125163
Delta: 0.0024800428092577823 	  Loss: 1.5700952393916625 	 Accuracy: 0.21773142112125163
Delta: 0.0017830352939383794 	  Loss: 1.5700681794365652 	 Accuracy: 0.21773142112125163
Delta: 0.0009419471829151257 	  Loss: 1.5700521335689055 	 Accuracy: 0.2151238591916558
Delta: 0.0019803981942674576 	  Loss: 1.569993807702992 	 Accuracy: 0.21773142112125163
Delta: 0.003296066675438975 	  Loss: 1.570143141136979 	 Accuracy: 0.21773142112125163
Delta: 0.0031068008030173395 	  Loss: 1.5701269781720086 	 Accuracy: 0.21773142112125163
Delta: 0.001906214591296635 	  Loss: 1.5701552641785053 	 Accuracy: 0.2151238591916558
Delta: 0.0024198065927837544 	  Loss: 1.570308575411938 	 Accuracy: 0.21642764015645372
Delta: 0.0022402106577614008 	  Loss: 1.5704075230470005 	 Accuracy: 0.21773142112125163
Delta: 4.368346136974982e-05 	  Loss: 1.5705569219367876 	 Accuracy: 0.21642764015645372
Delta: 0.0005775291498709081 	  Loss: 1.5704591698935837 	 Accuracy: 0.21773142112125163
Delta: 0.0028880090715990513 	  Loss: 1.5703188307691336 	 Accuracy: 0.21773142112125163
Delta: 0.0018006944421323902 	  Loss: 1.5701896021429387 	 Accuracy: 0.21642764015645372
Delta: 0.0005223797037582011 	  Loss: 1.5703019453835099 	 Accuracy: 0.21642764015645372
Delta: 0.0007142446994230236 	  Loss: 1.570280808541538 	 Accuracy: 0.21773142112125163
Delta: 0.001801977306939579 	  Loss: 1.5705657661004366 	 Accuracy: 0.21773142112125163
Delta: 0.001604489624223632 	  Loss: 1.570253962271296 	 Accuracy: 0.21773142112125163
Delta: 0.0012089832592603396 	  Loss: 1.570271893626132 	 Accuracy: 0.21773142112125163
Delta: 5.349021196193671e-05 	  Loss: 1.570251839136573 	 Accuracy: 0.21773142112125163
Delta: 0.00131664934807051 	  Loss: 1.5701535881955322 	 Accuracy: 0.21773142112125163
Delta: 0.0007661258088963128 	  Loss: 1.5703869983226721 	 Accuracy: 0.21773142112125163
Delta: 3.147931477918077e-05 	  Loss: 1.5701856596438297 	 Accuracy: 0.21773142112125163
Delta: 2.8343082675979184e-05 	  Loss: 1.5702608945510388 	 Accuracy: 0.21773142112125163
Delta: 0.0011223326650456008 	  Loss: 1.570174045309495 	 Accuracy: 0.21773142112125163
Delta: 2.9148230332235933e-05 	  Loss: 1.5702738205868305 	 Accuracy: 0.21773142112125163
Delta: 0.001154947398522537 	  Loss: 1.5702254424055626 	 Accuracy: 0.21773142112125163
Delta: 0.0007647022076252479 	  Loss: 1.570189783240006 	 Accuracy: 0.21773142112125163
Delta: 0.0023297038990810143 	  Loss: 1.5701536458911933 	 Accuracy: 0.21642764015645372
Delta: 0.0020999126543482854 	  Loss: 1.5702149890096817 	 Accuracy: 0.21773142112125163
Delta: 4.225650200943937e-05 	  Loss: 1.570244894766454 	 Accuracy: 0.21773142112125163
Delta: 0.001972291799255007 	  Loss: 1.570166011895405 	 Accuracy: 0.21773142112125163
Delta: 0.001277946151961923 	  Loss: 1.5701251035822648 	 Accuracy: 0.21773142112125163
Delta: 6.256497810860756e-05 	  Loss: 1.5704652269160733 	 Accuracy: 0.21642764015645372
Delta: 2.5423084087824533e-05 	  Loss: 1.5703890262000786 	 Accuracy: 0.21773142112125163
Delta: 0.002362807916609918 	  Loss: 1.5699886814994646 	 Accuracy: 0.21773142112125163
Delta: 0.004055916002248226 	  Loss: 1.569692355992101 	 Accuracy: 0.21773142112125163
Delta: 0.0006321501421529661 	  Loss: 1.5697121568892982 	 Accuracy: 0.21773142112125163
Delta: 0.0006610676224109102 	  Loss: 1.5699988009031376 	 Accuracy: 0.21773142112125163
Delta: 0.02087820968909244 	  Loss: 2.1589283638956402 	 Accuracy: 0.19295958279009126
Delta: 0.018629297299624918 	  Loss: 2.071294937716247 	 Accuracy: 0.21642764015645372
Delta: 0.016312009344637314 	  Loss: 1.9318009442915363 	 Accuracy: 0.26727509778357234
Delta: 0.01451407197335008 	  Loss: 1.7995941377850093 	 Accuracy: 0.2842242503259452
Delta: 0.01274589674781156 	  Loss: 1.7109289794469764 	 Accuracy: 0.28552803129074317
Delta: 0.012420053759371245 	  Loss: 1.6543036087922616 	 Accuracy: 0.2920469361147327
Delta: 0.011630613392704584 	  Loss: 1.6166628647952637 	 Accuracy: 0.29465449804432853
Delta: 0.009849683286696906 	  Loss: 1.5919885230061093 	 Accuracy: 0.3011734028683181
Delta: 0.008691679418883604 	  Loss: 1.57650146345966 	 Accuracy: 0.30247718383311606
Delta: 0.0076611766669481395 	  Loss: 1.5679519554213996 	 Accuracy: 0.30378096479791394
Delta: 0.006161424335449803 	  Loss: 1.5626755061896112 	 Accuracy: 0.3050847457627119

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005793167241069512 	  Loss: 1.5594908233924647 	 Accuracy: 0.3076923076923077
Delta: 0.005176851605177729 	  Loss: 1.558324659048442 	 Accuracy: 0.30638852672750977
Delta: 0.0048321690319172335 	  Loss: 1.55654723250956 	 Accuracy: 0.30638852672750977
Delta: 0.00434419439622845 	  Loss: 1.5559347656754314 	 Accuracy: 0.3076923076923077
Delta: 0.004918896650713849 	  Loss: 1.5554455156551799 	 Accuracy: 0.30638852672750977
Delta: 0.003079182744260633 	  Loss: 1.5552729884407102 	 Accuracy: 0.30638852672750977
Delta: 0.003259241968083315 	  Loss: 1.5552856106049193 	 Accuracy: 0.3076923076923077
Delta: 0.0031778444723121395 	  Loss: 1.555064134624791 	 Accuracy: 0.30638852672750977
Delta: 0.0020128261750442067 	  Loss: 1.554989329483953 	 Accuracy: 0.3076923076923077
Delta: 0.0017960387449281051 	  Loss: 1.554910750178152 	 Accuracy: 0.3076923076923077
Delta: 4.659101954262181e-05 	  Loss: 1.554865689145577 	 Accuracy: 0.3076923076923077
Delta: 0.0028637525410198012 	  Loss: 1.5548048643790477 	 Accuracy: 0.3076923076923077
Delta: 4.7834776813728085e-05 	  Loss: 1.5548130863237943 	 Accuracy: 0.3076923076923077
Delta: 0.000533783973868342 	  Loss: 1.554681061025612 	 Accuracy: 0.3076923076923077
Delta: 0.0017600202048299012 	  Loss: 1.5548255943929277 	 Accuracy: 0.3076923076923077
Delta: 0.0006418084242101035 	  Loss: 1.5546303781379263 	 Accuracy: 0.3076923076923077
Delta: 0.0022357357296790455 	  Loss: 1.5544944757188235 	 Accuracy: 0.3076923076923077
Delta: 0.0007167788714946915 	  Loss: 1.5545537591209952 	 Accuracy: 0.3076923076923077
Delta: 5.338882051664252e-05 	  Loss: 1.5544486225342702 	 Accuracy: 0.3076923076923077
Delta: 0.0021120605255199785 	  Loss: 1.5543636874670743 	 Accuracy: 0.3076923076923077
Delta: 0.002235905941324024 	  Loss: 1.5542653020080728 	 Accuracy: 0.3076923076923077
Delta: 0.0009058165951878549 	  Loss: 1.5544801638368548 	 Accuracy: 0.3076923076923077
Delta: 6.188899448785822e-05 	  Loss: 1.5543509690932822 	 Accuracy: 0.3076923076923077
Delta: 4.366349577806506e-05 	  Loss: 1.554242612029491 	 Accuracy: 0.3076923076923077
Delta: 2.959462611820206e-05 	  Loss: 1.5543393529060552 	 Accuracy: 0.3076923076923077
Delta: 4.381617114903085e-05 	  Loss: 1.5544773134172454 	 Accuracy: 0.3076923076923077
Delta: 8.405029479148544e-05 	  Loss: 1.5540288658327657 	 Accuracy: 0.30638852672750977
Delta: 0.0006356667030653171 	  Loss: 1.554172777425528 	 Accuracy: 0.30638852672750977
Delta: 0.0019500137185912497 	  Loss: 1.5542647639705793 	 Accuracy: 0.30638852672750977
Delta: 0.0028102317008304764 	  Loss: 1.5545775832495836 	 Accuracy: 0.3076923076923077
Delta: 0.002497144229205214 	  Loss: 1.5541824404151932 	 Accuracy: 0.3076923076923077
Delta: 0.002022577224872583 	  Loss: 1.5541219521968457 	 Accuracy: 0.3076923076923077
Delta: 3.1339605874043555e-05 	  Loss: 1.554080323236052 	 Accuracy: 0.30638852672750977
Delta: 0.0008938631747009913 	  Loss: 1.5541568886185697 	 Accuracy: 0.3076923076923077
Delta: 0.0010516400281825444 	  Loss: 1.5541864919314492 	 Accuracy: 0.30638852672750977
Delta: 0.0005599232443986915 	  Loss: 1.5542348302924516 	 Accuracy: 0.3076923076923077
Delta: 0.0005740797552177764 	  Loss: 1.5539471256409763 	 Accuracy: 0.3050847457627119
Delta: 0.00010672653760914032 	  Loss: 1.5543859374772535 	 Accuracy: 0.30638852672750977
Delta: 0.0020149695047888224 	  Loss: 1.5545827585628378 	 Accuracy: 0.30638852672750977
Delta: 0.001182556558514235 	  Loss: 1.5543222409416328 	 Accuracy: 0.30638852672750977
Delta: 0.002110418102370183 	  Loss: 1.5547914906994968 	 Accuracy: 0.30638852672750977
Delta: 0.0007723647091690943 	  Loss: 1.5542953977191925 	 Accuracy: 0.30638852672750977
Delta: 0.002828221928990362 	  Loss: 1.5544461874940114 	 Accuracy: 0.30638852672750977
Delta: 0.0009416580496018734 	  Loss: 1.5545216384161735 	 Accuracy: 0.3050847457627119
Delta: 0.0016941586824651294 	  Loss: 1.5544384931048014 	 Accuracy: 0.30638852672750977
Delta: 0.0027011682174848716 	  Loss: 1.5547799413160819 	 Accuracy: 0.30638852672750977
Delta: 0.002094575585149719 	  Loss: 1.5546166195751492 	 Accuracy: 0.30378096479791394
Delta: 0.002423005339914771 	  Loss: 1.5548688892199933 	 Accuracy: 0.30638852672750977
Delta: 0.0034390410057430665 	  Loss: 1.5557915418351054 	 Accuracy: 0.3076923076923077
Delta: 0.0025292225493558957 	  Loss: 1.5550251693435193 	 Accuracy: 0.30638852672750977
Delta: 0.0019107044027340473 	  Loss: 1.5548899191031307 	 Accuracy: 0.30638852672750977
Delta: 0.002391535691313536 	  Loss: 1.5544991730508766 	 Accuracy: 0.3050847457627119
Delta: 0.0029612685050711346 	  Loss: 1.554806155229216 	 Accuracy: 0.3050847457627119
Delta: 0.0015913796950078078 	  Loss: 1.5548923051350314 	 Accuracy: 0.3050847457627119
Delta: 0.0008701559922412213 	  Loss: 1.5548654906324897 	 Accuracy: 0.3050847457627119
Delta: 0.0010812596185502048 	  Loss: 1.5548057423268329 	 Accuracy: 0.3050847457627119
Delta: 0.0013103499515409443 	  Loss: 1.5549162376258732 	 Accuracy: 0.3050847457627119
Delta: 0.001203120061259075 	  Loss: 1.5547265415509006 	 Accuracy: 0.30638852672750977
Delta: 0.004130433907826586 	  Loss: 1.5547371842206121 	 Accuracy: 0.3050847457627119
Delta: 0.000630970709213461 	  Loss: 1.5547698690170528 	 Accuracy: 0.30638852672750977
Delta: 0.0035908303779631054 	  Loss: 1.5553340098951047 	 Accuracy: 0.3050847457627119
Delta: 0.001937422669022307 	  Loss: 1.5553560119912893 	 Accuracy: 0.3050847457627119
Delta: 0.0009011213646597561 	  Loss: 1.5550156826379973 	 Accuracy: 0.30638852672750977
Delta: 0.0016569082723705336 	  Loss: 1.5556644040467975 	 Accuracy: 0.3050847457627119
Delta: 0.00013406283396618236 	  Loss: 1.555307062329193 	 Accuracy: 0.30638852672750977
Delta: 0.001272164910855657 	  Loss: 1.5556132578102533 	 Accuracy: 0.30638852672750977
Delta: 0.0016653950338696136 	  Loss: 1.5552878557354435 	 Accuracy: 0.30638852672750977
Delta: 0.0016612364821594477 	  Loss: 1.5552118870066791 	 Accuracy: 0.3050847457627119
Delta: 0.0017568053156171502 	  Loss: 1.5552531849907094 	 Accuracy: 0.30638852672750977
Delta: 0.0015610928267989596 	  Loss: 1.555195104717177 	 Accuracy: 0.30638852672750977
Delta: 0.0018308823746848535 	  Loss: 1.5555831607660342 	 Accuracy: 0.30638852672750977
Delta: 0.001072212587947159 	  Loss: 1.5556182102933185 	 Accuracy: 0.30638852672750977
Delta: 0.0029995429356083608 	  Loss: 1.5556765894013576 	 Accuracy: 0.3076923076923077
Delta: 0.002451271782240817 	  Loss: 1.5556155046653286 	 Accuracy: 0.30378096479791394
Delta: 0.0036847673780357744 	  Loss: 1.5568418651762916 	 Accuracy: 0.30638852672750977
Delta: 0.0027213512422093267 	  Loss: 1.5568179373947921 	 Accuracy: 0.30638852672750977
Delta: 0.002646427548252755 	  Loss: 1.5566042993018292 	 Accuracy: 0.3050847457627119
Delta: 0.0016616045420702818 	  Loss: 1.5568417551331084 	 Accuracy: 0.3050847457627119
Delta: 0.0024984304287244173 	  Loss: 1.5567964024861047 	 Accuracy: 0.3050847457627119
Delta: 0.003048830757709351 	  Loss: 1.5568228536296762 	 Accuracy: 0.30638852672750977
Delta: 0.002947371877626787 	  Loss: 1.5569673230202614 	 Accuracy: 0.30638852672750977
Delta: 2.0245270178369718e-05 	  Loss: 1.55692437599328 	 Accuracy: 0.30638852672750977
Delta: 1.7424575469453165e-05 	  Loss: 1.5569125829944463 	 Accuracy: 0.30378096479791394
Delta: 0.00209598682872121 	  Loss: 1.5567913897706278 	 Accuracy: 0.30638852672750977
Delta: 0.0019974381711669598 	  Loss: 1.5563657270950535 	 Accuracy: 0.3050847457627119
Delta: 0.0008241592424134058 	  Loss: 1.556416558861433 	 Accuracy: 0.30638852672750977
Delta: 0.0008048049644094697 	  Loss: 1.5563250668825115 	 Accuracy: 0.3076923076923077
Delta: 0.0019602768326282332 	  Loss: 1.5567891122269033 	 Accuracy: 0.30638852672750977
Delta: 0.001229672485315012 	  Loss: 1.5563632648467265 	 Accuracy: 0.30378096479791394
Delta: 0.02103677890573769 	  Loss: 2.1581841143715086 	 Accuracy: 0.22164276401564537
Delta: 0.018264927326599557 	  Loss: 2.0758383946012513 	 Accuracy: 0.3076923076923077
Delta: 0.016234635007847435 	  Loss: 1.9544588740043558 	 Accuracy: 0.30378096479791394
Delta: 0.0146690663168507 	  Loss: 1.8249152130976611 	 Accuracy: 0.32073011734028684
Delta: 0.013829122643554658 	  Loss: 1.7342178375910793 	 Accuracy: 0.39895697522816165
Delta: 0.013450734252556011 	  Loss: 1.6672302932097627 	 Accuracy: 0.44328552803129073
Delta: 0.01187618264076595 	  Loss: 1.6161504546599788 	 Accuracy: 0.4445893089960887
Delta: 0.009875675680504903 	  Loss: 1.584922380251315 	 Accuracy: 0.4485006518904824
Delta: 0.007638036406237129 	  Loss: 1.5715496155603341 	 Accuracy: 0.45632333767926986
Delta: 0.0059187843430773554 	  Loss: 1.5643438703362536 	 Accuracy: 0.45371577574967403

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006040510076418544 	  Loss: 1.5608256395346252 	 Accuracy: 0.455019556714472
Delta: 0.004352238737306058 	  Loss: 1.5594382400684428 	 Accuracy: 0.4498044328552803
Delta: 0.0037554028484741305 	  Loss: 1.5591621537285045 	 Accuracy: 0.4498044328552803
Delta: 0.003735844095878049 	  Loss: 1.558810760207662 	 Accuracy: 0.4511082138200782
Delta: 0.0032407706509992393 	  Loss: 1.5584912823950314 	 Accuracy: 0.45241199478487615
Delta: 0.0017914415568025322 	  Loss: 1.558424164294212 	 Accuracy: 0.45241199478487615
Delta: 0.0021982321259316215 	  Loss: 1.5583286831793681 	 Accuracy: 0.45241199478487615
Delta: 0.0016168619263831703 	  Loss: 1.5580769147763678 	 Accuracy: 0.45241199478487615
Delta: 0.0025556959277906045 	  Loss: 1.5579656278633638 	 Accuracy: 0.45241199478487615
Delta: 0.0024356860695314416 	  Loss: 1.558066935544649 	 Accuracy: 0.45241199478487615
Delta: 0.0025677874407655783 	  Loss: 1.5581534669980452 	 Accuracy: 0.45241199478487615
Delta: 0.0024427576833795273 	  Loss: 1.5580205299102237 	 Accuracy: 0.45241199478487615
Delta: 0.0015947517245665345 	  Loss: 1.557996284639948 	 Accuracy: 0.45241199478487615
Delta: 0.0010705144601083519 	  Loss: 1.5580373884922878 	 Accuracy: 0.45241199478487615
Delta: 0.0016089720238776247 	  Loss: 1.5578795865679036 	 Accuracy: 0.4511082138200782
Delta: 0.0031545188432505504 	  Loss: 1.5583702193453588 	 Accuracy: 0.4511082138200782
Delta: 0.00136094343574126 	  Loss: 1.5583887405450243 	 Accuracy: 0.4511082138200782
Delta: 0.0016877064337156242 	  Loss: 1.558009608159508 	 Accuracy: 0.4511082138200782
Delta: 1.9374546707150116e-05 	  Loss: 1.5579773347152412 	 Accuracy: 0.4511082138200782
Delta: 0.000518001855904696 	  Loss: 1.5579792565322519 	 Accuracy: 0.4511082138200782
Delta: 0.0011447878730729635 	  Loss: 1.5578457355559383 	 Accuracy: 0.45241199478487615
Delta: 0.003254012028370227 	  Loss: 1.557631704982899 	 Accuracy: 0.44198174706649285
Delta: 0.0016361835561882502 	  Loss: 1.5580834374877877 	 Accuracy: 0.4511082138200782
Delta: 0.0030804384321283093 	  Loss: 1.558271755978498 	 Accuracy: 0.4511082138200782
Delta: 0.0021676398591894525 	  Loss: 1.5585687651043172 	 Accuracy: 0.4511082138200782
Delta: 0.001194967878319936 	  Loss: 1.5581850924824345 	 Accuracy: 0.4511082138200782
Delta: 1.5612162174856185e-05 	  Loss: 1.55821955270279 	 Accuracy: 0.4511082138200782
Delta: 3.2953019704725076e-05 	  Loss: 1.5581467974972298 	 Accuracy: 0.4511082138200782
Delta: 0.001531544345497725 	  Loss: 1.5584279706211892 	 Accuracy: 0.4511082138200782
Delta: 0.0009702412948451114 	  Loss: 1.5585537071550972 	 Accuracy: 0.4511082138200782
Delta: 0.0011890560146494765 	  Loss: 1.5585943926010195 	 Accuracy: 0.4498044328552803
Delta: 0.001864290115110082 	  Loss: 1.5588132193636555 	 Accuracy: 0.4511082138200782
Delta: 1.641583430387198e-05 	  Loss: 1.5587780861438305 	 Accuracy: 0.4511082138200782
Delta: 1.6631960138083155e-05 	  Loss: 1.558848415041862 	 Accuracy: 0.4511082138200782
Delta: 2.5306964634971457e-05 	  Loss: 1.5588535754007617 	 Accuracy: 0.4498044328552803
Delta: 0.0005458805769022687 	  Loss: 1.5589676580102703 	 Accuracy: 0.4511082138200782
Delta: 0.0005425399696904615 	  Loss: 1.558783724119197 	 Accuracy: 0.4511082138200782
Delta: 2.1377442309311846e-05 	  Loss: 1.5587688955852668 	 Accuracy: 0.4498044328552803
Delta: 1.9419713551840212e-05 	  Loss: 1.5587913106137785 	 Accuracy: 0.4706649282920469
Delta: 1.8469497978982424e-05 	  Loss: 1.5587551807692248 	 Accuracy: 0.4511082138200782
Delta: 0.0017104049615430748 	  Loss: 1.5593191818325987 	 Accuracy: 0.4511082138200782
Delta: 7.487336921607992e-05 	  Loss: 1.5589420532553082 	 Accuracy: 0.4511082138200782
Delta: 0.001200364285391412 	  Loss: 1.5588847914037687 	 Accuracy: 0.4498044328552803
Delta: 1.7333681311140122e-05 	  Loss: 1.558794578149575 	 Accuracy: 0.4511082138200782
Delta: 1.361329762349595e-05 	  Loss: 1.5588441045717958 	 Accuracy: 0.4511082138200782
Delta: 0.0015071018182715244 	  Loss: 1.5586052031495448 	 Accuracy: 0.4511082138200782
Delta: 0.001059303098430823 	  Loss: 1.5587914570262815 	 Accuracy: 0.4511082138200782
Delta: 1.0943883984296373e-05 	  Loss: 1.5588214725139347 	 Accuracy: 0.4511082138200782
Delta: 0.002657686762898869 	  Loss: 1.5581331308550217 	 Accuracy: 0.4511082138200782
Delta: 4.601280082990997e-06 	  Loss: 1.558127693244896 	 Accuracy: 0.4511082138200782
Delta: 0.0021685788537539833 	  Loss: 1.5585711358007808 	 Accuracy: 0.4498044328552803
Delta: 0.0014546960176914697 	  Loss: 1.5588836820465852 	 Accuracy: 0.4511082138200782
Delta: 7.18403830685549e-05 	  Loss: 1.558616298977826 	 Accuracy: 0.4511082138200782
Delta: 0.00259564379260463 	  Loss: 1.558137355625059 	 Accuracy: 0.4511082138200782
Delta: 1.9154578799580275e-05 	  Loss: 1.5581854403392468 	 Accuracy: 0.4511082138200782
Delta: 2.034795183673421e-05 	  Loss: 1.5581771526657073 	 Accuracy: 0.4511082138200782
Delta: 0.0014759849164605768 	  Loss: 1.5581721919910176 	 Accuracy: 0.45241199478487615
Delta: 0.0027905390223979167 	  Loss: 1.5586269304982427 	 Accuracy: 0.4498044328552803
Delta: 0.003518426879147634 	  Loss: 1.5593770534120792 	 Accuracy: 0.4498044328552803
Delta: 0.0009413094331431254 	  Loss: 1.5593123228487542 	 Accuracy: 0.4485006518904824
Delta: 0.0005559103514727046 	  Loss: 1.5591196383387222 	 Accuracy: 0.4498044328552803
Delta: 0.0032214568831075174 	  Loss: 1.5590662636013466 	 Accuracy: 0.44589308996088656
Delta: 0.0037273554860449707 	  Loss: 1.5601327814428185 	 Accuracy: 0.4485006518904824
Delta: 0.001438587495375266 	  Loss: 1.5601810843452595 	 Accuracy: 0.4498044328552803
Delta: 0.004294853933955639 	  Loss: 1.5594834303648595 	 Accuracy: 0.4498044328552803
Delta: 0.0010384697959596775 	  Loss: 1.5593070972955339 	 Accuracy: 0.4498044328552803
Delta: 3.5694645264774814e-05 	  Loss: 1.5593328123735994 	 Accuracy: 0.4498044328552803
Delta: 5.6839874198901855e-05 	  Loss: 1.5591383696150305 	 Accuracy: 0.4498044328552803
Delta: 5.526706410749019e-05 	  Loss: 1.5593252292809285 	 Accuracy: 0.45241199478487615
Delta: 9.126045740707619e-06 	  Loss: 1.5592756525721212 	 Accuracy: 0.4498044328552803
Delta: 0.0018157118013310046 	  Loss: 1.5595472741903964 	 Accuracy: 0.4498044328552803
Delta: 6.444070857201897e-05 	  Loss: 1.5594678066904462 	 Accuracy: 0.4498044328552803
Delta: 3.428634140622914e-05 	  Loss: 1.5593242772405773 	 Accuracy: 0.4498044328552803
Delta: 1.6726191290929842e-05 	  Loss: 1.5593537356604839 	 Accuracy: 0.4471968709256845
Delta: 2.117869695825254e-05 	  Loss: 1.5593866084749335 	 Accuracy: 0.4498044328552803
Delta: 0.005110729529470214 	  Loss: 1.558869007885115 	 Accuracy: 0.4485006518904824
Delta: 0.0014234169691105163 	  Loss: 1.5588672627772064 	 Accuracy: 0.4498044328552803
Delta: 0.0016111318089500964 	  Loss: 1.558578782008262 	 Accuracy: 0.4511082138200782
Delta: 0.005109578668624367 	  Loss: 1.5582327007671117 	 Accuracy: 0.4485006518904824
Delta: 0.003954140570447956 	  Loss: 1.56009610160887 	 Accuracy: 0.44328552803129073
Delta: 0.004078747719520433 	  Loss: 1.5612010076708787 	 Accuracy: 0.44328552803129073
Delta: 0.0012368769115938066 	  Loss: 1.5613237657654464 	 Accuracy: 0.44589308996088656
Delta: 0.0008800355783079772 	  Loss: 1.5606424106020635 	 Accuracy: 0.4471968709256845
Delta: 5.9555054393471276e-05 	  Loss: 1.5606475984480084 	 Accuracy: 0.4471968709256845
Delta: 5.285497493524084e-05 	  Loss: 1.5606495637471471 	 Accuracy: 0.4471968709256845
Delta: 1.6902817302511444e-05 	  Loss: 1.5606554361987264 	 Accuracy: 0.4471968709256845
Delta: 4.1174012431825015e-05 	  Loss: 1.5606440476073287 	 Accuracy: 0.4471968709256845
Delta: 0.0012359062908583538 	  Loss: 1.560709822028599 	 Accuracy: 0.4471968709256845
Delta: 0.0012334512688272966 	  Loss: 1.5606510865258965 	 Accuracy: 0.44589308996088656
Delta: 0.004910903606236947 	  Loss: 1.562044013607754 	 Accuracy: 0.44589308996088656
Delta: 0.020911200380667256 	  Loss: 2.158620833857902 	 Accuracy: 0.21642764015645372
Delta: 0.018560014927849908 	  Loss: 2.071014809514423 	 Accuracy: 0.2333767926988266
Delta: 0.016565656258992457 	  Loss: 1.9315080924838175 	 Accuracy: 0.2790091264667536
Delta: 0.014809475434023165 	  Loss: 1.805467542575797 	 Accuracy: 0.39504563233376794
Delta: 0.013387194745740714 	  Loss: 1.731989663955078 	 Accuracy: 0.4028683181225554
Delta: 0.012489897914120494 	  Loss: 1.6919529492713359 	 Accuracy: 0.4028683181225554
Delta: 0.012188887965772973 	  Loss: 1.6635503369057298 	 Accuracy: 0.42633637548891784
Delta: 0.011095500452336116 	  Loss: 1.6378773980693184 	 Accuracy: 0.43415906127770537
Delta: 0.008948849322480542 	  Loss: 1.6221337300204919 	 Accuracy: 0.41460234680573665
Delta: 0.007736542474037211 	  Loss: 1.6136676887605321 	 Accuracy: 0.4172099087353325
Delta: 0.007152017403253956 	  Loss: 1.6093299562167602 	 Accuracy: 0.423728813559322

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007229901736788559 	  Loss: 1.6056547427831154 	 Accuracy: 0.41460234680573665
Delta: 0.005437871181092401 	  Loss: 1.6040774169983694 	 Accuracy: 0.4211212516297262
Delta: 0.005764656183857408 	  Loss: 1.6025884609609367 	 Accuracy: 0.4198174706649283
Delta: 0.00469448190038532 	  Loss: 1.60166555601274 	 Accuracy: 0.41851368970013036
Delta: 0.003271499341267721 	  Loss: 1.6016468830945332 	 Accuracy: 0.4198174706649283
Delta: 0.0026684400813385164 	  Loss: 1.6014405780241603 	 Accuracy: 0.4172099087353325
Delta: 0.0043152993950231625 	  Loss: 1.6015799803016368 	 Accuracy: 0.4211212516297262
Delta: 0.0021127561169824627 	  Loss: 1.601543510253696 	 Accuracy: 0.42633637548891784
Delta: 0.004398385110883324 	  Loss: 1.6024141061548705 	 Accuracy: 0.41851368970013036
Delta: 0.002437651084016806 	  Loss: 1.6020689124806462 	 Accuracy: 0.4198174706649283
Delta: 5.9249027659938326e-05 	  Loss: 1.6020270552163374 	 Accuracy: 0.4198174706649283
Delta: 0.0009574899460384878 	  Loss: 1.6021238989493771 	 Accuracy: 0.4198174706649283
Delta: 0.0015308468946835696 	  Loss: 1.601778536327856 	 Accuracy: 0.4198174706649283
Delta: 0.0018651016674211237 	  Loss: 1.601561031565283 	 Accuracy: 0.41851368970013036
Delta: 0.0005380888659287826 	  Loss: 1.601606386896747 	 Accuracy: 0.4198174706649283
Delta: 0.000977968379899192 	  Loss: 1.6012745156934158 	 Accuracy: 0.41851368970013036
Delta: 0.0005040329171784501 	  Loss: 1.601351241479683 	 Accuracy: 0.41851368970013036
Delta: 0.0022188637042796487 	  Loss: 1.6012881677274966 	 Accuracy: 0.4198174706649283
Delta: 0.0020510019466914503 	  Loss: 1.6011332711046076 	 Accuracy: 0.4172099087353325
Delta: 0.0012185983138535655 	  Loss: 1.601158569147553 	 Accuracy: 0.4198174706649283
Delta: 0.0005200157470709 	  Loss: 1.6011015852047623 	 Accuracy: 0.4198174706649283
Delta: 0.0007330296424247805 	  Loss: 1.6010713224071862 	 Accuracy: 0.4198174706649283
Delta: 0.001166361749300804 	  Loss: 1.6008019189581069 	 Accuracy: 0.42242503259452413
Delta: 0.0017200718574081916 	  Loss: 1.6010858627448987 	 Accuracy: 0.4198174706649283
Delta: 0.0008179627774436548 	  Loss: 1.601162557964919 	 Accuracy: 0.4198174706649283
Delta: 0.0005175987145981304 	  Loss: 1.6011791496144752 	 Accuracy: 0.4198174706649283
Delta: 0.002645296155409008 	  Loss: 1.6010616757774303 	 Accuracy: 0.4198174706649283
Delta: 0.0018733850365718128 	  Loss: 1.6008284225318614 	 Accuracy: 0.41851368970013036
Delta: 0.0006517421279071886 	  Loss: 1.6009748181642152 	 Accuracy: 0.41851368970013036
Delta: 0.003645766282041929 	  Loss: 1.6010051783524695 	 Accuracy: 0.4172099087353325
Delta: 0.0015978287325948439 	  Loss: 1.6007658355544876 	 Accuracy: 0.41851368970013036
Delta: 0.001255072656628641 	  Loss: 1.6008572609145992 	 Accuracy: 0.4198174706649283
Delta: 5.625897811455407e-05 	  Loss: 1.6008776376369003 	 Accuracy: 0.41851368970013036
Delta: 0.001827685104300288 	  Loss: 1.6008978059443335 	 Accuracy: 0.41851368970013036
Delta: 0.0018507157417762413 	  Loss: 1.6008010309945422 	 Accuracy: 0.41851368970013036
Delta: 0.0007692995742644218 	  Loss: 1.600773330801458 	 Accuracy: 0.4198174706649283
Delta: 0.0016968373724525782 	  Loss: 1.6008286882497118 	 Accuracy: 0.4172099087353325
Delta: 0.00149533154034955 	  Loss: 1.6010514511556788 	 Accuracy: 0.41590612777053454
Delta: 0.0024567115690265584 	  Loss: 1.6011367402605008 	 Accuracy: 0.4172099087353325
Delta: 0.0037517304260158047 	  Loss: 1.601511808026133 	 Accuracy: 0.4172099087353325
Delta: 0.003380117822298579 	  Loss: 1.6013013131913365 	 Accuracy: 0.4172099087353325
Delta: 5.67047441036219e-05 	  Loss: 1.6011999751824035 	 Accuracy: 0.4172099087353325
Delta: 0.0029971085524923636 	  Loss: 1.6019300483081595 	 Accuracy: 0.4172099087353325
Delta: 0.001020843863253312 	  Loss: 1.6018764462440105 	 Accuracy: 0.41590612777053454
Delta: 1.6593797560622456e-05 	  Loss: 1.6018850570809322 	 Accuracy: 0.41590612777053454
Delta: 9.279882043648341e-06 	  Loss: 1.601866901586552 	 Accuracy: 0.4172099087353325
Delta: 0.002339768013131938 	  Loss: 1.6014772659651135 	 Accuracy: 0.41590612777053454
Delta: 0.002138480383535865 	  Loss: 1.6015156076472992 	 Accuracy: 0.4172099087353325
Delta: 0.0015967017822722915 	  Loss: 1.6014741887863653 	 Accuracy: 0.4172099087353325
Delta: 0.0018309904636843106 	  Loss: 1.601956203848099 	 Accuracy: 0.4172099087353325
Delta: 0.0010437164454133807 	  Loss: 1.6016044642617033 	 Accuracy: 0.4172099087353325
Delta: 4.629184583789589e-05 	  Loss: 1.6014855366188834 	 Accuracy: 0.4172099087353325
Delta: 0.0001234245215835893 	  Loss: 1.601782888816886 	 Accuracy: 0.4198174706649283
Delta: 0.005181980822973087 	  Loss: 1.6013037486149249 	 Accuracy: 0.41460234680573665
Delta: 0.0026959983170760198 	  Loss: 1.6012777831760658 	 Accuracy: 0.41851368970013036
Delta: 0.0006207883565414452 	  Loss: 1.6012633593575223 	 Accuracy: 0.4172099087353325
Delta: 0.0010210971627520403 	  Loss: 1.601408934150603 	 Accuracy: 0.4172099087353325
Delta: 0.0015842300154902435 	  Loss: 1.6012967523458275 	 Accuracy: 0.4132985658409387
Delta: 0.002485903382094531 	  Loss: 1.6012207047878078 	 Accuracy: 0.41590612777053454
Delta: 0.0008709277438293036 	  Loss: 1.6011784610666449 	 Accuracy: 0.4132985658409387
Delta: 0.0011470277013505348 	  Loss: 1.6012868168123748 	 Accuracy: 0.41460234680573665
Delta: 3.701869711307273e-05 	  Loss: 1.601279782420381 	 Accuracy: 0.41199478487614083
Delta: 0.001696023238689173 	  Loss: 1.6014942896324489 	 Accuracy: 0.4132985658409387
Delta: 0.0014691167076281628 	  Loss: 1.601258125391368 	 Accuracy: 0.4172099087353325
Delta: 6.528179871144658e-05 	  Loss: 1.6012907963277256 	 Accuracy: 0.41590612777053454
Delta: 0.0016879679183616416 	  Loss: 1.601105336475585 	 Accuracy: 0.4132985658409387
Delta: 0.0005595310487238004 	  Loss: 1.6012281781009772 	 Accuracy: 0.41590612777053454
Delta: 4.7469291562285914e-05 	  Loss: 1.6012661562213486 	 Accuracy: 0.41590612777053454
Delta: 1.7242860275599796e-05 	  Loss: 1.601171411075574 	 Accuracy: 0.41590612777053454
Delta: 2.8955798349395083e-05 	  Loss: 1.6012244952008117 	 Accuracy: 0.409387222946545
Delta: 0.0009824869885944193 	  Loss: 1.6013890648329716 	 Accuracy: 0.41590612777053454
Delta: 0.0007529202980173355 	  Loss: 1.6012180238147882 	 Accuracy: 0.41590612777053454
Delta: 2.937333682983699e-05 	  Loss: 1.6012377341207218 	 Accuracy: 0.41590612777053454
Delta: 2.4556096315170117e-05 	  Loss: 1.6011904460191682 	 Accuracy: 0.41590612777053454
Delta: 0.0010567195114466995 	  Loss: 1.6011419858084577 	 Accuracy: 0.41590612777053454
Delta: 2.3184286190846778e-05 	  Loss: 1.6011860640981534 	 Accuracy: 0.4172099087353325
Delta: 9.87040589885588e-06 	  Loss: 1.6011870715321899 	 Accuracy: 0.41590612777053454
Delta: 4.828267451563126e-05 	  Loss: 1.6011648622307713 	 Accuracy: 0.41590612777053454
Delta: 4.148928787868871e-05 	  Loss: 1.6011896355304738 	 Accuracy: 0.41590612777053454
Delta: 0.0019407775036752628 	  Loss: 1.6013343380062883 	 Accuracy: 0.41590612777053454
Delta: 0.0006550062947844062 	  Loss: 1.6012124007498394 	 Accuracy: 0.41590612777053454
Delta: 0.0008167991012836454 	  Loss: 1.6011784492312513 	 Accuracy: 0.41590612777053454
Delta: 3.042132664716352e-05 	  Loss: 1.6011549329104056 	 Accuracy: 0.41590612777053454
Delta: 3.915621669254946e-05 	  Loss: 1.6011199522889268 	 Accuracy: 0.4172099087353325
Delta: 0.0010924205702562972 	  Loss: 1.6012061007841152 	 Accuracy: 0.4172099087353325
Delta: 0.001789657180268629 	  Loss: 1.6012630677344184 	 Accuracy: 0.41590612777053454
Delta: 5.974888334182753e-05 	  Loss: 1.601169933789722 	 Accuracy: 0.41590612777053454
Delta: 0.001865538279496398 	  Loss: 1.6012105677599369 	 Accuracy: 0.41460234680573665
Delta: 0.0007352593169694121 	  Loss: 1.6013868141602927 	 Accuracy: 0.41590612777053454
Delta: 0.02087725997290726 	  Loss: 2.1591487367840796 	 Accuracy: 0.21251629726205998
Delta: 0.018388209775026934 	  Loss: 2.070039424303691 	 Accuracy: 0.23468057366362452
Delta: 0.016803670075891432 	  Loss: 1.9211216597619971 	 Accuracy: 0.20860495436766624
Delta: 0.015150264824122496 	  Loss: 1.7824537016482194 	 Accuracy: 0.2542372881355932
Delta: 0.013204522963023966 	  Loss: 1.6995780520551664 	 Accuracy: 0.2620599739243807
Delta: 0.01139475213403376 	  Loss: 1.6539878954975324 	 Accuracy: 0.2516297262059974
Delta: 0.010663570706135685 	  Loss: 1.6282829225836881 	 Accuracy: 0.242503259452412
Delta: 0.009393075415282351 	  Loss: 1.6131272757951407 	 Accuracy: 0.242503259452412
Delta: 0.00799885371083719 	  Loss: 1.6059865134887006 	 Accuracy: 0.24119947848761408

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007205416878865335 	  Loss: 1.6029790381516624 	 Accuracy: 0.24511082138200782
Delta: 0.006792225056271185 	  Loss: 1.6010582721137792 	 Accuracy: 0.24119947848761408
Delta: 0.004445746958230525 	  Loss: 1.6001741805374239 	 Accuracy: 0.24119947848761408
Delta: 0.004138808500024534 	  Loss: 1.60007689630099 	 Accuracy: 0.24119947848761408
Delta: 0.0033820246181826595 	  Loss: 1.59995522548103 	 Accuracy: 0.2438070404172099
Delta: 0.00362531859263858 	  Loss: 1.599927760134332 	 Accuracy: 0.242503259452412
Delta: 0.003672945869688148 	  Loss: 1.6003393739641922 	 Accuracy: 0.242503259452412
Delta: 0.0022770429292408175 	  Loss: 1.6003275627195828 	 Accuracy: 0.24119947848761408
Delta: 0.002003028884859743 	  Loss: 1.6004718483408207 	 Accuracy: 0.242503259452412
Delta: 0.0021190648794223604 	  Loss: 1.6003710540080704 	 Accuracy: 0.242503259452412
Delta: 5.2525310835710235e-05 	  Loss: 1.6003613519018554 	 Accuracy: 0.242503259452412
Delta: 0.0037792641152683696 	  Loss: 1.6004389082505694 	 Accuracy: 0.242503259452412
Delta: 0.0017063054375337358 	  Loss: 1.6005018900295607 	 Accuracy: 0.242503259452412
Delta: 0.0007736795917754264 	  Loss: 1.600369550894719 	 Accuracy: 0.242503259452412
Delta: 0.001084898612412537 	  Loss: 1.600312000003418 	 Accuracy: 0.242503259452412
Delta: 5.4111663701067945e-05 	  Loss: 1.6003809436278909 	 Accuracy: 0.242503259452412
Delta: 4.337397341576253e-05 	  Loss: 1.6004365416163653 	 Accuracy: 0.23859191655801826
Delta: 0.0008590666287048486 	  Loss: 1.6004028463813529 	 Accuracy: 0.242503259452412
Delta: 0.0019732104709643066 	  Loss: 1.6004323554759972 	 Accuracy: 0.242503259452412
Delta: 0.0010350971746855445 	  Loss: 1.600298097006901 	 Accuracy: 0.242503259452412
Delta: 6.309746571850579e-05 	  Loss: 1.6003407683502684 	 Accuracy: 0.242503259452412
Delta: 0.0018775084570085078 	  Loss: 1.6004144804782836 	 Accuracy: 0.242503259452412
Delta: 0.0005532694324503812 	  Loss: 1.6003967868165017 	 Accuracy: 0.24119947848761408
Delta: 6.669435092831068e-05 	  Loss: 1.6003521759572887 	 Accuracy: 0.242503259452412
Delta: 0.000545420416769618 	  Loss: 1.6003154010745493 	 Accuracy: 0.242503259452412
Delta: 0.0005304855399816776 	  Loss: 1.6003293180973461 	 Accuracy: 0.242503259452412
Delta: 3.799162425474477e-05 	  Loss: 1.6001722280419242 	 Accuracy: 0.242503259452412
Delta: 0.0005483991870698289 	  Loss: 1.6002755226068026 	 Accuracy: 0.242503259452412
Delta: 6.139380856256242e-05 	  Loss: 1.600175497831808 	 Accuracy: 0.242503259452412
Delta: 4.1994236069455594e-05 	  Loss: 1.6005171788381216 	 Accuracy: 0.242503259452412
Delta: 4.257259930876585e-05 	  Loss: 1.6001911425079947 	 Accuracy: 0.24119947848761408
Delta: 3.515425079285644e-05 	  Loss: 1.600242003693491 	 Accuracy: 0.24119947848761408
Delta: 0.0025179354741218995 	  Loss: 1.6007325569320559 	 Accuracy: 0.242503259452412
Delta: 0.0022932347462223733 	  Loss: 1.6002680314431545 	 Accuracy: 0.242503259452412
Delta: 0.0013465433666892221 	  Loss: 1.6000934731897942 	 Accuracy: 0.24119947848761408
Delta: 7.641566725230413e-05 	  Loss: 1.6003438293267096 	 Accuracy: 0.242503259452412
Delta: 0.0007505505420259372 	  Loss: 1.600328126835075 	 Accuracy: 0.2438070404172099
Delta: 0.004324760507226592 	  Loss: 1.6005025526922743 	 Accuracy: 0.2438070404172099
Delta: 0.0023591125125297036 	  Loss: 1.6006464741674218 	 Accuracy: 0.2438070404172099
Delta: 0.0032703280724882817 	  Loss: 1.6001169766007928 	 Accuracy: 0.2438070404172099
Delta: 0.002739464556734478 	  Loss: 1.6005799567487071 	 Accuracy: 0.242503259452412
Delta: 0.0009911483651025615 	  Loss: 1.6004667302044138 	 Accuracy: 0.242503259452412
Delta: 0.00241497253183606 	  Loss: 1.600296517197803 	 Accuracy: 0.24511082138200782
Delta: 0.003204729303244236 	  Loss: 1.5998647224771545 	 Accuracy: 0.2438070404172099
Delta: 0.002555683563126486 	  Loss: 1.6001966772517346 	 Accuracy: 0.2438070404172099
Delta: 0.0019929743466694286 	  Loss: 1.599718518497788 	 Accuracy: 0.2438070404172099
Delta: 0.0013476683654763102 	  Loss: 1.599704806460168 	 Accuracy: 0.2438070404172099
Delta: 0.0009563714435447473 	  Loss: 1.5999417927797448 	 Accuracy: 0.2438070404172099
Delta: 0.0001102299106647904 	  Loss: 1.5997174039652204 	 Accuracy: 0.2438070404172099
Delta: 2.4715459755853227e-05 	  Loss: 1.5997323815117694 	 Accuracy: 0.2438070404172099
Delta: 2.70771414711261e-05 	  Loss: 1.5997364076979377 	 Accuracy: 0.2438070404172099
Delta: 1.1066953960269112e-05 	  Loss: 1.5997187344614654 	 Accuracy: 0.242503259452412
Delta: 0.0020676223378512 	  Loss: 1.5997949405937115 	 Accuracy: 0.242503259452412
Delta: 0.0014584106576373494 	  Loss: 1.5998592199929607 	 Accuracy: 0.2438070404172099
Delta: 0.0005454828233985368 	  Loss: 1.5997019110822879 	 Accuracy: 0.2438070404172099
Delta: 1.661154314050269e-05 	  Loss: 1.5997166261676856 	 Accuracy: 0.2438070404172099
Delta: 0.0018873713843187833 	  Loss: 1.5999343642203487 	 Accuracy: 0.2438070404172099
Delta: 0.0009190976923016828 	  Loss: 1.5998684229860654 	 Accuracy: 0.2438070404172099
Delta: 4.264482228873326e-05 	  Loss: 1.59975195866392 	 Accuracy: 0.2438070404172099
Delta: 2.130886401904909e-05 	  Loss: 1.5996974118204745 	 Accuracy: 0.24119947848761408
Delta: 0.0007381380330482867 	  Loss: 1.5996686525925 	 Accuracy: 0.2438070404172099
Delta: 0.0014294604311045635 	  Loss: 1.6000151697515026 	 Accuracy: 0.24511082138200782
Delta: 7.887197294214974e-05 	  Loss: 1.599804400476093 	 Accuracy: 0.2438070404172099
Delta: 3.8298814666961324e-05 	  Loss: 1.5997388073497771 	 Accuracy: 0.2438070404172099
Delta: 2.7343271876554912e-05 	  Loss: 1.5997079654940631 	 Accuracy: 0.24771838331160365
Delta: 0.005210683045734917 	  Loss: 1.599955047998618 	 Accuracy: 0.2438070404172099
Delta: 0.0040735990650885645 	  Loss: 1.6000148611373928 	 Accuracy: 0.242503259452412
Delta: 0.0005506154574111572 	  Loss: 1.5998896096329691 	 Accuracy: 0.2438070404172099
Delta: 0.004685855208794552 	  Loss: 1.6000495645324917 	 Accuracy: 0.242503259452412
Delta: 0.003731876705244746 	  Loss: 1.6003636965252055 	 Accuracy: 0.242503259452412
Delta: 0.0007766077408921341 	  Loss: 1.6005507593305466 	 Accuracy: 0.242503259452412
Delta: 1.5636165152965996e-07 	  Loss: 1.6005508367200316 	 Accuracy: 0.242503259452412
converged at iter  80
Delta: 0.020838635300235907 	  Loss: 2.159086130251482 	 Accuracy: 0.20860495436766624
Delta: 0.01856443282925033 	  Loss: 2.0675374818269767 	 Accuracy: 0.25684485006518903
Delta: 0.01712561886122383 	  Loss: 1.9063884979255188 	 Accuracy: 0.34419817470664926
Delta: 0.01635094146390949 	  Loss: 1.7470271651664018 	 Accuracy: 0.3546284224250326
Delta: 0.01424975794493825 	  Loss: 1.639121828777963 	 Accuracy: 0.3246414602346806
Delta: 0.010415717355382596 	  Loss: 1.5941499120129423 	 Accuracy: 0.318122555410691
Delta: 0.008845234781670992 	  Loss: 1.579296579267508 	 Accuracy: 0.3259452411994785

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007329358948456153 	  Loss: 1.573590343736012 	 Accuracy: 0.3272490221642764
Delta: 0.006395093939091231 	  Loss: 1.5710167056785107 	 Accuracy: 0.32073011734028684
Delta: 0.0059352356885400475 	  Loss: 1.5691755361992907 	 Accuracy: 0.32073011734028684
Delta: 0.0044802039047885595 	  Loss: 1.5686860197732875 	 Accuracy: 0.3220338983050847
Delta: 0.004094553701663636 	  Loss: 1.568624328396054 	 Accuracy: 0.3246414602346806
Delta: 0.0016168865284927252 	  Loss: 1.5686023255782398 	 Accuracy: 0.3246414602346806
Delta: 0.003030135764054121 	  Loss: 1.5683809829833577 	 Accuracy: 0.3220338983050847
Delta: 0.002498185630348811 	  Loss: 1.5685123174148599 	 Accuracy: 0.3246414602346806
Delta: 0.002459837481863937 	  Loss: 1.5687297088851464 	 Accuracy: 0.32333767926988266
Delta: 0.004040878737314015 	  Loss: 1.5685999594585807 	 Accuracy: 0.32333767926988266
Delta: 0.0013321392479729904 	  Loss: 1.568678260245317 	 Accuracy: 0.32333767926988266
Delta: 0.0008580024316145353 	  Loss: 1.568683261942302 	 Accuracy: 0.32333767926988266
Delta: 0.0015725314616894307 	  Loss: 1.5687899654147854 	 Accuracy: 0.32333767926988266
Delta: 0.0006311357210515119 	  Loss: 1.5687362030759462 	 Accuracy: 0.32333767926988266
Delta: 0.0019380765355547635 	  Loss: 1.5687310986338634 	 Accuracy: 0.32333767926988266
Delta: 0.0009365083132187384 	  Loss: 1.5687121380402738 	 Accuracy: 0.3220338983050847
Delta: 0.000960126368216227 	  Loss: 1.5686152060234482 	 Accuracy: 0.3220338983050847
Delta: 1.350102777079635e-05 	  Loss: 1.5686213735455938 	 Accuracy: 0.32333767926988266
Delta: 0.0023716712972169677 	  Loss: 1.5687023982402462 	 Accuracy: 0.3220338983050847
Delta: 0.0007391412184376783 	  Loss: 1.568789646770727 	 Accuracy: 0.32333767926988266
Delta: 0.0006302264098467636 	  Loss: 1.5688137659122716 	 Accuracy: 0.32333767926988266
Delta: 0.0006351904117332416 	  Loss: 1.568702671356087 	 Accuracy: 0.32333767926988266
Delta: 2.642179568058535e-05 	  Loss: 1.5687615873350538 	 Accuracy: 0.32333767926988266
Delta: 0.0013111291295134114 	  Loss: 1.5686594719494886 	 Accuracy: 0.32333767926988266
Delta: 0.0025864078658413762 	  Loss: 1.5688234400920467 	 Accuracy: 0.32333767926988266
Delta: 0.0011567310744243224 	  Loss: 1.5689025472270837 	 Accuracy: 0.32333767926988266
Delta: 0.0029670459642078782 	  Loss: 1.5687877441976243 	 Accuracy: 0.32333767926988266
Delta: 0.0007154316321377321 	  Loss: 1.5688007418327379 	 Accuracy: 0.32333767926988266
Delta: 0.0007586388347056743 	  Loss: 1.5686540721802886 	 Accuracy: 0.3220338983050847
Delta: 5.1017617446873953e-05 	  Loss: 1.5690726915919062 	 Accuracy: 0.32333767926988266
Delta: 5.7575137505818984e-05 	  Loss: 1.5685815192023949 	 Accuracy: 0.3246414602346806
Delta: 0.0015463185960466158 	  Loss: 1.56850658303541 	 Accuracy: 0.3220338983050847
Delta: 6.198675678977336e-05 	  Loss: 1.5688188218110872 	 Accuracy: 0.3220338983050847
Delta: 0.0012345302963772372 	  Loss: 1.5688687456028951 	 Accuracy: 0.32333767926988266
Delta: 0.00010489514791174208 	  Loss: 1.5685835812685462 	 Accuracy: 0.3259452411994785
Delta: 1.8481655839303033e-05 	  Loss: 1.5686053157608972 	 Accuracy: 0.32333767926988266
Delta: 0.0009788939246150874 	  Loss: 1.5687382627566544 	 Accuracy: 0.3220338983050847
Delta: 0.0013806954701787424 	  Loss: 1.568830804624852 	 Accuracy: 0.32333767926988266
Delta: 0.0012328962922598732 	  Loss: 1.5686213899167663 	 Accuracy: 0.3220338983050847
Delta: 5.769345724161908e-05 	  Loss: 1.5684671027804216 	 Accuracy: 0.32333767926988266
Delta: 3.158213333297173e-05 	  Loss: 1.568574042031178 	 Accuracy: 0.32333767926988266
Delta: 5.015095861099728e-05 	  Loss: 1.56851512440974 	 Accuracy: 0.3246414602346806
Delta: 0.0032313860575252998 	  Loss: 1.5687490765540808 	 Accuracy: 0.3220338983050847
Delta: 0.005068993467456689 	  Loss: 1.5695641881636186 	 Accuracy: 0.32073011734028684
Delta: 0.0035770853105142665 	  Loss: 1.5694652725428855 	 Accuracy: 0.3259452411994785
Delta: 0.004528067663309362 	  Loss: 1.5680806195562338 	 Accuracy: 0.32333767926988266
Delta: 0.0018332703922726082 	  Loss: 1.5689850965872825 	 Accuracy: 0.32073011734028684
Delta: 0.0018886406860617667 	  Loss: 1.5689223445533855 	 Accuracy: 0.32073011734028684
Delta: 0.0006335253597441425 	  Loss: 1.5689356228141 	 Accuracy: 0.3220338983050847
Delta: 0.0011512896691186188 	  Loss: 1.5691796178155495 	 Accuracy: 0.3220338983050847
Delta: 0.0011698469993021454 	  Loss: 1.5689582838120377 	 Accuracy: 0.32073011734028684
Delta: 0.0007504259093250875 	  Loss: 1.5691458896195556 	 Accuracy: 0.32073011734028684
Delta: 0.00271890576580644 	  Loss: 1.5695121043266522 	 Accuracy: 0.32073011734028684
Delta: 2.8931462613505356e-06 	  Loss: 1.5695092756051992 	 Accuracy: 0.32073011734028684
Delta: 0.002038503656792237 	  Loss: 1.5691524636944083 	 Accuracy: 0.32073011734028684
Delta: 0.0016674095862322922 	  Loss: 1.5690584310278686 	 Accuracy: 0.32333767926988266
Delta: 0.0021543927139683946 	  Loss: 1.5688817734234186 	 Accuracy: 0.32073011734028684
Delta: 2.5196517121581732e-05 	  Loss: 1.5688373238063835 	 Accuracy: 0.3220338983050847
Delta: 0.0015818320878381279 	  Loss: 1.5687974535342413 	 Accuracy: 0.3220338983050847
Delta: 3.751718710634246e-05 	  Loss: 1.5688210014676218 	 Accuracy: 0.3220338983050847
Delta: 0.0028051218350687145 	  Loss: 1.5696304922874773 	 Accuracy: 0.3220338983050847
Delta: 0.0027592758504921097 	  Loss: 1.5688370720881644 	 Accuracy: 0.3220338983050847
Delta: 0.0007384115345333208 	  Loss: 1.5690039780363536 	 Accuracy: 0.3220338983050847
Delta: 0.004485965363868612 	  Loss: 1.5696082232685737 	 Accuracy: 0.3220338983050847
Delta: 0.0005227803407336757 	  Loss: 1.5696492477494877 	 Accuracy: 0.3220338983050847
Delta: 0.0025456328106451633 	  Loss: 1.5688235696224087 	 Accuracy: 0.3220338983050847
Delta: 0.0017568092113210468 	  Loss: 1.5688281485949964 	 Accuracy: 0.32985658409387225
Delta: 0.0007571784452304465 	  Loss: 1.5688445136081368 	 Accuracy: 0.3220338983050847
Delta: 6.575614338963576e-05 	  Loss: 1.5687907789406124 	 Accuracy: 0.3220338983050847
Delta: 0.0007348007810927627 	  Loss: 1.5687804793086253 	 Accuracy: 0.3220338983050847
Delta: 2.6274613949455117e-05 	  Loss: 1.568754728167896 	 Accuracy: 0.32333767926988266
Delta: 7.857901780183696e-05 	  Loss: 1.5690814949991676 	 Accuracy: 0.32333767926988266
Delta: 8.63088026787611e-05 	  Loss: 1.5688478557519145 	 Accuracy: 0.32073011734028684
Delta: 0.0006915177890358792 	  Loss: 1.5694489862852414 	 Accuracy: 0.3272490221642764
Delta: 0.0002013463965789716 	  Loss: 1.5689407927445307 	 Accuracy: 0.32073011734028684
Delta: 3.3941852186964074e-05 	  Loss: 1.5690385081077733 	 Accuracy: 0.3220338983050847
Delta: 4.879488195572698e-05 	  Loss: 1.5688014883929027 	 Accuracy: 0.3220338983050847
Delta: 2.693425102958187e-05 	  Loss: 1.5688854968604211 	 Accuracy: 0.3220338983050847
Delta: 0.00327176648804816 	  Loss: 1.5694080984322503 	 Accuracy: 0.3220338983050847
Delta: 5.8824554451519525e-05 	  Loss: 1.569477513635038 	 Accuracy: 0.3220338983050847
Delta: 4.285556807106682e-05 	  Loss: 1.569481511370292 	 Accuracy: 0.3220338983050847
Delta: 4.8239634344240096e-05 	  Loss: 1.5694886703020008 	 Accuracy: 0.3220338983050847
Delta: 0.002771055814423248 	  Loss: 1.5698129271302004 	 Accuracy: 0.3220338983050847
Delta: 0.0006059097934776502 	  Loss: 1.569633677091351 	 Accuracy: 0.3246414602346806
Delta: 0.004969465808675856 	  Loss: 1.569849779382292 	 Accuracy: 0.3155149934810952
Delta: 0.004630061143842819 	  Loss: 1.568939879191264 	 Accuracy: 0.3220338983050847
Delta: 0.001201077535877277 	  Loss: 1.5690816803466094 	 Accuracy: 0.3220338983050847
Delta: 0.00435381713710608 	  Loss: 1.5693769524853507 	 Accuracy: 0.3220338983050847
Delta: 0.000782740119405319 	  Loss: 1.5693726018497753 	 Accuracy: 0.3220338983050847
Delta: 0.0009819558812052993 	  Loss: 1.5695618102120217 	 Accuracy: 0.32073011734028684
Delta: 0.0027210674034093677 	  Loss: 1.5698781501011831 	 Accuracy: 0.32073011734028684
Delta: 0.003027842388804526 	  Loss: 1.5706646310326287 	 Accuracy: 0.32073011734028684
Delta: 0.0020489165310133973 	  Loss: 1.5709606869478068 	 Accuracy: 0.32333767926988266
Delta: 0.020963694182534538 	  Loss: 2.1578205214768107 	 Accuracy: 0.22946544980443284
Delta: 0.01863418545977914 	  Loss: 2.0531498614689765 	 Accuracy: 0.24771838331160365
Delta: 0.01765799327404202 	  Loss: 1.8641311890679084 	 Accuracy: 0.3011734028683181
Delta: 0.015237643969146597 	  Loss: 1.687827661239308 	 Accuracy: 0.29595827900912647
Delta: 0.012034141360044836 	  Loss: 1.613489460098771 	 Accuracy: 0.318122555410691
Delta: 0.00976164080980092 	  Loss: 1.5910108684710533 	 Accuracy: 0.32333767926988266
Delta: 0.007811801391330994 	  Loss: 1.5847776506432423 	 Accuracy: 0.3220338983050847

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006705196804187196 	  Loss: 1.5829371502009169 	 Accuracy: 0.3272490221642764
Delta: 0.006085230019883416 	  Loss: 1.5825544974843868 	 Accuracy: 0.3272490221642764
Delta: 0.005004585788365591 	  Loss: 1.5822829279814756 	 Accuracy: 0.32985658409387225
Delta: 0.0031360509789484974 	  Loss: 1.5821254417090285 	 Accuracy: 0.3272490221642764
Delta: 0.003379984151204373 	  Loss: 1.5820949149868753 	 Accuracy: 0.32985658409387225
Delta: 0.0034493325469605192 	  Loss: 1.5821370675453739 	 Accuracy: 0.3272490221642764
Delta: 0.0019958522925424336 	  Loss: 1.5820230321332205 	 Accuracy: 0.3272490221642764
Delta: 0.0013412359741067157 	  Loss: 1.581908241076977 	 Accuracy: 0.3272490221642764
Delta: 0.0009596899335382997 	  Loss: 1.5821128605224297 	 Accuracy: 0.3272490221642764
Delta: 0.0010808825411353104 	  Loss: 1.5819957958695037 	 Accuracy: 0.3272490221642764
Delta: 0.0005163822168394799 	  Loss: 1.5819787999655015 	 Accuracy: 0.3272490221642764
Delta: 4.927717103814484e-05 	  Loss: 1.5819763681321408 	 Accuracy: 0.3272490221642764
Delta: 0.0017849361114511987 	  Loss: 1.582115166236541 	 Accuracy: 0.3272490221642764
Delta: 0.004406133829401497 	  Loss: 1.5822689403832109 	 Accuracy: 0.32985658409387225
Delta: 0.0030915309527315606 	  Loss: 1.5822195087702453 	 Accuracy: 0.3272490221642764
Delta: 0.002500800634979374 	  Loss: 1.5818796952132965 	 Accuracy: 0.3259452411994785
Delta: 0.0028481791476687025 	  Loss: 1.5820012778633097 	 Accuracy: 0.3272490221642764
Delta: 0.002295598819085399 	  Loss: 1.581945669480383 	 Accuracy: 0.3272490221642764
Delta: 0.001421515275099622 	  Loss: 1.5818479426467746 	 Accuracy: 0.3272490221642764
Delta: 2.0040561788182093e-05 	  Loss: 1.5818908611389657 	 Accuracy: 0.3272490221642764
Delta: 2.1132601191200518e-05 	  Loss: 1.58186076274285 	 Accuracy: 0.318122555410691
Delta: 0.0008990761888810022 	  Loss: 1.5821272905698662 	 Accuracy: 0.3272490221642764
Delta: 0.004181487989834406 	  Loss: 1.5825213359005588 	 Accuracy: 0.3259452411994785
Delta: 0.005308863021280303 	  Loss: 1.5823617388091278 	 Accuracy: 0.3272490221642764
Delta: 0.0038214103356505975 	  Loss: 1.5827351217355337 	 Accuracy: 0.3259452411994785
Delta: 0.004696738762511694 	  Loss: 1.5831052207663785 	 Accuracy: 0.3259452411994785
Delta: 0.003489777193293255 	  Loss: 1.5832802103336336 	 Accuracy: 0.3259452411994785
Delta: 0.0031608491575388525 	  Loss: 1.583306205469968 	 Accuracy: 0.3259452411994785
Delta: 0.0006565559610496334 	  Loss: 1.583275143250728 	 Accuracy: 0.3259452411994785
Delta: 0.0016206783480164069 	  Loss: 1.58309989662848 	 Accuracy: 0.3259452411994785
Delta: 0.003484195719105874 	  Loss: 1.5828856155960205 	 Accuracy: 0.3272490221642764
Delta: 0.002193619359701909 	  Loss: 1.5823076680706012 	 Accuracy: 0.3259452411994785
Delta: 0.003451739370598913 	  Loss: 1.5824579873308104 	 Accuracy: 0.3259452411994785
Delta: 0.001080510329763739 	  Loss: 1.5825234380682363 	 Accuracy: 0.3246414602346806
Delta: 0.0027005213347096 	  Loss: 1.582890935823173 	 Accuracy: 0.32333767926988266
Delta: 0.002627413768540837 	  Loss: 1.582818056981249 	 Accuracy: 0.3259452411994785
Delta: 0.0031046239104736226 	  Loss: 1.5824882264105729 	 Accuracy: 0.32333767926988266
Delta: 0.0017013484954328608 	  Loss: 1.5825391784425102 	 Accuracy: 0.3246414602346806
Delta: 4.4606664137250795e-05 	  Loss: 1.5823830421405158 	 Accuracy: 0.3259452411994785
Delta: 0.001131508898057182 	  Loss: 1.5826499148050497 	 Accuracy: 0.3272490221642764
Delta: 0.0022567787664873637 	  Loss: 1.5830001667029556 	 Accuracy: 0.3272490221642764
Delta: 0.0013290117795926224 	  Loss: 1.5824826033224177 	 Accuracy: 0.3272490221642764
Delta: 0.0029894529985962947 	  Loss: 1.5829225038584798 	 Accuracy: 0.3285528031290743
Delta: 0.004418791861571247 	  Loss: 1.5825786245434643 	 Accuracy: 0.3285528031290743
Delta: 0.002650465909122149 	  Loss: 1.582385006236913 	 Accuracy: 0.3259452411994785
Delta: 4.560773591129651e-05 	  Loss: 1.5824225355235655 	 Accuracy: 0.3272490221642764
Delta: 3.756001331802839e-05 	  Loss: 1.582278194687125 	 Accuracy: 0.3259452411994785
Delta: 0.0013982183022743018 	  Loss: 1.5825640812875843 	 Accuracy: 0.3259452411994785
Delta: 0.003145901887969198 	  Loss: 1.5825653585654218 	 Accuracy: 0.3259452411994785
Delta: 0.0027797319129115273 	  Loss: 1.5822486333690864 	 Accuracy: 0.32985658409387225
Delta: 0.002925098524719111 	  Loss: 1.5826653309768757 	 Accuracy: 0.3272490221642764
Delta: 0.004404814814003701 	  Loss: 1.5825590470030364 	 Accuracy: 0.3259452411994785
Delta: 0.0029220983626341676 	  Loss: 1.5830798227184009 	 Accuracy: 0.3259452411994785
Delta: 0.0032076456557062526 	  Loss: 1.583101889320695 	 Accuracy: 0.3246414602346806
Delta: 0.002764024847754589 	  Loss: 1.5835525495145268 	 Accuracy: 0.3220338983050847
Delta: 0.0015219481728543478 	  Loss: 1.583720774226892 	 Accuracy: 0.3259452411994785
Delta: 0.0027109787933419986 	  Loss: 1.5840366034733444 	 Accuracy: 0.3272490221642764
Delta: 2.5883546636052964e-05 	  Loss: 1.5841058993460075 	 Accuracy: 0.3350717079530639
Delta: 0.0018472161536661953 	  Loss: 1.5835921435944877 	 Accuracy: 0.3272490221642764
Delta: 0.0006633320295534349 	  Loss: 1.5840296491372077 	 Accuracy: 0.3259452411994785
Delta: 9.06740304973278e-05 	  Loss: 1.5838171722120187 	 Accuracy: 0.3259452411994785
Delta: 0.004256063066759466 	  Loss: 1.5842638581629207 	 Accuracy: 0.3259452411994785
Delta: 0.0019383167577728293 	  Loss: 1.5840165832969388 	 Accuracy: 0.3272490221642764
Delta: 0.0014342740825677184 	  Loss: 1.5840748802061375 	 Accuracy: 0.3272490221642764
Delta: 0.004024818041870835 	  Loss: 1.5846986885073981 	 Accuracy: 0.32985658409387225
Delta: 0.005637322692893432 	  Loss: 1.5843326024575242 	 Accuracy: 0.32985658409387225
Delta: 0.0023186223958001646 	  Loss: 1.584394055582821 	 Accuracy: 0.3285528031290743
Delta: 0.005310982862446471 	  Loss: 1.584622571646542 	 Accuracy: 0.3285528031290743
Delta: 0.003760260734310477 	  Loss: 1.5844942646824998 	 Accuracy: 0.32985658409387225
Delta: 0.0019365282800318214 	  Loss: 1.5844444683054482 	 Accuracy: 0.32985658409387225
Delta: 0.0004982399990096084 	  Loss: 1.5844405922911606 	 Accuracy: 0.32985658409387225
Delta: 2.8179215599583107e-06 	  Loss: 1.5844430212004659 	 Accuracy: 0.32985658409387225
Delta: 0.003932799108767667 	  Loss: 1.5846962809885898 	 Accuracy: 0.32985658409387225
Delta: 0.00320151659637629 	  Loss: 1.5840792583483407 	 Accuracy: 0.3285528031290743
Delta: 0.0023323495826054353 	  Loss: 1.5840918884877726 	 Accuracy: 0.32333767926988266
Delta: 4.55693900504243e-05 	  Loss: 1.5841800716401981 	 Accuracy: 0.32985658409387225
Delta: 0.0015606249353019082 	  Loss: 1.5845854155708605 	 Accuracy: 0.32985658409387225
Delta: 0.0022954443369303202 	  Loss: 1.584454740958059 	 Accuracy: 0.3285528031290743
Delta: 0.0016737605810364174 	  Loss: 1.5842946214973876 	 Accuracy: 0.32985658409387225
Delta: 0.0022576542044387394 	  Loss: 1.5840781523714704 	 Accuracy: 0.32985658409387225
Delta: 0.0010245083497757903 	  Loss: 1.5843662198067976 	 Accuracy: 0.32985658409387225
Delta: 0.0010234993585201326 	  Loss: 1.5841373715657694 	 Accuracy: 0.3285528031290743
Delta: 0.003785262577611214 	  Loss: 1.5843428161791837 	 Accuracy: 0.33376792698826596
Delta: 0.0027996613003193364 	  Loss: 1.583959673264839 	 Accuracy: 0.3285528031290743
Delta: 0.0007141931338289618 	  Loss: 1.584110410111857 	 Accuracy: 0.33376792698826596
Delta: 0.005563761237070846 	  Loss: 1.5834061224729439 	 Accuracy: 0.3220338983050847
Delta: 0.003622885882993263 	  Loss: 1.5846423452861775 	 Accuracy: 0.32985658409387225
Delta: 0.0010304691869106096 	  Loss: 1.5848073986451006 	 Accuracy: 0.3272490221642764
Delta: 0.004395537413949285 	  Loss: 1.5837279295004376 	 Accuracy: 0.32985658409387225
Delta: 0.003896824443715636 	  Loss: 1.5835430460668725 	 Accuracy: 0.3272490221642764
Delta: 0.003912202170950268 	  Loss: 1.5838186066139186 	 Accuracy: 0.3272490221642764
Delta: 0.0038195266022896255 	  Loss: 1.5845079093118817 	 Accuracy: 0.32985658409387225
Delta: 0.003420955415590873 	  Loss: 1.5841239030879435 	 Accuracy: 0.32985658409387225
Delta: 0.02088832423320757 	  Loss: 2.1591876534697736 	 Accuracy: 0.22294654498044328
Delta: 0.01867787663222728 	  Loss: 2.0633936441867853 	 Accuracy: 0.24771838331160365
Delta: 0.017654707367919683 	  Loss: 1.8834390212404655 	 Accuracy: 0.2790091264667536
Delta: 0.016170144020255822 	  Loss: 1.7214541500057337 	 Accuracy: 0.28552803129074317
Delta: 0.013391427503925095 	  Loss: 1.631427931548267 	 Accuracy: 0.2790091264667536
Delta: 0.010454378932451065 	  Loss: 1.6000117235312878 	 Accuracy: 0.27249022164276404
Delta: 0.008155482538834647 	  Loss: 1.5924794695678184 	 Accuracy: 0.27249022164276404

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006589070780762678 	  Loss: 1.590163587740816 	 Accuracy: 0.2646675358539765
Delta: 0.005631183229500201 	  Loss: 1.5892665550390013 	 Accuracy: 0.2607561929595828
Delta: 0.005141709787657583 	  Loss: 1.5887030114333904 	 Accuracy: 0.2620599739243807
Delta: 0.004433805888149891 	  Loss: 1.5883151185213091 	 Accuracy: 0.2620599739243807
Delta: 0.0035257025039643498 	  Loss: 1.5881951297294168 	 Accuracy: 0.25945241199478486
Delta: 0.0024833110264555567 	  Loss: 1.588125039835533 	 Accuracy: 0.2607561929595828
Delta: 0.0029239395813418717 	  Loss: 1.5882525564396945 	 Accuracy: 0.25945241199478486
Delta: 0.0017154380987927903 	  Loss: 1.5883023385498283 	 Accuracy: 0.2607561929595828
Delta: 0.0005126682621487947 	  Loss: 1.5883180966682449 	 Accuracy: 0.2607561929595828
Delta: 0.00360209812066439 	  Loss: 1.5883602808894637 	 Accuracy: 0.2607561929595828
Delta: 0.0014508785184744021 	  Loss: 1.5884072786071308 	 Accuracy: 0.2607561929595828
Delta: 0.0010800576460844602 	  Loss: 1.5883200220641918 	 Accuracy: 0.2607561929595828
Delta: 1.0166094578267854e-05 	  Loss: 1.588363122013307 	 Accuracy: 0.2607561929595828
Delta: 1.3232739132973822e-05 	  Loss: 1.5883748839462677 	 Accuracy: 0.2607561929595828
Delta: 0.001190965709899339 	  Loss: 1.5882566423789672 	 Accuracy: 0.2607561929595828
Delta: 1.987154227092365e-05 	  Loss: 1.5882377383487838 	 Accuracy: 0.2607561929595828
Delta: 1.6244523001499824e-05 	  Loss: 1.5882717781501094 	 Accuracy: 0.25945241199478486
Delta: 0.001015597042514979 	  Loss: 1.5883629707963314 	 Accuracy: 0.2607561929595828
Delta: 0.0036723696857111545 	  Loss: 1.5887322653522942 	 Accuracy: 0.2620599739243807
Delta: 0.0008203141610315572 	  Loss: 1.5885834924681033 	 Accuracy: 0.2620599739243807
Delta: 0.0013679673942958276 	  Loss: 1.5886054618568393 	 Accuracy: 0.2607561929595828
Delta: 0.0036373597176900026 	  Loss: 1.58832565274807 	 Accuracy: 0.2607561929595828
Delta: 0.0019031469377806436 	  Loss: 1.5884386052661816 	 Accuracy: 0.24902216427640156
Delta: 0.0022700178056708448 	  Loss: 1.5883361911060172 	 Accuracy: 0.2607561929595828
Delta: 0.0010689999796574883 	  Loss: 1.588262467030645 	 Accuracy: 0.2607561929595828
Delta: 9.757178046871129e-06 	  Loss: 1.5882776041763327 	 Accuracy: 0.2607561929595828
Delta: 1.3979781993449705e-05 	  Loss: 1.5882820946049094 	 Accuracy: 0.2607561929595828
Delta: 3.854881929357677e-05 	  Loss: 1.5882180968120279 	 Accuracy: 0.25945241199478486
Delta: 0.0005492381861811725 	  Loss: 1.5883984176345562 	 Accuracy: 0.25945241199478486
Delta: 0.0031019661573491175 	  Loss: 1.588758340609609 	 Accuracy: 0.25945241199478486
Delta: 0.002255074180401431 	  Loss: 1.5882453344270684 	 Accuracy: 0.2607561929595828
Delta: 0.0005253374593220113 	  Loss: 1.5883145319439447 	 Accuracy: 0.2607561929595828
Delta: 0.0006562554158903646 	  Loss: 1.5882091552898845 	 Accuracy: 0.2607561929595828
Delta: 0.0011845246055168267 	  Loss: 1.588265329119212 	 Accuracy: 0.2607561929595828
Delta: 0.0005702091700042007 	  Loss: 1.588072637374073 	 Accuracy: 0.2607561929595828
Delta: 0.000808170106188013 	  Loss: 1.588164051413737 	 Accuracy: 0.2607561929595828
Delta: 3.328920549744929e-05 	  Loss: 1.5880425028987504 	 Accuracy: 0.2607561929595828
Delta: 0.0009820150254130336 	  Loss: 1.5882022937111315 	 Accuracy: 0.25945241199478486
Delta: 0.002630587152388983 	  Loss: 1.58876246939685 	 Accuracy: 0.25945241199478486
Delta: 0.003871259760042287 	  Loss: 1.5889586253207124 	 Accuracy: 0.25945241199478486
Delta: 0.0015055556208358042 	  Loss: 1.5886490441617558 	 Accuracy: 0.25945241199478486
Delta: 0.00322188891227004 	  Loss: 1.588959120327261 	 Accuracy: 0.25945241199478486
Delta: 0.0027339138126755026 	  Loss: 1.589352342880955 	 Accuracy: 0.25945241199478486
Delta: 0.003527888174492968 	  Loss: 1.5895494851386527 	 Accuracy: 0.258148631029987
Delta: 0.0016713634747874543 	  Loss: 1.5896632475482564 	 Accuracy: 0.258148631029987
Delta: 0.0014709854618339445 	  Loss: 1.5894518043301837 	 Accuracy: 0.25945241199478486
Delta: 0.0013279742986068124 	  Loss: 1.589170090539326 	 Accuracy: 0.25945241199478486
Delta: 0.0006071413221145352 	  Loss: 1.5894937149286466 	 Accuracy: 0.25684485006518903
Delta: 0.00211992338459027 	  Loss: 1.5892957816107918 	 Accuracy: 0.25945241199478486
Delta: 2.7596043794742723e-05 	  Loss: 1.5893094554366864 	 Accuracy: 0.25945241199478486
Delta: 8.562333664614063e-05 	  Loss: 1.5895105412481825 	 Accuracy: 0.258148631029987
Delta: 0.0023379823061265457 	  Loss: 1.5896025039582249 	 Accuracy: 0.25945241199478486
Delta: 0.0019017384471988854 	  Loss: 1.5893613756273446 	 Accuracy: 0.25945241199478486
Delta: 0.002362896343470694 	  Loss: 1.5897008291943413 	 Accuracy: 0.25945241199478486
Delta: 0.0038099432511274 	  Loss: 1.5891093549077189 	 Accuracy: 0.25945241199478486
Delta: 0.003813136005344657 	  Loss: 1.5885995335035425 	 Accuracy: 0.25945241199478486
Delta: 0.002728058103668002 	  Loss: 1.5891142557413518 	 Accuracy: 0.25945241199478486
Delta: 0.0024019026066104667 	  Loss: 1.5895331103498336 	 Accuracy: 0.25945241199478486
Delta: 3.853540901739713e-05 	  Loss: 1.589490832478252 	 Accuracy: 0.25945241199478486
Delta: 3.8463805431916584e-05 	  Loss: 1.5894453752453161 	 Accuracy: 0.25945241199478486
Delta: 3.593105664550894e-05 	  Loss: 1.5895281834554584 	 Accuracy: 0.25945241199478486
Delta: 0.002201993640700612 	  Loss: 1.5886310050534087 	 Accuracy: 0.25945241199478486
Delta: 0.0013810617726519332 	  Loss: 1.5887909989645208 	 Accuracy: 0.25945241199478486
Delta: 0.0005413736454148802 	  Loss: 1.588612600901889 	 Accuracy: 0.258148631029987
Delta: 3.5267182947671484e-05 	  Loss: 1.588621931026073 	 Accuracy: 0.258148631029987
Delta: 5.587931378964849e-05 	  Loss: 1.5888570643331108 	 Accuracy: 0.258148631029987
Delta: 0.0030412225394785557 	  Loss: 1.5894810054361745 	 Accuracy: 0.2607561929595828
Delta: 0.0011704593226240557 	  Loss: 1.5891903543457144 	 Accuracy: 0.25945241199478486
Delta: 0.0010692951082657734 	  Loss: 1.589587273810785 	 Accuracy: 0.25945241199478486
Delta: 9.179614661718004e-06 	  Loss: 1.5895675522054677 	 Accuracy: 0.25945241199478486
Delta: 5.7387324041083704e-05 	  Loss: 1.5893182693527272 	 Accuracy: 0.25945241199478486
Delta: 0.0031142576311168424 	  Loss: 1.5890393806682772 	 Accuracy: 0.25945241199478486
Delta: 0.0016127337362673525 	  Loss: 1.5888665823255685 	 Accuracy: 0.25945241199478486
Delta: 3.457987219020079e-05 	  Loss: 1.588920832999188 	 Accuracy: 0.25945241199478486
Delta: 3.4118922041179594e-05 	  Loss: 1.5888672375859956 	 Accuracy: 0.25945241199478486
Delta: 0.0005362875929849301 	  Loss: 1.589181162139921 	 Accuracy: 0.258148631029987
Delta: 0.0018694168020070268 	  Loss: 1.5890853002871341 	 Accuracy: 0.25945241199478486
Delta: 0.0013530125951219105 	  Loss: 1.5888676128191075 	 Accuracy: 0.2607561929595828
Delta: 1.5869646344738246e-05 	  Loss: 1.588865403656321 	 Accuracy: 0.25945241199478486
Delta: 0.0009457246782423613 	  Loss: 1.5889166147485467 	 Accuracy: 0.25945241199478486
Delta: 0.0005618906282840973 	  Loss: 1.5890462401910286 	 Accuracy: 0.25945241199478486
Delta: 0.002304198708434061 	  Loss: 1.5889099239438527 	 Accuracy: 0.258148631029987
Delta: 2.9989646244701307e-05 	  Loss: 1.588958480835235 	 Accuracy: 0.25945241199478486
Delta: 3.0062772546972328e-05 	  Loss: 1.5889017200151376 	 Accuracy: 0.25945241199478486
Delta: 0.0017352013665784649 	  Loss: 1.5889053911068518 	 Accuracy: 0.25945241199478486
Delta: 0.0024237117337239764 	  Loss: 1.5893501795837084 	 Accuracy: 0.2620599739243807
Delta: 0.004587671936884885 	  Loss: 1.5902893124850068 	 Accuracy: 0.25945241199478486
Delta: 0.0023111878576055297 	  Loss: 1.5901955407726378 	 Accuracy: 0.25945241199478486
Delta: 0.001742652372290995 	  Loss: 1.5902135717809402 	 Accuracy: 0.25945241199478486
Delta: 8.538826674247672e-05 	  Loss: 1.5901977119418544 	 Accuracy: 0.25945241199478486
Delta: 8.513509438814502e-05 	  Loss: 1.5902255850961087 	 Accuracy: 0.25945241199478486
Delta: 6.600740043579215e-08 	  Loss: 1.590225547470478 	 Accuracy: 0.25945241199478486
converged at iter  98
Delta: 0.021104538681999244 	  Loss: 2.156243017368899 	 Accuracy: 0.18904823989569752
Delta: 0.018984309817545026 	  Loss: 2.029838841027349 	 Accuracy: 0.24902216427640156
Delta: 0.017414473375414588 	  Loss: 1.8097858024580487 	 Accuracy: 0.25554106910039115
Delta: 0.01471258448413148 	  Loss: 1.6560763484880325 	 Accuracy: 0.2333767926988266
Delta: 0.011301501183578767 	  Loss: 1.6076885507069645 	 Accuracy: 0.22164276401564537
Delta: 0.008826536794990496 	  Loss: 1.5920977651489219 	 Accuracy: 0.21642764015645372

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007476058361424854 	  Loss: 1.5873647368922208 	 Accuracy: 0.22294654498044328
Delta: 0.006790171903237799 	  Loss: 1.5856597232678182 	 Accuracy: 0.21903520208604954
Delta: 0.005444695647533743 	  Loss: 1.5851935884943407 	 Accuracy: 0.21773142112125163
Delta: 0.0031174622272400424 	  Loss: 1.5850613541660206 	 Accuracy: 0.21773142112125163
Delta: 0.0032690960095140054 	  Loss: 1.5850012992890763 	 Accuracy: 0.21773142112125163
Delta: 0.0011068408024263027 	  Loss: 1.58496903524235 	 Accuracy: 0.21773142112125163
Delta: 0.003311112180447761 	  Loss: 1.585036537072909 	 Accuracy: 0.21903520208604954
Delta: 0.0025723332259279023 	  Loss: 1.5850362540414586 	 Accuracy: 0.22033898305084745
Delta: 0.0005377394490449919 	  Loss: 1.5850618149626297 	 Accuracy: 0.21903520208604954
Delta: 6.494961030118209e-05 	  Loss: 1.5850640649764296 	 Accuracy: 0.21773142112125163
Delta: 3.9667142208701586e-05 	  Loss: 1.5849546762320603 	 Accuracy: 0.21903520208604954
Delta: 0.0013607461674578598 	  Loss: 1.5850177611820215 	 Accuracy: 0.21903520208604954
Delta: 5.19459093436952e-05 	  Loss: 1.5850465036806654 	 Accuracy: 0.21773142112125163
Delta: 0.0036416133075433555 	  Loss: 1.584570043417846 	 Accuracy: 0.21903520208604954
Delta: 0.00317609698294894 	  Loss: 1.5847684193194325 	 Accuracy: 0.21773142112125163
Delta: 0.0015834861696918572 	  Loss: 1.5848910080659824 	 Accuracy: 0.22033898305084745
Delta: 0.0006892027079203015 	  Loss: 1.58483133342788 	 Accuracy: 0.21903520208604954
Delta: 0.002718669874804176 	  Loss: 1.58471697458425 	 Accuracy: 0.21903520208604954
Delta: 0.0016649615443912653 	  Loss: 1.5850452986662948 	 Accuracy: 0.21903520208604954
Delta: 0.00093880004911019 	  Loss: 1.585123739946038 	 Accuracy: 0.21903520208604954
Delta: 0.0015951498376158624 	  Loss: 1.584979987266154 	 Accuracy: 0.21903520208604954
Delta: 0.0016869935183194114 	  Loss: 1.5848120951541675 	 Accuracy: 0.21642764015645372
Delta: 0.003459418990047251 	  Loss: 1.5853156155688313 	 Accuracy: 0.21903520208604954
Delta: 0.002390197761475603 	  Loss: 1.585220871266437 	 Accuracy: 0.21903520208604954
Delta: 0.004872651287478985 	  Loss: 1.585045419620497 	 Accuracy: 0.21903520208604954
Delta: 0.0025842069290134316 	  Loss: 1.5850052066943343 	 Accuracy: 0.21903520208604954
Delta: 0.0006009058887968855 	  Loss: 1.5848799272877003 	 Accuracy: 0.22033898305084745
Delta: 0.003624170782283516 	  Loss: 1.5850436030226318 	 Accuracy: 0.21903520208604954
Delta: 5.518738524458e-05 	  Loss: 1.5850299992799628 	 Accuracy: 0.21903520208604954
Delta: 0.0022444373897419416 	  Loss: 1.5851686340429734 	 Accuracy: 0.21903520208604954
Delta: 0.0018059787159787257 	  Loss: 1.584940926988573 	 Accuracy: 0.21903520208604954
Delta: 0.0005194440745779806 	  Loss: 1.584712712613346 	 Accuracy: 0.21903520208604954
Delta: 0.0005309675470882479 	  Loss: 1.5848760158468411 	 Accuracy: 0.21903520208604954
Delta: 0.0012321952292867974 	  Loss: 1.5849210035639072 	 Accuracy: 0.21903520208604954
Delta: 0.0021876990302690863 	  Loss: 1.5850440039783487 	 Accuracy: 0.21903520208604954
Delta: 0.0005339984918734876 	  Loss: 1.584642259664635 	 Accuracy: 0.22033898305084745
Delta: 0.0015894380755549942 	  Loss: 1.5847149772879354 	 Accuracy: 0.21903520208604954
Delta: 2.762375686843451e-05 	  Loss: 1.58466602789873 	 Accuracy: 0.21642764015645372
Delta: 0.003906246980954321 	  Loss: 1.5849254560857455 	 Accuracy: 0.21773142112125163
Delta: 0.0007940904747890472 	  Loss: 1.5847187261761482 	 Accuracy: 0.21773142112125163
Delta: 3.758302998126158e-05 	  Loss: 1.584742598499922 	 Accuracy: 0.21773142112125163
Delta: 0.0025661459881007893 	  Loss: 1.585037174733395 	 Accuracy: 0.21642764015645372
Delta: 0.005422867340319294 	  Loss: 1.5860770127164199 	 Accuracy: 0.21773142112125163
Delta: 0.0016331370097678244 	  Loss: 1.5855583205320878 	 Accuracy: 0.21642764015645372
Delta: 0.001712425532836533 	  Loss: 1.586114891015097 	 Accuracy: 0.21642764015645372
Delta: 0.004026003385637617 	  Loss: 1.5858240737986216 	 Accuracy: 0.21642764015645372
Delta: 0.0036256547061331228 	  Loss: 1.5861606666975243 	 Accuracy: 0.21642764015645372
Delta: 0.0038349315134069387 	  Loss: 1.5855906800967752 	 Accuracy: 0.21642764015645372
Delta: 0.0018434920775014382 	  Loss: 1.5858198371051135 	 Accuracy: 0.21773142112125163
Delta: 0.002449526616752928 	  Loss: 1.5858030040285582 	 Accuracy: 0.21642764015645372
Delta: 0.0007663861747415653 	  Loss: 1.585672919386853 	 Accuracy: 0.2151238591916558
Delta: 0.002455104225468495 	  Loss: 1.5862627572680048 	 Accuracy: 0.21642764015645372
Delta: 0.0019131879408303947 	  Loss: 1.586366713004412 	 Accuracy: 0.21642764015645372
Delta: 1.9182403212706042e-05 	  Loss: 1.5862753208706284 	 Accuracy: 0.21642764015645372
Delta: 0.0026231556199453098 	  Loss: 1.5862706214254603 	 Accuracy: 0.21773142112125163
Delta: 0.0008207591061795966 	  Loss: 1.5861477159042079 	 Accuracy: 0.21773142112125163
Delta: 0.004840551018163476 	  Loss: 1.5859045104062552 	 Accuracy: 0.21903520208604954
Delta: 0.001895633157202883 	  Loss: 1.5858331947996884 	 Accuracy: 0.21773142112125163
Delta: 0.004076836557095145 	  Loss: 1.5859562316959086 	 Accuracy: 0.21773142112125163
Delta: 0.002439630186321962 	  Loss: 1.5857905597267703 	 Accuracy: 0.21773142112125163
Delta: 0.002371774762082462 	  Loss: 1.5860828890883982 	 Accuracy: 0.21773142112125163
Delta: 0.004595436863224122 	  Loss: 1.586179053692775 	 Accuracy: 0.22033898305084745
Delta: 0.003093461786542284 	  Loss: 1.585796634029007 	 Accuracy: 0.21773142112125163
Delta: 0.0027290433503219815 	  Loss: 1.586048324740032 	 Accuracy: 0.2151238591916558
Delta: 0.00194241874799406 	  Loss: 1.585741461709263 	 Accuracy: 0.21642764015645372
Delta: 1.7448415449005252e-05 	  Loss: 1.5857724030162514 	 Accuracy: 0.2151238591916558
Delta: 0.0033985024043859135 	  Loss: 1.5855045849112404 	 Accuracy: 0.2151238591916558
Delta: 7.2483176804132855e-06 	  Loss: 1.5854972914643166 	 Accuracy: 0.21642764015645372
Delta: 0.00320810585540293 	  Loss: 1.5858865746545643 	 Accuracy: 0.21642764015645372
Delta: 2.7197651659871193e-05 	  Loss: 1.5857724254962888 	 Accuracy: 0.21642764015645372
Delta: 0.003592664046820855 	  Loss: 1.5861617013487024 	 Accuracy: 0.21642764015645372
Delta: 0.0049276984351400615 	  Loss: 1.5872542966882786 	 Accuracy: 0.2138200782268579
Delta: 0.0034420663358913127 	  Loss: 1.587433070137294 	 Accuracy: 0.2151238591916558
Delta: 0.005252306839000479 	  Loss: 1.5860152775385314 	 Accuracy: 0.2151238591916558
Delta: 0.00611497209322817 	  Loss: 1.5862742592280017 	 Accuracy: 0.2138200782268579
Delta: 0.0060082955142043235 	  Loss: 1.5852214862873684 	 Accuracy: 0.21642764015645372
Delta: 0.0023354904553647008 	  Loss: 1.5847788666786427 	 Accuracy: 0.2151238591916558
Delta: 0.004296142686096467 	  Loss: 1.5855804129138822 	 Accuracy: 0.2151238591916558
Delta: 0.002607430031952648 	  Loss: 1.585494324378088 	 Accuracy: 0.21251629726205998
Delta: 0.004757038522915836 	  Loss: 1.586188195344597 	 Accuracy: 0.2151238591916558
Delta: 0.0024762487334423666 	  Loss: 1.585988645979228 	 Accuracy: 0.2151238591916558
Delta: 0.0013713994152654706 	  Loss: 1.5856084995479578 	 Accuracy: 0.2151238591916558
Delta: 2.916072367210473e-05 	  Loss: 1.5856857656036218 	 Accuracy: 0.2138200782268579
Delta: 0.0028884593821410097 	  Loss: 1.5857648010542829 	 Accuracy: 0.2151238591916558
Delta: 0.004181693610951245 	  Loss: 1.5850559373638144 	 Accuracy: 0.2138200782268579
Delta: 0.0019904567255637235 	  Loss: 1.585267334296066 	 Accuracy: 0.2138200782268579
Delta: 2.6418795773680705e-05 	  Loss: 1.5852524166337978 	 Accuracy: 0.2138200782268579
Delta: 0.004175794699415756 	  Loss: 1.5859327921403514 	 Accuracy: 0.2138200782268579
Delta: 0.0024834216336102836 	  Loss: 1.5856178002274 	 Accuracy: 0.2138200782268579
Delta: 0.0006563203449835983 	  Loss: 1.5853968988337686 	 Accuracy: 0.2138200782268579
Delta: 6.986251388079334e-06 	  Loss: 1.5853882270209967 	 Accuracy: 0.2138200782268579
Delta: 6.921586393347753e-05 	  Loss: 1.5855399181899252 	 Accuracy: 0.21773142112125163
Delta: 7.395302633376904e-05 	  Loss: 1.585495266248688 	 Accuracy: 0.2138200782268579
Delta: 0.002907843239800312 	  Loss: 1.5860413043905333 	 Accuracy: 0.2151238591916558
Delta: 0.020935470909375465 	  Loss: 2.1592919044937133 	 Accuracy: 0.27509778357235987
Delta: 0.01913633065094042 	  Loss: 2.0539935103977953 	 Accuracy: 0.24641460234680573
Delta: 0.017955129816562367 	  Loss: 1.8527939025730604 	 Accuracy: 0.28683181225554105
Delta: 0.015941939447206135 	  Loss: 1.6850936452080725 	 Accuracy: 0.26727509778357234
Delta: 0.012365680650892514 	  Loss: 1.6112638093471656 	 Accuracy: 0.24641460234680573
Delta: 0.009741525760445943 	  Loss: 1.5919604911910328 	 Accuracy: 0.2438070404172099
Delta: 0.006835453812707891 	  Loss: 1.5873585940320294 	 Accuracy: 0.23728813559322035

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005310694779047276 	  Loss: 1.5862587869472908 	 Accuracy: 0.23598435462842243
Delta: 0.004885575577803252 	  Loss: 1.5859762887376532 	 Accuracy: 0.23598435462842243
Delta: 0.0038828172363601448 	  Loss: 1.5859297626784024 	 Accuracy: 0.23076923076923078
Delta: 0.0038800027576797918 	  Loss: 1.586117617850945 	 Accuracy: 0.23468057366362452
Delta: 0.0015331866922578962 	  Loss: 1.5861162560496684 	 Accuracy: 0.23598435462842243
Delta: 0.0023914117735842942 	  Loss: 1.5861157629476734 	 Accuracy: 0.23598435462842243
Delta: 0.0018681770250917756 	  Loss: 1.5861751706099607 	 Accuracy: 0.23598435462842243
Delta: 0.001004399384001483 	  Loss: 1.5861428747356228 	 Accuracy: 0.23728813559322035
Delta: 0.0012566191275775987 	  Loss: 1.586092709645798 	 Accuracy: 0.23728813559322035
Delta: 0.0007144783196279135 	  Loss: 1.5860888564793136 	 Accuracy: 0.23728813559322035
Delta: 0.0018340611072667757 	  Loss: 1.5862378725675723 	 Accuracy: 0.23728813559322035
Delta: 2.4741063578809913e-05 	  Loss: 1.5861782136549618 	 Accuracy: 0.23728813559322035
Delta: 0.0015176807899871458 	  Loss: 1.5861254090205588 	 Accuracy: 0.23728813559322035
Delta: 0.001425495454756691 	  Loss: 1.5861635436178056 	 Accuracy: 0.23728813559322035
Delta: 0.0012237551750731827 	  Loss: 1.5862051846214649 	 Accuracy: 0.23598435462842243
Delta: 0.0032426311781178696 	  Loss: 1.5864820946044844 	 Accuracy: 0.23728813559322035
Delta: 0.0011830167780302696 	  Loss: 1.5867351904540816 	 Accuracy: 0.23728813559322035
Delta: 0.0031590734546888613 	  Loss: 1.5870095727237676 	 Accuracy: 0.23989569752281617
Delta: 0.004626202189299909 	  Loss: 1.5875049501252465 	 Accuracy: 0.23728813559322035
Delta: 0.0018533443694878468 	  Loss: 1.587167397409431 	 Accuracy: 0.23859191655801826
Delta: 0.0038458502069700076 	  Loss: 1.5872422647371887 	 Accuracy: 0.23859191655801826
Delta: 0.002504584853933238 	  Loss: 1.5869039375335539 	 Accuracy: 0.23598435462842243
Delta: 0.002510022720947341 	  Loss: 1.586932449499701 	 Accuracy: 0.23728813559322035
Delta: 0.0030657996749344856 	  Loss: 1.5866839583660697 	 Accuracy: 0.23598435462842243
Delta: 0.003918164275738781 	  Loss: 1.5864157690126452 	 Accuracy: 0.23598435462842243
Delta: 0.001810674066007018 	  Loss: 1.5866833156730586 	 Accuracy: 0.23598435462842243
Delta: 0.001050014726686448 	  Loss: 1.5863043938745993 	 Accuracy: 0.23598435462842243
Delta: 4.211497136672205e-05 	  Loss: 1.5863163445545072 	 Accuracy: 0.23468057366362452
Delta: 0.003804496079286981 	  Loss: 1.5865603936905663 	 Accuracy: 0.23468057366362452
Delta: 0.0010512762460281554 	  Loss: 1.586966339137859 	 Accuracy: 0.23468057366362452
Delta: 0.0028450766842778863 	  Loss: 1.5865199928719749 	 Accuracy: 0.2333767926988266
Delta: 7.023156805914969e-05 	  Loss: 1.5866762238011274 	 Accuracy: 0.23598435462842243
Delta: 5.9239450806842194e-05 	  Loss: 1.586340881204761 	 Accuracy: 0.23468057366362452
Delta: 0.0008907035436041737 	  Loss: 1.5866179012384198 	 Accuracy: 0.23598435462842243
Delta: 0.001211497427610564 	  Loss: 1.5866577083715032 	 Accuracy: 0.23598435462842243
Delta: 2.8820506002920725e-05 	  Loss: 1.5866153627976047 	 Accuracy: 0.23598435462842243
Delta: 0.0024453351556509633 	  Loss: 1.5862949286549468 	 Accuracy: 0.23598435462842243
Delta: 0.0005105478776647872 	  Loss: 1.5863420743691437 	 Accuracy: 0.23598435462842243
Delta: 0.0012671059078139331 	  Loss: 1.5863274915864158 	 Accuracy: 0.23728813559322035
Delta: 0.0028213677065644545 	  Loss: 1.5865077357611086 	 Accuracy: 0.23728813559322035
Delta: 2.3330634150430696e-05 	  Loss: 1.5864971779453814 	 Accuracy: 0.23728813559322035
Delta: 6.576602960304633e-05 	  Loss: 1.586480227965535 	 Accuracy: 0.23859191655801826
Delta: 0.0005587111783563714 	  Loss: 1.5864252109025854 	 Accuracy: 0.23728813559322035
Delta: 4.5390646090501464e-05 	  Loss: 1.5865158456661193 	 Accuracy: 0.23728813559322035
Delta: 0.0005841453372767577 	  Loss: 1.586345189751103 	 Accuracy: 0.23728813559322035
Delta: 0.0011706725395089282 	  Loss: 1.586579496699692 	 Accuracy: 0.23728813559322035
Delta: 6.170170994865805e-05 	  Loss: 1.5865060441804282 	 Accuracy: 0.23728813559322035
Delta: 8.443076112474212e-05 	  Loss: 1.5866034385729253 	 Accuracy: 0.23728813559322035
Delta: 6.762465232521204e-05 	  Loss: 1.5863773607125087 	 Accuracy: 0.23728813559322035
Delta: 0.0019747863745239003 	  Loss: 1.5867143438333655 	 Accuracy: 0.23598435462842243
Delta: 8.703490080970695e-05 	  Loss: 1.5866524077996973 	 Accuracy: 0.23728813559322035
Delta: 0.0006648174928324119 	  Loss: 1.5864558384416891 	 Accuracy: 0.23728813559322035
Delta: 0.0009009710319116306 	  Loss: 1.5867775912794873 	 Accuracy: 0.23728813559322035
Delta: 9.568619556167446e-05 	  Loss: 1.5866044104654606 	 Accuracy: 0.23859191655801826
Delta: 0.00279489545523928 	  Loss: 1.586134595895512 	 Accuracy: 0.2333767926988266
Delta: 0.0021463520732674978 	  Loss: 1.586391459741845 	 Accuracy: 0.23728813559322035
Delta: 0.0029328121807000607 	  Loss: 1.5868468934246873 	 Accuracy: 0.23728813559322035
Delta: 0.0006320722964082856 	  Loss: 1.5869316373666587 	 Accuracy: 0.23728813559322035
Delta: 0.0015420867189355515 	  Loss: 1.5869615357066555 	 Accuracy: 0.23728813559322035
Delta: 0.0020948319144346032 	  Loss: 1.5861442982845473 	 Accuracy: 0.23728813559322035
Delta: 0.002724302290360793 	  Loss: 1.5864189406321787 	 Accuracy: 0.23728813559322035
Delta: 0.0013940428266982499 	  Loss: 1.5867671098146414 	 Accuracy: 0.23728813559322035
Delta: 0.002132598303758973 	  Loss: 1.5875621188344848 	 Accuracy: 0.23728813559322035
Delta: 0.0022286452814781537 	  Loss: 1.58758066570729 	 Accuracy: 0.23728813559322035
Delta: 0.002717893636541807 	  Loss: 1.5875570395427858 	 Accuracy: 0.23728813559322035
Delta: 0.002214797875998642 	  Loss: 1.5875374615107514 	 Accuracy: 0.23728813559322035
Delta: 7.715370853037347e-06 	  Loss: 1.5875243942360542 	 Accuracy: 0.23728813559322035
Delta: 0.0010028015706248035 	  Loss: 1.5876706240789944 	 Accuracy: 0.23728813559322035
Delta: 0.001708572698126427 	  Loss: 1.5877781565713431 	 Accuracy: 0.23728813559322035
Delta: 0.0015251609616558917 	  Loss: 1.5875578416405134 	 Accuracy: 0.23859191655801826
Delta: 0.00191736286552229 	  Loss: 1.5868859601823435 	 Accuracy: 0.23728813559322035
Delta: 0.000851274942954687 	  Loss: 1.586545952688843 	 Accuracy: 0.23728813559322035
Delta: 0.0007477577427069282 	  Loss: 1.5867341103829593 	 Accuracy: 0.23728813559322035
Delta: 0.0015550012829751159 	  Loss: 1.5867379172465 	 Accuracy: 0.23728813559322035
Delta: 4.3731328180216454e-05 	  Loss: 1.5865113649892297 	 Accuracy: 0.23728813559322035
Delta: 1.8036532754524674e-05 	  Loss: 1.5865431149977538 	 Accuracy: 0.23728813559322035
Delta: 4.196713649444903e-05 	  Loss: 1.5866324252501647 	 Accuracy: 0.23468057366362452
Delta: 0.004850938184441896 	  Loss: 1.5878399854037148 	 Accuracy: 0.23728813559322035
Delta: 0.001919398482451397 	  Loss: 1.5879879557820173 	 Accuracy: 0.23728813559322035
Delta: 0.0015014136402463692 	  Loss: 1.587780925436292 	 Accuracy: 0.23598435462842243
Delta: 0.0009678933087896342 	  Loss: 1.587823879369136 	 Accuracy: 0.23728813559322035
Delta: 0.0021942973606957333 	  Loss: 1.587692923940989 	 Accuracy: 0.23728813559322035
Delta: 0.0001277224741698661 	  Loss: 1.5879769184351535 	 Accuracy: 0.23728813559322035
Delta: 6.085830251899113e-05 	  Loss: 1.5880108498183425 	 Accuracy: 0.23728813559322035
Delta: 0.0005414413719306284 	  Loss: 1.5880587221011355 	 Accuracy: 0.23728813559322035
Delta: 0.0010228776795672238 	  Loss: 1.5880453225596765 	 Accuracy: 0.23859191655801826
Delta: 0.005400563262522686 	  Loss: 1.58864163237706 	 Accuracy: 0.23468057366362452
Delta: 0.0026772352649092074 	  Loss: 1.5883522498951779 	 Accuracy: 0.23728813559322035
Delta: 0.0005853961941380103 	  Loss: 1.5886265660463579 	 Accuracy: 0.23859191655801826
Delta: 0.0026849231687462445 	  Loss: 1.5885632470719087 	 Accuracy: 0.23728813559322035
Delta: 0.003329334859936946 	  Loss: 1.5884698971558031 	 Accuracy: 0.23728813559322035
Delta: 0.0011696898148119068 	  Loss: 1.5884659019981635 	 Accuracy: 0.23728813559322035
Delta: 0.0037787146156077972 	  Loss: 1.5888001175639421 	 Accuracy: 0.23468057366362452
Delta: 0.020868618072390616 	  Loss: 2.159019924339864 	 Accuracy: 0.2255541069100391
Delta: 0.018699571979633817 	  Loss: 2.0573648996298104 	 Accuracy: 0.20860495436766624
Delta: 0.017557302597475212 	  Loss: 1.8672987653117479 	 Accuracy: 0.288135593220339
Delta: 0.01654177751859059 	  Loss: 1.7199553700836074 	 Accuracy: 0.31029986962190353
Delta: 0.014535131944260373 	  Loss: 1.6456041416202567 	 Accuracy: 0.30247718383311606
Delta: 0.011759524943282463 	  Loss: 1.6143113829262896 	 Accuracy: 0.30378096479791394
Delta: 0.008743084422811895 	  Loss: 1.6048568376872159 	 Accuracy: 0.30378096479791394

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006552894743417025 	  Loss: 1.6027327608177846 	 Accuracy: 0.3011734028683181
Delta: 0.005750250187014537 	  Loss: 1.6016098445189633 	 Accuracy: 0.3011734028683181
Delta: 0.0026400341821450745 	  Loss: 1.6013313800197162 	 Accuracy: 0.30247718383311606
Delta: 0.0031534491255700205 	  Loss: 1.6013590409584684 	 Accuracy: 0.30378096479791394
Delta: 0.003194713796852396 	  Loss: 1.6005911366131071 	 Accuracy: 0.30378096479791394
Delta: 0.002607605627833526 	  Loss: 1.6007039582137637 	 Accuracy: 0.30378096479791394
Delta: 0.003461667197023575 	  Loss: 1.6006877646244788 	 Accuracy: 0.30378096479791394
Delta: 0.0024240783492675373 	  Loss: 1.600670679938867 	 Accuracy: 0.30378096479791394
Delta: 0.0006309113552051724 	  Loss: 1.60058929882606 	 Accuracy: 0.30247718383311606
Delta: 0.002088385266253876 	  Loss: 1.6008132737217746 	 Accuracy: 0.3011734028683181
Delta: 0.0032909880162841033 	  Loss: 1.600712252172069 	 Accuracy: 0.30247718383311606
Delta: 0.002023368225577631 	  Loss: 1.6007483892760141 	 Accuracy: 0.30247718383311606
Delta: 0.004572326917138679 	  Loss: 1.601481075330788 	 Accuracy: 0.3011734028683181
Delta: 0.0006584479878288716 	  Loss: 1.6017082832755178 	 Accuracy: 0.30247718383311606
Delta: 6.30493070519768e-05 	  Loss: 1.601620859355053 	 Accuracy: 0.30247718383311606
Delta: 0.002256082007026512 	  Loss: 1.601210392459064 	 Accuracy: 0.30247718383311606
Delta: 3.559939810666284e-05 	  Loss: 1.6010805362320306 	 Accuracy: 0.30247718383311606
Delta: 0.002253517118082358 	  Loss: 1.6007273618995583 	 Accuracy: 0.30378096479791394
Delta: 0.0026640395296596434 	  Loss: 1.6005174385167993 	 Accuracy: 0.30378096479791394
Delta: 0.002194496150670886 	  Loss: 1.6005352501638546 	 Accuracy: 0.3050847457627119
Delta: 0.0018266745513330258 	  Loss: 1.6002392834626742 	 Accuracy: 0.30378096479791394
Delta: 0.002687029091305489 	  Loss: 1.600561696427591 	 Accuracy: 0.30247718383311606
Delta: 0.0007011405555792542 	  Loss: 1.60046570138044 	 Accuracy: 0.30378096479791394
Delta: 0.0006613177729106448 	  Loss: 1.6002373703284032 	 Accuracy: 0.30378096479791394
Delta: 2.8238749519099444e-05 	  Loss: 1.6002676092165913 	 Accuracy: 0.30247718383311606
Delta: 0.0008788909219038233 	  Loss: 1.600503843665877 	 Accuracy: 0.30378096479791394
Delta: 0.0007103666077991283 	  Loss: 1.600231048301846 	 Accuracy: 0.30378096479791394
Delta: 3.781599365960549e-05 	  Loss: 1.60021296737041 	 Accuracy: 0.30378096479791394
Delta: 0.0016330647623898152 	  Loss: 1.600546845947641 	 Accuracy: 0.30247718383311606
Delta: 0.0038419552704250337 	  Loss: 1.6008633771234078 	 Accuracy: 0.30378096479791394
Delta: 0.003841743376574545 	  Loss: 1.6014820821772422 	 Accuracy: 0.30247718383311606
Delta: 0.002030724400632704 	  Loss: 1.601348587213792 	 Accuracy: 0.30247718383311606
Delta: 0.002345096113421272 	  Loss: 1.6009908001602424 	 Accuracy: 0.30378096479791394
Delta: 0.002004512219294859 	  Loss: 1.6009384662360597 	 Accuracy: 0.30247718383311606
Delta: 0.0015387352919872795 	  Loss: 1.6010634522894422 	 Accuracy: 0.30247718383311606
Delta: 0.0010795217614716485 	  Loss: 1.6010452477502506 	 Accuracy: 0.30247718383311606
Delta: 3.09933241817113e-05 	  Loss: 1.600983390180727 	 Accuracy: 0.30247718383311606
Delta: 0.0007448677440545255 	  Loss: 1.6012318491403519 	 Accuracy: 0.30247718383311606
Delta: 5.634804526167536e-05 	  Loss: 1.6010286270623415 	 Accuracy: 0.30247718383311606
Delta: 0.0022391470694277356 	  Loss: 1.6014073104117543 	 Accuracy: 0.3011734028683181
Delta: 0.0037562062368991355 	  Loss: 1.601545082057241 	 Accuracy: 0.3011734028683181
Delta: 3.522404809345625e-05 	  Loss: 1.601542444158023 	 Accuracy: 0.3011734028683181
Delta: 0.002243449714701146 	  Loss: 1.6011240042122687 	 Accuracy: 0.3011734028683181
Delta: 5.408432140887407e-05 	  Loss: 1.6012529274894836 	 Accuracy: 0.29986962190352023
Delta: 0.0013339728778641931 	  Loss: 1.6017345403687107 	 Accuracy: 0.3011734028683181
Delta: 0.00342828518374634 	  Loss: 1.6022804438858005 	 Accuracy: 0.2985658409387223
Delta: 0.002004084637629714 	  Loss: 1.602245402794233 	 Accuracy: 0.3011734028683181
Delta: 0.002612459468142936 	  Loss: 1.6027510695893294 	 Accuracy: 0.29726205997392435
Delta: 0.0025532791372320763 	  Loss: 1.6035315335974207 	 Accuracy: 0.29335071707953064
Delta: 0.003166341894450751 	  Loss: 1.603828659810355 	 Accuracy: 0.29986962190352023
Delta: 0.004897930017529933 	  Loss: 1.6044737112960252 	 Accuracy: 0.29986962190352023
Delta: 0.0007489298174885066 	  Loss: 1.6043927203325832 	 Accuracy: 0.29986962190352023
Delta: 0.0025699962803587824 	  Loss: 1.6041807911630577 	 Accuracy: 0.29986962190352023
Delta: 0.0042284220079001076 	  Loss: 1.6036442614485211 	 Accuracy: 0.3011734028683181
Delta: 0.0019064449769751908 	  Loss: 1.603673972894709 	 Accuracy: 0.2985658409387223
Delta: 0.0035425989941027893 	  Loss: 1.6048021672086237 	 Accuracy: 0.2985658409387223
Delta: 0.003831246925083169 	  Loss: 1.6040319468164932 	 Accuracy: 0.29726205997392435
Delta: 0.0022506388685105015 	  Loss: 1.6040267839379674 	 Accuracy: 0.29726205997392435
Delta: 0.00327973214726111 	  Loss: 1.6039795404813086 	 Accuracy: 0.2985658409387223
Delta: 0.0016241980653836285 	  Loss: 1.604057086444755 	 Accuracy: 0.2985658409387223
Delta: 1.917861742015959e-05 	  Loss: 1.6040182161750831 	 Accuracy: 0.29726205997392435
Delta: 0.00336968288240213 	  Loss: 1.6047305290093103 	 Accuracy: 0.3011734028683181
Delta: 0.003582702440799966 	  Loss: 1.6046089990576538 	 Accuracy: 0.2985658409387223
Delta: 0.0027750823286424395 	  Loss: 1.6049266682940337 	 Accuracy: 0.2985658409387223
Delta: 0.0013584566083440102 	  Loss: 1.604851283772165 	 Accuracy: 0.2985658409387223
Delta: 0.0017154925470760302 	  Loss: 1.6045226092492815 	 Accuracy: 0.29986962190352023
Delta: 0.004918177638770872 	  Loss: 1.6041998089687113 	 Accuracy: 0.29986962190352023
Delta: 0.005284495798518077 	  Loss: 1.6013153710548917 	 Accuracy: 0.30247718383311606
Delta: 0.004050282789638023 	  Loss: 1.6011800248820616 	 Accuracy: 0.30247718383311606
Delta: 0.0016354033347957839 	  Loss: 1.600925278177366 	 Accuracy: 0.30247718383311606
Delta: 0.0005282755567514264 	  Loss: 1.600938489010308 	 Accuracy: 0.30247718383311606
Delta: 0.0005257278854937437 	  Loss: 1.6008945723424555 	 Accuracy: 0.30247718383311606
Delta: 2.75635773986646e-05 	  Loss: 1.6009224810405254 	 Accuracy: 0.29986962190352023
Delta: 0.002276649765880723 	  Loss: 1.600884541516765 	 Accuracy: 0.30247718383311606
Delta: 0.0013125965699056213 	  Loss: 1.6009058553907862 	 Accuracy: 0.30247718383311606
Delta: 0.0007978716656055284 	  Loss: 1.6009033668018056 	 Accuracy: 0.30247718383311606
Delta: 1.4564813062741852e-05 	  Loss: 1.600902485854786 	 Accuracy: 0.30247718383311606
Delta: 0.003998402768782211 	  Loss: 1.6017507215702447 	 Accuracy: 0.30378096479791394
Delta: 0.002961200369684611 	  Loss: 1.6009387150718997 	 Accuracy: 0.30247718383311606
Delta: 7.952613044324419e-05 	  Loss: 1.6011994647763883 	 Accuracy: 0.30378096479791394
Delta: 7.562616255361983e-05 	  Loss: 1.6008982976294224 	 Accuracy: 0.30247718383311606
Delta: 3.306486921360261e-05 	  Loss: 1.6009125632999233 	 Accuracy: 0.30247718383311606
Delta: 9.18512713954261e-08 	  Loss: 1.6009127355511108 	 Accuracy: 0.30247718383311606
Delta: 0.0014996042101271439 	  Loss: 1.599886916435985 	 Accuracy: 0.30378096479791394
Delta: 0.0037447771115260643 	  Loss: 1.600113413045587 	 Accuracy: 0.3050847457627119
Delta: 0.004621854493037688 	  Loss: 1.5999497053369063 	 Accuracy: 0.30378096479791394
Delta: 0.0037101769652937984 	  Loss: 1.5996552640666428 	 Accuracy: 0.30378096479791394
Delta: 0.0038441023689611874 	  Loss: 1.599924438440029 	 Accuracy: 0.3050847457627119
Delta: 0.003142399568777353 	  Loss: 1.5995743667281923 	 Accuracy: 0.3050847457627119
Delta: 0.0005315990436416012 	  Loss: 1.5998169185794153 	 Accuracy: 0.30638852672750977
Delta: 0.0023143761163726823 	  Loss: 1.6003121061712897 	 Accuracy: 0.3050847457627119
Delta: 0.005541614175352409 	  Loss: 1.600777231014408 	 Accuracy: 0.3011734028683181
Delta: 0.005016009583668532 	  Loss: 1.6013369249036666 	 Accuracy: 0.30378096479791394
Delta: 0.02107968203763265 	  Loss: 2.1585365482401784 	 Accuracy: 0.1577574967405476
Delta: 0.01890476088427816 	  Loss: 2.045360368354946 	 Accuracy: 0.1681877444589309
Delta: 0.017941889349090513 	  Loss: 1.840526910878625 	 Accuracy: 0.22816166883963493
Delta: 0.01616229088175991 	  Loss: 1.6745302889740112 	 Accuracy: 0.242503259452412
Delta: 0.011775608321963995 	  Loss: 1.6188339461784653 	 Accuracy: 0.2438070404172099
Delta: 0.008665841915821346 	  Loss: 1.6086503581182048 	 Accuracy: 0.2438070404172099

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006257527439686397 	  Loss: 1.607457923066328 	 Accuracy: 0.24771838331160365
Delta: 0.005584877689168967 	  Loss: 1.6075519605804838 	 Accuracy: 0.24511082138200782
Delta: 0.003957570120788212 	  Loss: 1.6077820855047338 	 Accuracy: 0.24641460234680573
Delta: 0.002215800300131608 	  Loss: 1.6077026280738043 	 Accuracy: 0.24641460234680573
Delta: 0.0020775453501048285 	  Loss: 1.608057145507193 	 Accuracy: 0.24641460234680573
Delta: 0.002449271083789003 	  Loss: 1.6081645126054522 	 Accuracy: 0.24641460234680573
Delta: 0.0014584554206614417 	  Loss: 1.6080331765019955 	 Accuracy: 0.24902216427640156
Delta: 0.0027184360767650946 	  Loss: 1.6080630634802455 	 Accuracy: 0.24641460234680573
Delta: 0.00277158611475018 	  Loss: 1.6080438825423142 	 Accuracy: 0.24641460234680573
Delta: 0.003185153172119719 	  Loss: 1.6084732406241646 	 Accuracy: 0.24641460234680573
Delta: 0.0017662212677337493 	  Loss: 1.608075386760782 	 Accuracy: 0.24641460234680573
Delta: 0.001618967789581606 	  Loss: 1.6083242155940316 	 Accuracy: 0.24511082138200782
Delta: 0.0031174464615520868 	  Loss: 1.6084011992340705 	 Accuracy: 0.24641460234680573
Delta: 0.001537515822870593 	  Loss: 1.6083557162048843 	 Accuracy: 0.24119947848761408
Delta: 5.396943394700314e-05 	  Loss: 1.6083673601743433 	 Accuracy: 0.24511082138200782
Delta: 0.0014913153846218778 	  Loss: 1.6085363311670369 	 Accuracy: 0.24511082138200782
Delta: 0.000933588095568604 	  Loss: 1.6086570272635363 	 Accuracy: 0.2438070404172099
Delta: 0.00010058491389462108 	  Loss: 1.6080471725479486 	 Accuracy: 0.24641460234680573
Delta: 0.003282108848627498 	  Loss: 1.6077585862301353 	 Accuracy: 0.24771838331160365
Delta: 0.000864674021072898 	  Loss: 1.6078114353302984 	 Accuracy: 0.24771838331160365
Delta: 0.002154590248201904 	  Loss: 1.6081306138344225 	 Accuracy: 0.24641460234680573
Delta: 0.0033734969001755133 	  Loss: 1.6083148604608684 	 Accuracy: 0.24771838331160365
Delta: 0.0015123285863600463 	  Loss: 1.6081028714027248 	 Accuracy: 0.24902216427640156
Delta: 0.0014970649256069695 	  Loss: 1.6080873745603945 	 Accuracy: 0.24771838331160365
Delta: 0.000983738582176688 	  Loss: 1.6081981465619308 	 Accuracy: 0.24771838331160365
Delta: 0.003438580343994935 	  Loss: 1.6084199860730062 	 Accuracy: 0.24771838331160365
Delta: 0.0014232716468094509 	  Loss: 1.6081616048193446 	 Accuracy: 0.24771838331160365
Delta: 4.9902446502554376e-05 	  Loss: 1.6082015636480804 	 Accuracy: 0.24771838331160365
Delta: 1.8526908533168716e-05 	  Loss: 1.608114250273227 	 Accuracy: 0.24771838331160365
Delta: 0.0016103098033561753 	  Loss: 1.6081042070043798 	 Accuracy: 0.2542372881355932
Delta: 3.173454374990681e-05 	  Loss: 1.6080636649863014 	 Accuracy: 0.24771838331160365
Delta: 0.001465415597888017 	  Loss: 1.6083175318452092 	 Accuracy: 0.24771838331160365
Delta: 0.001073737945194752 	  Loss: 1.6080208478821314 	 Accuracy: 0.24771838331160365
Delta: 2.720710805983451e-05 	  Loss: 1.6080742381875326 	 Accuracy: 0.24771838331160365
Delta: 2.8602659353709155e-05 	  Loss: 1.6081318139092815 	 Accuracy: 0.24641460234680573
Delta: 0.0021200499623263117 	  Loss: 1.608234914386795 	 Accuracy: 0.24641460234680573
Delta: 8.810030142142203e-05 	  Loss: 1.6082982063931999 	 Accuracy: 0.24641460234680573
Delta: 0.0016613623718667783 	  Loss: 1.6082705110040059 	 Accuracy: 0.24771838331160365
Delta: 5.84788522673235e-05 	  Loss: 1.6080800466528413 	 Accuracy: 0.24641460234680573
Delta: 2.8677702746550893e-05 	  Loss: 1.608151219204616 	 Accuracy: 0.24771838331160365
Delta: 2.7809149071850422e-05 	  Loss: 1.608057139824262 	 Accuracy: 0.24771838331160365
Delta: 0.0012842487636397257 	  Loss: 1.6080561157964137 	 Accuracy: 0.23598435462842243
Delta: 0.0006456586306711797 	  Loss: 1.608102807024716 	 Accuracy: 0.24771838331160365
Delta: 7.525267373458638e-05 	  Loss: 1.608141765028749 	 Accuracy: 0.24771838331160365
Delta: 7.026048480447964e-05 	  Loss: 1.6080679625661216 	 Accuracy: 0.24771838331160365
Delta: 3.786065870098425e-06 	  Loss: 1.608065590888671 	 Accuracy: 0.24771838331160365
Delta: 5.884082547263993e-06 	  Loss: 1.6080672178771098 	 Accuracy: 0.24771838331160365
Delta: 0.001541317726296328 	  Loss: 1.6083537154915208 	 Accuracy: 0.24771838331160365
Delta: 0.0021941944229771316 	  Loss: 1.6095612397438654 	 Accuracy: 0.24771838331160365
Delta: 0.0029712399005558535 	  Loss: 1.6100563997423836 	 Accuracy: 0.2529335071707953
Delta: 0.003161546225305729 	  Loss: 1.6114565416193534 	 Accuracy: 0.24902216427640156
Delta: 7.185273358457662e-05 	  Loss: 1.6110979956833995 	 Accuracy: 0.24902216427640156
Delta: 0.0017648828634846134 	  Loss: 1.6111169401028076 	 Accuracy: 0.2503259452411995
Delta: 0.00281670927507565 	  Loss: 1.6109702216301565 	 Accuracy: 0.24902216427640156
Delta: 0.0030970389516102588 	  Loss: 1.6103718888471468 	 Accuracy: 0.24902216427640156
Delta: 0.0035031887476156187 	  Loss: 1.6101826875112568 	 Accuracy: 0.24771838331160365
Delta: 0.004806017212447968 	  Loss: 1.6069081888682712 	 Accuracy: 0.2503259452411995
Delta: 0.004166729844144059 	  Loss: 1.6068162958035943 	 Accuracy: 0.24902216427640156
Delta: 0.0047138438314240985 	  Loss: 1.6077801363215622 	 Accuracy: 0.24641460234680573
Delta: 0.0020425616309580922 	  Loss: 1.6077812994254645 	 Accuracy: 0.2503259452411995
Delta: 0.0013415303732791533 	  Loss: 1.607775109838026 	 Accuracy: 0.2516297262059974
Delta: 0.002039589008273884 	  Loss: 1.6076910775986455 	 Accuracy: 0.24641460234680573
Delta: 0.003711666911040441 	  Loss: 1.608356804509713 	 Accuracy: 0.24771838331160365
Delta: 0.004644463613871598 	  Loss: 1.6077909291549117 	 Accuracy: 0.24771838331160365
Delta: 0.003333707177527202 	  Loss: 1.607862302947489 	 Accuracy: 0.24641460234680573
Delta: 0.004420385520376182 	  Loss: 1.6075459794193898 	 Accuracy: 0.24511082138200782
Delta: 0.005031713451177887 	  Loss: 1.6080885646058178 	 Accuracy: 0.2438070404172099
Delta: 0.0005115593939819022 	  Loss: 1.6080746253824714 	 Accuracy: 0.24641460234680573
Delta: 0.003909717908827468 	  Loss: 1.6078336227023038 	 Accuracy: 0.24771838331160365
Delta: 0.0006246342874232394 	  Loss: 1.6077374020906938 	 Accuracy: 0.24641460234680573
Delta: 0.0006272395064419359 	  Loss: 1.6078296865254864 	 Accuracy: 0.24511082138200782
Delta: 0.0032646394088086546 	  Loss: 1.6084144675286893 	 Accuracy: 0.24641460234680573
Delta: 0.0011465653705307638 	  Loss: 1.6082033463005074 	 Accuracy: 0.2438070404172099
Delta: 0.004118228393482697 	  Loss: 1.6081308050917278 	 Accuracy: 0.24119947848761408
Delta: 0.0035053166036200264 	  Loss: 1.6079327509796761 	 Accuracy: 0.24641460234680573
Delta: 0.0021685647313153594 	  Loss: 1.6077374092747627 	 Accuracy: 0.24641460234680573
Delta: 0.0021421258929353246 	  Loss: 1.6079751652356333 	 Accuracy: 0.24641460234680573
Delta: 0.003929462238702463 	  Loss: 1.608514619598119 	 Accuracy: 0.24641460234680573
Delta: 0.003973028514699912 	  Loss: 1.607639976258458 	 Accuracy: 0.24641460234680573
Delta: 0.0021027985976172932 	  Loss: 1.6079943077131225 	 Accuracy: 0.24511082138200782
Delta: 0.0035086328639074666 	  Loss: 1.607486304576024 	 Accuracy: 0.2438070404172099
Delta: 0.0021810097961980244 	  Loss: 1.6072757964682203 	 Accuracy: 0.24641460234680573
Delta: 0.0010753990905952025 	  Loss: 1.6072397255632969 	 Accuracy: 0.24641460234680573
Delta: 4.419340961520052e-06 	  Loss: 1.607239654945368 	 Accuracy: 0.24511082138200782
converged at iter  89
Delta: 0.020908522259331767 	  Loss: 2.1588293886684014 	 Accuracy: 0.21903520208604954
Delta: 0.018849328268149584 	  Loss: 2.0539934038095202 	 Accuracy: 0.2138200782268579
Delta: 0.017935195957195997 	  Loss: 1.8587003128260957 	 Accuracy: 0.23076923076923078
Delta: 0.016134115474856985 	  Loss: 1.7119469704012427 	 Accuracy: 0.258148631029987
Delta: 0.013274660022234258 	  Loss: 1.6574269214087023 	 Accuracy: 0.27249022164276404
Delta: 0.009595166844475322 	  Loss: 1.64549367018641 	 Accuracy: 0.2711864406779661

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007632520165230682 	  Loss: 1.6430866889989413 	 Accuracy: 0.2685788787483703
Delta: 0.005828423716420648 	  Loss: 1.6427987178259944 	 Accuracy: 0.2620599739243807
Delta: 0.00560352361221115 	  Loss: 1.6428067766955885 	 Accuracy: 0.26727509778357234
Delta: 0.004800606219405603 	  Loss: 1.6429731252155286 	 Accuracy: 0.26727509778357234
Delta: 0.0029040894865561473 	  Loss: 1.6431114553262751 	 Accuracy: 0.2685788787483703
Delta: 0.0023020860916605746 	  Loss: 1.6430557148702842 	 Accuracy: 0.26727509778357234
Delta: 0.0005099000917934002 	  Loss: 1.6430759429258441 	 Accuracy: 0.2685788787483703
Delta: 3.2135405528809836e-05 	  Loss: 1.643084439018566 	 Accuracy: 0.26727509778357234
Delta: 4.2790660592957094e-05 	  Loss: 1.6431711784974696 	 Accuracy: 0.26727509778357234
Delta: 6.052102061937057e-05 	  Loss: 1.6430909500704765 	 Accuracy: 0.26988265971316816
Delta: 0.002199045021969613 	  Loss: 1.6429916440927532 	 Accuracy: 0.26727509778357234
Delta: 4.042647537043542e-05 	  Loss: 1.6429230796248149 	 Accuracy: 0.26727509778357234
Delta: 0.0009004878221501387 	  Loss: 1.6429986470371407 	 Accuracy: 0.2685788787483703
Delta: 0.0005753510045715868 	  Loss: 1.6429744881900223 	 Accuracy: 0.2685788787483703
Delta: 0.0009223132003534233 	  Loss: 1.6431625039577855 	 Accuracy: 0.2516297262059974
Delta: 6.266896877576877e-05 	  Loss: 1.643049367700971 	 Accuracy: 0.26988265971316816
Delta: 5.4133668142723295e-05 	  Loss: 1.6430302014161087 	 Accuracy: 0.26727509778357234
Delta: 7.583120851350545e-05 	  Loss: 1.643041869988 	 Accuracy: 0.26727509778357234
Delta: 0.0013279893058296042 	  Loss: 1.6429078558469814 	 Accuracy: 0.2646675358539765
Delta: 0.002723767754678615 	  Loss: 1.6429784694077538 	 Accuracy: 0.26727509778357234
Delta: 0.0026243535802508763 	  Loss: 1.6430742788372878 	 Accuracy: 0.26727509778357234
Delta: 0.001230281851152433 	  Loss: 1.6429377817502189 	 Accuracy: 0.26727509778357234
Delta: 0.0007846897018968928 	  Loss: 1.6431203222132011 	 Accuracy: 0.26727509778357234
Delta: 7.792195426790068e-05 	  Loss: 1.6430136430914226 	 Accuracy: 0.26727509778357234
Delta: 5.133003683437818e-05 	  Loss: 1.6431065038453128 	 Accuracy: 0.23728813559322035
Delta: 0.003990080649887774 	  Loss: 1.6430867836028997 	 Accuracy: 0.26727509778357234
Delta: 0.0024464793294657855 	  Loss: 1.642957506301956 	 Accuracy: 0.26727509778357234
Delta: 0.0028887650316570565 	  Loss: 1.6431900339302705 	 Accuracy: 0.26727509778357234
Delta: 0.0016486452065084568 	  Loss: 1.6430167193786969 	 Accuracy: 0.26727509778357234
Delta: 0.0006903253699622416 	  Loss: 1.6431553920531186 	 Accuracy: 0.2607561929595828
Delta: 6.767162278399832e-05 	  Loss: 1.643175750475049 	 Accuracy: 0.26727509778357234
Delta: 0.0025784271580364584 	  Loss: 1.6426112990369555 	 Accuracy: 0.26727509778357234
Delta: 0.0032424875216874385 	  Loss: 1.6423279015393761 	 Accuracy: 0.26727509778357234
Delta: 0.0030834899733992653 	  Loss: 1.6423057029698116 	 Accuracy: 0.26727509778357234
Delta: 0.0022908457254871505 	  Loss: 1.6424570523632416 	 Accuracy: 0.26727509778357234
Delta: 0.0006645047980678906 	  Loss: 1.6421253374461464 	 Accuracy: 0.26727509778357234
Delta: 0.0016580893229083873 	  Loss: 1.642266122685788 	 Accuracy: 0.26597131681877445
Delta: 0.0011017219011885172 	  Loss: 1.6422258657471382 	 Accuracy: 0.26727509778357234
Delta: 0.0008947032397537727 	  Loss: 1.6424172325203648 	 Accuracy: 0.26727509778357234
Delta: 0.003908330275800549 	  Loss: 1.6427456810380823 	 Accuracy: 0.2685788787483703
Delta: 0.002329138701960364 	  Loss: 1.6426148031027306 	 Accuracy: 0.2685788787483703
Delta: 0.0041680923412389615 	  Loss: 1.6424381148198754 	 Accuracy: 0.26727509778357234
Delta: 0.002498965542806305 	  Loss: 1.642675705803558 	 Accuracy: 0.2685788787483703
Delta: 0.0032633978627493562 	  Loss: 1.6428253588204085 	 Accuracy: 0.2685788787483703
Delta: 0.004085464721809687 	  Loss: 1.6430013410951694 	 Accuracy: 0.2685788787483703
Delta: 0.0014774689453042457 	  Loss: 1.6428320603654933 	 Accuracy: 0.2685788787483703
Delta: 0.005050027235677526 	  Loss: 1.6434979808870258 	 Accuracy: 0.25945241199478486
Delta: 0.004806374971149736 	  Loss: 1.6434172689247168 	 Accuracy: 0.23989569752281617
Delta: 0.0033793759929031325 	  Loss: 1.6430422709384158 	 Accuracy: 0.2685788787483703
Delta: 0.0017760034987030547 	  Loss: 1.6430691614738713 	 Accuracy: 0.26727509778357234
Delta: 0.0019460046183011601 	  Loss: 1.643241960474401 	 Accuracy: 0.2685788787483703
Delta: 0.00439283662954969 	  Loss: 1.6424892490204022 	 Accuracy: 0.2646675358539765
Delta: 0.005334024198893572 	  Loss: 1.6428429791873782 	 Accuracy: 0.2607561929595828
Delta: 0.005136160122783053 	  Loss: 1.6427419155459064 	 Accuracy: 0.2646675358539765
Delta: 0.003571658061597563 	  Loss: 1.6425421744204107 	 Accuracy: 0.2646675358539765
Delta: 0.0030795549182623893 	  Loss: 1.6434815811678045 	 Accuracy: 0.2646675358539765
Delta: 0.0017878209916667412 	  Loss: 1.643729777665397 	 Accuracy: 0.2646675358539765
Delta: 2.3137313572666377e-05 	  Loss: 1.6436648377544132 	 Accuracy: 0.2646675358539765
Delta: 0.0014234032222506887 	  Loss: 1.643443110757318 	 Accuracy: 0.2646675358539765
Delta: 0.0007226625830429028 	  Loss: 1.6428612001752616 	 Accuracy: 0.2646675358539765
Delta: 2.808798531160578e-06 	  Loss: 1.6428645663521881 	 Accuracy: 0.2646675358539765
Delta: 1.583000697804962e-05 	  Loss: 1.642907368105833 	 Accuracy: 0.2646675358539765
Delta: 0.00413205573139751 	  Loss: 1.6423207852258916 	 Accuracy: 0.2646675358539765
Delta: 0.0007111024826004243 	  Loss: 1.6423646810895933 	 Accuracy: 0.26597131681877445
Delta: 0.0016787944067438313 	  Loss: 1.6425493061473369 	 Accuracy: 0.25945241199478486
Delta: 0.0017051134957535182 	  Loss: 1.642465318030247 	 Accuracy: 0.2646675358539765
Delta: 0.0026479712150727923 	  Loss: 1.6420319939819203 	 Accuracy: 0.26727509778357234
Delta: 0.0017006527246449194 	  Loss: 1.6420502544421582 	 Accuracy: 0.2646675358539765
Delta: 3.2775464004376924e-05 	  Loss: 1.6419353555785519 	 Accuracy: 0.2646675358539765
Delta: 3.141541728431259e-05 	  Loss: 1.6420208317137246 	 Accuracy: 0.2646675358539765
Delta: 3.138124654703611e-05 	  Loss: 1.6419404085819713 	 Accuracy: 0.2646675358539765
Delta: 3.538639596473515e-05 	  Loss: 1.6419436907009584 	 Accuracy: 0.2646675358539765
Delta: 3.539131216528899e-05 	  Loss: 1.6419429962244032 	 Accuracy: 0.2646675358539765
Delta: 0.0019796714303390783 	  Loss: 1.6421977193534374 	 Accuracy: 0.2646675358539765
Delta: 5.9842621587558606e-05 	  Loss: 1.6419187116472163 	 Accuracy: 0.2646675358539765
Delta: 1.847510532801779e-05 	  Loss: 1.6419832892078527 	 Accuracy: 0.2646675358539765
Delta: 1.8477608842873446e-05 	  Loss: 1.6419190666892296 	 Accuracy: 0.2646675358539765
Delta: 3.587488039059354e-05 	  Loss: 1.6419774853566544 	 Accuracy: 0.2646675358539765
Delta: 0.001440036347782006 	  Loss: 1.64208817950959 	 Accuracy: 0.2646675358539765
Delta: 0.0005248052009053746 	  Loss: 1.6421553914939313 	 Accuracy: 0.2646675358539765
Delta: 0.0005493716233939685 	  Loss: 1.6418914625829741 	 Accuracy: 0.2633637548891786
Delta: 0.001247739219807681 	  Loss: 1.6421805897204615 	 Accuracy: 0.2646675358539765
Delta: 0.0033087930350043063 	  Loss: 1.6426018979811232 	 Accuracy: 0.2646675358539765
Delta: 0.0012710545935420753 	  Loss: 1.64215153266149 	 Accuracy: 0.2646675358539765
Delta: 4.39726942364849e-07 	  Loss: 1.6421498961856127 	 Accuracy: 0.2646675358539765
Delta: 0.001309468916548205 	  Loss: 1.6419229721212005 	 Accuracy: 0.2646675358539765
Delta: 4.6166239305517574e-06 	  Loss: 1.641909042916064 	 Accuracy: 0.26597131681877445
Delta: 0.0025074703908523144 	  Loss: 1.6416604457058264 	 Accuracy: 0.2646675358539765
Delta: 0.005227121937092694 	  Loss: 1.6429291472846514 	 Accuracy: 0.2633637548891786
Delta: 0.004298903385687884 	  Loss: 1.6420669441395914 	 Accuracy: 0.2646675358539765
Delta: 0.003143680526709353 	  Loss: 1.641674108697754 	 Accuracy: 0.26597131681877445
Delta: 0.004993847077996555 	  Loss: 1.6415574573857077 	 Accuracy: 0.2685788787483703
Delta: 0.004183978975442852 	  Loss: 1.641387901718935 	 Accuracy: 0.26727509778357234
Delta: 0.005157734524168662 	  Loss: 1.6422660440776884 	 Accuracy: 0.26727509778357234
Delta: 0.020820605060881 	  Loss: 2.159154129231067 	 Accuracy: 0.2151238591916558
Delta: 0.019028898883724076 	  Loss: 2.0508564824784665 	 Accuracy: 0.242503259452412
Delta: 0.017688956112847362 	  Loss: 1.8524229765212055 	 Accuracy: 0.3050847457627119
Delta: 0.016278558296639222 	  Loss: 1.7126357531903373 	 Accuracy: 0.30378096479791394
Delta: 0.01271358392550596 	  Loss: 1.6626928679932125 	 Accuracy: 0.28292046936114734
Delta: 0.010723160305379441 	  Loss: 1.6495596077048158 	 Accuracy: 0.2777053455019557

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008406222538518518 	  Loss: 1.6459885298047614 	 Accuracy: 0.27640156453715775
Delta: 0.0063667095413379 	  Loss: 1.6450611613354689 	 Accuracy: 0.2777053455019557
Delta: 0.005301397475676616 	  Loss: 1.6443581445655762 	 Accuracy: 0.27509778357235987
Delta: 0.004615234352077163 	  Loss: 1.6438190756444964 	 Accuracy: 0.27509778357235987
Delta: 0.0022831851120438352 	  Loss: 1.6436808864146142 	 Accuracy: 0.27640156453715775
Delta: 0.0010300200041110958 	  Loss: 1.643546671070827 	 Accuracy: 0.27640156453715775
Delta: 1.4993940361378789e-05 	  Loss: 1.643658689755621 	 Accuracy: 0.27640156453715775
Delta: 0.0020058780199224487 	  Loss: 1.6435957329582394 	 Accuracy: 0.27249022164276404
Delta: 0.0006647962241690468 	  Loss: 1.6435433449664552 	 Accuracy: 0.27509778357235987
Delta: 4.879263064578716e-05 	  Loss: 1.6434194564304447 	 Accuracy: 0.27640156453715775
Delta: 2.3458471163866103e-05 	  Loss: 1.6433586660175936 	 Accuracy: 0.27640156453715775
Delta: 4.441406553180459e-05 	  Loss: 1.6434873171304805 	 Accuracy: 0.27640156453715775
Delta: 4.422030889115956e-05 	  Loss: 1.6433591718849196 	 Accuracy: 0.27640156453715775
Delta: 4.055700197838766e-05 	  Loss: 1.6433535565707862 	 Accuracy: 0.2842242503259452
Delta: 2.217781176746416e-05 	  Loss: 1.6433549431151668 	 Accuracy: 0.2777053455019557
Delta: 2.8376459106593306e-05 	  Loss: 1.6433492519579858 	 Accuracy: 0.27640156453715775
Delta: 0.002033153456783253 	  Loss: 1.6434690940817158 	 Accuracy: 0.27640156453715775
Delta: 0.0010714239859021025 	  Loss: 1.6433839105467647 	 Accuracy: 0.27509778357235987
Delta: 0.0031944344045689724 	  Loss: 1.6436827086748744 	 Accuracy: 0.2816166883963494
Delta: 0.00354020502521308 	  Loss: 1.6431116806864037 	 Accuracy: 0.27509778357235987
Delta: 0.004502154302306801 	  Loss: 1.642556365538839 	 Accuracy: 0.27640156453715775
Delta: 0.00211880214400296 	  Loss: 1.642638652782663 	 Accuracy: 0.27640156453715775
Delta: 0.004052852706954981 	  Loss: 1.6424846021522308 	 Accuracy: 0.2790091264667536
Delta: 0.004599769694314685 	  Loss: 1.641325523603903 	 Accuracy: 0.27640156453715775
Delta: 0.004208246543409405 	  Loss: 1.6406954988676947 	 Accuracy: 0.2790091264667536
Delta: 0.0039402324058032566 	  Loss: 1.6414132202172653 	 Accuracy: 0.2777053455019557
Delta: 0.0025655434663323564 	  Loss: 1.6412001675784142 	 Accuracy: 0.2777053455019557
Delta: 0.0021295743583343465 	  Loss: 1.6413860147582218 	 Accuracy: 0.2790091264667536
Delta: 0.005390781883532465 	  Loss: 1.6416618221994894 	 Accuracy: 0.2816166883963494
Delta: 0.004147942394680523 	  Loss: 1.6417848397316481 	 Accuracy: 0.2790091264667536
Delta: 0.0007586977843266427 	  Loss: 1.6418224066487381 	 Accuracy: 0.2803129074315515
Delta: 0.0005418961017398591 	  Loss: 1.6415392499682055 	 Accuracy: 0.2803129074315515
Delta: 0.0006122143383238985 	  Loss: 1.6415733750201627 	 Accuracy: 0.2803129074315515
Delta: 1.7277374466422677e-05 	  Loss: 1.6415608987284571 	 Accuracy: 0.2803129074315515
Delta: 0.0019285727734566734 	  Loss: 1.6415630385748752 	 Accuracy: 0.2803129074315515
Delta: 1.6947271376331e-05 	  Loss: 1.641577041718875 	 Accuracy: 0.2790091264667536
Delta: 0.0014469794246123719 	  Loss: 1.6416621267606155 	 Accuracy: 0.2803129074315515
Delta: 2.7869729458967243e-05 	  Loss: 1.6416572436956998 	 Accuracy: 0.2790091264667536
Delta: 0.001226311201754766 	  Loss: 1.6415364247722652 	 Accuracy: 0.2803129074315515
Delta: 0.0005159205829955271 	  Loss: 1.6415315618840876 	 Accuracy: 0.2803129074315515
Delta: 0.002057314469382485 	  Loss: 1.6415084645027418 	 Accuracy: 0.2803129074315515
Delta: 0.0005345634641376575 	  Loss: 1.641628170575192 	 Accuracy: 0.28292046936114734
Delta: 2.7296916426609428e-05 	  Loss: 1.641540965547617 	 Accuracy: 0.2790091264667536
Delta: 0.0036170311217979876 	  Loss: 1.642233409247307 	 Accuracy: 0.2777053455019557
Delta: 0.003129019917215074 	  Loss: 1.642175438346549 	 Accuracy: 0.2633637548891786
Delta: 0.002921573503133326 	  Loss: 1.642548543985066 	 Accuracy: 0.27509778357235987
Delta: 0.0027989638005991796 	  Loss: 1.6421946218953056 	 Accuracy: 0.2777053455019557
Delta: 0.003613494931540398 	  Loss: 1.6420886475800485 	 Accuracy: 0.2777053455019557
Delta: 0.0025046656282942735 	  Loss: 1.642474853867503 	 Accuracy: 0.2816166883963494
Delta: 0.0029737992144449007 	  Loss: 1.6428512829650215 	 Accuracy: 0.2803129074315515
Delta: 0.0034151916134745317 	  Loss: 1.6423284100670021 	 Accuracy: 0.28552803129074317
Delta: 0.006974063283056315 	  Loss: 1.6409174578495809 	 Accuracy: 0.2803129074315515
Delta: 0.004335771221661527 	  Loss: 1.6403542160466957 	 Accuracy: 0.2790091264667536
Delta: 0.004589945478879965 	  Loss: 1.640664141420681 	 Accuracy: 0.2790091264667536
Delta: 0.001998975892402801 	  Loss: 1.6403952084916147 	 Accuracy: 0.2803129074315515
Delta: 0.0022098942193489006 	  Loss: 1.6409099166720766 	 Accuracy: 0.2803129074315515
Delta: 0.0035377996983642244 	  Loss: 1.6410251859206846 	 Accuracy: 0.2790091264667536
Delta: 0.0035203402314561653 	  Loss: 1.6410897378504723 	 Accuracy: 0.2790091264667536
Delta: 0.003735423907585582 	  Loss: 1.6411952929708786 	 Accuracy: 0.2790091264667536
Delta: 0.005015395209728501 	  Loss: 1.6411351200823072 	 Accuracy: 0.2777053455019557
Delta: 0.002070867857409645 	  Loss: 1.641039304428956 	 Accuracy: 0.2790091264667536
Delta: 0.004101650263743542 	  Loss: 1.6410649052073099 	 Accuracy: 0.2790091264667536
Delta: 0.0009150191750599046 	  Loss: 1.641014297436601 	 Accuracy: 0.2803129074315515
Delta: 0.0021470016852302826 	  Loss: 1.6409399087343135 	 Accuracy: 0.2777053455019557
Delta: 0.005024746506750308 	  Loss: 1.6418655956720842 	 Accuracy: 0.2803129074315515
Delta: 0.005176929361996223 	  Loss: 1.6401157792830325 	 Accuracy: 0.2777053455019557
Delta: 0.002963482705848788 	  Loss: 1.6404931676682997 	 Accuracy: 0.27640156453715775
Delta: 0.005110531079907007 	  Loss: 1.6413110662548203 	 Accuracy: 0.2777053455019557
Delta: 0.0019959172441804977 	  Loss: 1.6411674537401821 	 Accuracy: 0.2790091264667536
Delta: 0.0031281823988070956 	  Loss: 1.6406494285448558 	 Accuracy: 0.2790091264667536
Delta: 0.0005919489471929669 	  Loss: 1.6407012198098516 	 Accuracy: 0.2803129074315515
Delta: 0.0026540401406764708 	  Loss: 1.640311900722237 	 Accuracy: 0.2790091264667536
Delta: 0.0013218108424317785 	  Loss: 1.6406968051876527 	 Accuracy: 0.2777053455019557
Delta: 0.004306848298800599 	  Loss: 1.6408643287734168 	 Accuracy: 0.27640156453715775
Delta: 0.002938068871061004 	  Loss: 1.641378855647706 	 Accuracy: 0.27509778357235987
Delta: 0.0013517234393699378 	  Loss: 1.6412161765598394 	 Accuracy: 0.27640156453715775
Delta: 0.0026562767483397937 	  Loss: 1.6411404870057171 	 Accuracy: 0.2777053455019557
Delta: 0.0028349270620750726 	  Loss: 1.6409886445319146 	 Accuracy: 0.2777053455019557
Delta: 0.0024167677659725707 	  Loss: 1.6411795256427184 	 Accuracy: 0.2777053455019557
Delta: 0.0031549884541390376 	  Loss: 1.6411026528862305 	 Accuracy: 0.27640156453715775
Delta: 0.003375104558632913 	  Loss: 1.6405955738034195 	 Accuracy: 0.2777053455019557
Delta: 0.0009632834839301338 	  Loss: 1.6405935811922736 	 Accuracy: 0.2777053455019557
Delta: 8.222414098865339e-05 	  Loss: 1.640673255149858 	 Accuracy: 0.2777053455019557
Delta: 0.00013985953658178144 	  Loss: 1.6404656522684438 	 Accuracy: 0.27640156453715775
Delta: 0.0030871358261395383 	  Loss: 1.6408091056828222 	 Accuracy: 0.2790091264667536
Delta: 0.003913794014156811 	  Loss: 1.6399958360804054 	 Accuracy: 0.2777053455019557
Delta: 0.004266110142562732 	  Loss: 1.6390005649943622 	 Accuracy: 0.2777053455019557
Delta: 0.002296198949806574 	  Loss: 1.6389420949852995 	 Accuracy: 0.2777053455019557
Delta: 0.004032686027540636 	  Loss: 1.6389674717242873 	 Accuracy: 0.27640156453715775
Delta: 0.001648362191627768 	  Loss: 1.638901480686217 	 Accuracy: 0.2777053455019557
Delta: 0.0008664560814853867 	  Loss: 1.6389425138089022 	 Accuracy: 0.2777053455019557
Delta: 0.004659022897605452 	  Loss: 1.6396769541501126 	 Accuracy: 0.27640156453715775
Delta: 0.0032457680249074836 	  Loss: 1.6393088120545314 	 Accuracy: 0.2777053455019557
Delta: 0.002721506767627767 	  Loss: 1.6391445631697796 	 Accuracy: 0.2777053455019557
Delta: 0.020930264142022717 	  Loss: 2.1589437538900476 	 Accuracy: 0.19035202086049544
Delta: 0.018999783575990303 	  Loss: 2.0524793649849196 	 Accuracy: 0.1773142112125163
Delta: 0.01820516105611637 	  Loss: 1.845683943054918 	 Accuracy: 0.19556714471968709
Delta: 0.01595868075143979 	  Loss: 1.696283715830148 	 Accuracy: 0.20078226857887874
Delta: 0.012406919029006059 	  Loss: 1.6477529794272696 	 Accuracy: 0.21251629726205998
Delta: 0.009343835195173452 	  Loss: 1.638385625096828 	 Accuracy: 0.21251629726205998

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007669360690676639 	  Loss: 1.636719901204045 	 Accuracy: 0.21121251629726207
Delta: 0.005511635583162201 	  Loss: 1.636153854260768 	 Accuracy: 0.2151238591916558
Delta: 0.004626803756753196 	  Loss: 1.6355907163524366 	 Accuracy: 0.2151238591916558
Delta: 0.001891128036369939 	  Loss: 1.6354255951738965 	 Accuracy: 0.2151238591916558
Delta: 0.0028803118914325827 	  Loss: 1.6352667238319474 	 Accuracy: 0.21642764015645372
Delta: 2.3240006329887902e-05 	  Loss: 1.635240445616952 	 Accuracy: 0.2151238591916558
Delta: 0.0011964448405119665 	  Loss: 1.6352294948256816 	 Accuracy: 0.2151238591916558
Delta: 0.002174937231283584 	  Loss: 1.6354364169901099 	 Accuracy: 0.2151238591916558
Delta: 5.9951407912487224e-05 	  Loss: 1.6355412926443154 	 Accuracy: 0.2151238591916558
Delta: 0.0023634561508298286 	  Loss: 1.6356818189189455 	 Accuracy: 0.2151238591916558
Delta: 0.0023543572496767524 	  Loss: 1.6353777457499494 	 Accuracy: 0.2151238591916558
Delta: 0.0009148115748428799 	  Loss: 1.635196159272168 	 Accuracy: 0.21642764015645372
Delta: 6.864633969912185e-05 	  Loss: 1.6354364589945651 	 Accuracy: 0.21642764015645372
Delta: 0.0013473226399224813 	  Loss: 1.635345774936302 	 Accuracy: 0.21642764015645372
Delta: 0.00010389067973403018 	  Loss: 1.6351727044369837 	 Accuracy: 0.21642764015645372
Delta: 0.003209085827075067 	  Loss: 1.6350812401642303 	 Accuracy: 0.2320730117340287
Delta: 0.0035121123169173144 	  Loss: 1.6348518695822585 	 Accuracy: 0.2151238591916558
Delta: 0.002097295640345239 	  Loss: 1.635348972624893 	 Accuracy: 0.21642764015645372
Delta: 0.0009381108766186677 	  Loss: 1.6351631620349898 	 Accuracy: 0.21642764015645372
Delta: 0.0007828108592837198 	  Loss: 1.6351143457044364 	 Accuracy: 0.2151238591916558
Delta: 0.00416198571124514 	  Loss: 1.6353818574011585 	 Accuracy: 0.21773142112125163
Delta: 0.0025508955335407464 	  Loss: 1.634993893664139 	 Accuracy: 0.21773142112125163
Delta: 0.0062832422563309795 	  Loss: 1.636210985024713 	 Accuracy: 0.21642764015645372
Delta: 0.0037726808686103295 	  Loss: 1.6356897092925706 	 Accuracy: 0.21773142112125163
Delta: 0.0024546699273632 	  Loss: 1.63574316149153 	 Accuracy: 0.21773142112125163
Delta: 0.0005439136010123843 	  Loss: 1.6355110687981222 	 Accuracy: 0.21773142112125163
Delta: 0.003889573550804379 	  Loss: 1.6357037383273605 	 Accuracy: 0.21773142112125163
Delta: 0.0012993765628373862 	  Loss: 1.6357789443257467 	 Accuracy: 0.21642764015645372
Delta: 5.294831399825584e-05 	  Loss: 1.6356351346342892 	 Accuracy: 0.2151238591916558
Delta: 0.0018056022292789425 	  Loss: 1.636101851409755 	 Accuracy: 0.2151238591916558
Delta: 0.004255245734054156 	  Loss: 1.636341761439067 	 Accuracy: 0.21773142112125163
Delta: 0.005075978529885234 	  Loss: 1.6364793485320528 	 Accuracy: 0.2138200782268579
Delta: 0.005546224600650238 	  Loss: 1.6347352413534706 	 Accuracy: 0.2151238591916558
Delta: 0.004198681959815893 	  Loss: 1.6349099009198635 	 Accuracy: 0.2151238591916558
Delta: 0.0027948998618287503 	  Loss: 1.6348799196678048 	 Accuracy: 0.2151238591916558
Delta: 0.0009757287330062597 	  Loss: 1.63487783485186 	 Accuracy: 0.2138200782268579
Delta: 0.001929792184424973 	  Loss: 1.6348545219890762 	 Accuracy: 0.2138200782268579
Delta: 1.7270317669024148e-05 	  Loss: 1.6349424142193176 	 Accuracy: 0.2138200782268579
Delta: 0.003960067420679283 	  Loss: 1.6348781482633963 	 Accuracy: 0.2138200782268579
Delta: 0.0040950506367274505 	  Loss: 1.6343871631248699 	 Accuracy: 0.2138200782268579
Delta: 0.0054462019556530995 	  Loss: 1.6348992722500575 	 Accuracy: 0.21903520208604954
Delta: 0.0025356173631410515 	  Loss: 1.6348556561922576 	 Accuracy: 0.2151238591916558
Delta: 0.0033548200123087553 	  Loss: 1.6348253620194946 	 Accuracy: 0.21251629726205998
Delta: 0.0034620572389455384 	  Loss: 1.6356695178476446 	 Accuracy: 0.21251629726205998
Delta: 0.001660406052047895 	  Loss: 1.6355592705104622 	 Accuracy: 0.21251629726205998
Delta: 3.1095989573756292e-06 	  Loss: 1.6355702034343595 	 Accuracy: 0.21251629726205998
Delta: 3.79464764606788e-06 	  Loss: 1.6355620682563536 	 Accuracy: 0.21121251629726207
Delta: 0.0028493566034038073 	  Loss: 1.635679620876874 	 Accuracy: 0.21251629726205998
Delta: 0.004022000090816841 	  Loss: 1.6357953180385194 	 Accuracy: 0.2138200782268579
Delta: 0.0016820697195811913 	  Loss: 1.6353224171029481 	 Accuracy: 0.2138200782268579
Delta: 0.0013698480488946014 	  Loss: 1.6353701852795384 	 Accuracy: 0.2138200782268579
Delta: 0.0034988703018860824 	  Loss: 1.635426006118096 	 Accuracy: 0.2138200782268579
Delta: 0.004922083793354828 	  Loss: 1.6353975972274986 	 Accuracy: 0.2151238591916558
Delta: 0.0011488122071430195 	  Loss: 1.6352187467068084 	 Accuracy: 0.2138200782268579
Delta: 0.001642381238542242 	  Loss: 1.63544882211246 	 Accuracy: 0.2138200782268579
Delta: 0.0019351369174105497 	  Loss: 1.6356505727495314 	 Accuracy: 0.2138200782268579
Delta: 0.0012039398111412056 	  Loss: 1.6354257381014916 	 Accuracy: 0.21251629726205998
Delta: 0.004143970510100213 	  Loss: 1.6359897876334375 	 Accuracy: 0.2138200782268579
Delta: 0.0019053111232453363 	  Loss: 1.634944262709912 	 Accuracy: 0.21773142112125163
Delta: 0.0018838477574203473 	  Loss: 1.6346769230017748 	 Accuracy: 0.2151238591916558
Delta: 0.0027161311743326313 	  Loss: 1.63508422648867 	 Accuracy: 0.2138200782268579
Delta: 0.0005677114298437529 	  Loss: 1.6349198071535147 	 Accuracy: 0.2151238591916558
Delta: 0.0010252961286660407 	  Loss: 1.634657113817948 	 Accuracy: 0.21642764015645372
Delta: 1.6112421799189473e-05 	  Loss: 1.6346940236267051 	 Accuracy: 0.2151238591916558
Delta: 1.137010029577259e-05 	  Loss: 1.6346607744508819 	 Accuracy: 0.2151238591916558
Delta: 2.2148341522515368e-06 	  Loss: 1.6346606645316357 	 Accuracy: 0.21251629726205998
Delta: 0.002004519242593356 	  Loss: 1.6353119108180234 	 Accuracy: 0.2138200782268579
Delta: 0.000947086473520049 	  Loss: 1.6355669660547858 	 Accuracy: 0.2151238591916558
Delta: 0.0011060300315411946 	  Loss: 1.6346785328175693 	 Accuracy: 0.21642764015645372
Delta: 0.005343103262255384 	  Loss: 1.6349286774396732 	 Accuracy: 0.21642764015645372
Delta: 0.0016581364128304033 	  Loss: 1.6346477100068721 	 Accuracy: 0.21642764015645372
Delta: 0.001947915815847218 	  Loss: 1.6345333959040866 	 Accuracy: 0.2151238591916558
Delta: 0.002461950984745895 	  Loss: 1.6345594492408841 	 Accuracy: 0.2151238591916558
Delta: 0.0033147505515480017 	  Loss: 1.6341951806559822 	 Accuracy: 0.2151238591916558
Delta: 0.004377985511648039 	  Loss: 1.6341194896515212 	 Accuracy: 0.2151238591916558
Delta: 0.0007582507617678495 	  Loss: 1.6338073068322019 	 Accuracy: 0.2151238591916558
Delta: 0.002824237479165798 	  Loss: 1.634058357610547 	 Accuracy: 0.2151238591916558
Delta: 0.0014452431219844995 	  Loss: 1.6340888945992895 	 Accuracy: 0.2151238591916558
Delta: 0.0005384606329938542 	  Loss: 1.633862226200753 	 Accuracy: 0.2151238591916558
Delta: 0.001581589578849171 	  Loss: 1.633787246173379 	 Accuracy: 0.2151238591916558
Delta: 7.700470366800458e-05 	  Loss: 1.6338811482966087 	 Accuracy: 0.2151238591916558
Delta: 3.145462564426199e-06 	  Loss: 1.633865429091238 	 Accuracy: 0.2151238591916558
Delta: 1.9473968485210565e-05 	  Loss: 1.6339623486538497 	 Accuracy: 0.2151238591916558
Delta: 0.004505784315648394 	  Loss: 1.6349222113822375 	 Accuracy: 0.2151238591916558
Delta: 0.003591892170571194 	  Loss: 1.6336686081560559 	 Accuracy: 0.2151238591916558
Delta: 0.0033060549649439725 	  Loss: 1.633343594272812 	 Accuracy: 0.2151238591916558
Delta: 0.0018314298865135933 	  Loss: 1.6336539263172978 	 Accuracy: 0.2151238591916558
Delta: 8.352250772878109e-06 	  Loss: 1.6336478601589521 	 Accuracy: 0.2151238591916558
Delta: 0.0023728186828025815 	  Loss: 1.6333617042215145 	 Accuracy: 0.2151238591916558
Delta: 0.0017840647097552588 	  Loss: 1.6334401947243247 	 Accuracy: 0.2151238591916558
Delta: 0.003818663789845864 	  Loss: 1.6332319102807924 	 Accuracy: 0.2151238591916558
Delta: 0.004094681632223362 	  Loss: 1.6335961009561832 	 Accuracy: 0.2151238591916558
Delta: 0.002751998954072208 	  Loss: 1.6338427792215122 	 Accuracy: 0.21903520208604954
Delta: 0.004694467447288986 	  Loss: 1.6318572573621108 	 Accuracy: 0.21773142112125163
Delta: 0.021032520453621882 	  Loss: 2.158759236233694 	 Accuracy: 0.20599739243807041
Delta: 0.019232281936513818 	  Loss: 2.0362448517005194 	 Accuracy: 0.21251629726205998
Delta: 0.01801576045180083 	  Loss: 1.83782051462707 	 Accuracy: 0.27249022164276404
Delta: 0.01601085166998901 	  Loss: 1.7154921979336284 	 Accuracy: 0.3089960886571056
Delta: 0.012180602510500358 	  Loss: 1.6774280741598329 	 Accuracy: 0.31681877444589307

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00975127526535379 	  Loss: 1.667946118273013 	 Accuracy: 0.30378096479791394
Delta: 0.00710691026471342 	  Loss: 1.6660905545750277 	 Accuracy: 0.3050847457627119
Delta: 0.004671171572269317 	  Loss: 1.6652702676648266 	 Accuracy: 0.30638852672750977
Delta: 0.004421608234408995 	  Loss: 1.6657502038119065 	 Accuracy: 0.3050847457627119
Delta: 0.004056712518819462 	  Loss: 1.6656671185455123 	 Accuracy: 0.30638852672750977
Delta: 0.0013727890471400426 	  Loss: 1.6657663992099745 	 Accuracy: 0.30638852672750977
Delta: 0.0026655897981868117 	  Loss: 1.665751977798771 	 Accuracy: 0.30638852672750977
Delta: 0.0013947561565342444 	  Loss: 1.6658682100203235 	 Accuracy: 0.3076923076923077
Delta: 0.0008403143640145186 	  Loss: 1.6658638261983998 	 Accuracy: 0.3076923076923077
Delta: 0.0014149783682951779 	  Loss: 1.6657181956482963 	 Accuracy: 0.30638852672750977
Delta: 1.8584330967570726e-05 	  Loss: 1.6657479337530194 	 Accuracy: 0.2985658409387223
Delta: 6.342354483882964e-05 	  Loss: 1.6657901240088235 	 Accuracy: 0.3050847457627119
Delta: 0.0015567867808616031 	  Loss: 1.665830326629528 	 Accuracy: 0.30638852672750977
Delta: 0.0004993504702406928 	  Loss: 1.6658110882894421 	 Accuracy: 0.30638852672750977
Delta: 0.004210588039029386 	  Loss: 1.6660026488323227 	 Accuracy: 0.30638852672750977
Delta: 0.0034947830212691973 	  Loss: 1.6658557502932516 	 Accuracy: 0.30638852672750977
Delta: 7.504614557397736e-05 	  Loss: 1.6657671570317305 	 Accuracy: 0.30638852672750977
Delta: 0.0016596874701581006 	  Loss: 1.6658613059854566 	 Accuracy: 0.30638852672750977
Delta: 0.0005655332622612821 	  Loss: 1.6657910260901625 	 Accuracy: 0.30638852672750977
Delta: 0.0021823674982870142 	  Loss: 1.665511299766468 	 Accuracy: 0.3076923076923077
Delta: 0.0018720818265687239 	  Loss: 1.66583053485524 	 Accuracy: 0.30638852672750977
Delta: 0.0010612483585774161 	  Loss: 1.6657066628966832 	 Accuracy: 0.30638852672750977
Delta: 0.00411459412689737 	  Loss: 1.6661316521594989 	 Accuracy: 0.30638852672750977
Delta: 0.00399657498153867 	  Loss: 1.664791586168132 	 Accuracy: 0.3050847457627119
Delta: 0.003336508760217464 	  Loss: 1.6644509155643858 	 Accuracy: 0.30638852672750977
Delta: 0.003579398003662271 	  Loss: 1.6645291829306499 	 Accuracy: 0.3050847457627119
Delta: 0.004381194182722582 	  Loss: 1.6655020343037734 	 Accuracy: 0.3050847457627119
Delta: 0.0014750409117965356 	  Loss: 1.6655801984876395 	 Accuracy: 0.3050847457627119
Delta: 0.0008198677170373665 	  Loss: 1.6656385517736951 	 Accuracy: 0.30638852672750977
Delta: 0.001776351052024035 	  Loss: 1.6654503550676985 	 Accuracy: 0.30638852672750977
Delta: 0.006253495462642346 	  Loss: 1.6658594320401576 	 Accuracy: 0.30638852672750977
Delta: 0.0046359013560925205 	  Loss: 1.6655967494714123 	 Accuracy: 0.30638852672750977
Delta: 0.0031000466486123825 	  Loss: 1.6652162022168862 	 Accuracy: 0.30638852672750977
Delta: 0.0034624430057004743 	  Loss: 1.6650091538148328 	 Accuracy: 0.30638852672750977
Delta: 0.0006187968491234673 	  Loss: 1.6649867481720138 	 Accuracy: 0.30638852672750977
Delta: 5.3277728079132965e-06 	  Loss: 1.6649679286545835 	 Accuracy: 0.30638852672750977
Delta: 1.438259732645881e-05 	  Loss: 1.6649892624080644 	 Accuracy: 0.30638852672750977
Delta: 0.005433963059046513 	  Loss: 1.6644073471168541 	 Accuracy: 0.3076923076923077
Delta: 0.003803501718041283 	  Loss: 1.6649211616980994 	 Accuracy: 0.30638852672750977
Delta: 0.0017968252440866304 	  Loss: 1.6657977819361829 	 Accuracy: 0.3076923076923077
Delta: 0.005405169405842929 	  Loss: 1.663572450077735 	 Accuracy: 0.3050847457627119
Delta: 0.005414277921236752 	  Loss: 1.6654340920611754 	 Accuracy: 0.30638852672750977
Delta: 0.0035651772655032063 	  Loss: 1.6647287100397956 	 Accuracy: 0.30638852672750977
Delta: 0.003737807082112284 	  Loss: 1.6649576805591764 	 Accuracy: 0.30638852672750977
Delta: 0.0031968528630358295 	  Loss: 1.66537542856463 	 Accuracy: 0.3050847457627119
Delta: 0.0034874051645308823 	  Loss: 1.6653606080867378 	 Accuracy: 0.30638852672750977
Delta: 0.0011617908600306225 	  Loss: 1.6652511714727067 	 Accuracy: 0.30638852672750977
Delta: 3.5994936536801304e-05 	  Loss: 1.665209563705516 	 Accuracy: 0.30638852672750977
Delta: 5.677680969119433e-06 	  Loss: 1.6652117553385104 	 Accuracy: 0.30638852672750977
Delta: 0.00284107970148844 	  Loss: 1.664616333431216 	 Accuracy: 0.30247718383311606
Delta: 0.003770337526081488 	  Loss: 1.664565555698347 	 Accuracy: 0.30638852672750977
Delta: 0.001066494220963581 	  Loss: 1.6646613024403152 	 Accuracy: 0.3076923076923077
Delta: 2.107398798208428e-05 	  Loss: 1.6646836809144552 	 Accuracy: 0.3089960886571056
Delta: 0.0022460941872773014 	  Loss: 1.6647463434627547 	 Accuracy: 0.30638852672750977
Delta: 0.0026501424124301637 	  Loss: 1.6649432798916854 	 Accuracy: 0.3089960886571056
Delta: 0.0005797597283247128 	  Loss: 1.6647039678847082 	 Accuracy: 0.3076923076923077
Delta: 0.0022824593622637157 	  Loss: 1.6650008535047758 	 Accuracy: 0.30638852672750977
Delta: 0.004844222869288448 	  Loss: 1.6654464116835683 	 Accuracy: 0.3076923076923077
Delta: 0.0010501623014739139 	  Loss: 1.6652613052219922 	 Accuracy: 0.30247718383311606
Delta: 0.0050739224328986065 	  Loss: 1.6668509724691973 	 Accuracy: 0.30378096479791394
Delta: 0.0028818178751437093 	  Loss: 1.6666964078556905 	 Accuracy: 0.3050847457627119
Delta: 0.003973714000739397 	  Loss: 1.6659156135371864 	 Accuracy: 0.30378096479791394
Delta: 0.0013295449954223491 	  Loss: 1.665884342835772 	 Accuracy: 0.3050847457627119
Delta: 0.0029850788925697494 	  Loss: 1.6660429816216693 	 Accuracy: 0.3050847457627119
Delta: 0.002532216250298266 	  Loss: 1.6661151771589626 	 Accuracy: 0.3050847457627119
Delta: 2.2931337140910954e-05 	  Loss: 1.6661824458908918 	 Accuracy: 0.3050847457627119
Delta: 0.002788425494513164 	  Loss: 1.6662760850675595 	 Accuracy: 0.3050847457627119
Delta: 0.0016300766947037562 	  Loss: 1.666111275974032 	 Accuracy: 0.3050847457627119
Delta: 1.4942560562172764e-05 	  Loss: 1.6660901639355945 	 Accuracy: 0.30638852672750977
Delta: 3.831378253244117e-06 	  Loss: 1.666073603032142 	 Accuracy: 0.3050847457627119
Delta: 4.79535652803249e-05 	  Loss: 1.6663831115699181 	 Accuracy: 0.3050847457627119
Delta: 0.002217999321873035 	  Loss: 1.666417787394603 	 Accuracy: 0.30378096479791394
Delta: 0.004079515442601137 	  Loss: 1.6667880887182982 	 Accuracy: 0.3050847457627119
Delta: 6.481860641169559e-05 	  Loss: 1.6668015260722053 	 Accuracy: 0.3050847457627119
Delta: 0.00472544142278006 	  Loss: 1.6660038247293123 	 Accuracy: 0.31029986962190353
Delta: 0.006696237188814264 	  Loss: 1.6683571512216144 	 Accuracy: 0.3089960886571056
Delta: 0.005216525495829145 	  Loss: 1.6671834296754091 	 Accuracy: 0.3050847457627119
Delta: 0.0021494605106248655 	  Loss: 1.6668924274194097 	 Accuracy: 0.30638852672750977
Delta: 0.0006621061466884861 	  Loss: 1.6668475459246064 	 Accuracy: 0.30638852672750977
Delta: 0.0008419279305382533 	  Loss: 1.666915086024094 	 Accuracy: 0.30247718383311606
Delta: 0.004608423800069471 	  Loss: 1.667226093896036 	 Accuracy: 0.30638852672750977
Delta: 0.004197135169798666 	  Loss: 1.6657932576057348 	 Accuracy: 0.30638852672750977
Delta: 0.002928597615645155 	  Loss: 1.6657158754935573 	 Accuracy: 0.30638852672750977
Delta: 0.0041897574039653305 	  Loss: 1.664701688781525 	 Accuracy: 0.30638852672750977
Delta: 0.004187582689488498 	  Loss: 1.6655480553360298 	 Accuracy: 0.3089960886571056
Delta: 0.0067899121488861885 	  Loss: 1.6625658869461568 	 Accuracy: 0.3089960886571056
Delta: 0.0033960682164462766 	  Loss: 1.6616467094764698 	 Accuracy: 0.3076923076923077
Delta: 0.004717526520508953 	  Loss: 1.660638600672895 	 Accuracy: 0.318122555410691
Delta: 0.0049431156971156695 	  Loss: 1.6627194400660217 	 Accuracy: 0.3089960886571056
Delta: 0.0032446547757333587 	  Loss: 1.6627504072400252 	 Accuracy: 0.3089960886571056
Delta: 0.0013679015549028306 	  Loss: 1.6627855660516775 	 Accuracy: 0.3089960886571056
Delta: 0.000618939034150897 	  Loss: 1.6628156441130217 	 Accuracy: 0.3089960886571056
Delta: 0.0035849185557884173 	  Loss: 1.662773958350478 	 Accuracy: 0.31421121251629724
Delta: 0.004220051685326685 	  Loss: 1.6629274595903978 	 Accuracy: 0.3089960886571056
Delta: 0.0025006150513538416 	  Loss: 1.662711883576622 	 Accuracy: 0.3089960886571056
Delta: 0.02121376548466925 	  Loss: 2.1576896657992943 	 Accuracy: 0.25684485006518903
Delta: 0.01921097576802617 	  Loss: 2.0332503657005727 	 Accuracy: 0.2685788787483703
Delta: 0.018257968785180552 	  Loss: 1.7940513129427738 	 Accuracy: 0.30247718383311606
Delta: 0.014859625045299819 	  Loss: 1.675669875333508 	 Accuracy: 0.29986962190352023
Delta: 0.009402934952028558 	  Loss: 1.6577210269681817 	 Accuracy: 0.3050847457627119

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007845314227372667 	  Loss: 1.6546006131137878 	 Accuracy: 0.3089960886571056
Delta: 0.006600077143434337 	  Loss: 1.654963825107509 	 Accuracy: 0.30638852672750977
Delta: 0.004875152650055244 	  Loss: 1.65527483029706 	 Accuracy: 0.3194263363754889
Delta: 0.0032600935388055587 	  Loss: 1.6550622553847218 	 Accuracy: 0.3076923076923077
Delta: 0.0012660808153819273 	  Loss: 1.6550317265020722 	 Accuracy: 0.3076923076923077
Delta: 0.0011236442834766007 	  Loss: 1.655056332573496 	 Accuracy: 0.3076923076923077
Delta: 1.4656318768991827e-05 	  Loss: 1.6549963348218018 	 Accuracy: 0.30378096479791394
Delta: 0.0006654684217766082 	  Loss: 1.6549424542471463 	 Accuracy: 0.30638852672750977
Delta: 0.0021406272692357617 	  Loss: 1.655124606331088 	 Accuracy: 0.3076923076923077
Delta: 0.002524299375450171 	  Loss: 1.6551182335730281 	 Accuracy: 0.3076923076923077
Delta: 2.4303000714131893e-05 	  Loss: 1.655216000212089 	 Accuracy: 0.3076923076923077
Delta: 0.0005300612791471227 	  Loss: 1.655206480629147 	 Accuracy: 0.3076923076923077
Delta: 4.20392061492815e-05 	  Loss: 1.6551559302896424 	 Accuracy: 0.31290743155149936
Delta: 0.0010568789658866656 	  Loss: 1.6551723662674402 	 Accuracy: 0.3076923076923077
Delta: 0.0016719122094044536 	  Loss: 1.6550773746506167 	 Accuracy: 0.3076923076923077
Delta: 6.45591489250322e-06 	  Loss: 1.6550906028300103 	 Accuracy: 0.3089960886571056
Delta: 8.026175342353791e-06 	  Loss: 1.6550488815538014 	 Accuracy: 0.3076923076923077
Delta: 2.9996659449634025e-05 	  Loss: 1.655121490344789 	 Accuracy: 0.3076923076923077
Delta: 3.588368862418189e-05 	  Loss: 1.6550812040778504 	 Accuracy: 0.3076923076923077
Delta: 1.903011253940643e-06 	  Loss: 1.6550751432203086 	 Accuracy: 0.31421121251629724
Delta: 0.002136900794489734 	  Loss: 1.65520034525644 	 Accuracy: 0.3076923076923077
Delta: 6.093327476079473e-05 	  Loss: 1.6549182379063607 	 Accuracy: 0.3089960886571056
Delta: 1.935205614275321e-05 	  Loss: 1.6549343882203282 	 Accuracy: 0.3076923076923077
Delta: 3.031496355899483e-05 	  Loss: 1.654880195377085 	 Accuracy: 0.3076923076923077
Delta: 4.793897475658864e-05 	  Loss: 1.6548716023023111 	 Accuracy: 0.30638852672750977
Delta: 5.299437059394343e-05 	  Loss: 1.654939419224739 	 Accuracy: 0.3076923076923077
Delta: 2.146704836311144e-05 	  Loss: 1.65487205630198 	 Accuracy: 0.30378096479791394
Delta: 0.0009127295514771264 	  Loss: 1.6549424446514518 	 Accuracy: 0.3089960886571056
Delta: 7.152133672911957e-05 	  Loss: 1.654960009765494 	 Accuracy: 0.31290743155149936
Delta: 0.0016238285722999502 	  Loss: 1.6547331513865964 	 Accuracy: 0.30378096479791394
Delta: 0.0038897745566733324 	  Loss: 1.6551251857812384 	 Accuracy: 0.3076923076923077
Delta: 0.0017922805045323784 	  Loss: 1.6548585037259333 	 Accuracy: 0.31029986962190353
Delta: 0.003553532061274992 	  Loss: 1.6546963527647514 	 Accuracy: 0.3089960886571056
Delta: 0.0058174054318413035 	  Loss: 1.6547641183721775 	 Accuracy: 0.3076923076923077
Delta: 0.003529078843389282 	  Loss: 1.654611361308191 	 Accuracy: 0.3089960886571056
Delta: 0.0026373292322049813 	  Loss: 1.6545764358450148 	 Accuracy: 0.3089960886571056
Delta: 0.0008550410339306935 	  Loss: 1.6545679897324532 	 Accuracy: 0.3089960886571056
Delta: 0.0004915016622653725 	  Loss: 1.654570972712026 	 Accuracy: 0.31029986962190353
Delta: 5.2917820572161626e-05 	  Loss: 1.6544626528801354 	 Accuracy: 0.3089960886571056
Delta: 5.411897991481575e-05 	  Loss: 1.654581077146454 	 Accuracy: 0.3089960886571056
Delta: 0.0018375889892291942 	  Loss: 1.6549637056219546 	 Accuracy: 0.3089960886571056
Delta: 3.4699220759226235e-05 	  Loss: 1.6550270278231327 	 Accuracy: 0.31029986962190353
Delta: 4.800541564194423e-05 	  Loss: 1.6549534789655558 	 Accuracy: 0.3089960886571056
Delta: 0.001710802386508183 	  Loss: 1.655343120806661 	 Accuracy: 0.3089960886571056
Delta: 0.0009267699023466039 	  Loss: 1.654969693317659 	 Accuracy: 0.3089960886571056
Delta: 0.004409991737492872 	  Loss: 1.6556945305062079 	 Accuracy: 0.30247718383311606
Delta: 0.007784297271198426 	  Loss: 1.6557741114740852 	 Accuracy: 0.30638852672750977
Delta: 0.00415708663565699 	  Loss: 1.6554162429676518 	 Accuracy: 0.3076923076923077
Delta: 0.005298329593011967 	  Loss: 1.654190368914755 	 Accuracy: 0.3076923076923077
Delta: 0.0026403497089273584 	  Loss: 1.6547458128022379 	 Accuracy: 0.3089960886571056
Delta: 0.0025244489208243945 	  Loss: 1.6549912346202034 	 Accuracy: 0.30638852672750977
Delta: 0.0034739859593798817 	  Loss: 1.65510238049178 	 Accuracy: 0.3076923076923077
Delta: 0.004109566379065455 	  Loss: 1.6548317999544855 	 Accuracy: 0.3089960886571056
Delta: 0.0032354641760104696 	  Loss: 1.6545296234623486 	 Accuracy: 0.3116036505867014
Delta: 0.00493828006169902 	  Loss: 1.6533534550058984 	 Accuracy: 0.3089960886571056
Delta: 0.0015712914304937735 	  Loss: 1.6535179520915437 	 Accuracy: 0.31029986962190353
Delta: 0.005276367077398045 	  Loss: 1.6543276254792334 	 Accuracy: 0.31029986962190353
Delta: 0.0031972784227726546 	  Loss: 1.6543450208469586 	 Accuracy: 0.31029986962190353
Delta: 0.004439088853698573 	  Loss: 1.6539285135474575 	 Accuracy: 0.3116036505867014
Delta: 0.0017729533713862363 	  Loss: 1.6538030387897857 	 Accuracy: 0.3116036505867014
Delta: 0.00445211919759973 	  Loss: 1.653546901000908 	 Accuracy: 0.3155149934810952
Delta: 0.004175532720932099 	  Loss: 1.653791723046227 	 Accuracy: 0.3089960886571056
Delta: 0.0035920250405798585 	  Loss: 1.6539366561160551 	 Accuracy: 0.31029986962190353
Delta: 0.0016260332730022307 	  Loss: 1.6538004535177464 	 Accuracy: 0.3116036505867014
Delta: 5.0513400473313456e-05 	  Loss: 1.6537865199569959 	 Accuracy: 0.31029986962190353
Delta: 0.0005736582002555996 	  Loss: 1.6536919812660966 	 Accuracy: 0.31029986962190353
Delta: 0.0039400353322754 	  Loss: 1.653464047366712 	 Accuracy: 0.3116036505867014
Delta: 0.0014976836358308087 	  Loss: 1.6535239157947015 	 Accuracy: 0.31029986962190353
Delta: 0.003807098825761566 	  Loss: 1.6534030746737072 	 Accuracy: 0.3076923076923077
Delta: 0.003002568064816217 	  Loss: 1.653389212925458 	 Accuracy: 0.3116036505867014
Delta: 0.0005126738801694801 	  Loss: 1.6533435520290074 	 Accuracy: 0.3116036505867014
Delta: 0.0014748368022961507 	  Loss: 1.6535188666787963 	 Accuracy: 0.3116036505867014
Delta: 0.0017776687620429633 	  Loss: 1.6533438647616217 	 Accuracy: 0.3116036505867014
Delta: 2.614749127701691e-06 	  Loss: 1.6533418411699348 	 Accuracy: 0.3076923076923077
Delta: 3.0691333214406806e-05 	  Loss: 1.6532653529074997 	 Accuracy: 0.31290743155149936
Delta: 0.0007457155410634388 	  Loss: 1.653447871411377 	 Accuracy: 0.32073011734028684
Delta: 0.004363751839016348 	  Loss: 1.652948468637327 	 Accuracy: 0.3116036505867014
Delta: 0.001890288533286053 	  Loss: 1.6534888981160967 	 Accuracy: 0.31290743155149936
Delta: 0.0019194694158417005 	  Loss: 1.6535081116915964 	 Accuracy: 0.31290743155149936
Delta: 0.0034723646366389914 	  Loss: 1.6533038740660193 	 Accuracy: 0.31290743155149936
Delta: 0.002705649409453977 	  Loss: 1.6532755849688323 	 Accuracy: 0.31290743155149936
Delta: 0.0006174512060049911 	  Loss: 1.6532774823371932 	 Accuracy: 0.31421121251629724
Delta: 0.0015608730672318797 	  Loss: 1.6532793297156176 	 Accuracy: 0.31290743155149936
Delta: 0.0008705070028248695 	  Loss: 1.6535214172070412 	 Accuracy: 0.3155149934810952
Delta: 9.718685157785203e-05 	  Loss: 1.653268108518036 	 Accuracy: 0.31421121251629724
Delta: 1.7099716864318276e-05 	  Loss: 1.6533022627981904 	 Accuracy: 0.31290743155149936
Delta: 1.6800366561813657e-05 	  Loss: 1.6532699235579464 	 Accuracy: 0.31290743155149936
Delta: 2.7152062926464478e-08 	  Loss: 1.6532699448710082 	 Accuracy: 0.31290743155149936
converged at iter  92
Delta: 0.020867320401941558 	  Loss: 2.1589667606723464 	 Accuracy: 0.23989569752281617
Delta: 0.019078266362330905 	  Loss: 2.038891177631808 	 Accuracy: 0.24902216427640156
Delta: 0.018120074319711514 	  Loss: 1.8228203784695625 	 Accuracy: 0.30638852672750977
Delta: 0.016378098626973304 	  Loss: 1.6885938122420026 	 Accuracy: 0.29595827900912647
Delta: 0.01354858184221128 	  Loss: 1.649868142973237 	 Accuracy: 0.2894393741851369

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010290670623583003 	  Loss: 1.6402957629430168 	 Accuracy: 0.288135593220339
Delta: 0.007108352420140841 	  Loss: 1.6391664736926261 	 Accuracy: 0.28552803129074317
Delta: 0.00522829189677462 	  Loss: 1.6385617420893626 	 Accuracy: 0.28552803129074317
Delta: 0.0016677274604545054 	  Loss: 1.6383701416013166 	 Accuracy: 0.28683181225554105
Delta: 0.003493699701187794 	  Loss: 1.6383083083078014 	 Accuracy: 0.28552803129074317
Delta: 0.0026332272651859324 	  Loss: 1.638300732257799 	 Accuracy: 0.2816166883963494
Delta: 0.002000990860190533 	  Loss: 1.6383492065367313 	 Accuracy: 0.2842242503259452
Delta: 0.0019174911883110227 	  Loss: 1.6385516768303274 	 Accuracy: 0.28683181225554105
Delta: 0.001211369646284864 	  Loss: 1.638191628418531 	 Accuracy: 0.2842242503259452
Delta: 6.330361073158854e-05 	  Loss: 1.6381125318429204 	 Accuracy: 0.288135593220339
Delta: 2.137406519424479e-05 	  Loss: 1.6381966751865942 	 Accuracy: 0.28683181225554105
Delta: 0.001299849517198983 	  Loss: 1.6382797533091464 	 Accuracy: 0.28683181225554105
Delta: 0.0005174147985543347 	  Loss: 1.6382238339835982 	 Accuracy: 0.28683181225554105
Delta: 0.0005070815120447859 	  Loss: 1.6381745215785695 	 Accuracy: 0.28683181225554105
Delta: 0.0034775117312300626 	  Loss: 1.6383954793251823 	 Accuracy: 0.28683181225554105
Delta: 0.0029864446060622954 	  Loss: 1.638058217624877 	 Accuracy: 0.28552803129074317
Delta: 0.0026955016560718348 	  Loss: 1.6378204030415198 	 Accuracy: 0.288135593220339
Delta: 0.003046113026172222 	  Loss: 1.6377416672887128 	 Accuracy: 0.288135593220339
Delta: 1.5348615132189393e-05 	  Loss: 1.6377688417111167 	 Accuracy: 0.2842242503259452
Delta: 0.0022941332564491235 	  Loss: 1.6376258594849662 	 Accuracy: 0.28683181225554105
Delta: 0.0021573883792851967 	  Loss: 1.6377888250958166 	 Accuracy: 0.288135593220339
Delta: 2.8665920741152664e-05 	  Loss: 1.6378313562477067 	 Accuracy: 0.2907431551499348
Delta: 0.0008264778497609098 	  Loss: 1.6376448996282962 	 Accuracy: 0.288135593220339
Delta: 1.6063445654648938e-06 	  Loss: 1.637648243517288 	 Accuracy: 0.28683181225554105
Delta: 4.006045583015589e-05 	  Loss: 1.637640699884297 	 Accuracy: 0.29726205997392435
Delta: 4.053423235356944e-05 	  Loss: 1.6376440140975848 	 Accuracy: 0.2894393741851369
Delta: 0.0020662459843273024 	  Loss: 1.637560911036506 	 Accuracy: 0.288135593220339
Delta: 8.084348282172556e-06 	  Loss: 1.6375633203712825 	 Accuracy: 0.2894393741851369
Delta: 0.002361770148411456 	  Loss: 1.6374270088719214 	 Accuracy: 0.28683181225554105
Delta: 5.817424894741118e-05 	  Loss: 1.6375564887604717 	 Accuracy: 0.288135593220339
Delta: 0.0016052064386185986 	  Loss: 1.6376506504535562 	 Accuracy: 0.28683181225554105
Delta: 0.004750396565250275 	  Loss: 1.6387516996650855 	 Accuracy: 0.2907431551499348
Delta: 0.0034178565619608636 	  Loss: 1.6376496216606629 	 Accuracy: 0.288135593220339
Delta: 0.0033841962554021386 	  Loss: 1.6380800001110303 	 Accuracy: 0.28552803129074317
Delta: 0.0006277348090995709 	  Loss: 1.6380945044252129 	 Accuracy: 0.2894393741851369
Delta: 2.8621971592383986e-05 	  Loss: 1.638003037329864 	 Accuracy: 0.288135593220339
Delta: 0.006624953754560677 	  Loss: 1.6390811642544834 	 Accuracy: 0.29726205997392435
Delta: 0.006566450579377794 	  Loss: 1.6377966523476983 	 Accuracy: 0.29335071707953064
Delta: 0.003991217453468959 	  Loss: 1.6384773179626713 	 Accuracy: 0.29465449804432853
Delta: 0.003434852381265022 	  Loss: 1.6376039684419716 	 Accuracy: 0.29465449804432853
Delta: 0.0033949095070103345 	  Loss: 1.6374836545825857 	 Accuracy: 0.29595827900912647
Delta: 0.0025568715021241605 	  Loss: 1.6374718673088005 	 Accuracy: 0.29465449804432853
Delta: 0.0004983791521300262 	  Loss: 1.6375012694529625 	 Accuracy: 0.29465449804432853
Delta: 0.0018370683244663289 	  Loss: 1.6374935085074398 	 Accuracy: 0.29465449804432853
Delta: 1.04580973532939e-05 	  Loss: 1.6375084404681486 	 Accuracy: 0.28683181225554105
Delta: 0.004333059365340763 	  Loss: 1.637420796615289 	 Accuracy: 0.2920469361147327
Delta: 0.005249306885152299 	  Loss: 1.6381571609943553 	 Accuracy: 0.29335071707953064
Delta: 0.00574189320333294 	  Loss: 1.637121239793221 	 Accuracy: 0.29986962190352023
Delta: 0.005934649163028603 	  Loss: 1.638143286007208 	 Accuracy: 0.29595827900912647
Delta: 0.0027142409789849883 	  Loss: 1.637509082226901 	 Accuracy: 0.29595827900912647
Delta: 0.005745752009264799 	  Loss: 1.6370414325074814 	 Accuracy: 0.29465449804432853
Delta: 0.005192879031270822 	  Loss: 1.63727313786853 	 Accuracy: 0.29335071707953064
Delta: 0.005106054187962817 	  Loss: 1.6377697776946127 	 Accuracy: 0.29465449804432853
Delta: 0.0010261763645654214 	  Loss: 1.6378172577868677 	 Accuracy: 0.28683181225554105
Delta: 0.0012728939623595581 	  Loss: 1.637839952080574 	 Accuracy: 0.29465449804432853
Delta: 2.0933874005495972e-05 	  Loss: 1.6378224487152084 	 Accuracy: 0.2894393741851369
Delta: 0.004280511335654276 	  Loss: 1.638734185960641 	 Accuracy: 0.29465449804432853
Delta: 0.0023136308643198077 	  Loss: 1.638473748111164 	 Accuracy: 0.29465449804432853
Delta: 0.0028408543157596756 	  Loss: 1.6386958537298804 	 Accuracy: 0.2907431551499348
Delta: 0.0029171902220507953 	  Loss: 1.6391145637619755 	 Accuracy: 0.29335071707953064
Delta: 0.0005718554636019656 	  Loss: 1.638741204870226 	 Accuracy: 0.29335071707953064
Delta: 0.0026788974091553385 	  Loss: 1.638458516008209 	 Accuracy: 0.29465449804432853
Delta: 0.0007337881375841773 	  Loss: 1.6383633649402065 	 Accuracy: 0.2894393741851369
Delta: 0.0030725747595612973 	  Loss: 1.6381505286787705 	 Accuracy: 0.29595827900912647
Delta: 0.0034566869876814367 	  Loss: 1.6378670922570595 	 Accuracy: 0.29465449804432853
Delta: 0.0010714051487601688 	  Loss: 1.6379622247099164 	 Accuracy: 0.29595827900912647
Delta: 0.004688484059288304 	  Loss: 1.6378769108929567 	 Accuracy: 0.29465449804432853
Delta: 0.005020196789457594 	  Loss: 1.6383694027867692 	 Accuracy: 0.2985658409387223
Delta: 0.004949689682648996 	  Loss: 1.6369458455753025 	 Accuracy: 0.2985658409387223
Delta: 0.0005122621357324794 	  Loss: 1.6369481595747766 	 Accuracy: 0.29595827900912647
Delta: 0.004916814542023883 	  Loss: 1.637524325275633 	 Accuracy: 0.29595827900912647
Delta: 0.0019516348873251047 	  Loss: 1.6378629015821864 	 Accuracy: 0.29595827900912647
Delta: 0.004558657170532713 	  Loss: 1.6378368359348832 	 Accuracy: 0.29726205997392435
Delta: 0.003679113236048846 	  Loss: 1.6381524571765198 	 Accuracy: 0.29595827900912647
Delta: 0.002161137492096918 	  Loss: 1.638219807767047 	 Accuracy: 0.29595827900912647
Delta: 0.0007386570911581956 	  Loss: 1.6382940879563206 	 Accuracy: 0.29595827900912647
Delta: 0.001904094565039851 	  Loss: 1.6382113918745485 	 Accuracy: 0.29595827900912647
Delta: 3.1938937297043206e-06 	  Loss: 1.6382020252202625 	 Accuracy: 0.29595827900912647
Delta: 2.747052658019726e-05 	  Loss: 1.6382948396117163 	 Accuracy: 0.29595827900912647
Delta: 2.762756185336015e-05 	  Loss: 1.6381908427938208 	 Accuracy: 0.29595827900912647
Delta: 3.0496351549780866e-06 	  Loss: 1.6382024541309343 	 Accuracy: 0.30638852672750977
Delta: 0.0034335541289181467 	  Loss: 1.638632135358399 	 Accuracy: 0.29465449804432853
Delta: 0.0007918275123013361 	  Loss: 1.6385771178871895 	 Accuracy: 0.29465449804432853
Delta: 0.0006163446067464861 	  Loss: 1.6385210895057922 	 Accuracy: 0.29465449804432853
Delta: 1.7079527675609546e-06 	  Loss: 1.638520527528038 	 Accuracy: 0.29726205997392435
Delta: 0.0032388803218040643 	  Loss: 1.6383996002236703 	 Accuracy: 0.29595827900912647
Delta: 0.002066084307468152 	  Loss: 1.6386632118411928 	 Accuracy: 0.29335071707953064
Delta: 0.003765520435011762 	  Loss: 1.6387764872276975 	 Accuracy: 0.29465449804432853
Delta: 0.004505477313873059 	  Loss: 1.6394571367574664 	 Accuracy: 0.29465449804432853
Delta: 0.0010012697751721953 	  Loss: 1.639454272130945 	 Accuracy: 0.29465449804432853
Delta: 1.3654483498930528e-07 	  Loss: 1.6394542587887573 	 Accuracy: 0.29595827900912647
converged at iter  95
Delta: 0.021033977879541595 	  Loss: 2.1575540057666904 	 Accuracy: 0.2046936114732725
Delta: 0.019302827549100586 	  Loss: 2.0288395809051822 	 Accuracy: 0.1981747066492829
Delta: 0.018692115437257965 	  Loss: 1.7757486451924143 	 Accuracy: 0.2255541069100391
Delta: 0.015222251769162773 	  Loss: 1.6403248014006122 	 Accuracy: 0.21642764015645372
Delta: 0.010128234870136395 	  Loss: 1.6193872592358731 	 Accuracy: 0.2255541069100391

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0072750019953801625 	  Loss: 1.6173952351767342 	 Accuracy: 0.2242503259452412
Delta: 0.005588696305382787 	  Loss: 1.6167256322034222 	 Accuracy: 0.22164276401564537
Delta: 0.003524788553600105 	  Loss: 1.6165854208424273 	 Accuracy: 0.22033898305084745
Delta: 0.00434360462237714 	  Loss: 1.6165508884620463 	 Accuracy: 0.22294654498044328
Delta: 0.0030048608520900234 	  Loss: 1.6166277887512257 	 Accuracy: 0.22033898305084745
Delta: 0.0017471500768528757 	  Loss: 1.6166233856460521 	 Accuracy: 0.22164276401564537
Delta: 0.0013583905050907122 	  Loss: 1.616674856536372 	 Accuracy: 0.22164276401564537
Delta: 0.0017465602818874902 	  Loss: 1.616758284217174 	 Accuracy: 0.22033898305084745
Delta: 0.0028513064426812776 	  Loss: 1.6169847388601641 	 Accuracy: 0.22164276401564537
Delta: 0.0019248529233029342 	  Loss: 1.6172518266701725 	 Accuracy: 0.22294654498044328
Delta: 0.001298327037648014 	  Loss: 1.6173947843992973 	 Accuracy: 0.22294654498044328
Delta: 0.0009844093178609735 	  Loss: 1.6173964121518183 	 Accuracy: 0.22033898305084745
Delta: 5.57179576318475e-05 	  Loss: 1.6172457305012702 	 Accuracy: 0.22033898305084745
Delta: 5.5642639769018605e-05 	  Loss: 1.6173971856420768 	 Accuracy: 0.21903520208604954
Delta: 0.0018889556946291928 	  Loss: 1.617329235472726 	 Accuracy: 0.22033898305084745
Delta: 5.038863112492838e-05 	  Loss: 1.6174756680827915 	 Accuracy: 0.22033898305084745
Delta: 3.9562148843994006e-05 	  Loss: 1.617459848534036 	 Accuracy: 0.22033898305084745
Delta: 1.0038740812172038e-05 	  Loss: 1.6173962662799397 	 Accuracy: 0.22033898305084745
Delta: 0.0020611290733437205 	  Loss: 1.61754136534971 	 Accuracy: 0.22294654498044328
Delta: 0.0015921463908879054 	  Loss: 1.6173912765308323 	 Accuracy: 0.22164276401564537
Delta: 0.0015024953267430514 	  Loss: 1.6175859850963983 	 Accuracy: 0.22294654498044328
Delta: 3.7667320315977536e-05 	  Loss: 1.617393841879712 	 Accuracy: 0.22033898305084745
Delta: 3.936975036116124e-05 	  Loss: 1.617532744946652 	 Accuracy: 0.22294654498044328
Delta: 3.9326429293368834e-05 	  Loss: 1.6173920619406985 	 Accuracy: 0.22033898305084745
Delta: 2.1849596361521167e-07 	  Loss: 1.6173932103748703 	 Accuracy: 0.22294654498044328
Delta: 1.1270722154673817e-05 	  Loss: 1.6173981545295024 	 Accuracy: 0.22033898305084745
Delta: 3.440629549843791e-05 	  Loss: 1.6175335731759681 	 Accuracy: 0.22294654498044328
Delta: 0.004217413721243008 	  Loss: 1.6181382637659754 	 Accuracy: 0.22164276401564537
Delta: 0.003158395634904643 	  Loss: 1.618310112449771 	 Accuracy: 0.22164276401564537
Delta: 0.0034244109229234192 	  Loss: 1.618540652796663 	 Accuracy: 0.22164276401564537
Delta: 0.0037766678298481963 	  Loss: 1.6183699983969322 	 Accuracy: 0.22164276401564537
Delta: 0.0016113065730952033 	  Loss: 1.6180677302715407 	 Accuracy: 0.22033898305084745
Delta: 0.0019230059177208843 	  Loss: 1.618039498714428 	 Accuracy: 0.22033898305084745
Delta: 0.0008989465749771673 	  Loss: 1.6182058402975543 	 Accuracy: 0.21903520208604954
Delta: 0.0028590269947216195 	  Loss: 1.6181663067481953 	 Accuracy: 0.22033898305084745
Delta: 0.0014699724576951363 	  Loss: 1.6183719371156462 	 Accuracy: 0.22033898305084745
Delta: 0.0005990879189669081 	  Loss: 1.618242266964342 	 Accuracy: 0.21903520208604954
Delta: 0.0013636259028508074 	  Loss: 1.618081008093815 	 Accuracy: 0.21773142112125163
Delta: 0.002985475071523956 	  Loss: 1.6183854622645129 	 Accuracy: 0.22033898305084745
Delta: 0.0020510326654019635 	  Loss: 1.6182343136892339 	 Accuracy: 0.22033898305084745
Delta: 0.001796731036268091 	  Loss: 1.6180009365285914 	 Accuracy: 0.22294654498044328
Delta: 0.0018800121181280656 	  Loss: 1.6179660387787744 	 Accuracy: 0.22033898305084745
Delta: 0.002717647095990103 	  Loss: 1.6181552896676934 	 Accuracy: 0.22033898305084745
Delta: 0.0018201491794759609 	  Loss: 1.6182274373211607 	 Accuracy: 0.22033898305084745
Delta: 0.002173947328510204 	  Loss: 1.618316939958178 	 Accuracy: 0.2138200782268579
Delta: 0.003589792513016969 	  Loss: 1.6177194742149343 	 Accuracy: 0.21773142112125163
Delta: 0.003075904445639547 	  Loss: 1.6183714989337639 	 Accuracy: 0.21903520208604954
Delta: 0.002803246974203356 	  Loss: 1.6185365593763006 	 Accuracy: 0.21773142112125163
Delta: 0.003969391088233867 	  Loss: 1.6177404104653696 	 Accuracy: 0.21903520208604954
Delta: 0.0021631982417178027 	  Loss: 1.617737944100893 	 Accuracy: 0.21903520208604954
Delta: 0.002329612956489608 	  Loss: 1.6180518595496116 	 Accuracy: 0.21773142112125163
Delta: 0.0035770126121038768 	  Loss: 1.6177676680695958 	 Accuracy: 0.21773142112125163
Delta: 0.0016182312272073895 	  Loss: 1.6177011503508032 	 Accuracy: 0.21903520208604954
Delta: 0.0022616053443798613 	  Loss: 1.6177423076728652 	 Accuracy: 0.21903520208604954
Delta: 0.00316989054261796 	  Loss: 1.6171330005890874 	 Accuracy: 0.21903520208604954
Delta: 5.5236277272244835e-05 	  Loss: 1.6171352651488995 	 Accuracy: 0.21642764015645372
Delta: 0.003912289479306582 	  Loss: 1.6176066545960763 	 Accuracy: 0.21773142112125163
Delta: 0.0005352805152473825 	  Loss: 1.6175965729865185 	 Accuracy: 0.21773142112125163
Delta: 0.0023046672959505785 	  Loss: 1.6178378725472173 	 Accuracy: 0.21773142112125163
Delta: 0.0016675393676488263 	  Loss: 1.6176978263862851 	 Accuracy: 0.21642764015645372
Delta: 0.0041555748830079614 	  Loss: 1.6172346094535033 	 Accuracy: 0.21903520208604954
Delta: 0.0035950501788848395 	  Loss: 1.6179454453394653 	 Accuracy: 0.21773142112125163
Delta: 0.0017925610486647927 	  Loss: 1.6174552233020834 	 Accuracy: 0.22294654498044328
Delta: 0.004181410252566946 	  Loss: 1.6191262263276032 	 Accuracy: 0.22033898305084745
Delta: 0.0038122635026502606 	  Loss: 1.6177321891071115 	 Accuracy: 0.21903520208604954
Delta: 0.002350714751749093 	  Loss: 1.6177704913649267 	 Accuracy: 0.21903520208604954
Delta: 0.00265956782603398 	  Loss: 1.617589293579457 	 Accuracy: 0.21903520208604954
Delta: 0.00302919716245983 	  Loss: 1.6178696552910115 	 Accuracy: 0.21903520208604954
Delta: 0.0028317386456576253 	  Loss: 1.6180238471992943 	 Accuracy: 0.21903520208604954
Delta: 0.0031834292703115177 	  Loss: 1.6179380290415535 	 Accuracy: 0.21903520208604954
Delta: 0.0024531781779214 	  Loss: 1.6179388717739154 	 Accuracy: 0.21903520208604954
Delta: 0.002238060171727845 	  Loss: 1.618147364460924 	 Accuracy: 0.21773142112125163
Delta: 0.000892202546289712 	  Loss: 1.6180895418037087 	 Accuracy: 0.21773142112125163
Delta: 0.0007689044101833258 	  Loss: 1.6178354034031572 	 Accuracy: 0.21773142112125163
Delta: 0.002687836768420818 	  Loss: 1.617448373871869 	 Accuracy: 0.2151238591916558
Delta: 0.003864899243366051 	  Loss: 1.61717666906492 	 Accuracy: 0.21642764015645372
Delta: 0.0023673546244592308 	  Loss: 1.6166818077304428 	 Accuracy: 0.22164276401564537
Delta: 0.004778610581411592 	  Loss: 1.6198017331952268 	 Accuracy: 0.21642764015645372
Delta: 0.00580197010303315 	  Loss: 1.6191224716647161 	 Accuracy: 0.21642764015645372
Delta: 0.005397616884928795 	  Loss: 1.619439578373252 	 Accuracy: 0.21773142112125163
Delta: 0.0048887124231969 	  Loss: 1.6191396292525255 	 Accuracy: 0.22033898305084745
Delta: 0.002720949967102493 	  Loss: 1.6189225147007749 	 Accuracy: 0.21903520208604954
Delta: 0.004124662520984687 	  Loss: 1.6190568215513759 	 Accuracy: 0.21903520208604954
Delta: 0.002512567962306696 	  Loss: 1.6191614450850575 	 Accuracy: 0.21903520208604954
Delta: 0.0033260455331766982 	  Loss: 1.6192460353416642 	 Accuracy: 0.21903520208604954
Delta: 0.0023033333243774696 	  Loss: 1.6193629708972068 	 Accuracy: 0.21903520208604954
Delta: 1.210291801431316e-05 	  Loss: 1.6193742120929802 	 Accuracy: 0.21903520208604954
Delta: 0.004643019068540067 	  Loss: 1.61964801276295 	 Accuracy: 0.21903520208604954
Delta: 8.70582424303514e-05 	  Loss: 1.619484438487171 	 Accuracy: 0.21903520208604954
Delta: 0.0030173958874567808 	  Loss: 1.6193689387882109 	 Accuracy: 0.22033898305084745
Delta: 0.004285611143110942 	  Loss: 1.6192954855311903 	 Accuracy: 0.21903520208604954
Delta: 0.003826412936996656 	  Loss: 1.620332833768933 	 Accuracy: 0.22033898305084745
Delta: 0.004188316565560028 	  Loss: 1.6190964927457039 	 Accuracy: 0.21903520208604954
Delta: 0.004749902452121112 	  Loss: 1.6189943473505175 	 Accuracy: 0.21903520208604954
Delta: 0.0036026545429756153 	  Loss: 1.6190044887951975 	 Accuracy: 0.21773142112125163
Delta: 0.020978425598082426 	  Loss: 2.1584903857000817 	 Accuracy: 0.20208604954367665
Delta: 0.01822501182335624 	  Loss: 2.0842056665368176 	 Accuracy: 0.2685788787483703
Delta: 0.016444514451393392 	  Loss: 1.9811494002783685 	 Accuracy: 0.24511082138200782
Delta: 0.014227684575916067 	  Loss: 1.8799296874842786 	 Accuracy: 0.21251629726205998
Delta: 0.01245749932096113 	  Loss: 1.8046803993649996 	 Accuracy: 0.20860495436766624
Delta: 0.010865307368230147 	  Loss: 1.7515532124971083 	 Accuracy: 0.20599739243807041
Delta: 0.010356628404604457 	  Loss: 1.7121212234063958 	 Accuracy: 0.2033898305084746
Delta: 0.009858599679989689 	  Loss: 1.6810208834286082 	 Accuracy: 0.20208604954367665
Delta: 0.008819881238224749 	  Loss: 1.656047881791482 	 Accuracy: 0.19947848761408082
Delta: 0.00827404312579839 	  Loss: 1.636759604857884 	 Accuracy: 0.19556714471968709
Delta: 0.006912987139745157 	  Loss: 1.6229632636006444 	 Accuracy: 0.19426336375488917
Delta: 0.007372247735912201 	  Loss: 1.61307525656032 	 Accuracy: 0.19426336375488917
Delta: 0.00598594220830174 	  Loss: 1.605474463965269 	 Accuracy: 0.19947848761408082
Delta: 0.005770305382792742 	  Loss: 1.5999006494205756 	 Accuracy: 0.1981747066492829
Delta: 0.004751787024697475 	  Loss: 1.5954866379642352 	 Accuracy: 0.196870925684485
Delta: 0.0045044665846136105 	  Loss: 1.5920705698311175 	 Accuracy: 0.1981747066492829
Delta: 0.004747726410614341 	  Loss: 1.5894333785669552 	 Accuracy: 0.19947848761408082
Delta: 0.005309868397893441 	  Loss: 1.5870827187402714 	 Accuracy: 0.20078226857887874
Delta: 0.005155631342761633 	  Loss: 1.5853518548676018 	 Accuracy: 0.20208604954367665
Delta: 0.004876498016080232 	  Loss: 1.5840724540704763 	 Accuracy: 0.19947848761408082
Delta: 0.004417296739306801 	  Loss: 1.582616160710205 	 Accuracy: 0.19947848761408082
Delta: 0.0036960665182175756 	  Loss: 1.581639100990215 	 Accuracy: 0.2033898305084746
Delta: 0.005136872236536262 	  Loss: 1.5803500208199324 	 Accuracy: 0.2033898305084746
Delta: 0.0038484001385178076 	  Loss: 1.5796246495924189 	 Accuracy: 0.20078226857887874
Delta: 0.003621449877319032 	  Loss: 1.5788269269040547 	 Accuracy: 0.1981747066492829
Delta: 0.003689820791550013 	  Loss: 1.5780138488295616 	 Accuracy: 0.19947848761408082
Delta: 0.0030859187781653546 	  Loss: 1.5774212640961007 	 Accuracy: 0.19947848761408082
Delta: 0.003952937610746507 	  Loss: 1.5768598340367834 	 Accuracy: 0.1981747066492829
Delta: 0.003642413105683743 	  Loss: 1.5763485530066788 	 Accuracy: 0.20078226857887874
Delta: 0.00338253729027255 	  Loss: 1.5758488292006763 	 Accuracy: 0.19947848761408082
Delta: 0.0010425139692530243 	  Loss: 1.5754534035997545 	 Accuracy: 0.19947848761408082

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0031374840868466053 	  Loss: 1.5750724709526143 	 Accuracy: 0.20078226857887874
Delta: 0.0045481944381774485 	  Loss: 1.5748296456931676 	 Accuracy: 0.19947848761408082
Delta: 0.0028229995795211907 	  Loss: 1.5744108863946158 	 Accuracy: 0.20078226857887874
Delta: 0.004421258805706091 	  Loss: 1.5741119035624704 	 Accuracy: 0.20078226857887874
Delta: 0.004025809434294766 	  Loss: 1.5736751722943887 	 Accuracy: 0.19947848761408082
Delta: 0.003857864793408405 	  Loss: 1.5737094728030139 	 Accuracy: 0.19426336375488917
Delta: 0.003248780916165267 	  Loss: 1.5734064128400815 	 Accuracy: 0.196870925684485
Delta: 0.0015125602019478862 	  Loss: 1.573187893164925 	 Accuracy: 0.19947848761408082
Delta: 0.0019754891074673605 	  Loss: 1.573121427989387 	 Accuracy: 0.19556714471968709
Delta: 0.003458357154023325 	  Loss: 1.5730156501826817 	 Accuracy: 0.19556714471968709
Delta: 0.001024200465791245 	  Loss: 1.5727841750379101 	 Accuracy: 0.196870925684485
Delta: 0.004065894135692721 	  Loss: 1.5726899035717135 	 Accuracy: 0.19947848761408082
Delta: 0.0019256059978058284 	  Loss: 1.572516470525737 	 Accuracy: 0.1981747066492829
Delta: 0.003109234226535785 	  Loss: 1.572384485133273 	 Accuracy: 0.1981747066492829
Delta: 0.0026055130590578917 	  Loss: 1.5722827588438968 	 Accuracy: 0.1981747066492829
Delta: 0.002594239234698678 	  Loss: 1.5721060921506451 	 Accuracy: 0.19556714471968709
Delta: 0.0020241374284789572 	  Loss: 1.5719491633533362 	 Accuracy: 0.196870925684485
Delta: 0.0018056539683065174 	  Loss: 1.5718004542895816 	 Accuracy: 0.196870925684485
Delta: 0.001641692966866129 	  Loss: 1.5717191456221813 	 Accuracy: 0.1981747066492829
Delta: 0.002981485947889078 	  Loss: 1.5716508016305633 	 Accuracy: 0.1981747066492829
Delta: 0.0017581266348470363 	  Loss: 1.5715344226076942 	 Accuracy: 0.1981747066492829
Delta: 0.0030366488885704896 	  Loss: 1.5714616998836697 	 Accuracy: 0.196870925684485
Delta: 0.0005509602047454108 	  Loss: 1.5713530706062875 	 Accuracy: 0.196870925684485
Delta: 4.2628007542138015e-05 	  Loss: 1.5713244628657907 	 Accuracy: 0.196870925684485
Delta: 0.002193004071208334 	  Loss: 1.5712693100080988 	 Accuracy: 0.196870925684485
Delta: 0.002127308661698932 	  Loss: 1.571140991683273 	 Accuracy: 0.196870925684485
Delta: 0.002602237841032021 	  Loss: 1.5710837573752023 	 Accuracy: 0.196870925684485
Delta: 0.002575536378054687 	  Loss: 1.5710013588945397 	 Accuracy: 0.196870925684485
Delta: 3.173266991652392e-05 	  Loss: 1.5709649706801703 	 Accuracy: 0.196870925684485
Delta: 0.003180398713954002 	  Loss: 1.570863842504592 	 Accuracy: 0.196870925684485
Delta: 0.0029994427791590764 	  Loss: 1.5707721433612711 	 Accuracy: 0.196870925684485
Delta: 0.0014271025878189213 	  Loss: 1.5707128114502205 	 Accuracy: 0.196870925684485
Delta: 0.0037933649132158853 	  Loss: 1.5706711265465354 	 Accuracy: 0.196870925684485
Delta: 0.0016131945374492614 	  Loss: 1.570645538684777 	 Accuracy: 0.196870925684485
Delta: 0.0026839516445118367 	  Loss: 1.5706187996726644 	 Accuracy: 0.1981747066492829
Delta: 0.001526656357517076 	  Loss: 1.5705614361802656 	 Accuracy: 0.196870925684485
Delta: 0.0011213808486129446 	  Loss: 1.5704727780183476 	 Accuracy: 0.196870925684485
Delta: 0.001291961116950494 	  Loss: 1.5704637713741398 	 Accuracy: 0.196870925684485
Delta: 0.0005329127275992994 	  Loss: 1.5704348298511426 	 Accuracy: 0.196870925684485
Delta: 0.0017109373930409863 	  Loss: 1.5704381433697092 	 Accuracy: 0.196870925684485
Delta: 0.0007310306978416813 	  Loss: 1.57038530763858 	 Accuracy: 0.196870925684485
Delta: 0.00292963590338489 	  Loss: 1.5703353798774518 	 Accuracy: 0.196870925684485
Delta: 0.003504526363663896 	  Loss: 1.570300841304997 	 Accuracy: 0.196870925684485
Delta: 0.003174193139156139 	  Loss: 1.570299636723095 	 Accuracy: 0.1981747066492829
Delta: 0.002426564004478397 	  Loss: 1.570198396287483 	 Accuracy: 0.196870925684485
Delta: 0.0008249742548695989 	  Loss: 1.5701787330366421 	 Accuracy: 0.1981747066492829
Delta: 0.0010896598353819047 	  Loss: 1.5701438177995017 	 Accuracy: 0.196870925684485
Delta: 0.0018682006441176565 	  Loss: 1.570137520977114 	 Accuracy: 0.196870925684485
Delta: 0.0018480432589434565 	  Loss: 1.570159320674047 	 Accuracy: 0.196870925684485
Delta: 0.0005532313243370502 	  Loss: 1.5701286902993585 	 Accuracy: 0.196870925684485
Delta: 0.001997592790274936 	  Loss: 1.570079172730674 	 Accuracy: 0.196870925684485
Delta: 0.002145375124121418 	  Loss: 1.5700990188893098 	 Accuracy: 0.196870925684485
Delta: 0.0017523264632758342 	  Loss: 1.5700859102325775 	 Accuracy: 0.196870925684485
Delta: 0.0015203870065478677 	  Loss: 1.5700814468483097 	 Accuracy: 0.196870925684485
Delta: 0.0006207647356169407 	  Loss: 1.5700593511929566 	 Accuracy: 0.196870925684485
Delta: 0.0021705489897432396 	  Loss: 1.5700496501967078 	 Accuracy: 0.196870925684485
Delta: 0.0007964522005733677 	  Loss: 1.5700358347662753 	 Accuracy: 0.196870925684485
Delta: 0.0016741909058792994 	  Loss: 1.5700219605342416 	 Accuracy: 0.196870925684485
Delta: 3.7315739335836935e-05 	  Loss: 1.5700319065748078 	 Accuracy: 0.196870925684485
Delta: 3.913451691437001e-05 	  Loss: 1.5700213673660135 	 Accuracy: 0.196870925684485
Delta: 0.0014277399755057867 	  Loss: 1.5699954108656593 	 Accuracy: 0.196870925684485
Delta: 2.2184724566123327e-05 	  Loss: 1.5699848561946963 	 Accuracy: 0.196870925684485
Delta: 0.001950116699318237 	  Loss: 1.5699594108353394 	 Accuracy: 0.196870925684485
Delta: 0.0006376677548222379 	  Loss: 1.5699401918912423 	 Accuracy: 0.196870925684485
Delta: 2.343879019398563e-05 	  Loss: 1.569923865771257 	 Accuracy: 0.196870925684485
Delta: 0.0015653186557582084 	  Loss: 1.5699390404429343 	 Accuracy: 0.196870925684485
Delta: 0.0014561261026338136 	  Loss: 1.5699253099840385 	 Accuracy: 0.196870925684485
Delta: 0.0024549209765509636 	  Loss: 1.5699045588418774 	 Accuracy: 0.196870925684485
Delta: 0.0005214334118715826 	  Loss: 1.569886705908123 	 Accuracy: 0.196870925684485
Delta: 0.021004571261136147 	  Loss: 2.1581624555685317 	 Accuracy: 0.19295958279009126
Delta: 0.01838232574020779 	  Loss: 2.076351226202447 	 Accuracy: 0.2646675358539765
Delta: 0.01629215636849532 	  Loss: 1.963194299354036 	 Accuracy: 0.19165580182529335
Delta: 0.01436514638788743 	  Loss: 1.854198205302288 	 Accuracy: 0.1981747066492829
Delta: 0.012013295960334779 	  Loss: 1.7740511495285265 	 Accuracy: 0.1981747066492829
Delta: 0.011040848008177262 	  Loss: 1.7215813119950134 	 Accuracy: 0.2033898305084746
Delta: 0.01035700483963747 	  Loss: 1.6868691120094268 	 Accuracy: 0.20208604954367665
Delta: 0.010312901373291581 	  Loss: 1.6611115654703346 	 Accuracy: 0.1981747066492829
Delta: 0.010243722343227337 	  Loss: 1.639188846100157 	 Accuracy: 0.19426336375488917
Delta: 0.009165299571812856 	  Loss: 1.6214493421223914 	 Accuracy: 0.19426336375488917
Delta: 0.008415144359444729 	  Loss: 1.6069219418865353 	 Accuracy: 0.19165580182529335
Delta: 0.007666765762640331 	  Loss: 1.5971265601378302 	 Accuracy: 0.19165580182529335
Delta: 0.0066480018051820345 	  Loss: 1.5894717199755815 	 Accuracy: 0.19165580182529335
Delta: 0.006342879402749156 	  Loss: 1.5843901473697852 	 Accuracy: 0.196870925684485
Delta: 0.005831391341836075 	  Loss: 1.5809797933512124 	 Accuracy: 0.19947848761408082
Delta: 0.0047685226135298665 	  Loss: 1.5786267759973551 	 Accuracy: 0.1981747066492829
Delta: 0.005359678491856666 	  Loss: 1.5768868476300095 	 Accuracy: 0.1981747066492829

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005361971293657706 	  Loss: 1.575429355762331 	 Accuracy: 0.1981747066492829
Delta: 0.0036626100533604837 	  Loss: 1.5745932622530636 	 Accuracy: 0.1981747066492829
Delta: 0.003699857859426607 	  Loss: 1.5737787188665826 	 Accuracy: 0.1981747066492829
Delta: 0.004562525037605953 	  Loss: 1.5731630095642073 	 Accuracy: 0.1981747066492829
Delta: 0.00485205789881473 	  Loss: 1.5726412875783273 	 Accuracy: 0.1981747066492829
Delta: 0.0044462166577752624 	  Loss: 1.5721539288753563 	 Accuracy: 0.1981747066492829
Delta: 0.002546741225804116 	  Loss: 1.5718785456800028 	 Accuracy: 0.1981747066492829
Delta: 0.003815383482063835 	  Loss: 1.571693558787937 	 Accuracy: 0.1981747066492829
Delta: 0.0025717678388357985 	  Loss: 1.571436570539223 	 Accuracy: 0.1981747066492829
Delta: 0.0023918923061147105 	  Loss: 1.5712638864813244 	 Accuracy: 0.1981747066492829
Delta: 0.0007442141480895103 	  Loss: 1.5711468032639866 	 Accuracy: 0.1981747066492829
Delta: 0.002354169208583559 	  Loss: 1.5710925586525684 	 Accuracy: 0.1981747066492829
Delta: 0.0026640975383824955 	  Loss: 1.5709554533654284 	 Accuracy: 0.1981747066492829
Delta: 0.0009863777462825434 	  Loss: 1.5708857634207374 	 Accuracy: 0.1981747066492829
Delta: 0.002030990177257069 	  Loss: 1.5708518498887631 	 Accuracy: 0.1981747066492829
Delta: 0.0011445383200981427 	  Loss: 1.5708154274154 	 Accuracy: 0.1981747066492829
Delta: 0.0015385774366608617 	  Loss: 1.570796874612819 	 Accuracy: 0.1981747066492829
Delta: 0.0016208395535920843 	  Loss: 1.5707638914582358 	 Accuracy: 0.1981747066492829
Delta: 0.0009304551137097255 	  Loss: 1.5707122222705032 	 Accuracy: 0.1981747066492829
Delta: 0.002440576656822738 	  Loss: 1.5707160481397229 	 Accuracy: 0.1981747066492829
Delta: 0.0007768718129729515 	  Loss: 1.5706808085283481 	 Accuracy: 0.1981747066492829
Delta: 3.05779643162372e-05 	  Loss: 1.570692289024573 	 Accuracy: 0.1981747066492829
Delta: 0.0023131573514930297 	  Loss: 1.5706950144669922 	 Accuracy: 0.1981747066492829
Delta: 0.0013303854313439275 	  Loss: 1.570635040782703 	 Accuracy: 0.1981747066492829
Delta: 5.122548544591893e-05 	  Loss: 1.5707109339179894 	 Accuracy: 0.1981747066492829
Delta: 2.7955828486967912e-05 	  Loss: 1.570704053282653 	 Accuracy: 0.1981747066492829
Delta: 3.352745572919479e-05 	  Loss: 1.5707027010767405 	 Accuracy: 0.1981747066492829
Delta: 0.0025841571098099577 	  Loss: 1.5706894759518764 	 Accuracy: 0.1981747066492829
Delta: 5.8906875768872835e-05 	  Loss: 1.5706917176144133 	 Accuracy: 0.1981747066492829
Delta: 5.1142256544764184e-05 	  Loss: 1.5706563346753009 	 Accuracy: 0.1981747066492829
Delta: 0.0026445251509784936 	  Loss: 1.5706247676453355 	 Accuracy: 0.1981747066492829
Delta: 3.2130293612092605e-05 	  Loss: 1.5705974586517075 	 Accuracy: 0.1981747066492829
Delta: 0.0009102695933719878 	  Loss: 1.5707465641823921 	 Accuracy: 0.1981747066492829
Delta: 4.624340157046233e-05 	  Loss: 1.5707785571680515 	 Accuracy: 0.1981747066492829
Delta: 4.0897300057656285e-05 	  Loss: 1.570632343654157 	 Accuracy: 0.1981747066492829
Delta: 0.0022222606406012996 	  Loss: 1.5707108421955673 	 Accuracy: 0.1981747066492829
Delta: 4.658220549377916e-05 	  Loss: 1.5707197798046197 	 Accuracy: 0.1981747066492829
Delta: 4.32293620242631e-05 	  Loss: 1.5708656916646364 	 Accuracy: 0.1981747066492829
Delta: 7.154286813604856e-05 	  Loss: 1.5707657474330616 	 Accuracy: 0.196870925684485
Delta: 6.043642167702941e-05 	  Loss: 1.5710871339468073 	 Accuracy: 0.1981747066492829
Delta: 3.612004706342989e-05 	  Loss: 1.5711268716245863 	 Accuracy: 0.1981747066492829
Delta: 0.0013310247928501509 	  Loss: 1.5707355472580258 	 Accuracy: 0.1981747066492829
Delta: 0.0016544961542980404 	  Loss: 1.57080463133263 	 Accuracy: 0.1981747066492829
Delta: 0.002613803685897022 	  Loss: 1.5702764320213258 	 Accuracy: 0.19947848761408082
Delta: 0.0022575718830618492 	  Loss: 1.5705986274251702 	 Accuracy: 0.1981747066492829
Delta: 0.0017440215148875771 	  Loss: 1.570571630230417 	 Accuracy: 0.19947848761408082
Delta: 4.867073713459575e-05 	  Loss: 1.570799085229915 	 Accuracy: 0.1981747066492829
Delta: 0.0005736243784900058 	  Loss: 1.570330534509549 	 Accuracy: 0.19947848761408082
Delta: 0.0010368311352245117 	  Loss: 1.570419928612454 	 Accuracy: 0.1981747066492829
Delta: 0.0023449971318750843 	  Loss: 1.570214233889104 	 Accuracy: 0.2046936114732725
Delta: 6.318552599075327e-05 	  Loss: 1.5703159617198597 	 Accuracy: 0.1981747066492829
Delta: 5.0109733104001974e-05 	  Loss: 1.57030056073651 	 Accuracy: 0.1981747066492829
Delta: 0.0007066721801355 	  Loss: 1.5707856285677209 	 Accuracy: 0.1981747066492829
Delta: 0.0006953948409700033 	  Loss: 1.5703963684676308 	 Accuracy: 0.1981747066492829
Delta: 8.086954579419788e-05 	  Loss: 1.570332599928276 	 Accuracy: 0.1981747066492829
Delta: 0.002085312275703071 	  Loss: 1.5704548394617266 	 Accuracy: 0.1981747066492829
Delta: 0.0021877667702514597 	  Loss: 1.5706392352411982 	 Accuracy: 0.1981747066492829
Delta: 0.0008374207076729182 	  Loss: 1.5706442402977916 	 Accuracy: 0.196870925684485
Delta: 0.0037068498431606016 	  Loss: 1.5709113550948015 	 Accuracy: 0.19947848761408082
Delta: 0.0016073995746204723 	  Loss: 1.5706855972920106 	 Accuracy: 0.1981747066492829
Delta: 0.0016947434830848704 	  Loss: 1.570846828814211 	 Accuracy: 0.19947848761408082
Delta: 0.0030629204254483287 	  Loss: 1.5708197992736035 	 Accuracy: 0.1981747066492829
Delta: 0.002151250814774849 	  Loss: 1.5706322568543412 	 Accuracy: 0.1981747066492829
Delta: 0.000775350550073508 	  Loss: 1.570709944056552 	 Accuracy: 0.1981747066492829
Delta: 0.002809508757552752 	  Loss: 1.5703964642442823 	 Accuracy: 0.19947848761408082
Delta: 0.0029096895325535638 	  Loss: 1.5701799267666727 	 Accuracy: 0.19947848761408082
Delta: 3.5147010944072404e-05 	  Loss: 1.5701299499176886 	 Accuracy: 0.19947848761408082
Delta: 0.0023453083260786245 	  Loss: 1.5699712026755819 	 Accuracy: 0.19947848761408082
Delta: 0.0018138404400116935 	  Loss: 1.5703698378685997 	 Accuracy: 0.19947848761408082
Delta: 0.0022092054370479878 	  Loss: 1.5707122458109122 	 Accuracy: 0.1981747066492829
Delta: 0.0011666306003113248 	  Loss: 1.5703090028280875 	 Accuracy: 0.19947848761408082
Delta: 0.002269569071803517 	  Loss: 1.570473603301471 	 Accuracy: 0.196870925684485
Delta: 0.0032164454528890137 	  Loss: 1.5706783810056453 	 Accuracy: 0.1981747066492829
Delta: 0.0023909768580690997 	  Loss: 1.571274967846123 	 Accuracy: 0.1981747066492829
Delta: 0.0008371174206703348 	  Loss: 1.57120191250257 	 Accuracy: 0.1981747066492829
Delta: 0.000605185153011796 	  Loss: 1.571161351842008 	 Accuracy: 0.19947848761408082
Delta: 0.004412674442832116 	  Loss: 1.5712764896425075 	 Accuracy: 0.1981747066492829
Delta: 0.0012467326528859753 	  Loss: 1.5711199454297782 	 Accuracy: 0.1981747066492829
Delta: 0.002246932775441818 	  Loss: 1.5712801131767253 	 Accuracy: 0.19947848761408082
Delta: 0.003375702164695729 	  Loss: 1.5712325964706562 	 Accuracy: 0.1981747066492829
Delta: 0.0026701751894349134 	  Loss: 1.5714148909158547 	 Accuracy: 0.20078226857887874
Delta: 0.0008210403329353097 	  Loss: 1.5711303440503324 	 Accuracy: 0.1981747066492829
Delta: 0.00011977946427395986 	  Loss: 1.571073718699617 	 Accuracy: 0.19947848761408082
Delta: 0.02106185669377143 	  Loss: 2.1572420620963957 	 Accuracy: 0.20078226857887874
Delta: 0.018006534282087438 	  Loss: 2.075651959273776 	 Accuracy: 0.2242503259452412
Delta: 0.015450361018333868 	  Loss: 1.962093938845549 	 Accuracy: 0.17861799217731422
Delta: 0.013909975421300106 	  Loss: 1.8483475949064152 	 Accuracy: 0.20078226857887874
Delta: 0.012084249572348443 	  Loss: 1.7638698260670365 	 Accuracy: 0.196870925684485
Delta: 0.010149553306416384 	  Loss: 1.7125909608111543 	 Accuracy: 0.19165580182529335
Delta: 0.009358461792435315 	  Loss: 1.684651849681016 	 Accuracy: 0.19035202086049544
Delta: 0.009790706105135891 	  Loss: 1.6666314462947076 	 Accuracy: 0.18252933507170796
Delta: 0.01038417770328684 	  Loss: 1.6513724147684528 	 Accuracy: 0.18513689700130379
Delta: 0.009663478691070797 	  Loss: 1.639420996197592 	 Accuracy: 0.19035202086049544
Delta: 0.008929116198464673 	  Loss: 1.6291235370781654 	 Accuracy: 0.19035202086049544
Delta: 0.00776003110823469 	  Loss: 1.6214949590122187 	 Accuracy: 0.19426336375488917
Delta: 0.00800149270563699 	  Loss: 1.615336745178583 	 Accuracy: 0.1981747066492829
Delta: 0.007126378047011397 	  Loss: 1.6111641651180166 	 Accuracy: 0.19947848761408082
Delta: 0.006872245920116725 	  Loss: 1.6077665991360885 	 Accuracy: 0.1981747066492829

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0059828354000612234 	  Loss: 1.606192356231081 	 Accuracy: 0.19947848761408082
Delta: 0.004623423166878514 	  Loss: 1.605550382090568 	 Accuracy: 0.20078226857887874
Delta: 0.005114127711448899 	  Loss: 1.6045481444385419 	 Accuracy: 0.20078226857887874
Delta: 0.005113500080862136 	  Loss: 1.6037051288140876 	 Accuracy: 0.20078226857887874
Delta: 0.005208636606573141 	  Loss: 1.6027128450159214 	 Accuracy: 0.20208604954367665
Delta: 0.003252607854759526 	  Loss: 1.6023260705349593 	 Accuracy: 0.2033898305084746
Delta: 0.0036620650373461066 	  Loss: 1.6019370831272015 	 Accuracy: 0.20208604954367665
Delta: 0.0035192557855817834 	  Loss: 1.6016174066641682 	 Accuracy: 0.19947848761408082
Delta: 0.0023010890106899664 	  Loss: 1.601465208776726 	 Accuracy: 0.19947848761408082
Delta: 0.0031511130268812018 	  Loss: 1.6015407142173337 	 Accuracy: 0.19947848761408082
Delta: 0.002860036349793063 	  Loss: 1.6014964147633246 	 Accuracy: 0.19947848761408082
Delta: 0.002973004879237398 	  Loss: 1.6012649694574077 	 Accuracy: 0.19947848761408082
Delta: 0.0036264157534780703 	  Loss: 1.6014938740308944 	 Accuracy: 0.19947848761408082
Delta: 0.0007849723359313402 	  Loss: 1.6012571596874647 	 Accuracy: 0.19947848761408082
Delta: 0.0017701188147332806 	  Loss: 1.6014379015857223 	 Accuracy: 0.19947848761408082
Delta: 0.0027284524882220163 	  Loss: 1.601292378112745 	 Accuracy: 0.19947848761408082
Delta: 0.0036891744298829183 	  Loss: 1.6013143368619085 	 Accuracy: 0.19947848761408082
Delta: 0.001743184095315872 	  Loss: 1.6011998332924242 	 Accuracy: 0.19947848761408082
Delta: 0.0021479603307161107 	  Loss: 1.6012326729942084 	 Accuracy: 0.19947848761408082
Delta: 0.003352392286840638 	  Loss: 1.6009731576957127 	 Accuracy: 0.19947848761408082
Delta: 6.306914931339207e-05 	  Loss: 1.6011602055235832 	 Accuracy: 0.19947848761408082
Delta: 0.000635339869841875 	  Loss: 1.6010768011620775 	 Accuracy: 0.1981747066492829
Delta: 0.002274284213248754 	  Loss: 1.6012773741463178 	 Accuracy: 0.19947848761408082
Delta: 0.0005552903140558924 	  Loss: 1.6010594095007744 	 Accuracy: 0.19947848761408082
Delta: 0.001545646637501807 	  Loss: 1.6009130965160225 	 Accuracy: 0.19947848761408082
Delta: 0.000946000291821238 	  Loss: 1.6009963963319178 	 Accuracy: 0.19947848761408082
Delta: 0.0005235752827772998 	  Loss: 1.6008469846692197 	 Accuracy: 0.19947848761408082
Delta: 0.002674118804795614 	  Loss: 1.6008134534462428 	 Accuracy: 0.19947848761408082
Delta: 0.0017229694662289807 	  Loss: 1.6007832515369347 	 Accuracy: 0.20078226857887874
Delta: 0.0028089291226345223 	  Loss: 1.6011453406322924 	 Accuracy: 0.19947848761408082
Delta: 0.001847612721771184 	  Loss: 1.6011668934457721 	 Accuracy: 0.19947848761408082
Delta: 0.0014562714004162168 	  Loss: 1.6010275538741467 	 Accuracy: 0.19947848761408082
Delta: 3.1189365075152796e-05 	  Loss: 1.6010613921513273 	 Accuracy: 0.19947848761408082
Delta: 2.2531046472641776e-05 	  Loss: 1.6010118776561304 	 Accuracy: 0.19947848761408082
Delta: 0.0008959170160887366 	  Loss: 1.6010922158748802 	 Accuracy: 0.19947848761408082
Delta: 3.1086323352440154e-05 	  Loss: 1.6011008593030178 	 Accuracy: 0.20208604954367665
Delta: 0.00175886812072002 	  Loss: 1.600820193506322 	 Accuracy: 0.1981747066492829
Delta: 0.0010060953112799456 	  Loss: 1.6010107286943431 	 Accuracy: 0.196870925684485
Delta: 0.0019148968091513494 	  Loss: 1.601175791645081 	 Accuracy: 0.19947848761408082
Delta: 0.001367575504199403 	  Loss: 1.600935495135103 	 Accuracy: 0.1981747066492829
Delta: 0.0025747012093381857 	  Loss: 1.6011229296445286 	 Accuracy: 0.19947848761408082
Delta: 0.0009977832188815526 	  Loss: 1.6009807579811133 	 Accuracy: 0.19947848761408082
Delta: 4.486363629656119e-05 	  Loss: 1.6010419657526371 	 Accuracy: 0.20208604954367665
Delta: 0.0011967526255436975 	  Loss: 1.600748738369466 	 Accuracy: 0.20078226857887874
Delta: 0.0030108863547360946 	  Loss: 1.6006110611630147 	 Accuracy: 0.19947848761408082
Delta: 0.0031942580709856836 	  Loss: 1.6002960280687166 	 Accuracy: 0.20078226857887874
Delta: 0.0019295686298606484 	  Loss: 1.6007378257223754 	 Accuracy: 0.20078226857887874
Delta: 0.00271534025733389 	  Loss: 1.6006897462391305 	 Accuracy: 0.20078226857887874
Delta: 0.0023079346086086363 	  Loss: 1.6006897226878665 	 Accuracy: 0.19947848761408082
converged at iter  63
Delta: 0.021082069774359526 	  Loss: 2.15795199331228 	 Accuracy: 0.2033898305084746
Delta: 0.018300233018959174 	  Loss: 2.072473997848999 	 Accuracy: 0.2516297262059974
Delta: 0.01611823255005424 	  Loss: 1.9463861563191154 	 Accuracy: 0.18383311603650587
Delta: 0.014428364064355631 	  Loss: 1.8300507941594746 	 Accuracy: 0.20599739243807041
Delta: 0.01264660214287879 	  Loss: 1.747283049507621 	 Accuracy: 0.20599739243807041
Delta: 0.012200097804785951 	  Loss: 1.6946574473443352 	 Accuracy: 0.2046936114732725
Delta: 0.011627530126755497 	  Loss: 1.6605637999888234 	 Accuracy: 0.19426336375488917
Delta: 0.010725662376775818 	  Loss: 1.6382950538943395 	 Accuracy: 0.19426336375488917
Delta: 0.009874908193579548 	  Loss: 1.6223723837324138 	 Accuracy: 0.19165580182529335
Delta: 0.009234436032178257 	  Loss: 1.6107911238721013 	 Accuracy: 0.19165580182529335
Delta: 0.007226751118107452 	  Loss: 1.6044145534359031 	 Accuracy: 0.19165580182529335
Delta: 0.006315826469079221 	  Loss: 1.6008558358157663 	 Accuracy: 0.18513689700130379

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005265110538636267 	  Loss: 1.5981021730378515 	 Accuracy: 0.17861799217731422
Delta: 0.0052311159440223435 	  Loss: 1.5965970327371455 	 Accuracy: 0.18122555410691005
Delta: 0.005175732857886751 	  Loss: 1.5951003615664519 	 Accuracy: 0.18513689700130379
Delta: 0.004559235906929794 	  Loss: 1.595386866624304 	 Accuracy: 0.1864406779661017
Delta: 0.004567347791445402 	  Loss: 1.5942673277641886 	 Accuracy: 0.18513689700130379
Delta: 0.003741024229902462 	  Loss: 1.5939510718703274 	 Accuracy: 0.18513689700130379
Delta: 0.004478494552533317 	  Loss: 1.593386551609692 	 Accuracy: 0.18383311603650587
Delta: 0.004350490594801181 	  Loss: 1.5929793712060796 	 Accuracy: 0.1864406779661017
Delta: 0.0024115519111308904 	  Loss: 1.5930596441992495 	 Accuracy: 0.1864406779661017
Delta: 0.0021041377995801675 	  Loss: 1.592931510655289 	 Accuracy: 0.18252933507170796
Delta: 0.002059135054986138 	  Loss: 1.5926457822097606 	 Accuracy: 0.18383311603650587
Delta: 0.0029230921234629495 	  Loss: 1.592591826614839 	 Accuracy: 0.18383311603650587
Delta: 0.0019498187149858915 	  Loss: 1.592769289283528 	 Accuracy: 0.18383311603650587
Delta: 0.0017833586613553974 	  Loss: 1.5926965626077247 	 Accuracy: 0.18383311603650587
Delta: 0.0021584252807205265 	  Loss: 1.5928083502101966 	 Accuracy: 0.18513689700130379
Delta: 0.0012764646385801713 	  Loss: 1.5928980647877142 	 Accuracy: 0.18383311603650587
Delta: 1.3977589404254185e-05 	  Loss: 1.5928291680695055 	 Accuracy: 0.18383311603650587
Delta: 0.0011208732567517844 	  Loss: 1.592838868265522 	 Accuracy: 0.18383311603650587
Delta: 0.0009661980745937468 	  Loss: 1.5927442673134546 	 Accuracy: 0.18383311603650587
Delta: 0.0024175021853916224 	  Loss: 1.592856151553339 	 Accuracy: 0.18383311603650587
Delta: 0.0029853177270264737 	  Loss: 1.592953926784209 	 Accuracy: 0.18383311603650587
Delta: 0.001778062639323 	  Loss: 1.592855749755787 	 Accuracy: 0.18383311603650587
Delta: 2.3804883047616638e-05 	  Loss: 1.592850457771419 	 Accuracy: 0.18383311603650587
Delta: 3.408610080522863e-05 	  Loss: 1.592913142826566 	 Accuracy: 0.18383311603650587
Delta: 0.001851559121140159 	  Loss: 1.5930229830229194 	 Accuracy: 0.18383311603650587
Delta: 0.000722149471180532 	  Loss: 1.5929570110077251 	 Accuracy: 0.18383311603650587
Delta: 0.0007184263281828132 	  Loss: 1.59294157538746 	 Accuracy: 0.18513689700130379
Delta: 0.0007544074360985312 	  Loss: 1.5930288312384713 	 Accuracy: 0.18383311603650587
Delta: 0.000955032137621566 	  Loss: 1.5930537034924324 	 Accuracy: 0.18383311603650587
Delta: 0.0007052378532732646 	  Loss: 1.5930155876944654 	 Accuracy: 0.18513689700130379
Delta: 2.7016108999036864e-05 	  Loss: 1.593092220249329 	 Accuracy: 0.18383311603650587
Delta: 0.0009415836053906511 	  Loss: 1.5930272552494782 	 Accuracy: 0.18513689700130379
Delta: 1.8342404750096115e-05 	  Loss: 1.5930111857986753 	 Accuracy: 0.18383311603650587
Delta: 3.495950482983791e-05 	  Loss: 1.5929575198415828 	 Accuracy: 0.19035202086049544
Delta: 0.0026645204139311212 	  Loss: 1.5929905561191324 	 Accuracy: 0.18383311603650587
Delta: 0.0028267460977887755 	  Loss: 1.5932783470724818 	 Accuracy: 0.18383311603650587
Delta: 0.0015014334638105073 	  Loss: 1.5930691334986453 	 Accuracy: 0.18383311603650587
Delta: 0.0010137235339526 	  Loss: 1.592951712110107 	 Accuracy: 0.18383311603650587
Delta: 0.0012999197541843914 	  Loss: 1.592908140058336 	 Accuracy: 0.18383311603650587
Delta: 0.0010384808564833379 	  Loss: 1.5928754101889062 	 Accuracy: 0.18383311603650587
Delta: 4.223866366088678e-05 	  Loss: 1.5931785750676983 	 Accuracy: 0.18513689700130379
Delta: 5.574004097738647e-05 	  Loss: 1.5929401364646958 	 Accuracy: 0.18383311603650587
Delta: 0.000520637387431233 	  Loss: 1.5928671622783686 	 Accuracy: 0.18383311603650587
Delta: 0.0013162861149577315 	  Loss: 1.5928610708982558 	 Accuracy: 0.18383311603650587
Delta: 0.0012491323710648958 	  Loss: 1.5926959900685165 	 Accuracy: 0.18383311603650587
Delta: 0.0007442916975372141 	  Loss: 1.5928146499461662 	 Accuracy: 0.1864406779661017
Delta: 0.002209800172494094 	  Loss: 1.5929815149466617 	 Accuracy: 0.18383311603650587
Delta: 0.0007296900275933612 	  Loss: 1.592953341076837 	 Accuracy: 0.18513689700130379
Delta: 3.325612986840757e-05 	  Loss: 1.5929258823145918 	 Accuracy: 0.18513689700130379
Delta: 0.0014695489985609349 	  Loss: 1.5927260369261087 	 Accuracy: 0.18383311603650587
Delta: 0.002167079052304104 	  Loss: 1.5927167351738074 	 Accuracy: 0.18513689700130379
Delta: 0.0015648321084861332 	  Loss: 1.593062814243348 	 Accuracy: 0.18513689700130379
Delta: 0.0019741565939282064 	  Loss: 1.5924315959171915 	 Accuracy: 0.18513689700130379
Delta: 0.0011391371492354516 	  Loss: 1.5921654896578967 	 Accuracy: 0.18383311603650587
Delta: 0.001954792623839604 	  Loss: 1.5923828964314728 	 Accuracy: 0.1864406779661017
Delta: 0.002824380366764429 	  Loss: 1.592474597115391 	 Accuracy: 0.1864406779661017
Delta: 0.001687510415414377 	  Loss: 1.5924922512822286 	 Accuracy: 0.18513689700130379
Delta: 0.001375690511514564 	  Loss: 1.5925369179460582 	 Accuracy: 0.18383311603650587
Delta: 0.0016222994699645376 	  Loss: 1.5922902404671628 	 Accuracy: 0.18252933507170796
Delta: 0.002702683209470276 	  Loss: 1.5921439911782167 	 Accuracy: 0.18383311603650587
Delta: 0.0007416060298132018 	  Loss: 1.592278060585252 	 Accuracy: 0.18383311603650587
Delta: 0.0018302990348416375 	  Loss: 1.5919090666440254 	 Accuracy: 0.18383311603650587
Delta: 0.0005564996693235156 	  Loss: 1.5922749941823762 	 Accuracy: 0.18383311603650587
Delta: 0.002559454639570271 	  Loss: 1.592555417551691 	 Accuracy: 0.18383311603650587
Delta: 0.0038460518785011517 	  Loss: 1.593975141123368 	 Accuracy: 0.18383311603650587
Delta: 0.0010125253525561932 	  Loss: 1.5934224095161111 	 Accuracy: 0.18383311603650587
Delta: 0.0038393732857910944 	  Loss: 1.593113297770583 	 Accuracy: 0.18383311603650587
Delta: 0.0017423563128208801 	  Loss: 1.5930770013774949 	 Accuracy: 0.18383311603650587
Delta: 0.0032392427217146644 	  Loss: 1.5933165491638999 	 Accuracy: 0.18383311603650587
Delta: 0.0032015003286991277 	  Loss: 1.5931274753087385 	 Accuracy: 0.18383311603650587
Delta: 0.002072108142876097 	  Loss: 1.5927756846056789 	 Accuracy: 0.18383311603650587
Delta: 0.0023122343494430607 	  Loss: 1.5926188959550482 	 Accuracy: 0.18383311603650587
Delta: 0.0019999650913865184 	  Loss: 1.5924420029348778 	 Accuracy: 0.18383311603650587
Delta: 2.3055968134397396e-05 	  Loss: 1.5924667440252183 	 Accuracy: 0.18383311603650587
Delta: 0.0027128536058118853 	  Loss: 1.5926865830854124 	 Accuracy: 0.18383311603650587
Delta: 0.0009414097067665158 	  Loss: 1.592080623689781 	 Accuracy: 0.18383311603650587
Delta: 0.00010310862441763818 	  Loss: 1.5924931801978095 	 Accuracy: 0.17861799217731422
Delta: 9.501865525652915e-05 	  Loss: 1.5920928938073682 	 Accuracy: 0.1864406779661017
Delta: 0.0034494957271840737 	  Loss: 1.5926081908673773 	 Accuracy: 0.18383311603650587
Delta: 0.0014630710913105431 	  Loss: 1.592745877335024 	 Accuracy: 0.18383311603650587
Delta: 0.0005332925466806863 	  Loss: 1.5927310403125707 	 Accuracy: 0.18383311603650587
Delta: 0.0032051659815807015 	  Loss: 1.5927922901999034 	 Accuracy: 0.18383311603650587
Delta: 0.0020121575067979934 	  Loss: 1.593264231857701 	 Accuracy: 0.18122555410691005
Delta: 0.0038471863783868894 	  Loss: 1.5940002880467463 	 Accuracy: 0.18252933507170796
Delta: 0.001175204624927496 	  Loss: 1.59386316673876 	 Accuracy: 0.18252933507170796
Delta: 0.003336898929244708 	  Loss: 1.594724096555963 	 Accuracy: 0.18252933507170796
Delta: 0.001843719523806637 	  Loss: 1.5942190922506398 	 Accuracy: 0.18383311603650587
Delta: 0.005107963883945517 	  Loss: 1.596160302958718 	 Accuracy: 0.18252933507170796
Delta: 0.020960030546264368 	  Loss: 2.1587660372658877 	 Accuracy: 0.20078226857887874
Delta: 0.01837341661099463 	  Loss: 2.0735711715665506 	 Accuracy: 0.2633637548891786
Delta: 0.016958038496293213 	  Loss: 1.9391153937074375 	 Accuracy: 0.21642764015645372
Delta: 0.014704721092841721 	  Loss: 1.808957273887159 	 Accuracy: 0.2033898305084746
Delta: 0.012816673039274754 	  Loss: 1.723001515520065 	 Accuracy: 0.2046936114732725
Delta: 0.01134974169615565 	  Loss: 1.6774110135979854 	 Accuracy: 0.2046936114732725
Delta: 0.010711954318846967 	  Loss: 1.6526189892793566 	 Accuracy: 0.19947848761408082
Delta: 0.010610542918673667 	  Loss: 1.6348852800761646 	 Accuracy: 0.20078226857887874
Delta: 0.010057970837436965 	  Loss: 1.620685707251512 	 Accuracy: 0.20599739243807041
Delta: 0.008133308374024283 	  Loss: 1.611635445213428 	 Accuracy: 0.20599739243807041

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008292750912559836 	  Loss: 1.6048864812344856 	 Accuracy: 0.20730117340286833
Delta: 0.006250277308306841 	  Loss: 1.601218467227593 	 Accuracy: 0.21121251629726207
Delta: 0.0053284436960465715 	  Loss: 1.599155443987883 	 Accuracy: 0.21121251629726207
Delta: 0.005068432938724437 	  Loss: 1.5975819547225014 	 Accuracy: 0.20730117340286833
Delta: 0.004497126753148715 	  Loss: 1.596696216046002 	 Accuracy: 0.21251629726205998
Delta: 0.004981919628820972 	  Loss: 1.595866420857173 	 Accuracy: 0.20860495436766624
Delta: 0.0032155305460133017 	  Loss: 1.5955315442225022 	 Accuracy: 0.20860495436766624
Delta: 0.003014716543471767 	  Loss: 1.5954049989576244 	 Accuracy: 0.20860495436766624
Delta: 0.0036843203002076583 	  Loss: 1.5958296043234097 	 Accuracy: 0.20730117340286833
Delta: 0.0027749248356930566 	  Loss: 1.5957247418213658 	 Accuracy: 0.20730117340286833
Delta: 0.0026377376096800337 	  Loss: 1.5957920606345561 	 Accuracy: 0.20730117340286833
Delta: 0.0019719928368227484 	  Loss: 1.5958515149091341 	 Accuracy: 0.20730117340286833
Delta: 0.0014069418584348706 	  Loss: 1.5958639987990513 	 Accuracy: 0.20860495436766624
Delta: 0.004539864139140489 	  Loss: 1.5955529434404148 	 Accuracy: 0.20860495436766624
Delta: 0.0009502972422245711 	  Loss: 1.5955014573975514 	 Accuracy: 0.20860495436766624
Delta: 0.0008053161029225727 	  Loss: 1.595351357056974 	 Accuracy: 0.20860495436766624
Delta: 0.0017567607537017217 	  Loss: 1.595757818897235 	 Accuracy: 0.20860495436766624
Delta: 0.002581179618844 	  Loss: 1.595592117636969 	 Accuracy: 0.20860495436766624
Delta: 0.0007320552146442116 	  Loss: 1.5956867022181824 	 Accuracy: 0.20860495436766624
Delta: 0.0014611546073269633 	  Loss: 1.5959104468625727 	 Accuracy: 0.20860495436766624
Delta: 0.0007418173617009094 	  Loss: 1.5957460434096638 	 Accuracy: 0.20860495436766624
Delta: 0.0028070806591169307 	  Loss: 1.595655872777684 	 Accuracy: 0.20860495436766624
Delta: 0.0015335228513696725 	  Loss: 1.595614913559524 	 Accuracy: 0.20208604954367665
Delta: 0.0018027572415519034 	  Loss: 1.5955150938343419 	 Accuracy: 0.20860495436766624
Delta: 0.0015177980773878233 	  Loss: 1.595733737848462 	 Accuracy: 0.20860495436766624
Delta: 0.0005688053374134419 	  Loss: 1.5954351517401157 	 Accuracy: 0.20860495436766624
Delta: 0.0005447856841415268 	  Loss: 1.5956408801905941 	 Accuracy: 0.20860495436766624
Delta: 0.000766722314672522 	  Loss: 1.5953563687694987 	 Accuracy: 0.20860495436766624
Delta: 0.0005151516960068882 	  Loss: 1.5952373037454406 	 Accuracy: 0.20860495436766624
Delta: 0.0014528167902534061 	  Loss: 1.5953076734510678 	 Accuracy: 0.20860495436766624
Delta: 0.0023236657791156053 	  Loss: 1.5950796737389767 	 Accuracy: 0.20860495436766624
Delta: 0.0007706686277859607 	  Loss: 1.5950052833855815 	 Accuracy: 0.20860495436766624
Delta: 0.0012362607229236694 	  Loss: 1.5955025648939039 	 Accuracy: 0.20730117340286833
Delta: 0.0008693943605289552 	  Loss: 1.595302115864083 	 Accuracy: 0.20860495436766624
Delta: 0.002681407149476787 	  Loss: 1.5955408554455048 	 Accuracy: 0.2046936114732725
Delta: 0.0025705579000849343 	  Loss: 1.59565955305695 	 Accuracy: 0.20860495436766624
Delta: 7.099738108894867e-05 	  Loss: 1.59547294576748 	 Accuracy: 0.20990873533246415
Delta: 0.000675138202207762 	  Loss: 1.5954169422495603 	 Accuracy: 0.20860495436766624
Delta: 0.0038480393573099457 	  Loss: 1.5954011970499453 	 Accuracy: 0.20860495436766624
Delta: 0.0009050962462582954 	  Loss: 1.5956109271688326 	 Accuracy: 0.20860495436766624
Delta: 0.0017793487190476908 	  Loss: 1.5951669087347817 	 Accuracy: 0.20860495436766624
Delta: 6.732633482717136e-05 	  Loss: 1.5955415489457787 	 Accuracy: 0.20860495436766624
Delta: 0.0021871794477580494 	  Loss: 1.5952060284889016 	 Accuracy: 0.19556714471968709
Delta: 0.004010597229440205 	  Loss: 1.5959715575460773 	 Accuracy: 0.20860495436766624
Delta: 0.001186820654988044 	  Loss: 1.5959745166836754 	 Accuracy: 0.20730117340286833
Delta: 0.003793359779000035 	  Loss: 1.597134905820519 	 Accuracy: 0.20860495436766624
Delta: 0.005344051731896865 	  Loss: 1.59555713010425 	 Accuracy: 0.20860495436766624
Delta: 0.0009217156121110952 	  Loss: 1.5956251965038026 	 Accuracy: 0.20860495436766624
Delta: 0.0009732220754225935 	  Loss: 1.5956904853406364 	 Accuracy: 0.20860495436766624
Delta: 0.0009215757857731696 	  Loss: 1.5959364653336654 	 Accuracy: 0.20860495436766624
Delta: 0.000964611468036828 	  Loss: 1.596026683068176 	 Accuracy: 0.20860495436766624
Delta: 3.412067237967455e-05 	  Loss: 1.5958761018993948 	 Accuracy: 0.20860495436766624
Delta: 6.070479386765499e-05 	  Loss: 1.5956406070181268 	 Accuracy: 0.20860495436766624
Delta: 0.002408393115646883 	  Loss: 1.5960838558897792 	 Accuracy: 0.20860495436766624
Delta: 0.0007498286601134815 	  Loss: 1.5958348222080265 	 Accuracy: 0.20860495436766624
Delta: 0.0016283234765962864 	  Loss: 1.5958212718995617 	 Accuracy: 0.20860495436766624
Delta: 0.002093643295537192 	  Loss: 1.5961961435602234 	 Accuracy: 0.20860495436766624
Delta: 0.001805558283676816 	  Loss: 1.5957439451139335 	 Accuracy: 0.20860495436766624
Delta: 0.005804979507368253 	  Loss: 1.5955778003437953 	 Accuracy: 0.20730117340286833
Delta: 0.002606204705800633 	  Loss: 1.595373761173477 	 Accuracy: 0.20860495436766624
Delta: 0.00477071194799454 	  Loss: 1.595463628407225 	 Accuracy: 0.20860495436766624
Delta: 0.002085960456846565 	  Loss: 1.5954352895805342 	 Accuracy: 0.21121251629726207
Delta: 6.257317772722793e-05 	  Loss: 1.5954653482138945 	 Accuracy: 0.20860495436766624
Delta: 0.0009204316821360382 	  Loss: 1.5952275052964904 	 Accuracy: 0.20730117340286833
Delta: 0.004604281929390564 	  Loss: 1.5960741269166927 	 Accuracy: 0.20860495436766624
Delta: 0.0024472541735094345 	  Loss: 1.596144770976019 	 Accuracy: 0.20860495436766624
Delta: 0.003174180167793363 	  Loss: 1.5950564393101565 	 Accuracy: 0.20860495436766624
Delta: 0.0024445478609027996 	  Loss: 1.5960880845041117 	 Accuracy: 0.20730117340286833
Delta: 0.0032691647087957146 	  Loss: 1.5959752590733414 	 Accuracy: 0.20860495436766624
Delta: 0.0027869099569407404 	  Loss: 1.596138264579884 	 Accuracy: 0.20860495436766624
Delta: 0.004698750127863389 	  Loss: 1.5944884068117533 	 Accuracy: 0.20860495436766624
Delta: 0.0037262610771130653 	  Loss: 1.5954182672720971 	 Accuracy: 0.20860495436766624
Delta: 0.002324805387616197 	  Loss: 1.5947925434127659 	 Accuracy: 0.20860495436766624
Delta: 6.703548540075473e-05 	  Loss: 1.5947130706302814 	 Accuracy: 0.20860495436766624
Delta: 0.0006865896573537436 	  Loss: 1.5949516356675597 	 Accuracy: 0.20860495436766624
Delta: 5.38452704870481e-05 	  Loss: 1.5949132096794183 	 Accuracy: 0.20860495436766624
Delta: 6.65850820126275e-05 	  Loss: 1.5949836919019758 	 Accuracy: 0.20860495436766624
Delta: 0.0001019031152132706 	  Loss: 1.5948407925949848 	 Accuracy: 0.20860495436766624
Delta: 4.476309948335987e-05 	  Loss: 1.5948487726104092 	 Accuracy: 0.20860495436766624
Delta: 0.0006630004318005135 	  Loss: 1.594840351749379 	 Accuracy: 0.20860495436766624
Delta: 0.0006516514862362784 	  Loss: 1.594885883785719 	 Accuracy: 0.20730117340286833
Delta: 7.267754035493362e-05 	  Loss: 1.5949644139542332 	 Accuracy: 0.20730117340286833
Delta: 0.0035288590372141585 	  Loss: 1.5953613594657787 	 Accuracy: 0.20730117340286833
Delta: 0.0038729436174798804 	  Loss: 1.5949348463841782 	 Accuracy: 0.20730117340286833
Delta: 0.0022475159583110827 	  Loss: 1.5949725461110207 	 Accuracy: 0.20730117340286833
Delta: 0.0009343900780586366 	  Loss: 1.5949279876159803 	 Accuracy: 0.20730117340286833
Delta: 0.001777643255420506 	  Loss: 1.5949293808052776 	 Accuracy: 0.20730117340286833
Delta: 0.0006289088933261202 	  Loss: 1.5952314637801892 	 Accuracy: 0.20730117340286833
Delta: 0.0008063907900417145 	  Loss: 1.5950007712850744 	 Accuracy: 0.20730117340286833
Delta: 0.00010253828407248267 	  Loss: 1.5949321970635248 	 Accuracy: 0.20730117340286833
Delta: 0.02102998335581555 	  Loss: 2.1574639929542747 	 Accuracy: 0.20730117340286833
Delta: 0.018665534365948117 	  Loss: 2.056061156794091 	 Accuracy: 0.27509778357235987
Delta: 0.016535757279623333 	  Loss: 1.8990213746387135 	 Accuracy: 0.32985658409387225
Delta: 0.014618520015516608 	  Loss: 1.7681317460660686 	 Accuracy: 0.31290743155149936
Delta: 0.012229827023592875 	  Loss: 1.691040135629228 	 Accuracy: 0.3076923076923077
Delta: 0.010747739404357234 	  Loss: 1.650507716923472 	 Accuracy: 0.2816166883963494
Delta: 0.010133509710291708 	  Loss: 1.6278769460365425 	 Accuracy: 0.2790091264667536
Delta: 0.009277140488292295 	  Loss: 1.6159221450198364 	 Accuracy: 0.28292046936114734

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008730128179479713 	  Loss: 1.6084344174215386 	 Accuracy: 0.2803129074315515
Delta: 0.007678512209271222 	  Loss: 1.6036251058838409 	 Accuracy: 0.2790091264667536
Delta: 0.006458694768587875 	  Loss: 1.6005953187590845 	 Accuracy: 0.28552803129074317
Delta: 0.005472971967399238 	  Loss: 1.599863711485294 	 Accuracy: 0.28552803129074317
Delta: 0.00469771793430941 	  Loss: 1.5990255364989692 	 Accuracy: 0.28292046936114734
Delta: 0.0040518227933562965 	  Loss: 1.5989504508087367 	 Accuracy: 0.2816166883963494
Delta: 0.004088216029054144 	  Loss: 1.598869809569404 	 Accuracy: 0.2816166883963494
Delta: 0.00289749252227923 	  Loss: 1.5986694630540368 	 Accuracy: 0.2816166883963494
Delta: 0.003752970786794648 	  Loss: 1.5988021647175152 	 Accuracy: 0.28292046936114734
Delta: 0.006039762278800676 	  Loss: 1.6001958812921044 	 Accuracy: 0.2790091264667536
Delta: 0.0023544775193766743 	  Loss: 1.5998200899214159 	 Accuracy: 0.2790091264667536
Delta: 0.0035277655549761536 	  Loss: 1.5995933102153796 	 Accuracy: 0.2790091264667536
Delta: 0.0034232445953831033 	  Loss: 1.5997170372210219 	 Accuracy: 0.2790091264667536
Delta: 0.0009569763640468386 	  Loss: 1.5995328532388586 	 Accuracy: 0.2790091264667536
Delta: 0.000743404433625753 	  Loss: 1.5996313769232082 	 Accuracy: 0.2803129074315515
Delta: 4.456452867020664e-05 	  Loss: 1.5996502791836424 	 Accuracy: 0.2803129074315515
Delta: 7.641560008114549e-05 	  Loss: 1.5995111570714617 	 Accuracy: 0.2790091264667536
Delta: 7.302206238048188e-05 	  Loss: 1.5996506346244128 	 Accuracy: 0.2803129074315515
Delta: 1.7501516871648892e-05 	  Loss: 1.5996364154827376 	 Accuracy: 0.2803129074315515
Delta: 0.0009920800791992923 	  Loss: 1.599404972163068 	 Accuracy: 0.2790091264667536
Delta: 0.0012762988297026938 	  Loss: 1.5996340547566015 	 Accuracy: 0.2803129074315515
Delta: 0.0005270508343094559 	  Loss: 1.5996757338513132 	 Accuracy: 0.2790091264667536
Delta: 1.1613479354057152e-05 	  Loss: 1.599642484521106 	 Accuracy: 0.2803129074315515
Delta: 5.5584459245908055e-05 	  Loss: 1.599699525703597 	 Accuracy: 0.2803129074315515
Delta: 7.150466239803528e-05 	  Loss: 1.5996210243056517 	 Accuracy: 0.2790091264667536
Delta: 7.302704777189594e-05 	  Loss: 1.5995888321230127 	 Accuracy: 0.2790091264667536
Delta: 0.0014054407227707963 	  Loss: 1.5994801641829768 	 Accuracy: 0.2803129074315515
Delta: 0.0024707907461702203 	  Loss: 1.5992349080004367 	 Accuracy: 0.2790091264667536
Delta: 0.0011443378636716952 	  Loss: 1.5997215735139196 	 Accuracy: 0.2803129074315515
Delta: 0.0005371680623989284 	  Loss: 1.599583305413068 	 Accuracy: 0.2803129074315515
Delta: 4.428520941228666e-05 	  Loss: 1.5997005707016205 	 Accuracy: 0.2803129074315515
Delta: 0.0009493756685284774 	  Loss: 1.599817545337035 	 Accuracy: 0.2777053455019557
Delta: 0.002509849479874579 	  Loss: 1.5996718072459821 	 Accuracy: 0.2790091264667536
Delta: 0.0028964602229369467 	  Loss: 1.5995114291388197 	 Accuracy: 0.2790091264667536
Delta: 0.0024896218454228207 	  Loss: 1.5996712755705706 	 Accuracy: 0.2790091264667536
Delta: 0.001798786150042338 	  Loss: 1.5996254624846098 	 Accuracy: 0.2790091264667536
Delta: 0.0036139098428969512 	  Loss: 1.5994818309687941 	 Accuracy: 0.2790091264667536
Delta: 0.0017100306403150113 	  Loss: 1.5996011030528405 	 Accuracy: 0.27640156453715775
Delta: 0.0035917669872325714 	  Loss: 1.5998072040606846 	 Accuracy: 0.2790091264667536
Delta: 0.0035656814366794576 	  Loss: 1.5993510433919513 	 Accuracy: 0.2803129074315515
Delta: 0.0013847202696494626 	  Loss: 1.599428181213466 	 Accuracy: 0.2790091264667536
Delta: 0.0005737633800449939 	  Loss: 1.5995431990844375 	 Accuracy: 0.2803129074315515
Delta: 0.0005601326683599223 	  Loss: 1.5993395387218592 	 Accuracy: 0.2790091264667536
Delta: 0.003336028174703747 	  Loss: 1.5992959251950043 	 Accuracy: 0.2790091264667536
Delta: 0.001814246932220672 	  Loss: 1.5993307909163277 	 Accuracy: 0.2790091264667536
Delta: 0.0018849694366249925 	  Loss: 1.5992746482674398 	 Accuracy: 0.2790091264667536
Delta: 0.0024048766915822184 	  Loss: 1.599647619550704 	 Accuracy: 0.2790091264667536
Delta: 0.002548240221627104 	  Loss: 1.5999886117488655 	 Accuracy: 0.2803129074315515
Delta: 0.004009501714435365 	  Loss: 1.600125169674767 	 Accuracy: 0.2790091264667536
Delta: 0.004410097256296697 	  Loss: 1.6003918298428017 	 Accuracy: 0.2803129074315515
Delta: 0.0027858422582159328 	  Loss: 1.600427070319594 	 Accuracy: 0.2803129074315515
Delta: 0.0045976567581280554 	  Loss: 1.6003454773739896 	 Accuracy: 0.2790091264667536
Delta: 0.0033753201675926657 	  Loss: 1.6001556606343896 	 Accuracy: 0.27640156453715775
Delta: 0.002650913253090732 	  Loss: 1.600047947930441 	 Accuracy: 0.2803129074315515
Delta: 0.002845991027315242 	  Loss: 1.599887322671582 	 Accuracy: 0.2790091264667536
Delta: 0.002642241413486011 	  Loss: 1.6001395632345226 	 Accuracy: 0.2790091264667536
Delta: 0.002619989910061525 	  Loss: 1.6006668023271462 	 Accuracy: 0.2803129074315515
Delta: 0.003028214182811865 	  Loss: 1.5998585411471011 	 Accuracy: 0.2777053455019557
Delta: 0.0043990470531076195 	  Loss: 1.601099698362169 	 Accuracy: 0.27640156453715775
Delta: 0.0013035173985566774 	  Loss: 1.600991403970018 	 Accuracy: 0.2777053455019557
Delta: 0.0005461242566159847 	  Loss: 1.601090521232839 	 Accuracy: 0.2777053455019557
Delta: 0.0020875984143065504 	  Loss: 1.6010129094986656 	 Accuracy: 0.27640156453715775
Delta: 0.0030722817839315235 	  Loss: 1.6009776524225856 	 Accuracy: 0.27640156453715775
Delta: 0.0043691242708116754 	  Loss: 1.6009403547292653 	 Accuracy: 0.27509778357235987
Delta: 0.003713232859668695 	  Loss: 1.600222990481365 	 Accuracy: 0.28683181225554105
Delta: 0.005680614869627497 	  Loss: 1.6013741640329877 	 Accuracy: 0.27640156453715775
Delta: 0.005112619734897635 	  Loss: 1.6010934321513217 	 Accuracy: 0.27640156453715775
Delta: 0.0029005371405742457 	  Loss: 1.601419134333368 	 Accuracy: 0.2777053455019557
Delta: 0.0026849536315662744 	  Loss: 1.6009801755877695 	 Accuracy: 0.2790091264667536
Delta: 0.004636512493982782 	  Loss: 1.6037439671842812 	 Accuracy: 0.27640156453715775
Delta: 0.004296644419782636 	  Loss: 1.6016972108645202 	 Accuracy: 0.2777053455019557
Delta: 0.004966070202255079 	  Loss: 1.6025583495760438 	 Accuracy: 0.27640156453715775
Delta: 0.0033330826277580246 	  Loss: 1.6027770496428373 	 Accuracy: 0.2777053455019557
Delta: 0.003890760967983939 	  Loss: 1.603643121054744 	 Accuracy: 0.2790091264667536
Delta: 0.0040473742474882585 	  Loss: 1.6032583158154166 	 Accuracy: 0.2790091264667536
Delta: 0.0029662048085824606 	  Loss: 1.6029053308643886 	 Accuracy: 0.2777053455019557
Delta: 0.0023713794535455846 	  Loss: 1.6030391743873507 	 Accuracy: 0.2777053455019557
Delta: 0.0012106568619513363 	  Loss: 1.6030138517648203 	 Accuracy: 0.2777053455019557
Delta: 0.0016828413227625173 	  Loss: 1.6025646960052335 	 Accuracy: 0.2777053455019557
Delta: 0.00011110575599430917 	  Loss: 1.603268730679659 	 Accuracy: 0.27509778357235987
Delta: 0.00429150489710845 	  Loss: 1.6031882774142305 	 Accuracy: 0.27640156453715775
Delta: 0.0030422664062629773 	  Loss: 1.6037372001707626 	 Accuracy: 0.27640156453715775
Delta: 0.0014905812473430032 	  Loss: 1.6039282864737405 	 Accuracy: 0.27640156453715775
Delta: 0.002700172856345937 	  Loss: 1.6037560900354182 	 Accuracy: 0.2737940026075619
Delta: 0.0034779065342733385 	  Loss: 1.6045334032170215 	 Accuracy: 0.27509778357235987
Delta: 0.0038170427152405977 	  Loss: 1.6054122351801559 	 Accuracy: 0.27509778357235987
Delta: 2.5646102070695274e-05 	  Loss: 1.6054211528865574 	 Accuracy: 0.27509778357235987
Delta: 0.0009137217909209578 	  Loss: 1.6056183138138536 	 Accuracy: 0.2737940026075619
Delta: 0.0012545019386237467 	  Loss: 1.6055636779715414 	 Accuracy: 0.2737940026075619
Delta: 0.0033167742132650503 	  Loss: 1.6064729744478372 	 Accuracy: 0.2737940026075619
Delta: 0.00012963542779345454 	  Loss: 1.6067869960251215 	 Accuracy: 0.27509778357235987
Delta: 0.002591948553630884 	  Loss: 1.6070167139394376 	 Accuracy: 0.2737940026075619
Delta: 0.02108729538844986 	  Loss: 2.1585708523412106 	 Accuracy: 0.2033898305084746
Delta: 0.018686658108598358 	  Loss: 2.0675792129721975 	 Accuracy: 0.20599739243807041
Delta: 0.016865497009816145 	  Loss: 1.9246367804053321 	 Accuracy: 0.13820078226857888
Delta: 0.014964757319087892 	  Loss: 1.7938813251465386 	 Accuracy: 0.14471968709256844
Delta: 0.013507584689357864 	  Loss: 1.7101129074505987 	 Accuracy: 0.1408083441981747
Delta: 0.012716739485196336 	  Loss: 1.6624003868157704 	 Accuracy: 0.13820078226857888
Delta: 0.010661337555236395 	  Loss: 1.6422825640935534 	 Accuracy: 0.1290743155149935
Delta: 0.008322628860498197 	  Loss: 1.6346470946488352 	 Accuracy: 0.12777053455019557
Delta: 0.006629801826916172 	  Loss: 1.631326828547047 	 Accuracy: 0.12646675358539766

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005585531605338284 	  Loss: 1.6291626861651927 	 Accuracy: 0.12777053455019557
Delta: 0.0052082070798637825 	  Loss: 1.6279038220252853 	 Accuracy: 0.12646675358539766
Delta: 0.004193888311023379 	  Loss: 1.6275204448903753 	 Accuracy: 0.12646675358539766
Delta: 0.003977234976728681 	  Loss: 1.6275117883856993 	 Accuracy: 0.12646675358539766
Delta: 0.003244697691595304 	  Loss: 1.6275733522492666 	 Accuracy: 0.12646675358539766
Delta: 0.0035535348196792274 	  Loss: 1.6277401023027727 	 Accuracy: 0.12646675358539766
Delta: 0.0025839829982992864 	  Loss: 1.6278608604822378 	 Accuracy: 0.12646675358539766
Delta: 0.0017874660351918186 	  Loss: 1.627700456934731 	 Accuracy: 0.12646675358539766
Delta: 0.0034380207480388973 	  Loss: 1.6274992983334498 	 Accuracy: 0.12646675358539766
Delta: 0.0012665074392951047 	  Loss: 1.6277597600635236 	 Accuracy: 0.12646675358539766
Delta: 0.0005684461237912589 	  Loss: 1.6273602914304632 	 Accuracy: 0.12646675358539766
Delta: 6.947001301576172e-05 	  Loss: 1.6275685568540552 	 Accuracy: 0.12646675358539766
Delta: 0.002374645666788437 	  Loss: 1.6278644154682462 	 Accuracy: 0.12646675358539766
Delta: 0.0034961071020093368 	  Loss: 1.6282628806448642 	 Accuracy: 0.12516297262059975
Delta: 0.00299060505615638 	  Loss: 1.6288314662042214 	 Accuracy: 0.12646675358539766
Delta: 0.0018202308359999684 	  Loss: 1.6282824890473655 	 Accuracy: 0.12646675358539766
Delta: 0.003565903921041322 	  Loss: 1.6281431366445365 	 Accuracy: 0.12646675358539766
Delta: 0.000559389143728316 	  Loss: 1.6281890152543395 	 Accuracy: 0.12646675358539766
Delta: 0.0023059646732954014 	  Loss: 1.628101702619399 	 Accuracy: 0.12646675358539766
Delta: 0.003497073639810717 	  Loss: 1.6277398854853993 	 Accuracy: 0.12646675358539766
Delta: 0.0019226540219290486 	  Loss: 1.6278963831961284 	 Accuracy: 0.12646675358539766
Delta: 0.0017877744910379217 	  Loss: 1.62798738106459 	 Accuracy: 0.12646675358539766
Delta: 0.0020674722145117186 	  Loss: 1.6281355707912035 	 Accuracy: 0.12385919165580182
Delta: 0.0025161783569099747 	  Loss: 1.6285018169361634 	 Accuracy: 0.12646675358539766
Delta: 0.0031207255314824422 	  Loss: 1.6285729229291448 	 Accuracy: 0.12646675358539766
Delta: 0.003703682127699898 	  Loss: 1.6283543362935893 	 Accuracy: 0.12255541069100391
Delta: 0.0046926016781904945 	  Loss: 1.629081717109241 	 Accuracy: 0.12516297262059975
Delta: 0.0026531818123997093 	  Loss: 1.629400777113322 	 Accuracy: 0.12516297262059975
Delta: 0.0030219230798540346 	  Loss: 1.6299603998048966 	 Accuracy: 0.12516297262059975
Delta: 0.000568345616911791 	  Loss: 1.6297927997061983 	 Accuracy: 0.12516297262059975
Delta: 0.004436195105477397 	  Loss: 1.630457277437138 	 Accuracy: 0.12516297262059975
Delta: 0.002962312910666574 	  Loss: 1.6298230181010853 	 Accuracy: 0.12516297262059975
Delta: 0.0014829004068937907 	  Loss: 1.6291800051928853 	 Accuracy: 0.12516297262059975
Delta: 0.0006729998743176123 	  Loss: 1.6291631016441668 	 Accuracy: 0.12385919165580182
Delta: 0.0027367435332230957 	  Loss: 1.6293632608706372 	 Accuracy: 0.12516297262059975
Delta: 0.003270476657893577 	  Loss: 1.6295132532148588 	 Accuracy: 0.12516297262059975
Delta: 0.0006597845332458342 	  Loss: 1.6295833635306403 	 Accuracy: 0.12516297262059975
Delta: 0.0012907295355471231 	  Loss: 1.6295240264321516 	 Accuracy: 0.12516297262059975
Delta: 0.002486565364372003 	  Loss: 1.6294494796725658 	 Accuracy: 0.1303780964797914
Delta: 0.002811354849924363 	  Loss: 1.62943215156458 	 Accuracy: 0.12385919165580182
Delta: 0.0006648661119628674 	  Loss: 1.6292433774950434 	 Accuracy: 0.12516297262059975
Delta: 4.86584557977513e-05 	  Loss: 1.6294906569262355 	 Accuracy: 0.12516297262059975
Delta: 0.001937216255843368 	  Loss: 1.6294081941232732 	 Accuracy: 0.12516297262059975
Delta: 0.0041771120593285084 	  Loss: 1.6297505899306253 	 Accuracy: 0.12516297262059975
Delta: 0.002490221785455518 	  Loss: 1.6294576415995141 	 Accuracy: 0.12646675358539766
Delta: 0.002954055094707137 	  Loss: 1.6293661891886566 	 Accuracy: 0.12385919165580182
Delta: 0.0045970291174124295 	  Loss: 1.6302485690050006 	 Accuracy: 0.12385919165580182
Delta: 0.0030100850560213265 	  Loss: 1.6296254498036296 	 Accuracy: 0.12516297262059975
Delta: 0.0045570411111931835 	  Loss: 1.6296485338394802 	 Accuracy: 0.12385919165580182
Delta: 0.0017259477340822258 	  Loss: 1.6295554904119323 	 Accuracy: 0.12385919165580182
Delta: 8.230786831878697e-05 	  Loss: 1.629637084456439 	 Accuracy: 0.12255541069100391
Delta: 0.003957956887985652 	  Loss: 1.6294227708341698 	 Accuracy: 0.12385919165580182
Delta: 0.004610526547401186 	  Loss: 1.629409988312292 	 Accuracy: 0.12385919165580182
Delta: 0.0010286490595584753 	  Loss: 1.6292278478604219 	 Accuracy: 0.12385919165580182
Delta: 0.0023753875315037387 	  Loss: 1.629122086456357 	 Accuracy: 0.12385919165580182
Delta: 0.0038713462300551836 	  Loss: 1.6283428585924398 	 Accuracy: 0.12385919165580182
Delta: 0.003090450229314486 	  Loss: 1.629150735086224 	 Accuracy: 0.12385919165580182
Delta: 0.002610622102731536 	  Loss: 1.6289662088814425 	 Accuracy: 0.12385919165580182
Delta: 0.0027927683539250184 	  Loss: 1.628873665211401 	 Accuracy: 0.12385919165580182
Delta: 0.000579702577855918 	  Loss: 1.629013229846547 	 Accuracy: 0.12385919165580182
Delta: 8.574850939677574e-05 	  Loss: 1.6291169113600594 	 Accuracy: 0.12385919165580182
Delta: 0.001504191534302372 	  Loss: 1.6290670225419475 	 Accuracy: 0.12385919165580182
Delta: 0.0013387591854985507 	  Loss: 1.6292504921303395 	 Accuracy: 0.12255541069100391
Delta: 0.0035742284569617614 	  Loss: 1.6291970932432727 	 Accuracy: 0.12385919165580182
Delta: 0.001030305978345443 	  Loss: 1.6291953746315588 	 Accuracy: 0.12385919165580182
Delta: 0.0008816825277874034 	  Loss: 1.6292839263049639 	 Accuracy: 0.12516297262059975
Delta: 0.004551196203618556 	  Loss: 1.6291302713025848 	 Accuracy: 0.12385919165580182
Delta: 0.0031411138558185346 	  Loss: 1.629653977198595 	 Accuracy: 0.12385919165580182
Delta: 0.003237193796490204 	  Loss: 1.6295924968551518 	 Accuracy: 0.12385919165580182
Delta: 0.0033064141867852714 	  Loss: 1.629067988768996 	 Accuracy: 0.12385919165580182
Delta: 6.167446708902355e-05 	  Loss: 1.628906415495623 	 Accuracy: 0.12385919165580182
Delta: 0.001514934431690572 	  Loss: 1.6290281545100231 	 Accuracy: 0.12516297262059975
Delta: 0.0042400513423466275 	  Loss: 1.6288053427747153 	 Accuracy: 0.12516297262059975
Delta: 0.0022605837809761085 	  Loss: 1.6288128944929638 	 Accuracy: 0.12516297262059975
Delta: 0.005803571690263424 	  Loss: 1.6293477458985337 	 Accuracy: 0.12385919165580182
Delta: 0.0038354515171042814 	  Loss: 1.6291655410320698 	 Accuracy: 0.12646675358539766
Delta: 0.004907564335589359 	  Loss: 1.628642772003028 	 Accuracy: 0.12646675358539766
Delta: 0.003151868844460899 	  Loss: 1.628868633563771 	 Accuracy: 0.12646675358539766
Delta: 0.003027468414830787 	  Loss: 1.6291831969865673 	 Accuracy: 0.12516297262059975
Delta: 0.0033104763220639932 	  Loss: 1.6293041325500448 	 Accuracy: 0.12516297262059975
Delta: 7.98637962527771e-05 	  Loss: 1.6293415930780273 	 Accuracy: 0.12516297262059975
Delta: 7.915272266397634e-05 	  Loss: 1.6293029595773763 	 Accuracy: 0.12516297262059975
Delta: 0.0030486367670904766 	  Loss: 1.6293405669294483 	 Accuracy: 0.12516297262059975
Delta: 0.003847777998945753 	  Loss: 1.6294518970589937 	 Accuracy: 0.12516297262059975
Delta: 3.3911884925836935e-05 	  Loss: 1.6294346104366402 	 Accuracy: 0.12516297262059975
Delta: 0.004219058552899006 	  Loss: 1.6297941608368038 	 Accuracy: 0.12516297262059975
Delta: 0.0007576558388954003 	  Loss: 1.6298016100776076 	 Accuracy: 0.12516297262059975
Delta: 0.0040823400745205315 	  Loss: 1.6311782751573523 	 Accuracy: 0.12516297262059975
Delta: 0.0015814247708346555 	  Loss: 1.6310891016658773 	 Accuracy: 0.12516297262059975
Delta: 7.528834066100649e-05 	  Loss: 1.6311765087218189 	 Accuracy: 0.12516297262059975
Delta: 1.7919298949593557e-05 	  Loss: 1.6311769094806978 	 Accuracy: 0.12516297262059975
Delta: 0.02108334584793729 	  Loss: 2.1578429935766614 	 Accuracy: 0.19556714471968709
Delta: 0.018753057844451908 	  Loss: 2.0598904901737543 	 Accuracy: 0.26597131681877445
Delta: 0.017735200291090675 	  Loss: 1.8994032086411046 	 Accuracy: 0.2685788787483703
Delta: 0.015910917226572667 	  Loss: 1.7388527077872207 	 Accuracy: 0.2790091264667536
Delta: 0.012699026481781141 	  Loss: 1.6473559821515202 	 Accuracy: 0.2685788787483703
Delta: 0.009859791314626672 	  Loss: 1.6155433755333766 	 Accuracy: 0.26727509778357234
Delta: 0.008643713306925949 	  Loss: 1.6051147198819162 	 Accuracy: 0.2542372881355932
Delta: 0.007926178914168754 	  Loss: 1.6003546727467497 	 Accuracy: 0.2503259452411995

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007121711043049609 	  Loss: 1.5977220308625124 	 Accuracy: 0.2516297262059974
Delta: 0.0059887264745846205 	  Loss: 1.5967747422939347 	 Accuracy: 0.2503259452411995
Delta: 0.004540334219869428 	  Loss: 1.5960936907136762 	 Accuracy: 0.2529335071707953
Delta: 0.00442549532977127 	  Loss: 1.5960578267254832 	 Accuracy: 0.2503259452411995
Delta: 0.0028749066245562288 	  Loss: 1.5961963783786581 	 Accuracy: 0.2503259452411995
Delta: 0.004231342429212997 	  Loss: 1.5962140886443934 	 Accuracy: 0.2503259452411995
Delta: 0.003120871026154238 	  Loss: 1.5962292503097544 	 Accuracy: 0.2503259452411995
Delta: 0.003232939065205666 	  Loss: 1.596201159495164 	 Accuracy: 0.2503259452411995
Delta: 0.0019056664964283102 	  Loss: 1.5961773469450125 	 Accuracy: 0.2503259452411995
Delta: 0.0007157412561501678 	  Loss: 1.5961636918737443 	 Accuracy: 0.2503259452411995
Delta: 0.001302528310951389 	  Loss: 1.5962817882631795 	 Accuracy: 0.2503259452411995
Delta: 0.0012369771598540608 	  Loss: 1.5960093498356664 	 Accuracy: 0.2503259452411995
Delta: 0.0033927387857576497 	  Loss: 1.5960633681792067 	 Accuracy: 0.2503259452411995
Delta: 0.0020990640708907645 	  Loss: 1.5958129058043624 	 Accuracy: 0.2503259452411995
Delta: 0.003142906545506095 	  Loss: 1.5960178808752112 	 Accuracy: 0.2516297262059974
Delta: 0.002350795055725538 	  Loss: 1.595954335523487 	 Accuracy: 0.2516297262059974
Delta: 0.001670939788573192 	  Loss: 1.5961116939405287 	 Accuracy: 0.2529335071707953
Delta: 0.002721568787883141 	  Loss: 1.5960590722643921 	 Accuracy: 0.2516297262059974
Delta: 0.0015815983625519622 	  Loss: 1.5958938668831002 	 Accuracy: 0.2529335071707953
Delta: 0.0023957630383821724 	  Loss: 1.5957849614878796 	 Accuracy: 0.2516297262059974
Delta: 0.0013151460493951285 	  Loss: 1.59603943722891 	 Accuracy: 0.2529335071707953
Delta: 0.001758733877465267 	  Loss: 1.5958479338808593 	 Accuracy: 0.2529335071707953
Delta: 0.0030147734627405344 	  Loss: 1.5955927730197337 	 Accuracy: 0.2516297262059974
Delta: 0.0013192390777689291 	  Loss: 1.5957996422916185 	 Accuracy: 0.2529335071707953
Delta: 0.0011073571532483242 	  Loss: 1.5953954996665725 	 Accuracy: 0.2529335071707953
Delta: 4.928194465068518e-05 	  Loss: 1.595398947079202 	 Accuracy: 0.24902216427640156
Delta: 8.58468874204236e-05 	  Loss: 1.5954615262132936 	 Accuracy: 0.2529335071707953
Delta: 0.0016299709925730785 	  Loss: 1.595801037123417 	 Accuracy: 0.2529335071707953
Delta: 0.0014678022567905656 	  Loss: 1.5954889451188299 	 Accuracy: 0.24902216427640156
Delta: 8.832829316951071e-05 	  Loss: 1.5957406198558879 	 Accuracy: 0.2516297262059974
Delta: 0.00010035866896325488 	  Loss: 1.5955325901128674 	 Accuracy: 0.2542372881355932
Delta: 0.0001382981770402218 	  Loss: 1.5954728311859137 	 Accuracy: 0.2503259452411995
Delta: 0.0020362281862931807 	  Loss: 1.5957735515881488 	 Accuracy: 0.2516297262059974
Delta: 0.0018710669336292067 	  Loss: 1.5954556890909843 	 Accuracy: 0.24641460234680573
Delta: 0.0006557602239167494 	  Loss: 1.595715562017843 	 Accuracy: 0.2516297262059974
Delta: 0.0010630497301459896 	  Loss: 1.595690694134216 	 Accuracy: 0.2516297262059974
Delta: 0.0013771812437643784 	  Loss: 1.5955822895560823 	 Accuracy: 0.2516297262059974
Delta: 0.0026406726825121685 	  Loss: 1.595905761341335 	 Accuracy: 0.2529335071707953
Delta: 0.003592042877552296 	  Loss: 1.5963280530082575 	 Accuracy: 0.2516297262059974
Delta: 0.0017682763700217804 	  Loss: 1.59657870870606 	 Accuracy: 0.2503259452411995
Delta: 0.0019663643219393276 	  Loss: 1.5964879542883135 	 Accuracy: 0.2529335071707953
Delta: 0.0016612145686917788 	  Loss: 1.5962825830012055 	 Accuracy: 0.2516297262059974
Delta: 0.0019975346286494676 	  Loss: 1.5965506282708597 	 Accuracy: 0.2516297262059974
Delta: 0.001676019036497618 	  Loss: 1.5964106301504917 	 Accuracy: 0.2516297262059974
Delta: 0.001753949478612386 	  Loss: 1.5967270933442985 	 Accuracy: 0.2542372881355932
Delta: 0.0016181494112302763 	  Loss: 1.5966543597321543 	 Accuracy: 0.2529335071707953
Delta: 0.0004998535566067541 	  Loss: 1.596633492486614 	 Accuracy: 0.24902216427640156
Delta: 0.0017001498047000644 	  Loss: 1.5966169058310287 	 Accuracy: 0.2503259452411995
Delta: 0.0010850636094321775 	  Loss: 1.5964319423088853 	 Accuracy: 0.2516297262059974
Delta: 0.0013576763033496505 	  Loss: 1.5964912250940546 	 Accuracy: 0.2529335071707953
Delta: 0.002018927781731732 	  Loss: 1.5967904033766498 	 Accuracy: 0.2516297262059974
Delta: 0.001956767028145536 	  Loss: 1.5968568931730678 	 Accuracy: 0.2503259452411995
Delta: 0.0014998136129307533 	  Loss: 1.5967288009560592 	 Accuracy: 0.2516297262059974
Delta: 9.065290286602966e-05 	  Loss: 1.5964384467463915 	 Accuracy: 0.2529335071707953
Delta: 0.0017413053406699465 	  Loss: 1.5962438450337637 	 Accuracy: 0.2529335071707953
Delta: 0.0005812638285143195 	  Loss: 1.5963894286680032 	 Accuracy: 0.2529335071707953
Delta: 4.743140315794599e-05 	  Loss: 1.5963903235442982 	 Accuracy: 0.242503259452412
Delta: 0.0025243090781949472 	  Loss: 1.597269198552191 	 Accuracy: 0.2503259452411995
Delta: 0.004427373373063461 	  Loss: 1.5969253439274076 	 Accuracy: 0.2529335071707953
Delta: 0.003548794177723107 	  Loss: 1.5968961790872036 	 Accuracy: 0.2516297262059974
Delta: 0.0036155745903116224 	  Loss: 1.5967072227802 	 Accuracy: 0.2529335071707953
Delta: 0.003910779414309773 	  Loss: 1.5969708710552462 	 Accuracy: 0.2503259452411995
Delta: 0.0015248922406641888 	  Loss: 1.5970357299262283 	 Accuracy: 0.2516297262059974
Delta: 0.0028198759225877496 	  Loss: 1.5969512253492226 	 Accuracy: 0.2529335071707953
Delta: 0.002976047953007193 	  Loss: 1.5968227196138725 	 Accuracy: 0.2529335071707953
Delta: 0.0005930705368403442 	  Loss: 1.5967743784884627 	 Accuracy: 0.2529335071707953
Delta: 0.001282038641827804 	  Loss: 1.596364465790324 	 Accuracy: 0.2529335071707953
Delta: 0.004115800626587502 	  Loss: 1.5946305770146658 	 Accuracy: 0.2542372881355932
Delta: 0.0023505900553009752 	  Loss: 1.5954041133646353 	 Accuracy: 0.2542372881355932
Delta: 0.00213277815413637 	  Loss: 1.5950125245796198 	 Accuracy: 0.2542372881355932
Delta: 2.629234850866534e-06 	  Loss: 1.595012020159551 	 Accuracy: 0.2516297262059974
Delta: 0.003847752322378701 	  Loss: 1.5954428114545351 	 Accuracy: 0.2542372881355932
Delta: 0.0037239316205887408 	  Loss: 1.5955598970001672 	 Accuracy: 0.2529335071707953
Delta: 0.001803052741716503 	  Loss: 1.5953701618802731 	 Accuracy: 0.2542372881355932
Delta: 0.0007741739034580892 	  Loss: 1.5951681585804711 	 Accuracy: 0.2542372881355932
Delta: 0.0032941103487832838 	  Loss: 1.5947631331102774 	 Accuracy: 0.2542372881355932
Delta: 5.7529155657490326e-05 	  Loss: 1.5949127202820732 	 Accuracy: 0.2542372881355932
Delta: 3.1163409677618116e-05 	  Loss: 1.5949195638889184 	 Accuracy: 0.2542372881355932
Delta: 9.898641215380469e-05 	  Loss: 1.594988234486251 	 Accuracy: 0.25554106910039115
Delta: 0.0030713646428083153 	  Loss: 1.5944737665444828 	 Accuracy: 0.2503259452411995
Delta: 0.0017206318352879402 	  Loss: 1.594611364338492 	 Accuracy: 0.2542372881355932
Delta: 0.00012404652754697087 	  Loss: 1.5944618308097853 	 Accuracy: 0.2542372881355932
Delta: 0.003409525871613873 	  Loss: 1.5940661156220934 	 Accuracy: 0.242503259452412
Delta: 0.005960350766538622 	  Loss: 1.5961452327564074 	 Accuracy: 0.24641460234680573
Delta: 0.0044984685243060155 	  Loss: 1.5963597978749198 	 Accuracy: 0.2529335071707953
Delta: 0.003437975710324802 	  Loss: 1.5968894064492267 	 Accuracy: 0.24641460234680573
Delta: 0.002325761420479742 	  Loss: 1.596667445064766 	 Accuracy: 0.24641460234680573
Delta: 0.0007329280223685416 	  Loss: 1.5966070288577852 	 Accuracy: 0.24771838331160365
Delta: 0.0019219972359283506 	  Loss: 1.5966126167700558 	 Accuracy: 0.24902216427640156
Delta: 5.996032066441288e-05 	  Loss: 1.5966316478529863 	 Accuracy: 0.24641460234680573
Delta: 0.0016074248170305987 	  Loss: 1.5969644600505704 	 Accuracy: 0.242503259452412
Delta: 0.0038280066229349386 	  Loss: 1.5974854994292864 	 Accuracy: 0.24641460234680573
Delta: 0.02094979364130602 	  Loss: 2.1584619438074606 	 Accuracy: 0.20208604954367665
Delta: 0.01859719455494273 	  Loss: 2.064747860530891 	 Accuracy: 0.2516297262059974
Delta: 0.017128883753923765 	  Loss: 1.9020999608031381 	 Accuracy: 0.22294654498044328
Delta: 0.014916442963237162 	  Loss: 1.7634248109620079 	 Accuracy: 0.2151238591916558
Delta: 0.013210750306080703 	  Loss: 1.694280761548826 	 Accuracy: 0.20078226857887874
Delta: 0.012413094331119373 	  Loss: 1.659724340076808 	 Accuracy: 0.17992177314211213
Delta: 0.010704529095536156 	  Loss: 1.639214228255081 	 Accuracy: 0.16688396349413298

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009155457152975319 	  Loss: 1.6293359428532508 	 Accuracy: 0.16427640156453716
Delta: 0.007503635479853455 	  Loss: 1.6248522408324164 	 Accuracy: 0.16297262059973924
Delta: 0.00640300994035596 	  Loss: 1.6233159944930513 	 Accuracy: 0.16427640156453716
Delta: 0.004856462337427998 	  Loss: 1.6229500036572369 	 Accuracy: 0.16297262059973924
Delta: 0.004737486761990781 	  Loss: 1.6231733419616163 	 Accuracy: 0.16427640156453716
Delta: 0.003229575710943934 	  Loss: 1.6229656801424541 	 Accuracy: 0.16297262059973924
Delta: 0.0014118166104915063 	  Loss: 1.622746431976807 	 Accuracy: 0.16297262059973924
Delta: 0.001803063681136003 	  Loss: 1.62282376420628 	 Accuracy: 0.16427640156453716
Delta: 0.0026683683283679235 	  Loss: 1.6226113769561954 	 Accuracy: 0.16297262059973924
Delta: 0.002682058309323974 	  Loss: 1.6225817029616791 	 Accuracy: 0.16297262059973924
Delta: 0.0012883117461190321 	  Loss: 1.622617841279389 	 Accuracy: 0.16297262059973924
Delta: 0.0033000990575623363 	  Loss: 1.6229655797220872 	 Accuracy: 0.16297262059973924
Delta: 0.001280899219940034 	  Loss: 1.6229861258880356 	 Accuracy: 0.16297262059973924
Delta: 0.0009109792459907975 	  Loss: 1.622884006791094 	 Accuracy: 0.16297262059973924
Delta: 0.002643915741629017 	  Loss: 1.6228597400209965 	 Accuracy: 0.16166883963494133
Delta: 0.0007687317213235227 	  Loss: 1.6225896781181914 	 Accuracy: 0.16297262059973924
Delta: 0.0021106810883271083 	  Loss: 1.6227007668483902 	 Accuracy: 0.16297262059973924
Delta: 0.0011120358483357724 	  Loss: 1.623006323165706 	 Accuracy: 0.16297262059973924
Delta: 0.0005251678569179398 	  Loss: 1.6230617971074692 	 Accuracy: 0.16297262059973924
Delta: 4.122701690721877e-05 	  Loss: 1.6230948000231065 	 Accuracy: 0.16166883963494133
Delta: 4.48467507479969e-05 	  Loss: 1.6228492464375954 	 Accuracy: 0.16297262059973924
Delta: 4.1901225708703054e-05 	  Loss: 1.6229029614105768 	 Accuracy: 0.16297262059973924
Delta: 0.000749892398164347 	  Loss: 1.6229801250688496 	 Accuracy: 0.16297262059973924
Delta: 0.0015985449350110186 	  Loss: 1.623001251430228 	 Accuracy: 0.16297262059973924
Delta: 0.00010746688028819263 	  Loss: 1.6227628524167041 	 Accuracy: 0.16297262059973924
Delta: 0.001337243843018281 	  Loss: 1.622905975392592 	 Accuracy: 0.16297262059973924
Delta: 0.0032311028078234713 	  Loss: 1.6232681638768427 	 Accuracy: 0.16297262059973924
Delta: 0.00397584629454839 	  Loss: 1.6235904256300935 	 Accuracy: 0.16427640156453716
Delta: 0.0036221786707863178 	  Loss: 1.623266124668283 	 Accuracy: 0.16036505867014342
Delta: 0.0016846688890249392 	  Loss: 1.6230835773848302 	 Accuracy: 0.16427640156453716
Delta: 7.882130810534017e-05 	  Loss: 1.6230448740737815 	 Accuracy: 0.16427640156453716
Delta: 0.0006499869311365968 	  Loss: 1.622842702206135 	 Accuracy: 0.16558018252933507
Delta: 0.0015150680146126892 	  Loss: 1.6231216756159634 	 Accuracy: 0.16427640156453716
Delta: 0.002018898114236495 	  Loss: 1.6234142105474902 	 Accuracy: 0.16427640156453716
Delta: 0.0027778131000492797 	  Loss: 1.6234504817641322 	 Accuracy: 0.16427640156453716
Delta: 0.0016774586698607545 	  Loss: 1.6228551769115005 	 Accuracy: 0.16036505867014342
Delta: 0.003614499777570146 	  Loss: 1.623130051735277 	 Accuracy: 0.16427640156453716
Delta: 0.0036165612284584482 	  Loss: 1.623465002620591 	 Accuracy: 0.16427640156453716
Delta: 0.0015132663807093229 	  Loss: 1.6235359515183196 	 Accuracy: 0.16427640156453716
Delta: 0.0022708864508390225 	  Loss: 1.6234039331631887 	 Accuracy: 0.16427640156453716
Delta: 0.0033001070593951316 	  Loss: 1.6233228340493286 	 Accuracy: 0.16427640156453716
Delta: 0.001793755821936932 	  Loss: 1.6233411411682075 	 Accuracy: 0.16427640156453716
Delta: 0.0010214334712582676 	  Loss: 1.6231791161401872 	 Accuracy: 0.16427640156453716
Delta: 0.000806690483005453 	  Loss: 1.6230094486966697 	 Accuracy: 0.16427640156453716
Delta: 6.236698524573757e-05 	  Loss: 1.6230291184286862 	 Accuracy: 0.16427640156453716
Delta: 5.9299482615695376e-05 	  Loss: 1.6231922857978942 	 Accuracy: 0.1694915254237288
Delta: 0.0025325146592969764 	  Loss: 1.6235856836749798 	 Accuracy: 0.16427640156453716
Delta: 0.0014977520011301012 	  Loss: 1.623183069925505 	 Accuracy: 0.16427640156453716
Delta: 0.0025978463746991363 	  Loss: 1.6231275913422616 	 Accuracy: 0.16688396349413298
Delta: 0.009292097438727985 	  Loss: 1.622971043640367 	 Accuracy: 0.15384615384615385
Delta: 0.008324614373794467 	  Loss: 1.6201793981654695 	 Accuracy: 0.15384615384615385
Delta: 0.0034512287527542892 	  Loss: 1.6199060426439074 	 Accuracy: 0.15123859191655803
Delta: 0.002711093475240833 	  Loss: 1.6199568302143434 	 Accuracy: 0.15384615384615385
Delta: 0.0012176881215065502 	  Loss: 1.6197511930459665 	 Accuracy: 0.15384615384615385
Delta: 0.002989051126348943 	  Loss: 1.6200481313546007 	 Accuracy: 0.14471968709256844
Delta: 0.0007248695339139672 	  Loss: 1.6200581125618227 	 Accuracy: 0.15514993481095177
Delta: 0.0011771800796416022 	  Loss: 1.620065588950744 	 Accuracy: 0.15384615384615385
Delta: 0.0005936840003713135 	  Loss: 1.6202146291835697 	 Accuracy: 0.15123859191655803
Delta: 0.0027549576999519342 	  Loss: 1.6202247263582001 	 Accuracy: 0.15514993481095177
Delta: 0.0011271593569477142 	  Loss: 1.619896509683527 	 Accuracy: 0.15254237288135594
Delta: 0.0010973034835569451 	  Loss: 1.6198389145245649 	 Accuracy: 0.15645371577574968
Delta: 5.516952466691567e-05 	  Loss: 1.6197155430857801 	 Accuracy: 0.15384615384615385
Delta: 0.0005572655676999948 	  Loss: 1.6195596133563719 	 Accuracy: 0.15254237288135594
Delta: 4.0737874193586016e-05 	  Loss: 1.6196296269459545 	 Accuracy: 0.15254237288135594
Delta: 0.005027511221529879 	  Loss: 1.6203880699135387 	 Accuracy: 0.15254237288135594
Delta: 0.0019026862768506342 	  Loss: 1.6209039798142022 	 Accuracy: 0.15254237288135594
Delta: 0.0032869925355545897 	  Loss: 1.621463756919134 	 Accuracy: 0.15254237288135594
Delta: 0.0028878721918369327 	  Loss: 1.620379723536252 	 Accuracy: 0.15254237288135594
Delta: 0.0034258613657932257 	  Loss: 1.620473684171195 	 Accuracy: 0.15254237288135594
Delta: 0.002488860648471117 	  Loss: 1.620471203513294 	 Accuracy: 0.15254237288135594
Delta: 0.0027104535858204835 	  Loss: 1.6207555567963676 	 Accuracy: 0.15254237288135594
Delta: 6.663179987932874e-05 	  Loss: 1.6206346635996762 	 Accuracy: 0.15123859191655803
Delta: 0.0008147660061942675 	  Loss: 1.6207545826013887 	 Accuracy: 0.15254237288135594
Delta: 4.5849404445935063e-05 	  Loss: 1.620641253231888 	 Accuracy: 0.15254237288135594
Delta: 3.4091313125342166e-05 	  Loss: 1.6206677396763844 	 Accuracy: 0.15384615384615385
Delta: 2.2774838298954646e-05 	  Loss: 1.6205618707633036 	 Accuracy: 0.15645371577574968
Delta: 0.0014260442896963372 	  Loss: 1.621037889115017 	 Accuracy: 0.15254237288135594
Delta: 0.0028130522059763023 	  Loss: 1.6209739402136414 	 Accuracy: 0.15514993481095177
Delta: 0.0036894524587303555 	  Loss: 1.6213772675898501 	 Accuracy: 0.15254237288135594
Delta: 0.0039480539375206375 	  Loss: 1.6208083700854643 	 Accuracy: 0.15254237288135594
Delta: 0.0018858944683257052 	  Loss: 1.6207345341728143 	 Accuracy: 0.15254237288135594
Delta: 0.001979087250884216 	  Loss: 1.6209535634218109 	 Accuracy: 0.15254237288135594
Delta: 0.0005535033949861176 	  Loss: 1.6208565326625775 	 Accuracy: 0.15254237288135594
Delta: 7.796307396441941e-05 	  Loss: 1.621208187628488 	 Accuracy: 0.15254237288135594
Delta: 1.1775594179741382e-05 	  Loss: 1.6212527054733383 	 Accuracy: 0.15254237288135594
Delta: 0.0009388577273649965 	  Loss: 1.6211022723903856 	 Accuracy: 0.15254237288135594
Delta: 0.0031596708603885 	  Loss: 1.620377647741856 	 Accuracy: 0.15254237288135594
Delta: 0.0005350600669694576 	  Loss: 1.6203582921974269 	 Accuracy: 0.14863102998696218
Delta: 0.0038289782689699334 	  Loss: 1.6208536072888786 	 Accuracy: 0.15254237288135594
Delta: 0.0024046152943612248 	  Loss: 1.6207727211974905 	 Accuracy: 0.15254237288135594
Delta: 0.002960556728317244 	  Loss: 1.620654964148888 	 Accuracy: 0.15254237288135594
Delta: 0.0030719942614032027 	  Loss: 1.6204756216385272 	 Accuracy: 0.15123859191655803
Delta: 0.0040844354907050235 	  Loss: 1.621193063585977 	 Accuracy: 0.15123859191655803
Delta: 0.021059579087050934 	  Loss: 2.158591562716967 	 Accuracy: 0.2033898305084746
Delta: 0.018560702134251386 	  Loss: 2.059819179238183 	 Accuracy: 0.20990873533246415
Delta: 0.01685233808702513 	  Loss: 1.9036280278361255 	 Accuracy: 0.2242503259452412
Delta: 0.014746467680401673 	  Loss: 1.7909871860998465 	 Accuracy: 0.21642764015645372
Delta: 0.013287336403546915 	  Loss: 1.7348971067177472 	 Accuracy: 0.23598435462842243
Delta: 0.011924323363305681 	  Loss: 1.7092239845286512 	 Accuracy: 0.2333767926988266
Delta: 0.01008058119630744 	  Loss: 1.6977251538589573 	 Accuracy: 0.22946544980443284
Delta: 0.00911805421537603 	  Loss: 1.6921232312121244 	 Accuracy: 0.2333767926988266

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007552516292335727 	  Loss: 1.6903297933244856 	 Accuracy: 0.2320730117340287
Delta: 0.006050922366306573 	  Loss: 1.6893055195783586 	 Accuracy: 0.23468057366362452
Delta: 0.006004181049708213 	  Loss: 1.688579644201867 	 Accuracy: 0.2333767926988266
Delta: 0.005538962935281341 	  Loss: 1.6883550459394248 	 Accuracy: 0.2333767926988266
Delta: 0.0032279596620750084 	  Loss: 1.6882651835448532 	 Accuracy: 0.2333767926988266
Delta: 0.00286301509943896 	  Loss: 1.6883775174995752 	 Accuracy: 0.2333767926988266
Delta: 0.005777976302278501 	  Loss: 1.688014854038582 	 Accuracy: 0.2333767926988266
Delta: 0.002597944241796563 	  Loss: 1.6879592453859855 	 Accuracy: 0.2333767926988266
Delta: 0.0022920573943959284 	  Loss: 1.6880278146488128 	 Accuracy: 0.2333767926988266
Delta: 0.0008395999078027985 	  Loss: 1.688078406677909 	 Accuracy: 0.2333767926988266
Delta: 0.0013115290599985817 	  Loss: 1.6881549907254043 	 Accuracy: 0.2333767926988266
Delta: 0.001559154510676516 	  Loss: 1.687783754330492 	 Accuracy: 0.2333767926988266
Delta: 0.0023534552303876573 	  Loss: 1.6878658422787953 	 Accuracy: 0.2333767926988266
Delta: 7.129785187212272e-05 	  Loss: 1.6880190849289822 	 Accuracy: 0.2333767926988266
Delta: 0.002503630537395573 	  Loss: 1.688022492241376 	 Accuracy: 0.2333767926988266
Delta: 9.383159187924312e-05 	  Loss: 1.687996092315684 	 Accuracy: 0.2333767926988266
Delta: 0.0016871041390245927 	  Loss: 1.6877821404017967 	 Accuracy: 0.2333767926988266
Delta: 0.001742867671906925 	  Loss: 1.6879829293758286 	 Accuracy: 0.23728813559322035
Delta: 0.002480966064727364 	  Loss: 1.688118623350959 	 Accuracy: 0.2333767926988266
Delta: 0.004963220485920513 	  Loss: 1.6875278788440662 	 Accuracy: 0.2333767926988266
Delta: 0.005183976300505914 	  Loss: 1.687363462391842 	 Accuracy: 0.23468057366362452
Delta: 0.0006816292925331908 	  Loss: 1.6874802708980894 	 Accuracy: 0.23468057366362452
Delta: 0.0022370620102496563 	  Loss: 1.687623696598209 	 Accuracy: 0.23468057366362452
Delta: 0.0034105039211490234 	  Loss: 1.6873631497557082 	 Accuracy: 0.23468057366362452
Delta: 0.003263376648742242 	  Loss: 1.6869843538489007 	 Accuracy: 0.23468057366362452
Delta: 0.001466962396778109 	  Loss: 1.6868588357916092 	 Accuracy: 0.23468057366362452
Delta: 0.0028728760445786866 	  Loss: 1.687464801104818 	 Accuracy: 0.23468057366362452
Delta: 0.0008773488398006182 	  Loss: 1.687190021108699 	 Accuracy: 0.23468057366362452
Delta: 0.002136827764389881 	  Loss: 1.687164518752712 	 Accuracy: 0.23468057366362452
Delta: 0.0009852615483642092 	  Loss: 1.687026843162343 	 Accuracy: 0.23468057366362452
Delta: 6.046499933250653e-05 	  Loss: 1.68726276599893 	 Accuracy: 0.23468057366362452
Delta: 0.0018495664031035882 	  Loss: 1.6868840877046747 	 Accuracy: 0.2333767926988266
Delta: 0.002119780030498387 	  Loss: 1.6872024344461336 	 Accuracy: 0.23598435462842243
Delta: 0.001141764978341973 	  Loss: 1.6872693571926283 	 Accuracy: 0.23468057366362452
Delta: 0.0015813403467622386 	  Loss: 1.6870721284569856 	 Accuracy: 0.23468057366362452
Delta: 0.004370697345151691 	  Loss: 1.6879542028724037 	 Accuracy: 0.23468057366362452
Delta: 0.004059753809856756 	  Loss: 1.6879150659176996 	 Accuracy: 0.23468057366362452
Delta: 0.002644035977112103 	  Loss: 1.6877265925639104 	 Accuracy: 0.23468057366362452
Delta: 0.001196121703174703 	  Loss: 1.6882357262771732 	 Accuracy: 0.23468057366362452
Delta: 0.003118295295513318 	  Loss: 1.6886598668100472 	 Accuracy: 0.2333767926988266
Delta: 0.0024187289538396615 	  Loss: 1.6882491718625119 	 Accuracy: 0.2333767926988266
Delta: 0.0023230901721386747 	  Loss: 1.6885975109523574 	 Accuracy: 0.23468057366362452
Delta: 0.00423213590023345 	  Loss: 1.6886790866329273 	 Accuracy: 0.23598435462842243
Delta: 0.0038727753960699886 	  Loss: 1.6886199240479929 	 Accuracy: 0.23598435462842243
Delta: 0.0027566371702643666 	  Loss: 1.6885524014131015 	 Accuracy: 0.23598435462842243
Delta: 0.005415686076772503 	  Loss: 1.6887207951719003 	 Accuracy: 0.23468057366362452
Delta: 0.0028178045850728323 	  Loss: 1.688606390394397 	 Accuracy: 0.23468057366362452
Delta: 0.0032308952632608898 	  Loss: 1.6884040751186156 	 Accuracy: 0.23468057366362452
Delta: 0.001686972484570459 	  Loss: 1.68814269607948 	 Accuracy: 0.23468057366362452
Delta: 0.003395596416179224 	  Loss: 1.6879067237551888 	 Accuracy: 0.23468057366362452
Delta: 0.002250771993954692 	  Loss: 1.6883528442631843 	 Accuracy: 0.23468057366362452
Delta: 0.0018653497470437275 	  Loss: 1.6887112726546771 	 Accuracy: 0.23468057366362452
Delta: 0.0035437768250189297 	  Loss: 1.6883546591876342 	 Accuracy: 0.23468057366362452
Delta: 0.0043494515170638265 	  Loss: 1.6875414250304575 	 Accuracy: 0.23598435462842243
Delta: 0.00391868975489264 	  Loss: 1.6873892392578052 	 Accuracy: 0.23468057366362452
Delta: 0.00429432959546499 	  Loss: 1.6867714725853253 	 Accuracy: 0.23728813559322035
Delta: 0.003227185544675439 	  Loss: 1.6873270129677702 	 Accuracy: 0.23728813559322035
Delta: 0.003214365471687671 	  Loss: 1.6870054551689178 	 Accuracy: 0.23598435462842243
Delta: 0.0013158876623431623 	  Loss: 1.6869562760023342 	 Accuracy: 0.23728813559322035
Delta: 0.00508186307663419 	  Loss: 1.6875394780807689 	 Accuracy: 0.23859191655801826
Delta: 3.2448075142696656e-05 	  Loss: 1.687531402974158 	 Accuracy: 0.23598435462842243
Delta: 0.0017302738141835548 	  Loss: 1.6871928948137183 	 Accuracy: 0.23598435462842243
Delta: 2.6168457248078658e-05 	  Loss: 1.6871881972181968 	 Accuracy: 0.23598435462842243
Delta: 0.00010662497769433462 	  Loss: 1.6875628848652617 	 Accuracy: 0.23468057366362452
Delta: 0.003928845892175513 	  Loss: 1.687912436256356 	 Accuracy: 0.23468057366362452
Delta: 0.002367146988871509 	  Loss: 1.6879019669763844 	 Accuracy: 0.23468057366362452
Delta: 0.001615827754934737 	  Loss: 1.6877193285058696 	 Accuracy: 0.23598435462842243
Delta: 0.0016745949415511554 	  Loss: 1.6874740596823146 	 Accuracy: 0.23468057366362452
Delta: 0.0022948617407803212 	  Loss: 1.68783871224651 	 Accuracy: 0.23468057366362452
Delta: 5.682295869132296e-05 	  Loss: 1.6878883420365618 	 Accuracy: 0.2333767926988266
Delta: 0.0009122392173979412 	  Loss: 1.6875592844308933 	 Accuracy: 0.23468057366362452
Delta: 0.0035541906528124612 	  Loss: 1.6877584879465424 	 Accuracy: 0.23468057366362452
Delta: 0.003566300625450465 	  Loss: 1.6877983502740173 	 Accuracy: 0.23598435462842243
Delta: 0.00437443957836261 	  Loss: 1.6880669246415985 	 Accuracy: 0.23728813559322035
Delta: 0.002527335110700815 	  Loss: 1.687720411613483 	 Accuracy: 0.23468057366362452
Delta: 0.0031985060279222733 	  Loss: 1.688778542302497 	 Accuracy: 0.23468057366362452
Delta: 0.0028414046154222015 	  Loss: 1.6882366169951117 	 Accuracy: 0.23468057366362452
Delta: 0.004245000474849049 	  Loss: 1.688246367401531 	 Accuracy: 0.22946544980443284
Delta: 0.00377879029328767 	  Loss: 1.688818351458738 	 Accuracy: 0.23076923076923078
Delta: 0.0035300613719595015 	  Loss: 1.6889257139965346 	 Accuracy: 0.23468057366362452
Delta: 0.0008665303063859256 	  Loss: 1.6883797977800463 	 Accuracy: 0.2333767926988266
Delta: 0.0009859181579037128 	  Loss: 1.6887027192392206 	 Accuracy: 0.23468057366362452
Delta: 0.0008167471865987004 	  Loss: 1.6887253562689644 	 Accuracy: 0.23468057366362452
Delta: 0.003423150473028208 	  Loss: 1.6893608397349777 	 Accuracy: 0.2333767926988266
Delta: 0.003202400526083901 	  Loss: 1.6892868095460531 	 Accuracy: 0.23468057366362452
Delta: 0.005243371599875708 	  Loss: 1.689118002310433 	 Accuracy: 0.2333767926988266
Delta: 0.004717003700871181 	  Loss: 1.6895384964283586 	 Accuracy: 0.23468057366362452
Delta: 0.004027174746524225 	  Loss: 1.6886446871853245 	 Accuracy: 0.23859191655801826
Delta: 0.004850066340282587 	  Loss: 1.689110914628459 	 Accuracy: 0.23468057366362452
Delta: 0.0034793299441245647 	  Loss: 1.6883251068613356 	 Accuracy: 0.23468057366362452
Delta: 0.002843174432800161 	  Loss: 1.6882326310427682 	 Accuracy: 0.23468057366362452
Delta: 5.223708009868445e-05 	  Loss: 1.6882084773471846 	 Accuracy: 0.23468057366362452
Delta: 0.021038275066251458 	  Loss: 2.15852460577693 	 Accuracy: 0.20078226857887874
Delta: 0.018945006816523637 	  Loss: 2.0562747170188933 	 Accuracy: 0.22294654498044328
Delta: 0.01754256251147922 	  Loss: 1.8757520873088072 	 Accuracy: 0.20078226857887874
Delta: 0.014705380401165967 	  Loss: 1.7384197569950115 	 Accuracy: 0.19165580182529335
Delta: 0.01320865625453889 	  Loss: 1.6751306943692352 	 Accuracy: 0.18904823989569752
Delta: 0.011920627062926502 	  Loss: 1.6488161537390469 	 Accuracy: 0.1864406779661017
Delta: 0.00955694373470335 	  Loss: 1.6365065322622754 	 Accuracy: 0.18252933507170796

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008088071845540978 	  Loss: 1.6319240328761577 	 Accuracy: 0.1877444589308996
Delta: 0.0061354867069787775 	  Loss: 1.6300897147170883 	 Accuracy: 0.1864406779661017
Delta: 0.005683591544622037 	  Loss: 1.6305438552725127 	 Accuracy: 0.1864406779661017
Delta: 0.0045265238665067485 	  Loss: 1.6299951762921343 	 Accuracy: 0.1864406779661017
Delta: 0.003367407619246642 	  Loss: 1.6300275554523214 	 Accuracy: 0.1877444589308996
Delta: 0.004255210224968866 	  Loss: 1.6305267072338523 	 Accuracy: 0.1877444589308996
Delta: 0.002719183322537055 	  Loss: 1.63025795015146 	 Accuracy: 0.1877444589308996
Delta: 0.00282796195027959 	  Loss: 1.6301185548506862 	 Accuracy: 0.1877444589308996
Delta: 0.002345744929536005 	  Loss: 1.6300328072622186 	 Accuracy: 0.1877444589308996
Delta: 0.003170439808341153 	  Loss: 1.6302145199263158 	 Accuracy: 0.1877444589308996
Delta: 0.0011436569488248564 	  Loss: 1.6299918090112557 	 Accuracy: 0.1877444589308996
Delta: 0.0014603921585847812 	  Loss: 1.6299524418356464 	 Accuracy: 0.1877444589308996
Delta: 0.0007527623328251979 	  Loss: 1.6298296053605315 	 Accuracy: 0.19035202086049544
Delta: 0.003865174812239162 	  Loss: 1.6296053393819463 	 Accuracy: 0.1877444589308996
Delta: 0.003242789396385512 	  Loss: 1.630231827384295 	 Accuracy: 0.18904823989569752
Delta: 0.002670462538156097 	  Loss: 1.630104421429386 	 Accuracy: 0.18904823989569752
Delta: 0.003062002196124871 	  Loss: 1.6301335179714407 	 Accuracy: 0.18904823989569752
Delta: 0.0030746691769570713 	  Loss: 1.630299128405261 	 Accuracy: 0.1877444589308996
Delta: 0.003792588011959884 	  Loss: 1.6301939134933736 	 Accuracy: 0.19295958279009126
Delta: 0.0005917230493652771 	  Loss: 1.6302648258850423 	 Accuracy: 0.19035202086049544
Delta: 0.0021034145755529526 	  Loss: 1.629993651957296 	 Accuracy: 0.19035202086049544
Delta: 0.0006503325523977171 	  Loss: 1.6300809721973688 	 Accuracy: 0.1877444589308996
Delta: 0.0009053375412024442 	  Loss: 1.63019542741781 	 Accuracy: 0.18904823989569752
Delta: 0.0037054558148475144 	  Loss: 1.6302194093628892 	 Accuracy: 0.1877444589308996
Delta: 0.0030345382940334406 	  Loss: 1.6298097455190539 	 Accuracy: 0.18904823989569752
Delta: 0.0018303605919303778 	  Loss: 1.6302787033496684 	 Accuracy: 0.19035202086049544
Delta: 0.0007602877711840443 	  Loss: 1.6302670112444324 	 Accuracy: 0.18904823989569752
Delta: 0.0028059748971451443 	  Loss: 1.630355249208161 	 Accuracy: 0.18904823989569752
Delta: 0.0006720580075688834 	  Loss: 1.6307149615229695 	 Accuracy: 0.19035202086049544
Delta: 0.00417021332099792 	  Loss: 1.630594391327612 	 Accuracy: 0.18904823989569752
Delta: 0.002078054545109264 	  Loss: 1.630632215323368 	 Accuracy: 0.1877444589308996
Delta: 0.0016655499139842309 	  Loss: 1.6307461216284687 	 Accuracy: 0.1877444589308996
Delta: 0.0019350576617716277 	  Loss: 1.6306984010844179 	 Accuracy: 0.1877444589308996
Delta: 0.005593010184578862 	  Loss: 1.6313635606444148 	 Accuracy: 0.1877444589308996
Delta: 0.0025275668685531046 	  Loss: 1.6312902649364864 	 Accuracy: 0.19035202086049544
Delta: 0.003011663764148044 	  Loss: 1.630636691752047 	 Accuracy: 0.19035202086049544
Delta: 0.0043074455805545316 	  Loss: 1.6306003073455138 	 Accuracy: 0.19035202086049544
Delta: 6.875630869072593e-05 	  Loss: 1.6307596117255172 	 Accuracy: 0.1877444589308996
Delta: 0.0017516114793561966 	  Loss: 1.630666222263924 	 Accuracy: 0.1877444589308996
Delta: 0.004176367622606804 	  Loss: 1.6316207097385846 	 Accuracy: 0.18904823989569752
Delta: 0.004284498077430061 	  Loss: 1.6307463708646335 	 Accuracy: 0.18904823989569752
Delta: 0.0021440117151808975 	  Loss: 1.6309408965766277 	 Accuracy: 0.1877444589308996
Delta: 0.0034612144170054807 	  Loss: 1.6307691204750618 	 Accuracy: 0.1877444589308996
Delta: 0.0012754090196237067 	  Loss: 1.6307950640495061 	 Accuracy: 0.1877444589308996
Delta: 0.0005061543313009812 	  Loss: 1.6308201698698295 	 Accuracy: 0.1877444589308996
Delta: 0.0020424067808769695 	  Loss: 1.6315755554981797 	 Accuracy: 0.1877444589308996
Delta: 0.0031799183670619662 	  Loss: 1.6303608277406003 	 Accuracy: 0.1877444589308996
Delta: 0.001785684941668679 	  Loss: 1.6313443210952476 	 Accuracy: 0.1877444589308996
Delta: 0.0019557394159062033 	  Loss: 1.6308519343957004 	 Accuracy: 0.1877444589308996
Delta: 2.4853065901969436e-05 	  Loss: 1.6308720630167093 	 Accuracy: 0.1877444589308996
Delta: 0.0024100547282125983 	  Loss: 1.6316777611528646 	 Accuracy: 0.19035202086049544
Delta: 0.0038300860945615473 	  Loss: 1.630124185099099 	 Accuracy: 0.18513689700130379
Delta: 0.002061407555491998 	  Loss: 1.6314764904450325 	 Accuracy: 0.18904823989569752
Delta: 0.0025908368139548376 	  Loss: 1.630567266527871 	 Accuracy: 0.18904823989569752
Delta: 9.670169357125363e-05 	  Loss: 1.6310224074871873 	 Accuracy: 0.18904823989569752
Delta: 0.0017874337732438374 	  Loss: 1.6307686126669059 	 Accuracy: 0.18904823989569752
Delta: 0.002865271729525273 	  Loss: 1.6309318794243288 	 Accuracy: 0.18904823989569752
Delta: 0.003924096276364067 	  Loss: 1.6309875709454307 	 Accuracy: 0.18904823989569752
Delta: 0.002803341332966075 	  Loss: 1.6308897026571982 	 Accuracy: 0.18904823989569752
Delta: 0.0028738420321359134 	  Loss: 1.6310687210751138 	 Accuracy: 0.18904823989569752
Delta: 4.573053269785211e-05 	  Loss: 1.631073340579651 	 Accuracy: 0.18904823989569752
Delta: 0.002155672905123328 	  Loss: 1.631361217959281 	 Accuracy: 0.18904823989569752
Delta: 0.0017711010548528854 	  Loss: 1.6310646297387503 	 Accuracy: 0.18904823989569752
Delta: 0.002611219831945132 	  Loss: 1.6310317430631351 	 Accuracy: 0.18904823989569752
Delta: 0.0023205345505248214 	  Loss: 1.6311063840138043 	 Accuracy: 0.18904823989569752
Delta: 8.434566155441632e-05 	  Loss: 1.6313647002725216 	 Accuracy: 0.18904823989569752
Delta: 0.0016054197263478981 	  Loss: 1.631225818618281 	 Accuracy: 0.18904823989569752
Delta: 0.0011927193904772261 	  Loss: 1.6309842597515134 	 Accuracy: 0.18904823989569752
Delta: 0.0023569556871766277 	  Loss: 1.6314746367424768 	 Accuracy: 0.1877444589308996
Delta: 0.002634927405933663 	  Loss: 1.631876409117417 	 Accuracy: 0.1877444589308996
Delta: 0.003381121742123927 	  Loss: 1.6316735240421227 	 Accuracy: 0.1877444589308996
Delta: 0.0008618657976777985 	  Loss: 1.6315914450015796 	 Accuracy: 0.18513689700130379
Delta: 0.0030476370397208023 	  Loss: 1.6321792286877232 	 Accuracy: 0.1864406779661017
Delta: 0.0022141601859377528 	  Loss: 1.6319385770841444 	 Accuracy: 0.1864406779661017
Delta: 0.0010235307926121516 	  Loss: 1.6319235324850783 	 Accuracy: 0.1864406779661017
Delta: 0.00257199054550203 	  Loss: 1.6322018169915349 	 Accuracy: 0.1864406779661017
Delta: 0.0026163390025822453 	  Loss: 1.6324024749976782 	 Accuracy: 0.1864406779661017
Delta: 0.00010496365149446274 	  Loss: 1.6322401653571215 	 Accuracy: 0.1864406779661017
Delta: 0.0016501396327416944 	  Loss: 1.632258874109099 	 Accuracy: 0.1864406779661017
Delta: 0.002193311354963538 	  Loss: 1.6320803845097551 	 Accuracy: 0.18513689700130379
Delta: 7.893205915667145e-05 	  Loss: 1.6324683624494563 	 Accuracy: 0.1864406779661017
Delta: 4.9737037358180265e-05 	  Loss: 1.632214528669171 	 Accuracy: 0.1864406779661017
Delta: 5.289498559679952e-05 	  Loss: 1.6324197502130506 	 Accuracy: 0.18513689700130379
Delta: 0.0023612889573332426 	  Loss: 1.6322722155852034 	 Accuracy: 0.1864406779661017
Delta: 0.0036784232154547167 	  Loss: 1.6319688751433998 	 Accuracy: 0.1864406779661017
Delta: 0.0011760156612668979 	  Loss: 1.6321605818048484 	 Accuracy: 0.1864406779661017
Delta: 0.003757542421571754 	  Loss: 1.6324208348401168 	 Accuracy: 0.1877444589308996
Delta: 0.0029578892655594607 	  Loss: 1.6320209852252496 	 Accuracy: 0.1877444589308996
Delta: 0.0010825635773411314 	  Loss: 1.6319471409026178 	 Accuracy: 0.1877444589308996
Delta: 0.0018601106812422775 	  Loss: 1.6320921621681161 	 Accuracy: 0.18252933507170796
Delta: 0.004925247162104668 	  Loss: 1.634865542012741 	 Accuracy: 0.1877444589308996
Delta: 0.003607944539792669 	  Loss: 1.6324609940809705 	 Accuracy: 0.1864406779661017
Delta: 0.0040389932981973456 	  Loss: 1.6330873589297044 	 Accuracy: 0.1864406779661017
Delta: 0.021050261744785605 	  Loss: 2.15840768881752 	 Accuracy: 0.2046936114732725
Delta: 0.01884838251304777 	  Loss: 2.0538322415447547 	 Accuracy: 0.22164276401564537
Delta: 0.017623600198837498 	  Loss: 1.8725115277233984 	 Accuracy: 0.2046936114732725
Delta: 0.014909157159062823 	  Loss: 1.7296194423774491 	 Accuracy: 0.19556714471968709
Delta: 0.012639356966617093 	  Loss: 1.672842802043376 	 Accuracy: 0.19295958279009126

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.011203274541028745 	  Loss: 1.6518859459517103 	 Accuracy: 0.19947848761408082
Delta: 0.009168351576393511 	  Loss: 1.645222067204708 	 Accuracy: 0.20078226857887874
Delta: 0.006992973536370108 	  Loss: 1.6429692739413222 	 Accuracy: 0.19556714471968709
Delta: 0.0057734339554503 	  Loss: 1.642664644065099 	 Accuracy: 0.19426336375488917
Delta: 0.006219870125891688 	  Loss: 1.642509312887806 	 Accuracy: 0.19426336375488917
Delta: 0.004276421166010545 	  Loss: 1.6425288067497341 	 Accuracy: 0.19426336375488917
Delta: 0.003545274605576269 	  Loss: 1.6427505397252524 	 Accuracy: 0.19426336375488917
Delta: 0.0028611959876661546 	  Loss: 1.6427575846817248 	 Accuracy: 0.19426336375488917
Delta: 0.004159822789280881 	  Loss: 1.6424661982015152 	 Accuracy: 0.19426336375488917
Delta: 0.0028169897583668825 	  Loss: 1.6425152400775946 	 Accuracy: 0.19426336375488917
Delta: 0.002185444537507754 	  Loss: 1.642403173401267 	 Accuracy: 0.19426336375488917
Delta: 0.002602548761234503 	  Loss: 1.6424915902942026 	 Accuracy: 0.19426336375488917
Delta: 3.4132741681910804e-05 	  Loss: 1.642475634052901 	 Accuracy: 0.19426336375488917
Delta: 0.0029214510995660783 	  Loss: 1.6420641229693598 	 Accuracy: 0.19426336375488917
Delta: 0.002105358948236497 	  Loss: 1.6423584084374385 	 Accuracy: 0.19426336375488917
Delta: 0.0014380532894697868 	  Loss: 1.6424455212684164 	 Accuracy: 0.19426336375488917
Delta: 0.0022069580488112968 	  Loss: 1.6425094175752277 	 Accuracy: 0.19426336375488917
Delta: 0.002196669296668539 	  Loss: 1.6421733663009683 	 Accuracy: 0.19426336375488917
Delta: 0.0020930823076380795 	  Loss: 1.6425892796204713 	 Accuracy: 0.19426336375488917
Delta: 5.6435193260741785e-05 	  Loss: 1.6423862484319527 	 Accuracy: 0.19426336375488917
Delta: 0.002028798600825013 	  Loss: 1.6427713383906442 	 Accuracy: 0.19426336375488917
Delta: 0.001878022314121176 	  Loss: 1.6421655682756677 	 Accuracy: 0.19556714471968709
Delta: 0.0012039491611102765 	  Loss: 1.6424875360170783 	 Accuracy: 0.19426336375488917
Delta: 0.0024033045334484297 	  Loss: 1.642431940096198 	 Accuracy: 0.19426336375488917
Delta: 0.0019540523851091316 	  Loss: 1.6425314731166467 	 Accuracy: 0.19426336375488917
Delta: 0.002707563321603501 	  Loss: 1.6423416056935112 	 Accuracy: 0.19295958279009126
Delta: 0.00137757044252047 	  Loss: 1.6422384617922685 	 Accuracy: 0.19426336375488917
Delta: 0.0017953875063949072 	  Loss: 1.642659648569547 	 Accuracy: 0.19426336375488917
Delta: 0.0027465851762576697 	  Loss: 1.6428067304011376 	 Accuracy: 0.19426336375488917
Delta: 0.0025546067936880654 	  Loss: 1.6424453734184705 	 Accuracy: 0.18904823989569752
Delta: 0.0012172080846239747 	  Loss: 1.6423462357061578 	 Accuracy: 0.19426336375488917
Delta: 0.0006373991838716422 	  Loss: 1.6422808009299823 	 Accuracy: 0.19426336375488917
Delta: 0.0016710581467565522 	  Loss: 1.6425773288351382 	 Accuracy: 0.19426336375488917
Delta: 1.5331741320365377e-05 	  Loss: 1.6425636609254963 	 Accuracy: 0.19426336375488917
Delta: 0.0016416884731337402 	  Loss: 1.6427355112125999 	 Accuracy: 0.19426336375488917
Delta: 0.002838029242088739 	  Loss: 1.6430925958588682 	 Accuracy: 0.19426336375488917
Delta: 0.0007822616353929749 	  Loss: 1.6432876613506204 	 Accuracy: 0.19295958279009126
Delta: 0.0031956200116106176 	  Loss: 1.6442463593978969 	 Accuracy: 0.19556714471968709
Delta: 0.0024520899892889574 	  Loss: 1.644442305374605 	 Accuracy: 0.19295958279009126
Delta: 0.0014467383669781299 	  Loss: 1.6442883502603276 	 Accuracy: 0.19295958279009126
Delta: 0.0016636860873449862 	  Loss: 1.6441067373346052 	 Accuracy: 0.19295958279009126
Delta: 0.0041049840605148335 	  Loss: 1.6444164414378961 	 Accuracy: 0.19295958279009126
Delta: 0.0021550429757235105 	  Loss: 1.6447648533222252 	 Accuracy: 0.19426336375488917
Delta: 0.0017249777703499504 	  Loss: 1.644193417210023 	 Accuracy: 0.19426336375488917
Delta: 0.0038050059124623767 	  Loss: 1.6437472220432545 	 Accuracy: 0.19426336375488917
Delta: 0.0030544817256280303 	  Loss: 1.6427391120429928 	 Accuracy: 0.19426336375488917
Delta: 0.004501161450492348 	  Loss: 1.643011881925513 	 Accuracy: 0.196870925684485
Delta: 0.005051515907240567 	  Loss: 1.6430858175678886 	 Accuracy: 0.19295958279009126
Delta: 0.0028948532960314127 	  Loss: 1.6429171116195158 	 Accuracy: 0.19295958279009126
Delta: 0.000926700957505892 	  Loss: 1.6431532645523976 	 Accuracy: 0.19165580182529335
Delta: 0.002803620386914311 	  Loss: 1.643392653687316 	 Accuracy: 0.19295958279009126
Delta: 0.002578051416020213 	  Loss: 1.6433004277285637 	 Accuracy: 0.19295958279009126
Delta: 6.12467580506917e-05 	  Loss: 1.6430996632435089 	 Accuracy: 0.19165580182529335
Delta: 0.002830540086651067 	  Loss: 1.6429851533056268 	 Accuracy: 0.19295958279009126
Delta: 0.0036201191702315465 	  Loss: 1.6429059946377216 	 Accuracy: 0.19295958279009126
Delta: 0.0026777303936588465 	  Loss: 1.6438064120499236 	 Accuracy: 0.19426336375488917
Delta: 0.000608319174463572 	  Loss: 1.6429544544528538 	 Accuracy: 0.19295958279009126
Delta: 0.0023860302087154697 	  Loss: 1.6432565984249778 	 Accuracy: 0.19295958279009126
Delta: 0.0016277193414009454 	  Loss: 1.6433500848095393 	 Accuracy: 0.19295958279009126
Delta: 0.0031940862451579517 	  Loss: 1.6434298029538459 	 Accuracy: 0.19295958279009126
Delta: 5.30534250047547e-05 	  Loss: 1.6434983056097716 	 Accuracy: 0.19165580182529335
Delta: 0.004160619394526058 	  Loss: 1.6438832812733069 	 Accuracy: 0.19295958279009126
Delta: 0.0027590665304267213 	  Loss: 1.6434828511609885 	 Accuracy: 0.19165580182529335
Delta: 0.0021698485620918846 	  Loss: 1.6432459819831973 	 Accuracy: 0.19295958279009126
Delta: 0.0012117709979525158 	  Loss: 1.643356263657195 	 Accuracy: 0.19295958279009126
Delta: 0.0012056374790958566 	  Loss: 1.6433948680237906 	 Accuracy: 0.19295958279009126
Delta: 0.0008014842422386923 	  Loss: 1.6434519341798817 	 Accuracy: 0.19165580182529335
Delta: 0.0007413607038078684 	  Loss: 1.6433537409138013 	 Accuracy: 0.19295958279009126
Delta: 3.153521035138774e-05 	  Loss: 1.6433425034682978 	 Accuracy: 0.19556714471968709
Delta: 8.601081868732167e-05 	  Loss: 1.6434087322180841 	 Accuracy: 0.19295958279009126
Delta: 1.8682957696633685e-05 	  Loss: 1.6433892766738623 	 Accuracy: 0.19295958279009126
Delta: 0.0005402846336837856 	  Loss: 1.6434088775624973 	 Accuracy: 0.19295958279009126
Delta: 0.002552015755858596 	  Loss: 1.6434254790159357 	 Accuracy: 0.19165580182529335
Delta: 0.0012506560588497438 	  Loss: 1.6436014474703935 	 Accuracy: 0.19295958279009126
Delta: 2.950429771467874e-05 	  Loss: 1.6434806403737148 	 Accuracy: 0.19426336375488917
Delta: 0.0020152412529133193 	  Loss: 1.6431977849734687 	 Accuracy: 0.19295958279009126
Delta: 0.001111602812095519 	  Loss: 1.643261203099735 	 Accuracy: 0.19165580182529335
Delta: 0.0012309520333214166 	  Loss: 1.643442745680592 	 Accuracy: 0.19295958279009126
Delta: 0.0018549847697762745 	  Loss: 1.643587722986435 	 Accuracy: 0.19295958279009126
Delta: 0.0017746870853635624 	  Loss: 1.6433955214319442 	 Accuracy: 0.19165580182529335
Delta: 1.2703765852234996e-05 	  Loss: 1.6434226206832534 	 Accuracy: 0.19295958279009126
Delta: 9.160712401231153e-05 	  Loss: 1.643283608751744 	 Accuracy: 0.19295958279009126
Delta: 6.45816158791526e-05 	  Loss: 1.6433616794147112 	 Accuracy: 0.19295958279009126
Delta: 3.900296765875464e-06 	  Loss: 1.643346304335543 	 Accuracy: 0.19295958279009126
Delta: 0.0005484563003568422 	  Loss: 1.6432913214078002 	 Accuracy: 0.19295958279009126
Delta: 0.0005489659502621908 	  Loss: 1.6431753534765674 	 Accuracy: 0.19295958279009126
Delta: 0.00461000941438862 	  Loss: 1.6429903379106643 	 Accuracy: 0.19295958279009126
Delta: 0.005121145345755638 	  Loss: 1.6437997826983413 	 Accuracy: 0.2033898305084746
Delta: 0.0013412337616818695 	  Loss: 1.643652848898541 	 Accuracy: 0.19426336375488917
Delta: 8.200603784339988e-05 	  Loss: 1.6439007444514795 	 Accuracy: 0.19165580182529335
Delta: 0.0022859965923186097 	  Loss: 1.643899475255647 	 Accuracy: 0.19165580182529335
Delta: 0.001386793363248566 	  Loss: 1.6439528294617245 	 Accuracy: 0.17992177314211213
Delta: 0.006571464509713324 	  Loss: 1.645925282141697 	 Accuracy: 0.19295958279009126
Delta: 0.0057087987581975926 	  Loss: 1.644971154527988 	 Accuracy: 0.19426336375488917
Delta: 0.005328395062145591 	  Loss: 1.6434820310056373 	 Accuracy: 0.19426336375488917
Delta: 0.021206262740454236 	  Loss: 2.156571847531217 	 Accuracy: 0.2033898305084746
Delta: 0.018438861569807088 	  Loss: 2.047081195612483 	 Accuracy: 0.15514993481095177
Delta: 0.017251603347603398 	  Loss: 1.8581054941359487 	 Accuracy: 0.18122555410691005
Delta: 0.015183314882446397 	  Loss: 1.7255539865395715 	 Accuracy: 0.1681877444589309
Delta: 0.011570020812804723 	  Loss: 1.6829225861769608 	 Accuracy: 0.17470664928292046
Delta: 0.009771563587009766 	  Loss: 1.6736386637534348 	 Accuracy: 0.18122555410691005
Delta: 0.007205295903951927 	  Loss: 1.6702362603430012 	 Accuracy: 0.17861799217731422

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007661242262249225 	  Loss: 1.6697365496387016 	 Accuracy: 0.17992177314211213
Delta: 0.004246074686353896 	  Loss: 1.66962199987651 	 Accuracy: 0.17861799217731422
Delta: 0.004065355536985576 	  Loss: 1.6696155482656423 	 Accuracy: 0.17861799217731422
Delta: 0.0024750466065410247 	  Loss: 1.669648772382684 	 Accuracy: 0.17861799217731422
Delta: 0.00011660205907782444 	  Loss: 1.6696319208106414 	 Accuracy: 0.17861799217731422
Delta: 0.0022919768448577465 	  Loss: 1.6695205571991663 	 Accuracy: 0.17992177314211213
Delta: 0.003104207298201492 	  Loss: 1.6694551701883704 	 Accuracy: 0.17992177314211213
Delta: 0.0023618119345896736 	  Loss: 1.6694767261208696 	 Accuracy: 0.17992177314211213
Delta: 0.0032836184836617863 	  Loss: 1.6694717465893094 	 Accuracy: 0.18122555410691005
Delta: 0.0034528497997291423 	  Loss: 1.6691869452400674 	 Accuracy: 0.17992177314211213
Delta: 0.001477903175738532 	  Loss: 1.6693802771992599 	 Accuracy: 0.17992177314211213
Delta: 0.0031097104040861898 	  Loss: 1.6697697238180838 	 Accuracy: 0.17861799217731422
Delta: 0.003127654575343953 	  Loss: 1.6711373805519407 	 Accuracy: 0.17861799217731422
Delta: 4.107825628177825e-05 	  Loss: 1.6712257039567995 	 Accuracy: 0.17861799217731422
Delta: 0.0005387947363833208 	  Loss: 1.6707687557792161 	 Accuracy: 0.17861799217731422
Delta: 3.240074397592171e-05 	  Loss: 1.6707776896326967 	 Accuracy: 0.17861799217731422
Delta: 0.001288792325825274 	  Loss: 1.6710961881476922 	 Accuracy: 0.17861799217731422
Delta: 0.0009975781133313287 	  Loss: 1.671074447619034 	 Accuracy: 0.17861799217731422
Delta: 8.318151840314745e-06 	  Loss: 1.6710822371101248 	 Accuracy: 0.17861799217731422
Delta: 0.0017617125970277939 	  Loss: 1.6706242455013403 	 Accuracy: 0.17861799217731422
Delta: 0.0007274930150380518 	  Loss: 1.670787760711348 	 Accuracy: 0.17861799217731422
Delta: 0.0033085943458878637 	  Loss: 1.671205614420247 	 Accuracy: 0.1773142112125163
Delta: 0.0017150789868647248 	  Loss: 1.6710982579339535 	 Accuracy: 0.17861799217731422
Delta: 0.001246169963564978 	  Loss: 1.6710951698992063 	 Accuracy: 0.17861799217731422
Delta: 0.0012948754398629328 	  Loss: 1.6711920442573667 	 Accuracy: 0.17992177314211213
Delta: 0.0006610549632748585 	  Loss: 1.6711509770893451 	 Accuracy: 0.17861799217731422
Delta: 0.0017655143272085532 	  Loss: 1.6711271854845262 	 Accuracy: 0.17992177314211213
Delta: 0.00404849410295206 	  Loss: 1.6710558148782828 	 Accuracy: 0.17992177314211213
Delta: 0.0028840113600226243 	  Loss: 1.6711015145972157 	 Accuracy: 0.17992177314211213
Delta: 0.0017553019807739862 	  Loss: 1.6710759751858806 	 Accuracy: 0.17992177314211213
Delta: 0.000819899542924285 	  Loss: 1.6710808855302088 	 Accuracy: 0.17992177314211213
Delta: 0.004450014162885035 	  Loss: 1.6710867509830556 	 Accuracy: 0.17992177314211213
Delta: 0.0007726085220710419 	  Loss: 1.6711016499397506 	 Accuracy: 0.17992177314211213
Delta: 0.004692433614149381 	  Loss: 1.6708662979937008 	 Accuracy: 0.17992177314211213
Delta: 0.0022778597597755265 	  Loss: 1.670686515875257 	 Accuracy: 0.17992177314211213
Delta: 0.0031669065087198455 	  Loss: 1.6709525696405247 	 Accuracy: 0.17992177314211213
Delta: 0.0034278449098611484 	  Loss: 1.6713167920849117 	 Accuracy: 0.17992177314211213
Delta: 0.0033305332321249574 	  Loss: 1.6708457431721322 	 Accuracy: 0.17992177314211213
Delta: 0.0008249518102950345 	  Loss: 1.671019856045775 	 Accuracy: 0.17861799217731422
Delta: 0.0019160703652174355 	  Loss: 1.670768279659876 	 Accuracy: 0.17992177314211213
Delta: 0.0019902007911405738 	  Loss: 1.6708024922981397 	 Accuracy: 0.17992177314211213
Delta: 0.0019662021208147365 	  Loss: 1.670914306854727 	 Accuracy: 0.17992177314211213
Delta: 0.0035528872246754725 	  Loss: 1.6711146961079977 	 Accuracy: 0.17992177314211213
Delta: 0.004687336582266532 	  Loss: 1.6712563120800756 	 Accuracy: 0.17992177314211213
Delta: 0.002261088642180542 	  Loss: 1.6714442758216652 	 Accuracy: 0.17992177314211213
Delta: 0.0026124060558732334 	  Loss: 1.6708903167869122 	 Accuracy: 0.17992177314211213
Delta: 0.0036747760980586903 	  Loss: 1.6709861379779576 	 Accuracy: 0.17992177314211213
Delta: 0.0018179039707178846 	  Loss: 1.671084081348275 	 Accuracy: 0.17992177314211213
Delta: 0.0012614589053480518 	  Loss: 1.6709207853960368 	 Accuracy: 0.17992177314211213
Delta: 0.0036280919050901256 	  Loss: 1.671001358694797 	 Accuracy: 0.17992177314211213
Delta: 0.004716958931361498 	  Loss: 1.671125815165737 	 Accuracy: 0.17992177314211213
Delta: 0.003245949487077646 	  Loss: 1.6710993789496538 	 Accuracy: 0.17992177314211213
Delta: 0.0014105620792918372 	  Loss: 1.6707764871549262 	 Accuracy: 0.18122555410691005
Delta: 0.0035167496425240596 	  Loss: 1.6711582528853444 	 Accuracy: 0.17861799217731422
Delta: 0.0033348299420241033 	  Loss: 1.6715301614677163 	 Accuracy: 0.17992177314211213
Delta: 0.0014913906587611 	  Loss: 1.6715351373618303 	 Accuracy: 0.18252933507170796
Delta: 0.002517428739236754 	  Loss: 1.672025244320287 	 Accuracy: 0.18252933507170796
Delta: 0.0027968104530444416 	  Loss: 1.6722336260135071 	 Accuracy: 0.17992177314211213
Delta: 0.0028155486590403897 	  Loss: 1.6723512250905 	 Accuracy: 0.18122555410691005
Delta: 0.005409964276437484 	  Loss: 1.6724167204056464 	 Accuracy: 0.17992177314211213
Delta: 0.003031494918176998 	  Loss: 1.672103130868383 	 Accuracy: 0.18122555410691005
Delta: 0.004780232651388186 	  Loss: 1.6719197456407366 	 Accuracy: 0.17992177314211213
Delta: 0.006174958351425385 	  Loss: 1.6736131048425018 	 Accuracy: 0.18122555410691005
Delta: 0.004232776100328169 	  Loss: 1.6734159002476985 	 Accuracy: 0.18252933507170796
Delta: 0.004325084889124564 	  Loss: 1.6736323685762622 	 Accuracy: 0.18122555410691005
Delta: 0.0046193952260622315 	  Loss: 1.674008853283624 	 Accuracy: 0.18122555410691005
Delta: 0.004236052799303765 	  Loss: 1.6741259526304284 	 Accuracy: 0.18122555410691005
Delta: 0.001929837070142901 	  Loss: 1.6741216643901113 	 Accuracy: 0.17861799217731422
Delta: 0.0023347266609691966 	  Loss: 1.674151328164164 	 Accuracy: 0.18122555410691005
Delta: 0.0017423604484945708 	  Loss: 1.6742705369868203 	 Accuracy: 0.18122555410691005
Delta: 0.0017192460818765084 	  Loss: 1.674020093697133 	 Accuracy: 0.18252933507170796
Delta: 0.0016891245730842424 	  Loss: 1.6737459451101597 	 Accuracy: 0.17992177314211213
Delta: 0.0018159448107348266 	  Loss: 1.6740490101030092 	 Accuracy: 0.18122555410691005
Delta: 9.604247114920269e-05 	  Loss: 1.6742291609540432 	 Accuracy: 0.19947848761408082
Delta: 9.126178657411466e-05 	  Loss: 1.674345987605587 	 Accuracy: 0.18122555410691005
Delta: 0.0034112110203947587 	  Loss: 1.6739036621020906 	 Accuracy: 0.18252933507170796
Delta: 0.003280553083796053 	  Loss: 1.6738566046175758 	 Accuracy: 0.18252933507170796
Delta: 0.0006513666481648493 	  Loss: 1.674080780358386 	 Accuracy: 0.18252933507170796
Delta: 0.002867554161944771 	  Loss: 1.674823465113188 	 Accuracy: 0.18122555410691005
Delta: 0.0023193593249942134 	  Loss: 1.6751522739631328 	 Accuracy: 0.18122555410691005
Delta: 2.2430874295855335e-05 	  Loss: 1.675035540654818 	 Accuracy: 0.18122555410691005
Delta: 0.002830877396007293 	  Loss: 1.6751161747683119 	 Accuracy: 0.18122555410691005
Delta: 0.0018171099229226347 	  Loss: 1.6750428550156844 	 Accuracy: 0.18122555410691005
Delta: 0.004683707155077191 	  Loss: 1.6760156218734732 	 Accuracy: 0.18122555410691005
Delta: 0.0029541048322915134 	  Loss: 1.675989807478414 	 Accuracy: 0.18122555410691005
Delta: 0.0016641834202232426 	  Loss: 1.675883450378545 	 Accuracy: 0.18383311603650587
Delta: 0.0011956713064473225 	  Loss: 1.6760476723770192 	 Accuracy: 0.18383311603650587
Delta: 1.7641580355870526e-06 	  Loss: 1.6760445126969348 	 Accuracy: 0.18122555410691005
Delta: 7.112318246116115e-05 	  Loss: 1.675779921289156 	 Accuracy: 0.17992177314211213
Delta: 0.003137695187198704 	  Loss: 1.675826021561309 	 Accuracy: 0.18122555410691005
Delta: 0.002163873919100305 	  Loss: 1.6759468987267123 	 Accuracy: 0.18122555410691005
Delta: 0.0005613146524623611 	  Loss: 1.6759408129447815 	 Accuracy: 0.18122555410691005
Delta: 0.005434366519171142 	  Loss: 1.6770602230688783 	 Accuracy: 0.18122555410691005
Delta: 0.021066591253446426 	  Loss: 2.1581627530357297 	 Accuracy: 0.20208604954367665
Delta: 0.01870996959418595 	  Loss: 2.049300254247737 	 Accuracy: 0.19165580182529335
Delta: 0.017235906786337435 	  Loss: 1.8718624530938657 	 Accuracy: 0.19426336375488917
Delta: 0.01611663549280602 	  Loss: 1.7505689828003503 	 Accuracy: 0.19426336375488917
Delta: 0.0148255718112637 	  Loss: 1.6781021051198044 	 Accuracy: 0.20208604954367665
Delta: 0.01171797850743881 	  Loss: 1.643608533305069 	 Accuracy: 0.21121251629726207
Delta: 0.009335398334263932 	  Loss: 1.631384564371516 	 Accuracy: 0.21773142112125163

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006997104868959787 	  Loss: 1.6286845957579454 	 Accuracy: 0.21642764015645372
Delta: 0.0055439568914373745 	  Loss: 1.628274762896134 	 Accuracy: 0.2151238591916558
Delta: 0.0047581408674332555 	  Loss: 1.628332433481853 	 Accuracy: 0.21773142112125163
Delta: 0.0039568466169138655 	  Loss: 1.6284445087626758 	 Accuracy: 0.21642764015645372
Delta: 0.0017712045063668278 	  Loss: 1.6283298053946704 	 Accuracy: 0.21642764015645372
Delta: 0.0021687530907709995 	  Loss: 1.6281262531787908 	 Accuracy: 0.21642764015645372
Delta: 0.0007892388307723363 	  Loss: 1.6281349959451275 	 Accuracy: 0.21642764015645372
Delta: 3.940917277135541e-05 	  Loss: 1.6283124337070414 	 Accuracy: 0.21642764015645372
Delta: 1.7538732964278644e-05 	  Loss: 1.628197992957985 	 Accuracy: 0.21642764015645372
Delta: 1.2385995814400235e-05 	  Loss: 1.628235379441723 	 Accuracy: 0.21642764015645372
Delta: 0.0027690106103286124 	  Loss: 1.6279067916618823 	 Accuracy: 0.21642764015645372
Delta: 0.005226996072480179 	  Loss: 1.6272346805635176 	 Accuracy: 0.21642764015645372
Delta: 0.0027230060138232967 	  Loss: 1.6266514403038037 	 Accuracy: 0.21642764015645372
Delta: 4.5920080711313976e-05 	  Loss: 1.6270658171640395 	 Accuracy: 0.2138200782268579
Delta: 0.002820029800990764 	  Loss: 1.6278660708055481 	 Accuracy: 0.2151238591916558
Delta: 0.0017574783268200663 	  Loss: 1.628200113741488 	 Accuracy: 0.21642764015645372
Delta: 9.247210623896728e-05 	  Loss: 1.6278188626931622 	 Accuracy: 0.2151238591916558
Delta: 0.0024663811588443423 	  Loss: 1.6285321003633482 	 Accuracy: 0.2151238591916558
Delta: 0.0013278818631775242 	  Loss: 1.628280106527132 	 Accuracy: 0.2151238591916558
Delta: 0.002566042202521796 	  Loss: 1.6283380265466556 	 Accuracy: 0.2151238591916558
Delta: 0.001973387288945335 	  Loss: 1.628083857800163 	 Accuracy: 0.2138200782268579
Delta: 0.002530167707897385 	  Loss: 1.6286262345717484 	 Accuracy: 0.2151238591916558
Delta: 0.0021921382469578007 	  Loss: 1.628303373010897 	 Accuracy: 0.2151238591916558
Delta: 0.0021243733994542975 	  Loss: 1.628340374429337 	 Accuracy: 0.2151238591916558
Delta: 0.002291907748613128 	  Loss: 1.6285734783779282 	 Accuracy: 0.2151238591916558
Delta: 0.0008631401193941329 	  Loss: 1.6284016609378464 	 Accuracy: 0.2151238591916558
Delta: 0.0035788110130358943 	  Loss: 1.6286809875491137 	 Accuracy: 0.2151238591916558
Delta: 0.003021782059773912 	  Loss: 1.6287726046832212 	 Accuracy: 0.2138200782268579
Delta: 0.003306548073188376 	  Loss: 1.6289114797887891 	 Accuracy: 0.2151238591916558
Delta: 0.00170695256420069 	  Loss: 1.6289357816930436 	 Accuracy: 0.2151238591916558
Delta: 0.005030284375912055 	  Loss: 1.6299106909539498 	 Accuracy: 0.2151238591916558
Delta: 0.0015731308501395487 	  Loss: 1.6298041881092715 	 Accuracy: 0.2151238591916558
Delta: 0.004288599356179518 	  Loss: 1.6300779474675142 	 Accuracy: 0.21642764015645372
Delta: 0.0024623385913299565 	  Loss: 1.630481642766347 	 Accuracy: 0.21773142112125163
Delta: 0.0016576939280837685 	  Loss: 1.6304730279149076 	 Accuracy: 0.2151238591916558
Delta: 0.00312669813522421 	  Loss: 1.6313161886534842 	 Accuracy: 0.2151238591916558
Delta: 0.002858965686899964 	  Loss: 1.6299138385996224 	 Accuracy: 0.2151238591916558
Delta: 0.0035184971041536083 	  Loss: 1.6299407784357136 	 Accuracy: 0.2151238591916558
Delta: 0.003822728670724934 	  Loss: 1.6297700714676022 	 Accuracy: 0.2151238591916558
Delta: 0.0034792906793546566 	  Loss: 1.6287968308171215 	 Accuracy: 0.2151238591916558
Delta: 7.64473900385486e-05 	  Loss: 1.6288354431740086 	 Accuracy: 0.2151238591916558
Delta: 0.0031775448106465313 	  Loss: 1.6284523352030362 	 Accuracy: 0.2151238591916558
Delta: 0.0033193016777384563 	  Loss: 1.6281659705585394 	 Accuracy: 0.2151238591916558
Delta: 0.002959659914717811 	  Loss: 1.6287519529844943 	 Accuracy: 0.2151238591916558
Delta: 0.0018353765294521942 	  Loss: 1.6287814222876165 	 Accuracy: 0.2151238591916558
Delta: 0.002635833524855423 	  Loss: 1.628393699453574 	 Accuracy: 0.2151238591916558
Delta: 0.0065884092349642554 	  Loss: 1.62790383904541 	 Accuracy: 0.21903520208604954
Delta: 0.004380017958681722 	  Loss: 1.628489350507819 	 Accuracy: 0.2151238591916558
Delta: 0.003514078551994088 	  Loss: 1.6284600139702539 	 Accuracy: 0.2151238591916558
Delta: 0.0022250882265333577 	  Loss: 1.6284432666888828 	 Accuracy: 0.21121251629726207
Delta: 0.002674158962494239 	  Loss: 1.628737915883535 	 Accuracy: 0.2151238591916558
Delta: 0.0029910430852698377 	  Loss: 1.6286544821570152 	 Accuracy: 0.2151238591916558
Delta: 0.004515845531593771 	  Loss: 1.629882700439186 	 Accuracy: 0.2151238591916558
Delta: 0.0039107410795384025 	  Loss: 1.6309909945577625 	 Accuracy: 0.2138200782268579
Delta: 0.00520713521171299 	  Loss: 1.6304186267710563 	 Accuracy: 0.2138200782268579
Delta: 0.0011078133340845096 	  Loss: 1.6302165543457336 	 Accuracy: 0.2151238591916558
Delta: 0.006024238121695165 	  Loss: 1.6290307481768678 	 Accuracy: 0.21642764015645372
Delta: 0.0047736623275903296 	  Loss: 1.6290879352265233 	 Accuracy: 0.21642764015645372
Delta: 0.0013002716446994518 	  Loss: 1.6288757085914396 	 Accuracy: 0.2151238591916558
Delta: 0.00203612573058737 	  Loss: 1.6285871939525944 	 Accuracy: 0.21642764015645372
Delta: 0.0008763612544321379 	  Loss: 1.6287890849279623 	 Accuracy: 0.21642764015645372
Delta: 0.003545435413211497 	  Loss: 1.629770102872897 	 Accuracy: 0.21642764015645372
Delta: 0.0033626994024101094 	  Loss: 1.6296974432975766 	 Accuracy: 0.21903520208604954
Delta: 0.004178781055376153 	  Loss: 1.6304026916795364 	 Accuracy: 0.21642764015645372
Delta: 0.003994074271582126 	  Loss: 1.628919226986788 	 Accuracy: 0.21642764015645372
Delta: 0.003715529544154396 	  Loss: 1.6287066344325578 	 Accuracy: 0.21642764015645372
Delta: 0.003927506176273269 	  Loss: 1.6286836084700653 	 Accuracy: 0.21773142112125163
Delta: 0.006145567650319413 	  Loss: 1.6281886794945257 	 Accuracy: 0.21642764015645372
Delta: 0.004169601015228532 	  Loss: 1.628951398324423 	 Accuracy: 0.21642764015645372
Delta: 0.0033758969310121087 	  Loss: 1.6287787773252564 	 Accuracy: 0.21642764015645372
Delta: 0.0034411658728681926 	  Loss: 1.6289622362019234 	 Accuracy: 0.21642764015645372
Delta: 0.002750226351842406 	  Loss: 1.6283626953707113 	 Accuracy: 0.21642764015645372
Delta: 0.0031752921343227813 	  Loss: 1.6281585579258375 	 Accuracy: 0.2138200782268579
Delta: 0.0038952802905325217 	  Loss: 1.6285070300077442 	 Accuracy: 0.2151238591916558
Delta: 0.0021915959310027885 	  Loss: 1.6278332977276642 	 Accuracy: 0.21251629726205998
Delta: 0.0038993454141166657 	  Loss: 1.6284344990949284 	 Accuracy: 0.2138200782268579
Delta: 0.0015127435089060462 	  Loss: 1.6284719904935783 	 Accuracy: 0.2138200782268579
Delta: 0.00484966839450238 	  Loss: 1.6289963565420513 	 Accuracy: 0.2151238591916558
Delta: 0.0036978848298854627 	  Loss: 1.6289310850403194 	 Accuracy: 0.2151238591916558
Delta: 0.0008797113448249884 	  Loss: 1.6289988078254598 	 Accuracy: 0.2151238591916558
Delta: 0.0018960132603124491 	  Loss: 1.6291540952354935 	 Accuracy: 0.21642764015645372
Delta: 0.0011986037052938157 	  Loss: 1.628827823165488 	 Accuracy: 0.21642764015645372
Delta: 0.002351925182036405 	  Loss: 1.6293679574716053 	 Accuracy: 0.21773142112125163
Delta: 0.0040696211090615365 	  Loss: 1.6301190306751603 	 Accuracy: 0.21642764015645372
Delta: 0.00015035502045088986 	  Loss: 1.6307264878085053 	 Accuracy: 0.21642764015645372
Delta: 0.002120292774360267 	  Loss: 1.6309571083703847 	 Accuracy: 0.21642764015645372
Delta: 0.0018408774036286712 	  Loss: 1.631277855812681 	 Accuracy: 0.2151238591916558
Delta: 0.004553308813264481 	  Loss: 1.6317525298852975 	 Accuracy: 0.2138200782268579
Delta: 0.0019646810806711263 	  Loss: 1.631457182561941 	 Accuracy: 0.2151238591916558
Delta: 0.004483843453390862 	  Loss: 1.6294715262338326 	 Accuracy: 0.21642764015645372
Delta: 0.0038416391127532646 	  Loss: 1.6305852053436363 	 Accuracy: 0.2151238591916558
Delta: 0.003632202846354926 	  Loss: 1.6307790002972689 	 Accuracy: 0.2151238591916558
Delta: 0.0016860047640510887 	  Loss: 1.6308732479524093 	 Accuracy: 0.2151238591916558
Delta: 0.021161125897451713 	  Loss: 2.1569421737389605 	 Accuracy: 0.20078226857887874
Delta: 0.01904183739099412 	  Loss: 2.037814374622642 	 Accuracy: 0.2633637548891786
Delta: 0.017522503819628322 	  Loss: 1.8549902769009035 	 Accuracy: 0.3155149934810952
Delta: 0.015920974939296877 	  Loss: 1.7324593625934814 	 Accuracy: 0.2777053455019557
Delta: 0.013457572754811032 	  Loss: 1.6703010599662624 	 Accuracy: 0.28292046936114734
Delta: 0.009897685112916643 	  Loss: 1.6526749489147345 	 Accuracy: 0.2907431551499348

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008043523591786781 	  Loss: 1.6485131862294313 	 Accuracy: 0.28683181225554105
Delta: 0.005495327046907261 	  Loss: 1.6465487471473041 	 Accuracy: 0.2894393741851369
Delta: 0.005030558306875857 	  Loss: 1.6459742697830393 	 Accuracy: 0.28683181225554105
Delta: 0.0027010704027469793 	  Loss: 1.6453842543080501 	 Accuracy: 0.28683181225554105
Delta: 0.002103608723945756 	  Loss: 1.6452732094219393 	 Accuracy: 0.288135593220339
Delta: 0.002471983090795657 	  Loss: 1.6450854364245937 	 Accuracy: 0.288135593220339
Delta: 0.0005712584381939265 	  Loss: 1.6452711115783825 	 Accuracy: 0.28552803129074317
Delta: 0.0031880626213795014 	  Loss: 1.6451669373616746 	 Accuracy: 0.28552803129074317
Delta: 0.0009816917670637916 	  Loss: 1.6451971834980392 	 Accuracy: 0.28552803129074317
Delta: 0.0009684638907160022 	  Loss: 1.6448595850944736 	 Accuracy: 0.28552803129074317
Delta: 2.7993937227207058e-05 	  Loss: 1.6448955875567466 	 Accuracy: 0.28683181225554105
Delta: 0.0029222716696788165 	  Loss: 1.6450732609817822 	 Accuracy: 0.288135593220339
Delta: 0.002353690077623324 	  Loss: 1.6447889648652916 	 Accuracy: 0.28683181225554105
Delta: 0.00010195157507529325 	  Loss: 1.6446338000049403 	 Accuracy: 0.28552803129074317
Delta: 6.654734963811279e-05 	  Loss: 1.644693139588053 	 Accuracy: 0.28552803129074317
Delta: 0.0008071454414762221 	  Loss: 1.6448513229538069 	 Accuracy: 0.28552803129074317
Delta: 0.0015043372636629497 	  Loss: 1.644611455551164 	 Accuracy: 0.28552803129074317
Delta: 0.0024997361245013305 	  Loss: 1.6442395378481733 	 Accuracy: 0.28683181225554105
Delta: 0.0005836011224393174 	  Loss: 1.644539712410071 	 Accuracy: 0.28552803129074317
Delta: 0.0024093906872893274 	  Loss: 1.644835447904295 	 Accuracy: 0.2842242503259452
Delta: 0.0030800219297197236 	  Loss: 1.64501332129412 	 Accuracy: 0.2842242503259452
Delta: 0.0018264607851807737 	  Loss: 1.645312528161502 	 Accuracy: 0.2842242503259452
Delta: 0.0023684198254945357 	  Loss: 1.6452585557607744 	 Accuracy: 0.28683181225554105
Delta: 0.0030124612551125167 	  Loss: 1.6456415185997102 	 Accuracy: 0.2842242503259452
Delta: 0.002361951387136602 	  Loss: 1.6456285828275967 	 Accuracy: 0.28292046936114734
Delta: 0.003321821028099463 	  Loss: 1.6446412985597516 	 Accuracy: 0.28552803129074317
Delta: 0.0022903368373403963 	  Loss: 1.6445686023434218 	 Accuracy: 0.27249022164276404
Delta: 0.0036949392965748696 	  Loss: 1.6454509255446284 	 Accuracy: 0.2842242503259452
Delta: 0.0033398022923911298 	  Loss: 1.6459448476858092 	 Accuracy: 0.28552803129074317
Delta: 0.0031814983994510556 	  Loss: 1.644726210353153 	 Accuracy: 0.28552803129074317
Delta: 0.004021351358210426 	  Loss: 1.645903973149979 	 Accuracy: 0.2842242503259452
Delta: 0.004809151271940713 	  Loss: 1.6464411278750977 	 Accuracy: 0.28552803129074317
Delta: 0.003044449448010259 	  Loss: 1.6459628706408695 	 Accuracy: 0.28552803129074317
Delta: 0.003487113492326301 	  Loss: 1.6456775136204702 	 Accuracy: 0.28683181225554105
Delta: 0.0035670350857985 	  Loss: 1.646056177491869 	 Accuracy: 0.28552803129074317
Delta: 0.0029875584086214964 	  Loss: 1.6460657111955581 	 Accuracy: 0.28552803129074317
Delta: 0.003521619649728864 	  Loss: 1.6468812595383837 	 Accuracy: 0.2842242503259452
Delta: 0.003710956747090172 	  Loss: 1.647482350225606 	 Accuracy: 0.2842242503259452
Delta: 0.0032324815829754034 	  Loss: 1.6470916147782328 	 Accuracy: 0.2842242503259452
Delta: 0.005129766095927259 	  Loss: 1.6455666431200302 	 Accuracy: 0.2816166883963494
Delta: 0.0013879300906234483 	  Loss: 1.64623324757388 	 Accuracy: 0.28292046936114734
Delta: 0.0016770102433900467 	  Loss: 1.6457453115969851 	 Accuracy: 0.2842242503259452
Delta: 0.0034674686170021634 	  Loss: 1.6460532503891234 	 Accuracy: 0.28552803129074317
Delta: 0.0016062887020635518 	  Loss: 1.6456600471121048 	 Accuracy: 0.28683181225554105
Delta: 0.0036820810134107138 	  Loss: 1.6450517454491067 	 Accuracy: 0.28683181225554105
Delta: 0.003966252652431395 	  Loss: 1.645267529911441 	 Accuracy: 0.28683181225554105
Delta: 0.0026993235090261173 	  Loss: 1.6453828005327895 	 Accuracy: 0.28552803129074317
Delta: 0.002718543586517236 	  Loss: 1.6453677909901054 	 Accuracy: 0.28552803129074317
Delta: 0.0036162355995633362 	  Loss: 1.6452828277525477 	 Accuracy: 0.28552803129074317
Delta: 0.001952830443213742 	  Loss: 1.6453121815671174 	 Accuracy: 0.288135593220339
Delta: 0.0030015243601261743 	  Loss: 1.6454788038136776 	 Accuracy: 0.2842242503259452
Delta: 0.0010514422349770475 	  Loss: 1.6455484781018437 	 Accuracy: 0.28552803129074317
Delta: 0.0014363813610767768 	  Loss: 1.6454353588427937 	 Accuracy: 0.2842242503259452
Delta: 0.0011254391731406364 	  Loss: 1.6454015130066286 	 Accuracy: 0.2842242503259452
Delta: 0.0015135590098764274 	  Loss: 1.6455067115123967 	 Accuracy: 0.28552803129074317
Delta: 0.0008441686200919002 	  Loss: 1.6454395580775323 	 Accuracy: 0.28552803129074317
Delta: 0.001032372156491134 	  Loss: 1.6455679134813415 	 Accuracy: 0.28552803129074317
Delta: 0.0014682863409867315 	  Loss: 1.6458061102192425 	 Accuracy: 0.28552803129074317
Delta: 0.0014581854520159792 	  Loss: 1.6454804666798357 	 Accuracy: 0.2790091264667536
Delta: 0.0015793684742821364 	  Loss: 1.6457997155972648 	 Accuracy: 0.28292046936114734
Delta: 0.0033570192846258252 	  Loss: 1.6464342335867355 	 Accuracy: 0.2842242503259452
Delta: 0.0024366170521468275 	  Loss: 1.6467887069097698 	 Accuracy: 0.2842242503259452
Delta: 8.013408558453505e-05 	  Loss: 1.646859844301105 	 Accuracy: 0.2842242503259452
Delta: 0.0006351210479834434 	  Loss: 1.6469014704073122 	 Accuracy: 0.28292046936114734
Delta: 0.0037563384614827822 	  Loss: 1.6472655966640362 	 Accuracy: 0.28292046936114734
Delta: 0.004994983728344577 	  Loss: 1.64690850369214 	 Accuracy: 0.2816166883963494
Delta: 0.003533054276613888 	  Loss: 1.6468201604760884 	 Accuracy: 0.2816166883963494
Delta: 0.0012725227358062574 	  Loss: 1.6469704772708273 	 Accuracy: 0.2803129074315515
Delta: 0.00435300729519735 	  Loss: 1.6472750757037327 	 Accuracy: 0.2816166883963494
Delta: 0.003043276285837245 	  Loss: 1.64683863254348 	 Accuracy: 0.2816166883963494
Delta: 0.0029108344399233032 	  Loss: 1.6470183663601399 	 Accuracy: 0.28292046936114734
Delta: 0.0007343651081048021 	  Loss: 1.6470555044732194 	 Accuracy: 0.28292046936114734
Delta: 0.003928104296896315 	  Loss: 1.6471187387813782 	 Accuracy: 0.28292046936114734
Delta: 0.0026035513118483314 	  Loss: 1.6467188357310882 	 Accuracy: 0.28292046936114734
Delta: 0.0004999139633390922 	  Loss: 1.6467162628802516 	 Accuracy: 0.28292046936114734
Delta: 0.004139881993953314 	  Loss: 1.6480171199046354 	 Accuracy: 0.2842242503259452
Delta: 0.0009631567930245402 	  Loss: 1.6480448105768724 	 Accuracy: 0.28292046936114734
Delta: 0.0030814326899598994 	  Loss: 1.6481837600075822 	 Accuracy: 0.28292046936114734
Delta: 0.0016676067907418672 	  Loss: 1.64807369284581 	 Accuracy: 0.2816166883963494
Delta: 0.0031730034374480424 	  Loss: 1.6487676645799898 	 Accuracy: 0.2816166883963494
Delta: 0.0038218091012225453 	  Loss: 1.6487963880814471 	 Accuracy: 0.2816166883963494
Delta: 0.005188414760945088 	  Loss: 1.6476091538643014 	 Accuracy: 0.2816166883963494
Delta: 0.003978767191745501 	  Loss: 1.6482873300500787 	 Accuracy: 0.2816166883963494
Delta: 0.004211339550381204 	  Loss: 1.6487444550691435 	 Accuracy: 0.28292046936114734
Delta: 0.0038439959352019465 	  Loss: 1.6499637087920762 	 Accuracy: 0.28292046936114734
Delta: 0.004334211249123388 	  Loss: 1.649482792802286 	 Accuracy: 0.2803129074315515
Delta: 0.004096930182883192 	  Loss: 1.6497948141684382 	 Accuracy: 0.2816166883963494
Delta: 0.0021495456716407405 	  Loss: 1.649435159775964 	 Accuracy: 0.2803129074315515
Delta: 0.002941353089409144 	  Loss: 1.6499497310587512 	 Accuracy: 0.28292046936114734
Delta: 0.0021307288700360724 	  Loss: 1.6498519918315186 	 Accuracy: 0.2816166883963494
Delta: 8.878152255376933e-05 	  Loss: 1.6494187363967883 	 Accuracy: 0.2816166883963494
Delta: 1.1099015229426847e-05 	  Loss: 1.6493674967325704 	 Accuracy: 0.2803129074315515
Delta: 0.003407997548868192 	  Loss: 1.650027788166054 	 Accuracy: 0.2816166883963494
Delta: 0.00376713243275783 	  Loss: 1.650488453223352 	 Accuracy: 0.2816166883963494
Delta: 0.021051978873096972 	  Loss: 2.157296339013339 	 Accuracy: 0.20599739243807041
Delta: 0.018899385781311673 	  Loss: 2.0451475154090755 	 Accuracy: 0.29465449804432853
Delta: 0.017919656219078272 	  Loss: 1.8588890321744638 	 Accuracy: 0.29595827900912647
Delta: 0.01669089136838732 	  Loss: 1.7146477033844412 	 Accuracy: 0.2777053455019557
Delta: 0.01367259117056253 	  Loss: 1.6550093362579124 	 Accuracy: 0.2607561929595828
Delta: 0.010487754412016551 	  Loss: 1.6372064964435498 	 Accuracy: 0.25945241199478486

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007617339182133419 	  Loss: 1.6322335385829208 	 Accuracy: 0.258148631029987
Delta: 0.00603992967962029 	  Loss: 1.6312226235595575 	 Accuracy: 0.2607561929595828
Delta: 0.004028335019714827 	  Loss: 1.6309411331871217 	 Accuracy: 0.25684485006518903
Delta: 0.0036609101338894046 	  Loss: 1.6305422281235553 	 Accuracy: 0.25945241199478486
Delta: 0.001749130552110971 	  Loss: 1.6304769279419151 	 Accuracy: 0.2607561929595828
Delta: 0.003236543219393332 	  Loss: 1.630680644336063 	 Accuracy: 0.25945241199478486
Delta: 0.0010415695445254007 	  Loss: 1.6306152619560916 	 Accuracy: 0.2607561929595828
Delta: 0.0011267129759936169 	  Loss: 1.630676176318663 	 Accuracy: 0.2607561929595828
Delta: 0.003771195234295869 	  Loss: 1.63041441876238 	 Accuracy: 0.2607561929595828
Delta: 0.0029018365903047774 	  Loss: 1.6303502194495476 	 Accuracy: 0.2607561929595828
Delta: 0.001884270330631928 	  Loss: 1.6302070572008982 	 Accuracy: 0.2620599739243807
Delta: 0.0010077506793360084 	  Loss: 1.6302949911308247 	 Accuracy: 0.2607561929595828
Delta: 0.0015614010155019715 	  Loss: 1.6303998165154274 	 Accuracy: 0.2607561929595828
Delta: 0.0014905415893949228 	  Loss: 1.6302515264761652 	 Accuracy: 0.2607561929595828
Delta: 0.002419220493937342 	  Loss: 1.6300822258649408 	 Accuracy: 0.25945241199478486
Delta: 0.0035212691370812596 	  Loss: 1.6301949252131855 	 Accuracy: 0.2607561929595828
Delta: 0.0028580265400797553 	  Loss: 1.6301886200627913 	 Accuracy: 0.2607561929595828
Delta: 0.0031014665566121646 	  Loss: 1.6304905289963518 	 Accuracy: 0.2646675358539765
Delta: 0.0005571126288762508 	  Loss: 1.6304075232064084 	 Accuracy: 0.25945241199478486
Delta: 0.0013679587166756419 	  Loss: 1.6300779399044658 	 Accuracy: 0.2607561929595828
Delta: 0.0030455564683846883 	  Loss: 1.6299674962357358 	 Accuracy: 0.258148631029987
Delta: 0.0017554804913638214 	  Loss: 1.6299954982635572 	 Accuracy: 0.25684485006518903
Delta: 0.0024748211170850564 	  Loss: 1.6304808744499457 	 Accuracy: 0.25945241199478486
Delta: 0.0016269571751431268 	  Loss: 1.630180710578975 	 Accuracy: 0.25945241199478486
Delta: 0.002557430545833409 	  Loss: 1.6302804724267757 	 Accuracy: 0.2607561929595828
Delta: 0.0034073849055518937 	  Loss: 1.6300224800937828 	 Accuracy: 0.25945241199478486
Delta: 0.003347937574428151 	  Loss: 1.630210377109472 	 Accuracy: 0.25945241199478486
Delta: 0.003903861518839959 	  Loss: 1.6300595721018531 	 Accuracy: 0.25945241199478486
Delta: 0.0013224595341220905 	  Loss: 1.6300326924244104 	 Accuracy: 0.25945241199478486
Delta: 0.0011094574248035017 	  Loss: 1.630035901224252 	 Accuracy: 0.2633637548891786
Delta: 0.004517497044355222 	  Loss: 1.6311274857835367 	 Accuracy: 0.2620599739243807
Delta: 0.0026856091416422004 	  Loss: 1.6310962509525035 	 Accuracy: 0.25945241199478486
Delta: 0.0019076849894929674 	  Loss: 1.630831984488296 	 Accuracy: 0.25945241199478486
Delta: 0.003112350226547045 	  Loss: 1.6309657856284163 	 Accuracy: 0.2607561929595828
Delta: 0.0030475733527002254 	  Loss: 1.6308289039046677 	 Accuracy: 0.2607561929595828
Delta: 0.0017072118406055688 	  Loss: 1.6308061945720935 	 Accuracy: 0.25945241199478486
Delta: 0.001811594406193275 	  Loss: 1.6308613889698753 	 Accuracy: 0.2607561929595828
Delta: 0.0028239026351171283 	  Loss: 1.630665238556716 	 Accuracy: 0.25684485006518903
Delta: 0.0019361571510447667 	  Loss: 1.6309442539142844 	 Accuracy: 0.2607561929595828
Delta: 0.0006753124934436735 	  Loss: 1.630945124291959 	 Accuracy: 0.2607561929595828
Delta: 2.799071934711598e-05 	  Loss: 1.6309308678199623 	 Accuracy: 0.258148631029987
Delta: 0.0012804591185914158 	  Loss: 1.6314000914350393 	 Accuracy: 0.25945241199478486
Delta: 0.003138983804211854 	  Loss: 1.6312170957622412 	 Accuracy: 0.23989569752281617
Delta: 0.002346375682783449 	  Loss: 1.6313195697582996 	 Accuracy: 0.25945241199478486
Delta: 0.002396632823716935 	  Loss: 1.6309527631483751 	 Accuracy: 0.25684485006518903
Delta: 0.002696286420879892 	  Loss: 1.631587858159686 	 Accuracy: 0.25945241199478486
Delta: 0.0019222380714818724 	  Loss: 1.6310877405596105 	 Accuracy: 0.2620599739243807
Delta: 0.0038423748141090466 	  Loss: 1.6318087293807828 	 Accuracy: 0.25945241199478486
Delta: 0.0014252496111249774 	  Loss: 1.6313324113704668 	 Accuracy: 0.2607561929595828
Delta: 0.0027241159195569783 	  Loss: 1.6309910385280812 	 Accuracy: 0.2542372881355932
Delta: 0.004298902738311602 	  Loss: 1.631270631578961 	 Accuracy: 0.25945241199478486
Delta: 0.0019296186733267033 	  Loss: 1.6311323094360124 	 Accuracy: 0.25945241199478486
Delta: 0.0022833751579338863 	  Loss: 1.6310648355565018 	 Accuracy: 0.258148631029987
Delta: 0.0028971841067934817 	  Loss: 1.6309539247972609 	 Accuracy: 0.25945241199478486
Delta: 0.0009189615570964023 	  Loss: 1.6309762552785343 	 Accuracy: 0.25945241199478486
Delta: 0.001896995676748322 	  Loss: 1.6311137129716577 	 Accuracy: 0.2620599739243807
Delta: 0.0021319994255669587 	  Loss: 1.6310109274569928 	 Accuracy: 0.2542372881355932
Delta: 0.0030943170893612116 	  Loss: 1.6312439023317302 	 Accuracy: 0.25945241199478486
Delta: 0.002893088318064403 	  Loss: 1.6309687484577096 	 Accuracy: 0.2620599739243807
Delta: 0.00011077962412531883 	  Loss: 1.6309995356662137 	 Accuracy: 0.2620599739243807
Delta: 0.0008572663162369051 	  Loss: 1.6309069652754236 	 Accuracy: 0.2607561929595828
Delta: 0.0005652885144656521 	  Loss: 1.6310300751344715 	 Accuracy: 0.2620599739243807
Delta: 0.002573091643240952 	  Loss: 1.6312495050437816 	 Accuracy: 0.2620599739243807
Delta: 0.002107261193470751 	  Loss: 1.6310845211266352 	 Accuracy: 0.2620599739243807
Delta: 0.002128558383184217 	  Loss: 1.631330279697267 	 Accuracy: 0.26597131681877445
Delta: 0.00013329354609900842 	  Loss: 1.631000050396786 	 Accuracy: 0.2620599739243807
Delta: 0.0036068394591901656 	  Loss: 1.6309716861657608 	 Accuracy: 0.2620599739243807
Delta: 0.0008253157241586907 	  Loss: 1.6309024181355893 	 Accuracy: 0.2633637548891786
Delta: 0.004555871775775717 	  Loss: 1.6310213968971456 	 Accuracy: 0.2633637548891786
Delta: 0.0015898823297026859 	  Loss: 1.63103854527863 	 Accuracy: 0.2633637548891786
Delta: 0.0023332949756018537 	  Loss: 1.6310932312442483 	 Accuracy: 0.2620599739243807
Delta: 0.003098315485634754 	  Loss: 1.6310674211692806 	 Accuracy: 0.2620599739243807
Delta: 0.0012019585328606798 	  Loss: 1.6310530664390648 	 Accuracy: 0.2633637548891786
Delta: 0.004130411944199799 	  Loss: 1.6312111016495214 	 Accuracy: 0.2633637548891786
Delta: 0.0007394890351279608 	  Loss: 1.6311557340701395 	 Accuracy: 0.2620599739243807
Delta: 0.002709521191286346 	  Loss: 1.6310491018548419 	 Accuracy: 0.2620599739243807
Delta: 6.983045745906757e-06 	  Loss: 1.63104949634679 	 Accuracy: 0.2620599739243807
Delta: 1.924447124240733e-09 	  Loss: 1.6310494951020469 	 Accuracy: 0.2620599739243807
converged at iter  83
Delta: 0.02102344586507392 	  Loss: 2.1583551451739074 	 Accuracy: 0.20599739243807041
Delta: 0.01918292558108551 	  Loss: 2.044396345366766 	 Accuracy: 0.22033898305084745
Delta: 0.01786517661024978 	  Loss: 1.8454240480699715 	 Accuracy: 0.20860495436766624
Delta: 0.015615321047269598 	  Loss: 1.7178829934193636 	 Accuracy: 0.18513689700130379
Delta: 0.01412488953578716 	  Loss: 1.659618516451201 	 Accuracy: 0.17209908735332463
Delta: 0.010965223131859509 	  Loss: 1.6411796311045381 	 Accuracy: 0.17340286831812254

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008220746482711358 	  Loss: 1.636912762977376 	 Accuracy: 0.17340286831812254
Delta: 0.00583019245552595 	  Loss: 1.636174746271884 	 Accuracy: 0.1773142112125163
Delta: 0.004417899118044672 	  Loss: 1.6358235283868463 	 Accuracy: 0.17861799217731422
Delta: 0.0036305370059819763 	  Loss: 1.6357181394746092 	 Accuracy: 0.17861799217731422
Delta: 0.0011362964839487268 	  Loss: 1.6358531401472052 	 Accuracy: 0.17861799217731422
Delta: 0.0034751915702891357 	  Loss: 1.6358732125972402 	 Accuracy: 0.1773142112125163
Delta: 0.001123475716408344 	  Loss: 1.6358652812746253 	 Accuracy: 0.17861799217731422
Delta: 0.003676104394723694 	  Loss: 1.6356698019308014 	 Accuracy: 0.17861799217731422
Delta: 0.0018394738595763978 	  Loss: 1.6354686508275922 	 Accuracy: 0.17861799217731422
Delta: 0.0012606458873140873 	  Loss: 1.6357336837514937 	 Accuracy: 0.17861799217731422
Delta: 0.002899809644582832 	  Loss: 1.6358960096339796 	 Accuracy: 0.17861799217731422
Delta: 0.0015950644631629381 	  Loss: 1.6360018122696576 	 Accuracy: 0.17861799217731422
Delta: 0.0021249898068930336 	  Loss: 1.636179751565666 	 Accuracy: 0.17861799217731422
Delta: 0.0021835148488462907 	  Loss: 1.635879091357367 	 Accuracy: 0.18122555410691005
Delta: 0.002223741061128274 	  Loss: 1.6358307376240728 	 Accuracy: 0.17861799217731422
Delta: 0.0015636207215700586 	  Loss: 1.6360505777125771 	 Accuracy: 0.17861799217731422
Delta: 6.653726230671823e-05 	  Loss: 1.6361448836722639 	 Accuracy: 0.17861799217731422
Delta: 0.0007866569786736496 	  Loss: 1.6360201356202602 	 Accuracy: 0.17992177314211213
Delta: 0.0023497168065202047 	  Loss: 1.6354266061957246 	 Accuracy: 0.17861799217731422
Delta: 0.0033278796478601333 	  Loss: 1.6352500937908803 	 Accuracy: 0.17861799217731422
Delta: 0.0015535388507081653 	  Loss: 1.6350463957511434 	 Accuracy: 0.17992177314211213
Delta: 0.002442267570578964 	  Loss: 1.6358144988864063 	 Accuracy: 0.17992177314211213
Delta: 0.0026540668235834164 	  Loss: 1.635945325528899 	 Accuracy: 0.17992177314211213
Delta: 0.002808523543324259 	  Loss: 1.6362654242603896 	 Accuracy: 0.17992177314211213
Delta: 0.002756774032604337 	  Loss: 1.6362666538680584 	 Accuracy: 0.17992177314211213
Delta: 0.0037370531790928167 	  Loss: 1.6375684820550278 	 Accuracy: 0.17992177314211213
Delta: 0.0012224926322157391 	  Loss: 1.6374487369697739 	 Accuracy: 0.1760104302477184
Delta: 0.004487285479498591 	  Loss: 1.6368263839080877 	 Accuracy: 0.17861799217731422
Delta: 0.0009140314105202002 	  Loss: 1.636448480800526 	 Accuracy: 0.17861799217731422
Delta: 0.001909569262208928 	  Loss: 1.6366582331574095 	 Accuracy: 0.17861799217731422
Delta: 0.003081539389546611 	  Loss: 1.6366636731858932 	 Accuracy: 0.17992177314211213
Delta: 0.0022791844998728905 	  Loss: 1.636554329632802 	 Accuracy: 0.17861799217731422
Delta: 0.001517979097638305 	  Loss: 1.6365982314398653 	 Accuracy: 0.17861799217731422
Delta: 0.0011214699170276007 	  Loss: 1.6366144838430365 	 Accuracy: 0.17861799217731422
Delta: 0.0009557843096230142 	  Loss: 1.6365701136321844 	 Accuracy: 0.17861799217731422
Delta: 0.0032231532762186355 	  Loss: 1.6365302760827118 	 Accuracy: 0.17861799217731422
Delta: 0.00415706807571389 	  Loss: 1.6369233794245146 	 Accuracy: 0.1773142112125163
Delta: 0.0038710681116075523 	  Loss: 1.6372336731448143 	 Accuracy: 0.17209908735332463
Delta: 0.002762831232060301 	  Loss: 1.6372018562364692 	 Accuracy: 0.1760104302477184
Delta: 0.00500628618921955 	  Loss: 1.6367068432494927 	 Accuracy: 0.1760104302477184
Delta: 0.0021922848538591623 	  Loss: 1.636728828154512 	 Accuracy: 0.1773142112125163
Delta: 0.0019294581357426933 	  Loss: 1.6368557004009903 	 Accuracy: 0.1760104302477184
Delta: 0.001254492134333139 	  Loss: 1.6370372625240204 	 Accuracy: 0.1773142112125163
Delta: 0.0005623663627464153 	  Loss: 1.636747261985871 	 Accuracy: 0.1773142112125163
Delta: 3.68829037912872e-05 	  Loss: 1.6367342520988943 	 Accuracy: 0.1773142112125163
Delta: 3.089156572310169e-05 	  Loss: 1.6367070999304942 	 Accuracy: 0.17209908735332463
Delta: 0.0045779648988082235 	  Loss: 1.6376405435312953 	 Accuracy: 0.1760104302477184
Delta: 0.004475178299469697 	  Loss: 1.6365796971610467 	 Accuracy: 0.17470664928292046
Delta: 0.003427953840255758 	  Loss: 1.6366845027152366 	 Accuracy: 0.17470664928292046
Delta: 0.0024715633738399525 	  Loss: 1.636496944795203 	 Accuracy: 0.17470664928292046
Delta: 0.002698797451349305 	  Loss: 1.6370040147618241 	 Accuracy: 0.17470664928292046
Delta: 0.002277447493404773 	  Loss: 1.636335267597977 	 Accuracy: 0.17470664928292046
Delta: 0.0025663716771583585 	  Loss: 1.6361197725398244 	 Accuracy: 0.17340286831812254
Delta: 0.00472408282304155 	  Loss: 1.6361098392910312 	 Accuracy: 0.1760104302477184
Delta: 0.004068754494026368 	  Loss: 1.6360065185536463 	 Accuracy: 0.17470664928292046
Delta: 0.00409778193832729 	  Loss: 1.635747380434738 	 Accuracy: 0.1760104302477184
Delta: 0.0031011207851272876 	  Loss: 1.635878812444033 	 Accuracy: 0.1760104302477184
Delta: 0.0018016522056671942 	  Loss: 1.635639589167147 	 Accuracy: 0.1760104302477184
Delta: 0.002201911967543573 	  Loss: 1.63622545438331 	 Accuracy: 0.17470664928292046
Delta: 0.004765553126614086 	  Loss: 1.636812171029562 	 Accuracy: 0.1760104302477184
Delta: 0.001943595434591788 	  Loss: 1.6367971837346178 	 Accuracy: 0.1864406779661017
Delta: 0.004208132460923022 	  Loss: 1.6367974189578465 	 Accuracy: 0.1760104302477184
Delta: 0.005150119046566263 	  Loss: 1.6363158181305613 	 Accuracy: 0.17470664928292046
Delta: 0.004779371195479345 	  Loss: 1.6368362005352077 	 Accuracy: 0.1760104302477184
Delta: 0.002384409791525354 	  Loss: 1.6370641501890266 	 Accuracy: 0.1760104302477184
Delta: 0.003206234977305598 	  Loss: 1.636866494228716 	 Accuracy: 0.1760104302477184
Delta: 0.004195261134988308 	  Loss: 1.6372348170193658 	 Accuracy: 0.1760104302477184
Delta: 0.0033329292563651124 	  Loss: 1.6369009889164448 	 Accuracy: 0.1773142112125163
Delta: 0.003193546394792043 	  Loss: 1.6372772091046839 	 Accuracy: 0.17209908735332463
Delta: 0.003561418860649735 	  Loss: 1.6377500200164545 	 Accuracy: 0.1760104302477184
Delta: 0.0017511471182501618 	  Loss: 1.637101612379857 	 Accuracy: 0.17470664928292046
Delta: 0.004245221681887892 	  Loss: 1.6367135179751968 	 Accuracy: 0.17861799217731422
Delta: 0.0028972411802423333 	  Loss: 1.6371734368947894 	 Accuracy: 0.1760104302477184
Delta: 0.0013124500280824985 	  Loss: 1.6370305589134406 	 Accuracy: 0.17992177314211213
Delta: 5.513456137747302e-05 	  Loss: 1.637302691199139 	 Accuracy: 0.1760104302477184
Delta: 0.004623518102626036 	  Loss: 1.6384432772535982 	 Accuracy: 0.17340286831812254
Delta: 0.0013413149599585184 	  Loss: 1.6382324599564375 	 Accuracy: 0.1773142112125163
Delta: 0.0036678047783382005 	  Loss: 1.637687179759577 	 Accuracy: 0.17992177314211213
Delta: 0.0029825203076698716 	  Loss: 1.637231046720858 	 Accuracy: 0.1773142112125163
Delta: 0.004314504480022132 	  Loss: 1.6377594972826812 	 Accuracy: 0.17470664928292046
Delta: 0.0028973244612289163 	  Loss: 1.6375274330822776 	 Accuracy: 0.1773142112125163
Delta: 0.0020301004887454243 	  Loss: 1.6377660684073105 	 Accuracy: 0.1773142112125163
Delta: 0.0040775497448571445 	  Loss: 1.6374567890799814 	 Accuracy: 0.1773142112125163
Delta: 0.0009173346079720985 	  Loss: 1.6375732360593729 	 Accuracy: 0.17861799217731422
Delta: 0.0016890889436255246 	  Loss: 1.637651393638321 	 Accuracy: 0.1773142112125163
Delta: 0.0013059513812630715 	  Loss: 1.6375762279675712 	 Accuracy: 0.17861799217731422
Delta: 0.003080992090168524 	  Loss: 1.6380053196722613 	 Accuracy: 0.17861799217731422
Delta: 0.0043308934416790654 	  Loss: 1.6393061357384058 	 Accuracy: 0.17861799217731422
Delta: 0.0036626965636433577 	  Loss: 1.6397187339014418 	 Accuracy: 0.17992177314211213
Delta: 0.0011297286692811908 	  Loss: 1.6397812306277706 	 Accuracy: 0.17861799217731422
Delta: 0.0021299010656080962 	  Loss: 1.640102122839402 	 Accuracy: 0.18252933507170796
Delta: 0.003868144116805617 	  Loss: 1.6399798494669433 	 Accuracy: 0.1773142112125163
Delta: 0.006531095573691328 	  Loss: 1.64152097983796 	 Accuracy: 0.17470664928292046
Delta: 0.0059501150053333715 	  Loss: 1.642420706509447 	 Accuracy: 0.17470664928292046
Delta: 0.0209952805681253 	  Loss: 2.1585657096029145 	 Accuracy: 0.2046936114732725
Delta: 0.01896954976658831 	  Loss: 2.042163559361458 	 Accuracy: 0.21903520208604954
Delta: 0.01770679407063413 	  Loss: 1.8575366991931577 	 Accuracy: 0.21773142112125163
Delta: 0.015498483802078222 	  Loss: 1.746919804881038 	 Accuracy: 0.1981747066492829
Delta: 0.012769385101556417 	  Loss: 1.70372640054511 	 Accuracy: 0.18904823989569752
Delta: 0.010666951003762564 	  Loss: 1.691016385973777 	 Accuracy: 0.19165580182529335

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00800588424317985 	  Loss: 1.6884465698791413 	 Accuracy: 0.19556714471968709
Delta: 0.007019705251868892 	  Loss: 1.6868217861481887 	 Accuracy: 0.19556714471968709
Delta: 0.005845850013809408 	  Loss: 1.6863243395727867 	 Accuracy: 0.196870925684485
Delta: 0.004980507034516889 	  Loss: 1.6859200646914267 	 Accuracy: 0.19556714471968709
Delta: 0.0035167640811086995 	  Loss: 1.6858322174165208 	 Accuracy: 0.19556714471968709
Delta: 0.0018829696201620389 	  Loss: 1.6855896961140813 	 Accuracy: 0.19556714471968709
Delta: 0.0016712718971885682 	  Loss: 1.6855440324681004 	 Accuracy: 0.19556714471968709
Delta: 0.002523384287264276 	  Loss: 1.6850192272057658 	 Accuracy: 0.19556714471968709
Delta: 0.003058752314002212 	  Loss: 1.6847290166143396 	 Accuracy: 0.19556714471968709
Delta: 0.0022329558674417374 	  Loss: 1.6844319268788965 	 Accuracy: 0.19165580182529335
Delta: 0.003554537810591853 	  Loss: 1.6835902973933043 	 Accuracy: 0.19556714471968709
Delta: 0.003312265061036957 	  Loss: 1.6834031241125966 	 Accuracy: 0.196870925684485
Delta: 0.003726859162609004 	  Loss: 1.6839439497604556 	 Accuracy: 0.19426336375488917
Delta: 0.00295370914421743 	  Loss: 1.6832021583313796 	 Accuracy: 0.19426336375488917
Delta: 0.0005053565460279415 	  Loss: 1.6832006361513079 	 Accuracy: 0.19426336375488917
Delta: 0.002158142609336272 	  Loss: 1.6834740194085582 	 Accuracy: 0.19426336375488917
Delta: 0.002715603474554078 	  Loss: 1.6835453990155556 	 Accuracy: 0.19426336375488917
Delta: 0.002286897705993616 	  Loss: 1.6831898233251998 	 Accuracy: 0.19295958279009126
Delta: 0.001787254841352361 	  Loss: 1.6832709547212177 	 Accuracy: 0.19426336375488917
Delta: 0.0026475927365814593 	  Loss: 1.6834281686834256 	 Accuracy: 0.19426336375488917
Delta: 0.0019838916186465695 	  Loss: 1.6835968830420234 	 Accuracy: 0.19426336375488917
Delta: 0.0017534658127985126 	  Loss: 1.6834292526241121 	 Accuracy: 0.19426336375488917
Delta: 0.0008890040056841441 	  Loss: 1.68349457292167 	 Accuracy: 0.19426336375488917
Delta: 0.0023598065067984672 	  Loss: 1.68313711191968 	 Accuracy: 0.19426336375488917
Delta: 0.0010866799894785602 	  Loss: 1.6831885940170292 	 Accuracy: 0.19426336375488917
Delta: 0.0030185316268330127 	  Loss: 1.683614480694954 	 Accuracy: 0.18122555410691005
Delta: 0.003503426962309867 	  Loss: 1.6840700590032172 	 Accuracy: 0.19426336375488917
Delta: 0.001990041388526775 	  Loss: 1.683447642954289 	 Accuracy: 0.19426336375488917
Delta: 0.0012750113546212058 	  Loss: 1.6829903409611466 	 Accuracy: 0.19426336375488917
Delta: 0.001829796004764372 	  Loss: 1.6827371972773286 	 Accuracy: 0.19556714471968709
Delta: 0.002128065576172273 	  Loss: 1.6827782744897246 	 Accuracy: 0.19426336375488917
Delta: 5.164648977865077e-05 	  Loss: 1.6829720906438321 	 Accuracy: 0.19426336375488917
Delta: 2.358445717189374e-05 	  Loss: 1.6828545948341935 	 Accuracy: 0.19426336375488917
Delta: 0.0015414647160031198 	  Loss: 1.682674702703336 	 Accuracy: 0.19556714471968709
Delta: 0.001440835866385035 	  Loss: 1.6830452937570548 	 Accuracy: 0.19426336375488917
Delta: 0.0006977252918561244 	  Loss: 1.6833950106794373 	 Accuracy: 0.19426336375488917
Delta: 0.0015334706905924113 	  Loss: 1.6834082271554247 	 Accuracy: 0.19426336375488917
Delta: 0.0009390887899484956 	  Loss: 1.6832495466610717 	 Accuracy: 0.19426336375488917
Delta: 0.00010175396896059392 	  Loss: 1.683168603099229 	 Accuracy: 0.19426336375488917
Delta: 0.0006431901891099383 	  Loss: 1.6830990781855852 	 Accuracy: 0.19556714471968709
Delta: 0.0031003411948933145 	  Loss: 1.6835879823607205 	 Accuracy: 0.19426336375488917
Delta: 0.0017266550943056032 	  Loss: 1.6830806216522982 	 Accuracy: 0.19426336375488917
Delta: 0.002890502652156133 	  Loss: 1.6829040476829245 	 Accuracy: 0.19426336375488917
Delta: 0.0025409032544157256 	  Loss: 1.6827198042666425 	 Accuracy: 0.19426336375488917
Delta: 0.00253358329788573 	  Loss: 1.68302110006719 	 Accuracy: 0.19426336375488917
Delta: 0.0019516833315817153 	  Loss: 1.6828292372445481 	 Accuracy: 0.19295958279009126
Delta: 0.003499327325630236 	  Loss: 1.6825448922101978 	 Accuracy: 0.19295958279009126
Delta: 5.0178995679116555e-05 	  Loss: 1.6828561395729627 	 Accuracy: 0.18513689700130379
Delta: 0.006361951005648571 	  Loss: 1.6846027881461616 	 Accuracy: 0.19295958279009126
Delta: 0.005119612641306362 	  Loss: 1.6828477039845855 	 Accuracy: 0.19426336375488917
Delta: 0.0041276361326590605 	  Loss: 1.6823994406170784 	 Accuracy: 0.19426336375488917
Delta: 0.0013298923253621368 	  Loss: 1.68259036259704 	 Accuracy: 0.19295958279009126
Delta: 0.003023402285442987 	  Loss: 1.682967403949909 	 Accuracy: 0.19295958279009126
Delta: 0.0038883180334002444 	  Loss: 1.6827130418301661 	 Accuracy: 0.19295958279009126
Delta: 0.004024946042683047 	  Loss: 1.6822038651920264 	 Accuracy: 0.19295958279009126
Delta: 0.000547681762787469 	  Loss: 1.6821607026104768 	 Accuracy: 0.19426336375488917
Delta: 0.0014916499392328413 	  Loss: 1.6824558716498488 	 Accuracy: 0.19165580182529335
Delta: 0.004589015531574786 	  Loss: 1.6817969299023665 	 Accuracy: 0.19295958279009126
Delta: 0.0033472599854743016 	  Loss: 1.681232147615224 	 Accuracy: 0.19426336375488917
Delta: 0.0015223506107364675 	  Loss: 1.681900247444255 	 Accuracy: 0.19295958279009126
Delta: 0.0025374009507986386 	  Loss: 1.6816247309360906 	 Accuracy: 0.19295958279009126
Delta: 0.0031105189840539803 	  Loss: 1.6811458777980606 	 Accuracy: 0.19426336375488917
Delta: 0.001685924603723107 	  Loss: 1.6816163610473418 	 Accuracy: 0.19426336375488917
Delta: 0.002452000640849866 	  Loss: 1.6815551060778133 	 Accuracy: 0.19295958279009126
Delta: 0.0005734850114255778 	  Loss: 1.6817425305866813 	 Accuracy: 0.19426336375488917
Delta: 2.1584819408750767e-05 	  Loss: 1.6817692543456944 	 Accuracy: 0.19426336375488917
Delta: 0.0005690472108972873 	  Loss: 1.6818439883664946 	 Accuracy: 0.19426336375488917
Delta: 0.002754955217962862 	  Loss: 1.6815356210255885 	 Accuracy: 0.19295958279009126
Delta: 0.0036220167090749798 	  Loss: 1.6822056321871979 	 Accuracy: 0.19426336375488917
Delta: 0.005945517464520946 	  Loss: 1.6820933627314107 	 Accuracy: 0.19556714471968709
Delta: 0.004072806847528049 	  Loss: 1.6828424005079456 	 Accuracy: 0.1981747066492829
Delta: 0.0057613091291055804 	  Loss: 1.683807107435555 	 Accuracy: 0.196870925684485
Delta: 0.004029024079086174 	  Loss: 1.683820103817672 	 Accuracy: 0.196870925684485
Delta: 0.005248848537852778 	  Loss: 1.6833906890773118 	 Accuracy: 0.19556714471968709
Delta: 0.003686461624293586 	  Loss: 1.68297993207879 	 Accuracy: 0.1981747066492829
Delta: 0.0019188228068270526 	  Loss: 1.6831466200938283 	 Accuracy: 0.196870925684485
Delta: 0.004403754324324893 	  Loss: 1.6834767931482646 	 Accuracy: 0.196870925684485
Delta: 0.004841026841296517 	  Loss: 1.682286158921491 	 Accuracy: 0.196870925684485
Delta: 0.0020223619846663574 	  Loss: 1.6821452194925919 	 Accuracy: 0.196870925684485
Delta: 8.636240104806849e-05 	  Loss: 1.6822486532208112 	 Accuracy: 0.196870925684485
Delta: 6.360514669470869e-05 	  Loss: 1.6823044459186005 	 Accuracy: 0.196870925684485
Delta: 1.8941891010626195e-05 	  Loss: 1.68222687939605 	 Accuracy: 0.196870925684485
Delta: 0.004406244247875605 	  Loss: 1.682292045870422 	 Accuracy: 0.19556714471968709
Delta: 0.0022686211717027325 	  Loss: 1.6822610178281974 	 Accuracy: 0.196870925684485
Delta: 0.0025987965000932624 	  Loss: 1.6822659394032735 	 Accuracy: 0.19556714471968709
Delta: 0.0017743134150071031 	  Loss: 1.6819031752833418 	 Accuracy: 0.19556714471968709
Delta: 0.0007468089780432478 	  Loss: 1.6819111244150924 	 Accuracy: 0.19556714471968709
Delta: 0.0031637880351592226 	  Loss: 1.681584463353333 	 Accuracy: 0.19556714471968709
Delta: 0.004152540527253293 	  Loss: 1.6823336249961778 	 Accuracy: 0.1981747066492829
Delta: 0.0053814887393012645 	  Loss: 1.6829358998992834 	 Accuracy: 0.19556714471968709
Delta: 0.0034323933907642423 	  Loss: 1.6833305295029772 	 Accuracy: 0.1981747066492829
Delta: 0.004636333178987178 	  Loss: 1.6838428862597958 	 Accuracy: 0.19947848761408082
Delta: 0.0037532448676346796 	  Loss: 1.683346931438148 	 Accuracy: 0.19556714471968709
Delta: 0.0024874342208015595 	  Loss: 1.6831927647634295 	 Accuracy: 0.19556714471968709
Delta: 0.02108779721239801 	  Loss: 2.1583749229012934 	 Accuracy: 0.20208604954367665
Delta: 0.019047894072982404 	  Loss: 2.037208659507387 	 Accuracy: 0.20860495436766624
Delta: 0.018218244893657243 	  Loss: 1.8372333675802164 	 Accuracy: 0.1981747066492829
Delta: 0.015930313238515313 	  Loss: 1.7130625377059163 	 Accuracy: 0.19556714471968709
Delta: 0.01242776865339411 	  Loss: 1.6674668020614698 	 Accuracy: 0.1864406779661017
Delta: 0.009832040816200855 	  Loss: 1.654071292683109 	 Accuracy: 0.18383311603650587

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008134989590170703 	  Loss: 1.650308139299379 	 Accuracy: 0.18122555410691005
Delta: 0.004637887527682622 	  Loss: 1.6499533051984812 	 Accuracy: 0.18383311603650587
Delta: 0.0042762287498127344 	  Loss: 1.649975698810331 	 Accuracy: 0.18383311603650587
Delta: 0.003811211064683387 	  Loss: 1.6497712333275614 	 Accuracy: 0.1864406779661017
Delta: 0.0029742875617629425 	  Loss: 1.6498092652641216 	 Accuracy: 0.18383311603650587
Delta: 0.002091931823221914 	  Loss: 1.6496100431806866 	 Accuracy: 0.18252933507170796
Delta: 0.003720962104112294 	  Loss: 1.6490746966725616 	 Accuracy: 0.18252933507170796
Delta: 0.0012806524980130136 	  Loss: 1.6488459552012062 	 Accuracy: 0.18252933507170796
Delta: 0.0015412767071824238 	  Loss: 1.649182163559352 	 Accuracy: 0.18122555410691005
Delta: 0.002607475497537277 	  Loss: 1.6494500403285475 	 Accuracy: 0.18252933507170796
Delta: 0.0018189749924172427 	  Loss: 1.6488042396549019 	 Accuracy: 0.18252933507170796
Delta: 0.0028225688592184075 	  Loss: 1.6488985816698212 	 Accuracy: 0.18252933507170796
Delta: 0.0022790220537324208 	  Loss: 1.6493558339354537 	 Accuracy: 0.18383311603650587
Delta: 3.3077592517294827e-05 	  Loss: 1.6492614546674007 	 Accuracy: 0.18252933507170796
Delta: 9.215855845418802e-06 	  Loss: 1.6492234624328388 	 Accuracy: 0.18252933507170796
Delta: 2.9772012743410215e-05 	  Loss: 1.6492112500736429 	 Accuracy: 0.18252933507170796
Delta: 5.940938795109127e-05 	  Loss: 1.6493449964900424 	 Accuracy: 0.18252933507170796
Delta: 0.002925549820201829 	  Loss: 1.6494946471694838 	 Accuracy: 0.18252933507170796
Delta: 6.973101055009467e-05 	  Loss: 1.6493358123425779 	 Accuracy: 0.18122555410691005
Delta: 0.0024670238054054893 	  Loss: 1.6491330193831821 	 Accuracy: 0.18122555410691005
Delta: 0.0030409585125762955 	  Loss: 1.6490288100373878 	 Accuracy: 0.18252933507170796
Delta: 0.0026187427287645256 	  Loss: 1.6487440509413451 	 Accuracy: 0.18252933507170796
Delta: 0.0018360243349319005 	  Loss: 1.6486348486947358 	 Accuracy: 0.18383311603650587
Delta: 0.001085959873457124 	  Loss: 1.6488274147496798 	 Accuracy: 0.18252933507170796
Delta: 0.001782672697080893 	  Loss: 1.6488598675800499 	 Accuracy: 0.18252933507170796
Delta: 0.0022802526496457963 	  Loss: 1.6492273407108655 	 Accuracy: 0.18252933507170796
Delta: 0.0014418505886843614 	  Loss: 1.6487291502611396 	 Accuracy: 0.18252933507170796
Delta: 0.0009221675263619155 	  Loss: 1.648771973335233 	 Accuracy: 0.17992177314211213
Delta: 0.002006025018787057 	  Loss: 1.648973113974641 	 Accuracy: 0.18252933507170796
Delta: 0.00010079281965736495 	  Loss: 1.6488719597031056 	 Accuracy: 0.18252933507170796
Delta: 0.001006939446587177 	  Loss: 1.6490031492756447 	 Accuracy: 0.18122555410691005
Delta: 0.0027388647146833105 	  Loss: 1.6494492211029792 	 Accuracy: 0.18252933507170796
Delta: 0.0009070546798600079 	  Loss: 1.6496017211179341 	 Accuracy: 0.18252933507170796
Delta: 0.0005475536467136393 	  Loss: 1.6494797030536268 	 Accuracy: 0.17992177314211213
Delta: 0.0021776826394054017 	  Loss: 1.6495452838947124 	 Accuracy: 0.18252933507170796
Delta: 0.002468730624758261 	  Loss: 1.6490104032052482 	 Accuracy: 0.18122555410691005
Delta: 0.0029158808983131327 	  Loss: 1.6488449467722344 	 Accuracy: 0.18252933507170796
Delta: 0.00137470105724164 	  Loss: 1.6488305688966065 	 Accuracy: 0.18252933507170796
Delta: 3.4695146081676316e-05 	  Loss: 1.6488407715090636 	 Accuracy: 0.17992177314211213
Delta: 8.04592328775984e-05 	  Loss: 1.6488182883552842 	 Accuracy: 0.19035202086049544
Delta: 0.003465345592971553 	  Loss: 1.6483078675315292 	 Accuracy: 0.18383311603650587
Delta: 0.001112174239269268 	  Loss: 1.6485131714885677 	 Accuracy: 0.18252933507170796
Delta: 0.00205004860438577 	  Loss: 1.6483841851241752 	 Accuracy: 0.18383311603650587
Delta: 0.0030978667780403027 	  Loss: 1.6484710986371596 	 Accuracy: 0.18383311603650587
Delta: 0.006229363683861334 	  Loss: 1.6491263686178983 	 Accuracy: 0.19426336375488917
Delta: 0.0043725914872914514 	  Loss: 1.648602315973394 	 Accuracy: 0.1773142112125163
Delta: 0.005130060925938482 	  Loss: 1.6490453016915758 	 Accuracy: 0.18513689700130379
Delta: 0.0023321250667031486 	  Loss: 1.6491321660674112 	 Accuracy: 0.18252933507170796
Delta: 0.0037812107945114446 	  Loss: 1.649455638081239 	 Accuracy: 0.17861799217731422
Delta: 0.0026466811854747485 	  Loss: 1.6494986315262024 	 Accuracy: 0.16427640156453716
Delta: 0.005710575523364675 	  Loss: 1.6487676257377726 	 Accuracy: 0.18252933507170796
Delta: 0.0024563295357900466 	  Loss: 1.6491119972002557 	 Accuracy: 0.18122555410691005
Delta: 0.004386304443267001 	  Loss: 1.6498199320369316 	 Accuracy: 0.18252933507170796
Delta: 0.002928797733811428 	  Loss: 1.649755701488885 	 Accuracy: 0.17861799217731422
Delta: 0.005682426920973062 	  Loss: 1.6498611834752483 	 Accuracy: 0.18122555410691005
Delta: 0.003770066056583721 	  Loss: 1.649347675075316 	 Accuracy: 0.18122555410691005
Delta: 0.0042800765162180334 	  Loss: 1.6495700960421087 	 Accuracy: 0.18122555410691005
Delta: 0.004170386017201235 	  Loss: 1.6490223089316378 	 Accuracy: 0.18122555410691005
Delta: 0.0006454970792696394 	  Loss: 1.648930564224274 	 Accuracy: 0.1877444589308996
Delta: 0.004545583244823169 	  Loss: 1.6488200558533297 	 Accuracy: 0.18252933507170796
Delta: 0.0026238258523012987 	  Loss: 1.649288515438089 	 Accuracy: 0.16297262059973924
Delta: 0.006012651950311163 	  Loss: 1.6507498097474986 	 Accuracy: 0.18252933507170796
Delta: 0.005686340939766599 	  Loss: 1.6504632765040053 	 Accuracy: 0.18252933507170796
Delta: 0.006263035991807725 	  Loss: 1.6512371299756612 	 Accuracy: 0.18122555410691005
Delta: 0.004915096138030949 	  Loss: 1.6498656681404216 	 Accuracy: 0.18122555410691005
Delta: 0.005301278995923965 	  Loss: 1.6524551997046442 	 Accuracy: 0.18252933507170796
Delta: 0.0029165392627619894 	  Loss: 1.6521303477136402 	 Accuracy: 0.18122555410691005
Delta: 0.0021605180167479296 	  Loss: 1.6522468749476824 	 Accuracy: 0.18252933507170796
Delta: 0.003147724681481307 	  Loss: 1.6519088825394468 	 Accuracy: 0.18252933507170796
Delta: 0.0026239550646343156 	  Loss: 1.651923982599949 	 Accuracy: 0.18252933507170796
Delta: 0.0036393811611809515 	  Loss: 1.651888784166416 	 Accuracy: 0.18122555410691005
Delta: 0.004001091394787903 	  Loss: 1.6525757768687575 	 Accuracy: 0.17861799217731422
Delta: 0.0006507409931529698 	  Loss: 1.652587366460799 	 Accuracy: 0.18122555410691005
Delta: 0.0036167417967991667 	  Loss: 1.6531965237916717 	 Accuracy: 0.18122555410691005
Delta: 0.0036017118937760177 	  Loss: 1.653482496569686 	 Accuracy: 0.1760104302477184
Delta: 0.004001208464900988 	  Loss: 1.6536212182406271 	 Accuracy: 0.17209908735332463
Delta: 0.004791545521262069 	  Loss: 1.6546996360515633 	 Accuracy: 0.17992177314211213
Delta: 0.005551649577196127 	  Loss: 1.6532061049673819 	 Accuracy: 0.18383311603650587
Delta: 0.0035970108037611808 	  Loss: 1.6529943540921805 	 Accuracy: 0.18252933507170796
Delta: 2.9104689617292214e-05 	  Loss: 1.6530359378927924 	 Accuracy: 0.18252933507170796
Delta: 0.0008465852962614223 	  Loss: 1.6529762387920153 	 Accuracy: 0.18383311603650587
Delta: 0.0032097439053699276 	  Loss: 1.6529201968279845 	 Accuracy: 0.18252933507170796
Delta: 0.0053204663423005 	  Loss: 1.651642568309316 	 Accuracy: 0.17992177314211213
Delta: 0.0054708099532317185 	  Loss: 1.6526650314411278 	 Accuracy: 0.17861799217731422
Delta: 0.004041000023990547 	  Loss: 1.6526096814086797 	 Accuracy: 0.17861799217731422
Delta: 0.004824657953013282 	  Loss: 1.6516494809843378 	 Accuracy: 0.1773142112125163
Delta: 0.002459541871666743 	  Loss: 1.6516050021838327 	 Accuracy: 0.17992177314211213
Delta: 0.0037250508105119468 	  Loss: 1.6514089351795265 	 Accuracy: 0.17992177314211213
Delta: 0.001957620531989267 	  Loss: 1.6515597994338238 	 Accuracy: 0.17861799217731422
Delta: 0.00528511833920097 	  Loss: 1.6506475050514342 	 Accuracy: 0.17861799217731422
Delta: 0.004402741837081481 	  Loss: 1.6520065278257787 	 Accuracy: 0.18122555410691005
Delta: 0.0038830058063535422 	  Loss: 1.6518649663856437 	 Accuracy: 0.17992177314211213
Delta: 0.002489197553654729 	  Loss: 1.6513449949007044 	 Accuracy: 0.17209908735332463
Delta: 0.0030402869980666078 	  Loss: 1.6512620478064837 	 Accuracy: 0.17992177314211213
Delta: 0.02103020875837145 	  Loss: 2.1584108135085796 	 Accuracy: 0.2033898305084746
Delta: 0.019415364111656983 	  Loss: 2.0358655505983467 	 Accuracy: 0.20599739243807041
Delta: 0.018073185456706064 	  Loss: 1.8226560852015536 	 Accuracy: 0.2138200782268579
Delta: 0.014899610270461607 	  Loss: 1.700759839365484 	 Accuracy: 0.20990873533246415
Delta: 0.01263779839994937 	  Loss: 1.6658766330176042 	 Accuracy: 0.196870925684485

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009929449261982824 	  Loss: 1.6589555263670972 	 Accuracy: 0.19295958279009126
Delta: 0.006779875278120109 	  Loss: 1.6572556529289548 	 Accuracy: 0.19295958279009126
Delta: 0.0056772861789075165 	  Loss: 1.6572141222644166 	 Accuracy: 0.19295958279009126
Delta: 0.0037007251557280426 	  Loss: 1.6569334734741359 	 Accuracy: 0.19295958279009126
Delta: 0.003619529897308392 	  Loss: 1.6569724669983619 	 Accuracy: 0.19295958279009126
Delta: 0.003840044450464405 	  Loss: 1.6570318501153578 	 Accuracy: 0.19295958279009126
Delta: 0.0016181516384188293 	  Loss: 1.6570195215118655 	 Accuracy: 0.19295958279009126
Delta: 0.002987350022798019 	  Loss: 1.6570426452114635 	 Accuracy: 0.19426336375488917
Delta: 0.0008088761671928389 	  Loss: 1.6572112103828802 	 Accuracy: 0.19426336375488917
Delta: 0.0005202749612781323 	  Loss: 1.657191477954772 	 Accuracy: 0.19295958279009126
Delta: 1.974555979667595e-05 	  Loss: 1.6571768583789366 	 Accuracy: 0.20208604954367665
Delta: 0.005837281498138034 	  Loss: 1.6581864443315584 	 Accuracy: 0.19556714471968709
Delta: 0.004929710576496873 	  Loss: 1.6585956692954844 	 Accuracy: 0.19556714471968709
Delta: 0.0032110218196544265 	  Loss: 1.65873790588991 	 Accuracy: 0.19556714471968709
Delta: 0.003761079089614063 	  Loss: 1.658694181230982 	 Accuracy: 0.19556714471968709
Delta: 0.0032741174139453762 	  Loss: 1.658688080839556 	 Accuracy: 0.19426336375488917
Delta: 0.0022791522187465257 	  Loss: 1.6586083820788535 	 Accuracy: 0.19556714471968709
Delta: 0.0023273445978531527 	  Loss: 1.658597491442246 	 Accuracy: 0.19426336375488917
Delta: 0.002558938228545965 	  Loss: 1.6589057181609344 	 Accuracy: 0.19556714471968709
Delta: 0.0018310931521976189 	  Loss: 1.658566983708905 	 Accuracy: 0.19426336375488917
Delta: 0.0007959503609279818 	  Loss: 1.6585899698320024 	 Accuracy: 0.19556714471968709
Delta: 0.0016790691144690742 	  Loss: 1.6588521367597828 	 Accuracy: 0.19556714471968709
Delta: 0.0028490726434963827 	  Loss: 1.6597262501456542 	 Accuracy: 0.19426336375488917
Delta: 0.0021326407239837964 	  Loss: 1.6591272900062135 	 Accuracy: 0.196870925684485
Delta: 0.0013022379963487792 	  Loss: 1.659193716294258 	 Accuracy: 0.196870925684485
Delta: 0.005714806845435296 	  Loss: 1.6592991375223565 	 Accuracy: 0.1981747066492829
Delta: 0.00583521155782657 	  Loss: 1.6584593565558774 	 Accuracy: 0.196870925684485
Delta: 0.006046249267930246 	  Loss: 1.6602321889114142 	 Accuracy: 0.196870925684485
Delta: 0.0022599659245429535 	  Loss: 1.6602026777457226 	 Accuracy: 0.196870925684485
Delta: 0.0023021936821218175 	  Loss: 1.6595525853782247 	 Accuracy: 0.19556714471968709
Delta: 0.0029847772303731503 	  Loss: 1.6596661180979084 	 Accuracy: 0.19556714471968709
Delta: 0.001291672918488279 	  Loss: 1.6598573230069347 	 Accuracy: 0.19556714471968709
Delta: 0.0008999705968609411 	  Loss: 1.6598861036830912 	 Accuracy: 0.196870925684485
Delta: 0.005435640688530464 	  Loss: 1.6602923197442063 	 Accuracy: 0.1981747066492829
Delta: 0.005174300076344191 	  Loss: 1.659547663913268 	 Accuracy: 0.196870925684485
Delta: 0.003490268362355822 	  Loss: 1.6590565820760095 	 Accuracy: 0.196870925684485
Delta: 0.0029484303345875054 	  Loss: 1.6590348691975438 	 Accuracy: 0.196870925684485
Delta: 0.0025704169114119774 	  Loss: 1.6590633190478123 	 Accuracy: 0.196870925684485
Delta: 0.0005349650231024827 	  Loss: 1.6590339156376204 	 Accuracy: 0.19295958279009126
Delta: 0.0028282243285853857 	  Loss: 1.6592227788617877 	 Accuracy: 0.19556714471968709
Delta: 0.0025675839577031945 	  Loss: 1.6592512900576502 	 Accuracy: 0.1981747066492829
Delta: 0.00581179962103847 	  Loss: 1.6595502458844837 	 Accuracy: 0.1981747066492829
Delta: 0.004647637562061325 	  Loss: 1.6592345832810054 	 Accuracy: 0.1981747066492829
Delta: 0.002307969470161618 	  Loss: 1.6594178041006165 	 Accuracy: 0.1981747066492829
Delta: 0.0013846573188610032 	  Loss: 1.6594425175604286 	 Accuracy: 0.1981747066492829
Delta: 0.0013842784869871447 	  Loss: 1.6594165375068357 	 Accuracy: 0.1981747066492829
Delta: 1.8093552346921793e-05 	  Loss: 1.659511726684884 	 Accuracy: 0.1981747066492829
Delta: 6.232575369527082e-05 	  Loss: 1.6593669578802006 	 Accuracy: 0.1981747066492829
Delta: 6.299073323127044e-05 	  Loss: 1.6594039114240031 	 Accuracy: 0.1981747066492829
Delta: 0.0034752316379250453 	  Loss: 1.6598240064419065 	 Accuracy: 0.1981747066492829
Delta: 0.004609211980600625 	  Loss: 1.6589092890009893 	 Accuracy: 0.196870925684485
Delta: 0.0024954318415780124 	  Loss: 1.6588722208806352 	 Accuracy: 0.1981747066492829
Delta: 0.0038875948338496407 	  Loss: 1.658787185076632 	 Accuracy: 0.1981747066492829
Delta: 0.0005473176741379624 	  Loss: 1.6588553256345882 	 Accuracy: 0.196870925684485
Delta: 0.0014342699560194489 	  Loss: 1.6588518018311955 	 Accuracy: 0.196870925684485
Delta: 0.0028448362763147284 	  Loss: 1.6589564959892762 	 Accuracy: 0.196870925684485
Delta: 0.0031242742762925308 	  Loss: 1.6586339160320533 	 Accuracy: 0.19947848761408082
Delta: 0.0021396918692985828 	  Loss: 1.6588926646784237 	 Accuracy: 0.19295958279009126
Delta: 6.658896262032592e-05 	  Loss: 1.658949631760969 	 Accuracy: 0.19426336375488917
Delta: 0.003016136372136479 	  Loss: 1.6583640630421241 	 Accuracy: 0.19556714471968709
Delta: 0.004355734729296157 	  Loss: 1.6584115885834074 	 Accuracy: 0.19426336375488917
Delta: 0.002777882056149253 	  Loss: 1.6579952990766067 	 Accuracy: 0.19556714471968709
Delta: 0.003993947115143725 	  Loss: 1.6586862207164896 	 Accuracy: 0.19556714471968709
Delta: 0.0034931003993790948 	  Loss: 1.658029904626773 	 Accuracy: 0.19165580182529335
Delta: 0.0038552771965231973 	  Loss: 1.6581190936907235 	 Accuracy: 0.19295958279009126
Delta: 0.000731292381870145 	  Loss: 1.6581857738206276 	 Accuracy: 0.19295958279009126
Delta: 0.0035041577304487587 	  Loss: 1.6586082533066058 	 Accuracy: 0.19426336375488917
Delta: 0.004564980542437296 	  Loss: 1.6580363820262511 	 Accuracy: 0.19426336375488917
Delta: 0.0011440456639061425 	  Loss: 1.6579638959591585 	 Accuracy: 0.19556714471968709
Delta: 0.0028881382251493464 	  Loss: 1.6579633798946736 	 Accuracy: 0.19556714471968709
Delta: 0.0007404853048833329 	  Loss: 1.657850349856273 	 Accuracy: 0.19556714471968709
Delta: 0.002104676532695281 	  Loss: 1.6568538079938215 	 Accuracy: 0.19426336375488917
Delta: 0.0030591473509897107 	  Loss: 1.6571703142567715 	 Accuracy: 0.19295958279009126
Delta: 0.0026174016701597893 	  Loss: 1.6573695069762855 	 Accuracy: 0.19426336375488917
Delta: 0.0026866662477294787 	  Loss: 1.6577082490291057 	 Accuracy: 0.19295958279009126
Delta: 0.002832048208217994 	  Loss: 1.6577619901863725 	 Accuracy: 0.19426336375488917
Delta: 0.0006399313801718578 	  Loss: 1.657897913427218 	 Accuracy: 0.19295958279009126
Delta: 0.0011770224962751367 	  Loss: 1.6579347934885287 	 Accuracy: 0.19426336375488917
Delta: 0.0008827608965665359 	  Loss: 1.6579081110184963 	 Accuracy: 0.19426336375488917
Delta: 0.0036069263764663267 	  Loss: 1.6576938381812396 	 Accuracy: 0.19426336375488917
Delta: 0.0023677689831390295 	  Loss: 1.657207082924208 	 Accuracy: 0.19426336375488917
Delta: 0.0016522592422169979 	  Loss: 1.6574485556011092 	 Accuracy: 0.19295958279009126
Delta: 0.005638654247503142 	  Loss: 1.6566592030830023 	 Accuracy: 0.19426336375488917
Delta: 0.004303955821312714 	  Loss: 1.6569809610179846 	 Accuracy: 0.19556714471968709
Delta: 0.00454278022283442 	  Loss: 1.6569016070887352 	 Accuracy: 0.19426336375488917
Delta: 0.0035741018922560343 	  Loss: 1.6570648101623124 	 Accuracy: 0.19556714471968709
Delta: 0.001962086397145079 	  Loss: 1.6572029709206588 	 Accuracy: 0.19426336375488917
Delta: 0.0042876997802146705 	  Loss: 1.6571986107884737 	 Accuracy: 0.19295958279009126
Delta: 0.003999652586709871 	  Loss: 1.6572613143976853 	 Accuracy: 0.19165580182529335
Delta: 0.0033458588874922405 	  Loss: 1.657308062209692 	 Accuracy: 0.19295958279009126
Delta: 5.192728205095602e-05 	  Loss: 1.657311288742724 	 Accuracy: 0.19426336375488917
Delta: 0.001225961146377329 	  Loss: 1.657337615196135 	 Accuracy: 0.19035202086049544
Delta: 7.381703554681885e-05 	  Loss: 1.6573107886968683 	 Accuracy: 0.19295958279009126
Delta: 0.002165346307319551 	  Loss: 1.6574766538725556 	 Accuracy: 0.19295958279009126
Delta: 4.0801505773240805e-05 	  Loss: 1.6575187492356502 	 Accuracy: 0.19556714471968709
Delta: 0.021009016540458017 	  Loss: 2.1585649231917188 	 Accuracy: 0.2033898305084746
Delta: 0.019318450129043842 	  Loss: 2.032486198645132 	 Accuracy: 0.16688396349413298
Delta: 0.018198383482463026 	  Loss: 1.8223569542679843 	 Accuracy: 0.20599739243807041
Delta: 0.015957577070226128 	  Loss: 1.6941006143576751 	 Accuracy: 0.21903520208604954
Delta: 0.012324283493897255 	  Loss: 1.6597068068349032 	 Accuracy: 0.2046936114732725

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009342346379048044 	  Loss: 1.651561193073043 	 Accuracy: 0.20599739243807041
Delta: 0.0075043920703399295 	  Loss: 1.6497253901979763 	 Accuracy: 0.20860495436766624
Delta: 0.00445462631315181 	  Loss: 1.6498794596542605 	 Accuracy: 0.20990873533246415
Delta: 0.0036433788700156763 	  Loss: 1.6495783658455911 	 Accuracy: 0.20990873533246415
Delta: 0.003197303483349397 	  Loss: 1.6494546274526485 	 Accuracy: 0.20990873533246415
Delta: 0.0036503228281580652 	  Loss: 1.6498555408730207 	 Accuracy: 0.20990873533246415
Delta: 0.0036651430718131974 	  Loss: 1.649984997855102 	 Accuracy: 0.20990873533246415
Delta: 0.003827079749149762 	  Loss: 1.6504792636054981 	 Accuracy: 0.20990873533246415
Delta: 0.002169074825316675 	  Loss: 1.6506307572962968 	 Accuracy: 0.20990873533246415
Delta: 0.0013249115894502222 	  Loss: 1.6500949634106243 	 Accuracy: 0.20990873533246415
Delta: 0.0007085818599745777 	  Loss: 1.650167963814417 	 Accuracy: 0.20990873533246415
Delta: 0.0026452569362385653 	  Loss: 1.6498188702133443 	 Accuracy: 0.20990873533246415
Delta: 0.003421793852973265 	  Loss: 1.649822806570937 	 Accuracy: 0.20990873533246415
Delta: 0.0037183285065707024 	  Loss: 1.6498198734988607 	 Accuracy: 0.20990873533246415
Delta: 0.0016526400177439996 	  Loss: 1.6504229650918236 	 Accuracy: 0.20990873533246415
Delta: 0.003773233821567719 	  Loss: 1.6504922198646508 	 Accuracy: 0.20990873533246415
Delta: 0.0025783412620927417 	  Loss: 1.6501378511893596 	 Accuracy: 0.20990873533246415
Delta: 0.0011577288930347783 	  Loss: 1.6506987155324426 	 Accuracy: 0.20990873533246415
Delta: 0.0019485112621345567 	  Loss: 1.650063002208531 	 Accuracy: 0.20990873533246415
Delta: 0.001851789762871464 	  Loss: 1.6500624779240722 	 Accuracy: 0.20990873533246415
Delta: 0.0012719295840797123 	  Loss: 1.650493771245376 	 Accuracy: 0.20990873533246415
Delta: 0.0005733092425435523 	  Loss: 1.6505815841686986 	 Accuracy: 0.20990873533246415
Delta: 0.0026887073121523806 	  Loss: 1.650464745741451 	 Accuracy: 0.21121251629726207
Delta: 0.001780368347997967 	  Loss: 1.650612858512885 	 Accuracy: 0.20990873533246415
Delta: 4.249271491892561e-05 	  Loss: 1.6505823549221752 	 Accuracy: 0.21251629726205998
Delta: 0.004408774379095816 	  Loss: 1.6505884841277991 	 Accuracy: 0.20990873533246415
Delta: 0.002939728457888142 	  Loss: 1.6505616515725268 	 Accuracy: 0.21121251629726207
Delta: 0.0033584330510426728 	  Loss: 1.6500408359297034 	 Accuracy: 0.21121251629726207
Delta: 0.0028956687017845186 	  Loss: 1.6497752552903333 	 Accuracy: 0.21121251629726207
Delta: 0.0010048764220738668 	  Loss: 1.6496917145849008 	 Accuracy: 0.21251629726205998
Delta: 0.0011444032520394757 	  Loss: 1.6500095339970509 	 Accuracy: 0.20990873533246415
Delta: 0.004116661755066938 	  Loss: 1.6510099793826 	 Accuracy: 0.21251629726205998
Delta: 0.0057626757008194295 	  Loss: 1.6507009036585008 	 Accuracy: 0.20990873533246415
Delta: 0.003224740876853217 	  Loss: 1.6508318661575436 	 Accuracy: 0.21121251629726207
Delta: 0.004006367464475882 	  Loss: 1.651550957718173 	 Accuracy: 0.21251629726205998
Delta: 0.0021478049132081125 	  Loss: 1.6519876283129822 	 Accuracy: 0.21251629726205998
Delta: 0.00253559338536819 	  Loss: 1.6531869429883905 	 Accuracy: 0.21251629726205998
Delta: 0.005128374128882517 	  Loss: 1.653279282851455 	 Accuracy: 0.21121251629726207
Delta: 0.004045921197102517 	  Loss: 1.6532487124968904 	 Accuracy: 0.20860495436766624
Delta: 0.003159515775442581 	  Loss: 1.6530470870227572 	 Accuracy: 0.20990873533246415
Delta: 0.0016844824938611602 	  Loss: 1.6517025259814508 	 Accuracy: 0.20990873533246415
Delta: 0.0029930582295270214 	  Loss: 1.6511706823569647 	 Accuracy: 0.21251629726205998
Delta: 0.0044050437197852765 	  Loss: 1.652616029147634 	 Accuracy: 0.21121251629726207
Delta: 0.0017194218996537493 	  Loss: 1.652006651137044 	 Accuracy: 0.20990873533246415
Delta: 8.19560710003047e-05 	  Loss: 1.651920366168377 	 Accuracy: 0.20860495436766624
Delta: 0.0038702119183527854 	  Loss: 1.6540015610278402 	 Accuracy: 0.20860495436766624
Delta: 0.004783046588854175 	  Loss: 1.6519952646880707 	 Accuracy: 0.21121251629726207
Delta: 0.0038840334564368634 	  Loss: 1.6510517396318742 	 Accuracy: 0.21251629726205998
Delta: 0.004699911269109999 	  Loss: 1.650841293351653 	 Accuracy: 0.2151238591916558
Delta: 0.0030377996758601962 	  Loss: 1.6518001698644464 	 Accuracy: 0.2138200782268579
Delta: 0.0008393551883825093 	  Loss: 1.6514104299639811 	 Accuracy: 0.21642764015645372
Delta: 0.003445866802542848 	  Loss: 1.65183538390283 	 Accuracy: 0.2138200782268579
Delta: 0.005536626027672635 	  Loss: 1.65070872135813 	 Accuracy: 0.21251629726205998
Delta: 0.0008811565848277466 	  Loss: 1.6505034855476564 	 Accuracy: 0.2138200782268579
Delta: 0.003691391093030499 	  Loss: 1.6505452771842752 	 Accuracy: 0.21642764015645372
Delta: 0.004826922492366723 	  Loss: 1.650646711803307 	 Accuracy: 0.2151238591916558
Delta: 0.005328285323452395 	  Loss: 1.6514505345073078 	 Accuracy: 0.20860495436766624
Delta: 0.006115835816161257 	  Loss: 1.6513893498645138 	 Accuracy: 0.20599739243807041
Delta: 0.005261914399894675 	  Loss: 1.6516845795391735 	 Accuracy: 0.20990873533246415
Delta: 0.005755534556095033 	  Loss: 1.6518072661714163 	 Accuracy: 0.2046936114732725
Delta: 0.003676748415324655 	  Loss: 1.6524535768075261 	 Accuracy: 0.21121251629726207
Delta: 0.0026587840349579315 	  Loss: 1.6518720147662134 	 Accuracy: 0.20730117340286833
Delta: 0.001557921169282613 	  Loss: 1.6520891863568785 	 Accuracy: 0.20730117340286833
Delta: 0.0047272727529696495 	  Loss: 1.652526877769823 	 Accuracy: 0.20730117340286833
Delta: 0.0032638545688655307 	  Loss: 1.6526485926259347 	 Accuracy: 0.20599739243807041
Delta: 0.004851298673869181 	  Loss: 1.6527062582546923 	 Accuracy: 0.20860495436766624
Delta: 0.003109852205647309 	  Loss: 1.6524965106832104 	 Accuracy: 0.20730117340286833
Delta: 0.002510023983391916 	  Loss: 1.6525773915441722 	 Accuracy: 0.20599739243807041
Delta: 0.004394681316685859 	  Loss: 1.6524405615129925 	 Accuracy: 0.20730117340286833
Delta: 0.004539967003356829 	  Loss: 1.652342851487008 	 Accuracy: 0.20730117340286833
Delta: 0.002625747619713299 	  Loss: 1.6524834301863498 	 Accuracy: 0.20990873533246415
Delta: 0.0009859728840212313 	  Loss: 1.6524361612209941 	 Accuracy: 0.20730117340286833
Delta: 5.318330652719806e-05 	  Loss: 1.652515428622141 	 Accuracy: 0.2046936114732725
Delta: 0.003402988836587384 	  Loss: 1.652936742949128 	 Accuracy: 0.20599739243807041
Delta: 0.002495857933773261 	  Loss: 1.6525656322531685 	 Accuracy: 0.20078226857887874
Delta: 0.004813682127541888 	  Loss: 1.6533958545011431 	 Accuracy: 0.2046936114732725
Delta: 0.0057582397867585325 	  Loss: 1.6530458643157515 	 Accuracy: 0.2046936114732725
Delta: 0.0021683214409473997 	  Loss: 1.6528202345608043 	 Accuracy: 0.2046936114732725
Delta: 0.004144157390915857 	  Loss: 1.6540384222581697 	 Accuracy: 0.20599739243807041
Delta: 0.0044817908811054805 	  Loss: 1.6513620512770535 	 Accuracy: 0.2046936114732725
Delta: 0.005206112456333081 	  Loss: 1.6540016263184696 	 Accuracy: 0.21903520208604954
Delta: 0.004917577038833283 	  Loss: 1.6533924766216608 	 Accuracy: 0.20599739243807041
Delta: 0.0024249938098583074 	  Loss: 1.6542107305901688 	 Accuracy: 0.2033898305084746
Delta: 0.0058899167182250274 	  Loss: 1.656161432494284 	 Accuracy: 0.20860495436766624
Delta: 0.0036456919449218096 	  Loss: 1.6544813289416698 	 Accuracy: 0.19556714471968709
Delta: 0.00575997829097689 	  Loss: 1.6559016773411166 	 Accuracy: 0.20078226857887874
Delta: 0.0042258025515168225 	  Loss: 1.6550850137267836 	 Accuracy: 0.20730117340286833
Delta: 0.0038776869347033173 	  Loss: 1.6553998294122172 	 Accuracy: 0.20860495436766624
Delta: 0.0042584579041443655 	  Loss: 1.6555834059344408 	 Accuracy: 0.20730117340286833
Delta: 0.002424399535399835 	  Loss: 1.6556923752509047 	 Accuracy: 0.2138200782268579
Delta: 0.006420866725002302 	  Loss: 1.6554413341636423 	 Accuracy: 0.20860495436766624
Delta: 0.0024775670399790396 	  Loss: 1.6553612199376566 	 Accuracy: 0.21121251629726207
Delta: 0.005580308836680649 	  Loss: 1.6532292319194783 	 Accuracy: 0.20860495436766624
Delta: 0.006582469703107966 	  Loss: 1.6515306221740214 	 Accuracy: 0.21251629726205998
Delta: 0.00590152899129904 	  Loss: 1.653417017235865 	 Accuracy: 0.21121251629726207
Delta: 0.020919202452281963 	  Loss: 2.1542061455324237 	 Accuracy: 0.19426336375488917
Delta: 0.01841517863214712 	  Loss: 2.086117522014119 	 Accuracy: 0.3220338983050847
Delta: 0.01645858388805336 	  Loss: 1.9941036896348647 	 Accuracy: 0.5176010430247718
Delta: 0.01547632147699957 	  Loss: 1.8821783684191862 	 Accuracy: 0.5801825293350718
Delta: 0.013319646555722216 	  Loss: 1.7732989837670923 	 Accuracy: 0.6427640156453716
Delta: 0.011315364524879799 	  Loss: 1.703339200013354 	 Accuracy: 0.6427640156453716
Delta: 0.010096461892331876 	  Loss: 1.6581347628882073 	 Accuracy: 0.6558018252933507
Delta: 0.008867245833513488 	  Loss: 1.6283035286278114 	 Accuracy: 0.6597131681877445
Delta: 0.007796387074678991 	  Loss: 1.6079600570781236 	 Accuracy: 0.6636245110821382
Delta: 0.00778923713394822 	  Loss: 1.5932966676413403 	 Accuracy: 0.666232073011734
Delta: 0.0072528028394569155 	  Loss: 1.582150804956764 	 Accuracy: 0.6766623207301173
Delta: 0.007002219838852583 	  Loss: 1.5736506441942302 	 Accuracy: 0.6779661016949152
Delta: 0.006585577893636026 	  Loss: 1.567230383119636 	 Accuracy: 0.6844850065189049
Delta: 0.006305272306253483 	  Loss: 1.5621246805974787 	 Accuracy: 0.7027379400260756
Delta: 0.0065989095305897085 	  Loss: 1.5577399194865615 	 Accuracy: 0.6962190352020861
Delta: 0.006700501984084177 	  Loss: 1.553491727039722 	 Accuracy: 0.6883963494132985
Delta: 0.005963831533663829 	  Loss: 1.5502903989915924 	 Accuracy: 0.6857887874837028
Delta: 0.00615191889023693 	  Loss: 1.546950978240409 	 Accuracy: 0.6923076923076923
Delta: 0.006180044861174954 	  Loss: 1.5435340789704877 	 Accuracy: 0.6988265971316818
Delta: 0.006668549200597205 	  Loss: 1.5399452433823826 	 Accuracy: 0.6936114732724902
Delta: 0.005505670335717808 	  Loss: 1.5374704756913862 	 Accuracy: 0.6975228161668839
Delta: 0.00516996271340102 	  Loss: 1.5350923425595744 	 Accuracy: 0.6753585397653195
Delta: 0.005651646976461443 	  Loss: 1.5324611897036735 	 Accuracy: 0.6949152542372882
Delta: 0.006261684426226575 	  Loss: 1.5297856372782452 	 Accuracy: 0.6870925684485006
Delta: 0.005275497543696257 	  Loss: 1.5277039442974156 	 Accuracy: 0.6962190352020861
Delta: 0.0061449407120433225 	  Loss: 1.52543511211412 	 Accuracy: 0.7027379400260756
Delta: 0.005074850893554869 	  Loss: 1.5228079848752927 	 Accuracy: 0.7040417209908736
Delta: 0.005401217398733895 	  Loss: 1.5209787319184156 	 Accuracy: 0.7040417209908736
Delta: 0.005088314897227345 	  Loss: 1.5191060552721596 	 Accuracy: 0.7079530638852672
Delta: 0.004501978798564372 	  Loss: 1.5178811486039856 	 Accuracy: 0.7066492829204694
Delta: 0.004393637458489088 	  Loss: 1.5163466882077525 	 Accuracy: 0.7092568448500652
Delta: 0.00427464375439075 	  Loss: 1.5152641643163904 	 Accuracy: 0.7053455019556715
Delta: 0.003078962573254914 	  Loss: 1.5141396655058144 	 Accuracy: 0.7105606258148631
Delta: 0.0038130967933235646 	  Loss: 1.5132735784992826 	 Accuracy: 0.7053455019556715
Delta: 0.003306899727976643 	  Loss: 1.51248754701363 	 Accuracy: 0.7053455019556715

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.004084242339087128 	  Loss: 1.5115915722194218 	 Accuracy: 0.7027379400260756
Delta: 0.004591079264971117 	  Loss: 1.510652967812995 	 Accuracy: 0.7040417209908736
Delta: 0.002851237416281059 	  Loss: 1.50993858300165 	 Accuracy: 0.7040417209908736
Delta: 0.0028751915125756426 	  Loss: 1.5095635734770085 	 Accuracy: 0.7014341590612777
Delta: 0.001365257032996999 	  Loss: 1.5091068477071494 	 Accuracy: 0.7014341590612777
Delta: 0.003119461520359742 	  Loss: 1.508590206917714 	 Accuracy: 0.7014341590612777
Delta: 0.00337089493549227 	  Loss: 1.5081176946437438 	 Accuracy: 0.7040417209908736
Delta: 0.0022399137957246395 	  Loss: 1.5079055298569006 	 Accuracy: 0.7027379400260756
Delta: 0.0007453150503311585 	  Loss: 1.5077188758285123 	 Accuracy: 0.7001303780964798
Delta: 0.002758243022924812 	  Loss: 1.507405222095168 	 Accuracy: 0.7027379400260756
Delta: 0.0019205194034170162 	  Loss: 1.5071491062621285 	 Accuracy: 0.7027379400260756
Delta: 0.0029314127947477698 	  Loss: 1.5068239001084187 	 Accuracy: 0.7014341590612777
Delta: 0.0033817131057667328 	  Loss: 1.5064697543776258 	 Accuracy: 0.7001303780964798
Delta: 0.0010310358997014464 	  Loss: 1.5063244820940433 	 Accuracy: 0.7014341590612777
Delta: 0.00285660631518034 	  Loss: 1.5060894697999272 	 Accuracy: 0.7027379400260756
Delta: 0.003518403515231828 	  Loss: 1.5059725058688285 	 Accuracy: 0.7014341590612777
Delta: 0.002815020619685584 	  Loss: 1.5056704562045744 	 Accuracy: 0.7027379400260756
Delta: 0.0016786204091784021 	  Loss: 1.505888353288939 	 Accuracy: 0.6988265971316818
Delta: 0.002573302504081072 	  Loss: 1.5056301282518063 	 Accuracy: 0.7014341590612777
Delta: 0.0011504658388401983 	  Loss: 1.5055298315088368 	 Accuracy: 0.7027379400260756
Delta: 0.0025136001326288796 	  Loss: 1.5053598411623976 	 Accuracy: 0.7014341590612777
Delta: 0.0029810225796492187 	  Loss: 1.5052691615183704 	 Accuracy: 0.7001303780964798
Delta: 0.001912928196811798 	  Loss: 1.5051648635860078 	 Accuracy: 0.7001303780964798
Delta: 0.0026035653911288177 	  Loss: 1.5049583199595384 	 Accuracy: 0.7001303780964798
Delta: 0.002564310599278151 	  Loss: 1.504875424995108 	 Accuracy: 0.6988265971316818
Delta: 0.0016069521283126366 	  Loss: 1.5047447211225384 	 Accuracy: 0.6988265971316818
Delta: 0.003756015410465613 	  Loss: 1.5046101768205353 	 Accuracy: 0.7001303780964798
Delta: 0.002355157149657453 	  Loss: 1.5044306034392279 	 Accuracy: 0.6962190352020861
Delta: 0.002747720567982953 	  Loss: 1.5044397379601404 	 Accuracy: 0.7014341590612777
Delta: 0.0024185071665876775 	  Loss: 1.5043877285959861 	 Accuracy: 0.6988265971316818
Delta: 0.0006314668098537925 	  Loss: 1.5042893826408579 	 Accuracy: 0.7001303780964798
Delta: 0.002099661243668136 	  Loss: 1.504173039624518 	 Accuracy: 0.6988265971316818
Delta: 0.0034478076384941553 	  Loss: 1.504075684200803 	 Accuracy: 0.6988265971316818
Delta: 0.0014173842219974311 	  Loss: 1.5039653584027295 	 Accuracy: 0.7001303780964798
Delta: 0.0021696977639467973 	  Loss: 1.503925939031371 	 Accuracy: 0.7014341590612777
Delta: 0.0018672277394199408 	  Loss: 1.503958683985085 	 Accuracy: 0.7040417209908736
Delta: 0.0019578909056148985 	  Loss: 1.5038414799235014 	 Accuracy: 0.7014341590612777
Delta: 0.0008176746089108775 	  Loss: 1.5037809524746824 	 Accuracy: 0.7014341590612777
Delta: 0.0020346440409545756 	  Loss: 1.5037716017597886 	 Accuracy: 0.7040417209908736
Delta: 0.0019303895481215729 	  Loss: 1.5037496369903662 	 Accuracy: 0.7027379400260756
Delta: 0.0005294022322951233 	  Loss: 1.5037277820719583 	 Accuracy: 0.7001303780964798
Delta: 0.0019083178069364368 	  Loss: 1.5037245140844702 	 Accuracy: 0.7014341590612777
Delta: 2.5829363754331733e-05 	  Loss: 1.503661984604661 	 Accuracy: 0.7001303780964798
Delta: 0.0013910220037500576 	  Loss: 1.503652105906269 	 Accuracy: 0.7001303780964798
Delta: 0.001961853354195024 	  Loss: 1.5035808335868044 	 Accuracy: 0.7001303780964798
Delta: 0.0009616159137982327 	  Loss: 1.5035309245337647 	 Accuracy: 0.7027379400260756
Delta: 0.0006344794422447301 	  Loss: 1.5035200164315243 	 Accuracy: 0.7014341590612777
Delta: 3.3322022443410876e-05 	  Loss: 1.5034814979880142 	 Accuracy: 0.7027379400260756
Delta: 0.0007247590660394268 	  Loss: 1.5034557235330066 	 Accuracy: 0.7027379400260756
Delta: 0.0007960015491018375 	  Loss: 1.5034248854089198 	 Accuracy: 0.7014341590612777
Delta: 0.0014649312001342213 	  Loss: 1.5034210331394848 	 Accuracy: 0.7027379400260756
Delta: 0.0011667822458131683 	  Loss: 1.5033835288156028 	 Accuracy: 0.7040417209908736
Delta: 0.0029360636696106925 	  Loss: 1.5033417445660997 	 Accuracy: 0.7027379400260756
Delta: 0.0011300606953647805 	  Loss: 1.5033123917042843 	 Accuracy: 0.7014341590612777
Delta: 0.0008727511350380907 	  Loss: 1.503291695059401 	 Accuracy: 0.7027379400260756
Delta: 0.0005241723006589603 	  Loss: 1.503297540784764 	 Accuracy: 0.7040417209908736
Delta: 0.0026474005141073845 	  Loss: 1.5032601615078796 	 Accuracy: 0.7027379400260756
Delta: 0.0021333845750083247 	  Loss: 1.5032444348173586 	 Accuracy: 0.7040417209908736
Delta: 0.0014149147350601317 	  Loss: 1.5031834364879737 	 Accuracy: 0.7027379400260756
Delta: 0.0015976255546607764 	  Loss: 1.5031925444780885 	 Accuracy: 0.7027379400260756
Delta: 0.0008795254428466516 	  Loss: 1.5031523727787803 	 Accuracy: 0.7027379400260756
Delta: 0.001862621011895416 	  Loss: 1.5031339645420276 	 Accuracy: 0.7027379400260756
Delta: 0.0021506646506574095 	  Loss: 1.5030921718228423 	 Accuracy: 0.7027379400260756
Delta: 3.339316415896319e-05 	  Loss: 1.5030488228957557 	 Accuracy: 0.7079530638852672
Delta: 0.0028239605961776428 	  Loss: 1.50299286075649 	 Accuracy: 0.7066492829204694
Delta: 0.02094025516875234 	  Loss: 2.1543854513011986 	 Accuracy: 0.19295958279009126
Delta: 0.01849409182660027 	  Loss: 2.0817685352711353 	 Accuracy: 0.3546284224250326
Delta: 0.017066348208671988 	  Loss: 1.9646724754712004 	 Accuracy: 0.5801825293350718
Delta: 0.014734208923068905 	  Loss: 1.8203359646410149 	 Accuracy: 0.6440677966101694
Delta: 0.012252871303123077 	  Loss: 1.720646293597587 	 Accuracy: 0.6688396349413298
Delta: 0.010841263711804673 	  Loss: 1.6597987883295993 	 Accuracy: 0.6571056062581486
Delta: 0.00957912834471774 	  Loss: 1.620731213497759 	 Accuracy: 0.6649282920469362
Delta: 0.008930401234998307 	  Loss: 1.5956800515038938 	 Accuracy: 0.666232073011734
Delta: 0.00841556296243341 	  Loss: 1.5790507914221217 	 Accuracy: 0.6766623207301173
Delta: 0.0075480100234609215 	  Loss: 1.5680411869859352 	 Accuracy: 0.6779661016949152

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0061858296301027646 	  Loss: 1.5601610626254092 	 Accuracy: 0.6792698826597132
Delta: 0.00669719889061211 	  Loss: 1.554536035533584 	 Accuracy: 0.6831812255541069
Delta: 0.006545975419709901 	  Loss: 1.5501622874543157 	 Accuracy: 0.6870925684485006
Delta: 0.006134350977379102 	  Loss: 1.546842508440953 	 Accuracy: 0.6844850065189049
Delta: 0.006347222435272163 	  Loss: 1.5436296966522827 	 Accuracy: 0.681877444589309
Delta: 0.0061127603129851734 	  Loss: 1.540928428962573 	 Accuracy: 0.6857887874837028
Delta: 0.005858430404748494 	  Loss: 1.538428128179231 	 Accuracy: 0.6870925684485006
Delta: 0.006209450681010345 	  Loss: 1.5360392100573104 	 Accuracy: 0.6883963494132985
Delta: 0.006039317417444916 	  Loss: 1.5338638144343588 	 Accuracy: 0.6910039113428944
Delta: 0.004127371114223891 	  Loss: 1.5324002536514925 	 Accuracy: 0.6910039113428944
Delta: 0.004573190485899193 	  Loss: 1.5309065511493634 	 Accuracy: 0.6949152542372882
Delta: 0.00546509101856831 	  Loss: 1.5292877682195392 	 Accuracy: 0.6975228161668839
Delta: 0.004278505740171338 	  Loss: 1.5281990527773548 	 Accuracy: 0.7001303780964798
Delta: 0.005323402859449062 	  Loss: 1.5267464217547424 	 Accuracy: 0.7001303780964798
Delta: 0.0034417862541204682 	  Loss: 1.5261292656293475 	 Accuracy: 0.7053455019556715
Delta: 0.0036783600847821777 	  Loss: 1.5254680350935648 	 Accuracy: 0.7131681877444589
Delta: 0.0035165400877111065 	  Loss: 1.5250773895961727 	 Accuracy: 0.7092568448500652
Delta: 0.0037301062691597153 	  Loss: 1.5247672170024122 	 Accuracy: 0.7079530638852672
Delta: 0.004032103375266389 	  Loss: 1.5240612784114296 	 Accuracy: 0.7157757496740548
Delta: 0.003710674046984387 	  Loss: 1.5234067948469499 	 Accuracy: 0.7053455019556715
Delta: 0.0033619172092917 	  Loss: 1.5231744698432843 	 Accuracy: 0.7157757496740548
Delta: 0.0033914777388229225 	  Loss: 1.5228932210471415 	 Accuracy: 0.7131681877444589
Delta: 0.0009796834958426001 	  Loss: 1.5228251931847248 	 Accuracy: 0.7144719687092569
Delta: 0.0022420786624160163 	  Loss: 1.5226469897773733 	 Accuracy: 0.7196870925684485
Delta: 0.0009232757173880822 	  Loss: 1.5225479995371027 	 Accuracy: 0.7183833116036505
Delta: 0.0013666687701854943 	  Loss: 1.522528292171553 	 Accuracy: 0.7144719687092569
Delta: 0.003034701603806206 	  Loss: 1.5223073540939756 	 Accuracy: 0.7209908735332464
Delta: 0.004095621222748749 	  Loss: 1.5218026161277358 	 Accuracy: 0.7301173402868318
Delta: 0.003616676627320232 	  Loss: 1.5216127979953418 	 Accuracy: 0.7288135593220338
Delta: 0.0026411165600744788 	  Loss: 1.521446445239096 	 Accuracy: 0.7327249022164276
Delta: 0.0023412113339794714 	  Loss: 1.5213042959701446 	 Accuracy: 0.7314211212516297
Delta: 0.0021817668772399312 	  Loss: 1.5212779518884505 	 Accuracy: 0.7327249022164276
Delta: 0.002881086102858663 	  Loss: 1.521138905052784 	 Accuracy: 0.7314211212516297
Delta: 0.0013897315724488817 	  Loss: 1.5210591084593577 	 Accuracy: 0.7340286831812256
Delta: 0.0009506043277471253 	  Loss: 1.5210908959501892 	 Accuracy: 0.7301173402868318
Delta: 0.000568886072551853 	  Loss: 1.521152878922068 	 Accuracy: 0.7327249022164276
Delta: 0.0032223352820715703 	  Loss: 1.521201646182158 	 Accuracy: 0.7327249022164276
Delta: 0.0007712157717412759 	  Loss: 1.521063736773066 	 Accuracy: 0.7340286831812256
Delta: 4.60320060068175e-05 	  Loss: 1.521003552896346 	 Accuracy: 0.7314211212516297
Delta: 0.0014697924208037954 	  Loss: 1.5210481514427872 	 Accuracy: 0.7353324641460235
Delta: 0.002190346428280744 	  Loss: 1.5210367529092597 	 Accuracy: 0.7353324641460235
Delta: 0.0011529627067789945 	  Loss: 1.521028105503141 	 Accuracy: 0.7392438070404173
Delta: 0.0007395645671325146 	  Loss: 1.5209281416973306 	 Accuracy: 0.7379400260756193
Delta: 0.0018851945523858501 	  Loss: 1.5207524438238662 	 Accuracy: 0.7366362451108214
Delta: 0.0019849473666472663 	  Loss: 1.5207261219441397 	 Accuracy: 0.7340286831812256
Delta: 0.001012040436004128 	  Loss: 1.5207536131835129 	 Accuracy: 0.7340286831812256
Delta: 2.1032950153387905e-05 	  Loss: 1.5207420566120222 	 Accuracy: 0.7340286831812256
Delta: 0.0005093067101103728 	  Loss: 1.5207410508682027 	 Accuracy: 0.7353324641460235
Delta: 0.001485254894306074 	  Loss: 1.5207232224925358 	 Accuracy: 0.7327249022164276
Delta: 0.00108260904094903 	  Loss: 1.5207862732206188 	 Accuracy: 0.7353324641460235
Delta: 0.0016501288381762355 	  Loss: 1.5208065020246002 	 Accuracy: 0.7327249022164276
Delta: 0.0005324710515969357 	  Loss: 1.520760650300001 	 Accuracy: 0.7353324641460235
Delta: 2.724258847971512e-05 	  Loss: 1.5207453042324337 	 Accuracy: 0.7353324641460235
Delta: 2.1585780623004386e-05 	  Loss: 1.5207390470747537 	 Accuracy: 0.7353324641460235
Delta: 0.0014814716443909616 	  Loss: 1.5207009592554273 	 Accuracy: 0.7340286831812256
Delta: 2.3293198201233965e-05 	  Loss: 1.5207257475645586 	 Accuracy: 0.7340286831812256
Delta: 1.441922182715737e-05 	  Loss: 1.520722919932512 	 Accuracy: 0.7353324641460235
Delta: 1.5986060309410476e-05 	  Loss: 1.5207106853770838 	 Accuracy: 0.7353324641460235
Delta: 2.7060909200956834e-05 	  Loss: 1.5206764753365554 	 Accuracy: 0.7340286831812256
Delta: 4.538638887000536e-05 	  Loss: 1.5206878785136393 	 Accuracy: 0.7340286831812256
Delta: 0.0015981812733623256 	  Loss: 1.5206693881991638 	 Accuracy: 0.7327249022164276
Delta: 4.87803860360463e-05 	  Loss: 1.5207038281799725 	 Accuracy: 0.7366362451108214
Delta: 0.0005418012156746612 	  Loss: 1.520618280482608 	 Accuracy: 0.7366362451108214
Delta: 0.002040747850267081 	  Loss: 1.5205866663754977 	 Accuracy: 0.7366362451108214
Delta: 0.0020233470482767333 	  Loss: 1.5204780655921288 	 Accuracy: 0.7366362451108214
Delta: 0.0020065554514410834 	  Loss: 1.520431823142694 	 Accuracy: 0.7366362451108214
Delta: 2.6812274102347177e-05 	  Loss: 1.5204866747035128 	 Accuracy: 0.7379400260756193
Delta: 1.0084439486544154e-05 	  Loss: 1.5204529135464044 	 Accuracy: 0.7379400260756193
Delta: 0.0008087484865656361 	  Loss: 1.520387003289629 	 Accuracy: 0.7392438070404173
Delta: 3.4339440356071985e-05 	  Loss: 1.5203805088869726 	 Accuracy: 0.7392438070404173
Delta: 0.0022078434150313345 	  Loss: 1.5204499639891518 	 Accuracy: 0.7366362451108214
Delta: 0.004761026031121312 	  Loss: 1.5202642306447773 	 Accuracy: 0.7340286831812256
Delta: 0.006588210202388445 	  Loss: 1.5220329017811558 	 Accuracy: 0.7314211212516297
Delta: 0.001959993533624363 	  Loss: 1.5221252045637874 	 Accuracy: 0.7314211212516297
Delta: 0.0017258565689606512 	  Loss: 1.5221369781824496 	 Accuracy: 0.7314211212516297
Delta: 0.000523460194094971 	  Loss: 1.5221568618339258 	 Accuracy: 0.7314211212516297
Delta: 3.20968929799926e-05 	  Loss: 1.5221397584554481 	 Accuracy: 0.7314211212516297
Delta: 0.0005545562905625465 	  Loss: 1.5219499875002358 	 Accuracy: 0.7314211212516297
Delta: 5.7483783096230255e-05 	  Loss: 1.5221431477487504 	 Accuracy: 0.7301173402868318
Delta: 0.0023275172998393186 	  Loss: 1.522086515694996 	 Accuracy: 0.7327249022164276
Delta: 2.2923092824188888e-05 	  Loss: 1.5220571693747131 	 Accuracy: 0.7301173402868318
Delta: 2.4323873165980154e-05 	  Loss: 1.5220378974646371 	 Accuracy: 0.7314211212516297
Delta: 2.754537409189595e-05 	  Loss: 1.5219970419419022 	 Accuracy: 0.7301173402868318
Delta: 0.00081364859653236 	  Loss: 1.521942344349561 	 Accuracy: 0.7327249022164276
Delta: 3.6569541439552855e-05 	  Loss: 1.5219900673944287 	 Accuracy: 0.7314211212516297
Delta: 2.792222505163651e-05 	  Loss: 1.5219440969452396 	 Accuracy: 0.7314211212516297
Delta: 2.9752136225156236e-05 	  Loss: 1.5219484227670426 	 Accuracy: 0.7327249022164276
Delta: 0.0016739637703302582 	  Loss: 1.5218640696086139 	 Accuracy: 0.7327249022164276
Delta: 3.766663360048448e-05 	  Loss: 1.5218751764806417 	 Accuracy: 0.7353324641460235
Delta: 0.0006268711803218758 	  Loss: 1.5219786954447045 	 Accuracy: 0.7353324641460235
Delta: 0.020987287623445643 	  Loss: 2.153470475308477 	 Accuracy: 0.19165580182529335
Delta: 0.018751952719378025 	  Loss: 2.0756093108274882 	 Accuracy: 0.3194263363754889
Delta: 0.017001618344926396 	  Loss: 1.9576660432695796 	 Accuracy: 0.5267275097783573
Delta: 0.01552074598659441 	  Loss: 1.8151494511699675 	 Accuracy: 0.5723598435462842
Delta: 0.013370698061238284 	  Loss: 1.708454566595558 	 Accuracy: 0.6036505867014341
Delta: 0.011786095304268492 	  Loss: 1.6446926486533178 	 Accuracy: 0.5958279009126467
Delta: 0.010120609089168819 	  Loss: 1.6069380962895776 	 Accuracy: 0.5997392438070405
Delta: 0.009434903895708346 	  Loss: 1.5839435845396692 	 Accuracy: 0.5840938722294654
Delta: 0.008303252473547615 	  Loss: 1.569726527905984 	 Accuracy: 0.5749674054758801
Delta: 0.008312649896846052 	  Loss: 1.5596168729327293 	 Accuracy: 0.5541069100391134
Delta: 0.007410425837763223 	  Loss: 1.5523847852062789 	 Accuracy: 0.5567144719687093
Delta: 0.007795193625500352 	  Loss: 1.5460358070315892 	 Accuracy: 0.546284224250326
Delta: 0.007247564556167429 	  Loss: 1.5407265431387198 	 Accuracy: 0.5449804432855281
Delta: 0.0054857457377292035 	  Loss: 1.5371242780741297 	 Accuracy: 0.5488917861799217
Delta: 0.006784084925502458 	  Loss: 1.5334296689367415 	 Accuracy: 0.5397653194263363

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005855083627459275 	  Loss: 1.531203368720756 	 Accuracy: 0.5449804432855281
Delta: 0.006080213273016515 	  Loss: 1.5289875725493245 	 Accuracy: 0.5371577574967406
Delta: 0.004555253600068605 	  Loss: 1.5282618699890147 	 Accuracy: 0.5436766623207301
Delta: 0.0034349123864176176 	  Loss: 1.5276835129635342 	 Accuracy: 0.5449804432855281
Delta: 0.004801679664178644 	  Loss: 1.5272942517244528 	 Accuracy: 0.5423728813559322
Delta: 0.004220912992069406 	  Loss: 1.5266838344760878 	 Accuracy: 0.5410691003911343
Delta: 0.0038140703915374974 	  Loss: 1.5269085243748455 	 Accuracy: 0.5397653194263363
Delta: 0.0025263569935253397 	  Loss: 1.526720022337761 	 Accuracy: 0.5397653194263363
Delta: 0.0018796713707214094 	  Loss: 1.5267463447011531 	 Accuracy: 0.5410691003911343
Delta: 0.0024451958807370703 	  Loss: 1.526675303369032 	 Accuracy: 0.5423728813559322
Delta: 0.002128441221352444 	  Loss: 1.526701356054196 	 Accuracy: 0.5410691003911343
Delta: 0.0037079048969449247 	  Loss: 1.526904629244764 	 Accuracy: 0.5410691003911343
Delta: 5.8067494671623655e-05 	  Loss: 1.5268796733765773 	 Accuracy: 0.5384615384615384
Delta: 0.0011830813195717097 	  Loss: 1.5268637910711844 	 Accuracy: 0.5410691003911343
Delta: 0.0011722047055395047 	  Loss: 1.5265788980172874 	 Accuracy: 0.5423728813559322
Delta: 0.00203461766179939 	  Loss: 1.5267294770378257 	 Accuracy: 0.5423728813559322
Delta: 6.190147744452963e-05 	  Loss: 1.5266090767350926 	 Accuracy: 0.5436766623207301
Delta: 0.001838118386916952 	  Loss: 1.5264563426592406 	 Accuracy: 0.5436766623207301
Delta: 0.0008162630149345255 	  Loss: 1.5264541612091143 	 Accuracy: 0.5436766623207301
Delta: 0.002854507423452189 	  Loss: 1.5263121336278649 	 Accuracy: 0.5423728813559322
Delta: 2.5661792586336264e-05 	  Loss: 1.5263512422207648 	 Accuracy: 0.5410691003911343
Delta: 0.002459525121014335 	  Loss: 1.5264202089919126 	 Accuracy: 0.5423728813559322
Delta: 0.0012295960703398328 	  Loss: 1.5262141499269661 	 Accuracy: 0.5423728813559322
Delta: 0.0005572961140990159 	  Loss: 1.5265279744685252 	 Accuracy: 0.5410691003911343
Delta: 4.7137782383894616e-05 	  Loss: 1.526285939597809 	 Accuracy: 0.5423728813559322
Delta: 0.002251229371050389 	  Loss: 1.526227960814614 	 Accuracy: 0.5410691003911343
Delta: 0.0011204826186811468 	  Loss: 1.5262584484122255 	 Accuracy: 0.5423728813559322
Delta: 3.624593202931698e-05 	  Loss: 1.526126752478472 	 Accuracy: 0.5423728813559322
Delta: 1.2123083440524834e-05 	  Loss: 1.5261271744785496 	 Accuracy: 0.5423728813559322
Delta: 2.9314861170266202e-05 	  Loss: 1.5261803615724978 	 Accuracy: 0.5423728813559322
Delta: 0.0020592878572968064 	  Loss: 1.5262415810117065 	 Accuracy: 0.5423728813559322
Delta: 3.455319288114083e-05 	  Loss: 1.526139895502641 	 Accuracy: 0.5423728813559322
Delta: 0.0027326645066578625 	  Loss: 1.5263557589728105 	 Accuracy: 0.5423728813559322
Delta: 0.0022526139242965305 	  Loss: 1.526187555796831 	 Accuracy: 0.5436766623207301
Delta: 0.0011137805693370306 	  Loss: 1.5262152941298928 	 Accuracy: 0.5423728813559322
Delta: 0.0013794944327780569 	  Loss: 1.526404247771201 	 Accuracy: 0.5436766623207301
Delta: 7.561626742470928e-05 	  Loss: 1.5261656964830859 	 Accuracy: 0.5423728813559322
Delta: 3.2996614635869565e-05 	  Loss: 1.5261086518550462 	 Accuracy: 0.5423728813559322
Delta: 0.0010354633132017368 	  Loss: 1.5259754216918133 	 Accuracy: 0.5410691003911343
Delta: 0.0005550529958278951 	  Loss: 1.5261835818216658 	 Accuracy: 0.5410691003911343
Delta: 0.0015492741142445817 	  Loss: 1.5260474160758148 	 Accuracy: 0.5436766623207301
Delta: 0.001239026910791296 	  Loss: 1.5261979105534567 	 Accuracy: 0.5423728813559322
Delta: 5.7290482025859056e-05 	  Loss: 1.5261790487777391 	 Accuracy: 0.5410691003911343
Delta: 5.261195233102028e-05 	  Loss: 1.5260657535232292 	 Accuracy: 0.5423728813559322
Delta: 0.0029119267060238457 	  Loss: 1.5260584161843131 	 Accuracy: 0.5410691003911343
Delta: 0.002569988731379116 	  Loss: 1.5257529401246506 	 Accuracy: 0.5449804432855281
Delta: 0.0028299797747948796 	  Loss: 1.5261799559158544 	 Accuracy: 0.5423728813559322
Delta: 0.003968563996582513 	  Loss: 1.527210898774992 	 Accuracy: 0.5436766623207301
Delta: 0.002395525119819265 	  Loss: 1.5268226119876283 	 Accuracy: 0.5436766623207301
Delta: 0.002359049112796702 	  Loss: 1.5271331470750185 	 Accuracy: 0.5410691003911343
Delta: 6.209920777328579e-05 	  Loss: 1.527123811380881 	 Accuracy: 0.5423728813559322
Delta: 0.0008029227167015301 	  Loss: 1.5272204380050083 	 Accuracy: 0.5436766623207301
Delta: 0.003080429976131704 	  Loss: 1.52804537000464 	 Accuracy: 0.5410691003911343
Delta: 0.001918929670954528 	  Loss: 1.5275700634938145 	 Accuracy: 0.5410691003911343
Delta: 0.0020735074878474842 	  Loss: 1.5269508851938525 	 Accuracy: 0.5436766623207301
Delta: 0.001201868983108225 	  Loss: 1.5270162747190836 	 Accuracy: 0.5410691003911343
Delta: 0.0014259856115313272 	  Loss: 1.5270418960532244 	 Accuracy: 0.5410691003911343
Delta: 0.000537220758490541 	  Loss: 1.52700941521661 	 Accuracy: 0.5410691003911343
Delta: 0.004100728363838494 	  Loss: 1.5279312765662545 	 Accuracy: 0.5397653194263363
Delta: 0.0023152432617942224 	  Loss: 1.5281974775904064 	 Accuracy: 0.5384615384615384
Delta: 0.0010856319013493841 	  Loss: 1.528186770946776 	 Accuracy: 0.5410691003911343
Delta: 0.0033828779143172745 	  Loss: 1.5277056189527267 	 Accuracy: 0.5423728813559322
Delta: 0.001535376463525606 	  Loss: 1.5274444196010835 	 Accuracy: 0.5423728813559322
Delta: 0.0026427028963670403 	  Loss: 1.527973240429132 	 Accuracy: 0.5410691003911343
Delta: 0.0005889850482279622 	  Loss: 1.5280073709351742 	 Accuracy: 0.5423728813559322
Delta: 0.00401990032868498 	  Loss: 1.527638772535079 	 Accuracy: 0.5410691003911343
Delta: 0.0030594020742692094 	  Loss: 1.5286050753599276 	 Accuracy: 0.5436766623207301
Delta: 0.001924121314738159 	  Loss: 1.5277869787078076 	 Accuracy: 0.5436766623207301
Delta: 0.0008469550365009299 	  Loss: 1.528274122162094 	 Accuracy: 0.5436766623207301
Delta: 0.0029616079451651885 	  Loss: 1.528403606144908 	 Accuracy: 0.5423728813559322
Delta: 0.0018809421093121076 	  Loss: 1.5280076557372744 	 Accuracy: 0.5410691003911343
Delta: 0.0018223688927237805 	  Loss: 1.5287162108154793 	 Accuracy: 0.5423728813559322
Delta: 0.0005736176862451269 	  Loss: 1.5282431758325412 	 Accuracy: 0.5397653194263363
Delta: 0.004698002503342447 	  Loss: 1.5283710994334414 	 Accuracy: 0.5410691003911343
Delta: 0.0006375545827490272 	  Loss: 1.528323325093903 	 Accuracy: 0.5384615384615384
Delta: 0.00252602149102018 	  Loss: 1.5284275973876391 	 Accuracy: 0.5449804432855281
Delta: 0.0015206667607975234 	  Loss: 1.5287778720706893 	 Accuracy: 0.5397653194263363
Delta: 0.0011132202894882017 	  Loss: 1.5285179067408703 	 Accuracy: 0.5397653194263363
Delta: 0.0036858164915375027 	  Loss: 1.528582722758067 	 Accuracy: 0.5397653194263363
Delta: 0.002733817016197656 	  Loss: 1.5284740034658506 	 Accuracy: 0.5397653194263363
Delta: 0.0009711873395189299 	  Loss: 1.528443471174771 	 Accuracy: 0.5384615384615384
Delta: 6.23643984541887e-05 	  Loss: 1.5285480405110798 	 Accuracy: 0.5384615384615384
Delta: 0.002551688319731255 	  Loss: 1.5278767194661267 	 Accuracy: 0.5397653194263363
Delta: 0.002226119988376547 	  Loss: 1.5279384912653602 	 Accuracy: 0.5397653194263363
Delta: 4.727105889394443e-05 	  Loss: 1.5279148835855239 	 Accuracy: 0.5436766623207301
Delta: 0.020940024412262555 	  Loss: 2.1540140923325115 	 Accuracy: 0.19035202086049544
Delta: 0.018431773178753986 	  Loss: 2.077410744159533 	 Accuracy: 0.38722294654498046
Delta: 0.01625733118708138 	  Loss: 1.965577591632996 	 Accuracy: 0.4589308996088657
Delta: 0.015780724983902466 	  Loss: 1.83388041596111 	 Accuracy: 0.45632333767926986
Delta: 0.014066345263121042 	  Loss: 1.7163651163163416 	 Accuracy: 0.4315514993481095
Delta: 0.011982431658175587 	  Loss: 1.6394006291658478 	 Accuracy: 0.39504563233376794
Delta: 0.01013791291094929 	  Loss: 1.6009736422081242 	 Accuracy: 0.38461538461538464
Delta: 0.009125819906465526 	  Loss: 1.5822416403390358 	 Accuracy: 0.3754889178617992
Delta: 0.007928952043587541 	  Loss: 1.5724052373800201 	 Accuracy: 0.36766623207301175
Delta: 0.00751777205015288 	  Loss: 1.5659635486864558 	 Accuracy: 0.3650586701434159
Delta: 0.006573166973829573 	  Loss: 1.5618887018792038 	 Accuracy: 0.36766623207301175
Delta: 0.005871833576386825 	  Loss: 1.5593759417781876 	 Accuracy: 0.363754889178618

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006416938526106748 	  Loss: 1.5572971929276447 	 Accuracy: 0.3624511082138201
Delta: 0.005100801610371706 	  Loss: 1.5557832587746785 	 Accuracy: 0.363754889178618
Delta: 0.004784043624319549 	  Loss: 1.5550652643662692 	 Accuracy: 0.3559322033898305
Delta: 0.004793247509523252 	  Loss: 1.5542344810716398 	 Accuracy: 0.35853976531942633
Delta: 0.0047338786254941916 	  Loss: 1.5542836969673246 	 Accuracy: 0.35984354628422427
Delta: 0.003178173660041416 	  Loss: 1.5540692865970365 	 Accuracy: 0.363754889178618
Delta: 0.003655031335628332 	  Loss: 1.553955523523706 	 Accuracy: 0.35984354628422427
Delta: 0.002612906957001365 	  Loss: 1.5538395576050537 	 Accuracy: 0.35984354628422427
Delta: 0.001815913307668758 	  Loss: 1.553754492228434 	 Accuracy: 0.363754889178618
Delta: 0.001970958219344173 	  Loss: 1.5536960082590452 	 Accuracy: 0.35984354628422427
Delta: 0.003109682691991669 	  Loss: 1.5538075972952727 	 Accuracy: 0.35984354628422427
Delta: 0.002697321711969164 	  Loss: 1.5537097205534673 	 Accuracy: 0.3624511082138201
Delta: 0.0009252656395696851 	  Loss: 1.5536249008682486 	 Accuracy: 0.36114732724902215
Delta: 0.0010000434409256354 	  Loss: 1.5537025272771183 	 Accuracy: 0.3624511082138201
Delta: 0.0016562490905100988 	  Loss: 1.5535861048888848 	 Accuracy: 0.36114732724902215
Delta: 0.0035047178298393245 	  Loss: 1.553556555871804 	 Accuracy: 0.36114732724902215
Delta: 0.0013972961590852286 	  Loss: 1.5536487302171413 	 Accuracy: 0.363754889178618
Delta: 0.0007459809115417062 	  Loss: 1.5534948949107075 	 Accuracy: 0.3624511082138201
Delta: 0.002016287395030131 	  Loss: 1.5535490176252527 	 Accuracy: 0.3624511082138201
Delta: 0.0011054724098700543 	  Loss: 1.5536224119875564 	 Accuracy: 0.36114732724902215
Delta: 2.379355850857296e-05 	  Loss: 1.5536066863549736 	 Accuracy: 0.3624511082138201
Delta: 0.0010953958391629961 	  Loss: 1.5536981218321997 	 Accuracy: 0.3624511082138201
Delta: 0.001145866090745503 	  Loss: 1.5536623481008385 	 Accuracy: 0.3624511082138201
Delta: 5.859649432575209e-05 	  Loss: 1.5535169530641393 	 Accuracy: 0.36114732724902215
Delta: 0.0012390179628283397 	  Loss: 1.5535737405209191 	 Accuracy: 0.3624511082138201
Delta: 5.9909863987405266e-05 	  Loss: 1.5534666531642218 	 Accuracy: 0.363754889178618
Delta: 0.0005361484538425217 	  Loss: 1.55351145206368 	 Accuracy: 0.36114732724902215
Delta: 0.0007627285559834093 	  Loss: 1.553513095035311 	 Accuracy: 0.3624511082138201
Delta: 0.0010589437863385302 	  Loss: 1.5536181441444108 	 Accuracy: 0.363754889178618
Delta: 5.086110272328293e-05 	  Loss: 1.5537597320666985 	 Accuracy: 0.3624511082138201
Delta: 0.0005496200825673975 	  Loss: 1.5534945436536762 	 Accuracy: 0.36114732724902215
Delta: 4.771784148609134e-05 	  Loss: 1.5536312796799232 	 Accuracy: 0.36114732724902215
Delta: 0.002043737051175435 	  Loss: 1.553852952997937 	 Accuracy: 0.36114732724902215
Delta: 0.001541673414452768 	  Loss: 1.5539575405138153 	 Accuracy: 0.36114732724902215
Delta: 0.004356412196163914 	  Loss: 1.553661453925943 	 Accuracy: 0.36114732724902215
Delta: 0.0031078370737844673 	  Loss: 1.5535879343596541 	 Accuracy: 0.36114732724902215
Delta: 0.002767625341896572 	  Loss: 1.5535248266413273 	 Accuracy: 0.36114732724902215
Delta: 0.0025625922432115727 	  Loss: 1.553864544823112 	 Accuracy: 0.35984354628422427
Delta: 0.0035771317507433857 	  Loss: 1.5546681457911378 	 Accuracy: 0.36114732724902215
Delta: 0.0016248777011533177 	  Loss: 1.5539668940070306 	 Accuracy: 0.3624511082138201
Delta: 0.0019804357921069477 	  Loss: 1.5539857139205755 	 Accuracy: 0.3624511082138201
Delta: 0.0023081684111147627 	  Loss: 1.5538490123160844 	 Accuracy: 0.36114732724902215
Delta: 0.001590710891714949 	  Loss: 1.5539137330538442 	 Accuracy: 0.36114732724902215
Delta: 0.002641806761792079 	  Loss: 1.5541786439983296 	 Accuracy: 0.36114732724902215
Delta: 0.0010548688742302423 	  Loss: 1.5541153252783237 	 Accuracy: 0.35984354628422427
Delta: 0.0005571150033744222 	  Loss: 1.5540597272937169 	 Accuracy: 0.36114732724902215
Delta: 2.7684988027766106e-05 	  Loss: 1.554155329935919 	 Accuracy: 0.36114732724902215
Delta: 2.7326777642799356e-05 	  Loss: 1.5540084682240054 	 Accuracy: 0.3533246414602347
Delta: 0.0018129874238832916 	  Loss: 1.55470377509754 	 Accuracy: 0.36114732724902215
Delta: 0.004510801153681006 	  Loss: 1.555397059627554 	 Accuracy: 0.36114732724902215
Delta: 0.000634834363222585 	  Loss: 1.5552545664602 	 Accuracy: 0.36114732724902215
Delta: 6.296054587601925e-05 	  Loss: 1.5554073494836071 	 Accuracy: 0.35984354628422427
Delta: 7.070012544015116e-05 	  Loss: 1.5553988701810306 	 Accuracy: 0.363754889178618
Delta: 0.0029568772137129155 	  Loss: 1.5551901777165846 	 Accuracy: 0.363754889178618
Delta: 0.0034961573787945263 	  Loss: 1.5551844323843145 	 Accuracy: 0.3624511082138201
Delta: 0.0029371311397792727 	  Loss: 1.5549085571671588 	 Accuracy: 0.3624511082138201
Delta: 6.546675489622131e-05 	  Loss: 1.5549225674384344 	 Accuracy: 0.3624511082138201
Delta: 0.0023307674009146605 	  Loss: 1.554298754598617 	 Accuracy: 0.3624511082138201
Delta: 0.002042733360311284 	  Loss: 1.5549011875135488 	 Accuracy: 0.3624511082138201
Delta: 0.0010303656359159428 	  Loss: 1.5554559462742459 	 Accuracy: 0.3624511082138201
Delta: 3.7924450024234415e-05 	  Loss: 1.5553640203851034 	 Accuracy: 0.36114732724902215
Delta: 0.0019305883002600607 	  Loss: 1.5560543707092243 	 Accuracy: 0.35853976531942633
Delta: 0.0009429180127201175 	  Loss: 1.555387031775569 	 Accuracy: 0.35853976531942633
Delta: 0.0014465193604121368 	  Loss: 1.5553237456222013 	 Accuracy: 0.35984354628422427
Delta: 0.0005502851445921844 	  Loss: 1.5553103984346537 	 Accuracy: 0.35984354628422427
Delta: 0.0009783529356127325 	  Loss: 1.55538935676398 	 Accuracy: 0.35984354628422427
Delta: 0.0005811979726935131 	  Loss: 1.555372448710578 	 Accuracy: 0.35984354628422427
Delta: 0.002144895183841382 	  Loss: 1.5553170483524552 	 Accuracy: 0.35984354628422427
Delta: 0.0029609317887106215 	  Loss: 1.55561201108305 	 Accuracy: 0.3624511082138201
Delta: 0.00332830112995569 	  Loss: 1.5550467341831613 	 Accuracy: 0.36114732724902215
Delta: 0.0012120181009077258 	  Loss: 1.5552790625216635 	 Accuracy: 0.35984354628422427
Delta: 0.0005309459029502058 	  Loss: 1.555079277928836 	 Accuracy: 0.3624511082138201
Delta: 0.0011681161630214983 	  Loss: 1.5550701554403716 	 Accuracy: 0.35071707953063885
Delta: 0.001825000726932751 	  Loss: 1.5551677720337056 	 Accuracy: 0.35853976531942633
Delta: 0.0036923423695313946 	  Loss: 1.5553944342725763 	 Accuracy: 0.3624511082138201
Delta: 0.0015742336744499247 	  Loss: 1.555559115290242 	 Accuracy: 0.3624511082138201
Delta: 0.002486782500092905 	  Loss: 1.55518869420637 	 Accuracy: 0.3624511082138201
Delta: 0.0016849288755816964 	  Loss: 1.5553643769452232 	 Accuracy: 0.36114732724902215
Delta: 0.000990728538361157 	  Loss: 1.5551659522901464 	 Accuracy: 0.36114732724902215
Delta: 8.524306929553749e-05 	  Loss: 1.5554413867641377 	 Accuracy: 0.3624511082138201
Delta: 0.0008615719711244419 	  Loss: 1.5554801275142618 	 Accuracy: 0.35984354628422427
Delta: 0.0038777060075785284 	  Loss: 1.5557046976212865 	 Accuracy: 0.36114732724902215
Delta: 0.0027749778669649314 	  Loss: 1.555721719894061 	 Accuracy: 0.36114732724902215
Delta: 0.0005388389523558873 	  Loss: 1.555633168872581 	 Accuracy: 0.36114732724902215
Delta: 0.0026783040515696455 	  Loss: 1.5557537462625581 	 Accuracy: 0.3624511082138201
Delta: 0.0005813105580976731 	  Loss: 1.5560429214210834 	 Accuracy: 0.3663624511082138
Delta: 0.0035809651871209366 	  Loss: 1.5561519601479228 	 Accuracy: 0.3624511082138201
Delta: 0.0025924315809809015 	  Loss: 1.5561789335746226 	 Accuracy: 0.3624511082138201
Delta: 0.021071230598789372 	  Loss: 2.153268720818907 	 Accuracy: 0.1981747066492829
Delta: 0.01909646627287027 	  Loss: 2.064084518160731 	 Accuracy: 0.49282920469361147
Delta: 0.016949488959372958 	  Loss: 1.8867029904806971 	 Accuracy: 0.6232073011734028
Delta: 0.014241407192273386 	  Loss: 1.7224496566997807 	 Accuracy: 0.6492829204693612
Delta: 0.012109102163238938 	  Loss: 1.633772842626111 	 Accuracy: 0.6440677966101694
Delta: 0.010963623396653282 	  Loss: 1.587692667926213 	 Accuracy: 0.6153846153846154
Delta: 0.009281662798787137 	  Loss: 1.5638397959578607 	 Accuracy: 0.5971316818774446
Delta: 0.008293201853725217 	  Loss: 1.5509762082753789 	 Accuracy: 0.5958279009126467

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006947752670995243 	  Loss: 1.544417442347545 	 Accuracy: 0.5919165580182529
Delta: 0.006532012126310386 	  Loss: 1.5410915839813784 	 Accuracy: 0.5840938722294654
Delta: 0.005455378126828765 	  Loss: 1.5387941631263446 	 Accuracy: 0.5827900912646675
Delta: 0.005855104511474679 	  Loss: 1.53744184121641 	 Accuracy: 0.5814863102998696
Delta: 0.0048522910043971275 	  Loss: 1.5367350038400234 	 Accuracy: 0.5840938722294654
Delta: 0.004346494388785535 	  Loss: 1.536391492798007 	 Accuracy: 0.5788787483702738
Delta: 0.004066947283037248 	  Loss: 1.5362510663436795 	 Accuracy: 0.5814863102998696
Delta: 0.004654185230368148 	  Loss: 1.5363331496036838 	 Accuracy: 0.5788787483702738
Delta: 0.002634251381007076 	  Loss: 1.5362170742915795 	 Accuracy: 0.5801825293350718
Delta: 0.002676826166728702 	  Loss: 1.5362630401807944 	 Accuracy: 0.5788787483702738
Delta: 0.001626665981952973 	  Loss: 1.536258784744584 	 Accuracy: 0.5788787483702738
Delta: 0.002703964328418526 	  Loss: 1.536277438967454 	 Accuracy: 0.5801825293350718
Delta: 0.002049107485717274 	  Loss: 1.5362822526905582 	 Accuracy: 0.5801825293350718
Delta: 0.002110456637108559 	  Loss: 1.5362781242395323 	 Accuracy: 0.5788787483702738
Delta: 0.0008173862903262907 	  Loss: 1.5362552304156312 	 Accuracy: 0.5775749674054759
Delta: 0.0008408189923812412 	  Loss: 1.5363095584526978 	 Accuracy: 0.5775749674054759
Delta: 0.0020612603196137197 	  Loss: 1.536263312603546 	 Accuracy: 0.5788787483702738
Delta: 0.00303189096313019 	  Loss: 1.5361193617454942 	 Accuracy: 0.5775749674054759
Delta: 0.0019623499710681594 	  Loss: 1.5363322634789347 	 Accuracy: 0.5775749674054759
Delta: 0.0008309159481179504 	  Loss: 1.5362454746043377 	 Accuracy: 0.5788787483702738
Delta: 4.629883454234908e-05 	  Loss: 1.5362665211455142 	 Accuracy: 0.5775749674054759
Delta: 0.0006288353241234244 	  Loss: 1.5362495856982377 	 Accuracy: 0.5775749674054759
Delta: 4.4787506483610874e-05 	  Loss: 1.536307924880512 	 Accuracy: 0.576271186440678
Delta: 0.0019007565977317397 	  Loss: 1.5364359550384532 	 Accuracy: 0.5788787483702738
Delta: 3.8750351351213125e-05 	  Loss: 1.5362818971214418 	 Accuracy: 0.5788787483702738
Delta: 6.080169138431991e-05 	  Loss: 1.5363884418404095 	 Accuracy: 0.5788787483702738
Delta: 4.861751245842615e-05 	  Loss: 1.536247764305052 	 Accuracy: 0.5775749674054759
Delta: 0.0032557356448257094 	  Loss: 1.536419352622487 	 Accuracy: 0.576271186440678
Delta: 0.004455622922696233 	  Loss: 1.5362120629054496 	 Accuracy: 0.5749674054758801
Delta: 0.004004328410641384 	  Loss: 1.5365110548864271 	 Accuracy: 0.5801825293350718
Delta: 0.0011886798233940725 	  Loss: 1.5365072426894868 	 Accuracy: 0.5788787483702738
Delta: 0.0018913023603516457 	  Loss: 1.5362375723069588 	 Accuracy: 0.5827900912646675
Delta: 0.0014791099426705713 	  Loss: 1.536369694612208 	 Accuracy: 0.5788787483702738
Delta: 0.003150696912411026 	  Loss: 1.5364359803162597 	 Accuracy: 0.5775749674054759
Delta: 0.0005301319977014216 	  Loss: 1.5364252302889891 	 Accuracy: 0.5775749674054759
Delta: 0.0016910980761962568 	  Loss: 1.5365687100449792 	 Accuracy: 0.5788787483702738
Delta: 0.0005607444658847525 	  Loss: 1.5364320727241498 	 Accuracy: 0.576271186440678
Delta: 0.0018643551196401659 	  Loss: 1.5365442839102916 	 Accuracy: 0.5814863102998696
Delta: 0.0005555292145017703 	  Loss: 1.5365159766579133 	 Accuracy: 0.5788787483702738
Delta: 8.359070527891988e-05 	  Loss: 1.5365158794577978 	 Accuracy: 0.5775749674054759
converged at iter  47
Delta: 0.021055617791917253 	  Loss: 2.1529442054245895 	 Accuracy: 0.21642764015645372
Delta: 0.01858251665379259 	  Loss: 2.0697862515057492 	 Accuracy: 0.3155149934810952
Delta: 0.01668066033652658 	  Loss: 1.9390360347724456 	 Accuracy: 0.33116036505867014
Delta: 0.014843413495404143 	  Loss: 1.8094059690899038 	 Accuracy: 0.28683181225554105
Delta: 0.013682876421562273 	  Loss: 1.726028535646037 	 Accuracy: 0.27509778357235987
Delta: 0.013123729200453725 	  Loss: 1.670422513767034 	 Accuracy: 0.26727509778357234
Delta: 0.011456627698671748 	  Loss: 1.6313120445658893 	 Accuracy: 0.258148631029987
Delta: 0.00991636408929117 	  Loss: 1.6077500754760974 	 Accuracy: 0.24641460234680573
Delta: 0.007838624830297538 	  Loss: 1.5954205289259193 	 Accuracy: 0.2438070404172099

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005891265330948219 	  Loss: 1.5905870379035587 	 Accuracy: 0.23989569752281617
Delta: 0.005243278507953535 	  Loss: 1.58873550712461 	 Accuracy: 0.24119947848761408
Delta: 0.005392785698002579 	  Loss: 1.5878482050392757 	 Accuracy: 0.23859191655801826
Delta: 0.0037193338765476006 	  Loss: 1.5874223951935238 	 Accuracy: 0.23728813559322035
Delta: 0.0035858989986298833 	  Loss: 1.5874172152770423 	 Accuracy: 0.23859191655801826
Delta: 0.003089255565970811 	  Loss: 1.587473788970741 	 Accuracy: 0.23728813559322035
Delta: 0.0020499659202865613 	  Loss: 1.5873963371169917 	 Accuracy: 0.23989569752281617
Delta: 0.0021135143697923312 	  Loss: 1.587398863025669 	 Accuracy: 0.23728813559322035
Delta: 0.001398340300305293 	  Loss: 1.5875155438025863 	 Accuracy: 0.23728813559322035
Delta: 3.1349293705941066e-05 	  Loss: 1.5874949813806363 	 Accuracy: 0.23989569752281617
Delta: 0.002527029856670448 	  Loss: 1.5874582509145736 	 Accuracy: 0.23989569752281617
Delta: 0.0007983488849452545 	  Loss: 1.5874980865976147 	 Accuracy: 0.23989569752281617
Delta: 2.054930425935569e-05 	  Loss: 1.5874909927462844 	 Accuracy: 0.23989569752281617
Delta: 4.084534217885793e-05 	  Loss: 1.5874479039930525 	 Accuracy: 0.23989569752281617
Delta: 1.9919329365764673e-05 	  Loss: 1.587470959149739 	 Accuracy: 0.23859191655801826
Delta: 2.6049628618205826e-05 	  Loss: 1.5874968563941816 	 Accuracy: 0.23728813559322035
Delta: 1.165123766468327e-05 	  Loss: 1.5875025335163366 	 Accuracy: 0.23728813559322035
Delta: 1.615826033416005e-05 	  Loss: 1.587504506928358 	 Accuracy: 0.23728813559322035
Delta: 0.0014044510073798746 	  Loss: 1.5875678477835171 	 Accuracy: 0.23859191655801826
Delta: 0.003647360255872432 	  Loss: 1.5878966419484968 	 Accuracy: 0.23859191655801826
Delta: 0.0016058552130116977 	  Loss: 1.5876154363570085 	 Accuracy: 0.23859191655801826
Delta: 0.001966233562608091 	  Loss: 1.5876336262623099 	 Accuracy: 0.23859191655801826
Delta: 0.0038352907242091188 	  Loss: 1.587833157552879 	 Accuracy: 0.23598435462842243
Delta: 0.0037702529965429423 	  Loss: 1.5875397024325346 	 Accuracy: 0.23989569752281617
Delta: 0.0016254504599723244 	  Loss: 1.5876026040943678 	 Accuracy: 0.23859191655801826
Delta: 0.0013060435863355032 	  Loss: 1.5876548290250287 	 Accuracy: 0.23859191655801826
Delta: 0.0014921675057780219 	  Loss: 1.5877335949470457 	 Accuracy: 0.23989569752281617
Delta: 0.0005669876280537073 	  Loss: 1.5877370108289606 	 Accuracy: 0.23598435462842243
Delta: 0.002310846869800228 	  Loss: 1.5877874573540947 	 Accuracy: 0.23859191655801826
Delta: 0.0013305355573866595 	  Loss: 1.587674797335739 	 Accuracy: 0.23859191655801826
Delta: 0.0022737012059746405 	  Loss: 1.587686540563079 	 Accuracy: 0.23859191655801826
Delta: 0.0013896033949615868 	  Loss: 1.587699106261049 	 Accuracy: 0.23728813559322035
Delta: 0.0010135110098443343 	  Loss: 1.5876956505022157 	 Accuracy: 0.23728813559322035
Delta: 0.0032687217623904702 	  Loss: 1.5876910105187338 	 Accuracy: 0.23859191655801826
Delta: 0.0008222511241768692 	  Loss: 1.5876502167927078 	 Accuracy: 0.23859191655801826
Delta: 0.0026904754197981653 	  Loss: 1.5876922482299003 	 Accuracy: 0.23859191655801826
Delta: 0.0011154158617237375 	  Loss: 1.587859174669112 	 Accuracy: 0.23859191655801826
Delta: 0.004659624232093552 	  Loss: 1.5882200968367028 	 Accuracy: 0.23468057366362452
Delta: 0.002452795906960435 	  Loss: 1.5883493355331004 	 Accuracy: 0.23859191655801826
Delta: 0.0025199787973456925 	  Loss: 1.588317635084068 	 Accuracy: 0.23859191655801826
Delta: 0.002789795501025868 	  Loss: 1.588487223137342 	 Accuracy: 0.23598435462842243
Delta: 0.0038970338440426685 	  Loss: 1.5881798033835373 	 Accuracy: 0.23598435462842243
Delta: 0.002363460071617764 	  Loss: 1.588068944086221 	 Accuracy: 0.23598435462842243
Delta: 0.003155253919582758 	  Loss: 1.5878652886308988 	 Accuracy: 0.23598435462842243
Delta: 0.0025398418126213913 	  Loss: 1.5879004456181427 	 Accuracy: 0.23598435462842243
Delta: 0.0016522301800512792 	  Loss: 1.5878076311731855 	 Accuracy: 0.23598435462842243
Delta: 0.0011119143377947942 	  Loss: 1.5877556069490393 	 Accuracy: 0.23468057366362452
Delta: 0.004938580728775843 	  Loss: 1.5883114861614762 	 Accuracy: 0.2333767926988266
Delta: 0.0017885594492333548 	  Loss: 1.5883333665698274 	 Accuracy: 0.2333767926988266
Delta: 0.0025826830279457903 	  Loss: 1.5881100808348627 	 Accuracy: 0.23468057366362452
Delta: 0.003575480533713932 	  Loss: 1.588279712322908 	 Accuracy: 0.23468057366362452
Delta: 0.0019814581747672937 	  Loss: 1.5885633445561385 	 Accuracy: 0.23598435462842243
Delta: 0.0007717729128653135 	  Loss: 1.5883509412244288 	 Accuracy: 0.23468057366362452
Delta: 0.0017785334220601404 	  Loss: 1.5878446195881315 	 Accuracy: 0.23468057366362452
Delta: 0.002552069877380569 	  Loss: 1.588355416842448 	 Accuracy: 0.23728813559322035
Delta: 0.005101651063237952 	  Loss: 1.5898791662718117 	 Accuracy: 0.2320730117340287
Delta: 0.0032126913664275126 	  Loss: 1.589106495994935 	 Accuracy: 0.23468057366362452
Delta: 0.0015709602177997415 	  Loss: 1.5886542550467708 	 Accuracy: 0.23468057366362452
Delta: 0.0026422868728339126 	  Loss: 1.58866688106386 	 Accuracy: 0.23598435462842243
Delta: 0.0030377380728849167 	  Loss: 1.5882288207987156 	 Accuracy: 0.23468057366362452
Delta: 0.0015391075347170324 	  Loss: 1.5881452379817071 	 Accuracy: 0.23468057366362452
Delta: 0.004453613510906678 	  Loss: 1.5877426284012133 	 Accuracy: 0.23468057366362452
Delta: 0.0021103592994582867 	  Loss: 1.588132568450173 	 Accuracy: 0.23468057366362452
Delta: 0.0030691893176903553 	  Loss: 1.5879565587676927 	 Accuracy: 0.23468057366362452
Delta: 0.0016167837963080745 	  Loss: 1.5882695804877245 	 Accuracy: 0.23468057366362452
Delta: 0.002830196576361987 	  Loss: 1.5881058410266142 	 Accuracy: 0.23598435462842243
Delta: 0.0053145780615271275 	  Loss: 1.5880750669459214 	 Accuracy: 0.2333767926988266
Delta: 0.0031457697153162386 	  Loss: 1.5881328878502232 	 Accuracy: 0.23468057366362452
Delta: 0.0031197788522752978 	  Loss: 1.5887653701611706 	 Accuracy: 0.23468057366362452
Delta: 0.0012426239608213485 	  Loss: 1.5885515689381997 	 Accuracy: 0.2333767926988266
Delta: 0.0041532697247270425 	  Loss: 1.5889815295624705 	 Accuracy: 0.23468057366362452
Delta: 0.0017864919070311894 	  Loss: 1.5894065802300186 	 Accuracy: 0.23468057366362452
Delta: 0.0013891442668274947 	  Loss: 1.5894329998541032 	 Accuracy: 0.23468057366362452
Delta: 0.0023608699480524432 	  Loss: 1.5898432470326176 	 Accuracy: 0.23598435462842243
Delta: 0.0020300226839618176 	  Loss: 1.5892413723388135 	 Accuracy: 0.23468057366362452
Delta: 0.001966522766637309 	  Loss: 1.5903879958145473 	 Accuracy: 0.23468057366362452
Delta: 0.0015014963170539278 	  Loss: 1.5892313332394905 	 Accuracy: 0.2333767926988266
Delta: 0.0020022303984019722 	  Loss: 1.5903163083676564 	 Accuracy: 0.2333767926988266
Delta: 0.003140883720915318 	  Loss: 1.5893252443843426 	 Accuracy: 0.2333767926988266
Delta: 0.0035572052328352423 	  Loss: 1.5907329987052554 	 Accuracy: 0.23076923076923078
Delta: 0.0032590024929640376 	  Loss: 1.590904842342037 	 Accuracy: 0.2333767926988266
Delta: 0.003967409153203598 	  Loss: 1.5888840438234775 	 Accuracy: 0.23859191655801826
Delta: 0.005213730306489287 	  Loss: 1.5878929185916744 	 Accuracy: 0.2255541069100391
Delta: 0.0015850739494813293 	  Loss: 1.5880015918014143 	 Accuracy: 0.2333767926988266
Delta: 0.003118991961540243 	  Loss: 1.587607657655149 	 Accuracy: 0.2333767926988266
Delta: 0.0038620221209796006 	  Loss: 1.5879929285476235 	 Accuracy: 0.23598435462842243
Delta: 0.002620847516812698 	  Loss: 1.5875311531173062 	 Accuracy: 0.2320730117340287
Delta: 0.0011175926071219757 	  Loss: 1.587509798832832 	 Accuracy: 0.2320730117340287
Delta: 0.0032780768920479004 	  Loss: 1.5874256494894268 	 Accuracy: 0.2333767926988266
Delta: 0.0037685620031446035 	  Loss: 1.5872373706241 	 Accuracy: 0.2333767926988266
Delta: 0.0034220755134382083 	  Loss: 1.5875965687778217 	 Accuracy: 0.23468057366362452
Delta: 0.020970143337430084 	  Loss: 2.1540647494018645 	 Accuracy: 0.19295958279009126
Delta: 0.018621861758408825 	  Loss: 2.070175568545545 	 Accuracy: 0.4067796610169492
Delta: 0.017829577135169545 	  Loss: 1.9211806432380436 	 Accuracy: 0.5475880052151239
Delta: 0.016299573988092717 	  Loss: 1.7371551708322586 	 Accuracy: 0.5619295958279009
Delta: 0.014112531540029378 	  Loss: 1.624744323468596 	 Accuracy: 0.5371577574967406
Delta: 0.01093964942480111 	  Loss: 1.5760129945819699 	 Accuracy: 0.5345501955671447
Delta: 0.009180962853992275 	  Loss: 1.5566699021407069 	 Accuracy: 0.529335071707953
Delta: 0.008069972738367664 	  Loss: 1.5491520137804122 	 Accuracy: 0.5358539765319427

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007105518530277773 	  Loss: 1.5451066517370533 	 Accuracy: 0.5358539765319427
Delta: 0.00565941885525923 	  Loss: 1.5437031561723509 	 Accuracy: 0.5332464146023468
Delta: 0.005390584476932431 	  Loss: 1.5428272855282485 	 Accuracy: 0.530638852672751
Delta: 0.004363229687151486 	  Loss: 1.542710810015738 	 Accuracy: 0.530638852672751
Delta: 0.0034562392981030018 	  Loss: 1.5425772428691427 	 Accuracy: 0.5332464146023468
Delta: 0.003391580559465909 	  Loss: 1.542355503377546 	 Accuracy: 0.5345501955671447
Delta: 0.0016832101330356943 	  Loss: 1.5423576037486846 	 Accuracy: 0.5332464146023468
Delta: 0.0026279257845701672 	  Loss: 1.5423072642445308 	 Accuracy: 0.5332464146023468
Delta: 3.148630206107072e-05 	  Loss: 1.5423763226353542 	 Accuracy: 0.5332464146023468
Delta: 0.0005165111374440304 	  Loss: 1.5423476606710396 	 Accuracy: 0.5345501955671447
Delta: 2.674628233128447e-05 	  Loss: 1.5423856102192155 	 Accuracy: 0.5358539765319427
Delta: 0.002326070895210443 	  Loss: 1.5423757684444637 	 Accuracy: 0.5358539765319427
Delta: 5.012562687204573e-05 	  Loss: 1.5422901857411166 	 Accuracy: 0.5332464146023468
Delta: 0.0017112909837332286 	  Loss: 1.5423702201334888 	 Accuracy: 0.5332464146023468
Delta: 0.0007851758191499196 	  Loss: 1.5425206002147207 	 Accuracy: 0.5332464146023468
Delta: 2.7680556028807398e-05 	  Loss: 1.542528029340457 	 Accuracy: 0.5332464146023468
Delta: 0.001500903639333191 	  Loss: 1.5422787173502417 	 Accuracy: 0.5332464146023468
Delta: 0.0008632230309530565 	  Loss: 1.5422673690847921 	 Accuracy: 0.5332464146023468
Delta: 2.5132506347044767e-05 	  Loss: 1.5422677610242723 	 Accuracy: 0.5345501955671447
Delta: 0.0011512626001773415 	  Loss: 1.5422811497015823 	 Accuracy: 0.5332464146023468
Delta: 0.0005496490722508011 	  Loss: 1.5423181740844942 	 Accuracy: 0.5332464146023468
Delta: 3.3182596086149457e-05 	  Loss: 1.5424171197186045 	 Accuracy: 0.5345501955671447
Delta: 0.001141300959006306 	  Loss: 1.5427163299697964 	 Accuracy: 0.5358539765319427
Delta: 0.0011197122508292232 	  Loss: 1.5426781685983977 	 Accuracy: 0.5358539765319427
Delta: 0.0014765289252873389 	  Loss: 1.5421135759031406 	 Accuracy: 0.5345501955671447
Delta: 0.0016172009523269916 	  Loss: 1.5419697433084283 	 Accuracy: 0.5345501955671447
Delta: 0.0006692107763264897 	  Loss: 1.5422865121429963 	 Accuracy: 0.5345501955671447
Delta: 0.0009200188025852904 	  Loss: 1.5422378413342264 	 Accuracy: 0.5345501955671447
Delta: 0.0005509502330118498 	  Loss: 1.5422110405850344 	 Accuracy: 0.5319426336375489
Delta: 0.002382048024991151 	  Loss: 1.5420311063395078 	 Accuracy: 0.5345501955671447
Delta: 0.0027834994189195445 	  Loss: 1.5421167666116355 	 Accuracy: 0.5345501955671447
Delta: 2.3454118134134303e-05 	  Loss: 1.54204387832158 	 Accuracy: 0.5332464146023468
Delta: 0.0005388905453606 	  Loss: 1.5423721748843187 	 Accuracy: 0.5345501955671447
Delta: 0.0010105999028034193 	  Loss: 1.5423745681125975 	 Accuracy: 0.5345501955671447
Delta: 0.003854784014634944 	  Loss: 1.5427550293846641 	 Accuracy: 0.5332464146023468
Delta: 0.001916204545266629 	  Loss: 1.5429065144405525 	 Accuracy: 0.530638852672751
Delta: 0.004319462203209412 	  Loss: 1.5432904577506754 	 Accuracy: 0.5345501955671447
Delta: 0.0030093211884128384 	  Loss: 1.542730598987669 	 Accuracy: 0.530638852672751
Delta: 0.0019883124916084895 	  Loss: 1.542837856639013 	 Accuracy: 0.5345501955671447
Delta: 0.0016798067646060573 	  Loss: 1.542528786463816 	 Accuracy: 0.5345501955671447
Delta: 0.0012758635552874553 	  Loss: 1.5424020629012305 	 Accuracy: 0.5345501955671447
Delta: 0.001707366763571928 	  Loss: 1.5421492878651588 	 Accuracy: 0.5345501955671447
Delta: 0.0013886247635331178 	  Loss: 1.5426424423469236 	 Accuracy: 0.5358539765319427
Delta: 0.001552276667625181 	  Loss: 1.5423067596439972 	 Accuracy: 0.5358539765319427
Delta: 0.0010051666523364351 	  Loss: 1.5425857926831243 	 Accuracy: 0.5332464146023468
Delta: 8.358549825156066e-05 	  Loss: 1.5432986981609949 	 Accuracy: 0.5345501955671447
Delta: 0.001323641464425233 	  Loss: 1.5427567273287188 	 Accuracy: 0.5358539765319427
Delta: 0.0007817747409849933 	  Loss: 1.5422514705221997 	 Accuracy: 0.5345501955671447
Delta: 9.882124357446453e-05 	  Loss: 1.5428515519422294 	 Accuracy: 0.5345501955671447
Delta: 3.75538838323396e-05 	  Loss: 1.5427594027860736 	 Accuracy: 0.5358539765319427
Delta: 0.002421504146552381 	  Loss: 1.5421375311921826 	 Accuracy: 0.5345501955671447
Delta: 0.0013572596768133918 	  Loss: 1.5422595736845417 	 Accuracy: 0.5371577574967406
Delta: 0.0006132183489364527 	  Loss: 1.5427770641818133 	 Accuracy: 0.5332464146023468
Delta: 6.25474340470217e-05 	  Loss: 1.5424421295835948 	 Accuracy: 0.5358539765319427
Delta: 0.0020251012887323675 	  Loss: 1.5425779266940742 	 Accuracy: 0.5358539765319427
Delta: 5.7040508940545526e-05 	  Loss: 1.5424993292959979 	 Accuracy: 0.5371577574967406
Delta: 0.0016185033636231761 	  Loss: 1.5422167224151533 	 Accuracy: 0.5345501955671447
Delta: 0.001725625042909693 	  Loss: 1.5421389142951634 	 Accuracy: 0.5267275097783573
Delta: 0.0010010793128993308 	  Loss: 1.5425129672310476 	 Accuracy: 0.5358539765319427
Delta: 0.00013147763409175321 	  Loss: 1.5423712555863747 	 Accuracy: 0.5345501955671447
Delta: 0.0013199130012499461 	  Loss: 1.5427555858827469 	 Accuracy: 0.5345501955671447
Delta: 4.912617033105009e-05 	  Loss: 1.542464628325491 	 Accuracy: 0.5358539765319427
Delta: 0.0005688969572585199 	  Loss: 1.5426634495758693 	 Accuracy: 0.5384615384615384
Delta: 0.0015358889978516921 	  Loss: 1.5428948501566175 	 Accuracy: 0.5345501955671447
Delta: 6.291512215783748e-05 	  Loss: 1.5427654014963452 	 Accuracy: 0.5371577574967406
Delta: 0.0005526937377700463 	  Loss: 1.542718303877999 	 Accuracy: 0.5358539765319427
Delta: 0.003788651782346469 	  Loss: 1.5422815874592914 	 Accuracy: 0.5358539765319427
Delta: 0.004563382149215395 	  Loss: 1.5420236743255682 	 Accuracy: 0.5358539765319427
Delta: 0.002153899952120745 	  Loss: 1.5412808811918994 	 Accuracy: 0.5332464146023468
Delta: 0.0023727143716204225 	  Loss: 1.541560971308026 	 Accuracy: 0.5345501955671447
Delta: 0.0033230345020494843 	  Loss: 1.5416746842624924 	 Accuracy: 0.5345501955671447
Delta: 0.0028658895125076474 	  Loss: 1.5422566516660678 	 Accuracy: 0.5358539765319427
Delta: 0.006172767853724413 	  Loss: 1.5424594727470522 	 Accuracy: 0.5358539765319427
Delta: 0.0033246929360317783 	  Loss: 1.5419684496472543 	 Accuracy: 0.5345501955671447
Delta: 0.004589359023274954 	  Loss: 1.5425972834073447 	 Accuracy: 0.5332464146023468
Delta: 0.0015894763806653545 	  Loss: 1.5433731006719582 	 Accuracy: 0.5332464146023468
Delta: 0.0005556684852994776 	  Loss: 1.5430688614381847 	 Accuracy: 0.5332464146023468
Delta: 6.595736687941348e-05 	  Loss: 1.5427454378984045 	 Accuracy: 0.5332464146023468
Delta: 8.386556599080595e-05 	  Loss: 1.543172694349698 	 Accuracy: 0.5332464146023468
Delta: 0.00012069876828466881 	  Loss: 1.5425936443577903 	 Accuracy: 0.5319426336375489
Delta: 0.002538554421889049 	  Loss: 1.5431724087202936 	 Accuracy: 0.5319426336375489
Delta: 0.00308127092624977 	  Loss: 1.543393162614902 	 Accuracy: 0.5345501955671447
Delta: 0.0033674174658157785 	  Loss: 1.5434362934490573 	 Accuracy: 0.5332464146023468
Delta: 8.627217626501222e-05 	  Loss: 1.5434161236234516 	 Accuracy: 0.5332464146023468
Delta: 0.002125322296267525 	  Loss: 1.5430831860853766 	 Accuracy: 0.5345501955671447
Delta: 0.003636097962431693 	  Loss: 1.542993690204003 	 Accuracy: 0.5332464146023468
Delta: 0.0005906579646276283 	  Loss: 1.5431258066309712 	 Accuracy: 0.5332464146023468
Delta: 1.430667685835161e-05 	  Loss: 1.5430966617760067 	 Accuracy: 0.530638852672751
Delta: 0.0032704069281307316 	  Loss: 1.5435774640537725 	 Accuracy: 0.5319426336375489
Delta: 0.0025072581425177706 	  Loss: 1.5429529059359481 	 Accuracy: 0.5280312907431551
Delta: 0.0014385930747391569 	  Loss: 1.5428329033835708 	 Accuracy: 0.5332464146023468
Delta: 0.002472086674802056 	  Loss: 1.543192389331679 	 Accuracy: 0.5280312907431551
Delta: 0.02093418069874369 	  Loss: 2.1538294452613824 	 Accuracy: 0.20078226857887874
Delta: 0.01883456426626381 	  Loss: 2.0634425169763126 	 Accuracy: 0.3728813559322034
Delta: 0.017693615925496356 	  Loss: 1.9025835362219747 	 Accuracy: 0.45371577574967403
Delta: 0.016315530038388593 	  Loss: 1.7250234963000775 	 Accuracy: 0.4367666232073012
Delta: 0.013460160853466095 	  Loss: 1.615799763639401 	 Accuracy: 0.4106910039113429
Delta: 0.010531156338952534 	  Loss: 1.5761710212926214 	 Accuracy: 0.40808344198174706
Delta: 0.007932120240512153 	  Loss: 1.5653435114252103 	 Accuracy: 0.4028683181225554
Delta: 0.00757455827788455 	  Loss: 1.5612824497392757 	 Accuracy: 0.41590612777053454

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006924351438044515 	  Loss: 1.5590592490516766 	 Accuracy: 0.41199478487614083
Delta: 0.006545312311388638 	  Loss: 1.5571644811607208 	 Accuracy: 0.41199478487614083
Delta: 0.005479839513764946 	  Loss: 1.5562968781870303 	 Accuracy: 0.4041720990873533
Delta: 0.004701631848758187 	  Loss: 1.5558939973944885 	 Accuracy: 0.41460234680573665
Delta: 0.0030006832405397982 	  Loss: 1.55563583266401 	 Accuracy: 0.41460234680573665
Delta: 0.0026639850725634507 	  Loss: 1.5556466896526686 	 Accuracy: 0.409387222946545
Delta: 0.003031705719297451 	  Loss: 1.5557216066157562 	 Accuracy: 0.40808344198174706
Delta: 0.002093776262278974 	  Loss: 1.5557096575403493 	 Accuracy: 0.4106910039113429
Delta: 2.5387156553390537e-05 	  Loss: 1.5556566762752677 	 Accuracy: 0.41199478487614083
Delta: 3.849094091832781e-05 	  Loss: 1.555602665758867 	 Accuracy: 0.409387222946545
Delta: 7.470515934621948e-05 	  Loss: 1.5557310448477688 	 Accuracy: 0.41199478487614083
Delta: 0.0005777734135482272 	  Loss: 1.5555636311317056 	 Accuracy: 0.41199478487614083
Delta: 0.0017412432644428228 	  Loss: 1.5556071422212399 	 Accuracy: 0.41199478487614083
Delta: 0.0011026963777249746 	  Loss: 1.5557007155724811 	 Accuracy: 0.41199478487614083
Delta: 0.0005147375601027425 	  Loss: 1.555671061163828 	 Accuracy: 0.4106910039113429
Delta: 2.935479335506652e-05 	  Loss: 1.55566289439871 	 Accuracy: 0.41199478487614083
Delta: 3.643684699829588e-05 	  Loss: 1.5555526066453456 	 Accuracy: 0.4106910039113429
Delta: 0.0011253637264649556 	  Loss: 1.5555000309077642 	 Accuracy: 0.4106910039113429
Delta: 0.003132682482996215 	  Loss: 1.5554597101209118 	 Accuracy: 0.4106910039113429
Delta: 0.0022442431347890306 	  Loss: 1.5556708863991406 	 Accuracy: 0.40808344198174706
Delta: 0.0016473907315889783 	  Loss: 1.55601811478668 	 Accuracy: 0.4106910039113429
Delta: 0.002679989244526185 	  Loss: 1.5559956362897258 	 Accuracy: 0.4106910039113429
Delta: 0.0034260747873752083 	  Loss: 1.5560600775422315 	 Accuracy: 0.4106910039113429
Delta: 0.00263669922670087 	  Loss: 1.5559491278181627 	 Accuracy: 0.4106910039113429
Delta: 0.0012263113616000853 	  Loss: 1.555810370072644 	 Accuracy: 0.41199478487614083
Delta: 0.001654749793695449 	  Loss: 1.555845728138752 	 Accuracy: 0.4132985658409387
Delta: 0.0005747960117497808 	  Loss: 1.5560622662357664 	 Accuracy: 0.4106910039113429
Delta: 0.0001015041327563308 	  Loss: 1.5561046545748614 	 Accuracy: 0.4106910039113429
Delta: 0.002557890524834155 	  Loss: 1.5564050420169764 	 Accuracy: 0.4106910039113429
Delta: 0.001507902844868547 	  Loss: 1.5560028378388657 	 Accuracy: 0.4106910039113429
Delta: 0.0018756779437998224 	  Loss: 1.556250716569953 	 Accuracy: 0.4106910039113429
Delta: 0.0014121875833395985 	  Loss: 1.5562204111906346 	 Accuracy: 0.41199478487614083
Delta: 0.004176664813725513 	  Loss: 1.5552770164074006 	 Accuracy: 0.4067796610169492
Delta: 0.003490596165727033 	  Loss: 1.5546261080036206 	 Accuracy: 0.4106910039113429
Delta: 0.0033216684185674817 	  Loss: 1.5546857743417353 	 Accuracy: 0.41199478487614083
Delta: 0.0018999560659455081 	  Loss: 1.5546725843113807 	 Accuracy: 0.41199478487614083
Delta: 4.336698222632531e-05 	  Loss: 1.5546240274428498 	 Accuracy: 0.41199478487614083
Delta: 0.0027897543183568467 	  Loss: 1.5550091187640778 	 Accuracy: 0.4106910039113429
Delta: 0.0028699231899943015 	  Loss: 1.55512252509055 	 Accuracy: 0.4106910039113429
Delta: 0.0029251984060541894 	  Loss: 1.5550187101816164 	 Accuracy: 0.4106910039113429
Delta: 0.001618303645911348 	  Loss: 1.5551742379601636 	 Accuracy: 0.409387222946545
Delta: 3.7218284174247835e-05 	  Loss: 1.5551090286306675 	 Accuracy: 0.41199478487614083
Delta: 0.0031107440185235424 	  Loss: 1.5548922830445302 	 Accuracy: 0.4106910039113429
Delta: 0.0034507144099824505 	  Loss: 1.5550415034729488 	 Accuracy: 0.409387222946545
Delta: 0.002957642058259258 	  Loss: 1.555154300584642 	 Accuracy: 0.4106910039113429
Delta: 0.0026578393065761316 	  Loss: 1.5550854937610081 	 Accuracy: 0.4106910039113429
Delta: 0.00261543498173266 	  Loss: 1.5550487296452642 	 Accuracy: 0.41199478487614083
Delta: 4.459849615182944e-05 	  Loss: 1.5552042482332356 	 Accuracy: 0.409387222946545
Delta: 0.004252207573884694 	  Loss: 1.5563529355810681 	 Accuracy: 0.4106910039113429
Delta: 0.0005814915237721457 	  Loss: 1.5563052277689284 	 Accuracy: 0.41199478487614083
Delta: 0.0035461218107439873 	  Loss: 1.555773600018843 	 Accuracy: 0.41199478487614083
Delta: 0.002279222790671421 	  Loss: 1.5564471104227215 	 Accuracy: 0.4106910039113429
Delta: 0.0028596597522014384 	  Loss: 1.5556402465007728 	 Accuracy: 0.4132985658409387
Delta: 0.001302534659369585 	  Loss: 1.5557418867381116 	 Accuracy: 0.41460234680573665
Delta: 0.001094831477390178 	  Loss: 1.5554463422023503 	 Accuracy: 0.41199478487614083
Delta: 0.0014932146906862197 	  Loss: 1.5556451201119437 	 Accuracy: 0.4106910039113429
Delta: 0.002037770942747702 	  Loss: 1.5551400686484138 	 Accuracy: 0.4106910039113429
Delta: 0.0017537838419340532 	  Loss: 1.555374637222392 	 Accuracy: 0.41199478487614083
Delta: 0.0006105688027348089 	  Loss: 1.5551362381896991 	 Accuracy: 0.4106910039113429
Delta: 0.0014795744699870406 	  Loss: 1.5549824414655748 	 Accuracy: 0.4106910039113429
Delta: 5.596486938188131e-05 	  Loss: 1.5549304559223316 	 Accuracy: 0.409387222946545
Delta: 4.2056736044774235e-05 	  Loss: 1.5550115455433606 	 Accuracy: 0.409387222946545
Delta: 0.0014964925407988698 	  Loss: 1.5551759079004426 	 Accuracy: 0.4041720990873533
Delta: 0.0023593710524626925 	  Loss: 1.5549987588529852 	 Accuracy: 0.409387222946545
Delta: 0.0005672745973914144 	  Loss: 1.5549428907177243 	 Accuracy: 0.4106910039113429
Delta: 4.489343715209622e-05 	  Loss: 1.5548258188470796 	 Accuracy: 0.40808344198174706
Delta: 0.0019901818237105743 	  Loss: 1.555124640210236 	 Accuracy: 0.409387222946545
Delta: 0.000567564620329864 	  Loss: 1.5549904577851872 	 Accuracy: 0.40808344198174706
Delta: 2.309301271540579e-05 	  Loss: 1.5549916407850386 	 Accuracy: 0.409387222946545
Delta: 0.0023917518837475176 	  Loss: 1.5549881818411584 	 Accuracy: 0.4132985658409387
Delta: 0.0026833308396226043 	  Loss: 1.5550912207711685 	 Accuracy: 0.4067796610169492
Delta: 0.004586883774813356 	  Loss: 1.5564588544878777 	 Accuracy: 0.409387222946545
Delta: 0.003465261258379204 	  Loss: 1.555223466661992 	 Accuracy: 0.409387222946545
Delta: 0.0030001860589417943 	  Loss: 1.5547385410797476 	 Accuracy: 0.409387222946545
Delta: 0.0019837152234100596 	  Loss: 1.5549955838416472 	 Accuracy: 0.409387222946545
Delta: 1.6840858800264534e-06 	  Loss: 1.5549940110591751 	 Accuracy: 0.4106910039113429
Delta: 3.8466891965150985e-05 	  Loss: 1.5551051023176974 	 Accuracy: 0.4041720990873533
Delta: 4.0581402862982045e-05 	  Loss: 1.5549922437464478 	 Accuracy: 0.40808344198174706
Delta: 0.0023799292021774473 	  Loss: 1.5551884283447963 	 Accuracy: 0.409387222946545
Delta: 0.0021870720639310818 	  Loss: 1.5552126687118075 	 Accuracy: 0.409387222946545
Delta: 3.1557993483300716e-05 	  Loss: 1.5552919833341667 	 Accuracy: 0.38722294654498046
Delta: 0.0009577895827527364 	  Loss: 1.555626645989065 	 Accuracy: 0.40808344198174706
Delta: 0.0038699344818639006 	  Loss: 1.555971314625992 	 Accuracy: 0.40808344198174706
Delta: 1.0529418938087595e-05 	  Loss: 1.5559563538892451 	 Accuracy: 0.4015645371577575
Delta: 0.0005829671769014614 	  Loss: 1.5562904983170758 	 Accuracy: 0.40808344198174706
Delta: 9.469441143274475e-05 	  Loss: 1.5559560938924266 	 Accuracy: 0.40808344198174706
Delta: 0.0037447652706212686 	  Loss: 1.5556349352323484 	 Accuracy: 0.40808344198174706
Delta: 2.839608139974706e-05 	  Loss: 1.5555625244491145 	 Accuracy: 0.40808344198174706
Delta: 0.002518727004522105 	  Loss: 1.555855151249609 	 Accuracy: 0.40808344198174706
Delta: 0.0032364116597810317 	  Loss: 1.5559211809322941 	 Accuracy: 0.40808344198174706
Delta: 0.0024493279985148986 	  Loss: 1.5564275364737634 	 Accuracy: 0.4067796610169492
Delta: 0.004720715430161293 	  Loss: 1.5575153145707596 	 Accuracy: 0.4041720990873533
Delta: 0.02097538148168234 	  Loss: 2.1537368630691187 	 Accuracy: 0.21642764015645372
Delta: 0.018824201016859457 	  Loss: 2.066435182473449 	 Accuracy: 0.3285528031290743
Delta: 0.01663451431073854 	  Loss: 1.9276488225912205 	 Accuracy: 0.38461538461538464
Delta: 0.015616353325317923 	  Loss: 1.7941465480521122 	 Accuracy: 0.4132985658409387
Delta: 0.014512661245742351 	  Loss: 1.713151755405256 	 Accuracy: 0.41851368970013036
Delta: 0.013127271300985562 	  Loss: 1.672647628782228 	 Accuracy: 0.423728813559322
Delta: 0.01101519193137662 	  Loss: 1.6504206511967145 	 Accuracy: 0.4198174706649283
Delta: 0.009297107396421986 	  Loss: 1.6388614704600308 	 Accuracy: 0.4211212516297262

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007673672142392224 	  Loss: 1.634202350714442 	 Accuracy: 0.4198174706649283
Delta: 0.00663173802898905 	  Loss: 1.631425694048772 	 Accuracy: 0.42242503259452413
Delta: 0.005146927132148855 	  Loss: 1.6313801285009077 	 Accuracy: 0.423728813559322
Delta: 0.004660162012701807 	  Loss: 1.6309756494480794 	 Accuracy: 0.4198174706649283
Delta: 0.0030798333150478373 	  Loss: 1.630965686070335 	 Accuracy: 0.4211212516297262
Delta: 0.00216729858667615 	  Loss: 1.6304800195475355 	 Accuracy: 0.4211212516297262
Delta: 0.0005409951089477697 	  Loss: 1.6308530359406768 	 Accuracy: 0.4211212516297262
Delta: 0.0009182197108206084 	  Loss: 1.6303478274343959 	 Accuracy: 0.4211212516297262
Delta: 0.002320120616638212 	  Loss: 1.6300394521054349 	 Accuracy: 0.4198174706649283
Delta: 0.0026264914501787032 	  Loss: 1.6297966683989913 	 Accuracy: 0.4211212516297262
Delta: 0.0046010391790477535 	  Loss: 1.628982255548632 	 Accuracy: 0.4198174706649283
Delta: 0.00344747209042839 	  Loss: 1.628729579384302 	 Accuracy: 0.4211212516297262
Delta: 0.0015226457538508736 	  Loss: 1.6285245160812742 	 Accuracy: 0.42242503259452413
Delta: 0.0011487908779683356 	  Loss: 1.6286337297605202 	 Accuracy: 0.4198174706649283
Delta: 0.002294162751008372 	  Loss: 1.6291861193097867 	 Accuracy: 0.4198174706649283
Delta: 0.0022657903042965248 	  Loss: 1.6286545980146907 	 Accuracy: 0.4198174706649283
Delta: 0.00115884376047029 	  Loss: 1.6285122524656577 	 Accuracy: 0.4198174706649283
Delta: 0.0020865587160951706 	  Loss: 1.629175530754103 	 Accuracy: 0.4211212516297262
Delta: 3.302563562798875e-05 	  Loss: 1.6290841119140582 	 Accuracy: 0.4211212516297262
Delta: 0.0018076464860179396 	  Loss: 1.6290415603051036 	 Accuracy: 0.4211212516297262
Delta: 0.0026229127056401425 	  Loss: 1.628627743741325 	 Accuracy: 0.4211212516297262
Delta: 0.0010700340230214013 	  Loss: 1.6285914826883825 	 Accuracy: 0.4211212516297262
Delta: 0.0012854457984449136 	  Loss: 1.6284981068331446 	 Accuracy: 0.4198174706649283
Delta: 0.0017890094137918272 	  Loss: 1.6289782894234488 	 Accuracy: 0.4211212516297262
Delta: 0.002002453903998151 	  Loss: 1.6287192953225782 	 Accuracy: 0.4198174706649283
Delta: 0.002894436154177456 	  Loss: 1.628683548726639 	 Accuracy: 0.41851368970013036
Delta: 0.0028852864338525064 	  Loss: 1.6288377928753135 	 Accuracy: 0.41851368970013036
Delta: 0.002052753759707022 	  Loss: 1.6287724404890613 	 Accuracy: 0.4198174706649283
Delta: 0.0012338168031331114 	  Loss: 1.628574725667667 	 Accuracy: 0.41851368970013036
Delta: 0.0030744150101064565 	  Loss: 1.6283422374543592 	 Accuracy: 0.4198174706649283
Delta: 0.004950143622960104 	  Loss: 1.6291869234042964 	 Accuracy: 0.4198174706649283
Delta: 0.0027309331086653914 	  Loss: 1.6291995776411519 	 Accuracy: 0.4198174706649283
Delta: 0.0019182632484936353 	  Loss: 1.6290707284428558 	 Accuracy: 0.4172099087353325
Delta: 0.0033094312158236908 	  Loss: 1.628668862320148 	 Accuracy: 0.4198174706649283
Delta: 0.0039863570278015495 	  Loss: 1.628717052417505 	 Accuracy: 0.41851368970013036
Delta: 0.0011063669681502998 	  Loss: 1.6291378992402914 	 Accuracy: 0.41851368970013036
Delta: 0.0022811139661819985 	  Loss: 1.6286456829178595 	 Accuracy: 0.41851368970013036
Delta: 0.0024489681668537814 	  Loss: 1.628902023603198 	 Accuracy: 0.41851368970013036
Delta: 0.0012619778608364287 	  Loss: 1.6288913585561033 	 Accuracy: 0.41851368970013036
Delta: 5.84318430082927e-05 	  Loss: 1.6289163202426467 	 Accuracy: 0.4172099087353325
Delta: 0.004780102808066702 	  Loss: 1.631373218257592 	 Accuracy: 0.41851368970013036
Delta: 0.0017185337007790344 	  Loss: 1.6304443603105812 	 Accuracy: 0.4172099087353325
Delta: 0.003544400846507225 	  Loss: 1.6311244126408702 	 Accuracy: 0.41851368970013036
Delta: 6.845259489968201e-05 	  Loss: 1.6308135918071693 	 Accuracy: 0.4198174706649283
Delta: 6.749296016867723e-05 	  Loss: 1.6309057698032126 	 Accuracy: 0.4198174706649283
Delta: 5.379840540635164e-05 	  Loss: 1.6306828462142038 	 Accuracy: 0.423728813559322
Delta: 0.004258555247209583 	  Loss: 1.6305658553060889 	 Accuracy: 0.4198174706649283
Delta: 0.0035510656899179413 	  Loss: 1.6302771963675777 	 Accuracy: 0.4198174706649283
Delta: 0.0033398236227848294 	  Loss: 1.6305068775807074 	 Accuracy: 0.4211212516297262
Delta: 0.0005414422367893313 	  Loss: 1.6305926282955667 	 Accuracy: 0.4198174706649283
Delta: 0.001064687548938701 	  Loss: 1.6305859644931728 	 Accuracy: 0.4211212516297262
Delta: 0.0007858944214321556 	  Loss: 1.6304683477565436 	 Accuracy: 0.4198174706649283
Delta: 0.002628071246868621 	  Loss: 1.63065599320423 	 Accuracy: 0.4198174706649283
Delta: 0.0021453527806219804 	  Loss: 1.630435854484789 	 Accuracy: 0.4198174706649283
Delta: 0.001487229876848853 	  Loss: 1.6302217965547825 	 Accuracy: 0.4198174706649283
Delta: 8.011360189723032e-05 	  Loss: 1.6306146701168425 	 Accuracy: 0.4198174706649283
Delta: 0.0005571805739007885 	  Loss: 1.6302999407669365 	 Accuracy: 0.4198174706649283
Delta: 7.519418384702414e-05 	  Loss: 1.6305149640415086 	 Accuracy: 0.4198174706649283
Delta: 0.0016430960931549136 	  Loss: 1.6304045761695234 	 Accuracy: 0.4198174706649283
Delta: 0.0005906819855657958 	  Loss: 1.6298840634516059 	 Accuracy: 0.4198174706649283
Delta: 0.0005717136956250508 	  Loss: 1.6303254606000666 	 Accuracy: 0.4198174706649283
Delta: 7.05564564205367e-05 	  Loss: 1.6306120645869284 	 Accuracy: 0.4172099087353325
Delta: 0.0014263614448656273 	  Loss: 1.6306723257956235 	 Accuracy: 0.4211212516297262
Delta: 0.003963491563493554 	  Loss: 1.631222781264795 	 Accuracy: 0.42242503259452413
Delta: 0.004073187757910696 	  Loss: 1.6311563676124132 	 Accuracy: 0.3833116036505867
Delta: 0.003982813110872889 	  Loss: 1.6313617342658886 	 Accuracy: 0.41851368970013036
Delta: 0.004875248648018135 	  Loss: 1.6312367912968755 	 Accuracy: 0.41851368970013036
Delta: 0.0010749988844729074 	  Loss: 1.6311602375494894 	 Accuracy: 0.4198174706649283
Delta: 0.0024815983968131234 	  Loss: 1.630835706500172 	 Accuracy: 0.39765319426336376
Delta: 0.0011754757019417955 	  Loss: 1.63108621030031 	 Accuracy: 0.4211212516297262
Delta: 0.004671293040279785 	  Loss: 1.6290522091992035 	 Accuracy: 0.4198174706649283
Delta: 0.001600839387016542 	  Loss: 1.629065900129495 	 Accuracy: 0.41460234680573665
Delta: 0.0035981721514200004 	  Loss: 1.629296087272755 	 Accuracy: 0.42242503259452413
Delta: 0.0029040847305740534 	  Loss: 1.6303184656603849 	 Accuracy: 0.4198174706649283
Delta: 0.002232382263480507 	  Loss: 1.6309423634845435 	 Accuracy: 0.41851368970013036
Delta: 0.0005788113180263563 	  Loss: 1.630547635689168 	 Accuracy: 0.4172099087353325
Delta: 0.0013230064382350323 	  Loss: 1.6308071116399496 	 Accuracy: 0.4198174706649283
Delta: 0.002960486078141075 	  Loss: 1.6307090519003011 	 Accuracy: 0.4198174706649283
Delta: 0.002288659325842597 	  Loss: 1.6312854269144177 	 Accuracy: 0.42242503259452413
Delta: 0.002828533785355562 	  Loss: 1.6313407931257613 	 Accuracy: 0.4211212516297262
Delta: 0.00360101732806632 	  Loss: 1.6316239772605754 	 Accuracy: 0.41590612777053454
Delta: 0.004360702762425472 	  Loss: 1.6320866389697741 	 Accuracy: 0.4198174706649283
Delta: 0.001543991633021829 	  Loss: 1.631626279444906 	 Accuracy: 0.41851368970013036
Delta: 0.0005412040124005788 	  Loss: 1.6318476059283908 	 Accuracy: 0.4211212516297262
Delta: 0.002661309163230371 	  Loss: 1.6318884878502016 	 Accuracy: 0.4172099087353325
Delta: 1.3242537715652007e-05 	  Loss: 1.631831255994818 	 Accuracy: 0.41851368970013036
Delta: 0.0034380467402852113 	  Loss: 1.6320398738293522 	 Accuracy: 0.41590612777053454
Delta: 0.0034411633501856493 	  Loss: 1.6320047595851244 	 Accuracy: 0.41851368970013036
Delta: 0.0008539744673539711 	  Loss: 1.6321333119064443 	 Accuracy: 0.41851368970013036
Delta: 0.003546830520328433 	  Loss: 1.6310436718986008 	 Accuracy: 0.4198174706649283
Delta: 0.0030737852795910707 	  Loss: 1.6307810195343149 	 Accuracy: 0.4198174706649283
Delta: 0.0038930108763236765 	  Loss: 1.6311812216363861 	 Accuracy: 0.4211212516297262
Delta: 0.021111192797494054 	  Loss: 2.152802017592313 	 Accuracy: 0.20860495436766624
Delta: 0.01903257574955357 	  Loss: 2.0509384754841298 	 Accuracy: 0.2985658409387223
Delta: 0.017498928464674577 	  Loss: 1.8606253013168907 	 Accuracy: 0.3011734028683181
Delta: 0.015167555797063635 	  Loss: 1.7069675551501096 	 Accuracy: 0.3272490221642764
Delta: 0.012500927814633751 	  Loss: 1.647172872640151 	 Accuracy: 0.3272490221642764
Delta: 0.01078513923955404 	  Loss: 1.6243262914851404 	 Accuracy: 0.32985658409387225
Delta: 0.008574937897304822 	  Loss: 1.6158086510569076 	 Accuracy: 0.3324641460234681
Delta: 0.00755659575721341 	  Loss: 1.612244956006607 	 Accuracy: 0.3428943937418514

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006859734815469515 	  Loss: 1.6102087859964007 	 Accuracy: 0.3455019556714472
Delta: 0.005215848626711011 	  Loss: 1.6095218907593718 	 Accuracy: 0.3494132985658409
Delta: 0.005334259563517473 	  Loss: 1.6092822406147609 	 Accuracy: 0.3494132985658409
Delta: 0.002850162774031534 	  Loss: 1.6092094367347651 	 Accuracy: 0.34810951760104303
Delta: 0.0036295477750571702 	  Loss: 1.6092192977725255 	 Accuracy: 0.35071707953063885
Delta: 0.0005415858549776069 	  Loss: 1.6091652016228082 	 Accuracy: 0.3520208604954368
Delta: 0.002964052201276178 	  Loss: 1.6092546344713752 	 Accuracy: 0.3520208604954368
Delta: 0.002794666015102586 	  Loss: 1.6092409548854392 	 Accuracy: 0.3494132985658409
Delta: 0.0012187318816282852 	  Loss: 1.6091741405204587 	 Accuracy: 0.35071707953063885
Delta: 0.0012640760258858512 	  Loss: 1.6092552076779123 	 Accuracy: 0.35071707953063885
Delta: 0.0009591152097868157 	  Loss: 1.609377102323882 	 Accuracy: 0.3494132985658409
Delta: 0.002633028530553982 	  Loss: 1.6093854410040334 	 Accuracy: 0.3520208604954368
Delta: 0.0005279898289701065 	  Loss: 1.609402590389036 	 Accuracy: 0.35071707953063885
Delta: 1.7898412062124436e-05 	  Loss: 1.6094024475938427 	 Accuracy: 0.3494132985658409
Delta: 0.0023147022675560377 	  Loss: 1.609288465122484 	 Accuracy: 0.34810951760104303
Delta: 0.003264332545345998 	  Loss: 1.6094248185250515 	 Accuracy: 0.35071707953063885
Delta: 0.0012230593477769957 	  Loss: 1.609488863048707 	 Accuracy: 0.3494132985658409
Delta: 0.0005619223538353176 	  Loss: 1.6096446342235906 	 Accuracy: 0.34810951760104303
Delta: 0.0015113674922182933 	  Loss: 1.6092749480637396 	 Accuracy: 0.34810951760104303
Delta: 0.0016322737611384208 	  Loss: 1.609471349930124 	 Accuracy: 0.3494132985658409
Delta: 0.0026461100257609243 	  Loss: 1.6093662195887926 	 Accuracy: 0.35071707953063885
Delta: 0.0014875029764426272 	  Loss: 1.6092645612843102 	 Accuracy: 0.3455019556714472
Delta: 0.001983146322628622 	  Loss: 1.6094142071469248 	 Accuracy: 0.35071707953063885
Delta: 3.4692668795923785e-05 	  Loss: 1.6094040274980816 	 Accuracy: 0.3494132985658409
Delta: 0.0015381259013392526 	  Loss: 1.6092337884808625 	 Accuracy: 0.3520208604954368
Delta: 5.98148460864762e-05 	  Loss: 1.6092000359593879 	 Accuracy: 0.3520208604954368
Delta: 1.1062545216916907e-05 	  Loss: 1.6091822762185086 	 Accuracy: 0.3494132985658409
Delta: 0.001704715947852299 	  Loss: 1.6092807575815828 	 Accuracy: 0.3468057366362451
Delta: 0.0022723529143976228 	  Loss: 1.6093988744968835 	 Accuracy: 0.3520208604954368
Delta: 0.003636450102671264 	  Loss: 1.6099439438990346 	 Accuracy: 0.35071707953063885
Delta: 0.0034881936687327125 	  Loss: 1.6104458417491179 	 Accuracy: 0.3520208604954368
Delta: 0.00262058037495081 	  Loss: 1.6100888508512845 	 Accuracy: 0.3494132985658409
Delta: 0.0020477223341244448 	  Loss: 1.6100274085656663 	 Accuracy: 0.3520208604954368
Delta: 0.004140906976656027 	  Loss: 1.610616772076851 	 Accuracy: 0.3520208604954368
Delta: 0.003013552853499622 	  Loss: 1.6106483275720103 	 Accuracy: 0.3520208604954368
Delta: 0.0017237486631359914 	  Loss: 1.6113507039352393 	 Accuracy: 0.35071707953063885
Delta: 0.0011212437679902877 	  Loss: 1.6111153140873937 	 Accuracy: 0.34419817470664926
Delta: 0.00265548434377516 	  Loss: 1.610561416458701 	 Accuracy: 0.3494132985658409
Delta: 0.003890674790313908 	  Loss: 1.6099731503941714 	 Accuracy: 0.3494132985658409
Delta: 0.0012839506418843313 	  Loss: 1.6099913156774766 	 Accuracy: 0.3494132985658409
Delta: 0.002745239413432392 	  Loss: 1.6102786492562882 	 Accuracy: 0.3455019556714472
Delta: 0.0018586777956327413 	  Loss: 1.6103238714693764 	 Accuracy: 0.3494132985658409
Delta: 0.002532582492241484 	  Loss: 1.6099681399875063 	 Accuracy: 0.3494132985658409
Delta: 0.002602370049422567 	  Loss: 1.6101115986399432 	 Accuracy: 0.3494132985658409
Delta: 0.005099537591557353 	  Loss: 1.6104390466559564 	 Accuracy: 0.3494132985658409
Delta: 0.004178864733564867 	  Loss: 1.610927087734899 	 Accuracy: 0.3468057366362451
Delta: 0.0028402755060921558 	  Loss: 1.6105495365963796 	 Accuracy: 0.34810951760104303
Delta: 0.004136176859976701 	  Loss: 1.610195002560041 	 Accuracy: 0.3468057366362451
Delta: 0.0024275454427019065 	  Loss: 1.6099796757242495 	 Accuracy: 0.3389830508474576
Delta: 0.0005529663383788811 	  Loss: 1.6099615200154067 	 Accuracy: 0.34810951760104303
Delta: 0.00352572607920078 	  Loss: 1.6093862670115127 	 Accuracy: 0.34810951760104303
Delta: 0.0019111386410132864 	  Loss: 1.609713243386075 	 Accuracy: 0.34419817470664926
Delta: 0.0034919603551534124 	  Loss: 1.6098761777629493 	 Accuracy: 0.3468057366362451
Delta: 0.003563831778034327 	  Loss: 1.6094006109117531 	 Accuracy: 0.34810951760104303
Delta: 0.004098843586655758 	  Loss: 1.6097349331007416 	 Accuracy: 0.3468057366362451
Delta: 0.0005124838995240123 	  Loss: 1.609759544173365 	 Accuracy: 0.3455019556714472
Delta: 1.7914535771265337e-05 	  Loss: 1.6097244404116395 	 Accuracy: 0.3455019556714472
Delta: 5.255906180122839e-09 	  Loss: 1.6097244326441267 	 Accuracy: 0.34419817470664926
converged at iter  65
Delta: 0.020973108951820706 	  Loss: 2.154150904677695 	 Accuracy: 0.19295958279009126
Delta: 0.018726406781055034 	  Loss: 2.0613871408776374 	 Accuracy: 0.4276401564537158
Delta: 0.018279684551640713 	  Loss: 1.8913557874160616 	 Accuracy: 0.5658409387222947
Delta: 0.016528555748099628 	  Loss: 1.7083734418525953 	 Accuracy: 0.5867014341590613
Delta: 0.013775264501938871 	  Loss: 1.617813391965964 	 Accuracy: 0.5541069100391134
Delta: 0.011449050236765955 	  Loss: 1.5885057876067177 	 Accuracy: 0.5345501955671447
Delta: 0.00980587894611703 	  Loss: 1.5752491389654537 	 Accuracy: 0.5319426336375489

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0075569845149590364 	  Loss: 1.569382702149595 	 Accuracy: 0.5280312907431551
Delta: 0.0069170243891579514 	  Loss: 1.5680569977655296 	 Accuracy: 0.529335071707953
Delta: 0.005534761530810229 	  Loss: 1.5674523016813615 	 Accuracy: 0.5267275097783573
Delta: 0.0037597699162347023 	  Loss: 1.5670919281780353 	 Accuracy: 0.5280312907431551
Delta: 0.0026049556098855053 	  Loss: 1.5669258089076026 	 Accuracy: 0.5280312907431551
Delta: 0.0031609476049827903 	  Loss: 1.5676733239069995 	 Accuracy: 0.5254237288135594
Delta: 0.0011107437915995847 	  Loss: 1.5673013273491152 	 Accuracy: 0.5280312907431551
Delta: 0.002713546862682473 	  Loss: 1.5674008239919877 	 Accuracy: 0.5280312907431551
Delta: 0.0022426772996573256 	  Loss: 1.567145486397788 	 Accuracy: 0.530638852672751
Delta: 0.000527780545491959 	  Loss: 1.5670557932083846 	 Accuracy: 0.5267275097783573
Delta: 8.21703633693269e-05 	  Loss: 1.5671112336338244 	 Accuracy: 0.5280312907431551
Delta: 0.0011173751472870576 	  Loss: 1.5672023485441082 	 Accuracy: 0.5280312907431551
Delta: 0.002041677679013769 	  Loss: 1.5671542826405809 	 Accuracy: 0.5280312907431551
Delta: 0.002331389654016492 	  Loss: 1.5672357603609541 	 Accuracy: 0.5267275097783573
Delta: 0.0014638758169263064 	  Loss: 1.5672631411331062 	 Accuracy: 0.5280312907431551
Delta: 0.004692033524212452 	  Loss: 1.567504752807639 	 Accuracy: 0.5280312907431551
Delta: 4.9384790116493025e-05 	  Loss: 1.56759008327995 	 Accuracy: 0.5280312907431551
Delta: 0.0005319020738738444 	  Loss: 1.5673542581241495 	 Accuracy: 0.529335071707953
Delta: 4.0472529097761854e-05 	  Loss: 1.5674880809404446 	 Accuracy: 0.5280312907431551
Delta: 4.339151192193326e-06 	  Loss: 1.5674825742196257 	 Accuracy: 0.5280312907431551
Delta: 0.001136318775053939 	  Loss: 1.5675150683227619 	 Accuracy: 0.5280312907431551
Delta: 0.0014673732799583641 	  Loss: 1.5674024637839294 	 Accuracy: 0.5280312907431551
Delta: 0.0014373035544759365 	  Loss: 1.5674756590178367 	 Accuracy: 0.5241199478487614
Delta: 0.0015611956814402027 	  Loss: 1.5678131362569998 	 Accuracy: 0.5267275097783573
Delta: 0.002728191382116409 	  Loss: 1.567748175251529 	 Accuracy: 0.5241199478487614
Delta: 0.0005572847460772125 	  Loss: 1.568094446041815 	 Accuracy: 0.5280312907431551
Delta: 0.002049599874805434 	  Loss: 1.5675477170734722 	 Accuracy: 0.5280312907431551
Delta: 3.50505492780268e-05 	  Loss: 1.5675449984886252 	 Accuracy: 0.5280312907431551
Delta: 0.0006518661661574624 	  Loss: 1.5676023175509677 	 Accuracy: 0.530638852672751
Delta: 0.002108529790317351 	  Loss: 1.5672629347321871 	 Accuracy: 0.5280312907431551
Delta: 0.0017031757955477123 	  Loss: 1.567870845322543 	 Accuracy: 0.529335071707953
Delta: 3.330691429611463e-05 	  Loss: 1.5677223124631712 	 Accuracy: 0.5280312907431551
Delta: 0.0030533202666343175 	  Loss: 1.567627993593291 	 Accuracy: 0.5280312907431551
Delta: 0.0011693434945484796 	  Loss: 1.5676907890617828 	 Accuracy: 0.5267275097783573
Delta: 0.0005488650021114739 	  Loss: 1.5675352409688352 	 Accuracy: 0.5215123859191656
Delta: 0.003166915613363128 	  Loss: 1.567247037802309 	 Accuracy: 0.5267275097783573
Delta: 0.003933595019091015 	  Loss: 1.5670326155024092 	 Accuracy: 0.5280312907431551
Delta: 0.0026843403885801827 	  Loss: 1.5674507781510274 	 Accuracy: 0.5267275097783573
Delta: 0.0024409000133681254 	  Loss: 1.567510469637193 	 Accuracy: 0.5280312907431551
Delta: 3.587645120116045e-05 	  Loss: 1.5673944721989082 	 Accuracy: 0.5267275097783573
Delta: 0.002559046807840766 	  Loss: 1.5673701896342809 	 Accuracy: 0.5280312907431551
Delta: 0.001489931794696769 	  Loss: 1.5673443239704725 	 Accuracy: 0.5280312907431551
Delta: 0.0030768092243607928 	  Loss: 1.5671203497227078 	 Accuracy: 0.5280312907431551
Delta: 0.0032326732112378776 	  Loss: 1.5669353384587328 	 Accuracy: 0.5267275097783573
Delta: 0.0034300148762538606 	  Loss: 1.566997220433474 	 Accuracy: 0.5267275097783573
Delta: 0.002323073105931595 	  Loss: 1.5670951105722222 	 Accuracy: 0.5267275097783573
Delta: 0.0037295011961278445 	  Loss: 1.5669586606655836 	 Accuracy: 0.5228161668839635
Delta: 0.005123515210203203 	  Loss: 1.5678944581409482 	 Accuracy: 0.5280312907431551
Delta: 0.002442274578497239 	  Loss: 1.5678828197588577 	 Accuracy: 0.5228161668839635
Delta: 3.136533280939877e-05 	  Loss: 1.567910212151476 	 Accuracy: 0.5241199478487614
Delta: 0.0006490587818933998 	  Loss: 1.5681045677451402 	 Accuracy: 0.5241199478487614
Delta: 0.0012658200175551105 	  Loss: 1.567828795113447 	 Accuracy: 0.5254237288135594
Delta: 0.00010091088532905938 	  Loss: 1.5677690651714937 	 Accuracy: 0.5254237288135594
Delta: 0.0010308765540022187 	  Loss: 1.5678490612266387 	 Accuracy: 0.5241199478487614
Delta: 0.0008506872474298167 	  Loss: 1.5678984007788153 	 Accuracy: 0.5254237288135594
Delta: 0.0008254944958510708 	  Loss: 1.5679561062360543 	 Accuracy: 0.5254237288135594
Delta: 0.0023785720610117276 	  Loss: 1.5681666069590674 	 Accuracy: 0.5241199478487614
Delta: 0.0008163877400885144 	  Loss: 1.5679319132539242 	 Accuracy: 0.5241199478487614
Delta: 0.002108098621263508 	  Loss: 1.5675289509361239 	 Accuracy: 0.5241199478487614
Delta: 0.001576120801654171 	  Loss: 1.5679663161137731 	 Accuracy: 0.5228161668839635
Delta: 0.0005390267074180796 	  Loss: 1.5680876287522996 	 Accuracy: 0.5241199478487614
Delta: 0.004794803822628415 	  Loss: 1.5686032341047313 	 Accuracy: 0.5228161668839635
Delta: 0.004089875547478378 	  Loss: 1.5680862208096207 	 Accuracy: 0.5241199478487614
Delta: 0.0033679455332938407 	  Loss: 1.5685663497401625 	 Accuracy: 0.5215123859191656
Delta: 0.005008570826953139 	  Loss: 1.5688797852955694 	 Accuracy: 0.5228161668839635
Delta: 0.003966916545121751 	  Loss: 1.56919085420856 	 Accuracy: 0.5228161668839635
Delta: 0.00400390349853265 	  Loss: 1.5684764856136542 	 Accuracy: 0.5228161668839635
Delta: 0.0036841579398009467 	  Loss: 1.5682307176513284 	 Accuracy: 0.5215123859191656
Delta: 0.003747599582660593 	  Loss: 1.5682609714535387 	 Accuracy: 0.5149934810951761
Delta: 0.004516423597870947 	  Loss: 1.56859970981436 	 Accuracy: 0.5202086049543677
Delta: 6.23743981678022e-05 	  Loss: 1.5682364749407172 	 Accuracy: 0.5202086049543677
Delta: 2.8927429976826275e-05 	  Loss: 1.5682073777551948 	 Accuracy: 0.5228161668839635
Delta: 0.0014960748837131803 	  Loss: 1.5679849834141404 	 Accuracy: 0.5202086049543677
Delta: 0.0008581839500732692 	  Loss: 1.568246940785187 	 Accuracy: 0.5215123859191656
Delta: 5.7340556632307064e-05 	  Loss: 1.5682910049889787 	 Accuracy: 0.5241199478487614
Delta: 0.001020958556320518 	  Loss: 1.5681689759057913 	 Accuracy: 0.5215123859191656
Delta: 5.8081542446260275e-05 	  Loss: 1.568053825302229 	 Accuracy: 0.5202086049543677
Delta: 6.76135958361777e-05 	  Loss: 1.5682395418841275 	 Accuracy: 0.5202086049543677
Delta: 1.5153717495661404e-05 	  Loss: 1.5682305852267389 	 Accuracy: 0.5189048239895697
Delta: 0.002649179143749917 	  Loss: 1.5683357013436394 	 Accuracy: 0.5254237288135594
Delta: 0.0005918681386806943 	  Loss: 1.56784527782606 	 Accuracy: 0.5215123859191656
Delta: 0.001688231991250945 	  Loss: 1.5682876237773862 	 Accuracy: 0.5189048239895697
Delta: 0.0008234276741967887 	  Loss: 1.5682406959972617 	 Accuracy: 0.5202086049543677
Delta: 4.239949747954881e-06 	  Loss: 1.568245994285045 	 Accuracy: 0.5215123859191656
Delta: 0.0012169255968034582 	  Loss: 1.568209764839719 	 Accuracy: 0.5215123859191656
Delta: 0.004705368301660178 	  Loss: 1.5683993170887893 	 Accuracy: 0.5215123859191656
Delta: 2.4588354813800627e-05 	  Loss: 1.5684254845675847 	 Accuracy: 0.5202086049543677
Delta: 0.0032665909877920116 	  Loss: 1.5682730864390746 	 Accuracy: 0.5176010430247718
Delta: 0.004769163349882913 	  Loss: 1.5683220528345578 	 Accuracy: 0.5241199478487614
Delta: 0.0012266212709214632 	  Loss: 1.5679094989785631 	 Accuracy: 0.5202086049543677
Delta: 0.0005658553406327006 	  Loss: 1.5683730045920674 	 Accuracy: 0.5202086049543677
Delta: 2.352427218436374e-05 	  Loss: 1.5682962473477697 	 Accuracy: 0.5254237288135594
Delta: 0.00446722849232099 	  Loss: 1.5683754532731071 	 Accuracy: 0.5228161668839635
Delta: 0.020958696435167443 	  Loss: 2.154111827911678 	 Accuracy: 0.19035202086049544
Delta: 0.01895976475715451 	  Loss: 2.0568222387222734 	 Accuracy: 0.40547588005215124
Delta: 0.018174072377635825 	  Loss: 1.8756442070592092 	 Accuracy: 0.529335071707953
Delta: 0.016514350640281082 	  Loss: 1.6952691189004638 	 Accuracy: 0.5541069100391134
Delta: 0.013992680335876523 	  Loss: 1.6062119651089823 	 Accuracy: 0.5332464146023468
Delta: 0.01107443853817512 	  Loss: 1.5751036707525716 	 Accuracy: 0.5267275097783573
Delta: 0.009584835448636218 	  Loss: 1.5617514061000266 	 Accuracy: 0.5241199478487614

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006986880932439318 	  Loss: 1.5579814592449623 	 Accuracy: 0.5241199478487614
Delta: 0.005742546383328482 	  Loss: 1.5568197504091248 	 Accuracy: 0.5241199478487614
Delta: 0.005034846762608053 	  Loss: 1.556068953969126 	 Accuracy: 0.5241199478487614
Delta: 0.0031656098089831784 	  Loss: 1.5561607776043498 	 Accuracy: 0.5241199478487614
Delta: 0.00315290659718593 	  Loss: 1.5561296279388661 	 Accuracy: 0.5228161668839635
Delta: 0.0025878153561492037 	  Loss: 1.5564081868258826 	 Accuracy: 0.5202086049543677
Delta: 0.003257466586781336 	  Loss: 1.5565743434013322 	 Accuracy: 0.5215123859191656
Delta: 0.004532373919036465 	  Loss: 1.556770094154543 	 Accuracy: 0.5215123859191656
Delta: 0.003080525018891812 	  Loss: 1.556947520653925 	 Accuracy: 0.5202086049543677
Delta: 0.0021964224342777366 	  Loss: 1.5569715360674898 	 Accuracy: 0.5215123859191656
Delta: 0.004169596282194279 	  Loss: 1.557266355970361 	 Accuracy: 0.5202086049543677
Delta: 0.002263508864999999 	  Loss: 1.55757168492135 	 Accuracy: 0.5215123859191656
Delta: 0.002014025038056365 	  Loss: 1.5568951146509566 	 Accuracy: 0.5215123859191656
Delta: 0.0028353876508330116 	  Loss: 1.5569880426075708 	 Accuracy: 0.5215123859191656
Delta: 4.44886431928548e-05 	  Loss: 1.5569415321593465 	 Accuracy: 0.5215123859191656
Delta: 0.0012941268986312545 	  Loss: 1.5568975562424154 	 Accuracy: 0.5176010430247718
Delta: 0.002523465703185556 	  Loss: 1.5565594571770625 	 Accuracy: 0.5215123859191656
Delta: 0.0007824201330327446 	  Loss: 1.557075675461041 	 Accuracy: 0.5241199478487614
Delta: 0.0032491351110945973 	  Loss: 1.5561714501736694 	 Accuracy: 0.5228161668839635
Delta: 0.0023235708227534063 	  Loss: 1.5564926408024258 	 Accuracy: 0.5228161668839635
Delta: 0.002245489508221377 	  Loss: 1.5568139292550203 	 Accuracy: 0.5241199478487614
Delta: 6.275158515641397e-05 	  Loss: 1.5565910381488788 	 Accuracy: 0.5228161668839635
Delta: 0.0016963202841046578 	  Loss: 1.5565739123287023 	 Accuracy: 0.5228161668839635
Delta: 0.0020033605597692215 	  Loss: 1.5568490307416507 	 Accuracy: 0.529335071707953
Delta: 0.003426382584339291 	  Loss: 1.5574675310711532 	 Accuracy: 0.5241199478487614
Delta: 0.0024312369858436257 	  Loss: 1.5571491860081332 	 Accuracy: 0.5228161668839635
Delta: 0.0012808638884645148 	  Loss: 1.557658053914392 	 Accuracy: 0.5202086049543677
Delta: 0.002515094368614858 	  Loss: 1.5580748798023216 	 Accuracy: 0.5228161668839635
Delta: 3.3733111917422084e-05 	  Loss: 1.5580292025532387 	 Accuracy: 0.5202086049543677
Delta: 2.4167888312802024e-05 	  Loss: 1.5580087009518517 	 Accuracy: 0.5202086049543677
Delta: 1.2509869248157989e-05 	  Loss: 1.5580246516481326 	 Accuracy: 0.5202086049543677
Delta: 3.26966314655086e-05 	  Loss: 1.5580414079427596 	 Accuracy: 0.5202086049543677
Delta: 3.5292136442073704e-05 	  Loss: 1.5580600046539361 	 Accuracy: 0.5215123859191656
Delta: 0.0006486209834510676 	  Loss: 1.558021014142183 	 Accuracy: 0.5202086049543677
Delta: 0.0006478748944114126 	  Loss: 1.5580426303282733 	 Accuracy: 0.5202086049543677
Delta: 0.0010781639064796138 	  Loss: 1.5580816824615775 	 Accuracy: 0.5215123859191656
Delta: 0.0020292974125780444 	  Loss: 1.5580102772295175 	 Accuracy: 0.5189048239895697
Delta: 0.000964214997279868 	  Loss: 1.5580525405518828 	 Accuracy: 0.5202086049543677
Delta: 0.0013720045078815654 	  Loss: 1.5581850952829421 	 Accuracy: 0.5202086049543677
Delta: 0.0010402260460331528 	  Loss: 1.5579573080313294 	 Accuracy: 0.5202086049543677
Delta: 2.9136256782360536e-05 	  Loss: 1.5579923956071173 	 Accuracy: 0.4276401564537158
Delta: 0.004033828169035468 	  Loss: 1.5616452216090195 	 Accuracy: 0.516297262059974
Delta: 0.003243269399357126 	  Loss: 1.5580264520607805 	 Accuracy: 0.5202086049543677
Delta: 0.001444801259643587 	  Loss: 1.5573684994683368 	 Accuracy: 0.5215123859191656
Delta: 0.004002035959779527 	  Loss: 1.5563858079966177 	 Accuracy: 0.5228161668839635
Delta: 0.0031345710850731994 	  Loss: 1.5552845843755323 	 Accuracy: 0.5241199478487614
Delta: 0.0011908540644469264 	  Loss: 1.5554572417462245 	 Accuracy: 0.5215123859191656
Delta: 0.0019451303969760913 	  Loss: 1.5550827612229843 	 Accuracy: 0.5254237288135594
Delta: 7.66019267522554e-05 	  Loss: 1.5552224452605676 	 Accuracy: 0.5189048239895697
Delta: 0.0029991396020056828 	  Loss: 1.5559771102120776 	 Accuracy: 0.5189048239895697
Delta: 0.0037821043687015013 	  Loss: 1.5578980294616558 	 Accuracy: 0.5176010430247718
Delta: 0.0033852525410571245 	  Loss: 1.5559954954399646 	 Accuracy: 0.5228161668839635
Delta: 0.0035367572374569185 	  Loss: 1.5562250339214794 	 Accuracy: 0.5202086049543677
Delta: 0.003674238600500556 	  Loss: 1.5552087766212381 	 Accuracy: 0.5241199478487614
Delta: 0.0032544927658669596 	  Loss: 1.554923667877851 	 Accuracy: 0.5241199478487614
Delta: 0.0009850602408224681 	  Loss: 1.5547153178175184 	 Accuracy: 0.5228161668839635
Delta: 4.297277810902347e-06 	  Loss: 1.5547043062344978 	 Accuracy: 0.5228161668839635
Delta: 6.505146166814595e-12 	  Loss: 1.5547043062279426 	 Accuracy: 0.5202086049543677
converged at iter  64
Delta: 0.021058362666219646 	  Loss: 2.153951258349469 	 Accuracy: 0.19556714471968709
Delta: 0.019119578665138706 	  Loss: 2.050362547309847 	 Accuracy: 0.4002607561929596
Delta: 0.01820967573873487 	  Loss: 1.8430428095977238 	 Accuracy: 0.48239895697522817
Delta: 0.015596635210052265 	  Loss: 1.6785245312554924 	 Accuracy: 0.4667535853976532
Delta: 0.0125112807572362 	  Loss: 1.6219184495322836 	 Accuracy: 0.439374185136897
Delta: 0.010033386233032869 	  Loss: 1.6061876723319353 	 Accuracy: 0.43546284224250326

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007605475549545788 	  Loss: 1.601490772676289 	 Accuracy: 0.4276401564537158
Delta: 0.006642470703305006 	  Loss: 1.6001970955019604 	 Accuracy: 0.43546284224250326
Delta: 0.0058511100833870434 	  Loss: 1.600080906438452 	 Accuracy: 0.4315514993481095
Delta: 0.003234215579016401 	  Loss: 1.600069739727636 	 Accuracy: 0.4315514993481095
Delta: 0.0030376105953433805 	  Loss: 1.6000066604187602 	 Accuracy: 0.4302477183833116
Delta: 0.0010513151642249552 	  Loss: 1.599999020853693 	 Accuracy: 0.4302477183833116
Delta: 0.001981458122279069 	  Loss: 1.6002777658727674 	 Accuracy: 0.43285528031290743
Delta: 0.0019514529226217863 	  Loss: 1.6001057270783192 	 Accuracy: 0.4302477183833116
Delta: 0.0006748411296165337 	  Loss: 1.5999684326739674 	 Accuracy: 0.4315514993481095
Delta: 1.5349209972165612e-05 	  Loss: 1.599956340392041 	 Accuracy: 0.43285528031290743
Delta: 0.001122077175409159 	  Loss: 1.5999162289941595 	 Accuracy: 0.43415906127770537
Delta: 0.0018096032094300366 	  Loss: 1.5998936979847282 	 Accuracy: 0.4302477183833116
Delta: 0.0033981321430827643 	  Loss: 1.600350025480774 	 Accuracy: 0.42894393741851367
Delta: 0.002630988452580367 	  Loss: 1.6000299036106664 	 Accuracy: 0.4302477183833116
Delta: 0.0009021216080781802 	  Loss: 1.5998312861599988 	 Accuracy: 0.42894393741851367
Delta: 0.0009472682473629021 	  Loss: 1.600006036682887 	 Accuracy: 0.42894393741851367
Delta: 0.00012649654227621005 	  Loss: 1.6000843878417659 	 Accuracy: 0.4315514993481095
Delta: 0.0024786796911449565 	  Loss: 1.600307891747839 	 Accuracy: 0.4302477183833116
Delta: 9.349600574204075e-05 	  Loss: 1.6004502752674494 	 Accuracy: 0.4315514993481095
Delta: 0.0006714356662269074 	  Loss: 1.6003980026026496 	 Accuracy: 0.4315514993481095
Delta: 0.0011768011616937533 	  Loss: 1.6006489230122551 	 Accuracy: 0.4302477183833116
Delta: 0.002699396570525664 	  Loss: 1.6003344362559306 	 Accuracy: 0.4445893089960887
Delta: 0.0015598040689865226 	  Loss: 1.6003975552914351 	 Accuracy: 0.4302477183833116
Delta: 0.0022937948504432528 	  Loss: 1.599831218362394 	 Accuracy: 0.4302477183833116
Delta: 0.0026203471899449325 	  Loss: 1.5997320137158035 	 Accuracy: 0.4302477183833116
Delta: 0.0005453716327141437 	  Loss: 1.6000130913095254 	 Accuracy: 0.4315514993481095
Delta: 0.0016557271417190333 	  Loss: 1.6002889316202507 	 Accuracy: 0.4276401564537158
Delta: 0.0011605435746500894 	  Loss: 1.600658189815376 	 Accuracy: 0.4302477183833116
Delta: 0.0010509659763563166 	  Loss: 1.6003489928621404 	 Accuracy: 0.43415906127770537
Delta: 0.0005472679711488778 	  Loss: 1.600581299156414 	 Accuracy: 0.4302477183833116
Delta: 0.0005633069621871818 	  Loss: 1.6004926040545477 	 Accuracy: 0.4302477183833116
Delta: 0.0005534114018183857 	  Loss: 1.60029183763071 	 Accuracy: 0.4302477183833116
Delta: 0.0005527955903861724 	  Loss: 1.6004917045784628 	 Accuracy: 0.4315514993481095
Delta: 2.933438155844873e-05 	  Loss: 1.6005995291216117 	 Accuracy: 0.42633637548891784
Delta: 0.0007655821065714319 	  Loss: 1.6005023789469779 	 Accuracy: 0.4276401564537158
Delta: 0.0032371675848505764 	  Loss: 1.6000488230367707 	 Accuracy: 0.4315514993481095
Delta: 0.004070849357626992 	  Loss: 1.5998937731761704 	 Accuracy: 0.4302477183833116
Delta: 0.0006378639891957754 	  Loss: 1.6002648811795694 	 Accuracy: 0.4315514993481095
Delta: 0.0016157310829953064 	  Loss: 1.5998738248234015 	 Accuracy: 0.4302477183833116
Delta: 0.0028387409742451513 	  Loss: 1.6004268050661103 	 Accuracy: 0.4315514993481095
Delta: 0.0019712152806382424 	  Loss: 1.599937455879832 	 Accuracy: 0.4315514993481095
Delta: 0.0008668386061935066 	  Loss: 1.600103119732022 	 Accuracy: 0.4302477183833116
Delta: 0.003667453035334477 	  Loss: 1.6005941526213883 	 Accuracy: 0.4315514993481095
Delta: 1.776077716086411e-05 	  Loss: 1.6005804927254865 	 Accuracy: 0.4302477183833116
Delta: 2.577284528652885e-07 	  Loss: 1.6005802758266028 	 Accuracy: 0.4315514993481095
Delta: 0.002350853062383684 	  Loss: 1.6006874511815932 	 Accuracy: 0.42894393741851367
Delta: 0.0034303030542028254 	  Loss: 1.6007367574023976 	 Accuracy: 0.4315514993481095
Delta: 0.001753507823768439 	  Loss: 1.6012723487123464 	 Accuracy: 0.4302477183833116
Delta: 0.0023603111645309626 	  Loss: 1.6012868234736835 	 Accuracy: 0.4302477183833116
Delta: 0.000774284224459378 	  Loss: 1.6007238459089033 	 Accuracy: 0.4302477183833116
Delta: 0.0008684632902771104 	  Loss: 1.600631604056673 	 Accuracy: 0.42894393741851367
Delta: 0.0021209878739214005 	  Loss: 1.6007943242162148 	 Accuracy: 0.4276401564537158
Delta: 0.0025198802525286607 	  Loss: 1.6002306791957086 	 Accuracy: 0.4315514993481095
Delta: 0.001474036970109125 	  Loss: 1.6002673978998116 	 Accuracy: 0.4302477183833116
Delta: 0.0025607298862082547 	  Loss: 1.6001494570213743 	 Accuracy: 0.42894393741851367
Delta: 0.0034825018634807793 	  Loss: 1.5997045966310992 	 Accuracy: 0.4315514993481095
Delta: 0.004007622062700356 	  Loss: 1.5999901330543596 	 Accuracy: 0.4276401564537158
Delta: 0.0037832280010457217 	  Loss: 1.6002520251677539 	 Accuracy: 0.4276401564537158
Delta: 0.0036721529828915543 	  Loss: 1.6001998404190796 	 Accuracy: 0.4276401564537158
Delta: 0.0013069241607111854 	  Loss: 1.6001693961524388 	 Accuracy: 0.4276401564537158
Delta: 0.0005629282742016902 	  Loss: 1.6002653258869248 	 Accuracy: 0.41851368970013036
Delta: 0.0053410328414231515 	  Loss: 1.60100401992706 	 Accuracy: 0.41851368970013036
Delta: 0.003312020953727629 	  Loss: 1.6006404557503706 	 Accuracy: 0.42633637548891784
Delta: 6.7578486688687e-05 	  Loss: 1.6006627581501571 	 Accuracy: 0.4276401564537158
Delta: 0.005247243250241424 	  Loss: 1.5995209903752574 	 Accuracy: 0.4276401564537158
Delta: 0.0017944250279215792 	  Loss: 1.599898079663033 	 Accuracy: 0.4276401564537158
Delta: 0.0001273661434967596 	  Loss: 1.5994176050722706 	 Accuracy: 0.4276401564537158
Delta: 0.0033224483169059667 	  Loss: 1.5996107853706918 	 Accuracy: 0.4276401564537158
Delta: 0.0011975786614446108 	  Loss: 1.5994209260802799 	 Accuracy: 0.42894393741851367
Delta: 0.004134610818421446 	  Loss: 1.5993863206948407 	 Accuracy: 0.42894393741851367
Delta: 0.0017418451109068227 	  Loss: 1.599541556887293 	 Accuracy: 0.42894393741851367
Delta: 0.0033938953772392915 	  Loss: 1.5993962093657772 	 Accuracy: 0.42633637548891784
Delta: 2.0339528201429328e-05 	  Loss: 1.5993912407245467 	 Accuracy: 0.4276401564537158
Delta: 0.002809754439263127 	  Loss: 1.5993283395563922 	 Accuracy: 0.4276401564537158
Delta: 0.0036564977612845487 	  Loss: 1.5994523971463415 	 Accuracy: 0.42633637548891784
Delta: 0.0015872445698199948 	  Loss: 1.5995103068094048 	 Accuracy: 0.42633637548891784
Delta: 0.003070907097503651 	  Loss: 1.598538846747943 	 Accuracy: 0.4276401564537158
Delta: 0.003601056840508981 	  Loss: 1.5993081746291407 	 Accuracy: 0.4276401564537158
Delta: 0.0026732246943486607 	  Loss: 1.599144948606375 	 Accuracy: 0.42894393741851367
Delta: 0.0018917880403843145 	  Loss: 1.599179903504443 	 Accuracy: 0.4276401564537158
Delta: 0.004552944220041601 	  Loss: 1.5992081493088615 	 Accuracy: 0.4276401564537158
Delta: 4.882446479285385e-05 	  Loss: 1.5991461492012278 	 Accuracy: 0.4276401564537158
Delta: 7.835830678709768e-05 	  Loss: 1.5990190293665438 	 Accuracy: 0.4276401564537158
Delta: 0.003548331673325816 	  Loss: 1.5987761136556577 	 Accuracy: 0.42503259452411996
Delta: 0.0006307232348706904 	  Loss: 1.598669014369895 	 Accuracy: 0.4276401564537158
Delta: 0.002227302403527048 	  Loss: 1.5985077563750534 	 Accuracy: 0.4276401564537158
Delta: 0.003454284313964562 	  Loss: 1.5982891765091825 	 Accuracy: 0.4276401564537158
Delta: 0.0013791391388923927 	  Loss: 1.5985326718277848 	 Accuracy: 0.4276401564537158
Delta: 0.004926837280532352 	  Loss: 1.599535829526865 	 Accuracy: 0.42633637548891784
Delta: 0.003579600396940686 	  Loss: 1.5996409273608045 	 Accuracy: 0.42633637548891784
Delta: 0.0010380919133015456 	  Loss: 1.599695538293211 	 Accuracy: 0.42503259452411996
Delta: 1.8489576937531185e-05 	  Loss: 1.5996810988977028 	 Accuracy: 0.4276401564537158
Delta: 0.0027423294425246957 	  Loss: 1.5996068136599986 	 Accuracy: 0.42503259452411996
Delta: 0.0044410980807971295 	  Loss: 1.5996780138542215 	 Accuracy: 0.42633637548891784
Delta: 0.021099426124388046 	  Loss: 2.1526367135638096 	 Accuracy: 0.20078226857887874
Delta: 0.01871933939578151 	  Loss: 2.0461052139435436 	 Accuracy: 0.35853976531942633
Delta: 0.018158232495941437 	  Loss: 1.8580361238345475 	 Accuracy: 0.5228161668839635
Delta: 0.016805989885372918 	  Loss: 1.6911641827340684 	 Accuracy: 0.5032594524119948
Delta: 0.013158109745445304 	  Loss: 1.6150624124927515 	 Accuracy: 0.5202086049543677
Delta: 0.010360964850279104 	  Loss: 1.590381232925093 	 Accuracy: 0.5136897001303781

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007393574428054593 	  Loss: 1.583365815757789 	 Accuracy: 0.5241199478487614
Delta: 0.005997527539917289 	  Loss: 1.5815667021655206 	 Accuracy: 0.5176010430247718
Delta: 0.004767686444769285 	  Loss: 1.5812840913714061 	 Accuracy: 0.5149934810951761
Delta: 0.0027754259125348083 	  Loss: 1.581064756802934 	 Accuracy: 0.516297262059974
Delta: 0.0038905224666994287 	  Loss: 1.5810624045914872 	 Accuracy: 0.516297262059974
Delta: 0.001241669854221855 	  Loss: 1.5809326697702746 	 Accuracy: 0.5136897001303781
Delta: 0.002031707757194706 	  Loss: 1.5810201290406927 	 Accuracy: 0.5123859191655802
Delta: 2.4850910296348693e-05 	  Loss: 1.580988187004181 	 Accuracy: 0.5110821382007823
Delta: 1.0167327774694835e-05 	  Loss: 1.5810094267114176 	 Accuracy: 0.516297262059974
Delta: 2.7923110532701946e-05 	  Loss: 1.5809890023182855 	 Accuracy: 0.516297262059974
Delta: 0.000887763505442043 	  Loss: 1.5810523638719576 	 Accuracy: 0.5149934810951761
Delta: 1.3474594125777511e-05 	  Loss: 1.581029752639397 	 Accuracy: 0.516297262059974
Delta: 0.003176530829134598 	  Loss: 1.5808826940779552 	 Accuracy: 0.516297262059974
Delta: 0.004073727668073317 	  Loss: 1.580639799535801 	 Accuracy: 0.5176010430247718
Delta: 0.0029712527293987794 	  Loss: 1.5810537521471655 	 Accuracy: 0.516297262059974
Delta: 0.0028971947393969105 	  Loss: 1.5812805735699111 	 Accuracy: 0.516297262059974
Delta: 0.0018117997441893766 	  Loss: 1.5813280029520544 	 Accuracy: 0.5176010430247718
Delta: 0.0021727273125699263 	  Loss: 1.5813999316229843 	 Accuracy: 0.516297262059974
Delta: 0.003126458928539548 	  Loss: 1.5816699659366522 	 Accuracy: 0.5149934810951761
Delta: 0.003213320222788786 	  Loss: 1.5817477430209481 	 Accuracy: 0.516297262059974
Delta: 0.003268675513903376 	  Loss: 1.5815898543448081 	 Accuracy: 0.516297262059974
Delta: 0.002191363208843657 	  Loss: 1.5814017360939365 	 Accuracy: 0.516297262059974
Delta: 0.0030712110579581542 	  Loss: 1.5815923119195507 	 Accuracy: 0.516297262059974
Delta: 0.002145080497649119 	  Loss: 1.581809424026565 	 Accuracy: 0.516297262059974
Delta: 0.0034234133950506603 	  Loss: 1.5822285271630245 	 Accuracy: 0.5149934810951761
Delta: 0.0023782001375392756 	  Loss: 1.5823301342615528 	 Accuracy: 0.516297262059974
Delta: 0.004245330258419251 	  Loss: 1.5815119111735423 	 Accuracy: 0.516297262059974
Delta: 0.0027341604991854666 	  Loss: 1.580852157136706 	 Accuracy: 0.5136897001303781
Delta: 0.002539748057314809 	  Loss: 1.5810569772472454 	 Accuracy: 0.5202086049543677
Delta: 0.0026122869666638 	  Loss: 1.5818980878476787 	 Accuracy: 0.5149934810951761
Delta: 0.001676594716393755 	  Loss: 1.5813224312169827 	 Accuracy: 0.5176010430247718
Delta: 0.004221357399401935 	  Loss: 1.5813984681346165 	 Accuracy: 0.5202086049543677
Delta: 0.0037496455770894836 	  Loss: 1.5812748397520355 	 Accuracy: 0.5136897001303781
Delta: 0.002626941407849135 	  Loss: 1.5809316625518972 	 Accuracy: 0.5136897001303781
Delta: 0.00267258074528554 	  Loss: 1.5810533836082303 	 Accuracy: 0.5189048239895697
Delta: 0.0033050022525455847 	  Loss: 1.5815403418215919 	 Accuracy: 0.5176010430247718
Delta: 0.0033427230126445062 	  Loss: 1.5826368228429781 	 Accuracy: 0.5215123859191656
Delta: 0.003641170539129018 	  Loss: 1.5821744796138335 	 Accuracy: 0.5136897001303781
Delta: 0.002265504194085386 	  Loss: 1.582368169297296 	 Accuracy: 0.5189048239895697
Delta: 0.001858366279754046 	  Loss: 1.5823832233513389 	 Accuracy: 0.516297262059974
Delta: 0.0016828453700059112 	  Loss: 1.5825579495476638 	 Accuracy: 0.5149934810951761
Delta: 0.000947214831893707 	  Loss: 1.5826958890270224 	 Accuracy: 0.5110821382007823
Delta: 0.004116495052134574 	  Loss: 1.5819870848572863 	 Accuracy: 0.516297262059974
Delta: 0.00434567331569985 	  Loss: 1.581571496317422 	 Accuracy: 0.5189048239895697
Delta: 0.0026758673121433747 	  Loss: 1.5819431159470732 	 Accuracy: 0.5176010430247718
Delta: 0.0005440626460551404 	  Loss: 1.5819002775812236 	 Accuracy: 0.5136897001303781
Delta: 0.003237489883617253 	  Loss: 1.5824526856352459 	 Accuracy: 0.516297262059974
Delta: 0.002019939970171068 	  Loss: 1.582666837263204 	 Accuracy: 0.5149934810951761
Delta: 0.0025431945842598193 	  Loss: 1.5823975106830908 	 Accuracy: 0.516297262059974
Delta: 4.6797968165314655e-05 	  Loss: 1.5823599453551416 	 Accuracy: 0.5136897001303781
Delta: 0.003718251800230509 	  Loss: 1.5824398508854833 	 Accuracy: 0.5267275097783573
Delta: 0.0035276657226317007 	  Loss: 1.5824098683083052 	 Accuracy: 0.5202086049543677
Delta: 0.003589103538589096 	  Loss: 1.5811126200904448 	 Accuracy: 0.516297262059974
Delta: 0.002237686855810123 	  Loss: 1.5810685965099185 	 Accuracy: 0.516297262059974
Delta: 0.0006275088936695374 	  Loss: 1.5810314986032215 	 Accuracy: 0.49934810951760106
Delta: 0.002467249188384795 	  Loss: 1.5808773008590762 	 Accuracy: 0.5149934810951761
Delta: 0.001228323081378127 	  Loss: 1.5811507807415328 	 Accuracy: 0.5019556714471969
Delta: 0.0034152945688218804 	  Loss: 1.5831433037742206 	 Accuracy: 0.5123859191655802
Delta: 0.004480286845937292 	  Loss: 1.582811886932668 	 Accuracy: 0.5110821382007823
Delta: 0.005959966759211363 	  Loss: 1.5832574958418821 	 Accuracy: 0.5136897001303781
Delta: 0.0014074206327697207 	  Loss: 1.5832901253101612 	 Accuracy: 0.5110821382007823
Delta: 0.000825351578228504 	  Loss: 1.5834003894992819 	 Accuracy: 0.5110821382007823
Delta: 0.0038612487967642226 	  Loss: 1.5837611119505002 	 Accuracy: 0.5123859191655802
Delta: 0.0015305590580673495 	  Loss: 1.5836560935906139 	 Accuracy: 0.5136897001303781
Delta: 0.0001446151690163159 	  Loss: 1.5835624360974432 	 Accuracy: 0.5110821382007823
Delta: 0.002660743176890472 	  Loss: 1.5833655179438284 	 Accuracy: 0.5084745762711864
Delta: 0.003330414300508772 	  Loss: 1.5836063411274166 	 Accuracy: 0.5097783572359843
Delta: 0.0032069694359641637 	  Loss: 1.5837238672565404 	 Accuracy: 0.5071707953063885
Delta: 0.005344850733836829 	  Loss: 1.5849599039729356 	 Accuracy: 0.5071707953063885
Delta: 0.004095576372492315 	  Loss: 1.5849786659664795 	 Accuracy: 0.5045632333767927
Delta: 0.0019829973970757397 	  Loss: 1.5849247039276673 	 Accuracy: 0.5045632333767927
Delta: 0.002826168653330542 	  Loss: 1.5848879676076952 	 Accuracy: 0.5045632333767927
Delta: 0.0014836499771119097 	  Loss: 1.585139171777615 	 Accuracy: 0.5045632333767927
Delta: 2.3130916632047135e-05 	  Loss: 1.5851069105081677 	 Accuracy: 0.5058670143415906
Delta: 0.0034778266801016085 	  Loss: 1.5845744966960051 	 Accuracy: 0.5032594524119948
Delta: 0.002511395806980917 	  Loss: 1.586167788572384 	 Accuracy: 0.5045632333767927
Delta: 0.0032207067827148554 	  Loss: 1.5857826119063507 	 Accuracy: 0.5058670143415906
Delta: 0.0007687611243025634 	  Loss: 1.5858404010533165 	 Accuracy: 0.5045632333767927
Delta: 0.00398787000121322 	  Loss: 1.5871047494193269 	 Accuracy: 0.5058670143415906
Delta: 0.0022994930440150673 	  Loss: 1.5860850443311811 	 Accuracy: 0.5045632333767927
Delta: 0.002804591701449748 	  Loss: 1.5870007243268396 	 Accuracy: 0.5019556714471969
Delta: 7.22442978159978e-05 	  Loss: 1.586855470233446 	 Accuracy: 0.5032594524119948
Delta: 0.00016266989833817931 	  Loss: 1.5861567953722386 	 Accuracy: 0.5058670143415906
Delta: 0.0019042454243862342 	  Loss: 1.5862230033347822 	 Accuracy: 0.5045632333767927
Delta: 0.0015137235468488373 	  Loss: 1.5869918125373363 	 Accuracy: 0.5058670143415906
Delta: 0.0018431125792808126 	  Loss: 1.586130660183489 	 Accuracy: 0.5071707953063885
Delta: 0.003234376919065344 	  Loss: 1.586909500999124 	 Accuracy: 0.5058670143415906
Delta: 0.0014750308618464813 	  Loss: 1.5867960029972032 	 Accuracy: 0.5045632333767927
Delta: 0.0010049164520363754 	  Loss: 1.5868476669793865 	 Accuracy: 0.5110821382007823
Delta: 0.002479710182055846 	  Loss: 1.5862081763449005 	 Accuracy: 0.5136897001303781
Delta: 0.0013998453489015802 	  Loss: 1.5862915392270978 	 Accuracy: 0.5084745762711864
Delta: 0.0034264205015193173 	  Loss: 1.58507615170782 	 Accuracy: 0.5045632333767927
Delta: 0.0020769496279289244 	  Loss: 1.5864448052966384 	 Accuracy: 0.5071707953063885
Delta: 0.003812183258499379 	  Loss: 1.584751686723064 	 Accuracy: 0.5058670143415906
Delta: 0.02122750199618625 	  Loss: 2.1513960114136017 	 Accuracy: 0.2033898305084746
Delta: 0.019268528849239828 	  Loss: 2.024635255052139 	 Accuracy: 0.34028683181225555
Delta: 0.017773784244744538 	  Loss: 1.7892056550752686 	 Accuracy: 0.3533246414602347
Delta: 0.014494576398163081 	  Loss: 1.6730645343373753 	 Accuracy: 0.34159061277705344
Delta: 0.011870052681537593 	  Loss: 1.639932393861906 	 Accuracy: 0.34159061277705344

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008485307616757759 	  Loss: 1.6327064983232122 	 Accuracy: 0.33376792698826596
Delta: 0.0065943096374680545 	  Loss: 1.6302557039795138 	 Accuracy: 0.32985658409387225
Delta: 0.00547406974825374 	  Loss: 1.6293077175185129 	 Accuracy: 0.33116036505867014
Delta: 0.005627457421334228 	  Loss: 1.6287731610808494 	 Accuracy: 0.3350717079530639
Delta: 0.003592905351834666 	  Loss: 1.6290752124498347 	 Accuracy: 0.33376792698826596
Delta: 0.0024739647773351944 	  Loss: 1.6291487324117513 	 Accuracy: 0.3376792698826597
Delta: 0.0011532516328065037 	  Loss: 1.6293322077545007 	 Accuracy: 0.33376792698826596
Delta: 0.0008650163936902166 	  Loss: 1.6293624649380753 	 Accuracy: 0.3324641460234681
Delta: 0.0011904610292790046 	  Loss: 1.6293300194584832 	 Accuracy: 0.3324641460234681
Delta: 0.0018797330501654833 	  Loss: 1.6293815647611354 	 Accuracy: 0.3324641460234681
Delta: 0.0005483407515393575 	  Loss: 1.6293904023515577 	 Accuracy: 0.3324641460234681
Delta: 0.0011175196892317866 	  Loss: 1.6293580717285496 	 Accuracy: 0.3324641460234681
Delta: 0.0013088804915645919 	  Loss: 1.629368890756167 	 Accuracy: 0.33376792698826596
Delta: 0.0022768679848569635 	  Loss: 1.6294705608789999 	 Accuracy: 0.33376792698826596
Delta: 0.0008964272351015989 	  Loss: 1.6293364273678697 	 Accuracy: 0.3350717079530639
Delta: 0.0036814625604287845 	  Loss: 1.6294785243075118 	 Accuracy: 0.33116036505867014
Delta: 0.0019797534742984984 	  Loss: 1.6295220533666621 	 Accuracy: 0.3324641460234681
Delta: 0.0023086820445268543 	  Loss: 1.6294377946653937 	 Accuracy: 0.3324641460234681
Delta: 0.0016904153385283226 	  Loss: 1.629453793975044 	 Accuracy: 0.3324641460234681
Delta: 8.028751733476479e-05 	  Loss: 1.6293820797278706 	 Accuracy: 0.3376792698826597
Delta: 5.383805353365745e-05 	  Loss: 1.6294088455100173 	 Accuracy: 0.3324641460234681
Delta: 0.0005320102079610762 	  Loss: 1.6293771427373371 	 Accuracy: 0.33376792698826596
Delta: 0.002457402503593482 	  Loss: 1.6294570883043282 	 Accuracy: 0.33116036505867014
Delta: 0.0032101945103679566 	  Loss: 1.6295593154055361 	 Accuracy: 0.3350717079530639
Delta: 0.0018849170045728448 	  Loss: 1.6294306246865156 	 Accuracy: 0.33376792698826596
Delta: 0.002271792896861947 	  Loss: 1.6294471296161295 	 Accuracy: 0.3376792698826597
Delta: 0.002839879839543538 	  Loss: 1.6288349958038932 	 Accuracy: 0.34419817470664926
Delta: 0.0018743255513259062 	  Loss: 1.628901172070488 	 Accuracy: 0.33376792698826596
Delta: 0.002550937130234723 	  Loss: 1.6290045256094516 	 Accuracy: 0.3324641460234681
Delta: 0.004221926171227463 	  Loss: 1.6288163269871392 	 Accuracy: 0.33376792698826596
Delta: 0.0017595177277929396 	  Loss: 1.6287076989197862 	 Accuracy: 0.3324641460234681
Delta: 0.0020294818990907555 	  Loss: 1.6283681988750005 	 Accuracy: 0.3324641460234681
Delta: 0.0032139203115392535 	  Loss: 1.6276008291607877 	 Accuracy: 0.33376792698826596
Delta: 0.0023279883344111277 	  Loss: 1.6286455927106915 	 Accuracy: 0.3363754889178618
Delta: 0.0036591126374350895 	  Loss: 1.628540084705838 	 Accuracy: 0.33116036505867014
Delta: 0.0026687395954276645 	  Loss: 1.6285066112227131 	 Accuracy: 0.3324641460234681
Delta: 0.0009319205978267107 	  Loss: 1.6285733300480896 	 Accuracy: 0.33376792698826596
Delta: 0.004473072720054081 	  Loss: 1.6285164947163175 	 Accuracy: 0.3324641460234681
Delta: 0.003471713752166906 	  Loss: 1.6284394695601572 	 Accuracy: 0.33116036505867014
Delta: 0.002378810636102247 	  Loss: 1.6285703542859926 	 Accuracy: 0.3350717079530639
Delta: 0.0019999369100866557 	  Loss: 1.6283339641418055 	 Accuracy: 0.33376792698826596
Delta: 6.10893239789749e-05 	  Loss: 1.6284359668550699 	 Accuracy: 0.32985658409387225
Delta: 0.003739932281338623 	  Loss: 1.6289607868489755 	 Accuracy: 0.3324641460234681
Delta: 0.0015156012975082352 	  Loss: 1.6288886932474327 	 Accuracy: 0.33116036505867014
Delta: 0.00325243163935053 	  Loss: 1.6282786652452672 	 Accuracy: 0.32985658409387225
Delta: 0.002317974880369805 	  Loss: 1.6283610459488194 	 Accuracy: 0.3285528031290743
Delta: 8.9072875396674e-05 	  Loss: 1.6284402110805214 	 Accuracy: 0.32985658409387225
Delta: 2.8428581811954923e-05 	  Loss: 1.628488017513884 	 Accuracy: 0.32985658409387225
Delta: 0.0015415284777659055 	  Loss: 1.6285980884741504 	 Accuracy: 0.32985658409387225
Delta: 0.0031442334896870728 	  Loss: 1.6286829621020495 	 Accuracy: 0.3272490221642764
Delta: 0.0019405355572112177 	  Loss: 1.6287531110748836 	 Accuracy: 0.33116036505867014
Delta: 0.0010250209772811759 	  Loss: 1.628667133727283 	 Accuracy: 0.3285528031290743
Delta: 4.547315666425182e-05 	  Loss: 1.6286190017370998 	 Accuracy: 0.3285528031290743
Delta: 0.0016057499563369637 	  Loss: 1.6287490644311844 	 Accuracy: 0.3285528031290743
Delta: 0.004134629003609173 	  Loss: 1.6285890089653576 	 Accuracy: 0.32985658409387225
Delta: 0.003999825731950661 	  Loss: 1.6286643550412423 	 Accuracy: 0.3272490221642764
Delta: 0.003290765954631913 	  Loss: 1.6280522390993688 	 Accuracy: 0.3285528031290743
Delta: 0.003599855603389275 	  Loss: 1.6278573328019914 	 Accuracy: 0.3285528031290743
Delta: 0.0009750869419622268 	  Loss: 1.627713614005247 	 Accuracy: 0.3324641460234681
Delta: 0.004673368522575723 	  Loss: 1.6275692171268736 	 Accuracy: 0.3272490221642764
Delta: 0.0007289616343395697 	  Loss: 1.6274589495938891 	 Accuracy: 0.32985658409387225
Delta: 0.0011910811269642567 	  Loss: 1.6272727631531856 	 Accuracy: 0.32985658409387225
Delta: 0.002710305360327097 	  Loss: 1.6272480484634246 	 Accuracy: 0.3259452411994785
Delta: 0.0023363217638968244 	  Loss: 1.627418744166755 	 Accuracy: 0.3272490221642764
Delta: 0.0038198823111588527 	  Loss: 1.6274412890547019 	 Accuracy: 0.3285528031290743
Delta: 0.0021182518506306152 	  Loss: 1.6274363916941579 	 Accuracy: 0.3285528031290743
Delta: 0.004195136704909341 	  Loss: 1.6277282776985387 	 Accuracy: 0.33116036505867014
Delta: 0.004347064948143025 	  Loss: 1.627290218809125 	 Accuracy: 0.32985658409387225
Delta: 0.003466921874040699 	  Loss: 1.626765881679247 	 Accuracy: 0.32985658409387225
Delta: 0.005467550341682711 	  Loss: 1.6267547044941968 	 Accuracy: 0.3324641460234681
Delta: 0.00333224459004576 	  Loss: 1.626764610153658 	 Accuracy: 0.3285528031290743
Delta: 0.0032317152528513293 	  Loss: 1.6268435016357825 	 Accuracy: 0.32985658409387225
Delta: 0.0008534366763170608 	  Loss: 1.6267537733981774 	 Accuracy: 0.3285528031290743
Delta: 0.003007148338425469 	  Loss: 1.626802249119437 	 Accuracy: 0.32985658409387225
Delta: 1.3308299622739458e-05 	  Loss: 1.6268136523442944 	 Accuracy: 0.32985658409387225
Delta: 0.0018754480863185975 	  Loss: 1.627179668965017 	 Accuracy: 0.32985658409387225
Delta: 0.003129519542349836 	  Loss: 1.6266120981179215 	 Accuracy: 0.3272490221642764
Delta: 0.004655831536889124 	  Loss: 1.6277485761027701 	 Accuracy: 0.3285528031290743
Delta: 2.7295206881650898e-05 	  Loss: 1.6276774001153633 	 Accuracy: 0.3272490221642764
Delta: 1.6255239781830824e-05 	  Loss: 1.627733530242042 	 Accuracy: 0.3285528031290743
Delta: 0.0018519588625548601 	  Loss: 1.6271667009853166 	 Accuracy: 0.32333767926988266
Delta: 0.004513592678452105 	  Loss: 1.6286310794125356 	 Accuracy: 0.3272490221642764
Delta: 0.000771097069612963 	  Loss: 1.6284122123078253 	 Accuracy: 0.3272490221642764
Delta: 0.0008354951266580171 	  Loss: 1.628549988484398 	 Accuracy: 0.3272490221642764
Delta: 0.000655113552973301 	  Loss: 1.6283703934601774 	 Accuracy: 0.3259452411994785
Delta: 0.0029375768010659127 	  Loss: 1.6284505316695737 	 Accuracy: 0.32985658409387225
Delta: 0.004453472002483813 	  Loss: 1.6277574844359726 	 Accuracy: 0.3285528031290743
Delta: 0.003988724546903868 	  Loss: 1.6291600052881132 	 Accuracy: 0.3246414602346806
Delta: 0.004523289228697611 	  Loss: 1.6292858451455845 	 Accuracy: 0.3272490221642764
Delta: 0.003491496389487115 	  Loss: 1.6288433748818187 	 Accuracy: 0.3272490221642764
Delta: 0.00527026574402681 	  Loss: 1.6291065717306794 	 Accuracy: 0.3285528031290743
Delta: 0.002105754123679365 	  Loss: 1.6294021176468116 	 Accuracy: 0.3246414602346806
Delta: 0.0030986341549839526 	  Loss: 1.6295529263567659 	 Accuracy: 0.3272490221642764
Delta: 0.002749876437099212 	  Loss: 1.6295337173736848 	 Accuracy: 0.3272490221642764
Delta: 0.0028775552095905953 	  Loss: 1.6295666706207559 	 Accuracy: 0.3272490221642764
Delta: 0.020985848999226408 	  Loss: 2.154039730372834 	 Accuracy: 0.19426336375488917
Delta: 0.01876261209988064 	  Loss: 2.0531460625980507 	 Accuracy: 0.41590612777053454
Delta: 0.018509569410343964 	  Loss: 1.8697460256545182 	 Accuracy: 0.49022164276401564
Delta: 0.017265169545620795 	  Loss: 1.6892546217994362 	 Accuracy: 0.49282920469361147
Delta: 0.013815517427583116 	  Loss: 1.6073000284712402 	 Accuracy: 0.4745762711864407

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010247570291336168 	  Loss: 1.5864770958992003 	 Accuracy: 0.4784876140808344
Delta: 0.007924056010826871 	  Loss: 1.5816785485338443 	 Accuracy: 0.4745762711864407
Delta: 0.00611350209320702 	  Loss: 1.5805951548459423 	 Accuracy: 0.4810951760104302
Delta: 0.004348649160679175 	  Loss: 1.5803786430716111 	 Accuracy: 0.48239895697522817
Delta: 0.0034783427556423748 	  Loss: 1.5802905159554794 	 Accuracy: 0.4810951760104302
Delta: 0.0011501831958468571 	  Loss: 1.580499161081553 	 Accuracy: 0.4810951760104302
Delta: 0.0022479456266517577 	  Loss: 1.5802433376282343 	 Accuracy: 0.4810951760104302
Delta: 0.0030444673653809767 	  Loss: 1.5802796596078172 	 Accuracy: 0.4810951760104302
Delta: 0.001961631821077781 	  Loss: 1.5804204565445747 	 Accuracy: 0.4810951760104302
Delta: 0.0015013024949335303 	  Loss: 1.5804934997928586 	 Accuracy: 0.4810951760104302
Delta: 0.0027869769120039173 	  Loss: 1.5802624006640786 	 Accuracy: 0.48239895697522817
Delta: 0.003097231214818647 	  Loss: 1.580166510223815 	 Accuracy: 0.48239895697522817
Delta: 0.0014516609658943092 	  Loss: 1.5803052379798208 	 Accuracy: 0.48239895697522817
Delta: 0.0012243720888705368 	  Loss: 1.5802843484008657 	 Accuracy: 0.4810951760104302
Delta: 0.0015475100192001482 	  Loss: 1.5805535655078533 	 Accuracy: 0.48239895697522817
Delta: 0.001472744933229706 	  Loss: 1.5807156749815197 	 Accuracy: 0.4810951760104302
Delta: 0.0008467010357090021 	  Loss: 1.5810028462747825 	 Accuracy: 0.4810951760104302
Delta: 7.39395327398207e-05 	  Loss: 1.580715803297406 	 Accuracy: 0.4810951760104302
Delta: 0.00134633587324606 	  Loss: 1.5807731406999241 	 Accuracy: 0.4810951760104302
Delta: 0.002520841162725284 	  Loss: 1.5807090013635081 	 Accuracy: 0.48239895697522817
Delta: 0.002271985892526778 	  Loss: 1.580038202466357 	 Accuracy: 0.4784876140808344
Delta: 0.001219510188614504 	  Loss: 1.580642701194097 	 Accuracy: 0.4784876140808344
Delta: 0.001441446612799018 	  Loss: 1.5807255156786468 	 Accuracy: 0.4810951760104302
Delta: 0.0014067470526857953 	  Loss: 1.5803938436686944 	 Accuracy: 0.47979139504563234
Delta: 0.0022070611645768775 	  Loss: 1.5803200747113961 	 Accuracy: 0.48239895697522817
Delta: 0.0024126068046757864 	  Loss: 1.5808116785708486 	 Accuracy: 0.4810951760104302
Delta: 0.0042916000938036675 	  Loss: 1.5804386976852123 	 Accuracy: 0.4810951760104302
Delta: 0.003174252642278618 	  Loss: 1.5808471919865468 	 Accuracy: 0.4810951760104302
Delta: 0.0021946498500167565 	  Loss: 1.5809436371735952 	 Accuracy: 0.4810951760104302
Delta: 0.0028652268214532563 	  Loss: 1.58094655700516 	 Accuracy: 0.48239895697522817
Delta: 0.0019592407888333377 	  Loss: 1.5808579791999056 	 Accuracy: 0.4810951760104302
Delta: 0.0017807477969466734 	  Loss: 1.580934634539363 	 Accuracy: 0.4810951760104302
Delta: 8.033074709771283e-05 	  Loss: 1.5808187856056193 	 Accuracy: 0.4810951760104302
Delta: 0.000575685838439704 	  Loss: 1.5809116528763476 	 Accuracy: 0.48239895697522817
Delta: 0.0016353160096157905 	  Loss: 1.5811869943897698 	 Accuracy: 0.4810951760104302
Delta: 0.003656688126152282 	  Loss: 1.5810193635646534 	 Accuracy: 0.4758800521512386
Delta: 0.0045650857539839855 	  Loss: 1.5814197444328857 	 Accuracy: 0.48891786179921776
Delta: 0.00529470245998922 	  Loss: 1.5820014933663544 	 Accuracy: 0.4810951760104302
Delta: 0.004640360539988479 	  Loss: 1.5812400996998865 	 Accuracy: 0.48370273794002605
Delta: 0.0016670599663037968 	  Loss: 1.5814460805870072 	 Accuracy: 0.4915254237288136
Delta: 3.199894085928577e-05 	  Loss: 1.5814965863048474 	 Accuracy: 0.47979139504563234
Delta: 0.0023136592298591283 	  Loss: 1.5813045239477843 	 Accuracy: 0.47979139504563234
Delta: 0.0036319351095837177 	  Loss: 1.5812569677708024 	 Accuracy: 0.4810951760104302
Delta: 0.002912381890515217 	  Loss: 1.5811444956334175 	 Accuracy: 0.4810951760104302
Delta: 0.0022447900664519754 	  Loss: 1.5808159980365242 	 Accuracy: 0.47979139504563234
Delta: 0.001261037902419017 	  Loss: 1.5803137453585503 	 Accuracy: 0.48239895697522817
Delta: 0.0031755876599783802 	  Loss: 1.5800182689961362 	 Accuracy: 0.4745762711864407
Delta: 0.0025591329684441916 	  Loss: 1.5817328776174093 	 Accuracy: 0.4810951760104302
Delta: 0.002282700251592203 	  Loss: 1.5812835147400204 	 Accuracy: 0.47979139504563234
Delta: 0.002960059488545053 	  Loss: 1.5818574721370835 	 Accuracy: 0.4810951760104302
Delta: 0.002146847313776071 	  Loss: 1.5808511486501373 	 Accuracy: 0.47979139504563234
Delta: 0.003765526710039296 	  Loss: 1.5807121114767788 	 Accuracy: 0.4810951760104302
Delta: 0.0022276979422107134 	  Loss: 1.5812638672379855 	 Accuracy: 0.4771838331160365
Delta: 0.0031638477300879276 	  Loss: 1.582328008990034 	 Accuracy: 0.4784876140808344
Delta: 0.001081506592906733 	  Loss: 1.5822902460768828 	 Accuracy: 0.4784876140808344
Delta: 0.004121413868550632 	  Loss: 1.5820866995328615 	 Accuracy: 0.4784876140808344
Delta: 0.0026341052035293343 	  Loss: 1.5821338980957873 	 Accuracy: 0.47979139504563234
Delta: 0.0026073982269945715 	  Loss: 1.5819387450964815 	 Accuracy: 0.4784876140808344
Delta: 0.0011431044319530406 	  Loss: 1.5816515837778709 	 Accuracy: 0.47979139504563234
Delta: 6.282083217388411e-05 	  Loss: 1.5815542261566011 	 Accuracy: 0.4771838331160365
Delta: 0.0029356730843544307 	  Loss: 1.581247747074209 	 Accuracy: 0.47327249022164275
Delta: 0.005795463160243622 	  Loss: 1.581446240679905 	 Accuracy: 0.4758800521512386
Delta: 0.004129654452068141 	  Loss: 1.5812316316263584 	 Accuracy: 0.4745762711864407
Delta: 0.0045045193970226745 	  Loss: 1.5807020635868756 	 Accuracy: 0.47327249022164275
Delta: 0.004587313151557729 	  Loss: 1.5813883780699034 	 Accuracy: 0.47196870925684486
Delta: 0.003034322874127132 	  Loss: 1.5816511067129566 	 Accuracy: 0.47196870925684486
Delta: 0.00605592522896804 	  Loss: 1.5811503523624677 	 Accuracy: 0.4745762711864407
Delta: 0.004206204304958802 	  Loss: 1.5815631168594764 	 Accuracy: 0.47196870925684486
Delta: 0.003216893547323516 	  Loss: 1.5810060878303234 	 Accuracy: 0.4745762711864407
Delta: 0.004657844043068388 	  Loss: 1.5806766276181923 	 Accuracy: 0.4654498044328553
Delta: 0.005162030441071865 	  Loss: 1.5806963240786338 	 Accuracy: 0.4745762711864407
Delta: 0.0041929757473633065 	  Loss: 1.5811920548850193 	 Accuracy: 0.4745762711864407
Delta: 0.004362518525924887 	  Loss: 1.5798267298700468 	 Accuracy: 0.4745762711864407
Delta: 0.0050172253506585935 	  Loss: 1.5806438766960484 	 Accuracy: 0.47327249022164275
Delta: 0.005465508701055773 	  Loss: 1.5815617541640274 	 Accuracy: 0.4654498044328553
Delta: 0.003839280227952936 	  Loss: 1.5811443701393215 	 Accuracy: 0.4758800521512386
Delta: 0.004341166571588343 	  Loss: 1.5808330657798897 	 Accuracy: 0.47196870925684486
Delta: 0.0015175696135117053 	  Loss: 1.5808679172470548 	 Accuracy: 0.4706649282920469
Delta: 0.0048227050382928915 	  Loss: 1.581841179981536 	 Accuracy: 0.4706649282920469
Delta: 0.0017013804324035532 	  Loss: 1.5824301422286855 	 Accuracy: 0.47327249022164275
Delta: 0.000791783855141028 	  Loss: 1.5822847399257243 	 Accuracy: 0.47196870925684486
Delta: 0.0023435349600977756 	  Loss: 1.5822654004237173 	 Accuracy: 0.4784876140808344
Delta: 0.005221709385972093 	  Loss: 1.5819266575478275 	 Accuracy: 0.4745762711864407
Delta: 0.0011054454269559043 	  Loss: 1.5816891433419578 	 Accuracy: 0.4745762711864407
Delta: 0.004445916662745332 	  Loss: 1.5820378564409792 	 Accuracy: 0.4758800521512386
Delta: 0.0037583010706798863 	  Loss: 1.5816310504606872 	 Accuracy: 0.4758800521512386
Delta: 0.0013860469034293775 	  Loss: 1.5817554711321704 	 Accuracy: 0.4758800521512386
Delta: 4.8759731595431255e-05 	  Loss: 1.5816071679506596 	 Accuracy: 0.4758800521512386
Delta: 0.0019684312776108697 	  Loss: 1.5814571575342127 	 Accuracy: 0.47196870925684486
Delta: 0.0038016825354172767 	  Loss: 1.5814969765706486 	 Accuracy: 0.455019556714472
Delta: 0.007230651232649675 	  Loss: 1.5839464216294585 	 Accuracy: 0.47327249022164275
Delta: 0.00808083264361371 	  Loss: 1.583966304451375 	 Accuracy: 0.46153846153846156
Delta: 0.007701168037190416 	  Loss: 1.5880551267108798 	 Accuracy: 0.46153846153846156
Delta: 0.005539665370366201 	  Loss: 1.5867351464570534 	 Accuracy: 0.4602346805736636
Delta: 0.006768084357958028 	  Loss: 1.584231317887904 	 Accuracy: 0.4680573663624511
Delta: 0.02112318640322297 	  Loss: 2.1520764401848176 	 Accuracy: 0.2138200782268579
Delta: 0.019480821923702225 	  Loss: 2.020552784174344 	 Accuracy: 0.4758800521512386
Delta: 0.01812085500762211 	  Loss: 1.769427786098159 	 Accuracy: 0.5984354628422425
Delta: 0.015770997996194323 	  Loss: 1.6288359132742736 	 Accuracy: 0.6192959582790091
Delta: 0.01167990040774237 	  Loss: 1.5887858402623154 	 Accuracy: 0.6297262059973925

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00942186412275514 	  Loss: 1.5806962694724083 	 Accuracy: 0.6323337679269883
Delta: 0.007711464569120188 	  Loss: 1.5791932106908524 	 Accuracy: 0.6323337679269883
Delta: 0.0045171012780728026 	  Loss: 1.5788165908094576 	 Accuracy: 0.6336375488917861
Delta: 0.004064555017165554 	  Loss: 1.578779496020434 	 Accuracy: 0.6323337679269883
Delta: 0.005131488481189555 	  Loss: 1.578583575755244 	 Accuracy: 0.6323337679269883
Delta: 0.0030278160055192288 	  Loss: 1.5783465618830028 	 Accuracy: 0.6349413298565841
Delta: 0.0009459080183108871 	  Loss: 1.5783092804319143 	 Accuracy: 0.6336375488917861
Delta: 0.0029796245064908325 	  Loss: 1.5785507243188683 	 Accuracy: 0.6310299869621904
Delta: 0.0011139911243970247 	  Loss: 1.5786177473675969 	 Accuracy: 0.6310299869621904
Delta: 0.0017126374036390854 	  Loss: 1.5784979147321945 	 Accuracy: 0.6310299869621904
Delta: 0.0031689577562976547 	  Loss: 1.5788647838639391 	 Accuracy: 0.6323337679269883
Delta: 7.505971474271109e-05 	  Loss: 1.5788310720363088 	 Accuracy: 0.6232073011734028
Delta: 0.0026704680053733164 	  Loss: 1.5788875044340476 	 Accuracy: 0.6323337679269883
Delta: 0.0008651202555648057 	  Loss: 1.578888848148927 	 Accuracy: 0.6310299869621904
Delta: 0.0010429117451007045 	  Loss: 1.5788987734840836 	 Accuracy: 0.6310299869621904
Delta: 6.624172766931705e-05 	  Loss: 1.5787813036329656 	 Accuracy: 0.6323337679269883
Delta: 0.0019116794824955942 	  Loss: 1.5787251749889042 	 Accuracy: 0.6336375488917861
Delta: 3.570132941241333e-05 	  Loss: 1.5787377755767706 	 Accuracy: 0.6323337679269883
Delta: 0.0010419977107999443 	  Loss: 1.5788291155365362 	 Accuracy: 0.6284224250325945
Delta: 0.0008555933795383418 	  Loss: 1.5787356039389033 	 Accuracy: 0.6375488917861799
Delta: 0.004063158746848854 	  Loss: 1.5792482145879045 	 Accuracy: 0.6297262059973925
Delta: 0.0032361807840271253 	  Loss: 1.5793135311375561 	 Accuracy: 0.6336375488917861
Delta: 0.0005672180001786964 	  Loss: 1.5792237290678244 	 Accuracy: 0.6297262059973925
Delta: 0.003084708344783423 	  Loss: 1.5793005230395667 	 Accuracy: 0.6232073011734028
Delta: 0.005885535673081076 	  Loss: 1.579507751510971 	 Accuracy: 0.636245110821382
Delta: 0.00461133764077299 	  Loss: 1.5786886882826983 	 Accuracy: 0.6310299869621904
Delta: 0.0025119151820692603 	  Loss: 1.5788684677607154 	 Accuracy: 0.6323337679269883
Delta: 0.0018784476432817123 	  Loss: 1.5788824652808158 	 Accuracy: 0.6323337679269883
Delta: 0.003716975555505583 	  Loss: 1.5783319813427408 	 Accuracy: 0.6310299869621904
Delta: 0.002104479274025929 	  Loss: 1.5784055901003464 	 Accuracy: 0.6297262059973925
Delta: 0.0024106607417391443 	  Loss: 1.5786473408232662 	 Accuracy: 0.6336375488917861
Delta: 0.0009759645116931079 	  Loss: 1.578304953357485 	 Accuracy: 0.6310299869621904
Delta: 0.0020688430674541147 	  Loss: 1.5781689139236006 	 Accuracy: 0.6310299869621904
Delta: 0.0028246183001531832 	  Loss: 1.5780368622897982 	 Accuracy: 0.6349413298565841
Delta: 0.00066923617030076 	  Loss: 1.5779202590470702 	 Accuracy: 0.6349413298565841
Delta: 0.003417110184849812 	  Loss: 1.5777747424706807 	 Accuracy: 0.6271186440677966
Delta: 0.0008756758861108181 	  Loss: 1.5787452010395233 	 Accuracy: 0.6271186440677966
Delta: 0.002928167228505664 	  Loss: 1.5786096813460215 	 Accuracy: 0.6323337679269883
Delta: 6.43455363681867e-05 	  Loss: 1.5786008060928136 	 Accuracy: 0.6310299869621904
Delta: 0.000567752223307766 	  Loss: 1.5787005248745922 	 Accuracy: 0.6258148631029987
Delta: 0.0024867486893629946 	  Loss: 1.578863196109038 	 Accuracy: 0.6323337679269883
Delta: 0.0016825961841944123 	  Loss: 1.578484363580427 	 Accuracy: 0.6297262059973925
Delta: 0.00011559681469323975 	  Loss: 1.5790725966008423 	 Accuracy: 0.6310299869621904
Delta: 0.0025841831820262234 	  Loss: 1.577727933678138 	 Accuracy: 0.6310299869621904
Delta: 0.0035714262622590465 	  Loss: 1.5769253488353285 	 Accuracy: 0.6336375488917861
Delta: 0.004020251861370422 	  Loss: 1.576832848953937 	 Accuracy: 0.6349413298565841
Delta: 0.001975525977521082 	  Loss: 1.5763903252462703 	 Accuracy: 0.6349413298565841
Delta: 0.0031326342674352454 	  Loss: 1.575944873935173 	 Accuracy: 0.6336375488917861
Delta: 0.003606477896472905 	  Loss: 1.5765761475503912 	 Accuracy: 0.6323337679269883
Delta: 0.0035501138655290787 	  Loss: 1.5767935157626822 	 Accuracy: 0.6336375488917861
Delta: 0.0025824502710406847 	  Loss: 1.576906319369992 	 Accuracy: 0.6323337679269883
Delta: 0.0024241043096052033 	  Loss: 1.5769116913877588 	 Accuracy: 0.6323337679269883
Delta: 1.6862283537627387e-05 	  Loss: 1.57681302335281 	 Accuracy: 0.6323337679269883
Delta: 5.306283279598584e-06 	  Loss: 1.5768076261608643 	 Accuracy: 0.6349413298565841
Delta: 2.4576075968778133e-05 	  Loss: 1.576812015817771 	 Accuracy: 0.6310299869621904
Delta: 6.010152672230949e-05 	  Loss: 1.5770714845607539 	 Accuracy: 0.6310299869621904
Delta: 6.231931102655675e-05 	  Loss: 1.5768325862149382 	 Accuracy: 0.6323337679269883
Delta: 0.0039047391499033124 	  Loss: 1.5773163870545681 	 Accuracy: 0.6310299869621904
Delta: 0.0009368679376226516 	  Loss: 1.5773171924113136 	 Accuracy: 0.6323337679269883
Delta: 0.0028308568571362744 	  Loss: 1.5768554722139223 	 Accuracy: 0.6101694915254238
Delta: 3.112103175512454e-05 	  Loss: 1.5768910668069451 	 Accuracy: 0.6323337679269883
Delta: 3.26800799545722e-05 	  Loss: 1.5768743071601037 	 Accuracy: 0.6336375488917861
Delta: 0.0028351708229795024 	  Loss: 1.5768499136417158 	 Accuracy: 0.6336375488917861
Delta: 0.004309310257680068 	  Loss: 1.5763111634421065 	 Accuracy: 0.6310299869621904
Delta: 0.0026875020802764158 	  Loss: 1.5761620436754409 	 Accuracy: 0.636245110821382
Delta: 0.003884493641807626 	  Loss: 1.575732274397297 	 Accuracy: 0.6375488917861799
Delta: 0.0033951587744872067 	  Loss: 1.5753522548664955 	 Accuracy: 0.6375488917861799
Delta: 0.0009976771171279957 	  Loss: 1.5753205406425876 	 Accuracy: 0.6401564537157758
Delta: 0.004691007127623564 	  Loss: 1.5752594409919627 	 Accuracy: 0.6401564537157758
Delta: 0.002721768862378613 	  Loss: 1.5744904238519994 	 Accuracy: 0.6388526727509778
Delta: 0.0022941086045675974 	  Loss: 1.574396241739135 	 Accuracy: 0.6388526727509778
Delta: 0.002745042827202134 	  Loss: 1.5743507078849392 	 Accuracy: 0.6375488917861799
Delta: 0.003525601995746618 	  Loss: 1.57405808196789 	 Accuracy: 0.636245110821382
Delta: 0.0008374872289298572 	  Loss: 1.5738277576130577 	 Accuracy: 0.636245110821382
Delta: 0.0056742325606058 	  Loss: 1.5747512468265983 	 Accuracy: 0.6375488917861799
Delta: 0.0040070272411706 	  Loss: 1.5745277690704977 	 Accuracy: 0.6375488917861799
Delta: 0.0032548265437271503 	  Loss: 1.5741014600000431 	 Accuracy: 0.6375488917861799
Delta: 0.003755387874709926 	  Loss: 1.5743563189593215 	 Accuracy: 0.636245110821382
Delta: 0.0021832609426635755 	  Loss: 1.5740345243341225 	 Accuracy: 0.636245110821382
Delta: 0.0035382354698393187 	  Loss: 1.5739986676380406 	 Accuracy: 0.636245110821382
Delta: 0.001930215329240887 	  Loss: 1.5747143416126623 	 Accuracy: 0.6297262059973925
Delta: 0.0040702826316601215 	  Loss: 1.5769099968213667 	 Accuracy: 0.6336375488917861
Delta: 0.0015863671289902753 	  Loss: 1.5769102784302 	 Accuracy: 0.6271186440677966
Delta: 0.0036359031305989325 	  Loss: 1.5773400230025212 	 Accuracy: 0.6297262059973925
Delta: 0.0020135893906855773 	  Loss: 1.577976588552556 	 Accuracy: 0.6310299869621904
Delta: 0.002737453839647791 	  Loss: 1.5780091523845234 	 Accuracy: 0.6323337679269883
Delta: 0.003406622359539162 	  Loss: 1.576865969304024 	 Accuracy: 0.6310299869621904
Delta: 0.00461914467010212 	  Loss: 1.5782286864615247 	 Accuracy: 0.6297262059973925
Delta: 0.003074962072073622 	  Loss: 1.578229886441267 	 Accuracy: 0.6349413298565841
Delta: 0.003130297996435583 	  Loss: 1.5766494351923248 	 Accuracy: 0.6323337679269883
Delta: 0.0026173427667509483 	  Loss: 1.5764075594092914 	 Accuracy: 0.6375488917861799
Delta: 0.005026356972050387 	  Loss: 1.577739209196917 	 Accuracy: 0.6336375488917861
Delta: 0.005549066248936696 	  Loss: 1.5761584304571357 	 Accuracy: 0.6349413298565841
Delta: 0.0037986974391495667 	  Loss: 1.576531823821103 	 Accuracy: 0.6401564537157758
Delta: 0.0037276601596087726 	  Loss: 1.5761262098842377 	 Accuracy: 0.6375488917861799
Delta: 0.020974984509668396 	  Loss: 2.154048130589535 	 Accuracy: 0.19165580182529335
Delta: 0.018831653388929465 	  Loss: 2.0486194637450694 	 Accuracy: 0.4406779661016949
Delta: 0.01875277294417835 	  Loss: 1.8504272641977484 	 Accuracy: 0.5332464146023468
Delta: 0.017141405529130516 	  Loss: 1.6695523750446961 	 Accuracy: 0.5384615384615384
Delta: 0.01398356147894972 	  Loss: 1.5943392790326159 	 Accuracy: 0.5202086049543677

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009822796547484124 	  Loss: 1.5755801900494264 	 Accuracy: 0.5189048239895697
Delta: 0.006905553422205833 	  Loss: 1.5715771805022207 	 Accuracy: 0.5189048239895697
Delta: 0.00554097101133807 	  Loss: 1.570679383558153 	 Accuracy: 0.5189048239895697
Delta: 0.0047505358702860335 	  Loss: 1.5704905390854784 	 Accuracy: 0.5176010430247718
Delta: 0.0034843058050631716 	  Loss: 1.5704308548394659 	 Accuracy: 0.5176010430247718
Delta: 0.000555392859526993 	  Loss: 1.5705893386043646 	 Accuracy: 0.5176010430247718
Delta: 0.0023041837704849398 	  Loss: 1.570401344892274 	 Accuracy: 0.5176010430247718
Delta: 8.774583667098008e-05 	  Loss: 1.5703871408239984 	 Accuracy: 0.516297262059974
Delta: 0.0018391470074670781 	  Loss: 1.570398345229472 	 Accuracy: 0.5176010430247718
Delta: 0.001980194455826521 	  Loss: 1.570668863264868 	 Accuracy: 0.5202086049543677
Delta: 0.002429619546234693 	  Loss: 1.5705434481176663 	 Accuracy: 0.5176010430247718
Delta: 0.001203591635249198 	  Loss: 1.5707451533491221 	 Accuracy: 0.5176010430247718
Delta: 0.0021565770432349918 	  Loss: 1.570470634940103 	 Accuracy: 0.5149934810951761
Delta: 0.0024308504680676424 	  Loss: 1.5710444312154723 	 Accuracy: 0.516297262059974
Delta: 0.0017057845056136483 	  Loss: 1.5709824760740925 	 Accuracy: 0.516297262059974
Delta: 0.001232755326617517 	  Loss: 1.5710546619985053 	 Accuracy: 0.516297262059974
Delta: 2.0919262670170216e-05 	  Loss: 1.5710469363323272 	 Accuracy: 0.516297262059974
Delta: 0.0011004042101219998 	  Loss: 1.5710768290135222 	 Accuracy: 0.5176010430247718
Delta: 0.0007586308611411908 	  Loss: 1.5710423312253092 	 Accuracy: 0.516297262059974
Delta: 0.0028960672438833593 	  Loss: 1.5709061757733558 	 Accuracy: 0.5176010430247718
Delta: 0.003470568589116013 	  Loss: 1.5707971558963454 	 Accuracy: 0.5189048239895697
Delta: 0.002215178239451577 	  Loss: 1.5711821831941926 	 Accuracy: 0.516297262059974
Delta: 0.0017048073301191562 	  Loss: 1.5708359230007156 	 Accuracy: 0.516297262059974
Delta: 0.0022392927371370115 	  Loss: 1.5707792029239134 	 Accuracy: 0.516297262059974
Delta: 0.0023423012662395124 	  Loss: 1.5708664692994934 	 Accuracy: 0.5123859191655802
Delta: 0.002754870220940692 	  Loss: 1.5709113006292061 	 Accuracy: 0.516297262059974
Delta: 0.002390043673324193 	  Loss: 1.5711998570743178 	 Accuracy: 0.5215123859191656
Delta: 0.004438808935333493 	  Loss: 1.5699137486066845 	 Accuracy: 0.5149934810951761
Delta: 0.003608277771936499 	  Loss: 1.5702394947046907 	 Accuracy: 0.5189048239895697
Delta: 0.004321390128950098 	  Loss: 1.5694015679035163 	 Accuracy: 0.5189048239895697
Delta: 0.002813722322082281 	  Loss: 1.5692756577963434 	 Accuracy: 0.5189048239895697
Delta: 0.0016811863109093596 	  Loss: 1.5693783423425374 	 Accuracy: 0.5176010430247718
Delta: 0.0025372432299668305 	  Loss: 1.5696147055969467 	 Accuracy: 0.5176010430247718
Delta: 0.0034734700194698916 	  Loss: 1.569496286347226 	 Accuracy: 0.5176010430247718
Delta: 0.004731051216179264 	  Loss: 1.5695541958356614 	 Accuracy: 0.5176010430247718
Delta: 0.002837264289596761 	  Loss: 1.5696253881607414 	 Accuracy: 0.5176010430247718
Delta: 0.0022868273387783877 	  Loss: 1.5695904069884565 	 Accuracy: 0.5215123859191656
Delta: 0.001606977523067947 	  Loss: 1.5695755937358955 	 Accuracy: 0.516297262059974
Delta: 0.0020990458086012076 	  Loss: 1.5699009337676784 	 Accuracy: 0.5149934810951761
Delta: 0.0031487253255707377 	  Loss: 1.5700963024508146 	 Accuracy: 0.5136897001303781
Delta: 0.004179277832594201 	  Loss: 1.5698489534609457 	 Accuracy: 0.5176010430247718
Delta: 0.001666542059104065 	  Loss: 1.5698025179022905 	 Accuracy: 0.5189048239895697
Delta: 0.0016495145129517773 	  Loss: 1.5696191857066726 	 Accuracy: 0.5176010430247718
Delta: 8.499226563754438e-05 	  Loss: 1.5698949957070518 	 Accuracy: 0.5176010430247718
Delta: 0.003849559363259817 	  Loss: 1.5701844874755726 	 Accuracy: 0.5189048239895697
Delta: 0.0029487673492128125 	  Loss: 1.569874086389818 	 Accuracy: 0.5189048239895697
Delta: 0.0024001888858525564 	  Loss: 1.5696859591263113 	 Accuracy: 0.516297262059974
Delta: 0.003876414568341145 	  Loss: 1.5692662435550513 	 Accuracy: 0.516297262059974
Delta: 0.003884028297036466 	  Loss: 1.5698586992279808 	 Accuracy: 0.516297262059974
Delta: 0.0018898194671965523 	  Loss: 1.5697889705296206 	 Accuracy: 0.5110821382007823
Delta: 0.0016761678724026188 	  Loss: 1.569713638109992 	 Accuracy: 0.516297262059974
Delta: 0.0008520482414858979 	  Loss: 1.5697417360484065 	 Accuracy: 0.516297262059974
Delta: 0.0008684262368152834 	  Loss: 1.5696014519031902 	 Accuracy: 0.516297262059974
Delta: 5.4710635608826235e-05 	  Loss: 1.5697435127200419 	 Accuracy: 0.5149934810951761
Delta: 4.46593762947564e-05 	  Loss: 1.569757982076233 	 Accuracy: 0.516297262059974
Delta: 4.464811343167776e-05 	  Loss: 1.5697434918579496 	 Accuracy: 0.5058670143415906
Delta: 0.003256992777254854 	  Loss: 1.5696995449579063 	 Accuracy: 0.5110821382007823
Delta: 0.0037411375396042158 	  Loss: 1.5703454167293414 	 Accuracy: 0.5097783572359843
Delta: 0.002395267708374885 	  Loss: 1.5705974889225236 	 Accuracy: 0.5149934810951761
Delta: 0.0038580378973457593 	  Loss: 1.5712566950731102 	 Accuracy: 0.5149934810951761
Delta: 0.002304881180555885 	  Loss: 1.5705162434724231 	 Accuracy: 0.5032594524119948
Delta: 0.0016205632398763581 	  Loss: 1.5706637520153135 	 Accuracy: 0.5189048239895697
Delta: 0.004776753068701956 	  Loss: 1.5706286096231543 	 Accuracy: 0.5149934810951761
Delta: 0.002830171997053431 	  Loss: 1.5707059409324602 	 Accuracy: 0.516297262059974
Delta: 0.004605888334544756 	  Loss: 1.5704777837940083 	 Accuracy: 0.5149934810951761
Delta: 0.00667320331909769 	  Loss: 1.5714023858795132 	 Accuracy: 0.5280312907431551
Delta: 0.006929098128317134 	  Loss: 1.5716731812836338 	 Accuracy: 0.516297262059974
Delta: 0.004172580569923898 	  Loss: 1.5712742808618922 	 Accuracy: 0.516297262059974
Delta: 0.004370355277353699 	  Loss: 1.571939020639753 	 Accuracy: 0.516297262059974
Delta: 0.0029696670669573954 	  Loss: 1.5720489300264768 	 Accuracy: 0.5189048239895697
Delta: 0.004039081392508097 	  Loss: 1.5725112019975904 	 Accuracy: 0.5176010430247718
Delta: 0.0008118764292156334 	  Loss: 1.5726341952399103 	 Accuracy: 0.5202086049543677
Delta: 0.0017166222156484552 	  Loss: 1.5721359286489436 	 Accuracy: 0.516297262059974
Delta: 0.0033729217242358753 	  Loss: 1.572968764579079 	 Accuracy: 0.516297262059974
Delta: 0.0035152086064239242 	  Loss: 1.572485367552922 	 Accuracy: 0.516297262059974
Delta: 0.0021198283975848204 	  Loss: 1.5726860491618957 	 Accuracy: 0.5149934810951761
Delta: 0.0036167622251859328 	  Loss: 1.5732149742726154 	 Accuracy: 0.516297262059974
Delta: 0.003639734835020657 	  Loss: 1.5731431066093964 	 Accuracy: 0.5149934810951761
Delta: 0.005919857150411155 	  Loss: 1.5741496910722148 	 Accuracy: 0.5097783572359843
Delta: 0.00484874662498981 	  Loss: 1.5729750340917903 	 Accuracy: 0.5136897001303781
Delta: 0.0018908375800087925 	  Loss: 1.5731182474586527 	 Accuracy: 0.5136897001303781
Delta: 0.0032104655089658036 	  Loss: 1.572941508431516 	 Accuracy: 0.5136897001303781
Delta: 0.0028173495862252947 	  Loss: 1.573263356605886 	 Accuracy: 0.516297262059974
Delta: 0.004121161422416802 	  Loss: 1.5732174202380307 	 Accuracy: 0.516297262059974
Delta: 0.0030827109465300846 	  Loss: 1.5736358674660076 	 Accuracy: 0.5136897001303781
Delta: 0.002180112454458027 	  Loss: 1.5737671812211915 	 Accuracy: 0.5136897001303781
Delta: 0.004725209562863224 	  Loss: 1.575552185309643 	 Accuracy: 0.5136897001303781
Delta: 0.003369809551230992 	  Loss: 1.5746170015464198 	 Accuracy: 0.5123859191655802
Delta: 0.003542711358390217 	  Loss: 1.5745348889021913 	 Accuracy: 0.516297262059974
Delta: 0.0038068933066606296 	  Loss: 1.573867611430954 	 Accuracy: 0.5189048239895697
Delta: 0.0021627089390456765 	  Loss: 1.5735856730598354 	 Accuracy: 0.5110821382007823
Delta: 0.006205689980689623 	  Loss: 1.5758231069286004 	 Accuracy: 0.5136897001303781
Delta: 0.004208476152550794 	  Loss: 1.5764284003115194 	 Accuracy: 0.5149934810951761
Delta: 0.0052777505942436355 	  Loss: 1.5737465731874614 	 Accuracy: 0.516297262059974
Delta: 0.002576634495882774 	  Loss: 1.5741245694887522 	 Accuracy: 0.516297262059974
Delta: 0.021216361211203752 	  Loss: 2.1534158861533257 	 Accuracy: 0.2033898305084746
Delta: 0.019177688329392897 	  Loss: 2.0341568332665023 	 Accuracy: 0.23728813559322035
Delta: 0.018499976855835227 	  Loss: 1.8240030623945693 	 Accuracy: 0.26988265971316816
Delta: 0.01570453749721021 	  Loss: 1.7032785922903801 	 Accuracy: 0.27249022164276404
Delta: 0.011597761694753647 	  Loss: 1.6695825573357193 	 Accuracy: 0.27640156453715775

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009302647928136749 	  Loss: 1.661345140187522 	 Accuracy: 0.27640156453715775
Delta: 0.005991873124427248 	  Loss: 1.6600012643581177 	 Accuracy: 0.27640156453715775
Delta: 0.0035893913839620444 	  Loss: 1.6596906982090922 	 Accuracy: 0.2777053455019557
Delta: 0.004649420703537019 	  Loss: 1.659572601864535 	 Accuracy: 0.27640156453715775
Delta: 0.0033716010374220287 	  Loss: 1.6593248760038497 	 Accuracy: 0.2777053455019557
Delta: 0.002978891163362702 	  Loss: 1.6591232921760526 	 Accuracy: 0.2803129074315515
Delta: 0.004154464592987766 	  Loss: 1.6597131559131246 	 Accuracy: 0.26727509778357234
Delta: 0.004991884216454545 	  Loss: 1.6602842873889152 	 Accuracy: 0.27509778357235987
Delta: 0.002367193688078109 	  Loss: 1.6600394851266027 	 Accuracy: 0.27640156453715775
Delta: 0.000728011564713001 	  Loss: 1.660164986766245 	 Accuracy: 0.27509778357235987
Delta: 1.9779644677199687e-05 	  Loss: 1.6601364599669393 	 Accuracy: 0.2737940026075619
Delta: 0.0026231154626567494 	  Loss: 1.6603066602697898 	 Accuracy: 0.27509778357235987
Delta: 0.0013567842731544955 	  Loss: 1.660341052828917 	 Accuracy: 0.27640156453715775
Delta: 0.0013010061200332463 	  Loss: 1.660221868235988 	 Accuracy: 0.27640156453715775
Delta: 0.00300919557742402 	  Loss: 1.66017608368603 	 Accuracy: 0.27640156453715775
Delta: 0.001850074883570724 	  Loss: 1.6604466873816812 	 Accuracy: 0.27640156453715775
Delta: 0.003335068942505984 	  Loss: 1.660291072980729 	 Accuracy: 0.27640156453715775
Delta: 0.0013503007416511257 	  Loss: 1.6601711512049164 	 Accuracy: 0.2790091264667536
Delta: 0.0026054620845203436 	  Loss: 1.6594015672279607 	 Accuracy: 0.27640156453715775
Delta: 0.0029293463782384555 	  Loss: 1.6586190326384798 	 Accuracy: 0.27509778357235987
Delta: 0.0014773655618830308 	  Loss: 1.6594092029059182 	 Accuracy: 0.27640156453715775
Delta: 0.0024192213271934243 	  Loss: 1.6588135125792483 	 Accuracy: 0.27640156453715775
Delta: 0.0005961945725228979 	  Loss: 1.6591491129438802 	 Accuracy: 0.27640156453715775
Delta: 0.0022733244410941297 	  Loss: 1.6590952789457651 	 Accuracy: 0.2803129074315515
Delta: 0.0035471247761121112 	  Loss: 1.6575612487613058 	 Accuracy: 0.27509778357235987
Delta: 0.0048740939146260966 	  Loss: 1.6581540817352398 	 Accuracy: 0.27640156453715775
Delta: 0.00256919741775573 	  Loss: 1.6580966236008579 	 Accuracy: 0.27509778357235987
Delta: 0.0021350747825707632 	  Loss: 1.6581439706899055 	 Accuracy: 0.27509778357235987
Delta: 7.221632293774312e-05 	  Loss: 1.6579718327462758 	 Accuracy: 0.2737940026075619
Delta: 0.003830783032832083 	  Loss: 1.6576068322500457 	 Accuracy: 0.27509778357235987
Delta: 0.0028799413845860752 	  Loss: 1.6579325836009542 	 Accuracy: 0.27509778357235987
Delta: 0.0029246485516946467 	  Loss: 1.6570179755915242 	 Accuracy: 0.2737940026075619
Delta: 0.00259690402673434 	  Loss: 1.6563520389815807 	 Accuracy: 0.2737940026075619
Delta: 0.002282957602402486 	  Loss: 1.6563274975355045 	 Accuracy: 0.2737940026075619
Delta: 0.0007753765699888708 	  Loss: 1.656241387581034 	 Accuracy: 0.27509778357235987
Delta: 5.8486592027365644e-05 	  Loss: 1.6562825679668274 	 Accuracy: 0.2737940026075619
Delta: 0.0032355744162680016 	  Loss: 1.6560008343075634 	 Accuracy: 0.2737940026075619
Delta: 0.0029300747126181216 	  Loss: 1.6556695546621958 	 Accuracy: 0.2737940026075619
Delta: 0.0031985390778981465 	  Loss: 1.6560900154331852 	 Accuracy: 0.2737940026075619
Delta: 0.003191890159371472 	  Loss: 1.6562226025962288 	 Accuracy: 0.27249022164276404
Delta: 0.0038990743590593697 	  Loss: 1.6566136431508096 	 Accuracy: 0.2737940026075619
Delta: 0.001571937249317988 	  Loss: 1.6566376774404739 	 Accuracy: 0.27509778357235987
Delta: 0.0029215736450237152 	  Loss: 1.6562647088854243 	 Accuracy: 0.27509778357235987
Delta: 0.0018072990924426207 	  Loss: 1.6563124980427455 	 Accuracy: 0.2737940026075619
Delta: 0.0005536174174185358 	  Loss: 1.6563898007473554 	 Accuracy: 0.27249022164276404
Delta: 0.0005877298399981791 	  Loss: 1.6569226275036768 	 Accuracy: 0.2737940026075619
Delta: 0.0024651345768709025 	  Loss: 1.6568279994864519 	 Accuracy: 0.2737940026075619
Delta: 0.0011070446817354222 	  Loss: 1.6564440708551316 	 Accuracy: 0.2685788787483703
Delta: 0.0018654318044608823 	  Loss: 1.6560960880194098 	 Accuracy: 0.258148631029987
Delta: 0.002763764433679847 	  Loss: 1.656373913451735 	 Accuracy: 0.2737940026075619
Delta: 0.001661941747241798 	  Loss: 1.6560631847558822 	 Accuracy: 0.2737940026075619
Delta: 0.002518276913543302 	  Loss: 1.6561500887891014 	 Accuracy: 0.2737940026075619
Delta: 0.0007739350926448983 	  Loss: 1.6566036287695294 	 Accuracy: 0.2737940026075619
Delta: 5.928587679331818e-06 	  Loss: 1.6566098749655027 	 Accuracy: 0.2737940026075619
Delta: 7.2650717193437e-05 	  Loss: 1.6564016705760687 	 Accuracy: 0.27249022164276404
Delta: 0.0014033577807843148 	  Loss: 1.6559302600481158 	 Accuracy: 0.2711864406779661
Delta: 0.0036757078378814884 	  Loss: 1.6558467022940255 	 Accuracy: 0.2737940026075619
Delta: 0.0026497785262943447 	  Loss: 1.6564373615508545 	 Accuracy: 0.2737940026075619
Delta: 7.838014669323817e-05 	  Loss: 1.656615550115323 	 Accuracy: 0.2737940026075619
Delta: 3.997401062286628e-05 	  Loss: 1.656528321906203 	 Accuracy: 0.2737940026075619
Delta: 0.001496647737695723 	  Loss: 1.6568941721968997 	 Accuracy: 0.26988265971316816
Delta: 0.003259959058929143 	  Loss: 1.6561314819042214 	 Accuracy: 0.2737940026075619
Delta: 0.0020713582207075743 	  Loss: 1.6559134478858373 	 Accuracy: 0.2737940026075619
Delta: 0.0023969944531183757 	  Loss: 1.655975593653403 	 Accuracy: 0.27640156453715775
Delta: 0.00508697972317439 	  Loss: 1.6565925079485901 	 Accuracy: 0.2737940026075619
Delta: 0.0036573666665119077 	  Loss: 1.6563802014886397 	 Accuracy: 0.27640156453715775
Delta: 0.0023076344763132755 	  Loss: 1.6568085270633657 	 Accuracy: 0.27640156453715775
Delta: 0.0032209619544306275 	  Loss: 1.6564118857601382 	 Accuracy: 0.2737940026075619
Delta: 0.0034544526089180013 	  Loss: 1.656760551467068 	 Accuracy: 0.2777053455019557
Delta: 0.0042911861668136885 	  Loss: 1.6574488414166422 	 Accuracy: 0.27509778357235987
Delta: 0.0036822925173053632 	  Loss: 1.6570993792270832 	 Accuracy: 0.27249022164276404
Delta: 0.005111485781310636 	  Loss: 1.6557929604282438 	 Accuracy: 0.2737940026075619
Delta: 0.003328296215132243 	  Loss: 1.6561496333853993 	 Accuracy: 0.27640156453715775
Delta: 0.005403238840033092 	  Loss: 1.655353648298925 	 Accuracy: 0.27640156453715775
Delta: 0.0022279766395394097 	  Loss: 1.6551685045743316 	 Accuracy: 0.27640156453715775
Delta: 0.0015171966853739411 	  Loss: 1.6551226673264212 	 Accuracy: 0.27509778357235987
Delta: 0.004687227920200901 	  Loss: 1.6546437747207456 	 Accuracy: 0.27509778357235987
Delta: 0.0005184095530198326 	  Loss: 1.6546014503331927 	 Accuracy: 0.2646675358539765
Delta: 0.003966694477725155 	  Loss: 1.6542688129403258 	 Accuracy: 0.27640156453715775
Delta: 0.004087159270969584 	  Loss: 1.6540745293433754 	 Accuracy: 0.27509778357235987
Delta: 3.291004047166597e-05 	  Loss: 1.6540046215836681 	 Accuracy: 0.27640156453715775
Delta: 0.0018760641044596803 	  Loss: 1.6540987881636466 	 Accuracy: 0.2685788787483703
Delta: 0.0027344982134461515 	  Loss: 1.6539675534472589 	 Accuracy: 0.2737940026075619
Delta: 0.0038701047813763283 	  Loss: 1.6539159157617147 	 Accuracy: 0.2711864406779661
Delta: 0.003127564019810827 	  Loss: 1.6534068779432436 	 Accuracy: 0.27509778357235987
Delta: 0.0024474731923763383 	  Loss: 1.6533337169345703 	 Accuracy: 0.27640156453715775
Delta: 0.002644537474025753 	  Loss: 1.653463815616945 	 Accuracy: 0.27509778357235987
Delta: 0.002650301537836918 	  Loss: 1.6538953083162813 	 Accuracy: 0.27640156453715775
Delta: 0.0024565229432695563 	  Loss: 1.6533574235734856 	 Accuracy: 0.2711864406779661
Delta: 0.004529541568414472 	  Loss: 1.6531699687989239 	 Accuracy: 0.27640156453715775
Delta: 0.003935076348999792 	  Loss: 1.6526848206433036 	 Accuracy: 0.2803129074315515
Delta: 0.004327996563959117 	  Loss: 1.6526510121004871 	 Accuracy: 0.27640156453715775
Delta: 0.004516104017183293 	  Loss: 1.6534359267120944 	 Accuracy: 0.2777053455019557
Delta: 0.005601969245760781 	  Loss: 1.653714845748004 	 Accuracy: 0.27640156453715775
Delta: 0.0037101639502425243 	  Loss: 1.653613453493123 	 Accuracy: 0.27640156453715775
Delta: 0.021008130018795593 	  Loss: 2.1529470656395504 	 Accuracy: 0.196870925684485
Delta: 0.019093329206070365 	  Loss: 2.0435828893049792 	 Accuracy: 0.22294654498044328
Delta: 0.018362126750924176 	  Loss: 1.8550101333153044 	 Accuracy: 0.2333767926988266
Delta: 0.016281983399306577 	  Loss: 1.720217606222478 	 Accuracy: 0.2320730117340287
Delta: 0.012664696529142476 	  Loss: 1.6801802410162916 	 Accuracy: 0.23076923076923078

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0100861292076023 	  Loss: 1.6716416932961289 	 Accuracy: 0.2242503259452412
Delta: 0.007375544946531198 	  Loss: 1.6709648841395126 	 Accuracy: 0.2242503259452412
Delta: 0.006144103097537529 	  Loss: 1.6694773442993425 	 Accuracy: 0.2242503259452412
Delta: 0.0032745842194795874 	  Loss: 1.6695049082243743 	 Accuracy: 0.2242503259452412
Delta: 0.001328091170927566 	  Loss: 1.6694924666724558 	 Accuracy: 0.2242503259452412
Delta: 0.0034166663631366354 	  Loss: 1.668916408752434 	 Accuracy: 0.22294654498044328
Delta: 0.0023929682621612477 	  Loss: 1.6693970899184098 	 Accuracy: 0.22294654498044328
Delta: 0.0022831996450010917 	  Loss: 1.6687994397667085 	 Accuracy: 0.2242503259452412
Delta: 0.00398999546154066 	  Loss: 1.6682752981126563 	 Accuracy: 0.2242503259452412
Delta: 0.0035198999698922047 	  Loss: 1.6674536614008637 	 Accuracy: 0.22294654498044328
Delta: 0.0018289191609288929 	  Loss: 1.6673450074989098 	 Accuracy: 0.22294654498044328
Delta: 0.0006990934408535757 	  Loss: 1.6677221580550725 	 Accuracy: 0.22294654498044328
Delta: 0.000712374946248798 	  Loss: 1.6677232365012817 	 Accuracy: 0.22294654498044328
Delta: 0.002157861266159395 	  Loss: 1.6675386522131732 	 Accuracy: 0.2242503259452412
Delta: 9.6810681685029e-05 	  Loss: 1.6678286313727084 	 Accuracy: 0.2242503259452412
Delta: 0.0026267491148812593 	  Loss: 1.667600787769007 	 Accuracy: 0.2242503259452412
Delta: 0.0035755907117566025 	  Loss: 1.6675243250449454 	 Accuracy: 0.2242503259452412
Delta: 0.001975865312513342 	  Loss: 1.6672699837132638 	 Accuracy: 0.2242503259452412
Delta: 0.002688909814718252 	  Loss: 1.6677024760270498 	 Accuracy: 0.22685788787483702
Delta: 0.002557736002309114 	  Loss: 1.6674823430415295 	 Accuracy: 0.2255541069100391
Delta: 0.0023789540320417074 	  Loss: 1.6672213650918484 	 Accuracy: 0.2255541069100391
Delta: 0.0009592213357172434 	  Loss: 1.6672679724721782 	 Accuracy: 0.2255541069100391
Delta: 0.001996710200179939 	  Loss: 1.6674582804201883 	 Accuracy: 0.2320730117340287
Delta: 0.0018011886373504272 	  Loss: 1.667786766027218 	 Accuracy: 0.2255541069100391
Delta: 8.182396375332136e-05 	  Loss: 1.6676504021740728 	 Accuracy: 0.2255541069100391
Delta: 0.0010123168663973491 	  Loss: 1.6670132435457408 	 Accuracy: 0.2255541069100391
Delta: 0.002204114269882066 	  Loss: 1.6671962826161013 	 Accuracy: 0.2242503259452412
Delta: 7.057692460309975e-05 	  Loss: 1.6672009867000601 	 Accuracy: 0.2255541069100391
Delta: 4.3212093214220006e-05 	  Loss: 1.6671884430097434 	 Accuracy: 0.22816166883963493
Delta: 0.0009439183973041778 	  Loss: 1.6672538873443163 	 Accuracy: 0.2255541069100391
Delta: 3.1826408543278577e-05 	  Loss: 1.6672581369245763 	 Accuracy: 0.22685788787483702
Delta: 0.0033561982111393746 	  Loss: 1.667145723586895 	 Accuracy: 0.2255541069100391
Delta: 0.0022679930891340476 	  Loss: 1.667372676866184 	 Accuracy: 0.2242503259452412
Delta: 0.0007209501106450639 	  Loss: 1.6674038800748923 	 Accuracy: 0.2255541069100391
Delta: 5.489178679863247e-05 	  Loss: 1.6671927243485802 	 Accuracy: 0.2242503259452412
Delta: 7.470826363083356e-05 	  Loss: 1.666916294867749 	 Accuracy: 0.22294654498044328
Delta: 0.0019791012457827583 	  Loss: 1.6664738187550214 	 Accuracy: 0.22294654498044328
Delta: 0.0012103119860659224 	  Loss: 1.6667144610763343 	 Accuracy: 0.22946544980443284
Delta: 5.3856264686255126e-05 	  Loss: 1.6668656691862316 	 Accuracy: 0.2242503259452412
Delta: 0.002071802345788906 	  Loss: 1.6666983235886739 	 Accuracy: 0.2255541069100391
Delta: 0.003555139183801484 	  Loss: 1.666777379731187 	 Accuracy: 0.2242503259452412
Delta: 0.002000173924933471 	  Loss: 1.666698726917137 	 Accuracy: 0.2255541069100391
Delta: 9.316344741525747e-05 	  Loss: 1.6666105606569026 	 Accuracy: 0.2255541069100391
Delta: 0.002294243153078434 	  Loss: 1.6668423625488853 	 Accuracy: 0.22685788787483702
Delta: 0.003890933307160682 	  Loss: 1.667116859907729 	 Accuracy: 0.22294654498044328
Delta: 0.0031529012827691293 	  Loss: 1.6667598363481038 	 Accuracy: 0.2255541069100391
Delta: 0.003469478016325623 	  Loss: 1.666224166887566 	 Accuracy: 0.2255541069100391
Delta: 0.0008105556278715831 	  Loss: 1.6659317113400747 	 Accuracy: 0.2255541069100391
Delta: 2.924916467618544e-05 	  Loss: 1.6660343572980776 	 Accuracy: 0.2255541069100391
Delta: 0.0025594557684281622 	  Loss: 1.6661942357395807 	 Accuracy: 0.2255541069100391
Delta: 0.0023657370749760463 	  Loss: 1.6660375008610453 	 Accuracy: 0.22294654498044328
Delta: 0.0035840190553454872 	  Loss: 1.6662074902279653 	 Accuracy: 0.2255541069100391
Delta: 0.0005412286772482513 	  Loss: 1.6660780150829495 	 Accuracy: 0.22946544980443284
Delta: 0.00343715344266362 	  Loss: 1.6667157949571987 	 Accuracy: 0.2255541069100391
Delta: 0.0025516664212062003 	  Loss: 1.6666700655317723 	 Accuracy: 0.2255541069100391
Delta: 5.295015476507157e-05 	  Loss: 1.6665646236833205 	 Accuracy: 0.2242503259452412
Delta: 0.000931984505057535 	  Loss: 1.6667436919479641 	 Accuracy: 0.2255541069100391
Delta: 0.0025717336678399974 	  Loss: 1.6659820163511116 	 Accuracy: 0.2255541069100391
Delta: 7.8560515753367e-06 	  Loss: 1.665982065652738 	 Accuracy: 0.22685788787483702
converged at iter  63
Delta: 0.020991310856293122 	  Loss: 2.154022408751895 	 Accuracy: 0.19035202086049544
Delta: 0.019439806923784313 	  Loss: 2.0369667740193904 	 Accuracy: 0.47196870925684486
Delta: 0.019173193021711395 	  Loss: 1.7810012779842408 	 Accuracy: 0.5632333767926988
Delta: 0.016306350663055497 	  Loss: 1.6097285024806638 	 Accuracy: 0.5358539765319427
Delta: 0.012146599115162037 	  Loss: 1.5732340693792373 	 Accuracy: 0.5280312907431551

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008713518702188928 	  Loss: 1.5652011863663247 	 Accuracy: 0.5332464146023468
Delta: 0.005977413748571501 	  Loss: 1.5633026737171296 	 Accuracy: 0.5319426336375489
Delta: 0.004350654569717394 	  Loss: 1.5633778665374742 	 Accuracy: 0.5332464146023468
Delta: 0.004691691997851525 	  Loss: 1.5636542626795191 	 Accuracy: 0.5332464146023468
Delta: 0.0026184845612440047 	  Loss: 1.563656670767829 	 Accuracy: 0.5332464146023468
Delta: 0.0022128718215657954 	  Loss: 1.5635338704373418 	 Accuracy: 0.530638852672751
Delta: 0.0023354800539701283 	  Loss: 1.5636221317397403 	 Accuracy: 0.530638852672751
Delta: 0.0025690122094182764 	  Loss: 1.5636634867618526 	 Accuracy: 0.530638852672751
Delta: 0.0032897488246858464 	  Loss: 1.5636158263484825 	 Accuracy: 0.5371577574967406
Delta: 0.002916639528552033 	  Loss: 1.5642077472691494 	 Accuracy: 0.5319426336375489
Delta: 4.558150987242519e-05 	  Loss: 1.5640219343881459 	 Accuracy: 0.530638852672751
Delta: 0.0010849282050169812 	  Loss: 1.5638662268477446 	 Accuracy: 0.530638852672751
Delta: 0.0016858862387202009 	  Loss: 1.5638795414851792 	 Accuracy: 0.5319426336375489
Delta: 0.0007546645997845407 	  Loss: 1.5638010679463878 	 Accuracy: 0.5280312907431551
Delta: 0.0010602055745199252 	  Loss: 1.5639079082639524 	 Accuracy: 0.5280312907431551
Delta: 0.0029540960345988457 	  Loss: 1.5636073240612123 	 Accuracy: 0.530638852672751
Delta: 0.0038944156615240864 	  Loss: 1.5637500394417811 	 Accuracy: 0.529335071707953
Delta: 0.003450362644291527 	  Loss: 1.5636120729751228 	 Accuracy: 0.530638852672751
Delta: 0.000678006868436499 	  Loss: 1.5635848500382785 	 Accuracy: 0.529335071707953
Delta: 0.0006853824093784445 	  Loss: 1.5638444511708027 	 Accuracy: 0.529335071707953
Delta: 1.2468335002215983e-06 	  Loss: 1.5638423623168363 	 Accuracy: 0.529335071707953
Delta: 0.004394607201352309 	  Loss: 1.5636917135440287 	 Accuracy: 0.530638852672751
Delta: 0.004774810945831767 	  Loss: 1.5638914037038734 	 Accuracy: 0.529335071707953
Delta: 0.0011916611688917759 	  Loss: 1.5638058692055878 	 Accuracy: 0.5267275097783573
Delta: 0.0029039123474262404 	  Loss: 1.5638577029101626 	 Accuracy: 0.5384615384615384
Delta: 0.005481841245935429 	  Loss: 1.5637945900886443 	 Accuracy: 0.5332464146023468
Delta: 0.0033364038345566416 	  Loss: 1.563486649225306 	 Accuracy: 0.5345501955671447
Delta: 0.0019037233425734188 	  Loss: 1.5634943202481224 	 Accuracy: 0.5332464146023468
Delta: 4.991568821633811e-05 	  Loss: 1.5633492763026227 	 Accuracy: 0.5345501955671447
Delta: 4.7730987903096586e-05 	  Loss: 1.5635116907962603 	 Accuracy: 0.5332464146023468
Delta: 0.005856605865197322 	  Loss: 1.5627445743293817 	 Accuracy: 0.5371577574967406
Delta: 0.0033489141085945536 	  Loss: 1.5628313812987618 	 Accuracy: 0.530638852672751
Delta: 0.0041640289346909914 	  Loss: 1.5620573994481506 	 Accuracy: 0.5280312907431551
Delta: 0.0037101600131451023 	  Loss: 1.562430573500005 	 Accuracy: 0.5332464146023468
Delta: 0.0036654142872706162 	  Loss: 1.5632597278625493 	 Accuracy: 0.5358539765319427
Delta: 0.002296517528079596 	  Loss: 1.5626414723595146 	 Accuracy: 0.5319426336375489
Delta: 0.002763804780115244 	  Loss: 1.5631920273359214 	 Accuracy: 0.5332464146023468
Delta: 0.000560238977986848 	  Loss: 1.5631574831260733 	 Accuracy: 0.5319426336375489
Delta: 0.0007645947055765563 	  Loss: 1.56299181070733 	 Accuracy: 0.530638852672751
Delta: 0.00324718050032775 	  Loss: 1.5627020559511933 	 Accuracy: 0.530638852672751
Delta: 0.002142060803587975 	  Loss: 1.5629648850259124 	 Accuracy: 0.529335071707953
Delta: 0.003936750642611855 	  Loss: 1.5620603943502263 	 Accuracy: 0.530638852672751
Delta: 0.001580328586333801 	  Loss: 1.5621196654805738 	 Accuracy: 0.530638852672751
Delta: 3.7669354759372304e-06 	  Loss: 1.5621281787817625 	 Accuracy: 0.5319426336375489
Delta: 0.003245255462128081 	  Loss: 1.5631009228084647 	 Accuracy: 0.5371577574967406
Delta: 0.002222048840925117 	  Loss: 1.5635341104529985 	 Accuracy: 0.5332464146023468
Delta: 0.00218924940487935 	  Loss: 1.563142678060302 	 Accuracy: 0.5332464146023468
Delta: 0.0016332388242748892 	  Loss: 1.5623865084631405 	 Accuracy: 0.5254237288135594
Delta: 0.001843112397822292 	  Loss: 1.5634853051750275 	 Accuracy: 0.5280312907431551
Delta: 0.0037921334279965493 	  Loss: 1.56385597391136 	 Accuracy: 0.5319426336375489
Delta: 0.0019565609864505076 	  Loss: 1.5639949611290485 	 Accuracy: 0.530638852672751
Delta: 0.0015533449425342526 	  Loss: 1.5640444456227272 	 Accuracy: 0.5319426336375489
Delta: 0.003182552571720442 	  Loss: 1.5638148404741243 	 Accuracy: 0.530638852672751
Delta: 0.0027376155747350387 	  Loss: 1.5636614185338176 	 Accuracy: 0.530638852672751
Delta: 0.0013096377501337407 	  Loss: 1.5636022409765293 	 Accuracy: 0.530638852672751
Delta: 0.0028944103736151237 	  Loss: 1.563594896796539 	 Accuracy: 0.529335071707953
Delta: 0.0013851851460455072 	  Loss: 1.5635360355412276 	 Accuracy: 0.5345501955671447
Delta: 0.003509760030127533 	  Loss: 1.5633794601899 	 Accuracy: 0.5332464146023468
Delta: 0.0027463385511685384 	  Loss: 1.5626692300087703 	 Accuracy: 0.5332464146023468
Delta: 0.002530110575249086 	  Loss: 1.563306183702162 	 Accuracy: 0.529335071707953
Delta: 0.0027732674649545205 	  Loss: 1.5627684353322855 	 Accuracy: 0.5319426336375489
Delta: 0.0037292338090275092 	  Loss: 1.5620436374356574 	 Accuracy: 0.5345501955671447
Delta: 0.0015940838306367118 	  Loss: 1.5624976969397055 	 Accuracy: 0.5319426336375489
Delta: 0.003895955756781833 	  Loss: 1.5622222855104246 	 Accuracy: 0.5319426336375489
Delta: 0.0023236593865402938 	  Loss: 1.56189747625847 	 Accuracy: 0.5319426336375489
Delta: 2.0854338955205758e-05 	  Loss: 1.5618650089880717 	 Accuracy: 0.5345501955671447
Delta: 0.0038617980516420175 	  Loss: 1.5616265212567861 	 Accuracy: 0.5332464146023468
Delta: 0.0030351629171546375 	  Loss: 1.5618661534426117 	 Accuracy: 0.5319426336375489
Delta: 0.0015113373625854924 	  Loss: 1.5627740185518437 	 Accuracy: 0.5332464146023468
Delta: 0.0028453031967421187 	  Loss: 1.561579633151814 	 Accuracy: 0.5345501955671447
Delta: 0.003355667761715646 	  Loss: 1.5624407516825634 	 Accuracy: 0.5358539765319427
Delta: 0.0025126746051103996 	  Loss: 1.5619274342961285 	 Accuracy: 0.5345501955671447
Delta: 0.002017193314828848 	  Loss: 1.561810916960071 	 Accuracy: 0.5345501955671447
Delta: 0.002614251405688044 	  Loss: 1.5619650045647056 	 Accuracy: 0.5345501955671447
Delta: 0.0017563845318512106 	  Loss: 1.5618142232572485 	 Accuracy: 0.5345501955671447
Delta: 0.0004960413683550936 	  Loss: 1.561821665982455 	 Accuracy: 0.5358539765319427
Delta: 0.001862046540713442 	  Loss: 1.5618669283965283 	 Accuracy: 0.5358539765319427
Delta: 3.580647880979439e-05 	  Loss: 1.5618333530582036 	 Accuracy: 0.5345501955671447
Delta: 0.001460489335848194 	  Loss: 1.5625084357047427 	 Accuracy: 0.530638852672751
Delta: 0.002831604491362791 	  Loss: 1.5628352404982895 	 Accuracy: 0.5332464146023468
Delta: 1.002541813897712e-05 	  Loss: 1.5628123670780563 	 Accuracy: 0.5332464146023468
Delta: 1.2308687869986014e-05 	  Loss: 1.5628216887764785 	 Accuracy: 0.5332464146023468
Delta: 0.0013579355006715173 	  Loss: 1.562994495119133 	 Accuracy: 0.5319426336375489
Delta: 0.004045381786192275 	  Loss: 1.5634900211372085 	 Accuracy: 0.530638852672751
Delta: 0.003257188461616263 	  Loss: 1.5626479723143367 	 Accuracy: 0.5319426336375489
Delta: 4.495185524098355e-05 	  Loss: 1.5626969713981675 	 Accuracy: 0.5332464146023468
Delta: 0.0006300262688736593 	  Loss: 1.562832971595899 	 Accuracy: 0.530638852672751
Delta: 0.004228241826960821 	  Loss: 1.5632657019335876 	 Accuracy: 0.5358539765319427
Delta: 0.006275496826150355 	  Loss: 1.5627953096355918 	 Accuracy: 0.5371577574967406
Delta: 0.005623332370943363 	  Loss: 1.5621804479206776 	 Accuracy: 0.5371577574967406
Delta: 0.003451361289071033 	  Loss: 1.562475713377684 	 Accuracy: 0.5345501955671447
Delta: 0.001066657905177197 	  Loss: 1.5624224478755384 	 Accuracy: 0.5358539765319427
Delta: 0.0022752244083233536 	  Loss: 1.5624008790714592 	 Accuracy: 0.5358539765319427
Delta: 0.001624333649604096 	  Loss: 1.5624008224742603 	 Accuracy: 0.5397653194263363
converged at iter  98
Delta: 0.0209741891870422 	  Loss: 2.160109537536208 	 Accuracy: 0.16688396349413298
Delta: 0.018229435399571975 	  Loss: 2.09462584418329 	 Accuracy: 0.13298565840938723
Delta: 0.01591097044450234 	  Loss: 2.008511734066208 	 Accuracy: 0.11734028683181226
Delta: 0.015180008439184661 	  Loss: 1.908501100444705 	 Accuracy: 0.12385919165580182
Delta: 0.01343914145543608 	  Loss: 1.8118736004103841 	 Accuracy: 0.14993481095176012
Delta: 0.01159889549658555 	  Loss: 1.7388217916692572 	 Accuracy: 0.15254237288135594
Delta: 0.009923024942944687 	  Loss: 1.6878638403371409 	 Accuracy: 0.1395045632333768
Delta: 0.009373258073358494 	  Loss: 1.652295259351312 	 Accuracy: 0.1421121251629726
Delta: 0.007853575801316477 	  Loss: 1.6286160914900223 	 Accuracy: 0.1408083441981747
Delta: 0.0068190483177485856 	  Loss: 1.6124552752796109 	 Accuracy: 0.1303780964797914
Delta: 0.005979764373722896 	  Loss: 1.600577596114244 	 Accuracy: 0.13689700130378096
Delta: 0.005979378725466701 	  Loss: 1.5922462535072712 	 Accuracy: 0.13298565840938723
Delta: 0.005693630466584483 	  Loss: 1.585992335514407 	 Accuracy: 0.1303780964797914
Delta: 0.004171550725345502 	  Loss: 1.5811496969160053 	 Accuracy: 0.12777053455019557
Delta: 0.005368831650392637 	  Loss: 1.5771343957367339 	 Accuracy: 0.1316818774445893
Delta: 0.0038329943518859784 	  Loss: 1.573983462895561 	 Accuracy: 0.1290743155149935
Delta: 0.004112672477723582 	  Loss: 1.571702459239631 	 Accuracy: 0.1303780964797914
Delta: 0.0041537465412826175 	  Loss: 1.569693956054301 	 Accuracy: 0.12777053455019557
Delta: 0.004594569109848726 	  Loss: 1.568002375850312 	 Accuracy: 0.1290743155149935
Delta: 0.003340112935774713 	  Loss: 1.5664739608779878 	 Accuracy: 0.12255541069100391
Delta: 0.004994209199554222 	  Loss: 1.5652701990195488 	 Accuracy: 0.11994784876140809
Delta: 0.0029864870230604788 	  Loss: 1.5641543732763523 	 Accuracy: 0.12385919165580182
Delta: 0.003467922516897387 	  Loss: 1.5631314008771402 	 Accuracy: 0.12255541069100391
Delta: 0.0034115321661484037 	  Loss: 1.5624600568248976 	 Accuracy: 0.12385919165580182
Delta: 0.0026563034613360198 	  Loss: 1.5616498712353926 	 Accuracy: 0.121251629726206
Delta: 0.003362415417015613 	  Loss: 1.5611037736989473 	 Accuracy: 0.12777053455019557
Delta: 0.005047700930353956 	  Loss: 1.5602664318124828 	 Accuracy: 0.12646675358539766
Delta: 0.0034398843331706554 	  Loss: 1.5597182099119165 	 Accuracy: 0.12255541069100391
Delta: 0.0033935086404625024 	  Loss: 1.5592923747532714 	 Accuracy: 0.12385919165580182

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0015739053600004685 	  Loss: 1.5588241678429235 	 Accuracy: 0.12516297262059975
Delta: 0.003103251682493351 	  Loss: 1.5585432842486555 	 Accuracy: 0.12385919165580182
Delta: 0.0035502364299168946 	  Loss: 1.5581885413390428 	 Accuracy: 0.12385919165580182
Delta: 0.003186531088048189 	  Loss: 1.557837720048906 	 Accuracy: 0.11994784876140809
Delta: 0.004240345069229965 	  Loss: 1.557639625618907 	 Accuracy: 0.12516297262059975
Delta: 0.0026624987896480138 	  Loss: 1.557410749154546 	 Accuracy: 0.12516297262059975
Delta: 0.0033009057456379423 	  Loss: 1.5570978380232945 	 Accuracy: 0.12385919165580182
Delta: 0.004582691798705713 	  Loss: 1.5567840086867424 	 Accuracy: 0.12516297262059975
Delta: 0.004641678667748144 	  Loss: 1.5565429770377102 	 Accuracy: 0.12385919165580182
Delta: 0.003138580250017228 	  Loss: 1.55629601375554 	 Accuracy: 0.12255541069100391
Delta: 0.0024020769593300867 	  Loss: 1.5560577860404696 	 Accuracy: 0.12255541069100391
Delta: 0.002868933128705858 	  Loss: 1.5560410044747166 	 Accuracy: 0.11864406779661017
Delta: 0.0030670281235805437 	  Loss: 1.555758138430308 	 Accuracy: 0.11994784876140809
Delta: 0.0020879743165611417 	  Loss: 1.5556467920208361 	 Accuracy: 0.11734028683181226
Delta: 0.0036942056064719194 	  Loss: 1.5554573149640283 	 Accuracy: 0.11342894393741851
Delta: 0.003214717168375379 	  Loss: 1.5552063283027282 	 Accuracy: 0.11864406779661017
Delta: 0.0037725525441109037 	  Loss: 1.5550131295311136 	 Accuracy: 0.121251629726206
Delta: 0.001822531264813187 	  Loss: 1.5549299938729892 	 Accuracy: 0.11864406779661017
Delta: 0.004680731154365927 	  Loss: 1.5547596030897113 	 Accuracy: 0.11864406779661017
Delta: 0.0020554406917756393 	  Loss: 1.554605300020962 	 Accuracy: 0.11994784876140809
Delta: 0.002736449807440469 	  Loss: 1.5544302143393574 	 Accuracy: 0.11473272490221642
Delta: 0.0025327472473781155 	  Loss: 1.554326114422235 	 Accuracy: 0.11864406779661017
Delta: 0.004120977638919946 	  Loss: 1.5542916624796312 	 Accuracy: 0.11734028683181226
Delta: 0.0007291805271747603 	  Loss: 1.5541419696457863 	 Accuracy: 0.11734028683181226
Delta: 0.0015166547071555332 	  Loss: 1.554001043944047 	 Accuracy: 0.11734028683181226
Delta: 0.0018231986720381587 	  Loss: 1.5540316412990287 	 Accuracy: 0.11473272490221642
Delta: 0.0029329467864244057 	  Loss: 1.5539170435229426 	 Accuracy: 0.11864406779661017
Delta: 0.0026116849636872623 	  Loss: 1.553834620920872 	 Accuracy: 0.1121251629726206
Delta: 0.0015506859438598668 	  Loss: 1.5537764126635811 	 Accuracy: 0.11473272490221642
Delta: 0.002533490382836779 	  Loss: 1.5538019141516135 	 Accuracy: 0.11342894393741851
Delta: 0.0009758721271676604 	  Loss: 1.5537299810896874 	 Accuracy: 0.11342894393741851
Delta: 0.0010095207261183058 	  Loss: 1.5537041508110958 	 Accuracy: 0.11603650586701435
Delta: 0.00348335137143269 	  Loss: 1.5537031491619826 	 Accuracy: 0.11473272490221642
Delta: 0.0024775174777090826 	  Loss: 1.5536705157633568 	 Accuracy: 0.11473272490221642
Delta: 0.0022006953160601645 	  Loss: 1.5536183252788351 	 Accuracy: 0.11342894393741851
Delta: 0.0012641341741838792 	  Loss: 1.5535801356480556 	 Accuracy: 0.11473272490221642
Delta: 0.0026994073062031726 	  Loss: 1.5534217051648893 	 Accuracy: 0.11473272490221642
Delta: 0.0033602768159966163 	  Loss: 1.5533120705766321 	 Accuracy: 0.11473272490221642
Delta: 0.003809807137765139 	  Loss: 1.5532436581753841 	 Accuracy: 0.11473272490221642
Delta: 0.0030359112304333543 	  Loss: 1.5531782842470971 	 Accuracy: 0.11342894393741851
Delta: 0.0030065130857326915 	  Loss: 1.5530985842005236 	 Accuracy: 0.11473272490221642
Delta: 0.0008227254818639202 	  Loss: 1.5530568498491286 	 Accuracy: 0.11342894393741851
Delta: 0.0031658214915585986 	  Loss: 1.5530007234270995 	 Accuracy: 0.11603650586701435
Delta: 0.001502530290480809 	  Loss: 1.5529669895280618 	 Accuracy: 0.11603650586701435
Delta: 0.0008872417312106616 	  Loss: 1.5529321970590395 	 Accuracy: 0.11473272490221642
Delta: 0.001132301829461598 	  Loss: 1.5528974537267228 	 Accuracy: 0.11473272490221642
Delta: 0.000517951958391179 	  Loss: 1.5528346994296602 	 Accuracy: 0.11342894393741851
Delta: 0.0016404853050965146 	  Loss: 1.5527783204364283 	 Accuracy: 0.11473272490221642
Delta: 0.0023187705680909475 	  Loss: 1.5527490271523374 	 Accuracy: 0.11342894393741851
Delta: 0.0024265243881602685 	  Loss: 1.5527651979423926 	 Accuracy: 0.11342894393741851
Delta: 0.0005252145192996188 	  Loss: 1.5527258145704095 	 Accuracy: 0.11342894393741851
Delta: 0.0023837535151250066 	  Loss: 1.5526990326681926 	 Accuracy: 0.11342894393741851
Delta: 0.0009440700693881453 	  Loss: 1.5526522172228636 	 Accuracy: 0.11342894393741851
Delta: 0.0024670098380925034 	  Loss: 1.552591886895397 	 Accuracy: 0.11342894393741851
Delta: 0.0021062272730141725 	  Loss: 1.5525093756118158 	 Accuracy: 0.11342894393741851
Delta: 0.0021493744776815847 	  Loss: 1.5524610298890127 	 Accuracy: 0.11342894393741851
Delta: 0.0010193474399377907 	  Loss: 1.5524267875096025 	 Accuracy: 0.11342894393741851
Delta: 0.0023599915125887888 	  Loss: 1.5524457154848583 	 Accuracy: 0.11342894393741851
Delta: 0.0034653637029696013 	  Loss: 1.552387848686168 	 Accuracy: 0.11342894393741851
Delta: 0.0022432960730923556 	  Loss: 1.5523427994980952 	 Accuracy: 0.11342894393741851
Delta: 0.0024785020768831843 	  Loss: 1.5523226278782034 	 Accuracy: 0.11342894393741851
Delta: 0.0022037450575953625 	  Loss: 1.5522709651380742 	 Accuracy: 0.11342894393741851
Delta: 0.003259477402977835 	  Loss: 1.5521293969155234 	 Accuracy: 0.11342894393741851
Delta: 0.0012309483812673557 	  Loss: 1.5521013025456423 	 Accuracy: 0.11342894393741851
Delta: 0.0013701592944038372 	  Loss: 1.552048725844047 	 Accuracy: 0.11342894393741851
Delta: 0.002063218697752819 	  Loss: 1.5519913259130187 	 Accuracy: 0.11342894393741851
Delta: 0.0023747391524540926 	  Loss: 1.5519658510053187 	 Accuracy: 0.11342894393741851
Delta: 0.0006263018035668818 	  Loss: 1.551924706580333 	 Accuracy: 0.11342894393741851
Delta: 0.0016284047865581961 	  Loss: 1.5518881781415368 	 Accuracy: 0.1121251629726206
Delta: 0.0036311832810045942 	  Loss: 1.551840133659935 	 Accuracy: 0.11342894393741851
Delta: 0.0018788415002123483 	  Loss: 1.5518201258311723 	 Accuracy: 0.11342894393741851
Delta: 0.02096008861248011 	  Loss: 2.160097178209474 	 Accuracy: 0.16688396349413298
Delta: 0.018374069478970564 	  Loss: 2.0901535054323834 	 Accuracy: 0.15514993481095177
Delta: 0.016097642921842664 	  Loss: 1.9955329750486897 	 Accuracy: 0.12777053455019557
Delta: 0.01529843872181779 	  Loss: 1.8903835357906544 	 Accuracy: 0.11994784876140809
Delta: 0.013984636436067642 	  Loss: 1.7872787331947217 	 Accuracy: 0.11864406779661017
Delta: 0.012013556921897716 	  Loss: 1.7070866443009705 	 Accuracy: 0.10430247718383312
Delta: 0.010072497740010709 	  Loss: 1.6549014355442475 	 Accuracy: 0.1121251629726206
Delta: 0.009123179238543768 	  Loss: 1.6225759105488327 	 Accuracy: 0.11603650586701435
Delta: 0.007539089282323071 	  Loss: 1.602359010547838 	 Accuracy: 0.11473272490221642
Delta: 0.00722382493873726 	  Loss: 1.5896758565433804 	 Accuracy: 0.11473272490221642
Delta: 0.006782159272490394 	  Loss: 1.5810259914867313 	 Accuracy: 0.1121251629726206
Delta: 0.005957539680532447 	  Loss: 1.5741317361578666 	 Accuracy: 0.11603650586701435
Delta: 0.005393608382902072 	  Loss: 1.5700778917760219 	 Accuracy: 0.11473272490221642
Delta: 0.006151129237627374 	  Loss: 1.5663327711971253 	 Accuracy: 0.121251629726206
Delta: 0.005857466484199816 	  Loss: 1.5636511065142495 	 Accuracy: 0.10560625814863103
Delta: 0.004281141912464171 	  Loss: 1.5616721389346822 	 Accuracy: 0.11473272490221642

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005613513527984126 	  Loss: 1.560127364004488 	 Accuracy: 0.11603650586701435
Delta: 0.004361643540433092 	  Loss: 1.5588750279117594 	 Accuracy: 0.11864406779661017
Delta: 0.004489438120543802 	  Loss: 1.5579207146507301 	 Accuracy: 0.11734028683181226
Delta: 0.004230830266114114 	  Loss: 1.5569543024239578 	 Accuracy: 0.11473272490221642
Delta: 0.003974366323829318 	  Loss: 1.5562853965702905 	 Accuracy: 0.11734028683181226
Delta: 0.004485897218896265 	  Loss: 1.5555044172464187 	 Accuracy: 0.11473272490221642
Delta: 0.0043705472240215 	  Loss: 1.554957741526544 	 Accuracy: 0.11864406779661017
Delta: 0.003997337177767651 	  Loss: 1.5545796831196765 	 Accuracy: 0.11603650586701435
Delta: 0.0036912340565627335 	  Loss: 1.5543397894941835 	 Accuracy: 0.11734028683181226
Delta: 0.004404206063030972 	  Loss: 1.553892290760687 	 Accuracy: 0.11473272490221642
Delta: 0.004219161278193186 	  Loss: 1.553490191051709 	 Accuracy: 0.11734028683181226
Delta: 0.003429758717955005 	  Loss: 1.55334928928002 	 Accuracy: 0.11734028683181226
Delta: 0.002497627114118401 	  Loss: 1.5531882041930634 	 Accuracy: 0.11734028683181226
Delta: 0.003242997263193597 	  Loss: 1.5530895533685298 	 Accuracy: 0.11864406779661017
Delta: 0.002318665662358033 	  Loss: 1.5529715170160272 	 Accuracy: 0.11864406779661017
Delta: 0.004181487057268701 	  Loss: 1.5527443311701665 	 Accuracy: 0.11864406779661017
Delta: 0.0025396940273454648 	  Loss: 1.5526298459849133 	 Accuracy: 0.11734028683181226
Delta: 0.0018278860485048058 	  Loss: 1.552600540877626 	 Accuracy: 0.11864406779661017
Delta: 0.0020368251960981897 	  Loss: 1.5525245984745526 	 Accuracy: 0.11734028683181226
Delta: 0.001671887384178408 	  Loss: 1.5524421184535817 	 Accuracy: 0.11734028683181226
Delta: 0.0016555617836306554 	  Loss: 1.5524671988422045 	 Accuracy: 0.11734028683181226
Delta: 0.0008154062697285567 	  Loss: 1.5524388011276775 	 Accuracy: 0.11734028683181226
Delta: 3.2743610004828965e-05 	  Loss: 1.5524507384348347 	 Accuracy: 0.11734028683181226
Delta: 0.00278814640098218 	  Loss: 1.5524511750641592 	 Accuracy: 0.11864406779661017
Delta: 0.002088022903600226 	  Loss: 1.552268749890628 	 Accuracy: 0.11864406779661017
Delta: 0.0008384202337182675 	  Loss: 1.552358323880735 	 Accuracy: 0.11994784876140809
Delta: 0.0006588092804609184 	  Loss: 1.5524232217581866 	 Accuracy: 0.11994784876140809
Delta: 0.0023772484766209027 	  Loss: 1.5523464324367875 	 Accuracy: 0.11864406779661017
Delta: 0.0015394195226237813 	  Loss: 1.5523119011424558 	 Accuracy: 0.11994784876140809
Delta: 0.0005854519674839766 	  Loss: 1.552383061185735 	 Accuracy: 0.11994784876140809
Delta: 1.9863904523376436e-05 	  Loss: 1.552394668233888 	 Accuracy: 0.11994784876140809
Delta: 0.002257494783162137 	  Loss: 1.5523936360678903 	 Accuracy: 0.11994784876140809
Delta: 0.0005156247020323973 	  Loss: 1.5523931745366393 	 Accuracy: 0.11864406779661017
Delta: 5.442083745729698e-05 	  Loss: 1.552359590487589 	 Accuracy: 0.11734028683181226
Delta: 4.570384175225657e-05 	  Loss: 1.5523707300290686 	 Accuracy: 0.11994784876140809
Delta: 5.3105773831970745e-05 	  Loss: 1.5523662607711957 	 Accuracy: 0.11994784876140809
Delta: 0.0030961093415435045 	  Loss: 1.5523557306764477 	 Accuracy: 0.11864406779661017
Delta: 0.0006168285046211894 	  Loss: 1.5523516118716238 	 Accuracy: 0.11864406779661017
Delta: 0.0007102296267228565 	  Loss: 1.5523448708509753 	 Accuracy: 0.11864406779661017
Delta: 2.113120236525858e-05 	  Loss: 1.5523690886125905 	 Accuracy: 0.11864406779661017
Delta: 1.6864458840814522e-05 	  Loss: 1.552367780806973 	 Accuracy: 0.11994784876140809
Delta: 3.129273891704573e-05 	  Loss: 1.5524118544524415 	 Accuracy: 0.11994784876140809
Delta: 1.9475591954685643e-05 	  Loss: 1.5523890280321344 	 Accuracy: 0.11864406779661017
Delta: 6.121517579339887e-05 	  Loss: 1.552342417270089 	 Accuracy: 0.11864406779661017
Delta: 4.056674899176189e-05 	  Loss: 1.5523553841066695 	 Accuracy: 0.11864406779661017
Delta: 1.9815149230145665e-05 	  Loss: 1.5523611923598188 	 Accuracy: 0.11864406779661017
Delta: 1.3540039091938598e-05 	  Loss: 1.5523350143333232 	 Accuracy: 0.11864406779661017
Delta: 1.5454589991249637e-05 	  Loss: 1.552326255250609 	 Accuracy: 0.11864406779661017
Delta: 1.295774489410534e-05 	  Loss: 1.5523302578717906 	 Accuracy: 0.11864406779661017
Delta: 4.587358005442511e-06 	  Loss: 1.552345136006991 	 Accuracy: 0.11864406779661017
Delta: 3.5512710677514045e-05 	  Loss: 1.5523655064353967 	 Accuracy: 0.11864406779661017
Delta: 2.132958251706131e-05 	  Loss: 1.552361118687418 	 Accuracy: 0.11864406779661017
Delta: 0.001005505834612008 	  Loss: 1.5523648487435922 	 Accuracy: 0.11864406779661017
Delta: 3.35597483151265e-05 	  Loss: 1.5522956443576799 	 Accuracy: 0.11864406779661017
Delta: 4.5699500942823834e-05 	  Loss: 1.552283162492999 	 Accuracy: 0.11864406779661017
Delta: 0.001345472759131451 	  Loss: 1.5523163471026045 	 Accuracy: 0.11864406779661017
Delta: 0.0012381933708909272 	  Loss: 1.5523050340160411 	 Accuracy: 0.11864406779661017
Delta: 2.2341493328450825e-05 	  Loss: 1.552315741446763 	 Accuracy: 0.11864406779661017
Delta: 0.0017349640275703903 	  Loss: 1.5522739983740543 	 Accuracy: 0.11864406779661017
Delta: 4.00582806596056e-05 	  Loss: 1.5522794616056355 	 Accuracy: 0.11864406779661017
Delta: 0.0007344256247556045 	  Loss: 1.552286691675011 	 Accuracy: 0.11864406779661017
Delta: 9.856808480777111e-05 	  Loss: 1.5522965365688106 	 Accuracy: 0.11864406779661017
Delta: 0.0010149804596804605 	  Loss: 1.5524015059759724 	 Accuracy: 0.11864406779661017
Delta: 0.001753388789334653 	  Loss: 1.5522586753668026 	 Accuracy: 0.11864406779661017
Delta: 0.0023426732588956913 	  Loss: 1.5522735769045877 	 Accuracy: 0.11864406779661017
Delta: 0.0013573494290808963 	  Loss: 1.5523799371455476 	 Accuracy: 0.121251629726206
Delta: 0.0008375581129591547 	  Loss: 1.552342777146896 	 Accuracy: 0.11864406779661017
Delta: 0.001660241447679607 	  Loss: 1.5522185774163129 	 Accuracy: 0.11864406779661017
Delta: 0.0038805289138708903 	  Loss: 1.552028806276582 	 Accuracy: 0.11864406779661017
Delta: 0.00185358422044875 	  Loss: 1.5523453120244741 	 Accuracy: 0.121251629726206
Delta: 0.002866879005878991 	  Loss: 1.5523501396436168 	 Accuracy: 0.11734028683181226
Delta: 0.0010123278772066892 	  Loss: 1.552342466870584 	 Accuracy: 0.11603650586701435
Delta: 0.0010101428096791368 	  Loss: 1.5522553129515555 	 Accuracy: 0.11864406779661017
Delta: 0.0005010256897511798 	  Loss: 1.5522842008006599 	 Accuracy: 0.11864406779661017
Delta: 0.0008281380731840498 	  Loss: 1.5522457482863112 	 Accuracy: 0.11864406779661017
Delta: 0.00066399784341512 	  Loss: 1.5521943634987512 	 Accuracy: 0.11864406779661017
Delta: 6.733491796167896e-05 	  Loss: 1.5523200920788487 	 Accuracy: 0.11864406779661017
Delta: 5.95506460680872e-05 	  Loss: 1.5523018558943447 	 Accuracy: 0.11864406779661017
Delta: 0.001170519867178066 	  Loss: 1.5520885787060248 	 Accuracy: 0.11864406779661017
Delta: 0.0011464639230276943 	  Loss: 1.5522824641753257 	 Accuracy: 0.11864406779661017
Delta: 0.0015789080659861531 	  Loss: 1.55216798149244 	 Accuracy: 0.11864406779661017
Delta: 0.0014152093656161775 	  Loss: 1.5522808769952265 	 Accuracy: 0.11864406779661017
Delta: 0.0021535324814891473 	  Loss: 1.5522902734719908 	 Accuracy: 0.11864406779661017
Delta: 4.7107698316255496e-05 	  Loss: 1.5523240318304192 	 Accuracy: 0.11864406779661017
Delta: 0.0210834719473071 	  Loss: 2.1596517607204087 	 Accuracy: 0.1681877444589309
Delta: 0.01837644471753468 	  Loss: 2.0860745958834297 	 Accuracy: 0.12255541069100391
Delta: 0.016175504249147005 	  Loss: 1.9787720236001174 	 Accuracy: 0.1577574967405476
Delta: 0.014657730517408686 	  Loss: 1.8544175204204971 	 Accuracy: 0.13559322033898305
Delta: 0.01273797015223743 	  Loss: 1.748011157983213 	 Accuracy: 0.121251629726206
Delta: 0.011259866137901683 	  Loss: 1.6745259899625613 	 Accuracy: 0.1290743155149935
Delta: 0.00945945325689616 	  Loss: 1.6333932591744493 	 Accuracy: 0.1316818774445893
Delta: 0.008235246056934077 	  Loss: 1.6099938851346836 	 Accuracy: 0.14471968709256844
Delta: 0.0073396061194176965 	  Loss: 1.596994867072444 	 Accuracy: 0.14341590612777053
Delta: 0.006475099803544004 	  Loss: 1.5893788292213467 	 Accuracy: 0.14732724902216426
Delta: 0.006906592976976146 	  Loss: 1.5842968337898782 	 Accuracy: 0.14863102998696218
Delta: 0.005861983287031446 	  Loss: 1.5809429479585495 	 Accuracy: 0.15254237288135594
Delta: 0.005048160396856342 	  Loss: 1.5787729299717637 	 Accuracy: 0.14732724902216426

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005321956066821218 	  Loss: 1.577315083527299 	 Accuracy: 0.14993481095176012
Delta: 0.005328320751393984 	  Loss: 1.5761667082496973 	 Accuracy: 0.15123859191655803
Delta: 0.0049755338340023054 	  Loss: 1.5753760456211086 	 Accuracy: 0.1577574967405476
Delta: 0.0029460433238645456 	  Loss: 1.5748717695712795 	 Accuracy: 0.1590612777053455
Delta: 0.003018852056238752 	  Loss: 1.574538118508369 	 Accuracy: 0.15384615384615385
Delta: 0.004060892820317284 	  Loss: 1.5743469825615173 	 Accuracy: 0.1577574967405476
Delta: 0.003819022412688204 	  Loss: 1.574166990321749 	 Accuracy: 0.15645371577574968
Delta: 0.003861215699777372 	  Loss: 1.5741623028941016 	 Accuracy: 0.15384615384615385
Delta: 0.0036601306781855374 	  Loss: 1.574149150228662 	 Accuracy: 0.15645371577574968
Delta: 0.0037243312452181743 	  Loss: 1.5740784544147233 	 Accuracy: 0.15645371577574968
Delta: 0.0016195853933683492 	  Loss: 1.5741052636942907 	 Accuracy: 0.15514993481095177
Delta: 0.0015908482670084036 	  Loss: 1.5740439057055724 	 Accuracy: 0.15514993481095177
Delta: 0.002154291105927041 	  Loss: 1.5740139643693045 	 Accuracy: 0.15514993481095177
Delta: 0.0022382374526479292 	  Loss: 1.5739271573733808 	 Accuracy: 0.15514993481095177
Delta: 0.0018208857464197409 	  Loss: 1.573971146245417 	 Accuracy: 0.15384615384615385
Delta: 0.001565055937575662 	  Loss: 1.5739709088861016 	 Accuracy: 0.15514993481095177
Delta: 0.0018350304173515798 	  Loss: 1.5739897355860069 	 Accuracy: 0.15514993481095177
Delta: 0.0022451707484354194 	  Loss: 1.573908153708588 	 Accuracy: 0.15514993481095177
Delta: 0.001228980059283624 	  Loss: 1.5738537537585255 	 Accuracy: 0.15514993481095177
Delta: 0.0025587131611574747 	  Loss: 1.5738281338973052 	 Accuracy: 0.15645371577574968
Delta: 0.002354270248984682 	  Loss: 1.5739845962773193 	 Accuracy: 0.15514993481095177
Delta: 6.490539643209157e-05 	  Loss: 1.57367084837846 	 Accuracy: 0.14993481095176012
Delta: 0.001395151781979299 	  Loss: 1.5739086471811499 	 Accuracy: 0.15514993481095177
Delta: 0.0015320952979798682 	  Loss: 1.5738871384143018 	 Accuracy: 0.15514993481095177
Delta: 0.0009112580838604539 	  Loss: 1.5738832034551744 	 Accuracy: 0.15384615384615385
Delta: 0.0018187525780303465 	  Loss: 1.5740543774982687 	 Accuracy: 0.15384615384615385
Delta: 0.001664546801864762 	  Loss: 1.5739038710418125 	 Accuracy: 0.15514993481095177
Delta: 0.0007869616529769984 	  Loss: 1.5737367335876575 	 Accuracy: 0.15514993481095177
Delta: 0.0014268502688786133 	  Loss: 1.5737906175339336 	 Accuracy: 0.15514993481095177
Delta: 0.0012637855876821615 	  Loss: 1.5737871948366748 	 Accuracy: 0.15514993481095177
Delta: 4.517577417556355e-05 	  Loss: 1.5736573968800058 	 Accuracy: 0.15384615384615385
Delta: 0.0011967927433362935 	  Loss: 1.5736601219627142 	 Accuracy: 0.15514993481095177
Delta: 5.5437638162423795e-05 	  Loss: 1.5738994683085155 	 Accuracy: 0.15514993481095177
Delta: 0.0017580053634150684 	  Loss: 1.5740624563543388 	 Accuracy: 0.1590612777053455
Delta: 0.0009064919255947862 	  Loss: 1.573627973676694 	 Accuracy: 0.15384615384615385
Delta: 0.0009381792298709113 	  Loss: 1.5738387978682309 	 Accuracy: 0.15514993481095177
Delta: 0.0007846197441918238 	  Loss: 1.5736823632892023 	 Accuracy: 0.15514993481095177
Delta: 0.000834927198818265 	  Loss: 1.5736913185094945 	 Accuracy: 0.15514993481095177
Delta: 6.584416125181977e-05 	  Loss: 1.573818032136192 	 Accuracy: 0.15384615384615385
Delta: 0.0017135007233769076 	  Loss: 1.5736915966720986 	 Accuracy: 0.15514993481095177
Delta: 7.239301467233061e-05 	  Loss: 1.5737801539315874 	 Accuracy: 0.15514993481095177
Delta: 0.0029300446994991224 	  Loss: 1.5739679042034507 	 Accuracy: 0.15514993481095177
Delta: 3.0853911931622146e-05 	  Loss: 1.5740060424052242 	 Accuracy: 0.15514993481095177
Delta: 0.0008957685370993588 	  Loss: 1.573860408415376 	 Accuracy: 0.15514993481095177
Delta: 0.00011531650696724898 	  Loss: 1.5738897930651157 	 Accuracy: 0.15514993481095177
Delta: 8.246772698437067e-06 	  Loss: 1.5738852881303402 	 Accuracy: 0.15384615384615385
Delta: 1.3278157590378874e-05 	  Loss: 1.5738834825451984 	 Accuracy: 0.15384615384615385
Delta: 5.168633229298295e-05 	  Loss: 1.5739742923416942 	 Accuracy: 0.15514993481095177
Delta: 0.0007838583659695331 	  Loss: 1.5742176273159494 	 Accuracy: 0.15514993481095177
Delta: 0.0013921952589997673 	  Loss: 1.573969153293918 	 Accuracy: 0.15514993481095177
Delta: 0.0015902269676223103 	  Loss: 1.5743836564178817 	 Accuracy: 0.15514993481095177
Delta: 0.0016244760723609264 	  Loss: 1.574266194441864 	 Accuracy: 0.15514993481095177
Delta: 0.0015247296266064855 	  Loss: 1.573949029372812 	 Accuracy: 0.15514993481095177
Delta: 3.9451723675376574e-05 	  Loss: 1.5740047899890484 	 Accuracy: 0.15123859191655803
Delta: 5.876083232951004e-05 	  Loss: 1.5740946381239462 	 Accuracy: 0.15514993481095177
Delta: 0.0021194580461192376 	  Loss: 1.5738937475324388 	 Accuracy: 0.1590612777053455
Delta: 0.0014786523811269221 	  Loss: 1.5740871157252783 	 Accuracy: 0.15514993481095177
Delta: 0.0012249997294714414 	  Loss: 1.5740442429683537 	 Accuracy: 0.15514993481095177
Delta: 0.0012296904824776042 	  Loss: 1.5738215042551746 	 Accuracy: 0.15514993481095177
Delta: 0.0023058004096147 	  Loss: 1.573721556427583 	 Accuracy: 0.15514993481095177
Delta: 0.0017172817567779079 	  Loss: 1.5739134580547667 	 Accuracy: 0.15384615384615385
Delta: 0.0018316143339478126 	  Loss: 1.5740841235555598 	 Accuracy: 0.15384615384615385
Delta: 0.002200001676598026 	  Loss: 1.5742293597724182 	 Accuracy: 0.15384615384615385
Delta: 0.000574905377182353 	  Loss: 1.5739376100958093 	 Accuracy: 0.15514993481095177
Delta: 0.0015961776571315597 	  Loss: 1.5740891245926334 	 Accuracy: 0.15514993481095177
Delta: 4.631196976215123e-05 	  Loss: 1.5739412572057678 	 Accuracy: 0.15514993481095177
Delta: 4.3064990185766795e-05 	  Loss: 1.5739731563399013 	 Accuracy: 0.15514993481095177
Delta: 0.0001076245130885499 	  Loss: 1.5742112946088664 	 Accuracy: 0.15514993481095177
Delta: 0.00011460157434449178 	  Loss: 1.5740796294093058 	 Accuracy: 0.15514993481095177
Delta: 0.0035123567085641383 	  Loss: 1.5740807232859928 	 Accuracy: 0.15514993481095177
Delta: 0.0024931795762173346 	  Loss: 1.5741339030692028 	 Accuracy: 0.14993481095176012
Delta: 0.005628969423241531 	  Loss: 1.578170026485712 	 Accuracy: 0.15384615384615385
Delta: 0.004544463095952838 	  Loss: 1.574706784480231 	 Accuracy: 0.15514993481095177
Delta: 0.004502456655143955 	  Loss: 1.5748059631066675 	 Accuracy: 0.15514993481095177
Delta: 0.0032557710829944596 	  Loss: 1.5748105028819794 	 Accuracy: 0.15254237288135594
Delta: 0.0005617924201155651 	  Loss: 1.5750953926571376 	 Accuracy: 0.15384615384615385
Delta: 2.90830369520523e-05 	  Loss: 1.575071310947199 	 Accuracy: 0.15384615384615385
Delta: 0.0006629434738180922 	  Loss: 1.5751128152808134 	 Accuracy: 0.15254237288135594
Delta: 2.7823824691997548e-05 	  Loss: 1.5750424029631658 	 Accuracy: 0.15384615384615385
Delta: 6.0246937837453284e-05 	  Loss: 1.5750984370665506 	 Accuracy: 0.15384615384615385
Delta: 0.0005514658975834128 	  Loss: 1.5751261185390018 	 Accuracy: 0.15645371577574968
Delta: 0.0007707135309861326 	  Loss: 1.5750543733786406 	 Accuracy: 0.15384615384615385
Delta: 0.0007526498021822768 	  Loss: 1.5750998039686956 	 Accuracy: 0.15384615384615385
Delta: 0.0015071960691109714 	  Loss: 1.5752003122794385 	 Accuracy: 0.15384615384615385
Delta: 0.002054909028411972 	  Loss: 1.5750126074064377 	 Accuracy: 0.15384615384615385
Delta: 7.306829984003716e-05 	  Loss: 1.5750469857107978 	 Accuracy: 0.15384615384615385
Delta: 8.869292160725546e-05 	  Loss: 1.5751844639880412 	 Accuracy: 0.15514993481095177
Delta: 0.020920500349567026 	  Loss: 2.160849595620836 	 Accuracy: 0.17470664928292046
Delta: 0.018767035843884144 	  Loss: 2.0866331717019637 	 Accuracy: 0.11603650586701435
Delta: 0.017044053801145705 	  Loss: 1.9610246783800385 	 Accuracy: 0.13559322033898305
Delta: 0.015071071275871022 	  Loss: 1.8191598776342415 	 Accuracy: 0.14732724902216426
Delta: 0.012960376209535628 	  Loss: 1.7157590842038108 	 Accuracy: 0.13559322033898305
Delta: 0.011181036763533245 	  Loss: 1.6531655984841342 	 Accuracy: 0.13298565840938723
Delta: 0.010340401567736086 	  Loss: 1.6166170863411833 	 Accuracy: 0.1290743155149935
Delta: 0.009096439267213135 	  Loss: 1.5945464355702728 	 Accuracy: 0.1316818774445893
Delta: 0.008046667876952057 	  Loss: 1.580892980183906 	 Accuracy: 0.1303780964797914

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006975270598081095 	  Loss: 1.5724151284033954 	 Accuracy: 0.1290743155149935
Delta: 0.00647221931510906 	  Loss: 1.5678335794525566 	 Accuracy: 0.1303780964797914
Delta: 0.006044340406030982 	  Loss: 1.5646014379761748 	 Accuracy: 0.12516297262059975
Delta: 0.005335885496058917 	  Loss: 1.562649647390949 	 Accuracy: 0.12777053455019557
Delta: 0.004924130186340492 	  Loss: 1.5613651408289662 	 Accuracy: 0.12646675358539766
Delta: 0.004148842672297366 	  Loss: 1.5608038328096927 	 Accuracy: 0.12385919165580182
Delta: 0.004152388043113279 	  Loss: 1.5603095279753345 	 Accuracy: 0.12255541069100391
Delta: 0.00444527555721112 	  Loss: 1.5597774566863254 	 Accuracy: 0.12516297262059975
Delta: 0.002537120380276623 	  Loss: 1.5595433825631588 	 Accuracy: 0.12255541069100391
Delta: 0.004110943057750744 	  Loss: 1.559512722697819 	 Accuracy: 0.12385919165580182
Delta: 0.002448581115387971 	  Loss: 1.5595738430938373 	 Accuracy: 0.12385919165580182
Delta: 6.042683803062533e-05 	  Loss: 1.5594590421243395 	 Accuracy: 0.12255541069100391
Delta: 0.0008252763683665032 	  Loss: 1.5594398764407602 	 Accuracy: 0.12385919165580182
Delta: 0.000655070738167891 	  Loss: 1.5594317382066598 	 Accuracy: 0.12255541069100391
Delta: 0.0026683954003200398 	  Loss: 1.5594104505696271 	 Accuracy: 0.12255541069100391
Delta: 0.002115789080497981 	  Loss: 1.5594607789511652 	 Accuracy: 0.12255541069100391
Delta: 0.0012604368215967988 	  Loss: 1.5594909272579578 	 Accuracy: 0.12385919165580182
Delta: 1.2460846635320298e-05 	  Loss: 1.559494756538977 	 Accuracy: 0.12385919165580182
Delta: 0.0012090519584917535 	  Loss: 1.559567328592133 	 Accuracy: 0.12385919165580182
Delta: 3.326498431992205e-05 	  Loss: 1.5595769804614674 	 Accuracy: 0.12385919165580182
Delta: 1.6339843498515546e-05 	  Loss: 1.5595493936463993 	 Accuracy: 0.12385919165580182
Delta: 0.0026157603944677917 	  Loss: 1.5595287541434233 	 Accuracy: 0.12385919165580182
Delta: 0.001953198812216727 	  Loss: 1.5596096382930265 	 Accuracy: 0.12385919165580182
Delta: 0.0019784925135845825 	  Loss: 1.5597897585176042 	 Accuracy: 0.12385919165580182
Delta: 0.0007234302118233109 	  Loss: 1.5595219985909048 	 Accuracy: 0.12385919165580182
Delta: 0.0010163747889115886 	  Loss: 1.5594503012976069 	 Accuracy: 0.12385919165580182
Delta: 0.0019326453618755811 	  Loss: 1.5598375951303898 	 Accuracy: 0.12385919165580182
Delta: 0.0007395223309803325 	  Loss: 1.5595602799364898 	 Accuracy: 0.12385919165580182
Delta: 2.4533622889624747e-05 	  Loss: 1.5596330886564875 	 Accuracy: 0.12516297262059975
Delta: 0.0005859944629881645 	  Loss: 1.5595278545497246 	 Accuracy: 0.12385919165580182
Delta: 8.327455848006427e-05 	  Loss: 1.559661254995205 	 Accuracy: 0.12385919165580182
Delta: 0.0007165789389485552 	  Loss: 1.5595562073581566 	 Accuracy: 0.12385919165580182
Delta: 2.258584033702512e-05 	  Loss: 1.5595480891307898 	 Accuracy: 0.12385919165580182
Delta: 2.486103938616308e-05 	  Loss: 1.5596247809744757 	 Accuracy: 0.12385919165580182
Delta: 1.4596563736169074e-05 	  Loss: 1.5595802758221646 	 Accuracy: 0.12385919165580182
Delta: 2.133892631633082e-05 	  Loss: 1.5596507725995272 	 Accuracy: 0.12385919165580182
Delta: 0.0007265290043728238 	  Loss: 1.5597356688712973 	 Accuracy: 0.12385919165580182
Delta: 3.641715646204676e-05 	  Loss: 1.559790427018115 	 Accuracy: 0.12385919165580182
Delta: 4.514064937739112e-05 	  Loss: 1.5595835940109992 	 Accuracy: 0.12385919165580182
Delta: 4.404803106797282e-06 	  Loss: 1.5595714932141722 	 Accuracy: 0.12255541069100391
Delta: 1.7653254148773992e-05 	  Loss: 1.5595894368818253 	 Accuracy: 0.12385919165580182
Delta: 0.000740850879430401 	  Loss: 1.559477685172838 	 Accuracy: 0.12385919165580182
Delta: 4.194032561952759e-05 	  Loss: 1.5595516415198492 	 Accuracy: 0.12385919165580182
Delta: 2.8188922532440188e-05 	  Loss: 1.559614659959021 	 Accuracy: 0.12385919165580182
Delta: 2.807567565622094e-05 	  Loss: 1.5595783240994132 	 Accuracy: 0.12385919165580182
Delta: 9.554429912418606e-06 	  Loss: 1.5595816284186965 	 Accuracy: 0.12646675358539766
Delta: 5.352298339199067e-05 	  Loss: 1.559517744193815 	 Accuracy: 0.12385919165580182
Delta: 5.173357406818695e-05 	  Loss: 1.5595694340630026 	 Accuracy: 0.12385919165580182
Delta: 0.0026199817272668713 	  Loss: 1.559579202212344 	 Accuracy: 0.12385919165580182
Delta: 0.00012091878825464272 	  Loss: 1.5595620767263836 	 Accuracy: 0.12385919165580182
Delta: 0.0009262978913016346 	  Loss: 1.5595741377961256 	 Accuracy: 0.12385919165580182
Delta: 2.5863616632014353e-06 	  Loss: 1.5595776724481745 	 Accuracy: 0.12385919165580182
Delta: 1.0675640642243462e-06 	  Loss: 1.5595794864927497 	 Accuracy: 0.11734028683181226
Delta: 2.814958309566386e-05 	  Loss: 1.559628774999391 	 Accuracy: 0.12646675358539766
Delta: 2.4815904553462636e-05 	  Loss: 1.559592338559917 	 Accuracy: 0.12385919165580182
Delta: 9.151920885823125e-06 	  Loss: 1.5595919581063307 	 Accuracy: 0.12385919165580182
Delta: 4.576132185566018e-05 	  Loss: 1.5596239078227354 	 Accuracy: 0.12385919165580182
Delta: 4.8802819886567944e-05 	  Loss: 1.5595551031039638 	 Accuracy: 0.12385919165580182
Delta: 0.0010617002045845165 	  Loss: 1.5596239192027057 	 Accuracy: 0.12385919165580182
Delta: 0.0010596933760985245 	  Loss: 1.559562299494831 	 Accuracy: 0.12385919165580182
Delta: 6.597062087568837e-06 	  Loss: 1.5596035971783981 	 Accuracy: 0.12385919165580182
Delta: 9.19012980181647e-06 	  Loss: 1.5595972640518108 	 Accuracy: 0.12385919165580182
Delta: 8.01625987590831e-06 	  Loss: 1.5595704174540206 	 Accuracy: 0.12385919165580182
Delta: 7.531820446893282e-05 	  Loss: 1.5594922711111585 	 Accuracy: 0.12385919165580182
Delta: 4.543034079737379e-05 	  Loss: 1.559514726964258 	 Accuracy: 0.12385919165580182
Delta: 3.8307777917969486e-05 	  Loss: 1.5595655025617159 	 Accuracy: 0.12385919165580182
Delta: 1.5066637300220376e-05 	  Loss: 1.5595570100154272 	 Accuracy: 0.12385919165580182
Delta: 2.641185527710739e-05 	  Loss: 1.5595475326636514 	 Accuracy: 0.12385919165580182
Delta: 0.0008839773493290718 	  Loss: 1.559614210041487 	 Accuracy: 0.12385919165580182
Delta: 0.0007293855726832177 	  Loss: 1.5595906985702443 	 Accuracy: 0.12385919165580182
Delta: 0.0010656658911290396 	  Loss: 1.5596210885641997 	 Accuracy: 0.12385919165580182
Delta: 8.272698863607914e-06 	  Loss: 1.5596338836597203 	 Accuracy: 0.12385919165580182
Delta: 0.0008509765720385984 	  Loss: 1.5596537069536816 	 Accuracy: 0.12385919165580182
Delta: 0.0012647989268490542 	  Loss: 1.5595697464811926 	 Accuracy: 0.12385919165580182
Delta: 3.0358318072988903e-05 	  Loss: 1.5596030952746482 	 Accuracy: 0.12385919165580182
Delta: 3.095776639364225e-05 	  Loss: 1.5595413620571994 	 Accuracy: 0.12385919165580182
Delta: 1.5110765442982555e-05 	  Loss: 1.5595653476584936 	 Accuracy: 0.12385919165580182
Delta: 6.503175629809353e-06 	  Loss: 1.559555990203814 	 Accuracy: 0.12385919165580182
Delta: 8.724004220009247e-06 	  Loss: 1.5595766109884268 	 Accuracy: 0.12385919165580182
Delta: 5.286751474311497e-07 	  Loss: 1.5595766108476974 	 Accuracy: 0.12385919165580182
converged at iter  88
Delta: 0.020934962193307725 	  Loss: 2.1601924426588313 	 Accuracy: 0.17209908735332463
Delta: 0.018363955610255105 	  Loss: 2.0835352038198875 	 Accuracy: 0.11473272490221642
Delta: 0.016550934752075683 	  Loss: 1.9663685335960244 	 Accuracy: 0.10560625814863103
Delta: 0.014875273593173432 	  Loss: 1.8455351419299246 	 Accuracy: 0.10821382007822686
Delta: 0.01351284493804518 	  Loss: 1.7612989040966331 	 Accuracy: 0.11603650586701435
Delta: 0.013461833250908238 	  Loss: 1.6974870854580997 	 Accuracy: 0.11994784876140809
Delta: 0.012186800982782115 	  Loss: 1.6431455093865357 	 Accuracy: 0.12385919165580182
Delta: 0.010370904635191722 	  Loss: 1.60696849525196 	 Accuracy: 0.1408083441981747
Delta: 0.008980816551075209 	  Loss: 1.5874713028027019 	 Accuracy: 0.13820078226857888
Delta: 0.007985737712135805 	  Loss: 1.5769910152945208 	 Accuracy: 0.1395045632333768
Delta: 0.005695504434661703 	  Loss: 1.5735459546389268 	 Accuracy: 0.14341590612777053
Delta: 0.0051768375868875074 	  Loss: 1.571949767932799 	 Accuracy: 0.1421121251629726

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005917941759721021 	  Loss: 1.571166122353873 	 Accuracy: 0.1421121251629726
Delta: 0.003790934185796853 	  Loss: 1.570911852218999 	 Accuracy: 0.14341590612777053
Delta: 0.004450896220209796 	  Loss: 1.570651488673074 	 Accuracy: 0.14341590612777053
Delta: 0.0039108570926077845 	  Loss: 1.5705949042318443 	 Accuracy: 0.14471968709256844
Delta: 0.0036051228448756344 	  Loss: 1.5704896372887753 	 Accuracy: 0.14732724902216426
Delta: 0.002863654917565296 	  Loss: 1.5703533883128502 	 Accuracy: 0.14602346805736635
Delta: 0.0014425806050715874 	  Loss: 1.5703737737416474 	 Accuracy: 0.14602346805736635
Delta: 0.0012865522968165345 	  Loss: 1.5703830016439926 	 Accuracy: 0.14732724902216426
Delta: 0.0006458483641737004 	  Loss: 1.5703353216466023 	 Accuracy: 0.14732724902216426
Delta: 0.002763931492531518 	  Loss: 1.5703123107251606 	 Accuracy: 0.14602346805736635
Delta: 0.001982406241256011 	  Loss: 1.5702614701111246 	 Accuracy: 0.14732724902216426
Delta: 0.000724041929807949 	  Loss: 1.5702957871440502 	 Accuracy: 0.14602346805736635
Delta: 0.0010715571713740626 	  Loss: 1.5702583015783023 	 Accuracy: 0.14602346805736635
Delta: 0.003419441434017107 	  Loss: 1.5702257047682695 	 Accuracy: 0.14602346805736635
Delta: 2.8490065705050138e-05 	  Loss: 1.5701789247982059 	 Accuracy: 0.14732724902216426
Delta: 0.002315096212495266 	  Loss: 1.5702971666416465 	 Accuracy: 0.14732724902216426
Delta: 0.0009694160513007489 	  Loss: 1.570422717489444 	 Accuracy: 0.14732724902216426
Delta: 0.0005535445982448699 	  Loss: 1.5702017630230656 	 Accuracy: 0.14732724902216426
Delta: 0.0020078159409324474 	  Loss: 1.570369974083424 	 Accuracy: 0.14732724902216426
Delta: 0.001945501824716549 	  Loss: 1.5702323945549792 	 Accuracy: 0.14602346805736635
Delta: 0.0012203691025295374 	  Loss: 1.570184442644265 	 Accuracy: 0.14732724902216426
Delta: 0.0020867034687841214 	  Loss: 1.5701991755210394 	 Accuracy: 0.14732724902216426
Delta: 0.0013287240162304023 	  Loss: 1.5702014861220461 	 Accuracy: 0.14732724902216426
Delta: 0.0005199384043037769 	  Loss: 1.570143391433029 	 Accuracy: 0.14732724902216426
Delta: 4.080076309545186e-05 	  Loss: 1.5700998671790014 	 Accuracy: 0.14732724902216426
Delta: 0.0016291936857921981 	  Loss: 1.5700286864333437 	 Accuracy: 0.14732724902216426
Delta: 0.001966822673474241 	  Loss: 1.5701982724965775 	 Accuracy: 0.14732724902216426
Delta: 2.920462732656747e-05 	  Loss: 1.5701865339497445 	 Accuracy: 0.14732724902216426
Delta: 0.001614597082933062 	  Loss: 1.5702424872840728 	 Accuracy: 0.14732724902216426
Delta: 0.0013886897610337892 	  Loss: 1.570253906834493 	 Accuracy: 0.14602346805736635
Delta: 0.001097943315932106 	  Loss: 1.5701605867061863 	 Accuracy: 0.14732724902216426
Delta: 4.393012428306724e-05 	  Loss: 1.5701680952306636 	 Accuracy: 0.14732724902216426
Delta: 1.731437916659128e-05 	  Loss: 1.570187543091558 	 Accuracy: 0.14732724902216426
Delta: 0.003109307633996385 	  Loss: 1.5703462894877722 	 Accuracy: 0.14732724902216426
Delta: 4.7244848236918805e-05 	  Loss: 1.570269213622924 	 Accuracy: 0.14732724902216426
Delta: 0.00243521525481421 	  Loss: 1.5703966623052494 	 Accuracy: 0.14732724902216426
Delta: 0.0005369008536732602 	  Loss: 1.5704489218338331 	 Accuracy: 0.14732724902216426
Delta: 2.4443374822492783e-05 	  Loss: 1.5704184922353897 	 Accuracy: 0.14732724902216426
Delta: 1.901696190813601e-05 	  Loss: 1.5704445918899312 	 Accuracy: 0.14732724902216426
Delta: 1.2455146501191443e-05 	  Loss: 1.5704357247886107 	 Accuracy: 0.14732724902216426
Delta: 4.929916152864584e-05 	  Loss: 1.5704400788215818 	 Accuracy: 0.14732724902216426
Delta: 4.609179391436156e-05 	  Loss: 1.5704359513812114 	 Accuracy: 0.14732724902216426
Delta: 1.0188002971929018e-05 	  Loss: 1.5704453368076583 	 Accuracy: 0.14732724902216426
Delta: 2.5769860875894967e-05 	  Loss: 1.5705193811591949 	 Accuracy: 0.14732724902216426
Delta: 0.0008508278251697819 	  Loss: 1.5704043747394656 	 Accuracy: 0.14732724902216426
Delta: 0.0016327899867702974 	  Loss: 1.5704188668427324 	 Accuracy: 0.14732724902216426
Delta: 0.002265847680331888 	  Loss: 1.570505799803266 	 Accuracy: 0.13820078226857888
Delta: 8.172808641144851e-05 	  Loss: 1.570480341351027 	 Accuracy: 0.14732724902216426
Delta: 8.423317038658786e-05 	  Loss: 1.5704223476290737 	 Accuracy: 0.14732724902216426
Delta: 8.39597610181216e-05 	  Loss: 1.5703560327870236 	 Accuracy: 0.14602346805736635
Delta: 0.0019232739602622307 	  Loss: 1.5703138017647573 	 Accuracy: 0.14602346805736635
Delta: 5.283690342474781e-05 	  Loss: 1.5703709355079387 	 Accuracy: 0.14732724902216426
Delta: 0.0005290276184373887 	  Loss: 1.5703469725614383 	 Accuracy: 0.14732724902216426
Delta: 4.0346121427994887e-05 	  Loss: 1.5704983931984033 	 Accuracy: 0.14732724902216426
Delta: 0.0006428505727085676 	  Loss: 1.5704257214012263 	 Accuracy: 0.14993481095176012
Delta: 0.0005662227231292612 	  Loss: 1.5704457389624653 	 Accuracy: 0.14732724902216426
Delta: 0.0005689905417870534 	  Loss: 1.5703538648161142 	 Accuracy: 0.14732724902216426
Delta: 0.000542300752621318 	  Loss: 1.5703805132436586 	 Accuracy: 0.14732724902216426
Delta: 0.000553101032176825 	  Loss: 1.570368437238677 	 Accuracy: 0.14863102998696218
Delta: 0.0005365054810987402 	  Loss: 1.570394119649281 	 Accuracy: 0.14863102998696218
Delta: 0.0006708557899676315 	  Loss: 1.5703037883477917 	 Accuracy: 0.14732724902216426
Delta: 0.0006706261896442969 	  Loss: 1.5706077454401175 	 Accuracy: 0.14732724902216426
Delta: 0.0007400433137499367 	  Loss: 1.5704125174290484 	 Accuracy: 0.14732724902216426
Delta: 0.0007544808551695566 	  Loss: 1.570348872120872 	 Accuracy: 0.14471968709256844
Delta: 0.0034190426050982117 	  Loss: 1.5707678329351809 	 Accuracy: 0.14602346805736635
Delta: 0.0006502857724386784 	  Loss: 1.570001744276393 	 Accuracy: 0.14471968709256844
Delta: 0.003073218856851465 	  Loss: 1.5703576753057207 	 Accuracy: 0.14602346805736635
Delta: 0.0017098120548688098 	  Loss: 1.5705948936379444 	 Accuracy: 0.14732724902216426
Delta: 0.0006565407958089473 	  Loss: 1.5703337262712511 	 Accuracy: 0.14863102998696218
Delta: 0.002805952426438179 	  Loss: 1.5708092633005875 	 Accuracy: 0.14341590612777053
Delta: 0.0016159048962952854 	  Loss: 1.5703586516620522 	 Accuracy: 0.14602346805736635
Delta: 0.0015930883669232432 	  Loss: 1.5703517421220905 	 Accuracy: 0.14732724902216426
Delta: 0.001544532582108111 	  Loss: 1.5702881286816708 	 Accuracy: 0.14732724902216426
Delta: 0.0019392378843455123 	  Loss: 1.5702685642055956 	 Accuracy: 0.14863102998696218
Delta: 0.0026718367761031686 	  Loss: 1.570196607838442 	 Accuracy: 0.14732724902216426
Delta: 0.0006999667967482052 	  Loss: 1.5702020753863166 	 Accuracy: 0.14863102998696218
Delta: 0.0011184658731000206 	  Loss: 1.5703046515029913 	 Accuracy: 0.14732724902216426
Delta: 0.0014447574184290688 	  Loss: 1.5702633879816141 	 Accuracy: 0.14471968709256844
Delta: 0.0025433988542416064 	  Loss: 1.5703581105162867 	 Accuracy: 0.14732724902216426
Delta: 0.0036872887877333112 	  Loss: 1.5705461881610878 	 Accuracy: 0.14732724902216426
Delta: 2.798930291174928e-05 	  Loss: 1.5705450302035158 	 Accuracy: 0.14732724902216426
Delta: 0.0008117875914138375 	  Loss: 1.5705882443418144 	 Accuracy: 0.14863102998696218
Delta: 0.0009081151400082556 	  Loss: 1.5704442412606616 	 Accuracy: 0.14863102998696218
Delta: 0.0021408177066760473 	  Loss: 1.5704548933541087 	 Accuracy: 0.14863102998696218
Delta: 0.0018835508937042086 	  Loss: 1.5704209703905176 	 Accuracy: 0.14602346805736635
Delta: 0.0022601494487161514 	  Loss: 1.5705363417487073 	 Accuracy: 0.14863102998696218
Delta: 0.0013535657778281328 	  Loss: 1.570478395604691 	 Accuracy: 0.14863102998696218
Delta: 0.0006880725250539155 	  Loss: 1.5705191599950128 	 Accuracy: 0.14732724902216426
Delta: 0.021001345645999783 	  Loss: 2.1605948966764936 	 Accuracy: 0.15123859191655803
Delta: 0.01827965954444262 	  Loss: 2.0797229696998327 	 Accuracy: 0.10039113428943937
Delta: 0.017166794713924103 	  Loss: 1.9401299334324231 	 Accuracy: 0.10560625814863103
Delta: 0.015003885470268383 	  Loss: 1.7896386558612432 	 Accuracy: 0.10560625814863103
Delta: 0.01289391398498621 	  Loss: 1.6962505791760762 	 Accuracy: 0.10430247718383312
Delta: 0.011463455671076574 	  Loss: 1.6522372833668395 	 Accuracy: 0.11994784876140809
Delta: 0.00942748212803397 	  Loss: 1.6306249470444658 	 Accuracy: 0.1290743155149935
Delta: 0.008919208527421769 	  Loss: 1.6183243771358597 	 Accuracy: 0.14602346805736635
Delta: 0.007613316726441181 	  Loss: 1.6129534944026083 	 Accuracy: 0.14602346805736635
Delta: 0.0067243804862613344 	  Loss: 1.609698429419228 	 Accuracy: 0.14732724902216426

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006516332362396561 	  Loss: 1.6077117204158367 	 Accuracy: 0.14471968709256844
Delta: 0.0054281802648163645 	  Loss: 1.606601151750672 	 Accuracy: 0.1395045632333768
Delta: 0.004446405449239853 	  Loss: 1.60608032379053 	 Accuracy: 0.1421121251629726
Delta: 0.0038478967033537667 	  Loss: 1.605825841145721 	 Accuracy: 0.1421121251629726
Delta: 0.0019511220089543492 	  Loss: 1.6059443485568703 	 Accuracy: 0.14732724902216426
Delta: 0.0038201009400832364 	  Loss: 1.6057019879797074 	 Accuracy: 0.14341590612777053
Delta: 0.004798762675108332 	  Loss: 1.6059384544367408 	 Accuracy: 0.1421121251629726
Delta: 0.002023699839404682 	  Loss: 1.605958635189337 	 Accuracy: 0.14341590612777053
Delta: 0.0034913582880282614 	  Loss: 1.6058667961384274 	 Accuracy: 0.1421121251629726
Delta: 0.0017955983857080753 	  Loss: 1.605760573247343 	 Accuracy: 0.14471968709256844
Delta: 0.002812911720088591 	  Loss: 1.6057552754459548 	 Accuracy: 0.14341590612777053
Delta: 0.0013105520723900109 	  Loss: 1.605774003829192 	 Accuracy: 0.14471968709256844
Delta: 4.1931385790413574e-05 	  Loss: 1.6057739239073663 	 Accuracy: 0.14341590612777053
converged at iter  22
Delta: 0.020983138324968634 	  Loss: 2.160266700579757 	 Accuracy: 0.1760104302477184
Delta: 0.018353445540058407 	  Loss: 2.0789476622737086 	 Accuracy: 0.13559322033898305
Delta: 0.01694154151985533 	  Loss: 1.945606156245484 	 Accuracy: 0.17470664928292046
Delta: 0.01505431535744879 	  Loss: 1.8162722641089748 	 Accuracy: 0.20078226857887874
Delta: 0.014197602822545698 	  Loss: 1.7264544971784792 	 Accuracy: 0.20599739243807041
Delta: 0.012644501707916155 	  Loss: 1.661821294267749 	 Accuracy: 0.22033898305084745
Delta: 0.010457157593896288 	  Loss: 1.6280681337891443 	 Accuracy: 0.20860495436766624
Delta: 0.00918617868099951 	  Loss: 1.6131181675936304 	 Accuracy: 0.20730117340286833

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007735406447977069 	  Loss: 1.6066078834426487 	 Accuracy: 0.19165580182529335
Delta: 0.006001960596638384 	  Loss: 1.6044756721076616 	 Accuracy: 0.20208604954367665
Delta: 0.004950814605609829 	  Loss: 1.6034024491503007 	 Accuracy: 0.19947848761408082
Delta: 0.003846908701935131 	  Loss: 1.6034235513828983 	 Accuracy: 0.19947848761408082
Delta: 0.0031030961367370714 	  Loss: 1.60338565504227 	 Accuracy: 0.1981747066492829
Delta: 0.003007371809854983 	  Loss: 1.6031732789291988 	 Accuracy: 0.196870925684485
Delta: 0.0025095562429208705 	  Loss: 1.6031441612841557 	 Accuracy: 0.196870925684485
Delta: 0.002183997850775959 	  Loss: 1.6028618713102447 	 Accuracy: 0.196870925684485
Delta: 0.0020711926116667714 	  Loss: 1.602900561745101 	 Accuracy: 0.196870925684485
Delta: 0.0029335673378106954 	  Loss: 1.6027222958365912 	 Accuracy: 0.196870925684485
Delta: 4.7300467174205724e-05 	  Loss: 1.6027398657250567 	 Accuracy: 0.196870925684485
Delta: 0.0008045468250422175 	  Loss: 1.6027394128270394 	 Accuracy: 0.196870925684485
Delta: 0.0017984031130131467 	  Loss: 1.6028120065224951 	 Accuracy: 0.196870925684485
Delta: 0.0009603773894550335 	  Loss: 1.6029814611664654 	 Accuracy: 0.196870925684485
Delta: 0.001471597441424903 	  Loss: 1.6031094151253862 	 Accuracy: 0.196870925684485
Delta: 5.443462659513463e-05 	  Loss: 1.602953892867049 	 Accuracy: 0.196870925684485
Delta: 2.3309522092090917e-05 	  Loss: 1.602939790310396 	 Accuracy: 0.196870925684485
Delta: 0.0023788479115192857 	  Loss: 1.6029029528982606 	 Accuracy: 0.196870925684485
Delta: 5.420381618688234e-05 	  Loss: 1.6028436266468882 	 Accuracy: 0.196870925684485
Delta: 2.5311875896838328e-05 	  Loss: 1.6028479124237238 	 Accuracy: 0.196870925684485
Delta: 2.9621953412927877e-05 	  Loss: 1.6028548376600003 	 Accuracy: 0.196870925684485
Delta: 5.460154552112098e-05 	  Loss: 1.6029506509656894 	 Accuracy: 0.196870925684485
Delta: 4.95791627419598e-05 	  Loss: 1.6028516303408056 	 Accuracy: 0.196870925684485
Delta: 4.05122773876018e-05 	  Loss: 1.6028655018846845 	 Accuracy: 0.196870925684485
Delta: 0.0021539459807889266 	  Loss: 1.6029757607519939 	 Accuracy: 0.196870925684485
Delta: 0.0008457570855325111 	  Loss: 1.602850998855299 	 Accuracy: 0.196870925684485
Delta: 0.0010337892422912366 	  Loss: 1.6028824519636689 	 Accuracy: 0.20208604954367665
Delta: 4.940618565494974e-05 	  Loss: 1.6028626547207767 	 Accuracy: 0.196870925684485
Delta: 3.147963099733725e-05 	  Loss: 1.6028137717704292 	 Accuracy: 0.196870925684485
Delta: 2.889853387889654e-05 	  Loss: 1.6028578985902553 	 Accuracy: 0.196870925684485
Delta: 0.0010215610075396077 	  Loss: 1.6029704534311011 	 Accuracy: 0.196870925684485
Delta: 0.001027479336141729 	  Loss: 1.602868158746829 	 Accuracy: 0.196870925684485
Delta: 3.915268679376023e-05 	  Loss: 1.6028701413559654 	 Accuracy: 0.196870925684485
Delta: 3.6287950137583886e-05 	  Loss: 1.6028474483892405 	 Accuracy: 0.19556714471968709
Delta: 2.028866520995805e-05 	  Loss: 1.602869079147732 	 Accuracy: 0.196870925684485
Delta: 4.23822612281929e-05 	  Loss: 1.6029177914549881 	 Accuracy: 0.19426336375488917
Delta: 0.0011607776114612564 	  Loss: 1.602837489758452 	 Accuracy: 0.19556714471968709
Delta: 0.0008326090414936287 	  Loss: 1.6028972004600055 	 Accuracy: 0.196870925684485
Delta: 0.002235880796543154 	  Loss: 1.6028564902119795 	 Accuracy: 0.196870925684485
Delta: 3.2920542436541495e-05 	  Loss: 1.6028468740624426 	 Accuracy: 0.196870925684485
Delta: 6.558047278134313e-05 	  Loss: 1.6029499993150456 	 Accuracy: 0.196870925684485
Delta: 0.0007340675575463757 	  Loss: 1.6030888696303058 	 Accuracy: 0.19556714471968709
Delta: 0.0028473468338691458 	  Loss: 1.6028136881605315 	 Accuracy: 0.196870925684485
Delta: 8.863585369969107e-05 	  Loss: 1.6030427854255926 	 Accuracy: 0.19556714471968709
Delta: 0.0005619923590964355 	  Loss: 1.6028653750786985 	 Accuracy: 0.20990873533246415
Delta: 0.001206212768312564 	  Loss: 1.6028350494609795 	 Accuracy: 0.196870925684485
Delta: 0.000577008137371754 	  Loss: 1.6029864530689233 	 Accuracy: 0.196870925684485
Delta: 9.359408600188801e-05 	  Loss: 1.6028501902000771 	 Accuracy: 0.196870925684485
Delta: 4.7979985856805985e-06 	  Loss: 1.6028483718279358 	 Accuracy: 0.19556714471968709
Delta: 0.0006715578641787208 	  Loss: 1.6030845867126398 	 Accuracy: 0.19556714471968709
Delta: 0.0005513027024862133 	  Loss: 1.6028773385172328 	 Accuracy: 0.196870925684485
Delta: 6.514887430164101e-05 	  Loss: 1.6028961983227297 	 Accuracy: 0.196870925684485
Delta: 5.066545191606976e-05 	  Loss: 1.60292798372459 	 Accuracy: 0.19556714471968709
Delta: 0.0010853367519540287 	  Loss: 1.6029200211887669 	 Accuracy: 0.19165580182529335
Delta: 0.00441888216426071 	  Loss: 1.6027017890122328 	 Accuracy: 0.19556714471968709
Delta: 0.003756057435563177 	  Loss: 1.6029246230446057 	 Accuracy: 0.19556714471968709
Delta: 0.0018153190404933443 	  Loss: 1.6024446740928724 	 Accuracy: 0.19556714471968709
Delta: 0.0030616337818098046 	  Loss: 1.6027624696725784 	 Accuracy: 0.19556714471968709
Delta: 0.002808213699040376 	  Loss: 1.6024521193641101 	 Accuracy: 0.196870925684485
Delta: 0.0005870310383780198 	  Loss: 1.602290545252504 	 Accuracy: 0.196870925684485
Delta: 0.0029645108873378786 	  Loss: 1.6026602242644132 	 Accuracy: 0.19556714471968709
Delta: 0.0012003332669265226 	  Loss: 1.60267332684319 	 Accuracy: 0.196870925684485
Delta: 0.00260068029531761 	  Loss: 1.6025618263391286 	 Accuracy: 0.19556714471968709
Delta: 0.00202123731393498 	  Loss: 1.6032433159315884 	 Accuracy: 0.196870925684485
Delta: 0.002194174451771579 	  Loss: 1.6032371529598923 	 Accuracy: 0.196870925684485
Delta: 6.185029636651264e-06 	  Loss: 1.6032448230532625 	 Accuracy: 0.196870925684485
Delta: 1.1498330853084966e-05 	  Loss: 1.6032670180972155 	 Accuracy: 0.19556714471968709
Delta: 0.0022466105459590683 	  Loss: 1.6025062761180284 	 Accuracy: 0.196870925684485
Delta: 0.0023110200387815756 	  Loss: 1.6031511469518436 	 Accuracy: 0.196870925684485
Delta: 5.322293892617561e-05 	  Loss: 1.6032368906277155 	 Accuracy: 0.196870925684485
Delta: 9.463211849186821e-08 	  Loss: 1.6032367728424635 	 Accuracy: 0.196870925684485
Delta: 0.0008035048986665314 	  Loss: 1.603129481552167 	 Accuracy: 0.19556714471968709
Delta: 3.150492600919947e-05 	  Loss: 1.6032358750900078 	 Accuracy: 0.196870925684485
Delta: 0.0021229961289681806 	  Loss: 1.6032505781454274 	 Accuracy: 0.20078226857887874
Delta: 0.0014952757682856316 	  Loss: 1.603736942139717 	 Accuracy: 0.196870925684485
Delta: 0.0005562521728893754 	  Loss: 1.6032056875478458 	 Accuracy: 0.196870925684485
Delta: 0.001347692621998765 	  Loss: 1.6032259932202524 	 Accuracy: 0.196870925684485
Delta: 4.194734058936708e-05 	  Loss: 1.6032603391624582 	 Accuracy: 0.196870925684485
Delta: 1.8877541708671099e-06 	  Loss: 1.6032558673809933 	 Accuracy: 0.1981747066492829
Delta: 0.00204253927264812 	  Loss: 1.6031126269288138 	 Accuracy: 0.1981747066492829
Delta: 0.004036989751914371 	  Loss: 1.6027844885418074 	 Accuracy: 0.196870925684485
Delta: 0.0034384429970657233 	  Loss: 1.6030939200986802 	 Accuracy: 0.196870925684485
Delta: 0.0031114642920698284 	  Loss: 1.6032347794064958 	 Accuracy: 0.196870925684485
Delta: 9.030834160791385e-06 	  Loss: 1.6032342887091042 	 Accuracy: 0.196870925684485
Delta: 7.442552889956211e-07 	  Loss: 1.603233673830695 	 Accuracy: 0.196870925684485
Delta: 6.767121095676446e-05 	  Loss: 1.6034415405643818 	 Accuracy: 0.196870925684485
Delta: 0.00321838033671974 	  Loss: 1.6038336314078219 	 Accuracy: 0.20078226857887874
Delta: 0.0024801474959009343 	  Loss: 1.6037523414968278 	 Accuracy: 0.196870925684485
Delta: 0.0023319728828181626 	  Loss: 1.6037891359636756 	 Accuracy: 0.19556714471968709
Delta: 0.0030595449006861567 	  Loss: 1.6042737893762227 	 Accuracy: 0.19556714471968709
Delta: 0.0035465467708286325 	  Loss: 1.6036343571152463 	 Accuracy: 0.19556714471968709
Delta: 0.0016779429288276686 	  Loss: 1.6035158760355983 	 Accuracy: 0.19556714471968709
Delta: 0.020938406191681577 	  Loss: 2.1600196589571143 	 Accuracy: 0.16558018252933507
Delta: 0.018627821809752157 	  Loss: 2.0759783110064975 	 Accuracy: 0.13820078226857888
Delta: 0.016994073475218627 	  Loss: 1.9347375327684246 	 Accuracy: 0.1316818774445893
Delta: 0.015764556025785192 	  Loss: 1.7921162533472748 	 Accuracy: 0.1421121251629726
Delta: 0.014544938568254475 	  Loss: 1.6919779948572589 	 Accuracy: 0.14863102998696218
Delta: 0.012561488958520892 	  Loss: 1.6277733113607287 	 Accuracy: 0.15645371577574968
Delta: 0.010423860675286523 	  Loss: 1.597694326253626 	 Accuracy: 0.17992177314211213
Delta: 0.008191349181515706 	  Loss: 1.5874180027338411 	 Accuracy: 0.18252933507170796
Delta: 0.006524487034554172 	  Loss: 1.584303308143178 	 Accuracy: 0.18122555410691005

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006325314590958615 	  Loss: 1.5829854726224517 	 Accuracy: 0.17992177314211213
Delta: 0.005560007197581856 	  Loss: 1.5822848454698906 	 Accuracy: 0.1773142112125163
Delta: 0.004200819592413467 	  Loss: 1.5821328237996122 	 Accuracy: 0.1773142112125163
Delta: 0.004287527176895764 	  Loss: 1.5816862535401257 	 Accuracy: 0.17992177314211213
Delta: 0.0033367779059666927 	  Loss: 1.5815879987538257 	 Accuracy: 0.1773142112125163
Delta: 0.002502442752297417 	  Loss: 1.5816281609203846 	 Accuracy: 0.1760104302477184
Delta: 0.0038049604795891132 	  Loss: 1.5815086371563951 	 Accuracy: 0.1760104302477184
Delta: 0.0019684399935691304 	  Loss: 1.5813927023055219 	 Accuracy: 0.1773142112125163
Delta: 0.0005228771753594106 	  Loss: 1.5814455672690677 	 Accuracy: 0.1773142112125163
Delta: 0.0005427461064917968 	  Loss: 1.5814327425391528 	 Accuracy: 0.1773142112125163
Delta: 1.6583574342820997e-05 	  Loss: 1.581441881409794 	 Accuracy: 0.1760104302477184
Delta: 0.0013588323580181782 	  Loss: 1.581378355740748 	 Accuracy: 0.1760104302477184
Delta: 0.0021698558381606616 	  Loss: 1.5813694480352396 	 Accuracy: 0.1760104302477184
Delta: 0.0027697868518578436 	  Loss: 1.581487660318469 	 Accuracy: 0.1773142112125163
Delta: 0.0027044229752220717 	  Loss: 1.581523308402542 	 Accuracy: 0.1773142112125163
Delta: 0.0026785297357719414 	  Loss: 1.5812933145246164 	 Accuracy: 0.1773142112125163
Delta: 0.002164995754090553 	  Loss: 1.5813672403237562 	 Accuracy: 0.1773142112125163
Delta: 0.0017851165164435561 	  Loss: 1.5812330969677844 	 Accuracy: 0.1773142112125163
Delta: 0.0024385412388930284 	  Loss: 1.581369886766283 	 Accuracy: 0.1760104302477184
Delta: 0.0026008896838437797 	  Loss: 1.581485630979045 	 Accuracy: 0.1773142112125163
Delta: 0.0021763203400795308 	  Loss: 1.581431733756575 	 Accuracy: 0.1773142112125163
Delta: 0.002653566778325932 	  Loss: 1.5815436017048972 	 Accuracy: 0.1773142112125163
Delta: 8.915012897723312e-05 	  Loss: 1.5813892701581511 	 Accuracy: 0.1773142112125163
Delta: 6.897726945863265e-05 	  Loss: 1.5814496786918255 	 Accuracy: 0.17861799217731422
Delta: 5.7959192006447964e-05 	  Loss: 1.5813506406424804 	 Accuracy: 0.1773142112125163
Delta: 0.0012061645696497063 	  Loss: 1.5814496860073244 	 Accuracy: 0.1773142112125163
Delta: 0.0010845582289181546 	  Loss: 1.5814804325767589 	 Accuracy: 0.1760104302477184
Delta: 0.0006425909382919649 	  Loss: 1.581441199492432 	 Accuracy: 0.1773142112125163
Delta: 0.0018214481094736546 	  Loss: 1.5814957838305874 	 Accuracy: 0.1773142112125163
Delta: 0.0016126179495587537 	  Loss: 1.5813944227083565 	 Accuracy: 0.1773142112125163
Delta: 0.0013489355526755224 	  Loss: 1.581298262585923 	 Accuracy: 0.1773142112125163
Delta: 0.0017131017163109893 	  Loss: 1.5814612352299013 	 Accuracy: 0.1773142112125163
Delta: 3.298484890366805e-05 	  Loss: 1.5813029003397834 	 Accuracy: 0.1773142112125163
Delta: 3.8064873297400662e-06 	  Loss: 1.5813042175880785 	 Accuracy: 0.17209908735332463
Delta: 3.9813331734682665e-05 	  Loss: 1.581326440279914 	 Accuracy: 0.1773142112125163
Delta: 4.0215561924486157e-05 	  Loss: 1.5813093001700225 	 Accuracy: 0.17470664928292046
Delta: 0.0005254179755539491 	  Loss: 1.5813414394843806 	 Accuracy: 0.18904823989569752
Delta: 0.0016876280065622265 	  Loss: 1.581387278071729 	 Accuracy: 0.18252933507170796
Delta: 0.0013173968321328656 	  Loss: 1.581315668113641 	 Accuracy: 0.1773142112125163
Delta: 3.517082416048932e-05 	  Loss: 1.58129722730553 	 Accuracy: 0.1773142112125163
Delta: 0.0012770518170376552 	  Loss: 1.5813341767442326 	 Accuracy: 0.1773142112125163
Delta: 0.002521024035070639 	  Loss: 1.5813243635443393 	 Accuracy: 0.17861799217731422
Delta: 0.002343008898064338 	  Loss: 1.5814021616157174 	 Accuracy: 0.17861799217731422
Delta: 0.0015381130062293205 	  Loss: 1.5814002754970315 	 Accuracy: 0.17861799217731422
Delta: 0.00242749713588788 	  Loss: 1.5814534674716363 	 Accuracy: 0.1773142112125163
Delta: 0.0035625456325205068 	  Loss: 1.581378187049686 	 Accuracy: 0.1760104302477184
Delta: 0.0022326534648383365 	  Loss: 1.5815297578298724 	 Accuracy: 0.17470664928292046
Delta: 0.004859269434086428 	  Loss: 1.5809961642327943 	 Accuracy: 0.17861799217731422
Delta: 0.0026863014032240265 	  Loss: 1.5811335847155976 	 Accuracy: 0.17861799217731422
Delta: 0.005135086376198107 	  Loss: 1.5816611067627653 	 Accuracy: 0.17470664928292046
Delta: 0.003580854809317346 	  Loss: 1.5817798540934387 	 Accuracy: 0.17992177314211213
Delta: 0.0012336359438739422 	  Loss: 1.5817943571444482 	 Accuracy: 0.17861799217731422
Delta: 0.005442769296105331 	  Loss: 1.581707569695506 	 Accuracy: 0.17079530638852672
Delta: 0.002973939548150728 	  Loss: 1.5814890251878009 	 Accuracy: 0.17992177314211213
Delta: 0.0035689288368108666 	  Loss: 1.5818474561923705 	 Accuracy: 0.17992177314211213
Delta: 0.004352192983843205 	  Loss: 1.582783122508545 	 Accuracy: 0.17992177314211213
Delta: 0.004282200053425452 	  Loss: 1.582653655799338 	 Accuracy: 0.17209908735332463
Delta: 0.003523161607305901 	  Loss: 1.5824961950654246 	 Accuracy: 0.17861799217731422
Delta: 0.0028013351957761096 	  Loss: 1.5817225173145866 	 Accuracy: 0.17861799217731422
Delta: 0.004902930713977726 	  Loss: 1.581577330502157 	 Accuracy: 0.1773142112125163
Delta: 0.002930736722080192 	  Loss: 1.5818081823519532 	 Accuracy: 0.1760104302477184
Delta: 0.0023465525298105193 	  Loss: 1.581722537944893 	 Accuracy: 0.1773142112125163
Delta: 0.00322088041609804 	  Loss: 1.5819501653817443 	 Accuracy: 0.17340286831812254
Delta: 0.0009042412898624931 	  Loss: 1.5818721458266995 	 Accuracy: 0.1760104302477184
Delta: 1.255655890620654e-05 	  Loss: 1.5818847030908472 	 Accuracy: 0.1760104302477184
Delta: 0.0012132093363828862 	  Loss: 1.5819156016667288 	 Accuracy: 0.1760104302477184
Delta: 0.0013906531996438515 	  Loss: 1.5818450471635623 	 Accuracy: 0.1760104302477184
Delta: 4.977877875076614e-05 	  Loss: 1.581867724713085 	 Accuracy: 0.17340286831812254
Delta: 2.4942422548799867e-06 	  Loss: 1.5818591591804405 	 Accuracy: 0.1760104302477184
Delta: 2.496546012742363e-06 	  Loss: 1.5818677364698375 	 Accuracy: 0.17992177314211213
Delta: 0.0010775739421075398 	  Loss: 1.5819765034743467 	 Accuracy: 0.1760104302477184
Delta: 7.380844872856693e-05 	  Loss: 1.581836654862137 	 Accuracy: 0.1760104302477184
Delta: 7.72982012583242e-05 	  Loss: 1.5818665513427868 	 Accuracy: 0.18122555410691005
Delta: 0.002644216357937177 	  Loss: 1.581895460745947 	 Accuracy: 0.1773142112125163
Delta: 0.0020992173049111497 	  Loss: 1.58178603635018 	 Accuracy: 0.1760104302477184
Delta: 4.462290265133417e-05 	  Loss: 1.5817196820034336 	 Accuracy: 0.18252933507170796
Delta: 0.0005741985310553372 	  Loss: 1.581747022202963 	 Accuracy: 0.1773142112125163
Delta: 0.003886029990925129 	  Loss: 1.582494182972008 	 Accuracy: 0.17079530638852672
Delta: 0.0040673414528468775 	  Loss: 1.5831780019507895 	 Accuracy: 0.1760104302477184
Delta: 0.0037335094436145404 	  Loss: 1.5819578266418541 	 Accuracy: 0.1760104302477184
Delta: 0.0016685686411842123 	  Loss: 1.581966995719697 	 Accuracy: 0.1760104302477184
Delta: 0.0006572935628860742 	  Loss: 1.5818816553059303 	 Accuracy: 0.17861799217731422
Delta: 5.226511071337274e-05 	  Loss: 1.581964384254622 	 Accuracy: 0.1773142112125163
Delta: 9.340069043498195e-06 	  Loss: 1.5819462210454531 	 Accuracy: 0.1773142112125163
Delta: 2.4781607404075962e-05 	  Loss: 1.581984981314858 	 Accuracy: 0.1773142112125163
Delta: 4.6054695539336145e-05 	  Loss: 1.5819714498113977 	 Accuracy: 0.1760104302477184
Delta: 0.0034597200774773938 	  Loss: 1.5826178421107668 	 Accuracy: 0.1760104302477184
Delta: 0.002048813688900396 	  Loss: 1.5823611730559708 	 Accuracy: 0.1773142112125163
Delta: 0.0034850194723429536 	  Loss: 1.58205094905739 	 Accuracy: 0.17470664928292046
Delta: 3.4962863490918106e-05 	  Loss: 1.5820658077224754 	 Accuracy: 0.1760104302477184
Delta: 1.4808433723394935e-05 	  Loss: 1.5820059056014393 	 Accuracy: 0.1760104302477184
Delta: 0.020972687624717313 	  Loss: 2.160360562763439 	 Accuracy: 0.1773142112125163
Delta: 0.01875989281343078 	  Loss: 2.073501333995207 	 Accuracy: 0.11082138200782268
Delta: 0.017094178250893637 	  Loss: 1.9267959659361664 	 Accuracy: 0.15384615384615385
Delta: 0.015808794336599884 	  Loss: 1.7912776772431576 	 Accuracy: 0.17992177314211213
Delta: 0.0145284832089273 	  Loss: 1.6920797923393518 	 Accuracy: 0.18252933507170796
Delta: 0.012499673299941973 	  Loss: 1.6302937406253843 	 Accuracy: 0.1773142112125163
Delta: 0.009771359823079282 	  Loss: 1.6051903146704634 	 Accuracy: 0.16297262059973924

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007330231791799703 	  Loss: 1.5965822513995684 	 Accuracy: 0.16036505867014342
Delta: 0.0066862238171101875 	  Loss: 1.5940020003728836 	 Accuracy: 0.1681877444589309
Delta: 0.005398471854140456 	  Loss: 1.5939291772664856 	 Accuracy: 0.16688396349413298
Delta: 0.003950115990557813 	  Loss: 1.5935684270374646 	 Accuracy: 0.16688396349413298
Delta: 0.003009892082853557 	  Loss: 1.5935912470356894 	 Accuracy: 0.16688396349413298
Delta: 0.001793361034062923 	  Loss: 1.5935492511011704 	 Accuracy: 0.16688396349413298
Delta: 0.003710358473930546 	  Loss: 1.5935593637535457 	 Accuracy: 0.16688396349413298
Delta: 3.4807117414440096e-05 	  Loss: 1.5935568447841242 	 Accuracy: 0.1681877444589309
Delta: 5.832913131965417e-05 	  Loss: 1.5936335350045177 	 Accuracy: 0.16688396349413298
Delta: 0.0010776499422622094 	  Loss: 1.5936098826201048 	 Accuracy: 0.16688396349413298
Delta: 0.0019790541540519444 	  Loss: 1.593249263220138 	 Accuracy: 0.16688396349413298
Delta: 0.0007550428628395597 	  Loss: 1.5934494123392602 	 Accuracy: 0.18383311603650587
Delta: 0.0008274234478090955 	  Loss: 1.593330849416116 	 Accuracy: 0.16688396349413298
Delta: 0.002976066591238452 	  Loss: 1.5935380998897477 	 Accuracy: 0.16688396349413298
Delta: 0.0021420384782563496 	  Loss: 1.5933856997970177 	 Accuracy: 0.16688396349413298
Delta: 0.000808651957652881 	  Loss: 1.5934993108228581 	 Accuracy: 0.16688396349413298
Delta: 3.541782911492305e-05 	  Loss: 1.5933853548793475 	 Accuracy: 0.16688396349413298
Delta: 0.0008027337852325649 	  Loss: 1.5935309207533668 	 Accuracy: 0.1681877444589309
Delta: 8.072237642061225e-05 	  Loss: 1.593464036467874 	 Accuracy: 0.16688396349413298
Delta: 8.600611748575688e-05 	  Loss: 1.5932816571687067 	 Accuracy: 0.1694915254237288
Delta: 0.0016459971119325368 	  Loss: 1.5933191917207676 	 Accuracy: 0.1694915254237288
Delta: 0.000807157935627511 	  Loss: 1.5932775692109473 	 Accuracy: 0.16688396349413298
Delta: 0.0010908251651091144 	  Loss: 1.5933568217250156 	 Accuracy: 0.16688396349413298
Delta: 3.0406040297124663e-05 	  Loss: 1.5934801671827072 	 Accuracy: 0.16688396349413298
Delta: 0.0014044179919373756 	  Loss: 1.5936513355102386 	 Accuracy: 0.1681877444589309
Delta: 9.222319477682726e-05 	  Loss: 1.5933646707843918 	 Accuracy: 0.16688396349413298
Delta: 0.0006691932211676532 	  Loss: 1.5932637282144915 	 Accuracy: 0.16688396349413298
Delta: 3.882654862537277e-05 	  Loss: 1.5934275179146158 	 Accuracy: 0.1590612777053455
Delta: 0.003473178202339795 	  Loss: 1.5935245706569447 	 Accuracy: 0.16688396349413298
Delta: 0.0017461887255269084 	  Loss: 1.593241140171559 	 Accuracy: 0.16688396349413298
Delta: 0.0005332499183072308 	  Loss: 1.5932994567057277 	 Accuracy: 0.16688396349413298
Delta: 0.001399843134742811 	  Loss: 1.593542128985571 	 Accuracy: 0.16688396349413298
Delta: 0.0010052664332428755 	  Loss: 1.5932760813051463 	 Accuracy: 0.1681877444589309
Delta: 4.157464561364715e-05 	  Loss: 1.5932978708154146 	 Accuracy: 0.16688396349413298
Delta: 4.726399710785407e-05 	  Loss: 1.593242824051822 	 Accuracy: 0.16688396349413298
Delta: 0.0011754282545742714 	  Loss: 1.5931781530354368 	 Accuracy: 0.16688396349413298
Delta: 0.0032265292668939324 	  Loss: 1.593149941615433 	 Accuracy: 0.16688396349413298
Delta: 0.0025963444929671684 	  Loss: 1.593003253303618 	 Accuracy: 0.16688396349413298
Delta: 0.0037771246921013972 	  Loss: 1.5930926050744882 	 Accuracy: 0.15514993481095177
Delta: 0.0038676191556208683 	  Loss: 1.593016233405895 	 Accuracy: 0.16427640156453716
Delta: 0.0014391979419167119 	  Loss: 1.5927805002490825 	 Accuracy: 0.16166883963494133
Delta: 0.003336889958428346 	  Loss: 1.5931103100331296 	 Accuracy: 0.16427640156453716
Delta: 0.0009493897708453799 	  Loss: 1.593141500908911 	 Accuracy: 0.16427640156453716
Delta: 0.0025183131724818898 	  Loss: 1.5929478081233372 	 Accuracy: 0.18252933507170796
Delta: 0.002356649731155463 	  Loss: 1.593179450053222 	 Accuracy: 0.16297262059973924
Delta: 0.0038139734880335745 	  Loss: 1.593056854102357 	 Accuracy: 0.16297262059973924
Delta: 0.0033226393636968518 	  Loss: 1.5930184733226351 	 Accuracy: 0.16427640156453716
Delta: 6.0541622588006454e-05 	  Loss: 1.5929997032592862 	 Accuracy: 0.16427640156453716
Delta: 5.682391136961651e-05 	  Loss: 1.5930879397576168 	 Accuracy: 0.16427640156453716
Delta: 0.0012550120842935943 	  Loss: 1.5930027136937128 	 Accuracy: 0.16427640156453716
Delta: 0.0006124487780950949 	  Loss: 1.592997310300257 	 Accuracy: 0.16427640156453716
Delta: 1.0927802693878638e-05 	  Loss: 1.5929866260981456 	 Accuracy: 0.16166883963494133
Delta: 8.086178884422583e-05 	  Loss: 1.5930907440415605 	 Accuracy: 0.16427640156453716
Delta: 0.0020429612197662246 	  Loss: 1.5931322961742485 	 Accuracy: 0.16427640156453716
Delta: 8.043616016948487e-05 	  Loss: 1.5930688816273153 	 Accuracy: 0.16427640156453716
Delta: 6.582593082310437e-07 	  Loss: 1.5930677979674202 	 Accuracy: 0.16427640156453716
Delta: 0.0005236993397628428 	  Loss: 1.5931456872338545 	 Accuracy: 0.16427640156453716
Delta: 3.797977172563287e-05 	  Loss: 1.5930136689441454 	 Accuracy: 0.16297262059973924
Delta: 0.004928255563292785 	  Loss: 1.5942604593790044 	 Accuracy: 0.16558018252933507
Delta: 0.004054186065297927 	  Loss: 1.5940929517171687 	 Accuracy: 0.16166883963494133
Delta: 0.0033578184234263507 	  Loss: 1.5939022614169762 	 Accuracy: 0.16427640156453716
Delta: 0.0034960164836757195 	  Loss: 1.594436916131313 	 Accuracy: 0.16427640156453716
Delta: 0.0020457463539175773 	  Loss: 1.5940259347343035 	 Accuracy: 0.16427640156453716
Delta: 0.001979301478819611 	  Loss: 1.5938430429440953 	 Accuracy: 0.16427640156453716
Delta: 0.002054637502460102 	  Loss: 1.5939421943184098 	 Accuracy: 0.16558018252933507
Delta: 0.0011061408913106165 	  Loss: 1.5938432932526883 	 Accuracy: 0.16427640156453716
Delta: 1.3729731639707222e-05 	  Loss: 1.5938459894806263 	 Accuracy: 0.16427640156453716
Delta: 1.8991991020729438e-06 	  Loss: 1.5938404437707387 	 Accuracy: 0.1694915254237288
Delta: 0.002646784395155812 	  Loss: 1.5937998601290837 	 Accuracy: 0.16427640156453716
Delta: 0.0009092332371859292 	  Loss: 1.5938400711491347 	 Accuracy: 0.16166883963494133
Delta: 0.0026473440994654518 	  Loss: 1.5938739109021811 	 Accuracy: 0.16427640156453716
Delta: 0.0007294377256345015 	  Loss: 1.5938303153162021 	 Accuracy: 0.16166883963494133
Delta: 0.005065286858768636 	  Loss: 1.594651641810492 	 Accuracy: 0.16297262059973924
Delta: 0.004993654755479504 	  Loss: 1.5935407322835262 	 Accuracy: 0.16558018252933507
Delta: 0.001682247719346058 	  Loss: 1.5935666013982308 	 Accuracy: 0.16166883963494133
Delta: 0.004547186006295454 	  Loss: 1.5933283905112234 	 Accuracy: 0.16427640156453716
Delta: 0.002631438013304079 	  Loss: 1.5934143057000916 	 Accuracy: 0.16427640156453716
Delta: 0.0009165835937316788 	  Loss: 1.5934188473591755 	 Accuracy: 0.16427640156453716
Delta: 7.0848653626159e-05 	  Loss: 1.59341558229353 	 Accuracy: 0.16688396349413298
Delta: 0.004945796310747982 	  Loss: 1.593849354114338 	 Accuracy: 0.16427640156453716
Delta: 0.0005200123059590969 	  Loss: 1.5939450692136714 	 Accuracy: 0.16558018252933507
Delta: 0.0029279156831273166 	  Loss: 1.594491844722221 	 Accuracy: 0.16688396349413298
Delta: 0.0026018097563645154 	  Loss: 1.594890182158247 	 Accuracy: 0.15254237288135594
Delta: 0.0027213751004579734 	  Loss: 1.5948161426260987 	 Accuracy: 0.16558018252933507
Delta: 0.0047424960153520405 	  Loss: 1.5944609043320983 	 Accuracy: 0.16427640156453716
Delta: 0.0008965322148439654 	  Loss: 1.5944816980943004 	 Accuracy: 0.16558018252933507
Delta: 0.004261451542001245 	  Loss: 1.5938235973462924 	 Accuracy: 0.16558018252933507
Delta: 0.001441389926713366 	  Loss: 1.5942271117942366 	 Accuracy: 0.16558018252933507
Delta: 0.0012091631672550664 	  Loss: 1.5940365020766087 	 Accuracy: 0.16427640156453716
Delta: 0.005671527030570935 	  Loss: 1.5945545135642452 	 Accuracy: 0.17079530638852672
Delta: 0.0034508703758798645 	  Loss: 1.5951727961425823 	 Accuracy: 0.16558018252933507
Delta: 0.0039030980544716874 	  Loss: 1.595097860955522 	 Accuracy: 0.1694915254237288
Delta: 0.003267412409580762 	  Loss: 1.5951875980194532 	 Accuracy: 0.16688396349413298
Delta: 0.021040352559706484 	  Loss: 2.159257640570721 	 Accuracy: 0.17992177314211213
Delta: 0.0185875514126785 	  Loss: 2.0651664993477246 	 Accuracy: 0.15254237288135594
Delta: 0.016949706158130993 	  Loss: 1.907105192760071 	 Accuracy: 0.13559322033898305
Delta: 0.015932030989452485 	  Loss: 1.761189736210425 	 Accuracy: 0.1577574967405476
Delta: 0.013863423451376871 	  Loss: 1.6774729735136802 	 Accuracy: 0.16427640156453716
Delta: 0.01148057068328747 	  Loss: 1.6426184049057624 	 Accuracy: 0.17209908735332463
Delta: 0.010277191907407782 	  Loss: 1.626627995772699 	 Accuracy: 0.17340286831812254

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00742044874344782 	  Loss: 1.6244035722071801 	 Accuracy: 0.17992177314211213
Delta: 0.007381568974372264 	  Loss: 1.6215759663302254 	 Accuracy: 0.1773142112125163
Delta: 0.005969999288188357 	  Loss: 1.6214854003460928 	 Accuracy: 0.17861799217731422
Delta: 0.004729161504821668 	  Loss: 1.6214153835004965 	 Accuracy: 0.1773142112125163
Delta: 0.0020565601266677113 	  Loss: 1.621385708063166 	 Accuracy: 0.1773142112125163
Delta: 0.0029623713058155973 	  Loss: 1.6216444450508978 	 Accuracy: 0.1773142112125163
Delta: 0.0028616681495045914 	  Loss: 1.6214986138568317 	 Accuracy: 0.1773142112125163
Delta: 0.004061409855286449 	  Loss: 1.621666741841081 	 Accuracy: 0.1773142112125163
Delta: 0.0018096323552085351 	  Loss: 1.621630040533524 	 Accuracy: 0.17861799217731422
Delta: 0.0009096160349495832 	  Loss: 1.621379489188756 	 Accuracy: 0.1773142112125163
Delta: 5.665947028934973e-06 	  Loss: 1.6213758879173237 	 Accuracy: 0.17861799217731422
Delta: 0.0007382800611024563 	  Loss: 1.6214915546825026 	 Accuracy: 0.17861799217731422
Delta: 4.891740807822441e-06 	  Loss: 1.6214877587479057 	 Accuracy: 0.1773142112125163
Delta: 0.0036573272840201 	  Loss: 1.6211388029117835 	 Accuracy: 0.1773142112125163
Delta: 0.003024501301730575 	  Loss: 1.6210509294207536 	 Accuracy: 0.1760104302477184
Delta: 0.0009767043828790916 	  Loss: 1.6211388452841389 	 Accuracy: 0.1773142112125163
Delta: 8.21331557613107e-05 	  Loss: 1.6210348224248259 	 Accuracy: 0.1773142112125163
Delta: 0.004138119376127708 	  Loss: 1.6204319295392091 	 Accuracy: 0.1773142112125163
Delta: 8.637524611698355e-05 	  Loss: 1.6209648509244017 	 Accuracy: 0.1773142112125163
Delta: 0.00197341556728892 	  Loss: 1.6205795619502048 	 Accuracy: 0.1773142112125163
Delta: 0.0026450021337685358 	  Loss: 1.620898379321357 	 Accuracy: 0.1773142112125163
Delta: 0.0012807844938688185 	  Loss: 1.6208858123607328 	 Accuracy: 0.1760104302477184
Delta: 0.0005431655958062637 	  Loss: 1.6206209932646387 	 Accuracy: 0.1773142112125163
Delta: 6.477286538014162e-05 	  Loss: 1.6209122225710697 	 Accuracy: 0.17470664928292046
Delta: 0.0007490217819052969 	  Loss: 1.62092243619563 	 Accuracy: 0.1773142112125163
Delta: 0.0022909467763656747 	  Loss: 1.6209365337235035 	 Accuracy: 0.1773142112125163
Delta: 0.0008108486758996243 	  Loss: 1.6207474817979066 	 Accuracy: 0.1773142112125163
Delta: 0.0016537696724165235 	  Loss: 1.6208066011667897 	 Accuracy: 0.1773142112125163
Delta: 0.0005523300060985294 	  Loss: 1.6207785250380007 	 Accuracy: 0.1773142112125163
Delta: 0.004305184042608658 	  Loss: 1.6208421048930726 	 Accuracy: 0.1773142112125163
Delta: 6.1025038307956734e-05 	  Loss: 1.6207706880508443 	 Accuracy: 0.1773142112125163
Delta: 0.0029133083413815978 	  Loss: 1.6207868478963563 	 Accuracy: 0.1773142112125163
Delta: 4.889987126708792e-05 	  Loss: 1.6209424729240949 	 Accuracy: 0.17340286831812254
Delta: 0.0020665804370086395 	  Loss: 1.6210112389558737 	 Accuracy: 0.1773142112125163
Delta: 0.0020601215259053495 	  Loss: 1.620823351559836 	 Accuracy: 0.1773142112125163
Delta: 0.0016412619651664441 	  Loss: 1.6206880433674602 	 Accuracy: 0.1773142112125163
Delta: 0.0022639338950180086 	  Loss: 1.6206628881477585 	 Accuracy: 0.1773142112125163
Delta: 0.0010333654954741722 	  Loss: 1.6207508989428374 	 Accuracy: 0.1773142112125163
Delta: 0.0017051643528318626 	  Loss: 1.6207558841942098 	 Accuracy: 0.1773142112125163
Delta: 0.0008811560425966991 	  Loss: 1.6204487889126142 	 Accuracy: 0.1773142112125163
Delta: 0.0015315336166181457 	  Loss: 1.6207714374001814 	 Accuracy: 0.1773142112125163
Delta: 7.18133107683474e-05 	  Loss: 1.6207800103988448 	 Accuracy: 0.1773142112125163
Delta: 6.617313244817247e-05 	  Loss: 1.620562093860581 	 Accuracy: 0.1773142112125163
Delta: 0.001184803924481266 	  Loss: 1.6206670975215962 	 Accuracy: 0.1773142112125163
Delta: 0.0007148756149113277 	  Loss: 1.6206984864130982 	 Accuracy: 0.1773142112125163
Delta: 7.882413722874637e-05 	  Loss: 1.620684720464205 	 Accuracy: 0.1773142112125163
Delta: 0.0005710235173495694 	  Loss: 1.6208251307283859 	 Accuracy: 0.1773142112125163
Delta: 0.0008475164279220835 	  Loss: 1.6207791847938648 	 Accuracy: 0.17861799217731422
Delta: 0.004346272470873394 	  Loss: 1.6214311737140408 	 Accuracy: 0.17861799217731422
Delta: 0.001308374650691098 	  Loss: 1.6213415329658498 	 Accuracy: 0.1760104302477184
Delta: 0.0028735717745896183 	  Loss: 1.6214322009867153 	 Accuracy: 0.17861799217731422
Delta: 0.0023160382628379145 	  Loss: 1.6218987162294893 	 Accuracy: 0.17992177314211213
Delta: 0.002432566997596995 	  Loss: 1.6218461197553498 	 Accuracy: 0.1590612777053455
Delta: 0.0072852141627636645 	  Loss: 1.6274335519233807 	 Accuracy: 0.17079530638852672
Delta: 0.008006600803769172 	  Loss: 1.630986137401123 	 Accuracy: 0.17209908735332463
Delta: 0.0025011984510536337 	  Loss: 1.630924902556079 	 Accuracy: 0.1694915254237288
Delta: 0.0014930538282705054 	  Loss: 1.6311657057734115 	 Accuracy: 0.1694915254237288
Delta: 0.0019081285286875426 	  Loss: 1.6311837065853085 	 Accuracy: 0.1694915254237288
Delta: 0.001391267069852576 	  Loss: 1.631186800936824 	 Accuracy: 0.1694915254237288
Delta: 0.0009147197467205662 	  Loss: 1.6312916135016167 	 Accuracy: 0.1694915254237288
Delta: 0.0017635472628017858 	  Loss: 1.6311467947656624 	 Accuracy: 0.17079530638852672
Delta: 0.0011628988969359993 	  Loss: 1.631067749479895 	 Accuracy: 0.17209908735332463
Delta: 0.003419195291076696 	  Loss: 1.6306656103417836 	 Accuracy: 0.17079530638852672
Delta: 0.0030516315388244334 	  Loss: 1.6308653719944286 	 Accuracy: 0.1694915254237288
Delta: 0.0008030413745897829 	  Loss: 1.6308546390695007 	 Accuracy: 0.1694915254237288
Delta: 5.85815741471306e-05 	  Loss: 1.6308227634944399 	 Accuracy: 0.1694915254237288
Delta: 5.81247716120848e-05 	  Loss: 1.6308483295273266 	 Accuracy: 0.1694915254237288
Delta: 7.380225771943806e-06 	  Loss: 1.6308674864961936 	 Accuracy: 0.1694915254237288
Delta: 0.0024196020271603663 	  Loss: 1.630973950175047 	 Accuracy: 0.1694915254237288
Delta: 0.002242862049498247 	  Loss: 1.6307294391506089 	 Accuracy: 0.1694915254237288
Delta: 0.003846085885260577 	  Loss: 1.629880387571863 	 Accuracy: 0.16558018252933507
Delta: 0.0010784241956511267 	  Loss: 1.6298278043818173 	 Accuracy: 0.1694915254237288
Delta: 0.0031559106955746504 	  Loss: 1.6305084821834273 	 Accuracy: 0.1694915254237288
Delta: 0.0034403223981213267 	  Loss: 1.629813058278525 	 Accuracy: 0.1681877444589309
Delta: 3.921212126502373e-05 	  Loss: 1.6298358987926127 	 Accuracy: 0.1681877444589309
Delta: 0.0005351842164025135 	  Loss: 1.6297881048290643 	 Accuracy: 0.1681877444589309
Delta: 0.0005395677941611434 	  Loss: 1.6298370147420211 	 Accuracy: 0.1681877444589309
Delta: 0.003357231920789001 	  Loss: 1.6299628848684613 	 Accuracy: 0.1694915254237288
Delta: 0.003876069332237161 	  Loss: 1.6302863187088747 	 Accuracy: 0.1694915254237288
Delta: 0.002854662456661571 	  Loss: 1.6311095883709057 	 Accuracy: 0.1694915254237288
Delta: 0.0016104854985742574 	  Loss: 1.6314898913744584 	 Accuracy: 0.16688396349413298
Delta: 0.0018544824647537255 	  Loss: 1.6322524157050888 	 Accuracy: 0.17079530638852672
Delta: 0.0020253264334814 	  Loss: 1.6314510594557028 	 Accuracy: 0.17079530638852672
Delta: 0.0014488779607569752 	  Loss: 1.6316532474071286 	 Accuracy: 0.16558018252933507
Delta: 0.0005288943631358427 	  Loss: 1.6315197083052175 	 Accuracy: 0.1694915254237288
Delta: 2.472223547952388e-05 	  Loss: 1.631403576914246 	 Accuracy: 0.1773142112125163
Delta: 0.0009247277810734544 	  Loss: 1.6314212281532936 	 Accuracy: 0.1694915254237288
Delta: 0.0005665705215239612 	  Loss: 1.6316001540073675 	 Accuracy: 0.1694915254237288
Delta: 5.620454796126199e-05 	  Loss: 1.631550926634981 	 Accuracy: 0.1694915254237288
Delta: 0.0009934062117503831 	  Loss: 1.631520893311289 	 Accuracy: 0.1694915254237288
Delta: 0.0005652753605564086 	  Loss: 1.6316278158810538 	 Accuracy: 0.1694915254237288
Delta: 0.0005195840875243445 	  Loss: 1.6314995553710374 	 Accuracy: 0.17079530638852672
Delta: 0.002147804272638143 	  Loss: 1.631362317657227 	 Accuracy: 0.1694915254237288
Delta: 0.02106766399533783 	  Loss: 2.1587434130974112 	 Accuracy: 0.16688396349413298
Delta: 0.018986886702324405 	  Loss: 2.0624294811250463 	 Accuracy: 0.1681877444589309
Delta: 0.01735559403637089 	  Loss: 1.892874299757636 	 Accuracy: 0.19947848761408082
Delta: 0.015156806406953304 	  Loss: 1.7653930436320056 	 Accuracy: 0.1864406779661017
Delta: 0.013799984040408263 	  Loss: 1.7014787401495157 	 Accuracy: 0.19165580182529335
Delta: 0.012577855675317794 	  Loss: 1.6707725533698738 	 Accuracy: 0.19947848761408082

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010105741590757162 	  Loss: 1.654966262720683 	 Accuracy: 0.2151238591916558
Delta: 0.008745117567113837 	  Loss: 1.6478254346795183 	 Accuracy: 0.2033898305084746
Delta: 0.006261854993056479 	  Loss: 1.6456593184314359 	 Accuracy: 0.2046936114732725
Delta: 0.004924422819816923 	  Loss: 1.6448480989384051 	 Accuracy: 0.2046936114732725
Delta: 0.004060694733386983 	  Loss: 1.644787603500005 	 Accuracy: 0.2046936114732725
Delta: 0.0030306465389467077 	  Loss: 1.6449358111808867 	 Accuracy: 0.2046936114732725
Delta: 0.0028329993403227 	  Loss: 1.6451743142358148 	 Accuracy: 0.2046936114732725
Delta: 0.0017517975642554323 	  Loss: 1.6452014594811926 	 Accuracy: 0.20599739243807041
Delta: 0.0020235139433748385 	  Loss: 1.64524095514 	 Accuracy: 0.2046936114732725
Delta: 0.002314073605280238 	  Loss: 1.6452969478547548 	 Accuracy: 0.2046936114732725
Delta: 0.002576473486693649 	  Loss: 1.6455469259440454 	 Accuracy: 0.2046936114732725
Delta: 0.0017825979873316096 	  Loss: 1.64560469520448 	 Accuracy: 0.2046936114732725
Delta: 0.002749581031103239 	  Loss: 1.6452950479529203 	 Accuracy: 0.2046936114732725
Delta: 0.0016944491295665732 	  Loss: 1.645291825166738 	 Accuracy: 0.2046936114732725
Delta: 0.0005815488179732517 	  Loss: 1.6456576608278823 	 Accuracy: 0.2046936114732725
Delta: 0.0016724335152575878 	  Loss: 1.6456972895113506 	 Accuracy: 0.2033898305084746
Delta: 0.004496213123602976 	  Loss: 1.645910720835849 	 Accuracy: 0.2033898305084746
Delta: 0.0018860469995345722 	  Loss: 1.6458623150198948 	 Accuracy: 0.2033898305084746
Delta: 0.0017988339497324196 	  Loss: 1.6456288550732996 	 Accuracy: 0.2033898305084746
Delta: 0.003583919883944144 	  Loss: 1.6458516790387878 	 Accuracy: 0.20208604954367665
Delta: 0.0011664964339761002 	  Loss: 1.6457221348420035 	 Accuracy: 0.2033898305084746
Delta: 0.0012296084374711907 	  Loss: 1.6457652709935178 	 Accuracy: 0.2046936114732725
Delta: 5.26754265669283e-05 	  Loss: 1.6456083187063772 	 Accuracy: 0.2046936114732725
Delta: 0.0014242012098894963 	  Loss: 1.645646944444403 	 Accuracy: 0.20599739243807041
Delta: 2.7108492335718247e-05 	  Loss: 1.6456022649565056 	 Accuracy: 0.196870925684485
Delta: 0.004007660599637604 	  Loss: 1.6456234630292643 	 Accuracy: 0.2046936114732725
Delta: 0.004186120829606064 	  Loss: 1.6453810484905829 	 Accuracy: 0.2046936114732725
Delta: 0.0024430569137883114 	  Loss: 1.6448888472655314 	 Accuracy: 0.2046936114732725
Delta: 0.004480245944611768 	  Loss: 1.6445162281813495 	 Accuracy: 0.2033898305084746
Delta: 0.001402740834574195 	  Loss: 1.6448041552899282 	 Accuracy: 0.2046936114732725
Delta: 0.0022092011536071284 	  Loss: 1.6446109143161705 	 Accuracy: 0.2046936114732725
Delta: 0.003920203299323136 	  Loss: 1.6449480710580624 	 Accuracy: 0.20599739243807041
Delta: 0.0039869535260774035 	  Loss: 1.6449086044423913 	 Accuracy: 0.20730117340286833
Delta: 0.0016655094403156823 	  Loss: 1.6446996584906959 	 Accuracy: 0.20599739243807041
Delta: 0.0008056094368462953 	  Loss: 1.6447285644823357 	 Accuracy: 0.20599739243807041
Delta: 0.0032801795984219967 	  Loss: 1.6454386795306768 	 Accuracy: 0.20599739243807041
Delta: 0.0010966997089058828 	  Loss: 1.6446131984324 	 Accuracy: 0.2046936114732725
Delta: 0.0025966286426906283 	  Loss: 1.6444830587878463 	 Accuracy: 0.2046936114732725
Delta: 0.004607140887852217 	  Loss: 1.6447940129688998 	 Accuracy: 0.2046936114732725
Delta: 0.0022877227918855444 	  Loss: 1.6446503608520535 	 Accuracy: 0.2046936114732725
Delta: 0.0016691117441550746 	  Loss: 1.6449303260484052 	 Accuracy: 0.2033898305084746
Delta: 0.0017822660430043948 	  Loss: 1.6449731309203373 	 Accuracy: 0.2033898305084746
Delta: 0.0013760325996041182 	  Loss: 1.6450413596204747 	 Accuracy: 0.20599739243807041
Delta: 0.0006461054326180584 	  Loss: 1.645055764263177 	 Accuracy: 0.2033898305084746
Delta: 0.0005707898952409698 	  Loss: 1.6448083163673795 	 Accuracy: 0.20078226857887874
Delta: 0.003685578701135749 	  Loss: 1.6438783561804118 	 Accuracy: 0.2033898305084746
Delta: 0.0013481649028139493 	  Loss: 1.6440716374565059 	 Accuracy: 0.2033898305084746
Delta: 0.0017533491715401224 	  Loss: 1.6437657261886673 	 Accuracy: 0.2033898305084746
Delta: 0.001355230294356401 	  Loss: 1.6443058383303104 	 Accuracy: 0.22294654498044328
Delta: 0.0005292147441922843 	  Loss: 1.6442243691556606 	 Accuracy: 0.2033898305084746
Delta: 0.0005806705065368864 	  Loss: 1.643972849275538 	 Accuracy: 0.2033898305084746
Delta: 0.0015390614522462261 	  Loss: 1.6435981883763113 	 Accuracy: 0.2033898305084746
Delta: 0.0036795546608548776 	  Loss: 1.642873150613772 	 Accuracy: 0.2033898305084746
Delta: 0.0010350598747317769 	  Loss: 1.6427539376529754 	 Accuracy: 0.2033898305084746
Delta: 0.002508096216917256 	  Loss: 1.6440638052834677 	 Accuracy: 0.2046936114732725
Delta: 0.002043256195190974 	  Loss: 1.6435755317940726 	 Accuracy: 0.2046936114732725
Delta: 0.00011113867850563796 	  Loss: 1.6441586554736998 	 Accuracy: 0.2046936114732725
Delta: 0.002425942110228293 	  Loss: 1.6442282399437589 	 Accuracy: 0.20599739243807041
Delta: 0.0039025539011810126 	  Loss: 1.6444499863488056 	 Accuracy: 0.20599739243807041
Delta: 0.0036598822154979287 	  Loss: 1.6439027425764736 	 Accuracy: 0.20599739243807041
Delta: 0.003467951190638955 	  Loss: 1.6445162949183874 	 Accuracy: 0.2046936114732725
Delta: 0.0016458109079269874 	  Loss: 1.6440637862710497 	 Accuracy: 0.20599739243807041
Delta: 0.003601780746742823 	  Loss: 1.64406455424518 	 Accuracy: 0.20599739243807041
Delta: 0.0012979922802172418 	  Loss: 1.6439296891619477 	 Accuracy: 0.20599739243807041
Delta: 0.003290419048382316 	  Loss: 1.6441271050093773 	 Accuracy: 0.20599739243807041
Delta: 0.003612325604100868 	  Loss: 1.6445666394400869 	 Accuracy: 0.20599739243807041
Delta: 0.0015674339388679016 	  Loss: 1.644602595740823 	 Accuracy: 0.20990873533246415
Delta: 0.004115737712141186 	  Loss: 1.6452979453912555 	 Accuracy: 0.21251629726205998
Delta: 0.004214038410417321 	  Loss: 1.6444603998574 	 Accuracy: 0.20860495436766624
Delta: 0.0011534494225015398 	  Loss: 1.6446806435624803 	 Accuracy: 0.20990873533246415
Delta: 0.0005507436963115763 	  Loss: 1.6445515525936378 	 Accuracy: 0.20730117340286833
Delta: 0.0017842711748261369 	  Loss: 1.644868152521982 	 Accuracy: 0.20730117340286833
Delta: 0.0025955229448757135 	  Loss: 1.6452636191299208 	 Accuracy: 0.20990873533246415
Delta: 0.0028102190814285237 	  Loss: 1.6453124403019084 	 Accuracy: 0.20730117340286833
Delta: 0.001973350810024327 	  Loss: 1.6448092562848795 	 Accuracy: 0.20730117340286833
Delta: 0.0009562088190241826 	  Loss: 1.6448608370458404 	 Accuracy: 0.20730117340286833
Delta: 0.0006686492326685062 	  Loss: 1.6449766746118237 	 Accuracy: 0.20860495436766624
Delta: 0.0019654617361529484 	  Loss: 1.6457696363494938 	 Accuracy: 0.20860495436766624
Delta: 0.0013184724203130558 	  Loss: 1.6461355699214177 	 Accuracy: 0.20730117340286833
Delta: 0.000997949501389733 	  Loss: 1.6453035377324352 	 Accuracy: 0.20599739243807041
Delta: 0.0009274084951395355 	  Loss: 1.6449305160041718 	 Accuracy: 0.2033898305084746
Delta: 0.0007913627580032329 	  Loss: 1.6456279357953005 	 Accuracy: 0.20860495436766624
Delta: 0.0032460731938048657 	  Loss: 1.6463116372050146 	 Accuracy: 0.20208604954367665
Delta: 0.0023097327373897913 	  Loss: 1.6453315913975302 	 Accuracy: 0.20730117340286833
Delta: 0.0015988092757527638 	  Loss: 1.6447712944155142 	 Accuracy: 0.20860495436766624
Delta: 0.0032910230507880553 	  Loss: 1.644439365412478 	 Accuracy: 0.20990873533246415
Delta: 0.0030287022369991454 	  Loss: 1.6448213624906507 	 Accuracy: 0.20860495436766624
Delta: 0.003253400354321684 	  Loss: 1.6453805850250756 	 Accuracy: 0.20860495436766624
Delta: 0.0017200462797791042 	  Loss: 1.6453189515377002 	 Accuracy: 0.20860495436766624
Delta: 0.00228813980956916 	  Loss: 1.6448746739173032 	 Accuracy: 0.2046936114732725
Delta: 0.005004820349392058 	  Loss: 1.6469780975232877 	 Accuracy: 0.20860495436766624
Delta: 0.0015965230434087357 	  Loss: 1.6468094888236116 	 Accuracy: 0.20990873533246415
Delta: 0.0033464328017743968 	  Loss: 1.647295657650902 	 Accuracy: 0.20860495436766624
Delta: 0.0033535850453368507 	  Loss: 1.6479475719631744 	 Accuracy: 0.20860495436766624
Delta: 0.02098374219526165 	  Loss: 2.159111545397713 	 Accuracy: 0.13559322033898305
Delta: 0.018756343409871718 	  Loss: 2.0620245791328085 	 Accuracy: 0.15384615384615385
Delta: 0.018044478656346622 	  Loss: 1.880361332538194 	 Accuracy: 0.1681877444589309
Delta: 0.01629031309310212 	  Loss: 1.7175168780218253 	 Accuracy: 0.16166883963494133
Delta: 0.013840889674678166 	  Loss: 1.6266470572451417 	 Accuracy: 0.1773142112125163
Delta: 0.010858040542452334 	  Loss: 1.5974265716138303 	 Accuracy: 0.18513689700130379

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009256062702587711 	  Loss: 1.589098018849835 	 Accuracy: 0.18513689700130379
Delta: 0.006593700628519185 	  Loss: 1.587113363845403 	 Accuracy: 0.18252933507170796
Delta: 0.0048410758458470576 	  Loss: 1.5864922363044949 	 Accuracy: 0.1864406779661017
Delta: 0.003995010838151355 	  Loss: 1.5866554543818587 	 Accuracy: 0.18513689700130379
Delta: 0.0026283849065475043 	  Loss: 1.5864064448429003 	 Accuracy: 0.18513689700130379
Delta: 0.002757056944497213 	  Loss: 1.5864663818507978 	 Accuracy: 0.18513689700130379
Delta: 0.0012217752736509977 	  Loss: 1.5865551067898516 	 Accuracy: 0.18513689700130379
Delta: 0.0016892763774263829 	  Loss: 1.5862870393160173 	 Accuracy: 0.18513689700130379
Delta: 0.0009286385786380884 	  Loss: 1.5863710343853183 	 Accuracy: 0.18513689700130379
Delta: 1.99762972662617e-05 	  Loss: 1.58635491475062 	 Accuracy: 0.18513689700130379
Delta: 9.296050963922724e-06 	  Loss: 1.5863524088556042 	 Accuracy: 0.18513689700130379
Delta: 9.972993723140715e-05 	  Loss: 1.5863395330882648 	 Accuracy: 0.18383311603650587
Delta: 0.0031289686965329205 	  Loss: 1.586185938590745 	 Accuracy: 0.18383311603650587
Delta: 0.0021120161835599203 	  Loss: 1.5861842636261319 	 Accuracy: 0.18383311603650587
Delta: 0.0005236906171613906 	  Loss: 1.5861966487103312 	 Accuracy: 0.18383311603650587
Delta: 0.0009010567804500105 	  Loss: 1.5861735137350388 	 Accuracy: 0.18383311603650587
Delta: 0.002681949738950029 	  Loss: 1.5862182225791566 	 Accuracy: 0.18383311603650587
Delta: 0.0005496948574735792 	  Loss: 1.5862929778848291 	 Accuracy: 0.18383311603650587
Delta: 0.0008532803153341517 	  Loss: 1.5862924299117442 	 Accuracy: 0.18383311603650587
Delta: 0.005682084360662757 	  Loss: 1.5862396156669178 	 Accuracy: 0.18383311603650587
Delta: 0.0032495912031018166 	  Loss: 1.5864842307213274 	 Accuracy: 0.18383311603650587
Delta: 0.0027101014348053223 	  Loss: 1.58633008354267 	 Accuracy: 0.18383311603650587
Delta: 0.001712532772474043 	  Loss: 1.5861948358549487 	 Accuracy: 0.18252933507170796
Delta: 0.0018998698647551774 	  Loss: 1.58608488912767 	 Accuracy: 0.18383311603650587
Delta: 0.0010152704077319432 	  Loss: 1.5861922652314036 	 Accuracy: 0.18383311603650587
Delta: 0.0022148234515038815 	  Loss: 1.5862410614287055 	 Accuracy: 0.18383311603650587
Delta: 0.0014045949028475603 	  Loss: 1.586083672249564 	 Accuracy: 0.18252933507170796
Delta: 0.0034900713995207238 	  Loss: 1.586279165044897 	 Accuracy: 0.18122555410691005
Delta: 0.0038036692365856517 	  Loss: 1.586479606140742 	 Accuracy: 0.18122555410691005
Delta: 0.001125509708740887 	  Loss: 1.5863566471231776 	 Accuracy: 0.18122555410691005
Delta: 0.0020426354164983416 	  Loss: 1.5866065289441602 	 Accuracy: 0.18252933507170796
Delta: 0.0011339549284720106 	  Loss: 1.58649899949017 	 Accuracy: 0.18122555410691005
Delta: 0.0014429445174086336 	  Loss: 1.5863618049935642 	 Accuracy: 0.18122555410691005
Delta: 3.631353924204906e-05 	  Loss: 1.5864148098320414 	 Accuracy: 0.18122555410691005
Delta: 3.9018995495083724e-05 	  Loss: 1.5863717041307126 	 Accuracy: 0.18122555410691005
Delta: 0.001299372693393108 	  Loss: 1.586376411802724 	 Accuracy: 0.18252933507170796
Delta: 0.0035214918191085105 	  Loss: 1.5868780305870056 	 Accuracy: 0.18122555410691005
Delta: 0.0038234543242313857 	  Loss: 1.587215827925033 	 Accuracy: 0.18122555410691005
Delta: 0.003695230852745954 	  Loss: 1.5866275370646399 	 Accuracy: 0.18122555410691005
Delta: 0.00416364946516594 	  Loss: 1.5861371123103563 	 Accuracy: 0.18122555410691005
Delta: 0.002556932693847344 	  Loss: 1.5861428521812657 	 Accuracy: 0.18122555410691005
Delta: 0.0029683469316886804 	  Loss: 1.5859008964468781 	 Accuracy: 0.18122555410691005
Delta: 0.003156339325532107 	  Loss: 1.586729520243044 	 Accuracy: 0.18122555410691005
Delta: 0.0024976471189475597 	  Loss: 1.5858363140622542 	 Accuracy: 0.18122555410691005
Delta: 0.0046682844857668495 	  Loss: 1.5871957634406262 	 Accuracy: 0.18122555410691005
Delta: 2.1536757229312892e-05 	  Loss: 1.587226941001358 	 Accuracy: 0.18122555410691005
Delta: 0.0005434954334450863 	  Loss: 1.5871734283972312 	 Accuracy: 0.18252933507170796
Delta: 0.002318645669684373 	  Loss: 1.5872434645276008 	 Accuracy: 0.18122555410691005
Delta: 0.000914446602363935 	  Loss: 1.5872550347972836 	 Accuracy: 0.18122555410691005
Delta: 4.874532852204201e-05 	  Loss: 1.587243052901274 	 Accuracy: 0.17992177314211213
Delta: 0.0028878919993479846 	  Loss: 1.5862314938023845 	 Accuracy: 0.18122555410691005
Delta: 0.002101192766091862 	  Loss: 1.5861886691909906 	 Accuracy: 0.18122555410691005
Delta: 0.0009679128800635353 	  Loss: 1.586225145989594 	 Accuracy: 0.19556714471968709
Delta: 4.4220377837990164e-05 	  Loss: 1.586131339464285 	 Accuracy: 0.1773142112125163
Delta: 0.003855916679168456 	  Loss: 1.5871635117967045 	 Accuracy: 0.18122555410691005
Delta: 0.0018149437909392543 	  Loss: 1.587242222154729 	 Accuracy: 0.18122555410691005
Delta: 5.214509617166595e-05 	  Loss: 1.5872517548766343 	 Accuracy: 0.18122555410691005
Delta: 1.4304823702492455e-08 	  Loss: 1.587251737709368 	 Accuracy: 0.18122555410691005
converged at iter  63
Delta: 0.021098803553116656 	  Loss: 2.159304666994574 	 Accuracy: 0.17470664928292046
Delta: 0.01887984946533772 	  Loss: 2.059134700979815 	 Accuracy: 0.16297262059973924
Delta: 0.017481583388654392 	  Loss: 1.8904544244085546 	 Accuracy: 0.17209908735332463
Delta: 0.01691719912489397 	  Loss: 1.7364549632792423 	 Accuracy: 0.17992177314211213
Delta: 0.013747370035114902 	  Loss: 1.639665596744235 	 Accuracy: 0.17470664928292046
Delta: 0.009840063370061448 	  Loss: 1.6112468410588554 	 Accuracy: 0.16688396349413298

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007074657970688669 	  Loss: 1.6057810085222586 	 Accuracy: 0.1760104302477184
Delta: 0.007163583933743888 	  Loss: 1.6045467511139897 	 Accuracy: 0.1694915254237288
Delta: 0.005385044540138968 	  Loss: 1.604250754510638 	 Accuracy: 0.17209908735332463
Delta: 0.0044563857496330355 	  Loss: 1.6039976080233815 	 Accuracy: 0.17079530638852672
Delta: 0.0037841278404986993 	  Loss: 1.6038348219170908 	 Accuracy: 0.1694915254237288
Delta: 0.0012080940519458873 	  Loss: 1.6035912399146286 	 Accuracy: 0.1694915254237288
Delta: 0.0026072510369220016 	  Loss: 1.6040108841173264 	 Accuracy: 0.17079530638852672
Delta: 0.002821144324757301 	  Loss: 1.6040326024675913 	 Accuracy: 0.17079530638852672
Delta: 0.0012557513371223234 	  Loss: 1.6043667235041388 	 Accuracy: 0.1694915254237288
Delta: 0.0020369138345498502 	  Loss: 1.6044745618096807 	 Accuracy: 0.17079530638852672
Delta: 0.001574250200014126 	  Loss: 1.6047054086755135 	 Accuracy: 0.17079530638852672
Delta: 0.0016232012090887332 	  Loss: 1.6046707494504886 	 Accuracy: 0.17079530638852672
Delta: 0.002431913903343706 	  Loss: 1.604861592508881 	 Accuracy: 0.17079530638852672
Delta: 0.0012884162940507377 	  Loss: 1.6048739292162892 	 Accuracy: 0.17079530638852672
Delta: 0.0029351493497538897 	  Loss: 1.6049651387281765 	 Accuracy: 0.17079530638852672
Delta: 0.0011400993833978988 	  Loss: 1.6051062550905384 	 Accuracy: 0.17079530638852672
Delta: 0.0005008550364975919 	  Loss: 1.6050944267893725 	 Accuracy: 0.17079530638852672
Delta: 2.2767327539004813e-05 	  Loss: 1.6049845874536774 	 Accuracy: 0.17079530638852672
Delta: 4.472675411240167e-05 	  Loss: 1.6049395926535936 	 Accuracy: 0.17079530638852672
Delta: 6.496670844043564e-05 	  Loss: 1.6050652626523978 	 Accuracy: 0.17079530638852672
Delta: 0.0015971479701308259 	  Loss: 1.6046730286505837 	 Accuracy: 0.17079530638852672
Delta: 0.004644839351841623 	  Loss: 1.6046700034089811 	 Accuracy: 0.17209908735332463
Delta: 0.002758529740196667 	  Loss: 1.6043586027964358 	 Accuracy: 0.17209908735332463
Delta: 0.0010577990520555993 	  Loss: 1.6046209006933578 	 Accuracy: 0.17209908735332463
Delta: 0.0021817209625600437 	  Loss: 1.6045720269654487 	 Accuracy: 0.17209908735332463
Delta: 0.0005710890212661016 	  Loss: 1.6045907914229804 	 Accuracy: 0.17209908735332463
Delta: 0.001141428950380348 	  Loss: 1.6047125337399692 	 Accuracy: 0.1681877444589309
Delta: 0.0027957347497179863 	  Loss: 1.6044435320532013 	 Accuracy: 0.17209908735332463
Delta: 0.0010876099076350943 	  Loss: 1.6043088740817302 	 Accuracy: 0.17209908735332463
Delta: 3.7659680785772136e-05 	  Loss: 1.6044050149118934 	 Accuracy: 0.17209908735332463
Delta: 5.51583354017064e-07 	  Loss: 1.6044047009099964 	 Accuracy: 0.17209908735332463
Delta: 1.4945660236383347e-05 	  Loss: 1.6043904818963324 	 Accuracy: 0.17470664928292046
Delta: 0.002678454104562456 	  Loss: 1.604336906441895 	 Accuracy: 0.17209908735332463
Delta: 0.001642972532566005 	  Loss: 1.6041141039710802 	 Accuracy: 0.17340286831812254
Delta: 0.0007438836215214482 	  Loss: 1.6041349705083958 	 Accuracy: 0.17209908735332463
Delta: 0.0019433416471528232 	  Loss: 1.6041731659828073 	 Accuracy: 0.17209908735332463
Delta: 0.0008465310642219698 	  Loss: 1.6042349031376868 	 Accuracy: 0.17209908735332463
Delta: 8.278107406582924e-05 	  Loss: 1.6042870822627457 	 Accuracy: 0.17209908735332463
Delta: 0.0005519681217747475 	  Loss: 1.6041985928627007 	 Accuracy: 0.17209908735332463
Delta: 0.0016115486483963182 	  Loss: 1.6042979543273108 	 Accuracy: 0.17209908735332463
Delta: 0.001341343253804548 	  Loss: 1.6045680928815913 	 Accuracy: 0.17079530638852672
Delta: 0.0027496472218496814 	  Loss: 1.6046794837630762 	 Accuracy: 0.17079530638852672
Delta: 5.984291179656924e-05 	  Loss: 1.6044926483935436 	 Accuracy: 0.1681877444589309
Delta: 0.0034951118515226596 	  Loss: 1.6053975066138735 	 Accuracy: 0.17340286831812254
Delta: 0.0024067646000035976 	  Loss: 1.6046005156662544 	 Accuracy: 0.17209908735332463
Delta: 4.9149181002518285e-05 	  Loss: 1.6046495264802458 	 Accuracy: 0.17470664928292046
Delta: 0.002780801275716025 	  Loss: 1.604423861588701 	 Accuracy: 0.17340286831812254
Delta: 0.00010747978295268297 	  Loss: 1.6043797751068407 	 Accuracy: 0.17340286831812254
Delta: 2.413169597413919e-06 	  Loss: 1.6043893659147375 	 Accuracy: 0.17079530638852672
Delta: 2.542301965222124e-06 	  Loss: 1.6043766575625518 	 Accuracy: 0.17340286831812254
Delta: 0.002753433851178695 	  Loss: 1.6042157769714869 	 Accuracy: 0.17340286831812254
Delta: 0.0011676271356495602 	  Loss: 1.604461593854562 	 Accuracy: 0.17340286831812254
Delta: 0.0019073535110347537 	  Loss: 1.604376846608985 	 Accuracy: 0.17340286831812254
Delta: 3.7245487630396615e-06 	  Loss: 1.604381940154453 	 Accuracy: 0.17340286831812254
Delta: 0.0011697293767849802 	  Loss: 1.6044360316558413 	 Accuracy: 0.1681877444589309
Delta: 0.0032276108957926407 	  Loss: 1.6047935683259376 	 Accuracy: 0.17209908735332463
Delta: 0.00402408574713971 	  Loss: 1.6054333664329703 	 Accuracy: 0.17209908735332463
Delta: 0.0019356964619255965 	  Loss: 1.605481332120977 	 Accuracy: 0.17209908735332463
Delta: 0.0012466843210239443 	  Loss: 1.6053425362282758 	 Accuracy: 0.1694915254237288
Delta: 0.004338582672098679 	  Loss: 1.6051091265133461 	 Accuracy: 0.17209908735332463
Delta: 0.0022783445423334007 	  Loss: 1.6056086019634825 	 Accuracy: 0.17079530638852672
Delta: 0.0014872048052550488 	  Loss: 1.6052643405519156 	 Accuracy: 0.1694915254237288
Delta: 0.0005693246441132109 	  Loss: 1.6052096807394922 	 Accuracy: 0.17079530638852672
Delta: 0.0001277038726454355 	  Loss: 1.6047474716680696 	 Accuracy: 0.17079530638852672
Delta: 0.0018757869694150616 	  Loss: 1.6056309017723063 	 Accuracy: 0.17079530638852672
Delta: 0.003311581242784248 	  Loss: 1.60586003368471 	 Accuracy: 0.1694915254237288
Delta: 0.0005872175572958737 	  Loss: 1.6054679633016848 	 Accuracy: 0.17079530638852672
Delta: 3.703539550295735e-05 	  Loss: 1.6055713583547464 	 Accuracy: 0.1681877444589309
Delta: 0.0018659749269604852 	  Loss: 1.606162063293783 	 Accuracy: 0.17079530638852672
Delta: 0.004231327639118858 	  Loss: 1.606134848877249 	 Accuracy: 0.17079530638852672
Delta: 0.003439550162821082 	  Loss: 1.6068023614987943 	 Accuracy: 0.1681877444589309
Delta: 0.0027216033234839037 	  Loss: 1.6068629049947714 	 Accuracy: 0.17079530638852672
Delta: 0.0012407912683275618 	  Loss: 1.606762830104844 	 Accuracy: 0.17079530638852672
Delta: 0.001096764197681283 	  Loss: 1.6064857606096392 	 Accuracy: 0.17079530638852672
Delta: 0.0031980023670275916 	  Loss: 1.6070664535354062 	 Accuracy: 0.17079530638852672
Delta: 0.0015462437199732326 	  Loss: 1.606873191452725 	 Accuracy: 0.17079530638852672
Delta: 3.192284928445315e-05 	  Loss: 1.6067017443127694 	 Accuracy: 0.17079530638852672
Delta: 2.950065094443063e-06 	  Loss: 1.6066930698776436 	 Accuracy: 0.1694915254237288
Delta: 0.002463809094488955 	  Loss: 1.6063118960136857 	 Accuracy: 0.1694915254237288
Delta: 0.0030039806135219063 	  Loss: 1.6063954577172754 	 Accuracy: 0.17079530638852672
Delta: 0.003034341464709008 	  Loss: 1.6068420795759335 	 Accuracy: 0.17079530638852672
Delta: 0.0032741480530775863 	  Loss: 1.6066727496266564 	 Accuracy: 0.17079530638852672
Delta: 0.0020035182610084927 	  Loss: 1.606593400098109 	 Accuracy: 0.17340286831812254
Delta: 0.0033571317265025666 	  Loss: 1.606626719508049 	 Accuracy: 0.17079530638852672
Delta: 0.0038018857820541763 	  Loss: 1.6061610115760798 	 Accuracy: 0.17209908735332463
Delta: 0.0008624487269732036 	  Loss: 1.6061990164650006 	 Accuracy: 0.17209908735332463
Delta: 7.957544576628032e-07 	  Loss: 1.6062002120138605 	 Accuracy: 0.17340286831812254
Delta: 0.003862839851598831 	  Loss: 1.6057463083838366 	 Accuracy: 0.17209908735332463
Delta: 0.0007421964388476214 	  Loss: 1.6057319418734088 	 Accuracy: 0.17079530638852672
Delta: 0.003174551786138222 	  Loss: 1.6052743539574648 	 Accuracy: 0.17340286831812254
Delta: 0.0029175047782341694 	  Loss: 1.6057330637161025 	 Accuracy: 0.17340286831812254
Delta: 0.0024729067447857686 	  Loss: 1.6051502141009357 	 Accuracy: 0.17209908735332463
Delta: 0.0045604656156031835 	  Loss: 1.6043158756272236 	 Accuracy: 0.17209908735332463
Delta: 0.0045114461617858 	  Loss: 1.6040271500145944 	 Accuracy: 0.17340286831812254
Delta: 0.02108925637374721 	  Loss: 2.1596847815261566 	 Accuracy: 0.17079530638852672
Delta: 0.0187427733643996 	  Loss: 2.0625497554422036 	 Accuracy: 0.19556714471968709
Delta: 0.0173142745535602 	  Loss: 1.8954156803074196 	 Accuracy: 0.2033898305084746
Delta: 0.016311404498181314 	  Loss: 1.743945461968465 	 Accuracy: 0.20990873533246415
Delta: 0.014678732393207761 	  Loss: 1.6680177541644392 	 Accuracy: 0.21773142112125163

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010357850326286229 	  Loss: 1.6442907769910466 	 Accuracy: 0.21773142112125163
Delta: 0.007919736171988198 	  Loss: 1.6405260378076556 	 Accuracy: 0.22164276401564537
Delta: 0.005998149279435755 	  Loss: 1.640375764239554 	 Accuracy: 0.21903520208604954
Delta: 0.004257257950518149 	  Loss: 1.640153693271498 	 Accuracy: 0.21773142112125163
Delta: 0.0031779278145405293 	  Loss: 1.640087815387926 	 Accuracy: 0.21903520208604954
Delta: 0.002329663101467377 	  Loss: 1.6399262793139786 	 Accuracy: 0.21903520208604954
Delta: 0.00289344047887296 	  Loss: 1.6401825014680145 	 Accuracy: 0.2151238591916558
Delta: 0.002847011705528498 	  Loss: 1.6400320762723364 	 Accuracy: 0.21642764015645372
Delta: 0.0012143138111704076 	  Loss: 1.6398556448088621 	 Accuracy: 0.2151238591916558
Delta: 0.0015697849256878819 	  Loss: 1.6401374505881603 	 Accuracy: 0.21773142112125163
Delta: 4.988990719025006e-05 	  Loss: 1.6402083795598128 	 Accuracy: 0.21773142112125163
Delta: 0.002270401517628154 	  Loss: 1.6401401896276364 	 Accuracy: 0.21773142112125163
Delta: 0.0023028053291785323 	  Loss: 1.640192224457599 	 Accuracy: 0.21903520208604954
Delta: 0.001373585701949169 	  Loss: 1.640480434160196 	 Accuracy: 0.21642764015645372
Delta: 0.0034066054806377788 	  Loss: 1.6399975610817927 	 Accuracy: 0.21773142112125163
Delta: 0.003085199573626701 	  Loss: 1.6395803357016616 	 Accuracy: 0.21642764015645372
Delta: 0.0023757450305971844 	  Loss: 1.6394190846313297 	 Accuracy: 0.21642764015645372
Delta: 0.001499277842541461 	  Loss: 1.6395116652351516 	 Accuracy: 0.21642764015645372
Delta: 5.4964862113026724e-05 	  Loss: 1.639740355683016 	 Accuracy: 0.21642764015645372
Delta: 4.881961843895683e-05 	  Loss: 1.6395480567422858 	 Accuracy: 0.21642764015645372
Delta: 0.002965757626909063 	  Loss: 1.6393499532980955 	 Accuracy: 0.19947848761408082
Delta: 0.004652440126216923 	  Loss: 1.639139879574003 	 Accuracy: 0.2151238591916558
Delta: 0.002056014173401197 	  Loss: 1.639704621071553 	 Accuracy: 0.2151238591916558
Delta: 0.0021168338796180575 	  Loss: 1.6394198881196156 	 Accuracy: 0.2151238591916558
Delta: 0.0006183922444937557 	  Loss: 1.6394241719173128 	 Accuracy: 0.21642764015645372
Delta: 0.004982695617817372 	  Loss: 1.6387715337272795 	 Accuracy: 0.21773142112125163
Delta: 0.0041988175452943545 	  Loss: 1.6389797472743965 	 Accuracy: 0.21773142112125163
Delta: 0.0015462669360996515 	  Loss: 1.6387150696666086 	 Accuracy: 0.21903520208604954
Delta: 0.003684696759173665 	  Loss: 1.6387917105418919 	 Accuracy: 0.21903520208604954
Delta: 0.003086653929289238 	  Loss: 1.638645814057819 	 Accuracy: 0.22033898305084745
Delta: 0.0017441183190577004 	  Loss: 1.6386917223573625 	 Accuracy: 0.21903520208604954
Delta: 0.001463562236580386 	  Loss: 1.6385797803319777 	 Accuracy: 0.21903520208604954
Delta: 1.5270412036852684e-05 	  Loss: 1.6386214371143224 	 Accuracy: 0.22033898305084745
Delta: 0.0016788216744302554 	  Loss: 1.638773639818813 	 Accuracy: 0.21773142112125163
Delta: 0.0023957469007840843 	  Loss: 1.639312003354214 	 Accuracy: 0.21903520208604954
Delta: 0.002906442936982661 	  Loss: 1.6386432781916453 	 Accuracy: 0.21903520208604954
Delta: 0.0009865957963740295 	  Loss: 1.6388330452683812 	 Accuracy: 0.22164276401564537
Delta: 0.0030854396521967356 	  Loss: 1.6390887792647773 	 Accuracy: 0.21903520208604954
Delta: 0.002267177174778436 	  Loss: 1.6386498067953448 	 Accuracy: 0.21903520208604954
Delta: 5.2490675417815285e-05 	  Loss: 1.6385645672592053 	 Accuracy: 0.21903520208604954
Delta: 0.0022135210071508662 	  Loss: 1.6388286459869166 	 Accuracy: 0.21903520208604954
Delta: 0.0020693066967298794 	  Loss: 1.637892939538245 	 Accuracy: 0.21903520208604954
Delta: 0.002118702261430019 	  Loss: 1.638427564038199 	 Accuracy: 0.22033898305084745
Delta: 0.0023899859270496977 	  Loss: 1.6389899125188627 	 Accuracy: 0.21903520208604954
Delta: 0.0013826122375503224 	  Loss: 1.6384381780594885 	 Accuracy: 0.22294654498044328
Delta: 0.005219453257624487 	  Loss: 1.6386134895580478 	 Accuracy: 0.21773142112125163
Delta: 0.005286807830628469 	  Loss: 1.6380465540252094 	 Accuracy: 0.22033898305084745
Delta: 0.0014205091019761252 	  Loss: 1.6379514112302958 	 Accuracy: 0.22033898305084745
Delta: 3.5062954927559536e-06 	  Loss: 1.63795259367654 	 Accuracy: 0.21903520208604954
Delta: 0.0016289780730955425 	  Loss: 1.6379596113747232 	 Accuracy: 0.22033898305084745
Delta: 0.0017550645406986753 	  Loss: 1.6380860481177821 	 Accuracy: 0.22033898305084745
Delta: 0.0005612881459619494 	  Loss: 1.6379540744178107 	 Accuracy: 0.22033898305084745
Delta: 0.0017975603410918558 	  Loss: 1.6378981162246915 	 Accuracy: 0.22294654498044328
Delta: 0.0007907018981850956 	  Loss: 1.6382493819299604 	 Accuracy: 0.22033898305084745
Delta: 0.003022535142016452 	  Loss: 1.6388439755843762 	 Accuracy: 0.21903520208604954
Delta: 3.3246419242752886e-05 	  Loss: 1.638848673740434 	 Accuracy: 0.22164276401564537
Delta: 0.002777642301636877 	  Loss: 1.6384187018629364 	 Accuracy: 0.21903520208604954
Delta: 0.005408322308174962 	  Loss: 1.6366360402069156 	 Accuracy: 0.22033898305084745
Delta: 0.004028143841836226 	  Loss: 1.6376805658277007 	 Accuracy: 0.21903520208604954
Delta: 0.003901421875541069 	  Loss: 1.6375190292539497 	 Accuracy: 0.21903520208604954
Delta: 0.0040078640835846165 	  Loss: 1.6365458486116093 	 Accuracy: 0.2046936114732725
Delta: 0.003945128039047637 	  Loss: 1.6373742902302801 	 Accuracy: 0.21773142112125163
Delta: 0.0035751390707290053 	  Loss: 1.6364998406495714 	 Accuracy: 0.21773142112125163
Delta: 0.0005144220843254945 	  Loss: 1.6365410562615192 	 Accuracy: 0.21642764015645372
Delta: 0.0015592426254459823 	  Loss: 1.6363090407628205 	 Accuracy: 0.21642764015645372
Delta: 0.0020115966074351465 	  Loss: 1.6361069819574348 	 Accuracy: 0.21773142112125163
Delta: 4.09232023925261e-05 	  Loss: 1.6361498797647513 	 Accuracy: 0.21773142112125163
Delta: 0.0017970938473341957 	  Loss: 1.636459725070976 	 Accuracy: 0.21903520208604954
Delta: 0.004167419678773148 	  Loss: 1.637037247607054 	 Accuracy: 0.22816166883963493
Delta: 0.003046301298290737 	  Loss: 1.637169007117186 	 Accuracy: 0.2151238591916558
Delta: 0.0019452474789049214 	  Loss: 1.6371300276394756 	 Accuracy: 0.21773142112125163
Delta: 0.0027639554539875028 	  Loss: 1.637306686585498 	 Accuracy: 0.21773142112125163
Delta: 0.0005710125247241047 	  Loss: 1.6375372709534126 	 Accuracy: 0.21903520208604954
Delta: 0.0020288151379619793 	  Loss: 1.6360427493220189 	 Accuracy: 0.21642764015645372
Delta: 0.0005401619019946412 	  Loss: 1.635889613114238 	 Accuracy: 0.21773142112125163
Delta: 0.0005392735210926762 	  Loss: 1.636019060685411 	 Accuracy: 0.2046936114732725
Delta: 0.0043084282685073045 	  Loss: 1.6366073894805888 	 Accuracy: 0.21121251629726207
Delta: 0.004707832867617865 	  Loss: 1.6370587043083695 	 Accuracy: 0.21773142112125163
Delta: 0.0028637674182440194 	  Loss: 1.6350463981728227 	 Accuracy: 0.21773142112125163
Delta: 0.003295123024903269 	  Loss: 1.6358116163086063 	 Accuracy: 0.2242503259452412
Delta: 0.0036535565360269833 	  Loss: 1.6359930270557212 	 Accuracy: 0.22164276401564537
Delta: 0.0030073715294353215 	  Loss: 1.6369293499871183 	 Accuracy: 0.21903520208604954
Delta: 0.003980300486876953 	  Loss: 1.6353052711586868 	 Accuracy: 0.22164276401564537
Delta: 0.0044849226593737905 	  Loss: 1.6360872145383745 	 Accuracy: 0.22164276401564537
Delta: 0.004763812419876403 	  Loss: 1.635438303275973 	 Accuracy: 0.21903520208604954
Delta: 0.005821770725442748 	  Loss: 1.6340082368960274 	 Accuracy: 0.22033898305084745
Delta: 0.0033650774901757287 	  Loss: 1.6340113623419485 	 Accuracy: 0.22033898305084745
Delta: 0.006483768746465139 	  Loss: 1.633364232723481 	 Accuracy: 0.22164276401564537
Delta: 0.004942871676996625 	  Loss: 1.6335951408797666 	 Accuracy: 0.22033898305084745
Delta: 0.004199044843625086 	  Loss: 1.6331807132750702 	 Accuracy: 0.22033898305084745
Delta: 0.005364101425343179 	  Loss: 1.6319430512957587 	 Accuracy: 0.2151238591916558
Delta: 0.006281835202762936 	  Loss: 1.6338872430097928 	 Accuracy: 0.22033898305084745
Delta: 0.004404260335634036 	  Loss: 1.6348237341683687 	 Accuracy: 0.22033898305084745
Delta: 0.001227539088171285 	  Loss: 1.6348212858977738 	 Accuracy: 0.22033898305084745
Delta: 1.972067182795055e-05 	  Loss: 1.6348378445050398 	 Accuracy: 0.21903520208604954
Delta: 0.021008406362443055 	  Loss: 2.1595729490553977 	 Accuracy: 0.13559322033898305
Delta: 0.018949003187562607 	  Loss: 2.06028372705557 	 Accuracy: 0.11342894393741851
Delta: 0.017625786970700476 	  Loss: 1.8833312862069458 	 Accuracy: 0.16297262059973924
Delta: 0.01550834571637501 	  Loss: 1.7650285270332615 	 Accuracy: 0.18513689700130379
Delta: 0.013736253085026278 	  Loss: 1.7147802413460547 	 Accuracy: 0.1981747066492829
Delta: 0.012276445891775085 	  Loss: 1.693574313370212 	 Accuracy: 0.20990873533246415

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010091710410137289 	  Loss: 1.685092330988333 	 Accuracy: 0.2046936114732725
Delta: 0.008655506635675974 	  Loss: 1.680249167915005 	 Accuracy: 0.20860495436766624
Delta: 0.005648881838347379 	  Loss: 1.6792540737070483 	 Accuracy: 0.20860495436766624
Delta: 0.005570877911887848 	  Loss: 1.6783330581677665 	 Accuracy: 0.20730117340286833
Delta: 0.0035703729799999875 	  Loss: 1.6780167225383713 	 Accuracy: 0.20599739243807041
Delta: 0.001589053190931867 	  Loss: 1.6778646788005651 	 Accuracy: 0.20730117340286833
Delta: 0.0013882225633874952 	  Loss: 1.6778504865360873 	 Accuracy: 0.20730117340286833
Delta: 0.0023059476073964205 	  Loss: 1.678151503361692 	 Accuracy: 0.20599739243807041
Delta: 0.0023843396814132818 	  Loss: 1.6782422844347094 	 Accuracy: 0.2138200782268579
Delta: 0.003855649155266464 	  Loss: 1.6785278424527126 	 Accuracy: 0.20599739243807041
Delta: 0.002212261246675963 	  Loss: 1.6787613347508232 	 Accuracy: 0.20599739243807041
Delta: 1.95059003382162e-05 	  Loss: 1.6787679974229177 	 Accuracy: 0.20599739243807041
Delta: 1.800604773304641e-05 	  Loss: 1.6787813328987309 	 Accuracy: 0.20599739243807041
Delta: 0.0034643262884091397 	  Loss: 1.6785721863885241 	 Accuracy: 0.20208604954367665
Delta: 0.001651406700604884 	  Loss: 1.6786289540294723 	 Accuracy: 0.20599739243807041
Delta: 0.002254895630178744 	  Loss: 1.678479681135237 	 Accuracy: 0.20599739243807041
Delta: 0.001436070878903251 	  Loss: 1.678723679359645 	 Accuracy: 0.20599739243807041
Delta: 3.429133350092424e-05 	  Loss: 1.6786105202402628 	 Accuracy: 0.2046936114732725
Delta: 0.0008470681376992243 	  Loss: 1.6785994029122708 	 Accuracy: 0.20599739243807041
Delta: 3.342375286471786e-05 	  Loss: 1.6787099212734589 	 Accuracy: 0.21773142112125163
Delta: 5.5070122995639396e-05 	  Loss: 1.678803157640983 	 Accuracy: 0.20599739243807041
Delta: 0.0017498812263283 	  Loss: 1.678671215853101 	 Accuracy: 0.20599739243807041
Delta: 0.0008447152430979634 	  Loss: 1.6787319298303567 	 Accuracy: 0.20599739243807041
Delta: 7.386855894191623e-05 	  Loss: 1.678551989094076 	 Accuracy: 0.20599739243807041
Delta: 0.0006343454945373523 	  Loss: 1.6782858313396751 	 Accuracy: 0.20599739243807041
Delta: 4.144400620974783e-05 	  Loss: 1.6784232344174934 	 Accuracy: 0.20599739243807041
Delta: 1.165713667022422e-05 	  Loss: 1.6784424773464302 	 Accuracy: 0.20599739243807041
Delta: 6.576696990179035e-05 	  Loss: 1.678461642543955 	 Accuracy: 0.20599739243807041
Delta: 0.002301992945325352 	  Loss: 1.678276469567528 	 Accuracy: 0.20599739243807041
Delta: 0.0011271535795440125 	  Loss: 1.6786144019860418 	 Accuracy: 0.20599739243807041
Delta: 0.0018984946789135399 	  Loss: 1.6779282319977502 	 Accuracy: 0.2033898305084746
Delta: 0.0019422777330903899 	  Loss: 1.6783357208137557 	 Accuracy: 0.2046936114732725
Delta: 0.0008305464731916287 	  Loss: 1.6786410933049365 	 Accuracy: 0.20599739243807041
Delta: 3.9344006923827995e-05 	  Loss: 1.6785321326546059 	 Accuracy: 0.20730117340286833
Delta: 0.002776615014031111 	  Loss: 1.6783550096518782 	 Accuracy: 0.20599739243807041
Delta: 0.001847820281283476 	  Loss: 1.678351169493045 	 Accuracy: 0.20599739243807041
Delta: 0.0016590627088617184 	  Loss: 1.678345409044512 	 Accuracy: 0.20599739243807041
Delta: 0.002060300706994826 	  Loss: 1.678588538555801 	 Accuracy: 0.20599739243807041
Delta: 4.9763081474641796e-05 	  Loss: 1.6785090786207404 	 Accuracy: 0.20599739243807041
Delta: 1.4126987070322273e-05 	  Loss: 1.678505746224438 	 Accuracy: 0.20599739243807041
Delta: 1.1733527338781502e-05 	  Loss: 1.6785055960100999 	 Accuracy: 0.20599739243807041
Delta: 7.103488996112659e-05 	  Loss: 1.6787348176669945 	 Accuracy: 0.20599739243807041
Delta: 5.323628929983922e-05 	  Loss: 1.6785730094187161 	 Accuracy: 0.20599739243807041
Delta: 5.236982505955337e-05 	  Loss: 1.6784871930933773 	 Accuracy: 0.20730117340286833
Delta: 1.4226929971280944e-05 	  Loss: 1.6784754986466188 	 Accuracy: 0.20599739243807041
Delta: 6.088346501754196e-05 	  Loss: 1.6785837649753577 	 Accuracy: 0.2046936114732725
Delta: 7.3866031358242975e-06 	  Loss: 1.6785694877252335 	 Accuracy: 0.2046936114732725
Delta: 0.0008072201128999159 	  Loss: 1.6784000418486518 	 Accuracy: 0.20599739243807041
Delta: 3.656174395404888e-05 	  Loss: 1.6785696199605904 	 Accuracy: 0.20078226857887874
Delta: 4.873835218905178e-05 	  Loss: 1.6785064293220202 	 Accuracy: 0.20730117340286833
Delta: 0.002930188022174614 	  Loss: 1.67844081855173 	 Accuracy: 0.20599739243807041
Delta: 0.0039796974510467095 	  Loss: 1.678725640974956 	 Accuracy: 0.2046936114732725
Delta: 0.001230779648637412 	  Loss: 1.6786918128667083 	 Accuracy: 0.2046936114732725
Delta: 2.786909299501963e-06 	  Loss: 1.6786979709491523 	 Accuracy: 0.2033898305084746
Delta: 0.00258593097354629 	  Loss: 1.678919960488556 	 Accuracy: 0.2046936114732725
Delta: 0.00012153526577097112 	  Loss: 1.6786932805584438 	 Accuracy: 0.2046936114732725
Delta: 4.010664636390194e-06 	  Loss: 1.6786679367620678 	 Accuracy: 0.2033898305084746
Delta: 0.0016394970516195426 	  Loss: 1.678639712245324 	 Accuracy: 0.2046936114732725
Delta: 0.0023353149723524796 	  Loss: 1.6787781494120324 	 Accuracy: 0.2046936114732725
Delta: 7.892887432393869e-05 	  Loss: 1.67870623525015 	 Accuracy: 0.20208604954367665
Delta: 0.0021200776423126702 	  Loss: 1.678761077032128 	 Accuracy: 0.2033898305084746
Delta: 0.004113946132960878 	  Loss: 1.678896740887351 	 Accuracy: 0.2033898305084746
Delta: 0.0038837485598396805 	  Loss: 1.6785180851189252 	 Accuracy: 0.20208604954367665
Delta: 0.0033318970639586204 	  Loss: 1.6785505334784085 	 Accuracy: 0.196870925684485
Delta: 0.0005694632043925226 	  Loss: 1.6784175481572623 	 Accuracy: 0.2033898305084746
Delta: 0.0017000696892664033 	  Loss: 1.6784014115831047 	 Accuracy: 0.2033898305084746
Delta: 0.0012923702154441223 	  Loss: 1.6783934455353444 	 Accuracy: 0.2033898305084746
Delta: 4.358840258091809e-06 	  Loss: 1.6783944544931142 	 Accuracy: 0.2033898305084746
Delta: 1.9046998794844751e-06 	  Loss: 1.6783923007573127 	 Accuracy: 0.2033898305084746
Delta: 2.8955466712828112e-06 	  Loss: 1.6783957943522692 	 Accuracy: 0.2033898305084746
Delta: 4.414144322428417e-06 	  Loss: 1.6783979603907695 	 Accuracy: 0.2033898305084746
Delta: 4.717625415708003e-05 	  Loss: 1.6781454824590836 	 Accuracy: 0.2033898305084746
Delta: 0.0026912018947440257 	  Loss: 1.6785728999609089 	 Accuracy: 0.2033898305084746
Delta: 8.691220203730317e-05 	  Loss: 1.678349252100697 	 Accuracy: 0.2033898305084746
Delta: 5.619097254656525e-05 	  Loss: 1.6782590111826976 	 Accuracy: 0.2033898305084746
Delta: 2.841309514339135e-05 	  Loss: 1.678412871686485 	 Accuracy: 0.2033898305084746
Delta: 4.081105934181322e-05 	  Loss: 1.6783621457996236 	 Accuracy: 0.2033898305084746
Delta: 4.093976355540326e-05 	  Loss: 1.6784044934187379 	 Accuracy: 0.2033898305084746
Delta: 3.664180567759059e-05 	  Loss: 1.6783764244731336 	 Accuracy: 0.2046936114732725
Delta: 0.0005369633254647873 	  Loss: 1.6785266022881005 	 Accuracy: 0.2033898305084746
Delta: 3.222434151760888e-05 	  Loss: 1.678412434580503 	 Accuracy: 0.2033898305084746
Delta: 1.4211436255887468e-08 	  Loss: 1.6784124516610515 	 Accuracy: 0.2033898305084746
converged at iter  87
Delta: 0.021034860191588265 	  Loss: 2.159457836016975 	 Accuracy: 0.15384615384615385
Delta: 0.019150313139289846 	  Loss: 2.053883506166098 	 Accuracy: 0.19947848761408082
Delta: 0.017621150995488204 	  Loss: 1.876694176161461 	 Accuracy: 0.1694915254237288
Delta: 0.01553610372461171 	  Loss: 1.7642943154872701 	 Accuracy: 0.19556714471968709
Delta: 0.014492938214418336 	  Loss: 1.7154867401246718 	 Accuracy: 0.20860495436766624
Delta: 0.011818889077244455 	  Loss: 1.692872055720561 	 Accuracy: 0.2046936114732725

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008892908801643892 	  Loss: 1.6896043364379634 	 Accuracy: 0.20599739243807041
Delta: 0.00726410567818502 	  Loss: 1.6861633076031866 	 Accuracy: 0.2033898305084746
Delta: 0.006347123093487374 	  Loss: 1.684194456907554 	 Accuracy: 0.2033898305084746
Delta: 0.0033738657335670576 	  Loss: 1.6847193594952834 	 Accuracy: 0.2033898305084746
Delta: 0.0014515183673064916 	  Loss: 1.6842837566694566 	 Accuracy: 0.2033898305084746
Delta: 0.0008058153514043008 	  Loss: 1.6842987141498131 	 Accuracy: 0.20208604954367665
Delta: 0.003135969994664282 	  Loss: 1.6843006809710195 	 Accuracy: 0.20208604954367665
Delta: 0.0024760602618047025 	  Loss: 1.684261463751405 	 Accuracy: 0.20208604954367665
Delta: 0.0007944587977202133 	  Loss: 1.6842704387397072 	 Accuracy: 0.20208604954367665
Delta: 0.001165082844258444 	  Loss: 1.6845281862831314 	 Accuracy: 0.20078226857887874
Delta: 5.3035165962982916e-05 	  Loss: 1.6843486676367514 	 Accuracy: 0.20208604954367665
Delta: 0.0008072999739567775 	  Loss: 1.6842224389812126 	 Accuracy: 0.20208604954367665
Delta: 4.2416315068613426e-05 	  Loss: 1.684376750568661 	 Accuracy: 0.20078226857887874
Delta: 5.9893421951539055e-05 	  Loss: 1.6842820255631015 	 Accuracy: 0.20208604954367665
Delta: 0.002370127745877984 	  Loss: 1.6844770194049627 	 Accuracy: 0.20208604954367665
Delta: 0.0008445470214976889 	  Loss: 1.684581494607845 	 Accuracy: 0.20208604954367665
Delta: 0.008702353726095652 	  Loss: 1.6834988921123728 	 Accuracy: 0.196870925684485
Delta: 0.0041306634113111975 	  Loss: 1.6830187966251007 	 Accuracy: 0.2046936114732725
Delta: 0.0013447734438550051 	  Loss: 1.6829701295196609 	 Accuracy: 0.19426336375488917
Delta: 4.2209473492024325e-05 	  Loss: 1.6828975730758005 	 Accuracy: 0.19426336375488917
Delta: 0.0019472323337196365 	  Loss: 1.6829015847340425 	 Accuracy: 0.19556714471968709
Delta: 0.0006920584346352288 	  Loss: 1.682826484928917 	 Accuracy: 0.19426336375488917
Delta: 0.0029336206180310227 	  Loss: 1.6827106172537554 	 Accuracy: 0.19295958279009126
Delta: 0.00254412180366497 	  Loss: 1.6827579305291498 	 Accuracy: 0.19165580182529335
Delta: 0.0032169268449127567 	  Loss: 1.6824502143613669 	 Accuracy: 0.19295958279009126
Delta: 0.001962153579141565 	  Loss: 1.682476194519562 	 Accuracy: 0.19165580182529335
Delta: 0.0019253631971904767 	  Loss: 1.682344624770955 	 Accuracy: 0.19295958279009126
Delta: 0.0024258234111291426 	  Loss: 1.6825345860648198 	 Accuracy: 0.19556714471968709
Delta: 0.002018083531347085 	  Loss: 1.6824816773577687 	 Accuracy: 0.19556714471968709
Delta: 7.981858750849613e-05 	  Loss: 1.6823331907607095 	 Accuracy: 0.19426336375488917
Delta: 0.0012523430925606952 	  Loss: 1.6823683121777993 	 Accuracy: 0.19426336375488917
Delta: 0.0018856371992929228 	  Loss: 1.6824081933334278 	 Accuracy: 0.19165580182529335
Delta: 0.0007683787626861609 	  Loss: 1.6823523428068916 	 Accuracy: 0.16166883963494133
Delta: 0.004605003355108615 	  Loss: 1.682013311993197 	 Accuracy: 0.19035202086049544
Delta: 0.0011821901149594895 	  Loss: 1.6820686035826768 	 Accuracy: 0.20078226857887874
Delta: 0.004282059061590896 	  Loss: 1.6823923298364822 	 Accuracy: 0.19035202086049544
Delta: 0.0047303010960136746 	  Loss: 1.6821308352636515 	 Accuracy: 0.19295958279009126
Delta: 0.004658779883862808 	  Loss: 1.6819162158112553 	 Accuracy: 0.1864406779661017
Delta: 0.0027532063951345056 	  Loss: 1.6818190872645482 	 Accuracy: 0.19295958279009126
Delta: 7.486575419538546e-05 	  Loss: 1.6818511444683448 	 Accuracy: 0.19035202086049544
Delta: 6.792192024881238e-06 	  Loss: 1.681815965234761 	 Accuracy: 0.19035202086049544
Delta: 0.0032224882857931456 	  Loss: 1.6818176331551904 	 Accuracy: 0.19035202086049544
Delta: 0.001958181884193645 	  Loss: 1.6818359919495636 	 Accuracy: 0.19035202086049544
Delta: 2.35379117470503e-06 	  Loss: 1.6818338854211414 	 Accuracy: 0.19035202086049544
Delta: 0.0015163653234301462 	  Loss: 1.6818494523870986 	 Accuracy: 0.19035202086049544
Delta: 0.0010882913483329082 	  Loss: 1.6818278925823873 	 Accuracy: 0.19035202086049544
Delta: 3.880401153960435e-05 	  Loss: 1.6818688163025997 	 Accuracy: 0.19035202086049544
Delta: 3.760402194474384e-05 	  Loss: 1.6818365849701697 	 Accuracy: 0.19035202086049544
Delta: 4.012550637268057e-07 	  Loss: 1.6818348858782606 	 Accuracy: 0.18904823989569752
Delta: 5.5473895113600864e-05 	  Loss: 1.681858221468942 	 Accuracy: 0.19035202086049544
Delta: 0.003191778559389774 	  Loss: 1.6819288668769086 	 Accuracy: 0.19035202086049544
Delta: 5.217302946284177e-05 	  Loss: 1.6819908124800818 	 Accuracy: 0.19165580182529335
Delta: 0.0022992077111250704 	  Loss: 1.6820239200381795 	 Accuracy: 0.19556714471968709
Delta: 0.0037418689592388977 	  Loss: 1.6817537306588952 	 Accuracy: 0.19035202086049544
Delta: 0.0023378862085209006 	  Loss: 1.6820222164155707 	 Accuracy: 0.19165580182529335
Delta: 0.0010590656039734792 	  Loss: 1.6819964300406496 	 Accuracy: 0.19165580182529335
Delta: 2.6855529583298658e-05 	  Loss: 1.6820167142936278 	 Accuracy: 0.19035202086049544
Delta: 0.0014577430113792513 	  Loss: 1.681832560330648 	 Accuracy: 0.18904823989569752
Delta: 0.0016985641208096276 	  Loss: 1.681875744161317 	 Accuracy: 0.19035202086049544
Delta: 0.0013709187480556275 	  Loss: 1.6818324461138459 	 Accuracy: 0.1760104302477184
Delta: 0.0008739114573625569 	  Loss: 1.6818816594269155 	 Accuracy: 0.19035202086049544
Delta: 6.88252239014403e-05 	  Loss: 1.6816671355403008 	 Accuracy: 0.19035202086049544
Delta: 0.0037285716168552387 	  Loss: 1.6812170190688929 	 Accuracy: 0.19035202086049544
Delta: 0.0032027626178905014 	  Loss: 1.6815984410647054 	 Accuracy: 0.18513689700130379
Delta: 0.004365910910595691 	  Loss: 1.6812241496611837 	 Accuracy: 0.19165580182529335
Delta: 0.0032280868598826163 	  Loss: 1.6812959334344009 	 Accuracy: 0.18904823989569752
Delta: 0.0007587807605769543 	  Loss: 1.6812904408968778 	 Accuracy: 0.18904823989569752
Delta: 0.002056638667022508 	  Loss: 1.6812066497219913 	 Accuracy: 0.18904823989569752
Delta: 2.8481330903290345e-06 	  Loss: 1.681206608855954 	 Accuracy: 0.18904823989569752
converged at iter  74
Delta: 0.021072801844889587 	  Loss: 2.159472308453127 	 Accuracy: 0.16688396349413298
Delta: 0.018916292462024965 	  Loss: 2.0537846487899127 	 Accuracy: 0.1681877444589309
Delta: 0.017448213788243433 	  Loss: 1.873532724646016 	 Accuracy: 0.23728813559322035
Delta: 0.01577926022264011 	  Loss: 1.757405628150547 	 Accuracy: 0.27640156453715775
Delta: 0.013724829919255402 	  Loss: 1.714814707853567 	 Accuracy: 0.2737940026075619

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010346665128918053 	  Loss: 1.7027176536405937 	 Accuracy: 0.28552803129074317
Delta: 0.008188481744837883 	  Loss: 1.6981508679729571 	 Accuracy: 0.2842242503259452
Delta: 0.006602639785460888 	  Loss: 1.6971295500594725 	 Accuracy: 0.2842242503259452
Delta: 0.0035509433879594766 	  Loss: 1.696648939559884 	 Accuracy: 0.28292046936114734
Delta: 0.004717869147745065 	  Loss: 1.6962931892023068 	 Accuracy: 0.2816166883963494
Delta: 0.0022592761608698497 	  Loss: 1.6960674164541538 	 Accuracy: 0.28292046936114734
Delta: 0.0028901742275092095 	  Loss: 1.6960717237930916 	 Accuracy: 0.28292046936114734
Delta: 0.002060743893227009 	  Loss: 1.6955391813302834 	 Accuracy: 0.2816166883963494
Delta: 0.002157739194194675 	  Loss: 1.6954966523824735 	 Accuracy: 0.2842242503259452
Delta: 0.002767606174483546 	  Loss: 1.6950170863880878 	 Accuracy: 0.28292046936114734
Delta: 0.0015273780382478845 	  Loss: 1.695351105710425 	 Accuracy: 0.28292046936114734
Delta: 0.0012017910176014123 	  Loss: 1.6952613546020894 	 Accuracy: 0.28292046936114734
Delta: 0.002379844625867497 	  Loss: 1.6955229320718266 	 Accuracy: 0.28292046936114734
Delta: 0.0012909699928491131 	  Loss: 1.6955676690245234 	 Accuracy: 0.29465449804432853
Delta: 0.006662288360952675 	  Loss: 1.6936761556248865 	 Accuracy: 0.2842242503259452
Delta: 0.0025609666183308046 	  Loss: 1.6940227351150279 	 Accuracy: 0.2842242503259452
Delta: 2.4062717043474412e-05 	  Loss: 1.6940070376224363 	 Accuracy: 0.2842242503259452
Delta: 0.0035267801646667292 	  Loss: 1.6937720548680477 	 Accuracy: 0.28552803129074317
Delta: 0.0017556969903678291 	  Loss: 1.693616227794297 	 Accuracy: 0.2816166883963494
Delta: 0.002004623318576463 	  Loss: 1.6938442669539497 	 Accuracy: 0.2842242503259452
Delta: 0.0008415495383156329 	  Loss: 1.6939498271100237 	 Accuracy: 0.2842242503259452
Delta: 0.00212358071503029 	  Loss: 1.6940822266181708 	 Accuracy: 0.2842242503259452
Delta: 9.158299829456558e-05 	  Loss: 1.6938167044838046 	 Accuracy: 0.28552803129074317
Delta: 0.000915411555082454 	  Loss: 1.6938431555069413 	 Accuracy: 0.2842242503259452
Delta: 0.001336719042381447 	  Loss: 1.6940249357466939 	 Accuracy: 0.2842242503259452
Delta: 0.0009220953905044861 	  Loss: 1.6939057286893382 	 Accuracy: 0.2842242503259452
Delta: 0.000653681688618596 	  Loss: 1.6939996234577612 	 Accuracy: 0.2842242503259452
Delta: 0.001098576681098746 	  Loss: 1.6938295819922287 	 Accuracy: 0.2842242503259452
Delta: 0.001781463621523315 	  Loss: 1.6936040711011262 	 Accuracy: 0.2894393741851369
Delta: 0.004116340775231448 	  Loss: 1.693665795133791 	 Accuracy: 0.2842242503259452
Delta: 0.0019260153601232796 	  Loss: 1.6938663196964572 	 Accuracy: 0.2842242503259452
Delta: 4.960208210120533e-06 	  Loss: 1.693865401776939 	 Accuracy: 0.2842242503259452
Delta: 0.0017054075702502578 	  Loss: 1.693814648485326 	 Accuracy: 0.28683181225554105
Delta: 0.0011540979377842656 	  Loss: 1.6936517164348648 	 Accuracy: 0.2842242503259452
Delta: 0.0021003557022037573 	  Loss: 1.6938216758597158 	 Accuracy: 0.29595827900912647
Delta: 0.0013730629926057944 	  Loss: 1.6937991332253226 	 Accuracy: 0.28552803129074317
Delta: 0.001473578731768951 	  Loss: 1.6937468861904474 	 Accuracy: 0.2842242503259452
Delta: 0.0015532368448419858 	  Loss: 1.6936987522738087 	 Accuracy: 0.2842242503259452
Delta: 0.0005427223259211759 	  Loss: 1.6938436839415218 	 Accuracy: 0.2842242503259452
Delta: 5.549359613449874e-05 	  Loss: 1.6938128364607978 	 Accuracy: 0.28683181225554105
Delta: 0.0005608374341949769 	  Loss: 1.6936660757033941 	 Accuracy: 0.28683181225554105
Delta: 0.0010446846732243404 	  Loss: 1.69392805389185 	 Accuracy: 0.2842242503259452
Delta: 0.0005398383717265549 	  Loss: 1.693823368009653 	 Accuracy: 0.2842242503259452
Delta: 0.001380364499631966 	  Loss: 1.6938338946742753 	 Accuracy: 0.28552803129074317
Delta: 6.610657507934724e-05 	  Loss: 1.6938493130299443 	 Accuracy: 0.2842242503259452
Delta: 7.619388578149226e-05 	  Loss: 1.6939128327208781 	 Accuracy: 0.2842242503259452
Delta: 4.162623711416665e-05 	  Loss: 1.69371284832711 	 Accuracy: 0.28292046936114734
Delta: 0.0005729499986652389 	  Loss: 1.6940348663002034 	 Accuracy: 0.2803129074315515
Delta: 7.985391012731869e-05 	  Loss: 1.6939048436289732 	 Accuracy: 0.28552803129074317
Delta: 0.0017362381739826043 	  Loss: 1.693767288600886 	 Accuracy: 0.2790091264667536
Delta: 0.0007469892538544728 	  Loss: 1.6937481559165852 	 Accuracy: 0.2842242503259452
Delta: 0.0005430762460783364 	  Loss: 1.6936527899738036 	 Accuracy: 0.2803129074315515
Delta: 0.0039973016053109385 	  Loss: 1.6945236576646956 	 Accuracy: 0.2816166883963494
Delta: 0.0042011885083440914 	  Loss: 1.694883734549987 	 Accuracy: 0.2816166883963494
Delta: 0.002996698321263333 	  Loss: 1.6946904812043133 	 Accuracy: 0.2894393741851369
Delta: 0.003568817707157556 	  Loss: 1.695670000028323 	 Accuracy: 0.2816166883963494
Delta: 0.004577717944200079 	  Loss: 1.6960419010606278 	 Accuracy: 0.2816166883963494
Delta: 0.0026527610531272942 	  Loss: 1.6955721838629727 	 Accuracy: 0.2790091264667536
Delta: 0.0031091924742370743 	  Loss: 1.6949895893913638 	 Accuracy: 0.2803129074315515
Delta: 0.004521699632912386 	  Loss: 1.6954184338186575 	 Accuracy: 0.2790091264667536
Delta: 0.002705272270378857 	  Loss: 1.695476088402396 	 Accuracy: 0.2790091264667536
Delta: 0.003824216879503181 	  Loss: 1.6952067301408056 	 Accuracy: 0.2803129074315515
Delta: 0.0013884643834151302 	  Loss: 1.694525198601279 	 Accuracy: 0.2803129074315515
Delta: 1.3337503466957989e-05 	  Loss: 1.6945217102090773 	 Accuracy: 0.288135593220339
Delta: 0.003054461842546565 	  Loss: 1.6937353013525347 	 Accuracy: 0.2790091264667536
Delta: 0.004264313655091336 	  Loss: 1.6943052182992737 	 Accuracy: 0.28292046936114734
Delta: 0.0034505988605762175 	  Loss: 1.6940255977803564 	 Accuracy: 0.2803129074315515
Delta: 0.002957340045448143 	  Loss: 1.6936665919153457 	 Accuracy: 0.2816166883963494
Delta: 0.005149151770076631 	  Loss: 1.693955467950028 	 Accuracy: 0.28292046936114734
Delta: 0.004580617279441728 	  Loss: 1.6938719722112374 	 Accuracy: 0.2816166883963494
Delta: 0.004632708417944119 	  Loss: 1.694267002192485 	 Accuracy: 0.2803129074315515
Delta: 0.0033148570109990598 	  Loss: 1.6943519405773704 	 Accuracy: 0.2790091264667536
Delta: 0.003343937888742723 	  Loss: 1.6935145803308669 	 Accuracy: 0.2803129074315515
Delta: 8.696351104617651e-05 	  Loss: 1.6934307242879232 	 Accuracy: 0.2803129074315515
Delta: 5.65511144384506e-06 	  Loss: 1.693427453815625 	 Accuracy: 0.2803129074315515
Delta: 0.004188273653526859 	  Loss: 1.6936505382196674 	 Accuracy: 0.2816166883963494
Delta: 0.004786331785360908 	  Loss: 1.6937552424277404 	 Accuracy: 0.28292046936114734
Delta: 0.0033840103047232755 	  Loss: 1.6945230532637856 	 Accuracy: 0.2816166883963494
Delta: 0.004262302135720597 	  Loss: 1.6943247949877591 	 Accuracy: 0.2816166883963494
Delta: 0.003069330948730526 	  Loss: 1.6943262700668533 	 Accuracy: 0.2842242503259452
Delta: 0.003479080945326641 	  Loss: 1.6947012031338606 	 Accuracy: 0.2803129074315515
Delta: 0.004456833239455649 	  Loss: 1.694878408993059 	 Accuracy: 0.28292046936114734
Delta: 0.0017693164309883706 	  Loss: 1.6945776231617138 	 Accuracy: 0.2816166883963494
Delta: 2.700296947104533e-05 	  Loss: 1.6946737757530124 	 Accuracy: 0.2816166883963494
Delta: 4.399213049156833e-06 	  Loss: 1.6946638472981204 	 Accuracy: 0.2816166883963494
Delta: 4.488647845944424e-06 	  Loss: 1.69466761138978 	 Accuracy: 0.2777053455019557
Delta: 0.004723680733519593 	  Loss: 1.694537049589491 	 Accuracy: 0.2803129074315515
Delta: 0.0015293796624917184 	  Loss: 1.6945536724345172 	 Accuracy: 0.2803129074315515
Delta: 5.6216576605011945e-05 	  Loss: 1.694622998880311 	 Accuracy: 0.2803129074315515
Delta: 0.003616052646701116 	  Loss: 1.6948765252297489 	 Accuracy: 0.2803129074315515
Delta: 0.0012367886165970388 	  Loss: 1.694786015248591 	 Accuracy: 0.2816166883963494
Delta: 0.0016148526930491792 	  Loss: 1.6946997739253424 	 Accuracy: 0.28292046936114734
Delta: 0.004778396761829334 	  Loss: 1.6946517428790948 	 Accuracy: 0.27640156453715775
Delta: 0.004055928173656437 	  Loss: 1.6936128676211548 	 Accuracy: 0.2894393741851369
Delta: 0.007375875654867857 	  Loss: 1.693271646137302 	 Accuracy: 0.28552803129074317
Delta: 0.020984521417673565 	  Loss: 2.1588168554333986 	 Accuracy: 0.17079530638852672
Delta: 0.01894692202984239 	  Loss: 2.0498474323796305 	 Accuracy: 0.14863102998696218
Delta: 0.017848877377660978 	  Loss: 1.8662090112208223 	 Accuracy: 0.18383311603650587
Delta: 0.016611576097524887 	  Loss: 1.728829555837465 	 Accuracy: 0.21251629726205998
Delta: 0.01384351380128026 	  Loss: 1.6715374263549427 	 Accuracy: 0.21121251629726207

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010499971075872836 	  Loss: 1.6548870425748556 	 Accuracy: 0.20599739243807041
Delta: 0.006968754490043389 	  Loss: 1.6516321250565538 	 Accuracy: 0.20730117340286833
Delta: 0.00487916813877084 	  Loss: 1.6513118204489161 	 Accuracy: 0.20730117340286833
Delta: 0.004505111594386345 	  Loss: 1.6518415446341514 	 Accuracy: 0.20599739243807041
Delta: 0.004108939750536629 	  Loss: 1.6515148059016296 	 Accuracy: 0.20730117340286833
Delta: 0.0022205833726090703 	  Loss: 1.6514478131913863 	 Accuracy: 0.20599739243807041
Delta: 0.0010289232812665638 	  Loss: 1.6514195511627234 	 Accuracy: 0.20730117340286833
Delta: 0.0015429253409376834 	  Loss: 1.6513676077505888 	 Accuracy: 0.20599739243807041
Delta: 0.0005353047276838122 	  Loss: 1.6514570276951444 	 Accuracy: 0.20599739243807041
Delta: 0.0025284286023037413 	  Loss: 1.6513085990447471 	 Accuracy: 0.20599739243807041
Delta: 0.0007257649400099834 	  Loss: 1.6513713851713734 	 Accuracy: 0.20599739243807041
Delta: 0.0007425626648356641 	  Loss: 1.6512245138391988 	 Accuracy: 0.20730117340286833
Delta: 3.790910974900369e-05 	  Loss: 1.651237545195305 	 Accuracy: 0.20599739243807041
Delta: 5.38185300632128e-05 	  Loss: 1.6512103762406778 	 Accuracy: 0.2046936114732725
Delta: 0.0005387317601789419 	  Loss: 1.6512965246316478 	 Accuracy: 0.20599739243807041
Delta: 0.00155225180386049 	  Loss: 1.6513306152570886 	 Accuracy: 0.20599739243807041
Delta: 4.5897125428128554e-05 	  Loss: 1.6512677720833584 	 Accuracy: 0.20599739243807041
Delta: 2.0107887943974806e-05 	  Loss: 1.65122111361989 	 Accuracy: 0.20599739243807041
Delta: 0.0005118723986517106 	  Loss: 1.6511554172734049 	 Accuracy: 0.20599739243807041
Delta: 2.1214633578369243e-05 	  Loss: 1.6511010635403292 	 Accuracy: 0.20599739243807041
Delta: 0.001275862095095183 	  Loss: 1.6511572076394696 	 Accuracy: 0.20599739243807041
Delta: 0.001429097028133702 	  Loss: 1.6513942583082528 	 Accuracy: 0.20599739243807041
Delta: 0.002654993604329833 	  Loss: 1.6514473453973841 	 Accuracy: 0.20599739243807041
Delta: 4.83632225591775e-05 	  Loss: 1.651436923085857 	 Accuracy: 0.20599739243807041
Delta: 0.001111783526773196 	  Loss: 1.6513049464765015 	 Accuracy: 0.20599739243807041
Delta: 7.1761476576732e-05 	  Loss: 1.6514046067693955 	 Accuracy: 0.20599739243807041
Delta: 0.0005672313495124941 	  Loss: 1.651336563005867 	 Accuracy: 0.20599739243807041
Delta: 0.0008617796843162803 	  Loss: 1.6513532562878162 	 Accuracy: 0.20599739243807041
Delta: 0.0010496514681643462 	  Loss: 1.651163994759385 	 Accuracy: 0.20730117340286833
Delta: 0.0019471215968757415 	  Loss: 1.6510724716983765 	 Accuracy: 0.20599739243807041
Delta: 0.0016909362006484686 	  Loss: 1.6511751809684623 	 Accuracy: 0.20599739243807041
Delta: 3.699815906066734e-05 	  Loss: 1.651261256095813 	 Accuracy: 0.20599739243807041
Delta: 2.7954792702894133e-05 	  Loss: 1.6513889100185986 	 Accuracy: 0.20730117340286833
Delta: 0.002256215925809396 	  Loss: 1.6512668165412667 	 Accuracy: 0.20599739243807041
Delta: 0.0005346524613711267 	  Loss: 1.6513891000220646 	 Accuracy: 0.20599739243807041
Delta: 0.000527474480645066 	  Loss: 1.6513259332495678 	 Accuracy: 0.20599739243807041
Delta: 0.0007204991506775445 	  Loss: 1.651411453409375 	 Accuracy: 0.20599739243807041
Delta: 0.000549009460464699 	  Loss: 1.65140336428524 	 Accuracy: 0.20599739243807041
Delta: 3.8792688061350026e-05 	  Loss: 1.6513210680809913 	 Accuracy: 0.20599739243807041
Delta: 4.593906182876022e-05 	  Loss: 1.6513704162858507 	 Accuracy: 0.20599739243807041
Delta: 0.0011120659368223514 	  Loss: 1.6512700762505044 	 Accuracy: 0.20599739243807041
Delta: 0.0011215414871312405 	  Loss: 1.651346763700475 	 Accuracy: 0.20599739243807041
Delta: 9.759249658423537e-05 	  Loss: 1.6514201177615095 	 Accuracy: 0.20599739243807041
Delta: 9.024687654778487e-05 	  Loss: 1.6513733686059178 	 Accuracy: 0.20730117340286833
Delta: 0.0016855151615548295 	  Loss: 1.6514511727320804 	 Accuracy: 0.2046936114732725
Delta: 0.00010714470602674685 	  Loss: 1.651377863830156 	 Accuracy: 0.20599739243807041
Delta: 2.3859959602290997e-05 	  Loss: 1.6513957739900027 	 Accuracy: 0.20599739243807041
Delta: 5.950906945246109e-05 	  Loss: 1.6514030236569817 	 Accuracy: 0.20599739243807041
Delta: 0.0016970403689532349 	  Loss: 1.651242305914589 	 Accuracy: 0.20599739243807041
Delta: 7.796692359378043e-05 	  Loss: 1.6514101802381986 	 Accuracy: 0.20599739243807041
Delta: 6.69483035827192e-05 	  Loss: 1.6514880905002944 	 Accuracy: 0.20599739243807041
Delta: 6.660288431190786e-05 	  Loss: 1.6514155553019219 	 Accuracy: 0.20599739243807041
Delta: 7.426682559257966e-05 	  Loss: 1.6514728602870317 	 Accuracy: 0.2046936114732725
Delta: 3.935144281142301e-05 	  Loss: 1.6514210888544492 	 Accuracy: 0.20599739243807041
Delta: 8.555557892267154e-05 	  Loss: 1.6514036304383142 	 Accuracy: 0.20730117340286833
Delta: 4.161942794761294e-05 	  Loss: 1.651588701698448 	 Accuracy: 0.20599739243807041
Delta: 7.719567607822226e-05 	  Loss: 1.651362124199476 	 Accuracy: 0.20599739243807041
Delta: 6.507097112775089e-05 	  Loss: 1.6514026382768128 	 Accuracy: 0.20599739243807041
Delta: 1.3313040483291106e-05 	  Loss: 1.651396405723037 	 Accuracy: 0.20599739243807041
Delta: 0.0005524767221474676 	  Loss: 1.65138713094925 	 Accuracy: 0.20599739243807041
Delta: 5.513759493079511e-05 	  Loss: 1.6513909774403994 	 Accuracy: 0.20599739243807041
Delta: 0.0005163918425737868 	  Loss: 1.6514036155555099 	 Accuracy: 0.21121251629726207
Delta: 8.015069167595624e-05 	  Loss: 1.6516906713382562 	 Accuracy: 0.20599739243807041
Delta: 0.0005816373184730831 	  Loss: 1.6513170451437407 	 Accuracy: 0.20599739243807041
Delta: 4.488011772969638e-05 	  Loss: 1.6513597017153276 	 Accuracy: 0.20599739243807041
Delta: 0.0005671270783741826 	  Loss: 1.6514295818137072 	 Accuracy: 0.20599739243807041
Delta: 4.535350168625747e-05 	  Loss: 1.6512075408022282 	 Accuracy: 0.20599739243807041
Delta: 0.002190480990028687 	  Loss: 1.6505191985608965 	 Accuracy: 0.20599739243807041
Delta: 9.215954609449304e-05 	  Loss: 1.650933977399926 	 Accuracy: 0.20599739243807041
Delta: 0.0020298960535052664 	  Loss: 1.6514970253620795 	 Accuracy: 0.20599739243807041
Delta: 0.00272919919227123 	  Loss: 1.6515568834207288 	 Accuracy: 0.20599739243807041
Delta: 6.319763345880459e-05 	  Loss: 1.651457854062587 	 Accuracy: 0.20599739243807041
Delta: 0.000621244628796652 	  Loss: 1.6514957731897468 	 Accuracy: 0.20599739243807041
Delta: 4.5496465328492616e-05 	  Loss: 1.6513900100830559 	 Accuracy: 0.20730117340286833
Delta: 0.0006741758522664786 	  Loss: 1.6514803184809246 	 Accuracy: 0.20599739243807041
Delta: 0.003948793698476662 	  Loss: 1.6514488443514777 	 Accuracy: 0.20730117340286833
Delta: 0.0029713720394013788 	  Loss: 1.6516313361932946 	 Accuracy: 0.20730117340286833
Delta: 2.5251773808543683e-05 	  Loss: 1.651604936016143 	 Accuracy: 0.20730117340286833
Delta: 0.003420122501962174 	  Loss: 1.65158237312956 	 Accuracy: 0.20730117340286833
Delta: 0.0012501533516785458 	  Loss: 1.6515514223240801 	 Accuracy: 0.20599739243807041
Delta: 0.003281456797089369 	  Loss: 1.651622048486054 	 Accuracy: 0.2046936114732725
Delta: 0.0029580939997171487 	  Loss: 1.65191173968398 	 Accuracy: 0.20860495436766624
Delta: 0.0014819887278060338 	  Loss: 1.6516248620255087 	 Accuracy: 0.20730117340286833
Delta: 0.002789383481726829 	  Loss: 1.6519779540969526 	 Accuracy: 0.20860495436766624
Delta: 0.000967478197233825 	  Loss: 1.6517562268396295 	 Accuracy: 0.20860495436766624
Delta: 0.003489897085478756 	  Loss: 1.6511344522741913 	 Accuracy: 0.2033898305084746
Delta: 0.0007108970896411634 	  Loss: 1.6515832907584247 	 Accuracy: 0.20730117340286833
Delta: 0.002014181444929663 	  Loss: 1.6515019400539828 	 Accuracy: 0.20730117340286833
Delta: 5.586699880399664e-05 	  Loss: 1.651361513073169 	 Accuracy: 0.20860495436766624
Delta: 0.0008367653189316747 	  Loss: 1.6513315295924411 	 Accuracy: 0.20990873533246415
Delta: 0.0043299797668133215 	  Loss: 1.650819010505146 	 Accuracy: 0.20860495436766624
Delta: 0.0016070063024325584 	  Loss: 1.6508554628063097 	 Accuracy: 0.20599739243807041
Delta: 0.0020506131321024394 	  Loss: 1.6508289776089682 	 Accuracy: 0.20860495436766624
Delta: 0.002935401757141609 	  Loss: 1.6508427533072183 	 Accuracy: 0.20860495436766624
Delta: 0.0028624478748410604 	  Loss: 1.6509071373630326 	 Accuracy: 0.2046936114732725
Delta: 0.020986083713744785 	  Loss: 2.1592824274590168 	 Accuracy: 0.1681877444589309
Delta: 0.01905675903354119 	  Loss: 2.049277273267495 	 Accuracy: 0.14863102998696218
Delta: 0.0177792195849297 	  Loss: 1.8678523440434798 	 Accuracy: 0.20599739243807041
Delta: 0.01565902823109289 	  Loss: 1.7713617838883056 	 Accuracy: 0.21903520208604954
Delta: 0.013931501589198484 	  Loss: 1.7357028123242737 	 Accuracy: 0.23076923076923078
Delta: 0.01117959218628283 	  Loss: 1.7239670878394615 	 Accuracy: 0.2255541069100391

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00916529849001435 	  Loss: 1.7198948272663386 	 Accuracy: 0.22946544980443284
Delta: 0.00799357742880907 	  Loss: 1.716643970758867 	 Accuracy: 0.22816166883963493
Delta: 0.005201511298633235 	  Loss: 1.7164475191954147 	 Accuracy: 0.22816166883963493
Delta: 0.002920763824382109 	  Loss: 1.716826871461588 	 Accuracy: 0.22816166883963493
Delta: 0.001593617132210101 	  Loss: 1.7166157483601965 	 Accuracy: 0.22946544980443284
Delta: 0.0022735503251924234 	  Loss: 1.7166681933268335 	 Accuracy: 0.23076923076923078
Delta: 0.004355777880466751 	  Loss: 1.7162812934144098 	 Accuracy: 0.22946544980443284
Delta: 0.0038798605223219025 	  Loss: 1.7161225346975868 	 Accuracy: 0.22946544980443284
Delta: 0.0036535822518281827 	  Loss: 1.716498593260281 	 Accuracy: 0.22946544980443284
Delta: 0.0020769807706187836 	  Loss: 1.7163804946507837 	 Accuracy: 0.22946544980443284
Delta: 0.002025101120104511 	  Loss: 1.7164523778669434 	 Accuracy: 0.22946544980443284
Delta: 4.069902070869555e-06 	  Loss: 1.7164526541721103 	 Accuracy: 0.22946544980443284
Delta: 0.001940635684362421 	  Loss: 1.7164504112180077 	 Accuracy: 0.22946544980443284
Delta: 0.0031132481675545426 	  Loss: 1.7163650795751182 	 Accuracy: 0.22816166883963493
Delta: 0.0037046348507277075 	  Loss: 1.716541773330942 	 Accuracy: 0.22946544980443284
Delta: 0.0011525030869475382 	  Loss: 1.716494825933847 	 Accuracy: 0.22946544980443284
Delta: 0.003807531528825239 	  Loss: 1.7166606811385718 	 Accuracy: 0.22946544980443284
Delta: 0.004172508932182964 	  Loss: 1.716560534345595 	 Accuracy: 0.22946544980443284
Delta: 8.552529107123702e-05 	  Loss: 1.7167441004468396 	 Accuracy: 0.22946544980443284
Delta: 0.002648198266856973 	  Loss: 1.7164278954222116 	 Accuracy: 0.22946544980443284
Delta: 0.0013301091026136924 	  Loss: 1.7163330016730551 	 Accuracy: 0.22946544980443284
Delta: 0.0011064877372000393 	  Loss: 1.7162745921941498 	 Accuracy: 0.22946544980443284
Delta: 7.691764776074929e-05 	  Loss: 1.7164302582981759 	 Accuracy: 0.2242503259452412
Delta: 0.0031827745018193176 	  Loss: 1.7163354589847888 	 Accuracy: 0.22946544980443284
Delta: 0.0026816220148139815 	  Loss: 1.716348211344704 	 Accuracy: 0.22946544980443284
Delta: 0.0024809995266761795 	  Loss: 1.7163883032682747 	 Accuracy: 0.22946544980443284
Delta: 0.0015080273144348103 	  Loss: 1.7162751118271657 	 Accuracy: 0.22946544980443284
Delta: 0.0022382366503613986 	  Loss: 1.7161794819571008 	 Accuracy: 0.22946544980443284
Delta: 0.002889388641238138 	  Loss: 1.715978728083842 	 Accuracy: 0.22946544980443284
Delta: 0.0014276133328948437 	  Loss: 1.7159058292280602 	 Accuracy: 0.22946544980443284
Delta: 0.0038610017440265433 	  Loss: 1.7164066645044835 	 Accuracy: 0.2320730117340287
Delta: 0.0029339378774405145 	  Loss: 1.7167489820060795 	 Accuracy: 0.23076923076923078
Delta: 1.7015203810525076e-05 	  Loss: 1.71671584279042 	 Accuracy: 0.22685788787483702
Delta: 0.0019141532992571725 	  Loss: 1.716251758277724 	 Accuracy: 0.22946544980443284
Delta: 0.0022818076647364003 	  Loss: 1.7162679283317668 	 Accuracy: 0.23076923076923078
Delta: 0.0005316105693326595 	  Loss: 1.716265067293489 	 Accuracy: 0.23076923076923078
Delta: 0.0011618812351776604 	  Loss: 1.7167029624236427 	 Accuracy: 0.23076923076923078
Delta: 0.0009560327167196472 	  Loss: 1.7164942475636744 	 Accuracy: 0.23076923076923078
Delta: 0.0012071320265335278 	  Loss: 1.7164671613495814 	 Accuracy: 0.23076923076923078
Delta: 0.002535413693069587 	  Loss: 1.716066666218094 	 Accuracy: 0.23076923076923078
Delta: 0.00291864797795758 	  Loss: 1.7159025469899802 	 Accuracy: 0.23076923076923078
Delta: 0.002290791582673686 	  Loss: 1.716143574082688 	 Accuracy: 0.23076923076923078
Delta: 0.0011138941302807851 	  Loss: 1.7164942247694572 	 Accuracy: 0.23076923076923078
Delta: 5.159583343431467e-05 	  Loss: 1.7162426695763378 	 Accuracy: 0.23076923076923078
Delta: 5.1582455269530065e-05 	  Loss: 1.7162843859209642 	 Accuracy: 0.2320730117340287
Delta: 0.00011178452936772145 	  Loss: 1.7160346481341346 	 Accuracy: 0.23076923076923078
Delta: 0.0010178413306814727 	  Loss: 1.7161994933669424 	 Accuracy: 0.2333767926988266
Delta: 0.0037276988867995966 	  Loss: 1.7165800326976253 	 Accuracy: 0.2320730117340287
Delta: 0.0037204344653997325 	  Loss: 1.7165894433368272 	 Accuracy: 0.2333767926988266
Delta: 0.0034609138673603363 	  Loss: 1.7167637685010222 	 Accuracy: 0.2320730117340287
Delta: 0.0005824713983184894 	  Loss: 1.7165443623912335 	 Accuracy: 0.2320730117340287
Delta: 0.0038186328579306377 	  Loss: 1.7168170251886585 	 Accuracy: 0.2320730117340287
Delta: 0.003132721235929145 	  Loss: 1.7165510318996513 	 Accuracy: 0.2320730117340287
Delta: 0.0009702637087345767 	  Loss: 1.7167409499735315 	 Accuracy: 0.23468057366362452
Delta: 0.005084600701823948 	  Loss: 1.7168736434087237 	 Accuracy: 0.23468057366362452
Delta: 0.0020420476042509877 	  Loss: 1.7170378715587278 	 Accuracy: 0.2333767926988266
Delta: 0.0024563361193469424 	  Loss: 1.7167167969926531 	 Accuracy: 0.2255541069100391
Delta: 0.003154211737016934 	  Loss: 1.716318382102434 	 Accuracy: 0.2320730117340287
Delta: 0.0018350469811619558 	  Loss: 1.7166207191345428 	 Accuracy: 0.2320730117340287
Delta: 0.0027921040896561173 	  Loss: 1.716700246611504 	 Accuracy: 0.2320730117340287
Delta: 9.522781901380552e-05 	  Loss: 1.716654389113493 	 Accuracy: 0.2320730117340287
Delta: 0.0016322916931943083 	  Loss: 1.7166930364198927 	 Accuracy: 0.2320730117340287
Delta: 0.0023254667321134376 	  Loss: 1.7163946760422542 	 Accuracy: 0.2320730117340287
Delta: 0.003954478335426554 	  Loss: 1.7161747256658728 	 Accuracy: 0.2320730117340287
Delta: 0.0019170847418183874 	  Loss: 1.7164785510093759 	 Accuracy: 0.23468057366362452
Delta: 0.003323609433813957 	  Loss: 1.7165096271415992 	 Accuracy: 0.2333767926988266
Delta: 0.0026218871782290403 	  Loss: 1.7162788931525332 	 Accuracy: 0.2333767926988266
Delta: 0.0023407732666034593 	  Loss: 1.716090333675758 	 Accuracy: 0.2333767926988266
Delta: 0.0028003546065175195 	  Loss: 1.7158081285164495 	 Accuracy: 0.23468057366362452
Delta: 0.0029303385102293334 	  Loss: 1.7162690576062873 	 Accuracy: 0.23598435462842243
Delta: 0.002275228308822245 	  Loss: 1.7162073117043113 	 Accuracy: 0.2333767926988266
Delta: 0.0026490194657064624 	  Loss: 1.7166671933398976 	 Accuracy: 0.2333767926988266
Delta: 0.0009652071535379268 	  Loss: 1.7163666804167712 	 Accuracy: 0.2333767926988266
Delta: 0.0013410122971911646 	  Loss: 1.7163537814613 	 Accuracy: 0.22816166883963493
Delta: 0.003607586493448399 	  Loss: 1.7159435945333656 	 Accuracy: 0.2320730117340287
Delta: 0.0025928796054009973 	  Loss: 1.7154059644786406 	 Accuracy: 0.23076923076923078
Delta: 0.0020463186374372155 	  Loss: 1.7155920004220198 	 Accuracy: 0.2320730117340287
Delta: 0.0005780023586006197 	  Loss: 1.7154050824317488 	 Accuracy: 0.2320730117340287
Delta: 0.0015985472691749847 	  Loss: 1.7154749043912938 	 Accuracy: 0.2320730117340287
Delta: 0.0027122216086619424 	  Loss: 1.7154032288985315 	 Accuracy: 0.2320730117340287
Delta: 0.0033903903816605006 	  Loss: 1.7151508591871623 	 Accuracy: 0.2320730117340287
Delta: 0.0008188891443235928 	  Loss: 1.715297431013637 	 Accuracy: 0.23598435462842243
Delta: 3.507632508084473e-05 	  Loss: 1.7152904111103808 	 Accuracy: 0.23468057366362452
Delta: 0.001846507275614033 	  Loss: 1.7160566068875869 	 Accuracy: 0.2242503259452412
Delta: 0.0034327255421535887 	  Loss: 1.7163522006035277 	 Accuracy: 0.2320730117340287
Delta: 0.0023563521286569123 	  Loss: 1.716058997837778 	 Accuracy: 0.2320730117340287
Delta: 0.0037782629066525643 	  Loss: 1.7163118195786815 	 Accuracy: 0.2320730117340287
Delta: 0.0017795781576021787 	  Loss: 1.7160965022934875 	 Accuracy: 0.2320730117340287
Delta: 0.0028606004641313597 	  Loss: 1.716479718909357 	 Accuracy: 0.2320730117340287
Delta: 0.003004772752738012 	  Loss: 1.716065877986232 	 Accuracy: 0.2320730117340287
Delta: 0.00568704255926098 	  Loss: 1.7150122848177722 	 Accuracy: 0.2320730117340287
Delta: 0.004694156738302803 	  Loss: 1.7154654415125563 	 Accuracy: 0.22816166883963493
Delta: 0.0015477254551288177 	  Loss: 1.7151453034279431 	 Accuracy: 0.2320730117340287
Delta: 4.316246224370246e-05 	  Loss: 1.7153584084157938 	 Accuracy: 0.2320730117340287
Delta: 0.021187790226294963 	  Loss: 2.1597084835268294 	 Accuracy: 0.13298565840938723
Delta: 0.019222171106786316 	  Loss: 2.0508731801344933 	 Accuracy: 0.1864406779661017
Delta: 0.018556419597205324 	  Loss: 1.8487877113041398 	 Accuracy: 0.21251629726205998
Delta: 0.01595823304905386 	  Loss: 1.724583342876985 	 Accuracy: 0.20990873533246415
Delta: 0.012181493319660487 	  Loss: 1.6926482071123052 	 Accuracy: 0.21121251629726207

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009351579438761993 	  Loss: 1.682583561043745 	 Accuracy: 0.21642764015645372
Delta: 0.006485582193350854 	  Loss: 1.6821125857378756 	 Accuracy: 0.21773142112125163
Delta: 0.004580530696578433 	  Loss: 1.682048457910813 	 Accuracy: 0.21903520208604954
Delta: 0.001286111802416789 	  Loss: 1.682193430413601 	 Accuracy: 0.21903520208604954
Delta: 0.0022200767768839336 	  Loss: 1.6820287019430364 	 Accuracy: 0.21903520208604954
Delta: 0.0031647033882369327 	  Loss: 1.6821078268706378 	 Accuracy: 0.21903520208604954
Delta: 0.002004467063892769 	  Loss: 1.6820415320125393 	 Accuracy: 0.21903520208604954
Delta: 0.0024195433796688533 	  Loss: 1.6818436045257856 	 Accuracy: 0.22685788787483702
Delta: 0.009659493384599404 	  Loss: 1.6713380571022625 	 Accuracy: 0.2255541069100391
Delta: 0.003923533443709784 	  Loss: 1.6712319480376763 	 Accuracy: 0.22294654498044328
Delta: 0.0027687397045708393 	  Loss: 1.671388918330818 	 Accuracy: 0.22294654498044328
Delta: 0.0005322991619066035 	  Loss: 1.6713724802513434 	 Accuracy: 0.22294654498044328
Delta: 0.0024124684166973555 	  Loss: 1.6715518742208761 	 Accuracy: 0.22033898305084745
Delta: 0.0030970915769693587 	  Loss: 1.6714883569975796 	 Accuracy: 0.22294654498044328
Delta: 0.0014793401829216969 	  Loss: 1.6714134513657295 	 Accuracy: 0.22294654498044328
Delta: 7.11530762745312e-05 	  Loss: 1.6715201290700477 	 Accuracy: 0.22294654498044328
Delta: 0.0026323535266821138 	  Loss: 1.67173999216177 	 Accuracy: 0.22294654498044328
Delta: 0.0010706579540610813 	  Loss: 1.6715009086215655 	 Accuracy: 0.22294654498044328
Delta: 9.315898305061363e-05 	  Loss: 1.6715737887028612 	 Accuracy: 0.22294654498044328
Delta: 4.775779973793848e-06 	  Loss: 1.6715692403519484 	 Accuracy: 0.22294654498044328
Delta: 2.2873867778703522e-05 	  Loss: 1.6714971075336988 	 Accuracy: 0.22294654498044328
Delta: 0.0016977739491025714 	  Loss: 1.6713391986052244 	 Accuracy: 0.22294654498044328
Delta: 0.0013289417286076488 	  Loss: 1.6715662964841882 	 Accuracy: 0.22294654498044328
Delta: 8.348180646352518e-06 	  Loss: 1.6715268215187842 	 Accuracy: 0.22294654498044328
Delta: 9.670057335524836e-05 	  Loss: 1.6713867777000135 	 Accuracy: 0.22294654498044328
Delta: 9.579835920981599e-05 	  Loss: 1.6714532785845873 	 Accuracy: 0.22294654498044328
Delta: 9.722909156913883e-05 	  Loss: 1.6712166600095046 	 Accuracy: 0.22294654498044328
Delta: 5.567479033392398e-05 	  Loss: 1.6713290612654308 	 Accuracy: 0.22294654498044328
Delta: 0.0005697128554014436 	  Loss: 1.6714179508001463 	 Accuracy: 0.22685788787483702
Delta: 0.0005560501432364011 	  Loss: 1.6716165844172521 	 Accuracy: 0.22164276401564537
Delta: 0.00012981009903693228 	  Loss: 1.6708472410037627 	 Accuracy: 0.22294654498044328
Delta: 9.073662302226741e-05 	  Loss: 1.6714264872388918 	 Accuracy: 0.2242503259452412
Delta: 0.002697983908895563 	  Loss: 1.6714678434084569 	 Accuracy: 0.22685788787483702
Delta: 0.0036103720011681833 	  Loss: 1.6715520523126735 	 Accuracy: 0.22294654498044328
Delta: 0.0037418533005987562 	  Loss: 1.6719984972964905 	 Accuracy: 0.22164276401564537
Delta: 0.0023694905033522086 	  Loss: 1.6723430227179084 	 Accuracy: 0.22294654498044328
Delta: 0.0005649510018153099 	  Loss: 1.672427944455155 	 Accuracy: 0.22294654498044328
Delta: 0.0011965113433832035 	  Loss: 1.6722648609720268 	 Accuracy: 0.22033898305084745
Delta: 0.004898201978369605 	  Loss: 1.6738804055451146 	 Accuracy: 0.22294654498044328
Delta: 0.002365426183127775 	  Loss: 1.6736339771730604 	 Accuracy: 0.22294654498044328
Delta: 0.0001059269680350199 	  Loss: 1.6735548070214548 	 Accuracy: 0.22294654498044328
Delta: 0.0025693776530207662 	  Loss: 1.6734348610770207 	 Accuracy: 0.22164276401564537
Delta: 0.002062251653139838 	  Loss: 1.6733564564804357 	 Accuracy: 0.2242503259452412
Delta: 0.0005525087479461007 	  Loss: 1.6733824144780522 	 Accuracy: 0.22294654498044328
Delta: 0.0013580061976161157 	  Loss: 1.6731591437738231 	 Accuracy: 0.22294654498044328
Delta: 0.0006779873246357433 	  Loss: 1.6736697979564834 	 Accuracy: 0.22294654498044328
Delta: 0.002746815484142332 	  Loss: 1.6739482112739679 	 Accuracy: 0.22294654498044328
Delta: 0.0028575967552221123 	  Loss: 1.6739204513754786 	 Accuracy: 0.2242503259452412
Delta: 0.0039745401905421284 	  Loss: 1.6736794908126944 	 Accuracy: 0.2242503259452412
Delta: 0.0006174675982495213 	  Loss: 1.6736666734994605 	 Accuracy: 0.2242503259452412
Delta: 0.003082415121473327 	  Loss: 1.6736558708217428 	 Accuracy: 0.2255541069100391
Delta: 0.0043818989824800265 	  Loss: 1.6727855335844921 	 Accuracy: 0.2255541069100391
Delta: 0.0031626412085306575 	  Loss: 1.6727490338216469 	 Accuracy: 0.22685788787483702
Delta: 0.002736699416066022 	  Loss: 1.671528090843807 	 Accuracy: 0.22816166883963493
Delta: 0.002967547332312498 	  Loss: 1.6713089038730722 	 Accuracy: 0.22294654498044328
Delta: 0.0017240416219125936 	  Loss: 1.671640525047541 	 Accuracy: 0.2255541069100391
Delta: 4.478707577919166e-05 	  Loss: 1.6715668453307526 	 Accuracy: 0.2255541069100391
Delta: 3.827524194066812e-06 	  Loss: 1.6715731091655985 	 Accuracy: 0.2255541069100391
Delta: 3.827528623380058e-06 	  Loss: 1.6715668609483565 	 Accuracy: 0.2255541069100391
Delta: 0.004126872523285008 	  Loss: 1.6722589558187733 	 Accuracy: 0.2242503259452412
Delta: 0.001904586087679093 	  Loss: 1.6725222325233438 	 Accuracy: 0.22816166883963493
Delta: 0.0025368820536431002 	  Loss: 1.6720928004715043 	 Accuracy: 0.2242503259452412
Delta: 0.005607859639910719 	  Loss: 1.6740874770532312 	 Accuracy: 0.2255541069100391
Delta: 0.004504870494001171 	  Loss: 1.6739387622946886 	 Accuracy: 0.2255541069100391
Delta: 0.002976944408324584 	  Loss: 1.6727909700175152 	 Accuracy: 0.2255541069100391
Delta: 0.002202916865240531 	  Loss: 1.6729114468873498 	 Accuracy: 0.2255541069100391
Delta: 0.00135493869917198 	  Loss: 1.672970726993619 	 Accuracy: 0.2255541069100391
Delta: 0.002124670475548969 	  Loss: 1.6728084053050825 	 Accuracy: 0.22685788787483702
Delta: 0.001590586082314768 	  Loss: 1.6728424976245826 	 Accuracy: 0.22685788787483702
Delta: 0.003337083115346889 	  Loss: 1.6727952234472439 	 Accuracy: 0.22685788787483702
Delta: 0.0008958311899692216 	  Loss: 1.6727529266144208 	 Accuracy: 0.2255541069100391
Delta: 2.266517172766237e-05 	  Loss: 1.6727116032439955 	 Accuracy: 0.2255541069100391
Delta: 3.566465104569129e-05 	  Loss: 1.6728575545413384 	 Accuracy: 0.2242503259452412
Delta: 0.002394581229549596 	  Loss: 1.672580613441808 	 Accuracy: 0.2255541069100391
Delta: 0.0008613350574640168 	  Loss: 1.6728450658387992 	 Accuracy: 0.2255541069100391
Delta: 0.0005442706062197526 	  Loss: 1.6728440760958163 	 Accuracy: 0.22685788787483702
Delta: 0.001890232829302361 	  Loss: 1.6726842616920632 	 Accuracy: 0.2320730117340287
Delta: 0.004022233038873388 	  Loss: 1.6731258275698995 	 Accuracy: 0.22685788787483702
Delta: 0.0021662081443865667 	  Loss: 1.6731091761830283 	 Accuracy: 0.22685788787483702
Delta: 0.004469996533090571 	  Loss: 1.6728890485598853 	 Accuracy: 0.2255541069100391
Delta: 0.004508590994439879 	  Loss: 1.6734420906509935 	 Accuracy: 0.22685788787483702
Delta: 0.0026157100295166914 	  Loss: 1.6738019021656958 	 Accuracy: 0.2255541069100391
Delta: 0.00430515094744008 	  Loss: 1.6745126031079938 	 Accuracy: 0.23468057366362452
Delta: 0.003936872028837648 	  Loss: 1.6732353575330576 	 Accuracy: 0.22685788787483702
Delta: 0.001936605719675434 	  Loss: 1.6734007203155699 	 Accuracy: 0.22164276401564537
Delta: 0.003193341361029329 	  Loss: 1.6737393357177612 	 Accuracy: 0.2255541069100391
Delta: 0.004099422008977806 	  Loss: 1.674207435932591 	 Accuracy: 0.2242503259452412
Delta: 0.0032437122742843753 	  Loss: 1.6748759097073307 	 Accuracy: 0.2255541069100391
Delta: 0.002136852544788055 	  Loss: 1.6752152586772695 	 Accuracy: 0.22164276401564537
Delta: 0.004825005801014932 	  Loss: 1.675099043542858 	 Accuracy: 0.2255541069100391
Delta: 0.0026995968507483262 	  Loss: 1.6758513541743592 	 Accuracy: 0.22816166883963493
Delta: 0.0038499678519451005 	  Loss: 1.6761240849731913 	 Accuracy: 0.22164276401564537
Delta: 0.0021096581809222836 	  Loss: 1.6761053285838206 	 Accuracy: 0.2242503259452412
Delta: 0.0034280204296578895 	  Loss: 1.6743253596916794 	 Accuracy: 0.2255541069100391
Delta: 0.004144992804147154 	  Loss: 1.6759157902641015 	 Accuracy: 0.2255541069100391
Delta: 0.021050909174850696 	  Loss: 2.1588114861058214 	 Accuracy: 0.16688396349413298
Delta: 0.019207132481497143 	  Loss: 2.0458472837954886 	 Accuracy: 0.14993481095176012
Delta: 0.01796805448306037 	  Loss: 1.8619400013400549 	 Accuracy: 0.16036505867014342
Delta: 0.016415183109254765 	  Loss: 1.754379064170565 	 Accuracy: 0.18904823989569752
Delta: 0.013968564413296618 	  Loss: 1.7048491798392864 	 Accuracy: 0.1877444589308996

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009430672534567667 	  Loss: 1.6917715036753684 	 Accuracy: 0.18383311603650587
Delta: 0.007606002608756629 	  Loss: 1.6886489536703309 	 Accuracy: 0.18383311603650587
Delta: 0.006247171912059534 	  Loss: 1.6867550730078564 	 Accuracy: 0.17992177314211213
Delta: 0.0041388887418990225 	  Loss: 1.6866326353393668 	 Accuracy: 0.18252933507170796
Delta: 0.002761863153236368 	  Loss: 1.687272684125622 	 Accuracy: 0.18252933507170796
Delta: 0.0014401771141512082 	  Loss: 1.6873331138603627 	 Accuracy: 0.18122555410691005
Delta: 0.002307344304468721 	  Loss: 1.687549228862541 	 Accuracy: 0.18122555410691005
Delta: 6.186422307191178e-05 	  Loss: 1.6875606858267447 	 Accuracy: 0.18122555410691005
Delta: 5.1553943882500276e-05 	  Loss: 1.6873914660757046 	 Accuracy: 0.18122555410691005
Delta: 0.0017708521711170967 	  Loss: 1.6875782292731834 	 Accuracy: 0.18122555410691005
Delta: 0.0011722779979095404 	  Loss: 1.6875589528732897 	 Accuracy: 0.18122555410691005
Delta: 0.001439715178288993 	  Loss: 1.687612315683984 	 Accuracy: 0.18122555410691005
Delta: 0.0016221864712500848 	  Loss: 1.6875736507990053 	 Accuracy: 0.18122555410691005
Delta: 0.0005329059953539806 	  Loss: 1.6873412019627287 	 Accuracy: 0.18122555410691005
Delta: 0.0013964005630513886 	  Loss: 1.687600763748329 	 Accuracy: 0.18122555410691005
Delta: 6.507698546290386e-05 	  Loss: 1.6876188208355294 	 Accuracy: 0.18122555410691005
Delta: 2.514192928051172e-05 	  Loss: 1.6875789804013357 	 Accuracy: 0.18122555410691005
Delta: 0.00094844539416148 	  Loss: 1.6875868632225106 	 Accuracy: 0.18122555410691005
Delta: 0.0011434174862656175 	  Loss: 1.6873032421992467 	 Accuracy: 0.18122555410691005
Delta: 0.0005521593858677284 	  Loss: 1.687571165772348 	 Accuracy: 0.18122555410691005
Delta: 9.009340787421828e-05 	  Loss: 1.6876994859459362 	 Accuracy: 0.18122555410691005
Delta: 8.823643226525281e-05 	  Loss: 1.68746305798119 	 Accuracy: 0.18122555410691005
Delta: 6.048218805135117e-05 	  Loss: 1.6876227209184533 	 Accuracy: 0.18122555410691005
Delta: 3.49369962094199e-05 	  Loss: 1.6876980385053708 	 Accuracy: 0.18122555410691005
Delta: 1.891988247636009e-06 	  Loss: 1.6877021556763814 	 Accuracy: 0.18122555410691005
Delta: 9.68226667362495e-06 	  Loss: 1.6877086503581331 	 Accuracy: 0.18122555410691005
Delta: 1.4834664082593887e-05 	  Loss: 1.6876796186413683 	 Accuracy: 0.17992177314211213
Delta: 0.005631732256695219 	  Loss: 1.6876484328274708 	 Accuracy: 0.17861799217731422
Delta: 0.003830982531615173 	  Loss: 1.6877447514318717 	 Accuracy: 0.17861799217731422
Delta: 0.004655807759446105 	  Loss: 1.6885032099865152 	 Accuracy: 0.17861799217731422
Delta: 0.004442413833007118 	  Loss: 1.689134464079768 	 Accuracy: 0.1773142112125163
Delta: 0.002913604624556393 	  Loss: 1.689951311940812 	 Accuracy: 0.17861799217731422
Delta: 0.0038575607753128394 	  Loss: 1.6890067936623168 	 Accuracy: 0.17861799217731422
Delta: 0.0030887284096539434 	  Loss: 1.689109925099599 	 Accuracy: 0.17861799217731422
Delta: 0.0024341297845759326 	  Loss: 1.6887636279424383 	 Accuracy: 0.17861799217731422
Delta: 0.0013570760036704696 	  Loss: 1.6888809067346724 	 Accuracy: 0.1773142112125163
Delta: 0.002343624983292777 	  Loss: 1.6887331927880842 	 Accuracy: 0.17861799217731422
Delta: 7.233440550509817e-05 	  Loss: 1.6889194617661474 	 Accuracy: 0.17861799217731422
Delta: 0.0025481523089457433 	  Loss: 1.6889218202894605 	 Accuracy: 0.17861799217731422
Delta: 0.004336391466756584 	  Loss: 1.6887300129095908 	 Accuracy: 0.17861799217731422
Delta: 0.0027523905035023925 	  Loss: 1.6885269925031665 	 Accuracy: 0.17861799217731422
Delta: 0.003529013512400973 	  Loss: 1.6880892574080402 	 Accuracy: 0.1760104302477184
Delta: 0.005114513511468965 	  Loss: 1.689280748005718 	 Accuracy: 0.17861799217731422
Delta: 0.0037757949414587116 	  Loss: 1.68851345691199 	 Accuracy: 0.17861799217731422
Delta: 0.0026014139158298086 	  Loss: 1.6887614877977706 	 Accuracy: 0.17861799217731422
Delta: 0.004069510050053039 	  Loss: 1.6889206620041026 	 Accuracy: 0.17861799217731422
Delta: 2.038406124009761e-05 	  Loss: 1.6889410523484822 	 Accuracy: 0.17861799217731422
Delta: 0.001319004729254363 	  Loss: 1.6888830909708967 	 Accuracy: 0.17861799217731422
Delta: 7.376638432413661e-05 	  Loss: 1.6889067595715983 	 Accuracy: 0.17861799217731422
Delta: 1.3461843842446636e-08 	  Loss: 1.688906752711243 	 Accuracy: 0.17992177314211213
converged at iter  54
Delta: 0.02093431422515735 	  Loss: 2.175008303967365 	 Accuracy: 0.19556714471968709
Delta: 0.018343075383465957 	  Loss: 2.1015143380395394 	 Accuracy: 0.4002607561929596
Delta: 0.015746568309099998 	  Loss: 2.005257772376936 	 Accuracy: 0.5202086049543677
Delta: 0.014514992797557982 	  Loss: 1.8881735789919665 	 Accuracy: 0.5645371577574967
Delta: 0.012513371738600582 	  Loss: 1.7870022765030729 	 Accuracy: 0.5775749674054759
Delta: 0.010748444478485802 	  Loss: 1.7242358998495302 	 Accuracy: 0.6114732724902217
Delta: 0.0098196818495091 	  Loss: 1.6858400549190087 	 Accuracy: 0.6492829204693612
Delta: 0.009013347907910464 	  Loss: 1.6603442662895005 	 Accuracy: 0.6805736636245111
Delta: 0.008720459666772429 	  Loss: 1.6406699677706333 	 Accuracy: 0.6923076923076923
Delta: 0.008132217479373677 	  Loss: 1.6255827454309744 	 Accuracy: 0.7131681877444589
Delta: 0.008286028066170698 	  Loss: 1.6134130413833359 	 Accuracy: 0.7392438070404173
Delta: 0.008646104196296987 	  Loss: 1.60222052666848 	 Accuracy: 0.7640156453715776
Delta: 0.008136061442012746 	  Loss: 1.5920943080311596 	 Accuracy: 0.7940026075619296
Delta: 0.007787801366408588 	  Loss: 1.582969010699761 	 Accuracy: 0.817470664928292
Delta: 0.007666772838094258 	  Loss: 1.574075139543842 	 Accuracy: 0.8370273794002607
Delta: 0.006550347257158285 	  Loss: 1.5674926320349492 	 Accuracy: 0.8448500651890483
Delta: 0.006354629763765815 	  Loss: 1.5616162602207266 	 Accuracy: 0.8526727509778357
Delta: 0.0061052014206350175 	  Loss: 1.5557232332874351 	 Accuracy: 0.8578878748370273
Delta: 0.006213184445747882 	  Loss: 1.5510785582158273 	 Accuracy: 0.8578878748370273
Delta: 0.004600003941908696 	  Loss: 1.5472106341340401 	 Accuracy: 0.8604954367666232
Delta: 0.005875308004267483 	  Loss: 1.5432365019630083 	 Accuracy: 0.864406779661017
Delta: 0.003872897372344042 	  Loss: 1.540991045627359 	 Accuracy: 0.8709256844850065
Delta: 0.004511477074321581 	  Loss: 1.5389985165569036 	 Accuracy: 0.8657105606258149
Delta: 0.004136675676215719 	  Loss: 1.537296367107019 	 Accuracy: 0.8722294654498044
Delta: 0.003416066370497424 	  Loss: 1.5358343172996487 	 Accuracy: 0.8709256844850065
Delta: 0.0034707609174376326 	  Loss: 1.5347436309148972 	 Accuracy: 0.8722294654498044
Delta: 0.003628933020280995 	  Loss: 1.5340173884101684 	 Accuracy: 0.8696219035202086
Delta: 0.00110816494581829 	  Loss: 1.5332675042994353 	 Accuracy: 0.8722294654498044

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.003228537213377424 	  Loss: 1.5326674197367298 	 Accuracy: 0.8696219035202086
Delta: 0.0023409539182975537 	  Loss: 1.5321441279050627 	 Accuracy: 0.8709256844850065
Delta: 0.0035280560074403755 	  Loss: 1.5316348239758855 	 Accuracy: 0.8735332464146024
Delta: 0.0029795821694862694 	  Loss: 1.5311588132094105 	 Accuracy: 0.8683181225554107
Delta: 0.0033283670702757557 	  Loss: 1.5308408674358764 	 Accuracy: 0.8761408083441982
Delta: 0.0018363920408025031 	  Loss: 1.5304949829725836 	 Accuracy: 0.8709256844850065
Delta: 0.0011567770611471324 	  Loss: 1.5302416953265272 	 Accuracy: 0.8696219035202086
Delta: 0.0020852906280003167 	  Loss: 1.5299979660579262 	 Accuracy: 0.8709256844850065
Delta: 0.002614549865094531 	  Loss: 1.5297817670076994 	 Accuracy: 0.878748370273794
Delta: 0.0012809308287957935 	  Loss: 1.5296324796667964 	 Accuracy: 0.8696219035202086
Delta: 0.0031383060515191717 	  Loss: 1.5295090627582164 	 Accuracy: 0.8722294654498044
Delta: 0.002323317174509003 	  Loss: 1.529324012039297 	 Accuracy: 0.8670143415906127
Delta: 0.0011980364822801576 	  Loss: 1.5291452925189564 	 Accuracy: 0.8709256844850065
Delta: 0.000561104505544088 	  Loss: 1.5290473816379424 	 Accuracy: 0.864406779661017
Delta: 0.0032988014038065985 	  Loss: 1.5289608012988145 	 Accuracy: 0.8735332464146024
Delta: 0.0018574268069304564 	  Loss: 1.5287833698620825 	 Accuracy: 0.877444589308996
Delta: 0.0012690835042172505 	  Loss: 1.5286864493023864 	 Accuracy: 0.8722294654498044
Delta: 0.0023804054655519806 	  Loss: 1.5285298784521077 	 Accuracy: 0.877444589308996
Delta: 0.0020684347550534365 	  Loss: 1.5284366665984948 	 Accuracy: 0.8722294654498044
Delta: 0.0030570657180890577 	  Loss: 1.5283735839156511 	 Accuracy: 0.8722294654498044
Delta: 0.0027629044165893963 	  Loss: 1.528269762078277 	 Accuracy: 0.8761408083441982
Delta: 0.002426212133149945 	  Loss: 1.5281804108641712 	 Accuracy: 0.8709256844850065
Delta: 0.0011546670551925626 	  Loss: 1.5280972096145644 	 Accuracy: 0.8748370273794003
Delta: 0.00253049386292445 	  Loss: 1.5280961545481628 	 Accuracy: 0.8748370273794003
Delta: 0.002102111970899428 	  Loss: 1.528013282923072 	 Accuracy: 0.8761408083441982
Delta: 0.001942209585315325 	  Loss: 1.5279249752488415 	 Accuracy: 0.8748370273794003
Delta: 0.0010443827302778486 	  Loss: 1.5278422556506674 	 Accuracy: 0.877444589308996
Delta: 0.002049712952981047 	  Loss: 1.5277853372161254 	 Accuracy: 0.8696219035202086
Delta: 4.8768737104819515e-05 	  Loss: 1.5277586275546096 	 Accuracy: 0.864406779661017
Delta: 0.0013261336892258224 	  Loss: 1.5277564519313207 	 Accuracy: 0.8683181225554107
Delta: 0.0019452011357661493 	  Loss: 1.5276995483976137 	 Accuracy: 0.8683181225554107
Delta: 0.0011860023954829197 	  Loss: 1.5276635365917208 	 Accuracy: 0.8709256844850065
Delta: 0.0006326615064604649 	  Loss: 1.527607719250402 	 Accuracy: 0.8670143415906127
Delta: 0.001999763831242037 	  Loss: 1.5275805695509512 	 Accuracy: 0.8683181225554107
Delta: 0.0015541437760347263 	  Loss: 1.5275654179594873 	 Accuracy: 0.8683181225554107
Delta: 0.0017623322283284047 	  Loss: 1.5275476583733552 	 Accuracy: 0.8683181225554107
Delta: 0.0005106812407059571 	  Loss: 1.5275346923950308 	 Accuracy: 0.8657105606258149
Delta: 0.00251260577782437 	  Loss: 1.5275735300839695 	 Accuracy: 0.8709256844850065
Delta: 0.0024265305006771275 	  Loss: 1.527510684800335 	 Accuracy: 0.8683181225554107
Delta: 0.0012587077291887953 	  Loss: 1.5274661774622675 	 Accuracy: 0.8696219035202086
Delta: 1.4439668932918804e-05 	  Loss: 1.5274309319185633 	 Accuracy: 0.8709256844850065
Delta: 0.0006754699936221396 	  Loss: 1.5273906987932133 	 Accuracy: 0.8722294654498044
Delta: 0.0017766818413914142 	  Loss: 1.527357218755534 	 Accuracy: 0.8670143415906127
Delta: 0.002509662720447682 	  Loss: 1.5273074140246865 	 Accuracy: 0.8683181225554107
Delta: 0.001241748841933274 	  Loss: 1.527274547347809 	 Accuracy: 0.8709256844850065
Delta: 0.0009694545542272419 	  Loss: 1.527263193622738 	 Accuracy: 0.8709256844850065
Delta: 0.0023200433148223313 	  Loss: 1.5272384652652096 	 Accuracy: 0.8709256844850065
Delta: 0.0009406331470600482 	  Loss: 1.5272190128265968 	 Accuracy: 0.8709256844850065
Delta: 0.0014198704987287696 	  Loss: 1.5271920464813693 	 Accuracy: 0.8696219035202086
Delta: 0.0018461683227908247 	  Loss: 1.5271504595047478 	 Accuracy: 0.8683181225554107
Delta: 0.0013747337884720894 	  Loss: 1.5271276711516084 	 Accuracy: 0.8709256844850065
Delta: 0.002492360149669612 	  Loss: 1.5271241900845094 	 Accuracy: 0.8670143415906127
Delta: 3.064254990764849e-05 	  Loss: 1.5271201865434483 	 Accuracy: 0.8696219035202086
Delta: 0.0013315594318821576 	  Loss: 1.5271121222619848 	 Accuracy: 0.8683181225554107
Delta: 0.001875940452710978 	  Loss: 1.5270928074586938 	 Accuracy: 0.8709256844850065
Delta: 0.0017819138932000376 	  Loss: 1.527029792857478 	 Accuracy: 0.8683181225554107
Delta: 2.8246068399671733e-05 	  Loss: 1.5270473303237961 	 Accuracy: 0.8657105606258149
Delta: 0.0007178176336278614 	  Loss: 1.5270129000899315 	 Accuracy: 0.8670143415906127
Delta: 0.0005208973346952529 	  Loss: 1.526999766375985 	 Accuracy: 0.8683181225554107
Delta: 0.0005139858803821482 	  Loss: 1.5269956066815424 	 Accuracy: 0.863102998696219
Delta: 0.0008314750704334139 	  Loss: 1.5269961842073312 	 Accuracy: 0.864406779661017
Delta: 0.0019291409887685867 	  Loss: 1.5269955479232404 	 Accuracy: 0.8696219035202086
Delta: 0.0012203615425914354 	  Loss: 1.5269758971900762 	 Accuracy: 0.8683181225554107
Delta: 0.0012866163145851494 	  Loss: 1.5269664732381385 	 Accuracy: 0.8683181225554107
Delta: 0.0008673774747965272 	  Loss: 1.5269490384484548 	 Accuracy: 0.8670143415906127
Delta: 0.00101190836362265 	  Loss: 1.5269397645007952 	 Accuracy: 0.8683181225554107
Delta: 1.2330955672253507e-05 	  Loss: 1.5269241222926826 	 Accuracy: 0.8696219035202086
Delta: 0.0011314528631650085 	  Loss: 1.5269112939152847 	 Accuracy: 0.8670143415906127
Delta: 0.001065892347794056 	  Loss: 1.526891142726143 	 Accuracy: 0.8696219035202086
Delta: 0.0022875012046467205 	  Loss: 1.526886853509753 	 Accuracy: 0.8696219035202086
Delta: 0.0017447232687229518 	  Loss: 1.5268824122507838 	 Accuracy: 0.8670143415906127
Delta: 0.0013298586857474115 	  Loss: 1.5268859716478955 	 Accuracy: 0.8670143415906127
Delta: 0.02089801663858631 	  Loss: 2.1752511539135373 	 Accuracy: 0.1877444589308996
Delta: 0.01828701850505016 	  Loss: 2.101539673204083 	 Accuracy: 0.3663624511082138
Delta: 0.015721254930793932 	  Loss: 2.0060777496320776 	 Accuracy: 0.4067796610169492
Delta: 0.014783402390280406 	  Loss: 1.8998598887574558 	 Accuracy: 0.4002607561929596
Delta: 0.013538012041556097 	  Loss: 1.8027345353966198 	 Accuracy: 0.33376792698826596
Delta: 0.011603063347458366 	  Loss: 1.7348770028016443 	 Accuracy: 0.2907431551499348
Delta: 0.01046931543687083 	  Loss: 1.6924333273267034 	 Accuracy: 0.2790091264667536
Delta: 0.009711099111322253 	  Loss: 1.6642817596958586 	 Accuracy: 0.2790091264667536
Delta: 0.008428534692225887 	  Loss: 1.645220610567639 	 Accuracy: 0.29465449804432853
Delta: 0.00782467207068978 	  Loss: 1.6316796062218801 	 Accuracy: 0.3089960886571056
Delta: 0.007627096201502036 	  Loss: 1.621774647126922 	 Accuracy: 0.3285528031290743
Delta: 0.007357945231563715 	  Loss: 1.6141895965982935 	 Accuracy: 0.32073011734028684
Delta: 0.007386982299300076 	  Loss: 1.6073499037041863 	 Accuracy: 0.3246414602346806
Delta: 0.007133736420812569 	  Loss: 1.6011906402508713 	 Accuracy: 0.32333767926988266
Delta: 0.0065416009385002765 	  Loss: 1.5961696617532224 	 Accuracy: 0.3246414602346806

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006050031947805585 	  Loss: 1.5922060734313477 	 Accuracy: 0.3324641460234681
Delta: 0.006070949871467009 	  Loss: 1.5891482906786734 	 Accuracy: 0.3285528031290743
Delta: 0.005783168605182654 	  Loss: 1.5860494727430563 	 Accuracy: 0.33116036505867014
Delta: 0.004885664945332391 	  Loss: 1.5842853776709658 	 Accuracy: 0.3324641460234681
Delta: 0.004273854627735392 	  Loss: 1.5820334464794796 	 Accuracy: 0.33376792698826596
Delta: 0.005039152842892664 	  Loss: 1.5806648521144955 	 Accuracy: 0.3272490221642764
Delta: 0.0038074081485778735 	  Loss: 1.5794116666325893 	 Accuracy: 0.32985658409387225
Delta: 0.004634034293673046 	  Loss: 1.5782349756498657 	 Accuracy: 0.3194263363754889
Delta: 0.005012811183096578 	  Loss: 1.576623121849266 	 Accuracy: 0.3272490221642764
Delta: 0.004481835144654743 	  Loss: 1.5753599348210132 	 Accuracy: 0.3272490221642764
Delta: 0.0029591022890027435 	  Loss: 1.575439040520712 	 Accuracy: 0.32333767926988266
Delta: 0.003739417797356675 	  Loss: 1.575000863642313 	 Accuracy: 0.3285528031290743
Delta: 0.003638625936812738 	  Loss: 1.574223725005803 	 Accuracy: 0.3272490221642764
Delta: 0.003489779990838061 	  Loss: 1.5739951676940787 	 Accuracy: 0.3259452411994785
Delta: 0.003630846924735616 	  Loss: 1.5734409645923693 	 Accuracy: 0.3246414602346806
Delta: 0.002569555479549451 	  Loss: 1.5730956129636797 	 Accuracy: 0.32985658409387225
Delta: 0.003669285703940059 	  Loss: 1.572262342959717 	 Accuracy: 0.3285528031290743
Delta: 0.002298258162452657 	  Loss: 1.571798544583721 	 Accuracy: 0.3285528031290743
Delta: 0.0017811950881243314 	  Loss: 1.5716747595036216 	 Accuracy: 0.3272490221642764
Delta: 0.0023986809279923907 	  Loss: 1.5715567945061082 	 Accuracy: 0.3259452411994785
Delta: 0.003007402500665703 	  Loss: 1.571093565827442 	 Accuracy: 0.3272490221642764
Delta: 0.0015623564386945087 	  Loss: 1.5711713956824147 	 Accuracy: 0.3259452411994785
Delta: 0.0013792027573706 	  Loss: 1.5711204679601858 	 Accuracy: 0.3259452411994785
Delta: 0.0026362718045100106 	  Loss: 1.5711299783142858 	 Accuracy: 0.3272490221642764
Delta: 0.0014043083989268709 	  Loss: 1.5710536353524511 	 Accuracy: 0.3272490221642764
Delta: 0.0014358746209901694 	  Loss: 1.571023572785744 	 Accuracy: 0.3272490221642764
Delta: 0.0005237266800045587 	  Loss: 1.570992034736935 	 Accuracy: 0.3272490221642764
Delta: 0.0007650965088231276 	  Loss: 1.5710114934873083 	 Accuracy: 0.3259452411994785
Delta: 0.0031935455320672205 	  Loss: 1.5709975985402655 	 Accuracy: 0.3259452411994785
Delta: 3.240060074409524e-05 	  Loss: 1.5709695491823692 	 Accuracy: 0.3259452411994785
Delta: 0.002003906720860138 	  Loss: 1.571009812137825 	 Accuracy: 0.3259452411994785
Delta: 0.0005232882791359323 	  Loss: 1.5709703892499047 	 Accuracy: 0.3259452411994785
Delta: 0.0018441171727245995 	  Loss: 1.570988397683254 	 Accuracy: 0.3259452411994785
Delta: 4.0426699273057565e-05 	  Loss: 1.570987344764316 	 Accuracy: 0.3259452411994785
Delta: 0.0011263063989404212 	  Loss: 1.570992387029451 	 Accuracy: 0.3259452411994785
Delta: 2.195394912911688e-05 	  Loss: 1.5709822949513559 	 Accuracy: 0.3259452411994785
Delta: 2.573221140939371e-05 	  Loss: 1.5710117392384617 	 Accuracy: 0.3259452411994785
Delta: 1.267067014651237e-05 	  Loss: 1.5710301999370229 	 Accuracy: 0.3259452411994785
Delta: 9.664136349716573e-06 	  Loss: 1.57103272332222 	 Accuracy: 0.3259452411994785
Delta: 0.0005187663064517296 	  Loss: 1.5710619671871542 	 Accuracy: 0.3259452411994785
Delta: 7.946843116804398e-06 	  Loss: 1.5710507648781218 	 Accuracy: 0.3259452411994785
Delta: 7.161285969551255e-06 	  Loss: 1.5710493431751973 	 Accuracy: 0.3259452411994785
Delta: 0.0005241055252793662 	  Loss: 1.5710567672948708 	 Accuracy: 0.3259452411994785
Delta: 7.643975804129976e-06 	  Loss: 1.5710687867142332 	 Accuracy: 0.3259452411994785
Delta: 9.466868965703744e-06 	  Loss: 1.5710821526133698 	 Accuracy: 0.3259452411994785
Delta: 1.1309053921101196e-05 	  Loss: 1.5710616051630404 	 Accuracy: 0.3259452411994785
Delta: 1.1523471441440333e-05 	  Loss: 1.5710496928866886 	 Accuracy: 0.3259452411994785
Delta: 1.339458775283163e-05 	  Loss: 1.5710732690130547 	 Accuracy: 0.3259452411994785
Delta: 2.791242928794973e-05 	  Loss: 1.5710836831805017 	 Accuracy: 0.3259452411994785
Delta: 1.5730319613595647e-05 	  Loss: 1.5710752902327294 	 Accuracy: 0.3259452411994785
Delta: 1.618641150133289e-05 	  Loss: 1.5710220177248888 	 Accuracy: 0.3259452411994785
Delta: 0.001050575183981006 	  Loss: 1.5710396703221887 	 Accuracy: 0.3259452411994785
Delta: 0.0017928606445532273 	  Loss: 1.5710140535191044 	 Accuracy: 0.3259452411994785
Delta: 0.0015256584303769743 	  Loss: 1.5709739294205132 	 Accuracy: 0.3259452411994785
Delta: 0.0016425932615031207 	  Loss: 1.5709249924005617 	 Accuracy: 0.3259452411994785
Delta: 0.00274787370438256 	  Loss: 1.5708734519213767 	 Accuracy: 0.3259452411994785
Delta: 0.0017295666672135339 	  Loss: 1.5709280303178277 	 Accuracy: 0.3259452411994785
Delta: 5.053453729069115e-05 	  Loss: 1.5709038934392257 	 Accuracy: 0.3272490221642764
Delta: 4.46445878139452e-05 	  Loss: 1.570875706006852 	 Accuracy: 0.3272490221642764
Delta: 0.001155885403504628 	  Loss: 1.570921618913867 	 Accuracy: 0.3259452411994785
Delta: 3.844629210697641e-05 	  Loss: 1.570888909266465 	 Accuracy: 0.3259452411994785
Delta: 0.0013027686092158942 	  Loss: 1.5709107271590357 	 Accuracy: 0.3272490221642764
Delta: 5.842250610841578e-06 	  Loss: 1.5709201234437071 	 Accuracy: 0.3272490221642764
Delta: 0.0005027268797879429 	  Loss: 1.5709196701453414 	 Accuracy: 0.3259452411994785
Delta: 5.939572105586538e-06 	  Loss: 1.5709200515107753 	 Accuracy: 0.3272490221642764
Delta: 5.980330216510031e-06 	  Loss: 1.5709213601206438 	 Accuracy: 0.3272490221642764
Delta: 0.0017327015644304977 	  Loss: 1.5710247814256724 	 Accuracy: 0.3272490221642764
Delta: 3.8077735206442535e-05 	  Loss: 1.5709261521293003 	 Accuracy: 0.3272490221642764
Delta: 0.0013293545995810773 	  Loss: 1.5709606043580444 	 Accuracy: 0.3272490221642764
Delta: 5.95735998965611e-05 	  Loss: 1.571013899630896 	 Accuracy: 0.3272490221642764
Delta: 1.9867480484391398e-05 	  Loss: 1.5710325502944773 	 Accuracy: 0.3259452411994785
Delta: 4.2979306598610286e-05 	  Loss: 1.5709913770150217 	 Accuracy: 0.3259452411994785
Delta: 0.0010470945695452846 	  Loss: 1.5708413112577153 	 Accuracy: 0.3259452411994785
Delta: 0.0005346370892457095 	  Loss: 1.570964330748525 	 Accuracy: 0.3259452411994785
Delta: 0.0022529055848434887 	  Loss: 1.5709368752876072 	 Accuracy: 0.32333767926988266
Delta: 0.0019388410604649286 	  Loss: 1.570911267398872 	 Accuracy: 0.3246414602346806
Delta: 0.0010677653542588606 	  Loss: 1.570903099445466 	 Accuracy: 0.3259452411994785
Delta: 0.001646094024129714 	  Loss: 1.5708262734967926 	 Accuracy: 0.3259452411994785
Delta: 0.0005316463447787365 	  Loss: 1.570933753304495 	 Accuracy: 0.3259452411994785
Delta: 4.7289436986995764e-05 	  Loss: 1.5709259301471188 	 Accuracy: 0.3272490221642764
Delta: 0.002359336283007887 	  Loss: 1.5708380960698816 	 Accuracy: 0.3259452411994785
Delta: 0.0016471099465051005 	  Loss: 1.570912924243145 	 Accuracy: 0.3259452411994785
Delta: 0.000551463199071734 	  Loss: 1.5708788390014754 	 Accuracy: 0.3259452411994785
Delta: 0.0013016278242304036 	  Loss: 1.5709675028660648 	 Accuracy: 0.3259452411994785
Delta: 2.87274046272093e-05 	  Loss: 1.5708953908616423 	 Accuracy: 0.3259452411994785
Delta: 0.020966372784845318 	  Loss: 2.175364125371676 	 Accuracy: 0.19426336375488917
Delta: 0.018663503165799674 	  Loss: 2.0953493746888263 	 Accuracy: 0.3820078226857888
Delta: 0.016423377114952484 	  Loss: 1.9709612256695275 	 Accuracy: 0.48370273794002605
Delta: 0.014961380683873753 	  Loss: 1.812252207596054 	 Accuracy: 0.49282920469361147
Delta: 0.012201753519276397 	  Loss: 1.6926212343849285 	 Accuracy: 0.4276401564537158
Delta: 0.010153416383006483 	  Loss: 1.6325935360346806 	 Accuracy: 0.4211212516297262
Delta: 0.00910932016525513 	  Loss: 1.6022265831128601 	 Accuracy: 0.4276401564537158
Delta: 0.008068375410920415 	  Loss: 1.5850187777997635 	 Accuracy: 0.4445893089960887
Delta: 0.007286628457862669 	  Loss: 1.5741625376489767 	 Accuracy: 0.4367666232073012
Delta: 0.006810908382015797 	  Loss: 1.566441040680412 	 Accuracy: 0.45632333767926986
Delta: 0.006399298803846188 	  Loss: 1.5605500149325218 	 Accuracy: 0.45241199478487615
Delta: 0.006285268763292316 	  Loss: 1.556638412080762 	 Accuracy: 0.45241199478487615
Delta: 0.005428948195164911 	  Loss: 1.5534036834528295 	 Accuracy: 0.45371577574967403

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.005222935273065382 	  Loss: 1.5511075824637612 	 Accuracy: 0.455019556714472
Delta: 0.0049339602967794875 	  Loss: 1.5492964679718826 	 Accuracy: 0.455019556714472
Delta: 0.004690941577689507 	  Loss: 1.5479462057180993 	 Accuracy: 0.455019556714472
Delta: 0.0035523704494374022 	  Loss: 1.5471587047939428 	 Accuracy: 0.45371577574967403
Delta: 0.004158179530076043 	  Loss: 1.546524651105973 	 Accuracy: 0.4498044328552803
Delta: 0.0040189787848254645 	  Loss: 1.546098438012552 	 Accuracy: 0.4576271186440678
Delta: 0.001198498187658292 	  Loss: 1.5458290576144915 	 Accuracy: 0.4576271186440678
Delta: 0.0033566139394341716 	  Loss: 1.545554735264577 	 Accuracy: 0.44589308996088656
Delta: 0.0019274238150285314 	  Loss: 1.545329414147865 	 Accuracy: 0.4471968709256845
Delta: 0.002834113508075957 	  Loss: 1.5452680987608762 	 Accuracy: 0.45241199478487615
Delta: 0.003026582875649148 	  Loss: 1.5451254009424433 	 Accuracy: 0.4498044328552803
Delta: 0.0029581259794634706 	  Loss: 1.5450822283600494 	 Accuracy: 0.4471968709256845
Delta: 0.003238923750406967 	  Loss: 1.545031437445995 	 Accuracy: 0.4498044328552803
Delta: 0.0005440086720010121 	  Loss: 1.5450006886236545 	 Accuracy: 0.4498044328552803
Delta: 0.0012955500641804321 	  Loss: 1.5449649415360498 	 Accuracy: 0.4498044328552803
Delta: 0.002012717069528144 	  Loss: 1.544944828621461 	 Accuracy: 0.4498044328552803
Delta: 0.0013132997329312242 	  Loss: 1.5449363128483755 	 Accuracy: 0.4498044328552803
Delta: 0.0008867867480635794 	  Loss: 1.5449688463860287 	 Accuracy: 0.45241199478487615
Delta: 0.0011509577748098402 	  Loss: 1.5449355049381968 	 Accuracy: 0.4498044328552803
Delta: 0.002064646864569648 	  Loss: 1.5449241034215049 	 Accuracy: 0.4498044328552803
Delta: 0.0014295313987055887 	  Loss: 1.544968051409951 	 Accuracy: 0.4498044328552803
Delta: 0.0022984175173983968 	  Loss: 1.544913606195982 	 Accuracy: 0.45241199478487615
Delta: 0.0027317067059522307 	  Loss: 1.544940817012933 	 Accuracy: 0.45241199478487615
Delta: 0.0020545121180025622 	  Loss: 1.5449201671050172 	 Accuracy: 0.45241199478487615
Delta: 0.0006647772866765503 	  Loss: 1.5450732735908508 	 Accuracy: 0.45241199478487615
Delta: 3.9102597464389336e-05 	  Loss: 1.5449537059105363 	 Accuracy: 0.45241199478487615
Delta: 0.0018712085878342358 	  Loss: 1.5449027271875453 	 Accuracy: 0.4511082138200782
Delta: 0.0024295964713112123 	  Loss: 1.5451415618679665 	 Accuracy: 0.4511082138200782
Delta: 0.0015808981499027565 	  Loss: 1.5448103950773833 	 Accuracy: 0.4511082138200782
Delta: 0.001737505957419243 	  Loss: 1.5449641279853128 	 Accuracy: 0.4511082138200782
Delta: 0.0017885196105542308 	  Loss: 1.5449401804324843 	 Accuracy: 0.4498044328552803
Delta: 0.0019550012931094846 	  Loss: 1.5448392173421859 	 Accuracy: 0.4498044328552803
Delta: 0.0006409473691763028 	  Loss: 1.5448841145671015 	 Accuracy: 0.4498044328552803
Delta: 0.0020979125455345637 	  Loss: 1.544926505299679 	 Accuracy: 0.4498044328552803
Delta: 0.0005376149176044176 	  Loss: 1.5449103353210518 	 Accuracy: 0.4498044328552803
Delta: 0.001188183455603959 	  Loss: 1.544896676104184 	 Accuracy: 0.4498044328552803
Delta: 2.2018650819149317e-05 	  Loss: 1.5448729805815617 	 Accuracy: 0.4498044328552803
Delta: 0.0009889181795703806 	  Loss: 1.5448554316664302 	 Accuracy: 0.4511082138200782
Delta: 0.0010335346447070922 	  Loss: 1.5447782199639468 	 Accuracy: 0.4511082138200782
Delta: 2.6938947765619612e-05 	  Loss: 1.5448360709411901 	 Accuracy: 0.4511082138200782
Delta: 0.001936639552707298 	  Loss: 1.5447767854512398 	 Accuracy: 0.4511082138200782
Delta: 0.0014754724568270133 	  Loss: 1.5447877256863585 	 Accuracy: 0.4511082138200782
Delta: 6.19457332876321e-05 	  Loss: 1.5449574848055736 	 Accuracy: 0.4498044328552803
Delta: 0.0007342774201076844 	  Loss: 1.5448990078081057 	 Accuracy: 0.4498044328552803
Delta: 0.0005084330456374471 	  Loss: 1.5448234560181366 	 Accuracy: 0.4498044328552803
Delta: 1.960948123028813e-05 	  Loss: 1.5448660842762612 	 Accuracy: 0.4498044328552803
Delta: 0.0006135699148019226 	  Loss: 1.544856657204959 	 Accuracy: 0.4498044328552803
Delta: 1.7414210581981157e-05 	  Loss: 1.5448879344644042 	 Accuracy: 0.4511082138200782
Delta: 0.0008098719709915652 	  Loss: 1.5449368661501954 	 Accuracy: 0.4511082138200782
Delta: 0.001123583000005444 	  Loss: 1.5449199781696552 	 Accuracy: 0.44589308996088656
Delta: 0.0031243024949570695 	  Loss: 1.545181772075698 	 Accuracy: 0.4511082138200782
Delta: 0.001103272037593792 	  Loss: 1.5450598975776195 	 Accuracy: 0.4511082138200782
Delta: 0.003110176079956044 	  Loss: 1.5450897305564573 	 Accuracy: 0.45241199478487615
Delta: 3.1024541667290394e-05 	  Loss: 1.5450486622554531 	 Accuracy: 0.4511082138200782
Delta: 0.0005591619554912342 	  Loss: 1.5449964361112625 	 Accuracy: 0.4498044328552803
Delta: 0.0005492648405486066 	  Loss: 1.5452250119122226 	 Accuracy: 0.4511082138200782
Delta: 4.068855200184876e-05 	  Loss: 1.5452604577476263 	 Accuracy: 0.4471968709256845
Delta: 0.0016743273971048561 	  Loss: 1.545328694183482 	 Accuracy: 0.4498044328552803
Delta: 0.0012862736422877847 	  Loss: 1.5453829911489407 	 Accuracy: 0.4511082138200782
Delta: 0.000674608130167946 	  Loss: 1.5449238770198925 	 Accuracy: 0.4511082138200782
Delta: 0.0008521505952065227 	  Loss: 1.5449583929564135 	 Accuracy: 0.4511082138200782
Delta: 0.0008418638871872022 	  Loss: 1.5449977467299767 	 Accuracy: 0.4498044328552803
Delta: 0.0018184273795109984 	  Loss: 1.5452740477070643 	 Accuracy: 0.4511082138200782
Delta: 6.0962474296287903e-05 	  Loss: 1.5452636601028484 	 Accuracy: 0.4511082138200782
Delta: 3.972873602939182e-05 	  Loss: 1.5453835251085781 	 Accuracy: 0.4511082138200782
Delta: 5.3204923350581705e-05 	  Loss: 1.5453540504220067 	 Accuracy: 0.45241199478487615
Delta: 6.758466171833145e-05 	  Loss: 1.545304179349479 	 Accuracy: 0.4511082138200782
Delta: 0.001752286521338917 	  Loss: 1.5452324921122416 	 Accuracy: 0.4511082138200782
Delta: 0.0017415356388460503 	  Loss: 1.5452307010667203 	 Accuracy: 0.4498044328552803
Delta: 0.001195434890039262 	  Loss: 1.5452075344545766 	 Accuracy: 0.4485006518904824
Delta: 0.0017310297551737354 	  Loss: 1.545103339752442 	 Accuracy: 0.4511082138200782
Delta: 0.0010230007262449021 	  Loss: 1.5452974372140216 	 Accuracy: 0.45241199478487615
Delta: 0.0017984736504678394 	  Loss: 1.5452477474195758 	 Accuracy: 0.45241199478487615
Delta: 0.0011565040010420274 	  Loss: 1.5451876140987881 	 Accuracy: 0.45371577574967403
Delta: 0.0010755524566179835 	  Loss: 1.5451661655880833 	 Accuracy: 0.4511082138200782
Delta: 0.0012251718048409484 	  Loss: 1.5452853777965025 	 Accuracy: 0.4498044328552803
Delta: 0.0009786185158923329 	  Loss: 1.545267086957404 	 Accuracy: 0.4471968709256845
Delta: 0.0029655021340929642 	  Loss: 1.5450456021944028 	 Accuracy: 0.4511082138200782
Delta: 0.004005125433831317 	  Loss: 1.5448471671406891 	 Accuracy: 0.4498044328552803
Delta: 0.002653040747969984 	  Loss: 1.545122279043078 	 Accuracy: 0.4511082138200782
Delta: 0.0017067589495480774 	  Loss: 1.545213074688628 	 Accuracy: 0.4498044328552803
Delta: 0.0025076916082016625 	  Loss: 1.5452316939751247 	 Accuracy: 0.4498044328552803
Delta: 0.002052385263363583 	  Loss: 1.5450283924039943 	 Accuracy: 0.4498044328552803
Delta: 0.0013791910066247204 	  Loss: 1.5453549640381805 	 Accuracy: 0.4511082138200782
Delta: 0.0018646844258884115 	  Loss: 1.5451444117804265 	 Accuracy: 0.4498044328552803
Delta: 0.0015368561637547587 	  Loss: 1.545001910599149 	 Accuracy: 0.4498044328552803
Delta: 0.0019313092678178605 	  Loss: 1.545048255929272 	 Accuracy: 0.4498044328552803
Delta: 0.020870439385068662 	  Loss: 2.1751153204880813 	 Accuracy: 0.20078226857887874
Delta: 0.01832650575000468 	  Loss: 2.0955638351285115 	 Accuracy: 0.32333767926988266
Delta: 0.016237356457258822 	  Loss: 1.9778955050446523 	 Accuracy: 0.39504563233376794
Delta: 0.015236821399860217 	  Loss: 1.8471361180156283 	 Accuracy: 0.39374185136897
Delta: 0.013680566609764846 	  Loss: 1.7489747958694821 	 Accuracy: 0.3350717079530639
Delta: 0.01191008331167198 	  Loss: 1.6924615711101807 	 Accuracy: 0.30638852672750977
Delta: 0.010922776788948128 	  Loss: 1.6568453585256562 	 Accuracy: 0.2920469361147327
Delta: 0.00953445913494746 	  Loss: 1.633808374683599 	 Accuracy: 0.2790091264667536
Delta: 0.008261350190305232 	  Loss: 1.619566854670092 	 Accuracy: 0.2842242503259452
Delta: 0.0077073025840977355 	  Loss: 1.6108640676179309 	 Accuracy: 0.28683181225554105
Delta: 0.0073491510088454 	  Loss: 1.605410246210776 	 Accuracy: 0.28683181225554105
Delta: 0.006051342596184906 	  Loss: 1.6014737057964656 	 Accuracy: 0.288135593220339

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00606336475677727 	  Loss: 1.5985894275543764 	 Accuracy: 0.2894393741851369
Delta: 0.0051756414009120994 	  Loss: 1.596827506968256 	 Accuracy: 0.2907431551499348
Delta: 0.005510245692005129 	  Loss: 1.5954059482200011 	 Accuracy: 0.29726205997392435
Delta: 0.005163575073241319 	  Loss: 1.594078965281403 	 Accuracy: 0.29726205997392435
Delta: 0.003119993374735543 	  Loss: 1.5934249808041843 	 Accuracy: 0.2985658409387223
Delta: 0.004338579227996615 	  Loss: 1.5929945457979198 	 Accuracy: 0.30247718383311606
Delta: 0.003172668925440948 	  Loss: 1.5928289652018919 	 Accuracy: 0.30247718383311606
Delta: 0.0038589204322733426 	  Loss: 1.5924732563018125 	 Accuracy: 0.30378096479791394
Delta: 0.003589622396184873 	  Loss: 1.5922410741842445 	 Accuracy: 0.30378096479791394
Delta: 0.0029358528812107147 	  Loss: 1.5921028118745761 	 Accuracy: 0.3050847457627119
Delta: 0.00483373383546203 	  Loss: 1.5918210353707887 	 Accuracy: 0.3116036505867014
Delta: 0.001235404169325846 	  Loss: 1.5917955965737929 	 Accuracy: 0.31029986962190353
Delta: 0.001850758015571888 	  Loss: 1.591738357437316 	 Accuracy: 0.3116036505867014
Delta: 0.0017830040127784148 	  Loss: 1.5916267431532742 	 Accuracy: 0.3116036505867014
Delta: 0.0006553199358490157 	  Loss: 1.5916480832812843 	 Accuracy: 0.3116036505867014
Delta: 0.0012448791364408033 	  Loss: 1.5916186276859072 	 Accuracy: 0.31029986962190353
Delta: 0.0017233939286789702 	  Loss: 1.5916464207908456 	 Accuracy: 0.3089960886571056
Delta: 0.001040435975822914 	  Loss: 1.591726232716906 	 Accuracy: 0.3050847457627119
Delta: 0.00198679748118657 	  Loss: 1.5918133279714193 	 Accuracy: 0.3089960886571056
Delta: 2.825263946314628e-05 	  Loss: 1.5917779672464558 	 Accuracy: 0.3089960886571056
Delta: 0.001646722097193768 	  Loss: 1.5917645979570219 	 Accuracy: 0.3089960886571056
Delta: 2.524141148379913e-05 	  Loss: 1.5916996537710377 	 Accuracy: 0.3089960886571056
Delta: 2.2651350026679283e-05 	  Loss: 1.5917067634034185 	 Accuracy: 0.31029986962190353
Delta: 0.0008013786330985679 	  Loss: 1.591706487876133 	 Accuracy: 0.3076923076923077
Delta: 0.0017865236013560595 	  Loss: 1.5917477544286007 	 Accuracy: 0.3089960886571056
Delta: 0.0007309724689863323 	  Loss: 1.591802933911064 	 Accuracy: 0.3089960886571056
Delta: 0.0010138305920416955 	  Loss: 1.591855670467757 	 Accuracy: 0.3076923076923077
Delta: 2.7377140236587847e-05 	  Loss: 1.5918422639313425 	 Accuracy: 0.3089960886571056
Delta: 0.000503034805400414 	  Loss: 1.5918552220335018 	 Accuracy: 0.3076923076923077
Delta: 0.0007305629120097528 	  Loss: 1.5918678361282372 	 Accuracy: 0.3076923076923077
Delta: 0.0011504331654254949 	  Loss: 1.5918273903096893 	 Accuracy: 0.3089960886571056
Delta: 0.000921761082469512 	  Loss: 1.591883312814243 	 Accuracy: 0.3076923076923077
Delta: 5.219388510216843e-05 	  Loss: 1.591774839888319 	 Accuracy: 0.3076923076923077
Delta: 0.000519062567288888 	  Loss: 1.5918358028032262 	 Accuracy: 0.3076923076923077
Delta: 2.9271171244868083e-05 	  Loss: 1.591848154875636 	 Accuracy: 0.3076923076923077
Delta: 4.1860473896855394e-05 	  Loss: 1.59187505631626 	 Accuracy: 0.3076923076923077
Delta: 0.000525564529888322 	  Loss: 1.5918854549207304 	 Accuracy: 0.31029986962190353
Delta: 0.0014903447691052686 	  Loss: 1.591793517265808 	 Accuracy: 0.3089960886571056
Delta: 0.0006254756775216525 	  Loss: 1.5917701743896497 	 Accuracy: 0.3089960886571056
Delta: 0.0005696292445159301 	  Loss: 1.5918021807605944 	 Accuracy: 0.3076923076923077
Delta: 2.940215015744544e-05 	  Loss: 1.59179754736742 	 Accuracy: 0.31029986962190353
Delta: 0.0008056633337728161 	  Loss: 1.591859661334521 	 Accuracy: 0.3076923076923077
Delta: 3.4724912721482705e-05 	  Loss: 1.5917986614844437 	 Accuracy: 0.3076923076923077
Delta: 0.0005104871622209456 	  Loss: 1.5917934830295088 	 Accuracy: 0.3076923076923077
Delta: 1.7360888126438562e-05 	  Loss: 1.5918130173018632 	 Accuracy: 0.31029986962190353
Delta: 0.0005367406068229315 	  Loss: 1.591835308404716 	 Accuracy: 0.3089960886571056
Delta: 4.0079146276494146e-05 	  Loss: 1.5917868332728287 	 Accuracy: 0.3089960886571056
Delta: 0.0005356947510465342 	  Loss: 1.5918388085155937 	 Accuracy: 0.3076923076923077
Delta: 0.001917536932640546 	  Loss: 1.5918775248498886 	 Accuracy: 0.3089960886571056
Delta: 0.0008870831373758971 	  Loss: 1.5918659480756943 	 Accuracy: 0.3076923076923077
Delta: 5.569138329683302e-05 	  Loss: 1.5917373211556485 	 Accuracy: 0.3089960886571056
Delta: 0.000532597208448407 	  Loss: 1.5917219506627573 	 Accuracy: 0.3076923076923077
Delta: 4.879316335668522e-05 	  Loss: 1.591679873818549 	 Accuracy: 0.3076923076923077
Delta: 5.450534131709966e-05 	  Loss: 1.5917615344081133 	 Accuracy: 0.3089960886571056
Delta: 0.0005190992740771215 	  Loss: 1.591803258390839 	 Accuracy: 0.3089960886571056
Delta: 3.631352761034046e-05 	  Loss: 1.591777644225401 	 Accuracy: 0.3089960886571056
Delta: 3.071397229216004e-05 	  Loss: 1.5918594939157913 	 Accuracy: 0.3089960886571056
Delta: 0.0018119233914995294 	  Loss: 1.5919378380135347 	 Accuracy: 0.3089960886571056
Delta: 0.0017158118442377969 	  Loss: 1.5918929405309101 	 Accuracy: 0.3089960886571056
Delta: 1.7456630696754984e-05 	  Loss: 1.5918544073965435 	 Accuracy: 0.31029986962190353
Delta: 0.0011383698527570446 	  Loss: 1.5919433237510168 	 Accuracy: 0.3089960886571056
Delta: 3.855140694549823e-05 	  Loss: 1.5919167073973393 	 Accuracy: 0.3089960886571056
Delta: 0.0024116089418377154 	  Loss: 1.5920169522093404 	 Accuracy: 0.31029986962190353
Delta: 3.5314934449841725e-05 	  Loss: 1.5919389049879036 	 Accuracy: 0.3089960886571056
Delta: 0.0005378323378059467 	  Loss: 1.5919998014310148 	 Accuracy: 0.3089960886571056
Delta: 0.0027254518853083677 	  Loss: 1.5920648897878034 	 Accuracy: 0.3089960886571056
Delta: 0.0018611345512564987 	  Loss: 1.592041331783641 	 Accuracy: 0.31029986962190353
Delta: 0.002303104354156285 	  Loss: 1.5919445065824935 	 Accuracy: 0.3089960886571056
Delta: 0.001722667077558939 	  Loss: 1.5918285699689743 	 Accuracy: 0.3076923076923077
Delta: 0.0034845875694023932 	  Loss: 1.5919516940638634 	 Accuracy: 0.3076923076923077
Delta: 0.003409489760194257 	  Loss: 1.5920646254478057 	 Accuracy: 0.3089960886571056
Delta: 0.0017358185486614274 	  Loss: 1.5918526288396326 	 Accuracy: 0.3076923076923077
Delta: 0.0005419244592989943 	  Loss: 1.5917665457159804 	 Accuracy: 0.3089960886571056
Delta: 6.488126073353482e-05 	  Loss: 1.5919599327813132 	 Accuracy: 0.3076923076923077
Delta: 0.0033389616489655385 	  Loss: 1.5919141069135807 	 Accuracy: 0.3089960886571056
Delta: 0.0012813947238553933 	  Loss: 1.591833685652253 	 Accuracy: 0.3076923076923077
Delta: 8.219122476233293e-05 	  Loss: 1.5919468827210181 	 Accuracy: 0.30378096479791394
Delta: 0.002550666287864789 	  Loss: 1.5916866717368778 	 Accuracy: 0.3076923076923077
Delta: 0.0006009391913838404 	  Loss: 1.5918672365343185 	 Accuracy: 0.3089960886571056
Delta: 0.00444218743195507 	  Loss: 1.5918941923874623 	 Accuracy: 0.3089960886571056
Delta: 0.0024526576925579338 	  Loss: 1.5920046915778792 	 Accuracy: 0.3076923076923077
Delta: 0.003587893300104257 	  Loss: 1.592304684189067 	 Accuracy: 0.3089960886571056
Delta: 0.0035504924975893015 	  Loss: 1.5921092765598757 	 Accuracy: 0.3089960886571056
Delta: 0.0012295069371650229 	  Loss: 1.5926185098121493 	 Accuracy: 0.3076923076923077
Delta: 0.0005732016799592861 	  Loss: 1.5924222536470138 	 Accuracy: 0.3089960886571056
Delta: 0.004737214170617984 	  Loss: 1.5929865713817897 	 Accuracy: 0.3076923076923077
Delta: 0.0021795778959394427 	  Loss: 1.5930592992490473 	 Accuracy: 0.30638852672750977
Delta: 0.004810930881702963 	  Loss: 1.5946996408815526 	 Accuracy: 0.3076923076923077
Delta: 0.020981841076424573 	  Loss: 2.1752753636934656 	 Accuracy: 0.18122555410691005
Delta: 0.018792870751519163 	  Loss: 2.090240378562499 	 Accuracy: 0.3194263363754889
Delta: 0.017065703635551092 	  Loss: 1.9463545954284496 	 Accuracy: 0.3728813559322034
Delta: 0.015207823395555728 	  Loss: 1.7871644120625647 	 Accuracy: 0.36897001303780963
Delta: 0.013005039862641038 	  Loss: 1.6873243507413649 	 Accuracy: 0.3455019556714472
Delta: 0.011254971683794815 	  Loss: 1.6362006265050335 	 Accuracy: 0.3663624511082138
Delta: 0.009221536273859826 	  Loss: 1.6133297716785 	 Accuracy: 0.379400260756193
Delta: 0.008471146803197506 	  Loss: 1.6012957259669371 	 Accuracy: 0.3833116036505867
Delta: 0.007081265139256088 	  Loss: 1.5942874893149837 	 Accuracy: 0.39504563233376794

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007029792049936546 	  Loss: 1.5897581916888894 	 Accuracy: 0.38852672750977835
Delta: 0.005994410535577607 	  Loss: 1.586682995320405 	 Accuracy: 0.39895697522816165
Delta: 0.005732741455417056 	  Loss: 1.584742289266062 	 Accuracy: 0.39895697522816165
Delta: 0.005059450862236634 	  Loss: 1.5832766389565132 	 Accuracy: 0.39895697522816165
Delta: 0.005148722791011452 	  Loss: 1.5827939987832949 	 Accuracy: 0.4015645371577575
Delta: 0.002957455013285744 	  Loss: 1.5826232312675625 	 Accuracy: 0.4015645371577575
Delta: 0.003587503615896644 	  Loss: 1.5827903008848 	 Accuracy: 0.4002607561929596
Delta: 0.0029341129054556727 	  Loss: 1.5826783730370548 	 Accuracy: 0.4015645371577575
Delta: 0.003403375122378995 	  Loss: 1.5824732278033833 	 Accuracy: 0.39895697522816165
Delta: 0.0006100214345440263 	  Loss: 1.5824828541668183 	 Accuracy: 0.4002607561929596
Delta: 0.0021413459577016678 	  Loss: 1.5824309241901833 	 Accuracy: 0.4002607561929596
Delta: 0.001208657893071272 	  Loss: 1.5825955538082157 	 Accuracy: 0.4015645371577575
Delta: 0.0028590128356501487 	  Loss: 1.582539619522283 	 Accuracy: 0.4002607561929596
Delta: 0.001203979245360514 	  Loss: 1.5825487896512693 	 Accuracy: 0.39895697522816165
Delta: 2.75653680035509e-05 	  Loss: 1.5825449731793437 	 Accuracy: 0.4002607561929596
Delta: 0.000893834011427103 	  Loss: 1.582497476660908 	 Accuracy: 0.4002607561929596
Delta: 0.002057451722044508 	  Loss: 1.5823940316976624 	 Accuracy: 0.4041720990873533
Delta: 0.0005364474367348754 	  Loss: 1.5823548555907756 	 Accuracy: 0.4041720990873533
Delta: 0.0005156983950894826 	  Loss: 1.582490981712494 	 Accuracy: 0.39895697522816165
Delta: 0.0020422800357022598 	  Loss: 1.582524611313203 	 Accuracy: 0.4002607561929596
Delta: 0.0005351758383344216 	  Loss: 1.5825654301614276 	 Accuracy: 0.4015645371577575
Delta: 4.083001785450033e-05 	  Loss: 1.5824420086734836 	 Accuracy: 0.4002607561929596
Delta: 0.0005298362322286587 	  Loss: 1.5824931856040192 	 Accuracy: 0.4002607561929596
Delta: 0.0010484056064594322 	  Loss: 1.5823346734157682 	 Accuracy: 0.4015645371577575
Delta: 0.0009129285272885431 	  Loss: 1.5823940445553797 	 Accuracy: 0.4015645371577575
Delta: 2.8776133083693998e-05 	  Loss: 1.5823019938502842 	 Accuracy: 0.4002607561929596
Delta: 7.91938117694388e-05 	  Loss: 1.5822473524060499 	 Accuracy: 0.4015645371577575
Delta: 0.001376278615108155 	  Loss: 1.5822235393460886 	 Accuracy: 0.4002607561929596
Delta: 0.0022308409420654265 	  Loss: 1.5821818799682448 	 Accuracy: 0.39895697522816165
Delta: 0.002583247409737334 	  Loss: 1.5821759924558054 	 Accuracy: 0.39895697522816165
Delta: 0.0020885026760397475 	  Loss: 1.582098442266112 	 Accuracy: 0.4028683181225554
Delta: 0.001691590214918217 	  Loss: 1.5821264943534643 	 Accuracy: 0.4002607561929596
Delta: 7.393416417160547e-05 	  Loss: 1.5820800013533658 	 Accuracy: 0.39895697522816165
Delta: 6.788028633287249e-05 	  Loss: 1.582054344971466 	 Accuracy: 0.4015645371577575
Delta: 0.0015821453914317523 	  Loss: 1.582170568515063 	 Accuracy: 0.39895697522816165
Delta: 0.001973650554444108 	  Loss: 1.582005434067769 	 Accuracy: 0.39895697522816165
Delta: 0.002352116876174738 	  Loss: 1.5819363055864712 	 Accuracy: 0.39895697522816165
Delta: 2.3085288016450872e-05 	  Loss: 1.5819862001791414 	 Accuracy: 0.39895697522816165
Delta: 0.001655291260191175 	  Loss: 1.5820408455002517 	 Accuracy: 0.39895697522816165
Delta: 0.0014096624893522177 	  Loss: 1.5822612349141711 	 Accuracy: 0.40547588005215124
Delta: 0.002961731611273168 	  Loss: 1.582030398737963 	 Accuracy: 0.39895697522816165
Delta: 0.00217589861758217 	  Loss: 1.5820485592962574 	 Accuracy: 0.39765319426336376
Delta: 0.0034781698016744336 	  Loss: 1.5821753258543179 	 Accuracy: 0.39765319426336376
Delta: 0.0022763444044093845 	  Loss: 1.5825968448413037 	 Accuracy: 0.39765319426336376
Delta: 0.0013822398396494317 	  Loss: 1.5821549579114729 	 Accuracy: 0.39504563233376794
Delta: 0.0005623620465582073 	  Loss: 1.5820856667060135 	 Accuracy: 0.4002607561929596
Delta: 0.0022172382289224898 	  Loss: 1.5822027667634648 	 Accuracy: 0.41199478487614083
Delta: 0.0027957513473401805 	  Loss: 1.5819236634175502 	 Accuracy: 0.39765319426336376
Delta: 0.0011311513344816292 	  Loss: 1.5817948736500038 	 Accuracy: 0.39765319426336376
Delta: 8.420589829310208e-05 	  Loss: 1.5821804661012968 	 Accuracy: 0.39895697522816165
Delta: 4.897982818647045e-05 	  Loss: 1.5819262033821384 	 Accuracy: 0.3963494132985658
Delta: 0.002552746918725994 	  Loss: 1.5821225995130002 	 Accuracy: 0.39895697522816165
Delta: 0.002632044961541179 	  Loss: 1.5823100326461894 	 Accuracy: 0.39895697522816165
Delta: 0.0007627305063639686 	  Loss: 1.5821608712327841 	 Accuracy: 0.39765319426336376
Delta: 0.0001229548034603833 	  Loss: 1.5825527175684746 	 Accuracy: 0.39504563233376794
Delta: 0.004051249222300018 	  Loss: 1.582274261934601 	 Accuracy: 0.3898305084745763
Delta: 0.0024643087764416143 	  Loss: 1.5818351236788404 	 Accuracy: 0.39765319426336376
Delta: 0.0030088660732613183 	  Loss: 1.5823184040464908 	 Accuracy: 0.39374185136897
Delta: 0.002768967749722878 	  Loss: 1.5819142429140296 	 Accuracy: 0.39504563233376794
Delta: 0.0019446780293568056 	  Loss: 1.5823838090290379 	 Accuracy: 0.39895697522816165
Delta: 0.0018316030333453107 	  Loss: 1.582217955631997 	 Accuracy: 0.3963494132985658
Delta: 0.0018190004378733516 	  Loss: 1.5823240021369207 	 Accuracy: 0.39765319426336376
Delta: 0.002615910780943809 	  Loss: 1.5823537901527822 	 Accuracy: 0.3963494132985658
Delta: 0.003526366460963677 	  Loss: 1.5820092067290035 	 Accuracy: 0.39504563233376794
Delta: 0.0015212820291963742 	  Loss: 1.582400683100849 	 Accuracy: 0.39504563233376794
Delta: 0.0005722690003377645 	  Loss: 1.5818809486114367 	 Accuracy: 0.3963494132985658
Delta: 0.000856550553659346 	  Loss: 1.5820545820436522 	 Accuracy: 0.3963494132985658
Delta: 0.0011279558017906126 	  Loss: 1.582052862228799 	 Accuracy: 0.3963494132985658
Delta: 0.001163203244262493 	  Loss: 1.5819428586631896 	 Accuracy: 0.3859191655801825
Delta: 0.0014766151904206058 	  Loss: 1.582108651413646 	 Accuracy: 0.39765319426336376
Delta: 0.0041635973934330585 	  Loss: 1.5814864920713547 	 Accuracy: 0.3924380704041721
Delta: 0.005050104807206163 	  Loss: 1.5813574825919905 	 Accuracy: 0.3963494132985658
Delta: 0.0009027536734398456 	  Loss: 1.5814656300290202 	 Accuracy: 0.3963494132985658
Delta: 0.0022243685055679543 	  Loss: 1.5815338905350307 	 Accuracy: 0.39765319426336376
Delta: 0.001987968914713254 	  Loss: 1.581881904244875 	 Accuracy: 0.3963494132985658
Delta: 0.0023060437962576542 	  Loss: 1.5815707859837722 	 Accuracy: 0.38722294654498046
Delta: 0.0014524036911970236 	  Loss: 1.5816062819800654 	 Accuracy: 0.39895697522816165
Delta: 0.002663687508749808 	  Loss: 1.5817244758137905 	 Accuracy: 0.39504563233376794
Delta: 0.0013798738544767506 	  Loss: 1.581811721879769 	 Accuracy: 0.39504563233376794
Delta: 0.0028757914286327312 	  Loss: 1.5818182229506133 	 Accuracy: 0.3963494132985658
Delta: 0.002374065227071772 	  Loss: 1.5814829601369609 	 Accuracy: 0.39504563233376794
Delta: 0.001505054297414723 	  Loss: 1.5817581882384242 	 Accuracy: 0.3963494132985658
Delta: 0.0009229417583781042 	  Loss: 1.581626419230637 	 Accuracy: 0.3963494132985658
Delta: 3.372550267178789e-05 	  Loss: 1.5816906129348656 	 Accuracy: 0.3963494132985658
Delta: 0.0009092302033906713 	  Loss: 1.5814827860365583 	 Accuracy: 0.39504563233376794
Delta: 0.002035006153785806 	  Loss: 1.5814091373971277 	 Accuracy: 0.3963494132985658
Delta: 0.0005601753496894309 	  Loss: 1.5813819639494309 	 Accuracy: 0.3963494132985658
Delta: 0.0020473004923655166 	  Loss: 1.5818935407207442 	 Accuracy: 0.3963494132985658
Delta: 0.00107094380548243 	  Loss: 1.5816771557730211 	 Accuracy: 0.4002607561929596
Delta: 0.0012339514600150597 	  Loss: 1.5817863554513478 	 Accuracy: 0.4028683181225554
Delta: 0.005362509929538439 	  Loss: 1.5833494956901346 	 Accuracy: 0.39504563233376794
Delta: 0.020888676392632317 	  Loss: 2.1745073353292685 	 Accuracy: 0.19035202086049544
Delta: 0.01848032119308707 	  Loss: 2.0851714334068916 	 Accuracy: 0.3428943937418514
Delta: 0.01636726013921634 	  Loss: 1.945026000720885 	 Accuracy: 0.36766623207301175
Delta: 0.015213528133938958 	  Loss: 1.7912012552725902 	 Accuracy: 0.3376792698826597
Delta: 0.013319936399140715 	  Loss: 1.6907037503995117 	 Accuracy: 0.33116036505867014
Delta: 0.01139140361996388 	  Loss: 1.6450838358732298 	 Accuracy: 0.3194263363754889
Delta: 0.009435175692801986 	  Loss: 1.6229102509734232 	 Accuracy: 0.32073011734028684
Delta: 0.008442210092477722 	  Loss: 1.610633063408962 	 Accuracy: 0.3428943937418514
Delta: 0.007417698234274666 	  Loss: 1.6030724735328448 	 Accuracy: 0.3494132985658409
Delta: 0.006759879449987775 	  Loss: 1.5991836361165086 	 Accuracy: 0.3494132985658409

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.006184730588692437 	  Loss: 1.5958910154649337 	 Accuracy: 0.35071707953063885
Delta: 0.005835801841331228 	  Loss: 1.593964191591487 	 Accuracy: 0.3428943937418514
Delta: 0.005312540673546709 	  Loss: 1.5928381282818742 	 Accuracy: 0.34419817470664926
Delta: 0.0046045504130010646 	  Loss: 1.592269046096413 	 Accuracy: 0.34810951760104303
Delta: 0.0033836006766214772 	  Loss: 1.5919797851011037 	 Accuracy: 0.3468057366362451
Delta: 0.003294241538912957 	  Loss: 1.591889570866147 	 Accuracy: 0.3428943937418514
Delta: 0.0032795564007712798 	  Loss: 1.5918324677906117 	 Accuracy: 0.3468057366362451
Delta: 0.0019383906405074556 	  Loss: 1.5918081256619008 	 Accuracy: 0.3468057366362451
Delta: 0.002192836143981171 	  Loss: 1.5918656332663632 	 Accuracy: 0.3455019556714472
Delta: 0.002190993593010937 	  Loss: 1.5917776885285244 	 Accuracy: 0.3455019556714472
Delta: 3.8054816672586116e-05 	  Loss: 1.5917626716903719 	 Accuracy: 0.3455019556714472
Delta: 2.031620575548045e-05 	  Loss: 1.5917433509442922 	 Accuracy: 0.3468057366362451
Delta: 1.6659662224081775e-05 	  Loss: 1.5917348364810977 	 Accuracy: 0.3428943937418514
Delta: 0.0010729731073119179 	  Loss: 1.591709756057513 	 Accuracy: 0.3455019556714472
Delta: 2.3640357232156183e-05 	  Loss: 1.5917308004788233 	 Accuracy: 0.3455019556714472
Delta: 0.0008330743420662291 	  Loss: 1.591644900943265 	 Accuracy: 0.3455019556714472
Delta: 0.0005600009952361539 	  Loss: 1.5917266023978478 	 Accuracy: 0.3455019556714472
Delta: 0.0005736370810285019 	  Loss: 1.5917474858221343 	 Accuracy: 0.3468057366362451
Delta: 2.841446155284208e-05 	  Loss: 1.5917635923077205 	 Accuracy: 0.3455019556714472
Delta: 2.9723569833991418e-05 	  Loss: 1.5917767247542107 	 Accuracy: 0.3455019556714472
Delta: 0.001234591980933028 	  Loss: 1.591663275913393 	 Accuracy: 0.3455019556714472
Delta: 2.6443795817428728e-05 	  Loss: 1.5917773356838354 	 Accuracy: 0.34419817470664926
Delta: 5.193465166540565e-05 	  Loss: 1.59170600325047 	 Accuracy: 0.3455019556714472
Delta: 7.818093711056643e-05 	  Loss: 1.5917641810697916 	 Accuracy: 0.3468057366362451
Delta: 6.91089357207274e-05 	  Loss: 1.5917460761459816 	 Accuracy: 0.3455019556714472
Delta: 4.394094889300088e-05 	  Loss: 1.5917962487243977 	 Accuracy: 0.3455019556714472
Delta: 2.7756594223372998e-05 	  Loss: 1.5917410954244822 	 Accuracy: 0.3455019556714472
Delta: 1.822263372058436e-05 	  Loss: 1.591731908266291 	 Accuracy: 0.3455019556714472
Delta: 2.0407204176127692e-05 	  Loss: 1.5917240831554764 	 Accuracy: 0.3455019556714472
Delta: 0.0009049857693466576 	  Loss: 1.5917316307614793 	 Accuracy: 0.34419817470664926
Delta: 0.002583808171569699 	  Loss: 1.5918458989506705 	 Accuracy: 0.3455019556714472
Delta: 6.865901432273532e-05 	  Loss: 1.5917260799016495 	 Accuracy: 0.3455019556714472
Delta: 0.0009182604247955984 	  Loss: 1.591898992916819 	 Accuracy: 0.3468057366362451
Delta: 8.777804658883956e-05 	  Loss: 1.5917295102993192 	 Accuracy: 0.3468057366362451
Delta: 0.0008605270428347044 	  Loss: 1.5919201679555763 	 Accuracy: 0.3455019556714472
Delta: 8.427464690332648e-05 	  Loss: 1.5916287610205526 	 Accuracy: 0.34419817470664926
Delta: 0.0019026997822656768 	  Loss: 1.5916417579310287 	 Accuracy: 0.35071707953063885
Delta: 0.0012275136839998537 	  Loss: 1.5917353067644107 	 Accuracy: 0.3455019556714472
Delta: 0.002593192769896072 	  Loss: 1.5915078157621099 	 Accuracy: 0.3468057366362451
Delta: 0.00189847879254398 	  Loss: 1.5916064767561826 	 Accuracy: 0.3455019556714472
Delta: 0.002519570878735247 	  Loss: 1.5919921666790664 	 Accuracy: 0.3455019556714472
Delta: 0.0025275707258252955 	  Loss: 1.591665869995542 	 Accuracy: 0.3455019556714472
Delta: 0.001383459746174467 	  Loss: 1.591791585159156 	 Accuracy: 0.3455019556714472
Delta: 0.0017058403495523661 	  Loss: 1.5918843224568215 	 Accuracy: 0.3455019556714472
Delta: 6.709930926368195e-05 	  Loss: 1.591724914150555 	 Accuracy: 0.3455019556714472
Delta: 0.0016925150064407083 	  Loss: 1.5916677630449616 	 Accuracy: 0.3455019556714472
Delta: 0.001111676245362551 	  Loss: 1.5921262095257174 	 Accuracy: 0.3455019556714472
Delta: 0.0017845301404665296 	  Loss: 1.5919547309532325 	 Accuracy: 0.3428943937418514
Delta: 0.0007809338176102503 	  Loss: 1.5920300348886114 	 Accuracy: 0.3455019556714472
Delta: 0.0009453203603060369 	  Loss: 1.5918053948289617 	 Accuracy: 0.3455019556714472
Delta: 0.0005497790635467062 	  Loss: 1.5918539952923023 	 Accuracy: 0.3468057366362451
Delta: 0.0005870137488179421 	  Loss: 1.5917395528825922 	 Accuracy: 0.3455019556714472
Delta: 0.0009669874473611746 	  Loss: 1.5916931181577976 	 Accuracy: 0.3468057366362451
Delta: 0.002764357710398784 	  Loss: 1.5918861335206864 	 Accuracy: 0.3428943937418514
Delta: 0.0007673788901097383 	  Loss: 1.5921493914302258 	 Accuracy: 0.3455019556714472
Delta: 0.002144051099399485 	  Loss: 1.5915748657750743 	 Accuracy: 0.34419817470664926
Delta: 0.0013637360201909526 	  Loss: 1.5916776551040752 	 Accuracy: 0.3455019556714472
Delta: 0.004222244090687044 	  Loss: 1.5914352491831796 	 Accuracy: 0.3455019556714472
Delta: 0.002457535643801242 	  Loss: 1.5917750270995283 	 Accuracy: 0.3428943937418514
Delta: 0.0022428630227803678 	  Loss: 1.5921421901503385 	 Accuracy: 0.3428943937418514
Delta: 0.002741226732546297 	  Loss: 1.592513466267052 	 Accuracy: 0.34419817470664926
Delta: 0.0023030872973245717 	  Loss: 1.5922843286006638 	 Accuracy: 0.34419817470664926
Delta: 0.0013068622721342652 	  Loss: 1.5922492630595144 	 Accuracy: 0.34419817470664926
Delta: 0.0015792130206323525 	  Loss: 1.5920366490498146 	 Accuracy: 0.34419817470664926
Delta: 0.0025537878482130147 	  Loss: 1.592377563977493 	 Accuracy: 0.3468057366362451
Delta: 0.0018238150994024115 	  Loss: 1.5918403956239624 	 Accuracy: 0.34419817470664926
Delta: 0.001348698905427588 	  Loss: 1.592306413243643 	 Accuracy: 0.34419817470664926
Delta: 0.0012865980720558484 	  Loss: 1.5923932876795872 	 Accuracy: 0.3428943937418514
Delta: 4.4128453098883406e-05 	  Loss: 1.5923105854696809 	 Accuracy: 0.34419817470664926
Delta: 0.0019150886708915052 	  Loss: 1.5922957057333271 	 Accuracy: 0.3428943937418514
Delta: 7.284822469907695e-05 	  Loss: 1.5926018696686741 	 Accuracy: 0.3468057366362451
Delta: 0.0029018174233842345 	  Loss: 1.5918873614200653 	 Accuracy: 0.3455019556714472
Delta: 0.004219469651049544 	  Loss: 1.5921175548921642 	 Accuracy: 0.3455019556714472
Delta: 2.436669177636121e-05 	  Loss: 1.5920983999038425 	 Accuracy: 0.3468057366362451
Delta: 0.004248775992382642 	  Loss: 1.5924765101674292 	 Accuracy: 0.34419817470664926
Delta: 0.0032179702673914797 	  Loss: 1.5927757009403245 	 Accuracy: 0.34419817470664926
Delta: 0.0022555680338649667 	  Loss: 1.5928070550892754 	 Accuracy: 0.34419817470664926
Delta: 0.0019109521561304094 	  Loss: 1.592876694504866 	 Accuracy: 0.3468057366362451
Delta: 0.002558240006151151 	  Loss: 1.5927975797673892 	 Accuracy: 0.34419817470664926
Delta: 0.0019664167982580893 	  Loss: 1.5929812694991679 	 Accuracy: 0.34419817470664926
Delta: 0.001548872888054701 	  Loss: 1.5928878400703625 	 Accuracy: 0.34810951760104303
Delta: 9.259300897542251e-05 	  Loss: 1.5931088017088508 	 Accuracy: 0.34419817470664926
Delta: 0.001846497108718454 	  Loss: 1.5930176949761412 	 Accuracy: 0.34419817470664926
Delta: 0.0020499884888025063 	  Loss: 1.5930177975318323 	 Accuracy: 0.3468057366362451
Delta: 0.002565243490310186 	  Loss: 1.5930999317778083 	 Accuracy: 0.34419817470664926
Delta: 0.0022571096777994504 	  Loss: 1.5925150343900982 	 Accuracy: 0.34419817470664926
Delta: 0.0021005138144965883 	  Loss: 1.592308123696496 	 Accuracy: 0.3455019556714472
Delta: 0.004042651834699362 	  Loss: 1.592290118641464 	 Accuracy: 0.3455019556714472
Delta: 0.003977843598892286 	  Loss: 1.5914644928024306 	 Accuracy: 0.3455019556714472
Delta: 0.0021714631916814604 	  Loss: 1.5919287913911724 	 Accuracy: 0.3468057366362451
Delta: 0.02099246415737416 	  Loss: 2.1743886954330174 	 Accuracy: 0.1773142112125163
Delta: 0.01856277573702499 	  Loss: 2.083542516481437 	 Accuracy: 0.30378096479791394
Delta: 0.017398615822918295 	  Loss: 1.9204657466204376 	 Accuracy: 0.3324641460234681
Delta: 0.015466575028432995 	  Loss: 1.7421889279762375 	 Accuracy: 0.3350717079530639
Delta: 0.013371201378420341 	  Loss: 1.6405619328458902 	 Accuracy: 0.3455019556714472
Delta: 0.010460418497805851 	  Loss: 1.597472814861631 	 Accuracy: 0.34419817470664926
Delta: 0.008554193003872314 	  Loss: 1.5810064987031471 	 Accuracy: 0.34028683181225555

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00691901251576613 	  Loss: 1.574552161310721 	 Accuracy: 0.3533246414602347
Delta: 0.005568793889413524 	  Loss: 1.5724058386441147 	 Accuracy: 0.3546284224250326
Delta: 0.005292445266723042 	  Loss: 1.5717414358563482 	 Accuracy: 0.3494132985658409
Delta: 0.004655544100721251 	  Loss: 1.571384461041521 	 Accuracy: 0.3520208604954368
Delta: 0.003436488435533714 	  Loss: 1.571575669784552 	 Accuracy: 0.35071707953063885
Delta: 0.004656058885339185 	  Loss: 1.5716800089251182 	 Accuracy: 0.3520208604954368
Delta: 0.00274079564456002 	  Loss: 1.5718124222783867 	 Accuracy: 0.3533246414602347
Delta: 0.002315224973611442 	  Loss: 1.5717909905585206 	 Accuracy: 0.3520208604954368
Delta: 8.132808517804874e-05 	  Loss: 1.5717392514639865 	 Accuracy: 0.35071707953063885
Delta: 0.0008445526065425539 	  Loss: 1.5717282512019926 	 Accuracy: 0.35071707953063885
Delta: 0.0016921588555386894 	  Loss: 1.571766222931915 	 Accuracy: 0.35071707953063885
Delta: 0.0024944553294873337 	  Loss: 1.571750253038123 	 Accuracy: 0.35071707953063885
Delta: 4.9948159939692014e-05 	  Loss: 1.5718825061330697 	 Accuracy: 0.3520208604954368
Delta: 0.0019390056728291498 	  Loss: 1.5717738486597086 	 Accuracy: 0.35071707953063885
Delta: 0.0011104089805083078 	  Loss: 1.571659061918174 	 Accuracy: 0.35071707953063885
Delta: 0.002058807848864787 	  Loss: 1.5719387714770638 	 Accuracy: 0.3520208604954368
Delta: 0.002520032871976436 	  Loss: 1.5717891455145547 	 Accuracy: 0.35071707953063885
Delta: 0.0009362267242039824 	  Loss: 1.5717448830754783 	 Accuracy: 0.3494132985658409
Delta: 0.002950442315573105 	  Loss: 1.5715593161724157 	 Accuracy: 0.35071707953063885
Delta: 0.0011107642739027342 	  Loss: 1.5718858714603778 	 Accuracy: 0.35071707953063885
Delta: 0.000979401654047943 	  Loss: 1.5718787412285284 	 Accuracy: 0.35071707953063885
Delta: 0.0008372354829247249 	  Loss: 1.5718641413192258 	 Accuracy: 0.35071707953063885
Delta: 0.0009679675967092506 	  Loss: 1.5716995901926563 	 Accuracy: 0.35071707953063885
Delta: 0.003080242404122677 	  Loss: 1.5719401459768354 	 Accuracy: 0.35071707953063885
Delta: 0.0018049978796709904 	  Loss: 1.571627549009447 	 Accuracy: 0.35071707953063885
Delta: 0.0006561490102810945 	  Loss: 1.5717768635490756 	 Accuracy: 0.35071707953063885
Delta: 0.001824781829544778 	  Loss: 1.5720649012380508 	 Accuracy: 0.3494132985658409
Delta: 0.0030227291350638187 	  Loss: 1.5721988621480576 	 Accuracy: 0.35071707953063885
Delta: 0.0013299708582544902 	  Loss: 1.5720525381342474 	 Accuracy: 0.35071707953063885
Delta: 7.246181757214514e-05 	  Loss: 1.5718037874852202 	 Accuracy: 0.35071707953063885
Delta: 7.533588571417751e-05 	  Loss: 1.5720430357912607 	 Accuracy: 0.35071707953063885
Delta: 0.0012267202179598192 	  Loss: 1.5719604504413742 	 Accuracy: 0.35071707953063885
Delta: 0.0019373756691716414 	  Loss: 1.571812884645623 	 Accuracy: 0.3546284224250326
Delta: 0.0014468647544578946 	  Loss: 1.5721436628911514 	 Accuracy: 0.35071707953063885
Delta: 0.0007745181157375015 	  Loss: 1.5718753832679888 	 Accuracy: 0.3520208604954368
Delta: 7.893078860213308e-05 	  Loss: 1.5715949412885206 	 Accuracy: 0.34028683181225555
Delta: 6.496736931711568e-05 	  Loss: 1.5718619652966046 	 Accuracy: 0.35071707953063885
Delta: 0.0021047241505061996 	  Loss: 1.5719035072262832 	 Accuracy: 0.35071707953063885
Delta: 0.0006817069561166102 	  Loss: 1.5719687523230004 	 Accuracy: 0.35071707953063885
Delta: 2.99774714844724e-05 	  Loss: 1.572050926951293 	 Accuracy: 0.35071707953063885
Delta: 0.0006003386988102915 	  Loss: 1.5719675457300393 	 Accuracy: 0.3520208604954368
Delta: 6.615370023574359e-05 	  Loss: 1.5720701005741988 	 Accuracy: 0.3363754889178618
Delta: 0.001745789262130813 	  Loss: 1.571777247168391 	 Accuracy: 0.35071707953063885
Delta: 3.239790228244619e-05 	  Loss: 1.571660004060278 	 Accuracy: 0.35071707953063885
Delta: 0.0033826434855734715 	  Loss: 1.571468810573882 	 Accuracy: 0.3350717079530639
Delta: 0.000545481903607098 	  Loss: 1.5714299424446234 	 Accuracy: 0.35071707953063885
Delta: 0.0021751893130223412 	  Loss: 1.5715852439030666 	 Accuracy: 0.35071707953063885
Delta: 0.0014083593118971154 	  Loss: 1.571402914715991 	 Accuracy: 0.35071707953063885
Delta: 6.329361533266784e-05 	  Loss: 1.5713931000254506 	 Accuracy: 0.3494132985658409
Delta: 6.627584466401709e-05 	  Loss: 1.5715046206640477 	 Accuracy: 0.35071707953063885
Delta: 0.001458944300943193 	  Loss: 1.5716670000283735 	 Accuracy: 0.35071707953063885
Delta: 0.00275777076035374 	  Loss: 1.572105958357683 	 Accuracy: 0.35071707953063885
Delta: 1.5902531739212118e-05 	  Loss: 1.5720842849294603 	 Accuracy: 0.37157757496740546
Delta: 0.00011004097154675633 	  Loss: 1.5720268014945387 	 Accuracy: 0.3520208604954368
Delta: 0.0016644404861235278 	  Loss: 1.5718169032341083 	 Accuracy: 0.3520208604954368
Delta: 0.0016478925126148492 	  Loss: 1.5721402427217832 	 Accuracy: 0.35071707953063885
Delta: 0.0013607328629596219 	  Loss: 1.571974490766939 	 Accuracy: 0.3520208604954368
Delta: 0.0013583365030319428 	  Loss: 1.5721331707378625 	 Accuracy: 0.3494132985658409
Delta: 0.003362572294397202 	  Loss: 1.5720311556630067 	 Accuracy: 0.3494132985658409
Delta: 0.002425305624590053 	  Loss: 1.5724659560410568 	 Accuracy: 0.3494132985658409
Delta: 0.0023660739642163394 	  Loss: 1.5726409970936217 	 Accuracy: 0.3494132985658409
Delta: 0.002608023222380359 	  Loss: 1.5726720415508195 	 Accuracy: 0.34810951760104303
Delta: 0.001187257754011454 	  Loss: 1.5727893895575127 	 Accuracy: 0.34810951760104303
Delta: 0.002713337827846503 	  Loss: 1.5730537007733774 	 Accuracy: 0.34810951760104303
Delta: 6.0121826976669546e-05 	  Loss: 1.573057941115456 	 Accuracy: 0.3494132985658409
Delta: 0.0005891098192400688 	  Loss: 1.572606027815989 	 Accuracy: 0.3494132985658409
Delta: 6.7432492646113546e-06 	  Loss: 1.5726385614153149 	 Accuracy: 0.3494132985658409
Delta: 0.0005010468032291618 	  Loss: 1.5726470190249953 	 Accuracy: 0.3494132985658409
Delta: 0.0048759360366439795 	  Loss: 1.5780568213319999 	 Accuracy: 0.3559322033898305
Delta: 0.0008759471241131163 	  Loss: 1.5774341963450134 	 Accuracy: 0.3468057366362451
Delta: 0.00492739877427946 	  Loss: 1.5732147024801137 	 Accuracy: 0.35071707953063885
Delta: 0.0033466543609252672 	  Loss: 1.573698154421943 	 Accuracy: 0.3494132985658409
Delta: 0.001870771750900391 	  Loss: 1.5732631829806492 	 Accuracy: 0.3494132985658409
Delta: 0.0025028175898865216 	  Loss: 1.5734108976045103 	 Accuracy: 0.3494132985658409
Delta: 4.634275346168608e-05 	  Loss: 1.5733382123068615 	 Accuracy: 0.3494132985658409
Delta: 0.00098582976710874 	  Loss: 1.573165153763136 	 Accuracy: 0.34810951760104303
Delta: 0.0015677029789821152 	  Loss: 1.5732226070138293 	 Accuracy: 0.35853976531942633
Delta: 0.001237488396287181 	  Loss: 1.5733605914879134 	 Accuracy: 0.35071707953063885
Delta: 3.9138775262794056e-05 	  Loss: 1.5733735254497336 	 Accuracy: 0.34810951760104303
Delta: 0.001257999472821456 	  Loss: 1.573444000296695 	 Accuracy: 0.3494132985658409
Delta: 0.0012457589178626802 	  Loss: 1.5733395999506739 	 Accuracy: 0.3494132985658409
Delta: 0.0033461799389516425 	  Loss: 1.5726182681922216 	 Accuracy: 0.34810951760104303
Delta: 0.003175200216653003 	  Loss: 1.573443618599352 	 Accuracy: 0.3494132985658409
Delta: 0.0021902457650850187 	  Loss: 1.5737555024307734 	 Accuracy: 0.34810951760104303
Delta: 0.0022739613504748034 	  Loss: 1.573426970147108 	 Accuracy: 0.3494132985658409
Delta: 0.004323034347404298 	  Loss: 1.5735603669160874 	 Accuracy: 0.3494132985658409
Delta: 0.002805712737154255 	  Loss: 1.5735479219096289 	 Accuracy: 0.3494132985658409
Delta: 0.0029273660162200603 	  Loss: 1.573467242414041 	 Accuracy: 0.3494132985658409
Delta: 0.0021905251437016335 	  Loss: 1.5731692807162008 	 Accuracy: 0.34419817470664926
Delta: 0.0005847644514937839 	  Loss: 1.5736147738758128 	 Accuracy: 0.3455019556714472
Delta: 0.003733849515316016 	  Loss: 1.573387821092139 	 Accuracy: 0.3468057366362451
Delta: 0.0025565932438245996 	  Loss: 1.5735506216829889 	 Accuracy: 0.363754889178618
Delta: 3.2670577742982873e-05 	  Loss: 1.5735364756100578 	 Accuracy: 0.3468057366362451
Delta: 0.020958647691590747 	  Loss: 2.1747697189038777 	 Accuracy: 0.1981747066492829
Delta: 0.018355736510490956 	  Loss: 2.0820964459236553 	 Accuracy: 0.34159061277705344
Delta: 0.016445524717494202 	  Loss: 1.9339144018778345 	 Accuracy: 0.4471968709256845
Delta: 0.015833421418984583 	  Loss: 1.787894491335757 	 Accuracy: 0.4498044328552803
Delta: 0.014721282522007191 	  Loss: 1.6874677979401354 	 Accuracy: 0.4511082138200782
Delta: 0.01235574738406084 	  Loss: 1.631396806546622 	 Accuracy: 0.4576271186440678
Delta: 0.009766115618296633 	  Loss: 1.6062616328307135 	 Accuracy: 0.46284224250325945
Delta: 0.007999946554370745 	  Loss: 1.5952062382650696 	 Accuracy: 0.47327249022164275

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007973600432860956 	  Loss: 1.5883855997874834 	 Accuracy: 0.4784876140808344
Delta: 0.006148413737317444 	  Loss: 1.5850488734201105 	 Accuracy: 0.4810951760104302
Delta: 0.005344524561973877 	  Loss: 1.5837555254394133 	 Accuracy: 0.4863102998696219
Delta: 0.004122031385831651 	  Loss: 1.5828876044580966 	 Accuracy: 0.48239895697522817
Delta: 0.003647602476435477 	  Loss: 1.5829374925731923 	 Accuracy: 0.4810951760104302
Delta: 0.002851643745240594 	  Loss: 1.5828618259725027 	 Accuracy: 0.48239895697522817
Delta: 0.0023494703527972938 	  Loss: 1.5831157864527214 	 Accuracy: 0.48239895697522817
Delta: 0.003627383288455543 	  Loss: 1.5830152304945244 	 Accuracy: 0.48239895697522817
Delta: 0.0028234082947309475 	  Loss: 1.5828324801627947 	 Accuracy: 0.48370273794002605
Delta: 0.0010759420485381716 	  Loss: 1.582727533791822 	 Accuracy: 0.48370273794002605
Delta: 0.0012948650499210591 	  Loss: 1.5826960764598614 	 Accuracy: 0.48239895697522817
Delta: 6.33542048760647e-05 	  Loss: 1.5829866838091284 	 Accuracy: 0.48370273794002605
Delta: 3.103558935866168e-05 	  Loss: 1.5828296379540423 	 Accuracy: 0.485006518904824
Delta: 0.0005102551186364782 	  Loss: 1.5828169814220607 	 Accuracy: 0.4863102998696219
Delta: 5.23590251418233e-05 	  Loss: 1.5827257917564843 	 Accuracy: 0.48239895697522817
Delta: 6.43877100707667e-05 	  Loss: 1.5829873824187128 	 Accuracy: 0.48370273794002605
Delta: 4.858564390246817e-05 	  Loss: 1.5828979103892675 	 Accuracy: 0.48370273794002605
Delta: 0.0027614989985148886 	  Loss: 1.5830237333966628 	 Accuracy: 0.48239895697522817
Delta: 0.0018451443456866513 	  Loss: 1.5832114497298668 	 Accuracy: 0.48239895697522817
Delta: 6.51241731322645e-05 	  Loss: 1.5832288237391587 	 Accuracy: 0.48370273794002605
Delta: 0.0022066767622355237 	  Loss: 1.5833140507403003 	 Accuracy: 0.48370273794002605
Delta: 0.0009726162210974745 	  Loss: 1.5833998052789156 	 Accuracy: 0.485006518904824
Delta: 0.0005620299942685935 	  Loss: 1.5832726729261086 	 Accuracy: 0.48239895697522817
Delta: 0.002592271745456436 	  Loss: 1.5831958477938843 	 Accuracy: 0.48239895697522817
Delta: 0.0008162092324246617 	  Loss: 1.5830287561797975 	 Accuracy: 0.48370273794002605
Delta: 0.0005525587650671393 	  Loss: 1.583150016173222 	 Accuracy: 0.48370273794002605
Delta: 0.00010506613803973937 	  Loss: 1.5828823182243221 	 Accuracy: 0.485006518904824
Delta: 0.0008249671133018855 	  Loss: 1.5830539307548093 	 Accuracy: 0.48370273794002605
Delta: 0.002109964313654041 	  Loss: 1.5829330394712402 	 Accuracy: 0.485006518904824
Delta: 0.001511300346465075 	  Loss: 1.5829567808315754 	 Accuracy: 0.48239895697522817
Delta: 0.0013975200892216032 	  Loss: 1.5831729770041365 	 Accuracy: 0.48370273794002605
Delta: 0.002472606609390224 	  Loss: 1.583253796392146 	 Accuracy: 0.48370273794002605
Delta: 0.0006921099117703918 	  Loss: 1.58320458422809 	 Accuracy: 0.48370273794002605
Delta: 0.000730097863820138 	  Loss: 1.583145281494633 	 Accuracy: 0.48370273794002605
Delta: 6.713866622915791e-05 	  Loss: 1.5830519236143288 	 Accuracy: 0.48370273794002605
Delta: 0.0008536671397706928 	  Loss: 1.583035982154169 	 Accuracy: 0.48370273794002605
Delta: 8.836488797471729e-05 	  Loss: 1.5832042362323342 	 Accuracy: 0.48370273794002605
Delta: 0.00015037187716040388 	  Loss: 1.583192215666408 	 Accuracy: 0.4784876140808344
Delta: 3.300405647522601e-05 	  Loss: 1.5832073140044187 	 Accuracy: 0.48370273794002605
Delta: 4.741156432668662e-05 	  Loss: 1.5830012458637046 	 Accuracy: 0.48370273794002605
Delta: 3.534548804151914e-05 	  Loss: 1.5831288044894842 	 Accuracy: 0.48370273794002605
Delta: 0.000520428733376701 	  Loss: 1.5831930044227114 	 Accuracy: 0.48370273794002605
Delta: 0.001225230433927549 	  Loss: 1.583290434136495 	 Accuracy: 0.48370273794002605
Delta: 0.002118173238797843 	  Loss: 1.583013894837125 	 Accuracy: 0.48370273794002605
Delta: 2.9265909657754435e-05 	  Loss: 1.5830027963423647 	 Accuracy: 0.48239895697522817
Delta: 0.0007484476204612081 	  Loss: 1.5829653392096725 	 Accuracy: 0.48370273794002605
Delta: 0.0013901518082801466 	  Loss: 1.5830642712044485 	 Accuracy: 0.485006518904824
Delta: 0.000619333534302125 	  Loss: 1.5832133817321996 	 Accuracy: 0.485006518904824
Delta: 0.0028712654079652137 	  Loss: 1.5831555281124534 	 Accuracy: 0.485006518904824
Delta: 0.0007673446272415412 	  Loss: 1.5832302807512892 	 Accuracy: 0.48370273794002605
Delta: 0.00010608107309373056 	  Loss: 1.583219433927504 	 Accuracy: 0.4810951760104302
Delta: 0.0023547431470412944 	  Loss: 1.5834051444966475 	 Accuracy: 0.48239895697522817
Delta: 0.0005548532778671217 	  Loss: 1.5831212659754432 	 Accuracy: 0.48370273794002605
Delta: 0.0012390232856976993 	  Loss: 1.582874399000667 	 Accuracy: 0.485006518904824
Delta: 0.0012883056339466896 	  Loss: 1.5828811727335075 	 Accuracy: 0.48370273794002605
Delta: 0.0008190535706727526 	  Loss: 1.583151917936106 	 Accuracy: 0.48370273794002605
Delta: 0.0026378185837469836 	  Loss: 1.5830575936996705 	 Accuracy: 0.48370273794002605
Delta: 0.003397393879413578 	  Loss: 1.58309834308151 	 Accuracy: 0.48370273794002605
Delta: 0.0006431567467433889 	  Loss: 1.5829721986674041 	 Accuracy: 0.48370273794002605
Delta: 0.0005334917326834865 	  Loss: 1.5830871845521997 	 Accuracy: 0.48370273794002605
Delta: 0.0014312558981803682 	  Loss: 1.5829468767845862 	 Accuracy: 0.485006518904824
Delta: 0.0010723178197154942 	  Loss: 1.582960006957609 	 Accuracy: 0.48239895697522817
Delta: 0.001892827174347745 	  Loss: 1.5827831931054346 	 Accuracy: 0.485006518904824
Delta: 0.0019402348469695302 	  Loss: 1.583091038059497 	 Accuracy: 0.48370273794002605
Delta: 0.0018890580978056315 	  Loss: 1.5832012239543398 	 Accuracy: 0.48370273794002605
Delta: 0.0016452560658227597 	  Loss: 1.5831009063288186 	 Accuracy: 0.48370273794002605
Delta: 1.2030298834049931e-05 	  Loss: 1.5830836347001656 	 Accuracy: 0.48370273794002605
Delta: 0.0017285713127741951 	  Loss: 1.5829157437850279 	 Accuracy: 0.48370273794002605
Delta: 0.0013444781098231231 	  Loss: 1.5831679075122287 	 Accuracy: 0.48370273794002605
Delta: 0.0005601576168845395 	  Loss: 1.582962631191978 	 Accuracy: 0.48239895697522817
Delta: 6.136037766612085e-05 	  Loss: 1.5831166677342565 	 Accuracy: 0.48370273794002605
Delta: 0.0010739757296705163 	  Loss: 1.5833399556487742 	 Accuracy: 0.4810951760104302
Delta: 6.587257206427308e-05 	  Loss: 1.5831333156524692 	 Accuracy: 0.48370273794002605
Delta: 0.0005426174316717259 	  Loss: 1.5832311757941906 	 Accuracy: 0.48370273794002605
Delta: 0.0015015551005647123 	  Loss: 1.5828566550440104 	 Accuracy: 0.48370273794002605
Delta: 0.000568554176638964 	  Loss: 1.5832856601953709 	 Accuracy: 0.48239895697522817
Delta: 0.0028830823422530743 	  Loss: 1.582788028335552 	 Accuracy: 0.48370273794002605
Delta: 0.0013853568617551884 	  Loss: 1.5832316341155324 	 Accuracy: 0.4706649282920469
Delta: 0.005510994945590153 	  Loss: 1.5841666216332957 	 Accuracy: 0.485006518904824
Delta: 0.004787916914211618 	  Loss: 1.5829359525410032 	 Accuracy: 0.4863102998696219
Delta: 0.0005556951925373255 	  Loss: 1.5829469849529856 	 Accuracy: 0.49022164276401564
Delta: 0.004152250887862453 	  Loss: 1.5827840875313786 	 Accuracy: 0.4863102998696219
Delta: 0.002823957059682697 	  Loss: 1.5827641734981805 	 Accuracy: 0.48370273794002605
Delta: 0.002617496970943136 	  Loss: 1.582960769204456 	 Accuracy: 0.4876140808344198
Delta: 0.001436520821178299 	  Loss: 1.5829539369096377 	 Accuracy: 0.4863102998696219
Delta: 0.0022164732793933583 	  Loss: 1.5829281334738403 	 Accuracy: 0.48891786179921776
Delta: 0.0025579009747212487 	  Loss: 1.5829314795784202 	 Accuracy: 0.48891786179921776
Delta: 0.002036483579376273 	  Loss: 1.5831388508135587 	 Accuracy: 0.48370273794002605
Delta: 0.001688581512924981 	  Loss: 1.5835039553187609 	 Accuracy: 0.485006518904824
Delta: 0.0017308397025974096 	  Loss: 1.582775042406087 	 Accuracy: 0.485006518904824
Delta: 0.0021237683386249625 	  Loss: 1.5833013475362459 	 Accuracy: 0.4863102998696219
Delta: 0.0025152842434517883 	  Loss: 1.583132803086825 	 Accuracy: 0.4876140808344198
Delta: 0.020949935867098757 	  Loss: 2.1748721251860688 	 Accuracy: 0.18904823989569752
Delta: 0.01861030220654186 	  Loss: 2.082416517427412 	 Accuracy: 0.31029986962190353
Delta: 0.01712844750055347 	  Loss: 1.9251137041893767 	 Accuracy: 0.41460234680573665
Delta: 0.015310056405742532 	  Loss: 1.7842520692780577 	 Accuracy: 0.4015645371577575
Delta: 0.013397233571177494 	  Loss: 1.7173305765826075 	 Accuracy: 0.423728813559322
Delta: 0.011670980862528777 	  Loss: 1.6877096815944945 	 Accuracy: 0.4406779661016949
Delta: 0.010593593158723593 	  Loss: 1.670389247210507 	 Accuracy: 0.46284224250325945

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008955199469324085 	  Loss: 1.6606316908631316 	 Accuracy: 0.4602346805736636
Delta: 0.007710956846146036 	  Loss: 1.6563615268962433 	 Accuracy: 0.4589308996088657
Delta: 0.006036145991250887 	  Loss: 1.6539137922808727 	 Accuracy: 0.455019556714472
Delta: 0.005003845889987207 	  Loss: 1.6522377597392346 	 Accuracy: 0.4498044328552803
Delta: 0.004167446375702729 	  Loss: 1.6513615543105744 	 Accuracy: 0.4445893089960887
Delta: 0.0038633477456611236 	  Loss: 1.6510356836683195 	 Accuracy: 0.44328552803129073
Delta: 0.004100828567613001 	  Loss: 1.651166457035734 	 Accuracy: 0.44589308996088656
Delta: 0.0032639349461952706 	  Loss: 1.6511310108770174 	 Accuracy: 0.4445893089960887
Delta: 0.002600100737460312 	  Loss: 1.6512349412365814 	 Accuracy: 0.4445893089960887
Delta: 0.0005283424571263027 	  Loss: 1.6512714812602125 	 Accuracy: 0.4445893089960887
Delta: 0.0022489653114648833 	  Loss: 1.6514465649804564 	 Accuracy: 0.44589308996088656
Delta: 0.002539291474404215 	  Loss: 1.6515774148038285 	 Accuracy: 0.44589308996088656
Delta: 0.0024791780969676993 	  Loss: 1.651494070674936 	 Accuracy: 0.44589308996088656
Delta: 0.0008153871301697477 	  Loss: 1.651587731346475 	 Accuracy: 0.44589308996088656
Delta: 3.0611035194647756e-05 	  Loss: 1.651505130676651 	 Accuracy: 0.44589308996088656
Delta: 0.003515111630796181 	  Loss: 1.6517061166803475 	 Accuracy: 0.4485006518904824
Delta: 0.001537576170676309 	  Loss: 1.6515589698730908 	 Accuracy: 0.44589308996088656
Delta: 0.0015258574519951907 	  Loss: 1.6516222159293161 	 Accuracy: 0.44589308996088656
Delta: 1.9099018242752023e-05 	  Loss: 1.651659873325222 	 Accuracy: 0.44589308996088656
Delta: 1.6504478609390716e-05 	  Loss: 1.6516418788000071 	 Accuracy: 0.44589308996088656
Delta: 0.0007901275519804637 	  Loss: 1.6516400865631051 	 Accuracy: 0.44589308996088656
Delta: 7.952416209917523e-06 	  Loss: 1.6516411252639138 	 Accuracy: 0.44589308996088656
Delta: 0.0005281501853532459 	  Loss: 1.6517872386803036 	 Accuracy: 0.4445893089960887
Delta: 4.2671253857825784e-05 	  Loss: 1.651608263375769 	 Accuracy: 0.44589308996088656
Delta: 1.3611970696325163e-05 	  Loss: 1.6516419268400941 	 Accuracy: 0.44589308996088656
Delta: 1.856733292582608e-05 	  Loss: 1.6517349731392703 	 Accuracy: 0.4471968709256845
Delta: 0.0014369761897004179 	  Loss: 1.6517760113175461 	 Accuracy: 0.44589308996088656
Delta: 4.3599294529199065e-05 	  Loss: 1.6516773658250314 	 Accuracy: 0.44589308996088656
Delta: 0.0029138342493904264 	  Loss: 1.6516545345117732 	 Accuracy: 0.4445893089960887
Delta: 9.216104396642252e-05 	  Loss: 1.6517478676609798 	 Accuracy: 0.44198174706649285
Delta: 0.0017221838297777924 	  Loss: 1.651477605223553 	 Accuracy: 0.44589308996088656
Delta: 6.545168282028936e-05 	  Loss: 1.6516571320873874 	 Accuracy: 0.4445893089960887
Delta: 0.0008925534483570508 	  Loss: 1.6514774549963631 	 Accuracy: 0.44589308996088656
Delta: 0.001151554311779541 	  Loss: 1.651455829371531 	 Accuracy: 0.44328552803129073
Delta: 0.0026978522271227184 	  Loss: 1.651830111055426 	 Accuracy: 0.4471968709256845
Delta: 7.30038720499052e-05 	  Loss: 1.651580968587491 	 Accuracy: 0.4471968709256845
Delta: 0.002067885573115558 	  Loss: 1.6517370266454376 	 Accuracy: 0.44589308996088656
Delta: 0.004202668711795389 	  Loss: 1.652202312033472 	 Accuracy: 0.4511082138200782
Delta: 0.002720901061513731 	  Loss: 1.6522428378431828 	 Accuracy: 0.4485006518904824
Delta: 0.005119291277862913 	  Loss: 1.6533144830355608 	 Accuracy: 0.45632333767926986
Delta: 0.0033889385323973573 	  Loss: 1.6537864112967835 	 Accuracy: 0.4498044328552803
Delta: 0.00214192562390099 	  Loss: 1.6539524386040974 	 Accuracy: 0.4485006518904824
Delta: 0.002965460257852328 	  Loss: 1.6546833624030273 	 Accuracy: 0.4485006518904824
Delta: 0.0013619314866518226 	  Loss: 1.654755965033954 	 Accuracy: 0.4485006518904824
Delta: 0.0026290620881443067 	  Loss: 1.6548517442195227 	 Accuracy: 0.4485006518904824
Delta: 0.004256037431436315 	  Loss: 1.6548388743794384 	 Accuracy: 0.4485006518904824
Delta: 0.002857883236091691 	  Loss: 1.6549170021969761 	 Accuracy: 0.4498044328552803
Delta: 0.003070065835308544 	  Loss: 1.6555928996306988 	 Accuracy: 0.4498044328552803
Delta: 0.0029606150159673466 	  Loss: 1.6549877849383683 	 Accuracy: 0.4511082138200782
Delta: 0.004132367355050315 	  Loss: 1.6556778655275677 	 Accuracy: 0.45371577574967403
Delta: 0.0022761222454642104 	  Loss: 1.6555571930211603 	 Accuracy: 0.4511082138200782
Delta: 0.004034189104929571 	  Loss: 1.6560479620950108 	 Accuracy: 0.4511082138200782
Delta: 0.003383092889428041 	  Loss: 1.6558561664070854 	 Accuracy: 0.4485006518904824
Delta: 0.0024605054442516446 	  Loss: 1.6556190932205086 	 Accuracy: 0.45241199478487615
Delta: 0.0030264876204142486 	  Loss: 1.6557798633792058 	 Accuracy: 0.4511082138200782
Delta: 0.001948792005607113 	  Loss: 1.6555884515043926 	 Accuracy: 0.45241199478487615
Delta: 0.001564864196232007 	  Loss: 1.655498967346568 	 Accuracy: 0.45241199478487615
Delta: 0.003902930163935443 	  Loss: 1.6560019551307448 	 Accuracy: 0.45371577574967403
Delta: 0.0015096311949335266 	  Loss: 1.655789522456753 	 Accuracy: 0.45371577574967403
Delta: 0.0005652047072224887 	  Loss: 1.655835994100582 	 Accuracy: 0.4498044328552803
Delta: 0.002956187164641534 	  Loss: 1.6562772946046889 	 Accuracy: 0.4511082138200782
Delta: 0.001494755537072244 	  Loss: 1.6563060031336172 	 Accuracy: 0.4471968709256845
Delta: 0.001773445995971093 	  Loss: 1.6564560043404963 	 Accuracy: 0.45241199478487615
Delta: 0.004602753597753566 	  Loss: 1.65658829167323 	 Accuracy: 0.45371577574967403
Delta: 0.0021330400820258814 	  Loss: 1.6563145700908213 	 Accuracy: 0.4485006518904824
Delta: 0.002883359052380062 	  Loss: 1.6566012883784804 	 Accuracy: 0.4511082138200782
Delta: 0.0026501512218786148 	  Loss: 1.6565621459804427 	 Accuracy: 0.4511082138200782
Delta: 0.0028390254485904797 	  Loss: 1.6563765034150038 	 Accuracy: 0.4471968709256845
Delta: 0.0011626029399320274 	  Loss: 1.6565238491547762 	 Accuracy: 0.4498044328552803
Delta: 0.0020324016988092046 	  Loss: 1.6563490751103003 	 Accuracy: 0.4511082138200782
Delta: 0.0010984181827820986 	  Loss: 1.656411838764075 	 Accuracy: 0.4511082138200782
Delta: 0.001307301690749892 	  Loss: 1.6561406944361194 	 Accuracy: 0.45241199478487615
Delta: 0.005414196951328962 	  Loss: 1.656266363418562 	 Accuracy: 0.4498044328552803
Delta: 0.004876158072152839 	  Loss: 1.65620407229942 	 Accuracy: 0.4511082138200782
Delta: 0.0025420539780434113 	  Loss: 1.6564945325384324 	 Accuracy: 0.4511082138200782
Delta: 0.004015806560153993 	  Loss: 1.6569014395115191 	 Accuracy: 0.4511082138200782
Delta: 0.002198920818412599 	  Loss: 1.656967976931096 	 Accuracy: 0.4511082138200782
Delta: 0.0036844409998080495 	  Loss: 1.656576928850471 	 Accuracy: 0.4511082138200782
Delta: 0.0024073300548721004 	  Loss: 1.656747652908631 	 Accuracy: 0.4511082138200782
Delta: 0.0025773781056764294 	  Loss: 1.6566236407717048 	 Accuracy: 0.45241199478487615
Delta: 0.0010559712921986153 	  Loss: 1.65642163546227 	 Accuracy: 0.45371577574967403
Delta: 0.0020543564387963424 	  Loss: 1.6563470154612168 	 Accuracy: 0.45371577574967403
Delta: 0.004375478588887506 	  Loss: 1.6565021142991025 	 Accuracy: 0.4667535853976532
Delta: 0.0008935610070992018 	  Loss: 1.656149122906774 	 Accuracy: 0.45371577574967403
Delta: 0.0017468670534987354 	  Loss: 1.6562957441082082 	 Accuracy: 0.455019556714472
Delta: 0.004415305805597142 	  Loss: 1.6557941965207537 	 Accuracy: 0.45371577574967403
Delta: 0.002467077043352092 	  Loss: 1.6563470719480984 	 Accuracy: 0.46153846153846156
Delta: 0.0027403631549676928 	  Loss: 1.6563533836338917 	 Accuracy: 0.455019556714472
Delta: 6.377295208018246e-05 	  Loss: 1.656459127978338 	 Accuracy: 0.455019556714472
Delta: 1.4555699307453643e-06 	  Loss: 1.6564620237410912 	 Accuracy: 0.45371577574967403
Delta: 0.0047954197196728 	  Loss: 1.6567815798325065 	 Accuracy: 0.46153846153846156
Delta: 0.0038175286349416745 	  Loss: 1.6562824961725564 	 Accuracy: 0.45371577574967403
Delta: 0.0010482424538364107 	  Loss: 1.6563872664621384 	 Accuracy: 0.45241199478487615
Delta: 0.020957506796875504 	  Loss: 2.1748391028312755 	 Accuracy: 0.196870925684485
Delta: 0.018731884531758128 	  Loss: 2.073857332154043 	 Accuracy: 0.2816166883963494
Delta: 0.017671319848950224 	  Loss: 1.897640175489257 	 Accuracy: 0.29595827900912647
Delta: 0.014967872797260919 	  Loss: 1.752628464854504 	 Accuracy: 0.2685788787483703
Delta: 0.01309757392770125 	  Loss: 1.6822376719135004 	 Accuracy: 0.2711864406779661
Delta: 0.010659897983970141 	  Loss: 1.6526915849836785 	 Accuracy: 0.2790091264667536
Delta: 0.008734270558195627 	  Loss: 1.642650910420446 	 Accuracy: 0.28552803129074317

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007240337217399688 	  Loss: 1.6386645180390622 	 Accuracy: 0.28292046936114734
Delta: 0.0053678141563344335 	  Loss: 1.63726258127303 	 Accuracy: 0.2816166883963494
Delta: 0.005106998024842214 	  Loss: 1.6364360545471883 	 Accuracy: 0.2842242503259452
Delta: 0.004601018877278039 	  Loss: 1.6361957579808846 	 Accuracy: 0.288135593220339
Delta: 0.002461674552631107 	  Loss: 1.6361551132474843 	 Accuracy: 0.288135593220339
Delta: 0.004503580863162219 	  Loss: 1.6361065927980734 	 Accuracy: 0.28552803129074317
Delta: 0.0008402737711568915 	  Loss: 1.6361424390376724 	 Accuracy: 0.28552803129074317
Delta: 0.0017760825762078143 	  Loss: 1.6362507586264414 	 Accuracy: 0.28552803129074317
Delta: 0.0022734612527418067 	  Loss: 1.6362781801944317 	 Accuracy: 0.2842242503259452
Delta: 0.00160602709873558 	  Loss: 1.636329691593555 	 Accuracy: 0.2842242503259452
Delta: 0.002524376894827517 	  Loss: 1.6363197720927825 	 Accuracy: 0.2842242503259452
Delta: 0.0016984845360313362 	  Loss: 1.6363075008798793 	 Accuracy: 0.2842242503259452
Delta: 0.0016329868822087244 	  Loss: 1.6364365541372408 	 Accuracy: 0.2842242503259452
Delta: 0.003436173816246332 	  Loss: 1.6361511478342647 	 Accuracy: 0.28552803129074317
Delta: 0.002313667213791271 	  Loss: 1.6362441847976612 	 Accuracy: 0.2842242503259452
Delta: 0.003159959124398247 	  Loss: 1.6363848451862246 	 Accuracy: 0.2842242503259452
Delta: 0.001425090853617461 	  Loss: 1.6363601969377548 	 Accuracy: 0.2816166883963494
Delta: 0.0028184577777452483 	  Loss: 1.6362658866055224 	 Accuracy: 0.2842242503259452
Delta: 0.0017385697663267739 	  Loss: 1.6361948343936743 	 Accuracy: 0.2842242503259452
Delta: 4.399633904941222e-05 	  Loss: 1.6361148948298156 	 Accuracy: 0.2842242503259452
Delta: 0.0013345112531232175 	  Loss: 1.63620146195789 	 Accuracy: 0.2842242503259452
Delta: 0.0016437097842468722 	  Loss: 1.6362559606355802 	 Accuracy: 0.28552803129074317
Delta: 0.002655717899520297 	  Loss: 1.6362419047955048 	 Accuracy: 0.28552803129074317
Delta: 0.0027688907833007103 	  Loss: 1.6362124731331467 	 Accuracy: 0.2842242503259452
Delta: 0.002982523824563701 	  Loss: 1.636195277709028 	 Accuracy: 0.2842242503259452
Delta: 3.643174676368666e-05 	  Loss: 1.636164143490855 	 Accuracy: 0.28552803129074317
Delta: 0.0028036749916079125 	  Loss: 1.6359517276541324 	 Accuracy: 0.2803129074315515
Delta: 0.002896920728524481 	  Loss: 1.6361017290735989 	 Accuracy: 0.2842242503259452
Delta: 0.001083048930767227 	  Loss: 1.6362315273511578 	 Accuracy: 0.2842242503259452
Delta: 0.0031675181495212975 	  Loss: 1.6359278977518836 	 Accuracy: 0.2842242503259452
Delta: 0.0006137481671677052 	  Loss: 1.635899963683964 	 Accuracy: 0.2842242503259452
Delta: 0.002176797966789729 	  Loss: 1.6358168012435161 	 Accuracy: 0.2842242503259452
Delta: 0.0012686969078241144 	  Loss: 1.6362043732873712 	 Accuracy: 0.2842242503259452
Delta: 0.0013710667840430828 	  Loss: 1.6357345321690575 	 Accuracy: 0.28683181225554105
Delta: 0.0035107705056262196 	  Loss: 1.6357776086480231 	 Accuracy: 0.28552803129074317
Delta: 0.0028392995870605044 	  Loss: 1.6355653222042348 	 Accuracy: 0.28292046936114734
Delta: 0.0032547609679248668 	  Loss: 1.6362314384135026 	 Accuracy: 0.28552803129074317
Delta: 0.0027471881545791644 	  Loss: 1.636283657431997 	 Accuracy: 0.28292046936114734
Delta: 0.003330545872696556 	  Loss: 1.6365443762562748 	 Accuracy: 0.2816166883963494
Delta: 0.003618102938746409 	  Loss: 1.6364923101695281 	 Accuracy: 0.2816166883963494
Delta: 0.002666739495769027 	  Loss: 1.6361069916887971 	 Accuracy: 0.2816166883963494
Delta: 0.0018734325445326015 	  Loss: 1.6366616025617085 	 Accuracy: 0.2816166883963494
Delta: 0.0021266324045220563 	  Loss: 1.6365038613011604 	 Accuracy: 0.2816166883963494
Delta: 0.0020577022324392083 	  Loss: 1.6363483029505288 	 Accuracy: 0.2816166883963494
Delta: 0.00233403009798601 	  Loss: 1.6365214612672943 	 Accuracy: 0.2816166883963494
Delta: 0.003442001426847441 	  Loss: 1.6365585869492856 	 Accuracy: 0.2816166883963494
Delta: 2.6408464272098046e-05 	  Loss: 1.6365452707308275 	 Accuracy: 0.2816166883963494
Delta: 0.002288316233990582 	  Loss: 1.6367724278539768 	 Accuracy: 0.2816166883963494
Delta: 0.0031275080955539707 	  Loss: 1.6369516441378549 	 Accuracy: 0.2816166883963494
Delta: 0.0026210313295755624 	  Loss: 1.637338501062433 	 Accuracy: 0.2816166883963494
Delta: 0.003006270367105988 	  Loss: 1.6374324809164489 	 Accuracy: 0.2816166883963494
Delta: 0.002720923062340471 	  Loss: 1.6370739474606397 	 Accuracy: 0.2816166883963494
Delta: 0.002276481470534418 	  Loss: 1.6373724090719177 	 Accuracy: 0.2816166883963494
Delta: 6.79495265718735e-05 	  Loss: 1.6370529344558498 	 Accuracy: 0.2816166883963494
Delta: 0.0026774317156838022 	  Loss: 1.637199138460412 	 Accuracy: 0.2816166883963494
Delta: 0.0013087116573665609 	  Loss: 1.637820502833725 	 Accuracy: 0.2790091264667536
Delta: 0.004375073149206705 	  Loss: 1.637821554800626 	 Accuracy: 0.2816166883963494
Delta: 0.002439006046106817 	  Loss: 1.6374525562103508 	 Accuracy: 0.2803129074315515
Delta: 0.00171898962589532 	  Loss: 1.637491702723389 	 Accuracy: 0.2816166883963494
Delta: 0.0030597057918300852 	  Loss: 1.6370550933559553 	 Accuracy: 0.2816166883963494
Delta: 0.0021727968025230335 	  Loss: 1.6374867941906976 	 Accuracy: 0.29986962190352023
Delta: 0.005620323414770307 	  Loss: 1.637032259708928 	 Accuracy: 0.28292046936114734
Delta: 0.005261037367273366 	  Loss: 1.636294755897963 	 Accuracy: 0.2816166883963494
Delta: 0.002684256280137062 	  Loss: 1.6365269837937213 	 Accuracy: 0.28292046936114734
Delta: 0.003685411593141076 	  Loss: 1.6379585943470718 	 Accuracy: 0.2842242503259452
Delta: 0.004814511832254239 	  Loss: 1.6378987213114218 	 Accuracy: 0.2737940026075619
Delta: 0.0038687074943848316 	  Loss: 1.638611097136393 	 Accuracy: 0.28292046936114734
Delta: 0.0028492413939237593 	  Loss: 1.6375453186525222 	 Accuracy: 0.2842242503259452
Delta: 0.0047091188497898505 	  Loss: 1.6373877611277827 	 Accuracy: 0.2842242503259452
Delta: 0.0023703959497674613 	  Loss: 1.6374081373408564 	 Accuracy: 0.2842242503259452
Delta: 0.005187266952817645 	  Loss: 1.6382201204859212 	 Accuracy: 0.28292046936114734
Delta: 0.003989842458931136 	  Loss: 1.6380458891183098 	 Accuracy: 0.28292046936114734
Delta: 0.0018560862694776054 	  Loss: 1.6379270001079893 	 Accuracy: 0.28292046936114734
Delta: 0.0022016595023075687 	  Loss: 1.6383702292246918 	 Accuracy: 0.28292046936114734
Delta: 0.0023742008893630766 	  Loss: 1.638439729006043 	 Accuracy: 0.28292046936114734
Delta: 0.000553654071248246 	  Loss: 1.6384023510863335 	 Accuracy: 0.28292046936114734
Delta: 0.0017092282835987594 	  Loss: 1.6384020002416606 	 Accuracy: 0.2842242503259452
Delta: 3.8193973922591234e-05 	  Loss: 1.638451946116678 	 Accuracy: 0.2842242503259452
Delta: 0.0015669669136798518 	  Loss: 1.63825096774761 	 Accuracy: 0.28292046936114734
Delta: 3.3316468628790386e-05 	  Loss: 1.6383003137868397 	 Accuracy: 0.2842242503259452
Delta: 0.001967026427339357 	  Loss: 1.6386913387139086 	 Accuracy: 0.2803129074315515
Delta: 0.0033324500357265596 	  Loss: 1.6391968179252956 	 Accuracy: 0.28292046936114734
Delta: 0.0023114538602056855 	  Loss: 1.6382257828099274 	 Accuracy: 0.28292046936114734
Delta: 3.437464593534472e-05 	  Loss: 1.6383179942982915 	 Accuracy: 0.28292046936114734
Delta: 0.00421847362888517 	  Loss: 1.6380029654564352 	 Accuracy: 0.28292046936114734
Delta: 0.003250653996331199 	  Loss: 1.638119528874209 	 Accuracy: 0.28292046936114734
Delta: 0.0014614469364191542 	  Loss: 1.6382043397297994 	 Accuracy: 0.28292046936114734
Delta: 0.0011929575219870828 	  Loss: 1.6382877494507806 	 Accuracy: 0.2816166883963494
Delta: 0.0016485124073862322 	  Loss: 1.638237703591105 	 Accuracy: 0.28292046936114734
Delta: 0.0023918979761248975 	  Loss: 1.6382708110192135 	 Accuracy: 0.28292046936114734
Delta: 0.0013960427124272605 	  Loss: 1.638166361895285 	 Accuracy: 0.2842242503259452
Delta: 4.978227282137221e-05 	  Loss: 1.6382578615071401 	 Accuracy: 0.28292046936114734
Delta: 0.0008362775836058769 	  Loss: 1.6382268146119838 	 Accuracy: 0.2842242503259452
Delta: 0.021020682721261848 	  Loss: 2.1743887452748787 	 Accuracy: 0.1864406779661017
Delta: 0.01869831110661953 	  Loss: 2.0753397386147623 	 Accuracy: 0.3833116036505867
Delta: 0.017350549655521047 	  Loss: 1.9039895839406824 	 Accuracy: 0.5827900912646675
Delta: 0.016260390929535608 	  Loss: 1.735740351873595 	 Accuracy: 0.576271186440678
Delta: 0.01321819444930198 	  Loss: 1.6462602559505266 	 Accuracy: 0.5528031290743155
Delta: 0.010437721296177161 	  Loss: 1.6214082131292473 	 Accuracy: 0.5449804432855281

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00882604917986876 	  Loss: 1.6134463689110137 	 Accuracy: 0.5410691003911343
Delta: 0.007450389193426414 	  Loss: 1.6096618873088282 	 Accuracy: 0.5488917861799217
Delta: 0.006466086973388564 	  Loss: 1.6076506829327206 	 Accuracy: 0.5449804432855281
Delta: 0.005564617864421857 	  Loss: 1.6064796557612357 	 Accuracy: 0.5410691003911343
Delta: 0.003858279907385907 	  Loss: 1.6060741577466944 	 Accuracy: 0.5475880052151239
Delta: 0.003035055992785901 	  Loss: 1.6060589012253554 	 Accuracy: 0.546284224250326
Delta: 0.0037317298781284224 	  Loss: 1.606028287092896 	 Accuracy: 0.5449804432855281
Delta: 0.0005531942714591294 	  Loss: 1.6058657597806378 	 Accuracy: 0.5449804432855281
Delta: 0.001656551395828068 	  Loss: 1.605838918507517 	 Accuracy: 0.5449804432855281
Delta: 0.0015350701773340968 	  Loss: 1.6061609856177055 	 Accuracy: 0.5488917861799217
Delta: 0.0031743679997177673 	  Loss: 1.6050740154457177 	 Accuracy: 0.546284224250326
Delta: 0.0010735903825130164 	  Loss: 1.6051992904606753 	 Accuracy: 0.546284224250326
Delta: 0.0038006045848231478 	  Loss: 1.6050536114361593 	 Accuracy: 0.546284224250326
Delta: 0.0011388294574108595 	  Loss: 1.6054688673374493 	 Accuracy: 0.546284224250326
Delta: 0.0029295526106252307 	  Loss: 1.6053505219953679 	 Accuracy: 0.546284224250326
Delta: 2.2828662251464116e-05 	  Loss: 1.6052528783264086 	 Accuracy: 0.546284224250326
Delta: 0.002447835907548595 	  Loss: 1.6049598849283089 	 Accuracy: 0.546284224250326
Delta: 3.8569648950582754e-05 	  Loss: 1.6047124667365615 	 Accuracy: 0.546284224250326
Delta: 0.002401877288896911 	  Loss: 1.6045420533550976 	 Accuracy: 0.530638852672751
Delta: 3.316831421943601e-05 	  Loss: 1.6045593831155327 	 Accuracy: 0.546284224250326
Delta: 0.0012907777576066598 	  Loss: 1.6044922560849737 	 Accuracy: 0.5449804432855281
Delta: 0.0016513601167667915 	  Loss: 1.6051158650846622 	 Accuracy: 0.546284224250326
Delta: 0.001814812547471299 	  Loss: 1.6044743909167154 	 Accuracy: 0.5449804432855281
Delta: 0.0032252969885197677 	  Loss: 1.6050798034010545 	 Accuracy: 0.546284224250326
Delta: 0.00453332144760761 	  Loss: 1.6058678659333174 	 Accuracy: 0.5436766623207301
Delta: 0.00445445000849887 	  Loss: 1.6047510313890037 	 Accuracy: 0.5449804432855281
Delta: 0.003984901418184428 	  Loss: 1.603356854084525 	 Accuracy: 0.5436766623207301
Delta: 0.000598033498907334 	  Loss: 1.6034808946898873 	 Accuracy: 0.5514993481095176
Delta: 0.005157238693451595 	  Loss: 1.6021021337975245 	 Accuracy: 0.5449804432855281
Delta: 0.002538702320744632 	  Loss: 1.6015656707465369 	 Accuracy: 0.5436766623207301
Delta: 0.0015729503193690117 	  Loss: 1.6015025535349654 	 Accuracy: 0.5475880052151239
Delta: 0.005750762155746619 	  Loss: 1.6017789383063956 	 Accuracy: 0.5475880052151239
Delta: 0.003495625879777288 	  Loss: 1.599830175441129 	 Accuracy: 0.5449804432855281
Delta: 0.0008576014003062698 	  Loss: 1.5994577337544154 	 Accuracy: 0.5501955671447197
Delta: 0.004688652986321589 	  Loss: 1.5999960489428036 	 Accuracy: 0.5514993481095176
Delta: 0.00557273423003114 	  Loss: 1.5994686278345727 	 Accuracy: 0.5528031290743155
Delta: 0.002562365849246443 	  Loss: 1.5986219506987722 	 Accuracy: 0.5475880052151239
Delta: 0.001401039923092794 	  Loss: 1.5986298272697637 	 Accuracy: 0.5514993481095176
Delta: 0.00509343678286412 	  Loss: 1.5989171103992155 	 Accuracy: 0.5488917861799217
Delta: 0.0028178310464314084 	  Loss: 1.5990150249390338 	 Accuracy: 0.5488917861799217
Delta: 0.0020120533565295123 	  Loss: 1.5990345792054086 	 Accuracy: 0.5488917861799217
Delta: 0.0032296628918379038 	  Loss: 1.5990850314850367 	 Accuracy: 0.5488917861799217
Delta: 0.0009352367592931352 	  Loss: 1.5989028822251852 	 Accuracy: 0.5501955671447197
Delta: 0.005341101048689172 	  Loss: 1.599487652944763 	 Accuracy: 0.5501955671447197
Delta: 0.0028095473913022865 	  Loss: 1.5995361980957603 	 Accuracy: 0.5488917861799217
Delta: 0.00402357613495422 	  Loss: 1.5974622345132028 	 Accuracy: 0.5514993481095176
Delta: 0.0012688566564358315 	  Loss: 1.5974759145620951 	 Accuracy: 0.5514993481095176
Delta: 0.0028806846075545866 	  Loss: 1.5976781967115747 	 Accuracy: 0.5501955671447197
Delta: 0.0018781240090569307 	  Loss: 1.5974864539436169 	 Accuracy: 0.5514993481095176
Delta: 0.0013226505888161225 	  Loss: 1.597498470044468 	 Accuracy: 0.5528031290743155
Delta: 0.0021332267539438117 	  Loss: 1.5973140149091858 	 Accuracy: 0.5528031290743155
Delta: 0.0018008725597328556 	  Loss: 1.5977625529600612 	 Accuracy: 0.5541069100391134
Delta: 0.003664139570731885 	  Loss: 1.5970274001026228 	 Accuracy: 0.5528031290743155
Delta: 0.0015847469583181086 	  Loss: 1.597366605684004 	 Accuracy: 0.5514993481095176
Delta: 0.002297254685856831 	  Loss: 1.5972122755501652 	 Accuracy: 0.5501955671447197
Delta: 0.004923694539404634 	  Loss: 1.5970547036590896 	 Accuracy: 0.5488917861799217
Delta: 0.0016098007732440757 	  Loss: 1.5970298724163847 	 Accuracy: 0.5488917861799217
Delta: 0.005192155990136105 	  Loss: 1.5981379787006433 	 Accuracy: 0.5514993481095176
Delta: 0.004798752538546759 	  Loss: 1.5981947208864506 	 Accuracy: 0.5410691003911343
Delta: 0.0013095443071605133 	  Loss: 1.5978942187413532 	 Accuracy: 0.5488917861799217
Delta: 0.0012762160034323435 	  Loss: 1.5978969111216235 	 Accuracy: 0.5475880052151239
Delta: 0.004416732882504097 	  Loss: 1.5965556058455423 	 Accuracy: 0.5475880052151239
Delta: 0.004344269876361132 	  Loss: 1.5962899424390329 	 Accuracy: 0.5475880052151239
Delta: 0.002348593513174394 	  Loss: 1.5962561295001487 	 Accuracy: 0.5514993481095176
Delta: 0.0038923572729657276 	  Loss: 1.5966023354143224 	 Accuracy: 0.5488917861799217
Delta: 0.002327526565012762 	  Loss: 1.5962172374579193 	 Accuracy: 0.5397653194263363
Delta: 0.00252263862935891 	  Loss: 1.5961557717161412 	 Accuracy: 0.5475880052151239
Delta: 0.0010239270342948998 	  Loss: 1.5961278856526067 	 Accuracy: 0.5345501955671447
Delta: 0.0034442928477292217 	  Loss: 1.5968520534575137 	 Accuracy: 0.5475880052151239
Delta: 0.00198071180736733 	  Loss: 1.5965281713598491 	 Accuracy: 0.5332464146023468
Delta: 0.0020023180874477755 	  Loss: 1.5971247401529332 	 Accuracy: 0.5475880052151239
Delta: 0.0037928665862140888 	  Loss: 1.5971186253369696 	 Accuracy: 0.5488917861799217
Delta: 0.0030096163726506995 	  Loss: 1.5968937490018353 	 Accuracy: 0.5384615384615384
Delta: 0.004020108332371203 	  Loss: 1.597116235446006 	 Accuracy: 0.5397653194263363
Delta: 0.0007663901505926014 	  Loss: 1.5971214968780294 	 Accuracy: 0.546284224250326
Delta: 0.002559315366560137 	  Loss: 1.5967654585980147 	 Accuracy: 0.5475880052151239
Delta: 0.0026880000078818743 	  Loss: 1.5969124118933187 	 Accuracy: 0.5436766623207301
Delta: 0.002625859952801318 	  Loss: 1.5969471464373894 	 Accuracy: 0.5449804432855281
Delta: 0.002066632552517447 	  Loss: 1.5970657433895492 	 Accuracy: 0.5436766623207301
Delta: 0.00433014510965482 	  Loss: 1.59750047405918 	 Accuracy: 0.5488917861799217
Delta: 0.0035016403753857033 	  Loss: 1.5979829486916397 	 Accuracy: 0.546284224250326
Delta: 0.0028584960425963764 	  Loss: 1.5976322786587651 	 Accuracy: 0.5475880052151239
Delta: 0.0025321925677680625 	  Loss: 1.597707905567372 	 Accuracy: 0.546284224250326
Delta: 5.4797610972535745e-05 	  Loss: 1.597659910937597 	 Accuracy: 0.546284224250326
Delta: 1.647481982716572e-05 	  Loss: 1.5977017313380197 	 Accuracy: 0.5449804432855281
Delta: 0.0005853328967866888 	  Loss: 1.5974988689883225 	 Accuracy: 0.5475880052151239
Delta: 0.002197908419835999 	  Loss: 1.5973810981918821 	 Accuracy: 0.5475880052151239
Delta: 0.000820592018140368 	  Loss: 1.597292146938622 	 Accuracy: 0.5541069100391134
Delta: 0.0011369669465761095 	  Loss: 1.5973023637419117 	 Accuracy: 0.5475880052151239
Delta: 9.408030964816291e-05 	  Loss: 1.597322447349248 	 Accuracy: 0.5475880052151239
Delta: 4.00279705337219e-07 	  Loss: 1.5973215292799658 	 Accuracy: 0.5449804432855281
Delta: 0.0028723689219401732 	  Loss: 1.596644885095606 	 Accuracy: 0.5501955671447197
Delta: 0.003888172198653447 	  Loss: 1.5966984660021604 	 Accuracy: 0.546284224250326
Delta: 0.0014825685995553417 	  Loss: 1.5967007992711593 	 Accuracy: 0.5449804432855281
Delta: 0.021031992417733455 	  Loss: 2.174216500914233 	 Accuracy: 0.2138200782268579
Delta: 0.018756882225195195 	  Loss: 2.0722906476249587 	 Accuracy: 0.32985658409387225
Delta: 0.018089020308159374 	  Loss: 1.875121813833725 	 Accuracy: 0.3754889178617992
Delta: 0.015321434628746085 	  Loss: 1.716402645097653 	 Accuracy: 0.4106910039113429
Delta: 0.01227008679148824 	  Loss: 1.6620996910343093 	 Accuracy: 0.41199478487614083
Delta: 0.010765571823931749 	  Loss: 1.6424802093859006 	 Accuracy: 0.4211212516297262
Delta: 0.009423219777392038 	  Loss: 1.6336265214506622 	 Accuracy: 0.42503259452411996

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.008006127829268083 	  Loss: 1.629441390061822 	 Accuracy: 0.42894393741851367
Delta: 0.005557477241716108 	  Loss: 1.6277784693886614 	 Accuracy: 0.4315514993481095
Delta: 0.0035241089177843947 	  Loss: 1.627402465666416 	 Accuracy: 0.43285528031290743
Delta: 0.004220295609715813 	  Loss: 1.6273691653460558 	 Accuracy: 0.43285528031290743
Delta: 0.003371208155575519 	  Loss: 1.6274862741402623 	 Accuracy: 0.43415906127770537
Delta: 0.000529076220992606 	  Loss: 1.6273831817322877 	 Accuracy: 0.43285528031290743
Delta: 0.0025328642963292304 	  Loss: 1.6274060453874237 	 Accuracy: 0.43285528031290743
Delta: 0.0010001346967829351 	  Loss: 1.6277125267503356 	 Accuracy: 0.43285528031290743
Delta: 0.0032620722542173832 	  Loss: 1.6279932323816089 	 Accuracy: 0.43285528031290743
Delta: 0.003854366029299057 	  Loss: 1.6279621615588902 	 Accuracy: 0.43415906127770537
Delta: 0.0016272791509238263 	  Loss: 1.628062823244428 	 Accuracy: 0.43415906127770537
Delta: 0.0009625339907906209 	  Loss: 1.6282156530030485 	 Accuracy: 0.43415906127770537
Delta: 5.717037152755745e-05 	  Loss: 1.6284000307345683 	 Accuracy: 0.439374185136897
Delta: 0.00248420130910448 	  Loss: 1.6283243827644518 	 Accuracy: 0.4380704041720991
Delta: 0.0026020482927683977 	  Loss: 1.6285384572588324 	 Accuracy: 0.43415906127770537
Delta: 0.0014653494909810196 	  Loss: 1.6285945474016463 	 Accuracy: 0.43415906127770537
Delta: 4.6102291846128454e-05 	  Loss: 1.6284694246897091 	 Accuracy: 0.43415906127770537
Delta: 0.0012572577425836082 	  Loss: 1.6282336663628778 	 Accuracy: 0.43415906127770537
Delta: 0.0027062603669383792 	  Loss: 1.628252787126213 	 Accuracy: 0.43415906127770537
Delta: 0.0013733707378910426 	  Loss: 1.6285387345689069 	 Accuracy: 0.4367666232073012
Delta: 1.6264490772410147e-05 	  Loss: 1.6285423919528488 	 Accuracy: 0.4315514993481095
Delta: 0.0006154729664065835 	  Loss: 1.6285690027495707 	 Accuracy: 0.4315514993481095
Delta: 0.0018362681720754295 	  Loss: 1.6285790345101945 	 Accuracy: 0.43415906127770537
Delta: 8.930548039034046e-05 	  Loss: 1.6285758393190957 	 Accuracy: 0.43415906127770537
Delta: 0.0005275714300020461 	  Loss: 1.628509311346943 	 Accuracy: 0.43415906127770537
Delta: 0.0014037399138763485 	  Loss: 1.6282076101867538 	 Accuracy: 0.43285528031290743
Delta: 0.0005763318884541973 	  Loss: 1.6284010997027094 	 Accuracy: 0.4315514993481095
Delta: 0.0026545102709724148 	  Loss: 1.6286617935156256 	 Accuracy: 0.4367666232073012
Delta: 0.0005388270973572937 	  Loss: 1.6283510026080903 	 Accuracy: 0.43546284224250326
Delta: 0.0013837466136362151 	  Loss: 1.6283979447664585 	 Accuracy: 0.42633637548891784
Delta: 0.0009393640826222245 	  Loss: 1.628449117035693 	 Accuracy: 0.43415906127770537
Delta: 6.854742963299448e-05 	  Loss: 1.628446318397306 	 Accuracy: 0.43415906127770537
Delta: 2.7207473343319614e-05 	  Loss: 1.6284326411195655 	 Accuracy: 0.42894393741851367
Delta: 0.0012876473623811497 	  Loss: 1.6283834351385122 	 Accuracy: 0.43546284224250326
Delta: 0.00010605604588054935 	  Loss: 1.6282903635632928 	 Accuracy: 0.43285528031290743
Delta: 5.850546999367093e-05 	  Loss: 1.6283472636794152 	 Accuracy: 0.43546284224250326
Delta: 5.238431301589032e-05 	  Loss: 1.6284424107547726 	 Accuracy: 0.4315514993481095
Delta: 7.313504127586527e-06 	  Loss: 1.6284325416620584 	 Accuracy: 0.43285528031290743
Delta: 0.0007793616822683545 	  Loss: 1.6282380217460817 	 Accuracy: 0.43285528031290743
Delta: 0.0008114561973108909 	  Loss: 1.6285168955076037 	 Accuracy: 0.4315514993481095
Delta: 0.002208208982741507 	  Loss: 1.6283417408982523 	 Accuracy: 0.43285528031290743
Delta: 0.0006152744420690919 	  Loss: 1.6280213401563577 	 Accuracy: 0.4315514993481095
Delta: 0.0027478986393144216 	  Loss: 1.6281252429431612 	 Accuracy: 0.43415906127770537
Delta: 0.0009101051500214927 	  Loss: 1.6275682559794764 	 Accuracy: 0.4380704041720991
Delta: 0.0012611754910958467 	  Loss: 1.6282688915369767 	 Accuracy: 0.439374185136897
Delta: 0.0018737215217836587 	  Loss: 1.6279061877330754 	 Accuracy: 0.42894393741851367
Delta: 0.0007732214909504637 	  Loss: 1.628209516931389 	 Accuracy: 0.439374185136897
Delta: 0.001976438947780844 	  Loss: 1.6280331008919675 	 Accuracy: 0.43415906127770537
Delta: 4.108404362658616e-05 	  Loss: 1.6280695669511442 	 Accuracy: 0.4276401564537158
Delta: 0.0026383129349240274 	  Loss: 1.6278291317825346 	 Accuracy: 0.4315514993481095
Delta: 0.0015635621431731763 	  Loss: 1.628383044556007 	 Accuracy: 0.43415906127770537
Delta: 0.0019474051498484283 	  Loss: 1.6282052830197453 	 Accuracy: 0.43546284224250326
Delta: 9.261809360238727e-05 	  Loss: 1.6283192219216172 	 Accuracy: 0.43285528031290743
Delta: 8.448349125324508e-05 	  Loss: 1.628219472817919 	 Accuracy: 0.43546284224250326
Delta: 0.0020782894863069874 	  Loss: 1.6280621800633095 	 Accuracy: 0.43546284224250326
Delta: 0.0017304058651793552 	  Loss: 1.628151477532983 	 Accuracy: 0.4315514993481095
Delta: 0.0013331454442866647 	  Loss: 1.62825955776791 	 Accuracy: 0.43415906127770537
Delta: 0.0018320426094422485 	  Loss: 1.6277021235843125 	 Accuracy: 0.4315514993481095
Delta: 0.001850683641367815 	  Loss: 1.6276362594901173 	 Accuracy: 0.43546284224250326
Delta: 0.0038173785095816427 	  Loss: 1.6272706690871317 	 Accuracy: 0.43546284224250326
Delta: 0.002720579717510286 	  Loss: 1.6275840732437876 	 Accuracy: 0.43546284224250326
Delta: 0.004051782672263101 	  Loss: 1.6271764580336887 	 Accuracy: 0.43546284224250326
Delta: 0.003918630370258059 	  Loss: 1.6273582984764539 	 Accuracy: 0.43546284224250326
Delta: 0.0009482240792978307 	  Loss: 1.627527629947973 	 Accuracy: 0.43415906127770537
Delta: 0.0029156314397850566 	  Loss: 1.627076952037434 	 Accuracy: 0.42503259452411996
Delta: 0.00408616570295877 	  Loss: 1.6269855613571278 	 Accuracy: 0.43285528031290743
Delta: 0.004462161980997273 	  Loss: 1.6262483681148443 	 Accuracy: 0.43285528031290743
Delta: 0.0036583814289975866 	  Loss: 1.626546773394919 	 Accuracy: 0.43285528031290743
Delta: 0.002045578470788336 	  Loss: 1.6262949524181836 	 Accuracy: 0.43546284224250326
Delta: 7.076564433101942e-06 	  Loss: 1.6262889334577895 	 Accuracy: 0.43546284224250326
Delta: 0.0034045224384049353 	  Loss: 1.6255419710239478 	 Accuracy: 0.4406779661016949
Delta: 0.002267899744068892 	  Loss: 1.6251565427173191 	 Accuracy: 0.439374185136897
Delta: 0.0022390399028016 	  Loss: 1.6252954092049112 	 Accuracy: 0.43285528031290743
Delta: 0.004134365768160958 	  Loss: 1.6256639143237206 	 Accuracy: 0.43546284224250326
Delta: 0.002780949765511539 	  Loss: 1.6256224928892262 	 Accuracy: 0.43546284224250326
Delta: 4.815768665060435e-05 	  Loss: 1.6257903562687606 	 Accuracy: 0.4302477183833116
Delta: 0.0038966559006955296 	  Loss: 1.626020882256455 	 Accuracy: 0.43546284224250326
Delta: 0.004658391886790803 	  Loss: 1.625631028752463 	 Accuracy: 0.4367666232073012
Delta: 0.0016105725042601178 	  Loss: 1.625516545763461 	 Accuracy: 0.43285528031290743
Delta: 0.004677033496880205 	  Loss: 1.624584877634214 	 Accuracy: 0.44198174706649285
Delta: 0.004096173652529516 	  Loss: 1.625646169633002 	 Accuracy: 0.43415906127770537
Delta: 0.003303510004931503 	  Loss: 1.6257110668765244 	 Accuracy: 0.4367666232073012
Delta: 0.0019626823238799713 	  Loss: 1.625644817535564 	 Accuracy: 0.43546284224250326
Delta: 0.0018940921367420977 	  Loss: 1.6256092822421984 	 Accuracy: 0.43546284224250326
Delta: 0.0006573184549538218 	  Loss: 1.625687575595372 	 Accuracy: 0.4367666232073012
Delta: 0.004490890037978798 	  Loss: 1.6244507811176385 	 Accuracy: 0.4380704041720991
Delta: 0.001783227084928873 	  Loss: 1.6242933026945003 	 Accuracy: 0.4367666232073012
Delta: 0.0008662843226730985 	  Loss: 1.624418156286037 	 Accuracy: 0.43415906127770537
Delta: 0.0017563508109193595 	  Loss: 1.6244635275727322 	 Accuracy: 0.43546284224250326
Delta: 7.382270835588048e-05 	  Loss: 1.6241507532830926 	 Accuracy: 0.4380704041720991
Delta: 0.004561543693972116 	  Loss: 1.6237425985834781 	 Accuracy: 0.43546284224250326
Delta: 0.005718890429227327 	  Loss: 1.6243104141196643 	 Accuracy: 0.4367666232073012
Delta: 0.0031134883682277102 	  Loss: 1.624042302619825 	 Accuracy: 0.43546284224250326
Delta: 0.020901673302886534 	  Loss: 2.1744971715535386 	 Accuracy: 0.1981747066492829
Delta: 0.018785153145931925 	  Loss: 2.0702319888043945 	 Accuracy: 0.36897001303780963
Delta: 0.01757412699111813 	  Loss: 1.8788696220358012 	 Accuracy: 0.5697522816166884
Delta: 0.01600625234422435 	  Loss: 1.6949338922065698 	 Accuracy: 0.560625814863103
Delta: 0.012509254847919687 	  Loss: 1.6339397800500524 	 Accuracy: 0.5423728813559322

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01103665646217234 	  Loss: 1.617589076010238 	 Accuracy: 0.5345501955671447
Delta: 0.009495967727318862 	  Loss: 1.6084131680286644 	 Accuracy: 0.529335071707953
Delta: 0.007087690110342398 	  Loss: 1.6043017483053361 	 Accuracy: 0.5345501955671447
Delta: 0.005523892898335963 	  Loss: 1.6039664930488486 	 Accuracy: 0.5345501955671447
Delta: 0.0039594754864033955 	  Loss: 1.6039448533636835 	 Accuracy: 0.5332464146023468
Delta: 0.004932891125936903 	  Loss: 1.6042131519691092 	 Accuracy: 0.5345501955671447
Delta: 0.0026993775086633113 	  Loss: 1.6040003484525758 	 Accuracy: 0.5345501955671447
Delta: 0.002006028941164797 	  Loss: 1.603969713664977 	 Accuracy: 0.5332464146023468
Delta: 0.0030676306351438937 	  Loss: 1.603806568360231 	 Accuracy: 0.5358539765319427
Delta: 0.0041032688025227654 	  Loss: 1.6040939523941269 	 Accuracy: 0.5358539765319427
Delta: 0.0030883019085763954 	  Loss: 1.6038418373561183 	 Accuracy: 0.5332464146023468
Delta: 0.0008391405305625201 	  Loss: 1.6037942595329224 	 Accuracy: 0.5345501955671447
Delta: 0.003878133504373103 	  Loss: 1.604198165626351 	 Accuracy: 0.5345501955671447
Delta: 0.0012993745706538962 	  Loss: 1.6041586337766263 	 Accuracy: 0.5345501955671447
Delta: 0.0011070536082363799 	  Loss: 1.6044442243284287 	 Accuracy: 0.5345501955671447
Delta: 0.0023469201970568146 	  Loss: 1.603800594775143 	 Accuracy: 0.5371577574967406
Delta: 0.0026216736788347017 	  Loss: 1.6045067980035321 	 Accuracy: 0.5332464146023468
Delta: 0.001837551271335928 	  Loss: 1.604201187597452 	 Accuracy: 0.529335071707953
Delta: 0.0006575307382664929 	  Loss: 1.6043647147227391 	 Accuracy: 0.5332464146023468
Delta: 0.003115794443889343 	  Loss: 1.6047419856619767 	 Accuracy: 0.5319426336375489
Delta: 0.0029224981861528934 	  Loss: 1.6043710822896253 	 Accuracy: 0.5319426336375489
Delta: 0.0022647638806695693 	  Loss: 1.6045556082652483 	 Accuracy: 0.5332464146023468
Delta: 0.0005377436037052574 	  Loss: 1.6044213210536484 	 Accuracy: 0.5332464146023468
Delta: 0.0020740939763523145 	  Loss: 1.603975316251738 	 Accuracy: 0.5345501955671447
Delta: 0.0024328868038169184 	  Loss: 1.6035553669070453 	 Accuracy: 0.530638852672751
Delta: 0.0022141786780265947 	  Loss: 1.6043399844068658 	 Accuracy: 0.5332464146023468
Delta: 0.00012727774657541458 	  Loss: 1.6042713835394533 	 Accuracy: 0.5332464146023468
Delta: 0.0022559295523914874 	  Loss: 1.604337458654014 	 Accuracy: 0.5332464146023468
Delta: 0.001389008904014628 	  Loss: 1.6044096077049148 	 Accuracy: 0.530638852672751
Delta: 0.0016958039038503802 	  Loss: 1.604290453973529 	 Accuracy: 0.5267275097783573
Delta: 0.0034721611248603144 	  Loss: 1.6042526386840836 	 Accuracy: 0.5267275097783573
Delta: 0.00486645555962535 	  Loss: 1.6050797441506042 	 Accuracy: 0.5319426336375489
Delta: 0.003093329780356595 	  Loss: 1.6042746508195278 	 Accuracy: 0.5280312907431551
Delta: 0.0008507848140659793 	  Loss: 1.6041024779988016 	 Accuracy: 0.5319426336375489
Delta: 0.000823851046349863 	  Loss: 1.6041222416101835 	 Accuracy: 0.5319426336375489
Delta: 0.002152238017857649 	  Loss: 1.604407619275685 	 Accuracy: 0.5332464146023468
Delta: 0.0012352325794503592 	  Loss: 1.6042664205351718 	 Accuracy: 0.5332464146023468
Delta: 0.002445073944366657 	  Loss: 1.6046011262292925 	 Accuracy: 0.5319426336375489
Delta: 0.0032561408299965904 	  Loss: 1.6040118659734528 	 Accuracy: 0.5332464146023468
Delta: 0.0022331926737272313 	  Loss: 1.6043487476582057 	 Accuracy: 0.5332464146023468
Delta: 0.002589576071946785 	  Loss: 1.604572916374241 	 Accuracy: 0.5345501955671447
Delta: 0.002733213100113485 	  Loss: 1.604385502159165 	 Accuracy: 0.5319426336375489
Delta: 0.002650782255955624 	  Loss: 1.6038697662974084 	 Accuracy: 0.5345501955671447
Delta: 0.0021283688654340086 	  Loss: 1.6042471104748464 	 Accuracy: 0.529335071707953
Delta: 0.003336399504409843 	  Loss: 1.6039714027798555 	 Accuracy: 0.5319426336375489
Delta: 0.0018101109868520816 	  Loss: 1.604344088153559 	 Accuracy: 0.5332464146023468
Delta: 0.0019042133676675278 	  Loss: 1.6038784808254305 	 Accuracy: 0.5319426336375489
Delta: 0.0038521776662029375 	  Loss: 1.6038166795042135 	 Accuracy: 0.5319426336375489
Delta: 0.0027272952517833717 	  Loss: 1.6041171283501923 	 Accuracy: 0.5319426336375489
Delta: 0.0006669425694662427 	  Loss: 1.603950191239922 	 Accuracy: 0.5319426336375489
Delta: 0.003727195175552644 	  Loss: 1.6038360227019228 	 Accuracy: 0.5345501955671447
Delta: 0.0034931523300766112 	  Loss: 1.6039390096145376 	 Accuracy: 0.5319426336375489
Delta: 0.004773674722948496 	  Loss: 1.6037905169257225 	 Accuracy: 0.5319426336375489
Delta: 0.004284137777314392 	  Loss: 1.6038888427982942 	 Accuracy: 0.530638852672751
Delta: 0.003548647711306686 	  Loss: 1.6039574480697334 	 Accuracy: 0.5280312907431551
Delta: 0.0015571116018327298 	  Loss: 1.6037499381940536 	 Accuracy: 0.529335071707953
Delta: 0.0033095349131258794 	  Loss: 1.6040910448471375 	 Accuracy: 0.5332464146023468
Delta: 0.004125100261168499 	  Loss: 1.6041611976291963 	 Accuracy: 0.530638852672751
Delta: 3.4981208449909524e-05 	  Loss: 1.6040966178882832 	 Accuracy: 0.529335071707953
Delta: 0.0021729815073489784 	  Loss: 1.6038002863951588 	 Accuracy: 0.5267275097783573
Delta: 0.002844179105652253 	  Loss: 1.6042839783414506 	 Accuracy: 0.530638852672751
Delta: 0.0009042030064699038 	  Loss: 1.60421205241422 	 Accuracy: 0.5254237288135594
Delta: 0.0011016519264705107 	  Loss: 1.6038957480887026 	 Accuracy: 0.5215123859191656
Delta: 0.0008133963316514233 	  Loss: 1.6044561078098556 	 Accuracy: 0.529335071707953
Delta: 0.00010665463482264482 	  Loss: 1.6040892351829712 	 Accuracy: 0.5319426336375489
Delta: 0.0017142118177699366 	  Loss: 1.6037665400534125 	 Accuracy: 0.5345501955671447
Delta: 0.0024893850052445043 	  Loss: 1.603406213165754 	 Accuracy: 0.529335071707953
Delta: 0.0017307042676995104 	  Loss: 1.6035585430872281 	 Accuracy: 0.5332464146023468
Delta: 0.004263817780374197 	  Loss: 1.6037459883159477 	 Accuracy: 0.529335071707953
Delta: 0.0030022725322196614 	  Loss: 1.6039084113023079 	 Accuracy: 0.529335071707953
Delta: 0.006227945025994905 	  Loss: 1.6029571043705122 	 Accuracy: 0.529335071707953
Delta: 0.004591670688833314 	  Loss: 1.6032353986634726 	 Accuracy: 0.5280312907431551
Delta: 0.0026349570971649174 	  Loss: 1.6030484733009935 	 Accuracy: 0.529335071707953
Delta: 0.0025707226552067744 	  Loss: 1.6031758760699375 	 Accuracy: 0.529335071707953
Delta: 0.0021177706462789823 	  Loss: 1.6035315216085397 	 Accuracy: 0.5358539765319427
Delta: 0.00460669600447075 	  Loss: 1.6032304938140656 	 Accuracy: 0.530638852672751
Delta: 0.0035612905056229016 	  Loss: 1.603419981613644 	 Accuracy: 0.529335071707953
Delta: 0.005616760379521225 	  Loss: 1.6026839083204942 	 Accuracy: 0.530638852672751
Delta: 0.0027889206756594996 	  Loss: 1.6024471222175287 	 Accuracy: 0.5345501955671447
Delta: 0.0007033416183358712 	  Loss: 1.6019976420770448 	 Accuracy: 0.530638852672751
Delta: 0.0036430992013529086 	  Loss: 1.6031733936636468 	 Accuracy: 0.530638852672751
Delta: 0.003442950310001753 	  Loss: 1.6033015685952754 	 Accuracy: 0.530638852672751
Delta: 0.001009447734845373 	  Loss: 1.6032075067953333 	 Accuracy: 0.530638852672751
Delta: 0.0023968770061986388 	  Loss: 1.6027217116598984 	 Accuracy: 0.530638852672751
Delta: 0.0038541603074419375 	  Loss: 1.6043701096544436 	 Accuracy: 0.5267275097783573
Delta: 0.00013541832792301795 	  Loss: 1.6039378647158806 	 Accuracy: 0.529335071707953
Delta: 9.138134876360576e-05 	  Loss: 1.6034849815897552 	 Accuracy: 0.5267275097783573
Delta: 0.00408187201896206 	  Loss: 1.6028070515344304 	 Accuracy: 0.529335071707953
Delta: 0.000517719734946475 	  Loss: 1.6027823725580002 	 Accuracy: 0.529335071707953
Delta: 8.206216006146356e-06 	  Loss: 1.602816507611022 	 Accuracy: 0.5319426336375489
Delta: 0.0016909897631692636 	  Loss: 1.6028771061218605 	 Accuracy: 0.5332464146023468
Delta: 0.0044859914765035275 	  Loss: 1.6033695332186888 	 Accuracy: 0.530638852672751
Delta: 0.004274081256446694 	  Loss: 1.6025242274184661 	 Accuracy: 0.5319426336375489
Delta: 0.0036241306979446566 	  Loss: 1.6029185435753595 	 Accuracy: 0.5319426336375489
Delta: 0.0029824402253074505 	  Loss: 1.6025224800379274 	 Accuracy: 0.530638852672751
Delta: 0.02100025281381421 	  Loss: 2.17507959462447 	 Accuracy: 0.19947848761408082
Delta: 0.018545803472742577 	  Loss: 2.072215343513415 	 Accuracy: 0.3363754889178618
Delta: 0.017134100776145737 	  Loss: 1.90091901014615 	 Accuracy: 0.4641460234680574
Delta: 0.015202853981343474 	  Loss: 1.7669200180144593 	 Accuracy: 0.48891786179921776
Delta: 0.013733173744277143 	  Loss: 1.7181470053194308 	 Accuracy: 0.4980443285528031
Delta: 0.011335889361031954 	  Loss: 1.7015346008989556 	 Accuracy: 0.4784876140808344

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.01038374268235858 	  Loss: 1.6934948863249426 	 Accuracy: 0.4758800521512386
Delta: 0.009341764704994265 	  Loss: 1.6897032195647372 	 Accuracy: 0.4745762711864407
Delta: 0.007605230480590175 	  Loss: 1.6873992681115624 	 Accuracy: 0.4758800521512386
Delta: 0.007258750677654557 	  Loss: 1.6868523989481115 	 Accuracy: 0.4706649282920469
Delta: 0.004842179334447106 	  Loss: 1.6864806713290974 	 Accuracy: 0.46936114732724904
Delta: 0.004239102068147751 	  Loss: 1.685754283927019 	 Accuracy: 0.4745762711864407
Delta: 0.0027128807061169826 	  Loss: 1.6856356623825715 	 Accuracy: 0.4745762711864407
Delta: 0.002240693856634103 	  Loss: 1.6858893085499855 	 Accuracy: 0.46936114732724904
Delta: 0.0041170307409161624 	  Loss: 1.6864545560801323 	 Accuracy: 0.46936114732724904
Delta: 0.0031158731695279207 	  Loss: 1.6865240350824982 	 Accuracy: 0.4745762711864407
Delta: 0.0017269559401561151 	  Loss: 1.686496599759319 	 Accuracy: 0.47196870925684486
Delta: 0.0023547540405594288 	  Loss: 1.6863140128558642 	 Accuracy: 0.47196870925684486
Delta: 7.358523284996326e-05 	  Loss: 1.686396635700286 	 Accuracy: 0.47979139504563234
Delta: 0.0025993121270044403 	  Loss: 1.6864911066251893 	 Accuracy: 0.4706649282920469
Delta: 0.00233396707736861 	  Loss: 1.6866746533102601 	 Accuracy: 0.47327249022164275
Delta: 0.002847238972518214 	  Loss: 1.6867265561796838 	 Accuracy: 0.47327249022164275
Delta: 0.001718625251080404 	  Loss: 1.6868322232257977 	 Accuracy: 0.47327249022164275
Delta: 6.836924563011775e-05 	  Loss: 1.6865733468253683 	 Accuracy: 0.47327249022164275
Delta: 6.231635512796267e-05 	  Loss: 1.6864049237587961 	 Accuracy: 0.47327249022164275
Delta: 0.0020583127871769153 	  Loss: 1.6865724236720951 	 Accuracy: 0.47196870925684486
Delta: 8.657010049282224e-05 	  Loss: 1.6863128419889772 	 Accuracy: 0.47196870925684486
Delta: 6.89631764422138e-05 	  Loss: 1.6863223977157742 	 Accuracy: 0.47327249022164275
Delta: 0.0005411552570102735 	  Loss: 1.6864399692589098 	 Accuracy: 0.4745762711864407
Delta: 0.002136484082985001 	  Loss: 1.6868222812333795 	 Accuracy: 0.47327249022164275
Delta: 0.0014057269480707436 	  Loss: 1.6863069335318916 	 Accuracy: 0.47327249022164275
Delta: 0.0021837254404900607 	  Loss: 1.6866044824260136 	 Accuracy: 0.47327249022164275
Delta: 0.0012637248526032208 	  Loss: 1.6863683587053884 	 Accuracy: 0.4706649282920469
Delta: 0.002094612237413007 	  Loss: 1.6862312416965213 	 Accuracy: 0.47327249022164275
Delta: 0.0018143746494317203 	  Loss: 1.686320375175673 	 Accuracy: 0.4771838331160365
Delta: 0.0009612143456281008 	  Loss: 1.6866184831729711 	 Accuracy: 0.4745762711864407
Delta: 0.0008523140303338923 	  Loss: 1.6864167869389437 	 Accuracy: 0.47196870925684486
Delta: 0.0010888321840919412 	  Loss: 1.6864150822015647 	 Accuracy: 0.4706649282920469
Delta: 0.00088515394452893 	  Loss: 1.686400440248395 	 Accuracy: 0.47327249022164275
Delta: 0.003474848442671003 	  Loss: 1.686529546657943 	 Accuracy: 0.4654498044328553
Delta: 0.0024363568096368686 	  Loss: 1.6864834246783182 	 Accuracy: 0.4745762711864407
Delta: 0.00233552440579796 	  Loss: 1.6868015538477614 	 Accuracy: 0.4667535853976532
Delta: 0.002966057811215228 	  Loss: 1.6859108177707798 	 Accuracy: 0.47979139504563234
Delta: 0.0057681650991822314 	  Loss: 1.684675635038623 	 Accuracy: 0.4758800521512386
Delta: 0.0019304819924459236 	  Loss: 1.6849617979510279 	 Accuracy: 0.4771838331160365
Delta: 0.002988229784309104 	  Loss: 1.6849982792049198 	 Accuracy: 0.4745762711864407
Delta: 0.0020851613763874484 	  Loss: 1.684942102642495 	 Accuracy: 0.4745762711864407
Delta: 0.0024447841721695154 	  Loss: 1.684348003404803 	 Accuracy: 0.47327249022164275
Delta: 0.002353671869662521 	  Loss: 1.683957521235403 	 Accuracy: 0.4745762711864407
Delta: 0.0007562370468189249 	  Loss: 1.6844562928879947 	 Accuracy: 0.4745762711864407
Delta: 0.0034834960451840193 	  Loss: 1.6853135438308708 	 Accuracy: 0.4706649282920469
Delta: 0.004653346264910852 	  Loss: 1.685281137381517 	 Accuracy: 0.47327249022164275
Delta: 0.0029501143428065126 	  Loss: 1.685577005510033 	 Accuracy: 0.4758800521512386
Delta: 0.004499669129756506 	  Loss: 1.6862522104551454 	 Accuracy: 0.4758800521512386
Delta: 0.003558041808752489 	  Loss: 1.685057749726298 	 Accuracy: 0.4771838331160365
Delta: 0.0050824726952404435 	  Loss: 1.6852368326833198 	 Accuracy: 0.4784876140808344
Delta: 0.006514263380051153 	  Loss: 1.685110031334561 	 Accuracy: 0.47327249022164275
Delta: 0.004367039503563869 	  Loss: 1.6861570012376075 	 Accuracy: 0.4745762711864407
Delta: 0.004206915768747857 	  Loss: 1.6866271093324166 	 Accuracy: 0.47327249022164275
Delta: 0.0027311282548690974 	  Loss: 1.6866374057610694 	 Accuracy: 0.47327249022164275
Delta: 0.003953356311418115 	  Loss: 1.6864932094179883 	 Accuracy: 0.4771838331160365
Delta: 0.0024008471136082923 	  Loss: 1.6866154115022467 	 Accuracy: 0.47327249022164275
Delta: 0.0027000429463901092 	  Loss: 1.6869216768803847 	 Accuracy: 0.47327249022164275
Delta: 0.0023567693508918437 	  Loss: 1.6870356765995647 	 Accuracy: 0.47196870925684486
Delta: 0.0011936533199455018 	  Loss: 1.6871486432888627 	 Accuracy: 0.47196870925684486
Delta: 0.0005065291398023575 	  Loss: 1.687174211630821 	 Accuracy: 0.47327249022164275
Delta: 0.0007573436532339736 	  Loss: 1.686823708954674 	 Accuracy: 0.47196870925684486
Delta: 0.0008176233067802568 	  Loss: 1.687020308900212 	 Accuracy: 0.4667535853976532
Delta: 0.0028162512076302234 	  Loss: 1.6873737198437835 	 Accuracy: 0.47196870925684486
Delta: 0.0029372127383827983 	  Loss: 1.6868815240349404 	 Accuracy: 0.47327249022164275
Delta: 0.0027307771490464312 	  Loss: 1.6869055256985674 	 Accuracy: 0.47327249022164275
Delta: 0.003166442423940949 	  Loss: 1.6870194295053578 	 Accuracy: 0.47196870925684486
Delta: 0.00423613365538183 	  Loss: 1.6878667134076206 	 Accuracy: 0.4706649282920469
Delta: 0.0029315772885785325 	  Loss: 1.6878492560349643 	 Accuracy: 0.47327249022164275
Delta: 0.004379467128825159 	  Loss: 1.6874098006384841 	 Accuracy: 0.4784876140808344
Delta: 0.0029120623236849655 	  Loss: 1.687759741689584 	 Accuracy: 0.4758800521512386
Delta: 0.0029781564002770195 	  Loss: 1.6873896938027027 	 Accuracy: 0.4758800521512386
Delta: 0.0027815994041779295 	  Loss: 1.687274600391588 	 Accuracy: 0.47979139504563234
Delta: 0.0024580062942996593 	  Loss: 1.6873342558918418 	 Accuracy: 0.47327249022164275
Delta: 0.002961666915804868 	  Loss: 1.687450961775427 	 Accuracy: 0.47196870925684486
Delta: 0.0032802124307119433 	  Loss: 1.6878876614945648 	 Accuracy: 0.4745762711864407
Delta: 0.003683043423776087 	  Loss: 1.6879751613489877 	 Accuracy: 0.4745762711864407
Delta: 0.004457632941613407 	  Loss: 1.6884166442390083 	 Accuracy: 0.4758800521512386
Delta: 0.004265078356287733 	  Loss: 1.6884837197544793 	 Accuracy: 0.4745762711864407
Delta: 0.003944272243771698 	  Loss: 1.6887507830285755 	 Accuracy: 0.4771838331160365
Delta: 0.004319182418893139 	  Loss: 1.6886403013704812 	 Accuracy: 0.47327249022164275
Delta: 0.0043088489180744365 	  Loss: 1.6885744370209697 	 Accuracy: 0.4745762711864407
Delta: 0.002631041365308007 	  Loss: 1.6886947140188333 	 Accuracy: 0.4758800521512386
Delta: 0.0029967958114492624 	  Loss: 1.6884058441204117 	 Accuracy: 0.4745762711864407
Delta: 0.0049359853217975725 	  Loss: 1.688728126472821 	 Accuracy: 0.47327249022164275
Delta: 0.001303729915652143 	  Loss: 1.6889556677720736 	 Accuracy: 0.4745762711864407
Delta: 0.0047015460421804154 	  Loss: 1.6890964082001578 	 Accuracy: 0.4758800521512386
Delta: 0.0033611207100751055 	  Loss: 1.689773298558883 	 Accuracy: 0.4758800521512386
Delta: 0.0033908736661619914 	  Loss: 1.6892081811023 	 Accuracy: 0.4771838331160365
Delta: 0.00499141620391309 	  Loss: 1.6897322630398834 	 Accuracy: 0.47196870925684486
Delta: 0.00426511618299845 	  Loss: 1.6904246869891248 	 Accuracy: 0.4784876140808344
Delta: 0.004369141336109312 	  Loss: 1.6899291702810109 	 Accuracy: 0.48239895697522817
Delta: 0.004924573245385604 	  Loss: 1.6896533390983888 	 Accuracy: 0.4771838331160365
Delta: 0.0010742086538748415 	  Loss: 1.68962912496204 	 Accuracy: 0.4758800521512386
Delta: 0.005391137855740747 	  Loss: 1.6887806811801167 	 Accuracy: 0.4771838331160365
Delta: 0.020951098853233305 	  Loss: 2.174754317401641 	 Accuracy: 0.19556714471968709
Delta: 0.01884936679597143 	  Loss: 2.069312806038746 	 Accuracy: 0.35071707953063885
Delta: 0.018164880816895393 	  Loss: 1.8691338595505003 	 Accuracy: 0.5423728813559322
Delta: 0.016528229334041952 	  Loss: 1.6830921670533256 	 Accuracy: 0.5814863102998696
Delta: 0.01256857423496145 	  Loss: 1.6305062722296317 	 Accuracy: 0.5840938722294654

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.010374996801114532 	  Loss: 1.6159119092538041 	 Accuracy: 0.5893089960886571
Delta: 0.008814264393835234 	  Loss: 1.6113160436681122 	 Accuracy: 0.5945241199478487
Delta: 0.007271548200809521 	  Loss: 1.6096126605452246 	 Accuracy: 0.590612777053455
Delta: 0.006420832813746853 	  Loss: 1.6096193547940674 	 Accuracy: 0.5840938722294654
Delta: 0.004803856223092503 	  Loss: 1.6099345300646666 	 Accuracy: 0.5867014341590613
Delta: 0.0039959651635602484 	  Loss: 1.6099845105844488 	 Accuracy: 0.5840938722294654
Delta: 0.0016493599694198838 	  Loss: 1.6098266029482058 	 Accuracy: 0.5853976531942634
Delta: 0.0035802688372297054 	  Loss: 1.609466796509877 	 Accuracy: 0.5840938722294654
Delta: 0.004025288630000947 	  Loss: 1.6092081762823387 	 Accuracy: 0.5827900912646675
Delta: 0.0025232592153864647 	  Loss: 1.6094057722281048 	 Accuracy: 0.5840938722294654
Delta: 0.002196086038363907 	  Loss: 1.6094759086830188 	 Accuracy: 0.5840938722294654
Delta: 0.0025990130401755485 	  Loss: 1.609336281625576 	 Accuracy: 0.5853976531942634
Delta: 0.0007690066389751454 	  Loss: 1.6093751058554415 	 Accuracy: 0.5840938722294654
Delta: 0.000648393275448162 	  Loss: 1.6095319312569725 	 Accuracy: 0.5853976531942634
Delta: 0.0005118157743667387 	  Loss: 1.609784039936217 	 Accuracy: 0.5840938722294654
Delta: 0.0005295512466950271 	  Loss: 1.6093832622003683 	 Accuracy: 0.5853976531942634
Delta: 0.0019841427702827854 	  Loss: 1.6093073513833835 	 Accuracy: 0.5853976531942634
Delta: 9.158304675172954e-05 	  Loss: 1.6093067087425852 	 Accuracy: 0.5880052151238592
Delta: 0.0008660918571372933 	  Loss: 1.6092679197710784 	 Accuracy: 0.5827900912646675
Delta: 0.0019157370082524688 	  Loss: 1.6097705168301655 	 Accuracy: 0.5840938722294654
Delta: 4.8047197287079505e-05 	  Loss: 1.609394222318023 	 Accuracy: 0.5840938722294654
Delta: 1.8589359113802627e-05 	  Loss: 1.6092700592990108 	 Accuracy: 0.5488917861799217
Delta: 0.0009943785759065546 	  Loss: 1.609950269212435 	 Accuracy: 0.5840938722294654
Delta: 0.0008355127138857338 	  Loss: 1.6098108429829021 	 Accuracy: 0.5827900912646675
Delta: 0.005993471255074946 	  Loss: 1.6110119376829974 	 Accuracy: 0.5827900912646675
Delta: 0.00350441155323526 	  Loss: 1.6107029271320448 	 Accuracy: 0.5840938722294654
Delta: 0.0029575339120533404 	  Loss: 1.6104053091157873 	 Accuracy: 0.5840938722294654
Delta: 0.0030523406724165952 	  Loss: 1.610206789645479 	 Accuracy: 0.5840938722294654
Delta: 5.5827372442622674e-05 	  Loss: 1.6101539898598407 	 Accuracy: 0.5840938722294654
Delta: 0.0009202726850316611 	  Loss: 1.6097582116849387 	 Accuracy: 0.5840938722294654
Delta: 0.0010674489962438233 	  Loss: 1.609573260861898 	 Accuracy: 0.5840938722294654
Delta: 0.0016596350753028755 	  Loss: 1.6094573993558594 	 Accuracy: 0.5827900912646675
Delta: 0.0006725609306110255 	  Loss: 1.6098759490594574 	 Accuracy: 0.5788787483702738
Delta: 0.00218410982558985 	  Loss: 1.6105849670707812 	 Accuracy: 0.5827900912646675
Delta: 0.001086811796956531 	  Loss: 1.6105852990341822 	 Accuracy: 0.5827900912646675
Delta: 0.0007767120347489142 	  Loss: 1.6100092481231434 	 Accuracy: 0.5775749674054759
Delta: 0.0007703444917977746 	  Loss: 1.6102462327925742 	 Accuracy: 0.5827900912646675
Delta: 0.0018465240985264311 	  Loss: 1.6100806713293165 	 Accuracy: 0.5840938722294654
Delta: 0.0021391018648460455 	  Loss: 1.6100707441970759 	 Accuracy: 0.5840938722294654
Delta: 0.0006776073932872551 	  Loss: 1.6100223414188966 	 Accuracy: 0.5867014341590613
Delta: 0.0029721073429575737 	  Loss: 1.6099532872152393 	 Accuracy: 0.5853976531942634
Delta: 0.004390989897369566 	  Loss: 1.6097358917184081 	 Accuracy: 0.5853976531942634
Delta: 0.0028762236131444547 	  Loss: 1.6094043845819024 	 Accuracy: 0.5853976531942634
Delta: 0.001587845835937873 	  Loss: 1.6091993178541513 	 Accuracy: 0.5880052151238592
Delta: 0.0035359246615195876 	  Loss: 1.610384253676747 	 Accuracy: 0.5840938722294654
Delta: 0.0036010796587109075 	  Loss: 1.6100858665057076 	 Accuracy: 0.5814863102998696
Delta: 0.0013691551053729887 	  Loss: 1.6094259319603204 	 Accuracy: 0.5840938722294654
Delta: 0.0012911741682372284 	  Loss: 1.6095233500720894 	 Accuracy: 0.5840938722294654
Delta: 0.0001369765027419879 	  Loss: 1.6104240205299614 	 Accuracy: 0.5827900912646675
Delta: 0.0022755785920711034 	  Loss: 1.6101646550812814 	 Accuracy: 0.5827900912646675
Delta: 0.0027636861587688496 	  Loss: 1.6100591727811375 	 Accuracy: 0.5840938722294654
Delta: 0.0037204079546954796 	  Loss: 1.6096130851662382 	 Accuracy: 0.5840938722294654
Delta: 0.0009132545366494419 	  Loss: 1.6097038648326936 	 Accuracy: 0.5840938722294654
Delta: 0.001701824029830538 	  Loss: 1.609714380311455 	 Accuracy: 0.5867014341590613
Delta: 6.163618502275981e-05 	  Loss: 1.609578707797354 	 Accuracy: 0.5840938722294654
Delta: 7.675615182426028e-05 	  Loss: 1.6097477244823188 	 Accuracy: 0.5827900912646675
Delta: 0.004244730222742052 	  Loss: 1.6107713458587118 	 Accuracy: 0.5827900912646675
Delta: 0.00010979049690241494 	  Loss: 1.6105232771502327 	 Accuracy: 0.5853976531942634
Delta: 0.003603052208654379 	  Loss: 1.6097429380134813 	 Accuracy: 0.5801825293350718
Delta: 0.0024273787967346323 	  Loss: 1.6101310638548216 	 Accuracy: 0.5840938722294654
Delta: 0.0015328108081093198 	  Loss: 1.609715915533544 	 Accuracy: 0.5827900912646675
Delta: 0.0021395681315049763 	  Loss: 1.609928319009927 	 Accuracy: 0.5788787483702738
Delta: 0.003966126747139802 	  Loss: 1.6101363271491826 	 Accuracy: 0.5827900912646675
Delta: 0.0034835769340520505 	  Loss: 1.610383939588592 	 Accuracy: 0.5853976531942634
Delta: 0.002900758767653413 	  Loss: 1.6104024154332333 	 Accuracy: 0.576271186440678
Delta: 0.003292961041896217 	  Loss: 1.611790802826142 	 Accuracy: 0.5840938722294654
Delta: 0.00335282580421709 	  Loss: 1.611497760849276 	 Accuracy: 0.5840938722294654
Delta: 0.00223913271983396 	  Loss: 1.611482026439107 	 Accuracy: 0.5840938722294654
Delta: 0.0032331076227459874 	  Loss: 1.6102668886620108 	 Accuracy: 0.5827900912646675
Delta: 0.003801761509357028 	  Loss: 1.610081861736887 	 Accuracy: 0.5827900912646675
Delta: 0.000854601088846798 	  Loss: 1.6100452881113148 	 Accuracy: 0.5827900912646675
Delta: 0.004190152660575111 	  Loss: 1.6107282422241993 	 Accuracy: 0.5827900912646675
Delta: 0.0030376436516330305 	  Loss: 1.6110525950181567 	 Accuracy: 0.5827900912646675
Delta: 0.001699043264394714 	  Loss: 1.6106308877824171 	 Accuracy: 0.5840938722294654
Delta: 0.0033967959826098665 	  Loss: 1.6097688894839155 	 Accuracy: 0.5840938722294654
Delta: 0.004248493961829886 	  Loss: 1.6101229868332227 	 Accuracy: 0.5840938722294654
Delta: 0.004002286848403462 	  Loss: 1.6094771311628677 	 Accuracy: 0.5840938722294654
Delta: 0.0013289686646742415 	  Loss: 1.609496768466279 	 Accuracy: 0.5827900912646675
Delta: 0.0028819949636109798 	  Loss: 1.609799722164233 	 Accuracy: 0.5827900912646675
Delta: 0.0035461388053378996 	  Loss: 1.6101425571097854 	 Accuracy: 0.5853976531942634
Delta: 0.0026412074133568626 	  Loss: 1.609813268896631 	 Accuracy: 0.5853976531942634
Delta: 0.001492645128084734 	  Loss: 1.610217504019968 	 Accuracy: 0.5827900912646675
Delta: 0.001205040807659316 	  Loss: 1.6104439351329676 	 Accuracy: 0.5853976531942634
Delta: 0.0027965930866749996 	  Loss: 1.6107943912483629 	 Accuracy: 0.5840938722294654
Delta: 0.0014368210032957827 	  Loss: 1.6106434754613272 	 Accuracy: 0.5840938722294654
Delta: 0.0014233875775581932 	  Loss: 1.6106114116991748 	 Accuracy: 0.5814863102998696
Delta: 0.0030955025500541545 	  Loss: 1.6118079908991922 	 Accuracy: 0.5827900912646675
Delta: 0.000701387006553887 	  Loss: 1.6117923345891287 	 Accuracy: 0.5814863102998696
Delta: 0.0035629214553003093 	  Loss: 1.612068917202053 	 Accuracy: 0.5801825293350718
Delta: 0.0033677467247471863 	  Loss: 1.6126549827571293 	 Accuracy: 0.5788787483702738
Delta: 0.003100491988770201 	  Loss: 1.613756794202019 	 Accuracy: 0.5801825293350718
Delta: 0.002430870349441667 	  Loss: 1.6136842124717397 	 Accuracy: 0.5827900912646675
Delta: 0.002519439696045128 	  Loss: 1.6132533115214593 	 Accuracy: 0.5788787483702738
Delta: 0.0010440650436371157 	  Loss: 1.6135334638145897 	 Accuracy: 0.5801825293350718
Delta: 0.004512697195656398 	  Loss: 1.6143691810465626 	 Accuracy: 0.5801825293350718
Delta: 0.02113335948756686 	  Loss: 2.1711891500785785 	 Accuracy: 0.18252933507170796
Delta: 0.019529085307538233 	  Loss: 2.036004829050296 	 Accuracy: 0.34810951760104303
Delta: 0.018094501530370954 	  Loss: 1.779584127380964 	 Accuracy: 0.3650586701434159
Delta: 0.014443701696619382 	  Loss: 1.6708857948345792 	 Accuracy: 0.35723598435462844
Delta: 0.011964519596661552 	  Loss: 1.6418410076934533 	 Accuracy: 0.34028683181225555

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.00919168862588703 	  Loss: 1.6343582151796028 	 Accuracy: 0.34159061277705344
Delta: 0.007130055988756017 	  Loss: 1.6329090223063165 	 Accuracy: 0.34159061277705344
Delta: 0.004417378314594605 	  Loss: 1.6324883829256467 	 Accuracy: 0.3376792698826597
Delta: 0.004696928271276254 	  Loss: 1.6322847562559608 	 Accuracy: 0.3389830508474576
Delta: 0.002957019575296672 	  Loss: 1.6322518613111214 	 Accuracy: 0.3389830508474576
Delta: 0.001623383640706116 	  Loss: 1.632394747322408 	 Accuracy: 0.3376792698826597
Delta: 0.001905287483253148 	  Loss: 1.6323480704954776 	 Accuracy: 0.3389830508474576
Delta: 0.002350248020212899 	  Loss: 1.6322166830129963 	 Accuracy: 0.3389830508474576
Delta: 0.003300520336896731 	  Loss: 1.6319913692057582 	 Accuracy: 0.3376792698826597
Delta: 0.0016807993672863768 	  Loss: 1.6323361524022184 	 Accuracy: 0.3389830508474576
Delta: 0.0016063329638848552 	  Loss: 1.6322913041403717 	 Accuracy: 0.3363754889178618
Delta: 0.0026964686994297264 	  Loss: 1.631918410127617 	 Accuracy: 0.3363754889178618
Delta: 0.0028326039494929846 	  Loss: 1.6320013915694211 	 Accuracy: 0.3285528031290743
Delta: 0.0021626565260905073 	  Loss: 1.6316200224714053 	 Accuracy: 0.3376792698826597
Delta: 0.0017553519218926723 	  Loss: 1.631609460937605 	 Accuracy: 0.34028683181225555
Delta: 0.0007939309679367914 	  Loss: 1.6321533635063317 	 Accuracy: 0.3363754889178618
Delta: 0.0005795090073986642 	  Loss: 1.6322179463396784 	 Accuracy: 0.3350717079530639
Delta: 0.0010547210324151446 	  Loss: 1.6318074475588251 	 Accuracy: 0.3350717079530639
Delta: 9.893203315837593e-06 	  Loss: 1.631783115998437 	 Accuracy: 0.3363754889178618
Delta: 0.0024363419773306572 	  Loss: 1.6315164357229546 	 Accuracy: 0.33376792698826596
Delta: 0.0010340705473952485 	  Loss: 1.632003523807105 	 Accuracy: 0.3363754889178618
Delta: 5.864745373193021e-05 	  Loss: 1.632127595315683 	 Accuracy: 0.3363754889178618
Delta: 5.0492213539964855e-05 	  Loss: 1.6318398675609544 	 Accuracy: 0.3363754889178618
Delta: 0.0008418940637822213 	  Loss: 1.63167317101655 	 Accuracy: 0.3389830508474576
Delta: 0.002007090099878254 	  Loss: 1.6317592108819847 	 Accuracy: 0.3363754889178618
Delta: 0.0015525501254857051 	  Loss: 1.6316263645739344 	 Accuracy: 0.3350717079530639
Delta: 0.004332223329956444 	  Loss: 1.6309605526122162 	 Accuracy: 0.3350717079530639
Delta: 0.004186730799273992 	  Loss: 1.6308795620003813 	 Accuracy: 0.3350717079530639
Delta: 0.0019972938471246107 	  Loss: 1.6311561380869453 	 Accuracy: 0.3350717079530639
Delta: 0.0028482698091342835 	  Loss: 1.6311159884225988 	 Accuracy: 0.3350717079530639
Delta: 0.0007571978089983666 	  Loss: 1.6319921515570701 	 Accuracy: 0.3363754889178618
Delta: 0.0018150107133814981 	  Loss: 1.6318011392334753 	 Accuracy: 0.3350717079530639
Delta: 0.0030863867807617226 	  Loss: 1.6308020803317222 	 Accuracy: 0.34028683181225555
Delta: 0.002169255560382713 	  Loss: 1.6307617446311076 	 Accuracy: 0.3363754889178618
Delta: 0.0016051230440539174 	  Loss: 1.6303679923448862 	 Accuracy: 0.3350717079530639
Delta: 0.001323177267267774 	  Loss: 1.6305709321116943 	 Accuracy: 0.3363754889178618
Delta: 0.0010179771829432185 	  Loss: 1.6305907644465913 	 Accuracy: 0.3363754889178618
Delta: 0.001981974700418266 	  Loss: 1.6308366239733014 	 Accuracy: 0.3363754889178618
Delta: 0.0012583584964890313 	  Loss: 1.63056721641299 	 Accuracy: 0.3350717079530639
Delta: 0.005262057432511738 	  Loss: 1.6293893853836539 	 Accuracy: 0.33376792698826596
Delta: 0.0038155726019610645 	  Loss: 1.6291943002342384 	 Accuracy: 0.3363754889178618
Delta: 8.071968719976442e-05 	  Loss: 1.628923981416821 	 Accuracy: 0.3350717079530639
Delta: 0.0008282958878108239 	  Loss: 1.6294454130237035 	 Accuracy: 0.3350717079530639
Delta: 0.0007774520506409711 	  Loss: 1.629169141281685 	 Accuracy: 0.3363754889178618
Delta: 0.0006801724696675694 	  Loss: 1.6291569844990184 	 Accuracy: 0.3350717079530639
Delta: 0.001491900058462684 	  Loss: 1.6290707643010331 	 Accuracy: 0.3350717079530639
Delta: 0.001363822414535682 	  Loss: 1.6288007167002414 	 Accuracy: 0.3350717079530639
Delta: 0.0008727042529877579 	  Loss: 1.6292023239767253 	 Accuracy: 0.3324641460234681
Delta: 0.0007603393094018501 	  Loss: 1.6288392449492912 	 Accuracy: 0.3350717079530639
Delta: 0.0027837859902715817 	  Loss: 1.6284448349967575 	 Accuracy: 0.3350717079530639
Delta: 0.0033014659126708026 	  Loss: 1.6278803922047491 	 Accuracy: 0.3376792698826597
Delta: 0.006070114902981386 	  Loss: 1.6276791314775552 	 Accuracy: 0.3363754889178618
Delta: 0.0043034851486334754 	  Loss: 1.6278456166005357 	 Accuracy: 0.3376792698826597
Delta: 0.003358752683383013 	  Loss: 1.6279435989437059 	 Accuracy: 0.3376792698826597
Delta: 0.0018814650726334831 	  Loss: 1.6278293596981939 	 Accuracy: 0.3376792698826597
Delta: 0.0009033610529076737 	  Loss: 1.6277900513439132 	 Accuracy: 0.3376792698826597
Delta: 0.0028973416959121507 	  Loss: 1.6276781285333368 	 Accuracy: 0.3376792698826597
Delta: 0.003118685320101895 	  Loss: 1.6272169477476264 	 Accuracy: 0.3363754889178618
Delta: 0.003245778993595995 	  Loss: 1.6269684546894942 	 Accuracy: 0.3363754889178618
Delta: 0.003467205029598721 	  Loss: 1.6270585351506153 	 Accuracy: 0.3376792698826597
Delta: 0.0019485170345617884 	  Loss: 1.6268067554101795 	 Accuracy: 0.3376792698826597
Delta: 0.0021528914963940844 	  Loss: 1.6269272644705972 	 Accuracy: 0.3376792698826597
Delta: 0.0017981452494646047 	  Loss: 1.6270192862361608 	 Accuracy: 0.33376792698826596
Delta: 0.0008732755653192516 	  Loss: 1.6269813331201801 	 Accuracy: 0.3376792698826597
Delta: 0.0006028563274742592 	  Loss: 1.6272246191362045 	 Accuracy: 0.34159061277705344
Delta: 0.0035577606151996222 	  Loss: 1.6276970885751776 	 Accuracy: 0.3389830508474576
Delta: 0.00118788485052514 	  Loss: 1.6276473481290599 	 Accuracy: 0.33376792698826596
Delta: 0.0011133227461788634 	  Loss: 1.627323215008337 	 Accuracy: 0.3389830508474576
Delta: 4.5374527049602884e-05 	  Loss: 1.6274632868821723 	 Accuracy: 0.3363754889178618
Delta: 0.001849816672495974 	  Loss: 1.6274813588999018 	 Accuracy: 0.3363754889178618
Delta: 0.0035467028075204395 	  Loss: 1.6275414797594125 	 Accuracy: 0.3363754889178618
Delta: 0.0023179624553669323 	  Loss: 1.627326011988219 	 Accuracy: 0.3363754889178618
Delta: 0.0030881372857310425 	  Loss: 1.6274751579907336 	 Accuracy: 0.33376792698826596
Delta: 0.005099906254157112 	  Loss: 1.6272709542409765 	 Accuracy: 0.3363754889178618
Delta: 0.004205354311691489 	  Loss: 1.6265615976864316 	 Accuracy: 0.3363754889178618
Delta: 0.004243359322114713 	  Loss: 1.6263053525210953 	 Accuracy: 0.3363754889178618
Delta: 0.0027729466036068044 	  Loss: 1.6263971294408697 	 Accuracy: 0.3376792698826597
Delta: 0.00437463735736674 	  Loss: 1.6263169080065452 	 Accuracy: 0.3389830508474576
Delta: 0.004488891289524769 	  Loss: 1.6260520170763892 	 Accuracy: 0.3494132985658409
Delta: 0.003788971195806144 	  Loss: 1.6268266279308605 	 Accuracy: 0.3376792698826597
Delta: 0.0031929300237070963 	  Loss: 1.6263531635956217 	 Accuracy: 0.3389830508474576
Delta: 0.002333459457846075 	  Loss: 1.6261389375501123 	 Accuracy: 0.34028683181225555
Delta: 0.004147910304032386 	  Loss: 1.6265888335071277 	 Accuracy: 0.34028683181225555
Delta: 0.0025698335371656597 	  Loss: 1.6260628003159754 	 Accuracy: 0.34028683181225555
Delta: 4.819317887444656e-05 	  Loss: 1.6259191439224776 	 Accuracy: 0.34028683181225555
Delta: 0.0005094354174065425 	  Loss: 1.6258629942937763 	 Accuracy: 0.34028683181225555
Delta: 9.794006843727551e-06 	  Loss: 1.6258918057656753 	 Accuracy: 0.3389830508474576
Delta: 0.0014289006755564156 	  Loss: 1.6261799543737565 	 Accuracy: 0.3389830508474576
Delta: 0.0012943155294534896 	  Loss: 1.625604345075986 	 Accuracy: 0.3363754889178618
Delta: 6.571445660479231e-05 	  Loss: 1.6260504586488607 	 Accuracy: 0.3324641460234681
Delta: 0.003164823654464183 	  Loss: 1.6263035767165692 	 Accuracy: 0.3376792698826597
Delta: 0.00155638839347324 	  Loss: 1.6255144826502632 	 Accuracy: 0.3376792698826597
Delta: 0.006058904112516845 	  Loss: 1.6265056090741605 	 Accuracy: 0.3468057366362451
Delta: 0.0035517418425932727 	  Loss: 1.626621916196902 	 Accuracy: 0.3350717079530639
Delta: 0.004399163569284688 	  Loss: 1.6272334280275997 	 Accuracy: 0.33116036505867014
Delta: 0.02125337213991766 	  Loss: 2.172646065673365 	 Accuracy: 0.1590612777053455
Delta: 0.018905609220137627 	  Loss: 2.0538623680867563 	 Accuracy: 0.3246414602346806
Delta: 0.018177088754683778 	  Loss: 1.8434861264643736 	 Accuracy: 0.39113428943937417
Delta: 0.015643288346467457 	  Loss: 1.718737555626268 	 Accuracy: 0.4132985658409387
Delta: 0.011702953017954713 	  Loss: 1.6869783554118802 	 Accuracy: 0.4172099087353325

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.009056691475463874 	  Loss: 1.680956197690228 	 Accuracy: 0.41851368970013036
Delta: 0.006638142278912252 	  Loss: 1.6796004286244473 	 Accuracy: 0.4172099087353325
Delta: 0.005391717251141791 	  Loss: 1.680046961870381 	 Accuracy: 0.4211212516297262
Delta: 0.0035790234814882097 	  Loss: 1.6798553811278847 	 Accuracy: 0.4211212516297262
Delta: 0.0036187719870001854 	  Loss: 1.6799184241168095 	 Accuracy: 0.4198174706649283
Delta: 0.0030967813099932883 	  Loss: 1.6798730713104595 	 Accuracy: 0.4198174706649283
Delta: 0.0011174224957704174 	  Loss: 1.6797502533934878 	 Accuracy: 0.41851368970013036
Delta: 0.00713396492399331 	  Loss: 1.6806331648723547 	 Accuracy: 0.4198174706649283
Delta: 0.0039483677121999565 	  Loss: 1.6801620134470017 	 Accuracy: 0.4198174706649283
Delta: 0.004915592056326246 	  Loss: 1.679832598241022 	 Accuracy: 0.4211212516297262
Delta: 0.0039675281906444565 	  Loss: 1.6798723207545794 	 Accuracy: 0.4211212516297262
Delta: 0.0018845390584143152 	  Loss: 1.6799614713471365 	 Accuracy: 0.42242503259452413
Delta: 0.0021118174569173306 	  Loss: 1.679866814985263 	 Accuracy: 0.4211212516297262
Delta: 0.0023620405167099705 	  Loss: 1.6798488075864277 	 Accuracy: 0.4211212516297262
Delta: 3.505821165620419e-05 	  Loss: 1.679781445431098 	 Accuracy: 0.42633637548891784
Delta: 0.004710223453190839 	  Loss: 1.679055185181391 	 Accuracy: 0.423728813559322
Delta: 0.003060733439370163 	  Loss: 1.6788699001555585 	 Accuracy: 0.423728813559322
Delta: 0.003097129752506597 	  Loss: 1.678833323490264 	 Accuracy: 0.423728813559322
Delta: 0.0028266436822672143 	  Loss: 1.6784846491937482 	 Accuracy: 0.423728813559322
Delta: 4.212925861274461e-05 	  Loss: 1.6785856777727628 	 Accuracy: 0.423728813559322
Delta: 1.4425310892204882e-05 	  Loss: 1.678542210397747 	 Accuracy: 0.423728813559322
Delta: 4.740901997959495e-05 	  Loss: 1.6785635720019345 	 Accuracy: 0.423728813559322
Delta: 0.0006579435541618347 	  Loss: 1.6786671910478204 	 Accuracy: 0.42242503259452413
Delta: 0.006492410098435007 	  Loss: 1.678483868448781 	 Accuracy: 0.423728813559322
Delta: 0.00291120799202685 	  Loss: 1.6784887619592848 	 Accuracy: 0.423728813559322
Delta: 0.001777572368168099 	  Loss: 1.6784438867186264 	 Accuracy: 0.423728813559322
Delta: 0.0025082970297294724 	  Loss: 1.678381292160986 	 Accuracy: 0.42503259452411996
Delta: 0.0014657413814701174 	  Loss: 1.6781933615631321 	 Accuracy: 0.42503259452411996
Delta: 0.001772539003955366 	  Loss: 1.6779079646196349 	 Accuracy: 0.423728813559322
Delta: 0.0024615508754468533 	  Loss: 1.6783860745458652 	 Accuracy: 0.423728813559322
Delta: 0.0008206356596661803 	  Loss: 1.6781940221494105 	 Accuracy: 0.423728813559322
Delta: 0.0009153336389727123 	  Loss: 1.6784143944364511 	 Accuracy: 0.4211212516297262
Delta: 0.0013312930731406375 	  Loss: 1.6784367223241943 	 Accuracy: 0.423728813559322
Delta: 0.002337581133839585 	  Loss: 1.6781034964869765 	 Accuracy: 0.423728813559322
Delta: 0.002397166628510932 	  Loss: 1.6780117993211072 	 Accuracy: 0.423728813559322
Delta: 0.001244637570554509 	  Loss: 1.677891202968602 	 Accuracy: 0.4211212516297262
Delta: 0.0034304783763869813 	  Loss: 1.6773308009301777 	 Accuracy: 0.42503259452411996
Delta: 0.00388657815516758 	  Loss: 1.6775859598644947 	 Accuracy: 0.4276401564537158
Delta: 0.004708193988094559 	  Loss: 1.6765020498309202 	 Accuracy: 0.42503259452411996
Delta: 0.002596503428471492 	  Loss: 1.6766081826085768 	 Accuracy: 0.42633637548891784
Delta: 0.0021953268883623247 	  Loss: 1.6759562702552038 	 Accuracy: 0.42633637548891784
Delta: 0.0019124236393614396 	  Loss: 1.676030339739336 	 Accuracy: 0.42894393741851367
Delta: 0.003369403112037924 	  Loss: 1.6758433037163418 	 Accuracy: 0.42894393741851367
Delta: 0.0018500186789044684 	  Loss: 1.6758025310548648 	 Accuracy: 0.42633637548891784
Delta: 0.0020412987497760017 	  Loss: 1.6768027564267842 	 Accuracy: 0.42242503259452413
Delta: 0.0032699266334919406 	  Loss: 1.676146921606203 	 Accuracy: 0.4276401564537158
Delta: 0.0021475591457591134 	  Loss: 1.676631497588599 	 Accuracy: 0.4211212516297262
Delta: 0.0031654483537885266 	  Loss: 1.6772752458831628 	 Accuracy: 0.4211212516297262
Delta: 0.0050469436081714905 	  Loss: 1.6775019450906852 	 Accuracy: 0.4302477183833116
Delta: 0.004746561892557398 	  Loss: 1.676404321020228 	 Accuracy: 0.4302477183833116
Delta: 0.005652594281747208 	  Loss: 1.6752307618779982 	 Accuracy: 0.42894393741851367
Delta: 0.003543455511254835 	  Loss: 1.674247699729888 	 Accuracy: 0.4302477183833116
Delta: 0.0020003546652551337 	  Loss: 1.674371659112859 	 Accuracy: 0.4302477183833116
Delta: 0.0033546388145910717 	  Loss: 1.6742944945790401 	 Accuracy: 0.42894393741851367
Delta: 0.004878479860408109 	  Loss: 1.6758647412104 	 Accuracy: 0.4302477183833116
Delta: 0.0034650100650850616 	  Loss: 1.6746736155276118 	 Accuracy: 0.4315514993481095
Delta: 0.005059458794074153 	  Loss: 1.6751861679937994 	 Accuracy: 0.4315514993481095
Delta: 0.004440088552407409 	  Loss: 1.6736930536863202 	 Accuracy: 0.4302477183833116
Delta: 0.00339253792618014 	  Loss: 1.6735295520122029 	 Accuracy: 0.4315514993481095
Delta: 0.003462050747722014 	  Loss: 1.6735406888591506 	 Accuracy: 0.43285528031290743
Delta: 0.0026252547738216314 	  Loss: 1.673606285740202 	 Accuracy: 0.43415906127770537
Delta: 0.002895318517860302 	  Loss: 1.6732293973668866 	 Accuracy: 0.4315514993481095
Delta: 0.0023048241474068385 	  Loss: 1.6737392116891838 	 Accuracy: 0.42894393741851367
Delta: 0.0026170070490558815 	  Loss: 1.6741799530557226 	 Accuracy: 0.4302477183833116
Delta: 2.325565072204019e-05 	  Loss: 1.6741165796710429 	 Accuracy: 0.42894393741851367
Delta: 0.0029895131849396787 	  Loss: 1.6746095454614793 	 Accuracy: 0.4302477183833116
Delta: 0.0013640247100267118 	  Loss: 1.674742103826587 	 Accuracy: 0.4302477183833116
Delta: 0.0010495939554321025 	  Loss: 1.674577855488846 	 Accuracy: 0.4302477183833116
Delta: 0.0030309145689471455 	  Loss: 1.6743231999959234 	 Accuracy: 0.4302477183833116
Delta: 0.0016255018292276524 	  Loss: 1.6747041728621772 	 Accuracy: 0.4302477183833116
Delta: 0.003917456617176911 	  Loss: 1.6748848962270044 	 Accuracy: 0.4315514993481095
Delta: 0.0020172131116358524 	  Loss: 1.6749015011496087 	 Accuracy: 0.4302477183833116
Delta: 0.002005980372064985 	  Loss: 1.6744246893947268 	 Accuracy: 0.4302477183833116
Delta: 0.0031095178451672834 	  Loss: 1.674077627536299 	 Accuracy: 0.4315514993481095
Delta: 0.0025516527018972527 	  Loss: 1.6739442752093212 	 Accuracy: 0.4315514993481095
Delta: 0.0013911338450758944 	  Loss: 1.6742311505394372 	 Accuracy: 0.4315514993481095
Delta: 0.002338000231129142 	  Loss: 1.6741267152600203 	 Accuracy: 0.4302477183833116
Delta: 0.0035358547996767625 	  Loss: 1.674639960015257 	 Accuracy: 0.4302477183833116
Delta: 3.717953178478342e-05 	  Loss: 1.6747464069288789 	 Accuracy: 0.43415906127770537
Delta: 0.004884393475496612 	  Loss: 1.6735768928483106 	 Accuracy: 0.43285528031290743
Delta: 0.0007942599961480426 	  Loss: 1.6731278922978738 	 Accuracy: 0.43415906127770537
Delta: 0.0005017608341016264 	  Loss: 1.673130573373289 	 Accuracy: 0.43285528031290743
Delta: 0.0023326987790272 	  Loss: 1.6727751575409695 	 Accuracy: 0.43285528031290743
Delta: 0.00228950835472364 	  Loss: 1.67346639563557 	 Accuracy: 0.4315514993481095
Delta: 0.003984991430186829 	  Loss: 1.6742245042132027 	 Accuracy: 0.42894393741851367
Delta: 0.002766047346677905 	  Loss: 1.6740560032010188 	 Accuracy: 0.4315514993481095
Delta: 0.0006831470450424008 	  Loss: 1.6739482945503166 	 Accuracy: 0.4315514993481095
Delta: 0.0006302868311032258 	  Loss: 1.6738107063424024 	 Accuracy: 0.4315514993481095
Delta: 2.3416957847480505e-05 	  Loss: 1.6738667351779422 	 Accuracy: 0.43415906127770537
Delta: 0.002289526286987178 	  Loss: 1.6734458432612265 	 Accuracy: 0.4302477183833116
Delta: 0.0011223248102548741 	  Loss: 1.6738465008909227 	 Accuracy: 0.4315514993481095
Delta: 0.002512708630528825 	  Loss: 1.6730178983434154 	 Accuracy: 0.43415906127770537
Delta: 0.0028119789350313537 	  Loss: 1.6723738446769578 	 Accuracy: 0.43546284224250326
Delta: 0.0013344915057240789 	  Loss: 1.6724140127651548 	 Accuracy: 0.43546284224250326
Delta: 0.0030492344325264618 	  Loss: 1.6724937517313312 	 Accuracy: 0.43285528031290743
Delta: 0.021124946033015544 	  Loss: 2.1739259900593977 	 Accuracy: 0.17992177314211213
Delta: 0.019108044445239787 	  Loss: 2.0585716530343316 	 Accuracy: 0.3272490221642764
Delta: 0.018278305003392465 	  Loss: 1.8440512059268155 	 Accuracy: 0.4380704041720991
Delta: 0.015783381697635445 	  Loss: 1.697691262557175 	 Accuracy: 0.4680573663624511
Delta: 0.012131076050827515 	  Loss: 1.6601190028236976 	 Accuracy: 0.4589308996088657
Delta: 0.009278517571204847 	  Loss: 1.650196716994164 	 Accuracy: 0.4602346805736636

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007572477413546888 	  Loss: 1.646110159734854 	 Accuracy: 0.46153846153846156
Delta: 0.005779140208982268 	  Loss: 1.6439580804276228 	 Accuracy: 0.4576271186440678
Delta: 0.0032756059572523776 	  Loss: 1.6431302590828336 	 Accuracy: 0.46153846153846156
Delta: 0.003784244836032248 	  Loss: 1.6425965662046194 	 Accuracy: 0.45632333767926986
Delta: 0.0030077836195362587 	  Loss: 1.6429196866010172 	 Accuracy: 0.46153846153846156
Delta: 0.0015407155762710097 	  Loss: 1.641889882065493 	 Accuracy: 0.46284224250325945
Delta: 7.949016240302838e-05 	  Loss: 1.6418288740274594 	 Accuracy: 0.46284224250325945
Delta: 0.0018247991917464403 	  Loss: 1.6419561783327703 	 Accuracy: 0.46284224250325945
Delta: 0.0023763285204957073 	  Loss: 1.6416328847094472 	 Accuracy: 0.46284224250325945
Delta: 0.0011413384910912607 	  Loss: 1.641803675066817 	 Accuracy: 0.46284224250325945
Delta: 0.0035718348888682506 	  Loss: 1.6417092719252797 	 Accuracy: 0.46284224250325945
Delta: 0.0012767246486556025 	  Loss: 1.6415041471047576 	 Accuracy: 0.4641460234680574
Delta: 0.0009692570203117799 	  Loss: 1.6416978876931763 	 Accuracy: 0.46284224250325945
Delta: 0.0012978907818831978 	  Loss: 1.6416421443374345 	 Accuracy: 0.46284224250325945
Delta: 0.0017864917466703326 	  Loss: 1.6416698693657268 	 Accuracy: 0.4641460234680574
Delta: 0.0010778605749734462 	  Loss: 1.6419837138795184 	 Accuracy: 0.4602346805736636
Delta: 0.004770946488568716 	  Loss: 1.640611189056787 	 Accuracy: 0.4680573663624511
Delta: 0.002909042064781636 	  Loss: 1.6406521023090253 	 Accuracy: 0.46284224250325945
Delta: 0.0010868480704024305 	  Loss: 1.640670385098185 	 Accuracy: 0.4654498044328553
Delta: 0.004099564170995814 	  Loss: 1.6407249375831447 	 Accuracy: 0.4641460234680574
Delta: 0.003507267660872467 	  Loss: 1.6411875455067206 	 Accuracy: 0.4641460234680574
Delta: 0.002255533102894872 	  Loss: 1.641115288903869 	 Accuracy: 0.4654498044328553
Delta: 0.004434670416212334 	  Loss: 1.640946557343187 	 Accuracy: 0.46936114732724904
Delta: 0.0032469601543600414 	  Loss: 1.6407226564161066 	 Accuracy: 0.4667535853976532
Delta: 0.0013171537383182001 	  Loss: 1.6407049064625627 	 Accuracy: 0.4654498044328553
Delta: 0.001462728020134792 	  Loss: 1.6412251392123105 	 Accuracy: 0.4667535853976532
Delta: 0.00010238989970099255 	  Loss: 1.6405221037975166 	 Accuracy: 0.4641460234680574
Delta: 0.003073210712800618 	  Loss: 1.6405880602885938 	 Accuracy: 0.4680573663624511
Delta: 0.0012831799566509617 	  Loss: 1.6405830412290037 	 Accuracy: 0.4667535853976532
Delta: 0.001981622428813497 	  Loss: 1.6406975568236117 	 Accuracy: 0.4667535853976532
Delta: 0.000548238829061619 	  Loss: 1.6406713279664205 	 Accuracy: 0.4667535853976532
Delta: 6.110741451021876e-05 	  Loss: 1.6406676395322053 	 Accuracy: 0.4680573663624511
Delta: 0.0008308520638326897 	  Loss: 1.6406916991781104 	 Accuracy: 0.4667535853976532
Delta: 2.7249216837918487e-05 	  Loss: 1.6406762426376478 	 Accuracy: 0.4589308996088657
Delta: 0.0016722442818721441 	  Loss: 1.6403846128243056 	 Accuracy: 0.4641460234680574
Delta: 3.4662380743907466e-05 	  Loss: 1.6404355838925504 	 Accuracy: 0.4667535853976532
Delta: 0.0015383594767353847 	  Loss: 1.6407627034994043 	 Accuracy: 0.4667535853976532
Delta: 0.0007662461673915013 	  Loss: 1.640408333818695 	 Accuracy: 0.4667535853976532
Delta: 0.0006530291766037813 	  Loss: 1.64069612248191 	 Accuracy: 0.4667535853976532
Delta: 0.0010887892072419234 	  Loss: 1.6405585528117888 	 Accuracy: 0.4641460234680574
Delta: 0.0011238327311586477 	  Loss: 1.6406289622909476 	 Accuracy: 0.4745762711864407
Delta: 9.67116579331534e-05 	  Loss: 1.6405703508462115 	 Accuracy: 0.4667535853976532
Delta: 0.001784046556871551 	  Loss: 1.6406096528471217 	 Accuracy: 0.4667535853976532
Delta: 0.0010687168839442855 	  Loss: 1.6406213419416147 	 Accuracy: 0.4667535853976532
Delta: 0.004055544153592056 	  Loss: 1.640557137461847 	 Accuracy: 0.4667535853976532
Delta: 0.0014914306785419125 	  Loss: 1.6402548720945216 	 Accuracy: 0.4589308996088657
Delta: 0.0026545671212648055 	  Loss: 1.640865428089389 	 Accuracy: 0.46284224250325945
Delta: 0.004358402322360726 	  Loss: 1.6410613278708457 	 Accuracy: 0.4641460234680574
Delta: 0.0009153326515016668 	  Loss: 1.6412403458835094 	 Accuracy: 0.46153846153846156
Delta: 0.0036399849598673156 	  Loss: 1.6410629571174162 	 Accuracy: 0.46153846153846156
Delta: 0.002604754867118921 	  Loss: 1.6408784219819232 	 Accuracy: 0.46284224250325945
Delta: 0.001405305454631432 	  Loss: 1.6411945229849842 	 Accuracy: 0.4654498044328553
Delta: 0.004958697176968482 	  Loss: 1.6412644887514043 	 Accuracy: 0.4680573663624511
Delta: 0.0020374559292707668 	  Loss: 1.6418473504717352 	 Accuracy: 0.46284224250325945
Delta: 0.003019583561585901 	  Loss: 1.6414542564834702 	 Accuracy: 0.46153846153846156
Delta: 0.004220482342303728 	  Loss: 1.6417885253491609 	 Accuracy: 0.4641460234680574
Delta: 0.003429505676396147 	  Loss: 1.6413299759628053 	 Accuracy: 0.4511082138200782
Delta: 0.0012698449702501517 	  Loss: 1.6416364701847856 	 Accuracy: 0.4654498044328553
Delta: 0.0017966410488185285 	  Loss: 1.64150493240256 	 Accuracy: 0.4654498044328553
Delta: 0.0016026163377929432 	  Loss: 1.6415322127221772 	 Accuracy: 0.4602346805736636
Delta: 0.004020342459697324 	  Loss: 1.6408448730195964 	 Accuracy: 0.4602346805736636
Delta: 0.0014959560844237131 	  Loss: 1.6408450529637268 	 Accuracy: 0.4667535853976532
Delta: 0.003313486741279976 	  Loss: 1.6393897288093058 	 Accuracy: 0.4641460234680574
Delta: 0.004474666693518604 	  Loss: 1.639853885368196 	 Accuracy: 0.4641460234680574
Delta: 0.0026530255791221086 	  Loss: 1.638965420495422 	 Accuracy: 0.45241199478487615
Delta: 0.004476911726413075 	  Loss: 1.6400992807551287 	 Accuracy: 0.4641460234680574
Delta: 0.0030969921610947476 	  Loss: 1.6390877386530582 	 Accuracy: 0.46936114732724904
Delta: 0.007407494784194863 	  Loss: 1.6372858397404666 	 Accuracy: 0.4641460234680574
Delta: 0.005566627751547991 	  Loss: 1.6384107656993767 	 Accuracy: 0.46284224250325945
Delta: 0.003450223166110836 	  Loss: 1.6382635988415655 	 Accuracy: 0.4641460234680574
Delta: 4.50487856645173e-05 	  Loss: 1.63822071328616 	 Accuracy: 0.4654498044328553
Delta: 0.004194925355371254 	  Loss: 1.6391649540410225 	 Accuracy: 0.4667535853976532
Delta: 0.004969870898139318 	  Loss: 1.6391557253586404 	 Accuracy: 0.4654498044328553
Delta: 0.004038919221855781 	  Loss: 1.639296733998138 	 Accuracy: 0.4654498044328553
Delta: 0.0031716468353602503 	  Loss: 1.6390546572876077 	 Accuracy: 0.4654498044328553
Delta: 0.00495221127421523 	  Loss: 1.6381919284709456 	 Accuracy: 0.4641460234680574
Delta: 0.0011987157850879232 	  Loss: 1.6383238944284222 	 Accuracy: 0.4667535853976532
Delta: 0.004818979083886903 	  Loss: 1.6378073578682681 	 Accuracy: 0.4641460234680574
Delta: 0.004995926689513916 	  Loss: 1.6365770036235663 	 Accuracy: 0.47327249022164275
Delta: 0.00529206404940886 	  Loss: 1.636400201195968 	 Accuracy: 0.46936114732724904
Delta: 0.00338336752115847 	  Loss: 1.6358247946649813 	 Accuracy: 0.4680573663624511
Delta: 0.0027250752871678416 	  Loss: 1.6359119127467676 	 Accuracy: 0.4745762711864407
Delta: 0.006547095823944857 	  Loss: 1.634224500885334 	 Accuracy: 0.4706649282920469
Delta: 0.0056407838283445 	  Loss: 1.634834055907951 	 Accuracy: 0.47196870925684486
Delta: 0.0030765639447445825 	  Loss: 1.6348137113084398 	 Accuracy: 0.47196870925684486
Delta: 0.002260108979754103 	  Loss: 1.6340924251322677 	 Accuracy: 0.4706649282920469
Delta: 0.0041469610746672735 	  Loss: 1.635116461113701 	 Accuracy: 0.4863102998696219
Delta: 0.0061443772835836205 	  Loss: 1.6346515854664996 	 Accuracy: 0.46936114732724904
Delta: 0.005373355066838887 	  Loss: 1.6344446914901392 	 Accuracy: 0.47196870925684486
Delta: 0.0060344008296206505 	  Loss: 1.6349540649882595 	 Accuracy: 0.47196870925684486
Delta: 0.005864261312744244 	  Loss: 1.6364057484327 	 Accuracy: 0.47196870925684486
Delta: 0.002899182497898378 	  Loss: 1.6358499976549674 	 Accuracy: 0.4680573663624511
Delta: 0.001810588346292215 	  Loss: 1.6358368753141275 	 Accuracy: 0.47196870925684486
Delta: 0.0009605932030410234 	  Loss: 1.6358060194077098 	 Accuracy: 0.4654498044328553
Delta: 0.021194364050903143 	  Loss: 2.1730865532574803 	 Accuracy: 0.23859191655801826
Delta: 0.01939462357857544 	  Loss: 2.0400908345881703 	 Accuracy: 0.439374185136897
Delta: 0.01840271724921186 	  Loss: 1.7806467150377787 	 Accuracy: 0.5019556714471969
Delta: 0.014530594251844903 	  Loss: 1.6661100177162538 	 Accuracy: 0.500651890482399
Delta: 0.009746479450860785 	  Loss: 1.6506683341023927 	 Accuracy: 0.4941329856584094

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.0069894602321384555 	  Loss: 1.6492821992044926 	 Accuracy: 0.49674054758800523
Delta: 0.006185583489158052 	  Loss: 1.649751850726672 	 Accuracy: 0.49282920469361147
Delta: 0.005266647916161428 	  Loss: 1.6491608075695567 	 Accuracy: 0.49282920469361147
Delta: 0.003216727806597125 	  Loss: 1.64894381666411 	 Accuracy: 0.4915254237288136
Delta: 0.004285314676863757 	  Loss: 1.6483783795925602 	 Accuracy: 0.4915254237288136
Delta: 0.00207987923764779 	  Loss: 1.6481220108487409 	 Accuracy: 0.49282920469361147
Delta: 0.0036869910863050097 	  Loss: 1.648349692813861 	 Accuracy: 0.49282920469361147
Delta: 0.0027788303867246605 	  Loss: 1.6476736958943012 	 Accuracy: 0.4941329856584094
Delta: 0.0034162076813592695 	  Loss: 1.6480354217962399 	 Accuracy: 0.49282920469361147
Delta: 0.00297801301725719 	  Loss: 1.6476708743967496 	 Accuracy: 0.4876140808344198
Delta: 0.006731257349925051 	  Loss: 1.6475029321984207 	 Accuracy: 0.48891786179921776
Delta: 0.002729229566119565 	  Loss: 1.647915103378009 	 Accuracy: 0.48891786179921776
Delta: 0.0027182662467834452 	  Loss: 1.648294817200559 	 Accuracy: 0.4863102998696219
Delta: 0.0022841966710653873 	  Loss: 1.6480452686218625 	 Accuracy: 0.48891786179921776
Delta: 5.255111874333102e-05 	  Loss: 1.6477039281443746 	 Accuracy: 0.48891786179921776
Delta: 0.0009410195922921042 	  Loss: 1.6477703506322043 	 Accuracy: 0.4863102998696219
Delta: 0.0016144637207935332 	  Loss: 1.6480053165914827 	 Accuracy: 0.48891786179921776
Delta: 0.004240794926205469 	  Loss: 1.648838311325051 	 Accuracy: 0.4876140808344198
Delta: 0.005561224488606352 	  Loss: 1.6492214112232222 	 Accuracy: 0.4863102998696219
Delta: 0.003374358868009237 	  Loss: 1.6491381284028432 	 Accuracy: 0.4863102998696219
Delta: 0.0032115033780913843 	  Loss: 1.6488795032898567 	 Accuracy: 0.48891786179921776
Delta: 0.0028476944749405235 	  Loss: 1.6484633024275315 	 Accuracy: 0.48891786179921776
Delta: 0.0029502788087572974 	  Loss: 1.647867190952693 	 Accuracy: 0.4876140808344198
Delta: 2.7085591419451118e-05 	  Loss: 1.6479061543293612 	 Accuracy: 0.4876140808344198
Delta: 0.0007831001219871141 	  Loss: 1.6485714130440228 	 Accuracy: 0.4863102998696219
Delta: 0.003693550791587217 	  Loss: 1.6490389370425556 	 Accuracy: 0.4915254237288136
Delta: 0.0008572584963420914 	  Loss: 1.649111240213312 	 Accuracy: 0.4863102998696219
Delta: 0.0019262021842813705 	  Loss: 1.6492516430056137 	 Accuracy: 0.48891786179921776
Delta: 0.0005815987397782162 	  Loss: 1.6488212783106642 	 Accuracy: 0.4876140808344198
Delta: 0.0035536208689007746 	  Loss: 1.648868711832211 	 Accuracy: 0.4915254237288136
Delta: 0.0029439162312891545 	  Loss: 1.6489665768714636 	 Accuracy: 0.49022164276401564
Delta: 0.002840911753983522 	  Loss: 1.6488434941862486 	 Accuracy: 0.49282920469361147
Delta: 0.004704031730792818 	  Loss: 1.64838469499582 	 Accuracy: 0.49022164276401564
Delta: 0.001917506841964497 	  Loss: 1.6487252343871845 	 Accuracy: 0.4915254237288136
Delta: 0.0007989258621239617 	  Loss: 1.6483218107661886 	 Accuracy: 0.48891786179921776
Delta: 0.00386814622520015 	  Loss: 1.6491578598055383 	 Accuracy: 0.4915254237288136
Delta: 0.004704775122805001 	  Loss: 1.648972028659038 	 Accuracy: 0.4915254237288136
Delta: 0.0029861090893548064 	  Loss: 1.6489570683866686 	 Accuracy: 0.4915254237288136
Delta: 8.312884303487235e-06 	  Loss: 1.64896784380249 	 Accuracy: 0.4941329856584094
Delta: 0.0017445384080637563 	  Loss: 1.6489071889875158 	 Accuracy: 0.4915254237288136
Delta: 0.0031882390786444315 	  Loss: 1.6492602586074783 	 Accuracy: 0.49282920469361147
Delta: 0.0027148831036022123 	  Loss: 1.6491415873944328 	 Accuracy: 0.49022164276401564
Delta: 0.0014105046962767849 	  Loss: 1.6486639803702445 	 Accuracy: 0.49282920469361147
Delta: 0.0019256482689780155 	  Loss: 1.6489780842883301 	 Accuracy: 0.49282920469361147
Delta: 0.0016448632951775663 	  Loss: 1.648736619889471 	 Accuracy: 0.49022164276401564
Delta: 0.0009773000432460692 	  Loss: 1.648892352566604 	 Accuracy: 0.49282920469361147
Delta: 0.003032919097374124 	  Loss: 1.648286778773895 	 Accuracy: 0.4941329856584094
Delta: 0.004267261956946429 	  Loss: 1.6473337106328838 	 Accuracy: 0.49282920469361147
Delta: 0.0020679536577835134 	  Loss: 1.64730689657268 	 Accuracy: 0.48239895697522817
Delta: 0.005989475374564629 	  Loss: 1.6490789197544968 	 Accuracy: 0.4954367666232073
Delta: 0.005873877718882448 	  Loss: 1.6486351881951489 	 Accuracy: 0.4980443285528031
Delta: 0.003154520617015942 	  Loss: 1.6485753194533208 	 Accuracy: 0.4954367666232073
Delta: 0.0023858350357172046 	  Loss: 1.648646989795264 	 Accuracy: 0.4954367666232073
Delta: 0.0040208852499055096 	  Loss: 1.6487626981196244 	 Accuracy: 0.4954367666232073
Delta: 0.0018761844002199266 	  Loss: 1.6486805264792292 	 Accuracy: 0.4941329856584094
Delta: 0.0014722513731035875 	  Loss: 1.648852018278769 	 Accuracy: 0.49674054758800523
Delta: 4.8271321263604145e-05 	  Loss: 1.6487005117145088 	 Accuracy: 0.49282920469361147
Delta: 0.003540094905054196 	  Loss: 1.6488354822800613 	 Accuracy: 0.4954367666232073
Delta: 0.004770057682394956 	  Loss: 1.6490954112209344 	 Accuracy: 0.4954367666232073
Delta: 0.002192526425505266 	  Loss: 1.6489022840589103 	 Accuracy: 0.4941329856584094
Delta: 0.004026339937570565 	  Loss: 1.6489169882177697 	 Accuracy: 0.4954367666232073
Delta: 0.0018935860159926144 	  Loss: 1.6488781039466818 	 Accuracy: 0.49674054758800523
Delta: 0.002643333595730621 	  Loss: 1.6491714179088504 	 Accuracy: 0.4941329856584094
Delta: 0.0013205255329464538 	  Loss: 1.6488123917977155 	 Accuracy: 0.49674054758800523
Delta: 0.0034257247367489485 	  Loss: 1.6487874759532477 	 Accuracy: 0.4941329856584094
Delta: 0.0036679726912148634 	  Loss: 1.6485472459449062 	 Accuracy: 0.4954367666232073
Delta: 0.003392804486760139 	  Loss: 1.6489423307796143 	 Accuracy: 0.4954367666232073
Delta: 0.002592984664079318 	  Loss: 1.6493269350602158 	 Accuracy: 0.49674054758800523
Delta: 0.0005684790028922861 	  Loss: 1.6490247692412072 	 Accuracy: 0.49674054758800523
Delta: 0.0014422238125208183 	  Loss: 1.6486204043219237 	 Accuracy: 0.4954367666232073
Delta: 0.0025434024318879704 	  Loss: 1.6488608474448443 	 Accuracy: 0.4980443285528031
Delta: 0.00501335575692369 	  Loss: 1.6481225135285675 	 Accuracy: 0.4980443285528031
Delta: 0.0005108315022096285 	  Loss: 1.6480992606336222 	 Accuracy: 0.49934810951760106
Delta: 0.0017536631972878967 	  Loss: 1.6475807705860026 	 Accuracy: 0.4980443285528031
Delta: 0.002621089229990377 	  Loss: 1.6481747559865236 	 Accuracy: 0.49674054758800523
Delta: 0.0010654419281847076 	  Loss: 1.648140473241944 	 Accuracy: 0.4980443285528031
Delta: 0.003933378353643595 	  Loss: 1.6482980048211358 	 Accuracy: 0.49934810951760106
Delta: 0.0017570000070339443 	  Loss: 1.6483215247695977 	 Accuracy: 0.49934810951760106
Delta: 0.0027429788502645915 	  Loss: 1.6483200275825287 	 Accuracy: 0.500651890482399
Delta: 0.002775891975490947 	  Loss: 1.6482774076656646 	 Accuracy: 0.49934810951760106
Delta: 0.002038999862672639 	  Loss: 1.6483580920854828 	 Accuracy: 0.49934810951760106
Delta: 0.0004965061187975977 	  Loss: 1.6483548942766801 	 Accuracy: 0.49934810951760106
Delta: 0.002378324709938888 	  Loss: 1.6484089006535527 	 Accuracy: 0.4941329856584094
Delta: 0.005476706230448032 	  Loss: 1.6507950996086322 	 Accuracy: 0.49674054758800523
Delta: 0.004566625335067605 	  Loss: 1.6482577884845164 	 Accuracy: 0.49934810951760106
Delta: 0.004430230713634803 	  Loss: 1.648266531147225 	 Accuracy: 0.4980443285528031
Delta: 0.0005796969563684383 	  Loss: 1.6481439831435911 	 Accuracy: 0.49934810951760106
Delta: 0.0013035875086164009 	  Loss: 1.6485429110480692 	 Accuracy: 0.49934810951760106
Delta: 0.0034169039166404565 	  Loss: 1.6483297968675656 	 Accuracy: 0.500651890482399
Delta: 0.0023486922214963897 	  Loss: 1.648029489314221 	 Accuracy: 0.4980443285528031
Delta: 0.004093282729842019 	  Loss: 1.6490145309222815 	 Accuracy: 0.4980443285528031
Delta: 0.0030828825332772786 	  Loss: 1.6488247935178624 	 Accuracy: 0.49934810951760106
Delta: 0.002456531174915076 	  Loss: 1.6483966748569916 	 Accuracy: 0.49934810951760106
Delta: 1.0679563868027635e-05 	  Loss: 1.6483925969653477 	 Accuracy: 0.5019556714471969
Delta: 3.7692799775692766e-05 	  Loss: 1.6483233545285068 	 Accuracy: 0.5019556714471969
Delta: 0.020947350644948008 	  Loss: 2.175112172022735 	 Accuracy: 0.19165580182529335
Delta: 0.01878063249214929 	  Loss: 2.0615733999976893 	 Accuracy: 0.3650586701434159
Delta: 0.01803132889356938 	  Loss: 1.8707935164840674 	 Accuracy: 0.5332464146023468
Delta: 0.016545733010133967 	  Loss: 1.7267245862455056 	 Accuracy: 0.5123859191655802
Delta: 0.013246173245801766 	  Loss: 1.6735597330699845 	 Accuracy: 0.5176010430247718

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.011304516150701457 	  Loss: 1.6597309062507593 	 Accuracy: 0.5032594524119948
Delta: 0.008407904680951669 	  Loss: 1.6551897949919803 	 Accuracy: 0.5045632333767927
Delta: 0.005320573827949609 	  Loss: 1.6544238260763686 	 Accuracy: 0.4980443285528031
Delta: 0.0040515251132920435 	  Loss: 1.6541218769467985 	 Accuracy: 0.5032594524119948
Delta: 0.0033717341739909817 	  Loss: 1.6541806748343675 	 Accuracy: 0.5032594524119948
Delta: 0.0038704014856199478 	  Loss: 1.6541828455603147 	 Accuracy: 0.5045632333767927
Delta: 0.0032225236781563142 	  Loss: 1.654013978138905 	 Accuracy: 0.5019556714471969
Delta: 0.0012691913624802407 	  Loss: 1.6538348029888854 	 Accuracy: 0.5058670143415906
Delta: 4.352510831637674e-05 	  Loss: 1.6537836305160338 	 Accuracy: 0.49934810951760106
Delta: 2.9845516617307103e-05 	  Loss: 1.653625965261495 	 Accuracy: 0.5045632333767927
Delta: 0.001325308195433357 	  Loss: 1.653949589777899 	 Accuracy: 0.49674054758800523
Delta: 0.004183840035226078 	  Loss: 1.6541799566967703 	 Accuracy: 0.49934810951760106
Delta: 0.002932856145424168 	  Loss: 1.654161315494449 	 Accuracy: 0.5058670143415906
Delta: 0.002464828023702592 	  Loss: 1.6537744244997068 	 Accuracy: 0.500651890482399
Delta: 0.001823365072881735 	  Loss: 1.6535398870333684 	 Accuracy: 0.4915254237288136
Delta: 0.006126255973321924 	  Loss: 1.6542873296056286 	 Accuracy: 0.5058670143415906
Delta: 0.0036555235311900914 	  Loss: 1.6539005936969122 	 Accuracy: 0.5058670143415906
Delta: 0.003898344694064204 	  Loss: 1.654057975801712 	 Accuracy: 0.5058670143415906
Delta: 0.002689263121725212 	  Loss: 1.653587964634689 	 Accuracy: 0.4954367666232073
Delta: 0.0025823044682022145 	  Loss: 1.6533061793495196 	 Accuracy: 0.4980443285528031
Delta: 0.002618751289872815 	  Loss: 1.654092948102006 	 Accuracy: 0.5019556714471969
Delta: 0.000977784951480594 	  Loss: 1.6534517179314394 	 Accuracy: 0.5045632333767927
Delta: 0.00307809115597825 	  Loss: 1.6533274681926704 	 Accuracy: 0.5019556714471969
Delta: 0.0030132307304381527 	  Loss: 1.652937794722197 	 Accuracy: 0.5058670143415906
Delta: 0.001448689280451496 	  Loss: 1.65271594262454 	 Accuracy: 0.5058670143415906
Delta: 0.005079045202441458 	  Loss: 1.6526912786179015 	 Accuracy: 0.5058670143415906
Delta: 0.005434637323524698 	  Loss: 1.6515383920279514 	 Accuracy: 0.5097783572359843
Delta: 0.003406158102473425 	  Loss: 1.6516500017736022 	 Accuracy: 0.5071707953063885
Delta: 0.004059851565991097 	  Loss: 1.6515447037683704 	 Accuracy: 0.5097783572359843
Delta: 0.0011429877561840568 	  Loss: 1.6514568209852747 	 Accuracy: 0.5123859191655802
Delta: 0.0020929614992210603 	  Loss: 1.6510231126712385 	 Accuracy: 0.5136897001303781
Delta: 0.0026316956509004714 	  Loss: 1.6510541135594856 	 Accuracy: 0.5084745762711864
Delta: 0.0018601849649900423 	  Loss: 1.650509719081379 	 Accuracy: 0.5084745762711864
Delta: 0.003835845942835863 	  Loss: 1.649258777137445 	 Accuracy: 0.5084745762711864
Delta: 0.0037758493269483724 	  Loss: 1.6490366301111172 	 Accuracy: 0.5097783572359843
Delta: 0.004132692503458063 	  Loss: 1.6491071701208595 	 Accuracy: 0.5097783572359843
Delta: 0.0014924012828894707 	  Loss: 1.6489690709421565 	 Accuracy: 0.5045632333767927
Delta: 0.00240250027344028 	  Loss: 1.649827813403999 	 Accuracy: 0.5084745762711864
Delta: 0.0035242680961361226 	  Loss: 1.6512307815455274 	 Accuracy: 0.5097783572359843
Delta: 0.0012440970559446222 	  Loss: 1.651271023883142 	 Accuracy: 0.5084745762711864
Delta: 8.40000902801174e-05 	  Loss: 1.6510300156050794 	 Accuracy: 0.5019556714471969
Delta: 0.0027581869172801725 	  Loss: 1.6510616222234802 	 Accuracy: 0.5149934810951761
Delta: 0.0025509286869022534 	  Loss: 1.6507731051081513 	 Accuracy: 0.4941329856584094
Delta: 0.0025539467205101993 	  Loss: 1.6505522695744232 	 Accuracy: 0.5097783572359843
Delta: 0.0035833597707041623 	  Loss: 1.6488965555609965 	 Accuracy: 0.5110821382007823
Delta: 0.0020455167296109956 	  Loss: 1.6493761939305127 	 Accuracy: 0.5110821382007823
Delta: 0.0035692803689374723 	  Loss: 1.6492468654523262 	 Accuracy: 0.5019556714471969
Delta: 0.0044940203041539594 	  Loss: 1.6484802433689254 	 Accuracy: 0.5071707953063885
Delta: 0.004379474178572399 	  Loss: 1.649283467738624 	 Accuracy: 0.5084745762711864
Delta: 0.005359994289421716 	  Loss: 1.6500222347075617 	 Accuracy: 0.5084745762711864
Delta: 0.003416778314210339 	  Loss: 1.6497868116556416 	 Accuracy: 0.5071707953063885
Delta: 0.004126215630727312 	  Loss: 1.649074634526626 	 Accuracy: 0.5123859191655802
Delta: 0.002620669299297232 	  Loss: 1.649772392774655 	 Accuracy: 0.5071707953063885
Delta: 0.00260245892269821 	  Loss: 1.6498251538373943 	 Accuracy: 0.5097783572359843
Delta: 0.0022369621871323217 	  Loss: 1.649657045291017 	 Accuracy: 0.5097783572359843
Delta: 0.0018445780833519893 	  Loss: 1.649646836897141 	 Accuracy: 0.5058670143415906
Delta: 0.001537768692857862 	  Loss: 1.649641041441553 	 Accuracy: 0.5058670143415906
Delta: 2.10011481007324e-05 	  Loss: 1.6496271988353837 	 Accuracy: 0.5045632333767927
Delta: 0.0025755040984828622 	  Loss: 1.649613971661781 	 Accuracy: 0.5045632333767927
Delta: 0.004016728574819705 	  Loss: 1.6501845274783573 	 Accuracy: 0.5045632333767927
Delta: 0.0010174482762504305 	  Loss: 1.6503242934634428 	 Accuracy: 0.5032594524119948
Delta: 0.004994087266709498 	  Loss: 1.6504628834711035 	 Accuracy: 0.5071707953063885
Delta: 0.0023348132596447834 	  Loss: 1.6509384960591469 	 Accuracy: 0.49934810951760106
Delta: 0.003947960408322635 	  Loss: 1.6519948308730035 	 Accuracy: 0.49934810951760106
Delta: 0.0038309237564076166 	  Loss: 1.650650518603304 	 Accuracy: 0.5032594524119948
Delta: 1.4293245567023466e-05 	  Loss: 1.6506374421296395 	 Accuracy: 0.5045632333767927
Delta: 0.0031119722959764783 	  Loss: 1.6507246553207997 	 Accuracy: 0.5032594524119948
Delta: 0.0031762962546144614 	  Loss: 1.6507907777430082 	 Accuracy: 0.5032594524119948
Delta: 2.9841484844419178e-05 	  Loss: 1.6508281603377393 	 Accuracy: 0.516297262059974
Delta: 0.0032704154368783504 	  Loss: 1.6499320538221824 	 Accuracy: 0.5045632333767927
Delta: 0.0026584522480382067 	  Loss: 1.6498925768241586 	 Accuracy: 0.5058670143415906
Delta: 0.002869949576608066 	  Loss: 1.6494876337631361 	 Accuracy: 0.5032594524119948
Delta: 0.00384573814381707 	  Loss: 1.6495037511995492 	 Accuracy: 0.5045632333767927
Delta: 0.0026282261109289128 	  Loss: 1.6491090214795294 	 Accuracy: 0.5058670143415906
Delta: 0.0019744192871324643 	  Loss: 1.6500678290149504 	 Accuracy: 0.5058670143415906
Delta: 0.0013350432198151985 	  Loss: 1.6500321304242884 	 Accuracy: 0.5058670143415906
Delta: 6.692802114401419e-05 	  Loss: 1.6502291069013475 	 Accuracy: 0.5058670143415906
Delta: 0.0035402498098321754 	  Loss: 1.6500637928287651 	 Accuracy: 0.5058670143415906
Delta: 0.00010668673166131738 	  Loss: 1.6499634061570985 	 Accuracy: 0.5071707953063885
Delta: 0.0005137786316759267 	  Loss: 1.6499572623665002 	 Accuracy: 0.5058670143415906
Delta: 4.069789016730201e-05 	  Loss: 1.6499315013537337 	 Accuracy: 0.5058670143415906
Delta: 3.1664687071187013e-05 	  Loss: 1.6499634372303995 	 Accuracy: 0.5058670143415906
Delta: 1.0938273326782515e-07 	  Loss: 1.6499632273039546 	 Accuracy: 0.5045632333767927
Delta: 0.0025200328053608958 	  Loss: 1.6497203156340952 	 Accuracy: 0.5058670143415906
Delta: 0.0025038240751855227 	  Loss: 1.649563922213802 	 Accuracy: 0.5045632333767927
Delta: 0.004817715864470555 	  Loss: 1.6504820685482047 	 Accuracy: 0.49934810951760106
Delta: 0.0070350422379079555 	  Loss: 1.6490244604306175 	 Accuracy: 0.5019556714471969
Delta: 0.004665585561003542 	  Loss: 1.6493702651299083 	 Accuracy: 0.5032594524119948
Delta: 0.004876274631739754 	  Loss: 1.6498987418794053 	 Accuracy: 0.5071707953063885
Delta: 0.0053523202784903755 	  Loss: 1.6482112781524414 	 Accuracy: 0.5032594524119948
Delta: 0.004356521785823794 	  Loss: 1.6497735885998588 	 Accuracy: 0.5032594524119948
Delta: 0.0030470858281668916 	  Loss: 1.6507950327218697 	 Accuracy: 0.5084745762711864
Delta: 0.0027773828965754095 	  Loss: 1.6495529198240653 	 Accuracy: 0.5032594524119948
Delta: 0.0018660020710882753 	  Loss: 1.6492670029470042 	 Accuracy: 0.5045632333767927
Delta: 0.0015822559916177116 	  Loss: 1.6498796639615674 	 Accuracy: 0.5058670143415906
Delta: 0.021075635013028227 	  Loss: 2.175166715685708 	 Accuracy: 0.17861799217731422
Delta: 0.0191337593378714 	  Loss: 2.054955167835576 	 Accuracy: 0.3455019556714472
Delta: 0.018780773473636877 	  Loss: 1.8261239917224044 	 Accuracy: 0.409387222946545
Delta: 0.016753653399886197 	  Loss: 1.6583229082916318 	 Accuracy: 0.3963494132985658
Delta: 0.011050110179977755 	  Loss: 1.6220445220958466 	 Accuracy: 0.39504563233376794

/home/vgares/mambaforge/envs/jdcoot/lib/python3.12/site-packages/ot/bregman/_sinkhorn.py:666: UserWarning: Sinkhorn did not converge. You might want to increase the number of iterations `numItermax` or the regularization parameter `reg`.
  warnings.warn(

Delta: 0.007877896168171906 	  Loss: 1.617434665995532 	 Accuracy: 0.3963494132985658
Delta: 0.006260142914317923 	  Loss: 1.6159225212093753 	 Accuracy: 0.3963494132985658
Delta: 0.00442915526269464 	  Loss: 1.6154784720566615 	 Accuracy: 0.3924380704041721
Delta: 0.003283067971059584 	  Loss: 1.6157770781232301 	 Accuracy: 0.39504563233376794
Delta: 0.0034389915369266036 	  Loss: 1.6158466804580471 	 Accuracy: 0.39374185136897
Delta: 0.0015444669274346863 	  Loss: 1.6158155611839304 	 Accuracy: 0.39374185136897
Delta: 0.003573855018048309 	  Loss: 1.616013966368004 	 Accuracy: 0.39374185136897
Delta: 0.0013560211520524592 	  Loss: 1.6160902259896348 	 Accuracy: 0.39374185136897
Delta: 3.3647097517548485e-05 	  Loss: 1.6160985956042886 	 Accuracy: 0.39374185136897
Delta: 0.001447026010975401 	  Loss: 1.6160922551538244 	 Accuracy: 0.39374185136897
Delta: 0.0013692448984229208 	  Loss: 1.6160770352260565 	 Accuracy: 0.39374185136897
Delta: 0.0007821985160665661 	  Loss: 1.615824119931121 	 Accuracy: 0.39374185136897
Delta: 0.001154558597504198 	  Loss: 1.615683680797316 	 Accuracy: 0.3924380704041721
Delta: 0.0022843763924365068 	  Loss: 1.6160648817184582 	 Accuracy: 0.39113428943937417
Delta: 0.0009460496276279012 	  Loss: 1.6160783710390147 	 Accuracy: 0.3924380704041721
Delta: 0.0012731100700221123 	  Loss: 1.6155877714147642 	 Accuracy: 0.39504563233376794
Delta: 0.0015203285393068737 	  Loss: 1.6158349557609313 	 Accuracy: 0.39504563233376794
Delta: 0.0032779827323161084 	  Loss: 1.6155545537082832 	 Accuracy: 0.38852672750977835
Delta: 0.004151372799899901 	  Loss: 1.6154795901942687 	 Accuracy: 0.3924380704041721
Delta: 0.003237377327259058 	  Loss: 1.61585227977662 	 Accuracy: 0.39374185136897
Delta: 0.003789728376204472 	  Loss: 1.6152250355540325 	 Accuracy: 0.39374185136897
Delta: 0.002062049934497197 	  Loss: 1.6155059695619896 	 Accuracy: 0.38722294654498046
Delta: 0.004772448445635345 	  Loss: 1.6158475848029576 	 Accuracy: 0.39374185136897
Delta: 2.9017954671942265e-05 	  Loss: 1.615833215944535 	 Accuracy: 0.39374185136897
Delta: 0.002553204089738935 	  Loss: 1.616395332418848 	 Accuracy: 0.39504563233376794
Delta: 0.002131241472046204 	  Loss: 1.6165393743001157 	 Accuracy: 0.3963494132985658
Delta: 0.003654061877139948 	  Loss: 1.6157889471685007 	 Accuracy: 0.39374185136897
Delta: 0.004563381702452988 	  Loss: 1.6160608010698403 	 Accuracy: 0.39113428943937417
Delta: 0.001526482529060132 	  Loss: 1.6165495855069603 	 Accuracy: 0.3924380704041721
Delta: 0.0013104884355408266 	  Loss: 1.6166071597848242 	 Accuracy: 0.39374185136897
Delta: 0.0037634866034630967 	  Loss: 1.6169743591998342 	 Accuracy: 0.3924380704041721
Delta: 0.001692185568257464 	  Loss: 1.6170613354340113 	 Accuracy: 0.3859191655801825
Delta: 0.0017514760055378391 	  Loss: 1.6169289836523353 	 Accuracy: 0.3924380704041721
Delta: 0.0013483408557353736 	  Loss: 1.6169607593188187 	 Accuracy: 0.39113428943937417
Delta: 0.0012008135583482468 	  Loss: 1.6166892210554904 	 Accuracy: 0.3898305084745763
Delta: 0.0017887551212797635 	  Loss: 1.6166206193887243 	 Accuracy: 0.39113428943937417
Delta: 0.002553397931143561 	  Loss: 1.6163212130202274 	 Accuracy: 0.39113428943937417
Delta: 0.0022032566943548265 	  Loss: 1.615535564499406 	 Accuracy: 0.39113428943937417
Delta: 0.002703219639241954 	  Loss: 1.615961089214557 	 Accuracy: 0.39113428943937417
Delta: 0.0006987228900468439 	  Loss: 1.615969844915309 	 Accuracy: 0.39374185136897
Delta: 0.0028388365552425507 	  Loss: 1.6166562606238262 	 Accuracy: 0.39113428943937417
Delta: 1.3096215001180087e-05 	  Loss: 1.6166578771846138 	 Accuracy: 0.3924380704041721
Delta: 0.0015911857971712263 	  Loss: 1.6162942513868694 	 Accuracy: 0.39113428943937417
Delta: 0.0013695131209772516 	  Loss: 1.6160838114355673 	 Accuracy: 0.39374185136897
Delta: 0.0008427419199357126 	  Loss: 1.6159527624008545 	 Accuracy: 0.39374185136897
Delta: 0.003180773098016994 	  Loss: 1.6155670062362288 	 Accuracy: 0.39765319426336376
Delta: 0.0038009054107671276 	  Loss: 1.615276968095515 	 Accuracy: 0.39765319426336376
Delta: 0.0005963998035339994 	  Loss: 1.6152345758812892 	 Accuracy: 0.39504563233376794
Delta: 0.002966656903102769 	  Loss: 1.6156625326485752 	 Accuracy: 0.3963494132985658
Delta: 0.002134632509889856 	  Loss: 1.6151686756972576 	 Accuracy: 0.3924380704041721
Delta: 0.00331845097579608 	  Loss: 1.616322764908332 	 Accuracy: 0.39765319426336376
Delta: 0.004252439750231704 	  Loss: 1.6155085000010732 	 Accuracy: 0.39504563233376794
Delta: 0.001790821837073999 	  Loss: 1.615544975344794 	 Accuracy: 0.3963494132985658
Delta: 0.002361656343161589 	  Loss: 1.6155606909430038 	 Accuracy: 0.3963494132985658
Delta: 0.0037439479227954395 	  Loss: 1.6150152577514085 	 Accuracy: 0.39504563233376794
Delta: 0.005837010471944722 	  Loss: 1.6149425698237458 	 Accuracy: 0.3963494132985658
Delta: 0.004528714982981762 	  Loss: 1.6149195300998498 	 Accuracy: 0.39895697522816165
Delta: 0.003299308647341855 	  Loss: 1.6147683640052939 	 Accuracy: 0.39504563233376794
Delta: 0.001473920171383889 	  Loss: 1.6145906878898613 	 Accuracy: 0.4002607561929596
Delta: 1.7304164077691272e-05 	  Loss: 1.6145290469009406 	 Accuracy: 0.4067796610169492
Delta: 0.0029735007849018154 	  Loss: 1.6143768051285745 	 Accuracy: 0.4002607561929596
Delta: 0.0014186050858358606 	  Loss: 1.6145222314902998 	 Accuracy: 0.39765319426336376
Delta: 0.0018835247154215973 	  Loss: 1.614575263578586 	 Accuracy: 0.4002607561929596
Delta: 0.0017527770923030218 	  Loss: 1.6148372626757337 	 Accuracy: 0.4002607561929596
Delta: 0.004808673608739768 	  Loss: 1.6161216451636125 	 Accuracy: 0.3963494132985658
Delta: 0.006993149460756537 	  Loss: 1.614006483871485 	 Accuracy: 0.39895697522816165
Delta: 0.002896518330905422 	  Loss: 1.6139409427175253 	 Accuracy: 0.39765319426336376
Delta: 0.003526708408360936 	  Loss: 1.6148607902853627 	 Accuracy: 0.39895697522816165
Delta: 0.0032715062618558894 	  Loss: 1.6143298068695249 	 Accuracy: 0.4002607561929596
Delta: 0.004193098206244215 	  Loss: 1.614830099989836 	 Accuracy: 0.4002607561929596
Delta: 0.0010945348158082056 	  Loss: 1.6149930659160778 	 Accuracy: 0.39895697522816165
Delta: 0.0023240278872046116 	  Loss: 1.6148458493631008 	 Accuracy: 0.39765319426336376
Delta: 0.0037459663151649916 	  Loss: 1.6148879235566673 	 Accuracy: 0.39895697522816165
Delta: 0.0031949905749331805 	  Loss: 1.6149210202800448 	 Accuracy: 0.39765319426336376
Delta: 0.00012032005844482256 	  Loss: 1.6149742888947278 	 Accuracy: 0.39895697522816165
Delta: 0.00013113460942641833 	  Loss: 1.615374665494521 	 Accuracy: 0.3963494132985658
Delta: 0.003889718613326309 	  Loss: 1.6171294365308162 	 Accuracy: 0.3963494132985658
Delta: 0.000763047085405758 	  Loss: 1.617659178871032 	 Accuracy: 0.39895697522816165
Delta: 0.002924433761355676 	  Loss: 1.6163218121701923 	 Accuracy: 0.39765319426336376
Delta: 0.004627943291153855 	  Loss: 1.6171094205182062 	 Accuracy: 0.39765319426336376
Delta: 0.0019466619947982973 	  Loss: 1.6167332926065896 	 Accuracy: 0.4002607561929596
Delta: 0.002124121464779488 	  Loss: 1.6162427770656709 	 Accuracy: 0.3963494132985658
Delta: 0.0027887267027660377 	  Loss: 1.618430231962133 	 Accuracy: 0.3963494132985658
Delta: 0.003289321420950673 	  Loss: 1.6177204435537944 	 Accuracy: 0.3963494132985658
Delta: 0.0030607155595966436 	  Loss: 1.6181293771468699 	 Accuracy: 0.39765319426336376
Delta: 0.0037412579055687077 	  Loss: 1.6172911200228839 	 Accuracy: 0.39504563233376794
Delta: 0.005782772582383219 	  Loss: 1.6185134642359364 	 Accuracy: 0.39374185136897
Delta: 0.003244895899495939 	  Loss: 1.6184055639683965 	 Accuracy: 0.39113428943937417
Delta: 0.005020151965375185 	  Loss: 1.6204333176833414 	 Accuracy: 0.3898305084745763
Delta: 0.0040303803340158185 	  Loss: 1.6186272109031616 	 Accuracy: 0.39765319426336376
Delta: 0.0017287193028805749 	  Loss: 1.6187852491672294 	 Accuracy: 0.39504563233376794
Delta: 0.003973363340785905 	  Loss: 1.6188485698087203 	 Accuracy: 0.39504563233376794
Delta: 0.005413811070006885 	  Loss: 1.6212668421174723 	 Accuracy: 0.3963494132985658
Delta: 0.005923322718359715 	  Loss: 1.623374270759133 	 Accuracy: 0.39765319426336376
Delta: 0.005508482622208883 	  Loss: 1.6178802074455008 	 Accuracy: 0.4002607561929596

  recoding      learning  alpha  alpha_mean
0   jdcoot  unsupervised    1.0         1.0
1   jdcoot  unsupervised    1.9         1.9

In [6]:
df_summary.to_excel("results_mean.xlsx", index=False)

In [8]:
df_results

   repetition recoding      learning  alpha
0           0   jdcoot  unsupervised    1.9
1           1   jdcoot  unsupervised    1.9
2           2   jdcoot  unsupervised    1.9
3           3   jdcoot  unsupervised    1.9
4           4   jdcoot  unsupervised    1.9
5           5   jdcoot  unsupervised    1.9
6           6   jdcoot  unsupervised    1.9
7           7   jdcoot  unsupervised    1.0
8           8   jdcoot  unsupervised    1.0
9           9   jdcoot  unsupervised    1.0